### ISSUE TITLE
使用本项目调用p-tuning方法训练后的ChatGLM模型不成功

### ISSUE THREAD

**Issue by tschen666** [chatchat-space/Langchain-Chatchat#1004]
**问题描述**
我使用ChatGLM2-6B官方提供的p-tuning v2方法微调训练了模型，当我直接使用ChatGLM官方的启动微调模型的方法来启动微调后的模型来启动微调后的模型是是可以正常运行的，但是当我采用本项目调用p-tuning却失败了，虽然在控制台里显示ptuning检查点加载成果但实际上没有效果（仿佛直接调用的原模型），即使我点选了重新加载模型也不行。

**复现问题的步骤**
1. 我按照要求首先在config文件里把 **USE_PTUNING_V2** 参数改为了 **True**，然后下面的 **PTUNING_DIR** 我首先尝试了保持为 **'./ptuning-v2'** 不动，也尝试过修改为绝对路径。
2. 然后我也按照了要求在 **ptuning-v2** 文件夹里放入了该文件夹中 readme.md 所要求的有关微调后模型的两个文件
3. 然后我启动了webui.py 目前一切正常，终端也显示加载ptuning检查点加载成功，当我点开gradio前端界面的 **模型配置** 页发现 **使用p-tuning微调后的模型** 这一个选项也自动打上了对勾。
4. 但当我向模型发出请求问他问题“你是谁”的时候却没有能够活得我期望的回答（我直接使用ChatGLM官方的启动微调模型的方法来启动微调后的模型时，当我问他“你是谁”，他将会回答：我是亚里士多德，一个出生于斯托亚的古希腊哲学家。但在此我问他“你是谁”，他却回复我“我是ChatGLM，一个人工智能助手”，这个回答与我没有点选使用p-tuning微调后的模型时所做出的回答一样，所以我怀疑微调后的模型没有被正确调用）
5. 我尝试点击gradio前端界面的 **模型配置** 页 中的 **重新加载本地模型** 按钮，通过终端给我返回的东西发现，模型的确被重新加载了，也再次显示了加载ptuning检查点加载成功，但当我问他“你是谁”时，依然不能给我期望的回答。

**预期的结果**
当我向模型发出请求时，我希望它能够像我采用ChatGLM官方的启动微调模型的方法来启动微调后的模型那样回复我。

**实际结果 / Actual Result**
仿佛直接加载了原模型，而不是加载了微调后模型

**环境信息 / Environment Information**
- langchain-ChatGLM 采用了8月5号的最新的仓库文件（即使是之前一些版本我测试过也是不能正确调用）
- 是否使用 Docker 部署： 否
- 使用的模型：ChatGLM2-6B
- 使用的 Embedding 模型：text2vec-large-chinese 
- 操作系统及版本 / linux-Ubuntu   阿里云机器学习平台PAI的DWS交互式开发实例 
- Python 版本 / Python version:
- 其他相关环境信息 

问题相关截图
<img width="1043" alt="屏幕截图 2023-08-05 120121" src="https://github.com/chatchat-space/langchain-ChatGLM/assets/137777758/41dc2810-fcd7-4d91-9b8f-5ec6e7d99ef6">
上图为终端返回的 **模型加载相关内容** 与 **ptuning检查点加载成功**

<img width="1221" alt="屏幕截图 2023-08-05 120756" src="https://github.com/chatchat-space/langchain-ChatGLM/assets/137777758/0645d9a2-f656-4758-a9d4-1439a28f4142">
上图为我直接使用ChatGLM官方的启动微调模型的方法来启动微调后的模型 ，我问模型“你是谁“时的表现

<img width="1224" alt="屏幕截图 2023-08-05 120100" src="https://github.com/chatchat-space/langchain-ChatGLM/assets/137777758/8d8164f1-0449-49b7-8119-281b0dfe06fe">
上图为我使用本项目启动微调模型的方法来启动微调后的模型 ，我问模型“你是谁“时的表现，其表现与直接加载原模型（微调前模型）一致，我怀疑其没有正确调用微调后模型

**Comment by xiongot** [comment]
现在config里直接没有peft相关参数了

**Comment by XiaoXiaoJiangYun** [comment]
没人回答吗？
