### ISSUE TITLE
怎么进行文档人工预处理使回答准确率提高？

### ISSUE THREAD

**Issue by xs1145** [chatchat-space/Langchain-Chatchat#1008]
怎么样的文档内容回答的准确率更高，或者怎么样进行文档人工预处理？

**Comment by ZhangjiayiCYOU** [comment]
分段之后使用LLM打标签会有效果一点吗？类似SEO

**Comment by danny-zhu** [comment]
自定义的知识库文档，我测试了多种格式后发现，使用一行提问，一行回答，最好回答里面把问题的主语要包含进去，也就是回答本身去掉提问后仍然是一个完整的知识点。这样的格式回答问题的效果会更好。
比如：
```
问题：小麦常见的草害包含什么？
回答：小麦常见的草害包含冬葵,大车前,广布野豌豆,狼把草,三齿萼野豌豆,鼠曲草,山野豌豆,一年生杂草。
```

**Comment by xs1145** [comment]
> 自定义的知识库文档，我测试了多种格式后发现，使用一行提问，一行回答，最好回答里面把问题的主语要包含进去，也就是回答本身去掉提问后仍然是一个完整的知识点。这样的格式回答问题的效果会更好。 比如：
> 
> ```
> 问题：小麦常见的草害包含什么？
> 回答：小麦常见的草害包含冬葵,大车前,广布野豌豆,狼把草,三齿萼野豌豆,鼠曲草,山野豌豆,一年生杂草。
> ```

好的  谢谢，我试试

**Comment by cristianohello** [comment]
@danny-zhu 
这不就是FAQ了吗？不如直接走向量匹配模型吧？

**Comment by Mingxiangyu** [comment]
> 

然后后面加上个llm做个总结就行了，完全忽略lang-chain

**Comment by aleimu** [comment]
+1

**Comment by roki1031** [comment]
> 自定义的知识库文档，我测试了多种格式后发现，使用一行提问，一行回答，最好回答里面把问题的主语要包含进去，也就是回答本身去掉提问后仍然是一个完整的知识点。这样的格式回答问题的效果会更好。 比如：
> 
> ```
> 问题：小麦常见的草害包含什么？
> 回答：小麦常见的草害包含冬葵,大车前,广布野豌豆,狼把草,三齿萼野豌豆,鼠曲草,山野豌豆,一年生杂草。
> ```

可是这样为什么要用LLM呢，前面准备这些FAQ都需要很多时间

**Comment by Mingxiangyu** [comment]
> > 自定义的知识库文档，我测试了多种格式后发现，使用一行提问，一行回答，最好回答里面把问题的主语要包含进去，也就是回答本身去掉提问后仍然是一个完整的知识点。这样的格式回答问题的效果会更好。 比如：
> > ```
> > 问题：小麦常见的草害包含什么？
> > 回答：小麦常见的草害包含冬葵,大车前,广布野豌豆,狼把草,三齿萼野豌豆,鼠曲草,山野豌豆,一年生杂草。
> > ```
> 
> 可是这样为什么要用LLM呢，前面准备这些FAQ都需要很多时间

llm做个总结，对于匹配到的答案做个润色这种

**Comment by brealisty** [comment]
> 自定义的知识库文档，我测试了多种格式后发现，使用一行提问，一行回答，最好回答里面把问题的主语要包含进去，也就是回答本身去掉提问后仍然是一个完整的知识点。这样的格式回答问题的效果会更好。 比如：
> 
> ```
> 问题：小麦常见的草害包含什么？
> 回答：小麦常见的草害包含冬葵,大车前,广布野豌豆,狼把草,三齿萼野豌豆,鼠曲草,山野豌豆,一年生杂草。
> ```

这么做了，又该如何保持文档原样呢？

**Comment by zRzRzRzRzRzRzR** [comment]
建议搭配自定义分词器使用，最新代码中已经支持了自定义的分词器
