### ISSUE TITLE
[BUG] 上传知识库文件直接显示error

### ISSUE THREAD

**Issue by Cloudylake** [chatchat-space/Langchain-Chatchat#1010]
上传知识库文件直接显示error
使用的是autodl的镜像文件v3，成功打开webui后准备上传本地知识库，在点击文件上传后，显示加载结束之后便显示error，终端显示Error in faiss::FileIOReader::FileIOReader(const char*) at /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open /root/langchain-ChatGLM/vector_store/index.faiss for reading: No such file or directory
在vector_store里确实没有发现index.faiss文件
在尝试更换镜像，服务器后均未解决问题。
望解答，非常感谢！

**Comment by hvne4j** [comment]
同问

**Comment by danny-zhu** [comment]
index.faiss的路径不对，正常情况下向量库文件放在 langchain-ChatGLM/knowledge_base/xxxx知识库id/vector_store/index.faiss里面。有没有其他报错信息？

**Comment by sherwinNG** [comment]
设置文件修改为 md文档，就可以使用了

**Comment by hvne4j** [comment]
> 同问

知识库名不用中文就好了

**Comment by Cloudylake** [comment]
我之前通过在github文件里一个一个翻找找到了index.faiss文件下载装载进了vector_store文件夹里，就解决了这个问题，和md文档，名称是否为中文都没关系。不过好像作者刚刚大更新了，我还没试，应该是解决了这个问题。
