### ISSUE TITLE
[BUG] 无法手动设置模型路径，unrecognized arguments: --model-dir /root/model/

### ISSUE THREAD

**Issue by kavin2003** [chatchat-space/Langchain-Chatchat#1014]
使用python webui.py --model-dir /root/model/ --model chatglm-6b --no-remote-model运行，提示
usage: langchain-ChatGLM [-h] [--no-remote-model] [--model-name MODEL_NAME] [--use-lora USE_LORA] [--lora LORA] [--lora-dir LORA_DIR] [--use-ptuning-v2 USE_PTUNING_V2]
                         [--ptuning-dir PTUNING_DIR] [--load-in-8bit] [--bf16]
langchain-ChatGLM: error: unrecognized arguments: --model-dir /root/model/

我看文档里面还是有这个参数的，但是args.py中已经移除了这个参数，望及时更新文档，删除此参数后，我该如何使指定本地路径呢?

**Comment by sonicno1** [comment]
一样，旧版本把支持，新版本不行，直接报错2023-08-13 19:54:30 | INFO | model_worker | Loading the model ['chatglm2-6b-int4'] on worker 2ca1f8d8 ...

**Comment by jhw0510** [comment]
插眼

**Comment by hzg0601** [comment]
新版本不再支持在webui.py启动模型，需要在启动LLM服务中选择
