### ISSUE TITLE
[BUG] MAC只能使用chatglm-cpp吗，使用 chatglm2-6b-int4 时会报错

### ISSUE THREAD

**Issue by Merenguelkl** [chatchat-space/Langchain-Chatchat#1015]
**问题描述 / Problem Description**
m1 pro使用chatglm2-6b-int4模型时会报错

AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'
Traceback (most recent call last):
  File "cli_demo.py", line 88, in <module>
    main()
  File "cli_demo.py", line 70, in main
    enumerate(resp["source_documents"])]

**Comment by Merenguelkl** [comment]
模型加载到CPU可以解决，但这样也太慢了

量化版本不能再MPS上跑嘛

**Comment by liuhrme** [comment]
chatglm.cpp可以量化跑MPS，可以试试。
