### ISSUE TITLE
如何控制生成答案文本的长度？

### ISSUE THREAD

**Issue by soultrans** [chatchat-space/Langchain-Chatchat#1019]
请问，怎么控制生成的文本长度呢？我尝试对configs里的PROMPT_TEMPLATE增加提示信息，但是没有起任何作用，有没有大佬指导下如何控制生成文本的长度？

我目前使用的提示Prompt
`PROMPT_TEMPLATE = """{context}\n\n请根据上述一个或者多个已知信息与以下要求回答问题：\n1.多个已知信息中，存在与问题不相关的已知信息，请不要根据与问题无关的已知信息回答\n2.如果单独的已知信息中存在与问题高度相关的表述，优先根据该已知信息回答\n3.答案要简洁和专业\n4.答案要控制在100字以内\n5.答案请使用中文\n5.如果从提供的已知信息中，都无法得到答案，只能回答 “根据已知信息无法回答该问题”\n问题：{question}"""`

**Comment by lizhuang** [comment]
+1

**Comment by FavoriteStar** [comment]
个人感觉模型的理解能力还是挺有限的，有些prompt的指令很难理解到位，所以你告诉它指定数目感觉也很难成功
