### ISSUE TITLE
知识库不能上传文档

### ISSUE THREAD

**Issue by geraldjin** [chatchat-space/Langchain-Chatchat#1020]
**问题描述 / Problem Description**
知识库上传docx文档，大小11.5kb，显示一直processing没有反应，好几个小时后还在processing。启动没有报错，上传文档后后台也无反馈
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/12570106/e86de60e-bdfb-4438-b130-26bbfb148b91)
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/12570106/e4a10bab-e7a2-4ede-a9be-69d68837f32c)

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型：ChatGLM2-6B-int4 
- 使用的 Embedding 模型：ext2vec-large-chinese 
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version: 3.9
- 其他相关环境信息 / Other relevant environment information: cuda 12.2 显存6G

**Comment by geraldjin** [comment]
我在另一台纯cpu服务器上docker部署后可以上传文档成功，但推理太慢，我尝试将该cpu服务器上传生成的vector_store拷贝到这台上传不成功的机器上来，这样是否有问题？我试了下回答完全没有按照文档内容来。。

**Comment by geraldjin** [comment]
我在另一台纯cpu服务器上docker部署后可以上传文档成功，但推理太慢，我尝试将该cpu服务器上传生成的vector_store拷贝到这台上传不成功的机器上来，这样是否有问题？我试了下回答完全没有按照文档内容来。。

**Comment by raphaelcheung** [comment]
我这里初始化知识库好慢啊，一个14k的txt文档都搞了一个小时还没初始化完成
这一步貌似没有用到GPU，CPU占用也一直30%左右

**Comment by raphaelcheung** [comment]
> 

照这速度也没法用知识库啊，现在随便一个文旦几百K至少，那初始化一次都要跑一个礼拜+了

**Comment by zicheqingluo** [comment]
我新建知识库，上传文件就报连不上api可telnet是正常的
