### ISSUE TITLE
[BUG] 调用langchain ConversationSummaryBufferMemory

### ISSUE THREAD

**Issue by GXKIM** [chatchat-space/Langchain-Chatchat#1021]
def init_model():
    args = parser.parse_args()

    args_dict = vars(args)
    shared.loaderCheckPoint = LoaderCheckPoint(args_dict)
    llm_model_ins = shared.loaderLLM()
    memory = ConversationSummaryBufferMemory(llm=llm_model_ins, max_token_limit=100)

报错原因：pydantic.error_wrappers.ValidationError: 1 validation error for ConversationSummaryBufferMemory
llm
  Can't instantiate abstract class BaseLanguageModel with abstract methods agenerate_prompt, apredict, apredict_messages, generate_prompt, invoke, predict, predict_messages (type=type_error)

**Comment by ZHANGJUN-OK** [comment]
你好，请问你解决了么？我也遇到了同样的问题。

**Comment by GXKIM** [comment]
> 你好，请问你解决了么？我也遇到了同样的问题。

已解决
