### ISSUE TITLE
能不能只搜索知识库内容，如果没有匹配到，就回答「根据已经知识，无法回答」

### ISSUE THREAD

**Issue by leehoisleeho** [chatchat-space/Langchain-Chatchat#1030]
因为要为企业做一个私有的知识库，他们的需求是只能根据他们提供的文档进行回答。

**Comment by Mingxiangyu** [comment]
可以，添加一段代码就行，看看webui.py的知识库测试部分，逻辑就是如果向量检索没有检索到内容，则直接返回，不去调用llm生成回答，但是有一个问题，很难检索到内容

**Comment by xs1145** [comment]
可以，在local_doc_qa的get_knowledge_based_answer修改下就行

**Comment by leehoisleeho** [comment]
居然有人回答 .. 谢谢

**Comment by Mingxiangyu** [comment]
> 居然有人回答 .. 谢谢

hhh同性交友呗
