### ISSUE TITLE
vue对话和Gradio对话结果不一致，

### ISSUE THREAD

**Issue by liangyuan1** [chatchat-space/Langchain-Chatchat#1035]
1、采用api.py启动后启动vue项目进行对话与web_ui对话使用同一个本地知识库但是结果不一致
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/25976027/4dd5be89-a4d7-4fe2-ace1-0cac077e6bb4)
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/25976027/cb2d4813-117a-4fc4-881d-c5580c0995a2)
2、vue对话框回答问题的速度比web-ui的速度慢很多
3、vue对话框回答问题不会逐步展示文字

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
