### ISSUE TITLE
[BUG] 关于解决知识库里没有的问题也会回答的可能办法

### ISSUE THREAD

**Issue by xiximustpig** [chatchat-space/Langchain-Chatchat#1049]
看了一下chains文件夹中local_doc_qa.py里面对于回复功能定义的函数：
    def get_knowledge_based_answer(self, query, vs_path, chat_history=[], streaming: bool = STREAMING):
        vector_store = load_vector_store(vs_path, self.embeddings)
        vector_store.chunk_size = self.chunk_size
        vector_store.chunk_conent = self.chunk_conent
        vector_store.score_threshold = self.score_threshold
        related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
        torch_gc()
        if len(related_docs_with_score) > 0:
            prompt = generate_prompt(related_docs_with_score, query)
        else:
            prompt = query
发现如果没有从数据库中获取到相关的信息，直接给prompt赋值给query，但是query不是用户直接提的问题吗，没有用上model_config.py文件中的PROMPT_TEMPLATE，因此或许可以考虑将prompt = query修改为添加了PROMPT_TEMPLATE的prompt，或许可以解决模型胡乱回答的问题

**Comment by Peri-albert** [comment]
感兴趣这个话题，但没能理解您的意思，可否举例描述

**Comment by Peri-albert** [comment]
我明白您做的事情，我只是好奇您做的这件事情的效果提升是怎样的，因为不明确prompt_template会在询问llm时候带来多大的效果提升，您可否简单说明一下这么做的原因并举一个使用和不使用prompt_template询问llm给出的答案的不同呢？

**Comment by xiximustpig** [comment]
> 

如果直接使用prompt = query相当于没有告诉模型“在没有知识库信息的情况下请回答不知道”这个信息，因此需要把这部分信息补充进去，我在使用和不使用prompt_template情况下又测试了几个问题，目前模型已经学会回答“抱歉，我无法提供相关信息。我是一个LLM_MODEL，无法访问知识库之外的信息。”此类信息，不过似乎还是会有胡乱回答的情况出现，提升效果不明显

**Comment by winie-hy** [comment]
确实值得探讨，如何避免他回答多余的东西，有更新狠踢我，手动狗头

**Comment by thugbobby** [comment]
> local_doc_qa.py

请问一下为啥没找到你说的这个文件
