### ISSUE TITLE
[BUG] macos上faiss向量数据库知识库问答开始问立即core

### ISSUE THREAD

**Issue by imarkzzz** [chatchat-space/Langchain-Chatchat#1058]
**问题描述 / Problem Description**
macos上faiss向量数据库知识库问答开始问立即core，导致无法问答。

出错报文如下
```
loader.py[line:64] - INFO: Loading faiss.
loader.py[line:66] - INFO: Successfully loaded faiss.
Batches: 100%|█████████████████████████████████████████| 1/1 [00:00<00:00, 16.82it/s]
zsh: segmentation fault  python server/api.py
/anaconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

**复现问题的步骤 / Steps to Reproduce**
1. 按文档启动服务，选择【对话模式】为【知识库问答】
2. 输入问题”prompt是什么“

**预期的结果 / Expected Result**
关于prompt的回答

**实际结果 / Actual Result**
server/api.py服务core掉，导致页面报” RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)“

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：1b07648238b714a68d01c11ecdea283f73e02461
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：m3e-base
- 操作系统及版本 / Operating system and version:MacOs 13.5
- Python 版本 / Python version:Python 3.11.4 (main, Jul  5 2023, 08:54:11) [Clang 14.0.6 ] on darwin
- 其他相关环境信息 / Other relevant environment information:
- 向量数据库faiss配置如下
kbs_config = {
    "faiss": {
    },
}

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imarkzzz** [comment]
将faiss_kb_service.py中的`normalize_L2=True`全部改成`normalize_L2=False`能跑过，但是原因未知

**Comment by etveritas** [comment]
我也遇到这个问题了。设置`normalize_L2=False`后可以跑通，但是知识库回答匹配不出来答案了...

**Comment by imarkzzz** [comment]
来信已收到

**Comment by imClumsyPanda** [comment]
请问升级0.2.x版本后是否有重建虚拟环境，并安装全部依赖包？

如果设置修改为 normalize_L2=False，需要将 model_config.py 中 SCORE_THRESHOLD 修改为0-1100范围内的数值。normalize_L2=True 时，该范围对应从 0-1 。

**Comment by gyangyun** [comment]
> 请问升级0.2.x版本后是否有重建虚拟环境，并安装全部依赖包？
> 
> 如果设置修改为 normalize_L2=False，需要将 model_config.py 中 SCORE_THRESHOLD 修改为0-1100范围内的数值。normalize_L2=True 时，该范围对应从 0-1 。

操作起来，发现要改的还有点多：
1. model_config.py 中 SCORE_THRESHOLD 修改为0-1100范围内的数值，按照上一个版本langchain-chatglm版本推荐的配置应该是500
2. server/chat/knowledge_base_chat.py里knowledge_base_chat的入参score_threshold要调整到0-1100
3. server/knowledge_base/kb_service/faiss_kb_service.py的所有normalize_L2=True换成normalize_L2=False
4. webui_pages/dialogue/dialogue.py中dialogue_page方法里调整为score_threshold = st.number_input("知识匹配分数阈值：", 0.0, 1100.0, float(SCORE_THRESHOLD), 100.0)
因为我是调openai的api，向量化用的cpu，不知道是不是因为cpu的原因导致normalize_L2=True的时候内存泄露了。

**Comment by wuyifan18** [comment]
我也遇到了相同的问题，normalize_L2改成False后可以跑通。但问题原因是什么呢？

**Comment by imarkzzz** [comment]
来信已收到

**Comment by imClumsyPanda** [comment]
> 我也遇到了相同的问题，normalize_L2改成False后可以跑通。但问题原因是什么呢？

一般可能是langchain和faiss版本问题

**Comment by zyhui98** [comment]
L2归一化就是对向量的每一个值都除以向量的平方和的开方，可能导致内存错误[faiss工具使用
](https://blog.csdn.net/dreamfantacy/article/details/102723808)

**Comment by ocpinfo** [comment]
> SCORE_THRESHOLD

我也遇到同样问题，normalize_L2改成False后知识库匹配不出来了

**Comment by imarkzzz** [comment]
来信已收到

**Comment by ocpinfo** [comment]
> > SCORE_THRESHOLD
> 
> 我也遇到同样问题，normalize_L2改成False后知识库匹配不出来了



> > 请问升级0.2.x版本后是否有重建虚拟环境，并安装全部依赖包？
> > 如果设置修改为 normalize_L2=False，需要将 model_config.py 中 SCORE_THRESHOLD 修改为0-1100范围内的数值。normalize_L2=True 时，该范围对应从 0-1 。
> 
> 操作起来，发现要改的还有点多：
> 
> 1. model_config.py 中 SCORE_THRESHOLD 修改为0-1100范围内的数值，按照上一个版本langchain-chatglm版本推荐的配置应该是500
> 2. server/chat/knowledge_base_chat.py里knowledge_base_chat的入参score_threshold要调整到0-1100
> 3. server/knowledge_base/kb_service/faiss_kb_service.py的所有normalize_L2=True换成normalize_L2=False
> 4. webui_pages/dialogue/dialogue.py中dialogue_page方法里调整为score_threshold = st.number_input("知识匹配分数阈值：", 0.0, 1100.0, float(SCORE_THRESHOLD), 100.0)
>    因为我是调openai的api，向量化用的cpu，不知道是不是因为cpu的原因导致normalize_L2=True的时候内存泄露了。

按照这个方法暂时解决了，知识库不能匹配出结果的问题。期待项目进一步完善，可以在M1 Mac上顺利运行
