### ISSUE TITLE
如何输出*匹配文本*和*添加上下文和问题*的prompt

### ISSUE THREAD

**Issue by xiaohangguo** [chatchat-space/Langchain-Chatchat#1060]
如何打印或者输出，这一步生成的prompt？
![d84a10b1d3fff880f249924a626d253](https://github.com/chatchat-space/Langchain-Chatchat/assets/72799392/ece2a3e5-898a-4d48-9580-215895924136)
或者在这里加一些后处理，比如把prompt对原文进行一些修改（替换词语或者句子）之类的

**Comment by duanhaowei** [comment]
感觉上下文这个涉及到提问的向量化解决方案吧？

**Comment by xiaohangguo** [comment]
> 感觉上下文这个涉及到提问的向量化解决方案吧？

目前是在用langchian直接做，其实就是想用知识库的向量或者向量片段还修改原文提示词

**Comment by duanhaowei** [comment]
> > 感觉上下文这个涉及到提问的向量化解决方案吧？
> 
> 目前是在用langchian直接做，其实就是想用知识库的向量或者向量片段还修改原文提示词

但是他不完整呀，我的意思是，拿去做向量的提问本身就缺少上下文，这个时候向量查询出来的结果并不准确。这该怎么做呢？

**Comment by xiaohangguo** [comment]
> > > 感觉上下文这个涉及到提问的向量化解决方案吧？
> > 
> > 
> > 目前是在用langchian直接做，其实就是想用知识库的向量或者向量片段还修改原文提示词
> 
> 但是他不完整呀，我的意思是，拿去做向量的提问本身就缺少上下文，这个时候向量查询出来的结果并不准确。这该怎么做呢？

好问题，我其实想做的不是上下文的交互，只是通过知识库里面的词来替换或者修改原prompt。我不是很懂你的意思，查询向量数据库可以通过n-gram匹配吧，或者计算相似度然后再排序，上下文其实不是很重要吧，不懂。

**Comment by duanhaowei** [comment]
> > > > 感觉上下文这个涉及到提问的向量化解决方案吧？
> > > 
> > > 
> > > 目前是在用langchian直接做，其实就是想用知识库的向量或者向量片段还修改原文提示词
> > 
> > 
> > 但是他不完整呀，我的意思是，拿去做向量的提问本身就缺少上下文，这个时候向量查询出来的结果并不准确。这该怎么做呢？
> 
> 好问题，我其实想做的不是上下文的交互，只是通过知识库里面的词来替换或者修改原prompt。我不是很懂你的意思，查询向量数据库可以通过n-gram匹配吧，或者计算相似度然后再排序，上下文其实不是很重要吧，不懂。

多轮对话就需要了，我卡这个问题蛮久了。
你那个问题，我记得上下文和知识库里的备选答案应该会随着history一起传给LLM的。怎么改prompt或许是代码层面处理下看看？

**Comment by xiaohangguo** [comment]
> > > > > 感觉上下文这个涉及到提问的向量化解决方案吧？
> > > > 
> > > > 
> > > > 目前是在用langchian直接做，其实就是想用知识库的向量或者向量片段还修改原文提示词
> > > 
> > > 
> > > 但是他不完整呀，我的意思是，拿去做向量的提问本身就缺少上下文，这个时候向量查询出来的结果并不准确。这该怎么做呢？
> > 
> > 
> > 好问题，我其实想做的不是上下文的交互，只是通过知识库里面的词来替换或者修改原prompt。我不是很懂你的意思，查询向量数据库可以通过n-gram匹配吧，或者计算相似度然后再排序，上下文其实不是很重要吧，不懂。
> 
> 多轮对话就需要了，我卡这个问题蛮久了。 你那个问题，我记得上下文和知识库里的备选答案应该会随着history一起传给LLM的。怎么改prompt或许是代码层面处理下看看？

是的，其实用langchain搞搞，本质就是处理字符串，只不过要取出来，然后写一写算法来替换。那你是不是可以用langchaincache之类的项目来写。

**Comment by jx1100370217** [comment]
问句的向量检索也应该先融合上下文，再去做向量检索，不然在多轮对话中返回的检索文档是风马牛不相及的。请问对于这个问题是否有好的解决方案呢？

**Comment by duanhaowei** [comment]
> 问句的向量检索也应该先融合上下文，再去做向量检索，不然在多轮对话中返回的检索文档是风马牛不相及的。请问对于这个问题是否有好的解决方案呢？

我到现在也没想到好的办法，向量融合上下文之后，如果历史记录里面有不同的话题，则也会融合进去。影响本次问题的向量准确度了。。。

**Comment by justforword** [comment]
> 问句的向量检索也应该先融合上下文，再去做向量检索，不然在多轮对话中返回的检索文档是风马牛不相及的。请问对于这个问题是否有好的解决方案呢？

请问，你说的问句向量检索，上下文是怎么融合的。我现在是一直记录历史的主语进行传递，和当前问句融合。但是有时候提取的主语，和融合的句子并没有达到预期
