### ISSUE TITLE
  self.milvus.col.drop() AttributeError: 'NoneType' object has no attribute 'drop'

### ISSUE THREAD

**Issue by anfernees-iphone** [chatchat-space/Langchain-Chatchat#1063]
knowledge_base/kb_service/milvus_kb_service.py", line 72, in do_clear_vs
    self.milvus.col.drop()
AttributeError: 'NoneType' object has no attribute 'drop'

执行 python init_database.py --recreate-vs 时报错

**Comment by GordenChoy** [comment]
遇到了一样的问题

**Comment by GordenChoy** [comment]
用的是milvus向量库

**Comment by weedon666** [comment]
milvus需要自己创建一个吗，有没有教程

**Comment by qiankunli** [comment]
我这边部署milvus 2.1.3 的发现一直无法正常work，所以部署了一个milvus 2.2.12，这个错误没管，貌似不影响正常用。

**Comment by zqt996** [comment]
关于环境向量库  有docker 文件 docs/docker
sdk  pymilvus 需要对应见 requirements.txt

**Comment by imClumsyPanda** [comment]
请更新至v0.2.2版本后检查是否仍存在该问题。
