### ISSUE TITLE
[BUG] 服务运行成功，对话出错，无返回 | WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.

### ISSUE THREAD

**Issue by sshallow** [chatchat-space/Langchain-Chatchat#1067]
**问题描述 / Problem Description**
对话无返回，报错，

**复现问题的步骤 / Steps to Reproduce**
##### 修改配置文件模型路径

LLM

```bash
pwd
/home/xxx/langchain-chatglm/modle/chatglm2-6b-int4

llm_model_dict = {
    "chatglm2-6b-int4": {
        "local_model_path": "/home/xxx/langchain-chatglm/modle/chatglm2-6b-int4",
        "api_base_url": "http://localhost:8888/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },
}
```

Embedding

```bash
pwd
/home/xxx/langchain-chatglm/modle/m3e-base
embedding_model_dict = {
    "m3e-base": "/home/xxx/langchain-chatglm/modle/m3e-base",
}
```

修改运行设备 cpu

```bash
# LLM 名称
LLM_MODEL = "chatglm2-6b-int4"

# LLM 运行设备
LLM_DEVICE = "cpu"

# 选用的 Embedding 名称
EMBEDDING_MODEL = "m3e-base"
# Embedding 模型运行设备
EMBEDDING_DEVICE = "cpu"
```

修改配置文件名称为 model_config.py

```bash
mv model_config.py.example model_config.py
```

###### **知识库初始化与迁移**

```bash
python init_database.py --recreate-vs
```

###### **启动 API 服务或 Web UI**

```bash
# 启动 LLM
python server/llm_api.py
# 启动 API
python server/api.py
# 启动 Web UI
streamlit run webui.py
```

三个服务的启动情况：
`python server/llm_api.py`
<img width="997" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/21257340/da309608-45da-4c85-935d-b93a809594d3">
`python server/api.py`
<img width="1245" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/21257340/91bbb5a2-2809-4432-b6d7-9bcefd161035">

`streamlit run webui.py`
<img width="987" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/21257340/66d8bb46-6745-4bff-9b82-b5d78fbcc856">

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21257340/0425f0fc-351c-4fc7-beda-229c8448bac2)

```
INFO:     127.0.0.1:33012 - "POST /chat/chat HTTP/1.1" 200 OK
2023-08-14 17:02:28,544 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-14 17:02:28,544 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-14 17:02:28,544 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：84e4981cc18c18bc1c6c008910f6b361453abacc
- 使用的模型：ChatGLM2-6B-int4 
- 使用的 Embedding 模型：m3e-base
- 操作系统及版本 / Operating system and version: centos 7
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: 无 gpu
 
**附加信息 / Additional Information**

**Comment by liunux4odoo** [comment]
先赞一个，非常规范的提问。
webui没有显示回答，说明api请求没有正常返回。能否更新代码到最新版，到http://127.0.0.1:786`/docs中，测试一下对应的接口?

**Comment by hzg0601** [comment]
+1，这个提问感受到了尊重，由 python server/api.py可以看出，llm_api.py似乎没有正确启动

**Comment by qihangf** [comment]
请问楼主问题解决了吗，我在更新了代码之后也遇到了这个问题

**Comment by JixiangZeng** [comment]
同样的问题，接口是有返回的，但是webui不显示回答

> 先赞一个，非常规范的提问。 webui没有显示回答，说明api请求没有正常返回。能否更新代码到最新版，到[http://127.0.0.1:7861/docs中，测试一下对应的接口](http://127.0.0.1:7861/docs%E4%B8%AD%EF%BC%8C%E6%B5%8B%E8%AF%95%E4%B8%80%E4%B8%8B%E5%AF%B9%E5%BA%94%E7%9A%84%E6%8E%A5%E5%8F%A3)?

**Comment by sducxh** [comment]
与楼主同样的现象，只在api服务里有这段异常信息：

INFO:     127.0.0.1:48108 - "POST /chat/chat HTTP/1.1" 200 OK
2023-08-16 10:31:49,389 - util.py[line:67] - INFO: message='OpenAI API response' path=http://localhost:8888/v1/chat/completions processing_ms=None request_id=None response_code=200
Caught exception: 'choices'

-----------------

**Comment by liunux4odoo** [comment]
> 

这看起来是llm_api没有正确返回，能否在http://localhost:8888/docs中测试一下/v1/chat/completions接口？

**Comment by sducxh** [comment]
> > 
> 
> 这看起来是llm_api没有正确返回，能否在[http://localhost:8888/docs中测试一下/v1/chat/completions接口？](http://localhost:8888/docs%E4%B8%AD%E6%B5%8B%E8%AF%95%E4%B8%80%E4%B8%8B/v1/chat/completions%E6%8E%A5%E5%8F%A3%EF%BC%9F)
我的环境是双卡，模型用的chatglm2-6b-32k
测了结果如下，先贴上来，我也找找原因
response：code 400
content：
{
  "object": "error",
  "message": "**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat))",
  "code": 50001
}

**Comment by liunux4odoo** [comment]
> > > 
> > 
> > 
> > 这看起来是llm_api没有正确返回，能否在[http://localhost:8888/docs中测试一下/v1/chat/completions接口？](http://localhost:8888/docs%E4%B8%AD%E6%B5%8B%E8%AF%95%E4%B8%80%E4%B8%8B/v1/chat/completions%E6%8E%A5%E5%8F%A3%EF%BC%9F)
> 
> 我的环境是双卡，模型用的chatglm2-6b-32k 测了结果如下，先贴上来，我也找找原因 response：code 400 content： { "object": "error", "message": "**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat))", "code": 50001 }

这个明显是fastchat多卡部署失败了，请参照最新文档修改多卡参数试试？

**Comment by sducxh** [comment]
> 


我是按照 `5.1.1 基于多进程脚本 llm_api.py 启动 LLM 服务` 启动的
在 llm_api.py 中修改 create_model_worker_app 函数中的三个参数
```
        gpus="0,1",
        num_gpus=2,
        max_gpu_memory="10GiB", # 控制每个卡使用的显存容量
```

启动服务并无异常
```SHELL
2023-08-16 11:16:55 | INFO | model_worker | Register to controller
2023-08-16 11:16:55 | INFO | controller | Register a new worker: http://127.0.0.1:20002
2023-08-16 11:16:55 | INFO | controller | Register done: http://127.0.0.1:20002, {'model_names': ['chatglm2-6b-32k'], 'speed': 1, 'queue_length': 0}
2023-08-16 11:16:55 | INFO | stdout | INFO:     127.0.0.1:44968 - "POST /register_worker HTTP/1.1" 200 OK
2023-08-16 11:16:55 | ERROR | stderr | INFO:     Started server process [28561]
2023-08-16 11:16:55 | ERROR | stderr | INFO:     Waiting for application startup.
2023-08-16 11:16:56 | ERROR | stderr | INFO:     Application startup complete.
2023-08-16 11:16:56 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20002 (Press CTRL+C to quit)
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8888 (Press CTRL+C to quit)



2023-08-16 11:17:41 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b-32k']. Semaphore: None. call_ct: 0. worker_id: 51dfb7da. 
2023-08-16 11:17:41 | INFO | controller | Receive heart beat. http://127.0.0.1:20002
2023-08-16 11:17:41 | INFO | stdout | INFO:     127.0.0.1:44980 - "POST /receive_heart_beat HTTP/1.1" 200 OK
INFO:     10.1.60.82:52249 - "GET /docs HTTP/1.1" 200 OK
INFO:     10.1.60.82:52249 - "GET /openapi.json HTTP/1.1" 200 OK
2023-08-16 11:18:17 | INFO | controller | names: ['http://127.0.0.1:20002'], queue_lens: [0.0], ret: http://127.0.0.1:20002
2023-08-16 11:18:17 | INFO | stdout | INFO:     127.0.0.1:44992 - "POST /get_worker_address HTTP/1.1" 200 OK
2023-08-16 11:18:17,786 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20001/get_worker_address "HTTP/1.1 200 OK"
INFO:     10.1.60.82:52250 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
2023-08-16 11:18:26 | INFO | model_worker | Send heart beat. Models: ['chatglm2-6b-32k']. Semaphore: None. call_ct: 0. worker_id: 51dfb7da. 
```

**Comment by love520222** [comment]
同样的问题，感觉llm_api.py没有启动本地模型

**Comment by sducxh** [comment]
8.17更：基本定位是fastchat双卡的问题，但没找到解决办法，今天换单卡运行没问题。

**Comment by zhaozhiming** [comment]
楼主是不是部署在autodl上面？如果是的话，autodl上的8888端口被jupyter服务占用了，要改下 `server/llm_api.py`里面这行代码：`openai_api_port = 8888`，同时将`configs/model_config.py`里面的llm_model的api_base_url端口也改成一样的，示例代码如下：

server/llm_api.py
```py
openai_api_port = 7777
```

configs/model_config.py
```py
llm_model_dict = {
    "chatglm2-6b": {
        "local_model_path": "/root/autodl-tmp/chatglm2-6b",
        "api_base_url": "http://localhost:7777/v1",  # "name"修改为fastchat服务中的"api_base_url"
        "api_key": "EMPTY"
    },
```

**Comment by xiyuanyuan0506** [comment]
> 在[http://localhost:8888/docs中测试一下/v1/chat/completions接口？](http://localhost:8888/docs%E4%B8%AD%E6%B5%8B%E8%AF%95%E4%B8%80%E4%B8%8B/v1/chat/completions%E6%8E%A5%E5%8F%A3%EF%BC%9F)

请问怎么测试接口的

**Comment by imClumsyPanda** [comment]
请问 fschat 的版本更新至 0.2.24 版本后是否仍存在该问题？

**Comment by sducxh** [comment]
> 请问 fschat 的版本更新至 0.2.24 版本后是否仍存在该问题？

试了升级fschat==0.2.24，也是一样的错误

**Comment by hongkong9771** [comment]
> 与楼主同样的现象，只在api服务里有这段异常信息：
> 
> INFO: 127.0.0.1:48108 - "POST /chat/chat HTTP/1.1" 200 OK 2023-08-16 10:31:49,389 - util.py[line:67] - INFO: message='OpenAI API response' path=http://localhost:8888/v1/chat/completions processing_ms=None request_id=None response_code=200 Caught exception: 'choices'

你好，请问这个问题是怎么解决的啊？

**Comment by bestkimpang** [comment]
我也遇到同样的问题。解决方法：不使用本地的chatglm2-6b模型路径，让程序自己下载一遍模型，再运行就好了。

**Comment by zhuhaifengaaa** [comment]
> 楼主是不是部署在autodl上面？如果是的话，autodl上的8888端口被jupyter服务占用了，要改下 `server/llm_api.py`里面这行代码：`openai_api_port = 8888`，同时将`configs/model_config.py`里面的llm_model的api_base_url端口也改成一样的，示例代码如下：
> 
> server/llm_api.py
> 
> ```python
> openai_api_port = 7777
> ```
> 
> configs/model_config.py
> 
> ```python
> llm_model_dict = {
>     "chatglm2-6b": {
>         "local_model_path": "/root/autodl-tmp/chatglm2-6b",
>         "api_base_url": "http://localhost:7777/v1",  # "name"修改为fastchat服务中的"api_base_url"
>         "api_key": "EMPTY"
>     },
> ```

试了一下，确实可行，想请教下，将api_base_url改为和openai_api_port 一样的7777，调用的还是本地模型吗

**Comment by zhuhaifengaaa** [comment]
> 楼主是不是部署在autodl上面？如果是的话，autodl上的8888端口被jupyter服务占用了，要改下 `server/llm_api.py`里面这行代码：`openai_api_port = 8888`，同时将`configs/model_config.py`里面的llm_model的api_base_url端口也改成一样的，示例代码如下：
> 
> server/llm_api.py
> 
> ```python
> openai_api_port = 7777
> ```
> 
> configs/model_config.py
> 
> ```python
> llm_model_dict = {
>     "chatglm2-6b": {
>         "local_model_path": "/root/autodl-tmp/chatglm2-6b",
>         "api_base_url": "http://localhost:7777/v1",  # "name"修改为fastchat服务中的"api_base_url"
>         "api_key": "EMPTY"
>     },
> ```


我将openai_api_port 改为了8888，可以正常对话了，但是linux窗口运行api.py显示如下如下内容，请问这个有什么要紧的吗？
`2023-09-14 09:59:17,084 - util.py[line:67] - INFO: message='OpenAI API response' path=http://localhost:8888/v1/chat/completions processing_ms=None request_id=None resp`
