### ISSUE TITLE
【本地知识库问答】如何使引用部分能够显示引用全文而非引用段落？

### ISSUE THREAD

**Issue by dkw-wkd** [chatchat-space/Langchain-Chatchat#1071]
本地知识库问答中，会输出引用的段落
![14f6d741f304debeb24d056345cc67f](https://github.com/chatchat-space/Langchain-Chatchat/assets/75665807/c5cb1cff-d824-4cba-b680-fbc46ce6a519)

修改该处CHUNK_SIZE后依旧只输出最长的段落
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/75665807/314f6d44-b3a1-4e40-aa7f-3d26cfcfd8f3)

在webui.py中有输出引用文章的部分，如何修改能够显示引用的全文 而非段落，同时如果引用了多篇文章 最终只输出一次该篇文章的全文？
![1691995307452](https://github.com/chatchat-space/Langchain-Chatchat/assets/75665807/af3177c4-0832-4a32-8c5a-56dc4a54efbd)

**Comment by liunux4odoo** [comment]
文档大小未知的情况下输出整个文档不是个好选择。最新代码，来源中会给出引用文档的超链接，点击即可下载文档全文。

**Comment by imClumsyPanda** [comment]
当前版本未集成上下文扩充功能，将在后续版本依托重构后的结构重新添加该功能。

**Comment by imClumsyPanda** [comment]
上下文扩充已添加至 https://github.com/chatchat-space/Langchain-Chatchat/issues/1088 故关闭本 issue，如需关注开发/上线进度请前往上述 issue 链接查看
