### ISSUE TITLE
[BUG] 错误操作之后一直Connection refused，且找不到进程

### ISSUE THREAD

**Issue by a656418zz** [chatchat-space/Langchain-Chatchat#1073]
启动webui操作失误，直接streamlit webui.py了，没有启动前面的api服务，所以就ctrl+C强行终止进程了
但是这时候就一直在命令行重复
channel 4: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 4: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 4: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 4: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 3: open failed: connect failed: Connection refused
channel 4: open failed: connect failed: Connection refused

重新操作打开各种api之后确实能进行对话了（知识库embedding不对应报bug了，但这应该不是主要问题）
但是关闭之后（ctrl+C）三个进程，最后再进行一遍$ python server/llm_api_shutdown.py --serve all 
报错：
For more details see kill(1).
Traceback (most recent call last):
  File "/data/llm/Langchain-Chatchat/server/llm_api_shutdown.py", line 27, in <module>
    subprocess.run(shell_script, shell=True, check=True)
  File "/home/appops/miniconda3/envs/llm_chatchat/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'ps -eo user,pid,cmd|grep fastchat.serve|grep -v grep|awk '{print $2}'|xargs kill -9' returned non-zero exit status 123.

看似无法清除，ps -ef | grep fast也没有相关进程，因为是服务器所以不方便重新启动，重连上去之后仍然弹出Connection refused，非常烦人

**Comment by imClumsyPanda** [comment]
请问llm_api和api是否都启动了呢？

**Comment by hzg0601** [comment]
python server/llm_api_shutdown.py --serve all只能停止LLM相关的三个服务，目前像停止其他服务，仍需手动停止
