### ISSUE TITLE
autodl镜像部署失败，webui.py启动不起来

### ISSUE THREAD

**Issue by Wimet7** [chatchat-space/Langchain-Chatchat#1078]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/99958566/a1ff4591-79d9-4771-9c26-42c2291a90b6)
无报错信息，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/99958566/af29c064-dd0c-47c9-9998-8f0d1d773f5e)
迟迟不出下面的日志

**Comment by exceedzhang** [comment]
我也试了一下，好些问题还挺多的！

**Comment by zhit-W** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/99958566/7be1af76-877a-40a4-bea2-be12f21c88a4)
按照此步骤做的

**Comment by Hzzhang-nlp** [comment]
> ![image](https://user-images.githubusercontent.com/99958566/260395444-7be1af76-877a-40a4-bea2-be12f21c88a4.png) 按照此步骤做的

是需要开三个终端呗？

**Comment by ymx10086** [comment]
我也开了三个终端，但是也迟迟不出日志

**Comment by Yoga49** [comment]
需要给自定义https服务配置cors以允许任意来源的访问
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS'
    response.headers['Access-Control-Allow-Headers'] = 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range'
    response.headers['Access-Control-Max-Age'] = '1728000'

**Comment by zhit-W** [comment]
> 需要给自定义http服务配置cors以允许任意来源的访问 response.headers['Access-Control-Allow-Origin'] = '*' response.headers['Access-Control-Allow-Methods'] = 'GET, POST, OPTIONS' response.headers['Access-Control-Allow-Headers'] = 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' response.headers['Access-Control-Max-Age'] = '1728000'

目前是可以通过更换autodl机器来解决这个问题，部分机器是使用http的，可以直接进去用，使用https的机器就没办法用。这个请问具体在哪配置？

**Comment by glide-the** [comment]
autodl部分服务器cdn有问题，尝试更换服务发布区域
