### ISSUE TITLE
通义千文Qwen-7b special token不适配导致回答胡言乱语和出现乱码

### ISSUE THREAD

**Issue by jackaihfia2334** [chatchat-space/Langchain-Chatchat#1080]
<img width="1920" alt="73A17308-D4AD-4396-B180-CFA206042BF1" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/52377418/c508e7da-a447-4dc0-a107-fe4ac0c59993">

![iQEcAqNwbmcDAQTNAd4FzKEG2gAjhAGkIQPTSAKqAKgt20yMLjZd4APPAAABifNxJlwEzgAUY44HAAgACgQ png_720x720q90](https://github.com/chatchat-space/Langchain-Chatchat/assets/52377418/502088e3-fdac-41f8-b2f7-4d01900dcfd5)

@imClumsyPanda
@cinience

**Comment by ljun0128** [comment]
请问同义千问怎么配置啊，我在配置文件加了路径报错了

**Comment by jackaihfia2334** [comment]
> 请问同义千问怎么配置啊，我在配置文件加了路径报错了

好歹给个完整报错信息吧，可以先在issue里查查有没有和你一样的

**Comment by ljun0128** [comment]
![1692091295085](https://github.com/chatchat-space/Langchain-Chatchat/assets/11641212/1435c812-7933-41e3-b9f9-160bc3f7f9dd)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11641212/56873773-243d-4365-b80f-699575407a3d)
这里配置的不对嘛

**Comment by jackaihfia2334** [comment]
这个问题之前有人提过你可以翻翻看。
我建议你重新从huggingface下一下通义千万的模型配置文件(模型不用重新下)，另外把transformers更新到4.31.0

**Comment by ljun0128** [comment]
好的，谢谢
&nbsp;


NINI
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mao ***@***.***&gt;; 
发送时间: 2023年8月15日(星期二) 下午5:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] 通义千文Qwen-7b special token不适配导致回答胡言乱语和出现乱码 (Issue #1080)





 
这个问题之前有人提过你可以翻翻看。
 我建议你重新从huggingface下一下通义千万的模型配置文件(模型不用重新下)，另外把transformers更新到4.31.0

**Comment by imClumsyPanda** [comment]
可以试一下把fachat升级到最新版本

**Comment by jackaihfia2334** [comment]
已解决，fschat=0.2.24
