### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by JoyceLiC** [chatchat-space/Langchain-Chatchat#1081]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
example  
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/51525240/154ad6e6-8151-41d9-bc3e-fbaf16c0e0d3)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
python server/api.py

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
openai request success

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
openai request error
The model `openai-chatgpt-3.5` does not exist

**Comment by JoyceLiC** [comment]
@imClumsyPanda

**Comment by imClumsyPanda** [comment]
已修改，感谢反馈🙏
