### ISSUE TITLE
0.2版本中CHUNK_SIZE改变后不生效

### ISSUE THREAD

**Issue by xiao1014** [chatchat-space/Langchain-Chatchat#1082]
改变model_config.py文件中CHUNK_SIZE的值，匹配结果文本长度没有变化。此参数在上个版本是有效的。

**Comment by imClumsyPanda** [comment]
经检查参数确实有传入textsplitter作为入参，但langchain中并未强制按照chunk_size截断，将在后续版本中对这一问题进行优化。

**Comment by zRzRzRzRzRzRzR** [comment]
该问题已经在最新代码中解决，请关注我们即将发布的新代码
