### ISSUE TITLE
0.2版本webui聊天无法输出内容

### ISSUE THREAD

**Issue by KkkyleZ** [chatchat-space/Langchain-Chatchat#1083]
![WechatIMG1894](https://github.com/chatchat-space/Langchain-Chatchat/assets/115196691/ff27e15b-a730-4665-9c29-dedc02c9c881)
控制台有报错
![WechatIMG163](https://github.com/chatchat-space/Langchain-Chatchat/assets/115196691/ef9e1807-c398-482c-a3cf-1a0f2ac6a2cb)

**Comment by liunux4odoo** [comment]
请确保按照readme启动了llm_api.py和api.py

**Comment by imClumsyPanda** [comment]
请问是否按照requirements.txt中依赖包及版本要求重新配置环境？

**Comment by YulinZhang255** [comment]
requirements_api和requirements_webui.txt都要install一下，我一开始没install就出现了同样问题

**Comment by imClumsyPanda** [comment]
安装requirements一个就行了 如果webui和api在两台机器上才需要分别安装这俩
