### ISSUE TITLE
[BUG] 0.2版本按向导，在根目录运行 llm_api.py 后无法启动，找不到'configs.model_config'包

### ISSUE THREAD

**Issue by guoqingkong** [chatchat-space/Langchain-Chatchat#1084]
**问题描述 / Problem Description**
在根目录运行 llm_api.py 后无法启动，找不到'configs.model_config'包 ，实际上configs目录下有model_config.py文件

`(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python3 --version
Python 3.10.12

(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python3 server/llm_api.py
Traceback (most recent call last):
  File "/home/kong/dev/langchain-ChatGLM/server/llm_api.py", line 6, in <module>
    from configs.model_config import llm_model_dict, LLM_MODEL, LLM_DEVICE, LOG_PATH, logger
ModuleNotFoundError: No module named 'configs.model_config'`

**复现问题的步骤 / Steps to Reproduce**
按步骤下载模型，git拉取项目文件，conda建立环境，修改配置文件model_config.py,初始化数据库。 1、2、3、4 一切正常。
第5步，根目录启动llm服务失败，应该是路径的问题，找不到原因。

**预期的结果 / Expected Result**
llm服务本应正常启动，然后并没有

**实际结果 / Actual Result**
尝试了，根目录再向上一级启动，以及进入server目录启动，都失败。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 操作系统及版本 / Operating system and version: UB22.04
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**Comment by liunux4odoo** [comment]
我这边最新代码启动正常。请确认configs目录下有两个文件：
- model_config.py.example。 这是项目自带的示例配置文件
- 基于example文件修改自己的model_config.py。

**Comment by imClumsyPanda** [comment]
<img width="894" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5668498/ddaa06a3-c10e-4d8c-b7c2-6ebc3117360f">
详见 https://github.com/chatchat-space/Langchain-Chatchat#3-设置配置项

**Comment by guoqingkong** [comment]
目录下当然有这些文件，环境我都检查过了


(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ tree configs
configs
├── __init__.py
├── model_config.py
├── model_config.py.example
└── __pycache__
    ├── __init__.cpython-310.pyc
    └── model_config.cpython-310.pyc

1 directory, 5 files
(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$

**Comment by guoqingkong** [comment]
更新了两次 api 还是启动不了， allinone 卡在一直waitworker

**Comment by guoqingkong** [comment]
git 更新后依然如此


`(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ tree configs
configs
├── __init__.py
├── model_config.py
├── model_config.py.example
└── __pycache__
    ├── __init__.cpython-310.pyc
    └── model_config.cpython-310.pyc

1 directory, 5 files
(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python server/llm_api.py
Traceback (most recent call last):
  File "/home/kong/dev/langchain-ChatGLM/server/llm_api.py", line 6, in <module>
    from configs.model_config import llm_model_dict, LLM_MODEL, LLM_DEVICE, LOG_PATH, logger
ModuleNotFoundError: No module named 'configs.model_config'
(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ 
(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ echo $PATH
/home/kong/.local/bin:/home/kong/anaconda3/envs/langchain/bin:/home/kong/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin`

**Comment by guoqingkong** [comment]
启动 webui -allinone 和  论坛一个人结果很像：



`
(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python webui_allinone.py 
Starting webui_allineone.py, it would take a while, please be patient....
wait controller running
controller running
********************************************************************************
 --host localhost  --port 20002  --model-path THUDM/chatglm2-6b  --revision main  --device cuda  --gpus 0  --num-gpus 1  --max-gpu-memory 20GiB  --gptq-wbits 16  --gptq-groupsize -1  --limit-worker-concurrency 5  --stream-interval 2  --worker-address http://localhost:20002 
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running`

**Comment by guoqingkong** [comment]
找到原因了  configs 这个目录命名和很多安装包源冲突了，改成configss 就可以启动了。**** @imClumsyPanda @hzg0601
