### ISSUE TITLE
[BUG] 上传、修改知识库报错

### ISSUE THREAD

**Issue by DemoQAQ** [chatchat-space/Langchain-Chatchat#1085]
搭建好默认环境后上传、修改知识库会报错，初始化运行python init_database.py --recreate-vs也同样报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46156826/f6fc344b-847e-4747-9d2b-16d56544f0c4)

**Comment by imClumsyPanda** [comment]
请看一下api端的日志，可以从启动api的控制台/命令行中查看
