### ISSUE TITLE
text_splitter现在支持了嘛

### ISSUE THREAD

**Issue by steph730** [chatchat-space/Langchain-Chatchat#1086]
text_splitter现在支持了吗，阿里的语义分割怎么用呢

**Comment by imClumsyPanda** [comment]
新版目前默认使用SpacyTextSplitter或RecursiveCharacterTextSplitter，将在后续版本中测试更合适的分词方案

**Comment by imClumsyPanda** [comment]
可选 TextSplitter 已添加至 https://github.com/chatchat-space/Langchain-Chatchat/issues/1088 故关闭本 issue，如需关注开发/上线进度请前往上述 issue 链接查看
