### ISSUE TITLE
[FEATURE] 0.2.0版本如何配置星火、文心这种模型？

### ISSUE THREAD

**Issue by physi-cs** [chatchat-space/Langchain-Chatchat#1089]
现在看起来全部收口到Fast-chat了，但是Fast-chat好像不支持配置远程模型

**Comment by ALLinLLM** [comment]
我自己实现了一个文心turbo api的类，实现了ai_say方法，然后在model_config里增加一行配置就行

**Comment by hzg0601** [comment]
Fast-chat原生支持配置远程模型
