### ISSUE TITLE
[BUG] 0.2.0的api接口的stream有问题，当为false的时候只返回最后一个字符，也搜索不了向量数据库

### ISSUE THREAD

**Issue by wp19991** [chatchat-space/Langchain-Chatchat#1090]
和知识库对话的api接口的stream有问题
当为false的时候也只返回最后一个字符，这个接口也搜索不了向量数据库
可能是异步操作的问题，导致这个拼接的操作失败，和stream为true的效果一样
https://github.com/chatchat-space/Langchain-Chatchat/blob/0568e9be474723795e3db1d0bc9816693d65471d/server/chat/knowledge_base_chat.py#L90

还有下面的搜索结果为空，知识库里面的原话也搜索不到
https://github.com/chatchat-space/Langchain-Chatchat/blob/0568e9be474723795e3db1d0bc9816693d65471d/server/chat/knowledge_base_chat.py#L56

**Comment by liunux4odoo** [comment]
感谢提出问题。

关于第1个问题，在commit 126bd51已经修复：
https://github.com/chatchat-space/Langchain-Chatchat/commit/126bd5123213492bc50d24b2d9ca3c679607b6e1#diff-be99ee19e1581b135518cec362c9ea94238d2b4a61c9fccb496bbc6121b8d505L81

关于第2个问题，请问是否重建了知识库？新版代码默认启用了normalize_L2，原来的知识库搜索不到结果。我们正在更新文档。

问题我先关闭，请拉取最新代码再测试一下，如果还有问题，请重开这个issue.
