### ISSUE TITLE
[BUG] 无法将文件添加至向量库

### ISSUE THREAD

**Issue by leexk312** [chatchat-space/Langchain-Chatchat#1091]
**问题描述 / Problem Description**
1.打开运行网页时 langchain的图标无法显示（对话正常）
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/64be5b2c-2e49-453c-bc8c-05e0bea89136)
2.将文件添加至向量库报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/fe0e11d6-6242-46b8-9f5c-975d4ee2a909)
3.接口信息报错显示如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/46f78ddd-8784-4ab3-9920-19baca38b97d)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/d609d24b-80be-4d12-8208-1b35deb2df17)
4.补充
txt文档可正常添加到向量库 但是doc，docx无法加入

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）： ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-base-chinese-paraphrase
- 操作系统及版本 / Operating system and version:win11
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by adminChina** [comment]
pdf 需要安装 poppler 
doc 好像要 libreoffice
如果PDF不完全是文字，还需要装tesseract

**Comment by yang384** [comment]
我连txt pdf doc 都无法添加至向量库

**Comment by adminChina** [comment]
> 我连txt pdf doc 都无法添加至向量库

什么版本的，0.2.1吗？
