### ISSUE TITLE
[BUG] 0.2.0版本 切换标签页后，“知识库问答”下拉菜单失效

### ISSUE THREAD

**Issue by ALLinLLM** [chatchat-space/Langchain-Chatchat#1092]
**问题描述 / Problem Description**
0.2.0版本 切换标签页后，“知识库问答”下拉菜单失效

**复现问题的步骤 / Steps to Reproduce**
1. 先在“对话”标签页，选择知识库问答，在右侧进行几轮对话
2. 然后选择“知识库管理”标签页
3. 然后回到“对话”标签页
4. 问题出现：“知识库问答”下拉菜单失效，回到了“LLM对话”模式。此时再进行对话，无法引用知识库内容

**预期的结果 / Expected Result**
标签页切换后，应当保留知识库问答模式

**实际结果 / Actual Result**
标签页切换后，退出了知识库问答模式

**环境信息 / Environment Information**
- https://github.com/chatchat-space/Langchain-Chatchat/commit/0568e9be474723795e3db1d0bc9816693d65471d
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：moka-ai/base
- 操作系统及版本 / Operating system and version: Ubuntu 20.04
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15920086/6caca61b-64a2-48bf-b084-8e9c3de66ebc)

**Comment by imClumsyPanda** [comment]
因为对话模式未存储在session_state中，所以每次页面切换后，需重新选择所需的对话模式。
