### ISSUE TITLE
基于OpenAI的GPT接口模型，启动api.py后，使用chat/chat接口时报连接错误

### ISSUE THREAD

**Issue by etveritas** [chatchat-space/Langchain-Chatchat#1096]
使用OpenAI的GPT接口模型，启动api.py后，使用chat/chat接口时报连接错误。错误如下：
<img width="982" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/27916175/55f4d3e7-a79c-43de-aeae-28d01a32e1f7">

**Comment by etveritas** [comment]
`bash /Applications/Python\ 3.10/Install\ Certificates.command `
通过运行上述命令解决了。

**Comment by haof-github** [comment]
你好，请问你是在Windows上运行的吗？ 这个Certificates.command 是个什么问题？ 我在Linux遇到了同样的问题。

**Comment by 1062141499** [comment]
这个具体怎么解决，麻烦大佬回复一下

**Comment by yinglou2012** [comment]
你好，请问你是在Windows上运行的吗？ 这个Certificates.command 是个什么问题？ 我在Linux遇到了同样的问题。
