### ISSUE TITLE
复制粘贴问题

### ISSUE THREAD

**Issue by Ericaerica0929** [chatchat-space/Langchain-Chatchat#1098]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
在webui界面的对话框输入对话内容的时候，不能从pycharm以外复制粘贴内容到对话框里，但是从pycharm自身的文字复制过来的内容就可以。这是为什么呢？

**Comment by hzg0601** [comment]
非项目问题
