### ISSUE TITLE
[FEATURE] 接口支持只调用知识库+Embedding模型，不必调用LLM

### ISSUE THREAD

**Issue by bieyehui** [chatchat-space/Langchain-Chatchat#1103]
**功能描述 / Feature Description**
接口支持只调用知识库+Embedding模型，不必调用LLM。

**解决的问题 / Problem Solved**
可以让接口返回相对确定性的回答。

**实现建议 / Implementation Suggestions**
只调用知识库+Embedding模型，屏蔽掉队LLM接口的调用。如果从知识库里面知道了相关内容和文档，则返回相关内容和文档，如果知识库里面没有找到相关内容和文档，则返回告知没有相关内容。

**Comment by syq23719034** [comment]
我也需要这个功能，之前想用flowise做的

**Comment by xjune123** [comment]
现在我也碰到这样问题，不在知识库的乱回答。在知识库的内容但是又增加了自己的思考，没办法原文输出。

**Comment by roki1031** [comment]
强烈建议

**Comment by liunux4odoo** [comment]
很好的建议，我们会尽快实现。

欢迎多试用反馈。

**Comment by liunux4odoo** [comment]
在[commit 67b8ebe](https://github.com/chatchat-space/Langchain-Chatchat/commit/67b8ebef522ac9952897800dda9b4d9a3e713bc7#diff-d8a9741c169ca9f7e5aa223ea65d0373a9862126a98ebb76dae6e51a631962ad)中增加了知识库检索API接口。

**Comment by aiainui** [comment]
好问题
