### ISSUE TITLE
离线环境运行python webui_allinone.py报错

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1104]
**问题描述 / Problem Description**
离线环境运行python webui_allinone.py报错。已经将model_config.py里的chatglm2-6b替换为本地绝对路径。

**复现问题的步骤 / Steps to Reproduce**
运行 python webui_allinone.py

**实际结果 / Actual Result**
Starting webui_allineone.py, it would take a while, please be patient....
wait controller running
controller running
********************************************************************************
 --device cuda  --gptq-groupsize -1  --gptq-wbits 16  --gpus 0  --limit-worker-concurrency 5  --max-gpu-memory 20GiB  --model-path THUDM/chatglm2-6b  --num-gpus 1  --revision main  --stream-interval 2  --worker-address http://localhost:20002  --host localhost  --port 20002 
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B /
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：m2e
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.8.13
- 其他相关环境信息 / Other relevant environment information:

**Comment by guoqingkong** [comment]
一样

**Comment by xiongot** [comment]
你有报错吗，还是一直显示wait controller running，我是一直显示

**Comment by roki1031** [comment]
一直显示wait



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yixuan Xie ***@***.***&gt;
发送时间: 2023年8月15日 19:08
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: roki1031 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [chatchat-space/Langchain-Chatchat] 离线环境运行python webui_allinone.py报错 (Issue #1104)





 
你有报错吗，还是一直显示wait controller running，我是一直显示

**Comment by guoqingkong** [comment]
我的：


(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python server/api_allinone.py
2023-08-15 19:31:28,411 - utils.py[line:145] - INFO: Note: detected 96 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2023-08-15 19:31:28,411 - utils.py[line:148] - INFO: Note: NumExpr detected 96 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-08-15 19:31:28,411 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
wait controller running
controller running
********************************************************************************
 --host localhost  --port 20002  --model-path THUDM/chatglm2-6b  --revision main  --device cuda  --gpus 0  --num-gpus 1  --max-gpu-memory 20GiB  --gptq-wbits 16  --gptq-groupsize -1  --limit-worker-concurrency 5  --stream-interval 2  --worker-address http://localhost:20002 
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
^CTraceback (most recent call last):
  File "/home/kong/dev/langchain-ChatGLM/server/api_allinone.py", line 44, in <module>
    launch_all(args=args,controller_args=controller_args,worker_args=worker_args,server_args=server_args)
  File "/home/kong/dev/langchain-ChatGLM/server/llm_api_launch.py", line 240, in launch_all
    launch_worker(args.model_path_address,args=args,worker_args=worker_args)
  File "/home/kong/dev/langchain-ChatGLM/server/llm_api_launch.py", line 225, in launch_worker
    subprocess.run(worker_check_sh, shell=True, check=True)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$

**Comment by guoqingkong** [comment]
webui allinone 是这样：



(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python webui_allinone.py --nohup
usage: webui_allinone.py [-h] [--model-path-address MODEL_PATH_ADDRESS [MODEL_PATH_ADDRESS ...]]
                         [--controller-host CONTROLLER_HOST] [--controller-port CONTROLLER_PORT]
                         [--dispatch-method {lottery,shortest_queue}] [--worker-host WORKER_HOST] [--worker-port WORKER_PORT]
                         [--model-path MODEL_PATH] [--revision REVISION] [--device {cpu,cuda,mps,xpu}] [--gpus GPUS]
                         [--num-gpus NUM_GPUS] [--max-gpu-memory MAX_GPU_MEMORY] [--load-8bit] [--cpu-offloading]
                         [--gptq-ckpt GPTQ_CKPT] [--gptq-wbits {2,3,4,8,16}] [--gptq-groupsize GPTQ_GROUPSIZE]
                         [--gptq-act-order] [--model-names MODEL_NAMES] [--limit-worker-concurrency LIMIT_WORKER_CONCURRENCY]
                         [--stream-interval STREAM_INTERVAL] [--no-register] [--server-host SERVER_HOST]
                         [--server-port SERVER_PORT] [--allow-credentials] [--api-keys API_KEYS]
webui_allinone.py: error: unrecognized arguments: --nohup
(langchain) kong@kong-Super-Server:~/dev/langchain-ChatGLM$ python webui_allinone.py 
Starting webui_allineone.py, it would take a while, please be patient....
wait controller running
controller running
********************************************************************************
 --host localhost  --port 20002  --model-path THUDM/chatglm2-6b  --revision main  --device cuda  --gpus 0  --num-gpus 1  --max-gpu-memory 20GiB  --gptq-wbits 16  --gptq-groupsize -1  --limit-worker-concurrency 5  --stream-interval 2  --worker-address http://localhost:20002 
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
^CTraceback (most recent call last):
  File "/home/kong/dev/langchain-ChatGLM/webui_allinone.py", line 70, in <module>
    launch_all(args=args,controller_args=controller_args,worker_args=worker_args,server_args=server_args)
  File "/home/kong/dev/langchain-ChatGLM/server/llm_api_launch.py", line 240, in launch_all
    launch_worker(args.model_path_address,args=args,worker_args=worker_args)
  File "/home/kong/dev/langchain-ChatGLM/server/llm_api_launch.py", line 225, in launch_worker
    subprocess.run(worker_check_sh, shell=True, check=True)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1146, in communicate
    self.wait()
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1209, in wait
    return self._wait(timeout=timeout)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1959, in _wait
    (pid, sts) = self._try_wait(0)
  File "/home/kong/anaconda3/envs/langchain/lib/python3.10/subprocess.py", line 1917, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

**Comment by zhuhaifengaaa** [comment]
我的也是一直等待：
“wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
.
.
.
”

**Comment by liunux4odoo** [comment]
model_worker因为要加载LLM，所以启动速度比较慢，请耐心等待。

如果超过10分钟还显示wait，可以分别在3个终端运行以下命令试试：
```shell
python server\llm_api.py
python server\api.py
python webui.py
```

**Comment by roki1031** [comment]
> model_worker因为要加载LLM，所以启动速度比较慢，请耐心等待。
> 
> 如果超过10分钟还显示wait，可以分别在3个终端运行以下命令试试：
> 
> ```shell
> python server\llm_api.py
> python server\api.py
> python webui.py
> ```

按照5.1、5.2、5.3依次执行是ok的。 

我查看输入的log文件里显示`OSError: We couldn't connect to 'https://huggingface.co'to load this file.....` 

<img width="681" alt="f5c485f98b1a8906231140bb39f4ada" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/52522880/a70c0a61-84fa-425a-87d2-0a37d425e89e">

我想可能是因为模型的配置没写好？ 

>

**Comment by zhaozhiming** [comment]
一直等待+1

**Comment by roki1031** [comment]
破案了，`把./Langchain-Chatchat/server/llm_api_launch.py`里面的
`# ------multi worker-----------------
parser.add_argument('--model-path-address',
                    default="THUDM/chatglm2@localhost@20002",
                    nargs="+",
                    type=str,
                    help="model path, host, and port, formatted as model-path@host@path")`
中default字段里面的THUDM/chatglm2替换为本地模型的绝对路径。 @ 后面的内容不变。

**Comment by hzg0601** [comment]
如果要加载非默认模型路径，需要命令行用--model-path-address指定

**Comment by zhaozhiming** [comment]
> 破案了，`把./Langchain-Chatchat/server/llm_api_launch.py`里面的 `# ------multi worker----------------- parser.add_argument('--model-path-address', default="THUDM/chatglm2@localhost@20002", nargs="+", type=str, help="model path, host, and port, formatted as model-path@host@path")` 中default字段里面的THUDM/chatglm2替换为本地模型的绝对路径。 @ 后面的内容不变。

为什么我改了还是一直waiting

**Comment by ValentinZhao** [comment]
@hzg0601 

改完了绝对路径还是一直等待，通义千问 Qwen-7B-Chat 模型。本地使用fastchat的model_worker可以启动，但是在这个项目里用 llm_api.py 启动就一直等待。

开始加载第0个模型:/root/**/**/Qwen-7B-Chat@localhost@20002
********************************************************************************
 --host localhost  --port 20002  --model-path /root/**/**/Qwen-7B-Chat  --revision main  --device cuda  --gpus 1  --num-gpus 1  --max-gpu-memory 60GiB  --gptq-wbits 16  --gptq-groupsize -1  --limit-worker-concurrency 5  --stream-interval 2  --controller-address http://localhost:21001  --worker-address http://localhost:20002 
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
wait model_worker running
