### ISSUE TITLE
[BUG] 0.2版本对话总是空答复，web控制台有报错

### ISSUE THREAD

**Issue by raphaelcheung** [chatchat-space/Langchain-Chatchat#1105]
**问题描述 / Problem Description**
用0.2版本运行glm6b-int4后，对话时无论说什么，都是空答复

**复现问题的步骤 / Steps to Reproduce**
1. 执行 对话
2. 随意发送一句话

**预期的结果 / Expected Result**
要有较为正常的自然语言答复

**实际结果 / Actual Result**
答复为空

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B-int4
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-large-chinese
- 操作系统及版本 / Operating system and version: win10
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: 显卡1060 6G 内存16G

**附加信息 / Additional Information**
最后一张图有捕捉到异常，看不懂
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50747339/dd31f9af-67ae-478a-a6fe-8732f2cb0860)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50747339/25137d2b-1aca-44fc-b732-0a46b7864137)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50747339/796407db-54fa-4828-a6f9-99c44518c034)

**Comment by zoepao** [comment]
报同样的错误

**Comment by YulinZhang255** [comment]
实验了chatglm一代各种版本均同样报错，但是chatglm2-6b-int4不报错，看报错感觉是chatglm一代需要kernel？

**Comment by raphaelcheung** [comment]
> 实验了chatglm一代各种版本均同样报错，但是chatglm2-6b-int4不报错，看报错感觉是chatglm一代需要kernel？

这样吗，那我去试试glm2

**Comment by liunux4odoo** [comment]
> 实验了chatglm一代各种版本均同样报错，但是chatglm2-6b-int4不报错，看报错感觉是chatglm一代需要kernel？

是的，在当前版本的langchain和fastchat下，glm一代只支持全量+CUDA加载，有些组合方式可以加载，但一提问就会出错。有群友指出可以修改fastchat代码加载glm一代量化版，但这只是临时措施。建议使用chatglm2。

**Comment by xiyuanyuan0506** [comment]
> 报同样的错误
解决了吗

**Comment by xiyuanyuan0506** [comment]
> 

请问llm_model_dict配置中chatglm2-6b的api_base_url修改自己的API地址，你是怎么写的

**Comment by wzsage** [comment]
我是用的glm2也报错

**Comment by raphaelcheung** [comment]
> 我是用的glm2也报错

试试int4

**Comment by zoepao** [comment]
我用的chatglm2-6b-int4.提问还是无回答，有人可以帮忙看一下不

**Comment by raphaelcheung** [comment]
> 我用的chatglm2-6b-int4.提问还是无回答，有人可以帮忙看一下不

我更新了v0.2.1后，用chatglm2-6b-int4也是报choices错误了，悲催

**Comment by qiyer** [comment]
也遇到了，我本来是好的。。。重新装了一下环境依赖，出现了这样的问题。 初步判断还是环境问题（依赖库版本或是缺少依赖库），导致 模型加载不成功
