### ISSUE TITLE
为什么0.2.0版本要设计成先启动服务，再启动API服务，最后再启动webui？

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1107]
现在这个项目的版本感觉多了好多前后端相关的东西，对于这块内容不了解的新手看起来真的很吃力QAQ

**Comment by sducxh** [comment]
我理解的：调用链UI->API->LLM，这样启动没啥问题吧

**Comment by liunux4odoo** [comment]
这主要是为了解耦LLM、知识库、WEBUI。这样做一是通过模块化方便替换不同的工具，比如现在用fastchat实现OpenAI兼容的LLM接口，如果以后有更好的工具，就可以替换掉，其他模块同理；二是解耦之后方便进行分布式部署，比如1台机器运行FastChat的controller和openai api服务器，以及本项目api.py服务器，另外N台机器运行FastChat的model_worker服务器，可以根据需要进行各种组合。
