### ISSUE TITLE
上传知识库，pdf和word都显示文件未成功加载

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#1112]
下载新的项目后，上传知识库，pdf和word都显示文件未成功加载
之前的版本pdf还可以加载成功，这是为什么

**Comment by adminChina** [comment]
看报错，好像一般情况都是缺少 poppler、LibreOffice、tesseract

**Comment by guiniao** [comment]
并没有报错



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月15日(周二) 下午5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] 上传知识库，pdf和word都显示文件未成功加载 (Issue #1112)




 
看报错，好像一般情况都是缺少 poppler、LibreOffice、tesseract

**Comment by roki1031** [comment]
新版本貌似不支持pdf解析了

**Comment by weedon666** [comment]
> 看报错，好像一般情况都是缺少 poppler、LibreOffice、tesseract

请问这些插件，centos上可以安装吗，是直接yum还是离线包安装

**Comment by adminChina** [comment]
> 新版本貌似不支持pdf解析了

支持，只是要装插件

**Comment by adminChina** [comment]
> > 看报错，好像一般情况都是缺少 poppler、LibreOffice、tesseract
> 
> 请问这些插件，centos上可以安装吗，是直接yum还是离线包安装

不清楚噢，我是 ubuntu 22
