### ISSUE TITLE
[BUG]  上传中文的csv文件时报错

### ISSUE THREAD

**Issue by RainAutumnZero** [chatchat-space/Langchain-Chatchat#1113]
windows下的anaconda环境中上传中文的csv文件时报错，文件编码格式为utf-8，请问如何修改项目读取文件编码格式？

**Comment by RainAutumnZero** [comment]
已解决，被windows编码折磨了好久。
windows默认中文编码格式是gbk，可以在语言设置里面更改为utf8，这样程序会默认使用utf8的decoder，有效解决编码错误问题。

**Comment by imClumsyPanda** [comment]
后续会增加自动检测编码功能

**Comment by bk007lz** [comment]
> 

如何解决的？
