### ISSUE TITLE
[BUG]在csv文件中回答不正确

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/Langchain-Chatchat#1114]
**问题描述 / Problem Description**
有没有办法在处理csv时不进行分词，或者这不是分词导致的问题，还请大佬指点

**复现问题的步骤 / Steps to Reproduce**
依次运行server/llm_api.py  server/api.py   webui.py

**预期的结果 / Expected Result**
![微信截图_20230815181619](https://github.com/chatchat-space/Langchain-Chatchat/assets/131108176/92060e66-c629-4055-92c5-beb073d4c1bb)

**实际结果 / Actual Result**
![微信截图_20230815181633](https://github.com/chatchat-space/Langchain-Chatchat/assets/131108176/e249979e-6079-45bc-9d9c-e790677aba64)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number:2.0
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B-32k
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): m3e
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:3.10

**Comment by imClumsyPanda** [comment]
可以在 `server/knowledge_base/utils.py` 中增加 textsplitter 执行前的文件类型判断

**Comment by qihangf** [comment]
> 可以在 `server/knowledge_base/utils.py` 中增加 textsplitter 执行前的文件类型判断

我这样改了之后还是一样的问题，请问是我没改对，还是别的问题导致的呢
 if self.ext==".csv":
            docs = loader
        else:
            docs = loader.load_and_split(text_splitter)
        print(docs[0])
        if using_zh_title_enhance:
            docs = zh_title_enhance(docs)
        return docs

**Comment by MrRabbit12** [comment]
这个问题好像和模型也有关系，我把csv改成txt后还是一样。但是我将文本尽可能缩短成一句话后，可以检索并回答问题，推测是这个上下文长度目前还无法满足大文本的需要

**Comment by qihangf** [comment]
> 这个问题好像和模型也有关系，我把csv改成txt后还是一样。但是我将文本尽可能缩短成一句话后，可以检索并回答问题，推测是这个上下文长度目前还无法满足大文本的需要

这样吗，谢谢啊
