### ISSUE TITLE
有人遇到这个错误吗，KeyError: 'LLamaLLM'

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#1118]
针对这个项目https://github.com/ymcui/Chinese-LLaMA-Alpaca-2，有人遇到这种错误吗？

models/shared.py", line 21, in loaderLLM
    llm_model_info = llm_model_dict[pre_model_name]
KeyError: 'LLamaLLM'

**Comment by hzg0601** [comment]
信息不明确，无法定位

**Comment by cristianohello** [comment]
@hzg0601 
你好，这个问题已经解决了，出现了另一个问题。
chuxi出现kill错误。
<img width="706" alt="8c4b476b0b8c83d3386fddb1c90294a" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/109277248/b6ecb204-b83e-430f-ac4a-75f900dc5a14">


llm_model_dict = {
    "LLamaLLM": {
        "name": "llama",
        "pretrained_model_name": "llama",
        "local_model_path": "/root/autodl-tmp/Chinese-LLaMA-Alpaca-2/models",
        "provides": "LLamaLLM"
    }
}
这是模型设置。

**Comment by cristianohello** [comment]
@hzg0601 
也就是说，我用了https://huggingface.co/ziqingyang/chinese-alpaca-2-13b这个地址的llama增量训练后的权重进行加载。
出现kill报错，是不是不兼容问题？


有人这样说：如果可以使用别的llm.py逻辑加载并generate()，那么只需要修改这里的dict，但是如果不适配，那么你需要自己写一个xxx_llm.py
