### ISSUE TITLE
[BUG] webui运行正常，chat页面无回复，报错Caught exception: 'choices'

### ISSUE THREAD

**Issue by xiyuanyuan0506** [chatchat-space/Langchain-Chatchat#1120]
**问题描述 
正常安装代码运行webui页面，对话页面输入，无输出

**复现问题的步骤 /
先启动服务python server/llm_api.py-再启动API服务python server/api.py-webui服务streamlit run webui.py；
再页面中输入对话，无输出

**实际结果
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/64192773/87122003-41c1-4229-b2a5-5eeddb1f55f3)

描述实际发生的结果 
llm_api.py
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/64192773/8ff08a32-db4e-4b0b-97f2-3005256c1a36)
server/api.py
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/64192773/6b64f195-9a19-4925-a851-3ed6cc1a8282)
webui.py
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/64192773/bcb4c46a-8916-4007-9da3-7828bbcfe378)

考虑是model_config.py文件中llm_model_dict写错，应如何修改
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/64192773/63fef762-90f6-4b31-911d-0cea54a00ed2)

**环境信息 / ubantu20.4 anconda环境下

- 是否使用 Docker 部署（是/否）：否
- 使用的模型： ChatGLM2-6B

- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by bk007lz** [comment]
修改了什么解决的？

**Comment by xzhoubinx** [comment]
我也出现了一样的问题，回头重建一个环境试试看

**Comment by xzhoubinx** [comment]
重新创建了一个环境，还是没用

**Comment by 63447285** [comment]
我也遇见这个问题了，报错一模一样，请问大佬怎么解决的？

**Comment by 63447285** [comment]
> 不断试错后，重新创建一个环境后，没有报错

请问怎么解决的？

**Comment by byrain** [comment]
0.2.2 最新代码依然存在问题 Caught exception: 'choices' 问题。
可以告知错误原因吗？

**Comment by imClumsyPanda** [comment]
@byrain @FURYFOR 请确认一下升级版本后是否已按照model_config.py.example更新model_config

**Comment by FURYFOR** [comment]
> @byrain @FURYFOR 请确认一下升级版本后是否已按照model_config.py.example更新model_config
已确认更新最新model_config，在知识库问答情况下偶尔会出现 Caught exception: 'choices' 问题，通过减少知识库匹配条数可以解决。所以想请问下：匹配输入模型的本地知识匹配文本，是否存在字数限制？

**Comment by imClumsyPanda** [comment]
@FURYFOR 模型本身存在输入长度限制，如果prompt过长可能触发相应报错，可以关注一下llm api的报错信息

**Comment by shanliuju** [comment]
大家有解决的吗？怎么解决呢？

**Comment by Gzj369** [comment]
> @FURYFOR 模型本身存在输入长度限制，如果prompt过长可能触发相应报错，可以关注一下llm api的报错信息

感谢，我调小知识库的参数后，问题不再出现
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/a93948ed-b609-47fa-84f4-dc5ba2b8d751)

**Comment by shanliuju** [comment]
这参数之前设置过了&nbsp; 还是回答没结果




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年9月5日(星期二) 晚上7:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] webui运行正常，chat页面无回复，报错Caught exception: &#39;choices&#39; (Issue #1120)





  
@FURYFOR 模型本身存在输入长度限制，如果prompt过长可能触发相应报错，可以关注一下llm api的报错信息
  
感谢，我调小知识库的参数后，问题不再出现

**Comment by Gzj369** [comment]
> > @FURYFOR 模型本身存在输入长度限制，如果prompt过长可能触发相应报错，可以关注一下llm api的报错信息
> 
> 感谢，我调小知识库的参数后，问题不再出现 ![image](https://user-images.githubusercontent.com/13391430/265684034-a93948ed-b609-47fa-84f4-dc5ba2b8d751.png)

Langchain 平台 v0.2.2 版本，如上所示通过调小知识库参数本来已经解决了的，但现在一次性新增上传了18个docx文档后，知识库参数不变，提出同样的问题，结果依然报错Caught exception: 'choices' @imClumsyPanda 麻烦大佬帮忙看看
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/67f9cf1d-6371-4174-857f-54b2c128d924)

**Comment by Gzj369** [comment]
同时查看知识库管理，发现如下错误
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/23cb0bc6-31b5-4c6c-9cc5-e8cdf3eeffa1)

**Comment by q460902075** [comment]
我用了llama2模型，一切换到知识库回答就出现这个问题

**Comment by Gzj369** [comment]
> 同时查看知识库管理，发现如下错误 ![image](https://user-images.githubusercontent.com/13391430/266941901-23cb0bc6-31b5-4c6c-9cc5-e8cdf3eeffa1.png)

通过点击“依据源文件重建向量库”，问题解决

**Comment by dwwangzz** [comment]
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)]
项目版本：v0.2.3
langchain版本：0.0.266. fastchat版本：0.2.24
---
当前LLM模型：chatglm-6b-int4 @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'E:\\AI\\models\\chatglm-6b-int4'}
当前Embbedings模型： text2vec-base @ cuda

以上环境也是报错Caught exception: 'choices'，chat页面无回复，我再公司的ubuntu上面部署的也是一样的问题，windows环境已经重新配置过一次环境，还是一样的错误。请协助解决，谢谢！

PS：使用的chatglm-6b-int4和chatglm2-6b-int4模型，text2vec-base和m3e-base相互配合都是一样的错误，单独使用openai的接口是没问题的。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码解决了不少这种问题

**Comment by iyangiiiii** [comment]
我已经更新到了0.2.5 但是还是出现了这种问题 该怎么解决呢
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101607550/aaa2bb47-d000-4ae3-be76-f172bda74174)

**Comment by Xuexixin** [comment]
我是从ChatGLM2-6B切换到ChatGLM2-6B-int4，的时候发现的这个错误，只需要在web页面点击“清空对话即可”

**Comment by wzhty86** [comment]
这个问题最终是怎么解决的呢？ @imClumsyPanda  @xiyuanyuan0506
