### ISSUE TITLE
EMBEDDING_MODEL 修改为其他的模型还是默认的text2vec模型。不知道是哪里的缓存导致的

### ISSUE THREAD

**Issue by wgq910668** [chatchat-space/Langchain-Chatchat#1122]
第一次启动的时候使用的是EMBEDDING_MODEL = "text2vec"
第二次启动的时候使用的是EMBEDDING_MODEL = "bge-large-zh"，然后第二个选择的本地的模型为bge。文件上传的时候还是tex2vec模型。请问是项目哪里做的缓存了吗？
重启api.py跟 llm_api.py 还是加载的text2vec模型。
是server/knowledge_base/utils.py这里面缓存导致的吗？
@lru_cache(1)
def load_embeddings(model: str, device: str):
    embeddings = HuggingFaceEmbeddings(model_name=embedding_model_dict[model],
                                       model_kwargs={'device': device})
    return embeddings

**Comment by imClumsyPanda** [comment]
0.2.0版本中向量库在新建时与embedding模型绑定，为防止embedding模型变化导致向量库检索/新增向量时发生异常，暂未提供更换embedding模型并重建向量库的功能，将在后续版本中提供，因此目前需要改用其他向量模型需新建向量库。

**Comment by banbsyip** [comment]
<img width="1150" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/18277076/26ab6697-87fe-437d-ad53-a51d06ce87e3">
我用bge-large-zh模型就显示知识库无法建立
