### ISSUE TITLE
[BUG] webui一键启动脚本执行报错

### ISSUE THREAD

**Issue by Hasen-dc** [chatchat-space/Langchain-Chatchat#1123]
webui一键启动脚本执行报错

运行命令：python webui_allinone.py --use-remote-api
出现以下错误

usage: webui_allinone.py [-h] [--model-path-address MODEL_PATH_ADDRESS [MODEL_PATH_ADDRESS ...]] [--controller-host CONTROLLER_HOST]
                         [--controller-port CONTROLLER_PORT] [--dispatch-method {lottery,shortest_queue}] [--worker-host WORKER_HOST] [--worker-port WORKER_PORT]
                         [--model-path MODEL_PATH] [--revision REVISION] [--device {cpu,cuda,mps,xpu}] [--gpus GPUS] [--num-gpus NUM_GPUS]
                         [--max-gpu-memory MAX_GPU_MEMORY] [--load-8bit] [--cpu-offloading] [--gptq-ckpt GPTQ_CKPT] [--gptq-wbits {2,3,4,8,16}]
                         [--gptq-groupsize GPTQ_GROUPSIZE] [--gptq-act-order] [--model-names MODEL_NAMES] [--limit-worker-concurrency LIMIT_WORKER_CONCURRENCY]
                         [--stream-interval STREAM_INTERVAL] [--no-register] [--server-host SERVER_HOST] [--server-port SERVER_PORT] [--allow-credentials]
                         [--api-keys API_KEYS]
webui_allinone.py: error: unrecognized arguments: --use-remote-api

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by hzg0601** [comment]
请更新代码
