### ISSUE TITLE
新版的怎么释放显存

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#1125]
1、问题回答完成后（基于LLM或者知识库的方式）怎么释放显存
2、推理过程中显存释放问题，看到过moss在推理一个大的问题时，显存即将拉满，它会立即释放显存，继续推理问题，这个就能保证不会因为大量的推理导致答案生成过程中报显存不够的错误

请问下，这两个优化怎么弄，感谢

**Comment by sunlin-xiaonai** [comment]
我也发现了这个问题，我的是没有沾满，显存和utl都没拉满，但是貌似卡住了一样，无法再次进行问题，我是通过api调用的

**Comment by elven2016** [comment]
同问，API问过问题之后，api占用很高的显存不释放

**Comment by zzflybird** [comment]
我也遇到了同样的问题，在使用文件问答后（相当于LLM对话功能，就是context上下文部分为文件解析后的文本内容），问题+context构建的最终的prompt 的长度为22k左右，使用的模型为ChatGLM2-6B，显存占用暴增7GB。在问答过程中可以检测用户连接状态，释放显存吗？

**Comment by zRzRzRzRzRzRzR** [comment]
需要清空历史记录后就可以。显存暴增是因为你将context带入模型后产生的。如果没有历史记录就不会有这个现象。
请更新到最新代码后重试。如果清除历史还有该现象可以重新提出issue
