### ISSUE TITLE
[FEATURE] 希望添加通过webui网页切换模型的功能

### ISSUE THREAD

**Issue by jackaihfia2334** [chatchat-space/Langchain-Chatchat#1127]
期望添加以下功能：

本地多模型的切换
希望可以有 fast chat demo 那种，通过下拉的方式进行本地模型的切换(在 langchain-chatGLM v0.1.x 版本时通过「模型配置」tab 页可以进行该操作)

**Comment by imClumsyPanda** [comment]
该功能已在开发计划内，将在后续版本推出，但因为涉及到fastchat启停模型服务，因此需要一段时间开发。

**Comment by LinTXde** [comment]
> 该功能已在开发计划内，将在后续版本推出，但因为涉及到fastchat启停模型服务，因此需要一段时间开发。

有一个想法，大佬可以参考一下看看可不可行。试着更换一键启动逻辑，先启动webui，可以设置一个多选页开启和关闭模型。启动不同模型的fastchat serve，对应port不一样，完成多开不冲突（考虑到多模型负载，多选后点“应用‘可以提醒显存等情况来二次确认选择模型后，对应模型启动）。然后对应多选表可以显示fastapi的port 及对应api的port。

这个思路我的想法是想笔记本启动项目web时，针对不同大模型模型性能，网络环境和隐私需求，方便更换是否使用chatgpt非官方 api or 官方的api or 其他部署在服务器大模型的api。

**Comment by adamwuyu** [comment]
等待此功能，支持。

> 该功能已在开发计划内，将在后续版本推出，但因为涉及到fastchat启停模型服务，因此需要一段时间开发。
