### ISSUE TITLE
[BUG] 0.2.0版本无法添加txt至向量库，添加后一直等待中，没报错

### ISSUE THREAD

**Issue by raphaelcheung** [chatchat-space/Langchain-Chatchat#1129]
**问题描述 / Problem Description**

有执行过 pip install "unstructured[all-docs]"
并且已经可以用LLM正常对话聊天了

我用以下几种方式尝试均失败：
1、保留sample中的所有文件，直接命令行重建知识库，控制台没报错，就一直卡在 UnstructuredFileLoader，挂机挂了12个小时也没变化，CPU一直显示35%的占用
2、删掉sample文件夹，命令行重建知识库后，进页面中，用知识库页面的添加文档的方式添加原来sample中的txt文件，40K左右大小，另外还从中切分了2个更小的txt，分别16K，7K，添加进去后，RUNNING一直显示，控制台同样卡在UnstructuredFileLoader日志
     2.1、刷新页面后，RUNNING状态消失，能看到添加的那3个txt文件，但都显示为没有向量库
     2.2、点击最小的txt添加至向量库，又是同样的情况，显示RUNNING，控制台卡在UnstructuredFileLoader，CPU 保持35%

没招了

**复现问题的步骤 / Steps to Reproduce**
1. 进入知识库管理页面
2. 点击 添加至向量库

**预期的结果 / Expected Result**
上方显示RUNNING一段时间后，该txt文档的向量库状态显示打勾

**实际结果 / Actual Result**
页面上方一直显示RUNNING，控制台没有相关报错，只打印了了一条

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.0
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B-int4
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: WIN10
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: gtx 1060 6g  内存16g  CPU I3-7100

**附加信息 / Additional Information**

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50747339/2146d833-8f4e-485b-b146-08d861ed8d6e)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50747339/b63c292c-64b9-4ba2-b0da-810f3a2ad06e)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50747339/3059fabc-1fef-408d-82d6-cc9008ff4123)

**Comment by raphaelcheung** [comment]
有朋友遇到过吗

**Comment by raphaelcheung** [comment]
有朋友分享下经验吗

**Comment by imClumsyPanda** [comment]
该问题与 #1157 的问题2一致，故关闭本issue，如需持续跟踪，请关注 #1157
