### ISSUE TITLE
[BUG] 切换其他大语言模型不兼容

### ISSUE THREAD

**Issue by Meidanlong** [chatchat-space/Langchain-Chatchat#1134]
**问题描述 / Problem Description**
1. 下载的本地大模型chinese-alpaca-2-7b-hf或者Llama-2-7b-chat-hf
2. 配置的应该没有问题（LLM_MODEL改为chatglm2-6b运行正常）
3. 在调用的接口的时候好像没有走配置的模型而是尝试连接openai然后链接失败
4. 不知道是不是我模型下载的哪里有问题，还是下载完模型需要再配置什么？

**复现问题的步骤 / Steps to Reproduce**

1. 下载大语言模型模型到本地，模型文件
<img width="526" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/26903122/b11e0549-07bf-49f5-af4e-d95223573844">

2. 配置'model_config.py'
<img width="833" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/26903122/10a5d2ca-6804-4d0e-89ca-80e1f7cb3bd1">

3. 调用chat接口

4. 报错 ‘2023-08-17 10:14:01,598 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-17 10:14:01,599 - manager.py[line:364] - WARNING: Error in AsyncIteratorCallbackHandler.on_retry callback: 'AsyncIteratorCallbackHandler' object has no attribute 'on_retry'
2023-08-17 10:14:01,599 - manager.py[line:364] - WARNING: Error in StdOutCallbackHandler.on_retry callback: 'StdOutCallbackHandler' object has no attribute 'on_retry'’

**预期的结果 / Expected Result**
大语言模型正常回答
**实际结果 / Actual Result**
<img width="1428" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/26903122/3b446461-05e8-40c2-a04c-10669d97cfb5">

**Comment by Meidanlong** [comment]
修改api_base_url端口为8888
<img width="720" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/26903122/7c24f7c6-7475-4de3-abd5-64cee1266866">

**Comment by suoer95** [comment]
兄弟，我也遇到了这个问题，请问解决了吗？
