### ISSUE TITLE
使用BaiChuan13B进行知识库问答，模型不回答或者答非所问

### ISSUE THREAD

**Issue by yyl424525** [chatchat-space/Langchain-Chatchat#1138]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20411218/d1338ceb-de7b-4200-85c7-c06ae583884b)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20411218/a2d0da76-3187-4906-b69a-7aaa9ea6c57a)

请问什么原因啊？

**Comment by yyl424525** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20411218/f10c9c3c-7b85-44a7-b531-738833daa4c8)

**Comment by yyl424525** [comment]
以上问题是使用baichuan模型在前端界面回答错误的示例。如果换成chatGLM则没有这个问题：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20411218/922d2098-136d-4f4a-a024-bcd947612837)

**Comment by cuiwenbing** [comment]
同样问题，有没有大佬回答下

**Comment by zoepao** [comment]
> ![image](https://user-images.githubusercontent.com/20411218/261184881-d1338ceb-de7b-4200-85c7-c06ae583884b.png)
> 
> ![image](https://user-images.githubusercontent.com/20411218/261184946-a2d0da76-3187-4906-b69a-7aaa9ea6c57a.png)
> 
> 请问什么原因啊？

@yyl424525 请问一下，你是怎么部署达到可以问答的效果的啊？为啥我按照readme部署之后无法问答呢？就是问题无响应，可以请教一下不

**Comment by yyl424525** [comment]
> > ![image](https://user-images.githubusercontent.com/20411218/261184881-d1338ceb-de7b-4200-85c7-c06ae583884b.png)
> > ![image](https://user-images.githubusercontent.com/20411218/261184946-a2d0da76-3187-4906-b69a-7aaa9ea6c57a.png)
> > 请问什么原因啊？
> 
> @yyl424525 请问一下，你是怎么部署达到可以问答的效果的啊？为啥我按照readme部署之后无法问答呢？就是问题无响应，可以请教一下不

我就是按照readme指引部署的，保证每一步没有问题再进行下一步，你说的问题不无响应我还没遇到，可以加他们的微信群咨询一下

**Comment by lx11744** [comment]
我使用Baichuan-13b-Chat也遇到这个问题，待解决。

**Comment by roki1031** [comment]
在这个项目外单独使用Baichuan-13b-Chat会有这样的问题吗？

**Comment by imClumsyPanda** [comment]
请问fschat的版本是多少？

**Comment by yyl424525** [comment]
> 请问fschat的版本是多少？以及项目之外单独执行该模型是否存在该问题？

fschat    0.2.20，项目之外，单独启动百川模型，没有问题

**Comment by yyl424525** [comment]
> 在这个项目外单独使用Baichuan-13b-Chat会有这样的问题吗？

没有

**Comment by roki1031** [comment]
> > > ![image](https://user-images.githubusercontent.com/20411218/261184881-d1338ceb-de7b-4200-85c7-c06ae583884b.png)
> > > ![image](https://user-images.githubusercontent.com/20411218/261184946-a2d0da76-3187-4906-b69a-7aaa9ea6c57a.png)
> > > 请问什么原因啊？
> > 
> > 
> > @yyl424525 请问一下，你是怎么部署达到可以问答的效果的啊？为啥我按照readme部署之后无法问答呢？就是问题无响应，可以请教一下不
> 
> 我就是按照readme指引部署的，保证每一步没有问题再进行下一步，你说的问题不无响应我还没遇到，可以加他们的微信群咨询一下

readme中好像没有说怎么部署baichuan系列模型呀？大佬能简单说说改哪吗，我目前只改了model_config.py文件中的模型路径，但是运行之后不输出内容。

**Comment by iaoxuesheng** [comment]
请问你是如何应用baichuan13b的，都需要更改哪些地方呀

**Comment by imClumsyPanda** [comment]
可参考 https://github.com/chatchat-space/Langchain-Chatchat/issues/933#issuecomment-1683790103

**Comment by roki1031** [comment]
> 可参考 [#933 (comment)](https://github.com/chatchat-space/Langchain-Chatchat/issues/933#issuecomment-1683790103)
这个comment里面没有回答为啥BaiChuan13B会答非所问呀

**Comment by sweetboxwwy** [comment]
请问这个问题解决了吗，此外我发现知识库的检索能力比较差

**Comment by WilliamChen-luckbob** [comment]
原则上说baichuan2-13b由于训练集也就13b，跟GPT的170b差了十万八千里，此为其一。其二，你拆分原文的逻辑（拆出来的文本块）对LLM的回答具有本质的影响，如果你没有较好的拆分原文，那么光靠普通embeddings拿出来的引用语句块质量会非常低，如此这般，即使你用GPT4也只能阿巴阿巴。

**Comment by zoepao** [comment]
邮件已收到，谢谢。
