### ISSUE TITLE
[BUG] 简洁阐述问题 / 前端一直处于等待中

### ISSUE THREAD

**Issue by kanglinchun** [chatchat-space/Langchain-Chatchat#1140]
**问题描述 / Problem Description**
先启动服务python server/llm_api.py-再启动API服务python server/api.py-webui服务streamlit run webui.py；
打开前端一直显示等待中
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/132032328/0120ecd6-7610-43bf-b2ca-012dabbda54d)
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/132032328/fcb8bacb-6618-436a-a5da-fb8da3b0a7a7)
![3](https://github.com/chatchat-space/Langchain-Chatchat/assets/132032328/f0596715-1318-4f5c-899e-8a38f65fb701)
![4](https://github.com/chatchat-space/Langchain-Chatchat/assets/132032328/d998d60a-f19b-427a-ae60-b25599049a93)
 
我怀疑是我的环境无法运行 llm_api_launch.py，单独运行 llm_api_launch.py时，一直显示 wait controller running 

**环境信息 / Environment Information**
- Langchain-Chatchat
-
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：moka-ai/m3e-base
- 操作系统及版本 /  ubuntu22.04
- Python 版本 / Python version: Python 3.10.8

**Comment by bk007lz** [comment]
解决了吗？

**Comment by zoepao** [comment]
@kanglinchun 解决了不？遇到同样的问题了

**Comment by glide-the** [comment]
autodl部分服务器cdn有问题，尝试更换服务发布区域
