### ISSUE TITLE
[BUG] 知识库API调用时，stream参数设置：True时，返回正常，stream设置为False时候，返回为“。”

### ISSUE THREAD

**Issue by Nick198903** [chatchat-space/Langchain-Chatchat#1141]
**问题描述 / Problem Description**
知识库API调用时，stream参数设置：True时，返回正常，stream设置为False时候，返回为“。”

**复现问题的步骤 / Steps to Reproduce**
python test_knowledge_api.py， 代码如下
import requests
data = {
  "query": "宪法是什么时候发布的",
  "knowledge_base_name": "samples",
  "top_k": 1,
  "stream": False
}
res = requests.post('http://xx:7861/chat/knowledge_base_chat', json=data)
if res.status_code == 200:
  print("res.text=", res.text)

**Comment by liunux4odoo** [comment]
跟 #1090 重复的问题，已经修复。

0.2.1版已经发布，请按照文档更新依赖和项目代码后再试一下。

**Comment by liunux4odoo** [comment]
Duplicate of #1090
