### ISSUE TITLE
[BUG] 提问中带有json数据后，第二次提问携history后，ChatPromptTemplate.from_messages出现异常(只要提问中含有"括号{}"  )

### ISSUE THREAD

**Issue by developservertwo** [chatchat-space/Langchain-Chatchat#1142]
**问题描述 / Problem Description**
当首次提问中带有json数据后，第二次提问携history后，ChatPromptTemplate.from_messages出现异常，
即history中携带的历史提问信息中包含json格式数据时出现，验证问题。
异常信息为:
 File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/prompts/chat.py", line 502, in from_messages
    _messages = [_convert_to_message(message) for message in messages]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/prompts/chat.py", line 502, in <listcomp>
    _messages = [_convert_to_message(message) for message in messages]
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/prompts/chat.py", line 673, in _convert_to_message
    _message = _create_template_from_message_type(message_type_str, template)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/prompts/chat.py", line 619, in _create_template_from_message_type
    message: BaseMessagePromptTemplate = HumanMessagePromptTemplate.from_template(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/prompts/chat.py", line 142, in from_template
    prompt = PromptTemplate.from_template(template, template_format=template_format)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/prompts/prompt.py", line 218, in from_template
    return cls(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/langchain/load/serializable.py", line 74, in __init__
    super().__init__(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for PromptTemplate
__root__
  Invalid format specifier (type=value_error)

**复现问题的步骤 / Steps to Reproduce**
1. 提问附带json格式数据
2. 点击发送，正常回复
3. 第二次提问，随便输入什么（必须携带history）
4. 问题复现

请求接口:  http://localhost:7861/chat

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/133831396/86236212-2e5e-468b-b65c-d30feef6a71c)

**实际结果 / Actual Result**
![_1692255261798](https://github.com/chatchat-space/Langchain-Chatchat/assets/133831396/c1c9ef9c-6077-44b0-9a6c-cef0775cbb32)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master分支(v0.2.0)/commit号: 7ef032bcf4f89dcbec4e7e472842c8c2b1a313ee
![_16922553147533](https://github.com/chatchat-space/Langchain-Chatchat/assets/133831396/9e823145-9ad5-4b4b-8f81-a9d82d346f28)
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：m3e-large
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:  3.8.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by developservertwo** [comment]
补充一下:
只要输入的语句中含有 {}就会出现上述问题（100%复现）


![企业微信截图_16922623627424](https://github.com/chatchat-space/Langchain-Chatchat/assets/133831396/9661d811-6d94-44b7-8a8b-862e28b2ed7b)

**Comment by zoepao** [comment]
> 补充一下: 只要输入的语句中含有 {}就会出现上述问题（100%复现）
> 
> ![企业微信截图_16922623627424](https://user-images.githubusercontent.com/133831396/261254235-9661d811-6d94-44b7-8a8b-862e28b2ed7b.png)

请问你是怎么完成的部署啊，为啥我部署之后问答总是没有回复，是否可以请教一下。。谢谢

**Comment by developservertwo** [comment]
> > 补充一下: 只要输入的语句中含有 {}就会出现上述问题（100%复现）
> > ![企业微信截图_16922623627424](https://user-images.githubusercontent.com/133831396/261254235-9661d811-6d94-44b7-8a8b-862e28b2ed7b.png)
> 
> 请问你是怎么完成的部署啊，为啥我部署之后问答总是没有回复，是否可以请教一下。。谢谢

我这边首先是有ChatGLM2-6B的环境的，操作步骤如下(model_config配置以及修改):
1、进入ChatGLM2-6B目录启动 openai_api.py   命令 openai_api.py
2、进入Langchain-Chatchat目录启动 api.py    命令 python server/api.py 
3、启动web端,  启动webui.py             命令streamlit run webui.py

**Comment by imClumsyPanda** [comment]
该问题已收到，接下来将测试如何解决这一问题。

**Comment by pihang** [comment]
我也是这个问题，请问现在解决了吗？

**Comment by pihang** [comment]
在server/chat/utils.py下加：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/69835808/f67e73ab-05a8-4548-af9c-7a534f6cdbe4)
可解决

**Comment by liunux4odoo** [comment]
> 在server/chat/utils.py下加： ![image](https://user-images.githubusercontent.com/69835808/262297610-f67e73ab-05a8-4548-af9c-7a534f6cdbe4.png) 可解决

这样简单替换不行吧，会改变消息内容。

**Comment by liunux4odoo** [comment]
该问题已经在开发版中修复，请关注项目版本升级信息，或者可以拉取pre-release分支代码提前体验测试。

该issue先关闭，如测试中发现问题可以重开。
