### ISSUE TITLE
[FEATURE] 需要补充dockerfile

### ISSUE THREAD

**Issue by zeng-zc** [chatchat-space/Langchain-Chatchat#1145]
**功能描述 / Feature Description**
部署的那个镜像，registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.0，缺dockerfile

**解决的问题 / Problem Solved**
用docker部署时，没有dockerfile，没法自定义修改

**实现建议 / Implementation Suggestions**
补充build那个镜像的dockerfile

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by dividez** [comment]
同问 什么时候补充 Dockerfile 呢？

**Comment by sixintadi** [comment]
同问  期待尽快补充Dockerfile

**Comment by WeideMo** [comment]
同问 期待尽快补充Dockerfile

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.5会发布一个新的docker文件，请关注最新代码

**Comment by jmsking** [comment]
为什么不公布dockerfile了？
