### ISSUE TITLE
[FEATURE] 简洁阐述功能 / Concise description of the feature

### ISSUE THREAD

**Issue by Duyz232** [chatchat-space/Langchain-Chatchat#1147]
我想要了解一下,api能与GPT接口吗

**Comment by hzg0601** [comment]
可以

**Comment by Duyz232** [comment]
我在执行：streamlit run webui.py的时候，可以打开网页，
<img width="1026" alt="208738f4f23ff78cf3d1641340ec5b7" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/9047d636-c716-409f-83f9-939677998e1a">

但是提问的时候一直没有回答出现，如下报错“
<img width="1063" alt="a11c20d48b8802887f73807ac733e50" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/68ebec16-93a5-442d-85fd-8e0ac2056d7d">
”这种该如何处理呢
