### ISSUE TITLE
[FEATURE] 希望在readme中增加项目的工程架构

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1148]
也许可以通过图形方式更新当前0.2.0版本的项目工程架构、API、服务器、LLM以及前端之间的交互方式。这样可以更方便地理解项目的架构，从而便于进行二次开发。

**Comment by liunux4odoo** [comment]
项目主要架构就是下面这张图：
![](https://github.com/chatchat-space/Langchain-Chatchat/raw/master/img/langchain+chatglm.png)

看一下`0.2.x`服务启动方式也能清楚项目的调用流程,主要分为3个部分：
1. 第14步之前。是本项目基于langchain实现的，主要是知识库文档处理以及LLM对接。
2. LLM部分完全使用fastchat实现，本项目在这个基础上实现了LLM和知识库的相关接口`api.py`。
3. 最终的UI展示部分。这是本项目使用streamlit开发的，希望能为用户提供一个界面美观、功能多样、交互方便的WEB UI。

**Comment by aiot-tech** [comment]
chat/chat这个接口是调用了langchain的上下文知识推理功能吗:)

**Comment by zRzRzRzRzRzRzR** [comment]
我们将会在之后写wiki，更加的具有可读性
