### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by abigkeep** [chatchat-space/Langchain-Chatchat#115]
(test) C:\Users\linh\Desktop\langchain-ChatGLM-master>pip install -r requirements.txt
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2
  Cloning https://github.com/facebookresearch/detectron2.git (to revision v0.6) to c:\users\linh\appdata\local\temp\pip-install-r6nvkymy\detectron2_82fa96c5bd1e4f8dbb7dd72a4a9cf316
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\linh\AppData\Local\Temp\pip-install-r6nvkymy\detectron2_82fa96c5bd1e4f8dbb7dd72a4a9cf316'
  fatal: unable to access 'https://github.com/facebookresearch/detectron2.git/': SSL certificate problem: unable to get local issuer certificate
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\linh\AppData\Local\Temp\pip-install-r6nvkymy\detectron2_82fa96c5bd1e4f8dbb7dd72a4a9cf316' did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git 'C:\Users\linh\AppData\Local\Temp\pip-install-r6nvkymy\detectron2_82fa96c5bd1e4f8dbb7dd72a4a9cf316' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
报错如上。

**Comment by Iteravse** [comment]
同样的问题，我的python 版本是 Python 3.10.9 ubuntu 
同样是exit code128,
/home/langchain-ChatGLM$ pip install -r requirements.txt
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git@v0.6#egg=detectron2
  Cloning https://github.com/facebookresearch/detectron2.git (to revision v0.6) to /tmp/pip-install-yis71p9h/detectron2_903a1e934df5480f941c19a509436989
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-yis71p9h/detectron2_903a1e934df5480f941c19a509436989
  fatal: unable to access 'https://github.com/facebookresearch/detectron2.git/': Failed to connect to github.com port 443 after 130185 ms: Connection timed out
  error: subprocess-exited-with-error

  × git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-yis71p9h/detectron2_903a1e934df5480f941c19a509436989 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-yis71p9h/detectron2_903a1e934df5480f941c19a509436989 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

 @imClumsyPanda

**Comment by jackchenwen** [comment]
我在Windows server 2016的anaconda中，运行pip install -r requirements.txt，先后出现错误提示安装torch、pycocotools、Microsoft C++ Build Tools和修改最大文件长度等，解决一个又出现另一个，请问是什么原因呢？@imClumsyPanda

**Comment by zluckymn** [comment]
> 我在Windows server 2016的anaconda中，运行pip install -r requirements.txt，先后出现错误提示安装torch、pycocotools、Microsoft C++ Build Tools和修改最大文件长度等，解决一个又出现另一个，请问是什么原因呢？@imClumsyPanda

我也遇到一样的问题后面只能在wsl2 下使用
