### ISSUE TITLE
[BUG] 新增知识库时，提示无法连接到服务端API

### ISSUE THREAD

**Issue by xiaoshyang** [chatchat-space/Langchain-Chatchat#1157]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'      python startup.py --all-webui
2. 点击 '...' / Click '...'，   依据源文件重建向量库
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs
<img width="1498" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/12255598/15b02055-cf42-401d-8bc2-6f1f991cf307">

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
能够构建成功

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.31.
python版本：3.9.15 (main, Nov 24 2022, 14:31:59) 
[GCC 11.2.0]
项目版本：v0.2.1
langchain版本：0.0.257. fastchat版本：0.2.24

当前LLM模型：chatglm2-6b @ cuda
{'api_base_url': 'http://localhost:8899/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/mnt/workspace/chatglm2-6b'}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:8899/v1
请确认llm_model_dict中配置的api_base_url与上面地址一致。
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================
这是启动成功的信息。
**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zicheqingluo** [comment]
同样的问题

**Comment by imClumsyPanda** [comment]
截图中有两处报错信息：

1.  KeyError ‘finished’ 建议尝试将langchain版本升级至0.0.266后再次重建知识库试试看；

2. Nosuchfileordirectory:•/home/pai/1ib/python3.9/site-packages/st_aggrid/frontend/bui1d/bootstrap.min.css.map’ 看起来是streamlit-aggrid插件问题，如果该问题可复现，请反馈下streamlit及streamlit-aggrid版本及触发报错的操作。

**Comment by adminChina** [comment]
一样会报错，应该是api中的问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17397276/8f00232a-9dda-494f-bd7d-8a6a85385274)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17397276/50907245-59b5-4f7d-ae12-4bae18e29741)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17397276/6966ee3f-61c0-4c7b-855b-d5af156702e5)

**Comment by osbear** [comment]
>KeyError ‘finished’ 建议尝试将langchain版本升级至0.0.266后再次重建知识库试试看

已经将langchain版本升级到0.0.271，还是同样报错。

**Comment by adminChina** [comment]
> > KeyError ‘finished’ 建议尝试将langchain版本升级至0.0.266后再次重建知识库试试看
> 
> 已经将langchain版本升级到0.0.271，还是同样报错。

这个问题已经被修复了，重新pull一下这个仓库的代码。

**Comment by StevenLu8050** [comment]
@imClumsyPanda 我這邊還是有一直卡在UnstructuredFileLoader 的問題，依然沒有解決，向量庫載入的時候卡在這邊。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/139423772/fd6dc128-a82b-412d-8216-af39c634155b)

**Comment by FakeSnake618** [comment]
我也遇到了同样的问题，是最新的0.2.5的代码。2023-10-02 10:13:01 | INFO | root | UnstructuredFileLoader used for D:\projects\kefu\Langchain-Chatchat-0.2.5\knowledge_base\test\content\1.txt
2023-10-02 10:18:01 | ERROR | root | ReadTimeout: error when post http://localhost:7861/knowledge_base/upload_docs: timed out
2023-10-02 10:18:01 | INFO | root | UnstructuredFileLoader used for D:\projects\kefu\Langchain-Chatchat-0.2.5\knowledge_base\test\content\1.txt
在这一步卡死。

**Comment by StevenLu8050** [comment]
我嘗試更新到最新版的0.2.4就可以了，目前沒有試過0.2.5
