### ISSUE TITLE
自定义知识库 上传、删除等报错

### ISSUE THREAD

**Issue by bubble666666** [chatchat-space/Langchain-Chatchat#1158]
操作流程
1.创建知识库 本地embedding模型 都有、向量类型也设置好faiss  --->ok
2.上传文件-->报错  (如果用自带的samples上传是可以的 自定义的就报错)
页面报错
![7bb06805ffcbebff19edcf4e8b67b95](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/e9335036-6790-40d0-9b0b-55260b6d3bf7)
api也报错

相关代码片段
![8282fdf8766c8facfc02befa919c78a](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/d83db305-b2b6-435e-8916-7fe19a70b22c)
![136fe5d986c81b305c9b91671ac01d7](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/1ecca3d0-6737-4dae-ab47-bc13a64a6836)
![5a255c0f0147855863ccda64c9e168c](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/fb206bcc-c603-4cc2-84c8-574cd7cd5e3c)
![70fc30bc8ea6cbf833705672e9054c9](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/2b926f58-3f42-4aed-8d92-5da985c1681c)
说我api没开 实际上已经开了的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/4e8a1428-186a-4fe9-93f6-05f52515dee6)

**Comment by geraldjin** [comment]
和我的症状一样，检查了一下发现报错RuntimeError: CUDA out of memory.显存满了，停掉服务重新启动就好了。
另外max_gpu_memory我也设置了一下，不知道有没有用。。。

**Comment by weedon666** [comment]
同样报错：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/b4b2250e-c4ad-4f0b-bbc5-ef6174e4eb07)
但是文件还在继续传，显存和内存都有合适的空余。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/633ff168-c5ce-4a38-93ff-a09ed2ae2596)

**Comment by JohanRain** [comment]
同样的问题，旧版本报错报错JSONDecodeError: Expecting value: line 1 column 1 (char 0)
更新仓库后提示报错KeyError: 'msg'

**Comment by imClumsyPanda** [comment]
请将langchain版本升级至0.0.266后再次重建知识库试试看。

**Comment by ilovesouthpark** [comment]
没有升级langchain，但是再次重建知识库前面的msg问题就不出现了。

**Comment by MingjunHu** [comment]
我分别升级到 266和268 也重新安装了 faiss-cpu 和 faiss-gpu ，重新新建知识库。都依然报 “msg” 错误

**Comment by weedon666** [comment]
> 我分别升级到 266和268 也重新安装了 faiss-cpu 和 faiss-gpu ，重新新建知识库。都依然报 “msg” 错误

同

**Comment by liunux4odoo** [comment]
> 我分别升级到 266和268 也重新安装了 faiss-cpu 和 faiss-gpu ，重新新建知识库。都依然报 “msg” 错误

请更新一下本项目代码和依赖（特别是langchain/fschat），重新再试一下。

**Comment by zRzRzRzRzRzRzR** [comment]
请更新最新代码和新的环境要求
