### ISSUE TITLE
bug- 使用pg存储向量时，向量检索错误 {TypeError}TypeError("'Document' object is not subscriptable") 

### ISSUE THREAD

**Issue by shutter-cp** [chatchat-space/Langchain-Chatchat#1159]
**问题描述 / Problem Description**
使用pg存储向量时，向量检索错误 {TypeError}TypeError("'Document' object is not subscriptable") 

**复现问题的步骤 / Steps to Reproduce**
1. 执行 搜索

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.21
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：gpt
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by weedon666** [comment]
pg存储向量问题2：
问题描述 / Problem Description
使用pg存储向量时，知识库初始化时，建表错误ERROR:  type "vector" does not exist at character 73
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/66623d35-16cb-41b2-bebd-ad337668390d)

复现问题的步骤 / Steps to Reproduce
（1）config配置
# 默认向量库类型。可选：faiss, milvus, pg.
DEFAULT_VS_TYPE = "pg"
（2）初始化知识库
python init_database.py --recreate-vs

环境信息 / Environment Information
langchain-ChatGLM 版本/commit 号：0.21
是否使用 Docker 部署（是/否）：no
使用的模型：ChatGLM2-6B
使用的 Embedding 模型：GanymedeNil/text2vec-large-chinese 
pg依赖：
pgvector                  0.2.1
psycopg                   3.1.10
psycopg2-binary           2.9.7

**Comment by weedon666** [comment]
**另补充：**

docker-compose.yml中，POSTGRES_DB请修改为langchain_chatglm，和model_config.py中对标，否则报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/005b628a-ba1b-4922-8952-49d232ec9362)

**Comment by layjoy** [comment]
可以试试Milvus也报同样的错，只有faiss正常

**Comment by layjoy** [comment]
将 kb_service 中的 pd 和 Milvus 里的do_search  下的similarity_search 改为 similarity_search_with_score 就可以了。

**Comment by seasnakes** [comment]
> 将 kb_service 中的 pd 和 Milvus 里的do_search 下的similarity_search 改为 similarity_search_with_score 就可以了。

milvus向量数据库 除了本地docker部署和k8s 以外能用远程的吗？我试了下一直报超时

**Comment by zqt996** [comment]
> milvus

milvus # pymilvus==2.1.3 和milvus服务需要对应

**Comment by zqt996** [comment]
Q15: 使用pg向量库建表报错

A15: 需要手动安装对应的vector扩展(连接pg执行 CREATE EXTENSION IF NOT EXISTS vector)

Q16: pymilvus 连接超时

A16.pymilvus版本需要匹配和milvus对应否则会超时参考pymilvus==2.1.3

pg 和 milvus 主要要注意环境问题

**Comment by GXKIM** [comment]
> 将 kb_service 中的 pd 和 Milvus 里的do_search 下的similarity_search 改为 similarity_search_with_score 就可以了。

请问自己储存的向量，能在milvus向量库中正常查看吗？我这边是查看不到

**Comment by zqt996** [comment]
> > 将 kb_service 中的 pd 和 Milvus 里的do_search 下的similarity_search 改为 similarity_search_with_score 就可以了。
> 
> 请问自己储存的向量，能在milvus向量库中正常查看吗？我这边是查看不到

milvus_kb_service.py 
if __name__ == '__main__':
    # 测试建表使用
    from server.db.base import Base, engine
    Base.metadata.create_all(bind=engine)
    milvusService = MilvusKBService("test")
    milvusService.add_doc(KnowledgeFile("README.md", "test"))
    milvusService.delete_doc(KnowledgeFile("README.md", "test"))
    milvusService.do_drop_kb()
    print(milvusService.search_docs("测试"))
milvus_kb_service.py 文件主函数把删除文档删除知识库注释改下查可以

**Comment by GXKIM** [comment]
我是没改这个，我的问题已解决

zqt996 ***@***.***>于2023年8月22日 周二16:36写道：

**Comment by zqt996** [comment]
新修改代码了可以试一试
