### ISSUE TITLE
[BUG] 依据源文件重建向量库报错

### ISSUE THREAD

**Issue by adminChina** [chatchat-space/Langchain-Chatchat#1162]
**问题描述 / Problem Description**
依据源文件重建向量库，调用httpx报错，[Errno 115] Operation now in progress, 尝试了很多遍都是这个问题，也尝试了使用python 中requests 发出请求。curl 请求都是成功的唯独httpx报错

**复现问题的步骤 / Steps to Reproduce**
1、通过一键启动 python startup.py --all-webui
2、打开知识库管理
3、点击“依据源文件重建向量库”

**预期的结果 / Expected Result**
应该重建成功，无报错

**实际结果 / Actual Result**
报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17397276/04ed5538-3582-477b-b29a-8523dd2f5e96)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17397276/19d51e9c-2a37-405a-aef9-02327d60c28f)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zicheqingluo** [comment]
同样的问题

**Comment by zicheqingluo** [comment]
同样的问题

**Comment by imClumsyPanda** [comment]
请将langchain版本升级至0.0.266后再次重建知识库试试看。

**Comment by imClumsyPanda** [comment]
与 https://github.com/chatchat-space/Langchain-Chatchat/issues/1157 问题1相同，故关闭此 issue，请在 #1157 中继续跟踪
