### ISSUE TITLE
阿里云端部署的时候前端图片加载不出来

### ISSUE THREAD

**Issue by STARK-WANG-STAR** [chatchat-space/Langchain-Chatchat#1167]
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/131878259/d9e81f08-a8ae-43d4-957a-2171b0c9d9f4)

**Comment by STARK-WANG-STAR** [comment]
I made a stupid mistake

**Comment by JOY-SWang** [comment]
可以问一下怎么部署到阿里云端嘛？我这边涉及了很多websocket接口不对。。。

**Comment by STARK-WANG-STAR** [comment]
好久之前做的了，阿里云部署的时候注意一下一些图片的路径，包括这个项目文件夹在整个服务器里面的路径。其次是把阿里云服务器相关端口打开，streamlit运行在8501端口上的，保证别人IP+端口可以访问。其次.....不清楚了好长时间之前做的了，不清楚的可以尝试加那个项目底部的微信群，问问大佬
&nbsp;


★
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月21日(星期四) 上午9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] 阿里云端部署的时候前端图片加载不出来 (Issue #1167)





 
可以问一下怎么部署到阿里云端嘛？我这边涉及了很多websocket接口不对。。。
