### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by jnulzl** [chatchat-space/Langchain-Chatchat#1168]
startup.py文件中如下地方缺少","：
- 1、https://github.com/chatchat-space/Langchain-Chatchat/blob/cdea240c3122bf6a0febfc5eecfeeacf4d6a2fd8/startup.py#L287
- 2、https://github.com/chatchat-space/Langchain-Chatchat/blob/cdea240c3122bf6a0febfc5eecfeeacf4d6a2fd8/startup.py#L295

**Comment by imClumsyPanda** [comment]
已修复该问题，感谢反馈。
