### ISSUE TITLE
Caught exception: 'utf-8' codec can't decode byte 0xc9 in position 1440: invalid continuation byte

### ISSUE THREAD

**Issue by soyisou** [chatchat-space/Langchain-Chatchat#1169]
运行 python api.py，出现如下问题：
Caught exception: 'utf-8' codec can't decode byte 0xc9 in position 1440: invalid continuation byte
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/116480575/763d8d3e-f949-47d2-a0d8-3ff332471945)

**Comment by imClumsyPanda** [comment]
建议在本地测试一下文件使用什么encoding类型能够正确读取，以确定文件有无编码问题。
