### ISSUE TITLE
[BUG] 按照文档初始化知识库时报错 partition() got an unexpected keyword argument 'autodetect_encoding'

### ISSUE THREAD

**Issue by qengli** [chatchat-space/Langchain-Chatchat#1170]
**问题描述 / Problem Description**
按照文档操作，在运行`python init_database.py --recreate-vs` 时报错
```
partition() got an unexpected keyword argument 'autodetect_encoding'
```

**复现问题的步骤 / Steps to Reproduce**
1. 执行 `python init_database.py --recreate-vs`
2. 问题出现 / Problem occurs
```
2023-08-20 17:40:07,843 - utils.py[line:145] - INFO: Note: detected 96 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
2023-08-20 17:40:07,843 - utils.py[line:148] - INFO: Note: NumExpr detected 96 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-08-20 17:40:07,844 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
database talbes created
recreating all vector stores
UnstructuredFileLoader
partition() got an unexpected keyword argument 'autodetect_encoding'
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：
0.2.0和0.2.1都有此问题
- 是否使用 Docker 部署（是/否）：
否

- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：

chatglm2-6b

- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：
m3e-base

- 操作系统及版本 / Operating system and version:

ubuntu 22.04

- Python 版本 / Python version:

python 3.8

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
你的langchain/fschat/unstructured版本各是多少？

请更新一下项目代码，并按照文档更新依赖后，再试一下。

**Comment by jamesoujj** [comment]
我的问题和这个一样

操作系统：macOS-13.4.1-arm64-arm-64bit.
python版本：3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ]
项目版本：v0.2.1
langchain版本：0.0.266. fastchat版本：0.2.24
unstructured 版本：0.6.6

更新了项目代码，但还是老问题。
这问题已经出现了三四天了

**Comment by xiaoxiao261258** [comment]
> 我的问题和这个一样
> 
> 操作系统：macOS-13.4.1-arm64-arm-64bit. python版本：3.11.3 (main, Apr 19 2023, 18:49:55) [Clang 14.0.6 ] 项目版本：v0.2.1 langchain版本：0.0.266. fastchat版本：0.2.24 unstructured 版本：0.6.6
> 
> 更新了项目代码，但还是老问题。 这问题已经出现了三四天了

参考#1054 @solofeng网友的方法，亲测管用

[solofeng](https://github.com/solofeng) commented [17 hours ago](https://github.com/chatchat-space/Langchain-Chatchat/issues/1054#issuecomment-1689435866)
需要升级 unstructured unstructured-inference，我的是unstructured-0.10.5 unstructured-inference-0.5.16

**Comment by qengli** [comment]
我昨天拉取了最新的代码，并用conda重新初始化环境，设置为python3.9就好了。也知道是换了python的原因还是更新了代码的原因。
现在的commit refs: 
现在环境的主要模块版本如下：
langchain                     0.0.266
fschat                        0.2.24
fastapi                       0.99.1
unstructured                  0.10.4
unstructured-inference        0.5.14
spacy                         3.6.1

**Comment by liunux4odoo** [comment]
本项目代码是在3.8-3.10上测试的，尽量选择这几个版本。

**Comment by glide-the** [comment]
目前0.2版本的 分词器依赖unstructured
出现函数不存在入参的错误后
```
partition() got an unexpected keyword argument 'autodetect_encoding'
```
尝试使用下面命令修复这个错误
```
pip install unstructured==0.9.0 unstructured-inference==0.5.7

```

**Comment by chenhongwu127** [comment]
初始化知识库时报错：TypeError: Pooling.__init__() got an unexpected keyword argument '_name_or_path'，请教大佬们~
