### ISSUE TITLE
上传文件 报403

### ISSUE THREAD

**Issue by bubble666666** [chatchat-space/Langchain-Chatchat#1174]
![d7587e559db2cdd80edc097a1093b7e](https://github.com/chatchat-space/Langchain-Chatchat/assets/142568374/68941ca8-6676-467e-9062-0a885466a5d3)
AxiosError: Request failed with status code 403

**Comment by liunux4odoo** [comment]
这个看起来像是streamlit的问题，你的webui有使用反向代理一类的吗？

自己写一个简单的streamlite脚本试试文件上传功能是否正常？

**Comment by Gzj369** [comment]
@bubble666666 我使用iFrame把Langchain原始页面A嵌入到另一个前端页面B时，结果上传文件到知识库时也提示403，当我直接上传文件到Langchain原始页面A时，没有出错

**Comment by leoterry-ulrica** [comment]
> @bubble666666 我使用iFrame把Langchain原始页面A嵌入到另一个前端页面B时，结果上传文件到知识库时也提示403，当我直接上传文件到Langchain原始页面A时，没有出错

解决了没？

**Comment by Gzj369** [comment]
> > @bubble666666 我使用iFrame把Langchain原始页面A嵌入到另一个前端页面B时，结果上传文件到知识库时也提示403，当我直接上传文件到Langchain原始页面A时，没有出错
> 
> 解决了没？

还没有解决

**Comment by heidongqilin** [comment]
我使用老版本streamlit就没这个问题了。用的1.26

**Comment by Gzj369** [comment]
> 我使用老版本streamlit就没这个问题了。用的1.26

好的，感谢大佬！

**Comment by zhang-zzq** [comment]
> @bubble666666我使用iFrame把Langchain原始页面A嵌入到另一个前端B时，结果上传文件到知识库时也提示403，当我直接上传文件到Langchain原始页面A时，没有错误

请问是怎么解决的

**Comment by JinCheng666** [comment]
https://discuss.streamlit.io/t/file-uploader-403-error-when-embedding-streamlit-app-in-iframe/24109
启动时加上额外指令即可
streamlit run my_app.py --server.enableXsrfProtection=false

**Comment by Gzj369** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件我已经收到。看到后我一定会在第一时间内阅读并回复您。
