### ISSUE TITLE
[FEATURE] 0.2.0版本如何自定义知识库文档切分方式？

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1175]
0.2.0版本在做文档切分时，用的还是langchain.text_splitter吗？项目本身的这三个text_splitter没有用到吗？如果想自定义知识库文档的切分方式，应该如何修改呢？
![21040b82401add5f2b6f830fec7f52b](https://github.com/chatchat-space/Langchain-Chatchat/assets/52522880/06fe05d3-fb02-4f3c-b20d-94f4fbd5142d)

**Comment by ilovesouthpark** [comment]
用的是spacy了，也想知道怎么才能调用这其中的第一和第二个进行切分。

**Comment by roki1031** [comment]
> 用的是spacy了，也想知道怎么才能调用这其中的第一和第二个进行切分。

可以告诉我这段切分的代码在哪找吗？

**Comment by bk007lz** [comment]
同求如何自定义分割文本

**Comment by mandino83** [comment]
在Langchain-Chatchat-master/server/knowledge_base/utils.py文件中的file2text函数，请参考

   def file2text(self, using_zh_title_enhance=ZH_TITLE_ENHANCE):
        print("file2text:", self.document_loader_name, "text_splitter_name: ", self.text_splitter_name)
        try:
            document_loaders_module = importlib.import_module('langchain.document_loaders')
            DocumentLoader = getattr(document_loaders_module, self.document_loader_name)
        except Exception as e:
            print("file2text Exception:",e)
            document_loaders_module = importlib.import_module('langchain.document_loaders')
            DocumentLoader = getattr(document_loaders_module, "UnstructuredFileLoader")
        # if self.document_loader_name == "UnstructuredFileLoader":
        #     loader = DocumentLoader(self.filepath, autodetect_encoding=True)
        # else:
        #     loader = DocumentLoader(self.filepath)
        #
        # try:
        #     if self.text_splitter_name is None:
        #         print("text_splitter_name None")
        #         text_splitter_module = importlib.import_module('langchain.text_splitter')
        #         TextSplitter = getattr(text_splitter_module, "SpacyTextSplitter")
        #         text_splitter = TextSplitter(
        #             pipeline="zh_core_web_sm",
        #             chunk_size=CHUNK_SIZE,
        #             chunk_overlap=OVERLAP_SIZE,
        #         )
        #     else:
        #         print("text_splitter_name not None：", self.text_splitter_name)
        #         text_splitter_module = importlib.import_module('langchain.text_splitter')
        #         TextSplitter = getattr(text_splitter_module, self.text_splitter_name)
        #         text_splitter = TextSplitter(
        #             chunk_size=CHUNK_SIZE,
        #             chunk_overlap=OVERLAP_SIZE)
        # except Exception as e:
        #     print("file2text Exception2:", e)
        #     text_splitter_module = importlib.import_module('langchain.text_splitter')
        #     TextSplitter = getattr(text_splitter_module, "CharacterTextSplitter")
        #     text_splitter = TextSplitter(
        #         separator="**********",
        #         chunk_size=CHUNK_SIZE,
        #         chunk_overlap=OVERLAP_SIZE
        #     )

        loader = TextLoader(self.filepath, "utf-8")
        text_splitter = CharacterTextSplitter(
            separator="##########",
            chunk_size=100,
            chunk_overlap=0,
            length_function=len,
        )

        # docs = loader.load_and_split(text_splitter)
        pages = loader.load_and_split()
        docs= text_splitter.split_documents(pages)

        # print("file2text docs:",docs[0])
        for item in docs:
            print("file2text docs:", item)
            print("*************")
        if using_zh_title_enhance:
            docs = zh_title_enhance(docs)
        return docs

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码已经支持自定义分词器用于切割，请更新最新代码
