### ISSUE TITLE
分布式部署问题。 启动pyhton  /server/api.py

### ISSUE THREAD

**Issue by wgq910668** [chatchat-space/Langchain-Chatchat#1176]
现在我有2台 V100 的单卡linux服务器，每台机器都部署了单独的服务，使用nginx做负载均衡，使用了A机器上传文件之后，访问B机器之后，无法访问。
环境：
2台V100 GPU 数据库：Milvus 经过排查，每次上传文件之后，都会操作knowledge_base/info.db文件。这样就降低的并发能力。这个问题如何解决呢？

**Comment by imClumsyPanda** [comment]
可以在model_config中将SQLALCHEMY_DATABASE_URI修改为其他类型数据库，项目中数据库操作使用sqlalchemy，理论上可支持常见的各类数据库。

**Comment by Crescentz** [comment]
请问怎么做的负载均衡
