### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ly40** [chatchat-space/Langchain-Chatchat#118]
运行后 第一步加载配置一直报错：
Expecting value: line 1 column 1 (char 0)

不懂什么原因了，麻烦帮忙看下。

在命令行下运行demo是没问题的。

**Comment by huangjiaheng** [comment]
> 运行后 第一步加载配置一直报错： Expecting value: line 1 column 1 (char 0)
> 
> 不懂什么原因了，麻烦帮忙看下。
> 
> 在命令行下运行demo是没问题的。

模型路径可能不对

**Comment by ly40** [comment]
> 看样子大家都一样

bug webui bug还是比较多的。可能环境不同。再多调一下。

**Comment by ly40** [comment]
> 

换了模型，又转了lib等包，配置这一步过了，文件加载又卡住了。一样的报错。

**Comment by winie-hy** [comment]
同，有解决的吗。

**Comment by waveboy800** [comment]
我也是一样的报错，哎。

**Comment by jaccborn** [comment]
server_name 改成本机ip 再试试

**Comment by BKDragon** [comment]
遇到了相同的问题，解决方法：关掉代理。

**Comment by NotToday** [comment]
If you can't close your proxy, you can add this code in web_ui.py

`os.environ['no_proxy'] = '127.0.0.1,localhost'`

**Comment by fhybz** [comment]
我也是一样的问题关掉代理重启就好了

**Comment by jaccborn** [comment]
您好 实名认证请联系所属地市旅游局单位管理员(具体联系人我这边也不清楚，请您咨询一下)

**Comment by dyeeee** [comment]
关掉VPN重启即可

**Comment by jaccborn** [comment]
您好 实名认证请联系所属地市旅游局单位管理员(具体联系人我这边也不清楚，请您咨询一下)

**Comment by fhybz** [comment]
请问我有哪些地方不需要实名认证的吗？我在github上也没有看见哪里必须实名认证



---Original---
From: ***@***.***&gt;
Date: Sat, Jul 15, 2023 21:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [imClumsyPanda/langchain-ChatGLM] Expecting value: line 1 column1 (char 0) (Issue #118)




 您好 实名认证请联系所属地市旅游局单位管理员(具体联系人我这边也不清楚，请您咨询一下)

**Comment by xiaopeipeiya123** [comment]
关掉代理

**Comment by jaccborn** [comment]
您好 实名认证请联系所属地市旅游局单位管理员(具体联系人我这边也不清楚，请您咨询一下)
