### ISSUE TITLE
新版本中 知识库问答报错 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Leekinxun** [chatchat-space/Langchain-Chatchat#1182]
新建知识库报错：sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: knowledge_base

**Comment by liunux4odoo** [comment]
请按照部署文档要求，先初始化知识库:`python init_database.py --recreate-vs`
