### ISSUE TITLE
[BUG] 项目交流群无法加入 / 项目交流群已超过200人，需要邀请才能加入

### ISSUE THREAD

**Issue by redcat789** [chatchat-space/Langchain-Chatchat#1185]
是否可以拉我进群

**Comment by scut2sjtu** [comment]
+1

**Comment by JobsLee0** [comment]
+1

**Comment by imClumsyPanda** [comment]
已更新readme中二维码

**Comment by budian** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11451878/b1359656-31b0-46b4-879f-76783a07cc7e)

readme的二维码看不了诶
