### ISSUE TITLE
建议更换AG Grid组件

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#1188]
知识库管理中有个文件列表组件：AG GRID，一开始进去的时候会显示几秒钟的试用字眼：...trial...，建议更换成全开源的组件，或者没有试用字眼的组件。

**Comment by liunux4odoo** [comment]
使用AGGrid是为了能与用户选择知识库或文档进行交互，有什么合适的替代组件推荐吗？

**Comment by leoterry-ulrica** [comment]
> 使用AGGrid是为了能与用户选择知识库或文档进行交互，有什么合适的替代组件推荐吗？

第一个版本的Langchain-ChatGLM里面的文件列表组件可以复用吗？如果可以就行。
