### ISSUE TITLE
[BUG] 多卡，或指定卡启动都不生效

### ISSUE THREAD

**Issue by mumuszhang** [chatchat-space/Langchain-Chatchat#1192]
使用 python startup.py --all-webui 执行

模型是 baichuan-13B-chat

配置gpus不生效，无论是配4个，还是指定卡，一直用的是第一张卡

<img width="486" alt="企业微信20230822-134001@2x" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/13376020/0ddaa3cd-5d74-4a30-b352-fdb2518e495d">

![企业微信20230822-134017](https://github.com/chatchat-space/Langchain-Chatchat/assets/13376020/fd07d7b8-a6ae-42f9-be16-5cadd1dc0b13)

**Comment by mumuszhang** [comment]
试了下，server_config配置和startup文件create_model_worker_app函数配置同时修改一致就生效了

**Comment by coopot** [comment]
LLM_MODEL: {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # todo: 多卡加载需要配置的参数
        "gpus": "1", # 使用的GPU，以str的格式指定，如"0,1"
        "num_gpus": 1, # 使用GPU的数量
        # 以下为非常用参数，可根据需要配置
         "max_gpu_memory": "20GiB", # 每个GPU占用的最大显存
         
         
         
         指定第二张显卡加载无效，始终加载到第0张
