### ISSUE TITLE
我用fastAPI的/chat/knowledge_base_chat 回复的不准确或漏字

### ISSUE THREAD

**Issue by xuyaokun** [chatchat-space/Langchain-Chatchat#1194]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/e43fe689-7354-46a3-9f0c-1a167b22e824)
 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/8eb83fd1-6447-4b4e-bcca-733edc068998)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/b1ac9ca6-f9ff-472e-9bcf-f4fad088c81f)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/5b9e319f-0c06-4af8-816d-e472f5d54a29)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/3113f536-9e2c-42ae-8b34-8aa54b5a300b)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/a2fcb9ac-8611-4588-a88d-7fd9c00a950a)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/30c13b92-ec8b-468f-8e58-5eba6e46d341)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/9da98035-2e34-488e-91f0-d05dfc77532e)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/2d9ec847-8146-443f-861a-b50e607c6b68)

有没有遇到这种情况的，只有偶尔能回答正确，大部分都不准确或漏字掉字，愁人、着急！！

**Comment by xuyaokun** [comment]
客户端请求如下：

/chat/knowledge_base_chat

{
  "query": "老许入职时间是哪年?",
  "knowledge_base_name": "jianjie",
  "top_k": 3,
  "history": [],
  "stream": true
}

**Comment by vip68** [comment]
同样，经常发生问答不准的情况

**Comment by xuyaokun** [comment]
我快疯了，老板催着要，回答错的太离谱了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月22日(星期二) 下午5:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] 我用fastAPI的/chat/knowledge_base_chat 回复的不准确或漏字 (Issue #1194)





 
同样，经常发生问答不准的情况

**Comment by liunux4odoo** [comment]
> 客户端请求如下：
> 
> /chat/knowledge_base_chat
> 
> { "query": "老许入职时间是哪年?", "knowledge_base_name": "jianjie", "top_k": 3, "history": [], "stream": true }

方便提供一下知识库对应txt文件的内容吗？我来测试一下

**Comment by xuyaokun** [comment]
可以的。就一句测试的文字


上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月23日(星期三) 上午9:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] 我用fastAPI的/chat/knowledge_base_chat 回复的不准确或漏字 (Issue #1194)





  
客户端请求如下：
 
/chat/knowledge_base_chat
 
{ "query": "老许入职时间是哪年?", "knowledge_base_name": "jianjie", "top_k": 3, "history": [], "stream": true }
  
方便提供一下知识库对应txt文件的内容吗？我来测试一下

**Comment by xuyaokun** [comment]
> 就下面2句测试的文字


上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月

**Comment by liunux4odoo** [comment]
> > 就下面2句测试的文字
> 
> 上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月

你用的什么模型？我这边用chatglm2测了没有问题：


|  |  |
|--|--|
|<div style="background-color:#DCFDC8">User</div>|<div style="background-color:#DCFDC8">老许的入职时间是？</div>|
|<div style="background-color:#E0F7FA">AI</div>|<div style="background-color:#E0F7FA">根据已知信息，老许的入职时间是 2019 年 2 月。</div><br><br><div style="background-color:#E0F7FA">出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt) <br><br>上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。<br><br>老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月<br><br></div>|
|<div style="background-color:#DCFDC8">User</div>|<div style="background-color:#DCFDC8">老许入职时间是哪年？</div>|
|<div style="background-color:#E0F7FA">AI</div>|<div style="background-color:#E0F7FA">根据已知信息，老许的入职时间是 2019 年。</div><br><br><div style="background-color:#E0F7FA">出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt) <br><br>上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。<br><br>老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月<br><br></div>|
|<div style="background-color:#DCFDC8">User</div>|<div style="background-color:#DCFDC8">老许入职时间是哪年？</div>|
|<div style="background-color:#E0F7FA">AI</div>|<div style="background-color:#E0F7FA">老许入职时间是 2019 年。</div><br><br><div style="background-color:#E0F7FA">出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt) <br><br>上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。<br><br>老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月<br><br></div>|
|<div style="background-color:#DCFDC8">User</div>|<div style="background-color:#DCFDC8">老许入职时间是哪年？</div>|
|<div style="background-color:#E0F7FA">AI</div>|<div style="background-color:#E0F7FA">老许入职时间是 2019 年。</div><br><br><div style="background-color:#E0F7FA">出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt) <br><br>上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。<br><br>老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月<br><br></div>|

**Comment by xuyaokun** [comment]
> > > 就下面2句测试的文字
> > 
> > 
> > 上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月
> 
> 你用的什么模型？我这边用chatglm2测了没有问题：
> 
> User
> 老许的入职时间是？
> AI
> 根据已知信息，老许的入职时间是 2019 年 2 月。
> 
> 
> 出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt)
> 
> 上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。
> 
> 老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月
> 
> User
> 老许入职时间是哪年？
> AI
> 根据已知信息，老许的入职时间是 2019 年。
> 
> 
> 出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt)
> 
> 上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。
> 
> 老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月
> 
> User
> 老许入职时间是哪年？
> AI
> 老许入职时间是 2019 年。
> 
> 
> 出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt)
> 
> 上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。
> 
> 老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月
> 
> User
> 老许入职时间是哪年？
> AI
> 老许入职时间是 2019 年。
> 
> 
> 出处 [1] [test.txt](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=kbtest&file_name=test.txt)
> 
> 上海特威网络科技有限公司成立于2004年2月16日，公司员工29人。
> 
> 老许入职时间是2019年2月，蔡蔡入职时间2010年9月，张凤凤入职时间2010年3月

用的是：LLM_MODEL = "chatglm2-6b" ， EMBEDDING_MODEL = "m3e-base"

**Comment by liunux4odoo** [comment]
> 用的是：LLM_MODEL = "chatglm2-6b" ， EMBEDDING_MODEL = "m3e-base"

那真奇怪了。看起来不像代码错误，更像是LLM模型回答不对劲。

**Comment by xuyaokun** [comment]
> > 用的是：LLM_MODEL = "chatglm2-6b" ， EMBEDDING_MODEL = "m3e-base"
> 
> 那真奇怪了。看起来不像代码错误，更像是LLM模型回答不对劲。

我重新安装最新版，重头再试，如果还有问题再麻烦您 ，谢谢了！！

**Comment by xuyaokun** [comment]
> > 用的是：LLM_MODEL = "chatglm2-6b" ， EMBEDDING_MODEL = "m3e-base"
> 
> 那真奇怪了。看起来不像代码错误，更像是LLM模型回答不对劲。

我重装了下，在webui网页中（知识库）回答都对的，但是api.py问就不全对了，时好时坏。这种差异是什么情况呢？

我看了下webui的提交到一个网址的。这个有没有接口像api那样接入的

**Comment by mf22221111** [comment]
我的更离谱了 我用花生壳做了个接口的内网穿透 然后发送请求 根本不回复 answer直接是空的 然后然后 docs倒是右

**Comment by mf22221111** [comment]
怎么办啊 大佬们

**Comment by xuyaokun** [comment]
> 

你环境看下都支持吧，还有要先初始化数据表（python init_database.py --recreate-vs），启动 python server/llm_api.py  , python server/api.py

**Comment by imClumsyPanda** [comment]
不确定是否与api的测试工具有关，建议在api的docs中直接进行测试查看结果。

**Comment by liunux4odoo** [comment]
> > > 用的是：LLM_MODEL = "chatglm2-6b" ， EMBEDDING_MODEL = "m3e-base"
> > 
> > 
> > 那真奇怪了。看起来不像代码错误，更像是LLM模型回答不对劲。
> 
> 我重装了下，在webui网页中（知识库）回答都对的，但是api.py问就不全对了，时好时坏。这种差异是什么情况呢？
> 
> 我看了下webui的提交到一个网址的。这个有没有接口像api那样接入的

不太可能，webui也是调用的api.py的接口。多半是你测试工具的问题。

**Comment by chenhongwu127** [comment]
客户端请求如下：

/chat/knowledge_base_chat

{
"query": "老许入职时间是哪年?",
"knowledge_base_name": "jianjie",
"top_k": 3,
"history": [],
}
我这边是没有任何回复，只显示Connected to http://172.16.104.51:7861/chat/knowledge_base_chat，咋回事呢？
