### ISSUE TITLE
[BUG] 无法调用chatgpt

### ISSUE THREAD

**Issue by Merenguelkl** [chatchat-space/Langchain-Chatchat#1195]
配置chatgpt api并更改LLM_MODEL = "gpt-3.5-turbo"之后无法正常生成回复。

挂了代理，出现报错信息：
`2023-08-22 15:40:11,734 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 502 Bad Gateway"`

**Comment by Merenguelkl** [comment]
需要在哪里配置代理信息吗

**Comment by liunux4odoo** [comment]
贴一下你llm_model_dict中gpt-3.5-turbo的配置项。

看起来你的配置有问题，LLM_MODEL = "gpt-3.5-turbo"时，api_base_url必须使用openai的地址

**Comment by leexk312** [comment]
我也是这样 我的配置如下
![370b4927c9c17f6efa244ffbe03266b](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/54b5b5ae-5d37-45b2-9a5e-08dabc13d726)

**Comment by Merenguelkl** [comment]
这是我的配置
![WX20230823-145831@2x](https://github.com/chatchat-space/Langchain-Chatchat/assets/48408706/25289dcc-4a1b-4290-ad5b-8a5b86c3b936)

运行时依次运行
`python server/llm_api.py` 
`python server/api.py `
`streamlit run webui.py'`

本地模型可以正常调用，但是chatgpt不行

机器是MacBook m1 pro

**Comment by Merenguelkl** [comment]
> 贴一下你llm_model_dict中gpt-3.5-turbo的配置项。
> 
> 看起来你的配置有问题，LLM_MODEL = "gpt-3.5-turbo"时，api_base_url必须使用openai的地址

这是我的配置
![WX20230823-145831@2x](https://github.com/chatchat-space/Langchain-Chatchat/assets/48408706/25289dcc-4a1b-4290-ad5b-8a5b86c3b936)

运行时依次运行
`python server/llm_api.py` 
`python server/api.py `
`streamlit run webui.py'`

本地模型可以正常调用，但是chatgpt不行

机器是MacBook m1 pro

**Comment by liunux4odoo** [comment]
这多半不是本项目的问题，可能是网络的问题。

**Comment by Merenguelkl** [comment]
> 这多半不是本项目的问题，可能是网络的问题。

仔细看了一下报错信息，是在运行`python server/llm_api.py`后出现的报错

![WX20230823-152533@2x](https://github.com/chatchat-space/Langchain-Chatchat/assets/48408706/5b1e14ec-b26a-4e16-b257-ecf1246102b4)

**Comment by leexk312** [comment]
gpt是不用启动llm_api 只需要api 和webui 但是我只启动这两个也会出现这个问题

**Comment by Canyao45** [comment]
解决了吗我也报这个错误了

**Comment by leexk312** [comment]
> 

我测试了一下 应该是bug 因为连接gpt必须要vpn但是用了vpn这个框架就会有些问题 如果用国内代理的gpt就可以正常使用，但是收费很高

**Comment by liunux4odoo** [comment]
新版代码已经修复了这个问题，可以在configs.model_config.llm_model_dict中为chatgpt设置代理。即将发布，敬请期待。

**Comment by glide-the** [comment]
可以尝试使用新版本代码https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example#L71
或者使用OPENAI_PROXY环境变量配置http代理

**Comment by Duyz232** [comment]
您解决了吗？我也遇到了这个问题

**Comment by Duyz232** [comment]
> 新版代码已经修复了这个问题，可以在configs.model_config.llm_model_dict中为chatgpt设置代理。即将发布，敬请期待。

我测试了0.2.2似乎还是有这个问题，以下是我的configs.model_config.llm_model_dic
<img width="759" alt="cded897eb2b4f3cf3ffa15fb09b1b6c" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/b5701bec-462c-4617-80c3-cee71f3d22b0">
<img width="969" alt="8a519d75f0dc00037bd4243ba86de7f" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/b4617aed-1115-4c67-b81d-0a876bf0f249">

**Comment by Merenguelkl** [comment]
> > 新版代码已经修复了这个问题，可以在configs.model_config.llm_model_dict中为chatgpt设置代理。即将发布，敬请期待。
> 
> 我测试了0.2.2似乎还是有这个问题，以下是我的configs.model_config.llm_model_dic <img alt="cded897eb2b4f3cf3ffa15fb09b1b6c" width="759" src="https://user-images.githubusercontent.com/110820271/264043439-b5701bec-462c-4617-80c3-cee71f3d22b0.png"> <img alt="8a519d75f0dc00037bd4243ba86de7f" width="969" src="https://user-images.githubusercontent.com/110820271/264043641-b4617aed-1115-4c67-b81d-0a876bf0f249.png">

我通过新版本代码并配置代理信息解决这个问题了。

我的经验是代理vpn不要开全局模式，全局模式还是会报错。只开成规则模式就可以用了。

**Comment by Duyz232** [comment]
非常感谢您的回复。改成规则模式后好像是可以：
<img width="1069" alt="9b27cbd21423583376fb773a5bf18be" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/a5a834b2-b438-43c1-a105-ad7646b9f05b">
