### ISSUE TITLE
使用知识库造成报错

### ISSUE THREAD

**Issue by mf22221111** [chatchat-space/Langchain-Chatchat#1196]
**问题描述 / Problem Description**
使用知识库的时候 发送信息，造成了报错

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / 

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/85787104/ebd7b3ef-7b61-4e8f-8745-e8578a11036b)
peer closed connection without sending complete message body (incomplete chunked read)
File "D:\ProgramData\anaconda3\envs\mf\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
File "C:\Users\Administrator\Desktop\Langchain-Chatchat-master\webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
File "C:\Users\Administrator\Desktop\Langchain-Chatchat-master\webui_pages\dialogue\dialogue.py", line 117, in dialogue_page
    text += d["answer"]
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): milvus
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by bubble666666** [comment]
我也遇到了这个错误 看源码报错是 errorMsg

**Comment by kento996** [comment]
好巧，我也是遇到了这样的问题

**Comment by mf22221111** [comment]
看了这个https://github.com/chatchat-space/Langchain-Chatchat/issues/1159 issue我发现应该就是milvs的事 我是用milvus生成的链接，然后报的错，如果不生成链接就不会报错

**Comment by zqt996** [comment]
新加修改代码的可以试一试

**Comment by GXKIM** [comment]
> 好巧，我也是遇到了这样的问题

+1

**Comment by mf22221111** [comment]
换了最新的代码 解决了

**Comment by GXKIM** [comment]
> 换了最新的代码 解决了

我还是报错

**Comment by anfernees-iphone** [comment]
还是报错啊

**Comment by pen-ho** [comment]
还是 报错哦

**Comment by xxWeiDG** [comment]
不太懂这个是怎么触发的

**Comment by zzflybird** [comment]
我也遇到了这个问题，在生成代码的时候，代码比较多，没回答完整，我回复“继续”让LLM继续回答就报这个错误了。
