### ISSUE TITLE
[BUG] 本地模型，联网可以使用，离线超时

### ISSUE THREAD

**Issue by brealisty** [chatchat-space/Langchain-Chatchat#1197]
**问题描述 / Problem Description**
本地模型chatglm2-6b-int4，联网没有任何问题，断开网络一直重试，知道超时
`
INFO:     Waiting for connections to close. (CTRL+C to force quit)
2023-08-22 16:28:35,091 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
2023-08-22 16:28:39,087 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
`
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12651762/f00480f5-bc25-4c23-9b75-a4c1ac48c710)

**复现问题的步骤 / Steps to Reproduce**
1. 执行  python llm_api.py    python api.py    streamlit python webui.py

2. 调试api.py文件，问题出现在server/caht/chat.py 51行
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12651762/8aca488e-d0f9-4fb6-9f4b-4c57decef06d)

3. 模型配置
`
llm_model_dict = {
    "chatglm2-6b-int4": {
        "local_model_path": "path\to\model\Langchain-Chatchat\models\chatglm-6b",
        "api_base_url": "http://localhost:8888/v1",  # URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
    }
}

# LLM 名称
LLM_MODEL = "chatglm2-6b-int4"
`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.0 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B-int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： text2vec-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version:  3.10

**Comment by HongchaoSu** [comment]
同样问题

**Comment by brealisty** [comment]
> 同样问题

老哥，你解决了吗？

**Comment by brealisty** [comment]
经过多番测试发现，不是必须联网，而是网卡必须被占用（大概是这个意思，比如我用的笔记本电脑，连接手机热点或者有线网卡），即便没有互联网，也能够使用。然后想起来，localhost和127好像和这个有关联，因此将configs中的localhost都改为127，这个问题就可以解决了。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12651762/cf474a51-d3ff-4149-988d-636c245d8d2c)

**Comment by Andrewlilei** [comment]
https://blog.csdn.net/bandaoyu/article/details/87259631
这里讲了 localhost和 127.0.0.1的区别

**Comment by zhuhaifengaaa** [comment]
我试了一下，不行啊
