### ISSUE TITLE
这是什么错误，在Colab上运行的。

### ISSUE THREAD

**Issue by KYKY548** [chatchat-space/Langchain-Chatchat#120]
libcuda.so.1: cannot open shared object file: No such file or directory
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
libcuda.so.1: cannot open sha
<img width="901" alt="图1" src="https://user-images.githubusercontent.com/119725802/232573693-93d08ee7-ee21-4f27-a112-cbdf3b2f9cb2.png">
red object file: No such file or directory

**Comment by imClumsyPanda** [comment]
看起来像cuda驱动安装问题

**Comment by gdchaochao** [comment]
你是说这个错误吗
libcuda.so.1: cannot open shared object file: No such file or directory
这个错误安装就好yum install mesa-libGL
