### ISSUE TITLE
[BUG] `ChatPromptTemplate.from_messages()`读取数据时存在问题

### ISSUE THREAD

**Issue by cingtiye** [chatchat-space/Langchain-Chatchat#1201]
下面的代码中，会把`{input}`看成输入变量，用`query`赋值给`{input}`。但是在实际过程中，`history`中也可能出现类似`{input}`的内容，比如`{text}`。程序会把其也当作变量，从而导致程序运行出错。

```python
  chat_prompt = ChatPromptTemplate.from_messages(
      [i.to_msg_tuple() for i in history] + [("human", "{input}")])

  task = asyncio.create_task(wrap_done(
      chain.acall({"input": query}),
      callback.done),
  )
```

**Comment by liunux4odoo** [comment]
Duplicate of #1142 

该问题已经在开发版中修复，请关注项目版本升级信息，或者可以拉取pre-release分支代码提前体验测试。

该issue先关闭，如测试中发现问题可以重开。

**Comment by liunux4odoo** [comment]
Duplicate of #1142

**Comment by cingtiye** [comment]
> 该问题已经在开发版中修复，请关注项目版本升级信息，或者可以拉取pre-release分支代码提前体验测试。
> 
> 该issue先关闭，如测试中发现问题可以重开。

你好~我拉取了pre-release分支代码，发现也还是不行。

**Comment by liunux4odoo** [comment]
pre-release还没合并，你先拉取dev分支试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月23日(星期三) 中午11:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] [BUG] `ChatPromptTemplate.from_messages()`读取数据时存在问题 (Issue #1201)





  
该问题已经在开发版中修复，请关注项目版本升级信息，或者可以拉取pre-release分支代码提前体验测试。
 
该issue先关闭，如测试中发现问题可以重开。
  
你好~我拉取了pre-release分支代码，发现也还是不行。
