### ISSUE TITLE
ModuleNotFoundError: No module named 'configs.model_config'

### ISSUE THREAD

**Issue by Heckler-Dark** [chatchat-space/Langchain-Chatchat#1202]
执行命令：知识库初始化与迁移
python init_database.py --recreate-vs

报错结果：
Traceback (most recent call last):
  File "D:\LLM\langchain-ChatGLM\init_database.py", line 1, in <module>
    from server.knowledge_base.migrate import create_tables, folder2db, recreate_all_vs, list_kbs_from_folder
  File "D:\LLM\langchain-ChatGLM\server\knowledge_base\migrate.py", line 1, in <module>
    from configs.model_config import EMBEDDING_MODEL, DEFAULT_VS_TYPE
  File "D:\LLM\langchain-ChatGLM\configs\__init__.py", line 1, in <module>
    from .model_config import *
ModuleNotFoundError: No module named 'configs.model_config'

**Comment by Pickupppp** [comment]
cofigs目录下面有配置文件，你按照README修改文件名了吗

**Comment by Pickupppp** [comment]
> > cofigs目录下面有配置文件，你按照README修改文件名了吗
> 
> 它貌似已经更改过了，里面的内容和提供复制的也是一样的。

我的意思不是修改文件里面的内容，是把 model_config.py.example 修改成 model_config.py ，或者复制一份，并重命名为 model_config.py

**Comment by Heckler-Dark** [comment]
> > > cofigs目录下面有配置文件，你按照README修改文件名了吗
> > 
> > 
> > 它貌似已经更改过了，里面的内容和提供复制的也是一样的。
> 
> 我的意思不是修改文件里面的内容，是把 model_config.py.example 修改成 model_config.py ，或者复制一份，并重命名为 model_config.py

好的，谢谢
