### ISSUE TITLE
[BUG] web界面多轮对话，对话内容包含json字串就会报错 0.2.0版本

### ISSUE THREAD

**Issue by mandino83** [chatchat-space/Langchain-Chatchat#1204]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

web界面错误信息：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/10546388/86c5cf07-cb11-43f1-885c-1a22c1178471)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/10546388/804df517-9a4f-4dcf-8505-39c773e5698c)

服务端界面信息：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/10546388/a17cf47f-aad3-4a3f-9e58-caf87bebe17f)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/10546388/3e036d8d-32e7-47dc-918a-b0cb34cab623)

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
Duplicate of #1142

**Comment by liunux4odoo** [comment]
该问题已经在开发版中修复，请关注项目版本升级信息，也可以拉取pre-release或者dev分支代码提前体验测试，测试中遇到问题欢迎反馈。

**Comment by imClumsyPanda** [comment]
已在v0.2.2版本中解决该问题，请更新代码后再做测试。
