### ISSUE TITLE
如何自定义文档切分方式？

### ISSUE THREAD

**Issue by yyl424525** [chatchat-space/Langchain-Chatchat#1205]
我发现在使用默认的按文字长度切分文本块的方式，会导致某个知识会被切分到不同的文本块，最终喂给大模型的知识是不全的，导致回答的答案不尽人意。

如何自定义文档切分方式啊，比如我输入的是csv文件，我想一行文本为一个文本块。

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码已经支持自定义分词切割
