### ISSUE TITLE
[BUG] 将模型换成chatgpt时无法调用

### ISSUE THREAD

**Issue by leexk312** [chatchat-space/Langchain-Chatchat#1210]
调用gpt时先启用api.py 测试其中接口fastchat/chat时报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/48d3c7d1-e22c-4e50-8842-5c0a01663797)
测试chat/chat接口时报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/5b6c1109-89cd-4ce8-ac64-1edb700e09fe)
补充说明
使用本地模型完全正常
使用了代理 可以网页访问chatgpt
同时通过如下代码测试openai连接也正常回复
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/bab3877b-6ac4-453e-aaf2-72953b854e73)
我的config如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102641705/63016c39-ba79-4181-b9c4-a7827b210cd2)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：2.0.1
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatgpt
- 操作系统及版本 / Operating system and version:win11
- Python 版本 / Python version:3.8.1和3.10都报错

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
请更新至v0.2.2正式版后，再次测试是否仍有该问题，如果还存在可尝试对openai_proxy进行设置。

**Comment by KDQD** [comment]
> 请更新至v0.2.2正式版后，再次测试是否仍有该问题，如果还存在可尝试对openai_proxy进行设置。

环境变量中也对openai_proxy进行设置了，可是还是会报一样的错误

**Comment by Duyz232** [comment]
相同的错，加一

**Comment by leexk312** [comment]
我成功了 具体要设置openai_proxy 然后运行时也要开启代理

**Comment by Duyz232** [comment]
> 我成功了 具体要设置openai_proxy 然后运行时也要开启代理

麻烦问一下，是这样修改吗？
<img width="595" alt="30e6b49ab317c4dd0c54274460cca1a" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/47b76287-aa2d-4f3c-aacb-cecc89a1e5fa">
<img width="954" alt="0d0daa8366e36352e3118381a503cc8" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/110820271/c670313f-f335-4e96-b485-8f385fc4b116">

**Comment by leexk312** [comment]
> > 我成功了 具体要设置openai_proxy 然后运行时也要开启代理
> 
> 麻烦问一下，是这样修改吗？ <img alt="30e6b49ab317c4dd0c54274460cca1a" width="595" src="https://user-images.githubusercontent.com/110820271/263662930-47b76287-aa2d-4f3c-aacb-cecc89a1e5fa.png"> <img alt="0d0daa8366e36352e3118381a503cc8" width="954" src="https://user-images.githubusercontent.com/110820271/263662989-c670313f-f335-4e96-b485-8f385fc4b116.png">

你把os.en.....那些白色的代码去掉 只留key

**Comment by hh-hh19** [comment]
> 我成功了 具体要设置openai_proxy 然后运行时也要开启代理

请问具体如何查看自己的proxy呢？

**Comment by Duyz232** [comment]
一直报错：API通信超时，请确认已启动FastChat与API服务（详见RADME '5. 启动 API 服务或 Web UI'）
是不是自己找的，proxy不对呢
