### ISSUE TITLE
[BUG] bge模型的加载方式有问题

### ISSUE THREAD

**Issue by Peiyance** [chatchat-space/Langchain-Chatchat#1212]
bge官方repo里用的是HuggingFaceBgeEmbeddings， 里面有query_instruction的设置，但看起来这个库加载的时候直接用的是HuggingFaceEmbeddings，应该改为BGEembedding.  或者在界面注明输入查询的时候建议加上指令。

**Comment by imClumsyPanda** [comment]
已在 https://github.com/chatchat-space/Langchain-Chatchat/pull/1119 中解决，目前已汇入 dev 分支，将跟随下一版本发布。
