### ISSUE TITLE
项目介绍的不详细，哪位老哥能稍微详细介绍一下这个项目里面几个程序的关系吗？

### ISSUE THREAD

**Issue by zhuhaifengaaa** [chatchat-space/Langchain-Chatchat#1213]
**功能描述 / Feature Description**
项目介绍的不详细，跪求路过的老哥/前辈帮梳理一下思路。

**解决的问题 / Problem Solved**
需要运行的程序是这三个：python server/llm_api.py                python server/api.py        streamlit run webui.py
但是这几个什么关系啊？
llm_api.py 是启动模型？
api.py是启动前面启动模型的api，这个api是自己服务器本地的api？时刻准备好让别人调用是吗？
webui.py就是用来根据输入/调用模型api/输出结果的程序吗？

理解错了请大家指出来，顺便能详细介绍一下情况吗？
“小白”这厢有礼了，谢谢老哥们

**Comment by imClumsyPanda** [comment]
1. 使用 FastChat 提供开源 LLM 模型的 API，以 OpenAI API 接口形式接入，提升 LLM 模型加载效果，并支持近期新出的baichuan-inc/baichuan-7B、internlm/internlm-chat-7b、Qwen/Qwen-7B-Chat等模型；

2. 使用 langchain 中已有 Chain 的实现，便于后续接入不同类型 Chain，并将对 Agent 接入开展测试；

3. 使用 FastAPI 提供 API 服务，全部接口可在 FastAPI 自动生成的 docs 中开展测试，且所有对话接口支持通过参数设置流式或非流式输出；

4. 使用 Streamlit 提供 WebUI 服务，可选是否基于 API 服务启动 WebUI，后续可支持不同形式输出内容的显示；

**Comment by zhuhaifengaaa** [comment]
> 

谢谢老哥，请问 server/llm_api.py 、server/api.py 、webui.py这三个文件完整了什么功能呢

**Comment by zhuhaifengaaa** [comment]
> 1. 使用 FastChat 提供开源 LLM 模型的 API，以 OpenAI API 接口形式接入，提升 LLM 模型加载效果，并支持近期新出的baichuan-inc/baichuan-7B、internlm/internlm-chat-7b、Qwen/Qwen-7B-Chat等模型；
> 
> 2. 使用 langchain 中已有 Chain 的实现，便于后续接入不同类型 Chain，并将对 Agent 接入开展测试；
> 
> 3. 使用 FastAPI 提供 API 服务，全部接口可在 FastAPI 自动生成的 docs 中开展测试，且所有对话接口支持通过参数设置流式或非流式输出；
> 
> 4. 使用 Streamlit 提供 WebUI 服务，可选是否基于 API 服务启动 WebUI，后续可支持不同形式输出内容的显示；

**老哥，server/llm_api.py 、server/api.py 、webui.py这三个程序完成了原理图中的哪些环节呢？**

**原理图如下：**
<img width="603" alt="langchain+chatglm" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/50c350ae-bc75-4034-985b-0f3fd09a7272">

**Comment by roki1031** [comment]
同问

**Comment by imClumsyPanda** [comment]
> > 1. 使用 FastChat 提供开源 LLM 模型的 API，以 OpenAI API 接口形式接入，提升 LLM 模型加载效果，并支持近期新出的baichuan-inc/baichuan-7B、internlm/internlm-chat-7b、Qwen/Qwen-7B-Chat等模型；
> > 2. 使用 langchain 中已有 Chain 的实现，便于后续接入不同类型 Chain，并将对 Agent 接入开展测试；
> > 3. 使用 FastAPI 提供 API 服务，全部接口可在 FastAPI 自动生成的 docs 中开展测试，且所有对话接口支持通过参数设置流式或非流式输出；
> > 4. 使用 Streamlit 提供 WebUI 服务，可选是否基于 API 服务启动 WebUI，后续可支持不同形式输出内容的显示；
> 
> **老哥，这不是我想问的。我想请教一下，server/llm_api.py 、server/api.py 、webui.py这三个程序各自完成了原理图中的哪些环节呢？**
> 
> **原理图如下：** <img alt="langchain+chatglm" width="603" src="https://user-images.githubusercontent.com/69130513/262829449-50c350ae-bc75-4034-985b-0f3fd09a7272.png">

原理图是从程序执行的顺序上来介绍的，llm_api的作用是作为图中的llm提供对话服务，而原理图中完整流程都在api的chat/knowledge_base_chat中进行实现了，webui则是增加了交互后与api进行通信，以网页的形式完成配置项的选择与对话过程。

**Comment by zhuhaifengaaa** [comment]
> 



> > > 1. 使用 FastChat 提供开源 LLM 模型的 API，以 OpenAI API 接口形式接入，提升 LLM 模型加载效果，并支持近期新出的baichuan-inc/baichuan-7B、internlm/internlm-chat-7b、Qwen/Qwen-7B-Chat等模型；
> > > 2. 使用 langchain 中已有 Chain 的实现，便于后续接入不同类型 Chain，并将对 Agent 接入开展测试；
> > > 3. 使用 FastAPI 提供 API 服务，全部接口可在 FastAPI 自动生成的 docs 中开展测试，且所有对话接口支持通过参数设置流式或非流式输出；
> > > 4. 使用 Streamlit 提供 WebUI 服务，可选是否基于 API 服务启动 WebUI，后续可支持不同形式输出内容的显示；
> > 
> > 
> > **老哥，这不是我想问的。我想请教一下，server/llm_api.py 、server/api.py 、webui.py这三个程序各自完成了原理图中的哪些环节呢？**
> > **原理图如下：** <img alt="langchain+chatglm" width="603" src="https://user-images.githubusercontent.com/69130513/262829449-50c350ae-bc75-4034-985b-0f3fd09a7272.png">
> 
> 原理图是从程序执行的顺序上来介绍的，llm_api的作用是作为图中的llm提供对话服务，而原理图中完整流程都在api的chat/knowledge_base_chat中进行实现了，webui则是增加了交互后与api进行通信，以网页的形式完成配置项的选择与对话过程。

好的，多想老哥
