### ISSUE TITLE
关于文本切分问题

### ISSUE THREAD

**Issue by yanhl0** [chatchat-space/Langchain-Chatchat#1219]
目前text_splitter里有提到使用语义切分，用的是达摩的模型，如何指定使用达摩的语义切分，目前没有找到调用入口

**Comment by yanhl0** [comment]
> 

麻烦仔细说明一下，我有点不理解

**Comment by yanhl0** [comment]
> 得自己改代码，加载文件哪里分词方法换成模型分割

麻烦仔细说明一下，我有点不理解，谢谢

**Comment by huarong0906** [comment]
m

**Comment by imClumsyPanda** [comment]
当前版本默认使用的是spacy的textsplitter模型，如果缺少依赖会使用RecursiveCharacterTextSplitter，具体实现在server/knowledge_base/utils中KnowledgeFile类的file2text方法实现中。
