### ISSUE TITLE
租的gpu,Running on local URL:  http://0.0.0.0:7860  To create a public link, set `share=True` in `launch()`.  浏览器上访问不了？？？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#122]
(chatglm20230401) root@autodl-container-e82d11963c-10ece0d7:~/autodl-tmp/chatglm/langchain-ChatGLM-20230418# python3.9 webui.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:10<00:00,  1.28s/it]
No sentence-transformers model found with name /root/.cache/torch/sentence_transformers/GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
No sentence-transformers model found with name /root/.cache/torch/sentence_transformers/GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by imClumsyPanda** [comment]
Share=Ture, server_port=6006 改用 autodl 自定义服务访问

cristianohello ***@***.***>于2023年4月18日 周二11:40写道：

**Comment by blwaji** [comment]
是不是要用服务器的IP加端口，因为0.0.0.0是本机，指的是服务器，大概应该也许可能是这样

**Comment by zzl8023** [comment]
我也是autodl租用的服务器，请问这个问题最后解决了吗
