### ISSUE TITLE
[BUG] llm.api.py和api.py的url无法访问

### ISSUE THREAD

**Issue by lzw2000118** [chatchat-space/Langchain-Chatchat#1220]
我把这个项目部署在服务器上，为什么我的llm.api.py和api.py两个都正常启动了，最后产生的两个url在我本地电脑都打不开呢？

**Comment by zqt996** [comment]
啊这。。。。
有没有可能网不通

**Comment by imClumsyPanda** [comment]
如需远程访问api对应文档页面，需要在configs/server_config中把相应ip修改为“0.0.0.0”
