### ISSUE TITLE
[BUG] 上传文件报错'CSVLoader' object is not iterable  与 list index out of range

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/Langchain-Chatchat#1224]
**问题描述 / Problem Description**
最近git pull了只后，在上传csv时会报错'CSVLoader' object is not iterable，上传json会 list index out of range，ppt，pdf倒是正常

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.1
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): Qwen
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:乌班图
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by qihangf** [comment]
而且也没有报错信息，只有这两句话

**Comment by liunux4odoo** [comment]
感谢反馈。

已确认：

1. json文件向量化时报错：

`Detected a JSON file that does not conform to the Unstructured schema. partition_json currently only processes serialized Unstructured output.`

2. csv文件向量化时存在encoding问题。

我们会尽快检查修复。

**Comment by liunux4odoo** [comment]
开发版中已进行修复：

1. JSON文件已经可以正常向量化
2. 文本形式的PDF文件可以正常向量化，但扫描版PDF不行，会报`index out of range`错误，推测是PyPdf处理扫描PDF时报错。

**Comment by leoterry-ulrica** [comment]
> 开发版中已进行修复：
> 
> 1. JSON文件已经可以正常向量化
> 2. 文本形式的PDF文件可以正常向量化，但扫描版PDF不行，会报`index out of range`错误，推测是PyPdf处理扫描PDF时报错。

请问这个问题解决了吗？
