### ISSUE TITLE
[BUG] pg向量检索不准，输入知识库中没有的内容或者随便输入些东西必会出现出处，且结果不准

### ISSUE THREAD

**Issue by developservertwo** [chatchat-space/Langchain-Chatchat#1226]
**问题描述 ”
pg向量检索不准，输入知识库中没有的内容或者随便输入些东西必会出现出处，且结果不准

Langchain-Chatchat版本v0.2.0  commit 50c6369f46f67ab763e2abcd4f8197f403ba1252

**Comment by developservertwo** [comment]
使用faiss这无此问题，疑似相关度参数score_threshold只针对faiss

**Comment by developservertwo** [comment]
faiss相关代码
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/133831396/56463ebd-0a9a-4bd1-b920-ffd51a86c01b)
pg相关代码
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/133831396/add354c9-b966-4a3d-bfbe-990f0071a0b6)

**Comment by Pickupppp** [comment]
pq代码上面写了 `#todo: support score threshold` 就是这部分未来会做

> 使用faiss这无此问题，疑似相关度参数score_threshold只针对faiss

**Comment by zqt996** [comment]
周末处理
