### ISSUE TITLE
[BUG] No module named 'pydantic_v1'

### ISSUE THREAD

**Issue by RayYe586** [chatchat-space/Langchain-Chatchat#1231]
**问题描述 / Problem Description**
加载pdf报错：
INFO:     127.0.0.1:56842 - "POST /knowledge_base/delete_doc HTTP/1.1" 200 OK
UnstructuredFileLoader
No module named 'pydantic_v1'
No module named 'pydantic_v1'
’‘’
ipython：
In [1]: import pydantic_v1
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 import pydantic_v1

ModuleNotFoundError: No module named 'pydantic_v1'

In [2]: import pydantic

In [3]: exit
‘’‘
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：50c6369f46f67ab763e2abcd4f8197f403ba1252
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: ubuntu20
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
更新项目代码，按文档更新依赖，特别是unstructured。

**Comment by RayYe586** [comment]
这个是不是有bug，代码是最新的，req也-r安装的。也能找到pydanti库，但是没有pydanti_v1库，这个是不是不该调用v1的？

**Comment by liunux4odoo** [comment]
> 这个是不是有bug，代码是最新的，req也-r安装的。也能找到pydanti库，但是没有pydanti_v1库，这个是不是不该调用v1的？

你可以自己检查一下，最新版项目代码里没有任何导入`pydantic_v1`的地方，所以只能是某个依赖项的问题。

**Comment by OhMyGod32** [comment]
> > 这个是不是有bug，代码是最新的，req也-r安装的。也能找到pydanti库，但是没有pydanti_v1库，这个是不是不该调用v1的？
> 
> 你可以自己检查一下，最新版项目代码里没有任何导入`pydantic_v1`的地方，所以只能是某个依赖项的问题。

server\agent\weather.py 第23行“from langchain.pydantic_v1 import Extra, root_validator”就导入了，估计就是这个引起的
