### ISSUE TITLE
[BUG] 无法生成向量库

### ISSUE THREAD

**Issue by guowc** [chatchat-space/Langchain-Chatchat#1234]
**问题描述 / Problem Description**
不管是默认测试的test.txt，还是自己上传的pdf，都无法生成向量库，一点击添加到向量库，loading一秒钟消失就没反应了，知识库列表里也看不到新增的知识库
<img width="1086" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/11242226/25c64545-0c5a-4209-8d41-3b37d8cd7f2b">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: centos7.9
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by qiyer** [comment]
库的版本问题，之前也遇到了，把库都卸载了，重新安装就好了。
（通常是之前安装了老版本，后来升级最新版本，因为有些库的依赖问题，导致某些必须库的版本没有升级上来，还是老版本，就会出现上述问题）

**Comment by imClumsyPanda** [comment]
v0.1.x 和 v0.2.x 版本结构有大量调整，依赖包也有很大改变，因此在 README 开发部署章节中有提到，建议新建环境，重装全部依赖库后运行代码。

**Comment by liunux4odoo** [comment]
你这向量库也有问题，都没显示向量类型，嵌入模型也没显示，你configs里面两个配置文件都正确的吗。

**Comment by guowc** [comment]
我是全新安装的0.2的项目，找到问题了，配置里的路径要写绝对路径，问题已解决

**Comment by Gzj369** [comment]
> 我是全新安装的0.2的项目，找到问题了，配置里的路径要写绝对路径，问题已解决

我也遇到无法生成向量库的问题，请问您是在哪个配置里、修改了什么绝对路径解决的呢 @guowc
