### ISSUE TITLE
使用Llama2-Chinese-13b-Chat模型知识库问答报错

### ISSUE THREAD

**Issue by yanhl0** [chatchat-space/Langchain-Chatchat#1239]
**问题描述 / Problem Description**
message='OpenAI API response' path=http://localhost:8880/v1/chat/completions processing_ms=None request_id=None response_code=400
Caught exception: Invalid response object from API: '{"object":"error","message":"This model\'s maximum context length is 2048 tokens. However, you requested 2220 tokens (1708 in the messages, 512 in the completion). Please reduce the length of the messages or completion.","code":40303}' (HTTP response code was 400)

**复现问题的步骤 / Steps to Reproduce**
1. 配置LLM模型为Llama2-Chinese-13b-Chat，emmebdding为text2vec-large-chinese
2. 问答知识库

**Comment by yanhl0** [comment]
有些问题可以，有些问题报错

**Comment by yanhl0** [comment]
问题内容：XX是如何设计的。不到10个字

**Comment by liunux4odoo** [comment]
一是到http://localhost:8880/docs/里手动测试一下/v1/chat/completions接口。

二是降低history_len试试。
