### ISSUE TITLE
[BUG] 搜索引擎问答使用duckduckgo无结果返回，utils.py[line:214] - ERROR: 'Body' object is not iterabl

### ISSUE THREAD

**Issue by elven2016** [chatchat-space/Langchain-Chatchat#1240]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
使用duckduckgo搜索引擎搜索无返回
报错信息如下，看起来是消息模式解析问题
2023-08-25 14:59:10,149 - _client.py[line:1013] - INFO: HTTP Request: GET https://links.duckduckgo.com/d.js?q=%E6%9F%A5%E7%9C%8B%E4%B8%8B%E4%BB%8A%E5%A4%A9%E6%B7%B1%E5%9C%B3%E7%9A%84%E5%A4%A9%E6%B0%94&kl=wt-wt&l=wt-wt&s=0&df=y&vqd=4-77836614280161902370464272564858982006&o=json&sp=0&ex=-1 "HTTP/2 200 OK"
2023-08-25 14:59:10,150 - utils.py[line:214] - ERROR: 'Body' object is not iterable

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'  streamlit run webui.py
2. 点击 '...' / Click '...'  选择llm对话，
3. 滚动到 '...' / Scroll to '...'对话模式选择搜索引擎问答
4. 问题出现 / Problem occurs 对话框中输入：查看当前深圳的天气，无返回

**预期的结果 / Expected Result**  预期应该出现深圳天气的情况
描述应该出现的结果 / Describe the expected result. 

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
实际进行duckduckgo搜索后无法结果返回
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/16677082/49a9317d-5b32-4f04-b5dd-82e57b0052f5)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)  v0.2.2-preview
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: ubuntu22.04
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
请更新至0.2.2正式版后再测试下是否仍存在该问题。

**Comment by rdaim** [comment]
<img width="1253" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/38274819/3e921aa4-2e50-4eea-9274-3932e3b0e10a">
我也存在这个问题，搜索引擎有结果返回，但是对话没有内容

**Comment by imClumsyPanda** [comment]
> <img alt="image" width="1253" src="https://user-images.githubusercontent.com/38274819/263443044-3e921aa4-2e50-4eea-9274-3932e3b0e10a.png"> 我也存在这个问题，搜索引擎有结果返回，但是对话没有内容

按照截图信息，这应该属于对话有内容，但语言模型没理解上下文信息。可以尝试修改模型/提示词模版

**Comment by rdaim** [comment]
> > <img alt="image" width="1253" src="https://user-images.githubusercontent.com/38274819/263443044-3e921aa4-2e50-4eea-9274-3932e3b0e10a.png"> 我也存在这个问题，搜索引擎有结果返回，但是对话没有内容
> 
> 按照截图信息，这应该属于对话有内容，但语言模型没理解上下文信息。可以尝试修改模型/提示词模版

请问在哪个地方修改呢？我估计是系统内置的prompt可能是没有组合好的原因造成的

**Comment by imClumsyPanda** [comment]
> > > <img alt="image" width="1253" src="https://user-images.githubusercontent.com/38274819/263443044-3e921aa4-2e50-4eea-9274-3932e3b0e10a.png"> 我也存在这个问题，搜索引擎有结果返回，但是对话没有内容
> > 
> > 
> > 按照截图信息，这应该属于对话有内容，但语言模型没理解上下文信息。可以尝试修改模型/提示词模版
> 
> 请问在哪个地方修改呢？我估计是系统内置的prompt可能是没有组合好的原因造成的

configs/model_config 的 prompt_template

**Comment by elven2016** [comment]
升级新版本后也存在上面的问题，搜索无结果返回的问题是因为搜索引擎的prompt模板和知识库的模板源码中用的是一个。知识库的prompt模板不能直接用于搜索引擎，可以新建一个template格式，代码中调用这个新的模板就可以了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/16677082/d69614b8-8cfc-41b4-a321-d77f03462d06)
