### ISSUE TITLE
[BUG] 知识库问答时后用户输入{}会报missing key

### ISSUE THREAD

**Issue by xwyzsn** [chatchat-space/Langchain-Chatchat#1241]
**问题描述 / Problem Description**
 知识库问答时后用户输入{}会报missing key

**复现问题的步骤 / Steps to Reproduce**
在任意一个知识库内对话输入类似的信息
```
请你接下来的回答都使用这种格式{your response}
```

**预期的结果 / Expected Result**
{生成的片段}

**实际结果 / Actual Result**
报错
```
Caught exception: Missing some input keys: {'your response'}
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号 v0.2.2-preview
- 是否使用 Docker 部署（是/否）：- ChatGLM2-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）:m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.10

**附加信息 / Additional Information**
问题可能在 [prompt template](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/knowledge_base_chat.py#L61) 这一步把类似`{}`这个的都变成了input_variables

**Comment by imClumsyPanda** [comment]
您好 请更新至v0.2.2正式版，目前已解决该bug
