### ISSUE TITLE
[Feature] 调用openai api 使用windows全局代理问题

### ISSUE THREAD

**Issue by heatdrive** [chatchat-space/Langchain-Chatchat#1248]
v0.2.2-preview
windows环境部署，使用路由器挂代理调用openai api正常。
梯子客户端挂全局代理调用，提示500错误。
查了一下这个报错还是跟系统代理有关，但是关了代理又没法访问openai，
请问挂系统代理有没有可行的解决办法。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/100142472/c9457d4c-d40d-485e-bece-2a2fea2bab55)

**Comment by imClumsyPanda** [comment]
0.2.2版本已经正式上线，增加了openai_proxy的配置项，请检查一下是否已经正确配置

**Comment by heatdrive** [comment]
> 0.2.2版本已经正式上线，增加了openai_proxy的配置项，请检查一下是否已经正确配置

proxy配置应该如何填写 好像没有样例文档
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/100142472/e3648ca9-31e6-4d60-b355-d487d1ee0fb9)

**Comment by zqt996** [comment]
> > 0.2.2版本已经正式上线，增加了openai_proxy的配置项，请检查一下是否已经正确配置
> 
> proxy配置应该如何填写 好像没有样例文档 ![image](https://user-images.githubusercontent.com/100142472/263424162-e3648ca9-31e6-4d60-b355-d487d1ee0fb9.png)

    "gpt-3.5-turbo": {
        "local_model_path": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key":  "这是key的字符串",
        # 本地开代理一般是这个地址
        "openai_proxy": "http://127.0.0.1:4780"
    },

**Comment by zqt996** [comment]
"gpt-3.5-turbo": {
        "local_model_path": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        # 这种形式需要配置环境变量 值OPENAI_API_KEY  百度
        "api_key": os.environ.get("OPENAI_API_KEY"),
        "openai_proxy": "http://127.0.0.1:4780"
    },

**Comment by heatdrive** [comment]
太牛了，已解决。感谢两位。
