### ISSUE TITLE
调用openai API时，出现数据类型错误

### ISSUE THREAD

**Issue by Heckler-Dark** [chatchat-space/Langchain-Chatchat#1249]
Python\Python311\site-packages\fast\chat\serve\model_worker.py

第84行：
        self.conv.sep_style = int(self.conv.sep_style)

 TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by liunux4odoo** [comment]
贴一下startup显示的配置信息，或者python/chatchat/langchain/fastchat的版本

**Comment by zqt996** [comment]
> Python\Python311\site-packages\fast\chat\serve\model_worker.py
> 
> 第84行： self.conv.sep_style = int(self.conv.sep_style)
> 
> TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

用chatgpt不用启动llm_api

**Comment by Heckler-Dark** [comment]
> > Python\Python311\site-packages\fast\chat\serve\model_worker.py
> > 第84行： self.conv.sep_style = int(self.conv.sep_style)
> > TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> 
> 用chatgpt不用启动llm_api

请问你说的这个是在哪个目录下的文件

**Comment by ilovesouthpark** [comment]
你是用的一键启动吗？如果是用openai的api，不要去用一键启动，单独按照开发部署5里面的方法，只需单独启动5.2和5.3就行。

**Comment by Heckler-Dark** [comment]
> 你是用的一键启动吗？如果是用openai的api，不要去用一键启动，单独按照开发部署5里面的方法，只需单独启动5.2和5.3就行。

好的，我试一下。

**Comment by Heckler-Dark** [comment]
> 贴一下startup显示的配置信息，或者python/chatchat/langchain/fastchat的版本

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
项目版本：v0.2.2
langchain版本：0.0.266. fastchat版本：0.2.24


当前LLM模型：gpt-3.5-turbo @ cuda
{'api_base_url': 'http://127.0.0.1:8888/v1',
 'api_key': None,
 'local_model_path': 'gpt-3.5-turbo',
 'openai_proxy': None}
当前Embbedings模型： text-embedding-ada-002 @ cuda
==============================Langchain-Chatchat Configuration==============================

api_key: None
我复制粘贴，还是import openai都不行。

api_base_url
这一行我是看注释更改的，更改前一样不行

**Comment by liunux4odoo** [comment]
> > 贴一下startup显示的配置信息，或者python/chatchat/langchain/fastchat的版本
> 
> ==============================Langchain-Chatchat Configuration============================== 操作系统：Windows-10-10.0.22621-SP0. python版本：3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] 项目版本：v0.2.2 langchain版本：0.0.266. fastchat版本：0.2.24
> 
> 当前LLM模型：gpt-3.5-turbo @ cuda {'api_base_url': 'http://127.0.0.1:8888/v1', 'api_key': None, 'local_model_path': 'gpt-3.5-turbo', 'openai_proxy': None} 当前Embbedings模型： text-embedding-ada-002 @ cuda ==============================Langchain-Chatchat Configuration==============================
> 
> api_key: None 我复制粘贴，还是import openai都不行。
> 
> api_base_url 这一行我是看注释更改的，更改前一样不行


关于使用chatgpt在线API，model_config.py.example里有详细的说明。api_base_url要按openai的网址写，删除local_model_path。旧版本代码不要启动startup.py，直接启动api.py即可。

**Comment by Heckler-Dark** [comment]
> > > 贴一下startup显示的配置信息，或者python/chatchat/langchain/fastchat的版本
> > 
> > 
> > ==============================Langchain-Chatchat Configuration============================== 操作系统：Windows-10-10.0.22621-SP0. python版本：3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] 项目版本：v0.2.2 langchain版本：0.0.266. fastchat版本：0.2.24
> > 当前LLM模型：gpt-3.5-turbo @ cuda {'api_base_url': 'http://127.0.0.1:8888/v1', 'api_key': None, 'local_model_path': 'gpt-3.5-turbo', 'openai_proxy': None} 当前Embbedings模型： text-embedding-ada-002 @ cuda ==============================Langchain-Chatchat Configuration==============================
> > api_key: None 我复制粘贴，还是import openai都不行。
> > api_base_url 这一行我是看注释更改的，更改前一样不行
> 
> 关于使用chatgpt在线API，model_config.py.example里有详细的说明。api_base_url要按openai的网址写，删除local_model_path。
> 
> 旧版本代码可以分别启动api.py和webui.py即可，或者`python startup.py --api --webui`也可。

D:\Langchain-Chatchat\configs\model_config.py:
"gpt-3.5-turbo": {
        #"local_model_path": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": os.environ.get("sk-9M13Aw7WRxLL7UbLgXXXXXXXXXXXXXXXXXMbgN6Ie"),
        "openai_proxy": os.environ.get("OPENAI_PROXY")
    },

如上述情况，我输入了密钥，但仍然报错：

Did not find openai_api_key, please add an environment variable `OPENAI_API_KEY` which contains it, or pass  `openai_api_key` as a named parameter. (type=value_error)

**Comment by liunux4odoo** [comment]
> 

你错把key当key了。把os.environ.get那些去掉，只留key就行了

**Comment by Heckler-Dark** [comment]
> 你错把key当key了。把os.environ.get那些去掉，只留key就行了

感谢回复

**Comment by Duyz232** [comment]
> > 你错把key当key了。把os.environ.get那些去掉，只留key就行了
> 
> 感谢回复

可以了吗？我改过来后还是一样的报错！！

**Comment by Duyz232** [comment]
还有就是，麻烦问一下，OPENAI_PROXY这个怎么写呢？

**Comment by Duyz232** [comment]
> > > Python\Python311\site-packages\fast\chat\serve\model_worker.py
> > > 第84行： self.conv.sep_style = int(self.conv.sep_style)
> > > TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
> > 
> > 
> > 用chatgpt不用启动llm_api
> 
> 请问你说的这个是在哪个目录下的文件
意思是我用gpt-3.5-turbo的时候不用执行 python server/llm_api.py吗

**Comment by ilovesouthpark** [comment]
embedding不要用openai的试试，我单独llm是api的可以，embedding也改为openai的就不行了
