### ISSUE TITLE
[BUG] 简洁阐述问题 / 0.2.1和0.2.2版本都存在检索相似度大于1的情况，导致自定义知识库无法匹配上

### ISSUE THREAD

**Issue by danny-zhu** [chatchat-space/Langchain-Chatchat#1254]
**问题描述 / Problem Description**
设置score_threshold为1，无法检索到自定义知识库中的匹配内容。实际检索出来的相似度大于1，见下图：
![6bd79dc8f4a0ac013daaeeb06c477ac](https://github.com/chatchat-space/Langchain-Chatchat/assets/12292357/144bec2a-e7ae-4875-9a4c-f39a7a5b30a6)

类似情况在0.2.1里面很严重（所有自定义知识都无法匹配），0.2.2里面有所缓解（大部分能匹配上，但是存在少量情况无法匹配的情况）。尽管0.2.2版本里号称支持faiss但是还是会存在相似度大于1的情况。在0.2.2版本里重新导入自定义知识也无法匹配，因为相似度值大于1。

**复现问题的步骤 / Steps to Reproduce**
添加自定义知识库，提问。

**预期的结果 / Expected Result**
匹配自定义知识库中的内容，给出答案。

**实际结果 / Actual Result**
无法匹配自定义知识库。

**环境信息 / Environment Information**
Ubuntu22.04.1/Windows11

**Comment by liunux4odoo** [comment]
我这边测试的结果，FAISS没有超过1.0的。如果用的FAISS，你可以把info.db和*.faiss删掉，重建知识库试试？

milvus和pgvector的可能存在>1.0的，正在解决当中。

**Comment by aleimu** [comment]
我也遇到了这种问题,基本匹配不到知识条目

**Comment by FURYFOR** [comment]
我也遇到了一样的情况，使用FAISS进行本地知识库提问时匹配不上，测试sample也不行

**Comment by aleimu** [comment]
> 
我本地也改了一个版本,让阈值最大为2才能正常使用0.2.2版本,不过在测试baichuan大模型时输入的上下文并不会被模型正确使用

**Comment by aleimu** [comment]
> > > 
> > 
> > 
> > 我本地也改了一个版本,让阈值最大为2才能正常使用0.2.2版本,不过在测试baichuan大模型时输入的上下文并不会被模型正确使用
> 
> 能问下如何将阀值更改为2吗？

改代码,大概三四个文件有点小改动,具体的你看下代码自己改改

**Comment by elepherai** [comment]
https://github.com/langchain-ai/langchain/blob/c732d8fffd39d2b02bdc393c37d2ccdd48f7626d/libs/langchain/langchain/vectorstores/faiss.py#L219

我在这行后面加上scores = scores / 4后就和我自己用numpy算的一样了，是什么原因？

<img width="522" alt="d04abdbb98b9ec6f844359614c7c85f" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/43477405/91df3a2f-02fc-4d6b-82ea-1c80124b4206">

**Comment by fayxxxx** [comment]
目前版本里的score threshold在0-1取值，但是faiss的similarty search with score是按照欧几里得距离来进行匹配的，欧几里得距离是会大于1的，所以是不是就会出问题？

**Comment by zixiaotan21** [comment]
想请教各位大佬，faiss的similarty search with score 到底算的是欧几里得距离  还是余弦相似度~
