### ISSUE TITLE
[BUG] 0.2.1和0.2.2版本的webui界面回答问题会出现回答被截断的情况

### ISSUE THREAD

**Issue by danny-zhu** [chatchat-space/Langchain-Chatchat#1255]
**问题描述 / Problem Description**
0.2.1和0.2.2版本的webui界面回答问题会出现回答被截断的情况，我提的问题是：二十四节气，webui回答如下图所示：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12292357/7a5e9fd3-e925-4319-870e-cc5ba76e50ef)

问题回答不完整，通常答案超过600个字以上时，基本无法回答完整。

但是直接调用接口/chat/knowledge_base_chat测试，回答相同的问题，却回答的不一样，内容很简短，内容正确。下图是api直接调用返回的答案：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12292357/93c920a2-d808-4694-9f4c-53cfd8176fa7)

**Comment by liunux4odoo** [comment]
方便把这个知识文件发给我们测试一下吗？

network里看一下对/chat/knowledge_base_chat的请求，是不是把历史记录带上了？

**Comment by imClumsyPanda** [comment]
1.答案输出长度一般受到模型处理token数量限制，可以通过回复“继续”让模型继续输出内容；
2.llm本身回答存在受到历史记录与随机性影响，可通过调整temperature等模型参数和不传入历史记录来尽量减少模型生成内容的多样性，但从当前项目实现没法保证每次回答完全相同。理论上来说，webui或api环境下测试，也可能发生无历史记录的相同提问，得到不同回答。
