### ISSUE TITLE
[BUG] 上传PDF，偶发出现Can't find model 'zh_core_web_sm'

### ISSUE THREAD

**Issue by DJasonlin** [chatchat-space/Langchain-Chatchat#1256]
linux上已经按照提示安装zh_core_web_sm，但是依然提示下面的错误
UnstructuredFileLoader
[E050] Can't find model 'zh_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

使用的是最新的版本

**Comment by danny-zhu** [comment]
模型文件的路径对不对？windows环境要用双反斜杠\\作为文件路径分隔符，另外最好使用绝对路径。

**Comment by DJasonlin** [comment]
> 模型文件的路径对不对？windows环境要用双反斜杠\作为文件路径分隔符，另外最好使用绝对路径。

在Ubuntu环境里面，路径应该是没什么问题，我试试绝对路径

**Comment by DJasonlin** [comment]
很神奇，不报Can't find model 'zh_core_web_sm'错了，开始报：UnstructuredFileLoader
No module named 'zh-core-web-sm'？？？

**Comment by imClumsyPanda** [comment]
这是项目中在使用spacytextsplitter时会用到的分句模型，不使用也能够完成分句。

如需下载该模型，请运行python -m spacy download zh_core_web_sm

**Comment by ye7love7** [comment]
> 这是项目中在使用spacytextsplitter时会用到的分句模型，不使用也能够完成分句。
> 
> 如需下载该模型，请运行python -m spacy download zh_core_web_sm

大佬，请问如何将这个分词模型下载并部署到离线环境？

**Comment by nicole828** [comment]
> > 这是项目中在使用spacytextsplitter时会用到的分句模型，不使用也能够完成分句。
> > 如需下载该模型，请运行python -m spacy download zh_core_web_sm
> 
> 大佬，请问如何将这个分词模型下载并部署到离线环境？

请问一下，这个问题解决了么？

**Comment by ye7love7** [comment]
下载模型到离线环境，部署一下，或者改一下源码。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月14日(周四) 下午4:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 上传PDF，偶发出现Can't find model 'zh_core_web_sm' (Issue #1256)




   
这是项目中在使用spacytextsplitter时会用到的分句模型，不使用也能够完成分句。
 如需下载该模型，请运行python -m spacy download zh_core_web_sm
  
大佬，请问如何将这个分词模型下载并部署到离线环境？
  
请问一下，这个问题解决了么？
