### ISSUE TITLE
上传知识文件出错AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#1259]
**问题描述 / Problem Description**
上传知识文件（pdf、doc、txt）后出现AxiosError: Request failed with status code 400

**复现问题的步骤 / Steps to Reproduce**
在知识库目录下新建自定义知识文件夹后，运行python init_database.py --recreate-vs初始化
按文档描述启动api和web ui，在打开的web ui中，进入知识库管理，上传知识文件

**预期的结果 / Expected Result**
像samples一样里面有一个text.txt文件的源文件和向量库

**实际结果 / Actual Result**
上传自己的文档出现AxiosError: Request failed with status code 400

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.2
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 18.04
- Python 版本 / Python version: 3.8.17
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by delamoer** [comment]
@rabum 请问你解决这个问题了吗？我也遇到了同样的情况

**Comment by rabum** [comment]
> @rabum 请问你解决这个问题了吗？我也遇到了同样的情况

解决了，说来惭愧，这是个很简单的错误，我把vpn关了就可以上传了

**Comment by delamoer** [comment]
> > @rabum 请问你解决这个问题了吗？我也遇到了同样的情况
> 
> 解决了，说来惭愧，这是个很简单的错误，我把vpn关了就可以上传了

我的VPN是关闭的，通过重启电脑解决了。。。
