### ISSUE TITLE
[FEATURE] 是否能增加一个功能，直接读取服务器下某个文件夹的所有文件自动添加到知识库

### ISSUE THREAD

**Issue by DJasonlin** [chatchat-space/Langchain-Chatchat#1261]
出发点：
目前在做一个公开报告的知识库，有5000多个PDF，如果通过页面一个个上传，效率非常低。
想法是先把pdf文档上传到服务器的文件夹下，通过工具遍历文件夹下所有文档，添加到知识库
另外添加到知识库的效率有点低，是否能多线程添加

**Comment by DJasonlin** [comment]
目前添加500个pdf文档，整体耗时在4个小时左右

**Comment by liunux4odoo** [comment]
你可以把文件拷到服务器knowledge_base/{kb_name}/content里面，然后在webui知识库管理界面选“从源文件重建知识库"，即可略过文件上传环节。

**Comment by DJasonlin** [comment]
> 你可以把文件拷到服务器knowledge_base/{kb_name}/content里面，然后在webui知识库管理界面选“从源文件重建知识库"，即可略过文件上传环节。或者也可在服务端直接`python init_database.py --recreate-vs`

好的，我试试，但是对于重建知识库这个过程，没办法并行跑吗？

**Comment by weedon666** [comment]
可以进入文件夹目录，ctrl +A全选后，一次性上传；但是会有后续问题，比如一次上传过多文件后，会有部分文件加载失败，如下图，请大佬帮忙定位看下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/20f33a97-029c-4fad-86ff-ee89dbae52fd)

**Comment by liunux4odoo** [comment]
Duplicate of #821
