### ISSUE TITLE
使用chatglm2-6b-int8时报错

### ISSUE THREAD

**Issue by xjDUAN184** [chatchat-space/Langchain-Chatchat#1262]
以下是我的运行代码

# 生成向量数据库
from configs.model_config import *
from chains.local_doc_qa import LocalDocQA, load_file
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "2"  
import nltk
from models.loader.args import parser
import models.shared as shared
from models.loader import LoaderCheckPoint
nltk.data.path = [NLTK_DATA_PATH] + nltk.data.path

# Show reply with source text from input document
REPLY_WITH_SOURCE = True
args = None
args = parser.parse_args(args=[])
args_dict = vars(args)
shared.loaderCheckPoint = LoaderCheckPoint(args_dict)
llm_model_ins = shared.loaderLLM()
llm_model_ins.history_len = LLM_HISTORY_LEN
# CHUNK_SIZE = 400
print(VECTOR_SEARCH_TOP_K, SENTENCE_SIZE, CHUNK_SIZE)
local_doc_qa = LocalDocQA()
local_doc_qa.init_cfg(llm_model=llm_model_ins,
                          embedding_model=EMBEDDING_MODEL,
                          embedding_device=EMBEDDING_DEVICE,
                          top_k=VECTOR_SEARCH_TOP_K)
vs_path = None
while not vs_path:
    # filepath = input("Input your local knowledge file path 请输入本地知识文件路径：")
    filepath = '/root/ndz/Langchain-Chatchat/kbqa_data'
    # 判断 filepath 是否为空，如果为空的话，重新让用户输入,防止用户误触回车
    if not filepath:
        continue
    vs_path, _ = local_doc_qa.init_knowledge_vector_store(filepath)
history = []

报错的内容如下：
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
File [~/anaconda3/envs/chatv17/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py:261](https://vscode-remote+ssh-002dremote-002b4090.vscode-resource.vscode-cdn.net/root/ndz/Langchain-Chatchat/~/anaconda3/envs/chatv17/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py:261), in hf_raise_for_status(response, endpoint_name)
    260 try:
--> 261     response.raise_for_status()
    262 except HTTPError as e:

File [~/anaconda3/envs/chatv17/lib/python3.8/site-packages/requests/models.py:1021](https://vscode-remote+ssh-002dremote-002b4090.vscode-resource.vscode-cdn.net/root/ndz/Langchain-Chatchat/~/anaconda3/envs/chatv17/lib/python3.8/site-packages/requests/models.py:1021), in Response.raise_for_status(self)
   1020 if http_error_msg:
-> 1021     raise HTTPError(http_error_msg, response=self)

HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/THUDM/chatglm2-6b-int8/resolve/main/config.json

The above exception was the direct cause of the following exception:

RepositoryNotFoundError                   Traceback (most recent call last)
File [~/anaconda3/envs/chatv17/lib/python3.8/site-packages/transformers/utils/hub.py:417](https://vscode-remote+ssh-002dremote-002b4090.vscode-resource.vscode-cdn.net/root/ndz/Langchain-Chatchat/~/anaconda3/envs/chatv17/lib/python3.8/site-packages/transformers/utils/hub.py:417), in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, use_auth_token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash)
    415 try:
    416     # Load from URL or cache if already cached
--> 417     resolved_file = hf_hub_download(
    418         path_or_repo_id,
    419         filename,
    420         subfolder=None if len(subfolder) == 0 else subfolder,
    421         repo_type=repo_type,
    422         revision=revision,
...
    443         f"'https://huggingface.co/{path_or_repo_id}' for available revisions."
    444     )

OSError: THUDM/chatglm2-6b-int8 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?e6aaebaa-e109-4d8b-9735-1bbc8e5920e5) or open in a [text editor](command:workbench.action.openLargeOutput?e6aaebaa-e109-4d8b-9735-1bbc8e5920e5). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

我的代码版本是0.1.17，我将model_cofigs.py中的LLM_MODEL 参数设为 "chatglm2-6b-int8"。根据提示我的理解是huggingface中没有THUDM/chatglm2-6b-int8这个模型，我去查了一下确实没有，如何使用int8版本的模型呢（int4版本的模型是可以的）？
我尝试过将LOAD_IN_8BIT 设为True，还是会报错。

**Comment by imClumsyPanda** [comment]
可以测试一下chatglm2-6b模型加上LOAD_IN_8BIT 设为True，能否正常运行
