### ISSUE TITLE
[FEATURE] 知识库管理增加分页读取的功能

### ISSUE THREAD

**Issue by DJasonlin** [chatchat-space/Langchain-Chatchat#1270]
目前使用langchain v0.2.2版本
文件总数目前在5000条，每次进到知识库管理页面，总耗时在20多秒左右
希望可以增加分页的功能

**Comment by weedon666** [comment]
knowledge_base.py中，AgGrid里可以自行加两个参数先，heiht和width。固定小窗口展示且上下滑动，6000+文件加载耗时1s左右
代码如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/c6c7f80b-b2ad-477f-bebd-6807c85dd442)
效果如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135689911/8c8bba3e-e3ba-40f1-bd23-ba6cc6fa9cdd)

**Comment by DJasonlin** [comment]
> knowledge_base.py中，AgGrid里可以自行加两个参数先，heiht和width。固定小窗口展示且上下滑动，6000+文件加载耗时1s左右 代码如下： ![image](https://user-images.githubusercontent.com/135689911/263568904-c6c7f80b-b2ad-477f-bebd-6807c85dd442.png) 效果如下： ![image](https://user-images.githubusercontent.com/135689911/263576145-8c8bba3e-e3ba-40f1-bd23-ba6cc6fa9cdd.png)

我在knowledge_base.py里面加了如下一行代码：
gb.configure_pagination(enabled=True, paginationAutoPageSize=True, paginationPageSize=20)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/7c4af9d5-79ae-4f1e-9e1b-c2cf1c359c11)
展示效果如下图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/b434a8de-4e70-452a-a7fb-b4b6f19f008c)
但是这种目前依然是所有文件同时遍历出来，在浏览器进行分页，可能是我网络的原因，速度还是得3到4秒
