### ISSUE TITLE
[FEATURE] llm 和 embedding 接入公有 API

### ISSUE THREAD

**Issue by xingyun52** [chatchat-space/Langchain-Chatchat#1272]
llm能支持azure的chatgpt、百度、智普的SaaS 公有API吗？
embeddings同理能支持chatgpt、百度、智普的SaaS 公有API吗
毕竟私有部署llm挺高成本的。

**Comment by imClumsyPanda** [comment]
开发组近期也在考虑公有api接入方式，将在讨论确定后开展开发工作。

**Comment by winie-hy** [comment]
码住，希望可以付费私有api

**Comment by ArlanCooper** [comment]
同样咨询是否可以支持azure的openai接口

**Comment by zRzRzRzRzRzRzR** [comment]
在下2个版本中将会支持，目前有人提出PR，我们还在想是按照fschat来走还是直接走langchain
