### ISSUE TITLE
部署到腾讯云服务器，流式返回消息页面刷新看起来很卡

### ISSUE THREAD

**Issue by huanghuidmml** [chatchat-space/Langchain-Chatchat#1273]

**Comment by imClumsyPanda** [comment]
请问是流式输出速度慢吗？具体模型是？

**Comment by huanghuidmml** [comment]
用的llama，是流式回复的时候整个页面一闪一闪的，像闪屏一样。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年08月27日 23:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] 部署到腾讯云服务器，流式返回消息页面刷新看起来很卡 (Issue #1273) |

请问是流式输出速度慢吗？具体模型是？
