### ISSUE TITLE
一键启动脚本闪退

### ISSUE THREAD

**Issue by Heckler-Dark** [chatchat-space/Langchain-Chatchat#1274]
如题

**Comment by glide-the** [comment]
请按照bug模板提交，我们会抽出时间解决您的问题

**Comment by Heckler-Dark** [comment]
我原先的做法是：

新建一个文本，然后copy一键启动的脚本代码
python startup.py -a

接着保存，然后修改其后缀
这里我遇到了一个问题，因为我是用python创建虚拟环境按照项目文件的，所以它似乎要我先行激活环境

不过，即便是激活命令也是闪退。

总之就是，无论存在虚拟环境与否，bat文件仍然闪退——这在之前是我不曾遇见的。

**Comment by Heckler-Dark** [comment]
我在环境变量里删除了原来的设置，然后重新用conda装了一遍，现在问题解决了。估计是原先的环境path出了问题
