### ISSUE TITLE
新建知识库后，首次查询特别慢/第一次查询特别慢（使用的faiss是faiss-gpu）

### ISSUE THREAD

**Issue by ywancit** [chatchat-space/Langchain-Chatchat#1278]
想请教一下各位，为什么新建知识库后首次查询特别慢呢？知识库大小7万文档，140万向量，首次查询1分钟整，第二次及之后查询基本在0.7秒左右，差距达到接近100倍

**Comment by liunux4odoo** [comment]
项目对FAISS向量库加载做了缓存，第一次查询时会从磁盘加载，之后就会使用缓存。
你向量库比较大，加载时间明显，所以才觉得相差时间大。如果不做缓存，那每次查询都是1分钟。

**Comment by ywancit** [comment]
> 项目对FAISS向量库加载做了缓存，第一次查询时会从磁盘加载，之后就会使用缓存。 你向量库比较大，加载时间明显，所以才觉得相差时间大。如果不做缓存，那每次查询都是1分钟。

了解了，谢谢。
还想问一下那项目缓存是缓存显存里面吗？是不是faiss-gpu就缓存到显存，faiss-cpu缓存到内存？

**Comment by liunux4odoo** [comment]
> > 项目对FAISS向量库加载做了缓存，第一次查询时会从磁盘加载，之后就会使用缓存。 你向量库比较大，加载时间明显，所以才觉得相差时间大。如果不做缓存，那每次查询都是1分钟。
> 
> 了解了，谢谢。 还想问一下那项目缓存是缓存显存里面吗？是不是faiss-gpu就缓存到显存，faiss-cpu缓存到内存？

缓存到内存的。gpu的这个问题，倒还没考虑过，你如果用faiss-gpu，欢迎反馈试用情况。

**Comment by mppsk0** [comment]
> 想请教一下各位，为什么新建知识库后首次查询特别慢呢？知识库大小7万文档，140万向量，首次查询1分钟整，第二次及之后查询基本在0.7秒左右，差距达到接近100倍

想问下你是如何构建知识库的？
