### ISSUE TITLE
分开启动api服务时，在基于知识库问答时返回空答案，且后端有报错：httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by wufxgtihub123** [chatchat-space/Langchain-Chatchat#1279]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by wufxgtihub123** [comment]
使用的是V0.2.2，且使用一键脚本无法启动成功，已经按照要求更新了requirements

**Comment by xxWeiDG** [comment]
我也出现了这个毛病，您那解决了吗

**Comment by hh-hh19** [comment]
同样遇到这个问题

**Comment by xxWeiDG** [comment]
> 同样遇到这个问题

感觉应该是数据传输过程中的问题，但是不明白会出现这种问题

**Comment by weifan-zhao** [comment]
同样遇到这个问题

**Comment by zzflybird** [comment]
同样遇到这个问题，请问有人解决了吗？

**Comment by ipv6next** [comment]
同上，如何解决？

**Comment by zzflybird** [comment]
> 同上，如何解决？

我直接拉最新版本0.2.4的，重新部署就没有这个问题。
