### ISSUE TITLE
我更改默认的端口7861和8501，重启发现没变化呢

### ISSUE THREAD

**Issue by xuyaokun** [chatchat-space/Langchain-Chatchat#1281]
**更改  server 下的 server_config.py 文件 ：**

![1693205094095](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/901d2167-d77c-4443-880d-0605f746d5ec)

python server/llm_api.py 启动LLM模型服务
streamlit run webui.py 运行网页
python server/api.py  运行接口

**三个命令全部重启了，没有变化呢，仍然是原来的端口**

**Comment by liunux4odoo** [comment]
server_config是给startup.py使用的：`python startup.py -a`

**Comment by xuyaokun** [comment]
> server_config是给startup.py使用的：`python startup.py -a`

好的。对了，谢谢！
