### ISSUE TITLE
[BUG] 知识库迁移后无法匹配向量

### ISSUE THREAD

**Issue by CindyShenn** [chatchat-space/Langchain-Chatchat#1283]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
按照readme中的指引用python init_database.py完成了知识库的迁移，运行过程没有报错，且新旧版本均使用m3e-base、faiss。在旧版本知识库问答中能匹配到对应向量，但在新版本同一知识库提问时永远返回空。

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.2
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by CindyShenn** [comment]
> 需要加上参数`python init_database.py --recreate-vs`

感谢您回复，我看文档上说“向量库类型、Embedding 模型与 configs/model_config.py 中默认设置一致，如无变化只需用python init_database.py将现有知识库信息添加到数据库即可”，加--recreate-vs的话应该是重构向量库。我的模型和配置是一致的，而且已有向量库比较大，所以想尝试文档中直接“将现有知识库信息添加到数据库”的方法，但迁移后提问却匹配不到结果

**Comment by liunux4odoo** [comment]
> > 需要加上参数`python init_database.py --recreate-vs`
> 
> 感谢您回复，我看文档上说“向量库类型、Embedding 模型与 configs/model_config.py 中默认设置一致，如无变化只需用python init_database.py将现有知识库信息添加到数据库即可”，加--recreate-vs的话应该是重构向量库。我的模型和配置是一致的，而且已有向量库比较大，所以想尝试文档中直接“将现有知识库信息添加到数据库”的方法，但迁移后提问却匹配不到结果

因为新版代码启用了normalize_L2，一开始不支持score_threshold，所以不重建也没关系。

如果你知识库比较大，可以考虑用dev分支的最新代码去重建，它支持多线程。
