### ISSUE TITLE
浏览器无法访问

### ISSUE THREAD

**Issue by AlgoAssemblyLine** [chatchat-space/Langchain-Chatchat#1286]
**问题描述 / Problem Description**
webui.py正常启动后：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/137020512/e3941124-2413-4ae4-a768-cbd19f9b2a71)
浏览器打不开：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/137020512/dd63b802-5777-4e38-900b-f7273a8b05fb)

但是修改 server.config.py
DEFAULT_BIND_HOST改为0.0.0.0，能打开了，但对话之后，出现403 ，同时新建知识库也出现403 错误
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/137020512/26248e9d-1da5-46b6-bf06-72de746374bb)

用的最新版0.2.2
linux环境

**Comment by virsing** [comment]
我也遇到了这个问题，浏览器无法访问webui，修改 server.config.py文件
`DEAFULT_BIND_HOST=0.0.0.0`
就正常了，对话新建知识库都正常
