### ISSUE TITLE
TXT大文本，上传知识库时出错

### ISSUE THREAD

**Issue by xuyaokun** [chatchat-space/Langchain-Chatchat#1287]
![8359e36391b7f43052b7af4354c13e0](https://github.com/chatchat-space/Langchain-Chatchat/assets/20808760/703d9dfe-c4e6-42f8-980c-e784e06628ce)

pip install spacy
python -m spacy download zh_core_web_sm
安装过了

**这个在怎么解决呢？**

**Comment by fhyu** [comment]
`
def split_large_file(input_file, chunk_size):
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    num_lines = len(lines)
    num_chunks = (num_lines + chunk_size - 1) // chunk_size

    for i in range(num_chunks):
        start_idx = i * chunk_size
        end_idx = min((i + 1) * chunk_size, num_lines)
        chunk = lines[start_idx:end_idx]

        output_file = f"chunk_{i+1}.txt"
        with open(output_file, 'w', encoding='utf-8') as f_out:
            f_out.writelines(chunk)

        print(f"Created {output_file} with {len(chunk)} lines")

if __name__ == "__main__":
    input_file = "large_file.txt"  # 输入的大文件
    chunk_size = 10000  # 每个小文件的行数

    split_large_file(input_file, chunk_size)
`

**Comment by fhyu** [comment]
'''
def split_large_file(input_file, chunk_size):
    with open(input_file, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    num_lines = len(lines)
    num_chunks = (num_lines + chunk_size - 1) // chunk_size

    for i in range(num_chunks):
        start_idx = i * chunk_size
        end_idx = min((i + 1) * chunk_size, num_lines)
        chunk = lines[start_idx:end_idx]

        output_file = f"chunk_{i+1}.txt"
        with open(output_file, 'w', encoding='utf-8') as f_out:
            f_out.writelines(chunk)

        print(f"Created {output_file} with {len(chunk)} lines")

if __name__ == "__main__":
    input_file = "large_file.txt"  # 输入的大文件
    chunk_size = 1000  # 每个小文件的行数

    split_large_file(input_file, chunk_size)
'''

**Comment by xuyaokun** [comment]
nlp.max_length

> 可以用python把文件分成多个小文件 `def split_large_file(input_file, chunk_size): with open(input_file, 'r', encoding='utf-8') as f: lines = f.readlines()
> 
> ```
> num_lines = len(lines)
> num_chunks = (num_lines + chunk_size - 1) // chunk_size
> 
> for i in range(num_chunks):
>     start_idx = i * chunk_size
>     end_idx = min((i + 1) * chunk_size, num_lines)
>     chunk = lines[start_idx:end_idx]
> 
>     output_file = f"chunk_{i+1}.txt"
>     with open(output_file, 'w', encoding='utf-8') as f_out:
>         f_out.writelines(chunk)
> 
>     print(f"Created {output_file} with {len(chunk)} lines")
> ```
> 
> if **name** == "**main**": input_file = "large_file.txt" # 输入的大文件 chunk_size = 1000 # 每个小文件的行数
> 
> ```
> split_large_file(input_file, chunk_size)
> ```
> 
> `
假如用户上传的文本文件没换行咋办呢

**Comment by danny-zhu** [comment]
把spacy的中文语言包zh_core_web_sm下载就可以了
