### ISSUE TITLE
[BUG] 知识库回答完全不相关/ Concise description of the issue

### ISSUE THREAD

**Issue by linguibin** [chatchat-space/Langchain-Chatchat#1289]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
上传txt到知识库并使用知识库问答

**预期的结果 / Expected Result**
匹配知识库的答案进行回答
描述应该出现的结果 / Describe the expected result.
如何破冰与老板交谈？	老板，我看您酒柜上陈列这么多的xx产品，这应该是您店里卖的最好的一款产品吗？
**实际结果 / Actual Result**
创造机会与老板打招呼，主动敬酒，礼貌地打招呼，开始交谈。
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：langchain-ChatGLM v0.2.2-preview/ 67ac53242db1c120aff7b20d81fb2593ee8750b6 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version: Alibaba Cloud Linux (Aliyun Linux) release 2.1903 LTS
- Python 版本 / Python version:3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/40079776/e978ec18-ec8d-40c5-960d-a86fe7894413)

添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Hiwyl** [comment]
+1 使用test.txt也是同样，知识库匹配为空，调用的模型输出

**Comment by vip68** [comment]
一直没有什么好的解决办法，很困惑

**Comment by zicheqingluo** [comment]
之前langchain-chatglm回答虽说能对一半，但是现在chatchat使用同样的模型chatglm2-6n和text2vec一点能力都没有，要么查不到，要么胡编乱造呢

**Comment by zRzRzRzRzRzRzR** [comment]
建议使用最新的框架并使用更好的嵌入和LLM模型
