### ISSUE TITLE
[BUG] 运行 python init_database.py --recreate-vs 命令后卡住

### ISSUE THREAD

**Issue by SoccerClub** [chatchat-space/Langchain-Chatchat#1291]
运行 python init_database.py --recreate-vs 命令后，打印如下，进程卡住

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19042-SP0.
python版本：3.10.11 | packaged by Anaconda, Inc. | (main, May 16 2023, 00:55:32) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.2
langchain版本：0.0.266. fastchat版本：0.2.24

当前LLM模型：Qwen-7B @ cpu
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'E:\\Repository\\LLM\\Qwen-7B-Chat'}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

database talbes created
recreating all vector stores
loading vector store in 'samples'.
2023-08-28 22:18:15,565 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: E:\Repository\LLM\m3e-base
2023-08-28 22:18:16,458 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-08-28 22:18:16,459 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2023-08-28 22:18:16,459 - loader.py[line:64] - INFO: Loading faiss.
2023-08-28 22:18:16,474 - loader.py[line:66] - INFO: Successfully loaded faiss.
知识库 samples 缓存刷新：1
UnstructuredFileLoader

**Comment by HHH-China** [comment]
+1

**Comment by deepeye** [comment]
+1

**Comment by HHH-China** [comment]
cd your_python_path/site-packages/faiss
ln -s swigfaiss.py swigfaiss_avx2.py
useful to me

**Comment by StevenLu8050** [comment]
@HHH-China but swigfaiss_avx2.py already exists
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/139423772/d210d678-3bdc-4844-8b9e-e31801358f0c)

**Comment by CaoYongshengcys** [comment]
> cd your_python_path/site-packages/faiss ln -s swigfaiss.py swigfaiss_avx2.py useful to me

这个可以不报错了，但是还是卡住了，什么错都不保了，还是卡住了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/23182649/88932fd6-1284-4c1d-8d13-fb363feefafb)

**Comment by guanguoliang** [comment]
我也是运行到这里就卡住了我是MacBook PRO m1
<img width="825" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/30827262/49d0acf9-9f8a-4910-bbe1-7c95336a7698">
