### ISSUE TITLE
[BUG] 无法使用OpenAI API调用gpt-3.5-turbo

### ISSUE THREAD

**Issue by Judex-Yao** [chatchat-space/Langchain-Chatchat#1292]
**问题描述 / Problem Description**
使用本地ChatGLM2-6b时可以正常运行，但尝试通过API使用GPT-3.5-turbo时报错.

**复现问题的步骤 / Steps to Reproduce**
1. 修改了model_config.py
`    "gpt-3.5-turbo": {
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
    },
}

LLM_MODEL = "gpt-3.5-turbo"`

3. 执行python server/api.py
4. 执行streamlit run webui.py
5. 在webui界面进行对话，问题出现：
    webui界面报错：    {"detail":[{"loc":["body",61],"msg":"Expecting value: line 3 column 58 (char 61)","type":"value_error.jsondecode","ctx":{"msg":"Expecting value","doc":"\r\n\r\n{"query": "\u4f60\u597d\u54c7", "history": [], "stream": t","pos":61,"lineno":3,"colno":58}}]}
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/54424709/6deb64bd-7d30-4546-a6a6-aaac9dc9f3c6)
    api运行报错：
        INFO:     127.0.0.1:51715 - "POST /chat/chat HTTP/1.1" 422 Unprocessable Entity
        INFO:     127.0.0.1:51884 - "GET / HTTP/1.1" 307 Temporary Redirect

**环境信息 / Environment Information**
- langchain-Chatchat 版本/commit 号：0.2.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B成功 / gpt-3.5-turbo失败
- 使用的 Embedding 模型：text2vec-large-chinese
- 使用的向量库类型： faiss 
- 操作系统及版本 / Operating system and version: win10
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: 使用Anaconda环境

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
OpenAI API Key未过期，在其他途径可以正常调用该Key

**Comment by mashuiping** [comment]
[server/chat/chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/chat.py#L34) 

添加参数 
```python
model = ChatOpenAI(
    ...,
    max_tokens=llm_model_dict[model_name].get('max_tokens', 2048),
    ...
)
```

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码已经支持调用
