### ISSUE TITLE
如何指定显卡？

### ISSUE THREAD

**Issue by yuqx123** [chatchat-space/Langchain-Chatchat#1295]
运行时 怎么指定显卡

**Comment by glide-the** [comment]
运行时无法制定显卡，运行前可以通过在这个位置修改显卡
https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example#L85C5-L85C5

**Comment by yuqx123** [comment]
> 运行时无法制定显卡，运行前可以通过在这个位置修改显卡 https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example#L85C5-L85C5

我在server_config.py里指定了显卡，但是不生效。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/544afe6c-17e4-4d8d-98bf-4e2a7a779bff)

**Comment by Gzj369** [comment]
> > 运行时无法制定显卡，运行前可以通过在这个位置修改显卡 https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example#L85C5-L85C5
> 
> 我在server_config.py里指定了显卡，但是不生效。 ![image](https://user-images.githubusercontent.com/143470363/263982793-544afe6c-17e4-4d8d-98bf-4e2a7a779bff.png)

CUDA_VISIBLE_DEVICES=0 python 具体脚本.py ，可以试试看 @yuqx123

**Comment by yuqx123** [comment]
startup.py -a 启动的话需要在
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/f6a79a70-cafb-4a97-9b7a-7f4ffbfa0738)

**Comment by yuqx123** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/838d49a2-badc-4952-ba25-2aa2e834dbfb)

**Comment by 518jelly** [comment]
这个问题解决了吗？0.2.2中我碰到了同样的问题，可以指定多卡，但是gpus参数不生效，在指定非第一张卡时不论怎样都会使用第一张卡。

**Comment by evolcano** [comment]
在WIndows上，怎么改都无法生效 

https://github.com/chatchat-space/Langchain-Chatchat/issues/1563#issuecomment-1732515817

**Comment by yuys0602** [comment]
这个解决了嘛？
我是 `LLM_DEVICE = "cuda:7"` 也不行

**Comment by aszzp** [comment]
> > > 运行时无法制定显卡，运行前可以通过在这个位置修改显卡 https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/model_config.py.example#L85C5-L85C5
> > 
> > 
> > 我在server_config.py里指定了显卡，但是不生效。 ![image](https://user-images.githubusercontent.com/143470363/263982793-544afe6c-17e4-4d8d-98bf-4e2a7a779bff.png)
> 
> CUDA_VISIBLE_DEVICES=0 python 具体脚本.py ，可以试试看 @yuqx123

好使。
`CUDA_VISIBLE_DEVICES="1" python startup.py -a`就指定在第二块显卡运行

**Comment by Gzj369** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件我已经收到。看到后我一定会在第一时间内阅读并回复您。
