### ISSUE TITLE
解決PDF讀檔的問題，PDF檔案較大時會常常報錯

### ISSUE THREAD

**Issue by novem33** [chatchat-space/Langchain-Chatchat#1299]
舊版本中使用 UnstructuredPaddlePDFLoader 的PDF讀檔功能，在0.2.1版本中就移除了，自已去改了/server/knowledge_base/utils.py的內容，將pdf的讀檔功能加回來，提供俢改內容供pdf讀檔出現問題的人參考

**取代上述utils.py檔中，下面的file2text部份，希望對大家有幫助....**

    def file2text(self, using_zh_title_enhance=ZH_TITLE_ENHANCE):
        # print(self.document_loader_name)
        if  self.filepath.lower().endswith(".pdf"):                
            print(e)
            document_loaders_module = importlib.import_module('langchain.document_loaders')
            DocumentLoader = getattr(document_loaders_module, "UnstructuredPaddlePDFLoader")

        else:
            try:
                document_loaders_module = importlib.import_module('langchain.document_loaders')
                DocumentLoader = getattr(document_loaders_module, self.document_loader_name)
            except Exception as e:
                print(e)
                document_loaders_module = importlib.import_module('langchain.document_loaders')
                DocumentLoader = getattr(document_loaders_module, "UnstructuredFileLoader")
        if self.document_loader_name == "UnstructuredFileLoader":
            loader = DocumentLoader(self.filepath, autodetect_encoding=True)
        elif self.document_loader_name == "UnstructuredPaddlePDFLoader":
            loader = DocumentLoader(self.filepath, autodetect_encoding=True)
        else:
            loader = DocumentLoader(self.filepath)

        try:
            if self.text_splitter_name is None:
                text_splitter_module = importlib.import_module('langchain.text_splitter')
                TextSplitter = getattr(text_splitter_module, "SpacyTextSplitter")
                text_splitter = TextSplitter(
                    pipeline="zh_core_web_sm",
                    chunk_size=CHUNK_SIZE,
                    chunk_overlap=OVERLAP_SIZE,
                )
                self.text_splitter_name = "SpacyTextSplitter"
            else:
                text_splitter_module = importlib.import_module('langchain.text_splitter')
                TextSplitter = getattr(text_splitter_module, self.text_splitter_name)
                text_splitter = TextSplitter(
                    chunk_size=CHUNK_SIZE,
                    chunk_overlap=OVERLAP_SIZE)
        except Exception as e:
            print(e)
            text_splitter_module = importlib.import_module('langchain.text_splitter')
            TextSplitter = getattr(text_splitter_module, "RecursiveCharacterTextSplitter")
            text_splitter = TextSplitter(
                chunk_size=CHUNK_SIZE,
                chunk_overlap=OVERLAP_SIZE,
            )

        docs = loader.load_and_split(text_splitter)
        print(docs[0])
        if using_zh_title_enhance:
            docs = zh_title_enhance(docs)
        return docs

**Comment by uceehz0** [comment]
问下我添加了原来的UnstructuredPaddlePDFLoader，提示下面的报错，但好像没找到哪里需要调用下面的，单独运行pdf_loader也是正常的
Unable to get page count. Is poppler installed and in PATH?
No module named 'pytesseract'
tesseract is not installed or it's not in your PATH

**Comment by uceehz0** [comment]
> 请问原来的UnstructuredPaddlePDFLoader在哪里查看？
在loader路径下面的pdf_loader.py
https://github.com/chatchat-space/Langchain-Chatchat/releases/tag/v0.1.17

**Comment by novem33** [comment]
謝謝提醒，剛想到我是從0.1.X版本一路追上來的，所以才會直接這樣改。

補充說明問題：
0.1.17版本中，\Langchain-Chatchat-0.1.17\chains\local_doc_qa.py中的 def load_file是我參考的內容，另從 loader資料夾中的__init__.py就可看到from .pdf_loader import UnstructuredPaddlePDFLoader
的套件導入來源

將這個來源import進去就可以運行了!

**Comment by hh-hh19** [comment]
> > 请问原来的UnstructuredPaddlePDFLoader在哪里查看？
> > 在loader路径下面的pdf_loader.py
> > https://github.com/chatchat-space/Langchain-Chatchat/releases/tag/v0.1.17

非常感谢！

**Comment by hh-hh19** [comment]
> 謝謝提醒，剛想到我是從0.1.X版本一路追上來的，所以才會直接這樣改。
> 
> 補充說明問題： 0.1.17版本中，\Langchain-Chatchat-0.1.17\chains\local_doc_qa.py中的 def load_file是我參考的內容，另從 loader資料夾中的__init__.py就可看到from .pdf_loader import UnstructuredPaddlePDFLoader 的套件導入來源
> 
> 將這個來源import進去就可以運行了! 至於 'pytesseract'相關的套件，我以前就做過影像的作業所以有導入，看要不要直接pip install一下!!

非常感谢！
