### ISSUE TITLE
使用多卡启动模型后，问答时模型只消耗第一块显卡的显存，可以怎么修改让模型消耗别的显卡

### ISSUE THREAD

**Issue by baolixiong** [chatchat-space/Langchain-Chatchat#1301]

**Comment by heatdrive** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/100142472/516bdea5-f8ed-482d-b01d-8cd4629695b5)
有GPUID的应该可以控制，比较穷没试过。
哈哈。可以的话回来反馈哈。
