### ISSUE TITLE
用milvus创建知识库报错

### ISSUE THREAD

**Issue by guarx** [chatchat-space/Langchain-Chatchat#1302]
用milvus创建知识库报错

具体错误信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5118509/129fa141-8d54-40c8-81da-2304ccfd7c58)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5118509/859b9121-9a69-4e11-befe-d0def62031a0)

pymilvus                  2.3.0

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后重试
