### ISSUE TITLE
请问能否在聊天窗口调用langchain的内置tool

### ISSUE THREAD

**Issue by iceworld724** [chatchat-space/Langchain-Chatchat#1303]
请问能否在聊天窗口调用langchain的内置tool

tool列表如下：
https://python.langchain.com/docs/integrations/tools/

例如我想在pubmed上查找文献：
https://python.langchain.com/docs/integrations/tools/pubmed

**Comment by Gy1900** [comment]
+1，想知道怎么加入自己的tool，在该项目中如何能够使得LLM调用自定义的Tol

**Comment by iceworld724** [comment]
@Gy1900 我也有一些自定义的tool。查了很久没找到现成的轮子，后来我用Gradio自己做了个简陋的界面 :)
