### ISSUE TITLE
v0.2.2版本对单卡显存要求变大了吗？ 

### ISSUE THREAD

**Issue by yuqx123** [chatchat-space/Langchain-Chatchat#1304]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/5b84e495-b15a-499f-85c8-c6d640461add)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/bbafbf7c-2265-40bc-9287-74accfd07c6f)

**Comment by zRzRzRzRzRzRzR** [comment]
没有，如果显存不足，可以考虑将embed模型换到CPU上运行
