### ISSUE TITLE
[BUG] docker部署后功能都是报错的

### ISSUE THREAD

**Issue by tomasuki** [chatchat-space/Langchain-Chatchat#1307]
添加向量库
<img width="790" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/35524391/0c15d4d1-ce5d-4742-abe3-c555eb355a81">

对话
<img width="862" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/35524391/fc795d4a-984f-4e01-852a-ea3b7a9c465a">

新建知识库
<img width="802" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/35524391/d3a2ccd2-9a97-4cc1-865f-e3756f27a545">

等等

**Comment by SwordHG** [comment]
ERROR: 'NoneType' object has no attribute 'json'    这个问题+1

**Comment by PaleNeutron** [comment]
ConnectError: [Errno 111] Connection refused

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.5会发布新的docker，请更新docker

**Comment by tomasuki** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
好的，收到，会尽快回复。
