### ISSUE TITLE
文本写作，写到一半就没了，输出是不是有限制？应该如何修改呢？

### ISSUE THREAD

**Issue by yuqx123** [chatchat-space/Langchain-Chatchat#1308]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/4ae253ca-d1f0-46b8-a12c-b3b3ba1a6627)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/488e4272-cfc3-4c92-9a91-c4673bed5921)

**Comment by heatdrive** [comment]
我不太懂，但是斗胆出来说一句。试试看这里
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/100142472/97f3d814-007d-4cde-be6e-8bfde6a9aa9a)

**Comment by yuqx123** [comment]
> 我不太懂，但是斗胆出来说一句。试试看这里 ![image](https://user-images.githubusercontent.com/100142472/264023838-97f3d814-007d-4cde-be6e-8bfde6a9aa9a.png)

兄台，我这个是LLM对话，不是知识库问答，这个配置是知识库上传分段用的好像，和对话没有关系

**Comment by heatdrive** [comment]
那确实不太懂，token字数上限什么的是不是有关系，这个项目应该没有调长文本那种API吧（16k，32k）

**Comment by Shame-fight** [comment]
确实有这个问题，输出到一半没了

**Comment by zzflybird** [comment]
是这样的，目前应该还不能设置输出tokens的长度。

**Comment by xjwspeak** [comment]
这个是模型的限制吧

**Comment by yuqx123** [comment]
嗯 是模型都有这个问题，没什么好办法
