### ISSUE TITLE
[BUG] 一键启动点击添加文件到知识库，api.py会退出

### ISSUE THREAD

**Issue by SwordHG** [chatchat-space/Langchain-Chatchat#1309]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 48.10it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 68.41it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.96it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 47.54it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 76.92it/s]
Batches: 100%|█████████████████████████████████████████████████████████████████| 1/1 [00:00<?, ?it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 71.36it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.84it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.23it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.69it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 64.23it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 58.17it/s]
Batches: 100%|█████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 63.98it/s]
知识库 test 缓存刷新：2
INFO:     127.0.0.1:56219 - "POST /knowledge_base/upload_doc HTTP/1.1" 200 OK
Segmentation fault

**Comment by SwordHG** [comment]
ERROR: 'NoneType' object has no attribute 'json'        一键启动后，会抛出这个错误

**Comment by SwordHG** [comment]
已解决

**Comment by justforword** [comment]
> 已解决

请问怎么解决的？我现在也是报ERROR: 'NoneType' object has no attribute 'json' 错误

**Comment by JingxinLee** [comment]
> 已解决

请问怎么解决的？
