### ISSUE TITLE
知识库的建立介绍得有点太简略了

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#1312]
建议在文档中多加一点，怎么添加新的知识库，webui里的知识库管理怎么用，文档加载器、分词器怎么引入，会有哪些问题，这些都不太明白，是一个python init_database.py --recreate-vs就能搞定的吗？

**Comment by energy888666** [comment]
我也在摸索

**Comment by kungkook** [comment]
同问

**Comment by zRzRzRzRzRzRzR** [comment]
在新的代码中，知识库配置有更多选项
包括分词器，嵌入模型选项等
请更新到最新代码
