### ISSUE TITLE
[FEATURE] chatbot增加语音识别模块

### ISSUE THREAD

**Issue by Awyshw** [chatchat-space/Langchain-Chatchat#1316]
**功能描述 / Feature Description**
chatbot 增加语音识别模块，接入语音模型。

**解决的问题 / Problem Solved**
可以解放双手，语音进行交互。

**Comment by zRzRzRzRzRzRzR** [comment]
目前暂时没有很好的本地模型能够支持语音，我们将在未来的版本考虑开发该功能
