### ISSUE TITLE
知识库问答没有上下文能力

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#1320]
目前的知识库问答模式下，大语言模型为什么会完全记不住上文呢？只会回复“根据已知信息，无法回答该问题。”，尝试优化prompt也没什么效果

**Comment by Gzj369** [comment]
试试把之前的上文和本次的输入合在一起作为大模型的输入，是否能满足呢

**Comment by FavoriteStar** [comment]
同！例如我在查询某个用户的具体信息，给出该用户的姓名是什么，在一两次问答之后无法直接用“我”，它会说不知道我是谁！

**Comment by xjwspeak** [comment]
+1 ，遇到同样困惑

**Comment by roki1031** [comment]
我猜可能是因为模型的上下文窗口太小了吧，每次新的提问，就又去检索一遍知识库，然后把”上一次检索的结果+问题+回答“加到本次询问的prompt里面，导致字数太多了。

**Comment by zRzRzRzRzRzRzR** [comment]
知识库以知识库优先，我们将增加总结功能，支持知识库对话的连续对话能力
