### ISSUE TITLE
[FEATURE] docker镜像根据环境变量的配置从huggingface拉大模型和Embedding模型

### ISSUE THREAD

**Issue by kquark** [chatchat-space/Langchain-Chatchat#1322]
**功能描述 / Feature Description**
docker镜像部署支持通过环境变量配置选用的模型，构建服务的时候拉模型。

**解决的问题 / Problem Solved**
可以在镜像里应用多个模型，便于灵活部署。

**实现建议 / Implementation Suggestions**
docker镜像支持通过环境变量配置configs。
构建服务的时候拉模型到指定目录。
下载模型的目录建议挂载数据卷，这样下次就不用重复拉。
镜像也可自带默认的模型，默认模型也是大多数用户的最佳选择。

**Comment by zRzRzRzRzRzRzR** [comment]
最新的docker image将会参考一下这条issue，镜像已经自带了模型
感谢您的提出
