### ISSUE TITLE
WebUI已启动,对话时报错 403

### ISSUE THREAD

**Issue by zeze813** [chatchat-space/Langchain-Chatchat#1327]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53213704/41dfe315-ca88-4f07-b15a-93256d876b6c)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.2
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.8.10

**Comment by SwordHG** [comment]
ip没配置对，好好对齐一下

**Comment by zeze813** [comment]
> ip没配置对，好好对齐一下
如果我全部设置成'0.0.0.0',ModelWorker就会报错,返回503错误,如果ip设置为'127.0.0.1'则不会,但是我现在是部署在服务器,再通过局域网访问,就不能用'127.0.0.1',有什么办法吗

**Comment by zeze813** [comment]
> ip没配置对，好好对齐一下

如果我全部设置成'0.0.0.0',ModelWorker就会报错,返回503错误,如果ip设置为'127.0.0.1'则不会,但是我现在是部署在服务器,再通过局域网访问,就不能用'127.0.0.1',有什么办法吗

**Comment by wuli66ly** [comment]
一个是本地，局域网怎么可能访问本地，ip可以映射出去，或者换本机ip

**Comment by brealisty** [comment]
> > ip没配置对，好好对齐一下
> 
> 如果我全部设置成'0.0.0.0',ModelWorker就会报错,返回503错误,如果ip设置为'127.0.0.1'则不会,但是我现在是部署在服务器,再通过局域网访问,就不能用'127.0.0.1',有什么办法吗

请问一下你解决了吗，我换成0.0.0.0也是报错了
