### ISSUE TITLE
对接Qwen-7B-Chat模型没法做知识库检索

### ISSUE THREAD

**Issue by AlexNilone** [chatchat-space/Langchain-Chatchat#1329]
最近我在试用Langchain-Chatchat，集成chatglm2-6b正常，但集成最新版本的Qwen-7B-Chat(1.0.6)，发现直接LLM查询是正常的，但是无法做知识库的检索。

openai_api接收进程上提示报错：
****"POST /v1/chat/completions HTTP/1.1" 400 Bad Request****

--------------api.py-进程提示报错-------------------------------------------
WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIError: Invalid response object from API: '{"detail":"Invalid request -- 3"}' (HTTP response code was 400).
2023-08-31 16:31:00,518 - util.py[line:67] - INFO: message='OpenAI API response' path=http://XXX.XX.XX.XXX:8888/v1/chat/completions processing_ms=None request_id=None response_code=400

我这里的OpenAI端口是我自己通过Qwen-7B-Chat的命令独立在外面拉起来的（因为显存不够做量化部署及Python依赖包冲突等问题）

环境说明：
- Langchain-Chatchat  ：0.22
- 模型：Qwen-7B-Chat(1.0.6)
- Embedding 模型：m3e-base 
- 向量库类型 ： faiss  
- 操作系统及版本:  Redhat 7.3
- Python 版本 : Python 3.11

**Comment by imClumsyPanda** [comment]
请问另外启动的这个qwen的api的ip和port是否正确，直接在浏览器中能否访问该api的docs呢？如直接访问xxxx:8888/docs

**Comment by AlexNilone** [comment]
知道问题。这边发过去的消息对是偶数个，但是接收端有一个消息格式验证，只能是奇数个

**Comment by SHENRUN622** [comment]
这个问题修复在哪个版本？
