### ISSUE TITLE
[BUG]  Error communicating with OpenAI

### ISSUE THREAD

**Issue by jason95054** [chatchat-space/Langchain-Chatchat#1334]
**问题描述 / Problem Description**
Testing v0.2.2; run startup.py with webui and api; got "Caught exception: Error communicating with OpenAI".

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python ./startup --webui --api'
2. 点击 search
3. 问题出现 / Problem occurs: 'Caught exception: Error communicating with OpenAI'

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-Chatchat 版本/commit 号 v0.2.2
- 是否使用 Docker 部署（是/否）：No
- 使用的模型：ChatGLM2-6B-INT4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等): faiss
- 操作系统及版本 / Operating system and version: Ubuntu Linux-5.15.0-82
- Python 版本 / Python version: v3.10.12
- 其他相关环境信息 / Other relevant environment information: None

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
1. 运行本地部署模型时需要启动llm api、api和webui，建议直接用--all-webui直接启动

2. 请优先选择全量模型或chatgpt api进行部署，测试没有问题后再选择量化模型进行测试。

**Comment by jason95054** [comment]
Thanks for your info. However, when run as python ./startup.py -a and used 知知库问答, there is an error:
2023-09-01 15:08:32.394 Uncaught app exception
Traceback (most recent call last):
  File "/home/intai/projects/kb-ai2/venv-kb/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "/home/intai/projects/Langchain-Chatchat/webui.py", line 70, in <module>
    pages[selected_page]["func"](api)
  File "/home/intai/projects/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 71, in dialogue_page
    kb_list = api.list_knowledge_bases(no_remote_api=True)
  File "/home/intai/projects/Langchain-Chatchat/webui_pages/utils.py", line 411, in list_knowledge_bases
    response = run_async(list_kbs())
  File "/home/intai/projects/Langchain-Chatchat/server/utils.py", line 92, in run_async
    return loop.run_until_complete(cor)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/intai/projects/Langchain-Chatchat/server/knowledge_base/kb_api.py", line 12, in list_kbs
    return ListResponse(data=list_kbs_from_db())
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ListResponse
data -> 1
  none is not an allowed value (type=type_error.none.not_allowed)

**Comment by jason95054** [comment]
I have modified server/db/repository/knowledge_base_repository.py, in list_kbs_from_db(), line 21 to:
kbs = [kb[0] for kb in kbs if kb[0] != None]

The above error went away. However, the error of "Caught exception: Error communicating with OpenAI" was still there.
I ran 'python ./startup.py -a'; select 知知库问答; enter a query; the error occurred.

**Comment by jason95054** [comment]
Selecting  知知库问答 should not involve openai_chat.

**Comment by jason95054** [comment]
I found out why: the API port numbers in model_config.py were not matched with server_config.py.
I suggest that the API ports are defined in model_config.py and server_config.py imports those port numbers.
This will eliminate the mismatch.

**Comment by jason95054** [comment]
#1334 closed.
