### ISSUE TITLE
[BUG] Baichuan7b 加载后没有报错，但是提问感觉不是对应模型 / Concise description of the issue

### ISSUE THREAD

**Issue by ZlskCompany** [chatchat-space/Langchain-Chatchat#1335]
**问题描述 / Problem Description**
加载baichuan-7b 是成功的，但是页面问答又有问题，默认的glm模型就没问题

**复现问题的步骤 / Steps to Reproduce**
1.修改了配置文件的moudle_dic，增加了baichuan7b的本地路径
2.更换了默认的模型为baichuan7b
3.一键启动，但是没有像glm那样看到加载模型的进度条也没有报错

**预期的结果 / Expected Result**
问它是什么模型，应该回答是百川7b的模型

**实际结果 / Actual Result**
空白回答，或者英文乱语

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no):  no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan7b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): milvus
- 操作系统及版本 / Operating system and version: MacOS (M2)
- Python 版本 / Python version: 3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by huishaowangzhe** [comment]
兄弟，问题解决了嘛，我也同样问题

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新版本，更新fschat到0.2.29
