### ISSUE TITLE
[BUG] 偶发出现：有内容返回，同时又带上了“无法回答”这几个字

### ISSUE THREAD

**Issue by DJasonlin** [chatchat-space/Langchain-Chatchat#1343]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/d57e29ff-1de8-449a-aead-7b46d57cb113)
通过调用/knowledge_base/create_knowledge_base接口产生的回答。
版本是当前最新的0.2.2版本
以上问题不是每次出现，偶发

**Comment by 306404391** [comment]
我也遇到过这个问题，出现了这个，如果不换问法，会一直出现，换一下问法可能就正常回答了，不知道为什么

**Comment by xjwspeak** [comment]
+1 ， 感觉是模型能力不行

**Comment by LXXiaogege** [comment]
+1，有什么好的解决方法可以提供吗

**Comment by soultrans** [comment]
+1 ,持续关系，也遇到了类似的问题

**Comment by zRzRzRzRzRzRzR** [comment]
1. 模型能力不行
2. 检查是否调用了两次API
3. 提示词问题
更新到最新代码重试后若仍有问题可以在微信群中交流这个少见现象
