### ISSUE TITLE
[BUG] 向模型提问模型没有回答，请问是不是模型路径出问题了

### ISSUE THREAD

**Issue by Luka0770** [chatchat-space/Langchain-Chatchat#1350]
![c898356fd5d63b2ea43b0bc85ac838a](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/a67f7037-ca69-4d3c-85fc-d94d5f49c80c)
![9efec93e0e9ea6d4f19d94c535d866f](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/0f4071e7-866b-409a-ae08-33871518c667)
![7cd5cef2e54c7c3ade7d08c8a11fa51](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/cc034090-77ec-4785-9751-497df3ae01d4)
![4a12b0d5b0fcdfa218c85c7eb7b2d48](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/fd81dd3b-8fb0-4adc-936c-1872500c7c17)

**Comment by Luka0770** [comment]
![f7d550dd9821f47134a1353f14e2d8d](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/81affa3f-2644-4a26-a12a-ad2b4bc933eb)

**Comment by xiehangm** [comment]
我也是这个情况，同求解决方法。

**Comment by cchenjh** [comment]
我也是这个情况，同求解决方法。

**Comment by Lrrrr549** [comment]
我也是这个情况，同求解决方法。
