### ISSUE TITLE
关于api.py里 /chat/** 的一些接口的问题，想咨询各位大佬

### ISSUE THREAD

**Issue by Wimet7** [chatchat-space/Langchain-Chatchat#1351]
**功能描述 / Feature Description**
想自己包装一个前端页面，但是流式输出用不了，调用完接口是一次性回复的，体验不好。接口入参的Stream改成了True，返参里确实是流式输出了，但实际上还是一次性返回。烦请大佬告知怎么使用接口才能实现流式输出。

**Comment by xiaofuliang** [comment]
@Wimet7 请问解决没，遇到同样问题

**Comment by hais1992** [comment]
@xiaofuliang 请问解决没，遇到同样问题

**Comment by zyjnicemoe** [comment]
可以使用SSE协议
1、 pip install sse_starlette.sse 
2、引入依赖: from sse_starlette.sse import  EventSourceResponse
3、将StreamingResponse改为EventSourceResponse

前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求

**Comment by zyjnicemoe** [comment]
> 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> 
> 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求

StreamingResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name),
                             media_type="text/event-stream")   改为  EventSourceResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name))

**Comment by AaronMKk** [comment]
> > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> > 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求
> 
> StreamingResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name), media_type="text/event-stream") 改为 EventSourceResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name))

前端怎么实现呀？有fetch的例子吗

**Comment by vCloudSail** [comment]
> 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> 
> 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求

你这写的是python代码，实际上前端使用sse还是一次性全部返回了

**Comment by zyjnicemoe** [comment]
> > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> > 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求
> 
> 你这写的是python代码，实际上前端使用sse还是一次性全部返回了

前端使用库@microsoft/fetch-event-source，使用方式如下:

import { fetchEventSource } from '@microsoft/fetch-event-source'
  fetchEventSource('请求接口', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `token内容`,
    },
    body: JSON.stringify(requestData),
    async onopen(response) {
       
    },
    async onmessage(event) {
     //消息在此处处理
    },
    async onerror(error) {
    
    },
    async onclose() {
   
    }
  })
}

**Comment by zyjnicemoe** [comment]
> > > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> > > 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求
> > 
> > 
> > StreamingResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name), media_type="text/event-stream") 改为 EventSourceResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name))
> 
> 前端怎么实现呀？有fetch的例子吗

直接使用fetch需要处理流，比较麻烦，建议使用微软的@microsoft/fetch-event-source，例子如下:
import { fetchEventSource } from '@microsoft/fetch-event-source'
  fetchEventSource('请求接口', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `token内容`,
    },
    body: JSON.stringify(requestData),
    async onopen(response) {
       
    },
    async onmessage(event) {
     //消息在此处处理
    },
    async onerror(error) {
    
    },
    async onclose() {
   
    }
  })
}

**Comment by AaronMKk** [comment]
> > > > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> > > > 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求
> > > 
> > > 
> > > StreamingResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name), media_type="text/event-stream") 改为 EventSourceResponse(knowledge_base_chat_iterator(query, kb, top_k, history, model_name))
> > 
> > 
> > 前端怎么实现呀？有fetch的例子吗
> 
> 直接使用fetch需要处理流，比较麻烦，建议使用微软的@microsoft/fetch-event-source，例子如下: import { fetchEventSource } from '@microsoft/fetch-event-source' fetchEventSource('请求接口', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `token内容`, }, body: JSON.stringify(requestData), async onopen(response) {
> 
> ```
> },
> async onmessage(event) {
>  //消息在此处处理
> },
> async onerror(error) {
> 
> },
> async onclose() {
> 
> }
> ```
> 
> }) }

感谢大佬~学习了

**Comment by supersoulsoul** [comment]
> > > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> > > 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求
> > 
> > 
> > 你这写的是python代码，实际上前端使用sse还是一次性全部返回了
> 
> 前端使用库@microsoft/fetch-event-source，使用方式如下:
> 
> import { fetchEventSource } from '@microsoft/fetch-event-source' fetchEventSource('请求接口', { method: 'POST', headers: { 'Content-Type': 'application/json', 'Authorization': `token内容`, }, body: JSON.stringify(requestData), async onopen(response) {
> 
> ```
> },
> async onmessage(event) {
>  //消息在此处处理
> },
> async onerror(error) {
> 
> },
> async onclose() {
> 
> }
> ```
> 
> }) }

请问你有没有遇到这个问题，后端改成了EventSourceResponse，前端也用了fetchEventSource库，但是在onmessage中接收数据时，它还像是后端在最后一次性触发了onmessage事件，具体表现就是最后一瞬间触发了上百次onmessage，还是达不到打字机效果。

**Comment by pengxianggui** [comment]
```
pip install sse_starlette.sse
```
似乎没有`sse_starlette.sse` 这个包啊？
