### ISSUE TITLE
关于chatglm.cpp在mac 上的安装

### ISSUE THREAD

**Issue by qianli918** [chatchat-space/Langchain-Chatchat#1352]
我找到了这个pr：#859
但是和现在的master代码感觉完全不一样，请问如何配置config model

**Comment by RandyZ** [comment]
这个怎么close了呢？chatglm.cpp convert之后的模型要如何结合在chatchat里？看859的PR的代码都删除了。是规划了其他方案吗？有资料能发一下不？

**Comment by jeceldx** [comment]
> 因为已经merge了，但这个是1.0的代码，2.0使用了fschat作为后端，跟这个没有关系了

请问目前v0.2.8有可以把chatglm.cpp convert后模型结合到chatchat的方案吗
