### ISSUE TITLE
生成webui界面时，gradio如何支持https

### ISSUE THREAD

**Issue by Gzj369** [chatchat-space/Langchain-Chatchat#1354]
请问执行 streamlit run webui.py 时，如何指定为https服务

**Comment by jason95054** [comment]
1. obtain SSL certificate and key (or self-signed SSL)
2. create a configuration file, config.toml, in your login directory, ~/.streamlit/:
[browser]
gatherUsageStats = false
[server]
headless = true
sslCertFile = '<path to>/server.crt'
sslKeyFile = '<path to>/server.key'

That's it

**Comment by Gzj369** [comment]
@jason95054 我是通过mkcert创建的cert和key，按照您说的配置可以通过https来访问页面了，非常感谢您！

**Comment by Gzj369** [comment]
@jason95054 大佬，遇到另外1个问题，我使用的k8s的pod来部署的LangChain，目前执行 streamlit run webui.py时，已经能指定为https进行访问了，但是在pod外部（本地）chrome浏览器访问，总是提示 https不安全，证书无效；
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/b5edc066-cfee-4319-8f5e-3e49507ef908)

查了很多资料，但**是没有像我这种在pod外访问的（因为pod内localhost的IP1和pod所在的服务器节点的IP2还不同），我本地访问时只能通过https://IP2:端口 访问，无法通过 https://IP1:端口**

pod内/etc/hosts文件已经做了如下修改： 
一、已新增2条配置
IP1 domain
IP2 domain
二、修改1条已有的配置
127.0.0.1 localhost domain


mkcert命令如下：
mkcert domain localhost 127.0.0.1 ::1 IP2
生成了 domain.pem 和 domain-key.pem 这2个文件
mkcert -install

~/.streamlit/config.toml 文件中sslCertFile 和 sslKeyFile 赋值如下：
sslCertFile = '/home/Langchain-Chatchat-master/domain.pem'
sslKeyFile = '/home/Langchain-Chatchat-master/domain-key.pem'

麻烦大佬有时间的话，帮忙看看

**Comment by jason95054** [comment]
Self-signed SSL is not a real SSL certificate and always got browser complaining. Since you made, you can trust it and ignore it.

**Comment by Gzj369** [comment]
所以chrome浏览器始终会提示不安全

非常感谢您！
