### ISSUE TITLE
[FEATURE] fastapi外链local_model_path如何设置不自动下载huggingface模型

### ISSUE THREAD

**Issue by uceehz0** [chatchat-space/Langchain-Chatchat#1357]
**功能描述**
已经在别的服务器上部署了大模型fastapi接口(本地显存不够运行)，想实现类似chatgpt那样外链。现在默认会加载local_model_path，如何不填或者忽略，不自动去下载huggiface模型

**Comment by zRzRzRzRzRzRzR** [comment]
使用最新的代码，接入自己的api即可
