### ISSUE TITLE
[BUG] docx文件导入解析报错

### ISSUE THREAD

**Issue by BlueCestbon** [chatchat-space/Langchain-Chatchat#1360]
问题描述：
在知识库管理页面，新建知识库之后再上传docx文件报错，但是上传pdf和txt就没有问题
On the knowledge base management page, an error was reported when uploading docx files after creating a knowledge base, but there was no problem when uploading pdf and txt
报的错：**soffice command was not found. Please install libreoffice
on your system and try again.**

是需要安装office吗，docker部署的是可以解析docx的，但是我进入容器没有找到office的进程，只有相关的pip依赖，这些依赖我用非docker运行的环境下也都有
Do I need to install office? The docker deployment can parse docx, but when I entered the container, I could not find the office process, only the related pip dependencies, which are also found in the environment I run with non-Docker

**环境信息 / Environment Information**
- langchain-Chatchat版本：0.2.2
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型：ChatGLM2-6B-32k 
- 使用的 Embedding 模型：m3e-large
- 使用的向量库类型 ： faiss 
- 操作系统及版本 / Operating system and version: Linux Centos7 kernel：3
- Python 版本 / Python version: 3.8

**报错日志 error log**
UnstructuredFileLoader
[E050] Can't find model 'zh_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
soffice command was not found. Please install libreoffice
on your system and try again.

- Install instructions: https://www.libreoffice.org/get-help/install-howto/
- Mac: https://formulae.brew.sh/cask/libreoffice
- Debian: https://wiki.debian.org/LibreOffice
INFO:     127.0.0.1:46466 - "POST /knowledge_base/update_doc HTTP/1.1" 200 OK

**Comment by jason95054** [comment]
First, pip install spacy (if not installed).
Then, python -m spacy download zh_core_web_sm

**Comment by BlueCestbon** [comment]
> 
Still the same error, and the container I started with docker, I found after entering the container did not have this zh_core_web_cm, but it was normal to parse docx. 

**env**
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> tokenizer = spacy.load("zh_core_web_sm")
>>> tokenizer("hello")
hello

**error log**
UnstructuredFileLoader
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
soffice command was not found. Please install libreoffice
on your system and try again.

- Install instructions: https://www.libreoffice.org/get-help/install-howto/
- Mac: https://formulae.brew.sh/cask/libreoffice
- Debian: https://wiki.debian.org/LibreOffice
INFO:     127.0.0.1:55086 - "POST /knowledge_base/upload_doc HTTP/1.1" 200 OK

**Comment by BlueCestbon** [comment]
> First, pip install spacy (if not installed). Then, python -m spacy download zh_core_web_sm

Still the same error, and the container I started with docker, I found after entering the container did not have this zh_core_web_cm, but it was normal to parse docx. 

**env**
Python 3.8.13 (default, Mar 28 2022, 11:38:47) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import spacy
>>> tokenizer = spacy.load("zh_core_web_sm")
>>> tokenizer("hello")
hello

**error log**
UnstructuredFileLoader
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
soffice command was not found. Please install libreoffice
on your system and try again.

- Install instructions: https://www.libreoffice.org/get-help/install-howto/
- Mac: https://formulae.brew.sh/cask/libreoffice
- Debian: https://wiki.debian.org/LibreOffice
INFO:     127.0.0.1:55086 - "POST /knowledge_base/upload_doc HTTP/1.1" 200 OK

**Comment by BlueCestbon** [comment]
After I installed libreoffice and configured the environment variables, I started using the shell, and it was able to parse normally. (and upgraded the version to 0.2.3)
