### ISSUE TITLE
文件无法向量化，显示错误cannot import name 'HOCRConverter' from 'pdfminer.converter' 

### ISSUE THREAD

**Issue by crazyQQQ777** [chatchat-space/Langchain-Chatchat#1365]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果：文件上传至知识库并向量化

**实际结果 / Actual Result**
描述实际发生的结果：文件可以已上传至知识库，但是无法向量化，点击向量化按钮就报错：cannot import name 'HOCRConverter' from 'pdfminer.converter'
![无标题](https://github.com/chatchat-space/Langchain-Chatchat/assets/54255983/00a0ecf6-c872-4778-acfc-299ce92e2925)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan-13b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-large
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by SwordHG** [comment]
不支持图片类型的pdf吧

**Comment by imClumsyPanda** [comment]
请升级至最新版本后重试。
