### ISSUE TITLE
使用gpt怎么更改模型始终使用的gpt-3模型

### ISSUE THREAD

**Issue by whatTheHellDie** [chatchat-space/Langchain-Chatchat#1368]
**问题描述 / Problem Description**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21169344/c976344c-9553-4e0c-8dcc-3c2b155a1c4e)
在你们今天发的新版中0.2.3，仍是提问了回复gpt3,也不是不是gpt-3.5-turbo，已配置如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21169344/3aa7967b-00fc-470c-a9b9-2928e579ee68)

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21169344/3e4fab51-c9ec-49d6-b195-ccf3a39bc465)
如上在openAI的gpt3.5中是回答3.5的，所以你们始终使用的3.0模型，期望实现配置化

**Comment by whatTheHellDie** [comment]
问4.0回复也是gpt4

**Comment by zRzRzRzRzRzRzR** [comment]
根据最新代码进行配置，把名字改成 模型名称改成openai的具体模型名称就行

**Comment by zaoqishibing** [comment]
我现在是0.2.6 仍然有这个问题

**Comment by whatTheHellDie** [comment]
> 我现在是0.2.6 仍然有这个问题

我现在知道了，你用的是gpt4，它的回答仍然是3，但实际是4，我查外国人的论坛知道的，官方就是不改回答
