### ISSUE TITLE
[BUG] 最新的版本知识库初始化失败

### ISSUE THREAD

**Issue by woshikid** [chatchat-space/Langchain-Chatchat#1369]
前几天pull的时候是好的
刚刚pull的版本出现如下问题：
ModuleNotFoundError: No module named 'zhipuai'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29223368/543f4ddd-7c5f-4cd9-b40d-c8c9198b422e)

**Comment by liunux4odoo** [comment]
后续会将zhipuai变为非必要依赖。当前先安装一下zhipuai即可解决该问题。
