### ISSUE TITLE
[FEATURE] Langchain的Agent能力

### ISSUE THREAD

**Issue by adner1986** [chatchat-space/Langchain-Chatchat#1373]
**功能描述 / Feature Description**
Langchain的Agent能力是否可以在新架构新版本中发扬一下
实现类似chatgpt的插件功能，
通过agent可以调用外部其他系统的api

**Comment by joeyhacker** [comment]
一些想法，通过Agent + Tools的模式来实现知识库检索的能力会更加强大；
1.  首先用户可以指定不同的Agent来实现不同的查询模式
2.  Agent通过分析问答来选择不同的Tool去检索知识库（检索知识库的功能本身也是个Tool，比如QA类、分析总结类、知识点提取类等）
3.  用户可以扩展多种Tools（相当于UDF）来丰富Agent的处理能力

**Comment by zRzRzRzRzRzRzR** [comment]
我们正在新版本中推出这个功能的雏形，期待开发者们共同参与
