### ISSUE TITLE
在webui中切换至其他模型出错

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1375]
**问题描述**
在web中切换Qwen模型时出错

**复现问题的步骤**
1.config文件中加入字段：
```
"Qwen-7B-Chat": {
        "local_model_path": "/root/gpt/model/Qwen-7B-Chat",  
        "api_base_url": "http://localhost:8888/v1",  # "URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
    }
```

2.`python starup -a`
3.web界面中切换模型为Qwen-7B-Chat

**预期的结果 / Expected Result**
正常回复。

**实际结果 / Actual Result**
无回复，且ternimal报错：
<img width="872" alt="eb5cb85e4b84e7d399ca352c0ff7d97" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/52522880/965f27d0-b531-45ba-86b8-311296795a63">

**config文件中的默认模型为Baichuan-13B-Chat，在web切换Qwen模型时会出现如上错误。
用--model-name Qwen-7B-Chat指定为Qwen时，在web切换Baichuan模型也会出现如上错误。
切换至其他的模型如chatglm2-6b，也会出错**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52522880/d5d9b969-1e33-45b7-9722-1809a0bcbfd8)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.3

- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-7B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.8.10

**Comment by zhilonglu** [comment]
me too，启动时候默认chatglm2，然后切换成别的模型，显示一直加载中

**Comment by zRzRzRzRzRzRzR** [comment]
请确定每个模型用的是不同的卡，并确认端口是否冲突后即可解决问题
