### ISSUE TITLE
如何设置 trust_remote_code=True ？我在运行python server/llm_api.py时，出现需要设置 trust_remote_code=True的提示 

### ISSUE THREAD

**Issue by wsh228581** [chatchat-space/Langchain-Chatchat#1376]
ValueError: Loading this model requires you to execute execute some code in that repo on your local machine. Make sure you have read the code at https://hf.co//home/sun/data/weishihao/LangChain/model to avoid malicious use, then set the option `trust_remote_code=True` to remove this error.

**Comment by zRzRzRzRzRzRzR** [comment]
这个要在fschat源码改，如果你是Huggingface下载的模型应该没有这个问题

**Comment by winterpi** [comment]
在fschat源码里修改哪些呢？
