### ISSUE TITLE
log日志出现很多空文件

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1379]
**问题描述 / Problem Description**
日历目录./log里面有很多空文件，如图所示：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52522880/32051276-251f-4d8f-a6e1-b9bd3abfc0b2)

**复现问题的步骤 / Steps to Reproduce**
1.执行webui界面，随便对话几句。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.3
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-7B
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.8.10

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
启动的时候log就会开始记录。
如果中间切换了模型也会有记录。
可以尝试更新到最新代码后看是否还有该问题。
