### ISSUE TITLE
向模型提问模型没有回答，终端显示无法访问chatglm的api

### ISSUE THREAD

**Issue by Luka0770** [chatchat-space/Langchain-Chatchat#1383]
![d44e2fc26007f6ef3f485529cb09917](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/a11e9b2d-1434-43b4-946e-6e02ad264971)
![a952c7b7963372e6db5cabbce8221d4](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/95bae193-77eb-4307-94c8-f242d7285e46)
![99a8743e2b1345450d8ce05f655ad21](https://github.com/chatchat-space/Langchain-Chatchat/assets/139829995/7a7584c6-201a-4dc9-84d3-c6ef35147aeb)

**Comment by jason95054** [comment]
Can you check the line at 2023-09-05 21:01:27 | ERROR | stderr | ERROR:   [Error 98] error while attempting to bind on address ('127.0.......?
Fix that error first.
