### ISSUE TITLE
LangChain v0.2.2 无法在webui选择特定的LLM或者Embedding吗

### ISSUE THREAD

**Issue by Gzj369** [chatchat-space/Langchain-Chatchat#1386]
请教一下，LangChain v0.2.2 无法在webui选择特定的LLM或者Embedding吗，之前v0.1版本有个类似后台管理的页面，可以在webui页面切换选择某个LLM 或者 某个Embedding，以及常用的调整参数，v0.2.2好像没看到，麻烦帮忙看看
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/3d6a2312-5575-405c-bd2b-a0f2e96d6344)

**Comment by imClumsyPanda** [comment]
1. v0.2.3页面中可以选择llm模型

2. v0.2.x版本中embedding模型修改为与向量库绑定，因为对于已建立的知识库，修改默认embedding模型将引发冲突。在新建知识库时，有选择embedding模型的选项。

**Comment by Gzj369** [comment]
> 1. v0.2.3页面中可以选择llm模型
> 2. v0.2.x版本中embedding模型修改为与向量库绑定，因为对于已建立的知识库，修改默认embedding模型将引发冲突。在新建知识库时，有选择embedding模型的选项。

好的，感谢大佬
