### ISSUE TITLE
[FEATURE] 只需要本地运行ChatGlm的情况下，model_config.py文件下的建议

### ISSUE THREAD

**Issue by AaronMKk** [chatchat-space/Langchain-Chatchat#1389]
如果Linux服务器连不上Openai并且只想本地运行ChatGlm的情况，如果出现WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
可以做如下改变：
llm_model_dict = {
    "chatglm2-6b": {
        "local_model_path": "/home/XX/chatglm2-6b",
        "api_base_url": "http://10.12.345.67:8888/v1", 
        "api_key": "EMPTY"
    },
}

llm_model_dict = {
    "chatglm2-6b": {
        "local_model_path": "/home/XX/chatglm2-6b",
        "api_base_url": "http://10.12.345.67:8899/v1"，
        "api_key": "EMPTY"
    },
}

**Comment by zhuhaifengaaa** [comment]
试了，不行

**Comment by zRzRzRzRzRzRzR** [comment]
model_config随着版本变化 变化内容较多，我们将会根据issue来进行适当修改，尽量减少配置成本
