### ISSUE TITLE
api请求格式

### ISSUE THREAD

**Issue by iReuters** [chatchat-space/Langchain-Chatchat#1391]
我在远程服务器上部署的模型，打不开fastapi 的docs界面，所以看不到请求格式，可不可以帮忙发一下，包括聊天的和知识库问答。

**Comment by whh1009** [comment]
远程服务器上把`127.0.0.1` 改成 真实的`ip` 试试

如果用的域名，那就在代理到这个`ip`

**Comment by SnowyLchen** [comment]
{
  "query": "恼羞成怒",
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": false,
  "model_name": "chatglm2-6b",
  "temperature": 0.7
}

**Comment by zRzRzRzRzRzRzR** [comment]
可以打开7861端口的doc查看
