### ISSUE TITLE
[BUG] PDF文件上传至知识库出错

### ISSUE THREAD

**Issue by XWJ-98** [chatchat-space/Langchain-Chatchat#1393]
**问题描述 / Problem Description**
向知识库中添加一个pdf文件，出现报错如下。
operands could not be broadcast together with shapes (736,992) (1,1,3)

有的pdf可以成功，大多是都是报错

求问，应该咱们解决

**Comment by imClumsyPanda** [comment]
可通过升级依赖包 rapidocr_onnxruntime 以解决这一问题
```
pip install rapidocr_onnxruntime==1.3.2
```

**Comment by XWJ-98** [comment]
> 可通过升级依赖包 rapidocr_onnxruntime 以解决这一问题
> 
> ```
> pip install rapidocr_onnxruntime==1.3.2
> ```

感谢！！解决了
