### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by liangyuan1** [chatchat-space/Langchain-Chatchat#1396]
**原文：**

范县水厂压力计，今日压力：0.1Mpa昨天：0.3Mpa2023-08-09 12:32:32 0.2Mpa2023-08-10 12:32:32 0.2Mpa 

**划分后的文段：**

范县水厂压力计
今日压力：0.1Mpa
昨天：0.3Mpa
2023-08-09 12:32:32 0.2Mpa
2023-08-10 12:32:32 0.2Mpa 

**Context（可选）：**

**Comment by imClumsyPanda** [comment]
与用例征集中内容重复，故关闭本issue
