### ISSUE TITLE
是否可以增加向量召回的阈值设定，有些召回内容相关性太低，导致模型胡言乱语

### ISSUE THREAD

**Issue by qianglegend** [chatchat-space/Langchain-Chatchat#140]
如题

**Comment by imClumsyPanda** [comment]
目前有在研究实现方法，暂时还没搞定

qianglegend ***@***.***>于2023年4月20日 周四08:53写道：

**Comment by imClumsyPanda** [comment]
在最新版的v0.1.6中已经可以返回了，但是因为没有归一化，所以没有默认显示，输出方式可以参考cli_demo.py第40行注释的代码

下一步会增加归一化和阈值判断功能

**Comment by xupengrun** [comment]
为啥不做归一化？
