### ISSUE TITLE
[FEATURE] 使用 PDF 作为本地知识库时，对话中显示 PDF 页号

### ISSUE THREAD

**Issue by yulangz** [chatchat-space/Langchain-Chatchat#1400]
**功能描述 / Feature Description**
在使用 PDF 作为本地知识库时，问答的时候是否可以给出出处的 PDF 页号，如 [chatpdf](https://www.chatpdf.com/) 那样。

**解决的问题 / Problem Solved**
在对话是定位出处可以更加方便。

**实现建议 / Implementation Suggestions**
在语料切分的时候，带上 PDF 页号信息，并让模型在输出的时候带上页号信息。

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
无

**Comment by zRzRzRzRzRzRzR** [comment]
收到建议，
目前，语料切分并没有针对不同的类型进行切分（csv除外）
我们开设了自定义分词器，可以让用户根据自己的需求切分
我们将尽量满足各位开发者的要求，感谢您的支持
