### ISSUE TITLE
通过startup.py启动服务后只能本机访问

### ISSUE THREAD

**Issue by roy501-luo** [chatchat-space/Langchain-Chatchat#1402]
操作系统：m1
版本：0.2.3版本
启动方式：python startup.py -a 只能本机访问

启动方式改为：python server/api.py 
可以正常访问

**Comment by sducxh** [comment]
同样情况

**Comment by zhuhaifengaaa** [comment]
请问一下，如果想让任意电脑访问的话，
这种启动方式：python server/api.py，需要修改什么内容呢？

**Comment by roy501-luo** [comment]
<img width="902" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/11643302/636c1ff0-3dc8-4f56-876a-a59d8df25baf">

解决了，具体修改见上图

https://stackoverflow.com/questions/75040507/how-to-access-fastapi-backend-from-a-different-machine-ip-on-the-same-local-netw
