### ISSUE TITLE
启动api服务以后出现Invalid request url: /docs

### ISSUE THREAD

**Issue by yrfmessi** [chatchat-space/Langchain-Chatchat#1404]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/40223416/e1f9a5fd-3ce7-4214-9f69-eb2e3a50981a)
网页报307错误

**Comment by zRzRzRzRzRzRzR** [comment]
本地网络环境问题，请检查自己的网络环境，更新到最新代码检查是否出现问题，可以重新提出issue
