### ISSUE TITLE
知识文档向量化时，可以选择  EMBEDDING_MODEL 、CHUNK_SIZE

### ISSUE THREAD

**Issue by sducxh** [chatchat-space/Langchain-Chatchat#1405]
**功能描述 / Feature Description**
上传【知识文件】，向量化时可以选择  EMBEDDING_MODEL 、CHUNK_SIZE

**解决的问题 / Problem Solved**
目前是在 model_config.py 全局配置的，所有文件共用配置，增强灵活性

**实现建议 / Implementation Suggestions**
UI 增加 select box

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
可参考 dify 项目

**Comment by imClumsyPanda** [comment]
1. embedding model目前是和知识库绑定的，在新建知识库时有选项进行选择，如需对已建立的知识库修改向量化模型，需要进行整个知识库重建，改过程时间相对较长，建议直接参考readme中知识库迁移部分进行。

2. chunk size后续会考虑在自定义textsplitter效果相对稳定后提供选项，但仍存在不同用户通过各自界面修改，可能影响其他用户该参数设置的问题。

**Comment by Gzj369** [comment]
> 1. embedding model目前是和知识库绑定的，在新建知识库时有选项进行选择，如需对已建立的知识库修改向量化模型，需要进行整个知识库重建，改过程时间相对较长，建议直接参考readme中知识库迁移部分进行。
> 2. chunk size后续会考虑在自定义textsplitter效果相对稳定后提供选项，但仍存在不同用户通过各自界面修改，可能影响其他用户该参数设置的问题。

大佬，针对第2点，请问可以像v0.1.x版本那样，把配置页面做个权限校验，只让部分同事-比如管理员才能编辑修改配置参数吗

**Comment by zRzRzRzRzRzRzR** [comment]
最新的模型已经可以自己选择chunksize，针对权限校验问题，这个可能要在对应的落地方案才会针对自己的场景进行开发。
