### ISSUE TITLE
[BUG] failed change model from chatglm2-6b to Qwen-7B-Chat (v0.2.3)

### ISSUE THREAD

**Issue by cspung** [chatchat-space/Langchain-Chatchat#1406]
**问题描述 / Problem Description**
WebUI界面中，切换模型失败

**复现问题的步骤 / Steps to Reproduce**
1. 一键启动：python startup.py -a
2. 进入webUI界面，选择LLM模型
3. 
<img width="298" alt="langchainv0 2 3_running" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/87854494/b22a7ed0-6d1a-4e6b-96bc-4c1fe69ffb32">

4.  
![langchainv0 2 3_changemodel](https://github.com/chatchat-space/Langchain-Chatchat/assets/87854494/8bb3e21d-817a-42ae-96e6-e23ba1a140c6)

**预期的结果 / Expected Result**
模型切换到Qwen-7B-Chat，能够对话

**实际结果 / Actual Result**
failed change model from chatglm2-6b to Qwen-7B-Chat 

**环境信息 / Environment Information**
- langchain-ChatChat v0.2.3
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：（ChatGLM2-6B / Qwen-7B 等）
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu20.04
- Python 版本 / Python version:3.8.13

**附加信息 / Additional Information**
model_config中修改LLM_MODEL=Qwen-7B-Chat，重新启动，可以正常加载Qwen-7B-Chat模型；
另外，在第一个图片中，带Running的模型/api可以正常切换

**Comment by liunux4odoo** [comment]
dev分支已经修复了LLM切换的问题，你可以测试一下？

**Comment by cspung** [comment]
> 

试了一下，可以正常切换模型了
