### ISSUE TITLE
[BUG] 缺少模块 / zh_core_web_sm

### ISSUE THREAD

**Issue by Jerryyaozl** [chatchat-space/Langchain-Chatchat#1408]
**缺少模块 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'   添加文档
2. 点击 '...' / Click '...' 占击“添加文档到知识库”
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs ， 日志中出现  [E050] Can't find model 'zh_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information** autodl v7 默认配置

**Comment by tommyvinny** [comment]
docker制作时候加入
在RUN pip install -r requirements.txt 之后加入
RUN pip install PyMuPDF # 轻量级PDF，XPS和电子书查看器
RUN pip install spacy # spacy是Python自然语言处理（NLP）软件包             
RUN python -m spacy download zh_core_web_sm # Chinese pipeline optimized for CPU
RUN python -m spacy download en_core_web_sm # English pipeline optimized for CPU
RUN pip install rapidocr_onnxruntime # 整合PaddleOCR v4模型到rapidocr系列包中
RUN pip install rapidocr-onnxruntime # Python版RapidOCR

或进入控制台执行
pip install PyMuPDF
pip install spacy            
python -m spacy download zh_core_web_sm
python -m spacy download en_core_web_sm
pip install rapidocr_onnxruntime
pip install rapidocr-onnxruntime
