### ISSUE TITLE
输入长度问题

### ISSUE THREAD

**Issue by doublexxking** [chatchat-space/Langchain-Chatchat#141]
感谢作者支持ptuning微调模型。
有个关于输入长度的问题，ptuning 微调时候需要设置max_source_length，假设我设置为64。微调数据为纯问答，不包含匹配到已知内容。
chatglm支持 2048输入长度。
不知道现在微调时需要增大max_source_length 让他包含langchain infer时候的长度么？比如从64改为2048，这是否是有必要的？还是依旧64,让他适配我的微调数据即可。

**Comment by imClumsyPanda** [comment]
抱歉 暂时还没有做模型的ptuning工作，可能要看看其他朋友是否知道如何解决了
