### ISSUE TITLE
[BUG] 为什么用智普 api 会报APIConnectionError: Error communicating with OpenAI 的错误

### ISSUE THREAD

**Issue by yuming-L** [chatchat-space/Langchain-Chatchat#1410]
版本 v0.2.3

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/56901320/68d8112c-179d-413b-9d5c-dedd47454089)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/56901320/045babfd-6d84-4537-90ab-1d0f24133da9)

**Comment by kungkook** [comment]
我也是，你解决了嘛

**Comment by gittjob** [comment]
怎么解决啊

**Comment by qinb** [comment]
+1

**Comment by imClumsyPanda** [comment]
请问除上述retry信息外是否有其他报错信息？

**Comment by zhuhaifengaaa** [comment]
+1
