### ISSUE TITLE
【解决方案】关于使用非GPT模型还继续报错Error communicating with OpenAI。

### ISSUE THREAD

**Issue by syopenai** [chatchat-space/Langchain-Chatchat#1415]
我修改了两处地方：
1.model_config.py 
修改前：
"chatglm2-6b": {
        "local_model_path": "THUDM/chatglm2-6b",
        "api_base_url": "http://localhost:8888/v1",  # URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
修改后：
"chatglm2-6b": {
        "local_model_path": "D:\ChatGLM2-6B",
        "api_base_url": "http://192.168.3.71:8888/v1",  # URL需要与运行fastchat服务端的server_config.FSCHAT_OPENAI_API一致
        "api_key": "EMPTY"
2. model_config.py 
修改前:
    "gpt-3.5-turbo": {
        "api_base_url": "https://api.openai.com/v1",
        "api_key": os.environ.get("OPENAI_API_KEY"),
        "openai_proxy": os.environ.get("OPENAI_PROXY")
修改后：
   #"gpt-3.5-turbo": {
        #"api_base_url": "https://api.openai.com/v1",
        #"api_key": os.environ.get("OPENAI_API_KEY"),
       # "openai_proxy": os.environ.get("OPENAI_PROXY")
    #},
修改之后我就可以进行访问了。注：IP地址需要跟server_config.py 一样。

**Comment by gittjob** [comment]
Error communicating with OpenAI  我也遇到了

**Comment by jianzhengming** [comment]
还是不行呢

**Comment by zRzRzRzRzRzRzR** [comment]
请关注最新代码，并按照新的配置文件来写
