### ISSUE TITLE
删除知识库报错

### ISSUE THREAD

**Issue by shujun1992** [chatchat-space/Langchain-Chatchat#1417]
No such file or directory: '/opt/xxxxxx/lib/python3.10/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map'

**Comment by shujun1992** [comment]
我在网上下载bootstrap.min.css.map后放到对应目录解决了这个报错，但是知识库依然没删掉，也没提示报错

**Comment by shujun1992** [comment]
最终通过rm -rf 删除知识库目录，看看作者能否复现

**Comment by aben1900** [comment]
问题没解决怎么就把issue关闭了？？？？？
