### ISSUE TITLE
启动时加载模型失败

### ISSUE THREAD

**Issue by tendrillion** [chatchat-space/Langchain-Chatchat#1421]
python startup.py -a 启动时没有成功加载模型，没有Loading checkpoint shards过程，导致web界面提问没有响应，不能正常回答，后端提示：400 Bad Request
Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"Only chatglm-api allowed now, your model chatglm2-6b","code":40301}' (HTTP response code was 400).

python server/llm_api.py 启动能正常加载模型。

**Comment by xjw00654** [comment]
这个问题实际上是因为`server/utils.py:L211`里面验证是否是本地模型导致的，代码里写的是`if not os.path.isdir(config.get("local_model_path", "")):`，如果使用hf的cache的话默认会被当成online model。
所以如果非要可用的话直接把这行改成`not config.get("local_model_path", ""):`就行。但是不是最佳解决方案 0.0

**Comment by Chrosea** [comment]
> @lhua1980 @tendrillion 这个问题实际上是因为`server/utils.py:L211`里面验证是否是本地模型导致的，代码里写的是`if not os.path.isdir(config.get("local_model_path", "")):`，如果使用hf的cache的话默认会被当成online model。 所以如果非要可用的话直接把这行改成`not config.get("local_model_path", ""):`就行。但是不是最佳解决方案 0.0

对的实际上默认情况本地模型根本不会load，这已经属于恶性bug了
