### ISSUE TITLE
请问生成文本长度限制在哪设置。

### ISSUE THREAD

**Issue by renllll** [chatchat-space/Langchain-Chatchat#1423]
每次文本生成超不过1000字

**Comment by joeyhacker** [comment]
knowledge_base_chat.py 里面
model = ChatOpenAI(
            temperature=0,
            streaming=True,
            verbose=True,
            callbacks=[callback],
            openai_api_key=llm_model_dict[LLM_MODEL]["api_key"],
            openai_api_base=llm_model_dict[LLM_MODEL]["api_base_url"],
            model_name=LLM_MODEL
        )

这里面有个 `max_tokens` ，但现在好像这个参数没放出来；
