### ISSUE TITLE
[BUG] 跑一个PDF的时间耗时非常长，且页面添加至向量库，日志提示执行成功，页面还在running

### ISSUE THREAD

**Issue by DJasonlin** [chatchat-space/Langchain-Chatchat#1424]
在0.2.3版本下执行，存在一个pdf执行时间过长的问题
<img width="1030" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/d4618c80-bf5e-4e3a-86a7-284d0ee24578">
在页面上点击添加至向量库开始，到langchain.text_splitter分词，一个pdf文件花了8分多钟
然后日志中提示执行成功
<img width="714" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/e4bb978a-3b0b-4776-86d2-3ac77024fed8">
页面还提示running中
<img width="877" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/5cf1e2c7-0a6e-4790-9a27-7826e8005a85">

**Comment by DJasonlin** [comment]
作为对比，在0.2.2版本中，同一个pdf文件，添加到向量库的耗时如下：
<img width="959" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/808ba540-c5cd-4880-a0da-9b079476682f">
<img width="1037" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/37cb8894-fae6-4caa-b39d-c33ca57272dc">
整体耗时一分钟不到

**Comment by Gzj369** [comment]
是不是文档加载器不同导致的，v0.2.3版本新增支持了对pdf 中图片的识别，换了1个加载器

**Comment by DJasonlin** [comment]
> 是不是文档加载器不同导致的，v0.2.3版本新增支持了对pdf 中图片的识别，换了1个加载器

加载器确实换了，但是这个加载器的性能确实不太行，不知道是否有解法

**Comment by Lijia0** [comment]
我遇到的情况是日志没有提示成功，一直显示running。上传小一点的pdf就没事，15MB的就不行

**Comment by DJasonlin** [comment]
> 我遇到的情况是日志没有提示成功，一直显示running。上传小一点的pdf就没事，15MB的就不行

我测试的，还是只有几M的PDF，也得跑很久

**Comment by Gzj369** [comment]
是的，我现在也发现跑得很长时间，上传几M的文件还行，然后上传了1个15.9M的就报如下错误了：
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.10/site-packages/rapidocr_onnxruntime/utils.py", line 73, in __call__
    return self.session.run(self.get_output_names(), input_dict)
  File "/root/anaconda3/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running Conv node. Name:'batch_norm_3.tmp_2_nchwc' Status Message: Invalid input shape: {1,0}

**Comment by zhilonglu** [comment]
为什么我加载一个2M的文件总报错，libGL.so.1: cannot open shared object file: No such file or directory

**Comment by DJasonlin** [comment]
> 你是怎么上传的，是不是要重新初始化知识向量库

跟上传方式没关系吧。不论是页面上传的还是手动init_database跑脚本，都是一样的结果
