### ISSUE TITLE
[BUG] 不是很明白在知识库管理页面，点击某个文件，要请求后台并且刷新页面的逻辑

### ISSUE THREAD

**Issue by DJasonlin** [chatchat-space/Langchain-Chatchat#1425]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5448531/4c511023-d0f0-4d67-8c66-8b16ae5435ac)
在知识库管理页面，单击某个文件，总是要请求后台，并且页面会刷新（第一次点击的时候）。如果页面使用了分页，每次翻页点击，就会刷新跳转到第一页。
不是特别明白，点击刷新的原因是什么

**Comment by liunux4odoo** [comment]
这是streamlit的机制，UI控件状态变化时会触发后台rerun，具体可以搜索streamlit相关文档。
