### ISSUE TITLE
[BUG] 报错：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by zzflybird** [chatchat-space/Langchain-Chatchat#1429]
**问题描述 / Problem Description**
1、第一种情况，在与ChatGLM2B模型对话时，问题中有字典数据，也就是含有{}这样的大括号，第二次问答就会报以下错误：
![Snipaste_2023-09-21_11-18-30](https://github.com/chatchat-space/Langchain-Chatchat/assets/26504661/4d6146da-4307-4453-a94a-fc866a15060d)

```
peer closed connection without sending complete message body (incomplete chunked read)
```

2、第二种情况，让模型写C++代码，输出带有{}的文本，第二次问答时也会报错。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26504661/0856c69b-d089-40e1-9f89-ae43e251bf05)

**复现问题的步骤 / Steps to Reproduce**
问模型问题，然后让其继续。

**预期的结果 / Expected Result**
模型继续回答未回答的问题。

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26504661/0856c69b-d089-40e1-9f89-ae43e251bf05)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.3
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu 22.04
- Python 版本 / Python version: 3.10

**Comment by zzflybird** [comment]
更新到0.2.4版本后，该问题解决。

**Comment by IssacCzy** [comment]
> 更新到0.2.4版本后，该问题解决。

我最新版本 0.2.6 不知道怎么又出现这个问题了，您可以看下问题 [#1916](https://github.com/chatchat-space/Langchain-Chatchat/issues/1969)
