### ISSUE TITLE
doc文档中的表格好像无法识别

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#1430]
我将doc文档载入知识库提问，文字部分内容问答还有准确率，但涉及到表格内容，就完全问不出来了，知识库匹配结果显示也往往没有表格，是目前的分段方法无法把表名和表格联系起来吗？

**Comment by SwordHG** [comment]
目前的分段方法无法把表名和表格联系起来

**Comment by rabum** [comment]
哎，不知道有什么好的办法可以做到两者的联系呢

**Comment by zRzRzRzRzRzRzR** [comment]
之后的开发将会解决这个问题，预计三个版本内解决
