### ISSUE TITLE
知识库问答模式调用流式API，返回的结果中冗余重复的docs内容是否需要优化下

### ISSUE THREAD

**Issue by zoidburg** [chatchat-space/Langchain-Chatchat#1431]
在知识库问答模式调用流式API时，将以event stream的形式返回生成结果；其中有answer和docs两个字段，分别对应生成token和知识库reference信息。返回各个token时，对应的docs字段内容是冗余的
knowledge_base_chat.py代码中对应处理逻辑：
```
if stream:
    async for token in callback.aiter():
    # Use server-sent-events to stream the response
        yield json.dumps({"answer": token, "docs": source_documents},  ensure_ascii=False)
```
生成每个token都对应相同的source_documents值，是否需要优化下不返回重复冗余的docs内容

**Comment by liunux4odoo** [comment]
开发版中已修复该问题。
