### ISSUE TITLE
[BUG] 知识库搜索，一模一样的内容搜不到

### ISSUE THREAD

**Issue by H9990HH969** [chatchat-space/Langchain-Chatchat#1433]
我把一份简单的QA txt扔到知识库里面，用的是faiss和ernie-base。然后一模一样复制问题，结果显示”根据已知信息，无法回答该问题。“。而且知识库匹配不到。
其他： 1、生成知识库时没有报错，数据也生成好了 2、 知识库能匹配到，但是都不怎么相关
![1694427103317](https://github.com/chatchat-space/Langchain-Chatchat/assets/133352113/b2054880-5a31-41f2-b09d-364a3cc2081f)
![1694427421689](https://github.com/chatchat-space/Langchain-Chatchat/assets/133352113/f56ec9b4-9408-4015-a61d-504a579ac60e)

txt格式  ：
Q：XXXXXXXXXX A：XXXXXXXXXXX
Q：XXXXXXXXXX A：XXXXXXXXXXX
Q：XXXXXXXXXX A：XXXXXXXXXXX

- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：ernie-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 centos 7
- Python 版本 / Python version: 3.10

**Comment by soultrans** [comment]
遇到了同样的问题，目前尝试了以下操作：
1.调整问答对的格式，如：Q：xxxxx\nA:xxxxx
2.在Prompt中进行提示说明，如“根据上述问答对信息来回答问题”、“问句如果与已知问句语义相似，可使用对应答案句进行回答”等

发现调整后，仍然会存在（1）检索不到回答不出；（2）检索到相关来源同样回答不出的情况；
推测是底座模型推理的模型问题，后续准备尝试对问答对语料进行训练（还未验证具体效果）

**Comment by AaronMKk** [comment]
> 

会不会是因为题主想匹配的这些内容，太过于小众，知识库里面不存在？

**Comment by H9990HH969** [comment]
知识库是自己的，就400条问答数据
@AaronMKk

**Comment by H9990HH969** [comment]
我觉得是匹配是向量数据库有些问题，他就没有匹配到一模一样的信息
@soultrans

**Comment by soultrans** [comment]
> 我觉得是匹配是向量数据库有些问题，他就没有匹配到一模一样的信息 @soultrans

向量数据库匹配是一方面，构建问答对的时候，用后续输入的问句与已有的问答对匹配，随着数据增多，匹配到比较符合的前几个很有可能不是同样问题的问答对，这很正常

另一个方面，虽然能检索到相应的问答对信息，现有LLM在做理解和生成上也存在局限性问题

**Comment by soultrans** [comment]
@H9990HH969 你可以尝试垂直式的问题向量库构建，只把问题（Q）录入向量库，检索到对应的问题后，再把相应的答案找到，进行后续操作

**Comment by SwordHG** [comment]
你可以看下spacytextspliter这个文本分割方式，也看下分割后的文本样子，常理来说分割后文本长度较长，向量表示后，和你想要搜索的query向量表示相差已经比较大了，可以换一下textspliter试一下，再向量化，基本能解决问题

**Comment by wei8163** [comment]
确实会匹配不到，回退到0.1.7就好了，新版这个匹配问题是个大坑，希望官方赶紧填上

**Comment by kevindany** [comment]
> 

你解决了吗？我用的v0.2.4-preview版本。
碰到同样的问题，即使输入的文字和向量中的内容完全一样了（向量score=0.0），还是提示：根据已知信息，无法回答该问题。

**Comment by H9990HH969** [comment]
> 你可以看下spacytextspliter这个文本分割方式，也看下分割后的文本样子，常理来说分割后文本长度较长，向量表示后，和你想要搜索的query向量表示相差已经比较大了，可以换一下textspliter试一下，再向量化，基本能解决问题
@SwordHG 
我自己写了个文本划分，是可以正常用的。   
但我发现，真实问题并不是这些。
真正的问题是，我刚建好的数据库，可以正常问问题，但过了一段时间后，我刷新再用这个数据库，结果就什么都匹配不到了

**Comment by roki1031** [comment]
> 确实会匹配不到，当然不是完全匹配不到，新版的向量匹配性能下降了大概一个数量级，根据文档原文按着问一些稍微细致一些的问题就走不了langchain了，除非你是直接问一些小节的标题，否则80%概率全是模型在乱发挥。
> 
> 回退到0.1.17就好了，这个问题就能完全的修复。
> 
> 0.2.X新版这个匹配问题是个大坑，希望官方赶紧修复。

希望官方可以修复一下 @imClumsyPanda

**Comment by WilliamChen-luckbob** [comment]
同样的问题，我的场景是同类型机型，不同的型号有略微不同的细节，我自行修改了metadata，并在其中嵌入了当前文本出自哪个型号的文档，在实际搜索时最佳匹配选择5，结果就算是指明要某个型号，最佳匹配中一个对应的正确型号都没有

**Comment by justforword** [comment]
> 确实会匹配不到，当然不是完全匹配不到，新版的向量匹配性能下降了大概一个数量级，根据文档原文按着问一些稍微细致一些的问题就走不了langchain了，除非你是直接问一些小节的标题，否则80%概率全是模型在乱发挥。
> 
> 回退到0.1.17就好了，这个问题就能完全的修复。
> 
> 0.2.X新版这个匹配问题是个大坑，希望官方赶紧修复。

一样的问题

**Comment by zRzRzRzRzRzRzR** [comment]
我们在0.2.5的版本中进行了以下测试
模型：Qwen-14B-Chat chatglm2-6b Qwen-7B-Chat Baichuan2-7B-Chat Baichuan2-13B-Chat GPT4 GPT3.5 glm130B
嵌入模型： bge-large-zh
我们放入了一些纯文本知识库进行测试，未出现上述情况

可以更新到最新的代码后尝试一下是否还有出现这个问题

**Comment by quartets** [comment]
我用的是0.2.5版本，问题和楼主描述一模一样。pdf 的知识库文件还能回答点儿，txt、csv 等文档的内容完全回答不了。

**Comment by qazwsx042** [comment]
遇到同样的问题：输入txt文件构建知识库，新建知识库未报错，但LLM无法回答其中的内容。

**Comment by Jieszs** [comment]
用 txt 分得不是很好，用 csv会好一点。
主要大模型会乱回答，这个不太好

**Comment by zRzRzRzRzRzRzR** [comment]
针对以上问题，主要是三个方面的改进
1. 从读入数据的角度，自定义分词器和loader能更好的支持各种各样的文件
2. 从大模型回答的角度，更好的提示词和适合自己场景的提示词是很重要的，并且建议换一个支持文本更长，理解能力更强的模型，同时，换一个更好的embed模型例如bge-large-zh-v1.5，必要时刻可以微调嵌入模型。
3. 从框架的角度，目前在搜索部分 0.2.x和0.1.x确实算法不同，召回方面有一定的差距，在某些场景甚至是降低的，这个我们也意识到了，我们将会在这方面进行改进，提升召回率。
4. 从知识库的角度，尽量让知识库之间的混淆信息减少，以降低向量匹配时候的难度

**Comment by quinwu** [comment]
> 我们在0.2.5的版本中进行了以下测试 模型：Qwen-14B-Chat chatglm2-6b Qwen-7B-Chat Baichuan2-7B-Chat Baichuan2-13B-Chat GPT4 GPT3.5 glm130B 嵌入模型： bge-large-zh 我们放入了一些纯文本知识库进行测试，未出现上述情况
> 
> 可以更新到最新的代码后尝试一下是否还有出现这个问题

能说明下搜索方式有什么不同吗？在官方还未发版的时候，我可以先本地更新下

**Comment by Alfer-Feng** [comment]
> 针对以上问题，主要是以下几个方面的改进
> 
> 1. 从读入数据的角度，自定义分词器和loader能更好的支持各种各样的文件
> 2. 从大模型回答的角度，更好的提示词和适合自己场景的提示词是很重要的，并且建议换一个支持文本更长，理解能力更强的模型，同时，换一个更好的embed模型例如bge-large-zh-v1.5，必要时刻可以微调嵌入模型。
> 3. 从框架的角度，目前在搜索部分 0.2.x和0.1.x确实算法不同，召回方面有一定的差距，在某些场景甚至是降低的，这个我们也意识到了，我们将会在这方面进行改进，提升召回率。
> 4. 从知识库的角度，尽量让知识库之间的混淆信息减少，以降低向量匹配时候的难度

你好，请问0.2和0.1版本的匹配算法有什么不同吗？我的理解是两个版本都是文本分块算法（稍微不同）+m3e-base匹配模型（相同）。

**Comment by zRzRzRzRzRzRzR** [comment]
两个算法不一样
0.2 中仅仅用Embed模型进行对比
0.1 会寻找关键词附近的上下文

总的来说.0.1.x 的知识库效果确实好于0.2.x
在未来的0.2.x版本我们会加入0.1.x的这个功能让开发者选，同时，0.2.x我们有更多的支持，例如自定义分词器等
在未来我们将做到0.2.x版本的匹配率理论上不低于0.1.x

**Comment by tms2003** [comment]
问题很大，造成chatchat事实上的不可用

**Comment by youxiaomin** [comment]
> > 你可以看下spacytextspliter这个文本分割方式，也看下分割后的文本样子，常理来说分割后文本长度较长，向量表示后，和你想要搜索的query向量表示相差已经比较大了，可以换一下textspliter试一下，再向量化，基本能解决问题
> > @SwordHG
> > 我自己写了个文本划分，是可以正常用的。
> > 但我发现，真实问题并不是这些。
> > 真正的问题是，我刚建好的数据库，可以正常问问题，但过了一段时间后，我刷新再用这个数据库，结果就什么都匹配不到了

我也是！一段时间后就会搜不到，太诡异了

**Comment by Aikoin** [comment]
调整分数阈值，从1调到1.5

**Comment by hepj987** [comment]
> 调整分数阈值，从1调到1.5

请问一下都做了哪些设置呢？ 我打印了一下查询分数发现 分数都在100以上。
目前我开启了distance_strategy="MAX_INNER_PRODUCT"和METRIC_INNER_PRODUCT“”,normalize_L2=True 或者False都进行了尝试但是都没有什么效果，分数出来还是150左右

**Comment by herryRiver** [comment]
我重新用git clone方式下载了bge-large-zh-v1.5，好使了，可能是zip下载出行了文件错误

**Comment by TZJ12** [comment]
怎么加入寻找关键词附近的上下文的功能呢，我使用的是chatchat2.10版本，也遇到了召回效果不好的问题
