### ISSUE TITLE
是否无法通过前端直接切换模型？

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#1438]
我在本机下载好了tigerbot和baichuan的模型权重文件，通过chatchat启动的时候，只有configs/model_config.py文件LLM_MODEL所指定的模型能正常工作，切换模型的时候就会出现I nvalid response object from API: '{"object":"error","message":"Only baichuan2-13b allowed now, your model baichuan-13b","code":40301}' (HTTP response code was 400).这样的错误
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/8f7e984a-2366-483f-8d79-3fd7e95152a5)
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/e7f55919-256b-4556-bdab-07f6340e9871)

**Comment by liunux4odoo** [comment]
0.2.3模型切换功能有点问题，下个版本会修复。
