### ISSUE TITLE
[BUG] 调用本机模型出现Error communicating with OpenAI的问题

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#1439]
configs/model_config.py配置如下
`
llm_model_dict = {
    "baichuan-13b": {
        "local_model_path": "/data/LLM_Project/Baichuan-13B-Chat",
        "api_base_url": "http://172.17.27.158:8888/v1",
        "api_key": "EMPTY"
    },
    "baichuan2-13b": {
        "local_model_path": "/data/LLM_Project/Baichuan2-13B-Chat",
        "api_base_url": "http://172.17.27.158:8889/v1",
        "api_key": "EMPTY"
    },
    "tigerbot-13b": {
        "local_model_path": "/data/LLM_Project/Tigerbot-13b-chat-V2",
        "api_base_url": "http://172.17.27.158:8890/v1",
        "api_key": "EMPTY"
    },

LLM_MODEL = "baichuan2-13b"
`

通过前端进行推理时卡住没有响应，日志返回报错
![3](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/88dbe92e-546f-484d-8132-397421cc8c36)

**Comment by liunux4odoo** [comment]
请仔细看文档，api_base_url设置为统一的fastchat服务地址，也即是默认的。

**Comment by tanglu86** [comment]
> 请仔细看文档，api_base_url设置为统一的fastchat服务地址，也即是默认的。

我有设置和FSCHAT_OPENAI_API中的FASTCHAT保持一致，但是都不行的  这个是一个比较普遍的问题
