### ISSUE TITLE
如何用任意电脑访问服务器LangChain-Chatchat项目的webui网页？

### ISSUE THREAD

**Issue by zhuhaifengaaa** [chatchat-space/Langchain-Chatchat#1440]
我的问题是这样的：
我用自己公司服务器跑的项目代码，然后会返回一个链接：Chatchat WEBUI Server: http://127.0.0.1:8501，但是我不能用任意的电脑去连接这个链接进行对话。
群主前辈之前说，将server里面的defaultip改为0.0.0.0，试了好像不行。
ps:我们公司服务器有防火墙，但是我的电脑有权限访问这个服务器

**我其实有两个问题，**
第一，如何用**有**访问服务器权限的任意电脑访问WEBUI 进行对话？
第二，如何用**没有**访问服务器权限的任意电脑访问WEBUI 进行对话？

前各位前辈赐教，欢迎大家讨论

**Comment by ibuwei** [comment]
在server_config.py 里面 WEBUI_SERVER 的 host 参数调整为 0.0.0.0 就可以了, 如下图:
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/4596269/ee08d28e-4cb6-4070-be55-0f5fca96f80c)

**Comment by zhuhaifengaaa** [comment]
> 

好的，谢谢

**Comment by xxm1668** [comment]
不行啊

**Comment by Jingzhenzxz** [comment]
> ps:我们公司服务器有防火墙，但是我的电脑有权限访问这个服务器

需要让防火墙允许 8501 端口的流量，以centos7为例：
```
sudo firewall-cmd --zone=public --add-port=8501/tcp --permanent
```
