### ISSUE TITLE
知识库上传报错：文件向量化失败，报错信息为：Ran out of input

### ISSUE THREAD

**Issue by yuqx123** [chatchat-space/Langchain-Chatchat#1443]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/143470363/d5b24921-7450-4847-9874-8517dcfe132c)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码重试后若还有问题，可在微信群中提出，我们暂时没有办法复现出这个bug
