### ISSUE TITLE
[BUG] 本机能直连OPENAI，但是无法通过chatchat调用API KEY

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#1458]
服务器已经具备魔法能力，直接调用open api key是正常的，见图1
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/dcbec2f9-2d0c-4721-8a2f-c75d4896f2f9)

启动chatchat的方法：
```
python3 server/api.py
streamlit run webui.py --theme.base "light" --theme.primaryColor "#165dff" --theme.secondaryBackgroundColor "#f5f5f5" --theme.textColor "#000000"
```

通过chatchat启动服务后调用失败
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/56f01540-e500-4856-894d-ffadbefd3f21)

**Comment by tanglu86** [comment]
解决了  貌似是embedding模型的问题 必须要用openai的  这个地方忘改了

**Comment by manulife3417** [comment]
遇到同样问题，需要怎么修改
