### ISSUE TITLE
执行web_demo.py后，显示Killed，就退出了，是不是配置不足呢？

### ISSUE THREAD

**Issue by gitpxz** [chatchat-space/Langchain-Chatchat#146]
![图片](https://user-images.githubusercontent.com/26102866/233256425-c7aab999-11d7-4de9-867b-23ef18d519e4.png)

**Comment by imClumsyPanda** [comment]
新版本目前存在bug，建议在源代码中把第二个框出位置删除，目前正在修复

Xuezhi Peng ***@***.***>于2023年4月20日 周四12:35写道：

**Comment by imClumsyPanda** [comment]
![image](https://user-images.githubusercontent.com/5668498/233308746-53980696-5e05-4eeb-9463-45c4c05d37f7.png)

**Comment by songqiangchina** [comment]
Hi, I implement the newest version (master branch) of code, still face the same issue.  "webui.py" will meet killed

**Comment by luocj** [comment]
大佬，新版本的代码，这个文件只有83行

**Comment by luocj** [comment]
> ![image](https://user-images.githubusercontent.com/5668498/233308746-53980696-5e05-4eeb-9463-45c4c05d37f7.png)

大佬，新版本的代码，这个文件只有83行

**Comment by zRzRzRzRzRzRzR** [comment]
新代码可以解决问题
