### ISSUE TITLE
json格式该怎样导入

### ISSUE THREAD

**Issue by Lijia0** [chatchat-space/Langchain-Chatchat#1464]
使用默认的配置，上传json后，不能针对json的内容检索。
        elif self.document_loader_name == "CustomJSONLoader":
            loader = DocumentLoader(self.filepath, text_content=False)
将这里的False改为True，会报错，这个CustomJSONLoader该怎么使用呀？不懂python,谁能给个例子，这个metadata_func不知道该怎么写。
json格式如下：
[
    {
        "content": "张三是谁？",
        "summary": "张三是爱跳舞的科学家"
    }
]

这个能不能实现只向量化content的内容，返回的时候只返回summary的内容

**Comment by qihangf** [comment]
你要是这个格式的json为啥不转成csv呢

**Comment by Lijia0** [comment]
> 你要是这个格式的json为啥不转成csv呢

用csv实现了想要的效果，感谢~

**Comment by LXXiaogege** [comment]
> > 你要是这个格式的json为啥不转成csv呢
> 
> 用csv实现了想要的效果，感谢~

可以说下怎么只向量化问题，查询回答的操作吗，学习一下，我对这种问题是做成了markdown格式，但是他并不是只向量化问题。
