### ISSUE TITLE
[FEATURE] 简洁阐述功能 / Concise description of the feature  

### ISSUE THREAD

**Issue by liushifu12138** [chatchat-space/Langchain-Chatchat#1465]
How do I add a knowledge base with my fine-tuned model？

**Comment by glide-the** [comment]
```
fastchat.model.apply_lora.apply_lora
```
By using this method to merge Lora weight files into model files, the merged model file path needs to have a 'pert' identifier

https://github.com/lm-sys/FastChat/pull/1905#issuecomment-1627801216
