### ISSUE TITLE
集成使用Baichuan2-13B-Chat-4bits后对话内容异常，无报错！

### ISSUE THREAD

**Issue by Mr-IT007** [chatchat-space/Langchain-Chatchat#1466]
**问题描述 / Problem Description**
集成使用Baichuan2-13B-Chat-4bits的对话内容异常，单独使用模型示例脚本可以正常对话，见下图

![bc2-chat1](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/292b89d1-005d-4f01-8ddd-196292d687c6)

![bc2-chat2](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/a8a302db-498b-46a4-bbed-82f6be961b62)

![bc2-chat3](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/e738f10d-c31f-45cd-9c36-5ac66370ac8c)

![bc2-chat4](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/25302ae9-91f1-413b-a332-704095ef9ffc)

**复现问题的步骤 / Steps to Reproduce**
1. git clone https://github.com/chatchat-space/Langchain-Chatchat.git

2. 修改默认模型为Baichuan2-13B-Chat-4bits以及fastchat服务端口为18888

![bc2-chat5](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/e919a958-4056-49cb-9a2b-e13c59b3a4f1)

![bc2-chat7](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/81892227-bf14-48a0-86c6-9cedb8eeb6d9)

![bc2-chat6](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/be55dab1-fdfe-42f1-ac99-5f13214f976c)

3. 按照步骤启动服务

![bc2-chat8](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/103a30d4-835e-4790-bb1c-f7997b352c6e)

4. 问题出现 / Problem occurs：打开webui使用llm对话功能，对话内容异常

**预期的结果 / Expected Result**
正常对话

**实际结果 / Actual Result**
对话内容异常

**环境信息 / Environment Information**
- 版本号：UI页面显示的是LangChain-Chatchat v0.2.3
- 是否使用 Docker 部署：否
- 使用的模型：Baichuan2-13B-Chat-4bits
- 使用的 Embedding 模型：moka-ai/m3e-base
- 使用的向量库类型 ： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 18.04.5 LTS
- Python 版本 / Python version: 3.8.13

**Comment by luhairong11** [comment]
我也出现了类似的问题，加载的模型是baichuan2-7b-chat，版本是v0.2.2
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11584869/561737cf-5e35-4bc3-8c46-85e9fdcb3f74)

**Comment by algorithm007** [comment]
参考这个 https://github.com/lm-sys/FastChat/pull/2408/files
