### ISSUE TITLE
[BUG] 调用knowledge_base_chat接口时 ChatOpenAI 函数的stream=False会出现无返回的情况

### ISSUE THREAD

**Issue by jeurtr** [chatchat-space/Langchain-Chatchat#1468]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

将knowledge_base_chat.py 中
ChatOpenAI 函数的stream=False时，调用接口会出现无返回的情况

**复现问题的步骤 / Steps to Reproduce**

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
建议使用stream输出，之后的agent版本也只对stream只做了维护，其他功能可以更新到最新代码试一下

**Comment by zyhui98** [comment]
stream=true 也不是流输出，是不是版本不对。

返回的是一次性：

{"answer": "你"}{"answer": "好"}{"answer": "，"}{"answer": "有"}{"answer": "什"}{"answer": "么"}{"answer": "问题"}{"answer": "我"}{"answer": "能"}{"answer": "帮"}{"answer": "助"}{"answer": "你"}{"answer": "解"}{"answer": "答"}{"answer": "吗"}{"answer": "？"}{"docs": []}
