### ISSUE TITLE
求助！生成向量库时只调用CPU，GPU几乎没有占用，小白困惑。。

### ISSUE THREAD

**Issue by Sunadire** [chatchat-space/Langchain-Chatchat#1472]
![F(`C{N 7FTORI%C(%VH(((0](https://github.com/chatchat-space/Langchain-Chatchat/assets/107781447/436ff96a-3e42-45bf-895c-56323e28a0d1)
![XZL%HZ32%O6}38XI%)P)`3W](https://github.com/chatchat-space/Langchain-Chatchat/assets/107781447/e89ce272-9d8a-47b9-9c3b-77e2a1d7819e)
![%$_PF83~1AY @5 }$}`K(M4](https://github.com/chatchat-space/Langchain-Chatchat/assets/107781447/7adabe65-e813-4b40-9f30-c6267a912987)
一直卡在第一个，运行速度奇慢

**Comment by RainAutumnZero** [comment]
是不是安装pytorch的时候安装的是cpu版的？还是说调用的时候用的是cpu
