### ISSUE TITLE
[BUG] 知识库失效

### ISSUE THREAD

**Issue by H9990HH969** [chatchat-space/Langchain-Chatchat#1475]
**问题描述 / Problem Description**
刚刚生成给的知识库可以进行正常的问答，可以匹配到文本内的知识。但是过了一段时间后，我再加载这个知识库，进行问答，一样的问题，都匹配不到相关内容了。后台日志也是一切正常。
请问可能是什么问题呢？或者可以哪边加日志看看

![1694675408583](https://github.com/chatchat-space/Langchain-Chatchat/assets/133352113/2f1fb6a0-b91d-46cd-8d45-f8b6a122f36e)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.2
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：faiss
- 操作系统及版本 / Operating system and version: centos 7
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by H9990HH969** [comment]
我发现是同名知识库反复删除和建立，会导致查询该知识库的时候无效，真的是个BUG了

**Comment by zRzRzRzRzRzRzR** [comment]
收到bug反馈，开发组将尽快解决这问题，请留意我们的代码更新，感谢提出的issue。
