### ISSUE TITLE
[BUG] 执行python startup.py -a启动项目后， Chatchat  API  Server: http://127.0.0.1:7861 无法访问

### ISSUE THREAD

**Issue by maqiang114** [chatchat-space/Langchain-Chatchat#1478]
**执行python startup.py -a启动项目后， Chatchat  API  Server: http://127.0.0.1:7861 无法访问**

**环境信息 / Environment Information**
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.27.
python版本：3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
项目版本：v0.2.3
langchain版本：0.0.284. fastchat版本：0.2.26

**附加信息 / Additional Information**
启动完毕
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/69408337/232f9d45-5879-42f7-9154-1d8d6a51bba6)

点击链接访问后显示：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/69408337/40be638f-4972-4588-8442-75ade7224b71)

日志信息
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/69408337/19ce3297-4d00-4ed2-a92e-e25227011727)

不知有没有同学遇到这种情况，如有解决方案求解惑

**Comment by maqiang114** [comment]
使用模型正常对话是可以的，但是这个Chatchat API Server页面访问不进去

**Comment by qihangf** [comment]
我也进不去，但是分开一步一步来就可以

**Comment by cat1222** [comment]
是的，一键启动webui也进不去，分开启动就可以进去

**Comment by jhw0510** [comment]
同，而且更新了0.2.4之后没办法分步启动了好像

**Comment by jhw0510** [comment]
我看别人的方法解决了，把所有配置文件中的127.0.0.1改为0.0.0.0，尤其是configs里面的server_config.py和model_config.py，要是还不行就再找找，我改了好多hh

**Comment by Gzj369** [comment]
> 我看别人的方法解决了，把所有配置文件中的127.0.0.1改为0.0.0.0，尤其是configs里面的server_config.py和model_config.py，要是还不行就再找找，我改了好多hh

@jhw0510 我在v0.2.3版本采用分步骤启动，能正常运行，但切换不同的LLM，很容易出错，于是升级到v0.2.4版本，现在通过一键启动的方式，查看日志没有报错，但是web_ui以及/docs均无法被访问 @liunux4odoo 麻烦2位帮忙看看

**Comment by jhw0510** [comment]
> > 我看别人的方法解决了，把所有配置文件中的127.0.0.1改为0.0.0.0，尤其是configs里面的server_config.py和model_config.py，要是还不行就再找找，我改了好多hh
> 
> @jhw0510 我在v0.2.3版本采用分步骤启动，能正常运行，但切换不同的LLM，很容易出错，于是升级到v0.2.4版本，现在通过一键启动的方式，查看日志没有报错，但是web_ui以及/docs均无法被访问 @liunux4odoo 麻烦2位帮忙看看

看你这个说法很符合我遇到的问题，你尝试过我的方法了吗，就是把那些127.0.0.1改为0.0.0.0

**Comment by Gzj369** [comment]
> > > 我看别人的方法解决了，把所有配置文件中的127.0.0.1改为0.0.0.0，尤其是configs里面的server_config.py和model_config.py，要是还不行就再找找，我改了好多hh
> > 
> > 
> > @jhw0510 我在v0.2.3版本采用分步骤启动，能正常运行，但切换不同的LLM，很容易出错，于是升级到v0.2.4版本，现在通过一键启动的方式，查看日志没有报错，但是web_ui以及/docs均无法被访问 @liunux4odoo 麻烦2位帮忙看看
> 
> 看你这个说法很符合我遇到的问题，你尝试过我的方法了吗，就是把那些127.0.0.1改为0.0.0.0

对，把那些127.0.0.1改为0.0.0.0，这个方法有效，感谢大佬！

**Comment by liyiyiya** [comment]
> 我看别人的方法解决了，把所有配置文件中的127.0.0.1改为0.0.0.0，尤其是configs里面的server_config.py和model_config.py，要是还不行就再找找，我改了好多hh

我改了  也不行啊
