### ISSUE TITLE
[Question] 可以通过什么方式查看pdf处理后的结果吗

### ISSUE THREAD

**Issue by ticoAg** [chatchat-space/Langchain-Chatchat#1482]
**问题描述 / Problem Description**
我导了一个pdf，但是他有些篇幅是从中间切开的，有什么地方可以看识别 切片之后的结果么？

感谢诸佬

**Comment by liunux4odoo** [comment]
faiss自己手动加载向量库去查看，milvus有控制台工具和可视化工具可以查看
