### ISSUE TITLE
[FEATURE] 能否支持chatglm-cpp加速后的模型？
或者想要使用加速后的模型应该怎么处理，可否给我提供个思路？

### ISSUE THREAD

**Issue by Olbye** [chatchat-space/Langchain-Chatchat#1487]

**Comment by yhfgyyf** [comment]
项目所有llm入口都在fastchat，fastchat不支持llama.cpp,所以要让fastchat先支持llama-cpp-python,按照fastchat的架构，需要在modules中增加llama-cpp-python，在model/model_adapter.py中增加llama-cpp-python 的模型载入，在model/model_registry.py中增加模型注册信息

**Comment by Olbye** [comment]
> 项目所有llm入口都在fastchat，fastchat不支持llama.cpp,所以要让fastchat先支持llama-cpp-python,按照fastchat的架构，需要在modules中增加llama-cpp-python，在model/model_adapter.py中增加llama-cpp-python 的模型载入，在model/model_registry.py中增加模型注册信息

好的👌再研究研究
