### ISSUE TITLE
[BUG] 简洁阐述问题 /知识库创建与删除

### ISSUE THREAD

**Issue by cat1222** [chatchat-space/Langchain-Chatchat#1489]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
首先通过server/api.py启动了所有接口服务
然后调用"http://127.0.0.1:7861/knowledge_base/create_knowledge_base"接口进行知识库创建
接口传参：
post_json = {
    "knowledge_base_name": "investor_edu_chunk2_overlap2",
    "vector_store_type": "faiss",
    "embed_model": "m3e-base"
}
一直报【422】的错误。这个一直不知道到底哪里错了，，

用post访问这个接口，传一样的参数，第一次返回200，成功创建。
我手动删除了knowledge——base目录下创建的新的知识库文件，后续再调用接口创建同样名称的知识库，就显示【400】知识库已存在，在前端页面查看也是，这个知识库名称还在但是下面显示找不到目录。之前版本不应该是删了文件夹知识库就删调了嘛？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.3
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21336753/20a43879-43e3-46a0-9b72-854a4f77ae3d)

**Comment by imClumsyPanda** [comment]
请问报错中显示的路径实际是否存在呢？以及目前已发布最新0.2.4版本，请尝试更新后是否仍存在此问题。

**Comment by cat1222** [comment]
> 请问报错中显示的路径实际是否存在呢？以及目前已发布最新0.2.4版本，请尝试更新后是否仍存在此问题。

是不是我的传参格式不对？我调用其他接口也报422，起的api接口不是post一个json给对应的url吗？具体json包含哪些字段我参考具体方法的入参。如chat接口的入参参考server/chat/chat.py中的入参：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21336753/813ddd6d-53e0-480e-8b9b-bb171e02393a)
然后在其服务的机器上运行测试api的python文件。。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.5版本并重置知识库，看是否还存在该问题，如果还存在，可以打开新的issue
