### ISSUE TITLE
[BUG] docker版和本地版都报错：Caught exception: 'choices'

### ISSUE THREAD

**Issue by luckpunk** [chatchat-space/Langchain-Chatchat#1492]
使用最新版本， -a模式程序启动成功，使用 chatglm2-6b 或 chatglm2-6b-32k 模型chat时，

docker版和本地版都报错：Caught exception: 'choices'，

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/3422759/78897ba6-bf2c-4156-884a-1bc36845a36c)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/3422759/d59aebc5-ecd7-49a0-b1c7-2b6090700b6c)

模型确认已下载和已配置，使用OPENAI没问题。

**Comment by imClumsyPanda** [comment]
模型有成功加载吗？使用代码版本是多少？

**Comment by gogoods** [comment]
> 模型有成功加载吗？使用代码版本是多少？

有的，上面模型显示running，显存都占用了，

使用最新版本

**Comment by ilovesouthpark** [comment]
我也出现这样的问题，你可以试试换embedding或者让cpu加载embedding试试，然后再切换回来就好了。感觉是缓存问题

**Comment by chiehpower** [comment]
我也遇到类似的问题。

![screenshot-10-1-2-84-8501-1694948053932](https://github.com/chatchat-space/Langchain-Chatchat/assets/32332200/302f6c3b-eb7a-4076-a296-86d6f4309954)

```
2023-09-17 10:48:50 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7861/chat/chat "HTTP/1.1 200 OK"
2023-09-17 10:48:50 | INFO | stdout | INFO:     127.0.0.1:43336 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-09-17 10:48:50,937 - util.py[line:67] - INFO: message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-09-17 10:48:50 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-09-17 10:48:50,971 - utils.py[line:15] - ERROR: KeyError: Caught exception: 'choices'
```

不过目前我的 `server_config.py`内是设定CPU。

`LLM_DEVICE = "cpu" `
遇到的问题是在 `http://0.0.0.0:20002/worker_generate_stream ` 这支API上。
请问有人知道怎么解决吗？谢谢。

**Comment by geraldjin** [comment]
我开了load_8bit来加载qwen-7b-chat，也是同样的错误。使用chatglm2-6b正常。
embedding切换了cpu和gpu依然没有作用
求解决+1

**Comment by ilovesouthpark** [comment]
> 我也遇到类似的问题。
> 
> ![screenshot-10-1-2-84-8501-1694948053932](https://user-images.githubusercontent.com/32332200/268497399-302f6c3b-eb7a-4076-a296-86d6f4309954.png)
> 
> ```
> 2023-09-17 10:48:50 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7861/chat/chat "HTTP/1.1 200 OK"
> 2023-09-17 10:48:50 | INFO | stdout | INFO:     127.0.0.1:43336 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> 2023-09-17 10:48:50,937 - util.py[line:67] - INFO: message='OpenAI API response' path=http://0.0.0.0:8888/v1/chat/completions processing_ms=None request_id=None response_code=200
> 2023-09-17 10:48:50 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20002/worker_generate_stream "HTTP/1.1 200 OK"
> 2023-09-17 10:48:50,971 - utils.py[line:15] - ERROR: KeyError: Caught exception: 'choices'
> ```
> 
> 不过目前我的 `server_config.py`内是设定CPU。
> 
> `LLM_DEVICE = "cpu" ` 遇到的问题是在 `http://0.0.0.0:20002/worker_generate_stream ` 这支API上。 请问有人知道怎么解决吗？谢谢。

embedding 切换一下试试

**Comment by ilovesouthpark** [comment]
> 我开了load_8bit来加载qwen-7b-chat，也是同样的错误。使用chatglm2-6b正常。 embedding切换了cpu和gpu依然没有作用 求解决+1

我baichuan 13b 8bit是可以的，chatglm2 6b我不行，缺少某些模块。qwen 正常运行不量化会提示缺少某些依赖影响性能，但是运行还是可以的，但是0.2.2是好的。

**Comment by jiaolongxue** [comment]
切换到qianfan-api，然后使用知识库问答也有同样错误

**Comment by AnYingLieShouTuT** [comment]
+1

**Comment by FKgoogle** [comment]
+1

**Comment by gagakou** [comment]
+1
我是刚配置完环境用chatglm2-13b-32k可以进行问答，之后我更换了LLM的模型。当我再次换回chatglm2-13b-32k就出现了这个问题，而且一直没法解决。

**Comment by jhw0510** [comment]
插眼，我是可以正常使用ChatGLM2-6B，然后想着试试Baichuan2-13B-Chat，但是报了这个错误   Caught exception: 'choices' ，切换了embedding还是不行，然后我又换回ChatGLM2-6B了，明天试试重新建一个环境看行不行

**Comment by 337529542** [comment]
我的也是，ChatGLM2-6B-4bit，也是报这个错误，运行不了

**Comment by Godflyfly** [comment]
楼主解决了吗？

**Comment by 1065936727** [comment]
qianfan-api，使用知识库问答报这个错，但是知识库匹配结果能展开；对话不报错
xinghuo-api，使用知识库问答是正常的，对话也正常

**Comment by AIAdream** [comment]
在用qianfan-api，报错choices，修改如下图所示，即可正常回复
![Inkedbug：choices](https://github.com/chatchat-space/Langchain-Chatchat/assets/136043617/19e0d070-0426-4056-8f33-b3c57aafd6bd)

对于其他模型，可能也是这个原因，因为history中的输出多了在新一次的输入，造成了history中出现连续2个“user：“的情况导致报错，可以试一下。

**Comment by jhw0510** [comment]
> 在用qianfan-api，报错choices，修改如下图所示，即可正常回复 ![Inkedbug：choices](https://user-images.githubusercontent.com/136043617/270579702-19e0d070-0426-4056-8f33-b3c57aafd6bd.jpg)
> 
> 对于其他模型，可能也是这个原因，因为history中的输出多了在新一次的输入，造成了history中出现连续2个“user：“的情况导致报错，可以试一下。

 我还是不行，我用api，然后正常使用ChatGLM2-6B可以对话，然后想着试试Baichuan2-13B-Chat，不管是对话还是知识库都不行，会报错加乱答，可能也是类似这种问题，但是找不到问题在哪..

**Comment by gagakou** [comment]
> 在用qianfan-api，报错choices，修改如下图所示，即可正常回复 ![Inkedbug：choices](https://user-images.githubusercontent.com/136043617/270579702-19e0d070-0426-4056-8f33-b3c57aafd6bd.jpg)
> 
> 对于其他模型，可能也是这个原因，因为history中的输出多了在新一次的输入，造成了history中出现连续2个“user：“的情况导致报错，可以试一下。

试了一下不行，如果是history出现连续的user，把历史对话轮数设置为0，history应该就是空了吧，但是还是会报错。

**Comment by AIAdream** [comment]
> > 在用qianfan-api，报错choices，修改如下图所示，即可正常回复 ![Inkedbug：choices](https://user-images.githubusercontent.com/136043617/270579702-19e0d070-0426-4056-8f33-b3c57aafd6bd.jpg)
> > 对于其他模型，可能也是这个原因，因为history中的输出多了在新一次的输入，造成了history中出现连续2个“user：“的情况导致报错，可以试一下。
> 
> 我还是不行，我用api，然后正常使用ChatGLM2-6B可以对话，然后想着试试Baichuan2-13B-Chat，不管是对话还是知识库都不行，会报错加乱答，可能也是类似这种问题，但是找不到问题在哪..

可以试下接口和网页端分别发送，检测下log中的history和prompt有什么不同

**Comment by AIAdream** [comment]
> > 在用qianfan-api，报错choices，修改如下图所示，即可正常回复 ![Inkedbug：choices](https://user-images.githubusercontent.com/136043617/270579702-19e0d070-0426-4056-8f33-b3c57aafd6bd.jpg)
> > 对于其他模型，可能也是这个原因，因为history中的输出多了在新一次的输入，造成了history中出现连续2个“user：“的情况导致报错，可以试一下。
> 
> 试了一下不行，如果是history出现连续的user，把历史对话轮数设置为0，history应该就是空了吧，但是还是会报错。

历史对话轮数设置为0，好像历史中也会出现你新输入的那一条，因为i初始为1

**Comment by wenliangzwl** [comment]
同问，请问有解决了的吗
<img width="1304" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/40998662/2dbec209-8faf-4cb2-a5d3-c80453e030f4">
<img width="1387" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/40998662/9e4576ff-4ad8-42da-814d-ad46f7cad10f">

**Comment by zRzRzRzRzRzRzR** [comment]
这两天会更新0.2.5的docker文件，请注意新版本的变化并使用新版本来测试是否会有上述问题

**Comment by Wimet7** [comment]
确实很奇怪，我一开始是python3.10的环境，可以打开使用，后面用着突然报错packages/sqlalchemy/util/__init__.py", line 15, in <module>
    from ._collections import coerce_generator_arg as coerce_generator_arg
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1012, in get_code
  File "<frozen importlib._bootstrap_external>", line 672, in _compile_bytecode
ValueError: bad marshal data (unknown type code)

**Comment by Wimet7** [comment]
确实很奇怪，我一开始是python3.10的环境，可以打开使用，后面用着很卡，重启就起不来了，报错
packages/sqlalchemy/util/init.py", line 15, in
from ._collections import coerce_generator_arg as coerce_generator_arg
File "", line 1027, in _find_and_load
File "", line 1006, in _find_and_load_unlocked
File "", line 688, in _load_unlocked
File "", line 879, in exec_module
File "", line 1012, in get_code
File "", line 672, in _compile_bytecode
ValueError: bad marshal data (unknown type code)，
我又改了环境，把3.10改成3.8，3.11，启动倒是成功了，就是一直报错- ERROR: KeyError: Caught exception: 'choices'，
不回复了。就很奇怪

**Comment by houliangxue** [comment]
> 使用新版本来测试是否会有上述问题

使用了0.2.5还是有问题的呀

**Comment by iyangiiiii** [comment]
> 切换到qianfan-api，然后使用知识库问答也有同样错误

请问qianfan-api问题最后解决了吗 我llm问答和知识库回答都用不了

**Comment by wangzuohao** [comment]
我也是遇到这个问题，只有qianfan-api有这个错误，而且第一次基本都成功，但是后面的问答都会报错，看上去应该和history相关的
