### ISSUE TITLE
请教一下，knowledge_base/upload_doc接口上传的文件大小是否有限制？

### ISSUE THREAD

**Issue by RoronoaZoroh** [chatchat-space/Langchain-Chatchat#1493]
请教一下，knowledge_base/upload_doc接口上传的文件大小是否有限制？能否自定义，在哪设置？
并且在根据
<img width="638" alt="企业微信截图_1694768713465" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/87812264/caae7fb8-e02f-434c-956b-c2dd3424a01e">
进行非结构化处理后，上传非结构化文档类似时的接口是否不同，在哪看接口？

**Comment by liunux4odoo** [comment]
WEBUI中上传文件限制200M，不建议通过WEBUI上传过多、过大的文件。

API接口上传文件没有大小限制。
