### ISSUE TITLE
[BUG] 在聊天时候流式输出，偶尔出现只答复一部分内容

### ISSUE THREAD

**Issue by sunny6chen** [chatchat-space/Langchain-Chatchat#1495]
**问题描述 / Problem Description**
当我使用聊天功能的时候，发现在让其内容进行翻译时候，偶尔出现只答复一部分内容

**Comment by liunux4odoo** [comment]
请提供一下输入的prompt，LLM模型，错误的输出。

**Comment by hohosto** [comment]
我这边也遇到了
prompt
你是一位精通各种程序代码的资深工程师，请根据以下需求，为我生成一段Python代码： 代码目的：实现一个简单的GUI计算器 代码功能：实现两数的加、减、乘、除运算 代码要求：采用面向对象编程方式，GUI使用Tkinter

**Comment by liunux4odoo** [comment]
Duplicate of #1540 

已确认问题可以复现，回复“继续”后重新输出完整答案。

**Comment by liunux4odoo** [comment]
已确认是fastchat对max_tokens参数的限制所致，已向fastchat提交[pr](https://github.com/lm-sys/FastChat/pull/2544)
