### ISSUE TITLE
[BUG] v0.2.4 版本在 `ZH_TITLE_ENHANCE` 设置为 `True` 时添加文件会出现 `bool object is not callable` 错误

### ISSUE THREAD

**Issue by truc0** [chatchat-space/Langchain-Chatchat#1502]
**问题描述 / Problem Description**
v0.2.4 版本在 `ZH_TITLE_ENHANCE` 设置为 `True` 时添加文件会出现 `bool object is not callable` 错误，因为在 `docs2text` 函数中，本地的 `zh_title_enhance` 变量（用来标识是否启用 ZH_TITLE_ENHANCE）与全局的 `zh_title_enhance` 方法命名冲突。

`bool object is not callable` will be raised when `ZH_TITLE_ENHANCE` option is set to True and the user try to add a new file to vector store. The reason is the local variable `zh_title_enhance` (used to indicate if the option is enabled) shadowed the global `zh_title_enhance` method.

参照 / Reference：

- https://github.com/chatchat-space/Langchain-Chatchat/blob/7eed50337d102cd436edd11c8f3ff5eee54d361e/server/knowledge_base/utils.py#L310-L311

**复现问题的步骤 / Steps to Reproduce**
1. 在 `model_config.py` 中将 `ZH_TITLE_ENHANCE` 设置为 `True`
2. `python startup.py -a` 运行 `v0.2.4` 代码
3. 在知识库管理页面中添加一个文件，或点击重建向量库 / Add a file in knowledge base management page, or click `Rebuild vector base`

**预期的结果 / Expected Result**
没有错误出现 / No exception raised

**实际结果 / Actual Result**
出现错误 `bool object is not callable`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：No
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Baichuan2-13B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-zh-large
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: Python3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
已在 https://github.com/chatchat-space/Langchain-Chatchat/pull/1509 中修复
