### ISSUE TITLE
使用在线LLM模型时，是否还需要配合fastchat

### ISSUE THREAD

**Issue by jiusanears** [chatchat-space/Langchain-Chatchat#1505]
在使用在线的LLM模型时，修改了ONLINE_LLM_MODEL和LLM_MODEL直接启动就失败

**Comment by jiusanears** [comment]
访问web url NOT FOUND，不知道是不是fastchat没有加载模型的原因，因为电脑配置不行

**Comment by imClumsyPanda** [comment]
请贴一下报错信息

**Comment by zRzRzRzRzRzRzR** [comment]
需要使用，除了Openai，其他模型我们都是转换成fschat在转到langchain的chatopenai的接口
