### ISSUE TITLE
[BUG]baichuan2-7B模型问什么问题都不回答

### ISSUE THREAD

**Issue by iaoxuesheng** [chatchat-space/Langchain-Chatchat#1511]
**问题描述 / Problem [Description**]：问什么问题都不回答
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.9.18 (main, Sep 11 2023, 14:09:26) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.4
langchain版本：0.0.287. fastchat版本：0.2.28

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Baichuan2-7B-Chat'] @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': 'F:/Baichuan2-7B-Chat'}
当前Embbedings模型： bge-large-zh @ cuda
received input message:
{'history': [{'content': '你好', 'role': 'user'},
             {'content': '', 'role': 'assistant'},
             {'content': '课题目标是什么', 'role': 'user'}],
 'knowledge_base_name': '2',
 'local_doc_url': False,
 'model_name': 'Baichuan2-7B-Chat',
 'query': '课题目标是什么',
 'score_threshold': 0.5,
 'stream': True,
 'temperature': 0.7,
 'top_k': 3}
INFO:     127.0.0.1:56657 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2023-09-18 11:08:41 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13.75it/s]
2023-09-18 11:08:41 | INFO | stdout | INFO:     127.0.0.1:56658 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-09-18 11:08:41,556 - util.py[line:67] - INFO: message='OpenAI API response' path=http://localhost:8888/v1/chat/completions processing_ms=None request_id=None response_code=200
2023-09-18 11:08:42 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
{'docs': []}

**Comment by iaoxuesheng** [comment]
![微信截图_20230918110959](https://github.com/chatchat-space/Langchain-Chatchat/assets/94165844/709f77d5-2a4a-4774-b0d1-e4b24bd88499)

**Comment by Gzj369** [comment]
@iaoxuesheng 你选择的是 知识库问答模式，不是对话模式，试试切换成 对话模式

**Comment by iaoxuesheng** [comment]
对话模式也是不回答

**Comment by jianzhengming** [comment]
我也遇到同样的问题。我用的事qwen-7b的模型

**Comment by PonyM233** [comment]
更新 fastchat版本为：0.2.29

**Comment by zRzRzRzRzRzRzR** [comment]
更新 fastchat版本到最新即可
