### ISSUE TITLE
[BUG] 启动python startup。py -a 遇到TypeError: __init__() got an unexpected keyword argument 'embed_in_truncate'

### ISSUE THREAD

**Issue by qihangf** [chatchat-space/Langchain-Chatchat#1515]
**问题描述 / Problem Description**
如题

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
Process model_worker - chatglm2-6b-32k:
Traceback (most recent call last):
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/data/software/anaconda3/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/startup.py", line 303, in run_model_worker
    app = create_model_worker_app(log_level=log_level, **kwargs)
  File "/home/wyxx/warBackup/ner/Langchain-Chatchat/startup.py", line 135, in create_model_worker_app
    worker = ModelWorker(
TypeError: __init__() got an unexpected keyword argument 'embed_in_truncate'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)0.2.4
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:乌班图
- Python 版本 / Python version:3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liushifu12138** [comment]
请问怎么解决这个问题，谢谢

**Comment by diana-pwf** [comment]
> 请问怎么解决这个问题，谢谢

 把调用ModelWorker这行里的embed_in_truncate这个参数去掉就可以了
