### ISSUE TITLE
[FEATURE] 请求项目默认的分段器恢复以前默认的SpacySplitter

### ISSUE THREAD

**Issue by ConleyKong** [chatchat-space/Langchain-Chatchat#1520]
**功能描述 / Feature Description**
0.2.4版本的默认配置文件中提供的TEXT_SPLITTER为ChineseRecursiveTextSplitter，但是该分段器效果很不理想，会将语义连贯的话基于简单的标点符号分为特别碎的句子，导致召回率严重下降，导致大模型无法组织出有效的答案

**解决的问题 / Problem Solved**
缓解问答召回无法巡回完整语义原始文本的问题

**实现建议 / Implementation Suggestions**
将TEXT_SPLITTER恢复为不配置的模式，或者改为SpacyTextSplitter，同时需要将默认提供的text_splitter_dict的SpacyTextSplitter的source配置为空，否则根据现有配置会去huggingface官方下载gpt2模型，带来了很大的不便

**替代方案 / Alternative Solutions**
暂无

**其他信息 / Additional Information**
暂无

**Comment by imClumsyPanda** [comment]
请问是否方便提供测试用例，以及反馈下chunk size和overlap的设置情况

**Comment by ConleyKong** [comment]
谢谢回复~，私底下使用自己的数据又重新测试了下分段效果，发现目前ChineseRecursiveTextSplitter要好于spacy的，之所以出现先前的问题是由于自定义的loader继承了Unstructure那个类导致的，Unstructure那个类会使用英文的规则对文本进行提前分段从而导致后期的分段器是处理的unstructure处理后的文本，现在我本地已经将基类改成了BaseLoader类，逻辑更简单也更可控了
