### ISSUE TITLE
[BUG] 带有表格的中文pdf文件ocr的识别结果错乱 / Concise description of the issue

### ISSUE THREAD

**Issue by ConleyKong** [chatchat-space/Langchain-Chatchat#1521]
**问题描述 / Problem Description**
某些表格与文本混排的pdf文件进行ocr识别后的文字间的位置关系会整体错乱，导致问答召回的文本与原文中的严重不符，从而导致问答结果出错

**复现问题的步骤 / Steps to Reproduce**
pdf中首先出现表格，之后出现文字，但是表格中的文字的x坐标位置可能更大，就导致没有按照y轴的顺序先输出表格后输出文本而是先输出了x更小的文本，然后才输出了x较大的表格文本

**预期的结果 / Expected Result**
按照y轴的大小顺序优先输出表格，再输出文本，而不是按照x轴的顺序输出

**实际结果 / Actual Result**
实际现象就是召回的文本与原始文档中人眼看到的文字排版顺序不一致

**环境信息 / Environment Information**
- langchain-ChatChat 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B-int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: centos7
- Python 版本 / Python version:3.8.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
无

**Comment by zRzRzRzRzRzRzR** [comment]
带有表格 图表的文件我们的支持确实还不是很好，我们会在之后的版本进行改进。感谢您提到的issue
