### ISSUE TITLE
上传文件并加载知识库时，会不停地出现临时文件

### ISSUE THREAD

**Issue by xmxoxo** [chatchat-space/Langchain-Chatchat#153]
环境：ubuntu 18.04
使用 `python webui.py `启动服务；
打开浏览器，访问地址：`http://192.168.15.111:7860/`

在右侧添加一个知识库，然后上传一个文本文件，此时会不断的出现临时文件，一直停止不下来，代码界面也没有报错；
如下图：
![Uploading bug1.png…]()

**Comment by Betai18n** [comment]
我也遇到了这个问题，在不断生成临时文件的时候，直接点击“上传文件并加载知识库”，似乎能够直接成功，后台也提示“已成功加载”，对话时也似乎会按照知识库回答。
但是在无限生成临时文件过程中直接刷新页面，后台会报TypeError: 'NoneType' object is not iterable

**Comment by JadeLuo** [comment]
我尝试降级gradio ：
pip uninstall gradio
pip install gradio==3.24.1
就不会再出现此问题

**Comment by llwowowowoll** [comment]
我也遇到了
