### ISSUE TITLE
[BUG] 切换到【知识库管理】有错误日志输出

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#1536]
**问题描述 / Problem Description**
切换到【知识库管理】的时候提示：FileNotFoundError: [Errno 2] No such file or directory: xxx/envs/python3.10/lib/python3.10/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map'

**复现问题的步骤 / Steps to Reproduce**

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  Alibaba Cloud Linux 3 (Soaring Falcon)
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后重试一下哦
