### ISSUE TITLE
[FEATURE] Retrieval Argumented Generation / 引入LlamaIndex的工作

### ISSUE THREAD

**Issue by ticoAg** [chatchat-space/Langchain-Chatchat#1537]
**功能描述 / Feature Description**
知识图谱结合 LLM 的检索增强 / Knowledge Graph Combined with LLM for Retrieval Argumented Generation

**解决的问题 / Problem Solved**
似乎现在的一些工作和LlamaIndex是重合的 / It seems that some of the current work overlaps with LlamaIndex

That's where LlamaIndex comes in. LlamaIndex is a "data framework" to help you build LLM apps. It provides the following tools:

Offers data connectors to ingest your existing data sources and data formats (APIs, PDFs, docs, SQL, etc.)
Provides ways to structure your data (indices, graphs) so that this data can be easily used with LLMs.
Provides an advanced retrieval/query interface over your data: Feed in any LLM input prompt, get back retrieved context and knowledge-augmented output.
Allows easy integrations with your outer application framework (e.g. with LangChain, Flask, Docker, ChatGPT, anything else).

另外 请问是否有引入图谱增强的计划 / Also, may I ask if there are any plans to introduce graph enhancement

Best wishes

**Comment by zRzRzRzRzRzRzR** [comment]
是，我们也在积极学习同行的一些有点，包括图谱，agent等功能，感谢您的提议，我们将会对这些内容做出一定改进，并在未来版本推出
