### ISSUE TITLE
[BUG] 在聊天时候流式输出，比较长的回答出现只答复一部分内容

### ISSUE THREAD

**Issue by hohosto** [chatchat-space/Langchain-Chatchat#1540]
在使用chatglm2-6b 模型时，比较长的回答有时候只回复一部分内容，比如：这样的提问

你是一位精通各种程序代码的资深工程师，请根据以下需求，为我生成一段Python代码： 代码目的：实现一个简单的GUI计算器 代码功能：实现两数的加、减、乘、除运算 代码要求：采用面向对象编程方式，GUI使用Tkinter

**Comment by hohosto** [comment]
> 这个大概是长度限制，可以使用输入”继续“两字，LLM会继续回答，如：
> 
> self.button_4 = tk.Button(master, text="4", font=("Arial", 20), command=self.button_4_click) self.button_4.grid(row=1, column=5, sticky="W")
> 
> ```
>     self.button_5 = tk.Button(master, text="5", font
> ```
> 
> 继续
> 
> assistant avatar ， font=("Arial", 20), command=self.button_5_click) self.button_5.grid(row=1, column=6, sticky="W")
> 
> self.button_6 = tk.Button(master, text="6", font=("Arial", 20), command=self.button_6_click) self.button_6.grid(row=1, column=7, sticky="W")

在哪里可以设置长度吗？或者识别模型没有回答完，让他自动继续

**Comment by hohosto** [comment]
> > 这个大概是长度限制，可以使用输入”继续“两字，LLM会继续回答，如：
> > self.button_4 = tk.Button(master, text="4", font=("Arial", 20), command=self.button_4_click) self.button_4.grid(row=1, column=5, sticky="W")
> > ```
> >     self.button_5 = tk.Button(master, text="5", font
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 继续
> > assistant avatar ， font=("Arial", 20), command=self.button_5_click) self.button_5.grid(row=1, column=6, sticky="W")
> > self.button_6 = tk.Button(master, text="6", font=("Arial", 20), command=self.button_6_click) self.button_6.grid(row=1, column=7, sticky="W")
> 
> 在哪里可以设置长度吗？或者识别模型没有回答完，让他自动继续

问题找到了，需要在源码的chat.py中加入一个参数
<img width="799" alt="1690dcf4d02e86a6f3d58cde79f13ba" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/53573099/1b46985d-656b-44e1-9448-5f9d73fb459a">

**Comment by supersoulsoul** [comment]
> > > 这个大概是长度限制，可以使用输入”继续“两字，LLM会继续回答，如：
> > > self.button_4 = tk.Button(master, text="4", font=("Arial", 20), command=self.button_4_click) self.button_4.grid(row=1, column=5, sticky="W")
> > > ```
> > >     self.button_5 = tk.Button(master, text="5", font
> > > ```
> > > 
> > > 
> > > 继续
> > > assistant avatar ， font=("Arial", 20), command=self.button_5_click) self.button_5.grid(row=1, column=6, sticky="W")
> > > self.button_6 = tk.Button(master, text="6", font=("Arial", 20), command=self.button_6_click) self.button_6.grid(row=1, column=7, sticky="W")
> > 
> > 
> > 在哪里可以设置长度吗？或者识别模型没有回答完，让他自动继续
> 
> 问题找到了，需要在源码的chat.py中加入一个参数 <img alt="1690dcf4d02e86a6f3d58cde79f13ba" width="799" src="https://user-images.githubusercontent.com/53573099/269490474-1b46985d-656b-44e1-9448-5f9d73fb459a.png">

我改了不生效，还是回答不完整。请问你是哪个版本的，改了生效了？
