### ISSUE TITLE
[BUG] 使用baichuan2-13b-chat的第一个问题必然异常并且点击stop后GPU占用率异常

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [chatchat-space/Langchain-Chatchat#1541]
**问题描述 / Problem Description**
正常使用，第一个问题在生成回复时必然出现异常（乱码或持续输出同一个内容），并且会处理很长时间：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58684828/f8e01891-e415-4650-a7fb-e2ea36ed0021)

如果中途点击了stop，将会出现页面报错，GPU将会继续执行被中断的任务，直到完成，导致卡在100%使用率很长时间
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58684828/8a6d5109-e253-4ae5-8d0d-b202a18684c6)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58684828/eae12115-5dd3-49fa-9718-8f439586716e)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58684828/848b0af7-aa38-4481-bec2-1e81c7f63f92)

**复现问题的步骤 / Steps to Reproduce**
正常启动，使用baichuan2-13b-chat并进行对话

**预期的结果 / Expected Result**
正常使用

**实际结果 / Actual Result**
第一个问题必然异常，并且会执行很长的时间，如果中途stop掉，将会持续执行前面的任务，仍然停留在100%使用率，后续的执行将会大受影响

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4 commit b6c390777a34ec2611f25fd71cccb747b2b5c465
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan2-13b-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: 3.11.4
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zinc357** [comment]
同问，有解决办法吗

**Comment by 1250681923** [comment]
楼主，我下载了这个模型，但是运行的时候加载报错，需要更改哪里嘛？

**Comment by WilliamChen-luckbob** [comment]
> 楼主，我下载了这个模型，但是运行的时候加载报错，需要更改哪里嘛？

这个要你贴一下报错的内容了，十有八九是配置的问题，或者是你升了版本依赖包安装问题，`pip uninstall -r requirements.txt -y`卸载所有的依赖然后再按照requirements装回来，不然必挂

**Comment by gagakou** [comment]
同样问题

**Comment by zinc357** [comment]
升级fastchat版本可以解决。
fschat[model_worker]==0.2.29

**Comment by gagakou** [comment]
> 升级fastchat版本可以解决。 fschat[model_worker]==0.2.29

有效
