### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by FKgoogle** [chatchat-space/Langchain-Chatchat#1542]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a' 
2.本地部署chatglm26b可以正常使用，但是api调用网络模型均不可用

**环境信息 / Environment Information**
- langchain-Chatchat v2.04
- 非DOCK部署
- 使用的模型: ChatGLM2-6B
- 使用的 Embedding 模型m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:windows
- Python 版本 / Python version:3.8
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/144016181/14c341cd-3208-4064-a43b-61368d924405)

**Comment by luo-ji-777** [comment]
对，0.2.4版本还是存在这个问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59357554/475a3dfa-59ea-4cc2-80c3-830d1b495b68)
无论是用webui还是swagger调api，都稳定出现这个问题。重新装了环境还是一样。求大佬指点。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后，试试会不会出现同样的问题
