### ISSUE TITLE
提供一个完整的colab例子

### ISSUE THREAD

**Issue by liuxindtc** [chatchat-space/Langchain-Chatchat#1547]
为了方便大家学习，提供一个个人使用colab实践例子
https://colab.research.google.com/drive/107cZA3V885GtNfO8X7SIW-XdPA3WFYVG?usp=sharing

* 使用了本地部署
* LLM模型选用chatglm2-6b-int4
* embedding选用m3e-base
* 内网映射使用ngrok（这里不知道有没有其他方案，感谢大家指教）

**Comment by menghonghan** [comment]
老哥 按你的做法用 pyngrok之后也打不开webui啊 请问你是怎么做的 谢谢

**Comment by liuxindtc** [comment]
> 老哥 按你的做法用 pyngrok之后也打不开webui啊 请问你是怎么做的 谢谢

嗯，这里的确有点麻烦，我发现ngrok启动后没有显示地址，所以用nohup启动了他。这样做
1. 最后步执行，只要不报错就行
2. 到https://dashboard.ngrok.com/cloud-edge/endpoints 查看是否有激活的url，打开他就应该是webui了

**Comment by HuMian10** [comment]
你好，请问现在这个例子还能正常运行吗，我根据您提供的colab一直卡在这里
![ddccd17b04f9d506988b2af8207cda5d](https://github.com/chatchat-space/Langchain-Chatchat/assets/101257078/b540a490-2024-4188-b391-c9ffd3acd884)

**Comment by HuMian10** [comment]
十分感谢🙏🙏，目前程序运行没有问题，但是webui一直显示please  wait，我根据 #1397 修改后，依然显示这样，不知道您是否遇到过这个问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101257078/9c0fa003-fbc6-4040-9e81-06bf7f47f1ce)

**Comment by HuMian10** [comment]
> > 十分感谢🙏🙏，目前程序运行没有问题，但是webui一直显示please wait，我根据 #1397 修改后，依然显示这样，不知道您是否遇到过这个问题 ![image](https://user-images.githubusercontent.com/101257078/276537018-9c0fa003-fbc6-4040-9e81-06bf7f47f1ce.png)
> 
> 我刚才更新了下文件，使用0.2.5的chatchat下是可以完全正常运行的。试试看吧。

大佬🐮🐮🐮，十分感谢，成功运行出来了！！

**Comment by Roy-Q** [comment]
> > 十分感谢🙏🙏，目前程序运行没有问题，但是webui一直显示please wait，我根据 #1397 修改后，依然显示这样，不知道您是否遇到过这个问题 ![image](https://user-images.githubusercontent.com/101257078/276537018-9c0fa003-fbc6-4040-9e81-06bf7f47f1ce.png)
> 
> 我刚才更新了下文件，使用0.2.5的chatchat下是可以完全正常运行的。试试看吧。

你好，请问如何更新成0.2.5版本呢？
