### ISSUE TITLE
[BUG] 知识库 更新知识库文件

### ISSUE THREAD

**Issue by TongaoY** [chatchat-space/Langchain-Chatchat#1548]
上传完文件，下次再上传新的文件到知识库，还需要用python init_database.py --recreate-vs初始化知识库来向量化吗，那之前上传的向量化后的东西是不是就没了？

**Comment by CplusHua** [comment]
是的，应该用increament模式

**Comment by tommyvinny** [comment]
只有更换了版本或者知识库没有正常建立才需要执行初始化吧。
后面就继续添加就好了，是否是因为重新更换了版本或者更改了设置，容器内的更新会重置的。
如果是知识库消失了，而又是docker安装了，可以把/langchain-chatchat/knowledge_base/ 映射到本地磁盘。
