### ISSUE TITLE
webui中用户输入和模型输出都会缺少回车，导致浏览起来异常费力

### ISSUE THREAD

**Issue by Halflifefa** [chatchat-space/Langchain-Chatchat#1550]
**功能描述 / Feature Description**
能否设置webui输入输出不再缺少回车？

**解决的问题 / Problem Solved**
优化体验
例如模型输出
'设甲车速度为 $x$ 千米/小时，乙车速度为 $y$ 千米/小时，则有：\n'
                         '甲车从 A 地到 P 地所需时间：$\\frac{540}{x}$\n'
                         '甲车从 P 地到 B 地所需时间：$\\frac{540}{x}$\n'
webui实际展示的输出
'设甲车速度为 $x$ 千米/小时，乙车速度为 $y$ 千米/小时，则有：甲车从 A 地到 P 地所需时间：$\\frac{540}{x}$甲车从 P 地到 B 地所需时间：$\\frac{540}{x}$‘
可以看到\n都没了,可读性大为下降。

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
无
**其他信息 / Additional Information**
无

**Comment by zRzRzRzRzRzRzR** [comment]
输出的回车是由大模型决定的，对应的符号是\n 输入的回车已经支持，按住shift + 回车

**Comment by Halflifefa** [comment]
> 输出的回车是由大模型决定的，对应的符号是\n 输入的回车已经支持，按住shift + 回车

我的意思是模型输出的\n会被吞掉.用户输入的\n\n也会变成\n
