### ISSUE TITLE
建议Docker镜像仅负责环境搭建，代码直接挂载指定目录

### ISSUE THREAD

**Issue by myhabit** [chatchat-space/Langchain-Chatchat#1555]
**问题描述 / Problem Description**
如题，因0.2.3版本启动后一直卡在“Loading checkpoint shards: 14%”，仅0.2.0版本能够启动成功。
每次拉取镜像需要花费1个多钟，而且0.2.0没有百度千帆大模型的代码。
就想用master分支的代码替换掉0.2.0下的langchain-ChatGLM-dev目录的代码。
然后根据错误提示补充model_config.py和server_config.py还是报错，就萌生了挂载的想法！

**Comment by tommyvinny** [comment]
自建DOCKER就可了。自建DOCKERFILE，按照作者的说明，拉取底包 nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
然后docker构建得时候，git clone后，执行环境安装。然后启动docker的时候，再把//langchain-chatchat映射本地自己拉取的0.2.4的文件夹。
不说别的，自建docker也需要接近1个钟。而且版本变化后，环境也可能变化的。model和server这两个config的也有变化。要是想只替换文件的话，那就最好本地跑或者虚拟机分配显卡来跑。我是unraid，已经安装nvidia drive，自建0,2,4之后，也存在一些问题。0.2.3现在是比较稳定的。0.2.4是多了一些功能，但是看还存在一些环境的问题，所以可能出错。
附上我的dockerfile

FROM nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04
RUN apt-get update \ 
  && DEBIAN_FRONTEND="noninteractive" \ 
  apt-get install -y \
    git wget vim python3-pip python3-venv libopencv-dev git-lfs sudo build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev libsqlite3-dev libbz2-dev liblzma-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /temp
WORKDIR /Langchain-Chatchat  
RUN mkdir langchain-chatchat chatglm2-6b-32k m3e-large text2vec-bge-large-chinese tmp
RUN git clone https://github.com/chatchat-space/Langchain-Chatchat.git /Langchain-Chatchat-self

RUN python3 -m pip install --upgrade pip
RUN pip install --upgrade streamlit
RUN pip install -r https://github.com/chatchat-space/Langchain-Chatchat/Langchain-Chatchat-self/requirements.txt
RUN rm -r /Langchain-Chatchat-self
EXPOSE 8501
EXPOSE 7861
EXPOSE 20001
EXPOSE 20002
EXPOSE 20003
EXPOSE 8888
EXPOSE 19530
ENTRYPOINT ["python3", "startup.py", "-a"]

存在目录中后，unraid命令行进入文件夹，执行 docker build -t langchain-chatchat-self:v0.2.4 .
后面是有一个空格和 一个点。
然后再添加容器。
把拉取的最新的，映射到，另外自己的几个chatglm2-6b-32k m3e-large text2vec-bge-large-chinese 也自行拉取到本地映射到对应的/chatglm2-6b-32k /m3e-large中，映射端口，就可以启动了。

0.2.4在执行知识库的时候，我8124双路处理器有时候不会调用我的p40显卡，而会调用cpu，导致处理器满载，无论我是否设置了LLM=CUDA和显卡使用，也正常安装了库的。微软那个识别也是安装了的。
而另一台P40的X99双路就可以正常调用GPU用于知识库构建。

我现在已经退回0.2.3版本。自建和官方docker都很稳。

**Comment by renjietan** [comment]
大佬 请问一下 您这个docker file  是完整的吗

**Comment by tommyvinny** [comment]
完整的。可拉取后用 docker cp 把容器内容拷贝出来检查哈。&nbsp;&nbsp;


四川美术学院中国画系&nbsp;支部办公室
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月21日(星期三) 下午4:14
收件人: ***@***.***&gt;; 
抄送: "四川美术学院中国画系 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] 建议Docker镜像仅负责环境搭建，代码直接挂载指定目录 (Issue #1555)





 
大佬 请问一下 您这个docker file  是完整的吗
