### ISSUE TITLE
KeyError: 'st.session_state has no key "chat_history".

### ISSUE THREAD

**Issue by lululiu2323** [chatchat-space/Langchain-Chatchat#1556]
我按照流程部署了langchain+chatglm2-6b，遇到了一个报错，怎么都解决不了，麻烦大神给看下：KeyError: 'st.session_state has no key "chat_history".

**Comment by zRzRzRzRzRzRzR** [comment]
尝试更新到最新代码后，按照本地服务的方式进行配置，如还有问题，可以在社群微信群中提出

**Comment by TianZheng-9741** [comment]
> 我按照流程部署了langchain+chatglm2-6b，遇到了一个报错，怎么都解决不了，麻烦大神给看下：KeyError: 'st.session_state has no key "chat_history".

我也遇到了这个问题，请问你解决了吗

**Comment by TianZheng-9741** [comment]
> > 我按照流程部署了langchain+chatglm2-6b，遇到了一个报错，怎么都解决不了，麻烦大神给看下：KeyError: 'st.session_state has no key "chat_history".
> 
> 我也遇到了这个问题，请问你解决了吗

可能是启动命令错了，昨天用的python webui.py报错跟你一样，今天换成了python startup.py --all-webui可以运行

**Comment by alexxchen** [comment]
这个错误是概率出现的，只要网络不好，每次都会出现

**Comment by H9990HH969** [comment]
这个问题应该重新开放，因为这个是streamlit流控制的问题，如果要稳定使用，这个还是要跟的
