### ISSUE TITLE
[BUG] 无法指定GPU卡，gpus参数不生效

### ISSUE THREAD

**Issue by 518jelly** [chatchat-space/Langchain-Chatchat#1563]
**问题描述**
[0.2.2中我碰到了同样的问题，可以指定多卡，但是gpus参数不生效，在指定非第一张卡时不论怎样都会使用第一张卡。](https://github.com/chatchat-space/Langchain-Chatchat/issues/1295)

**复现问题的步骤**
通过python llm_api.py方式启动模型api服务。
server_config.py、llm_api.py中修改了均不生效。
在create_model_worker_app中打印相关变量都是没问题的。

**Comment by DongHT0801** [comment]
如果你是linux环境，需要在当前虚拟环境下设置~/.bashrc中的CUDA_VISIBLE_DEVICES，并且source。

**Comment by evolcano** [comment]
@518jelly   我做了如下尝试，在WIndows环境也不生效：
1、重装 cuda-toolkit 并设置 CUDA_VISIBLE_DEVICES环境变量
2、修改 startup.py 中和GPU相关的设置
3、修改 server_[config.py 中和GPU相关的设置

输出日志很简单，没有提示当前设置是否使用GPU，是否找到GPU，直接就进入了CPU：
 

> ==============================Langchain-Chatchat Configuration==============================
> 操作系统：Windows-10-10.0.22621-SP0.
> python版本：3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
> 项目版本：v0.2.4
> langchain版本：0.0.287. fastchat版本：0.2.28
> 
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter
> 当前启动的LLM模型：['chatglm2-6b'] @ cpu
> {'api_base_url': 'http://localhost:8888/v1',
>  'api_key': 'EMPTY',
>  'local_model_path': 'D:\\LLM\\ChatGLM2-6B'}
> 当前Embbedings模型： m3e-base @ cpu
> ==============================Langchain-Chatchat Configuration==============================
> 
> 
> 2023-09-24 15:50:28,566 - startup.py[line:541] - INFO: 正在启动服务：
> 2023-09-24 15:50:28,566 - startup.py[line:542] - INFO: 如需查看 llm_api 日志，请前往 D:\LLM\Langchain-Chatchat\logs
> 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Started server process [4856]
> 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Waiting for application startup.
> 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Application startup complete.
> 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
> Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.62s/it]
> INFO:     Started server process [3508]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
> 
> 
> ==============================Langchain-Chatchat Configuration==============================
> 操作系统：Windows-10-10.0.22621-SP0.
> python版本：3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
> 项目版本：v0.2.4
> langchain版本：0.0.287. fastchat版本：0.2.28
> 
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter
> 当前启动的LLM模型：['chatglm2-6b'] @ cpu
> {'api_base_url': 'http://localhost:8888/v1',
>  'api_key': 'EMPTY',
>  'local_model_path': 'D:\\LLM\\ChatGLM2-6B'}
> 当前Embbedings模型： m3e-base @ cpu
> 
> 
> 服务端运行信息：
>     OpenAI API Server: http://127.0.0.1:8888/v1
>      (请确认llm_model_dict中配置的api_base_url与上面地址一致。)
>     Chatchat  API  Server: http://127.0.0.1:7861
>     Chatchat WEBUI Server: http://127.0.0.1:8501
> ==============================Langchain-Chatchat Configuration==============================

**Comment by xjw00654** [comment]
@evolcano 
估摸着可能是装了cpu版的torch导致的？如果cuda的环境一切正常的话。
试试在终端跑一下`python3 -c "import torch; print(torch.cuda.is_availbale());`看看呢

**Comment by 518jelly** [comment]
> @518jelly 我做了如下尝试，在WIndows环境也不生效： 1、重装 cuda-toolkit 并设置 CUDA_VISIBLE_DEVICES环境变量 2、修改 startup.py 中和GPU相关的设置 3、修改 server_[config.py 中和GPU相关的设置
> 
> 输出日志很简单，没有提示当前设置是否使用GPU，是否找到GPU，直接就进入了CPU：
> 
> > ==============================Langchain-Chatchat Configuration==============================
> > 操作系统：Windows-10-10.0.22621-SP0.
> > python版本：3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
> > 项目版本：v0.2.4
> > langchain版本：0.0.287. fastchat版本：0.2.28
> > 当前使用的分词器：ChineseRecursiveTextSplitter
> > 当前启动的LLM模型：['chatglm2-6b'] @ cpu
> > {'api_base_url': 'http://localhost:8888/v1',
> > 'api_key': 'EMPTY',
> > 'local_model_path': 'D:\LLM\ChatGLM2-6B'}
> > 当前Embbedings模型： m3e-base @ cpu
> > ==============================Langchain-Chatchat Configuration==============================
> > 2023-09-24 15:50:28,566 - startup.py[line:541] - INFO: 正在启动服务：
> > 2023-09-24 15:50:28,566 - startup.py[line:542] - INFO: 如需查看 llm_api 日志，请前往 D:\LLM\Langchain-Chatchat\logs
> > 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Started server process [4856]
> > 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Waiting for application startup.
> > 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Application startup complete.
> > 2023-09-24 15:50:31 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
> > Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:11<00:00,  1.62s/it]
> > INFO:     Started server process [3508]
> > INFO:     Waiting for application startup.
> > INFO:     Application startup complete.
> > INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
> > ==============================Langchain-Chatchat Configuration==============================
> > 操作系统：Windows-10-10.0.22621-SP0.
> > python版本：3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
> > 项目版本：v0.2.4
> > langchain版本：0.0.287. fastchat版本：0.2.28
> > 当前使用的分词器：ChineseRecursiveTextSplitter
> > 当前启动的LLM模型：['chatglm2-6b'] @ cpu
> > {'api_base_url': 'http://localhost:8888/v1',
> > 'api_key': 'EMPTY',
> > 'local_model_path': 'D:\LLM\ChatGLM2-6B'}
> > 当前Embbedings模型： m3e-base @ cpu
> > 服务端运行信息：
> > OpenAI API Server: http://127.0.0.1:8888/v1
> > (请确认llm_model_dict中配置的api_base_url与上面地址一致。)
> > Chatchat  API  Server: http://127.0.0.1:7861
> > Chatchat WEBUI Server: http://127.0.0.1:8501
> > ==============================Langchain-Chatchat Configuration==============================

我这边是在centos7环境，显示配置了环境变量”exprot CUDA_VISIBLE_DEVICES=x,x,x"就可以了

**Comment by 518jelly** [comment]
显示配置了环境变量”exprot CUDA_VISIBLE_DEVICES=x,x,x"就可以了
