### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by jersonal** [chatchat-space/Langchain-Chatchat#1570]
版本v0.2.4

当上传的多个文件，其中某些文件内容为空时，print(f"文档切分示例：{docs[0]}")会报IndexError: list index out of range的错误。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/cb646b2f-2686-4651-a4b2-ce3e6a640489)
然后反复读取所有文件，报如下错误：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/2633a196-a4d8-4602-a564-d437542ae02c)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/ab7f99c2-4e2b-4768-bc94-701a44a697ec)
修改了之后依然重复加载，还是会报上面httpx.ReadTimeout: timed out
2023-09-22 14:58:21 | ERROR | root | AttributeError: API未能返回正确的JSON。无法连接API服务器，请确认已执行python server\api.py的错误
还是会反复加载上传文件。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/2c8e5cb4-b9ba-4639-9d80-c7881248e335)

**Comment by zRzRzRzRzRzRzR** [comment]
空的文件可能并不支持，因为无法分词出东西
