### ISSUE TITLE
[FEATURE] 优化知识库匹配逻辑，解决非结构化文档匹配不到相关知识的问题

### ISSUE THREAD

**Issue by Chenxiuling-Amy** [chatchat-space/Langchain-Chatchat#1571]
**功能描述 / Feature Description**
优化知识库匹配逻辑，解决非结构化文档匹配不到相关知识的问题

**解决的问题 / Problem Solved**
现有问题：我有一个非结构化文档，是运维手册，描述故障现象、故障原因、解决方案等，文档的分行分段比较多，在构建向量知识库时，会把每一句话作为一条知识，导致故障现象、该现象对应的每一个原因、每一个解决方案等，都被当做一条单独的文档存储和匹配。当用户提问某个故障原因是什么或者如何解决时，匹配到的只是故障现象的那条文档，无法获取其后文中相关的故障原因和解决方案等，所以无法根据文档内容回答用户问题。

**实现建议 / Implementation Suggestions**
对于非结构化文档中的某一条文档，建议同时存储这条文档对应的当前页内容、前一页内容、后一页内容拼接成的文本，作为该条文本的上下文。在匹配到该条文本后，实际获取的是该条文本对应的上下文而不是 该条文本本身，来作为模型问答的上下文。

**替代方案 / Alternative Solutions**
我考虑过切分文档的时候，不切那么细，直接把整页文本作为一条文档进行向量存储，但这样做匹配效果并不佳，该页文本内容中索然包含了用户问题，但进行向量相似度检索时没有检索出来，用户问题和一页文档之间的内容长度相差太大。

**其他信息 / Additional Information**
暂无

**Comment by zuoxiang95** [comment]
我是自己手动切分的，效果感觉还行

**Comment by WinncyNing** [comment]
您好～请问文本切分的代码是在项目的哪一份代码里实现的？因为我也想要尝试优化它的切分逻辑～

**Comment by WilliamChen-luckbob** [comment]
> 我是自己手动切分的，效果感觉还行

是不是metadata不会写入向量仓库中呢？

**Comment by zuoxiang95** [comment]
> > 我是自己手动切分的，效果感觉还行
> 
> 是不是metadata不会写入向量仓库中呢？
切分完之后用textloader读就行，load的时候不加splitter就好，metadata写不写向量库跟你做切分没有关系

**Comment by Chenxiuling-Amy** [comment]
好的，后面尝试一下这个方法，多谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ZuoXiang ***@***.***&gt;
发送时间: 2023年9月25日 14:36
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: Chenxiuling-Amy ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [chatchat-space/Langchain-Chatchat] [FEATURE] 优化知识库匹配逻辑，解决非结构化文档匹配不到相关知识的问题 (Issue #1571)





   
我是自己手动切分的，效果感觉还行
  
是不是metadata不会写入向量仓库中呢？
 切分完之后用textloader读就行，load的时候不加splitter就好，metadata写不写向量库跟你做切分没有关系
