### ISSUE TITLE
有没有java SSE对接示例？

### ISSUE THREAD

**Issue by SnowyLchen** [chatchat-space/Langchain-Chatchat#1572]
EventSource.Factory factory = EventSources.createFactory(this.okHttpClient);
			ObjectMapper mapper = new ObjectMapper();
			String requestBody = mapper.writeValueAsString(chatCompletion);
			log.info("请求参数：{}", requestBody);
			RequestBody requestContent = RequestBody.create(MediaType.parse(ContentType.JSON.getValue()), requestBody);
			Request request = new Request.Builder()
				.url(LangChainConstant.API + "/chat/chat")
				.post(requestContent)
				.build();
	//创建事件
	factory.newEventSource(request, eventSourceListener);

public class GlmEventSourceListener extends EventSourceListener {
	@Getter
	@Setter
	private Session remoteSession;

	@Override
	public void onOpen(EventSource eventSource, Response response) {
		// 减少问答次数
		ChatGPTConstants.QUESTION_COUNT.decrementAndGet();
		log.info("GLM2-6B建立sse连接...{}", response);
	}

	@Override
	@SneakyThrows
	public void onEvent(EventSource eventSource, String id, String type, String data) {
		log.info("GLM2-6B返回数据：{}", data);
	}

	@Override
	public void onClosed(@NotNull EventSource eventSource) {
		log.info("GLM2-6B关闭sse连接...");
		// 增加问答次数
		ChatGPTConstants.QUESTION_COUNT.incrementAndGet();
	}

	@SneakyThrows
	@Override
	public void onFailure(EventSource eventSource, Throwable t, Response response) {
		ChatUtils.sendFailMessage(remoteSession);
		if (Objects.isNull(response)) {
			log.error("GLM2-6B  sse连接异常:{}", t);
			eventSource.cancel();
			return;
		}
		ResponseBody body = response.body();
		if (Objects.nonNull(body)) {
			log.error("GLM2-6B  sse连接异常data：{}，异常：{}", body.string(), t);
		} else {
			log.error("GLM2-6B  sse连接异常data：{}，异常：{}", response, t);
		}
		eventSource.cancel();
	}
}

				
贴上部分代码，我写完后，不走EventSourceListener的onEvent事件，onOpen onClosed都是正常走的，请问一下是为什么？

**Comment by jayxuz** [comment]
默认的接口返回是StreamingResponse不是EventSourceResponse
按照下面的改造一下应该就能正常返回了
https://github.com/chatchat-space/Langchain-Chatchat/issues/1351#issuecomment-1710971814

**Comment by SnowyLchen** [comment]
> 默认的接口返回是StreamingResponse不是EventSourceResponse 按照下面的改造一下应该就能正常返回了 [#1351 (comment)](https://github.com/chatchat-space/Langchain-Chatchat/issues/1351#issuecomment-1710971814)

ok谢谢，我试了好多方式对接都不行，还是妥协了，去改源码了，增加了2个接口，没在原来的基础上改，不然webui不能用了
