### ISSUE TITLE
希望支持function calling，通过自然语言输入，驱动预先定义好的function

### ISSUE THREAD

**Issue by jiaolongxue** [chatchat-space/Langchain-Chatchat#1575]
**功能描述 / Feature Description**
希望支持function calling，通过自然语言输入，驱动预先定义好的function

**解决的问题 / Problem Solved**
llm agent驱动查询数据库，并做bi相关的展示

**Comment by zRzRzRzRzRzRzR** [comment]
Qwen新的模型支持这个功能，我们现在做的agent是react的形式，我们也会探索function calling的应用，可以期待我们后面的版本
