### ISSUE TITLE
docker文件要如何pull

### ISSUE THREAD

**Issue by blueroutecn** [chatchat-space/Langchain-Chatchat#1576]
我用docker search chatchat，找不到registry.cn-beijing.aliyuncs.com，请教官方镜像要如何下载？

**Comment by flowscolors** [comment]
docker search默认去连dockerhub的仓库，registry.cn-beijing.aliyuncs.com是阿里的仓库，直接执行命令就可以

**Comment by gitlyp** [comment]
docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5
Unable to find image 'registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5' locally
docker: Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5 not found: manifest unknown: manifest unknown.  直接执行找不到镜像
