### ISSUE TITLE
[BUG]讯飞星火 API 接入访问失败Unauthorized

### ISSUE THREAD

**Issue by 518jelly** [chatchat-space/Langchain-Chatchat#1580]
**问题描述 **
模型配置为xinghuo-api，配置相关相关参数后模型访问一直失败

**复现问题的步骤 / Steps to Reproduce**
1. 模型配置为xinghuo-api
2. api_base_url配置为：wss://spark-api.xf-yun.com/v1.5/chat或wss://spark-api.xf-yun.com/v1.1/chat
3. 配置申请的APPID、APISecret、api_key
4. python startup.py -a 启动
5. webui 交互

**实际结果 / Actual Result**
ERROR: APIError: Caught exception: Invalid response object from API: '{"message":"Unauthorized"}' (HTTP response code was 401)
{'docs': []}
INFO: message='OpenAI API response' path=wss://spark-api.xf-yun.com/v1.5/chat/chat/completions processing_ms=None request_id=None response_code=401
2023-09-23 16:34:56,435 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 10.0 seconds as it raised APIError: Invalid response object from API: '{"message":"Unauthorized"}' (HTTP response code was 401).

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：xinghuo-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:CentOS Linux release 7.6.1810 (Core)
- Python 版本 / Python version: 3.10.4

**Comment by 518jelly** [comment]
@liunux4odoo @imClumsyPanda 两位大佬帮忙看看

**Comment by liunux4odoo** [comment]
api_base_url保持默认，根你本地fastchat服务器一致。

**Comment by 518jelly** [comment]
> api_base_url保持默认，根你本地fastchat服务器一致。

可以了，非常感谢
