### ISSUE TITLE
[BUG] 使用ChatGLM模型本地部署，运行时还需访问ChatGPT

### ISSUE THREAD

**Issue by evolcano** [chatchat-space/Langchain-Chatchat#1586]
**问题描述 / Problem Description**
按照缺省步骤安装，有网络的时候运行正常；没有网络时运行没有输出。

**复现问题的步骤 / Steps to Reproduce**
1、按照安装步骤安装系统
2、按照说明设下载设置 THUDM/chatglm2-6b、moka-ai/m3e-base，LLM_MODEL = "chatglm2-6b"，不使用OpenAI的Embedding模型
model_config.py
[model_config.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/12710735/model_config.txt)
server_config.py
[server_config.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/12710737/server_config.txt)

3、启动，在有外网访问时问答正常
4、关闭网络，问答时错误，提示ChatGPT不能访问

**预期的结果 / Expected Result**
关闭网络，问答时应正常运行。需要支持本地部署和离线运行。

**实际结果 / Actual Result**

> (cc) PS D:\LLM\Langchain-Chatchat python startup.py -a
> 
> 
> ==============================Langchain-Chatchat Configuration==============================
> 操作系统：Windows-10-10.0.22621-SP0.
> python版本：3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
> 项目版本：v0.2.4
> langchain版本：0.0.287. fastchat版本：0.2.28
> 
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter
> 当前启动的LLM模型：['chatglm2-6b'] @ cpu
> {'api_base_url': 'http://localhost:8888/v1',
>  'api_key': 'EMPTY',
>  'local_model_path': 'D:\\LLM\\ChatGLM2-6B'}
> 当前Embbedings模型： m3e-base @ cpu
> ==============================Langchain-Chatchat Configuration==============================
> 
> 
> 2023-09-25 11:03:46,073 - startup.py[line:541] - INFO: 正在启动服务：
> 2023-09-25 11:03:46,073 - startup.py[line:542] - INFO: 如需查看 llm_api 日志，请前往 D:\LLM\Langchain-Chatchat\logs
> 2023-09-25 11:03:48 | ERROR | stderr | INFO:     Started server process [22808]
> 2023-09-25 11:03:48 | ERROR | stderr | INFO:     Waiting for application startup.
> 2023-09-25 11:03:48 | ERROR | stderr | INFO:     Application startup complete.
> 2023-09-25 11:03:48 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:8888 (Press CTRL+C to quit)
> Loading checkpoint shards: 100%| 7/7 [00:07<00:00,  1.01s/it]
> INFO:     Started server process [29952]
> INFO:     Waiting for application startup.
> INFO:     Application startup complete.
> INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
> 
> 
> ==============================Langchain-Chatchat Configuration==============================
> 操作系统：Windows-10-10.0.22621-SP0.
> python版本：3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
> 项目版本：v0.2.4
> langchain版本：0.0.287. fastchat版本：0.2.28
> 
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter
> 当前启动的LLM模型：['chatglm2-6b'] @ cpu
> {'api_base_url': 'http://localhost:8888/v1',
>  'api_key': 'EMPTY',
>  'local_model_path': 'D:\\LLM\\ChatGLM2-6B'}
> 当前Embbedings模型： m3e-base @ cpu
> 
> 
> 服务端运行信息：
>     OpenAI API Server: http://127.0.0.1:8888/v1
>      (请确认llm_model_dict中配置的api_base_url与上面地址一致。)
>     Chatchat  API  Server: http://127.0.0.1:7861
>     Chatchat WEBUI Server: http://127.0.0.1:8501
> ==============================Langchain-Chatchat Configuration==============================
> 
> 
> 
>   You can now view your Streamlit app in your browser.
> 
>   URL: http://127.0.0.1:8501
> 
> 2023-09-25 11:04:12,708 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
> INFO:     127.0.0.1:63572 - "POST /llm_model/list_models HTTP/1.1" 200 OK
> 2023-09-25 11:04:12,713 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 200 OK"
> 2023-09-25 11:04:12,713 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
> INFO:     127.0.0.1:63573 - "POST /llm_model/list_models HTTP/1.1" 200 OK
> 2023-09-25 11:04:12,717 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 200 OK"
> 2023-09-25 11:04:25,482 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
> INFO:     127.0.0.1:63595 - "POST /llm_model/list_models HTTP/1.1" 200 OK
> 2023-09-25 11:04:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/llm_model/list_models "HTTP/1.1 200 OK"
> received input message:
> {'history': [{'content': '油田和气田需要聘用监督人员。这些监督人员有几种？', 'role': 'user'}],
>  'knowledge_base_name': 'samples',
>  'local_doc_url': False,
>  'model_name': 'chatglm2-6b',
>  'query': '油田和气田需要聘用监督人员。这些监督人员有几种？',
>  'score_threshold': 1.0,
>  'stream': True,
>  'temperature': 0.7,
>  'top_k': 3}
> INFO:     127.0.0.1:63600 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
> 2023-09-25 11:04:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"2023-09-25 11:04:26,061 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: D:\LLM\m3e-base
> 2023-09-25 11:04:26,882 - faiss_cache.py[line:74] - INFO: loading vector store in 'samples' from disk.
> {'kb_name': 'samples', 'vs_type': 'faiss', 'embed_model': 'm3e-base', 'file_count': 4, 'create_time': datetime.datetime(2023, 9, 24, 11, 52, 22)}
> 2023-09-25 11:04:26,893 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
> 2023-09-25 11:04:26,893 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
> ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
> 2023-09-25 11:04:26,893 - loader.py[line:64] - INFO: Loading faiss.
> 2023-09-25 11:04:26,905 - loader.py[line:66] - INFO: Successfully loaded faiss.
> Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 25.49it/s]
> 2023-09-25 11:04:27,202 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
> 2023-09-25 11:04:31,205 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
> 2023-09-25 11:04:35,210 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals._completion_with_retry in 4.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
> 2023-09-25 11:04:39,223 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals._completion_with_retry in 8.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
> 2023-09-25 11:04:47,245 - before_sleep.py[line:65] - WARNING: Retrying langchain.chat_models.openai.acompletion_with_retry.<locals._completion_with_retry in 10.0 seconds as it raised APIConnectionError: Error communicating with OpenAI.
> {'docs': [...]}

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：1334
- 是否使用 Docker 部署 ： 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 : faiss
- 操作系统及版本 /  windows 11
- Python 版本 / 3.8
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
需要的就是本地运行，不能把数据发给ChatGPT。一不小心发多了，就会有问题

如果是还有什么配置要修改，请在安装说明中明示。

**Comment by WilliamChen-luckbob** [comment]
langchain集成本地LLM的原理是调用openai的方法，但是实际上调用地址是你的本地服务启动的LLM服务（将本地LLM的服务封装为与openai一样入参和路径的接口）从而实现通用化的调用，出现此错误十有八九是你的配置有误，而不是真的访问了openai。

**Comment by evolcano** [comment]
@WilliamChen-luckbob 谢谢回复。配置如下：
model_config.py
[model_config.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/12710735/model_config.txt)
server_config.py
[server_config.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/12710737/server_config.txt)

**Comment by libo119111** [comment]
> langchain集成本地LLM的原理是调用openai的方法，但是实际上调用地址是你的本地服务启动的LLM服务（将本地LLM的服务封装为与openai一样入参和路径的接口）从而实现通用化的调用，出现此错误十有八九是你的配置有误，而不是真的访问了openai。 另外把配置内容也贴一下。

您说的配置是指啥呢，我也遇到了同样的问题，烦请您说的再详细一些，目前很着急要解决这个谢谢

**Comment by hzg0601** [comment]
不是bug,建议仔细看readem

**Comment by yinglou2012** [comment]
The same problem

**Comment by ai408** [comment]
The same problem

**Comment by ite-jin** [comment]
题主解决了么？碰到了同样的问题
