### ISSUE TITLE
[FEATURE] 百川53B开放API了，请问能否接入使用

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#1588]
相比CHATGPT多了一个  secret_key ，请问如何接入chatchat进行使用
```
    url = "https://api.baichuan-ai.com/v1/chat"
    api_key = "your_api_key"
    secret_key = "your_secret_key"
```

**Comment by zRzRzRzRzRzRzR** [comment]
我们将会尽快更新这个功能，百川模型确实很好用

**Comment by jamesyao54** [comment]
好像还没有更新。

**Comment by zRzRzRzRzRzRzR** [comment]
支持的啊

**Comment by liurr9810** [comment]
> 相比CHATGPT多了一个 secret_key ，请问如何接入chatchat进行使用
> 
> ```
>     url = "https://api.baichuan-ai.com/v1/chat"
>     api_key = "your_api_key"
>     secret_key = "your_secret_key"
> ```

你好，您可以拿到secret key了么？
