### ISSUE TITLE
知识库问答问题，回复内容知识库已经匹配到对应内容，但是还是回复根据已知信息，无法回答该问题

### ISSUE THREAD

**Issue by SnowyLchen** [chatchat-space/Langchain-Chatchat#1590]
分数阈值都试过了，都不行
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/e4d01ace-af83-49b0-84cf-73c30bc07449)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/30f244a9-c510-49c2-aa98-e10c1eb7af01)

**Comment by SnowyLchen** [comment]
使用的是 LLM=chatglm2-6b
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/4bab1568-8e4e-40f8-9803-6cd13f70bde4)

**Comment by WilliamChen-luckbob** [comment]
你在直接和LLM对话中贴原文+问题看看chatglm2-6b能不能回答，有可能是LLM不给力总结不出来，我测试了chatglm1和2目前开源的全系列，可能是因为训练数据集小了，推理能力捉急，很多问题直接问也死都答不出来，后面换了baichuan2-13B-chat，解决了大部分此类问题，数据集b值越大，推理能力越强，带不动就加配置

**Comment by justforword** [comment]
我用了Qwen，在chatglm上栽太多跟头了

**Comment by liushifu12138** [comment]
> 你在直接和LLM对话中贴原文+问题看看chatglm2-6b能不能回答，有可能是LLM不给力总结不出来，我测试了chatglm1和2目前开源的全系列，可能是因为训练数据集小了，推理能力捉急，很多问题直接问也死都答不出来，后面换了baichuan2-13B-chat，解决了大部分此类问题，数据集b值越大，推理能力越强，带不动就加配置

请问您的数据集多大规模？用baichuan2-13B-chat是直接微调还是用langchain? 我微调baichuan2-13B-chat效果不理想，回答是错的

**Comment by SnowyLchen** [comment]
> 你在直接和LLM对话中贴原文+问题看看chatglm2-6b能不能回答，有可能是LLM不给力总结不出来，我测试了chatglm1和2目前开源的全系列，可能是因为训练数据集小了，推理能力捉急，很多问题直接问也死都答不出来，后面换了baichuan2-13B-chat，解决了大部分此类问题，数据集b值越大，推理能力越强，带不动就加配置

我试了一下，第一次居然不行，第二次就可以了，glm确实不大行

**Comment by SnowyLchen** [comment]
> 我用了Qwen，在chatglm上栽太多跟头了

确实，我也换一个试试

**Comment by SnowyLchen** [comment]
> 你在直接和LLM对话中贴原文+问题看看chatglm2-6b能不能回答，有可能是LLM不给力总结不出来，我测试了chatglm1和2目前开源的全系列，可能是因为训练数据集小了，推理能力捉急，很多问题直接问也死都答不出来，后面换了baichuan2-13B-chat，解决了大部分此类问题，数据集b值越大，推理能力越强，带不动就加配置

[FlagAlpha/Llama2-Chinese-13b-Chat](https://huggingface.co/FlagAlpha/Llama2-Chinese-13b-Chat) 这个怎么样

**Comment by zixiaotan21** [comment]
同样遇到这个问题，我用的是本地模型：chatglm3-6b
我尝试了直接和LLM对话中贴原文+问题看看chatglm3-6b能不能回答，回答效果不太理想
将本地模型换为：qwen-max api去跑，可以完全回答正确。
想请教大家有什么可以下载到本地的LLM模型推荐吗
