### ISSUE TITLE
知识库无法添加pdf至向量库

### ISSUE THREAD

**Issue by woshikid** [chatchat-space/Langchain-Chatchat#1591]
**问题描述 / Problem Description**
上传txt文件时，完全正常
上传pdf文件时，无法添加至向量库：
utils.py[line:368] - ERROR: ImportError: 从文件 test/1.pdf 加载文档时出错：libGL.so.1: cannot open shared object file: No such file or directory

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29223368/14320ba9-077b-4f7e-a5db-1d13ccaae685)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29223368/f060e5c3-f437-474d-913d-d4ece131a4a6)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4 ([af46ed9](https://github.com/chatchat-space/Langchain-Chatchat/commit/af46ed95394a3678fdce410d3d46296272350dea))
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： pg_vector
- 操作系统及版本 / Operating system and version: Ubuntu

**Comment by reimuyl** [comment]
我也一样，不过我的是win10系统的，报错信息是这个：
2023-09-25 20:15:45,167 - utils.py[line:368] - ERROR: RuntimeError: 从文件 Other/readme.pdf 加载文档时出错：Directory 'static/' does not exist
我也在找解决方法

**Comment by reimuyl** [comment]
pip install pyMuPDF
安装这个包解决了

**Comment by yanyang1024** [comment]
同报错, libGL.so.1: cannot open shared object file: No such file or directory,有解决过的么

**Comment by zRzRzRzRzRzRzR** [comment]
pip install pyMuPDF
可以试试
另外，可以更新到最新版本
如果还遇到相似问题，可以提出新的issue，本issue关闭

**Comment by pengxianggui** [comment]
> pyMuPDF

我也是遇到这个问题，不过我是centos

**Comment by pengxianggui** [comment]
> 同报错, libGL.so.1: cannot open shared object file: No such file or directory,有解决过的么

解决了上面的，又遇到你这个 😂
