### ISSUE TITLE
ModuleNotFoundError: No module named 'configs'

### ISSUE THREAD

**Issue by wuyj** [chatchat-space/Langchain-Chatchat#1593]
今天master更新了下代码，再启动就报错了。

python server/llm_api.py
Traceback (most recent call last):
  File "/home/mnt/Langchain-Chatchat/server/llm_api.py", line 2, in <module>
    from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT
ModuleNotFoundError: No module named 'configs'

系统是ubuntu22.40

**Comment by liguoyuan** [comment]
我也遇到同样的问题。pip install configs 后安装成功，但是又出现新的问题：
Traceback (most recent call last):
  File "server/llm_api.py", line 2, in <module>
    from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT
ImportError: cannot import name 'logger' from 'configs' (/lcdata/envs/langchainchat/lib/python3.8/site-packages/configs/__init__.py)

**Comment by glide-the** [comment]
相同问题https://github.com/chatchat-space/Langchain-Chatchat/issues/1202#issuecomment-1688246021

**Comment by JaneGDTOP** [comment]
请问解决了吗，我也遇到同样问题，LLM服务启动不起来
Traceback (most recent call last):
  File "server/llm_api.py", line 2, in <module>
    from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT
ModuleNotFoundError: No module named 'configs'

**Comment by JaneGDTOP** [comment]
> 相同问题[#1202 (comment)](https://github.com/chatchat-space/Langchain-Chatchat/issues/1202#issuecomment-1688246021)

好像不是同一个问题，有点差别

**Comment by kangchch** [comment]
解决了么？我也遇到这个问题

**Comment by JaneGDTOP** [comment]
> 解决了么？我也遇到这个问题
import sys
sys.path.append("...你的路径/langchain-ChatGLM")
我在文件第一行中添加了路径，然后直接一键启动服务。跑起来了。

**Comment by lihongyong** [comment]
> 今天master更新了下代码，再启动就报错了。
> 
> python server/llm_api.py Traceback (most recent call last): File "/home/mnt/Langchain-Chatchat/server/llm_api.py", line 2, in from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT ModuleNotFoundError: No module named 'configs'
> 
> 系统是ubuntu22.40

路径问题：
把sys.path.append(os.path.dirname(os.path.dirname(__file__)))
改为sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))即可，找多一级。

**Comment by muguangshaonian** [comment]
想要知道在哪个包下的哪个文件修改啊？

> > 今天master更新了下代码，再启动就报错了。
> > python server/llm_api.py 回溯（最近一次调用）：文件“/home/mnt/Langchain-Chaatchat/server/llm_api.py”，第 2 行，来自配置导入记录器、log_verbose、LLM_MODEL、HTTPX_DEFAULT_TIMEOUT ModuleNotFoundError：没有模块名为“配置”
> > 系统是ubuntu22.40
> 
> 路径问题： 把sys.path.append(os.path.dirname(os.path.dirname( **file** ))) 改为sys.path.append(os.path.dirname(os.path.dirname(os.path. abspath( **file** ))))即可，找到多一级。

在哪个目录的哪个文件下修改啊
