### ISSUE TITLE
[FEATURE] 使用bge系列embedding时，SCORE_THRESHOLD取值0-1无法满足要求

### ISSUE THREAD

**Issue by WilliamChen-luckbob** [chatchat-space/Langchain-Chatchat#1594]
**功能描述 / Feature Description**
实际测试bge系列的embedding（bge-large-en为例）时，直接使用原文进行匹配，对应的最相似匹配度从0.8开始，由于SCORE_THRESHOLD的限制，人工判定最精准的原文相似度大概会落到1.1总是被过滤掉，此处不应该限死0-1，否则框架很可能无法使用。

**解决的问题 / Problem Solved**
不能适用bge系列embedding

**实现建议 / Implementation Suggestions**
开放SCORE_THRESHOLD的限制

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
无

**Comment by zRzRzRzRzRzRzR** [comment]
因为其他模型都是在0-1 ，这个模型超出1 的部分我们无法有效复现，目前，代码先不做更改。您可以在
webui_pages/dialogue/dialogue.py 中将
score_threshold = st.slider("知识匹配分数阈值：", 0.0, 1.0, float(SCORE_THRESHOLD), 0.01)的1.0 进行修改为更大的值

**Comment by liwenju0** [comment]
> 因为其他模型都是在0-1 ，这个模型超出1 的部分我们无法有效复现，目前，代码先不做更改。您可以在 webui_pages/dialogue/dialogue.py 中将 score_threshold = st.slider("知识匹配分数阈值：", 0.0, 1.0, float(SCORE_THRESHOLD), 0.01)的1.0 进行修改为更大的值

按照这个修改后，界面上显示可调的阈值是大于1 了，但是真的设为1，进行召回时，显示unprocessable entity 的错误，请问是怎么回事呢

**Comment by qianbaidu1266** [comment]
人工判定最精准的原文相似度大概会落到1.1总是被过滤掉

---请教一下怎么看匹配度在1.1会被过滤掉呢，匹配阈值不应该是归一化之后的数字吗？为什么会有超过1的场景呢？
