### ISSUE TITLE
关于检索内容的扩展疑问

### ISSUE THREAD

**Issue by mzq20180601** [chatchat-space/Langchain-Chatchat#1596]
🙋老版本项目里面改了faiss检索相关文档的方法，基于检索的内容扩展一些上下文，新版项目里我没看到这个步骤，是我没注意到吗？如果是取消了这个步骤，想问问是如何考虑的。谢谢~

**Comment by RetormLi** [comment]
我自己把这个功能写了一下，大概思路是：
1. 在server/knowledge_base/kb_service/base.py的add_doc函数中，为每个doc的metadata中添加上下文的doc_info id
2. 在server/knowledge_base/kb_service/faiss_kb_service.py的do_search函数中，对得到的每个doc用metadata和FaissKBService.get_doc_by_id得到上下文并拼接。这里要注意，如果需要修改doc的内容并返回，相似度搜索函数返回的是引用，需要copy一下再修改。

**Comment by zRzRzRzRzRzRzR** [comment]
我们在1.x版本是对上下文进行了扩展，2.x版本没有，直接使用embed相似匹配来实现的匹配返回，我们现在在想一种非耦合的形式来实现1.x支持的功能，这方面的效果我们也进行了对比，但是还没有落地计划，之后的几个版本我们将把这个相似召回提上日程

**Comment by satsun-gaga** [comment]
@RetormLi 可以问下是怎么实现的吗 我目前发现faiss召回的东西都过于简短，可能就匹配上了标题，实际问题答案的正文反而没被召回，不知道是不是这个影响的

**Comment by RetormLi** [comment]
> @RetormLi 可以问下是怎么实现的吗 我目前发现faiss召回的东西都过于简短，可能就匹配上了标题，实际问题答案的正文反而没被召回，不知道是不是这个影响的

这个解决的是文档分片粒度比较小，能匹配到关键词所在的片，但是丢失了可能包含答案的上下文段落这个问题。如果你没法匹配到正文，可能需要别的方法。比如尝试粒度更小一点或者换embedding

**Comment by satsun-gaga** [comment]
> > @RetormLi 可以问下是怎么实现的吗 我目前发现faiss召回的东西都过于简短，可能就匹配上了标题，实际问题答案的正文反而没被召回，不知道是不是这个影响的
> 
> 这个解决的是文档分片粒度比较小，能匹配到关键词所在的片，但是丢失了可能包含答案的上下文段落这个问题。如果你没法匹配到正文，可能需要别的方法。比如尝试粒度更小一点或者换embedding

是的，我的问题也是匹配到了关键词，但是丢失了上下文，我用的是文本是html格式的，把分割的结果输出了下，发现标题跟正文属于不同的doc，只召回了标题，而没有召回正文。
