### ISSUE TITLE
v0.2.4版本中初始化数据库存在问题

### ISSUE THREAD

**Issue by Kathrine94** [chatchat-space/Langchain-Chatchat#1598]
**问题描述 / Problem Description**
调用v0.2.4版本的代码进行数据库初始化，做文本分割的时候每条文本被划分的很短，导致最后进行匹配的时候得到的匹配结果有问题。

原因：server/knowledge_base/migrate.py 中的folder2db的默认的 chunk_size 是-1导致的。
解决方法：将chunk_size参数传进去，或者直接将该默认参数设置成model_config中的CHUNK_SIZE（ps：可以顺便把OVER_SIZE的值也设置一下）

**Comment by zRzRzRzRzRzRzR** [comment]
收到了这个反馈，这是之前在调整分词器的时候没有调回来，我们将会对其进行调整修改，并于下一个版本修复这个bug
