### ISSUE TITLE
[BUG] 配置GPT信息之后，本地部署的模型访问不了了，如何处理

### ISSUE THREAD

**Issue by ArlanCooper** [chatchat-space/Langchain-Chatchat#1602]
**问题描述 / Problem Description**
我配置了GPT相关的配置信息，api-key等信息之后，可以正常调用，但是，本地下载安装的chatglm2-6b等模型却访问不了了，不知道是为什么？

**复现问题的步骤 / Steps to Reproduce**
1. 配置自己的openai相关信息
2 "gpt-35-turbo": {
        "api_base_url": openai.api_base,
        "api_key": openai.api_key,
        "openai_proxy": ""
    },
    "gpt-4": {
        "api_base_url": openai.api_base,
        "api_key": openai.api_key,
        "openai_proxy": ""
    },
    "gpt-4-32k": {
        "api_base_url": openai.api_base,
        "api_key": openai.api_key,
        "openai_proxy": ""
    }
3. 然后启动服务，python startup.py --all-webui
4. GPT类的接口可以正常访问，但是，chat2-6b这些模型，却无法访问：
5. 然后后台报错信息
```
INFO:openai:message='OpenAI API response' path=http://localhost:8888/v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview processing_ms=None request_id=None response_code=503
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised ServiceUnavailableError: The server is overloaded or not ready yet..
INFO:openai:message='OpenAI API response' path=http://localhost:8888/v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview processing_ms=None request_id=None response_code=503
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised ServiceUnavailableError: The server is overloaded or not ready yet..
```

**预期的结果 / Expected Result**
应该正常访问，可以返回结果的

**实际结果 / Actual Result**
实际报错：
```
INFO:openai:message='OpenAI API response' path=http://localhost:8888/v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview processing_ms=None request_id=None response_code=503
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised ServiceUnavailableError: The server is overloaded or not ready yet..
INFO:openai:message='OpenAI API response' path=http://localhost:8888/v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview processing_ms=None request_id=None response_code=503
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised ServiceUnavailableError: The server is overloaded or not ready yet..

```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 2.9.12
- 其他相关环境信息 / Other relevant environment information: 无

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by justforword** [comment]
env里面的http_proxy 是不是在？

**Comment by ArlanCooper** [comment]
> env里面的http_proxy 是不是在？
查了查，这个环境变量没有

**Comment by zRzRzRzRzRzRzR** [comment]
1. 检查系统是不是走代理了
2. 检查一下本地模型的llm_api是否有起，配置文件是否正确更改
根据反馈的报错来看，这个地方在配置文件应该就错误了，把本地模型当成了联网模型

最新代码对模型进行了重新配置，可以更新到最新代码是否还出现这问题，如果有，可以重新提出issue
