### ISSUE TITLE
模型的输出和baichuan官方程序给的输出不一样

### ISSUE THREAD

**Issue by yang159753** [chatchat-space/Langchain-Chatchat#1606]
langchain-ChatGLM 版本：v0.2.3
我训练了一个baichuan-13B的qlora然后和主模型合并成新模型，但模型的输出和baichuan官方程序给的输出不一样，是否是因为输入的Template和baichuan官方的不一样？我该怎么改？
config中的内容我也已对应修改了：

LLM_MODEL = "baichuan-13b"
llm_model_dict = {
    "baichuan-13b": {
        "local_model_path": "./model_new_0926",
        "api_base_url": "http://localhost:8888/v1", 
        "api_key": "EMPTY"
    }
}

**Comment by zRzRzRzRzRzRzR** [comment]
可以按照peft加载
如果你是merge成一个模型，你需要改一下你的template
并且，你需要确认fschat是否能支持读入你合并的模型

**Comment by yang159753** [comment]
> template



> 可以按照peft加载 如果你是merge成一个模型，你需要改一下你的template 并且，你需要确认fschat是否能支持读入你合并的模型

在哪修改template，有示例吗

**Comment by yang159753** [comment]
要自己更改fastchat.model.model_adapter.py中的内容，我已经搞定，感谢!

**Comment by XingchenMengxiang** [comment]
请问一下如何修改，方便给个示例吗
