### ISSUE TITLE
向知识库中添加文件后点击”上传文件并加载知识库“后Segmentation fault报错。

### ISSUE THREAD

**Issue by csmsp** [chatchat-space/Langchain-Chatchat#161]

**Comment by csmsp** [comment]
运行服务后的提示如下：
$ python webui.py
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
No compiled kernel found.
Compiling kernels : C:\Users\Reloading\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\Reloading\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels_parallel.c -shared -o C:\Users\Reloading\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantizatio
n_kernels_parallel.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile default cpu kernel failed, using default cpu kernel code.
Compiling gcc -O3 -fPIC -std=c99 C:\Users\Reloading\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels.c -shared -o C:\Users\Reloading\.cache\huggingface\modules\transformers_modules\chatglm-6b-int8\quantization_kernels.so
'gcc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Compile default cpu kernel failed.
Failed to load kernel.
Cannot load cpu kernel, don't use quantized model on cpu.
Using quantization cache
Applying quantization to glm layers
No sentence-transformers model found with name E:\AIproject\embedding\text2vec-large-chinese. Creating a new one with MEAN pooling.
The dtype of attention mask (torch.int64) is not bool
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
========
一旦选择上传文档到本地知识库，服务就退出来了。

**Comment by imClumsyPanda** [comment]
看起来是chatglm模型没有成功加载，可以参考chatglm-6b项目首先跑通模型。

csmsp ***@***.***>于2023年4月24日 周一13:01写道：

**Comment by csmsp** [comment]
llm对话是没有问题

**Comment by imClumsyPanda** [comment]
建议在微信群或者issue里面搜索看看，因为我自己没怎么用量化模型，看起来可能是量化模型运行过程中需要gcc支持

csmsp ***@***.***>于2023年4月24日 周一13:09写道：
