### ISSUE TITLE
[BUG] 配置gPT 接口参数之后，本地的模型比如chatglm无法使用

### ISSUE THREAD

**Issue by ArlanCooper** [chatchat-space/Langchain-Chatchat#1610]
就是配openai相关参数之后，可以调用gpt3.5,以及gpt-4,但是本地下载的模型无法访问，请问如何处理？
报错：
WARNING:langchain.chat_models.openai:WARNING! deployment_id is not default parameter.
                    deployment_id was transferred to model_kwargs.
                    Please confirm that deployment_id is what you intended.
2023-09-27 17:27:47 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7820/chat/chat "HTTP/1.1 200 OK"
2023-09-27 17:27:47 | INFO | stdout | INFO:     127.0.0.1:35728 - "POST /v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview HTTP/1.1" 404 Not Found
INFO:openai:message='OpenAI API response' path=http://localhost:8888/v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview processing_ms=None request_id=None response_code=404
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404).
2023-09-27 17:27:51 | INFO | stdout | INFO:     127.0.0.1:35800 - "POST /v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview HTTP/1.1" 404 Not Found
INFO:openai:message='OpenAI API response' path=http://localhost:8888/v1/openai/deployments/chatglm2-6b/chat/completions?api-version=2023-03-15-preview processing_ms=None request_id=None response_code=404
WARNING:langchain.llms.base:Retrying langchain.chat_models.openai.acompletion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"detail":"Not Found"}' (HTTP response code was 404).

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后重新根据readme进行配置，请注意端口不要互相冲突
