### ISSUE TITLE
[BUG] 重复生成同一句话，无法停止

### ISSUE THREAD

**Issue by soultrans** [chatchat-space/Langchain-Chatchat#1612]
**问题描述 / Problem Description**
对知识库提问了一个错误的知识问题，LLM模型一直生成重复的同一句话（eg：碳酸饮料、碳酸饮料、碳酸饮料、碳酸饮料、碳酸饮料、碳酸饮料...）无法停止。

图示如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/48265870/c4aade28-cc93-42c2-9f12-a57df36cb6c7)

**预期的结果 / Expected Result**
这应该是LLM生成的问题，是否能控制LLM指定生成的内容长度在一定限制范围内；或者终端进行检测异常处理，发现生成同样的内容连续到一定长度，就跳出大模型生成

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.17
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：faiss
- 操作系统及版本 / Operating system and version: Linux CentOS7.6
- Python 版本 / Python version: 3.8

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下fschat 到 0.2.29，这大概率是fschat的问题，如果还是不行，可以源码安装fschat并在源码内设置惩罚系数

**Comment by soultrans** [comment]
> 更新一下fschat 到 0.2.29，这大概率是fschat的问题，如果还是不行，可以源码安装fschat并在源码内设置惩罚系数

关于 **源码源码内设置惩罚系数** 您指的是哪里设置的？

**Comment by zRzRzRzRzRzRzR** [comment]
是的

**Comment by zRzRzRzRzRzRzR** [comment]
可以试一下换一个模型是不是正常
另外可以更新到最新代码试一下
