### ISSUE TITLE
LLM 类型换用如baichuan-7B其他模型出错

### ISSUE THREAD

**Issue by pikaqiuweixiao** [chatchat-space/Langchain-Chatchat#1614]
**LLM 类型换用如baichuan-7B其他模型出错**
LLM 类型换用如baichuan-7B其他模型出错，知识问答出错

**复现问题的步骤 **
1. 执行 python startup.py -a
2. 建立新的知识库，导入txt知识
3. 选择知识问答，选择新的知识库，进行输入问题
4. 发送

**预期的结果**
回复正常，有知识库知识

**实际结果**
无回复，只有有知识库知识
后台出错2023-09-28 08:53:36,126 - utils.py[line:15] - ERROR: KeyError: Caught exception: 'choices'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan-7B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:Linux-5.4.0-139-generic-x86_64-with-glibc2.17.
- Python 版本 / Python version:3.8.18
- 其他相关环境信息 / Other relevant environment information:
操作系统：Linux-5.4.0-139-generic-x86_64-with-glibc2.17.
python版本：3.8.18 (default, Sep 11 2023, 13:40:15)
[GCC 11.2.0]
项目版本：v0.2.4
langchain版本：0.0.287. fastchat版本：0.2.28

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['baichuan-7B'] @ cuda
{'api_base_url': 'http://localhost:8888/v1',
 'api_key': 'EMPTY',
 'local_model_path': '/media/datadiskA/test/lcx/baichuan-7B/baichuan-7B-chat'}
当前Embbedings模型： m3e-base @ cuda

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是提示词的问题，我们这边测的代码中，baichaun2-7B是正常现象，能根据提问和知识库进行综合回答，你还可以设置一下温度等其他参数，看看有没有帮助

**Comment by ttyuuuuuuuuuu** [comment]
其他相关环境信息 / Other relevant environment information:
操作系统：Linux-5.4.0-139-generic-x86_64-with-glibc2.17.
python版本：3.8.18 (default, Sep 11 2023, 13:40:15)
[GCC 11.2.0]
项目版本：v0.2.4
langchain版本：0.0.287. fastchat版本：0.2.28

请问这个百川是用fastchat接入的，还是langchain？我看readme感觉是fastchat。不知道有没有langchain对接的版本能否提供？
