### ISSUE TITLE
[FEATURE] 支持向模型的tokenizer增加自定义的关键字

### ISSUE THREAD

**Issue by charlesyju** [chatchat-space/Langchain-Chatchat#1621]
支持在预训练模型中增加自定义的关键字。增加的关键字将被tokenizer解析为一个token。举例：
增加关键字之前：
        sentence=iphone13pro
        ids=[101, 8210, 8679, 10538, 102]
            [CLS]->101
            iphone->8210
            ##13->8679
            ##pro->10538
            [SEP]->102

增加关键字iphone13pro之后：
        sentence=iphone13pro
        ids=[101, 21128, 102]
        [CLS]->101
        iphone13pro->21128
        [SEP]->102

关键字可以通过文件来配置

**Comment by zRzRzRzRzRzRzR** [comment]
这个想法不错，
如果要发起PR的话，需要您将他添加到配置文件，方便开发团队和社区开发者来检验，以及如何使用你的这工具哦
你可以这么做
如果这个是及时的功能（改配置文件立即生效）
1. 在configs/model_config.py中加入这个字段，为嵌入模型添加关键字
如果这个是不及时的功能（要导出模型）
则建议加在主目录下，然后在doc中补充对应的文档后，完善你的PR

**Comment by charlesyju** [comment]
好的。我按照这个规范改一下。

**Comment by charlesyju** [comment]
1. 在docs目录下增加了文档：自定义关键字.md
2. 在model_config.py.example文件中增加了配置样例
3. 调整keyword_preprocess.py
4. 这个功能实现为非及时功能（要导出模型），这样不会对原有流程做侵入式改动，也避免因配置问题导致文档添加到向量数据库和查询时使用不同的tokenizer。

以上改动已经提交到dev分支。不需要重新提交pull request了吧？

**Comment by zRzRzRzRzRzRzR** [comment]
不需要，我们已经在pr中进行回复，最近这两天才在批量处理issue，你提的功能很好，我们还需要考虑一下

**Comment by vovovovovov** [comment]
> 支持在预训练模型中增加自定义的关键字。增加的关键字将被tokenizer解析为一个token。举例： 增加关键字之前： sentence=iphone13pro ids=[101, 8210, 8679, 10538, 102] [CLS]->101 iphone->8210 ##13->8679 ##pro->10538 [SEP]->102
> 
> 增加关键字iphone13pro之后： sentence=iphone13pro ids=[101, 21128, 102] [CLS]->101 iphone13pro->21128 [SEP]->102
> 
> 关键字可以通过文件来配置

你好，我使用此方法进行关键词相关配置后，效果反而变差了(相似度检索时候相似度降低)，请问有什么原因吗

**Comment by vovovovovov** [comment]
> > 支持在预训练模型中增加自定义的关键字。增加的关键字将被tokenizer解析为一个token。举例： 增加关键字之前： sentence=iphone13pro ids=[101, 8210, 8679, 10538, 102] [CLS]->101 iphone->8210 ##13->8679 ##pro->10538 [SEP]->102
> > 增加关键字iphone13pro之后： sentence=iphone13pro ids=[101, 21128, 102] [CLS]->101 iphone13pro->21128 [SEP]->102
> > 关键字可以通过文件来配置
> 
> 你好，我使用此方法进行关键词相关配置后，效果反而变差了(相似度检索时候相似度降低)，请问有什么原因吗

具体表现是在测试数据过程中相似的数据相似度降低，不相似的数据相似度提高
