### ISSUE TITLE
大佬们，wsl的ubuntu怎么配置用cuda加速，装了运行后发现是cpu在跑

### ISSUE THREAD

**Issue by Maddaxman** [chatchat-space/Langchain-Chatchat#164]
大佬们，wsl的ubuntu怎么配置用cuda加速，装了运行后发现是cpu在跑

**Comment by sleikang** [comment]
自己要安装cuda的库啊

**Comment by tianlichunhong** [comment]
> 自己要安装cuda的库啊

有没有详细方法呀？

**Comment by imClumsyPanda** [comment]
建议参考一下pytorch官网关于cuda支持的内容

Wilson ***@***.***>于2023年5月14日 周日20:52写道：
