### ISSUE TITLE
Qwen14b启动webui报错ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0.

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#1645]
**问题描述 / Problem Description**
2.5版本使用Qwen-14b-chat，python startup.py --all-webui后报错ValueError: Bfloat16 is only supported on GPUs with compute capability of at least 8.0. Your Tesla V100-SXM2-32GB GPU has compute capability 7.0.
我在2.2版本同样的配置用三步启动webui（python server/llm_api.py；python server/api.py；streamlit run webui.py）没有问题，Qwen-14b-chat可以正常使用，2.5版本就不行了，运行信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58140899/9489af17-c034-4c49-af88-b8a867117628)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 18.04
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:

**Comment by hzg0601** [comment]
把server_config的infer_turbo字段改成False

**Comment by supercocoa** [comment]
把dtype改成half就可以
https://github.com/vllm-project/vllm/issues/730
