### ISSUE TITLE
python startup.py --all-webui报错TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#1647]
**问题描述 / Problem Description**
2.5版本跑Qwen14b和chatglm2-6b都会出现，加载完模型后出错，原本同配置在2.2版本无问题。运行信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58140899/16ed37a3-13c4-46a3-ad09-65c95d03afff)

**Comment by ftyh2005** [comment]
同样遇到这个错误

**Comment by liunux4odoo** [comment]
建议使用python 3.10，或者手动把server/agent/callbacks.py中报错行的type hint删除

**Comment by hurner** [comment]
> 建议使用python 3.10，或者手动把server/agent/callbacks.py中报错行的type hint删除

升级到3.10可以。
