### ISSUE TITLE
[BUG] 在colab启动后页面一直显示请等待

### ISSUE THREAD

**Issue by callmeYe** [chatchat-space/Langchain-Chatchat#1648]
<img width="1437" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/15107776/c00e41bd-53c8-4237-930c-72e384ebc4c7">

**Comment by zRzRzRzRzRzRzR** [comment]
colab我们也没有尝试，你可以提交一下后台日志重新提交issue

**Comment by HuMian10** [comment]
你好，请问您在colab成功运行出来了吗

**Comment by cwyalpha** [comment]
https://github.com/cwyalpha/Langchain-Chatchat-Colab 试试这个
