### ISSUE TITLE
在github codespaces  docker运行出错

### ISSUE THREAD

**Issue by younggggger** [chatchat-space/Langchain-Chatchat#165]
docker run -d --restart=always --name chatglm -p 7860:7860 -v /www/wwwroot/code/langchain-ChatGLM:/chatGLM  chatglm
Unable to find image 'chatglm:latest' locally
docker: Error response from daemon: pull access denied for chatglm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

**Comment by BKDragon** [comment]
I encountered the same problem. Have you solved it?

**Comment by glide-the** [comment]
first run docker build  ,build images after to run container
