### ISSUE TITLE
[BUG] kb_config.py.exmaple文件名错误，应当是example，导致copy_config_example.py漏了此文件

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1656]
**问题描述 / Problem Description**
configs目录kb_config.py.exmaple文件名错误，应当是example，导致copy_config_example.py漏了此文件

**复现问题的步骤 / Steps to Reproduce**
1、执行python copy_config_example.py
2、打开configs目录，kb_config.py没有生成
3、文件名后缀单词拼写错误

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.5
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by szdengdi** [comment]
修改文件名kb_config.py.exmaple，为kb_config.py.example即可

**Comment by liunux4odoo** [comment]
感谢反馈。开发版已经修复，当前可以先手动复制文件。
