### ISSUE TITLE
Docker镜像已经失效了

### ISSUE THREAD

**Issue by digitalghost** [chatchat-space/Langchain-Chatchat#1660]
兄弟，这个docker镜像无法访问了
docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5

**Comment by FlintyLemming** [comment]
容器镜像最新貌似只有 0.2.3

**Comment by zoneRohn** [comment]
> 容器镜像最新貌似只有 0.2.3

0.2.3的也不行了一个月之前还可以部署的，今天就不行了...

**Comment by DrayChou** [comment]
现在都是 404 了，求助

**Comment by QiuZiXian** [comment]
我这会也拉不到镜像。求帮助

**Comment by thadous** [comment]
同拉不到镜像

**Comment by Pengyia** [comment]
docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5
镜像无法访问

**Comment by viannecc** [comment]
看来之前大家的评论，试了只有0.2.3还能拉取

**Comment by Pengyia** [comment]
确实，0.2.3镜像可以正常拉取

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.5 修改部分太多，镜像还没有制作完成，因此最后还没有上线dockerimage

**Comment by DrayChou** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/1692
