### ISSUE TITLE
想在输入的部分添加一层systemprompt，但找不到输入部分在哪里

### ISSUE THREAD

**Issue by BryanMurkyChan** [chatchat-space/Langchain-Chatchat#1661]
我想在langchain-chatchat的基础上，设置一层systemprompt，让模型固定扮演某一角色进行后续的聊天以及知识库检索，但是在startup.py中找不到用户输入文本的位置，在fastchat中也没有找到相关的输入部分，请问在哪里呢？

**Comment by zRzRzRzRzRzRzR** [comment]
不是所有的模型都支持system Prompt的，所以我们没有设置通用的systemPrompt模块，你可以尝试在llm的提示词部分自己加，这样每次调用都会有固定的提示词
