### ISSUE TITLE
[BUG] 脱网之后不能继续进行对话

### ISSUE THREAD

**Issue by libo119111** [chatchat-space/Langchain-Chatchat#1663]
**问题描述 / 脱网之后不能继续进行回答**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / python 3.10 .13**
- langchain-ChatGLM 版本/最新版 号：
- 是否使用 Docker 部署（是/否）：是否/ Is Docker deployment used (yes/no): yes
- 使用的模型: ChatGLM2-6B
- 使用的 Embedding 模型）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by libo119111** [comment]
![f64320c4c0f9caf5ea2417a1614d068](https://github.com/chatchat-space/Langchain-Chatchat/assets/78672081/640e8db0-83d8-4b7a-bb02-d16542be1524)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/78672081/aa0e0ffe-4b60-455e-a9f9-05ac88ac907a)

**Comment by zRzRzRzRzRzRzR** [comment]
用127.0.0.1，用的是全部本地的模型，数据库和分词器可以脱网运行
