### ISSUE TITLE
[BUG] 添加文件向量化时服务端报错

### ISSUE THREAD

**Issue by lesliewang895** [chatchat-space/Langchain-Chatchat#1664]
部署了新的0.2.5版本，通过webui把一个docx文档上传服务器后，鼠标点击“添加文件到知识库”按钮，页面上显示正常添加了，但服务器终端显示以下错误：
'(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): 
Max retries exceeded with url: /gpt2/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x148e57e79d50>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: 9dc95d75-05c7-4214-869a-098cb440e710)')' thrown while requesting HEAD https://huggingface.co/gpt2/resolve/main/tokenizer_config.json

用浏览器访问[这个url](https://huggingface.co/gpt2/resolve/main/tokenizer_config.json)，页面显示没有这个json文件。

![b1cdf4e717b656f0dd4056d65149bdd](https://github.com/chatchat-space/Langchain-Chatchat/assets/35760927/a0f971ca-80ca-4b5b-9a06-4d443d9c0760)

**Comment by huangyu996** [comment]
same issue here when upload a .doc or docx file to KB

**Comment by liunux4odoo** [comment]
可以把你使用的分词器中的gpt2等内容删掉：
```
    "ChineseRecursiveTextSplitter": {
        "source": "",  ## 选择tiktoken则使用openai的方法
        "tokenizer_name_or_path": "",
    },
```
