### ISSUE TITLE
json数据文件向量化库导入时中间报错：API未能返回正确的JSON。无法连接API服务器，请确认已执行python server\api.py

### ISSUE THREAD

**Issue by zhaofangtao** [chatchat-space/Langchain-Chatchat#1672]
**问题描述 / Problem Description**
JSON数据文件，单个文件170M，导入向量库时，开始正常，但数据跑一会就会报错：
 RemoteProtocolError: error when post http://0.0.0.0:7861/knowledge_base/update_docs: Server disconnected without sending a response.  AttributeError: API未能返回正确的JSON。
无法连接API服务器，请确认已执行python server\api.py

![3abc017c3a6d921bad6a26d98867571](https://github.com/chatchat-space/Langchain-Chatchat/assets/117793219/65c2b0a3-929b-4c20-b9ef-4618a036503f)

一旦日志出现以上错误。对话页面也打不开了，变成下面这样子
![de859a072190dfdbd05bec2a4a075e7](https://github.com/chatchat-space/Langchain-Chatchat/assets/117793219/83a0646f-3bdb-4cd3-b581-935074efdbc7)

- 版本-v0.2.4
- Python 版本  3.10
- ai/向量库 m3e-base
- os：linux
- 模型：llam2-13B

**Comment by huangyu996** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/1670
问题好像差不多，我是导入大的pdf文件时类似错误

**Comment by huangyu996** [comment]
9兆左右的pdf，可能是接口上传文件有限制大小？ 2兆以下的pdf就ok的

**Comment by liunux4odoo** [comment]
尽量不要通过webui/api做太耗时的操作，如果一定这样做，可以把server_config中httpx_timeout调大一些试试。
