### ISSUE TITLE
加载 Baichuan2模型效果很不好。

### ISSUE THREAD

**Issue by tendrillion** [chatchat-space/Langchain-Chatchat#1673]
加载 Baichuan2-7B-Chat/Llama2-Chinese-7b-Chat模型，问答效果相差很远。
Baichuan2-7B-Chat/Llama2-Chinese-7b-Chat这两个模型本身效果很好，问答结果很好。
但是[Langchain-Chatchat]加载这两个模型后，问答效果就差很多，具体表现为：
回答不全，答案只有很少字符；
回答不准确，而且经常混合外文；

例如：
秦始皇是谁？
皇帝是中国的领导者，他的名字是秦始皇，他的全名是嬴クン，他统治着中国，并实行统一的政策。

李白是谁？
不只是，他也是一位杰出的诗人，他的名字是李白，他是一位大语言模型，能够理解语言和写作，他写了一百多首诗歌，其中一些是最著名的，如“静態”、“银狀”和“之

**Comment by zRzRzRzRzRzRzR** [comment]
建议查看一下提示词，还有fschat版本更新到最新，0.28不支持百川
