### ISSUE TITLE
[BUG] 知识库录入docx文件时报错，Token indices sequence length is longer than the specified maximum sequence length for this model (2263 > 1024). Running this sequence through the model will result in indexing error

### ISSUE THREAD

**Issue by houmo03** [chatchat-space/Langchain-Chatchat#1677]
**问题描述 / Problem Description**

使用autodl的v9镜像，模型为qwen-14b-int4，在知识库里录入docx文件时，报错，内容为

Token indices sequence length is longer than the specified maximum sequence length for this model (2263 > 1024). Running this sequence through the model will result in indexing error

几乎每篇文章都会出现，区别是数字不同 

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-100-generic-x86_64-with-glibc2.31.
python版本：3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
项目版本：v0.2.5
langchain版本：0.0.306. fastchat版本：0.2.29

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-14B-Chat-Int4'] @ cuda
2023-10-07 18:58:22,370 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpcbinutux
2023-10-07 18:58:22,371 - instantiator.py[line:76] - INFO: Writing /tmp/tmpcbinutux/_remote_module_non_scriptable.py
[2023-10-07 18:58:22,943] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'model_path': '/root/autodl-tmp/Qwen-14B-Chat-Int4',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

**Comment by sinopec** [comment]
同样的问题

**Comment by zRzRzRzRzRzRzR** [comment]
这是超出了模型的长度限制，确定一下模型的限制是否有问题，在dev版本中我们仅仅在startup对模型token限制，（startup设置为8192），因此如果在dev版本还出现这个问题，就是超出模型token长度
