### ISSUE TITLE
[BUG] 0.25版本下object has no attribute 'sp_model' 问题

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#1689]
1、已正常安装好依赖环境、执行初始化数据
2、model_config.py内容主要修改如下
```
MODEL_PATH = {
    "embed_model": {
		...
        "piccolo-base-zh": "/data/Embedding_Project//piccolo-base-zh",
		...
    },
    "llm_model": {
		...
        "Baichuan2-13B-chat": "/data/LLM_Project/Baichuan2-13B-Chat",
		"internlm-chat-20B":"/data/LLM_Project/internlm-chat-20b",
		...
	}
}
```
3、执行python3 startup.py -a
4、出现object has no attribute 'sp_model' 错误，尝试更换多种LLM存在同样的问题
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/0279a47b-a0f1-493c-9383-034bca5d99d6)

**Comment by yinglou2012** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/147223509/7f2ab380-f8fd-405f-aade-c3bdd011803f)
第一轮问答没问题，第二轮就出现了
