### ISSUE TITLE
 'NoneType' object has no attribute 'message_types_by_name'报错

### ISSUE THREAD

**Issue by mls2009** [chatchat-space/Langchain-Chatchat#169]
_HISTOGRAMPROTO = DESCRIPTOR.message_types_by_name['HistogramProto']
AttributeError: 'NoneType' object has no attribute 'message_types_by_name'

环境是python3.10

**Comment by zqt996** [comment]
3.8可以我的是就行可以运行出来,可以换下试试

**Comment by gdchaochao** [comment]
我用的也是3.10也遇到这个问题，改python有点麻烦，我选择的是改依赖的版本。我卸载protobuf重新装这个版本。起码这个问题不会报了。
pip3 install protobuf==3.19.3

**Comment by sawyerbutton** [comment]
> 我用的也是3.10也遇到这个问题，改python有点麻烦，我选择的是改依赖的版本。我卸载protobuf重新装这个版本。起码这个问题不会报了。 pip3 install protobuf==3.19.3

使用Colab时这个问题依然存在，似乎是Colab自己不允许降级的原因
