### ISSUE TITLE
[BUG] docker镜像无法拉取 0.2.5

### ISSUE THREAD

**Issue by airclear** [chatchat-space/Langchain-Chatchat#1692]
如下：

```
PS C:\Users\Administrator> docker pull registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5
Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5 not found: manifest unknown: manifest unknown
PS C:\Users\Administrator>
```

**Comment by zhanbinHo** [comment]
遇到一样的问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20354178/b50714b2-b1eb-421b-b0a0-7bd150f8412f)

**Comment by fye** [comment]
一样的问题。

**Comment by gitlyp** [comment]
一样
docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5
Unable to find image 'registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5' locally
docker: Error response from daemon: manifest for registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.5 not found: manifest unknown: manifest unknown.
直接 pull也失败了
 docker pull chatchat/chatchat:0.2.5
Error response from daemon: pull access denied for chatchat/chatchat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by gitlyp** [comment]
换个版本就可以 文档写的有问题

docker pull  registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.3

**Comment by zRzRzRzRzRzRzR** [comment]
目前只有0.2.3 因为0.2.5的版本变化太大开发组来不及做docker，还得等一段时间
