### ISSUE TITLE
[BUG] windows下安装了angchain+chatglm2-6B，命令行窗口提示服务已启动，但是webui服务打不开，8501的端口没在监听请求，API服务可正常访问

### ISSUE THREAD

**Issue by JustDoItToo** [chatchat-space/Langchain-Chatchat#1693]
**问题描述 / Problem Description**
安装了langchain+chatglm2-6B，命令行窗口提示服务已经启动了，但是webui的URL打不开，查看端口，8501的端口并没有在监听请求，但是其他的端口都起来了，API服务可正常访问

**预期的结果 / Expected Result**
webUI页面可以打开

**实际结果 / Actual Result**
打开webui服务地址时，提示无法访问此页面，拒绝连接。怀疑是webUI服务没启动成功，但是日志没有异常信息

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:   Windows10
- Python 版本 / Python version: 3.10.12

**Comment by JustDoItToo** [comment]
怀疑是webUI服务没有启动起来，但是日志没有报错

**Comment by ItsZhengyd** [comment]
仔细观察控制台，第一次启动后控制台需要输入一个邮箱，然后按回车就可以了。否则就是你这种情况。

**Comment by JustDoItToo** [comment]
> 仔细观察控制台，第一次启动后控制台需要输入一个邮箱，然后按回车就可以了。否则就是你这种情况。

果然如此，已经可以访问了，非常感谢

**Comment by lihui123456** [comment]
我也报这个错误，请问下是怎么解决的呢 ？那个控制台输入邮箱每太看懂，能描述具体一点吗

**Comment by rizi960** [comment]
直接敲个回车就可以了，一次就管用
