### ISSUE TITLE
[BUG] 新创建知识库之后，知识库 问答，页面显示报错：AttributeError: 'Markdown' object has no attribute 'content'

### ISSUE THREAD

**Issue by zhanbei1** [chatchat-space/Langchain-Chatchat#1696]
**问题描述 / Problem Description**
新创建知识库之后，知识库问答，页面显示报错：AttributeError: 'Markdown' object has no attribute 'content' / 'state'

**复现问题的步骤 / Steps to Reproduce**
1. 版本：master分支【日期：2023-10-08】,commit号：295783b5
2. 创建知识库，并上传文件，使用的向量数据库是：milvus ，embedding模型为： 本地m3e-small)
3. 选择文件，添加到向量库，无响应（这个不确定是否为bug）
![截屏2023-10-08 16 44 00](https://github.com/chatchat-space/Langchain-Chatchat/assets/23068139/d1e479b5-ef27-4f91-a7f1-bd48ed02d690)

5. 知识库问，报错如下：
![截屏2023-10-08 16 46 21](https://github.com/chatchat-space/Langchain-Chatchat/assets/23068139/3ec73cec-19ca-40b6-aa36-1b4171d8ef88)

6. 报错信息文本如下：
`2023-10-08 16:36:35.049 Uncaught app exception
Traceback (most recent call last):
  File "/root/desmond_zhan/Langchain-Chatchat/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/root/desmond_zhan/Langchain-Chatchat/webui.py", line 66, in <module>
    pages[selected_page]["func"](api)
  File "/root/desmond_zhan/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 145, in dialogue_page
    history = get_messages_history(history_len)
  File "/root/desmond_zhan/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 36, in get_messages_history
    return chat_box.filter_history(history_len=history_len, filter=filter)
  File "/root/desmond_zhan/Langchain-Chatchat/venv/lib/python3.9/site-packages/streamlit_chatbox/messages.py", line 120, in filter_history
    filtered = filter(msg)
  File "/root/desmond_zhan/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 29, in filter
    content = [x.content for x in content]
  File "/root/desmond_zhan/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 29, in <listcomp>
    content = [x.content for x in content]
AttributeError: 'Markdown' object has no attribute 'content'`
或者是：TypeError: markdown() got an unexpected keyword argument 'state'

**环境信息 / Environment Information**
- langchain-ChatGLM commit 号：295783b5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipu-api。 verison:：chatglm_pro
- 使用的 Embedding 模型：m3e-small
- 使用的向量库类型 ： milvus
- 操作系统及版本 / Operating system and version: CentOS Linux release 7.6.1810 (Core)
- Python 版本 / Python version: 3.9.18
- 其他相关环境信息 / Other relevant environment information:

**Comment by liamlincs** [comment]
ubuntu 22.04 ChatGLM2-6B-int4 faiss Python3.10.12
也是一样的问题

**Comment by zhanbei1** [comment]
估计是新版本的问题，他们还没来的及修改。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] [BUG] 新创建知识库之后，知识库 问答，页面显示报错：AttributeError: 'Markdown' object has no attribute 'content' (Issue #1696)





 
ubuntu 22.04 ChatGLM2-6B-int4 faiss Python3.10.12
 也是一样的问题

**Comment by zhanbei1** [comment]
问题追加补充：主要是这个文件中的提交存在问题webui_pages/dialogue/dialogue.py
对应修改如下，即可继续使用（不知道是否影响其他内容，不做提交）
![截屏2023-10-08 19 05 17](https://github.com/chatchat-space/Langchain-Chatchat/assets/23068139/8951e013-6bae-4b0b-bfed-73360c70538e)

同时新增一个bug：【多次资料库问答，出现Markdown对象无法序列化】https://github.com/chatchat-space/Langchain-Chatchat/issues/1699
报错信息：Object of type Markdown is not JSON serializable

同时，仍旧无法在资料库管理中，将文件添加到向量库

**Comment by gumanchang** [comment]
我也这个报错

**Comment by zhanbei1** [comment]
> 我也这个报错

按照上面的改一下就可以继续用，但是还是等维护者修改吧，我这不确定影响范围，不干提交PR

**Comment by liunux4odoo** [comment]
代码升级到0.2.5版后有更新依赖吗？streamlit-chatbox需要1.1.9

**Comment by zhanbei1** [comment]
> 代码升级到0.2.5版后有更新依赖吗？streamlit-chatbox需要1.1.9

的确是这个问题，已经解决
