### ISSUE TITLE
[BUG] Win环境中，使用cpu运行模型，程序启动成功，页面渲染完成，输入问题后，后端出现报错

### ISSUE THREAD

**Issue by Kason-wu** [chatchat-space/Langchain-Chatchat#1698]
**问题描述 / Problem Description**
Win环境中，使用cpu运行模型，程序启动成功，页面渲染完成，输入问题后，后端出现报错

**复现问题的步骤 / Steps to Reproduce**
1. 运行程序，python start.py
2. 输入语句   你好
3. 问题出现 /  ERROR: KeyError: Caught exception: "choices"

**预期的结果 / Expected Result**
回答我的问题

**实际结果 / Actual Result**
![企业微信截图_16967591915426](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/dda04cbb-37c4-4a5e-8438-c5f929584cb9)

![企业微信截图_16967592212342](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/628a0fea-3165-4615-989a-dfd6309dd153)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.24
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Win10
- Python 版本 / Python version: 3.9.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
cpu跑的话，把server_config中httpx_timeout的值调大到600以上试试

**Comment by Kason-wu** [comment]
修改server_config中httpx_timeout的值调大到600以上，还是不行，依旧出现上述报错；问答时，出现如下页面错误
![Uploading 企业微信截图_16969038802726.png…]()

**Comment by Kason-wu** [comment]
修改server_config中httpx_timeout的值调大到600以上，还是不行，依旧出现上述报错；问答时，出现如下页面错误
[https://i.postimg.cc/JhVvvZ8J/16969038802726.png](url)

**Comment by Kason-wu** [comment]
> cpu跑的话，把server_config中httpx_timeout的值调大到600以上试试

修改server_config中httpx_timeout的值调大到600以上，还是不行，依旧出现上述报错；问答时，出现如下页面错误
![企业微信截图_16969038802726](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/84857fd3-6088-4ed4-9742-42e692fccd39)

**Comment by liunux4odoo** [comment]
> > cpu跑的话，把server_config中httpx_timeout的值调大到600以上试试
> 
> 修改server_config中httpx_timeout的值调大到600以上，还是不行，依旧出现上述报错；问答时，出现如下页面错误 ![企业微信截图_16969038802726](https://user-images.githubusercontent.com/72248809/273758742-84857fd3-6088-4ed4-9742-42e692fccd39.png)

更新代码后需要更新依赖，streamlit-chatbox版本不对

**Comment by Kason-wu** [comment]
> > > cpu跑的话，把server_config中httpx_timeout的值调大到600以上试试
> > 
> > 
> > 修改server_config中httpx_timeout的值调大到600以上，还是不行，依旧出现上述报错；问答时，出现如下页面错误 ![企业微信截图_16969038802726](https://user-images.githubusercontent.com/72248809/273758742-84857fd3-6088-4ed4-9742-42e692fccd39.png)
> 
> 更新代码后需要更新依赖，streamlit-chatbox版本不对

依赖更新后，现在不报错了，页面显示了知识哭结果，但是没有给出回答，控制台，依旧出现choices的问题
![企业微信截图_16969080837127](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/5f4aecfd-eb99-47b7-bf78-a0e5b4aa5d01)

![企业微信截图_16969080588939](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/ddc6c565-08ca-417a-9fb4-7b288a6bb525)

**Comment by yinshujuanqiwu** [comment]
请问解决了吗，我也遇到了一样的错误

**Comment by Kason-wu** [comment]
还没有回复

| |
Kason_Wu
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年10月12日 14:47 |
| 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> |
| 抄送人 | Kason_Wu ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] [BUG] Win环境中，使用cpu运行模型，程序启动成功，页面渲染完成，输入问题后，后端出现报错 (Issue #1698) |

请问解决了吗，我也遇到了一样的错误

**Comment by liunux4odoo** [comment]
@Kason-wu 你是如何启动的？尽量把请求时的完整log贴上来

**Comment by Kason-wu** [comment]
步骤：1.本地下载langchain代码
2.下载glm-6b和m3e-base模型至本地，修改对应路径
3.执行数据库python init_database.py --recreate-vs
4.pip install -r requirements.txt
5.python startup.py -a

**Comment by Kason-wu** [comment]
python3 startup.py -a
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-144-generic-x86_64-with-glibc2.29.
python版本：3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
项目版本：v0.2.4
langchain版本：0.0.310. fastchat版本：0.2.29
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm-6b'] @ cpu
{'api_base_url': 'http://192.168.2.134:8888/v1',
'api_key': 'EMPTY',
'local_model_path': 'THUDM/chatglm-6b'}
当前Embbedings模型： text2vec @ cpu
==============================Langchain-Chatchat Configuration==============================
2023-10-13 06:06:34,508 - startup.py[line:541] - INFO: 正在启动服务：
2023-10-13 06:06:34,509 - startup.py[line:542] - INFO: 如需查看 llm_api 日志，请前往 /home/Langchain-Chatchat-0.2.4/logs
2023-10-13 06:06:36,624 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpl7clgv5y
2023-10-13 06:06:36,625 - instantiator.py[line:76] - INFO: Writing /tmp/tmpl7clgv5y/_remote_module_non_scriptable.py
2023-10-13 06:06:38 | ERROR | stderr | INFO: Started server process [4121383]
2023-10-13 06:06:38 | ERROR | stderr | INFO: Waiting for application startup.
2023-10-13 06:06:38 | ERROR | stderr | INFO: Application startup complete.
2023-10-13 06:06:38 | ERROR | stderr | INFO: Uvicorn running on http://192.168.2.134:8888 (Press CTRL+C to quit)
2023-10-13 06:06:40,605 - instantiator.py[line:21] - INFO: Created a temporary directory at /tmp/tmpu_kdjhg2
2023-10-13 06:06:40,606 - instantiator.py[line:76] - INFO: Writing /tmp/tmpu_kdjhg2/_remote_module_non_scriptable.py
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at THUDM/chatglm-6b and are newly initialized: ['transformer.layers.20.mlp.dense_h_to_4h.weight', 'transformer.layers.8.input_layernorm.bias', 'transformer.layers.4.attention.dense.bias', 'transformer.layers.16.mlp.dense_4h_to_h.bias', 'transformer.layers.0.mlp.dense_h_to_4h.weight', 'transformer.layers.4.attention.query_key_value.weight', 'transformer.layers.16.post_attention_layernorm.bias', 'transformer.layers.1.attention.dense.bias', 'transformer.layers.22.input_layernorm.weight', 'transformer.layers.11.attention.dense.weight', 'transformer.layers.7.mlp.dense_4h_to_h.bias', 'transformer.layers.3.mlp.dense_h_to_4h.weight', 'transformer.layers.9.attention.dense.bias', 'transformer.layers.25.mlp.dense_4h_to_h.bias', 'transformer.layers.12.attention.rotary_emb.inv_freq', 'transformer.layers.13.mlp.dense_4h_to_h.weight', 'transformer.layers.26.mlp.dense_h_to_4h.weight', 'transformer.layers.23.input_layernorm.weight', 'transformer.layers.1.post_attention_layernorm.bias', 'transformer.layers.23.input_layernorm.bias', 'transformer.layers.7.post_attention_layernorm.weight', 'transformer.layers.11.attention.dense.bias', 'transformer.layers.7.attention.dense.bias', 'transformer.layers.15.attention.dense.weight', 'transformer.layers.23.post_attention_layernorm.weight', 'transformer.layers.2.attention.query_key_value.bias', 'transformer.layers.18.input_layernorm.bias', 'transformer.layers.15.post_attention_layernorm.bias', 'transformer.layers.17.attention.dense.weight', 'transformer.layers.22.input_layernorm.bias', 'transformer.layers.11.input_layernorm.weight', 'transformer.layers.13.attention.dense.bias', 'transformer.layers.17.mlp.dense_4h_to_h.weight', 'transformer.layers.27.input_layernorm.weight', 'transformer.layers.20.mlp.dense_4h_to_h.bias', 'transformer.layers.13.attention.dense.weight', 'transformer.layers.17.attention.query_key_value.bias', 'transformer.layers.14.attention.dense.weight', 'transformer.layers.2.post_attention_layernorm.bias', 'transformer.layers.4.attention.dense.weight', 'transformer.layers.2.attention.query_key_value.weight', 'transformer.layers.24.attention.query_key_value.bias', 'transformer.layers.14.mlp.dense_h_to_4h.weight', 'transformer.layers.6.mlp.dense_4h_to_h.weight', 'transformer.layers.16.input_layernorm.bias', 'transformer.layers.25.post_attention_layernorm.weight', 'transformer.layers.12.attention.query_key_value.weight', 'transformer.layers.22.post_attention_layernorm.bias', 'transformer.layers.26.input_layernorm.weight', 'transformer.layers.18.attention.dense.weight', 'transformer.layers.10.attention.query_key_value.bias', 'transformer.layers.26.attention.rotary_emb.inv_freq', 'transformer.layers.12.input_layernorm.bias', 'transformer.layers.10.input_layernorm.weight', 'transformer.layers.8.attention.query_key_value.bias', 'transformer.final_layernorm.weight', 'transformer.layers.2.mlp.dense_4h_to_h.weight', 'transformer.layers.24.input_layernorm.bias', 'transformer.layers.3.post_attention_layernorm.weight', 'transformer.layers.14.post_attention_layernorm.bias', 'transformer.layers.25.attention.query_key_value.bias', 'transformer.layers.25.attention.dense.weight', 'transformer.layers.16.attention.dense.bias', 'transformer.layers.6.post_attention_layernorm.weight', 'transformer.layers.2.attention.dense.weight', 'transformer.layers.1.input_layernorm.bias', 'transformer.layers.16.mlp.dense_h_to_4h.weight', 'transformer.layers.4.mlp.dense_4h_to_h.weight', 'transformer.layers.26.mlp.dense_4h_to_h.weight', 'transformer.layers.19.input_layernorm.bias', 'transformer.layers.11.attention.rotary_emb.inv_freq', 'transformer.layers.6.attention.query_key_value.bias', 'transformer.layers.27.mlp.dense_4h_to_h.bias', 'transformer.layers.17.mlp.dense_h_to_4h.bias', 'transformer.layers.6.attention.query_key_value.weight', 'transformer.layers.15.attention.rotary_emb.inv_freq', 'transformer.layers.1.post_attention_layernorm.weight', 'transformer.layers.21.attention.rotary_emb.inv_freq', 'transformer.layers.10.post_attention_layernorm.bias', 'transformer.layers.8.post_attention_layernorm.bias', 'transformer.layers.7.post_attention_layernorm.bias', 'transformer.layers.23.mlp.dense_h_to_4h.weight', 'transformer.layers.12.mlp.dense_h_to_4h.weight', 'transformer.layers.5.mlp.dense_4h_to_h.weight', 'transformer.layers.2.attention.dense.bias', 'transformer.layers.4.post_attention_layernorm.weight', 'transformer.layers.23.mlp.dense_4h_to_h.weight', 'transformer.layers.0.mlp.dense_4h_to_h.weight', 'transformer.layers.4.post_attention_layernorm.bias', 'transformer.layers.9.input_layernorm.weight', 'transformer.layers.20.post_attention_layernorm.bias', 'transformer.layers.6.mlp.dense_h_to_4h.weight', 'transformer.layers.12.mlp.dense_4h_to_h.bias', 'transformer.layers.1.mlp.dense_h_to_4h.weight', 'transformer.layers.17.attention.dense.bias', 'lm_head.weight', 'transformer.layers.20.mlp.dense_h_to_4h.bias', 'transformer.layers.1.attention.query_key_value.bias', 'transformer.final_layernorm.bias', 'transformer.layers.12.attention.query_key_value.bias', 'transformer.layers.22.attention.rotary_emb.inv_freq', 'transformer.layers.10.mlp.dense_h_to_4h.weight', 'transformer.layers.14.attention.rotary_emb.inv_freq', 'transformer.layers.16.attention.rotary_emb.inv_freq', 'transformer.layers.0.mlp.dense_4h_to_h.bias', 'transformer.layers.24.input_layernorm.weight', 'transformer.layers.25.attention.rotary_emb.inv_freq', 'transformer.layers.5.attention.dense.bias', 'transformer.layers.16.mlp.dense_4h_to_h.weight', 'transformer.layers.25.mlp.dense_4h_to_h.weight', 'transformer.layers.11.post_attention_layernorm.bias', 'transformer.layers.25.attention.query_key_value.weight', 'transformer.layers.18.post_attention_layernorm.bias', 'transformer.layers.10.mlp.dense_h_to_4h.bias', 'transformer.layers.21.post_attention_layernorm.weight', 'transformer.layers.2.mlp.dense_h_to_4h.weight', 'transformer.layers.9.attention.query_key_value.weight', 'transformer.layers.17.attention.query_key_value.weight', 'transformer.layers.0.mlp.dense_h_to_4h.bias', 'transformer.layers.23.attention.dense.bias', 'transformer.layers.3.attention.query_key_value.weight', 'transformer.layers.3.mlp.dense_4h_to_h.bias', 'transformer.layers.20.attention.query_key_value.weight', 'transformer.layers.14.input_layernorm.weight', 'transformer.layers.14.mlp.dense_h_to_4h.bias', 'transformer.layers.20.attention.query_key_value.bias', 'transformer.layers.5.mlp.dense_4h_to_h.bias', 'transformer.layers.18.attention.dense.bias', 'transformer.layers.0.post_attention_layernorm.bias', 'transformer.layers.8.mlp.dense_h_to_4h.weight', 'transformer.layers.27.attention.dense.bias', 'transformer.layers.25.mlp.dense_h_to_4h.bias', 'transformer.layers.0.attention.rotary_emb.inv_freq', 'transformer.layers.13.mlp.dense_4h_to_h.bias', 'transformer.layers.10.post_attention_layernorm.weight', 'transformer.layers.6.post_attention_layernorm.bias', 'transformer.layers.19.mlp.dense_4h_to_h.weight', 'transformer.layers.5.attention.query_key_value.weight', 'transformer.layers.0.attention.dense.weight', 'transformer.layers.4.input_layernorm.bias', 'transformer.layers.8.mlp.dense_h_to_4h.bias', 'transformer.layers.9.post_attention_layernorm.weight', 'transformer.layers.12.post_attention_layernorm.bias', 'transformer.layers.27.mlp.dense_h_to_4h.weight', 'transformer.layers.11.mlp.dense_4h_to_h.weight', 'transformer.layers.17.post_attention_layernorm.bias', 'transformer.layers.4.mlp.dense_h_to_4h.weight', 'transformer.layers.14.post_attention_layernorm.weight', 'transformer.layers.22.mlp.dense_4h_to_h.bias', 'transformer.layers.27.attention.query_key_value.bias', 'transformer.layers.20.attention.dense.bias', 'transformer.layers.8.mlp.dense_4h_to_h.bias', 'transformer.layers.11.input_layernorm.bias', 'transformer.layers.21.attention.query_key_value.weight', 'transformer.layers.18.mlp.dense_h_to_4h.weight', 'transformer.layers.5.mlp.dense_h_to_4h.bias', 'transformer.layers.26.post_attention_layernorm.weight', 'transformer.layers.8.input_layernorm.weight', 'transformer.layers.24.attention.query_key_value.weight', 'transformer.layers.7.input_layernorm.bias', 'transformer.layers.21.input_layernorm.weight', 'transformer.layers.2.input_layernorm.bias', 'transformer.layers.10.mlp.dense_4h_to_h.weight', 'transformer.layers.16.attention.dense.weight', 'transformer.layers.18.attention.rotary_emb.inv_freq', 'transformer.layers.24.attention.dense.weight', 'transformer.layers.19.mlp.dense_4h_to_h.bias', 'transformer.layers.19.attention.dense.weight', 'transformer.layers.19.attention.dense.bias', 'transformer.layers.11.post_attention_layernorm.weight', 'transformer.layers.23.attention.dense.weight', 'transformer.layers.18.mlp.dense_4h_to_h.weight', 'transformer.layers.23.attention.query_key_value.weight', 'transformer.layers.3.input_layernorm.bias', 'transformer.layers.23.attention.rotary_emb.inv_freq', 'transformer.layers.9.mlp.dense_4h_to_h.bias', 'transformer.layers.22.attention.query_key_value.weight', 'transformer.layers.2.input_layernorm.weight', 'transformer.layers.24.post_attention_layernorm.bias', 'transformer.layers.27.attention.dense.weight', 'transformer.layers.12.mlp.dense_4h_to_h.weight', 'transformer.layers.20.input_layernorm.bias', 'transformer.layers.23.attention.query_key_value.bias', 'transformer.layers.6.input_layernorm.bias', 'transformer.layers.4.attention.query_key_value.bias', 'transformer.layers.16.attention.query_key_value.weight', 'transformer.layers.1.attention.dense.weight', 'transformer.layers.26.mlp.dense_4h_to_h.bias', 'transformer.layers.12.input_layernorm.weight', 'transformer.layers.9.attention.dense.weight', 'transformer.layers.27.post_attention_layernorm.bias', 'transformer.layers.13.mlp.dense_h_to_4h.bias', 'transformer.layers.22.post_attention_layernorm.weight', 'transformer.layers.22.attention.query_key_value.bias', 'transformer.layers.5.attention.dense.weight', 'transformer.layers.0.attention.query_key_value.weight', 'transformer.layers.7.attention.dense.weight', 'transformer.layers.14.attention.dense.bias', 'transformer.layers.18.input_layernorm.weight', 'transformer.layers.6.attention.dense.bias', 'transformer.layers.20.input_layernorm.weight', 'transformer.layers.16.attention.query_key_value.bias', 'transformer.layers.8.attention.dense.bias', 'transformer.layers.16.mlp.dense_h_to_4h.bias', 'transformer.layers.14.input_layernorm.bias', 'transformer.layers.24.mlp.dense_4h_to_h.bias', 'transformer.layers.19.post_attention_layernorm.bias', 'transformer.layers.19.mlp.dense_h_to_4h.bias', 'transformer.layers.13.attention.query_key_value.weight', 'transformer.layers.21.attention.dense.bias', 'transformer.layers.9.attention.query_key_value.bias', 'transformer.layers.26.attention.query_key_value.weight', 'transformer.layers.10.attention.query_key_value.weight', 'transformer.layers.14.mlp.dense_4h_to_h.bias', 'transformer.layers.0.attention.dense.bias', 'transformer.layers.18.mlp.dense_4h_to_h.bias', 'transformer.layers.19.attention.rotary_emb.inv_freq', 'transformer.layers.13.attention.rotary_emb.inv_freq', 'transformer.layers.17.attention.rotary_emb.inv_freq', 'transformer.layers.17.post_attention_layernorm.weight', 'transformer.layers.27.mlp.dense_h_to_4h.bias', 'transformer.layers.10.mlp.dense_4h_to_h.bias', 'transformer.layers.21.mlp.dense_4h_to_h.weight', 'transformer.layers.11.attention.query_key_value.bias', 'transformer.layers.15.attention.dense.bias', 'transformer.layers.20.attention.dense.weight', 'transformer.layers.26.post_attention_layernorm.bias', 'transformer.layers.16.input_layernorm.weight', 'transformer.layers.6.input_layernorm.weight', 'transformer.layers.3.attention.dense.weight', 'transformer.layers.5.attention.rotary_emb.inv_freq', 'transformer.layers.21.attention.dense.weight', 'transformer.layers.24.mlp.dense_4h_to_h.weight', 'transformer.layers.22.mlp.dense_4h_to_h.weight', 'transformer.layers.19.attention.query_key_value.weight', 'transformer.word_embeddings.weight', 'transformer.layers.3.attention.rotary_emb.inv_freq', 'transformer.layers.4.mlp.dense_h_to_4h.bias', 'transformer.layers.10.attention.dense.weight', 'transformer.layers.16.post_attention_layernorm.weight', 'transformer.layers.26.attention.dense.bias', 'transformer.layers.3.mlp.dense_h_to_4h.bias', 'transformer.layers.5.mlp.dense_h_to_4h.weight', 'transformer.layers.20.mlp.dense_4h_to_h.weight', 'transformer.layers.0.input_layernorm.weight', 'transformer.layers.11.mlp.dense_4h_to_h.bias', 'transformer.layers.27.attention.rotary_emb.inv_freq', 'transformer.layers.11.mlp.dense_h_to_4h.weight', 'transformer.layers.27.attention.query_key_value.weight', 'transformer.layers.24.mlp.dense_h_to_4h.bias', 'transformer.layers.13.mlp.dense_h_to_4h.weight', 'transformer.layers.12.attention.dense.weight', 'transformer.layers.0.post_attention_layernorm.weight', 'transformer.layers.4.attention.rotary_emb.inv_freq', 'transformer.layers.25.attention.dense.bias', 'transformer.layers.27.mlp.dense_4h_to_h.weight', 'transformer.layers.9.attention.rotary_emb.inv_freq', 'transformer.layers.25.input_layernorm.weight', 'transformer.layers.5.post_attention_layernorm.weight', 'transformer.layers.12.post_attention_layernorm.weight', 'transformer.layers.5.input_layernorm.weight', 'transformer.layers.9.mlp.dense_h_to_4h.bias', 'transformer.layers.15.attention.query_key_value.bias', 'transformer.layers.14.attention.query_key_value.weight', 'transformer.layers.9.mlp.dense_4h_to_h.weight', 'transformer.layers.21.post_attention_layernorm.bias', 'transformer.layers.24.post_attention_layernorm.weight', 'transformer.layers.13.post_attention_layernorm.weight', 'transformer.layers.9.input_layernorm.bias', 'transformer.layers.15.input_layernorm.weight', 'transformer.layers.14.attention.query_key_value.bias', 'transformer.layers.10.input_layernorm.bias', 'transformer.layers.23.post_attention_layernorm.bias', 'transformer.layers.25.post_attention_layernorm.bias', 'transformer.layers.15.mlp.dense_h_to_4h.bias', 'transformer.layers.12.attention.dense.bias', 'transformer.layers.15.attention.query_key_value.weight', 'transformer.layers.23.mlp.dense_h_to_4h.bias', 'transformer.layers.5.attention.query_key_value.bias', 'transformer.layers.2.post_attention_layernorm.weight', 'transformer.layers.1.attention.rotary_emb.inv_freq', 'transformer.layers.5.input_layernorm.bias', 'transformer.layers.18.attention.query_key_value.bias', 'transformer.layers.26.input_layernorm.bias', 'transformer.layers.15.mlp.dense_h_to_4h.weight', 'transformer.layers.13.input_layernorm.weight', 'transformer.layers.3.attention.query_key_value.bias', 'transformer.layers.22.attention.dense.weight', 'transformer.layers.1.input_layernorm.weight', 'transformer.layers.22.mlp.dense_h_to_4h.bias', 'transformer.layers.6.attention.rotary_emb.inv_freq', 'transformer.layers.25.input_layernorm.bias', 'transformer.layers.19.input_layernorm.weight', 'transformer.layers.13.input_layernorm.bias', 'transformer.layers.5.post_attention_layernorm.bias', 'transformer.layers.4.input_layernorm.weight', 'transformer.layers.22.attention.dense.bias', 'transformer.layers.6.mlp.dense_h_to_4h.bias', 'transformer.layers.9.post_attention_layernorm.bias', 'transformer.layers.7.attention.rotary_emb.inv_freq', 'transformer.layers.26.mlp.dense_h_to_4h.bias', 'transformer.layers.18.post_attention_layernorm.weight', 'transformer.layers.9.mlp.dense_h_to_4h.weight', 'transformer.layers.8.attention.query_key_value.weight', 'transformer.layers.26.attention.dense.weight', 'transformer.layers.3.mlp.dense_4h_to_h.weight', 'transformer.layers.11.mlp.dense_h_to_4h.bias', 'transformer.layers.22.mlp.dense_h_to_4h.weight', 'transformer.layers.21.mlp.dense_h_to_4h.weight', 'transformer.layers.21.mlp.dense_h_to_4h.bias', 'transformer.layers.10.attention.dense.bias', 'transformer.layers.23.mlp.dense_4h_to_h.bias', 'transformer.layers.17.mlp.dense_h_to_4h.weight', 'transformer.layers.15.input_layernorm.bias', 'transformer.layers.15.mlp.dense_4h_to_h.bias', 'transformer.layers.18.attention.query_key_value.weight', 'transformer.layers.6.attention.dense.weight', 'transformer.layers.0.input_layernorm.bias', 'transformer.layers.7.input_layernorm.weight', 'transformer.layers.3.attention.dense.bias', 'transformer.layers.12.mlp.dense_h_to_4h.bias', 'transformer.layers.1.mlp.dense_h_to_4h.bias', 'transformer.layers.7.mlp.dense_h_to_4h.weight', 'transformer.layers.7.mlp.dense_4h_to_h.weight', 'transformer.layers.17.input_layernorm.bias', 'transformer.layers.21.mlp.dense_4h_to_h.bias', 'transformer.layers.24.attention.rotary_emb.inv_freq', 'transformer.layers.3.input_layernorm.weight', 'transformer.layers.8.attention.dense.weight', 'transformer.layers.1.attention.query_key_value.weight', 'transformer.layers.21.input_layernorm.bias', 'transformer.layers.7.attention.query_key_value.bias', 'transformer.layers.8.post_attention_layernorm.weight', 'transformer.layers.3.post_attention_layernorm.bias', 'transformer.layers.1.mlp.dense_4h_to_h.bias', 'transformer.layers.13.attention.query_key_value.bias', 'transformer.layers.26.attention.query_key_value.bias', 'transformer.layers.20.attention.rotary_emb.inv_freq', 'transformer.layers.17.input_layernorm.weight', 'transformer.layers.15.mlp.dense_4h_to_h.weight', 'transformer.layers.19.attention.query_key_value.bias', 'transformer.layers.8.attention.rotary_emb.inv_freq', 'transformer.layers.8.mlp.dense_4h_to_h.weight', 'transformer.layers.4.mlp.dense_4h_to_h.bias', 'transformer.layers.1.mlp.dense_4h_to_h.weight', 'transformer.layers.27.input_layernorm.bias', 'transformer.layers.15.post_attention_layernorm.weight', 'transformer.layers.24.mlp.dense_h_to_4h.weight', 'transformer.layers.19.mlp.dense_h_to_4h.weight', 'transformer.layers.17.mlp.dense_4h_to_h.bias', 'transformer.layers.11.attention.query_key_value.weight', 'transformer.layers.19.post_attention_layernorm.weight', 'transformer.layers.24.attention.dense.bias', 'transformer.layers.6.mlp.dense_4h_to_h.bias', 'transformer.layers.20.post_attention_layernorm.weight', 'transformer.layers.2.mlp.dense_h_to_4h.bias', 'transformer.layers.18.mlp.dense_h_to_4h.bias', 'transformer.layers.10.attention.rotary_emb.inv_freq', 'transformer.layers.2.attention.rotary_emb.inv_freq', 'transformer.layers.27.post_attention_layernorm.weight', 'transformer.layers.14.mlp.dense_4h_to_h.weight', 'transformer.layers.2.mlp.dense_4h_to_h.bias', 'transformer.layers.25.mlp.dense_h_to_4h.weight', 'transformer.layers.7.mlp.dense_h_to_4h.bias', 'transformer.layers.13.post_attention_layernorm.bias', 'transformer.layers.21.attention.query_key_value.bias', 'transformer.layers.7.attention.query_key_value.weight', 'transformer.layers.0.attention.query_key_value.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.8/dist-packages/langchain/__init__.py:40: UserWarning: Importing LLMChain from langchain root module is no longer supported.
warnings.warn(
/usr/local/lib/python3.8/dist-packages/langchain/__init__.py:40: UserWarning: Importing LLMChain from langchain root module is no longer supported.
warnings.warn(
INFO: Started server process [4121632]
INFO: Waiting for application startup.
INFO: Application startup complete.
INFO: Uvicorn running on http://192.168.2.134:7861 (Press CTRL+C to quit)
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-144-generic-x86_64-with-glibc2.29.
python版本：3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0]
项目版本：v0.2.4
langchain版本：0.0.310. fastchat版本：0.2.29
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm-6b'] @ cpu
{'api_base_url': 'http://192.168.2.134:8888/v1',
'api_key': 'EMPTY',
'local_model_path': 'THUDM/chatglm-6b'}
当前Embbedings模型： text2vec @ cpu
服务端运行信息：
OpenAI API Server: http://192.168.2.134:8888/v1
(请确认llm_model_dict中配置的api_base_url与上面地址一致。)
Chatchat API Server: http://192.168.2.134:7861
Chatchat WEBUI Server: http://192.168.2.134:8501
==============================Langchain-Chatchat Configuration==============================
You can now view your Streamlit app in your browser.
URL: http://192.168.2.134:8501

**Comment by liunux4odoo** [comment]
首先建议更新到0.2.5。
无论用哪个版本，按照requirements里要求的最低版本（如langchain>=0.0.287，那就安装287版本）的，特别是langchain/fastchat/transformers几个包。
还有，建议使用chatglm2模型，一代模型官方好久没更新了。

**Comment by Kason-wu** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/72852074-dd0f-418e-93a7-e7fbac0c846b)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/4e9422b5-71ca-489c-b7dd-b9e2fdc49dc1)

**Comment by liunux4odoo** [comment]
如果切换了embedding_model，需要先把旧的向量库删除

**Comment by Kason-wu** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/ad43b5b1-e597-4d00-89b6-a3cde93b94e7)

**Comment by liunux4odoo** [comment]
> 如果切换了embedding_model，需要先把旧的向量库删除

该问题已经在开发版中修复 (#1766)，请关注项目版本升级信息，也可以拉取pre-release或者dev分支代码提前体验测试，测试中遇到问题欢迎反馈。
对于当前版本，可以先删除FAISS向量库文件，再重建知识库。

**Comment by Kason-wu** [comment]
![企业微信截图_16975218001127](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/ee00e7fb-886e-4897-b1bc-0e9ea7ec9337)

**Comment by Kason-wu** [comment]
进度一直卡在86%

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题可能是你的内存不够？你内存多少
