### ISSUE TITLE
[BUG] 知识库问答，多次回答之后（两次），Markdown对象无法序列化

### ISSUE THREAD

**Issue by zhanbei1** [chatchat-space/Langchain-Chatchat#1699]
**问题描述 / Problem Description**
知识库问答，多次回答之后（两次），Markdown对象无法序列化。

报错信息为：
`2023-10-08 18:59:59 | INFO | httpx | HTTP Request: POST http://0.0.0.0:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'role': 'assistant', 'elements': [Markdown Element:
 根据已知信息无法回答该问题。, Markdown Element:
]}
{'role': 'user', 'elements': [Markdown Element:
公司使命]}
received input message:
{'history': [{'content': Markdown Element:
公司使命, 'role': 'user'},
             {'content': Markdown Element:
 根据已知信息无法回答该问题。,
              'role': 'assistant'}],
 'knowledge_base_name': 'desmond',
 'local_doc_url': False,
 'model_name': 'zhipu-api',
 'prompt_name': 'knowledge_base_chat',
 'query': '开发环境有哪些',
 'score_threshold': 1.0,
 'stream': True,
 'temperature': 0.7,
 'top_k': 3}
2023-10-08 18:59:59 | ERROR | root | TypeError: API通信遇到错误：Object of type Markdown is not JSON serializable`
![截屏2023-10-08 19 11 57](https://github.com/chatchat-space/Langchain-Chatchat/assets/23068139/f497ed93-4841-4861-9f5f-779a85a74151)

**复现问题的步骤 / Steps to Reproduce**
同：https://github.com/chatchat-space/Langchain-Chatchat/issues/1696

**环境信息 / Environment Information**
同: https://github.com/chatchat-space/Langchain-Chatchat/issues/1696

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
使用的代码版本和streamlit-chatbox版本报一下
