### ISSUE TITLE
[BUG] v0.2.5初始化知识库报错

### ISSUE THREAD

**Issue by 1748995976** [chatchat-space/Langchain-Chatchat#1703]
背景：在master分支初始化过一次知识库
问题：切到 tagv0.2.5 重新执行指令 `python init_database.py --recreate-vs`报错 如图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32857671/9e7f816b-7eb2-4d55-b253-95baa993f7c5)

**Comment by liunux4odoo** [comment]
把旧的向量库删掉再执行命令试试

**Comment by shaojianbo13** [comment]
> 背景：在master分支初始化过一次知识库 问题：切到 tagv0.2.5 重新执行指令 `python init_database.py --recreate-vs`报错 如图： ![image](https://user-images.githubusercontent.com/32857671/273495592-9e7f816b-7eb2-4d55-b253-95baa993f7c5.png)

麻烦问一下这个问题解决掉了吗

**Comment by 1748995976** [comment]
> 把旧的向量库删掉再执行命令试试

旧的向量库路径在哪？现在切回了V0.2.4是没有这个问题的

**Comment by yexia553** [comment]
一样的问题，我是第一次运行，也报这个错，切到V0.2.4没有这个问题

**Comment by Jacktsay** [comment]
> > 把旧的向量库删掉再执行命令试试
> 
> 旧的向量库路径在哪？现在切回了V0.2.4是没有这个问题的

旧的向量库路径: 先删除 knowledge_base 文件夹里的文件
再执行命令:  python init_database.py --recreate-vs
