### ISSUE TITLE
[BUG]简单的文本回答的很好，上传的一个医疗相关论文很多问题，直接不回答

### ISSUE THREAD

**Issue by houliangxue** [chatchat-space/Langchain-Chatchat#1704]
**问题描述 / Problem Description**
加载了文心一言、glm、星火几个api，简单的文本回答的很好，上传的一个医疗相关论文很多问题，都匹配到了相关内容，但没有给出答案，请问不回答是什么原因，有什么优化方法吗
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58758212/f6622e5a-edb2-4b6a-a8a7-58bfeeb2697c)

**Comment by zhanbei1** [comment]
你这个是部署的最新版本的吗？没有出现这个问题吗？https://github.com/chatchat-space/Langchain-Chatchat/issues/1696

**Comment by liunux4odoo** [comment]
你把history调到1再试试，看你知识库条目比较长，说不定是token超了。

**Comment by houliangxue** [comment]
> 你把history调到1再试试，看你知识库条目比较长，说不定是token超了。
没起作用，试过了
报错，感觉是
接不上在在线api
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58758212/9005ba7c-239b-49d7-a269-a79dbdff66d7)

**Comment by AnYingLieShouTuT** [comment]
1
