### ISSUE TITLE
[BUG] 选择"fangzhou-api"在线大模型报No module named 'volcengine'

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1708]
**问题描述 / Problem Description**
1、选择"fangzhou-api"在线大模型报No module named 'volcengine'
2、windows下pip install volcengine失败

**复现问题的步骤 / Steps to Reproduce**
1. model_config.py配置fangzhou-api
2. 一键启动程序
3. 后台报错：
  File "C:\chatchat\zhuoyu\server\model_workers\fangzhou.py", line 92, in generate_stream_gate
    for resp in request_volc_api(messages=messages,
  File "C:\chatchat\zhuoyu\server\model_workers\fangzhou.py", line 19, in request_volc_api
    from volcengine.maas import MaasService, MaasException, ChatRole
ModuleNotFoundError: No module named 'volcengine'
4.  pip install volcengine，在windows系统失败

**预期的结果 / Expected Result**
调用火山方舟在线模型平台

**实际结果 / Actual Result**
缺火山引擎模块，无法启动

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：fangzhou-api
- 操作系统及版本 / Operating system and version: Windows11
- Python 版本 / Python version: 3.10.9

**Comment by liunux4odoo** [comment]
方舟在线API需要安装volcengine，如果没有安装当然无法使用该功能。

这个包依赖有点多，需要你自己解决安装问题。
