### ISSUE TITLE
/chat/knowledge_base_chat接口改造后，还是一次性输出> > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse

### ISSUE THREAD

**Issue by supersoulsoul** [chatchat-space/Langchain-Chatchat#1712]
> > 可以使用SSE协议 1、 pip install sse_starlette.sse 2、引入依赖: from sse_starlette.sse import EventSourceResponse 3、将StreamingResponse改为EventSourceResponse
> > 前端使用EventSource进行请求，因原生EventSource支持get请求，可以使用Fetch请求或者微软的 @microsoft/fetch-event-source进行请求
> 
> 你这写的是python代码，实际上前端使用sse还是一次性全部返回了

前端使用库@microsoft/fetch-event-source，使用方式如下:

import { fetchEventSource } from '@microsoft/fetch-event-source'
  fetchEventSource('请求接口', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `token内容`,
    },
    body: JSON.stringify(requestData),
    async onopen(response) {
       
    },
    async onmessage(event) {
     //消息在此处处理
    },
    async onerror(error) {
    
    },
    async onclose() {
   
    }
  })
}

_Originally posted by @zyjnicemoe in https://github.com/chatchat-space/Langchain-Chatchat/issues/1351#issuecomment-1717661878_
            
后端已改造，前端也用了fetchEventSource 接收数据，但是还是在onmessage中一次性返回了，像是在最后一瞬间触发了上百次onmessage，返回了所有的event
![image](https://user-images.githubusercontent.com/38419476/273531898-7cc04a9d-7cb4-4d06-b79e-908577dad1b0.png)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38419476/8dc4c148-ef5e-40be-a2c7-8fddf2fff1ff)

**Comment by zyjnicemoe** [comment]
knowledge_base_chat接口中关于出处部分，是通过进行向量检索 时获取到的已知信息，非LLM模型输出，建议出处放在一个事件流中，若还是想实现打字效果，建议对出处部分内容进行推送事件流时进行  休眠（100ms）

**Comment by AaronMKk** [comment]
import { fetchEventSource } from '@microsoft/fetch-event-source'
fetchEventSource('请求接口', {
method: 'POST',
headers: {
'Content-Type': 'application/json',
'Authorization': token内容,
},
body: JSON.stringify(requestData),
async onopen(response) {

你这里的method还是post

**Comment by supersoulsoul** [comment]
> fetchEventSource

接口就是POST类型的啊？

**Comment by zyjnicemoe** [comment]
关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题

**Comment by supersoulsoul** [comment]
> 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题

我这里不只是出处一次性返回，回答内容也是一下子返回的......
在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。

我看后端写的好像也没有问题....不知道什么原因
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/38419476/83044fd3-bb6b-41f1-b8c0-59529ecff296)

**Comment by zyjnicemoe** [comment]
> > 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题
> 
> 我这里不只是出处一次性返回，回答内容也是一下子返回的...... 在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。
> 
> 我看后端写的好像也没有问题....不知道什么原因 ![image](https://user-images.githubusercontent.com/38419476/273748739-83044fd3-bb6b-41f1-b8c0-59529ecff296.png)

根据之前你截图来看，event事件确实有多个，是不是内容回复的内容太多看不出效果，使用普通的对话接口试试效果

**Comment by zyjnicemoe** [comment]
> > > 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题
> > 
> > 
> > 我这里不只是出处一次性返回，回答内容也是一下子返回的...... 在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。
> > 我看后端写的好像也没有问题....不知道什么原因 ![image](https://user-images.githubusercontent.com/38419476/273748739-83044fd3-bb6b-41f1-b8c0-59529ecff296.png)
> 
> 根据之前你截图来看，event事件确实有多个，是不是内容回复的内容太短看不出效果，因该是出处内容太多让你看起来时一次性返回的，使用普通的对话接口试试效果

可以试着先屏蔽出处这个返回，取看一下对话效果
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60834716/67671ee0-fd9e-4126-9eb2-740d385c7029)

**Comment by supersoulsoul** [comment]
> > > > 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题
> > > 
> > > 
> > > 我这里不只是出处一次性返回，回答内容也是一下子返回的...... 在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。
> > > 我看后端写的好像也没有问题....不知道什么原因 ![image](https://user-images.githubusercontent.com/38419476/273748739-83044fd3-bb6b-41f1-b8c0-59529ecff296.png)
> > 
> > 
> > 根据之前你截图来看，event事件确实有多个，是不是内容回复的内容太短看不出效果，因该是出处内容太多让你看起来时一次性返回的，使用普通的对话接口试试效果
> 
> 可以试着先屏蔽出处这个返回，取看一下对话效果 ![image](https://user-images.githubusercontent.com/60834716/273750565-67671ee0-fd9e-4126-9eb2-740d385c7029.png)

我试过很多了，长段落也是一下子在onmessage响应出来的，docs的dumps屏蔽我也试过了....
也试过把上面的search_docs直接屏蔽了
都不行，还是一下子触发了

**Comment by zyjnicemoe** [comment]
> > > > > 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题
> > > > 
> > > > 
> > > > 我这里不只是出处一次性返回，回答内容也是一下子返回的...... 在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。
> > > > 我看后端写的好像也没有问题....不知道什么原因 ![image](https://user-images.githubusercontent.com/38419476/273748739-83044fd3-bb6b-41f1-b8c0-59529ecff296.png)
> > > 
> > > 
> > > 根据之前你截图来看，event事件确实有多个，是不是内容回复的内容太短看不出效果，因该是出处内容太多让你看起来时一次性返回的，使用普通的对话接口试试效果
> > 
> > 
> > 可以试着先屏蔽出处这个返回，取看一下对话效果 ![image](https://user-images.githubusercontent.com/60834716/273750565-67671ee0-fd9e-4126-9eb2-740d385c7029.png)
> 
> 我试过很多了，长段落也是一下子在onmessage响应出来的，docs的dumps屏蔽我也试过了.... 也试过把上面的search_docs直接屏蔽了 都不行，还是一下子触发了

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60834716/aa828d1b-d016-43ff-8076-d785e22c1ec2)
你上面的那个截图上来看没啥问题呀，不是一次性返回是推送了多次事件流的，您这边使用一下普通的对话接口，/chat接口试一下效果，如果觉得还是一次性返回，有个办法可以验证，在
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60834716/8e054a3f-b641-4119-874e-a4621cab19db)
中间加入休眠100ms去验证一下

**Comment by supersoulsoul** [comment]
> > > > > > 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题
> > > > > 
> > > > > 
> > > > > 我这里不只是出处一次性返回，回答内容也是一下子返回的...... 在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。
> > > > > 我看后端写的好像也没有问题....不知道什么原因 ![image](https://user-images.githubusercontent.com/38419476/273748739-83044fd3-bb6b-41f1-b8c0-59529ecff296.png)
> > > > 
> > > > 
> > > > 根据之前你截图来看，event事件确实有多个，是不是内容回复的内容太短看不出效果，因该是出处内容太多让你看起来时一次性返回的，使用普通的对话接口试试效果
> > > 
> > > 
> > > 可以试着先屏蔽出处这个返回，取看一下对话效果 ![image](https://user-images.githubusercontent.com/60834716/273750565-67671ee0-fd9e-4126-9eb2-740d385c7029.png)
> > 
> > 
> > 我试过很多了，长段落也是一下子在onmessage响应出来的，docs的dumps屏蔽我也试过了.... 也试过把上面的search_docs直接屏蔽了 都不行，还是一下子触发了
> 
> ![image](https://user-images.githubusercontent.com/60834716/273751530-aa828d1b-d016-43ff-8076-d785e22c1ec2.png) 你上面的那个截图上来看没啥问题呀，不是一次性返回是推送了多次事件流的，您这边使用一下普通的对话接口，/chat接口试一下效果，如果觉得还是一次性返回，有个办法可以验证，在 ![image](https://user-images.githubusercontent.com/60834716/273751949-8e054a3f-b641-4119-874e-a4621cab19db.png) 中间加入休眠100ms去验证一下

我说的可能不太准确，确实不是一次性返回的，但是是一次性推送的。前端onopen后，一直在等响应，段落长的时候，要等的时间比较久，然后一下子收到了onmessage的所有事件。我试了加休眠，也没用。

**Comment by zyjnicemoe** [comment]
> > > > > > > 关于 出处内容部分一次性输出，问题来自于后端推送的事件流，最后一个事件流推送的出处内容是一次性返回的，修改一下就行了，不是库的问题
> > > > > > 
> > > > > > 
> > > > > > 我这里不只是出处一次性返回，回答内容也是一下子返回的...... 在fetchEventSource中，onopen后，一直在等响应，然后一下子进入了onmessage，在onmessage中打印的event，就是一秒钟同时打印出来的，所以并没有打字机效果，页面看起来还是等回答完了才全部显示。
> > > > > > 我看后端写的好像也没有问题....不知道什么原因 ![image](https://user-images.githubusercontent.com/38419476/273748739-83044fd3-bb6b-41f1-b8c0-59529ecff296.png)
> > > > > 
> > > > > 
> > > > > 根据之前你截图来看，event事件确实有多个，是不是内容回复的内容太短看不出效果，因该是出处内容太多让你看起来时一次性返回的，使用普通的对话接口试试效果
> > > > 
> > > > 
> > > > 可以试着先屏蔽出处这个返回，取看一下对话效果 ![image](https://user-images.githubusercontent.com/60834716/273750565-67671ee0-fd9e-4126-9eb2-740d385c7029.png)
> > > 
> > > 
> > > 我试过很多了，长段落也是一下子在onmessage响应出来的，docs的dumps屏蔽我也试过了.... 也试过把上面的search_docs直接屏蔽了 都不行，还是一下子触发了
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/60834716/273751530-aa828d1b-d016-43ff-8076-d785e22c1ec2.png) 你上面的那个截图上来看没啥问题呀，不是一次性返回是推送了多次事件流的，您这边使用一下普通的对话接口，/chat接口试一下效果，如果觉得还是一次性返回，有个办法可以验证，在 ![image](https://user-images.githubusercontent.com/60834716/273751949-8e054a3f-b641-4119-874e-a4621cab19db.png) 中间加入休眠100ms去验证一下
> 
> 我说的可能不太准确，确实不是一次性返回的，但是是一次性推送的。前端onopen后，一直在等响应，段落长的时候，要等的时间比较久，然后一下子收到了onmessage的所有事件。我试了加休眠，也没用。

将后端返回改成这种格式的试一下
            async for token in callback.aiter():
                      # Use server-sent-events to stream the response
                      answer = {
                          "response": answer,
                      }
                      yield {"data": json.dumps(answer, ensure_ascii=False)}

**Comment by supersoulsoul** [comment]
不行.......还是在for循环结束后推送了全部数据

**Comment by supersoulsoul** [comment]
找到问题了，是因为前端本地访问服务器走了nginx代理，应该是不支持sse，所以一直一次性返回。

...............

**Comment by zyhui98** [comment]
> 找到问题了，是因为前端本地访问服务器走了nginx代理，应该是不支持sse，所以一直一次性返回。
> 
> ...............

你用的什么版本，我看就是一次性返回的，都不是sse协议

**Comment by Maxliag** [comment]
> 找到问题了，是因为前端本地访问服务器走了nginx代理，应该是不支持sse，所以一直一次性返回。
> 
> ...............

你好我也有跟你相同的疑问，我在使用api调用测试回答时，出现了同样的问题，请问你是怎么解决的

**Comment by supersoulsoul** [comment]
后端确实不是sse，用EventSource不行，但是前端用fetch请求也可以，大概这样子：
fetch().then(response => {
    const reader = response.body.getReader();
    // 循环读取
    function read() {
        reader.read().then(({ done, value }) => {
            if (done) return;
            console.log(new TextDecoder().decode(value));
            read();
        })
    }
    read();
})

**Comment by Baikeqii** [comment]
@supersoulsoul 遇到了同样问题，后端接口用postman请求是流式输出，但前端用fetchEventSource请求onmessage就一直等到接口结束一次性返回了所有事件，除了nginx，有其他可能出错的地方吗
<img width="639" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/24309076/0789aeff-eb3d-428a-951e-ba657b7a8523">

**Comment by supersoulsoul** [comment]
> @supersoulsoul 遇到了同样问题，后端接口用postman请求是流式输出，但前端用fetchEventSource请求onmessage就一直等到接口结束一次性返回了所有事件，除了nginx，有其他可能出错的地方吗 <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/24309076/291761754-0789aeff-eb3d-428a-951e-ba657b7a8523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjM3MjgsIm5iZiI6MTcwMzA2MzQyOCwicGF0aCI6Ii8yNDMwOTA3Ni8yOTE3NjE3NTQtMDc4OWFlZmYtZWIzZC00MjhhLTk1MWUtYmE2NTdiN2E4NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZGJiYTYyYzkzMDY5MTRhOGQyMWI4ZjA4NTUwMmNlYzFkMzRlOGRhMWUxMDAyMGFjZmJkZWIzYTViNmYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTXFrRl3UljaYCU1iRBosQvw0sDwLjV9pyi3NmEO1N4">

前端本地做了代理，应该也要处理下nginx吧。具体怎么处理我也不知道，我把前端包部署到后台同服务器，线上是可以流式的，前端本地不行。

**Comment by supersoulsoul** [comment]
> @supersoulsoul 遇到了同样问题，后端接口用postman请求是流式输出，但前端用fetchEventSource请求onmessage就一直等到接口结束一次性返回了所有事件，除了nginx，有其他可能出错的地方吗 <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/24309076/291761754-0789aeff-eb3d-428a-951e-ba657b7a8523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjM3MjgsIm5iZiI6MTcwMzA2MzQyOCwicGF0aCI6Ii8yNDMwOTA3Ni8yOTE3NjE3NTQtMDc4OWFlZmYtZWIzZC00MjhhLTk1MWUtYmE2NTdiN2E4NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZGJiYTYyYzkzMDY5MTRhOGQyMWI4ZjA4NTUwMmNlYzFkMzRlOGRhMWUxMDAyMGFjZmJkZWIzYTViNmYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTXFrRl3UljaYCU1iRBosQvw0sDwLjV9pyi3NmEO1N4">
fetchEventSource库在这里不能用，因为后台不是EventSource的。前端写个fetch原生请求，read就可以。类似这样：
fetch().then(response => {
const reader = response.body.getReader();
// 循环读取
function read() {
reader.read().then(({ done, value }) => {
if (done) return;
console.log(new TextDecoder().decode(value));
read();
})
}
read();
})

**Comment by supersoulsoul** [comment]
> @supersoulsoul 遇到了同样问题，后端接口用postman请求是流式输出，但前端用fetchEventSource请求onmessage就一直等到接口结束一次性返回了所有事件，除了nginx，有其他可能出错的地方吗 <img alt="image" width="639" src="https://private-user-images.githubusercontent.com/24309076/291761754-0789aeff-eb3d-428a-951e-ba657b7a8523.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjM3MjgsIm5iZiI6MTcwMzA2MzQyOCwicGF0aCI6Ii8yNDMwOTA3Ni8yOTE3NjE3NTQtMDc4OWFlZmYtZWIzZC00MjhhLTk1MWUtYmE2NTdiN2E4NTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA5MTAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZGJiYTYyYzkzMDY5MTRhOGQyMWI4ZjA4NTUwMmNlYzFkMzRlOGRhMWUxMDAyMGFjZmJkZWIzYTViNmYxZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTXFrRl3UljaYCU1iRBosQvw0sDwLjV9pyi3NmEO1N4">

也有可能是前端本地做了代理，也需要设置nginx。你可以试试在线上是否能流式。

**Comment by fanxyu** [comment]
请问关于走了nginx代理或者本地代理之后就不能流式输出的问题解决了吗？我遇到了同样的问题。

**Comment by fanxyu** [comment]
我通过网上查询相关问题，已经解决了参考：https://blog.csdn.net/liweiweili126/article/details/139977370
