### ISSUE TITLE
[BUG] 在configs/model_config.py中修改PROMPT_TEMPLATE，回答并没有明显改变

### ISSUE THREAD

**Issue by Zou-njust** [chatchat-space/Langchain-Chatchat#1714]
如图所示，模型仍然正常回答，没有按指令来。
![17619c971e1375bf04036ccc12fe409f](https://github.com/chatchat-space/Langchain-Chatchat/assets/102728474/54156fb1-b5f4-4654-b980-5682ba9bbdc3)

原始版本中PROMPT_TEMPLATE有 ”如果无法从中得到答案，请说 “根据已知信息无法回答该问题”。“ ，修改引号中的”根据已知。。。“ 
能得到对应的改变。

怎么能让prompt有效根据业务需求修改？

**Comment by zRzRzRzRzRzRzR** [comment]
没有听懂
这个提示词是搜寻知识库的内容，并根据搜索到的内容来进行回答。由于不清楚你的业务需求，不清楚你需要使用知识库查询到的内容做什么

如果你只是想把搜到内容直接输出，你可以直接获取api的doc字段就行了

**Comment by Zou-njust** [comment]
不好意思我没有说清楚，业务需求需要对搜索到的内容按一定格式生成回答，例如在回答的开头加一段话“根据搜索到的内容”，但修改prompt没有产生影响。 

从 Windows 版邮件发送

发件人: zR
发送时间: 2023年10月9日 21:35
收件人: chatchat-space/Langchain-Chatchat
抄送: ZouYunqi; Author
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 在configs/model_config.py中修改PROMPT_TEMPLATE，回答并没有明显改变 (Issue #1714)

没有听懂
这个提示词是搜寻知识库的内容，并根据搜索到的内容来进行回答。由于不清楚你的业务需求，不清楚你需要使用知识库查询到的内容做什么
如果你只是想把搜到内容直接输出，你可以直接获取api的doc字段就行了

**Comment by Zou-njust** [comment]
继续测试后有些prompt的修改是有效的，有些玄学，我再试试，不好意思打扰了。

从 Windows 版邮件发送

发件人: zR
发送时间: 2023年10月9日 21:35
收件人: chatchat-space/Langchain-Chatchat
抄送: ZouYunqi; Author
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 在configs/model_config.py中修改PROMPT_TEMPLATE，回答并没有明显改变 (Issue #1714)

没有听懂
这个提示词是搜寻知识库的内容，并根据搜索到的内容来进行回答。由于不清楚你的业务需求，不清楚你需要使用知识库查询到的内容做什么
如果你只是想把搜到内容直接输出，你可以直接获取api的doc字段就行了

**Comment by zhuhaifengaaa** [comment]
是的，我也遇到了这个问题，比如修改prompt“让结果以英文的形式输出”没有作用，但是在对话框中让模型用英语输出它就会用英文输出。这个prompt感觉确实有点玄学，不太灵

**Comment by Quant2017** [comment]
模型能力不足会出现这种情况

**Comment by zhuhaifengaaa** [comment]
> 模型能力不足会出现这种情况

请问，换成什么模型效果会好点呢？我现在用的还是默认模型
