### ISSUE TITLE
PDF文档向量化失败

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#1715]
**问题描述 / Problem Description**
PDF文档向量化失败，提示：
INFO: RapidOCRPDFLoader used for ../knowledge_base/samples/content/123.pdf
 utils.py[line:360] - ERROR: ImportError: 从文件 samples/123.pdf 加载文档时出错：libXext.so.6: cannot open shared object file: No such file or directory

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.4
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu
- Python 版本 / Python version: python3.10

**Comment by leoterry-ulrica** [comment]
现在有新的错误：list index out of range

**Comment by liunux4odoo** [comment]
> 现在有新的错误：utils.py[line:360] - ERROR: IndexError: 从文件 samples/123.pdf 加载文档时出错：list index out of range

更新master代码，更新依赖（特别是rapidocr）试试

**Comment by leoterry-ulrica** [comment]
> > 现在有新的错误：utils.py[line:360] - ERROR: IndexError: 从文件 samples/123.pdf 加载文档时出错：list index out of range
> 
> 更新master代码，更新依赖（特别是rapidocr）试试



> > 现在有新的错误：utils.py[line:360] - ERROR: IndexError: 从文件 samples/123.pdf 加载文档时出错：list index out of range
> 
> 更新master代码，更新依赖（特别是rapidocr）试试

是今天下载的master代码，RapidOCR版本直接通过pip install -r requirements.txt 进行安装的。请问需要指定版本吗？

**Comment by zhanbei1** [comment]
看看是不是服务器上缺少某些依赖的工具。
比如：libXext.so.6: cannot open shared object file: No such file or directory 这个报错，可能就是缺少一些底层的包
可以参考这个回答：https://blog.csdn.net/qq_50195602/article/details/124188467

执行：`yum install mesa-libGL -y` 一下就可以了

**Comment by leoterry-ulrica** [comment]
> list index out of range

对于扫描的PDF，你有遇到这个问题没？list index out of range

**Comment by zhanbei1** [comment]
> > list index out of range
> 
> 对于扫描的PDF，你有遇到这个问题没？list index out of range

并没有，你可以把你的报错信息全部弄上来吗？可以看看他的chatchat源码，是不是有什么限制？

**Comment by leoterry-ulrica** [comment]
> > > list index out of range
> > 
> > 
> > 对于扫描的PDF，你有遇到这个问题没？list index out of range
> 
> 并没有，你可以把你的报错信息全部弄上来吗？可以看看他的chatchat源码，是不是有什么限制？

看到一个回复：https://github.com/chatchat-space/Langchain-Chatchat/issues/1224

**Comment by pzchu** [comment]
同遇到问题，从文件 samples/统编版语文二年级上册.pdf 加载文档时出错：Directory 'static/' does not exist  不知道为何会出来一个static文件夹，明明没有。
txt正常，windows平台

**Comment by pzchu** [comment]
> 同遇到问题，从文件 samples/统编版语文二年级上册.pdf 加载文档时出错：Directory 'static/' does not exist 不知道为何会出来一个static文件夹，明明没有。 txt正常，windows平台

已解决，static问题是由于fitz包导致的，pymupdf本身就已集成了fitz，因此如果安装了fitz就会导致fitz.open报错，卸载fitz和pymupdf，然后再重新安装pymupdf即可。
