### ISSUE TITLE
[BUG] 使用qwen-7b-chat-int4时出现错误：KeyError: 'transformer.h.26.mlp.gate_up_proj.bias'

### ISSUE THREAD

**Issue by Roych13** [chatchat-space/Langchain-Chatchat#1717]
**问题描述 / Problem Description**
运行python startup.py -a出现以下错误：

Traceback (most recent call last):
  File "startup.py", line 721, in start_main_server
    e.wait()
  File "/root/miniconda3/lib/python3.8/multiprocessing/managers.py", line 1110, in wait
    return self._callmethod('wait', (timeout,))
  File "/root/miniconda3/lib/python3.8/multiprocessing/managers.py", line 835, in _callmethod
    kind, result = conn.recv()
  File "/root/miniconda3/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/root/miniconda3/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/root/miniconda3/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
  File "startup.py", line 573, in f
    raise KeyboardInterrupt(f"{signalname} received")
KeyboardInterrupt: SIGINT received

**环境信息 / Environment Information**

python版本：python 3.10.8
操作系统：Ubuntu（autodl）
显卡： RTX 4090(24GB) * 1
CPU：12 vCPU Intel(R) Xeon(R) Platinum 8352V CPU @ 2.10GHz
内存：90GB

-----------------------
model_config关键配置（其它默认）：
"Qwen-7B":"/root/autodl-fs/Qwen-7B-Chat-Int4",
LLM_MODEL = "Qwen-7B"
----------------------
昨天用chatGLM-6B模型测试没问题，检查依赖包也没有错误。换成通义千问模型后失败。

依赖包如下（供参考）：
accelerate==0.23.0
aiohttp==3.8.6
aiosignal==1.3.1
altair==5.1.2
antlr4-python3-runtime==4.9.3
anyio==3.7.1
async-timeout==4.0.3
attrs==23.1.0
backports.zoneinfo==0.2.1
beautifulsoup4==4.12.2
blinker==1.6.3
blis==0.7.11
cachetools==5.3.1
catalogue==2.0.10
certifi==2023.7.22
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.0
click==8.1.7
cloudpathlib==0.15.1
cmake==3.27.6
coloredlogs==15.0.1
confection==0.1.3
contourpy==1.1.1
cryptography==41.0.4
cycler==0.12.1
cymem==2.0.8
dataclasses-json==0.6.1
EbookLib==0.18
effdet==0.4.1
einops==0.7.0
emoji==2.8.0
et-xmlfile==1.1.0
exceptiongroup==1.1.3
faiss-cpu==1.7.4
fastapi==0.103.2
filelock==3.12.4
filetype==1.2.0
flatbuffers==23.5.26
fonttools==4.43.1
frozenlist==1.4.0
fschat==0.2.29
fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.37
greenlet==3.0.0
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.0
iniconfig==2.0.0
iopath==0.1.10
Jinja2==3.1.2
joblib==1.3.2
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
langchain==0.0.310
langcodes==3.3.0
langdetect==1.0.9
langsmith==0.0.43
layoutparser==0.3.4
lit==17.0.2
lxml==4.9.3
Markdown==3.5
markdown-it-py==3.0.0
markdown2==2.4.10
MarkupSafe==2.1.3
marshmallow==3.20.1
matplotlib==3.7.3
mdurl==0.1.2
mpmath==1.3.0
msg-parser==1.2.0
msgpack==1.0.7
multidict==6.0.4
murmurhash==1.0.10
mypy-extensions==1.0.0
networkx==3.1
nh3==0.2.14
ninja==1.11.1
nltk==3.8.1
numexpr==2.8.6
numpy==1.24.4
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
olefile==0.46
omegaconf==2.3.0
onnx==1.14.1
onnxruntime==1.16.0
openai==0.28.1
opencv-python==4.8.1.78
openpyxl==3.1.2
packaging==23.2
pandas==2.0.3
pathlib==1.0.1
pathy==0.10.2
pdf2image==1.16.3
pdfminer.six==20221105
pdfplumber==0.10.2
peft==0.5.0
Pillow==10.0.1
pkgutil_resolve_name==1.3.10
pluggy==1.3.0
portalocker==2.8.2
preshed==3.0.9
prompt-toolkit==3.0.39
protobuf==4.24.4
psutil==5.9.5
pyarrow==13.0.0
pyclipper==1.3.0.post5
pycocotools==2.0.7
pycparser==2.21
pydantic==1.10.13
pydeck==0.8.1b0
Pygments==2.16.1
PyMuPDF==1.22.5
pypandoc==1.11
pyparsing==3.1.1
pypdfium2==4.20.0
pytesseract==0.3.10
pytest==7.4.2
python-dateutil==2.8.2
python-decouple==3.8
python-docx==0.8.11
python-iso639==2023.6.15
python-magic==0.4.27
python-multipart==0.0.6
python-pptx==0.6.21
pytz==2023.3.post1
PyYAML==6.0.1
rapidfuzz==3.3.1
rapidocr-onnxruntime==1.3.7
ray==2.7.0
referencing==0.30.2
regex==2023.10.3
requests==2.31.0
rich==13.6.0
rpds-py==0.10.4
safetensors==0.4.0
scikit-learn==1.3.1
scipy==1.10.1
sentence-transformers==2.2.2
sentencepiece==0.1.99
shapely==2.0.1
shortuuid==1.0.11
simplejson==3.19.2
six==1.16.0
smart-open==6.4.0
smmap==5.0.1
sniffio==1.3.0
soupsieve==2.5
spacy==3.7.1
spacy-legacy==3.0.12
spacy-loggers==1.0.5
SQLAlchemy==2.0.19
srsly==2.4.8
starlette==0.27.0
streamlit==1.27.2
streamlit-aggrid==0.3.4.post3
streamlit-antd-components==0.2.1
streamlit-chatbox==1.1.9
streamlit-option-menu==0.3.6
svgwrite==1.4.3
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
thinc==8.2.1
threadpoolctl==3.2.0
tiktoken==0.5.1
timm==0.9.7
tokenizers==0.13.3
toml==0.10.2
tomli==2.0.1
toolz==0.12.0
torch==2.0.1
torchaudio==2.0.2
torchvision==0.15.2
tornado==6.3.3
tqdm==4.66.1
transformers==4.33.3
transformers-stream-generator==0.0.4
triton==2.0.0
typer==0.9.0
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
tzlocal==5.1
unstructured==0.10.19
unstructured-inference==0.6.6
unstructured.pytesseract==0.3.12
urllib3==2.0.6
uvicorn==0.23.2
validators==0.22.0
vllm==0.1.7
wasabi==1.1.2
watchdog==3.0.0
wavedrom==2.0.3.post3
wcwidth==0.2.8
weasel==0.3.2
websockets==11.0.3
xformers==0.0.22
xlrd==2.0.1
XlsxWriter==3.1.6
yarl==1.9.2
zipp==3.17.0

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by yansheng105** [comment]
你可以尝试禁用vllm，可能有效，我使用的是Qwen-14B-Chat-Int4，也报了类似的错误，禁用vllm就可以启动了（修改server_config.py 中的 infer_turbo 键的值为False），禁用vllm后可能还需要修改 config.json 中 quantization_config 键的值，在quantization_config值中加一行 "disable_exllama": true

**Comment by yansheng105** [comment]
你可以尝试禁用vllm，可能有效，我使用的是Qwen-14B-Chat-Int4，也报了类似的错误，禁用vllm就可以启动了（修改server_config.py 中的 infer_turbo 键的值为False），禁用vllm后可能还需要修改 config.json 中 quantization_config 键的值，在quantization_config值中加一行 "disable_exllama": true

**Comment by ryancurry-mz** [comment]
> 你可以尝试禁用vllm，可能有效，我使用的是Qwen-14B-Chat-Int4，也报了类似的错误，禁用vllm就可以启动了（修改server_config.py 中的 infer_turbo 键的值为False），禁用vllm后可能还需要修改 config.json 中 quantization_config 键的值，在quantization_config值中加一行 "disable_exllama": true

@yansheng105 改了之后好使了，请问大佬方便说下禁用vllm的影响不，是否只影响推理速度？

**Comment by yansheng105** [comment]
> > 你可以尝试禁用vllm，可能有效，我使用的是Qwen-14B-Chat-Int4，也报了类似的错误，禁用vllm就可以启动了（修改server_config.py 中的 infer_turbo 键的值为False），禁用vllm后可能还需要修改 config.json 中 quantization_config 键的值，在quantization_config值中加一行 "disable_exllama": true
> 
> @yansheng105 改了之后好使了，请问大佬方便说下禁用vllm的影响不，是否只影响推理速度？

据我所知没其他影响了
