### ISSUE TITLE
[FEATURE] 以问答的形式写入知识库时，能精准的划分段落，以便于截取答案中的关键字

### ISSUE THREAD

**Issue by zzxs** [chatchat-space/Langchain-Chatchat#1718]
想做一个面向学生的问答学习系统，需要统计学生对于哪些知识点问的次数较多。
知识库文件如下，其中###中间包裹的是自己设计的关键字：
```python
问：SQLSERVER查询语句怎么写
答：###SQL查询语句###插入：INSERT INTO 表名 (列名 1, 列名 2, 列名 3) VALUES (值 1, 值 2, 值 3);

问：SQLSERVER更新语句怎么写
答：###SQL更新语句###更新：UPDATE 表名 SET 列名 1 = 值 1, 列名 2 = 值 2, 列名 3 = 值 3 WHERE 条件；
``` 

如果在询问“更新语句”时，回答的倒是没问题，就是显示出处的时候会把不属于该问答的部分也带上，使得在处理关键字时被带偏。
如下：
```python
{
    "docs": [
        "出处 [1] [test1.txt](http://43.137.47.53:7861/knowledge_base/download_doc?knowledge_base_name=sql&file_name=test1.txt) \n\n问：SQLSERVER查询语句怎么写 答：###SQL查询语句###插入：INSERT INTO 表名 (列名 1, 列名 2, 列名 3) VALUES (值 1, 值 2, 值 3);\n问：SQLSERVER更新语句怎么写 答：###SQL更新语句###更新：UPDATE 表名 SET 列名 1 = 值 1, 列名 2 = 值 2, 列名 3 = 值 3 WHERE 条件；\n\n"
    ]
}
``` 

我希望的是出处中仅返回第二个问答，而不显示第一个问答，这样我能精准的拿到该次问答的关键字。

或者有别的方案也行，求指导。

**Comment by zzxs** [comment]
目前为止的方案是每一个问答拆分成一个文档。

还有更好的方案吗？

**Comment by zRzRzRzRzRzRzR** [comment]
目前有两个方案，一个是自定义分词器，主要有开发者（例如您）完成自己的设计，针对自己的文档进行分词
第二个方案是我们在下一个版本可能会推出关键词嵌入Embed模型的方案，你对一些embed方式可以做一定的定制
我们建议方案一，因为他可操作性强，并且不用等比较长的时间

**Comment by digitalghost** [comment]
其实似乎是不是用MarkdownHeaderTextSplitter来对自己设计好的.md知识库进行分割，也能很好的解决类似问题？
参考我提的那个bug里面的设计方式，看看行不行：
https://github.com/chatchat-space/Langchain-Chatchat/issues/1825

**Comment by 0000sir** [comment]
> 目前有两个方案，一个是自定义分词器，主要有开发者（例如您）完成自己的设计，针对自己的文档进行分词 第二个方案是我们在下一个版本可能会推出关键词嵌入Embed模型的方案，你对一些embed方式可以做一定的定制 我们建议方案一，因为他可操作性强，并且不用等比较长的时间

能否请您写一个自定义分词器的设计思路，看了chinese_recursive_text_splitter，只知道它将文本拆成了合适的长度的chunk，如何实现题主（也是很多人遇到的）的需求，没看明白要怎么做分词，谢谢！

**Comment by 0000sir** [comment]
尝试参考zh_title_enhance的方式把问题和答案合到一起，效果略好于之前的问答分离，但是离可以应用的状态还很远。从原理上来看，也许按之前哪个答案里提过的只把问题导入到向量库，查询匹配到问题后，从关系数据库获取对应问题的答案更靠谱。

**Comment by 0000sir** [comment]
谢谢，还是有点不太明白，比如一个知识点要如何处理，是每个问答内容作为一个chunk吗？我还没有开始写分词器，尝试了把问题和答案合并到一行，用空行做分隔，然后用默认的chinese_recursive_text_splitter处理后，勉强能用，但是看知识库匹配结果中，同一条结果中都会带上其它条目的内容，导致内容不准确，请问这个是要如何处理

**Comment by zzxs** [comment]
> 设计思路如下
> 
> 1. 你想在哪里进行切分 例如 符号 "}"
> 2. 你的分词中是吧QA放一起还是Q 一个 A一个
>    这是一个可行建议

非常感谢。

还是说一下我的思路，目前的解决方案是每个问答单独成一个文件，当AI在问答时会返回参考的文档，根据相关度排序，那么取相关度最高的这个文档，读取里面的关键字，这里关键字我用###包起来，不论前端后端都很好处理。

最后解决方案也比较简单，知识库与知识内容分开，加个关系表做对应，每一条问答存成一条数据，数据包含问题、答案、关键字等等。当需要时，把对应知识库的知识内容每一条生成一个单独的txt文档，统一上传到知识库中。

**Comment by AI-HR** [comment]
为什么不用csv格式
