### ISSUE TITLE
[BUG] V0.2.4版本访问WebUI页面报错 AttributeError: 'NoneType' object has no attribute 'json'

### ISSUE THREAD

**Issue by 1748995976** [chatchat-space/Langchain-Chatchat#1721]
描述： V0.2.4版本执行`python startup.py -a`指令后访问 127.0.0.1:8501 报错如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32857671/a9959cd0-a775-46cf-a366-382fcec486fe)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32857671/d8769166-10c9-4cad-9d80-105be75ff905)

**Comment by guo-zh** [comment]
我刚在ubuntu部署了，也是这个情况

**Comment by Crystal-girl** [comment]
-a 启动没有该问题

**Comment by 123ytt** [comment]
> 更新分支，升级到0.2.5版本

这个该如何更新？
