### ISSUE TITLE
[BUG] 知识库回答报错TypeError: ChatBox.update_msg() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by guo-zh** [chatchat-space/Langchain-Chatchat#1723]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/67051515/a2553718-f9d5-44e3-8ede-df05556d8c8a)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/67051515/23cc1063-2833-46e3-a0b8-b32970ec0cdf)
如图

**Comment by Zymfl** [comment]
有解决嘛
