### ISSUE TITLE
[BUG] python startup.py -a启动后会跟服务器原有的chatglm2-6b模型的Fastchat冲突

### ISSUE THREAD

**Issue by xzhou89** [chatchat-space/Langchain-Chatchat#1724]
**问题描述 / Problem Description**
服务器上已经部署好了一个chatglm2-6b的模型了，端口是8001 ，地址是  http://127.0.0.1:8001/v1

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python startup.py -a 可以正常启动，但是会把原有的8001的给停了，因为8001是用的Fastchat的方式，启动的话有冲突

**预期的结果 / Expected Result**
想同时启动chatchat保证可用，只用知识库问答，又不想停掉原有的8001，请问下能不能直接用现有的8001的服务，不要再次启动Fastchat呢，配置文件应该如何配置

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  ubuntu 20.04
- Python 版本 / Python version: 3.10.5
- 其他相关环境信息 / Other relevant environment information:

**Comment by xzhou89** [comment]
配置文件如下：
MODEL_PATH = {
    "embed_model": {
        "ernie-tiny": "/usr/local/Langchain-Chatchat/models/ernie-3.0-nano-zh",
        "ernie-base": "/usr/local/Langchain-Chatchat/models/ernie-3.0-base-zh",
        "text2vec": "/usr/local/Langchain-Chatchat/models/text2vec-large-chinese",
    },
    # TODO: add all supported llm models
    "llm_model": {
        # 以下部分模型并未完全测试，仅根据fastchat和vllm模型的模型列表推定支持
        "chatglm2-6b": "/root/.cache/huggingface/hub/models--THUDM--chatglm2-6b/snapshots/0ecfe0b857efd00836a4851b3dd2ed04bd4b197f",
    },
}

# 选用的 Embedding 名称
EMBEDDING_MODEL = "text2vec"  # 可以尝试最新的嵌入式sota模型：piccolo-large-zh

# Embedding 模型运行设备。设为"auto"会自动检测，也可手动设定为"cuda","mps","cpu"其中之一。
EMBEDDING_DEVICE = "text2vec"

# LLM 名称
LLM_MODEL = "chatglm2-6b"

# LLM 运行设备。设为"auto"会自动检测，也可手动设定为"cuda","mps","cpu"其中之一。
LLM_DEVICE = "auto"


ONLINE_LLM_MODEL = {

    "chatglm2-6b": {
            "api_base_url": "http://127.0.0.1:8001/v1",
            "api_key": "EMPTY",
            "openai_proxy": "EMPTY",
    },
}

**Comment by xzhou89** [comment]
model_config 配置部分文件如下：

MODEL_PATH = {
    "embed_model": {
        "ernie-tiny": "/usr/local/Langchain-Chatchat/models/ernie-3.0-nano-zh",
        "ernie-base": "/usr/local/Langchain-Chatchat/models/ernie-3.0-base-zh",
        "text2vec": "/usr/local/Langchain-Chatchat/models/text2vec-large-chinese",
    },
    
    "llm_model": {
       
        "chatglm2-6b": "/root/.cache/huggingface/hub/models--THUDM--chatglm2-6b/snapshots/0ecfe0b857efd00836a4851b3dd2ed04bd4b197f",
    },
}


EMBEDDING_MODEL = "text2vec"  


EMBEDDING_DEVICE = "text2vec"


LLM_MODEL = "chatglm2-6b"


LLM_DEVICE = "auto"


HISTORY_LEN = 3


TEMPERATURE = 0.7



ONLINE_LLM_MODEL = {


    "chatglm2-6b": {
            "api_base_url": "http://127.0.0.1:8001/v1",
            "api_key": "EMPTY",
            "openai_proxy": "EMPTY",
    },
}

**Comment by zRzRzRzRzRzRzR** [comment]
在fschat的启动部分不要从8001启动就行，在server中有fscaht引出的端口
