### ISSUE TITLE
[BUG] Qwen-14B-Chat模型加载flash-attention后报错

### ISSUE THREAD

**Issue by mioMare77** [chatchat-space/Langchain-Chatchat#1726]
**问题描述 / Problem Description**
Qwen-14B-Chat模型+flash-attention库正常启动后接口出现“| ERROR | root | KeyError: Caught exception: 'choices'”错误

**复现问题的步骤 / Steps to Reproduce**
正常启动：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142886590/97bcdd60-c24e-4954-8fde-0d5bc7befa1d)
出现报错，web页面无应答：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142886590/5efa84f6-443c-4366-a0df-85a6e5fccf93)
将flash-attn库卸载后再次加载Qwen-14B-Chat模型后可以正常使用：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142886590/0c348fe4-e42d-42f5-8646-8c069cd63a74)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142886590/6824909d-c685-4e31-a61a-99be94895d38)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本：v0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux-5.15.0-84-generic-x86_64-with-glibc2.35.
- Python 版本 / Python version：3.9.18
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

**Comment by hzg0601** [comment]
加载flash-attention见qwen-7b模型文档

**Comment by mioMare77** [comment]
> 加载flash-attention见qwen-7b模型文档

我是按照qwen-7b模型文档里提供的方式安装了flash-attn后运行，就会出现上图所示的报错；将flash-attn卸载后再次运行无报错

**Comment by mioMare77** [comment]
> > 加载flash-attention见qwen-7b模型文档
> 
> 我是按照qwen-7b模型文档里提供的方式安装了flash-attn后运行，就会出现上图所示的报错；将flash-attn卸载后再次运行无报错

应该是服务器显卡是volta架构不支持flash-attn库导致的
