### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (1285 > 1024). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by sinopec** [chatchat-space/Langchain-Chatchat#1729]
**问题描述 / Problem Description**
知识库添加文档的过程中，出现标题的警告，是否是text splitter 使用的gpt2 tokenizer 的限制，1024的限制有点小，官方是否考虑换个..

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...' 
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： v0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 18.04
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by jason95054** [comment]
I encountered the same issue and could not find a solution.

**Comment by houmo03** [comment]
同样的报错， 加载pdf时没有出现，加载docx和pptx时有很大几率出现

**Comment by jason95054** [comment]
By the way, v0.1.x had no such issue

**Comment by sinopec** [comment]
gpt2的tokenizer 限制长度为1024
看分词策略怎么设计，但是不管怎么设计，总归是有超过这个限制的可能
现在CHUNK_SIZE设置成250，overlap设置成50 也还是偶尔会有超过国1024token的情况出现，有没有其他的tokernizer可以推荐呢

**Comment by sinopec** [comment]
将gpt2换成 tiktoken的cl100k_base，没在出现这个问题—— 至少在CHUNK_SIZE 250，overlap_size50的情况下没再出现
