### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue  无法调用api模型

### ISSUE THREAD

**Issue by iyangiiiii** [chatchat-space/Langchain-Chatchat#1734]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'  执行命令 python startup.py --all-webui --model-name qianfan-api
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs   无法使用线上的模型 试图调用千帆大模型 已经正常获取api 测试api可用 接入langchain时出现 Only  allowed now, your model qianfan-api

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.5
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): qianfan
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Windows 11 Version 22H2
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101607550/fe54ae17-b925-4ecf-926b-3ad2266bf9a0)

**Comment by bleakie** [comment]
同样遇到
