### ISSUE TITLE
体验chatchat遇到的问题汇总

### ISSUE THREAD

**Issue by zhuhaifengaaa** [chatchat-space/Langchain-Chatchat#1738]
1.model_config.py中的PROMPT_TEMPLATE提词没有太大用，有点玄学，让它用英文输出，不听话，费用用中文输出；
2.在互动的web页面对话时，错误率非常高，而且对历史信息的记忆非常差（我已经考虑历史对话轮数HISTORY_LEN的设置问题了），比如，前面两句聊天主角是刘邦，下一句话它不知道上面的代词“他”指谁了？

**Comment by samchaolau** [comment]
这两个问题可以追溯一下发给llm的内容

**Comment by zhuhaifengaaa** [comment]
> 这两个问题可以追溯一下发给llm的内容

没有明白你的意思！
能更详细的解释一下吗

**Comment by zRzRzRzRzRzRzR** [comment]
这个提示词会通过Langchain传入模型，我们开发组已经测试过确定是正确传入了，你也可以自己打印或者打断点验证一下
