### ISSUE TITLE
[FEATURE] 如何获取文档大纲总结

### ISSUE THREAD

**Issue by zyhui98** [chatchat-space/Langchain-Chatchat#1740]
**功能描述 / Feature Description**
如果需要对一篇文档进行总结该如何实现？现有的chatchat支持吗？

多问一句，现在不能针对知识库指定文件进行提问，这个后续有机会支持吗

**Comment by zRzRzRzRzRzRzR** [comment]
目前总结功能还没有支持，我们已经在写，之后会增加总结功能，不过可能不是最近的几个版本

**Comment by Zephyr69** [comment]
请问0.3支持总结了吗？
