### ISSUE TITLE
调用Qwen和baichuan报错，INFO | stdout | INFO:     127.0.0.1:37804 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request

### ISSUE THREAD

**Issue by zhangbaijin** [chatchat-space/Langchain-Chatchat#1746]
**问题描述 / Problem Description**
用ChatGLM就没有这个问题，是因为VLLM的问题吗

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 Ubuntu
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

实际没有返回值
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44993660/3666c549-0378-4add-9b39-3267c7f29337)

**Comment by zRzRzRzRzRzRzR** [comment]
需要后台报错日志
