### ISSUE TITLE
AssertionError: transformer.h.0.mlp.c_proj.weight shape mismatch between model and checkpoint: torch.Size([4096, 11008]) != torch.Size([5120, 11008])

### ISSUE THREAD

**Issue by Modas-Li** [chatchat-space/Langchain-Chatchat#1749]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/40042370/1f81dd9e-6dfe-419c-b723-3e446952ac92)

**Comment by iaoxuesheng** [comment]
加1，我也遇到这个问题了

**Comment by iaoxuesheng** [comment]
不用vllm就可以，用了就报错

**Comment by Modas-Li** [comment]
> 不用vllm就可以，用了就报错

不用怎么设置呢，谢谢

**Comment by yansheng105** [comment]
修改server_config.py的 42 行，将 infer_turbo 的值改为 False , 并执行命令：```pip install optimum auto-gptq```
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/65000135/1aa3389b-1404-4d3c-9c09-b16f42eb7bfb)
