### ISSUE TITLE
[BUG] 无法部署ptuning v2微调后的模型

### ISSUE THREAD

**Issue by XiaoXiaoJiangYun** [chatchat-space/Langchain-Chatchat#1750]
**问题描述 / Problem Description**
无法部署ptuning v2微调后的模型

**复现问题的步骤 / Steps to Reproduce**
1. 通过ChatGLM2的ptuning v2训练后，产生checkpoint，但是不是模型本身
2. 看了wiki，看不懂怎么加载peft，有没有简易教程？

**预期的结果 / Expected Result**
wiki写清楚怎么部署ptuning v2的模型（ChatGLM2主模型+ptuning v2微调后的checkpoint）

**实际结果 / Actual Result**
不会部署

**Comment by yuanzui0728** [comment]
同问

**Comment by zRzRzRzRzRzRzR** [comment]
不是peft模型无法部署，目前版本是这样的

**Comment by shuzhiweb** [comment]
> 不是peft模型无法部署，目前版本是这样的

请问，有其他可行的方案吗
