### ISSUE TITLE
使用 Baichuan2-7b 模型，对话乱码

### ISSUE THREAD

**Issue by chenlingmin** [chatchat-space/Langchain-Chatchat#1752]
使用 Baichuan2-7b 模型，对话乱码

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： f4153beccf82f47b19d5cccfcc8dab724eaaa4ec
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Baichuan2-7B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 操作系统及版本 / Operating system and version: MacOS Ventura 13.4
- Python 版本 / Python version: 3.10.13

<img width="1301" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/8233283/94af28ed-98c7-41cb-9002-7894c1c7794a">

**Comment by zRzRzRzRzRzRzR** [comment]
确定一下fschat版本对不对

**Comment by chenlingmin** [comment]
谢谢回复，fschat 版本为 0.2.29

我用 ChatGLM2-6B 的模型是没问题的
