### ISSUE TITLE
[FEATURE] 知识库增加json数组格式导入

### ISSUE THREAD

**Issue by coding-alt** [chatchat-space/Langchain-Chatchat#1754]
**功能描述 / Feature Description**
希望可以支持导入json数组格式.

**解决的问题 / Problem Solved**
当知识库中是Q/A或者其它成对数据的时候，如果通过默认按字数切分的方式，很有可能切到不成对的数据，导致回答参考的时候，结果不达预期。

**实现建议 / Implementation Suggestions**
支持导入json数据格式，例如：
[
{"Q":"问题1", "A":"回答1"},
{"Q":"问题2", "A":"回答2"},
......
]

**Comment by zRzRzRzRzRzRzR** [comment]
csv的处理方式就是这么做的，这个也可以自定义读入方式
