### ISSUE TITLE
[BUG] 多卡加载模型后，在问答时会报错Caught exception: 'choices'

### ISSUE THREAD

**Issue by jhw0510** [chatchat-space/Langchain-Chatchat#1755]
**问题描述 / Problem Description**
我有4张RTX4090，之前一直都是在单卡上加载的，单卡加载模型都是可以的，然后我改到多卡加载baichuan等模型，设置gpus="0,1"，模型倒是可以加载到GPU上，但就是在LLM问答时，模型的答案可以称为是乱码吧，还报了一个错误：Caught exception: 'choices'，如果直接和模型对话我记得显示的错误信息是RuntimeError: probability tensor contains either inf, nan or element < 0

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.4和0.2.5都尝试过
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Baichuan13B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.8

**Comment by hcxss** [comment]
我也是多卡就不行

**Comment by lzy83925** [comment]
我的也是多卡

**Comment by hcxss** [comment]
你解决了吗


&nbsp;


hcx
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Luis ***@***.***&gt;; 
发送时间: 2023年10月17日(星期二) 下午5:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 多卡加载模型后，在问答时会报错Caught exception: &#39;choices&#39; (Issue #1755)





 
我的也是多卡

**Comment by gagakou** [comment]
我就是用chatglm2-6b-32k会报这个错，其它模型就正常

**Comment by jhw0510** [comment]
> 我就是用chatglm2-6b-32k会报这个错，其它模型就正常

多卡部署chatglm2-6b-32k吗？不是多卡的话那个问题我记得是回答长度限制导致的，之前有人提过

**Comment by gagakou** [comment]
> > 我就是用chatglm2-6b-32k会报这个错，其它模型就正常
> 
> 多卡部署chatglm2-6b-32k吗？不是多卡的话那个问题我记得是回答长度限制导致的，之前有人提过

多卡和单卡都试过，就是chatglm2-6b-32k这个模型会出现这个问题，baichuan2-13b和llama2-13b都可以正常问答

**Comment by zRzRzRzRzRzRzR** [comment]
历史记录代码的问题，更新到dev试试还有没有这个情况

**Comment by hzg0601** [comment]
chatglm2-6b-32k模型的model代码写的有问题，参考chatglm2-6b的代码，将kv-cache中torch.cat相关的操作以元组的形式保存即可

**Comment by hzg0601** [comment]
建议像chatglm项目组反馈
