### ISSUE TITLE
[BUG] 初始化知识库报No module named 'configs.basic_config'

### ISSUE THREAD

**Issue by zhanghui-china** [chatchat-space/Langchain-Chatchat#1758]
**问题描述 / Problem Description**
初始化知识库报 No module named 'configs.basic_config

**复现问题的步骤 / Steps to Reproduce**
cd ~/Langchain-Chatchat/
python init_database.py --recreate-vs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
初始化成功。

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
(chatchat) zhanghui@zhanghui-OMEN-by-HP-Laptop-17-ck0xxx:~/Langchain-Chatchat$ python init_database.py --recreate-vs
Traceback (most recent call last):
  File "/home/zhanghui/Langchain-Chatchat/init_database.py", line 1, in <module>
    from server.knowledge_base.migrate import create_tables, reset_tables, folder2db, prune_db_docs, prune_folder_files
  File "/home/zhanghui/Langchain-Chatchat/server/knowledge_base/migrate.py", line 1, in <module>
    from configs import (EMBEDDING_MODEL, DEFAULT_VS_TYPE, ZH_TITLE_ENHANCE,
  File "/home/zhanghui/Langchain-Chatchat/configs/__init__.py", line 1, in <module>
    from .basic_config import *
ModuleNotFoundError: No module named 'configs.basic_config'

![f5b3c0204062445831b54b2422d1e40](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/2130c378-5fbb-4039-aa45-d01dcffd4bdd)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：No。
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: ubuntu 18.04
- Python 版本 / Python version:Python 3.10.13
- 其他相关环境信息 / Other relevant environment information: conda pytorch 2.1.0 cuda 12.1('2.1.0+cu121'）

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by CaoYongshengcys** [comment]
configs文件夹下的py.example改成py就可以

**Comment by zhanghui-china** [comment]
谢谢，已解决：
cp model_config.py.example model_config.py

cp server_config.py.example server_config.py

cp basic_config.py.example basic_config.py

cp kb_config.py.example kb_config.py

cp prompt_config.py.example prompt_config.py
