### ISSUE TITLE
[FEATURE] 上传文档的总结

### ISSUE THREAD

**Issue by wangzuohao** [chatchat-space/Langchain-Chatchat#1760]
现在这个项目只有根据知识库的聊天功能，可以提供对于上传文档的总结功能嘛？

**Comment by zRzRzRzRzRzRzR** [comment]
有的，之后的几个版本有在考虑这个功能

**Comment by wangzuohao** [comment]
非常感谢，请问有大概时间嘛？比如说一个月？两个月？因为我们最近在测试这个功能，如果时间赶不上，可能就要找其他方案或者自己开发了
