### ISSUE TITLE
可以提供单独调用fastchat部署的独立模型服务api接口吗？

### ISSUE THREAD

**Issue by lonngxiang** [chatchat-space/Langchain-Chatchat#1765]
这边想只用除了模型部署这块其他比如web界面相关的功能（页面，知识库、web等）；与fastchat部署的独立模型服务api怎么api对接

**Comment by liunux4odoo** [comment]
本项目基本可以与fastchat分开独立运行，但意义不大：
1. 本项目对fastchat做了一定封装，使LLM部署更便捷。
2. 本项目对fastchat做了一些扩展，比如在线API模型、LLM模型切换功能，使用独立的fastchat是无法实现的。
3. 在放弃模型切换功能的基础上，其它单独部署的fastchat模型可以注册到本项目启动的fastchat openai_api_server上，本项目可以通过fastchat正常调用。

**Comment by lonngxiang** [comment]
> 本项目基本可以与fastchat分开独立运行，但意义不大：
> 
> 1. 本项目对fastchat做了一定封装，使LLM部署更便捷。
> 2. 本项目对fastchat做了一些扩展，比如在线API模型、LLM模型切换功能，使用独立的fastchat是无法实现的。
> 3. 在放弃模型切换功能的基础上，其它单独部署的fastchat模型可以注册到本项目启动的fastchat openai_api_server上，本项目可以通过fastchat正常调用。

集成对于简单使用确实很好；但对于稍微有定制化需求就不大友好了；比如除了这个与fastchat分开独立运行，另外我还想挂一个确定性的第三方数据库呢

**Comment by liunux4odoo** [comment]
> > 本项目基本可以与fastchat分开独立运行，但意义不大：
> > 
> > 1. 本项目对fastchat做了一定封装，使LLM部署更便捷。
> > 2. 本项目对fastchat做了一些扩展，比如在线API模型、LLM模型切换功能，使用独立的fastchat是无法实现的。
> > 3. 在放弃模型切换功能的基础上，其它单独部署的fastchat模型可以注册到本项目启动的fastchat openai_api_server上，本项目可以通过fastchat正常调用。
> 
> 集成对于简单使用确实很好；但对于稍微有定制化需求就不大友好了；比如除了这个与fastchat分开独立运行，另外我还想挂一个确定性的第三方数据库呢

这个需求与fastchat分开不分开没有关系，需要自己二次开发。

**Comment by lonngxiang** [comment]
> > > 本项目基本可以与fastchat分开独立运行，但意义不大：
> > > 
> > > 1. 本项目对fastchat做了一定封装，使LLM部署更便捷。
> > > 2. 本项目对fastchat做了一些扩展，比如在线API模型、LLM模型切换功能，使用独立的fastchat是无法实现的。
> > > 3. 在放弃模型切换功能的基础上，其它单独部署的fastchat模型可以注册到本项目启动的fastchat openai_api_server上，本项目可以通过fastchat正常调用。
> > 
> > 
> > 集成对于简单使用确实很好；但对于稍微有定制化需求就不大友好了；比如除了这个与fastchat分开独立运行，另外我还想挂一个确定性的第三方数据库呢
> 
> 这个需求与fastchat分开不分开没有关系，需要自己二次开发。

嗯了解，感谢回复
