### ISSUE TITLE
[BUG] openai api 接口问题

### ISSUE THREAD

**Issue by cl165** [chatchat-space/Langchain-Chatchat#1767]
**问题描述 / Problem Description**
第一次运行项目初始化知识库报错
![5669495ab10a14ab4af6f138110a259](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/c9c446f4-ee19-4390-8bf0-ceb7f520bfe3)
api_base_url 修改为国内代理地址，如截图
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/141d7502-93f9-4ee5-9f7d-75c3428e7808)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：线上的openai接口
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text-embedding-ada-002
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04 LTS
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by cl165** [comment]
我发现使用openai接口时，替换api_base_url 为国内的根本不起作用啊，必须设置openai_proxy代理才可以,,,,

**Comment by cl165** [comment]
又发现直接和LLM对话，api_base_url配置生效，但结合知识库后就自动调用api.openai.com了。。。。。。。

**Comment by cl165** [comment]
已解决，就算不用openai_proxy，也不能注释掉。。。

**Comment by Flagami** [comment]
> 已解决，就算不用openai_proxy，也不能注释掉。。。

请问是怎么解决国内代理openai的api问题的
    "openai-api": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "这里填什么？"
        "api_key": "sk-代理提供的key",
        "openai_proxy": "这里填什么？",
    },
