### ISSUE TITLE
[BUG] 使用默认配置faiss向量库，报错 

### ISSUE THREAD

**Issue by cl165** [chatchat-space/Langchain-Chatchat#1769]
**问题描述 / Problem Description**
使用默认配置faiss向量库，报错 ，如下图
![fde2b366f6d12751ceee98785eec4c3](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/586b1007-c4a4-4399-99b9-a411505ce841)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：线上的openai接口
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text-embedding-ada-002
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:Ubuntu 22.04 LTS
- Python 版本 / Python version: Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by liunux4odoo** [comment]
Duplicate of #1657
