### ISSUE TITLE
[BUG] 传入中文的JSON文件后，无法生成内容

### ISSUE THREAD

**Issue by YangQianli92** [chatchat-space/Langchain-Chatchat#1774]
传入的知识库是JSON文件时，文件名是英文，内容是中文，编码方式是utf-8，然后利用本地知识库检索时，无法生成内容
但是有知识库匹配内容，打开看之后时ascii类型的，请问这个该如何解决呢？
用txt等就可以正常输出

**Comment by qweqwe716** [comment]
同求解答

**Comment by zRzRzRzRzRzRzR** [comment]
没有听懂，举个例子可以么，我们好复现

**Comment by YangQianli92** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/108046369/c78fdbd3-7148-4f0f-bfe4-e54ff74f69d2)
知识库检索时，无法生成内容，并且查看匹配的，都是ascii格式的

**Comment by rob-cd** [comment]
已经修复了吗

**Comment by YangQianli92** [comment]
已解决
在 `server/chat/knowledge_base_chat.py` 中将
`text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{doc.page_content}\n\n"""`
改为
`text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{bytes(doc.page_content,'utf-8').decode('unicode_escape')}\n\n"""`
可以解决知识库匹配结果中，无法展示JSON中文内容的问题

对于无法产生输出，我检查了一下，原因是：GPU显存不足，导致无法正常生成内容，如V100s 32GB，fp16加载时，若匹配到的知识比较长的话，会导致显存不足（但并不会报OOM），无法生成内容
