### ISSUE TITLE
[BUG] 简洁阐述问题 / 再Ubuntu服务器中，执行python3 startup.py -a 报错如图

### ISSUE THREAD

**Issue by Kason-wu** [chatchat-space/Langchain-Chatchat#1776]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 :/home/Langchain-Chatchat-0.2.5# python3 startup.py -a

**预期的结果 / Expected Result**

**实际结果 / Actual Result**
描述实际发生的结果 / 报错

![微信图片_20231017204506](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/5b80a810-9907-468a-87e6-dea64a1f59cc)

**环境信息 / Environment Information**
langchain-ChatGLM 版本/commit 号：v0.2.25版本
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm2-6b
使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: UBuntu
Python 版本 / Python version: 3.9.13
其他相关环境信息 / Other relevant environment information:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
确认一下server/agent/callbacks.py这个文件第一行有么有`from __future__ import annotations`，如果没有就需要更新一下代码和依赖。

**Comment by yansheng105** [comment]
升级到python 3.10即可，或者手动改下代码里面的函数参数类型定义部分，把 | 去掉就行

**Comment by Kason-wu** [comment]
![304464d85ddce69f883398c5d35d93b](https://github.com/chatchat-space/Langchain-Chatchat/assets/72248809/650cb7ca-8e90-4e74-8b94-52402247afd5)

问题：ems,回答的答案，不在训练的知识库中。这种属于正常现象吗？

**Comment by HuMian10** [comment]
问下你运行时，有出现这种情况吗
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101257078/d5fb69ae-ca6d-436f-9756-e9fc51acdb55)
