### ISSUE TITLE
请问使用CPU启动的最低内存要求是多少

### ISSUE THREAD

**Issue by 1249815869** [chatchat-space/Langchain-Chatchat#1777]
**问题描述 / Problem Description**
我使用python startup.py --a命令启动项目后会出现内存拉满然后触顶反弹的情况，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/65490763/53d54f42-3220-4500-90e1-d64308f20824)

最后项目只有20000端口的服务请求成功
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/65490763/6a817577-aaf9-4eda-845f-c3c4909bd148)
并且发送http://127.0.0.1:20000/v1/models 请求来查看被允许的模型也只有百川、方舟、通义千问等在线模型的api，没有我自己在model_config.py中配置的本地模型。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python startup.py --a
2. 使用postman发送http://127.0.0.1:20000/v1/models 请求查看可以使用的模型
3. 问题出现:只有在线模型的api可使用，没有本地配置的模型

**预期的结果 / Expected Result**
返回结果的列表中应该有我配置好的chatglm2-6b-int4模型

**实际结果 / Actual Result**
返回结果的列表中只有在线模型的api

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm2-6b-int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.10

**Comment by zRzRzRzRzRzRzR** [comment]
取决于你的模型，根据你提出的issu中的模型，我建议是10G，这个反弹是因为他吧模型从内存移动到显存了
你的内存需要取决于模型载入用的显存大小 + embed 模型大小
