### ISSUE TITLE
[FEATURE] 有没有按目录分隔文档的Text Splitter

### ISSUE THREAD

**Issue by Lijia0** [chatchat-space/Langchain-Chatchat#1778]
**功能描述 / Feature Description**
按文档的目录分隔文档

**Comment by zRzRzRzRzRzRzR** [comment]
什么意思，就是文件的目录 然后再文件中对应的目录文档分词吗
如果是这样，这可能比较困难，因为智能的识别目录将会是一个比较困难的过程
而且，就算这样分，一段文字太长，也不适合放入大模型，我们一般trunksize也就设置150 因为这样embed更好进行相似度比较

**Comment by PrimaLuz** [comment]
> 什么意思，就是文件的目录 然后再文件中对应的目录文档分词吗 如果是这样，这可能比较困难，因为智能的识别目录将会是一个比较困难的过程 而且，就算这样分，一段文字太长，也不适合放入大模型，我们一般trunksize也就设置150 因为这样embed更好进行相似度比较

请问一下，这个chunksize的大小有没有测试过，通常情况下设置多少会产生最好的效益。
