### ISSUE TITLE
[BUG] KeyError: Caught exception: 'choices' 更换了好几个模型全都是这个问题

### ISSUE THREAD

**Issue by JavaLionLi** [chatchat-space/Langchain-Chatchat#1780]
**问题描述 / Problem Description**
python 3.10 
m3e-base 
chatglm2-6b-int4 
单卡8g显存按照官网教程搭建 
代码没有任何改动最新的 
看了其他好多issue都没法解决

![166162e54eb1fc28a785d99c2cf4f60](https://github.com/chatchat-space/Langchain-Chatchat/assets/31852897/108c692d-91e1-49ed-af13-b2f5183624e1)
![73dabe0503b3ac9d617e4d17e5fcf8f](https://github.com/chatchat-space/Langchain-Chatchat/assets/31852897/c5423989-e2f4-4960-a41c-33eb2d9e8bcd)
![4699c0038f903b0b0c6410f12d953f1](https://github.com/chatchat-space/Langchain-Chatchat/assets/31852897/c98c9155-3f05-40ba-b634-0f17de12148c)
![241ac94cd5d8ef57f9ff371e9da3d7b](https://github.com/chatchat-space/Langchain-Chatchat/assets/31852897/d30e533f-a18f-4269-9e65-19026538597f)
![cafd58358d665215e7d9a6eb26ec9d4](https://github.com/chatchat-space/Langchain-Chatchat/assets/31852897/b25f531d-0823-4b70-a95c-44e70ac2ea56)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by uchihayou** [comment]
我也是这个问题，等一个大佬

**Comment by eyu11** [comment]
这个帮忙能不能优先处理一下呀

**Comment by zRzRzRzRzRzRzR** [comment]
更新到dev，这个是历史记录的问题

**Comment by lv199882** [comment]
> 更新到dev，这个是历史记录的问题

大佬，更新dev是更新环境吗？

**Comment by JavaLionLi** [comment]
> 更新到dev，这个是历史记录的问题

看图 我用的就是git最新的dev版本 一样有问题

**Comment by hzg0601** [comment]
截了这么多图没有一张截到点子上

**Comment by JavaLionLi** [comment]
这问题解决的真牛

**Comment by hzg0601** [comment]
> 解决不掉问题就关闭问题 真牛
不是解决不了问题，而是你连问问题的能力都没有

**Comment by ReMegumin** [comment]
试试降级吧 我torch 降级2.0.1就能用了

**Comment by AlphaNext** [comment]
> 解决不掉问题就关闭问题 真牛

毕竟背KPI

**Comment by chf-007** [comment]
+1

**Comment by hzg0601** [comment]
> > 解决不掉问题就关闭问题 真牛
> 
> 毕竟背KPI

蠢就算了，还恶毒
