### ISSUE TITLE
[BUG] pdf文件入向量库失败

### ISSUE THREAD

**Issue by zolibra** [chatchat-space/Langchain-Chatchat#1783]
**问题描述 / Problem Description**
2023-10-18 10:55:56 | ERROR | root | ImportError: 从文件 demo/abc.pdf 加载文档时出错：libGL.so.1: cannot open shared object file: No such file or directory

**临时解决方案：**
sudo apt-get install libgl1-mesa-glx

**预期解法**
pip install requirments的时候自动识别并提示安装？

**Comment by ecjtulrh** [comment]
libgl1-mesa-glx请问这个包是做啥用的呢？

**Comment by zRzRzRzRzRzRzR** [comment]
libgl1-mesa-glx不是py库，没办法写在requirments,这是系统包

**Comment by zRzRzRzRzRzRzR** [comment]
wiki已经写到，记得看看wiki

**Comment by ecjtulrh** [comment]
我也出现了这个问题，请问您的最后解决方案是什么呢？

**Comment by ecjtulrh** [comment]
我在我运行的docker里面运行了apt-get install libgl1-mesa-glx，成功安装了，但是PDF依然加载有问题

**Comment by Astlvk** [comment]
> wiki已经写到，记得看看wiki

wiki过了几遍没看到相关问题……emmm，这边linux系统，看issues里安装opencv-python-headless后就没问题了。

**Comment by Astlvk** [comment]
> 我在我运行的docker里面运行了apt-get install libgl1-mesa-glx，成功安装了，但是PDF依然加载有问题

可以尝试安装下opencv-python-headless，我这边安装后可以正常加载不报错了。

**Comment by ketewang** [comment]
安装opencv-python-headless

**Comment by irisrain** [comment]
yum update -y
yum install mesa-libGL glib2 -y

**Comment by SongJayJay** [comment]
我也遇到
