### ISSUE TITLE
how to access FastChat API for testing

### ISSUE THREAD

**Issue by JulyMin** [chatchat-space/Langchain-Chatchat#1786]
What are the steps for utilizing the original FastChat API (/v1) , for testing usage ,once ChatChat has been deployed?
Could you provide details on the parameters and scripts that require adjustments to make the original FastChat API (located at /v1) accessible following the deployment of ChatChat?

请问如何在部署 ChatChat 后使用FastChat API 为了方便测试？
请问在部署 ChatChat 后，需要修改哪些参数和脚本以暴露原始的 FastChat API（通常在 /v1）？

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.6前后端分离，部署后可以在7861看到所有的接口调用
