### ISSUE TITLE
基于知识库的问答是不是只支持单轮对话？

### ISSUE THREAD

**Issue by Orion-Zheng** [chatchat-space/Langchain-Chatchat#1790]
在使用的时候发现模型似乎只能针对每次的问题进行检索，无法结合历史的对话记录回答问题，请问这个是有意设计成这样的还是模型/prompt能力的原因呢？
![2934aac2-0459-4014-8e98-6b50b1863cd3](https://github.com/chatchat-space/Langchain-Chatchat/assets/62330719/74a34e69-584a-4f04-badf-6e35e80f01fc)

**Comment by zRzRzRzRzRzRzR** [comment]
支持连续对话，历史信息是传入到模型中的，但是由于嵌入的知识较长可能导致模型没法get到，这是有可能的，确实效果没有直接对话好
