### ISSUE TITLE
[BUG] windows10运行python startup.py -a报错FileNotFoundError: Could not find module

### ISSUE THREAD

**Issue by wzz981** [chatchat-space/Langchain-Chatchat#1793]
**问题描述 / Problem Description**
我使用Langchain-Chatchat版本是0.25，用 windows10来执行。
我按文档已经配置好了model_config.py,其中MODEL_PATH的llm_model和embed_model的路径更改成本地已下载好的模型路径，运行python startup.py -a报错FileNotFoundError: Could not find module，程序还是会自动下载huggingface，没有加载本地的模型。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python startup.py -a

只修改了model_config.py模型路径，其他未修改。

以下为日志信息：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/95325500/6c776553-b855-4ae0-bf30-0ff981739d4a)

请问这种情况怎么解决，是还需要配置哪些内容吗

**Comment by szdengdi** [comment]
查了一下.cache，是m3e-base会去调用gpt2的几个json文件，把这几个文件复制到本地就解决了。
链接:https://caiyun.139.com/m/i?135Clm8Qb6Cv8
提取码:5jTy
下载，解压，复制到chatchat的目录下面。

**Comment by zRzRzRzRzRzRzR** [comment]
可以不用gpt2，可以用文字分词，wiki都有写，看一下wiki哦

**Comment by wzz981** [comment]
> wiki

你好，这个需要修改哪里呢

**Comment by wzz981** [comment]
> 可以不用gpt2，可以用文字分词，wiki都有写，看一下wiki哦

你好，这个需要修改哪里呢

**Comment by yyppp9** [comment]
请问最后解决了吗？我用的是bge-large-zh-v1.5 & chatglm2-6b-int4，也出现了这样的问题
