### ISSUE TITLE
[BUG] 对话模式是知识库问答时，api_base_url配置不生效

### ISSUE THREAD

**Issue by cl165** [chatchat-space/Langchain-Chatchat#1795]
**问题描述 / Problem Description**
对话模式是知识库问答时，api_base_url配置不生效，默认还是使用api.openai.com域名

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新版本(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: windows11
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
刚才复现了一下，复现不出来，能提供一下截图和日志吗，你用dev版本试一下

**Comment by cl165** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/281b300b-a4d3-46c9-a794-e37ed60cb0ff)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/c2722a04-1f75-4a41-8042-26839f784c0a)

**Comment by cl165** [comment]
> 刚才复现了一下，复现不出来，能提供一下截图和日志吗，你用dev版本试一下

好的，已截图

**Comment by liunux4odoo** [comment]
修改配置后重启服务器了吗？

**Comment by cl165** [comment]
> 修改配置后重启服务器了吗？

重启了

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.6试一下，如果有还有这种情况，提交一下日志，我们没法复现出来

**Comment by cl165** [comment]
> 更新到0.2.6试一下，如果有还有这种情况，提交一下日志，我们没法复现出来

已更新0.2.6，手动部署，LLM_MODEL = "OpenAI"，发现另外的问题，并不是api_base_url不生效，问题描述：
1）初始化启动系统，打开web ui，直接使用知识库问答，报错；
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/cc63bfe2-7c98-4120-9d88-202bd284db06)
2）初始化启动系统，打开web ui，先选择LLM对话，一切正常，api_base_url 也变成我指定的域名，然后切换知识库问答，也正常，没有问题。
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/6203863/9d98ada1-c0bf-4b6e-a6c4-6f66e324c558)
总结：问题复现在第一种情况下会报错

**Comment by zRzRzRzRzRzRzR** [comment]
联网模型是一个问题，
目前，我们将langchain的模型和其他联网模型分开 openai 和Azure openai走的是langchain
由于走langchain的模型并不会走API，因此，这部分模型并没进行封装，在0.2.6发版的时候，我们仅保证所有模型都能正常调用，我们会在0.2.7版本解决这问题
