### ISSUE TITLE
bug :http://10.28.2.31:7861/chat/chat 只能调用gpt-3.5-turbo,不能调用其他gpt-3.5-turbo-16k等版本

### ISSUE THREAD

**Issue by toby911** [chatchat-space/Langchain-Chatchat#1797]
bug :
经过测试:
接口: http://10.28.2.31:7861/chat/fastchat 可以调用任何在线api
接口: http://10.28.2.31:7861/chat/chat:
1.国产在线api均可调用
2.openai的官网模型只能调用gpt-3.5-turbo,不能调用gpt-3.5-turbo-16k等其他版本

**Comment by ByteMelodist** [comment]
可以在配置文件中修改添加

**Comment by toby911** [comment]
> 可以在配置文件中修改添加
我已经在配置配置文件修改过了,我指的是这个接口http://10.28.2.31:7861/chat/chat:
无法成功请求gpt-3.5-turbo-16k
