### ISSUE TITLE
请问真正传入语言模型的输入是什么呢？

### ISSUE THREAD

**Issue by ito-integration** [chatchat-space/Langchain-Chatchat#1806]
（语言模型为chatglm2-6b，嵌入模型为piccolo-large-zh）我想要得到结构化的输出，让模型只输出ABCD中的一个（相当于让模型做选择题）。构造了如下的prompt：
 """
    <指令>结合已知信息，给出问题的正确选项。</指令>
    <已知信息>{{ context }}</已知信息>
    <问题>{{ question }}
    请直接回答正确选项，no reasoning！
    A. 冠心病
    B. 心肌炎
    C. 心肌病变
    D. 先天性心脏病</问题>
    """
以上的prompt模板在这个项目中可以得到格式化的输出：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/148534585/32216043-3446-4b45-9bf5-6ef4f4c6dd7a)
但是**使用相同的prompt模板，用generate/chat方法生成文本，却无法得到格式化输出**，模型在做填空题（前后的temperature都是0.0）：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/148534585/5d428c38-d531-4a9b-86a8-1d1fbedd517c)
我尝试过把prompt模板用ChatPromptTemplate.from_messages处理（和server/chat/knowledge_base_chat.py的做法类似），但是直接使用generate/chat方法依旧得不到格式化输出。

所以，是langchain库会对输入文本进行其它操作吗？真正输入至语言模型的文本是怎样的？还是说LLMchain.acall方法与模型自带的generate/chat方法不同？另外，对于chatglm2模型，除微调外，有没用可以稳定触发格式化输出的模板？

**Comment by zRzRzRzRzRzRzR** [comment]
context 是知识库搜索到的内容
question 是你的问题
这样会被组合成一个完整的prompt然后传入模型来回答
Langchain是会对提示词进行更底层的操作的，
对于glm2模型，他比较天马星空，稳定的话经过实际测试，得换更大的模型

**Comment by ito-integration** [comment]
> context 是知识库搜索到的内容 question 是你的问题 这样会被组合成一个完整的prompt然后传入模型来回答 Langchain是会对提示词进行更底层的操作的， 对于glm2模型，他比较天马星空，稳定的话经过实际测试，得换更大的模型

我想了解的就是Langchain对完整prompt的操作，请问有什么参考资料吗？（搞不懂Langchain库的源码，理不清头绪）

**Comment by zRzRzRzRzRzRzR** [comment]
Langchian的操作只是加上了前后缀，Prompt 跟你传入langchain是一样的

**Comment by sevenandseven** [comment]
> context 是知识库搜索到的内容 question 是你的问题 这样会被组合成一个完整的prompt然后传入模型来回答 Langchain是会对提示词进行更底层的操作的， 对于glm2模型，他比较天马星空，稳定的话经过实际测试，得换更大的模型

我想问一下，如果我的模板中有三个变量，我在context和question的基础上在添加一个history，是不是使用链的时候，输入await chain.acall({"context": context, "question": query，“”histoty":history})修改成这个样子就可以了？
