### ISSUE TITLE
[BUG] OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by Orion-Zheng** [chatchat-space/Langchain-Chatchat#1807]
在之前的[issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/1727)中，给出的解决方案是
```
cat /proc/sys/fs/inotify/max_user_watches # 默认应该是 8192
echo 81920 > /proc/sys/fs/inotify/max_user_watches
```
但是如果不是root用户的话没有权限修改（比如在公有的服务器上），所以就需要修改streamlit的config。
首先使用`streamlit config show`列出默认的配置。
然后使用`streamlit config show > ~/.streamlit/config.toml`在家目录下生成个streamlit的配置文件
然后进入文件，把[server]下的fileWatcherType改成none，另外把前两行没用的注释删掉
<img width="702" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/62330719/c93e6b50-8e6f-4a8e-b8b3-c160174149a2">
<img width="654" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/62330719/3be3fd95-6077-405d-95d3-58b8c0699dbc">
然后再运行就不会报错了
`CUDA_VISIBLE_DEVICES=7 python startup.py -a`

**Comment by hzg0601** [comment]
感谢提供解决方案

**Comment by FelixZhang7** [comment]
> streamlit config show > ~/.streamlit/config.toml

您好，我也遇到这个问题，在执行streamlit config show > ~/.streamlit/config.toml时会报错是为什么呢？
![7B0FF7BF-CC31-4115-A130-6567FFBFA7F9](https://github.com/chatchat-space/Langchain-Chatchat/assets/32166605/d3e372b7-73fb-42bf-a2a3-d2771e2be092)

**Comment by FelixZhang7** [comment]
> 在之前的[issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/1727)中，给出的解决方案是
> 
> ```
> cat /proc/sys/fs/inotify/max_user_watches # 默认应该是 8192
> echo 81920 > /proc/sys/fs/inotify/max_user_watches
> ```
> 
> 但是如果不是root用户的话没有权限修改（比如在公有的服务器上），所以就需要修改streamlit的config。 首先使用`streamlit config show`列出默认的配置。 然后使用`streamlit config show > ~/.streamlit/config.toml`在家目录下生成个streamlit的配置文件 然后进入文件，把[server]下的fileWatcherType改成none，另外把前两行没用的注释删掉 <img alt="image" width="702" src="https://user-images.githubusercontent.com/62330719/276885186-c93e6b50-8e6f-4a8e-b8b3-c160174149a2.png"> <img alt="image" width="654" src="https://user-images.githubusercontent.com/62330719/276885465-3be3fd95-6077-405d-95d3-58b8c0699dbc.png"> 然后再运行就不会报错了 `CUDA_VISIBLE_DEVICES=7 python startup.py -a`

**Comment by Orion-Zheng** [comment]
> > streamlit config show > ~/.streamlit/config.toml
> 
> 您好，我也遇到这个问题，在执行streamlit config show > ~/.streamlit/config.toml时会报错是为什么呢？ ![7B0FF7BF-CC31-4115-A130-6567FFBFA7F9](https://user-images.githubusercontent.com/32166605/277226058-d3e372b7-73fb-42bf-a2a3-d2771e2be092.png)

应该是没有创建~/.streamlit这个目录吧，你试一下`mkdir ~/.streamlit`

**Comment by callanwu** [comment]
thx a lot~ @Orion-Zheng
