### ISSUE TITLE
比如我提问"刚才我问的是什么?"

### ISSUE THREAD

**Issue by gao123qiang** [chatchat-space/Langchain-Chatchat#1809]
history里面有数据，我的问题是"刚才我问的是什么"，从知识库里面也是匹配到了一些score分数不高的数据，但是数据进去以后，是找不到答案的。这类型的提问该怎么去处理

**Comment by zRzRzRzRzRzRzR** [comment]
知识库的连续对话能力较弱，而且他是没有办法智能吧上次你提问的内容在嵌入进去的 历史记录只会被参考，不会被Embed
这个问题现在可以通过Agent对话来自由切换知识库或者不使用知识库
