### ISSUE TITLE
[FEATURE] Bing搜索引擎支持自定义搜索引擎

### ISSUE THREAD

**Issue by yangyl001** [chatchat-space/Langchain-Chatchat#1818]
**功能描述 / Feature Description**
Bing搜索引擎支持自定义搜索引擎

**解决的问题 / Problem Solved**
目前对Bind的搜索引擎仅支持一般搜索引擎，搜索配置url如下：
BING_SEARCH_URL = "https://api.bing.microsoft.com/v7.0/search"

**实现建议 / Implementation Suggestions**
是否可以增加
BING_SEARCH_CUSTOMER_URL ="https://api.bing.microsoft.com/v7.0/custom/search" + "q=" + searchTerm + "&customconfig=" + customConfigId;

**Comment by zRzRzRzRzRzRzR** [comment]
该功能属于开发者自定义的高级功能，目前短期内不会在基础的功能中实现
我们也参考了你的意见，并考虑在未来的版本中添加
