### ISSUE TITLE
请问如果不能联网，6B之类的文件从本地上传需要放到哪里

### ISSUE THREAD

**Issue by zhaoyiCC** [chatchat-space/Langchain-Chatchat#182]
感谢大佬的项目，很有启发~
问一个服务器的问题，由于服务器不能联网，现在报这个错：
HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /THUDM/chatglm-6b/resolve/main/tokenizer_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f451adcd6a0>, 'Connection to huggingface.co timed out. (connect timeout=10)'))' thrown while requesting HEAD https://huggingface.co/THUDM/chatglm-6b/resolve/main/tokenizer_config.json

想知道这些文件我从本地上传到哪个目录，以及在代码中该怎么指定（如果需要的话）

**Comment by zhaoyiCC** [comment]
想知道这些文件我从本地上传到哪个目录，以及在代码中该怎么指定（如果需要的话）

**Comment by imClumsyPanda** [comment]
建议参考一下 readme 常见问题中的方法把 embedding 和 llm 模型下载并在 configs/model_config.py 中配置 embedding 与 llm 的本地地址。

除此之外，对于本地使用 Web UI，建议将 Gradio 版本要求降低至 3.21，否则可能出现因需要联网下载字体导致的持续停留在 loading 画面

**Comment by zhaoyiCC** [comment]
您好，感谢您的回复~我把模型文件传上去了，然后现在遇到这个问题：

To create a public link, set `share=True` in `launch()`.
Error while sending telemetry: HTTPSConnectionPool(host='api.gradio.app', port=443): Max retries exceeded with url: /gradio-launched-telemetry/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb968df70d0>, 'Connection to api.gradio.app timed out. (connect timeout=3)'))

不知道是什么原因呢，想请教一下！

**Comment by wa2003** [comment]
> 您好，感谢您的回复~我把模型文件传上去了，然后现在遇到这个问题：
> 
> To create a public link, set `share=True` in `launch()`. Error while sending telemetry: HTTPSConnectionPool(host='api.gradio.app', port=443): Max retries exceeded with url: /gradio-launched-telemetry/ (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb968df70d0>, 'Connection to api.gradio.app timed out. (connect timeout=3)'))
> 
> 不知道是什么原因呢，想请教一下！

遇到了同样的问题，求教大神

**Comment by BUPTLdy** [comment]
也遇到了，不知道怎么处理。
