### ISSUE TITLE
向量库初始化：python init_database.py --recreate-vs 报错

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1824]
**问题描述 / Problem Description**
python init_database.py --recreate-vs
错误如下：
2023-10-21 23:40:53,941 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-10-21 23:40:53,941 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")

**复现问题的步骤 / Steps to Reproduce**
1. 运行数据库初始化 python init_database.py --recreate-vs
2. 后台包错
3. 缺模块faiss.swigfaiss_avx2
2023-10-21 23:40:53,941 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.26
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): No
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): 在线minimax
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:windows10
- Python 版本 / Python version:3.10.9

**Comment by digitalghost** [comment]
这个，感觉是没安装faiss模块导致的

**Comment by szdengdi** [comment]
不是没有按照是faiss，langchain的环境参数配置没有配置，如果没有AVX2，可以在环境变量里面关闭
https://api.python.langchain.com/en/latest/vectorstores/langchain.vectorstores.faiss.dependable_faiss_import.html?highlight=avx2

**Comment by tommickey2020** [comment]
如何配置这个环境参数？谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
严格按照requirements文件进行安装
