### ISSUE TITLE
[BUG] prompt模板提示词错误

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#1827]
**问题描述 / Problem Description**
在【请选择Prompt模板】时，选择的值跟右下角的提示词刚好相反。如图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/18339429/3fc7accd-1203-47a9-9855-db9406c42b7f)

环境信息 / Environment Information

langchain-ChatGLM 版本/commit 号：v0.2.6
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: Ubuntu 22.04
Python 版本 / Python version: python3.10
其他相关环境信息 / Other relevant environment information:

**Comment by szdengdi** [comment]
修改webui_pages\dialogue下面的dialogue.py，将143行
          text = f"已切换为 {prompt_template_name} 模板。"
修改为：
            text = f"已切换为 {st.session_state.prompt_template_select} 模板。"

**Comment by leoterry-ulrica** [comment]
> text

good

**Comment by leoterry-ulrica** [comment]
@imClumsyPanda 版本代码需要修复一下~

**Comment by ShinyWey** [comment]
> 修改webui_pages\dialogue下面的dialogue.py，将143行 text = f"已切换为 {prompt_template_name} 模板。" 修改为： text = f"已切换为 {st.session_state.prompt_template_select} 模板。"

good job

**Comment by Starlento** [comment]
commit: 6547005073eea0502fabb9d483fea6867a7f130e
我刚看了一下，好像这块代码又改回去了？
```
        index_prompt = {
            "LLM 对话": "llm_chat",
            "自定义Agent问答": "agent_chat",
            "搜索引擎问答": "search_engine_chat",
            "知识库问答": "knowledge_base_chat",
            "文件对话": "knowledge_base_chat",
        }
        prompt_templates_kb_list = list(PROMPT_TEMPLATES[index_prompt[dialogue_mode]].keys())
        prompt_template_name = prompt_templates_kb_list[0]
        if "prompt_template_select" not in st.session_state:
            st.session_state.prompt_template_select = prompt_templates_kb_list[0]

        def prompt_change():
            text = f"已切换为 {prompt_template_name} 模板。"
            st.toast(text)

        prompt_template_select = st.selectbox(
            "请选择Prompt模板：",
            prompt_templates_kb_list,
            index=0,
            on_change=prompt_change,
            key="prompt_template_select",
        )
        prompt_template_name = st.session_state.prompt_template_select
        temperature = st.slider("Temperature：", 0.0, 1.0, TEMPERATURE, 0.05)
        history_len = st.number_input("历史对话轮数：", 0, 20, HISTORY_LEN)
```
我试的时候又发现不一致了。
<img width="615" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/33574105/5128d50c-636a-4332-8e7b-0fec9b9b312d">

**Comment by zixiaotan21** [comment]
目前的Langchain-chatchat v0.2.10版本 仍然存在【请选择Prompt模板】时，选择的值跟右下角的提示词刚好相反的问题
按照这个方法修改成功了，谢谢！

> 修改webui_pages\dialogue下面的dialogue.py，将143行 text = f"已切换为 {prompt_template_name} 模板。" 修改为： text = f"已切换为 {st.session_state.prompt_template_select} 模板。"
