### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by Qingzig** [chatchat-space/Langchain-Chatchat#1834]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
将项目部署到AtuoDL以后，
**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
可以运行，但是  webui给的url打不开网页是为什么呢？
**环境信息 / Environment Information**

- 是否使用 Docker 部署（是/否）：否 /
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 

- 操作系统及版本 / Operating system and version:linux
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
由于在autodl中没有加入跨域配置
你可以尝试在跨域配置中选为True重试
