### ISSUE TITLE
知识库问答--输入新的知识库名称是中文的话，会报error

### ISSUE THREAD

**Issue by chow-q** [chatchat-space/Langchain-Chatchat#184]
![image](https://user-images.githubusercontent.com/73530205/234749634-6cb55a49-b303-49a5-8219-21780720a5b1.png)
知识库问答--输入新的知识库名称是中文的话，会报error，选择要加载的知识库那里也不显示之前添加的知识库

**Comment by imClumsyPanda** [comment]
将在后续版本中增加知识库名与实际存储位置字典，以解决这一问题

**Comment by Astlvk** [comment]
> 将在后续版本中增加知识库名与实际存储位置字典，以解决这一问题

你好，目前这边0.2.5版本，发现windows下创建知识库时不能输入中文名，但linux正常。
