### ISSUE TITLE
[FEATURE] 更新版本重建数据库时，复用原来的内容

### ISSUE THREAD

**Issue by alexxchen** [chatchat-space/Langchain-Chatchat#1844]
**功能描述 / Feature Description**
在版本更新以后，复用之前得到的embedding，避免从头用模型计算embedding 向量。

**解决的问题 / Problem Solved**
Embedding 模型的输出并没有改变，复用原来的向量可以大大节省算力和更新版本的成本。

**实现建议 / Implementation Suggestions**
在更换数据库结构的时候保留对应文件名的向量，只对其他键值进行修改。

**Comment by zRzRzRzRzRzRzR** [comment]
主要两个原因，从0.2.1开始，一是知识库向量化的过程一直在变化，而是知识库信息存到sqlite里，重建是最简单的迁移方式
在之后的版本中，我们尽量减少这样的情况发生
感谢你的提议
