### ISSUE TITLE
如何精确的能够按照某些特殊数字字符字母组成的类似“编号”一样的关键字进行知识库内容的召回

### ISSUE THREAD

**Issue by digitalghost** [chatchat-space/Langchain-Chatchat#1845]
我在项目中应用的向量数据库（FAISS）中存储的文档如下格式：

文档1:
故障代码: 2088
所属系统: XX系统
故障产生原因: XXXXXXX
故障检修方法: YYYYYYY

文档2:
故障代码: 2099
所所属系统: XX系统
故障产生原因: XXXXXXX
故障检修方法: YYYYYYY

我发现进行召回的时候，如果用自然语言描述进行召回，确实是可以按照所属系统、产生原因、检修方法等描述的内容进行较为精准的内容召回。
但是当我使用“故障代码为2099的故障“这样的查询语句进行内容召回时，基本上准确率近乎为0.
或许这并不属于本项目讨论的范围，而是FAISS相关的内容，但是在实际应用中，还是希望各位大佬对于类似这样的需求（各种故障手册，都有相关编号；或者其他具备索引内容的相关文章也有对应的各种专业号码索引）能有一些小白就能用的解决方案。
我在网上找了很久，也基本没有找到类似的解决方案，请问各位大佬这种问题该如何解决？以及在Langchain-chatchat的实际应用中，应该通过修改哪部分相关代码，做什么样的处理能解决这种问题。是否可以在未来加入对于这种FEATURE的支持。
谢谢

**Comment by hihanyi** [comment]
把你的故障代码向量化时存到metadata中, 召回时先根据metadata中的故障代码做一下过滤

**Comment by zRzRzRzRzRzRzR** [comment]
我还有一种办法是对embed模型进行找回，例如2099是一个单独的对比词
接着，在召回中对embed召回的词对比，最后返回答案

**Comment by glide-the** [comment]
可以把编号存入到数据库，通过精确匹配召回

**Comment by WilliamChen-luckbob** [comment]
> 我还有一种办法是对embed模型进行找回，例如2099是一个单独的对比词 接着，在召回中对embed召回的词对比，最后返回答案

实现了一个通用方案，可以康康这个PR[#1888 ]，解决了这个问题[#1565 ]，这个应该跟我之前讨论的应该是同一个问题，直接自定义好文件名就可以实现索引，如果是更精细的操作，估计还是要使用者自己实现更加精细的文本切分
