### ISSUE TITLE
[FEATURE] 知识图谱的结构化数据读取 / Knowledge Graph（JSON）

### ISSUE THREAD

**Issue by ecjtulrh** [chatchat-space/Langchain-Chatchat#1846]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zRzRzRzRzRzRzR** [comment]
我们会考虑加入该功能，不过这与我们的核心功能关系不大，可能不是我们的首要研发任务。
谢谢你的提议

**Comment by Wangzhongxi** [comment]
> 我们会考虑加入该功能，不过这与我们的核心功能关系不大，可能不是我们的首要研发任务。 谢谢你的提议

现在可以使用langchain-chatchat连接Neo4j的知识图谱与向量进行混合检索吗
