### ISSUE TITLE
[FEATURE] 如何对在检索知识库之前对知识库进行过滤

### ISSUE THREAD

**Issue by milk-bottle-liyu** [chatchat-space/Langchain-Chatchat#1847]
**功能描述 / Feature Description**
提供一个知识预处理的回调接口，如果实现了该接口，则在知识检索之前对知识库进行过滤

**解决的问题 / Problem Solved**
在部分场景下，有一些硬性的检索条件可以对知识库中的知识进行过略，这样在后续的检索过程中可以减少不必要的计算

**实现建议 / Implementation Suggestions**
NA

**替代方案 / Alternative Solutions**
NA

**其他信息 / Additional Information**
NA

**Comment by yang1111-gif** [comment]
不是，这个问题解决了？咋关闭了？meta过滤吗？
