### ISSUE TITLE
从0.2.4升级到0.2.6后，同样参数，同样向量库和数据和LLM模型，同样提示词模板和问题，但效果差了很多。

### ISSUE THREAD

**Issue by zhaofangtao** [chatchat-space/Langchain-Chatchat#1848]
从0.2.4升级到0.2.6后，同样参数，同样向量库和数据和LLM模型，同样提示词模板和问题，但效果差了很多。

回答比较啰嗦。而且每个回答前面都有个换行符\n.  且不论怎么修改模板和问题，绝大多数回复都前缀都是：\n根据已知信息,......

而且感觉temperature就算设置极低值0.05. 回复结果也会泛化啰嗦：\n根据已知信息,......

搜了代码，除了模板，其他地方并没有强制这些的回复文本。

0.2.4版本很少有这些问题，请问这个怎么回事呢？

LLM：基于llama2中文微调的alpaca-13b

**Comment by zRzRzRzRzRzRzR** [comment]
不同版本之间的效果有一定的差异
我们并没有测试0.2.x各个版本之间的差异
由于0.2.5发生了很大的变化，因此 0.2.5以后的搜索方式确实与之前的有一定差距
开发组将会不断提升检索的性能，感谢你的关注
