### ISSUE TITLE
[BUG] 0.2.6版本代码 AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

### ISSUE THREAD

**Issue by qazwsx042** [chatchat-space/Langchain-Chatchat#1851]
**问题描述**

按照readMe 步骤，执行 `python startup.py -a` 报错：

```shell
...
2023-10-24 13:48:11 | ERROR | stderr |     vocab = {self._convert_id_to_token(i): i for i in range(self.vocab_size)}
2023-10-24 13:48:11 | ERROR | stderr |   File "/home/local/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 104, in vocab_size
2023-10-24 13:48:11 | ERROR | stderr |     return self.tokenizer.n_words
2023-10-24 13:48:11 | ERROR | stderr | AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'
```

**复现问题的步骤**

1. 下载 v0.2.6代码；
2. 安装环境： `pip install -r requirements.txt` 
3. 复制配置文件：`python copy_config_example.py` 
    并修改m3e 和chatGLM2-6b为本地路径，device 手动修改为'cuda'
5. 初始化知识库：`python init_database.py --recreate-vs` 
6. 上述步骤成功执行后，运行：`python startup.py -a` 报错。

**环境信息**
- langchain-ChatGLM 版本/commit 号：v0.2.6
- 是否使用 Docker 部署：否
- 使用的模型：ChatGLM2-6B
- 使用的 Embedding 模型：moka-ai/m3e-base
- 使用的向量库类型： faiss 
- Python 版本 : 3.10.13
- 其他相关环境信息: 

```shell
操作系统：Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.6
langchain版本：0.0.320. fastchat版本：0.2.31
```

**附加信息**

```shell
transformers版本   4.34.1

NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7 
```

感谢🙏

**Comment by 1787812757** [comment]
一样有这个情况,像是vllm不支持chatglm

**Comment by sunnnyu** [comment]
参考一下这个试试 https://github.com/chatchat-space/Langchain-Chatchat/issues/1835#issuecomment-1774439494
或者可能是transformer版本的问题，用pip install transformers==4.33.0，降低一下transformer

**Comment by qifuxiao** [comment]
解决了，pip install transformers==4.33.1，降低一下transformers版本

**Comment by Astrallee** [comment]
除了降低transformers版本，还有个办法是去huggingface上同步更新一下tokenization_chatglm.py这个文件。亲测chatglm2-6b-32k解决。
