### ISSUE TITLE
vectorstores/MyFAISS.py文件中similarity_search_with_score_by_vector方法返回的score意义是什么？请问是指搜索知识相关度还是距离？

### ISSUE THREAD

**Issue by winnie1228** [chatchat-space/Langchain-Chatchat#1854]
代码版本tag-v0.1.17，使用langchain版本0.0.174
请问vectorstores/MyFAISS.py文件中similarity_search_with_score_by_vector方法返回的score意义是什么？请问是指搜索知识相关度还是距离？

**Comment by zRzRzRzRzRzRzR** [comment]
distance score

**Comment by zRzRzRzRzRzRzR** [comment]
There are some FAISS specific methods. One of them is similarity_search_with_score, which allows you to return not only the documents but also the distance score of the query to them. The returned distance score is L2 distance. Therefore, a lower score is better.

**Comment by zixiaotan21** [comment]
想问一下，MyFAISS.py文件在哪个文件夹下呀，我使用langchain版本是0.2.10，似乎在vectorstores 下面找不到？
