### ISSUE TITLE
[FEATURE] Docker 中有healcheck 的配置吗/ Concise description of the feature

### ISSUE THREAD

**Issue by huyang19881115** [chatchat-space/Langchain-Chatchat#1855]
**功能描述 / Feature Description**
因为使用docker 启动，建议完善一下docker compose 文件，并且方便后续部署提升，方便大家去试用。
docker 部署中，希望有一个healcheck 的配置，利于对服务状态的监控检测

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有提供dockerfile 和docker-compose，只有docker镜像，这方面的内容我们暂时不会提供
