### ISSUE TITLE
api调用的疑问

### ISSUE THREAD

**Issue by ipv6next** [chatchat-space/Langchain-Chatchat#1857]
langchain集成本地LLM的原理是调用openai的方法，但是实际上调用地址是你的本地服务启动的LLM服务（将本地LLM的服务封装为与openai一样入参和路径的接口）从而实现通用化的调用，出现此错误十有八九是你的配置有误，而不是真的访问了openai。

如果外部应用想调用本地LLM（比如Chatglm）的能力，base_api_url 和 key 该怎么写？

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有办法传key，只能在后台写死

**Comment by ipv6next** [comment]
如果是这样，是在哪个文件里配置？ model_config.py 吗?
api-base-url : http://0.0.0.0:端口号/v1
