### ISSUE TITLE
现在能通过问题匹配的相似度值，来直接返回文档中的文段，而不经过模型吗？因为有些答案在文档中，模型自己回答，不能回答文档中的答案

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#186]
现在能通过问题匹配的相似度值，来直接返回文档中的文段，而不经过模型吗？因为有些答案在文档中，模型自己回答，不能回答文档中的答案。也就是说，提供向量检索回答+模型回答相结合的策略。如果相似度值高于一定数值，直接返回文档中的文本，没有高于就返回模型的回答或者不知道

**Comment by imClumsyPanda** [comment]
之前的方式在匹配过程中也不经过模型，只是现在改成了自己写

cristianohello ***@***.***>于2023年4月27日 周四13:58写道：

**Comment by WSL0809** [comment]
向量化完了计算相似度就行了，这不是向量数据库自带的工能嘛
