### ISSUE TITLE
[BUG] 0.2.6版本webui只能看到running的模型

### ISSUE THREAD

**Issue by lovelyjuice** [chatchat-space/Langchain-Chatchat#1862]
**问题描述 / Problem Description**
0.2.6版本webui只能看到running的模型
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20644461/593fe678-29a2-478b-86d7-0ac517c51663)

**复现问题的步骤 / Steps to Reproduce**
`python startup.py -a`

**预期的结果 / Expected Result**
可以在webui切换其他模型，而不是每次切换模型都要改配置文件。

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：commit 2f67e1d0cc8db61cd4cbad0c4596bc4604067942
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：Badichuan2-13B-Chat
- 使用的 Embedding 模型：m3e-base
- 使用的向量库类型： faiss
- 操作系统及版本 / Operating system and version: ubuntu lts 22.04
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by woshikid** [comment]
早上我也纳闷呢，而且这些在线模型出现了2遍，而本地模型不见了

**Comment by qifuxiao** [comment]
已解决，修改webui_pages/dialogue/dialogue.py中第99行代码：worker_models = list(config_models.get("local", {}))

可以查看https://github.com/chatchat-space/Langchain-Chatchat/issues/1865#issue-1960465121

**Comment by lovelyjuice** [comment]
0.2.7版本依旧有这个问题，这个bug是不是已经变成feature了
