### ISSUE TITLE
【需求】关于知识库的对话功能，要比0.1X版本有所减弱，建议此类核心功能要保留

### ISSUE THREAD

**Issue by Mike2100** [chatchat-space/Langchain-Chatchat#1866]
估计有两月没使用这个项目了，最近使用了一下，感觉知识库的对话功能有所减弱。有些明显的word文档知识库查询，应该能查询到的，但是现在查询不到了。
知识库查询，文本格式类的，是Top级的核心功能，建议此类功能保留。
谢谢

**Comment by ipv6next** [comment]
有同感
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135030220/d6baff41-3d32-49fa-bd8a-3479364772e2)

**Comment by qihangf** [comment]
+1,同感，我这边pdf的回答上也不如之前

**Comment by zhuhaifengaaa** [comment]
+1，项目挺大，但是核心功能：本地知识库的效果不是很好

**Comment by roki1031** [comment]
建议再优化优化

**Comment by zRzRzRzRzRzRzR** [comment]
在https://github.com/chatchat-space/Langchain-Chatchat/issues/14 中我们已经提到这一点，对比了0.2.x和0.1.x的检索方式区别
我们会考虑在之后的模式中重新结合
