### ISSUE TITLE
[BUG] 星火Api 在 LLM对话模式中，没有输出结果

### ISSUE THREAD

**Issue by qqilin1213** [chatchat-space/Langchain-Chatchat#1870]
**问题描述 / Problem Description**
LLM对话选择 xinghuo-api 在线模型，发送“你好”，界面没有返回数据
**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.6
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：xinghuo-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- Python 版本 / Python version: 3.9.5
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
![7d193f15f6c4d45d16973e04645679f](https://github.com/chatchat-space/Langchain-Chatchat/assets/59048420/bb9c5e49-c4ad-4867-a297-4e778310d1ec)

**Comment by zRzRzRzRzRzRzR** [comment]
dev已修复bug，更新到dev或等待0.2.7版

**Comment by zodostffaa** [comment]
> dev已修复bug，更新到dev或等待0.2.7版

使用dev版本仍然没有结果
