### ISSUE TITLE
[BUG] startup.py脚本如何指定程序运行在某几块GPU？

### ISSUE THREAD

**Issue by roki1031** [chatchat-space/Langchain-Chatchat#1871]
请问在python startup.py -a -q 命令中，如何指定模型运行在某几个GPU上？
此外，我将这段代码的args.num_gpus = 1改为8之后，程序直接显示每张卡都爆显存了，这是怎么回事呢？

> if kwargs["model_names"][0] in VLLM_MODEL_DICT and args.infer_turbo == "vllm":
            import fastchat.serve.vllm_worker
            from fastchat.serve.vllm_worker import VLLMWorker,app
            from vllm import AsyncLLMEngine
            from vllm.engine.arg_utils import AsyncEngineArgs,EngineArgs
            args.tokenizer = args.model_path # 如果tokenizer与model_path不一致在此处添加
            args.tokenizer_mode = 'auto'
            args.trust_remote_code= True
            args.download_dir= None
            args.load_format = 'auto'
            args.dtype = 'auto'
            args.seed = 0
            args.worker_use_ray = False
            args.pipeline_parallel_size = 1
            args.tensor_parallel_size = 1
            args.block_size = 16
            args.swap_space = 4  # GiB
            args.gpu_memory_utilization = 0.90
            args.max_num_batched_tokens = 2560
            args.max_num_seqs = 256
            args.disable_log_stats = False
            args.conv_template = None
            args.limit_worker_concurrency = 5
            args.no_register = False
            args.num_gpus = 1 # vllm worker的切分是tensor并行，这里填写显卡的数量
            args.engine_use_ray = False
            args.disable_log_requests = False

**Comment by roki1031** [comment]
怎么用外部使用的cuda visiable来指定呢？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zR ***@***.***&gt;
发送时间: 2023年10月25日 22:00
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: roki1031 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] startup.py脚本如何指定程序运行在某几块GPU？ (Issue #1871)





 
vllm没有办法指定，需要外部使用cuda visiable来指定

**Comment by zRzRzRzRzRzRzR** [comment]
命令行，设置CUDA_VISIBLE_DEVICES
