### ISSUE TITLE
[BUG] 关于导入非ptuning类peft加载-lora

### ISSUE THREAD

**Issue by Astrallee** [chatchat-space/Langchain-Chatchat#1876]
**问题描述 / Problem Description**
一个自我认知的lora简单测试， 用的是llama efficient tuning项目代码，在llama efficient tuning项目中测试时候是没有问题的。 导入chatchat项目时候，就出现了图上的情况 ，模型丧失能力，就像单纯的使用了lora 而不是chatglm+lora。

**复现问题的步骤 / Steps to Reproduce**
完全按照wiki建议步骤：
1.将config.json文件修改为adapter_config.json;
2保证文件夹包含pytorch_model.bin文件；
3修改文件夹名称，保证文件夹包含'peft'一词；
4将peft文件夹移入项目目录下；
5确保adapter_config.json文件夹中base_model_name_or_path指向基础模型；
6将peft路径添加到model_config.py的llm_dict中，键为模型名，值为peft路径；
7开启 PEFT_SHARE_BASE_WEIGHTS=true环境变量，再执行python startup.py -a
8针对p-tuning和chatglm模型，需要对fastchat进行较大幅度的修改。

**实际结果 / Actual Result**
导入可以正常导入，但是效果出现错误。

**环境信息 / Environment Information**
-langchain-chatchat 0.2.6
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： ChatGLM2-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:win 10
- Python 版本 / Python version:3.10.13  
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
运行图如下，
![Uploading 8cff0d64-e94f-44b2-99ac-45d4f383108a.jpg…]()

**Comment by hzg0601** [comment]
如果确实有需求，就把lora文件、正确输出的测试脚本、正确和错误输出的示例，打包发给我，hzg0601@163.com

**Comment by hzg0601** [comment]
都试了什么方法？这个问题需要修改fastchat的源码？这个方法试过吗

**Comment by yaospacetim** [comment]
> 都试了什么方法？这个问题需要修改fastchat的源码？这个方法试过吗

就是调用后会很奇怪，要嘛就是完全没响应，要嘛就是乱响应，和正常的微调导出后的模型调用完全不一样了。

**Comment by Astrallee** [comment]
> 如果确实有需求，就把lora文件、正确输出的测试脚本、正确和错误输出的示例，打包发给我，[hzg0601@163.com](mailto:hzg0601@163.com)

补充一哈后续成功运行的方案。 在chatglm2-6b-32k上面用的是非peft方式导入的lora,该方法没有修改fastchat源码，这个会出错。 但是同样的方法，我导入了qwen-7b ，运行没有错误。 所以觉得方法没有错，只是chatglm2-6b-32k该模型可能不适合这个方法。
