### ISSUE TITLE
[BUG]对话模式为知识库问答，在知识库配置中请选择知识库置灰

### ISSUE THREAD

**Issue by Gsl-Work** [chatchat-space/Langchain-Chatchat#1879]
**问题描述 / Problem Description**
选择对话模式为知识库问题，在下面的知识库配置中请选择知识库置灰，无法选择
知识库管理中依据源文件重建向量库报错： "POST /llm_model/get_model_config HTTP/1.1" 422 Unprocessable Entity

**复现问题的步骤 / Steps to Reproduce**
按照安装步骤进行部署

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.6
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型：m3e-base 
- 使用的向量库类型：faiss / milvus / pg_vector 
- 操作系统及版本 / Operating system and version:win11
- Python 版本 / Python version:3.10

**Comment by zRzRzRzRzRzRzR** [comment]
没有初始化知识库吧
