### ISSUE TITLE
TypeError: The type of ChatGLM.callback_manager differs from the new default value; if you wish to change the type of this field, please use a type annotation

### ISSUE THREAD

**Issue by gsshawn** [chatchat-space/Langchain-Chatchat#188]
Mac 运行    python3 ./webui.py 报 TypeError: The type of ChatGLM.callback_manager differs from the new default value; if you wish to change the type of this field, please use a type annotation

**Comment by gsshawn** [comment]
工程是最新的，模型应该没有下载到本地，这个我下载模型后再试试吧

**Comment by gsshawn** [comment]
模型下载了，也按照Q9的提示修改了对应的路径，但启动程序还是报同样的问题。

**Comment by juanerxiaokeai** [comment]
更新pydantic包试试
