### ISSUE TITLE
[BUG] 按照流程部署，一键启动后报错ValueError: '' is not in list

### ISSUE THREAD

**Issue by LiKe-rm** [chatchat-space/Langchain-Chatchat#1881]
**问题描述 / Problem Description**
按照流程部署，一键启动后报错
File "/home/jovyan/.python_libs/conda_env/chat/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "/home/jovyan/work/Langchain-Chatchat/webui.py", line 60, in <module>
    pages[selected_page]["func"](api)
File "/home/jovyan/work/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 110, in dialogue_page
    index = llm_models.index(st.session_state.get("cur_llm_model", get_default_llm_model(api)[0]))

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72687314/90f418a1-a0f1-4a5f-a4d0-2fcff31e58b6)

**Comment by LiKe-rm** [comment]
莫得

**Comment by 202030481266** [comment]
网络问题，建议把网络的代理关掉就好了。

**Comment by LiKe-rm** [comment]
> 网络问题，建议把网络的代理关掉就好了。

可是在服务器上部署的，只能通过端口转发用webui丫

**Comment by LiKe-rm** [comment]
你说得对，在运行startup.py脚本的终端先运行下面三条指令取消代理设置就行了
unset http_proxy
unset https_proxy
unset no_proxy

**Comment by kangchch** [comment]
我是租的阿里云服务器，没设置过代理，跟这个代理有关系么？

**Comment by Nendo02** [comment]
同遇到了这个问题  我是在local部署的

**Comment by LiKe-rm** [comment]
> 我是租的阿里云服务器，没设置过代理，跟这个代理有关系么？

你可以截个图看看，我这边是no_proxy的设置导致的问题

**Comment by yutianchen666** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/pull/1838 应该是这个问题，proxy设置有一个bug

**Comment by LiKe-rm** [comment]
保持model_config.py中的EMBEDDING_DEVICE和LLM_DEVICE为auto，会把模型加载的cpu和内存里，该为cuda后又变成这样的报错了。。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72687314/a013b47b-d7d8-468e-be2c-d6a266c844ce)

**Comment by LiKe-rm** [comment]
有大佬提pr解决了，参考下图
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/72687314/3cfd694b-5428-4b34-90ac-9d07f7429572)

**Comment by LiKe-rm** [comment]
> 保持model_config.py中的EMBEDDING_DEVICE和LLM_DEVICE为auto，会把模型加载的cpu和内存里，该为cuda后又变成这样的报错了。。 ![image](https://user-images.githubusercontent.com/72687314/278586830-a013b47b-d7d8-468e-be2c-d6a266c844ce.png)

记录一下，加载到cpu的原因不是因为auto，而是torch、cuda版本不适配。。。

**Comment by Hzzhang-nlp** [comment]
> 我也碰到这个问题了，解决了么？

请问现在解决了吗？

**Comment by Hzzhang-nlp** [comment]
> **问题描述 / Problem Description** 按照流程部署，一键启动后报错 File "/home/jovyan/.python_libs/conda_env/chat/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script exec(code, module.**dict**) File "/home/jovyan/work/Langchain-Chatchat/webui.py", line 60, in pages[selected_page]["func"](api) File "/home/jovyan/work/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 110, in dialogue_page index = llm_models.index(st.session_state.get("cur_llm_model", get_default_llm_model(api)[0]))
> 
> ![image](https://user-images.githubusercontent.com/72687314/278283634-90f418a1-a0f1-4a5f-a4d0-2fcff31e58b6.png)

请问现在解决了吗？

**Comment by Hzzhang-nlp** [comment]
> 有大佬提pr解决了，参考下图 ![image](https://user-images.githubusercontent.com/72687314/278602171-3cfd694b-5428-4b34-90ac-9d07f7429572.png)

按照你给的方式修改了，但是不行

**Comment by Hzzhang-nlp** [comment]
> 网络问题，建议把网络的代理关掉就好了。

关了，重新启动页面webui也不行

**Comment by Hzzhang-nlp** [comment]
> 你说得对，在运行startup.py脚本的终端先运行下面三条指令取消代理设置就行了 unset http_proxy unset https_proxy unset no_proxy

没用

**Comment by Hzzhang-nlp** [comment]
> 网络问题，建议把网络的代理关掉就好了。

没用

**Comment by AlvinAi96** [comment]
> > 网络问题，建议把网络的代理关掉就好了。
> 
> 没用

你解决了吗？我也遇到相同问题。

**Comment by LiKe-rm** [comment]
> > 有大佬提pr解决了，参考下图 ![image](https://user-images.githubusercontent.com/72687314/278602171-3cfd694b-5428-4b34-90ac-9d07f7429572.png)
> 
> 按照你给的方式修改了，但是不行

我这边是可以的，你修改之后还是原来的报错吗

**Comment by AlvinAi96** [comment]
> 的，你修改之后还是原来的报错吗

嗯嗯，我这边按pr修改了，还是不行。

**Comment by fgggit** [comment]
> > 保持model_config.py中的EMBEDDING_DEVICE和LLM_DEVICE为auto，会把模型加载的cpu和内存里，该为cuda后又变成这样的报错了。。 ![image](https://user-images.githubusercontent.com/72687314/278586830-a013b47b-d7d8-468e-be2c-d6a266c844ce.png)
> 
> 记录一下，加载到cpu的原因不是因为auto，而是torch、cuda版本不适配。。。

torch和cuda版本不匹配的问题，非常坑人。到底什么是“匹配”的，这个问题并不好回答。我参考官网给出的[对照表](https://pytorch.org/get-started/previous-versions/)来安装的，即使匹配了还是会提示这个问题

**Comment by billhan16** [comment]
> 我是租的阿里云服务器，没设置过代理，跟这个代理有关系么？

请问解决了吗，我也遇到这个问题了

**Comment by sxy2069** [comment]
> > > 有大佬提pr解决了，参考下图 ![image](https://user-images.githubusercontent.com/72687314/278602171-3cfd694b-5428-4b34-90ac-9d07f7429572.png)
> > 
> > 
> > 按照你给的方式修改了，但是不行
> 
> 我这边是可以的，你修改之后还是原来的报错吗

我按照这个你们说的修改了，仍然报同样的错误

**Comment by sxy2069** [comment]
![Uploading image.png…]()

**Comment by sxy2069** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/19299869/27fbc034-524b-4d55-bdcb-a6b18e2a315c)

**Comment by Rmj99** [comment]
在线求助大佬：
 ```TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method```
