### ISSUE TITLE
[FEATURE] 希望增加无模型精简容器镜像

### ISSUE THREAD

**Issue by sagezhj** [chatchat-space/Langchain-Chatchat#1882]
**功能描述 / Feature Description**
建议增加无内置模型的精简容器镜像

**解决的问题 / Problem Solved**
对本地已有模型文件的情况，减少镜像下载、更新时间，现在的35G实在太大了

**实现建议 / Implementation Suggestions**
删除容器镜像里的模型，并增加自定义模型映射目录

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
如果可以，希望增加latest版本，以及可以发布到hub.docker.com上一份

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.7版本开始提供非本地模型的lite镜像，但是你提到的无模型的话可能要涉及到模型配置，我们会加以考虑

**Comment by nathubs** [comment]
不错的建议，可以考虑也把配置目录config添加到映射目录
