### ISSUE TITLE
[BUG] 0.26有BUG 模型加载完成后无法拉起服务

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#1887]
**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）： 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：百川2、书生等多个开源大模型
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 或者其他Embedding模型
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:Centos 7
- Python 版本 / Python version:3.10

使用requirements.txt里的环境模型都无法拉起，将transformer降级为4.33后模型可以拉起，但是chatchat服务无法正常启动
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/4d270bb6-dd43-4cd4-8161-347bb5b8441b)
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/d01a7034-e7df-46b0-8df8-e550c9e9fa33)

**Comment by zRzRzRzRzRzRzR** [comment]
如果使用最新的Transformer，模型配置文件需要升级，以GLM为例，最新的模型配置文件是两周前的文件，应该更新模型的配置文件
降级Transformers也是一个解决方案。

**Comment by tanglu86** [comment]
> 如果使用最新的Transformer，模型配置文件需要升级，以GLM为例，最新的模型配置文件是两周前的文件，应该更新模型的配置文件 降级Transformers也是一个解决方案。

降级transformer后还有图片上的问题  控制台输出没有太有用的错误信息

**Comment by zRzRzRzRzRzRzR** [comment]
这个无所谓的，能正常使用

**Comment by tanglu86** [comment]
> 这个无所谓的，能正常使用

不行呢，服务是没有起来的 8501这些端口全部没有监听

**Comment by 18575062745** [comment]
> > 这个无所谓的，能正常使用
> 
> 不行呢，服务是没有起来的 8501这些端口全部没有监听

貌似是网络的问题，我换了个airport就没有报错了
