### ISSUE TITLE
点击“从知识库中删除”或者“依据源文件重新构建向量库”陷入死循环

### ISSUE THREAD

**Issue by Ewillingfly** [chatchat-space/Langchain-Chatchat#1890]
如题目，点击这些按钮后页面陷入死循环，这时只可以点击其他按钮才能打断循环怀疑是前端库的问题，版本如下：
streamlit                     1.28.0
streamlit-aggrid              0.3.4.post3
streamlit-antd-components     0.2.3
streamlit-chatbox             1.1.10
streamlit-option-menu         0.3.6

**Comment by Gary2018X** [comment]
+1 清除历史也陷入死循环

**Comment by szdengdi** [comment]
解决办法：
server/knowledge_base/kb_doc_api.py的372行
"finished": i
改为
"finished": (i+1)

**Comment by Ewillingfly** [comment]
> 解决办法： server/knowledge_base/kb_doc_api.py的372行 "finished": i 改为 "finished": (i+1)

似乎没有起作用

**Comment by Awyshw** [comment]
是否是streamlit版本问题，1.28.0 回退到1.26.0 是否可行？

**Comment by cspung** [comment]
> 是否是streamlit版本问题，1.28.0 回退到1.26.0 是否可行？

试了一下，回退到1.26.0正常了。感谢
