### ISSUE TITLE
[BUG] 知识库管理-依据源文件重建向量库，UI会不停刷

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1898]
**问题描述 / Problem Description**
知识库管理-依据源文件重建向量库，如果文件加载成一行，在“依据源文件”重建向量库时，UI会不停刷

解决办法：
server/knowledge_base/kb_doc_api.py的372行
"finished": i
改为
"finished": (i+1)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.26
- 操作系统及版本 / Operating system and version:ubuntu 22.04
- Python 版本 / Python version:3.10.12

**Comment by zRzRzRzRzRzRzR** [comment]
已经审查，感谢建议

**Comment by lifengyu2005** [comment]
改了没效果，问题还在

**Comment by cspung** [comment]
试了一下，streamlit版本由1.28.0 回退到1.26.0后就正常了
