### ISSUE TITLE
Not Enough Memory

### ISSUE THREAD

**Issue by PrefreeLiu** [chatchat-space/Langchain-Chatchat#190]
运行命令行程序python cli_demo.py， 已经成功加载pdf文件, 报“DefaultCPUAllocator: not enough memory: you tried to allocate 458288380900 bytes”错误，请问哪里可以配置default memory

Compiling kernels : C:\Users\liupe\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\e02ba894cf18f3fd9b2526c795f983683c4ec732\quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 C:\Users\liupe\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\e02ba894cf18f3fd9b2526c795f983683c4ec732\quantization_kernels_parallel.c -shared -o C:\Users\liupe\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\e02ba894cf18f3fd9b2526c795f983683c4ec732\quantization_kernels_parallel.so
Load kernel : C:\Users\liupe\.cache\huggingface\modules\transformers_modules\THUDM\chatglm-6b-int4\e02ba894cf18f3fd9b2526c795f983683c4ec732\quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 8
Using quantization cache
Applying quantization to glm layers
No sentence-transformers model found with name C:\Users\L/.cache\torch\sentence_transformers\GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
Input your local knowledge file path 请输入本地知识文件路径：D:\Downloads\Documents\Test.pdf
detectron2 is not installed. Cannot use the hi_res partitioning strategy. Falling back to partitioning with the fast strategy.
test.pdf 已成功加载
Input your question 请输入问题：如何提取User信息
Input length of input_ids is 338485, but `max_length` is set to 10000. This can lead to unexpected behavior. You should consider increasing `max_new_tokens`.

**RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 458288380900 bytes.**

**Comment by zRzRzRzRzRzRzR** [comment]
可以更新到最新代码尝试，如遇到问题可以重新打开issue
