### ISSUE TITLE
[BUG] docx加载成非结构化数据，知识库召回准确率低

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1901]
**问题描述 / Problem Description**
 docx默认是非结构化数据加载器，知识库召回准确率低

修改server/knowledge_base/utils.py的LOADER_DICT
<img width="542" alt="d48f1629d679ebf22c72928a54fa9f4f_" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/134568594/90af3215-5b65-4d32-8ce8-1a819f77b1c6">
1、 "UnstructuredFileLoader":，删'.docx'
2、增加"Docx2txtLoader": ['.docx'],
3、pip install Docx2txtLoader

改为txt加载

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.26
- 是否使用 Docker 部署（是/否）：No
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: 3.10.12

**Comment by zRzRzRzRzRzRzR** [comment]
这个是我们用默认的lodader，实际上都应该自己对分词进行编排，这个只是能读入，不是能实际使用的
因此，通常来说，需要设计自己的读取文件的格式，自己设计分词器来实现更好效果

**Comment by szdengdi** [comment]
建议优化一下LOADER_DICT的配置，一大堆格式都UnstructuredFileLoader，会大大影响装载的效果，最后向量库的召回效果很差。
况且改Docx2txtLoader，效果会大大改善。

**Comment by FelixZhang7** [comment]
> 建议优化一下LOADER_DICT的配置，一大堆格式都UnstructuredFileLoader，会大大影响装载的效果，最后向量库的召回效果很差。 况且改Docx2txtLoader，效果会大大改善。

请问在使用spliter的时候可以动态设吗，比如txt文档使用ChineseRecursiveTextSplitter，.md的文档使用MarkdownHeaderTextSplitter？

**Comment by FelixZhang7** [comment]
> 请问在使用spliter的时候可以动态设吗，比如txt文档使用ChineseRecursiveTextSplitter，.md的文档使用MarkdownHeaderTextSplitter？

请问在使用spliter的时候可以动态设吗，比如txt文档使用ChineseRecursiveTextSplitter，.md的文档使用MarkdownHeaderTextSplitter？

**Comment by zRzRzRzRzRzRzR** [comment]
MarkdownHeaderTextSplitter是根据标题来确定的，不一定适合所有的文件
关于动态设置的话，我们暂时仅对csv进行了设定，我们之后将考虑设定自动检测文档并进行动态分词
