### ISSUE TITLE
[FEATURE] 建议知识库做成多选，可以同时在多个知识库进行检索

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#1908]
**功能描述 / Feature Description**
目前知识库是单选，很多场景需要多个知识库进行检索。
建议知识库做成多选，可以同时在多个知识库进行检索。

**解决的问题 / Problem Solved**
多知识库检索增强生成

**实现建议 / Implementation Suggestions**
WebUI知识库多选，多选后，同时检索多个知识库。

**Comment by yubeier** [comment]
+1

**Comment by zRzRzRzRzRzRzR** [comment]
那为什么不直接都放到一个知识库呢？
或者使用Agent版本，能自动切换多个知识库

**Comment by szdengdi** [comment]
企业里面会有多个部门、多个知识库，经常会需要多知识库、多领域交叉。

**Comment by ShinyWey** [comment]
> 企业里面会有多个部门、多个知识库，经常会需要多知识库、多领域交叉。

+1

**Comment by cptbaker233** [comment]
> 那为什么不直接都放到一个知识库呢？ 或者使用Agent版本，能自动切换多个知识库

请问我们可以自己修改代码支持多选知识库吗, 实际业务场景会涉及到多种数据库的排列组合, 一个大的知识库可能无法满足数据隔离要求, 如果是按照所有需求排列组合需要创建的知识库组合可能会有无数种, 没有实用价值

**Comment by flyysoul** [comment]
> > 那为什么不直接都放到一个知识库呢？ 或者使用Agent版本，能自动切换多个知识库
> 
> 请问我们可以自己修改代码支持多选知识库吗, 实际业务场景会涉及到多种数据库的排列组合, 一个大的知识库可能无法满足数据隔离要求, 如果是按照所有需求排列组合需要创建的知识库组合可能会有无数种, 没有实用价值

目测是可以的，我们也有这块需求，最近也在研究（不过还没动手），看了下代码最麻烦一种方式就是继承底层langchain的向量存储类（比如我们用的是pg向量库，重写PGVector）修改查询参数，但是查询完之后组织成的context也要做调整，然后还有一种不麻烦但是很暴力的方式就是查几个库就调几次search_doc；🤣
我们还有个比较麻烦的要求就是，多个知识库的检索权重占比不一样，目前还不知道怎么实现/(ㄒoㄒ)/~~
