### ISSUE TITLE
参与开发问题

### ISSUE THREAD

**Issue by zqt996** [chatchat-space/Langchain-Chatchat#191]
1.是否需要进专门的开发群
2.还是提交分支

**Comment by imClumsyPanda** [comment]
可以先进群聊之后加我微信

zqt996 ***@***.***>于2023年4月27日 周四15:44写道：

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
