### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by cbw7172002** [chatchat-space/Langchain-Chatchat#1910]
**问题描述 / Problem Description**
python 311 运行
.\python_embeded\python.exe -s Langchain-Chatchat-0.2.5/server/llm_api.py

Langchain-Chatchat-0.2.5\Langchain-Chatchat-0.2.5\server\llm_api.py", line 2, in <module>
    from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT
ImportError: cannot import name 'logger' from 'configs' (D:\Langchain-Chatchat-0.2.5\python_embeded\Lib\site-packages\configs\__init__.py)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.6，另外，我们目前只能保证python3.10能运行

**Comment by LeereYu** [comment]
python 311 运行
.\python_embeded\python.exe -s Langchain-Chatchat-0.2.5/server/llm_api.py

> 更新到0.2.6，另外，我们目前只能保证python3.10能运行

项目更新到了v0.2.6，python3.10，一样的问题

**Comment by LeereYu** [comment]
Traceback (most recent call last):
  File "C:\Users\30889\Langchain-Chatchat\server\llm_api.py", line 2, in <module>
    from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT,LANGCHAIN_LLM_MODEL
ModuleNotFoundError: No module named 'configs'
