### ISSUE TITLE
[BUG] ValueError: `inject_adapter_in_model` does not support None yet. Please use `get_peft_model`.

### ISSUE THREAD

**Issue by mingkai0319** [chatchat-space/Langchain-Chatchat#1912]
**问题描述 / Problem Description**
按照最佳实践步骤加载LLaMA-Factory项目lora微调导出的模型过程中报错， 

File "C:\Programing\Miniconda\envs\chatchat\lib\site-packages\peft\mapping.py", line 127, in inject_adapter_in_model
2023-10-29 18:22:32 | ERROR | stderr |     raise ValueError(
2023-10-29 18:22:32 | ERROR | stderr | ValueError: `inject_adapter_in_model` does not support None yet. Please use `get_peft_model`.

**复现问题的步骤 / Steps to Reproduce**
1. 按照最佳实践步骤操作，其中第一步如果将config.json文件修改为adapter_config.json，会报错
OSError: peft_TEST\Qwen-7B-TEST does not appear to have a file named config.json. Checkout 'https://huggingface.co/peft_TEST\Qwen-7B-TEST/None' for available files.

2.如果保留config.json及adapter_config.json会进入checkpoint加载并报标题中的错误
ValueError: `inject_adapter_in_model` does not support None yet. Please use `get_peft_model`.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.6
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-7B-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:win10
- Python 版本 / Python version:3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by yaospacetim** [comment]
不用改那个，将里面的路径指向原本大模型路径即可

**Comment by mingkai0319** [comment]
> 不用改那个，将里面的路径指向原本大模型路径即可
是指向原本的没错

**Comment by yaospacetim** [comment]
我的意思是不用改大模型里面的 config.json ，作者在说明里描述得模棱两可，所以有可能会有人误以为要改大模型的 config.json

**Comment by zRzRzRzRzRzRzR** [comment]
指向原本的路径，然后再startup或者server config加上你的带有peft微调路径即可

**Comment by mingkai0319** [comment]
> 指向原本的路径，然后再startup或者server config加上你的带有peft微调路径即可

请问server config里面在哪里添加peft微调路径

**Comment by yaospacetim** [comment]
> > 指向原本的路径，然后再startup或者server config加上你的带有peft微调路径即可
> 
> 请问server config里面在哪里添加peft微调路径

其实就是 llm_model 那里，技术人员描述容易惜字如金，说明白一个事就可以了。

**Comment by zyren123** [comment]
> 我的意思是不用改大模型里面的 config.json ，作者在说明里描述得模棱两可，所以有可能会有人误以为要改大模型的 config.json
能详细解答一下吗。。。看的模棱两可
