### ISSUE TITLE
[BUG] chatglm2-6b-int4量化模型加载报错

### ISSUE THREAD

**Issue by xushan666** [chatchat-space/Langchain-Chatchat#1915]
**问题描述 / Problem Description**
chatglm2-6b-int4量化模型加载报错

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/133193158/cb8a439b-c347-4fb9-8cc7-6d2e9d9b2d27)

**Comment by hzg0601** [comment]
chatglm的量化模块代码在这里写的兼容性有问题，请移步THUDM反馈
