### ISSUE TITLE
[BUG] 简洁阐述问题 / 0.17版本调用百川2-13，聊天报错

### ISSUE THREAD

**Issue by qutcat1997** [chatchat-space/Langchain-Chatchat#1916]
![ba98798ef51a58d52e2994716f48054](https://github.com/chatchat-space/Langchain-Chatchat/assets/54978665/0d82e488-8335-4d4f-8f57-0f957717cd7c)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新版本，0.1.x版本不维护了
