### ISSUE TITLE
有没有一种方案能解决知识库和自定义agent同对话模式提问呢？

### ISSUE THREAD

**Issue by staticTao** [chatchat-space/Langchain-Chatchat#1927]
**功能描述 / Feature Description**
一个对话模式中包含知识库和自定义agent的提问

**解决的问题 / Problem Solved**
解决工具使用会调用到知识库的内容

**Comment by yhfgyyf** [comment]
可以试下，自定义agent里把autogen代理封装成函数，autogen里调用知识库api

**Comment by staticTao** [comment]
之前试过，但是分不清知识库得描述词。知识库的描述词应该是 xx的作用/意义/概念（这是名词的搭配）。工具就是 用/获取/给/xxx做xxx（这是动词+行为意图）。知识库这个描述太过于泛化。不太知道怎么做。

**Comment by zRzRzRzRzRzRzR** [comment]
我们是有这功能的，调用知识库的api
