### ISSUE TITLE
[BUG] python init_database.py --recreate-vs提示sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

### ISSUE THREAD

**Issue by jason3000** [chatchat-space/Langchain-Chatchat#1930]
**问题描述 / Problem Description**
python init_database.py --recreate-vs提示sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

**复现问题的步骤 总是必现
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked

**预期的结果 / Expected Result**
描述应该出现的结果 / 成功

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
Langchain-Chatchat-0.2.6 vipython init_database.py --recreate-vs
/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/home/workspace/linlj/lc-chatglm/Langchain-Chatchat-0.2.6/init_database.py", line 80, in <module>
    reset_tables()
  File "/mnt/home/workspace/linlj/lc-chatglm/Langchain-Chatchat-0.2.6/server/knowledge_base/migrate.py", line 19, in reset_tables
    Base.metadata.drop_all(bind=engine)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5820, in drop_all
    bind._run_ddl_visitor(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3239, in _run_ddl_visitor
    conn._run_ddl_visitor(visitorcallable, element, **kwargs)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 1078, in visit_metadata
    self.traverse_single(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single
    return meth(obj, **kw)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 1145, in visit_table
    DropTable(table)._invoke_with(self.connection)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with
    return bind.execute(self)
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute
    return meth(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl
    ret = self._execute_context(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context
    return self._exec_single_context(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context
    self._handle_dbapi_exception(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL:
DROP TABLE file_doc]

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  Linux
- Python 版本 / Python version:   3.10.9
- 其他相关环境信息  4块A30 但是只使用1块

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / 运行

**Comment by zRzRzRzRzRzRzR** [comment]
代码权限被受到限制了估计

**Comment by zRzRzRzRzRzRzR** [comment]
如果你是dev版本，应该python init_database.py --create-tables
在python init_database.py -r

**Comment by wzhty86** [comment]
> **问题描述 / Problem Description** python init_database.py --recreate-vs提示sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
> 
> **复现问题的步骤 总是必现
> 
> 1. 执行 '...' / Run '...'
> 2. 点击 '...' / Click '...'
> 3. 滚动到 '...' / Scroll to '...'
> 4. 问题出现 / Problem occurs  sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
> 
> **预期的结果 / Expected Result** 描述应该出现的结果 / 成功
> 
> **实际结果 / Actual Result** 描述实际发生的结果 / Describe the actual result. Langchain-Chatchat-0.2.6 vipython init_database.py --recreate-vs /mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/torch/cuda/**init**.py:138: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.) return torch._C._cuda_getDeviceCount() > 0 Traceback (most recent call last): File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context self.dialect.do_execute( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute cursor.execute(statement, parameters) sqlite3.OperationalError: database is locked
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "/mnt/home/workspace/linlj/lc-chatglm/Langchain-Chatchat-0.2.6/init_database.py", line 80, in reset_tables() File "/mnt/home/workspace/linlj/lc-chatglm/Langchain-Chatchat-0.2.6/server/knowledge_base/migrate.py", line 19, in reset_tables Base.metadata.drop_all(bind=engine) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/schema.py", line 5820, in drop_all bind._run_ddl_visitor( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3239, in _run_ddl_visitor conn._run_ddl_visitor(visitorcallable, element, **kwargs) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2443, in _run_ddl_visitor visitorcallable(self.dialect, self, **kwargs).traverse_single(element) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single return meth(obj, **kw) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 1078, in visit_metadata self.traverse_single( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 670, in traverse_single return meth(obj, **kw) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 1145, in visit_table DropTable(table)._invoke_with(self.connection) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 315, in _invoke_with return bind.execute(self) File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1412, in execute return meth( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection return connection._execute_ddl( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1524, in _execute_ddl ret = self._execute_context( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1844, in _execute_context return self._exec_single_context( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1984, in _exec_single_context self._handle_dbapi_exception( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception raise sqlalchemy_exception.with_traceback(exc_info[2]) from e File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context self.dialect.do_execute( File "/mnt/home/workspace/linlj/chatchat/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute cursor.execute(statement, parameters) sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: DROP TABLE file_doc]
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
> * 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
> * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> * 操作系统及版本 / Operating system and version:  Linux
> * Python 版本 / Python version:   3.10.9
> * 其他相关环境信息  4块A30 但是只使用1块
> 
> **附加信息 / Additional Information** 添加与问题相关的任何其他信息 / 运行


这个问题最后是怎么解决的呢？能贴下方案吗

**Comment by wzhty86** [comment]
> 如果你是dev版本，应该python init_database.py --create-tables 在python init_database.py -r

我的项目版本是"v0.2.8"，在执行"python init_database.py --recreate-vs"时，也出现了类似的报错
