### ISSUE TITLE
[BUG]执行依据源文件重建向量库，文件反复build

### ISSUE THREAD

**Issue by acer88boy** [chatchat-space/Langchain-Chatchat#1934]
**问题描述 / 当执行依据源文件重建向量库的时候，同一文件反馈被读取没有中止**
![1122](https://github.com/chatchat-space/Langchain-Chatchat/assets/121653562/5d71b615-4c19-4b20-a14b-482db530fe10)

**问题描述 / 当执行依据源文件重建向量库的时候，同一文件反馈被读取没有中止**

**Comment by acer88boy** [comment]
![Uploading 1121.png…]()

**Comment by tommy3266** [comment]
是的额，我也遇到了同样的问题，当时是页面刷新了一次，在看后台log才停止

**Comment by zRzRzRzRzRzRzR** [comment]
现在这个问题还有么，更新0.2.7代码
