### ISSUE TITLE
from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT,LANGCHAIN_LLM_MODEL ModuleNotFoundError: No module named 'configs'

### ISSUE THREAD

**Issue by Hzzhang-nlp** [chatchat-space/Langchain-Chatchat#1936]
**python3 server/llm_api.py**
报错    from configs import logger, log_verbose, LLM_MODEL, HTTPX_DEFAULT_TIMEOUT,LANGCHAIN_LLM_MODEL
ModuleNotFoundError: No module named 'configs'.

“python3 init_database.py --recreate-vs”可以正常启动，里面也有from configs，但是没报错

**Comment by zRzRzRzRzRzRzR** [comment]
启动方式不对，请看wiki中的启动方式
