### ISSUE TITLE
[BUG] Chatglm3回答问题，生成很多不想干的内容round1,round2...

### ISSUE THREAD

**Issue by highroom** [chatchat-space/Langchain-Chatchat#1938]
使用了最新的chatglm3模型，在chat模式下问问题，很容易就出现问题，用原模型的web_demo就没这样的问题
![f58d021f6dc229234735c1cef0d0b81](https://github.com/chatchat-space/Langchain-Chatchat/assets/5362883/fd534db9-3a84-445b-9f4b-9e851552975e)

**Comment by WilliamChen-luckbob** [comment]
感觉十有八九就是LLM抽风了，跟框架可能没多大关系，你可以看一下你的配置中的prompt设定
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58684828/0c5d8530-5803-4c4b-be0e-367b2f354b22)
个人感觉，LLM的数据集能用大点用大点，比如14B的

**Comment by highroom** [comment]
反复验证了很多次，用原生的代码跑就没有问题，你用langchain-Chatchat就有问题，看了下日志会提示chain finished. 不知道是不是默认agent设置有问题？还是可能是fschat的框架调用模型有问题？

**Comment by kangchch** [comment]
用原生的代码跑，指的是什么原生的代码？

**Comment by ZamboLin** [comment]
因为prompt的定义不一样？

**Comment by highroom** [comment]
> 用原生的代码跑，指的是什么原生的代码？

https://github.com/THUDM/ChatGLM3 下的web_demo.py来跑就没问题

**Comment by AI-HR** [comment]
我也遇到类似的问题，输出的文本会带有prompt中的内容

**Comment by zhaofangtao** [comment]
一样，这种错乱很频繁。

**Comment by CaptainJi** [comment]
我也发现了，会出现多轮次的对话，而且不是用户输入的内容。估计得等fschat来修复了吧

**Comment by tjlcast** [comment]
同样遇到了这个问题。请问这个问题有新的更新了吗

**Comment by zRzRzRzRzRzRzR** [comment]
适配的问题，fschat没有适配glm3，如果你们没有手动在fschat适配对话，会出现这个问题的

**Comment by tjlcast** [comment]
了解了，非常感谢
----- 原始邮件 -----
发件人：zR ***@***.***>
收件人：chatchat-space/Langchain-Chatchat ***@***.***>
抄送人：tjlcast ***@***.***>,  Comment ***@***.***>
主题：Re:_[chatchat-space/Langchain-Chatchat]_[BUG]_Chatglm3回答问题，生成很多不想干的内容round1,round2..._(Issue_#1938)
日期：2023年11月07日 13点56分


适配的问题，fschat没有适配glm3，如果你们没有手动在fschat适配对话，会出现这个问题的

**Comment by zRzRzRzRzRzRzR** [comment]
等fscaht支持glm3之后这个问题应该会解决，这个issue先关闭了

**Comment by leavor** [comment]
一样的问题,问它"北京颐和园",结果除了颐和园,把北京的好几个景点都介绍一遍,强行给自己加戏
