### ISSUE TITLE
[BUG] 调用init_database.py发生segfault错误

### ISSUE THREAD

**Issue by tjlcast** [chatchat-space/Langchain-Chatchat#1939]
**问题描述 / Problem Description**
本地初始化知识失败

**复现问题的步骤 / Steps to Reproduce**
使用OpenAI的Embedding(text-embedding-ada-002)
在本地mac air(10.15.7)上进行知识库初始化时`$ python init_database.py --recreate-vs`报错：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/16621867/4b3e3937-f317-4625-8d91-0d1d3127f352)

**环境信息 / Environment Information**
- langchain-ChatGLM commit 7f9592773be13a4d9cae63ec28f12b0516e68e2a 
- 是否使用 Docker 部署（是/否）：no
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：OpenAI的Embedding(text-embedding-ada-002)
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: mac air(10.15.7)
- Python 版本 / Python version: 3.8.10

**附加信息 / Additional Information**
初步定位是初始化过程中的Faiss出现问题：
在server/knowledge_base/kb_cache/faiss_cache.py:44中调用的
```
vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True)
```
 发生segfault。
我大致跟进去看了一下，运行到faiss.extra_wrappers.normalize_L2()会发生这个情况。

**Comment by tjlcast** [comment]
另外，简单做了一个模拟测试。我用下面的代码模拟faiss.extra_wrappers.normalize_L2()的调用
```
import numpy as np
import os
from typing import (
    Any,
    Callable,
    Dict,
    Iterable,
    List,
    Optional,
    Sized,
    Tuple,
    Union,
)


def dependable_faiss_import(no_avx2: Optional[bool] = None) -> Any:
    if no_avx2 is None and "FAISS_NO_AVX2" in os.environ:
        no_avx2 = bool(os.getenv("FAISS_NO_AVX2"))

    try:
        if no_avx2:
            from faiss import swigfaiss as faiss
        else:
            import faiss
    except ImportError:
        raise ImportError(
            "Could not import faiss python package. "
            "Please install it with `pip install faiss-gpu` (for CUDA supported GPU) "
            "or `pip install faiss-cpu` (depending on Python version)."
        )
    return faiss


def get_test():
    faiss = dependable_faiss_import()
    embeddings = [[0.011784054179983402, -0.026221852186162086, -0.003376350192894581]]
    vector = np.array(embeddings, dtype=np.float32)
    faiss.normalize_L2(vector)

    print("Finish started.")
```
然后在init_database.py中直接调用会`get_test()`也报segfault。
```
if __name__ == "__main__":
    get_test()
    import argparse
    .... 
```
最后是一个奇怪的现象，把init_database.py中的`from server.knowledge_base.migrate import create_tables, reset_tables, folder2db, prune_db_docs, prune_folder_files`相关代码注释调，就不再出现segfault问题。

里面工程具体机制我不太了解，还请各位大佬解惑。

**Comment by liunux4odoo** [comment]
你导入 faiss 的时候把 `no_avx2=True` 再试一下？

**Comment by guanguoliang** [comment]
> 你导入 faiss 的时候把 `no_avx2=True` 再试一下？

请问这个修改在哪里做，python新手，能指导一下吗

**Comment by tjlcast** [comment]
Hello，抱歉那么久才回复。

我的机器上应该是有avx的支持的

后来我做一些调查，我的情况是`init_database.py`运行报segment fault，大概是因为 `server.knowledge_base.migrate` 里的某些包的引入导致faiss的`faiss.normalize_L2`调用异常。

最后通过降低引入的faiss包版本，问题不再出现。在requirements.txt中设置`faiss-cpu==1.7.0`（默认没有版本）
