### ISSUE TITLE
json文件回答不清晰[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by HuMian10** [chatchat-space/Langchain-Chatchat#1942]
版本：0.2.5

问题：导入json文件数据时，模型针对提问无法正确回答

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101257078/d53cfa10-aa44-4e32-bccf-45a30df5ba52)

json格式例如:
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101257078/efbf4d2e-a3f2-4263-b600-47d61cf0c9a4)

**Comment by MrSu3364** [comment]
别说这个键值对了，我传excel或者text的整句的内容都不能正常问答

**Comment by zRzRzRzRzRzRzR** [comment]
如果相关文档没有显示，就是没搜到相关内容
