### ISSUE TITLE
[BUG] Azure支持有问题？

### ISSUE THREAD

**Issue by devillaws** [chatchat-space/Langchain-Chatchat#1945]
【问题描述】
Azure接口postman跟curl、pythontest都没有问题，但本工程报错无法使用，报错内容如下：
![2bee0fd5b5fe5eda57af6c3e2bf1368](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/61a3b524-6ca4-4310-b93f-0c86cdf55b5c)
【工程相关配置如下】
![66afe463c99cbde6784059d3c627469](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/ce106d25-19fc-43f0-b07c-01f6b81fc97e)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/20bfc6a0-d6d8-4e36-9a52-8898da317ea2)
【postman验证成功示例】
![a6c8200fcc97687f352c8777d5b95f0](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/59e36d15-0173-4ca7-a610-54b77178c3ee)

**Comment by devillaws** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/afc172e7-1c31-41b1-8627-17ec249cc54a)
最新测试，postman如果是get请求，则会报同样Resource not found的错误

**Comment by devillaws** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/6f0bcffd-66b1-47fe-ba29-2a0a4b85a855)
同理api-version不传也会

**Comment by devillaws** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/a0ae9edb-9667-4aea-8a75-91d101343871)
解决了，注意url不要带其他后缀，按图这样填即可

**Comment by Flagami** [comment]
> ![image](https://private-user-images.githubusercontent.com/8604432/279888686-a0ae9edb-9667-4aea-8a75-91d101343871.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwMzYyMTIsIm5iZiI6MTcwMzAzNTkxMiwicGF0aCI6Ii84NjA0NDMyLzI3OTg4ODY4Ni1hMGFlOWVkYi05NjY3LTRhZWEtOGE3NS05MWQxMDEzNDM4NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMDEzMTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2IwYTE1MDc1NWM2MTMzNjE2ODAzN2YzMjk1NzE2MjE5MjBmNDZmYmY1NjJmN2ZiNWY1NzgyY2M1N2EyNzI1OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.S-wXaRIVWi3axplaxKbQQAnWculzEmFtJwm_HgnINGg) 解决了，注意url不要带其他后缀，按图这样填即可

配置中的第二个参数"model_version" 可以不填么？没找到后台关于这块的信息
