### ISSUE TITLE
[BUG] 使用Qwen/Qwen-14B-Chat-Int8模型无法加载

### ISSUE THREAD

**Issue by KatUsagi** [chatchat-space/Langchain-Chatchat#1947]
【问题描述】
模型使用Qwen/Qwen-14B-Chat-Int8无法加载：
（1）在开启量化参数时（'load_8bit': True）返回 ValueError: Cannot find any model weight files. Please check your (cached) weight path: 且模型未启用gpu加载
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32010999/7cd3f85c-d173-4ed6-90b2-3f675bf4d4d6)
（2）不开启量化参数直接读取则返回必须采用 gpuRuntimeError: GPU is required to quantize or run quantize model.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32010999/e3bdc4da-8821-472e-bc78-ec98c9d58b31)

【工程相关配置】
"Qwen-7B":"/data/shujubu/aliQwen/20230912/Qwen",
"Qwen-14B-Chat":"/data/shujubu/qwen-14b-8bit/20231031上传的文件",
EMBEDDING_MODEL = "m3e-base" # 可以尝试最新的嵌入式sota模型：bge-large-zh-v1.5
EMBEDDING_DEVICE = "auto"
LLM_MODEL = "Qwen-14B-Chat"
LLM_DEVICE = "auto"

【预期的结果 】
成功加载模型

【实际结果】
未加载模型

【附加信息 】
采用[Langchain-Chatchat v0.2.1](https://github.com/chatchat-space/Langchain-Chatchat/releases/tag/v0.2.1)环境则可以加载Qwen-14B-Chat-Int8模型

**Comment by yhfgyyf** [comment]
应该是torch版本不对，都没有使用gpu加载模型，pip show torch 看下

**Comment by Leweibo** [comment]
请问量化模型的 quantize(8)函数放在哪个文件里面？
