### ISSUE TITLE
[BUG] chatglm2-6b启动卡死

### ISSUE THREAD

**Issue by dayphosphor** [chatchat-space/Langchain-Chatchat#1956]
**问题描述 / Problem Description**
直接从huggface下载的chaglm2-6b,  用langchain-chatchat最新版，再3090机器上启动，直接卡死。  

如图：
<img width="1393" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/1256403/009e4870-ca61-430b-90d8-eceea6693e10">

**Comment by zRzRzRzRzRzRzR** [comment]
检查一下内存是否正常，目前无法复现这种情况
