### ISSUE TITLE
支持chatglm3模型

### ISSUE THREAD

**Issue by sunny0315** [chatchat-space/Langchain-Chatchat#1959]
**功能描述 / Feature Description**
增加对chatglm3-6B模型的支持

**解决的问题 / Problem Solved**
从评测来看有一定的提升，使用该模型提升基于上下文的总结能力

**Comment by zRzRzRzRzRzRzR** [comment]
我们已经对其做了基础的适配，但是我们的依赖fschat还没适配

**Comment by jrd77** [comment]
同求，特别是32k长文本版本

**Comment by zzflybird** [comment]
> 我们已经对其做了基础的适配，但是我们的依赖fschat还没适配

你好，fschat已经在最新的0.2.33版本适配了chatGLM3.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26504661/89051b2c-412a-43ee-a35d-2cd44c094aa8)

我安装最新版本的fscaht后
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26504661/cd977a7e-26a4-4e27-ad88-6c6c58841c7b)

问答结果如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26504661/37547ab0-2591-42b3-8383-fea04763da69)

请问是fschat最新版本不适配的原因吗？

**Comment by ghx2757** [comment]
@zzflybird 您好，我项目版本是0.2.8，fschat版本是0.2.33，出现了同样的上述问题，我将fschat版本更改为0.2.32有所改善但是仍有自问自答的现象，请问你这个问题解决了吗？

**Comment by zzflybird** [comment]
> @zzflybird 您好，我项目版本是0.2.8，fschat版本是0.2.33，出现了同样的上述问题，我将fschat版本更改为0.2.32有所改善但是仍有自问自答的现象，请问你这个问题解决了吗？

您好，最近没有搞这个项目了，使用0.2.33的问题一直没有跟进，不知道现在是如何，解决了没有。用的0.2.32也是会有自问自答的情况，那些自问自答的猜测是训练时的问答数据，不知道怎么就输出出来了。

**Comment by ghx2757** [comment]
@zzflybird  嗯嗯呐，好的，谢谢啦，我在调研调研。
