### ISSUE TITLE
[BUG] KnowledgeBase问答Chat，answer为空，doc有值，这是怎么回事？

### ISSUE THREAD

**Issue by AlvinAi96** [chatchat-space/Langchain-Chatchat#1961]
**问题描述 / Problem Description**
KnowledgeBase问答Chat，answer为空，doc有值，这是怎么回事？

调用startup正常：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42187008/622ed5b4-da7b-4fb0-9388-0a570ecfffbb)

每次提问，会报错：KeyError: Caught exception: 'choices'，我torch=2.0.1
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42187008/002fffa4-8fc0-4514-a69e-48bcea25c48f)

提问只有引用文档，没有answer，有朋友遇到这问题吗？怎么解决？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42187008/1748003e-8668-41d5-9e3d-c3b2a882df74)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42187008/5c44ab03-617b-46e2-b9b4-11f4a8ad67af)

**Comment by renzhangzhe** [comment]
我也遇到了相同的问题， 利用http://xxxxx:7861/chat/knowledge_base_chat/ 这个接口调用，返回的answer字段为空， 但是doc有数据。我用的torch=2.1.0

**Comment by chenhongwu127** [comment]
我也遇到了相同的问题， 利用http://xxxxx:7861/chat/knowledge_base_chat/ 这个接口调用，返回的answer字段为空， 但是doc有数据。我用的torch=2.1.0

**Comment by AlvinAi96** [comment]
我用老版本解决了，0.2.3没这个问题。

**Comment by LiKe-rm** [comment]
因为文档+prompt超出了模型的最大token数吧

**Comment by LiKe-rm** [comment]
因为文档+prompt超出了模型的最大token数吧，把匹配知识条数调成1试试

**Comment by renzhangzhe** [comment]
> 我用老版本解决了，0.2.3没这个问题。

请问torch要用0.2.3版本吗？

**Comment by AlvinAi96** [comment]
> 因为文档+prompt超出了模型的最大token数吧，把匹配知识条数调成1试试

试过了，好像也不行。

**Comment by AlvinAi96** [comment]
> > 我用老版本解决了，0.2.3没这个问题。
> 
> 请问torch要用0.2.3版本吗？

改用 langchain-chachat tag 0.2.3旧版本。

**Comment by renzhangzhe** [comment]
> > > 我用老版本解决了，0.2.3没这个问题。
> > 
> > 
> > 请问torch要用0.2.3版本吗？
> 
> 改用 langchain-chachat tag 0.2.3旧版本。
OK  感谢 到时候我也试一下
