### ISSUE TITLE
在轻量模式下使用在线的通义千问API--问题

### ISSUE THREAD

**Issue by eric086** [chatchat-space/Langchain-Chatchat#1963]
单独调试 调用通义千问API 有返回
但是在webui模式下会返回
  API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

日志显示:utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新的版本，应该没有这个问题

**Comment by princeGoo** [comment]
> 单独调试 调用通义千问API 有返回 但是在webui模式下会返回 API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
> 
> 日志显示:utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

您好，请问你问他解决了吗？目前配置参数key 请求通义千问API一直报错，直接请求官网http的api是可以成功的，请问有什么需要注意地方吗？
