### ISSUE TITLE
[BUG] 删除数据库后创建同名数据库并上传文件后，知识库问答引用删除前的内容

### ISSUE THREAD

**Issue by ArtPei** [chatchat-space/Langchain-Chatchat#1964]
**问题描述 / Problem Description**
 删除数据库后创建同名数据库并上传文件后，知识库问答引用删除前的内容

**Comment by zRzRzRzRzRzRzR** [comment]
没有听懂，能按照isssue规范，并用最新的代码复现一下吗

**Comment by zRzRzRzRzRzRzR** [comment]
我在disscusion开了一个关于知识库删除问题的讨论，你看一下你的问题是否跟他相同，我看这两个issue雷同了，我关闭了
