### ISSUE TITLE
客户端请求如下：

### ISSUE THREAD

**Issue by chenhongwu127** [chatchat-space/Langchain-Chatchat#1967]
客户端请求如下：

/chat/knowledge_base_chat

{
"query": "老许入职时间是哪年?",
"knowledge_base_name": "samples",
"top_k": 3,
"history": [],
}
我这边是没有任何回复，只显示Connected to http://172.16.104.51:7861/chat/knowledge_base_chat，咋回事呢？

_Originally posted by @chenhongwu127 in https://github.com/chatchat-space/Langchain-Chatchat/issues/1194#issuecomment-1793320531_

**Comment by chenhongwu127** [comment]
客户端请求如下：

**Comment by zRzRzRzRzRzRzR** [comment]
查看知识库是否初始化
查看后台运行的时候是否有过Embed模型
