### ISSUE TITLE
0.2.6容器启动报错

### ISSUE THREAD

**Issue by marslion** [chatchat-space/Langchain-Chatchat#1972]
*0.2.6容器启动报错 *
按照readme.md文档，执行docker run .....命令，容器启动报错。请帮忙分析是什么原因？

![error](https://github.com/chatchat-space/Langchain-Chatchat/assets/8375660/908e5d9d-e7f1-494c-9afa-e08412beac10)

运行环境：suse12sp4   
python版本：3.9.16

**Comment by zRzRzRzRzRzRzR** [comment]
暂时无法提供复现，在其他地方运行没有遇到类似的错误
