### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by alanywlee** [chatchat-space/Langchain-Chatchat#1974]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
使用 0.2.6 docker container，改默認 llm model 為 0.2.3. 版所使用的 "chatglm2-6b-32k" 在使用多GPU卡的時候，無法正常使用

**复现问题的步骤 / Steps to Reproduce**

1. 修改 startup.py 
line 169: 
args.gpus = "0"
-->
args.gpus = "0,1"

line 170: 把 max_gpu_memory 改小一點，比較容易分到兩張卡
args.max_gpu_memory = "22GiB"
-->
args.max_gpu_memory = "12GiB"

line 171: 
args.num_gpus = 1
-->
args.num_gpus = 2

修改 configs/model_config.py

新增 "llm_model" 
line 45
"chatglm2-6b-32k": "THUDM/chatglm2-6b-32k",

line 100
LLM_MODEL = "chatglm2-6b"
-->
LLM_MODEL = "chatglm2-6b-32k"

重啟 docker 
/langchain-chatchat/start_service.sh

2. 直接打 api

curl -X 'POST' \
  'http://192.168.1.1:20000/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "model": "chatglm2-6b-32k",
  "messages": "hello",
  "temperature": 0.7,
  "top_p": 1,
  "n": 1,
  "max_tokens": 1000,
  "stop": "string",
  "stream": false,
  "presence_penalty": 0,
  "frequency_penalty": 0,
  "user": "string"
}'

4. 问题出现 / Problem occurs

{
  "object": "error",
  "message": "**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1! (when checking argument for argument tensors in method wrapper_CUDA_cat))",
  "code": 50001
}

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): chatglm2-6b-32k
python版本：3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

- 其他相关环境信息 / Other relevant environment information:
操作系统：Linux-3.10.0-1160.71.1.el7.x86_64-x86_64-with-glibc2.35.
项目版本：v0.2.6
langchain版本：0.0.320. fastchat版本：0.2.31

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

console log:
2023-11-06 07:10:45,670 - utils.py[line:26] - ERROR: KeyError: Caught exception: 'choices'

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新版本看一下，0.2.3现在没有人维护

**Comment by weipeng008005** [comment]
> 更新到最新版本看一下，0.2.3现在没有人维护

您好，请问这个api请求里的n表示的是什么？
