### ISSUE TITLE
[0.2.7 pre-release] openapi 500 Internal Server Error

### ISSUE THREAD

**Issue by yangkai798** [chatchat-space/Langchain-Chatchat#1979]
pre-release branch 
python server/api.py using openai model.

<img width="921" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/33416945/334504f9-33ae-4664-a829-adb439f2a0fe">

**Comment by zRzRzRzRzRzRzR** [comment]
openai不能作为第一个启动的模型，选一个其他的切换成openai试试

**Comment by yangkai798** [comment]
> openai不能作为第一个启动的模型，选一个其他的切换成openai试试

0.2.7不会轻量化部署吗？采用都是线上API调用的方式，而不是本地部署的模型

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.7你用的轻量化版本是么，mark，我们看一下

**Comment by zRzRzRzRzRzRzR** [comment]
现在还有么

**Comment by Dorado607** [comment]
0.27正式版遇到了相同的问题0.27正式版

**Comment by yhfgyyf** [comment]
参考https://github.com/chatchat-space/Langchain-Chatchat/issues/2044#issue-1990273202 ，注销server/api.py   第89行代码#mount_knowledge_routes(app) 后bug修复

**Comment by yangkai798** [comment]
其他的Bug都修复了，现在前端显示有问题
<img width="909" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/33416945/3ef4e12e-b895-48c1-a194-aa969807bb89">

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到过，每次运行都会出现吗

**Comment by yangkai798** [comment]
已经解决了。

zR ***@***.***> 于2023年11月19日周日 11:18写道：
