### ISSUE TITLE
初始化向量数据库报错，python init_database.py --recreate-vs

### ISSUE THREAD

**Issue by terence-wu** [chatchat-space/Langchain-Chatchat#1987]
初始化向量数据库报错
执行python init_database.py --recreate-vs

报错信息
ERROR: ImportError: 从文件 samples/test.txt 加载文档时出错：libX11.so.6: cannot open shared object file: No such file or directory
('samples', 'test.txt', '从文件 samples/test.txt 加载文档时出错：libX11.so.6: cannot open shared object file: No such file or directory')
2023-11-07 16:42:20,003 - faiss_cache.py[line:20] - INFO: 已将向量库 ('samples', 'vector_store') 保存到磁盘

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki中的qa
