### ISSUE TITLE
[BUG] Exception in ASGI application

### ISSUE THREAD

**Issue by hustsunyu** [chatchat-space/Langchain-Chatchat#1988]
**问题描述 / Problem Description**
在webui界面输入提示词，一直报错。
webui上提示：API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
完整log如下：

(langchain-chatglm) D:\THUDM\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.331. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'd:\\models\\THUDM\\chatglm3-6b',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu
==============================Langchain-Chatchat Configuration==============================

2023-11-07 23:27:34,025 - startup.py[line:626] - INFO: 正在启动服务：
2023-11-07 23:27:34,025 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 D:\THUDM\Langchain-Chatchat\logs
2023-11-07 23:27:41 | ERROR | stderr | INFO:     Started server process [12080]
2023-11-07 23:27:41 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-07 23:27:41 | ERROR | stderr | INFO:     Application startup complete.
2023-11-07 23:27:41 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-11-07 23:27:42 | INFO | model_worker | Register to controller
2023-11-07 23:27:42 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 3c5f0013 ...
Loading checkpoint shards:   0%|                                                                 | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████▏                                                | 1/7 [00:19<01:57, 19.50s/it]
Loading checkpoint shards:  29%|████████████████▎                                        | 2/7 [00:39<01:39, 19.82s/it]
Loading checkpoint shards:  43%|████████████████████████▍                                | 3/7 [00:59<01:18, 19.68s/it]
Loading checkpoint shards:  57%|████████████████████████████████▌                        | 4/7 [01:18<00:58, 19.52s/it]
Loading checkpoint shards:  71%|████████████████████████████████████████▋                | 5/7 [01:38<00:39, 19.85s/it]
Loading checkpoint shards:  86%|████████████████████████████████████████████████▊        | 6/7 [01:58<00:19, 19.96s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [02:12<00:00, 17.73s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [02:12<00:00, 18.88s/it]
2023-11-07 23:29:55 | ERROR | stderr |
2023-11-07 23:29:56 | INFO | model_worker | Register to controller
INFO:     Started server process [20576]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.6
langchain版本：0.0.331. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'd:\\models\\THUDM\\chatglm3-6b',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================

  You can now view your Streamlit app in your browser.

  URL: http://127.0.0.1:8501

{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:30,390 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57009 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:30,393 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:30,799 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57009 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:30,802 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57009 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-07 23:30:30,806 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:31,103 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57009 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:31,106 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:45,696 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57036 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:45,700 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57036 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-07 23:30:45,706 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:45,962 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57036 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:45,964 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:48,114 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57047 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:48,116 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57047 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-07 23:30:48,121 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:30:48,382 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57047 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:30:48,387 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:31:07,043 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57059 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:31:07,046 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57059 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2023-11-07 23:31:07,049 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
{'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
2023-11-07 23:31:07,310 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:57059 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2023-11-07 23:31:07,312 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'max_tokens': None,
 'model_name': 'chatglm3-6b',
 'prompt_name': 'default',
 'query': '清华大学大模型有哪些',
 'stream': True,
 'temperature': 0.1}
INFO:     127.0.0.1:57059 - "POST /chat/chat HTTP/1.1" 200 OK
2023-11-07 23:31:07,323 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\fastapi\applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\routing.py", line 69, in app
    await response(scope, receive, send)
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\anyio\_backends\_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\responses.py", line 273, in wrap
    await func()
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\starlette\responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "D:\THUDM\Langchain-Chatchat\server\chat\chat.py", line 37, in chat_iterator
    model = get_ChatOpenAI(
  File "D:\THUDM\Langchain-Chatchat\server\utils.py", line 87, in get_ChatOpenAI
    model = ChatOpenAI(
  File "C:\Users\ysun\.conda\envs\langchain-chatglm\lib\site-packages\langchain\load\serializable.py", line 97, in __init__
    super().__init__(**kwargs)
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
__root__
  `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)
2023-11-07 23:31:07,442 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by chensheng06** [comment]
同问

**Comment by cl165** [comment]
同问

**Comment by hustsunyu** [comment]
看来不止我一个碰到这个问题。尝试pip install --upgrade openai，没用。

**Comment by hawcat** [comment]
> **问题描述 / Problem Description** 在webui界面输入提示词，一直报错。 webui上提示：API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read) 完整log如下：
> 
> (langchain-chatglm) D:\THUDM\Langchain-Chatchat>python startup.py -a
> 
> ==============================Langchain-Chatchat Configuration============================== 操作系统：Windows-10-10.0.19045-SP0. python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] 项目版本：v0.2.6 langchain版本：0.0.331. fastchat版本：0.2.31
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter 当前启动的LLM模型：['chatglm3-6b'] @ cpu {'device': 'cpu', 'host': '127.0.0.1', 'infer_turbo': False, 'model_path': 'd:\models\THUDM\chatglm3-6b', 'port': 20002} 当前Embbedings模型： m3e-base @ cpu ==============================Langchain-Chatchat Configuration==============================
> 
> 2023-11-07 23:27:34,025 - startup.py[line:626] - INFO: 正在启动服务： 2023-11-07 23:27:34,025 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 D:\THUDM\Langchain-Chatchat\logs 2023-11-07 23:27:41 | ERROR | stderr | INFO: Started server process [12080] 2023-11-07 23:27:41 | ERROR | stderr | INFO: Waiting for application startup. 2023-11-07 23:27:41 | ERROR | stderr | INFO: Application startup complete. 2023-11-07 23:27:41 | ERROR | stderr | INFO: Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit) 2023-11-07 23:27:42 | INFO | model_worker | Register to controller 2023-11-07 23:27:42 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 3c5f0013 ... Loading checkpoint shards: 0%| | 0/7 [00:00<?, ?it/s] Loading checkpoint shards: 14%|████████▏ | 1/7 [00:19<01:57, 19.50s/it] Loading checkpoint shards: 29%|████████████████▎ | 2/7 [00:39<01:39, 19.82s/it] Loading checkpoint shards: 43%|████████████████████████▍ | 3/7 [00:59<01:18, 19.68s/it] Loading checkpoint shards: 57%|████████████████████████████████▌ | 4/7 [01:18<00:58, 19.52s/it] Loading checkpoint shards: 71%|████████████████████████████████████████▋ | 5/7 [01:38<00:39, 19.85s/it] Loading checkpoint shards: 86%|████████████████████████████████████████████████▊ | 6/7 [01:58<00:19, 19.96s/it] Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [02:12<00:00, 17.73s/it] Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 7/7 [02:12<00:00, 18.88s/it] 2023-11-07 23:29:55 | ERROR | stderr | 2023-11-07 23:29:56 | INFO | model_worker | Register to controller INFO: Started server process [20576] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)
> 
> ==============================Langchain-Chatchat Configuration============================== 操作系统：Windows-10-10.0.19045-SP0. python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] 项目版本：v0.2.6 langchain版本：0.0.331. fastchat版本：0.2.31
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter 当前启动的LLM模型：['chatglm3-6b'] @ cpu {'device': 'cpu', 'host': '127.0.0.1', 'infer_turbo': False, 'model_path': 'd:\models\THUDM\chatglm3-6b', 'port': 20002} 当前Embbedings模型： m3e-base @ cpu
> 
> 服务端运行信息： OpenAI API Server: http://127.0.0.1:20000/v1 Chatchat API Server: http://127.0.0.1:7861 Chatchat WEBUI Server: http://127.0.0.1:8501 ==============================Langchain-Chatchat Configuration==============================
> 
> You can now view your Streamlit app in your browser.
> 
> URL: http://127.0.0.1:8501
> 
> {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:30,390 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57009 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:30,393 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:30,799 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57009 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:30,802 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57009 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK 2023-11-07 23:30:30,806 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK" {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:31,103 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57009 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:31,106 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:45,696 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57036 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:45,700 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57036 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK 2023-11-07 23:30:45,706 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK" {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:45,962 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57036 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:45,964 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:48,114 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57047 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:48,116 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57047 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK 2023-11-07 23:30:48,121 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK" {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:30:48,382 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57047 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:30:48,387 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" {'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:31:07,043 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57059 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:31:07,046 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57059 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK 2023-11-07 23:31:07,049 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK" {'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}} 2023-11-07 23:31:07,310 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK" INFO: 127.0.0.1:57059 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK 2023-11-07 23:31:07,312 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK" received input message: {'history': [], 'max_tokens': None, 'model_name': 'chatglm3-6b', 'prompt_name': 'default', 'query': '清华大学大模型有哪些', 'stream': True, 'temperature': 0.1} INFO: 127.0.0.1:57059 - "POST /chat/chat HTTP/1.1" 200 OK 2023-11-07 23:31:07,323 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/chat "HTTP/1.1 200 OK" ERROR: Exception in ASGI application Traceback (most recent call last): File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi result = await app( # type: ignore[func-returns-value] File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in **call** return await self.app(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\fastapi\applications.py", line 1106, in **call** await super().**call**(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\applications.py", line 122, in **call** await self.middleware_stack(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\errors.py", line 184, in **call** raise exc File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\errors.py", line 162, in **call** await self.app(scope, receive, _send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\exceptions.py", line 79, in **call** raise exc File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\middleware\exceptions.py", line 68, in **call** await self.app(scope, receive, sender) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in **call** raise e File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in **call** await self.app(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\routing.py", line 718, in **call** await route.handle(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\routing.py", line 276, in handle await self.app(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\routing.py", line 69, in app await response(scope, receive, send) File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\responses.py", line 270, in **call** async with anyio.create_task_group() as task_group: File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\anyio_backends_asyncio.py", line 597, in **aexit** raise exceptions[0] File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\responses.py", line 273, in wrap await func() File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\starlette\responses.py", line 262, in stream_response async for chunk in self.body_iterator: File "D:\THUDM\Langchain-Chatchat\server\chat\chat.py", line 37, in chat_iterator model = get_ChatOpenAI( File "D:\THUDM\Langchain-Chatchat\server\utils.py", line 87, in get_ChatOpenAI model = ChatOpenAI( File "C:\Users\ysun.conda\envs\langchain-chatglm\lib\site-packages\langchain\load\serializable.py", line 97, in **init** super().**init**(**kwargs) File "pydantic\main.py", line 341, in pydantic.main.BaseModel.**init** pydantic.error_wrappers.ValidationError: 1 validation error for ChatOpenAI **root** `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error) 2023-11-07 23:31:07,442 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

把openai版本从1.1换成0.28.1，昨天openai库有更新

**Comment by hawcat** [comment]
暂且的解决方法是openai库换到0.28.1，官方给的requirements是>=0.28.1，自动更新到1.1了，要兼容得等更新

**Comment by hustsunyu** [comment]
可以了，办法如下。感谢@hawcat提示。
requirements.txt修改openai行为openai~=0.28.1
pip insstall -r requirements.txt
