### ISSUE TITLE
用vue框架调用接口无法做到流式输出？

### ISSUE THREAD

**Issue by bk996smile** [chatchat-space/Langchain-Chatchat#1989]
前端vue用的是https://github.com/chatchat-space/Langchain-Chatchat/pull/659 这里的方式调用接口，参数也改成了流失，可是最后的效果还是整段完成后才能获取到文本。请问要怎么样才能做到打字机那样的流式输出？

**Comment by zRzRzRzRzRzRzR** [comment]
现在暂时还没支持vue，没有开发人员在做这方面的调试
