### ISSUE TITLE
加载本地模型时报 需要trust_model_code=True

### ISSUE THREAD

**Issue by zhanghui-china** [chatchat-space/Langchain-Chatchat#1999]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/e11d36b0-8449-4f0e-b8e6-5c10690ec174)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/a3c87fe9-ca44-4234-b43a-49f8196d4f10)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/f39344c7-010f-416b-a020-b8c70cb3e82a)

该如何处理？

OS: ubuntu 18.04 x86 

BTW:
手工代码一般是如下处理：
`from modelscope import (
    AutoModelForCausalLM, AutoTokenizer, GenerationConfig, snapshot_download
)

import torch
model_dir = '/home/zhanghui/models/Skywork/Skywork-13B-Base-8bits'

tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True, load_in_8bit_fp32_cpu_offload=True)
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="cuda:0", trust_remote_code=True).eval()

inputs = tokenizer('陕西的省会是西安', return_tensors='pt').to(model.device)
response = model.generate(inputs.input_ids, max_length=128)
print(tokenizer.decode(response.cpu()[0], skip_special_tokens=True))
#陕西的省会是西安，西安是我国著名的古都，在历史上有十三个朝代在此建都，所以西安又被称为“十三朝古都”。西安是我国著名的旅游城市，每年都有大量的游客来到西安旅游，西安的旅游资源
非常丰富，有很多著名的旅游景点，比如秦始皇兵马俑、大雁塔、华清池、大唐芙蓉园、西安城墙、大明宫国家遗址公园、西安碑林博物馆、西安钟楼、西安鼓楼、西安半坡博物馆、西安大兴善寺>、西安小雁塔^M

inputs = tokenizer('陕西的省会是西安，甘肃的省会是兰州，河南的省会是郑州', return_tensors='pt').to(model.device)
response = model.generate(inputs.input_ids, max_length=128)
print(tokenizer.decode(response.cpu()[0], skip_special_tokens=True))
#陕西的省会是西安，甘肃的省会是兰州，河南的省会是郑州，湖北的省会是武汉，湖南的省会是长沙，江西的省会是南昌，安徽的省会是合肥，江苏的省会是南京，浙江的省会是杭州，福建的省会
是福州，广东的省会是广州，广西的省会是南宁，海南的省会是海口，四川的省会是成都，贵州的省会是贵阳，云南的省会是昆明，西藏的省会是拉萨，青海的省会是西宁，宁夏的省会是银川，新>疆的省会是乌鲁木齐。`

在
tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True, load_in_8bit_fp32_cpu_offload=True)
model = AutoModelForCausalLM.from_pretrained(model_dir, device_map="cuda:0", trust_remote_code=True).eval()
都需要加 trust_remote_code=True 参数。
但是这个参数如何配置到 LangChain-ChatChat里面去？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/644f3705-a19f-4f03-a023-a77c47b44146)

**Comment by zRzRzRzRzRzRzR** [comment]
1. 本模型不不是我们现在支持的模型
2. 这个参数不是在chatchat里加的，你应该在我们的依赖fschat内源码修改，加入这个参数，可以根据报错定位库的位置并修改依赖源代码

**Comment by zhanghui-china** [comment]
现在有一些模型不支持的报错都是这个错。

比如 上面的 天工 Skywork/Skywork-13B-Base-8bits
还有 Yi：01ai/Yi-6B
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63148804/b798875b-6bbe-44d1-9eeb-387d1ba92acf)

不过我怀疑不是你们的问题，因为这两个模型都是基准模型，不是对话模型。基准模型一般只能做文本补齐。

等他们对话模型推出之后再试试。
