### ISSUE TITLE
调用lora时能否同时调用多个lora

### ISSUE THREAD

**Issue by Fraudsterrrr** [chatchat-space/Langchain-Chatchat#2001]
**功能描述 / Feature Description**
1.调用lora时能否同时调用多个lora。
2.切换相同底座的lora模型不需要重新加载底座。

**解决的问题 / Problem Solved**
1.希望同时加载多个lora根据问题权重控制它们融合在一起。
2.加快模型切换的效率。

**实现建议 / Implementation Suggestions**
看见peft已经有了相关的方法不知道能否实现在这个项目上。
https://github.com/huggingface/peft/issues/280
————————————————————
https://github.com/huggingface/peft/pull/263
————————————————————
https://github.com/lm-sys/FastChat/pull/1905

感谢！！

**Comment by zRzRzRzRzRzRzR** [comment]
多个lora建议直接合并成一个新的大模型，遇到的问题会比较少

**Comment by Fraudsterrrr** [comment]
> 多个lora建议直接合并成一个新的大模型，遇到的问题会比较少

好的，想问下第二个切换相同基座的lora模型时不重新加载基座是可以吗

**Comment by zheng5yu9** [comment]
> 新的

这个不成立吧,互相干扰了
