### ISSUE TITLE
need chatglm3-6b support

### ISSUE THREAD

**Issue by xutengfei** [chatchat-space/Langchain-Chatchat#2003]
need chatglm3-6b support

**Comment by zhanghui-china** [comment]
chatglm3-6b chatchat本来就是支持的。
[详见：](https://zhuanlan.zhihu.com/p/664029189)

**Comment by zRzRzRzRzRzRzR** [comment]
我们只支持fschat支持的模型，目前fschat还没有完全适配glm3，因此可以等fschat支持再使用

**Comment by tjlcast** [comment]
Hello, 我看[这里](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%94%AF%E6%8C%81%E5%88%97%E8%A1%A8#llm-%E6%A8%A1%E5%9E%8B%E6%94%AF%E6%8C%81%E5%88%97%E8%A1%A8)写已经支持，fschat完全适配glm3后，这边会有通知吗？
