### ISSUE TITLE
[BUG] 初始化卡住，init_database.py --recreate-vs时候DLL load failed while importing _swigfaiss_avx2: 找不到指定的模块。

### ISSUE THREAD

**Issue by Jzhnakui** [chatchat-space/Langchain-Chatchat#2004]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题：初始化卡住，init_database.py --recreate-vs时候  Could not load library with AVX2 support due to ImportError('DLL load failed while importing _swigfaiss_avx2: 找不到指定的模块。

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49728819/d119355f-1b48-44d4-96c2-e6e8c5dcc844)

我是严格按照requirements文件安装的，依次执行了readme文件中的
```
$ pip install -r requirements.txt 
$ pip install -r requirements_api.txt
$ pip install -r requirements_webui.txt  
```
**复现问题的步骤 / Steps to Reproduce**
1.执行  python  G:\Langchain-Chatchat-master\init_database.py --recreate-vs
然后：
```
(langcccglm) PS C:\Users\haoran> python  G:\Langchain-Chatchat-master\init_database.py --recreate-vs
database talbes reseted
recreating all vector stores
2023-11-10 03:24:30,585 - faiss_cache.py[line:75] - INFO: loading vector store in 'samples/vector_store' from disk.
{}
2023-11-10 03:24:30,685 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: G:\m3e-base
2023-11-10 03:24:31,815 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-11-10 03:24:31,818 - loader.py[line:58] - INFO: Could not load library with AVX2 support due to:
ImportError('DLL load failed while importing _swigfaiss_avx2: 找不到指定的模块。')
2023-11-10 03:24:31,819 - loader.py[line:64] - INFO: Loading faiss.
2023-11-10 03:24:31,987 - loader.py[line:66] - INFO: Successfully loaded faiss.
2023-11-10 03:24:31,999 - faiss_cache.py[line:75] - INFO: loading vector store in 'samples/vector_store' from disk.
Batches: 100%|███████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.39it/s]
2023-11-10 03:24:32,513 - utils.py[line:287] - INFO: UnstructuredFileLoader used for G:\Langchain-Chatchat-master\knowledge_base\samples\content\test.txt


```

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
正常初始化

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
卡死在了这一步骤。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.6，https://github.com/chatchat-space/Langchain-Chatchat.git下载到本地的。
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：G:\chatglm3-6b-32k：
```
G:\chatglm3-6b-32k\.gitattributes
G:\chatglm3-6b-32k\config.json
G:\chatglm3-6b-32k\configuration_chatglm.py
G:\chatglm3-6b-32k\MODEL_LICENSE
G:\chatglm3-6b-32k\modeling_chatglm.py
G:\chatglm3-6b-32k\pytorch_model.bin.index.json
G:\chatglm3-6b-32k\pytorch_model-00001-of-00007.bin
G:\chatglm3-6b-32k\pytorch_model-00002-of-00007.bin
G:\chatglm3-6b-32k\pytorch_model-00003-of-00007.bin
G:\chatglm3-6b-32k\pytorch_model-00004-of-00007.bin
G:\chatglm3-6b-32k\pytorch_model-00005-of-00007.bin
G:\chatglm3-6b-32k\pytorch_model-00006-of-00007.bin
G:\chatglm3-6b-32k\pytorch_model-00007-of-00007.bin
G:\chatglm3-6b-32k\quantization.py
G:\chatglm3-6b-32k\README.md
G:\chatglm3-6b-32k\tokenization_chatglm.py
G:\chatglm3-6b-32k\tokenizer.model
G:\chatglm3-6b-32k\tokenizer_config.json

```

- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base:
```
G:\m3e-base\.gitattributes
G:\m3e-base\1_Pooling
G:\m3e-base\config.json
G:\m3e-base\model.safetensors
G:\m3e-base\modules.json
G:\m3e-base\pytorch_model.bin
G:\m3e-base\README.md
G:\m3e-base\sentence_bert_config.json
G:\m3e-base\special_tokens_map.json
G:\m3e-base\tokenizer.json
G:\m3e-base\tokenizer_config.json
G:\m3e-base\vocab.txt

```

而且已经对G:\Langchain-Chatchat-master\configs\model_config.py文件进行了修改
```

# LLM 名称
LLM_MODEL = "chatglm3-6b-32k"

修改为绝对路径 "chatglm3-6b-32k": "G:\chatglm3-6b-32k",

# 选用的 Embedding 名称
EMBEDDING_MODEL = "m3e-base" # 可以尝试最新的嵌入式sota模型：bge-large-zh-v1.5

修改为绝对路径 "m3e-base": "G:\m3e-base",


```
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 

- 操作系统及版本 / Operating system and version:
- C:\Users\haoran>systeminfo | findstr /B /C:"OS 名称" /C:"OS 版本"
C:\Users\haoran>systeminfo | findstr /B /C:"OS 名称" /C:"OS 版本"
OS 名称:          Microsoft Windows 10 专业版
OS 版本:          10.0.19045 暂缺 Build 19045
CPU是AMD 5950x，支持AVX2
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49728819/79e5814b-6e89-4f0b-9aac-032cd5772044)

GPU
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49728819/658a9c17-46dd-48ad-beeb-43a635858027)

- Python 版本 / Python version:3.10.13
```
(langcccglm) PS C:\Users\haoran> python
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

```
- 其他相关环境信息 / Other relevant environment information:
```
(langcccglm) PS C:\Users\haoran> python -c "import faiss; print(faiss.__version__)"
1.7.4
而且是CPU版本的


>>> print(langchain.__version__)
0.0.333


```

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

已经尝试了下面的所有方式，均没有解决，谢谢作者的工作，希望作者回复一下，万分感谢
https://github.com/chatchat-space/Langchain-Chatchat/issues/1939
https://github.com/chatchat-space/Langchain-Chatchat/issues/20
https://github.com/chatchat-space/Langchain-Chatchat/issues/1291
https://github.com/chatchat-space/Langchain-Chatchat/issues/1824

**Comment by Jzhnakui** [comment]
或者有完全弃用fassi的方法吗？我尝试安装了pgvector然后卸载faiss，还是不行。
G:\Langchain-Chatchat-master\knowledge_base\samples\vector_store\index.faiss
G:\Langchain-Chatchat-master\knowledge_base\samples\vector_store\index.pkl
文件删除之后也会报错。
这是我的简单尝试，可能不对，但是还是希望上卖弄的faiss相关bug能解决

**Comment by zRzRzRzRzRzRzR** [comment]
如果你要用faiss，可以考虑用gpu版本
其次，如果用pg的话，你应该在kb_config改成使用pg

**Comment by liunux4odoo** [comment]
只是不使用avx2，不影响Faiss使用
