### ISSUE TITLE
【请优先处理】搜索引擎回答存在异常，答非所问，有时候无限循环

### ISSUE THREAD

**Issue by Modas-Li** [chatchat-space/Langchain-Chatchat#2010]
模型: chatglm3-6b
显卡：V100
版本：V0.2.6
问题：模型回答异常
如图所示：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/40042370/ca972c93-2bac-4f17-854f-68838b46f471)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/40042370/a1fd62d8-a2d9-46bb-9dcc-d223a3b13f92)

**Comment by zRzRzRzRzRzRzR** [comment]
GLM3模型适配还有问题，可能会出现奇奇怪怪的bug，建议先用glm2。同时，不要问大模型任何涉及政治的问题
