### ISSUE TITLE
自定义Agent这块，用chatGLM2回答时报错没有Agent对齐，如何解决

### ISSUE THREAD

**Issue by jinditongzi** [chatchat-space/Langchain-Chatchat#2012]
目前我想试试自定义Agent这个模块，也想后续用自己本地的接口，让LLM可以调用，目前没找到相关的参考文档关于Agent这块。目前就按默认的方式启动，使用Agent聊天时是报错的，而且会陷入死循环，想知道如何解决。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46389166/303f45b5-2aa2-4c18-998b-edd21325f998)

**Comment by zRzRzRzRzRzRzR** [comment]
对齐不了，GLM2原生模型就没有Agent功能，除非你自己微调，
如果你自己微调的GLM2，在0.2.7的model_config地下有一个能配置Agent模型的，自动接触这个限制

**Comment by jinditongzi** [comment]
> 对齐不了，GLM2原生模型就没有Agent功能，除非你自己微调， 如果你自己微调的GLM2，在0.2.7的model_config地下有一个能配置Agent模型的，就不报这个错了

我看了下GLM3这边也有大佬您写的llm调用自定义工具样例，langchain-chatchat这边可以加载glm3使用Agent功能吗？
https://github.com/THUDM/ChatGLM3/tree/main/langchain_demo

**Comment by zRzRzRzRzRzRzR** [comment]
fschat没有支持glm3
要等那边支持才行

**Comment by zRzRzRzRzRzRzR** [comment]
如果你只用这一个模型，你可以按照官方demo的方式接入Langchain和我们的框架，不依赖fschat
