### ISSUE TITLE
[BUG] 升级后chat_history表没有初始化写入不进去数据

### ISSUE THREAD

**Issue by snamper** [chatchat-space/Langchain-Chatchat#2014]
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: chat_history
[SQL: INSERT INTO chat_history (id, chat_type, "query", response, meta_data, feedback_score, feedback_reason, create_time) VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP) RETURNING create_time]
[parameters: ('bf2ab0ddd7394746b8c704ce2bb9b257', 'llm_chat', '好', '', '{}', -1, '')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by zRzRzRzRzRzRzR** [comment]
版本是啥

**Comment by liunux4odoo** [comment]
启动前先执行：`python init_database.py --create-tables`
