### ISSUE TITLE
[BUG] 连接127.0.0.1超时

### ISSUE THREAD

**Issue by zhou11630** [chatchat-space/Langchain-Chatchat#2015]
使用系统为centos7
在启动过程中总是遇到这个问题，提示连接host=‘127.0.0.1’，port=20001连接超时！
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/35956869/10feed58-b5cd-4dd7-8ca3-62487b4a0bf2)

**Comment by zRzRzRzRzRzRzR** [comment]
关闭vpn
