### ISSUE TITLE
[BUG] 执行python startup.py -a脚本后，run_api_server启动成功，run_openai_api和run_webui均启动失败 / after run "python startup.py -a", run_api_server is started successfully, but run_openai_api and run_webui failed

### ISSUE THREAD

**Issue by O-Givenchy** [chatchat-space/Langchain-Chatchat#2017]
**问题描述 / Problem Description**
执行python startup.py -a脚本后，run_api_server启动成功，run_openai_api和run_webui均启动失败 / after run 'python startup.py -a', run_api_server is started successfully, but run_openai_api and run_webui failed

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a' / Run 'python startup.py -a'

**实际结果 / Actual Result**
(chatchat) C:\cyrus_files\code\Langchain-Chatchat>python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.19045-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.7
langchain版本：0.0.334. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'C:\\cyrus_files\\code\\chatglm2-6b_weights',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-35-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-12 00:31:54,107 - startup.py[line:647] - INFO: 正在启动服务：
2023-11-12 00:31:54,107 - startup.py[line:648] - INFO: 如需查看 llm_api 日志，请前往 C:\cyrus_files\code\Langchain-Chatchat\logs
2023-11-12 00:31:59 | INFO | model_worker | Register to controller
### 2023-11-12 00:31:59 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2023-11-12 00:32:00 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker fa708b28 ...                                                                                                                                                                                  
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:07<00:00,  1.10s/it]
### INFO:     Uvicorn running on http://127.0.0.1:7861 (Press CTRL+C to quit)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本：0.0.334. fastchat版本：0.2.32 / langchain-ChatGLM version:0.0.334, fastchat version:0.2.32
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型：ChatGLM2-6B
- 使用的 Embedding 模型：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 Windows-10-10.0.19045-SP0./ Operating system and version:Windows-10-10.0.19045-SP0.
- Python 版本 3.10/ Python version:3.10

LLM为ChatGLM2-6B，Embedding 模型为moka-ai/m3e-base，两者的权重文件都下载到了本地，是从本地读取的模型

**Comment by liunux4odoo** [comment]
你可以到浏览器里确认下，服务器都已经正常启动。log里显示error是fastchat的问题

**Comment by O-Givenchy** [comment]
> 你可以到浏览器里确认下，服务器都已经正常启动。log里显示error是fastchat的问题

浏览器里有试过，webui没法正常访问，接口文档的地址倒是能正常访问

**Comment by ZhichaoOuyang** [comment]
> > 你可以到浏览器里确认下，服务器都已经正常启动。log里显示error是fastchat的问题
> 
> 浏览器里有试过，webui没法正常访问，接口文档的地址倒是能正常访问

我和你一样 如何解决的请问
