### ISSUE TITLE
[BUG] 大部分模型运行正常，qwen-14b-chat-int8/int4均不加载模型，也不报错，卡住不动

### ISSUE THREAD

**Issue by FinchSaXY** [chatchat-space/Langchain-Chatchat#2018]
**问题描述 / Problem Description**
大部分模型运行正常，chatglm2,3及量化版本均正常，qwen7b也正常，但是qwen-14b-chat-int8/int4均不加载模型，也不报错，卡住不动。如果使用在线模型，会下载模型，下载之后仍然不动。

**预期的结果 / Expected Result**
qwen-14b-chat-int8/int4能正常运行

**实际结果 / Actual Result**
qwen-14b-chat-int8/int4不能正常运行

**环境信息 / Environment Information**
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.2.0-36-generic-x86_64-with-glibc2.35.
显卡： NVIDIA GeForce RTX 4090 
python版本：3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
项目版本：v0.2.6
langchain版本：0.0.329. fastchat版本：0.2.31

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-14B-Chat-int8'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/media/ubuntu/98862CE9862CC998/models/Qwen-14B-Chat-Int8',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-12 08:27:05,259 - startup.py[line:626] - INFO: 正在启动服务：
2023-11-12 08:27:05,260 - startup.py[line:627] - INFO: 如需查看 llm_api 日志，请前往 /media/ubuntu/98862CE9862CC998/Langchain-Chatchat/logs
2023-11-12 08:27:10 | ERROR | stderr | INFO:     Started server process [92048]
2023-11-12 08:27:10 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-12 08:27:10 | ERROR | stderr | INFO:     Application startup complete.
2023-11-12 08:27:10 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-12 08:27:10 | INFO | model_worker | Loading the model ['Qwen-14B-Chat-int8'] on worker 4cc2f207 ...
2023-11-12 08:27:10 | WARNING | transformers_modules.Qwen-14B-Chat-Int8.modeling_qwen | Warning: please make sure that you are using the latest codes and checkpoints, especially if you used Qwen-7B before 09.25.2023.请使用最新模型和代码，尤其如果你在9月25日前已经开始使用Qwen-7B，千万注意不要使用错误代码和模型。
2023-11-12 08:27:10 | WARNING | transformers_modules.Qwen-14B-Chat-Int8.modeling_qwen | Try importing flash-attention for faster inference...
2023-11-12 08:27:11 | WARNING | transformers_modules.Qwen-14B-Chat-Int8.modeling_qwen | Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm

**附加信息 / Additional Information**
以搜索所有的issue并未发现类似的情况。

**Comment by O-Givenchy** [comment]
我看你的log有个报错我也遇见了，就是这几个error，服务启动后浏览器访问对应ip和端口打不开网页
2023-11-12 08:27:10 | ERROR | stderr | INFO: Started server process [92048]
2023-11-12 08:27:10 | ERROR | stderr | INFO: Waiting for application startup.
2023-11-12 08:27:10 | ERROR | stderr | INFO: Application startup complete.
2023-11-12 08:27:10 | ERROR | stderr | INFO: Uvicorn running on http://0.0.0.0:20000/ (Press CTRL+C to quit)

**Comment by O-Givenchy** [comment]
> 我看你的log有个报错我也遇见了，就是这几个error，服务启动后浏览器访问对应ip和端口打不开网页 2023-11-12 08:27:10 | ERROR | stderr | INFO: Started server process [92048] 2023-11-12 08:27:10 | ERROR | stderr | INFO: Waiting for application startup. 2023-11-12 08:27:10 | ERROR | stderr | INFO: Application startup complete. 2023-11-12 08:27:10 | ERROR | stderr | INFO: Uvicorn running on http://0.0.0.0:20000/ (Press CTRL+C to quit)

请问你运行正常的那些模型，webui可以正常访问吗

**Comment by FinchSaXY** [comment]
> > 我看你的log有个报错我也遇见了，就是这几个error，服务启动后浏览器访问对应ip和端口打不开网页 2023-11-12 08:27:10 | ERROR | stderr | INFO: Started server process [92048] 2023-11-12 08:27:10 | ERROR | stderr | INFO: Waiting for application startup. 2023-11-12 08:27:10 | ERROR | stderr | INFO: Application startup complete. 2023-11-12 08:27:10 | ERROR | stderr | INFO: Uvicorn running on http://0.0.0.0:20000/ (Press CTRL+C to quit)
> 
> 请问你运行正常的那些模型，webui可以正常访问吗

这几个error在正常运行的模型里也是有的，就没管。webui可以访问，但是需要把网址的0.0.0.0:8501改成127.0.0.0:8501，其他局域网电脑就是ip+端口就行。

**Comment by zRzRzRzRzRzRzR** [comment]
检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答

**Comment by FinchSaXY** [comment]
> 检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答

内存和ip都没问题，是webui也进不去，运行log只到我上面展示的那里，就一直不变了，不会再继续往下，就很奇怪

**Comment by O-Givenchy** [comment]
> 检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答

![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/39072481/a59b1bfd-8249-4a96-8dd8-b9d96c991cd9)
我把相关信息截了一张图，还请看看有没有思路。。使用的是默认LLM和Embbeding模型，但进不去webui页面，接口文档页面可以进入，接口通过postman也能正常请求

**Comment by zRzRzRzRzRzRzR** [comment]
> > 检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答
> 
> 内存和ip都没问题，是webui也进不去，运行log只到我上面展示的那里，就一直不变了，不会再继续往下，就很奇怪

emm，检查一下模型文件，然后他warn的两个库装一下了

**Comment by zRzRzRzRzRzRzR** [comment]
> > 检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答
> 
> ![2](https://user-images.githubusercontent.com/39072481/282296703-a59b1bfd-8249-4a96-8dd8-b9d96c991cd9.png) 我把相关信息截了一张图，还请看看有没有思路。。使用的是默认LLM和Embbeding模型，但进不去webui页面，接口文档页面可以进入，接口通过postman也能正常请求

你这个没有开vpn么，我看端口redirect了啊

**Comment by O-Givenchy** [comment]
> > > 检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答
> > 
> > 
> > ![2](https://user-images.githubusercontent.com/39072481/282296703-a59b1bfd-8249-4a96-8dd8-b9d96c991cd9.png) 我把相关信息截了一张图，还请看看有没有思路。。使用的是默认LLM和Embbeding模型，但进不去webui页面，接口文档页面可以进入，接口通过postman也能正常请求
> 
> 你这个没有开vpn么，我看端口redirect了啊

你好，没有开代理，7378和7379两个port是写在server_config.py配置里的（默认的端口我记不住，就改了两个容易记的）

**Comment by zRzRzRzRzRzRzR** [comment]
那这端口为什么跟你写的不一样？
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/93239683/baac15bf-7d62-438a-ae48-7a51e6adfef0)
这才是正常的情况
默认的demo是不是正常的

**Comment by FinchSaXY** [comment]
> > > 检查一下内存和ip地址，然后这个不能运行是webui都进不去还是正常进去但是发话了模型不回答
> > 
> > 
> > 内存和ip都没问题，是webui也进不去，运行log只到我上面展示的那里，就一直不变了，不会再继续往下，就很奇怪
> 
> emm，检查一下模型文件，然后他warn的两个库装一下了
模型文件没问题，我自己下的，或者让程序自己下的都试过，都是卡在这里，能下载下来但是不加载。

 至于warn的包是flash-attention，这个我装不了，这个是给快速推理用的，并且只是写给A100的。我也装过，装的时候会内存溢出，然后崩掉。主要理论上不用装，7b也显示了这个warn，但是没关系的，不影响使用，只会影响速度。

**Comment by O-Givenchy** [comment]
> 那这端口为什么跟你写的不一样？ ![图片](https://user-images.githubusercontent.com/93239683/282297522-baac15bf-7d62-438a-ae48-7a51e6adfef0.png) 这才是正常的情况 默认的demo是不是正常的

 抱歉不是很明白你说的正常的和我的区别在哪儿，我重新拉了一下最新的工程，只改了model_config.py里的这两行（我是本地的模型）然后进行了启动，还是只能访问7861端口，8501访问不到，另外我initial数据库的时候有挺多错误信息的，不知道是否会造成webui无法访问的情况呢？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39072481/74f8a328-b229-4079-b9a1-b6c16dd73d74)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39072481/d2333436-45e8-477f-9150-b3947a5a14c4)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39072481/574b4dbb-a72b-4ee0-9604-8d7ca7253c02)

**Comment by zRzRzRzRzRzRzR** [comment]
ok，那现在的情况是，7b能加载，14b能加载，int4不加载，mark，但是我这边无法复现，可能要等我们的其他开发组成员来尝试复现一下

**Comment by zRzRzRzRzRzRzR** [comment]
7861

> > 那这端口为什么跟你写的不一样？ ![图片](https://user-images.githubusercontent.com/93239683/282297522-baac15bf-7d62-438a-ae48-7a51e6adfef0.png) 这才是正常的情况 默认的demo是不是正常的
> 
> 抱歉不是很明白你说的正常的和我的区别在哪儿，我重新拉了一下最新的工程，只改了model_config.py里的这两行（我是本地的模型）然后进行了启动，还是只能访问7861端口，8501访问不到，另外我initial数据库的时候有挺多错误信息的，不知道是否会造成webui无法访问的情况呢？ ![image](https://user-images.githubusercontent.com/39072481/282298241-74f8a328-b229-4079-b9a1-b6c16dd73d74.png) ![image](https://user-images.githubusercontent.com/39072481/282298401-d2333436-45e8-477f-9150-b3947a5a14c4.png) ![image](https://user-images.githubusercontent.com/39072481/282298173-574b4dbb-a72b-4ee0-9604-8d7ca7253c02.png)

那只能先查看依赖是否正确了，我这复现不了这个维问题，我让我其他我们的开发组成员看看

**Comment by O-Givenchy** [comment]
> 7861
> 
> > > 那这端口为什么跟你写的不一样？ ![图片](https://user-images.githubusercontent.com/93239683/282297522-baac15bf-7d62-438a-ae48-7a51e6adfef0.png) 这才是正常的情况 默认的demo是不是正常的
> > 
> > 
> > 抱歉不是很明白你说的正常的和我的区别在哪儿，我重新拉了一下最新的工程，只改了model_config.py里的这两行（我是本地的模型）然后进行了启动，还是只能访问7861端口，8501访问不到，另外我initial数据库的时候有挺多错误信息的，不知道是否会造成webui无法访问的情况呢？ ![image](https://user-images.githubusercontent.com/39072481/282298241-74f8a328-b229-4079-b9a1-b6c16dd73d74.png) ![image](https://user-images.githubusercontent.com/39072481/282298401-d2333436-45e8-477f-9150-b3947a5a14c4.png) ![image](https://user-images.githubusercontent.com/39072481/282298173-574b4dbb-a72b-4ee0-9604-8d7ca7253c02.png)
> 
> 那只能先查看依赖是否正确了，我这复现不了这个维问题，我让我其他我们的开发组成员看看

多谢大侠耐心指教了这么久，可能真和依赖有关系，我把conda的环境重新整理后，现在可以正常体验webui了
btw有个问题想请教，前端使用vue框架的话，可以调用接口文档中的api实现最简单的知识库管理（新增/删除知识库，新增删除特点知识库中的文件）和进行知识库对话吗

**Comment by FinchSaXY** [comment]
> ok，那现在的情况是，7b能加载，14b能加载，int4不加载，mark，但是我这边无法复现，可能要等我们的其他开发组成员来尝试复现一下

感谢，确定7b能用，14b应该可以，不过加载到最后显示显存溢出了，所以没再尝试。但是量化版本怎么也不加载。

**Comment by fiioz** [comment]
把flash attention关了

**Comment by FinchSaXY** [comment]
> 把flash attention关了

请问怎么关啊？

**Comment by kaso1114** [comment]
pip uninstall flash-attn
