### ISSUE TITLE
生成结果

### ISSUE THREAD

**Issue by yy835055664** [chatchat-space/Langchain-Chatchat#202]
你好，想问一下langchain+chatglm-6B，找到相似匹配的prompt，是直接返回prompt对应的答案信息，还是chatglm-6B在此基础上自己优化答案？

**Comment by imClumsyPanda** [comment]
把prompt发给glm，由glm返回信息

yy ***@***.***>于2023年4月28日 周五15:30写道：

**Comment by yy835055664** [comment]
那返回的信息应该是在glm处理过的吧，并不会返回标准的答案，可以这么理解吗？

**Comment by imClumsyPanda** [comment]
是的 如果需要精确的标准答案，完全不需要llm的参与

yy ***@***.***>于2023年4月28日 周五15:59写道：

**Comment by yy835055664** [comment]
好的，多谢

**Comment by yy835055664** [comment]
你好，我准备了一些文本，如下所示。但是在提问后，感觉不能再里面得到相对的答案，是因为我的文本设计有问题吗？
文本：
![image](https://user-images.githubusercontent.com/57432458/235094733-02ff66ef-9760-4596-bd5b-49fd9697f74a.png)
结果：
![image](https://user-images.githubusercontent.com/57432458/235094895-51991efa-2727-4538-a1ac-97fb24f677e0.png)
