### ISSUE TITLE
LLM_MODELS本地模型加载切换错误

### ISSUE THREAD

**Issue by szdengdi** [chatchat-space/Langchain-Chatchat#2027]
**问题描述 / Problem Description**
model_config.py的LLM_MODELS配置了多个本地模型和在线模型。启动的时候，会把列入的本地模型都加载。
但在WebUI“选择LLM模型”里面只显示第一个本地模型，其他本地模型都没有显示，也无法切换。

**复现问题的步骤 / Steps to Reproduce**
1. 在model_config.py的LLM_MODELS里面配置多个本地模型和在线模型，例如：chatglm2-6b、zhipu_ai、chatglm3-6b
2. 启动程序，会把chatglm2-6b、chatglm3-6b本地模型都加载
3. 启动完毕后WebUI，”选择LLM模型“里面只能看到chatglm2-6b，看不到chatglm3-6b
4. 输入内容，实际是chatglm3-6b

**预期的结果 / Expected Result**
1、本地模型只加载第一个，如果切换到其他本地模型，再重新加载其他模型。
2、多个本地模型，可以选择

**实际结果 / Actual Result**
全部加载，无法选择

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.27
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm2-6b、zhipu_ai、chatglm3-6b
- 操作系统及版本 / Operating system and version: Ubuntu22.04
- Python 版本 / Python version:3.10.12

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新版本解决
