### ISSUE TITLE
Web UI上删除本地知识库删不干净，点击删除后会留个空的选项

### ISSUE THREAD

**Issue by DDYuudachi** [chatchat-space/Langchain-Chatchat#2030]
**问题描述 / Problem Description**
Web UI上删除本地知识库删不干净，点击删除后知识库的选项人仍然存在，需要手动在knowledge_base文件夹删除指定知识库

**复现问题的步骤 / Steps to Reproduce**
1. 新建知识库，向量库选项milvus，embedding模型m3e-base
2. 输入知识库名称testDB
3. 新建知识库
4. 点击删除知识库
5. 然后就显示了一个被删，但选项仍存在的知识库选项，详见实际结果截图

**预期的结果 / Expected Result**
点击删除知识库后，知识库选项中留了一个空的选项，如下图所示，要手动删除knowledge_base文件夹中的数据库名称

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/84870854/f77252ee-1932-498b-b124-e73d219ccbab)

**环境信息 / Environment Information**
- Langchain-ChatChat v0.2.7最新版 （今天刚拉的版本）

**Comment by zRzRzRzRzRzRzR** [comment]
mark，我们复现修复一下

**Comment by zRzRzRzRzRzRzR** [comment]
现在还有么

**Comment by DDYuudachi** [comment]
> 现在还有么

问题还在的，我把项目删了重新拉了一遍，还是这样

**Comment by zRzRzRzRzRzRzR** [comment]
好，我们在关注一下

**Comment by liunux4odoo** [comment]
最新版测试了一下，无法复现。

步骤：
1、webui 进入知识库管理页面
2、新建知识库，名称test，其它默认
3、上传一个文件，正常向量化
4、点击删除知识库，本地文件夹被直接删除，info.db 中test相关记录被一同删除。
