### ISSUE TITLE
an unexpected keyword argument 'proxy_ssl_context'   TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by fengyunzaidushi** [chatchat-space/Langchain-Chatchat#2032]
**问题描述 / Problem Description**
还是代理相关的问题

**复现问题的步骤**
1. 执行 '...' /  python startup.py -a

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

```
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://127.0.0.1:7890', 'https://': 'http://127.0.0.1:7890', 'all://': None}}
2023-11-13 10:57:13,695 - utils.py[line:94] - ERROR: TypeError: error when post /llm_model/list_running_models: __init__() got an unexpected keyword argument 'proxy_ssl_context'
2023-11-13 10:57:13.696 Uncaught app exception
Traceback (most recent call last):
  File "/opt/miniconda3/envs/py39lang/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/mnt/sda/github/10yue/langchain-ChatGLM/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/mnt/sda/github/10yue/langchain-ChatGLM/webui_pages/dialogue/dialogue.py", line 83, in dialogue_page
    running_models = list(api.list_running_models())
TypeError: 'NoneType' object is not iterable
```
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53250064/77c1aaff-b1b1-4a02-be47-e3c68e2c21ef)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.335
- 是否使用 Docker 部署：否
- 使用的模型： ChatGLM2-6B
- 使用的 Embedding 模型：m3e-base 
- 使用的向量库类型： faiss 
- 操作系统及版本 : ubuntu 22.04
- Python 版本 / Python version: 3.9.17
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
本地文件 /etc/profile 设置了代理：
1.
```
export http_proxy="http://127.0.0.1:7890"
export https_proxy="http://127.0.0.1:7890"
```
2.
ubuntu系统网络如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53250064/b032293f-1508-4455-942e-05f41988e065)

3. clash软件是打开状态，开启了rule模式。

ps:上一个版本,这种配置没有问题。

**Comment by IgnoranceSmile** [comment]
我也是，刚刚遇到这个问题

**Comment by fengyunzaidushi** [comment]
```
server/utils.py
# 构造Client
kwargs.update(timeout=timeout, proxies=default_proxies)
print(kwargs)
# 这里 的结果我本地是：
#{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': 'http://127.0.0.1:7890', 'https://': 'http://127.0.0.1:7890', 'all://': None}}
```

**Comment by fengyunzaidushi** [comment]
pip install httpx==0.25.0 解决了，原来版本是httpx==0.25.1

**Comment by ztfoolish** [comment]
> pip install httpx==0.25.0 解决了，原来版本是httpx==0.25.1

大佬你好，为啥我按你的方法做了依然不行啊😭（pip install httpx==0.25.0）
我是在云服务器上跑的，本地ssh连接上去看的。本地开了代理（应该不影响吧？）
![telegram-cloud-photo-size-5-6242220350800771243-y](https://github.com/chatchat-space/Langchain-Chatchat/assets/18691109/e678230a-ae36-421c-81f1-986af4404a0a)

**Comment by mountain1275** [comment]
> > pip install httpx==0.25.0 解决了，原来版本是httpx==0.25.1
> 
> 大佬你好，为啥我按你的方法做了依然不行啊😭（pip install httpx==0.25.0） 我是在云服务器上跑的，本地ssh连接上去看的。本地开了代理（应该不影响吧？） ![telegram-cloud-photo-size-5-6242220350800771243-y](https://private-user-images.githubusercontent.com/18691109/282897256-e678230a-ae36-421c-81f1-986af4404a0a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNjczNDYsIm5iZiI6MTcwMTA2NzA0NiwicGF0aCI6Ii8xODY5MTEwOS8yODI4OTcyNTYtZTY3ODIzMGEtYWUzNi00MjFjLTgxZjEtOTg2YWY0NDA0YTBhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI3VDA2MzcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZDhhYjc0OGMwZGJjN2YwMjczOGI5ZTczMTNiNWQzMDU4OGJiOTI3MTViYzVjMjQ3Mjc1MWZiZjU4NDBkMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jh_jjnOZuNGEFsKci77N9mcQXPzqyexk1e3XFm81tTw)

和你的报错一毛一样

**Comment by fengyunzaidushi** [comment]
后面还是有问题。我最后是重新创造环境，重新安装解决的。

**Comment by mension** [comment]
openai 依赖的httpx 是0.25.2 [openai-python requirements](https://github.com/openai/openai-python/blob/main/requirements.lock#L17C14-L17C14)

**Comment by AIfengstudy** [comment]
同样是这个问题！！！！

**Comment by zRzRzRzRzRzRzR** [comment]
现在还有这个问题吗

**Comment by AIfengstudy** [comment]
今天刚装了一遍还是有这个问题 我按照下面方法回退pip install httpx==0.25.1,就不报错了；还有就是，如果不按python startup.py -a换成只启动webui的命令，不会有问题

> pip install httpx==0.25.0 解决了，原来版本是httpx==0.25.1
