### ISSUE TITLE
怎么配置online LLM呢，设置了zhipuai的key，但是调用报错

### ISSUE THREAD

**Issue by Andyszl** [chatchat-space/Langchain-Chatchat#2036]
UI报：API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by jzf2003428036** [comment]
same issue：
m1 MacBook Pro 16GB

**Comment by zRzRzRzRzRzRzR** [comment]
没有复现，检查一下key是否正常
