### ISSUE TITLE
升级0.2.7后无法显示openai-api

### ISSUE THREAD

**Issue by phpdancer** [chatchat-space/Langchain-Chatchat#2037]
**问题描述 / Problem Description**
更新最新版0.2.7后页面上模型列表无法显示open-api了，且如果配置了两个本地模型会同时加载，这样容易造成oom，建议切换的时候再加载。

**Comment by fengyunzaidushi** [comment]
我也遇到了

**Comment by Monkey0000** [comment]
一样的问题，打不开api界面

**Comment by zRzRzRzRzRzRzR** [comment]
因为openai不走model woker，所以我们默认的选择里没有openai,这个问题暂时还没有修复

**Comment by jerryliang122** [comment]
> 因为openai不走model woker，所以我们默认的选择里没有openai,这个问题暂时还没有修复

那有什么临时的解决办法呢？

**Comment by pengxianggui** [comment]
> 因为openai不走model woker，所以我们默认的选择里没有openai,这个问题暂时还没有修复

意思是现在 openai接不了是吗？

**Comment by Victoriaheiheihei** [comment]
openai加载两个模型是否需要两个端口？
