### ISSUE TITLE
0.2.8 preview  chatglm3-6b 出现round 如何不让出现round 还有接口也出现

### ISSUE THREAD

**Issue by snamper** [chatchat-space/Langchain-Chatchat#2038]
![1699859035176](https://github.com/chatchat-space/Langchain-Chatchat/assets/172051/c390c03a-166e-4d88-b231-369484d39f2c)

后面的接口调用是不是可以 流的方式  是否返回json，是否返回思考过程，不然直接调用不太友好

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.7不支持glm3

**Comment by zRzRzRzRzRzRzR** [comment]
目前的fschat不支持glm3，你要源码安装fschat才能支持

**Comment by snamper** [comment]
好的
