### ISSUE TITLE
如何使用命令行生成对话而不使用UI呢？

### ISSUE THREAD

**Issue by HuDiLee** [chatchat-space/Langchain-Chatchat#2043]
服务器没有联网没用浏览器，怎么直接通过命令行让生成对话？

**Comment by zRzRzRzRzRzRzR** [comment]
没有提供命令行版本，因为功能太多了，你可以pr一个

**Comment by bluelightgit** [comment]
requirements中有fschat, 你或许可以使用 `python -m fastchat.serve.cli --model-path [/path/to/model]` 通过命令行运行
