### ISSUE TITLE
server/api.py文件中有行代码多写了一次，会报错

### ISSUE THREAD

**Issue by Monkey0000** [chatchat-space/Langchain-Chatchat#2044]
mount_app_routes方法中mount_knowledge_routes(app)和主方法入口都有这行代码，会导致api页面打不开，报错KeyError: <class 'pydantic.main.Body_search_docs_knowledge_base_search_docs_post>

**Comment by liunux4odoo** [comment]
开发版中已修复。

对于 startup.py 启动方式，该问题不影响正常使用。

**Comment by yhfgyyf** [comment]
嗯，昨天发现这个问题，今天注销了代码就可以了
