### ISSUE TITLE
执行python startup.py -a正常，但是网页端Not Found

### ISSUE THREAD

**Issue by gumanchang** [chatchat-space/Langchain-Chatchat#2045]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/9926137/40a81972-86ad-4f5f-85ec-06732a9add1f)
执行python startup.py -a正常
但是网页端web无妨访问：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/9926137/4aea55cd-bf9a-415f-a88a-b6a45b11b160)

**Comment by zRzRzRzRzRzRzR** [comment]
直接换成你局域网的IP地址试试不要0.0.0.0

**Comment by gumanchang** [comment]
机器的端口被占用了，我的问题，感谢。不是代码的问题
