### ISSUE TITLE
显存不足，请问chatglm3-6b量化模型quantize怎么改？

### ISSUE THREAD

**Issue by Leweibo** [chatchat-space/Langchain-Chatchat#2047]
chatglm3-6b量化方法：

model = AutoModel.from_pretrained("THUDM/chatglm3-6b",trust_remote_code=True).quantize(4).cuda()

但是不知道Langchain-Chatchat在哪里修改。

谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
没法改，只能导入模型

**Comment by Leweibo** [comment]
在startup.py 中将 args.load_8bit 更改为 True，即可实现量化int8模型

**Comment by psscar** [comment]
> 在startup.py 中将 args.load_8bit 更改为 True，即可实现量化int8模型

使用 @Leweibo 的方法成功运行了chatglm3-6b，int8下占有显存将近8G。

测试在8G显卡上问答可以正常进行，如进行知识库问答会出现‘CUDA out of memory’，所以想进一步请教下 @Leweibo ，是否有在 4-bit 量化加载的方法。

**Comment by nanisnull** [comment]
在startup.py 中将 args.load_8bit 更改为 True，web端问答会显示- utils.py[line:24] - ERROR: object of type 'NoneType' has no len()
