### ISSUE TITLE
[BUG] utils.py[line:25] - ERROR: KeyError: Caught exception: 'choices'

### ISSUE THREAD

**Issue by binbin5261** [chatchat-space/Langchain-Chatchat#2048]
**问题描述 / Problem Description**
utils.py[line:25] - ERROR: KeyError: Caught exception: 'choices'

**环境信息 / Environment Information**
- langchain-ChatGLM v0.2.7
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型  qwen-api

**Comment by yhfgyyf** [comment]
我用azure-api也有这个报错

**Comment by javenonly** [comment]
我调用qianfan-api在线模型，也是报错：
2023-11-16 10:24:43 | INFO | httpx | HTTP Request: POST https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/eb-instant?access_token=24.da7abdd54f6ff128dd757e6028979c7f.2592000.1702693294.282335-43102414 "HTTP/1.1 200 OK"
{'docs': [...]}
2023-11-16 10:24:43,990 - utils.py[line:25] - ERROR: KeyError: Caught exception: 'choices'
{'base_url': 'http://127.0.0.1:7861', 'timeout': 300.0, 'proxies': {'all://127.0.0.1': None, 'all://localhost': None, 'http://127.0.0.1': None, 'http://': None, 'https://': None, 'all://': None, 'http://localhost': None}}
向量EMBEDDING_MODEL = "m3e-base" ，数据能够正常召回，但是大模型没有显示回答。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31364630/35d2253a-c681-4bc0-a361-d6138aad06e5)

**Comment by applepieiris** [comment]
我也是出现这个错误，API正确填写了

**Comment by yhfgyyf** [comment]
0.2.7版本所有llm必须要在fastchat注册（估计是避免上个版本‘’list的bug），不注册webui不会显示，所以openai-api在server_config,py中没有配置。
我在server/model_worker/下增加了一个chatgpt.py，按照azure.py的重新写了OpenaiWorker（server_config.py中需要配置openai-api注册项，model_config.py中需要添加provider），server/utils.py中重写了get_ChatOpenAI（）函数，按照0.2.6的方法把openai-api和azure-api重写了下解决了。

**Comment by weixuansun** [comment]
我这边跑本地模型也遇到了这个问题，请问有可能是什么原因呢？

**Comment by gutengshuxia** [comment]
> 0.2.7版本所有llm必须要在fastchat注册（估计是避免上个版本‘’list的bug），不注册webui不会显示，所以openai-api在server_config,py中没有配置。 我在server/model_worker/下增加了一个chatgpt.py，按照azure.py的重新写了OpenaiWorker（server_config.py中需要配置openai-api注册项，model_config.py中需要添加provider），server/utils.py中重写了get_ChatOpenAI（）函数，按照0.2.6的方法把openai-api和azure-api重写了下解决了。

兄弟，可以告诉一下解决方法，我也遇到使用azure_api，出现Choice提示

**Comment by yhfgyyf** [comment]
> > 0.2.7版本所有llm必须要在fastchat注册（估计是避免上个版本‘’list的bug），不注册webui不会显示，所以openai-api在server_config,py中没有配置。 我在server/model_worker/下增加了一个chatgpt.py，按照azure.py的重新写了OpenaiWorker（server_config.py中需要配置openai-api注册项，model_config.py中需要添加provider），server/utils.py中重写了get_ChatOpenAI（）函数，按照0.2.6的方法把openai-api和azure-api重写了下解决了。
> 
> 兄弟，可以告诉一下解决方法，我也遇到使用azure_api，出现Choice提示

这里修改的地方有点多，一下子说不清楚，官方下个版本应该会修改掉，或者看看dev版本有没有改掉

**Comment by gutengshuxia** [comment]
> > > 0.2.7版本所有llm必须要在fastchat注册（估计是避免上个版本‘’list的bug），不注册webui不会显示，所以openai-api在server_config,py中没有配置。 我在server/model_worker/下增加了一个chatgpt.py，按照azure.py的重新写了OpenaiWorker（server_config.py中需要配置openai-api注册项，model_config.py中需要添加provider），server/utils.py中重写了get_ChatOpenAI（）函数，按照0.2.6的方法把openai-api和azure-api重写了下解决了。
> > 
> > 
> > 兄弟，可以告诉一下解决方法，我也遇到使用azure_api，出现Choice提示
> 
> 这里修改的地方有点多，一下子说不清楚，官方下个版本应该会修改掉，或者看看dev版本有没有改掉

我已经试过了Dev环境代码，似乎出现了通信问题，太难了。xinghuo的API没问题，azure就出现Choice问题。

**Comment by yhfgyyf** [comment]
> > > > 0.2.7版本所有llm必须要在fastchat注册（估计是避免上个版本‘’list的bug），不注册webui不会显示，所以openai-api在server_config,py中没有配置。 我在server/model_worker/下增加了一个chatgpt.py，按照azure.py的重新写了OpenaiWorker（server_config.py中需要配置openai-api注册项，model_config.py中需要添加provider），server/utils.py中重写了get_ChatOpenAI（）函数，按照0.2.6的方法把openai-api和azure-api重写了下解决了。
> > > 
> > > 
> > > 兄弟，可以告诉一下解决方法，我也遇到使用azure_api，出现Choice提示
> > 
> > 
> > 这里修改的地方有点多，一下子说不清楚，官方下个版本应该会修改掉，或者看看dev版本有没有改掉
> 
> 我已经试过了Dev环境代码，似乎出现了通信问题，太难了。xinghuo的API没问题，azure就出现Choice问题。
大概是这样的：server/utils.py下get_ChatOpenAI(）函数内把azure-api和openai-api隔离开，这里方便起见用了原来的get_OpenAI（)函数,这个函数在0.2.7版本的代码里没有用到

```
if model_name in ["openai-api","azure-api"]:
        return get_OpenAI(
            model_name = model_name,
            temperature = temperature,
            max_tokens = max_tokens,
            streaming = streaming,
            callbacks = callbacks,
            verbose = verbose,
            **kwargs
        )
    else: 
        model = ChatOpenAI(
            streaming=streaming,
            verbose=verbose,
            callbacks=callbacks,
            openai_api_key=config.get("api_key", "EMPTY"),
            openai_api_base=config.get("api_base_url", fschat_openai_api_address()),
            model_name=model_name,
            temperature=temperature,
            max_tokens=max_tokens,
            openai_proxy=config.get("openai_proxy"),
            **kwargs
        )

    return model
```
get_OpenAI（)内部重新实现azure-api和openai-api，分别用了两个langchain的ChatOpenAI, AzureChatOpenAI这两个chat model，这两个chat_model代码里也没有用到，azure的base_url可以用model_config.py中的resource_name拼接，也可以自己改，
```
if model_name in config_models.get("online", {}):
        config = config_models["online"][model_name]
        if model_name == "azure-api":
            model = AzureChatOpenAI(
                streaming=streaming,
                verbose=verbose,
                callbacks=callbacks,
                azure_deployment=config.get("deployment_name"),
                openai_api_type=config.get("openai_api_type"),
                base_url="*********",
                api_version=config.get("api_version"),
                api_key=config.get("api_key"),
                openai_proxy=config.get("openai_proxy"),
                temperature=temperature,
                max_tokens=max_tokens,
            )
elif model_name == "openai-api":
            model = ChatOpenAI(
                streaming=streaming,
                verbose=verbose,
                callbacks=callbacks,
                model_name=config.get("model_name"),
                openai_api_base=config.get("api_base_url"),
                openai_api_key=config.get("api_key"),
                openai_proxy=config.get("openai_proxy"),
                temperature=temperature,
                max_tokens=max_tokens,
            )
```
另外使用openai-api还需要在server/model_worker/中增加chatgpt的modelworker文件,这里可以参考azure.py写，_init_.py中需要import、config/model_config.py中增加openai-api的provider，server_config.py中增加openai-api的端口，参考azure-api。
