### ISSUE TITLE
从v0.2.3升级到最新版本v0.2.7，去除了api_base_url，使用远程服务器fastchat部署的chatglm3模型应该怎样进行配置

### ISSUE THREAD

**Issue by AI-HR** [chatchat-space/Langchain-Chatchat#2052]
**问题描述 / Problem Description**
修改了server_config.py中的FSCHAT_MODEL_WORKERS、FSCHAT_CONTROLLER、FSCHAT_OPENAI_API中的host为远程地址，找不到执行的模型，我这种情况应该怎样配置model_config和server_config

**复现问题的步骤 / Steps to Reproduce**
python startup.py --api -w

**预期的结果 / Expected Result**
正常运行项目

**实际结果 / Actual Result**
<img width="1264" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/83696206/60af3982-3e09-4222-a80c-992485406a86">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：  milvus
- 操作系统及版本 / Operating system and version:macos
- Python 版本 / Python version:3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by erjiguan** [comment]
解决了吗

**Comment by Jun-Howie** [comment]
"chatglm2-6b": {
        "model_name": "chatglm2-6b",
        "api_base_url": "https://127.0.0.1:8888/v1",
        "api_key": "nano",
        "openai_proxy": "",
    },
追加在ONLINE_LLM_MODEL中
注释MODEL_PATH下llm_model 
# "chatglm2-6b": "THUDM/chatglm2-6b",

随后python startup.py -a 可以拉起整个项目

v0.2.7 似乎有API通讯问题

**Comment by AI-HR** [comment]
> "chatglm2-6b": { "model_name": "chatglm2-6b", "api_base_url": "https://127.0.0.1:8888/v1", "api_key": "nano", "openai_proxy": "", }, 追加在ONLINE_LLM_MODEL中 注释MODEL_PATH下llm_model
> 
> # "chatglm2-6b": "THUDM/chatglm2-6b",
> 随后python startup.py -a 可以拉起整个项目
> 
> v0.2.7 似乎有API通讯问题

其他的地方还需要修改吗，按照上边的方法执行了,还是有点问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/83696206/085bc062-6c64-4447-b193-131bff695f2d)

**Comment by Jun-Howie** [comment]
@AI-HR 尝试最新的master代码或者dev分支

**Comment by Jun-Howie** [comment]
@AI-HR 不好意思，刚刚有忘记提到，还需求修改server_config.py中的FSCHAT_MODEL_WORKERS
新增 "chatglm2-6b": {
        "port": 21009,
    },

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/62869005/6c518d15-7618-40d0-a600-936cb726f631)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.8，好像直接解决了这个问题
