### ISSUE TITLE
[BUG] 知识库上传文件失败：AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by leoterry-ulrica** [chatchat-space/Langchain-Chatchat#2055]
**问题描述 / Problem Description**
知识库上传文件失败：AxiosError: Request failed with status code 403

**复现问题的步骤 / Steps to Reproduce**
知识库管理->上传文件失败，提示：AxiosError: Request failed with status code 403
![1699943991139](https://github.com/chatchat-space/Langchain-Chatchat/assets/18339429/760528a2-e271-4b21-aef9-f64ceff7e5d8)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Ubuntu
- Python 版本 / Python version: python3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by Mrleoleoleo** [comment]
我也是这个问题

**Comment by a656418zz** [comment]
+1 我最后直接把文件手动复制到content文件夹才解决的

**Comment by zRzRzRzRzRzRzR** [comment]
mark，这个有可能是steamlit的缓存或者存储问题，我们有收到类似的反馈，我们检查一下

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下新版本，我这边是正常的，0.2.8试试

**Comment by leoterry-ulrica** [comment]
> 更新一下新版本，我这边是正常的，0.2.8试试

好的  我试试

**Comment by heidongqilin** [comment]
用老版本streamlit  解决了 pip install streamlit==1.28.2

**Comment by adiligentpiggy** [comment]
https://wqmoran.com/streamlit-axioserror-status-code-403-solution/
