### ISSUE TITLE
可以支持codeshell模型吗？

### ISSUE THREAD

**Issue by Jingzhenzxz** [chatchat-space/Langchain-Chatchat#2057]
codeshell模型的地址为：https://github.com/WisdomShell/codeshell
谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
由于您的Issue不符合 [Issue 规范](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E5%81%9A%E5%87%BA%E8%B4%A1%E7%8C%AE#issue-%E8%A7%84%E8%8C%83) 该issue被关闭
