### ISSUE TITLE
[BUG]多用户并发问答报错

### ISSUE THREAD

**Issue by opsvr** [chatchat-space/Langchain-Chatchat#2059]
**问题描述 / Bad message format**
用简洁明了的语言描述这个问题 / 多用户并发问答，页面提示Bad message format, Bad 'setIn' index 2 (should be between [0, 1])

**复现问题的步骤 / Steps to Reproduce**
1. 多用户同时登录页面；
2. 同时提问不同问题；
3. 页面提示Bad message format，后端日志报错
```
File "/you/python/path/streamlit/runtime/scriptrunner/script_runner.py" line 541, in _run_script
    exec(code, module.__dict__)
File "/you/project/path/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "/you/project/path/Langchain-Chatchat/webui_page/dialogue/dialogue.py"
  chat_box.show_feedback(**feedback_kwargs,
File "/you/python/path/python310/lib/python3.10/sit-packages/streamlit_chatbox/message.py", line 307, in show_feedback
  with self._chat_containers[history_index]:
IndexError: list index out of range
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6b-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:Kylin v10
- Python 版本 / Python version:3.10.5
- 其他相关环境信息 / Other relevant environment information:streamlit==1.27.2,langchain==0.0.335

**Comment by zRzRzRzRzRzRzR** [comment]
并发的话要在fschat实现并发，前端这边是不并发的

**Comment by yph0925** [comment]
> **问题描述 / Bad message format** 用简洁明了的语言描述这个问题 / 多用户并发问答，页面提示Bad message format, Bad 'setIn' index 2 (should be between [0, 1])
> 
> **复现问题的步骤 / Steps to Reproduce**
> 
> 1. 多用户同时登录页面；
> 2. 同时提问不同问题；
> 3. 页面提示Bad message format，后端日志报错
> 
> ```
> File "/you/python/path/streamlit/runtime/scriptrunner/script_runner.py" line 541, in _run_script
>     exec(code, module.__dict__)
> File "/you/project/path/Langchain-Chatchat/webui.py", line 64, in <module>
>     pages[selected_page]["func"](api=api, is_lite=is_lite)
> File "/you/project/path/Langchain-Chatchat/webui_page/dialogue/dialogue.py"
>   chat_box.show_feedback(**feedback_kwargs,
> File "/you/python/path/python310/lib/python3.10/sit-packages/streamlit_chatbox/message.py", line 307, in show_feedback
>   with self._chat_containers[history_index]:
> IndexError: list index out of range
> ```
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：v0.2.7
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6b-32k
> * 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
> * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> * 操作系统及版本 / Operating system and version:Kylin v10
> * Python 版本 / Python version:3.10.5
> * 其他相关环境信息 / Other relevant environment information:streamlit==1.27.2,langchain==0.0.335

同样的报错，这个问题怎么解决

**Comment by Alfer-Feng** [comment]
> 并发的话要在fschat实现并发，前端这边是不并发的

就是前端chat_box.show_feedback点赞点踩功能目前释放的代码是没有并发的，如果要实现并发要自己写，是吗？

**Comment by kfchenhn** [comment]
> > **问题描述 / Bad message format** 用简洁明了的语言描述这个问题 / 多用户并发问答，页面提示Bad message format, Bad 'setIn' index 2 (should be between [0, 1])
> > **复现问题的步骤 / Steps to Reproduce**
> > 
> > 1. 多用户同时登录页面；
> > 2. 同时提问不同问题；
> > 3. 页面提示Bad message format，后端日志报错
> > 
> > ```
> > File "/you/python/path/streamlit/runtime/scriptrunner/script_runner.py" line 541, in _run_script
> >     exec(code, module.__dict__)
> > File "/you/project/path/Langchain-Chatchat/webui.py", line 64, in <module>
> >     pages[selected_page]["func"](api=api, is_lite=is_lite)
> > File "/you/project/path/Langchain-Chatchat/webui_page/dialogue/dialogue.py"
> >   chat_box.show_feedback(**feedback_kwargs,
> > File "/you/python/path/python310/lib/python3.10/sit-packages/streamlit_chatbox/message.py", line 307, in show_feedback
> >   with self._chat_containers[history_index]:
> > IndexError: list index out of range
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **环境信息 / Environment Information**
> > 
> > * langchain-ChatGLM 版本/commit 号：v0.2.7
> > * 是否使用 Docker 部署（是/否）：否
> > * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6b-32k
> > * 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
> > * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> > * 操作系统及版本 / Operating system and version:Kylin v10
> > * Python 版本 / Python version:3.10.5
> > * 其他相关环境信息 / Other relevant environment information:streamlit==1.27.2,langchain==0.0.335
> 
> 同样的报错，这个问题怎么解决

请问这个问题后来解决了吗？

**Comment by Zephyr69** [comment]
同问，同有这个问题。多用户提问除了这个之外好像没啥问题，这是并发还是不并发？

**Comment by xzxjysgd** [comment]
我也同样遇到了这种问题

**Comment by xzxjysgd** [comment]
File "/you/python/path/streamlit/runtime/scriptrunner/script_runner.py" line 541, in _run_script
    exec(code, module.__dict__)
File "/you/project/path/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "/you/project/path/Langchain-Chatchat/webui_page/dialogue/dialogue.py"
  chat_box.show_feedback(**feedback_kwargs,
File "/you/python/path/python310/lib/python3.10/sit-packages/streamlit_chatbox/message.py", line 307, in show_feedback
  with self._chat_containers[history_index]:
IndexError: list index out of range

**Comment by xzxjysgd** [comment]
我也同样遇到了这种问题

**Comment by liduang** [comment]
我也是同样的问题，五个并发报错： Bad 'setIn' index 20 (should be between [0, 3])

**Comment by zhang-zzq** [comment]
请问有解决方法吗

**Comment by yang1111-gif** [comment]
把反馈机制注释就好了

**Comment by zhang-zzq** [comment]
> 把反馈机制注释就好了

可以发一下是那块的代码吗

**Comment by yang1111-gif** [comment]
> > 把反馈机制注释就好了
> 
> 可以发一下是那块的代码吗

dailogue.py中的chta_box.show_feedback注释了

**Comment by zhang-zzq** [comment]
> > > 把反馈机制注释就好了
> > 
> > 
> > 可以发一下是那块的代码吗
> 
> dailogue.py中的chta_box.show_feedback注释了

好的，感谢，我试试
