### ISSUE TITLE
通过prompt让模型格式化输出

### ISSUE THREAD

**Issue by Zou-njust** [chatchat-space/Langchain-Chatchat#2061]
我使用chatglm2-6b-32k，尝试修改prompt让模型以json形式返回答案，在通过axios请求api，即7861/chat/chat，结果直接返回了一个json对象。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102728474/f10654fb-5062-48a0-9a86-47905eede655)
而我在8501端口直接进行llm对话，或者在7861/docx中curl请求，都没有复现这种情况，8501webui中的回答是“以下是提取出来的结果：”后接json形式的文本。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/102728474/bfa37c4d-108a-4dc2-905c-9fa07ed496be)
请问这是有什么机制吗？

**Comment by zRzRzRzRzRzRzR** [comment]
api返回的是json
聊天返回的是str
