### ISSUE TITLE
调用zhipu-api和qwen-api等在线模型时报错TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by 61-113** [chatchat-space/Langchain-Chatchat#2062]
**问题描述 / Problem Description**
1、调用zhipu-api和qwen-api等在线模型时报错TypeError: Caught exception: object of type 'NoneType' has no len()；
2、来回切换模型报错streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key=''`.

**复现问题的步骤 / Steps to Reproduce**
1、在本地试了多个在线模型，配置了正确key（可以确保正确，使用官方demo都能正常对话），只有xinghuo-api可正常对话，其他的比如zhipu-api和qwen-api对话后都报错：
 utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

2、来回切换在线模型后对话，抛出错误：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/81f92705-7241-4c3c-9dde-8f11b9a439a4)

**预期的结果 / Expected Result**
正常对话

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/140b76b8-3232-4dca-93e7-63809f63416c)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：xinghuo-api / zhipu-api / qwen-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu
- Python 版本 / Python version: python3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by 61-113** [comment]
qwen.py文件中传参有问题，api_key没值
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/d28cad02-9d39-48a3-bfbb-1c1b84c37c1c)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/498a3a64-880a-4ff6-8aea-a448f80f2a09)
没有读取到configs/model_config.py下的配置
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/98890690-0db4-410e-9ed8-d730da95add9)

**Comment by amusir** [comment]
我也是相关错误，可以看#2051

**Comment by amusir** [comment]
> 我也是相关错误，可以看#2051

你的第二个问题我也遇到过几次

**Comment by 61-113** [comment]
qwen-api修复：
1、修改model_workers/qwen.py文件，把import dashscope移到外面来，这时在启动会报错：
ModuleNotFoundError: No module named 'dashscope'
直接安装即可：pip install dashscope
避免一直为TypeError: Caught exception: object of type 'NoneType' has no len()这个错误困扰。

2、修改端口，与configs/server_config.py中保持一致：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/6799573b-eb30-49e4-b1ef-4b3101d05265)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2345060/82ff7eec-30f9-4a8c-8d2c-12dae877acc7)

**Comment by 61-113** [comment]
zhipu-api修复方法，同上面qwen-api：
1、修改model_workers/zhipu.py文件，把import zhipuai移到外面来，这时在启动会报错：
ModuleNotFoundError: No module named 'zhipuai'
直接安装即可：pip install zhipuai
避免一直为TypeError: Caught exception: object of type 'NoneType' has no len()这个错误困扰。

**Comment by 61-113** [comment]
> **问题描述 / Problem Description** 1、调用zhipu-api和qwen-api等在线模型时报错TypeError: Caught exception: object of type 'NoneType' has no len()； 2、来回切换模型报错streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key=''`.
> 
> **复现问题的步骤 / Steps to Reproduce** 1、在本地试了多个在线模型，配置了正确key（可以确保正确，使用官方demo都能正常对话），只有xinghuo-api可正常对话，其他的比如zhipu-api和qwen-api对话后都报错： utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
> 
> 2、来回切换在线模型后对话，抛出错误： ![image](https://user-images.githubusercontent.com/2345060/282975036-81f92705-7241-4c3c-9dde-8f11b9a439a4.png)
> 
> **预期的结果 / Expected Result** 正常对话
> 
> **实际结果 / Actual Result** ![image](https://user-images.githubusercontent.com/2345060/282974005-140b76b8-3232-4dca-93e7-63809f63416c.png)
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：v0.2.7
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：xinghuo-api / zhipu-api / qwen-api
> * 使用的 Embedding 模型（moka-ai/m3e-base 等）： moka-ai/m3e-base
> * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> * 操作系统及版本 / Operating system and version: Ubuntu
> * Python 版本 / Python version: python3.10
> * 其他相关环境信息 / Other relevant environment information:
> 
> **附加信息 / Additional Information** 添加与问题相关的任何其他信息 / Add any other information related to the issue.

当每个模型对话都正常时，来回切换模型在对话就没有报错了，即第2个问题也不存在了

**Comment by Leweibo** [comment]
问题解决了吗？
怎么Closed了？

**Comment by 61-113** [comment]
> 问题解决了吗？ 怎么Closed了？

按照上面的方法来，试了可以正常用

**Comment by zdhmd5** [comment]
我在本地使用的chatglm2-6b，也有相同的问题。

**Comment by GAllllong** [comment]
@61-113 谢谢您，这边已经调通了，chatchat027版本貌似需要安装qianfan==0.1.0，就可以了，之前我的依赖库不兼容。

**Comment by JustDoItToo** [comment]
@61-113 我按照这个方法修改了，还是会报这个错，请问还可能是什么原因导致的呀？我这边智谱的没问题，千问和百川的会报这个错误

> qwen-api修复： 1、修改model_workers/qwen.py文件，把import dashscope移到外面来，这时在启动会报错： ModuleNotFoundError: No module named 'dashscope' 直接安装即可：pip install dashscope 避免一直为TypeError: Caught exception: object of type 'NoneType' has no len()这个错误困扰。
> 
> 2、修改端口，与configs/server_config.py中保持一致： ![image](https://private-user-images.githubusercontent.com/2345060/282985545-6799573b-eb30-49e4-b1ef-4b3101d05265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzM0NDgsIm5iZiI6MTcwMjQzMzE0OCwicGF0aCI6Ii8yMzQ1MDYwLzI4Mjk4NTU0NS02Nzk5NTczYi1lYjMwLTQ5ZTQtYjFlZi00YjMxMDFkMDUyNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDIwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA4MGQ4ZjMxYmRhNjY5ZGVmZjZlMzYzZTQ1Y2E2ODZmYzA2N2YxY2Q4ODRmMzBjODFkYTQwMTgyMTQyNDUzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u6ZxD1SkqyCgw3Buy0HypFoT48TcEcHHNukBFpdsgnI) ![image](https://private-user-images.githubusercontent.com/2345060/282985781-82ff7eec-30f9-4a8c-8d2c-12dae877acc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzM0NDgsIm5iZiI6MTcwMjQzMzE0OCwicGF0aCI6Ii8yMzQ1MDYwLzI4Mjk4NTc4MS04MmZmN2VlYy0zMGY5LTRhOGMtOGQyYy0xMmRhZTg3N2FjYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDIwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFlZmRkMDYyYWYxM2Q2MzE5ODhiYThmZmFlNjk5OTc0ZGE2NGEwNTA2NGU1NzBiM2Q4YmZmMGZiYjc5MzFkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XP8u_KEi7tZVxFIrUq5N-4YwnH7lqO8MrXGHmT543g0)

**Comment by supersoulsoul** [comment]
> @61-113 我按照这个方法修改了，还是会报这个错，请问还可能是什么原因导致的呀？我这边智谱的没问题，千问和百川的会报这个错误
> 
> > qwen-api修复： 1、修改model_workers/qwen.py文件，把import dashscope移到外面来，这时在启动会报错： ModuleNotFoundError: No module named 'dashscope' 直接安装即可：pip install dashscope 避免一直为TypeError: Caught exception: object of type 'NoneType' has no len()这个错误困扰。
> > 2、修改端口，与configs/server_config.py中保持一致： ![image](https://private-user-images.githubusercontent.com/2345060/282985545-6799573b-eb30-49e4-b1ef-4b3101d05265.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzM0NDgsIm5iZiI6MTcwMjQzMzE0OCwicGF0aCI6Ii8yMzQ1MDYwLzI4Mjk4NTU0NS02Nzk5NTczYi1lYjMwLTQ5ZTQtYjFlZi00YjMxMDFkMDUyNjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDIwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDA4MGQ4ZjMxYmRhNjY5ZGVmZjZlMzYzZTQ1Y2E2ODZmYzA2N2YxY2Q4ODRmMzBjODFkYTQwMTgyMTQyNDUzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.u6ZxD1SkqyCgw3Buy0HypFoT48TcEcHHNukBFpdsgnI) ![image](https://private-user-images.githubusercontent.com/2345060/282985781-82ff7eec-30f9-4a8c-8d2c-12dae877acc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MzM0NDgsIm5iZiI6MTcwMjQzMzE0OCwicGF0aCI6Ii8yMzQ1MDYwLzI4Mjk4NTc4MS04MmZmN2VlYy0zMGY5LTRhOGMtOGQyYy0xMmRhZTg3N2FjYzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMDIwNTQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGFlZmRkMDYyYWYxM2Q2MzE5ODhiYThmZmFlNjk5OTc0ZGE2NGEwNTA2NGU1NzBiM2Q4YmZmMGZiYjc5MzFkNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.XP8u_KEi7tZVxFIrUq5N-4YwnH7lqO8MrXGHmT543g0)

请问你这个问题解决了吗？我遇到同样的问题，是0.2.6版本的。

**Comment by JerryYao80** [comment]
我在 0.2.9的 chatglm3版本上也出现了这个问题

**Comment by ZhichaoOuyang** [comment]
> 我在本地使用的chatglm2-6b，也有相同的问题。

解决了吗，我也是一样的问题

**Comment by ZhichaoOuyang** [comment]
> 我在 0.2.9的 chatglm3版本上也出现了这个问题

请问怎么解决

**Comment by xzx879886595** [comment]
修改model_workers/zhipu.py文件，把import zhipuai移到外面来.我看了一下zhipu.py这个文件，没找到import zhipuai在哪里？

**Comment by codermama** [comment]
我也没看 到 我把zhipu.py stream 设置成 了true  就是报这个 错  但是false  就是正常运行

**Comment by QuanSir07** [comment]
上面的都试了一遍，也没把zhipu跑通，依旧报这个错。。。。

**Comment by hosea7456** [comment]
> 上面的都试了一遍，也没把zhipu跑通，依旧报这个错。。。。

我也是，不起作用
