### ISSUE TITLE
[BUG] 较大的知识库（CSV）进行向量化的过程中无缘无故增加了几次线程

### ISSUE THREAD

**Issue by a656418zz** [chatchat-space/Langchain-Chatchat#2063]
**问题描述 / Problem Description**
较大的知识库进行向量化的过程中无缘无故增加了几次线程

**复现问题的步骤 / Steps to Reproduce**
1. 因为知识库较大，streamlit只支持200mb，所以新建文件夹后直接将文件放入 name/content/ 文件夹中
2. 回到webui区域，选择文件单击生成知识库文件

**预期的结果 / Expected Result**
在终端看过程应该只有一个【生成知识库文件的进度条】

**实际结果 / Actual Result**
在生成过程中额外产生多个【生成知识库文件的进度条】，并且执行时间延长数倍

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss

**附加信息 / Additional Information**
图片在这
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25815600/01f1b4dd-93bf-461e-ba23-b68bcbd0049f)
投issue期间，又增加了一条
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25815600/e7dd6ce7-1519-418f-966a-e27cfd222acc)

昨天已经踩过这个坑了，以为是会覆盖，实际上是内容叠加，昨天的经验是3条进度条，所以数据量翻了3倍

**Comment by 61-113** [comment]
碰到同样的问题，使用的是100M左右的pdf

**Comment by a656418zz** [comment]
> 碰到同样的问题，使用的是100M左右的pdf

复盘了一下，昨天还有把20M的csv数据丢进去也遇到了这个问题，但因为数据量小 所以可以盯着第一次结束就直接手动取消，所以无意间规避了这个问题，可能不是和较大知识库有关？

**Comment by qianlir** [comment]
碰到一样的问题2.8M csv

**Comment by danerlt** [comment]
+1 ，我也遇到了这个问题，上传的pdf文件，大小大约120M

**Comment by liunux4odoo** [comment]
请按以下步骤分别测试看看：
1、不要用webui，直接到 ip:7861/docs/knowledge_base/upload_docs 接口上传同样的文件
2、更新 streamlit 到1.28.2 然后再到webui上传同样的文件。

streamlit 1.27-1.28 早期版本似乎容易出现自动rerun的问题，相当于点击按钮的时候API会调用多次。
另外，大文件不建议通过webui进行入库操作，特别容易超时。

**Comment by Gzj369** [comment]
@liunux4odoo 您好，我现在需要将60M的csv文件作为知识库的语料上传到Langchain-Chatchat 0.2.9中，结果查看日志，接口返回了200，实际上向量化总是不成功，除了webui外，我也尝试了 ip:7861/docs/knowledge_base/upload_docs 接口上传同样的文件，发现向量化也不行，如下图所示：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/6c908b37-10fd-4394-96e7-4ca74fc64785)
实际上我看linux服务器下对应路径是存在output5.csv这个文件的，不知道为什么会“加载文档时出错：Error loading”

麻烦您有时间帮忙看看，非常感谢您
