### ISSUE TITLE
【建议】模型路径扫描

### ISSUE THREAD

**Issue by favouriter** [chatchat-space/Langchain-Chatchat#2066]
**每次升级修改本地模型路径很麻烦，建议增加一个模型目录扫描功能**
在模型配置文件中加一个扫描方法
def find_model(sub_path):
    root_path = pathlib.Path(f'./models/{sub_path}')
    return {p.name: p.absolute() for p in root_path.glob('./*') if '__py' not in p.name}

** 然后根据模型路径修改相关模型 **
for k in MODEL_PATH.keys():
    MODEL_PATH[k].update(find_model(k))

**Comment by favouriter** [comment]
我发现前面已经声明了模型路径
MODEL_ROOT_PATH = "./models"

扫描方法可以复用这个声明
def find_model(sub_path):
    root_path = pathlib.Path(f'{MODEL_ROOT_PATH}/{sub_path}')
    return {p.name: p.absolute() for p in root_path.glob('./*') if '__py' not in p.name}

**Comment by favouriter** [comment]
```python
#我发现前面已经声明了模型路径
MODEL_ROOT_PATH = "./models"

#扫描方法可以复用这个声明
def find_model(sub_path):
    root_path = pathlib.Path(f'{MODEL_ROOT_PATH}/{sub_path}')
    return {p.name: p.absolute() for p in root_path.glob('./*') if '__py' not in p.name}
```

**Comment by zRzRzRzRzRzRzR** [comment]
❤️ Mark，之后我们讨论以下，感谢建议
