### ISSUE TITLE
在win、ubuntu下都出现这个错误：attributeerror: 't5forconditionalgeneration' object has no attribute 'stream_chat'

### ISSUE THREAD

**Issue by ghhuang483** [chatchat-space/Langchain-Chatchat#207]
在win、ubuntu。下载完模型后，没办法修改代码以执行本地模型，每次都要重新输入路径； LLM 模型、Embedding 模型支持也都在官网下的，在其他项目（wenda）下可以使用

**Comment by imClumsyPanda** [comment]
请问llm模型使用的是哪一个

ghhuang483 ***@***.***>于2023年4月29日 周六16:46写道：

**Comment by ghhuang483** [comment]
ernie-tiny、ernie-base、text2vec-base、text2vec+ChatYuan-large-v2都不行

**Comment by imClumsyPanda** [comment]
chatyuan目前适配有点问题 将会在近期修复 glm目前可以跑通

ghhuang483 ***@***.***>于2023年4月29日 周六17:03写道：

**Comment by cxgreat2014** [comment]
同样的问题，期待修复

**Comment by ColorfulDick** [comment]
我也遇到了这个问题，现在有啥办法自己修复下吗

**Comment by imClumsyPanda** [comment]
@ColorfulDick 可以看一下chatyuan的流式调用方式，在chatglm_llm中增加个模型判断，如果是chatyuan模型则调用chatyuan可实现流式的函数，或直接参考chatglm_llm新建类chatyuan_llm
