### ISSUE TITLE
startup一键启动，应该是成功了。但是只能访问FastAPI Docs 界面，WEB UI界面打不开。

### ISSUE THREAD

**Issue by JessieZhao0111** [chatchat-space/Langchain-Chatchat#2070]
**问题描述 / Problem Description**
startup一键启动，应该是成功了。但是只能访问FastAPI Docs 界面，WEB UI界面打不开。

**复现问题的步骤 / Steps to Reproduce**
执行python startup.py -a
显示应该是已经启动成功
FastAPI Docs 界面能成功进入，但是WEB UI进不去。
linux服务器本地进WEB UI，显示“无法连接到x.x.x.x:8501服务器的链接”；
windows远程访问WEB UI，显示“X.X.X.X拒绝了我们的远程请求”

**预期的结果 / Expected Result**
WEB UI正常进入

**实际结果 / Actual Result**
打不开页面
**环境信息 / Environment Information**
- langchain-Chatchat 版本：v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:Linux-5.4.0-150-generic-x86_64-with-glibc2.27.
- Python 版本 / Python version:3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0]
- 其他相关环境信息 / Other relevant environment information:
公司网络
**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by guiniao** [comment]
@JessieZhao0111 ，你好，你用的transformer是哪个版本，我用的4.34，执行这个的时候python startup.py -a，报错AttributeError: 'ChatGLMTokenizer' object has no attribute 'tokenizer'

**Comment by zcyc** [comment]
问题和 #2178 一样，跑起来需要回车一下。
