### ISSUE TITLE
[BUG] 召回片段过短，导致模型推理较差

### ISSUE THREAD

**Issue by satsun-gaga** [chatchat-space/Langchain-Chatchat#2072]
使用ChineseRecursiveTextSplitter分词器，Embbedings模型为m3e-base @ cpu，文档为html形式，单篇文章时召回效果较佳，多篇文章时召回效果很差，进而导致模型推理的效果很差。

比如文章如下：
    标题：3.  action = 2 和 action = 4 现在有什么差别？
    正文：两者都是xxx，最终效果上没有差别
               不过若xxx，往往使用的是 xxx。

问题：xxx和xxx的区别是什么

单篇文章时，召回和回答表现都较佳
一旦加入别的文章，召回效果很差，多篇文章召回内容：
<已知信息>3.  action = 2 和 action = 4 现在有什么差别？
2.  为什么将 action = 2 改成了xxx？
"action": 2,
"action": 1,
"action": 0,
</已知信息>

可以调整哪些参数进行优化，小白求教～

**Comment by ilovesouthpark** [comment]
添加print打印出splitter的结果看看分析一下，ChineseRecursiveTextSplitter，还有ChineseTextSplitter都是可以自定义的，所以调整一下看看。

**Comment by yhfgyyf** [comment]
server/kb_config.py中修改CHUNK_SIZE 先改成500实时，model_config.py中embedding模型换bge-large-zh-v1.5（要下权重），m3e-base的embedding效果真的不好

**Comment by zRzRzRzRzRzRzR** [comment]
在讨论中有类似的问题，该issue关闭，在Discussion中讨论
