### ISSUE TITLE
部署后本地的m3e-base embedding的openai格式/v1/embeddings的接口请求无效

### ISSUE THREAD

**Issue by Mr-IT007** [chatchat-space/Langchain-Chatchat#2075]
![m3e](https://github.com/chatchat-space/Langchain-Chatchat/assets/39551480/a1490f78-5ec2-4426-8cc9-be2d38bef135)

**Comment by zRzRzRzRzRzRzR** [comment]
这是LLM模型的embed不是embed模型的embed
