### ISSUE TITLE
[BUG] 4GB的txt文件，使用faiss和milvus构建知识库，均会报错killed

### ISSUE THREAD

**Issue by LiuNull** [chatchat-space/Langchain-Chatchat#2076]
如题，当知识库较大时，会报错killed。已经看了几个issue，本来理解为faiss对于大文件支持不好，但是替换为milvus仍然报错，想请教是什么原因？该怎么解决呢

**Comment by LiuNull** [comment]
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
检查内存炸了吗？
这数据也太大了

**Comment by zRzRzRzRzRzRzR** [comment]
直接上传数据库就算能成功效果也很差，目前最佳实践还是人工来进行预处理
分成多个很小的markdown格式化文件，效果最好
