### ISSUE TITLE
[BUG] torch2.1.0版本和xformers、vllm的版本不匹配（cuda11.8版本）

### ISSUE THREAD

**Issue by zzflybird** [chatchat-space/Langchain-Chatchat#2080]
**问题描述 / Problem Description**
使用`pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118`安装torch2.1.0版本的，而xformers和vllm会覆盖原有torch，安装2.0.1版本的torch。

可以使用命令`pip install xformers==0.0.22.post4 --index-url https://download.pytorch.org/whl/cu118`安装cu118的xformers，匹配2.1.0的torch，**但是vllm在 https://download.pytorch.org/whl/cu118 中没有对应的版本**。

请问`vllm>=0.2.0; sys_platform == "linux"`这个包依赖是必须的吗？

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
顺利完成安装
**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
vllm安装依赖包，覆盖原有torch包
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7
- 是否使用 Docker 部署（是/否）：否
- 操作系统及版本 / Operating system and version: ubuntu 22
- Python 版本 / Python version: 3.10

**Comment by zRzRzRzRzRzRzR** [comment]
vllm不是必须的，可以不装

**Comment by sing-potato** [comment]
torch2.1.0 可以装xformers 0.0.23
