### ISSUE TITLE
[BUG]  baichuan2-13B-chat模型一直卡在loading 0%状态

### ISSUE THREAD

**Issue by Jayzhang1995** [chatchat-space/Langchain-Chatchat#2081]
**问题描述 / Problem Description**
baichuan2-13B-chat模型一直卡在loading 0%状态, 模型文件确认是没问题的，用streamlit可以直接启动

<img width="1415" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/24266745/feab06b7-7bb2-435a-8255-9d4643f9f3d8">

model_config.py的配置,只改动了这两个位置
LLM_MODELS = ["baichuan2-13b"]
"llm_model": {
        "baichuan2-13b": "/root/.cache/huggingface/modules/transformers_modules/baichuan-inc/Baichuan2-13B-Chat",

**Comment by Jayzhang1995** [comment]
直接安装requirements.txt的依赖后会出现报错，网上解决方案是降级transformers==4.33.1 and tokenizers==0.13.3。但是降级后就一直卡在loading了
https://github.com/baichuan-inc/Baichuan2/issues/251


<img width="1419" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/24266745/e8e2df06-56d4-403a-819d-e174a2ba5cce">

**Comment by zRzRzRzRzRzRzR** [comment]
你这不是卡啊，你这都报错了

**Comment by Jayzhang1995** [comment]
> 你这不是卡啊，你这都报错了

这是安装两种版本的输出结果，一个不报错卡loading，一个报错

**Comment by zRzRzRzRzRzRzR** [comment]
查看一下内存和显卡的调用情况，我记得第一次载入百川模型需要一定时间，确定你的内存超过 32G

**Comment by Jayzhang1995** [comment]
> 查看一下内存和显卡的调用情况，我记得第一次载入百川模型需要一定时间，确定你的内存超过 32G

显卡是A40,运行startup.py后，没有程序在调用，内存的话16G， 但是我用百川官方那个脚本跑起来正常的。

**Comment by zRzRzRzRzRzRzR** [comment]
百川官方应该是最小能用的版本，他们跑的起来不一定跑的起来，接着其他模型如果能用就是百川模型问题
