### ISSUE TITLE
[BUG] 0.27 知识库模式下Prompt指令貌似不会生效

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#2082]
已经在prompt中要求不得编造内容，但是在回答过程中，如果没找到相关文档，大模型会根据自身能力编造答案

![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/6ae07cd6-2e79-4bfc-aa4c-d5d22309a2e1)

**Comment by qianlir** [comment]
加一句：瞎编乱造，给你断电。
ps：把温度降为0试试

**Comment by tanglu86** [comment]
> 加一句：瞎编乱造，给你断电。 ps：把温度降为0试试

温度已经是0.1 在0.26版本下是可以通过prompt有效抑制的，但是0.27完全没有效果了

**Comment by zRzRzRzRzRzRzR** [comment]
有没有生效仅需要看有没有成功传入模型就行，具体有没有生效那是模型的问题了

**Comment by lurenyi4** [comment]
老哥是怎么解决这个问题的呢

**Comment by zixiaotan21** [comment]
同样遇到这个问题，prompt指令似乎效果不大，想问问各位大佬解决了吗
