### ISSUE TITLE
问答打断功能

### ISSUE THREAD

**Issue by SnowyLchen** [chatchat-space/Langchain-Chatchat#2084]
若进行问答中途刷新打断回答，此时再次输入，连续2-3次后，回复速度明显减慢，甚至不回答了，可否能解决？

**Comment by zRzRzRzRzRzRzR** [comment]
提供一下最小复现和PR
以及更多系统信息

**Comment by SnowyLchen** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/9de9664a-219c-44fc-be17-739dfb340e13

**Comment by SnowyLchen** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52272752/b0753d40-2cc3-46b8-97f4-4078b1692a06)

32G显存 千问14b模型 40内存

**Comment by zRzRzRzRzRzRzR** [comment]
检查内存和显存的情况，会不会是历史没清空显存往上涨爆了
