### ISSUE TITLE
[FEATURE] 可以返回tokens总数吗

### ISSUE THREAD

**Issue by Lijia0** [chatchat-space/Langchain-Chatchat#2085]
**功能描述 / Feature Description**
与知识库对话的接口可以返回总tokens消耗吗？方便费用统计。

使用zhipu-api 的event.meta中有'{"task_status":"SUCCESS","usage":{"completion_tokens":212,"prompt_tokens":3,"total_tokens":215},"task_id":"8107272798747869504","request_id":"8107272798747869504"}'，这个total_tokens该怎么传到langchain中？求助

**Comment by zRzRzRzRzRzRzR** [comment]
由于您的Issue不符合 [Issue 规范](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E5%81%9A%E5%87%BA%E8%B4%A1%E7%8C%AE#issue-%E8%A7%84%E8%8C%83) 该issue被关闭
