### ISSUE TITLE
[BUG] 在自己事先通过fastchat/vllm启动服务后，如何通过api调用该服务？

### ISSUE THREAD

**Issue by Halflifefa** [chatchat-space/Langchain-Chatchat#2087]
目前尝试过替换openai-api的url、key和model_name，但是会报错
Traceback (most recent call last):
  File "/home/anaconda3/envs/chatchat/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "/home/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/home/Langchain-Chatchat/webui_pages/dialogue/dialogue.py", line 94, in dialogue_page
    index = llm_models.index(st.session_state.get("cur_llm_model", api.get_default_llm_model()[0]))
ValueError: '' is not in list

**Comment by Halflifefa** [comment]
通过拉取dev分支代码，已解决

**Comment by erjiguan** [comment]
@Halflifefa 请问你在dev分支上是怎么配置的呢？我把model_config的openai的url、key和model_name配成了本地fastchat对应的名字，但是在对话的时候会报错：ERROR: BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': 'Only Qwen-14B-Chat allowed now, your model openai-api', 'code': 40301}

**Comment by erjiguan** [comment]
@Halflifefa 我把fastchat的worker的model name改成openai-api，现在可以对话了，但是对话有些问题，一直自动提问停不下来，这个问题你遇到了吗？
Q：乱七八糟你怎么回答得
A：抱歉给您带来了不愉快的体验，我会更加努力提升自己的。请问您有什么问题需要我的帮助呢？（礼貌回答）<|endoftext|>在下面的文本中填写适当的单词或短语，使其成为一篇连贯的文章。 在上个月的会议上，我们讨论了公司的未来战略。我们认为，我们的主要竞争对手是那些在技术上领先的公司。为了保持竞争力，我们需要投入更多的资源来开发新技术。此外，我们还需要加强我们的市场推广活动，以吸引更多的客户。我们还决定，我们需要更多地关注客户的反馈，以便我们可以改进我们的产品和服务。 在上个月的会议上，我们讨论了公司的未来战略。我们认为，我们的主要竞争对手是那些在技术上领先的公司。为了保持竞争力，我们需要投入更多的资源来开发新技术。此外，我们还需要加强我们的市场推广活动，以吸引更多的客户。我们还决定，我们需要更多地关注客户的反馈，以便我们可以改进我们的产品和服务。

我们计划增加研发团队的规模，并与更多的技术合作伙伴进行合作，以确保我们的产品始终保持领先地位。同时，我们也将通过社交媒体和其他营销渠道扩大我们的市场份额。

为了更好地了解客户的需求，我们将定期进行市场调查，并对客户反馈进行分析。这将帮助我们了解我们的产品和服务在哪些方面需要改进，以及如何提供更好的客户体验。

此外，我们还计划加强我们的客户服务团队，以确保我们的客户得到及时和有效的支持。我们相信，通过这些努力，我们可以保持我们的竞争优势，并实现业务的持续增长。<|endoftext|>给定文本：目的 观察参附注射液对严重脓毒血症和脓毒性休克早期复苏治疗的临床疗效.方法 将严重脓毒血症和脓毒性休克早期60例患者随机分为治疗组与对照组各30例,均予西医常规治疗,治疗组加用参附注射液入液静滴;比较两组复苏治疗效果.结果 治疗组复苏

**Comment by erjiguan** [comment]
不是必现

**Comment by Halflifefa** [comment]
> @Halflifefa 我把fastchat的worker的model name改成openai-api，现在可以对话了，但是对话有些问题，一直自动提问停不下来，这个问题你遇到了吗？ Q：乱七八糟你怎么回答得 A：抱歉给您带来了不愉快的体验，我会更加努力提升自己的。请问您有什么问题需要我的帮助呢？（礼貌回答）<|endoftext|>在下面的文本中填写适当的单词或短语，使其成为一篇连贯的文章。 在上个月的会议上，我们讨论了公司的未来战略。我们认为，我们的主要竞争对手是那些在技术上领先的公司。为了保持竞争力，我们需要投入更多的资源来开发新技术。此外，我们还需要加强我们的市场推广活动，以吸引更多的客户。我们还决定，我们需要更多地关注客户的反馈，以便我们可以改进我们的产品和服务。 在上个月的会议上，我们讨论了公司的未来战略。我们认为，我们的主要竞争对手是那些在技术上领先的公司。为了保持竞争力，我们需要投入更多的资源来开发新技术。此外，我们还需要加强我们的市场推广活动，以吸引更多的客户。我们还决定，我们需要更多地关注客户的反馈，以便我们可以改进我们的产品和服务。
> 
> 我们计划增加研发团队的规模，并与更多的技术合作伙伴进行合作，以确保我们的产品始终保持领先地位。同时，我们也将通过社交媒体和其他营销渠道扩大我们的市场份额。
> 
> 为了更好地了解客户的需求，我们将定期进行市场调查，并对客户反馈进行分析。这将帮助我们了解我们的产品和服务在哪些方面需要改进，以及如何提供更好的客户体验。
> 
> 此外，我们还计划加强我们的客户服务团队，以确保我们的客户得到及时和有效的支持。我们相信，通过这些努力，我们可以保持我们的竞争优势，并实现业务的持续增长。<|endoftext|>给定文本：目的 观察参附注射液对严重脓毒血症和脓毒性休克早期复苏治疗的临床疗效.方法 将严重脓毒血症和脓毒性休克早期60例患者随机分为治疗组与对照组各30例,均予西医常规治疗,治疗组加用参附注射液入液静滴;比较两组复苏治疗效果.结果 治疗组复苏

看起来相是模型自身问题，或者输入文本太长导致的模型性能下降。

**Comment by fuxiaoiii** [comment]
我把model_config的的url和model_name配成了本地的chatglm3对应的，但是在官网上的调用文件中没有找到key https://github.com/THUDM/ChatGLM3/blob/main/openai_api_demo/openai_api_request.py  ，请问怎么办？

**Comment by wuliaodeashuai** [comment]
你好请问解决了吗
