### ISSUE TITLE
[BUG]用智谱在线api 添加至向量库报错AnyIO worker thread

### ISSUE THREAD

**Issue by liulangjita** [chatchat-space/Langchain-Chatchat#2095]
通过init_database添加没问题，启动项目后，通过知识库管理添加报错AnyIO worker thread
跟踪代码发现在server/model_workers/base.py的ApiModelWorker __init__函数中self.semaphore = asyncio.Semaphore(self.limit_worker_concurrency)没有执行下去

**Comment by zRzRzRzRzRzRzR** [comment]
提供一下配置和具体的复现代码

**Comment by liulangjita** [comment]
我把self.semaphore = asyncio.Semaphore(self.limit_worker_concurrency)注释就暂时能用了
