### ISSUE TITLE
[FEATURE] knowledge_based_chatglm.py: renamed or missing?

### ISSUE THREAD

**Issue by jason95054** [chatchat-space/Langchain-Chatchat#210]
Not found. Was it renamed? Or, is it missing? How can I get it?

**Comment by imClumsyPanda** [comment]
Configuration was moved to configs/model_config.py and other codes moved to
cli_demo.py

jason95054 ***@***.***>于2023年5月1日 周一03:28写道：

**Comment by jason95054** [comment]
Thanks for the reply. I guess README_en.md and langchain-ChatGLM_README.md are/were stale.

**Comment by imClumsyPanda** [comment]
Yeah you’re right. I’ll update soon.

jason95054 ***@***.***>于2023年5月1日 周一09:14写道：
