### ISSUE TITLE
推理并发量如何提升

### ISSUE THREAD

**Issue by ZEROYXY** [chatchat-space/Langchain-Chatchat#2102]
实测，利用K6工具模拟多用户交互进行压测，发现于服务器上使用A100进行推理时，单卡可达并发量不到50.请问该状况正常吗？如果不适用vllm如何进一步提升并发

**Comment by zRzRzRzRzRzRzR** [comment]
huggingface 14B可能的，建议用一些推理工具来加速，比如vllm和trt，不适用vllm的模型只能自己写推理加速
