### ISSUE TITLE
[BUG] 新手想体验一下这个agent功能，但总是说“输入的格式不对。 Final Answer: 请提供正确的输入格式，我才能为您查询”

### ISSUE THREAD

**Issue by SolarKnight1** [chatchat-space/Langchain-Chatchat#2103]
有大佬指教一下小弟什么才是正确的输入格式，我主要想使用的是知识库的工具

**Comment by zRzRzRzRzRzRzR** [comment]
那你只能接GPT4了，正确的输入格式这样的
模型调用Agent之后，会有一个chain，这个chain会告诉模型吧用户输入的内容整合成一个dict，然后按照dict去查，但是除了gpt4基本没有能力能做第二次chain，整合出来的dict都是错的
