### ISSUE TITLE
上传了文档，但是对话里的LLM还是没有相关信息

### ISSUE THREAD

**Issue by ijiami-01** [chatchat-space/Langchain-Chatchat#2104]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129148313/e7827eb4-2006-44d5-9361-ea1fbabe912f)

**Comment by zRzRzRzRzRzRzR** [comment]
大概率是没有搜到，如果相关内容是空的，就是没搜到，搜到了没回答就是llm的问题
