### ISSUE TITLE
遇到一点小问题[BUG] requirments_api.txt中accelerate未指定版本

### ISSUE THREAD

**Issue by shishi11** [chatchat-space/Langchain-Chatchat#2105]
遇到一点小问题[BUG] requirments_api.txt中accelerate未指定版本，
执行 python init_database.py --recreate-vs时报错说  sentence_transformers不能加载，后跟踪发现是
accelerate包要求》=0.20，原来安装了0.19.1，重新升级到0.24.1后正常了。
也可能与sentence_transformers自己的升级有关，未深入研究。

**Comment by zRzRzRzRzRzRzR** [comment]
accelerate安装最新版最佳
