### ISSUE TITLE
[BUG] 多轮对话不生效？上下文无法形成关联

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#2109]
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/38269740/5a15c323-1f3e-4dcf-baff-90c23749d6b8)

使用百川2，历史对话轮数20
使用测试数据集进行提问
Q1中已经明确查询的是一个叫做回溯的数据库信息
Q2进一步查询端口号就无法形成关联了
Q3补充完整信息重新提问又匹配上

**Comment by zRzRzRzRzRzRzR** [comment]
知识库的历史对话能力很差，虽然我们在langchain中确实传了历史，但是效果确实很差，我们还需要关注一下

**Comment by lhyscau** [comment]
> 知识库的历史对话能力很差，虽然我们在langchain中确实传了历史，但是效果确实很差，我们还需要关注一下

请问这是因为prompt设置的问题吗？既需要关注历史内容，又需要关注已知信息。我认为目前默认的prompt可能存在一些问题
