### ISSUE TITLE
sudo apt-get install -y nvidia-container-toolkit-base执行报错

### ISSUE THREAD

**Issue by googlebox007** [chatchat-space/Langchain-Chatchat#211]
**问题描述 / Problem Description**
环境：windows11下的wls中的ubuntu22.04.6ltsc
描述：在终端执行sudo apt-get install -y nvidia-container-toolkit-base
系统报错
**复现问题的步骤 / Steps to Reproduce**
$ sudo apt-get install -y nvidia-container-toolkit-base
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package nvidia-container-toolkit-base

**解决方案/ salusion**
根据错误提示,系统无法找到nvidia-container-toolkit-base这个包。这通常有以下几种原因:
1. 您的Ubuntu系统源中实际上并没有这个包。您可以尝试更换系统源,选择一个包含更多包的源,比如Ubuntu官方源等。
2. 您的Ubuntu系统还没有启用CUDA仓库。需要执行以下命令来启用:
3. bash
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
sudo add-apt-repository "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/ /"
sudo apt-get update
根据我的ubuntu版本，上述命令的替换为
 sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/3bf863cc.pub
sudo add-apt-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/ /"
![image](https://user-images.githubusercontent.com/46581796/235389934-67d587ad-3371-46c2-9c58-1b57a0c901c3.png)
4.sudo apt-get update
5.sudo apt-get install -y nvidia-container-toolkit-base
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nvidia-container-toolkit-base
0 upgraded, 1 newly installed, 0 to remove and 16 not upgraded.
Need to get 2123 kB of archives.
After this operation, 9508 kB of additional disk space will be used.
Get:1 https://developer.download.nvidia.cn/compute/cuda/repos/ubuntu2204/x86_64  nvidia-container-toolkit-base 1.13.1-1 [2123 kB]
Fetched 2123 kB in 1s (2331 kB/s)
Selecting previously unselected package nvidia-container-toolkit-base.
(Reading database ... 24485 files and directories currently installed.)
Preparing to unpack .../nvidia-container-toolkit-base_1.13.1-1_amd64.deb ...
Unpacking nvidia-container-toolkit-base (1.13.1-1) ...
Setting up nvidia-container-toolkit-base (1.13.1-1) ...

成功

**Comment by Nicole19960319** [comment]
这个能跳过安装docker,直接基于本地模型去用吗？Docker重启一直出错，无法进行下去，感觉像个鸡肋
