### ISSUE TITLE
知识库页面文件管理

### ISSUE THREAD

**Issue by auroralzone** [chatchat-space/Langchain-Chatchat#2111]
文件太多不好管理，有时候，还会页面卡死

<img width="800" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/8601f0ea-60aa-4773-a8cb-f5c58afa39ef">

<img width="802" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/1275504c-2a94-4753-9ba6-466c4769dfcc">

**Comment by zRzRzRzRzRzRzR** [comment]
目前开源方案是针对小文档的，太多文档确实可能会卡死，预计在之后进行改善
