### ISSUE TITLE
[FEATURE] 快速修改info.db中绝对路径的前缀

### ISSUE THREAD

**Issue by Lu0Key** [chatchat-space/Langchain-Chatchat#2114]
**功能描述 / Feature Description**
希望能有一个快速修改knowledge_base/info.db中绝对路径的方式
因为尝试将完成的知识库和自己修改的项目发给别人，发现会有报错，排查发现应该是info.db中存的路径都是绝对路径，换一台机器就无法使用了，如果重新构建知识库有时候需要的时间很长，因此需要此功能

**解决的问题 / Problem Solved**
方便用户将项目迁移到别的机器上

**实现建议 / Implementation Suggestions**
在config里配置项目路径的前缀，或者提供一个脚本根据当前路径刷新indo.db 中那些绝对路径的前缀

**替代方案 / Alternative Solutions**

**其他信息 / Additional Information**

**Comment by zRzRzRzRzRzRzR** [comment]
感谢你的意见，我们已经支持了这个内容
