### ISSUE TITLE
[FEATURE] 请问支持钉钉对接吗？

### ISSUE THREAD

**Issue by yinmin2020** [chatchat-space/Langchain-Chatchat#2115]
**功能描述 / Feature Description**
我希望使用本地自建的[Langchain-Chatchat对接钉钉机器人

**解决的问题 / Problem Solved**
实现钉钉群机器人提供交互

**实现建议 / Implementation Suggestions**
请问现在的版本中有没有通过配置钉钉机器人WEBHOOK的方式来实现的配置文档？

**Comment by zRzRzRzRzRzRzR** [comment]
需要自己写适配，可以基于我们的api写

**Comment by faterlee** [comment]
> 需要自己写适配，可以基于我们的api写

@zRzRzRzRzRzRzR 请问基于哪个api实现？
