### ISSUE TITLE
在试百度千帆LLM和EMBED线上模式[BUG] qianfan.py里代码有误，先改造了

### ISSUE THREAD

**Issue by shishi11** [chatchat-space/Langchain-Chatchat#2117]
**问题描述 / Problem Description**
一方面代码 写错了，一方面embed有一个最大batch_size=16，超过会报错。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python init_database.py --recreate-vs

2. 问题出现 / 不能生成embedding_vector
3. 暂时先照着千问的代码改造了一下 do_embeddings 里面，部分代码如下
        url = f"https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/embeddings/{embed_model}?access_token={access_token}"
        # 这里有一个问题，最大的batch_size=16，但测试时用了23及以上，导致不能返回结果
        '''这是千问的代码，可能运行过
        result = []
        i = 0
        while i < len(params.texts):
            texts = params.texts[i:i+25]
            resp = dashscope.TextEmbedding.call(
                model=params.embed_model or self.DEFAULT_EMBED_MODEL,
                input=texts, # 最大25行
                api_key=params.api_key,
            )
            if resp["status_code"] != 200:
                return {"code": resp["status_code"], "msg": resp.message}
            else:
                embeddings = [x["embedding"] for x in resp["output"]["embeddings"]]
                result += embeddings
            i += 25
        '''
        with get_httpx_client() as client:
            #改造一下 16
            result = []
            i = 0
            MAX_BATCH_SIZE=16
            while i < len(params.texts):
                texts = params.texts[i:i + MAX_BATCH_SIZE]
                resp = client.post(url, json={"input": texts}).json()
                if "error_code" not in resp:
                    embeddings = [x["embedding"] for x in resp.get("data", [])]
                    result += embeddings
                else:
                    return {"code": resp["error_code"], "msg": resp["error_msg"]}
                i += MAX_BATCH_SIZE

            # resp = client.post(url, json={"input": params.texts}).json()
            #
            # if "error_cdoe" not in resp:#------------------->这里写错了
            #     embeddings = [x["embedding"] for x in resp.get("data", [])]
            #     return {"code": 200, "data": embeddings}
            # else:
            #     return {"code": resp["error_code"], "msg": resp["error_msg"]}
            return {"code": 200, "data": result}

**Comment by liunux4odoo** [comment]
开发版中已经修复，0.2.8版将解决该问题。

**Comment by shishi11** [comment]
开发版写的什么呀，都是错的。
