### ISSUE TITLE
官方案例-知识库回答错误

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#2118]
**问题描述 / Problem Description**
使用了官方的例子
# 查特查特团队荣获AGI Playground Hackathon黑客松“生产力工具的新想象”赛道季军。

## 报道简介
2023年10月16日, Founder Park在近日结束的AGI Playground Hackathon黑客松比赛中，查特查特团队展现出色的实力，荣获了“生产力工具的新想象”赛道季军。本次比赛由Founder Park主办，并由智谱、Dify、Zilliz、声网、AWS云服务等企业协办。

## 比赛介绍

比赛吸引了120多支参赛团队，最终有36支队伍进入决赛，其中34支队伍成功完成了路演。比赛规定，所有参赛选手必须在短短的48小时内完成一个应用产品开发，同时要求使用智谱大模型及Zilliz向量数据库进行开发。

## 获奖队员简介

+ 小明，A大学
  + 负责Agent旅游助手的开发、场地协调以及团队住宿和行程的安排
  + 在保证团队完赛上做出了主要贡献。作为队长，栋宇坚持自信，创新，沉着的精神，不断提出改进方案并抓紧落实，遇到相关问题积极请教老师，提高了团队开发效率。

+ 小蓝，B公司
  + 主管Agent智能知识库查询开发、Agent底层框架设计、相关API调整和UI调整。
  + 代表团队在规定的时间内呈现了产品的特点和优势，并完美的展示了产品demo。

使用知识库问答，回答的都是错误的，知识库匹配结果都没有。

**复现问题的步骤 / Steps to Reproduce**
1. 使用官方的查特查特例子，用#号处理了（案例建议来的）
2. 上传知识库，单段文本最大长度250，相邻文本重合长度50
3. 向量库为faiss，embedding为m3e-base
4. 大模型为chatglm3-6b
5. 使用知识库问答，回答的都是错误的，“未找到相关文档,该回答为大模型自身能力解答！”

**预期的结果 / Expected Result**
根据文档内容回答，出处应该能找出来

**实际结果 / Actual Result**
相关出处找不到，回答错误

**环境信息 / Environment Information**
- langchain-ChatGLM 版本：0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B，Qwen-13b-8int-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- Python 版本 / Python version:3.8

**Comment by danerlt** [comment]
使用0.2.6 升级到0.2.7，重建了数据库，使用知识库问答，所有的回答查看知识库匹配结果都显示：`未找到相关文档,该回答为大模型自身能力解答！`

**Comment by AaronFSJ** [comment]
0.2.7 我也是啊

**Comment by theone-daxia** [comment]
检查一下 SCORE_THRESHOLD ， 看看是不是设置的太小了（比如 <= 0.3），0.5左右比较合适。你可以在代码里打印出相关信息，来查看搜索到某个 doc 的 score 是多少，具体做法如下：

1、SCORE_THRESHOLD 调大，比如 0.6
2、在 knowledge_base_chat.py 中打印 docs

-------------------
这样你就可以对所有 doc 的 score 有个认知，调整 SCORE_THRESHOLD 时也就有了依据

**Comment by danerlt** [comment]
@theone-daxia 我重新将文档添加到向量库之后就解决了这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
要重新初始化向量数据库
