### ISSUE TITLE
[BUG] 简洁阐述问题 / 最新版本运行时候对话模块会提示空指针异常

### ISSUE THREAD

**Issue by Ginorva** [chatchat-space/Langchain-Chatchat#2119]
requirements_lite.txt里的httpx的版本给设定为httpx==0.24.1就能解决这个问题，出错原因是因为新版本的httpx去掉了一些参数

**Comment by zRzRzRzRzRzRzR** [comment]
已在dev中更改requirement，统一设置为httpx==0.24.1
