### ISSUE TITLE
谁能在网盘中放一下环境，或者懒人包啊？

### ISSUE THREAD

**Issue by WangShunzhiDQ** [chatchat-space/Langchain-Chatchat#2120]
谁能在网盘中放一下环境，或者懒人包啊？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：哪个对中文最好？
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: win10
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
有docker，但是基于windows环境实在复杂，官方暂时没有提供懒人包
