### ISSUE TITLE
[BUG] 知识库初始化时能读取软连接

### ISSUE THREAD

**Issue by shenmadouyaowen** [chatchat-space/Langchain-Chatchat#2125]
**功能描述 / Feature Description**
有一批几百万的txt文件，按照分类在不同目录，我把这个目录软连接到知识库下面：knowledge_base/zldata/content/wentxt
使用命令 · python init_database.py --recreate-vs· 无法获得软连接目录下面的文件，需要修改server/knowledge_base/utils.py 下面的list_files_from_folder 函数

**解决的问题 / Problem Solved**
初始化知识库时能读取到软连接下面的文件和目录

**实现建议 / Implementation Suggestions**
初始化知识库时能读取到软连接下面的文件和目录

**替代方案 / Alternative Solutions**
修改server/knowledge_base/utils.py 下面的list_files_from_folder 函数为
```
def list_files_from_folder(kb_name: str):
    doc_path = get_doc_path(kb_name)
    result = []
    def process_entry(entry):
        if entry.is_symlink():
            # 如果是软链接，递归处理目标路径utils.py
            target_path = os.path.realpath(entry.path)
            with os.scandir(target_path) as target_it:
                for target_entry in target_it:
                    process_entry(target_entry)
        elif entry.is_file():
            # 如果是文件，添加到结果列表
            result.append(entry.path)
        elif entry.is_dir():
            # 如果是目录，递归处理目录下的文件
            with os.scandir(entry.path) as it:
                for sub_entry in it:
                    process_entry(sub_entry)
    # 处理初始目录
    with os.scandir(doc_path) as it:
        for entry in it:
            process_entry(entry)
    return result
```

**其他信息 / Additional Information**
无

**Comment by zRzRzRzRzRzRzR** [comment]
参考了你的意见，感谢提议

**Comment by auroralzone** [comment]
`v0.2.7`
不知道为什么我无法使用软链接，改不改`list_files_from_folder()`都不行
```shell
mkdir -p knowledge_base/test2/content
ln -s ~/test_files/ knowledge_base/test2/content
python init_database.py --recreate-vs
python startup.py -a
```

```
test_files
├── langchain-ChatGLM_closed.csv
├── langchain-ChatGLM_closed.jsonl
├── langchain-ChatGLM_closed.xlsx
├── langchain-ChatGLM_open.csv
├── langchain-ChatGLM_open.jsonl
├── langchain-ChatGLM_open.xlsx
└── test.txt
```

<img width="284" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/77838cea-a265-434b-b66f-2e4c163fafb9">

**Comment by shenmadouyaowen** [comment]
> ```shell
> python init_database.py --recreate-vs
> ```

不改的话绝对不行，改的话是可以的，你运行：python init_database.py --recreate-vs  有读取到文件么？

**Comment by auroralzone** [comment]
**已改函数**`list_files_from_folder()`

`python init_database.py --recreate-vs` 没啥问题
```
...
t 添加到向量库，共包含59条文档
Batches: 100%|████████████████████████████████████████████████| 2/2 [00:00<00:00, 12.16it/s]
2023-11-28 10:41:09,887 - faiss_cache.py[line:24] - INFO: 已将向量库 ('test2', 'm3e-base')  保存到磁盘
总计用时： 0:00:16.215540
```
<img width="651" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/48132a5d-3c9e-4b5f-96f9-f72b83ed25d7">

***

`python startup.py -a` 没有问题

但是在对话中报错：`API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)`

<img width="738" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/42070770/6ff34e71-a404-4985-b712-3bb36aca8539">


本机存在文件或目录：
- `/root/code/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.csv`
- `/root/code/Langchain-Chatchat_new/knowledge_base/test2/content`

```
INFO:     127.0.0.1:47152 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK
2023-11-28 10:49:25,754 - _client.py[line:1013] - INFO: HTTP Request: GET http://127.0.0.1:7861/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
received input message:
{'history': [],
 'knowledge_base_name': 'test2',
 'max_tokens': None,
 'model_name': 'chatglm3-6b-32k',
 'prompt_name': 'default',
 'query': '优化',
 'score_threshold': 1.0,
 'stream': True,
 'temperature': 0.7,
 'top_k': 3}
INFO:     127.0.0.1:47152 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
Batches: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00, 196.99it/s]
2023-11-28 10:49:25,848 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/root/code/Langchain-Chatchat_new/server/chat/knowledge_base_chat.py", line 79, in knowledge_base_chat_iterator
    filename = Path(doc.metadata["source"]).resolve().relative_to(doc_path)
  File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/pathlib.py", line 818, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: '/root/code/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.csv' is not in the subpath of '/root/code/Langchain-Chatchat_new/knowledge_base/test2/content' OR one path is relative and the other is absolute.
2023-11-28 10:49:25,850 - utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
2023-11-28 10:49:25 | INFO | stdout | INFO:     127.0.0.1:43476 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2023-11-28 10:49:25,874 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2023-11-28 10:49:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
```

**Comment by shenmadouyaowen** [comment]
> **已改函数**`list_files_from_folder()`
> 
> `python init_database.py --recreate-vs` 没啥问题
> 
> ```
> ...
> t 添加到向量库，共包含59条文档
> Batches: 100%|████████████████████████████████████████████████| 2/2 [00:00<00:00, 12.16it/s]
> 2023-11-28 10:41:09,887 - faiss_cache.py[line:24] - INFO: 已将向量库 ('test2', 'm3e-base')  保存到磁盘
> 总计用时： 0:00:16.215540
> ```
> 
> <img alt="image" width="651" src="https://private-user-images.githubusercontent.com/42070770/286099354-48132a5d-3c9e-4b5f-96f9-f72b83ed25d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTQxNTQsIm5iZiI6MTcwMTE1Mzg1NCwicGF0aCI6Ii80MjA3MDc3MC8yODYwOTkzNTQtNDgxMzJhNWQtM2M5ZS00YjVmLTk2ZjktZjcyYjgzZWQyNWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA2NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZmFiODY4YTMzNmIzMGNlYzViZTgyZWY5NzA4OTgyNWQzMDVhYzI4ZjI0MjMyZjA4ZjE3YzIyM2JjNzMyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UxhoXI1BQy7g_kZxGeqjlT9vUlq54nQ8Mjw_8siYEW8">
> `python startup.py -a` 没有问题
> 
> 但是在对话中报错：`API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)`
> 
> <img alt="image" width="738" src="https://private-user-images.githubusercontent.com/42070770/286099508-6ff34e71-a404-4985-b712-3bb36aca8539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExNTQxNTQsIm5iZiI6MTcwMTE1Mzg1NCwicGF0aCI6Ii80MjA3MDc3MC8yODYwOTk1MDgtNmZmMzRlNzEtYTQwNC00OTg1LWI3MTItM2JiMzZhY2E4NTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI4VDA2NDQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNjRkMzg3ZWEwOWZiMGVhMjNlYTRmZDI3ZTRmZmViNzcyNGQ3NzJjYTg5OWUwNjlkYmQzNWEyNDY1MjU2MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPwG3vzRgCykevn-W6Gm6Kd0faHSArvVUvRlbIztiuo">
> 本机存在文件或目录：
> 
> * `/root/code/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.csv`
> * `/root/code/Langchain-Chatchat_new/knowledge_base/test2/content`
> 
> ```
> INFO:     127.0.0.1:47152 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK
> 2023-11-28 10:49:25,754 - _client.py[line:1013] - INFO: HTTP Request: GET http://127.0.0.1:7861/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
> received input message:
> {'history': [],
>  'knowledge_base_name': 'test2',
>  'max_tokens': None,
>  'model_name': 'chatglm3-6b-32k',
>  'prompt_name': 'default',
>  'query': '优化',
>  'score_threshold': 1.0,
>  'stream': True,
>  'temperature': 0.7,
>  'top_k': 3}
> INFO:     127.0.0.1:47152 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
> Batches: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00, 196.99it/s]
> 2023-11-28 10:49:25,848 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
> ERROR:    Exception in ASGI application
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
>     result = await app(  # type: ignore[func-returns-value]
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
>     return await self.app(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
>     await super().__call__(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
>     raise exc
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
>     await self.app(scope, receive, _send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
>     raise exc
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
>     await self.app(scope, receive, sender)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
>     raise e
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
>     await self.app(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
>     await route.handle(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
>     await self.app(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/routing.py", line 69, in app
>     await response(scope, receive, send)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/responses.py", line 270, in __call__
>     async with anyio.create_task_group() as task_group:
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
>     raise exceptions[0]
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/responses.py", line 273, in wrap
>     await func()
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/site-packages/starlette/responses.py", line 262, in stream_response
>     async for chunk in self.body_iterator:
>   File "/root/code/Langchain-Chatchat_new/server/chat/knowledge_base_chat.py", line 79, in knowledge_base_chat_iterator
>     filename = Path(doc.metadata["source"]).resolve().relative_to(doc_path)
>   File "/root/miniconda3/envs/Langchain-Chatchat-Master/lib/python3.10/pathlib.py", line 818, in relative_to
>     raise ValueError("{!r} is not in the subpath of {!r}"
> ValueError: '/root/code/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.csv' is not in the subpath of '/root/code/Langchain-Chatchat_new/knowledge_base/test2/content' OR one path is relative and the other is absolute.
> 2023-11-28 10:49:25,850 - utils.py[line:187] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
> 2023-11-28 10:49:25 | INFO | stdout | INFO:     127.0.0.1:43476 - "POST /v1/chat/completions HTTP/1.1" 200 OK
> 2023-11-28 10:49:25,874 - _client.py[line:1729] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
> 2023-11-28 10:49:25 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
> ```

参考楼上大佬的[79行](https://github.com/zRzRzRzRzRzRzR/Langchain-Chatchat/blob/dev/server/chat/knowledge_base_chat.py)修改一下
