### ISSUE TITLE
[BUG] 上传pdf文件，添加到向量库耗时太长

### ISSUE THREAD

**Issue by danerlt** [chatchat-space/Langchain-Chatchat#2126]
**问题描述 / Problem Description**
上传pdf文件，添加到向量库耗时太长

**复现问题的步骤 / Steps to Reproduce**
1. 知识库上传一个论文pdf文件，文件大小大约100M，80页左右，RapidOCRPDFLoader解析pdf的时间太长，解析完大约需要30分钟，能否优化？

**预期的结果 / Expected Result**
解析时间加快

**实际结果 / Actual Result**
解析时间太久了，解析完大约需要30分钟

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm3
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 : CentOS 7
- Python 版本: 3.10

**Comment by JHGo123** [comment]
怎么能够学习pdf中信息，我上传个很小的pdf自建知识库测试，发现但很简单的问题都无法回答，请问下你这边是怎么操作的？
使用的模型ChatGLM2-6B

**Comment by danerlt** [comment]
@JHGo123 我用的chatglm3-6b的模型，就修改配置把模型设置成chatglm3-6b,然后在知识库上传pdf，然后添加到向量库，然后问问题，这个回答的效果我试了也不是很好。

**Comment by zRzRzRzRzRzRzR** [comment]
建议使用markdown，pdf是用扫描来做的， 另外，请看wiki更换模型，这个配置的模型只是让大家能用

**Comment by Madilynalisa** [comment]
您好，有两个问题想请教：
1. 上传文档的速度太慢，15M的文档需要18分钟，如何优化？
2. 大大小小文档加起来可能超过100G，知识库能否容纳？上传是否可能因已存在的文档过多而报错？
