### ISSUE TITLE
python init_database.py --recreate-vs 报错

### ISSUE THREAD

**Issue by klw8888** [chatchat-space/Langchain-Chatchat#2127]
**问题描述 / Problem Description**
执行python init_database.py --recreate-vs命令后报错: warnings.warn ('resource tracker: There appear to be %d 

<img width="888" alt="截屏2023-11-21 17 30 39" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/54295717/d2a67e77-5cd1-44cd-bb5c-828396a364cb">

**环境信息 / Environment Information**
运行系统：macos ventura
CPU：Intel Core i7
内存：16G
显卡：AMD 6800XT 16G
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: macos ventura 13.2.1
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
accelerate                    0.24.1
aiohttp                       3.9.0
aiolimiter                    1.1.0
aiosignal                     1.3.1
altair                        5.1.2
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
async-timeout                 4.0.3
attrs                         23.1.0
backoff                       2.2.1
bce-python-sdk                0.8.96
beautifulsoup4                4.12.2
blinker                       1.7.0
blis                          0.7.11
Brotli                        1.1.0
cachetools                    5.3.2
catalogue                     2.0.10
certifi                       2023.11.17
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpathlib                  0.16.0
coloredlogs                   15.0.1
confection                    0.1.3
contourpy                     1.2.0
cryptography                  41.0.5
cycler                        0.12.1
cymem                         2.0.8
dashscope                     1.13.3
dataclasses                   0.6
dataclasses-json              0.6.2
distro                        1.8.0
effdet                        0.4.1
einops                        0.7.0
emoji                         2.8.0
et-xmlfile                    1.1.0
exceptiongroup                1.1.3
faiss-cpu                     1.7.4
fastapi                       0.104.1
filelock                      3.13.1
filetype                      1.2.0
flatbuffers                   23.5.26
fonttools                     4.45.0
frozenlist                    1.4.0
fschat                        0.2.32
fsspec                        2023.10.0
future                        0.18.3
gitdb                         4.0.11
GitPython                     3.1.40
greenlet                      3.0.1
h11                           0.14.0
h2                            4.1.0
hpack                         4.0.0
httpcore                      1.0.2
httpx                         0.25.1
huggingface-hub               0.19.4
humanfriendly                 10.0
hyperframe                    6.0.1
idna                          3.4
importlib-metadata            6.8.0
iniconfig                     2.0.0
iopath                        0.1.10
Jinja2                        3.1.2
joblib                        1.3.2
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.20.0
jsonschema-specifications     2023.11.1
kiwisolver                    1.4.5
langchain                     0.0.339
langchain-experimental        0.0.42
langcodes                     3.3.0
langdetect                    1.0.9
langsmith                     0.0.65
layoutparser                  0.3.4
lxml                          4.9.3
Markdown                      3.5.1
markdown-it-py                3.0.0
markdown2                     2.4.10
markdownify                   0.11.6
MarkupSafe                    2.1.3
marshmallow                   3.20.1
matplotlib                    3.8.2
mdurl                         0.1.2
mpmath                        1.3.0
msg-parser                    1.2.0
multidict                     6.0.4
murmurhash                    1.0.10
mypy-extensions               1.0.0
networkx                      3.2.1
nh3                           0.2.14
nltk                          3.8.1
numexpr                       2.8.7
numpy                         1.24.4
olefile                       0.46
omegaconf                     2.3.0
onnx                          1.15.0
onnxruntime                   1.15.1
openai                        1.3.3
opencv-python                 4.8.1.78
openpyxl                      3.1.2
packaging                     23.2
pandas                        2.0.3
pathlib                       1.0.1
pdf2image                     1.16.3
pdfminer.six                  20221105
pdfplumber                    0.10.3
peft                          0.6.2
Pillow                        9.5.0
pip                           23.3.1
pluggy                        1.3.0
portalocker                   2.8.2
preshed                       3.0.9
prompt-toolkit                3.0.41
protobuf                      4.25.1
psutil                        5.9.6
pyarrow                       14.0.1
pyclipper                     1.3.0.post5
pycocotools                   2.0.7
pycparser                     2.21
pycryptodome                  3.19.0
pydantic                      1.10.13
pydeck                        0.8.1b0
Pygments                      2.17.1
PyJWT                         2.8.0
PyMuPDF                       1.23.6
PyMuPDFb                      1.23.6
pypandoc                      1.12
pyparsing                     3.1.1
pypdfium2                     4.24.0
pytesseract                   0.3.10
pytest                        7.4.3
python-dateutil               2.8.2
python-decouple               3.8
python-docx                   1.1.0
python-iso639                 2023.6.15
python-magic                  0.4.27
python-multipart              0.0.6
python-pptx                   0.6.23
pytz                          2023.3.post1
PyYAML                        6.0.1
qianfan                       0.1.1
rapidfuzz                     3.5.2
rapidocr-onnxruntime          1.3.8
referencing                   0.31.0
regex                         2023.10.3
requests                      2.31.0
rich                          13.7.0
rpds-py                       0.13.1
safetensors                   0.4.0
scikit-learn                  1.3.2
scipy                         1.11.4
sentence-transformers         2.2.2
sentencepiece                 0.1.99
setuptools                    65.5.0
shapely                       2.0.2
shortuuid                     1.0.11
simplejson                    3.19.2
six                           1.16.0
smart-open                    6.4.0
smmap                         5.0.1
sniffio                       1.3.0
socksio                       1.0.0
soupsieve                     2.5
spacy                         3.7.2
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
SQLAlchemy                    2.0.19
srsly                         2.4.8
starlette                     0.27.0
streamlit                     1.27.2
streamlit-aggrid              0.3.4.post3
streamlit-antd-components     0.2.3
streamlit-chatbox             1.1.11
streamlit-feedback            0.1.3
streamlit-option-menu         0.3.6
strsimpy                      0.2.1
svgwrite                      1.4.3
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
thinc                         8.2.1
threadpoolctl                 3.2.0
tiktoken                      0.5.1
timm                          0.9.10
tokenizers                    0.15.0
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         2.1.1
torchaudio                    2.1.1
torchvision                   0.16.1
tornado                       6.3.3
tqdm                          4.66.1
transformers                  4.35.2
transformers-stream-generator 0.0.4
typer                         0.9.0
typing_extensions             4.8.0
typing-inspect                0.9.0
tzdata                        2023.3
tzlocal                       5.2
unstructured                  0.11.0
unstructured-inference        0.7.15
unstructured.pytesseract      0.3.12
urllib3                       2.1.0
uvicorn                       0.23.2
validators                    0.22.0
wasabi                        1.1.2
watchdog                      3.0.0
wavedrom                      2.0.3.post3
wcwidth                       0.2.10
weasel                        0.3.4
websockets                    12.0
wheel                         0.41.3
wrapt                         1.16.0
xformers                      0.0.22.post7
xlrd                          2.0.1
XlsxWriter                    3.1.9
yarl                          1.9.2
zhipuai                       1.0.7
zipp                          3.17.0

**Comment by klw8888** [comment]
accelerate                    0.24.1
aiohttp                       3.9.0
aiolimiter                    1.1.0
aiosignal                     1.3.1
altair                        5.1.2
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
async-timeout                 4.0.3
attrs                         23.1.0
backoff                       2.2.1
bce-python-sdk                0.8.96
beautifulsoup4                4.12.2
blinker                       1.7.0
blis                          0.7.11
Brotli                        1.1.0
cachetools                    5.3.2
catalogue                     2.0.10
certifi                       2023.11.17
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpathlib                  0.16.0
coloredlogs                   15.0.1
confection                    0.1.3
contourpy                     1.2.0
cryptography                  41.0.5
cycler                        0.12.1
cymem                         2.0.8
dashscope                     1.13.3
dataclasses                   0.6
dataclasses-json              0.6.2
distro                        1.8.0
effdet                        0.4.1
einops                        0.7.0
emoji                         2.8.0
et-xmlfile                    1.1.0
exceptiongroup                1.1.3
faiss-cpu                     1.7.4
fastapi                       0.104.1
filelock                      3.13.1
filetype                      1.2.0
flatbuffers                   23.5.26
fonttools                     4.45.0
frozenlist                    1.4.0
fschat                        0.2.32
fsspec                        2023.10.0
future                        0.18.3
gitdb                         4.0.11
GitPython                     3.1.40
greenlet                      3.0.1
h11                           0.14.0
h2                            4.1.0
hpack                         4.0.0
httpcore                      1.0.2
httpx                         0.25.1
huggingface-hub               0.19.4
humanfriendly                 10.0
hyperframe                    6.0.1
idna                          3.4
importlib-metadata            6.8.0
iniconfig                     2.0.0
iopath                        0.1.10
Jinja2                        3.1.2
joblib                        1.3.2
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.20.0
jsonschema-specifications     2023.11.1
kiwisolver                    1.4.5
langchain                     0.0.339
langchain-experimental        0.0.42
langcodes                     3.3.0
langdetect                    1.0.9
langsmith                     0.0.65
layoutparser                  0.3.4
lxml                          4.9.3
Markdown                      3.5.1
markdown-it-py                3.0.0
markdown2                     2.4.10
markdownify                   0.11.6
MarkupSafe                    2.1.3
marshmallow                   3.20.1
matplotlib                    3.8.2
mdurl                         0.1.2
mpmath                        1.3.0
msg-parser                    1.2.0
multidict                     6.0.4
murmurhash                    1.0.10
mypy-extensions               1.0.0
networkx                      3.2.1
nh3                           0.2.14
nltk                          3.8.1
numexpr                       2.8.7
numpy                         1.24.4
olefile                       0.46
omegaconf                     2.3.0
onnx                          1.15.0
onnxruntime                   1.15.1
openai                        1.3.3
opencv-python                 4.8.1.78
openpyxl                      3.1.2
packaging                     23.2
pandas                        2.0.3
pathlib                       1.0.1
pdf2image                     1.16.3
pdfminer.six                  20221105
pdfplumber                    0.10.3
peft                          0.6.2
Pillow                        9.5.0
pip                           23.3.1
pluggy                        1.3.0
portalocker                   2.8.2
preshed                       3.0.9
prompt-toolkit                3.0.41
protobuf                      4.25.1
psutil                        5.9.6
pyarrow                       14.0.1
pyclipper                     1.3.0.post5
pycocotools                   2.0.7
pycparser                     2.21
pycryptodome                  3.19.0
pydantic                      1.10.13
pydeck                        0.8.1b0
Pygments                      2.17.1
PyJWT                         2.8.0
PyMuPDF                       1.23.6
PyMuPDFb                      1.23.6
pypandoc                      1.12
pyparsing                     3.1.1
pypdfium2                     4.24.0
pytesseract                   0.3.10
pytest                        7.4.3
python-dateutil               2.8.2
python-decouple               3.8
python-docx                   1.1.0
python-iso639                 2023.6.15
python-magic                  0.4.27
python-multipart              0.0.6
python-pptx                   0.6.23
pytz                          2023.3.post1
PyYAML                        6.0.1
qianfan                       0.1.1
rapidfuzz                     3.5.2
rapidocr-onnxruntime          1.3.8
referencing                   0.31.0
regex                         2023.10.3
requests                      2.31.0
rich                          13.7.0
rpds-py                       0.13.1
safetensors                   0.4.0
scikit-learn                  1.3.2
scipy                         1.11.4
sentence-transformers         2.2.2
sentencepiece                 0.1.99
setuptools                    65.5.0
shapely                       2.0.2
shortuuid                     1.0.11
simplejson                    3.19.2
six                           1.16.0
smart-open                    6.4.0
smmap                         5.0.1
sniffio                       1.3.0
socksio                       1.0.0
soupsieve                     2.5
spacy                         3.7.2
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
SQLAlchemy                    2.0.19
srsly                         2.4.8
starlette                     0.27.0
streamlit                     1.27.2
streamlit-aggrid              0.3.4.post3
streamlit-antd-components     0.2.3
streamlit-chatbox             1.1.11
streamlit-feedback            0.1.3
streamlit-option-menu         0.3.6
strsimpy                      0.2.1
svgwrite                      1.4.3
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
thinc                         8.2.1
threadpoolctl                 3.2.0
tiktoken                      0.5.1
timm                          0.9.10
tokenizers                    0.15.0
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         2.1.1
torchaudio                    2.1.1
torchvision                   0.16.1
tornado                       6.3.3
tqdm                          4.66.1
transformers                  4.35.2
transformers-stream-generator 0.0.4
typer                         0.9.0
typing_extensions             4.8.0
typing-inspect                0.9.0
tzdata                        2023.3
tzlocal                       5.2
unstructured                  0.11.0
unstructured-inference        0.7.15
unstructured.pytesseract      0.3.12
urllib3                       2.1.0
uvicorn                       0.23.2
validators                    0.22.0
wasabi                        1.1.2
watchdog                      3.0.0
wavedrom                      2.0.3.post3
wcwidth                       0.2.10
weasel                        0.3.4
websockets                    12.0
wheel                         0.41.3
wrapt                         1.16.0
xformers                      0.0.22.post7
xlrd                          2.0.1
XlsxWriter                    3.1.9
yarl                          1.9.2
zhipuai                       1.0.7
zipp                          3.17.0

**Comment by SmartFrodo** [comment]
![WechatIMG124](https://github.com/chatchat-space/Langchain-Chatchat/assets/22165441/ea9b94ff-ef74-400b-a419-13b3f4e21a8d)
macos 出现相同的问题

**Comment by hzg0601** [comment]
报错呢？这不是个warning吗

**Comment by xiaoxiao9992** [comment]
大佬们, python init_database.py --recreate-vs命令后报错:lypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
![1701134712730](https://github.com/chatchat-space/Langchain-Chatchat/assets/86135060/0d5da819-53a4-4c44-a19d-eb07c4d2d6e6)
是在22.04.1-Ubuntu 版本上运行的, cuda版本12.1, torch版本2.1

**Comment by zRzRzRzRzRzRzR** [comment]
conjugate大概率是模型没找到或者模型没全，然后，关于依赖的问题，最新版本的依赖版本都比较高，我建议是装py310，bug稍微比较少见
