### ISSUE TITLE
[BUG] 简洁阐述问题 / 通义千问模型对话不会停止，会自问自答

### ISSUE THREAD

**Issue by erjiguan** [chatchat-space/Langchain-Chatchat#2132]
**问题描述 / Problem Description**
qwen本地部署的模型对话不会停止，会自问自答，当对话输出长的时候会出现。
我手动加上stop停止词["<|endoftext|>","<|im_end|>","<|im_start|>"]后，似乎修复了，我再观察一下

**预期的结果 / Expected Result**
对话正常停止

**环境信息 / Environment Information**
- 0.2.7 dev分支
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: centos7.9
- Python 版本 / Python version: 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Jingzhenzxz** [comment]
我也遇到了这个问题。

环境信息 / Environment Information

0.2.7 dev分支
是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
使用的模型（ChatGLM2-6B / Qwen-7B 等）：CodeShell-7B-Chat
使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: centos7.9
Python 版本 / Python version: 3.9.18

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下fschat试试？然后如果不行，可以在我们的对话中加入stop word 就是在langchain中加

**Comment by weigong1983** [comment]
> 更新一下fschat试试？然后如果不行，可以在我们的对话中加入stop word 就是在langchain中加

大部分AI问答应用的聊天输入框上方都有一个【停止生成】的按钮， 请问本开源项目如何添加这样一个功能，当出现AI对话无法自动停止的时候，可以人工停止。
