### ISSUE TITLE
[BUG] api页面正常使用，但是webui界面打开就只有一个控件  0.

### ISSUE THREAD

**Issue by plisking** [chatchat-space/Langchain-Chatchat#2135]
如图
![未命名1700621249](https://github.com/chatchat-space/Langchain-Chatchat/assets/19298506/79d6c36e-3521-4930-9f81-21453471b7d8)

**Comment by zRzRzRzRzRzRzR** [comment]
估计配置没装对，确保系统和硬件信息符合官方要求
建议提供一下后台日志，我们无法复现

**Comment by tigerun** [comment]
重新安装streamlit到1.28.0的版本可以解决
