### ISSUE TITLE
服务跑起来了，但是无法正常使用

### ISSUE THREAD

**Issue by xxWeiDG** [chatchat-space/Langchain-Chatchat#2138]
**问题描述 / Problem Description**
服务可以正常启动，但是输入对话，无法得到回复，然后我就在api界面问答，得到的回复报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/140797957/e96a45d0-f648-49e4-ad39-f4a5fcb7a820)

**环境信息 / Environment Information**
- 是否使用 Docker 部署：是 
- 使用的模型：ChatGLM-6B
- 使用的向量库类型 :faiss 
- 操作系统及版本 :ubuntu22.04

**Comment by zRzRzRzRzRzRzR** [comment]
确定一下docker后面端口情况正常？
能提供一下后台日志吗

**Comment by xxWeiDG** [comment]
> 确定一下docker后面端口情况正常？ 能提供一下后台日志吗

端口正常，日志在哪里看呢

**Comment by zRzRzRzRzRzRzR** [comment]
命令行日志呀
