### ISSUE TITLE
建议恢复cli_demo.py文件，帮助理解任务流

### ISSUE THREAD

**Issue by tomFoxxxx** [chatchat-space/Langchain-Chatchat#2142]
如题，ChatChat的使用与服务端的绑定过深了，更多是从产品的角度在做开发，然后在社区release并收集意见迭代版本。

希望作者可以考虑重新实现cli_demo.py，感谢。

**Comment by tomFoxxxx** [comment]
@imClumsyPanda

**Comment by imClumsyPanda** [comment]
建议直接参考chains中的脚本，是提供api的基础

**Comment by tomFoxxxx** [comment]
> 建议直接参考chains中的脚本，是提供api的基础

这个脚本太简略啦 对于知识库的新建和搜索过程 组装过程都没有提及

非常理解项目的演进方向 ChatChat的pipeline我再研究下 谢谢
