### ISSUE TITLE
Qwen-7B模型报错 Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by carlyxiao** [chatchat-space/Langchain-Chatchat#2149]

**Comment by carlyxiao** [comment]
对话，输入问题后，返回空白，且报错：
2023-11-23 10:47:22,051 - utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by zRzRzRzRzRzRzR** [comment]
检查是不是模型注册server config没写

**Comment by dijkstra-mose** [comment]
感觉这个项目不太成熟，调试起来问题很多。还涉及fastchat, langchain很多库，很难查。
