### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by fqdltd** [chatchat-space/Langchain-Chatchat#2151]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / webUi服务启动了但是使用8501端口在浏览器上访问无法访问

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / 应该可以访问webUI

**实际结果 / Actual Result**
描述实际发生的结果 / 404

**环境信息 / Environment Information**
-==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.17763-SP0.
python版本：3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:01:37) [MSC v.1935 64 bit (AMD64)]
项目版本：v0.2.7
langchain版本：0.0.339. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'chatglm2-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cpu

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501
==============================Langchain-Chatchat Configuration==============================

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / 另外我这个服务好像是运行在CPU上的，默认不是应该运行在GPU上么

**Comment by zRzRzRzRzRzRzR** [comment]
你查一下cuda版本就行，大概率是cuda版本没有装对，另外 0.2.7 gpt模型会报错，建议换到dev
