### ISSUE TITLE
加载ptuning微调后的Chatglm2模型报错

### ISSUE THREAD

**Issue by JZYYYYYYY** [chatchat-space/Langchain-Chatchat#2154]
### 问题描述
使用 ChatGLM2-6B-->ptuning 微调模型 ，并且按照wiki最佳实践当中的步骤加载模型。修改了
fastchat包和项目的代码。
https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#p-tuning%E5%8A%A0%E8%BD%BD

### 复现问题

1. 使用 ChatGLM2-6B ptuning-v2 方法微调微调模型

2. 按照 https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#%E6%8E%A8%E8%8D%90%E7%9A%84%E6%A8%A1%E5%9E%8B%E7%BB%84%E5%90%88(微调模型加载实操)
加载模型

<img width="105" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/55731650/2e702116-33cb-427d-b458-b96c1c9a106a">

3. 执行 PEFT_SHARE_BASE_WEIGHTS=true python startup.py -a

产生报错信息
<img width="692" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/55731650/fd83bf88-7d79-4e26-a196-37afffbf5ea9">

**Comment by zRzRzRzRzRzRzR** [comment]
你这个报错很明显，你的 `name_or_path`参数没必要传

**Comment by hsj576** [comment]
遇到了同样的问题，我的解决方法是把adapter_config.json中其他都删掉，只保留这些
{
  "base_model_name_or_path": "/THUDM/chatglm2-6b",
  "task_type": "CAUSAL_LM",
  "peft_type": "PREFIX_TUNING",
  "inference_mode": true,
  "revision": "main",
  "num_virtual_tokens": 16
}
然后运行就能正常启动了
