### ISSUE TITLE
[BUG] 无法切换模型，webui端的模型只显示第一个，并且读取模型错误

### ISSUE THREAD

**Issue by a656418zz** [chatchat-space/Langchain-Chatchat#2155]
**问题描述 / Problem Description**
无法切换模型，webui端的模型只显示第一个，并且读取模型错误

**复现问题的步骤 / Steps to Reproduce**
1.model_config中设定LLM_MODELS=["chatglm2-6b","chatglm3-6b"]
2.设定模型路径
3.启动服务

**预期的结果 / Expected Result**
WebUI端应该可以切换模型，并且显示什么模型就是用什么模型

**实际结果 / Actual Result**
WebUI端下拉只有当前模型，并且当前模型所读取的模型其实是另一个模型。（如WebUI端显示的是chatglm2，但实际上是读取的chatglm3模型）

**附加信息 / Additional Information**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25815600/13d5a9d1-1692-4392-b06d-838ea52a79ac)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25815600/98f5aca6-6fef-44e6-98a9-82410c8d3edd)

此外，进行了只读取单个模型的测试，这时候能够正常读取，所以也排除了模型的问题。

**Comment by zhanghaotian123** [comment]
+1，我是在model_config里配置LLM_MODELS = ["chatglm3-6b", "openai-api"]，但是webui里选择LLM模型下拉列表里只有一个chatglm3-6b(Running)，并没有openai-api这个选项

**Comment by liunux4odoo** [comment]
这两个问题将在0.2.8版修复。
