### ISSUE TITLE
[BUG] 点击‘新建知识库’ 界面报错

### ISSUE THREAD

**Issue by nikshe** [chatchat-space/Langchain-Chatchat#2157]
**问题描述 / Problem Description**
点击知识库管理，在”请选择或新建知识库：“下拉列表中选择”新建知识库“，页面报错：
<img width="750" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/2069663/8b91bbc5-ff46-4b14-8d3e-60b3494aebe2">
<img width="746" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/2069663/209853a4-dc33-4cfc-b74f-efe9564d82bb">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：在线zhipu-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：pg_vector
- 操作系统及版本 / Operating system and version: macOS-10.16-x86_64-i386-64bit.
- Python 版本 / Python version: 3.10

**Comment by zRzRzRzRzRzRzR** [comment]
这个是没找到你的embed模型， 你看看你模型路径对吗

**Comment by nikshe** [comment]
m3e-base 模型下载了，在项目跟目录下 moka-ai/m3e-base

**Comment by nikshe** [comment]
代码问题，已解决

**Comment by theFarHorizon** [comment]
@nikshe 你好，具体啥问题，我也遇到了，怎么解决的
