### ISSUE TITLE
[BUG] 知识库管理页面获取文档分段信息失败。

### ISSUE THREAD

**Issue by mazurkas** [chatchat-space/Langchain-Chatchat#2159]
**问题描述 / Problem Description**
在知识库管理页面增加了一个功能，可以查看每个导入文档的分段信息。
在文档列表中选中文档，再点击分段详情按钮，可以在下方显示详情。

**复现问题的步骤 / Steps to Reproduce**
1. 导入第一个文档，点击按钮，可以显示
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6165791/c5e269b8-0035-472d-951e-6304cd944f54)

3. 导入第二个文档，点击按钮，没有显示
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6165791/9e5d1e9f-555d-4b83-94d8-670ce4eef856)

**代码分析**
前台页面调用后台方法，核心代码如下：
`server/knowledge_base/kb_service/base.py`
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/6165791/78296621-ccb1-49ab-94b8-a4ab08cfb524)

跟踪发现`server/knowledge_base/kb_service/faiss_kb_service.py`中的`get_doc_by_id`方法中，`vs.docstore._dict`的映射表不会随着新增文档而更新。导致新增的文档查不出分段信息。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu-22.04.1
- Python 版本 / Python version: 3.10.13

**Comment by liunux4odoo** [comment]
你添加完第2个文件后，看看知识库根目录下的info.db里面有它的文档信息吗？

**Comment by mazurkas** [comment]
> 你添加完第2个文件后，看看知识库根目录下的info.db里面有它的文档信息吗？

info.db里面有第二次添加文档的信息。
而且从swagger的api页面增加一个接口调用相同的后台方法，也可以得到第二次添加文档信息。
就是在知识库管理页面不行，很怀疑是streamlit页面有缓存。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码试试，一些相关bug已经修复了
