### ISSUE TITLE
[BUG] PDF中关联出来的文档原文文字显示为乱码 

### ISSUE THREAD

**Issue by BrantonLiu** [chatchat-space/Langchain-Chatchat#2160]
**问题描述 / Problem Description**
根据PDF构建的知识库，进行问答后出现的引用文档中，显示为乱码。

**复现问题的步骤 / Steps to Reproduce**
1. 在构建知识库出上传PDF格式的文档后
2. 点击知识库问答对文档内容进行提问
3. 输出结果中展开引用文档
4. 出现错误：内容显示为乱码
![企业微信截图_17008078623908](https://github.com/chatchat-space/Langchain-Chatchat/assets/104844522/9665a2a3-e518-4cad-85f0-b06d926e6bbd)

**预期的结果 / Expected Result**
应该是正常显示中文才对。推测可能和PDF为表格信息有关系

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Ubuntu 9.4.0-1ubuntu1~20.04.1)
- Python 版本 / Python version: 3.10.12

**Comment by zRzRzRzRzRzRzR** [comment]
UTF8的问题？使用的操作系统是windows吗

**Comment by BrantonLiu** [comment]
抱歉，我知道是啥问题了。怪浏览器，用谷歌就可以了 ，火狐是有问题的。

**Comment by BrantonLiu** [comment]
linux上起的脚本，windows上用的web ui。谢谢关注~

**Comment by happy-xlf** [comment]
您好，我的依旧存在乱码情况，如图
<img width="743" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/57625939/1d10d2fb-2a70-4b00-966c-34b2ff455f41">

**Comment by BrantonLiu** [comment]
还了谷歌浏览器还是这样吗，可能得开发组看看。你可以另开一个issue，我这个关掉了
