### ISSUE TITLE
[BUG] API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by yachunchen** [chatchat-space/Langchain-Chatchat#2163]
**问题描述 / Problem Description**
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)。

和默认不同项：
1.后台模型为Qwen-14B-Chat,已经安装flash等。
2.config/kb_config.py中改成"MarkdownHeaderTextSplitter"。

然后在知识库创建界面中添加一个Markdown的文本，主要是以#为开头的文本，类似：
"""
#主题1:
xxxx

#主题2：
xxxx

#主题4：
xxx
。。。
"""
知识库创建成功；
markdown文本添加到知识库成功；
然后返回"对话"，按照markdown中的主题题问题，然后报错：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/30292771/49633c5c-8c06-4d7e-a2a7-13d6bf7301b2)

**Comment by zRzRzRzRzRzRzR** [comment]
看一下后台报错

**Comment by zRzRzRzRzRzRzR** [comment]
filename = Path(doc.metadata["source"]).resolve().relative_to(doc_path)
你试试吧这个markdown转成txt试试？
看看正不正常
对应的# 等markdown符号还要保留

**Comment by GLY-123** [comment]
> filename = Path(doc.metadata["source"]).resolve().relative_to(doc_path) 你试试吧这个markdown转成txt试试？ 看看正不正常 对应的# 等markdown符号还要保留

我就是用的txt，但是内容保留了#，还是上面的问题，报错也还是这个报错filename = Path(doc.metadata["source"]).resolve().relative_to(doc_path)
