### ISSUE TITLE
0.2.7版本VLLM加速按要求配置后没有生效

### ISSUE THREAD

**Issue by zhaofangtao** [chatchat-space/Langchain-Chatchat#2164]
vllm0.2.2, python 3.10， cuda驱动12.0， torch2.1.0， chatglm3-6b模型，m3e-base向量模型，fassis向量库。
从0.2.4升级到0.2.7版后。使用知识库，目前发现三个重要问题：
1.API响应速度慢了2倍多。原来800~1.2秒。现在变成了1.5到3秒
2.同样向量数据和测试集和提示词模板，同样参数，准确率大幅下降。
3.VLLM显存加速按要求设置后，比如VLLM_MODEL_DICT，配置和LLM_MODELS=["chatglm3-6b"..]一致,  infer_turbo："vllm"等。验证没有生效。 跟踪startup.py代码通过层层打日志方式。发现好像没有执行到VLLM的逻辑。
![fd597c6e02c737c9e55cb9527ae3ec0](https://github.com/chatchat-space/Langchain-Chatchat/assets/117793219/ce8c9be4-e341-41ca-983b-8316c45c603d)

请教大佬怎么回事。尤其第三个vllm怎么才能生效呢

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.5大改了框架，但是我们没有测出API大幅度减速，确保不是推理速度的原因？
第二个问题，glm3-6b的模板不适用glm2的，搜索方案也有一定改动，这个需要自己适配一下
至于第三个问题，你改改startup.py中的内容试试？

**Comment by hzg0601** [comment]
重新拉取代码，并按照server_config.py.example的说明修改fschat的代码
