### ISSUE TITLE
英伟达 T4 显卡使用千问 Qwen-7B-Chat-Int4 模型加载错误 ValueError: Found modules on cpu/disk. Using Exllama or Exllamav2 backend requires all the modules to be on GPU.You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object

### ISSUE THREAD

**Issue by Jackle910** [chatchat-space/Langchain-Chatchat#2165]
**问题描述 / Problem Description**
如题，由于 t4 显卡在加载 基础模型Qwen-7B-Chat时显存不够，因此尝试轻量化版本，已经安装了auto-gptq optimum flash-attn，在启动的时候报错:ValueError: Found modules on cpu/disk. Using Exllama or Exllamav2 backend requires all the modules to be on GPU.You can deactivate exllama backend by setting `disable_exllama=True` in the quantization config object

尝试搜索了解决办法，在千问的 issue 中找到了以下解决办法，但不知道在本项目中应该如何配置https://github.com/QwenLM/Qwen/issues/385：
```
1. 量化模型不支持CPU推理：旧版AutoGPTQ (<5.0.0)是不支持的CPU推理的，新版AutoGPTQ有实验性的支持。

2. 量化模型GPU推理，但exllama报错：
   
   * exllama提供了一种高效的kernel实现，仅支持GPTQ方式量化得到的int4模型和Modern GPU，需要所有模型参数在GPU上。AutoGPTQ旧版支持使用exllama的kernel，新版(5.0.0)支持exllama v2的kernel，可开可关，速度影响、显存占用影响，可以参考AutoGPTQ的[benchmark](https://github.com/huggingface/optimum/tree/main/tests/benchmark#batch-size--1)。
   * 在我们的样例代码中，部分使用了`device_map="auto"`，目的是缓解大模型加载的内存/显存压力，有可能一部分参数到内存里去了（可以查看模型的`hf_device_map`确认分配是否合理）。需要改成`device_map="cuda:0"`，这样会全加载到第一张GPU上（或者类似的方法，就是需要让模型都在GPU上）。如果硬件支持、软件版本匹配的话，"Found modules on cpu/disk"的报错可以解决。
     
     * `device_map`参数是利用Hugging Face Accelerate来支持的，它的语义跟`device`是不等价的，后面也不容易再修改模型参数的位置。
     * 如果你的内存/显存确实是不够用，那建议还是用`device_map="auto"`，然后关掉exllama。
   * 如果是exllama不支持，比如int8或者比较旧的显卡，就需要关掉它，GPU上也是能推理运行的。在quantization_config.json或者config.json的quantization_config字段或者代码中，旧版transformers是disable_exllama=True，新版transformers是use_exllama=False，按transformers的版本相应修改。
````
 
，
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master，0.2.7
- 是否使用 Docker 部署（是/否）： 否 / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Linux Ubuntu 22.04.5 keenel version 6.5
- Python 版本 / Python version: Python 3.10.13
- 其他相关环境信息 / Other relevant environment information: cuda 11.8

**附加信息 / Additional Information**
完整的报错信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/45070149/36773dc0-15e8-4740-8350-4665f9be059e)

**Comment by zRzRzRzRzRzRzR** [comment]
这个要改fschat源码的，int4模型不能直接载入，按照提示的位置去对应的地方设置Device map google一下就有

**Comment by pdo2013** [comment]
时间紧迫没有时间看进一步的解决方案，找到model_adapter.py，修改之，添加device_map="auto"：
比我在：lib/python3.10/site-packages/fastchat/model/model_adapter.py
1583         model = AutoModelForCausalLM.from_pretrained(
1584             model_path,
1585             config=config,
1586             low_cpu_mem_usage=True,
1587             trust_remote_code=True,
1588             **from_pretrained_kwargs,
1589             device_map="auto",
1590         ).eval()
