### ISSUE TITLE
华为晟腾910上的适配

### ISSUE THREAD

**Issue by TitusWjt** [chatchat-space/Langchain-Chatchat#2172]
想请问一下如果我想在华为晟腾910b上部署本地模型，该如何修改这个项目

**Comment by fuxiaoiii** [comment]
同问

**Comment by zRzRzRzRzRzRzR** [comment]
开发组没有这个机器，因此，目前不会在这个上面做工作，需要开发者自行适配

**Comment by tommy3266** [comment]
@fuxiaoiii @TitusWjt 两位老哥，请问chatchat在华为昇腾服务器跑起来了吗

**Comment by TitusWjt** [comment]
兄弟，可以加我一起讨论：Love0wjt
















在 2023-12-18 16:17:26，"miao" ***@***.***> 写道：

@***@***.*** 两位老哥，请问chatchat在华为昇腾服务器跑起来了吗

**Comment by Dioxideme** [comment]
@TitusWjt @fuxiaoiii @tommy3266  三位兄弟请问在昇腾910服务器上跑起来了吗？

**Comment by sunnnyu** [comment]
@TitusWjt @fuxiaoiii @tommy3266 @Dioxideme 四位兄弟请问在昇腾上跑起来了吗？

**Comment by sunnnyu** [comment]
您好，邮件已收到。                                                        孙宇

**Comment by fuxiaoiii** [comment]
没有

**Comment by ShawnHoo7256** [comment]
同样交流 也需要在晟腾适配。

**Comment by loki-keroro** [comment]
同问，同求组织，是否有相关的群组，一起拉进去交流一下

**Comment by zmh2000829** [comment]
已适配，欢迎交流，--昇腾910B

**Comment by sunnnyu** [comment]
您好，邮件已收到。                                                        孙宇

**Comment by Dioxideme** [comment]
> 已适配，欢迎交流，--昇腾910B

@zmh2000829 大佬，适配后的工程能否开源

**Comment by loki-keroro** [comment]
> > 已适配，欢迎交流，--昇腾910B
> 
> @zmh2000829 大佬，适配后的工程能否开源

+1

**Comment by loki-keroro** [comment]
怎么实现NPU多进程

**Comment by Maxliag** [comment]
> 已适配，欢迎交流，--昇腾910B

可以交流一下吗

**Comment by GLY-123** [comment]
> 已适配，欢迎交流，--昇腾910B

能交流一下吗

**Comment by Nancy7zt** [comment]
我也需要，能求一个组织吗

**Comment by Nancy7zt** [comment]
> 已适配，欢迎交流，--昇腾910B

能加个组织吗

**Comment by Xavier-123** [comment]
> 已适配，欢迎交流，--昇腾910B

加个组织

**Comment by Nancy7zt** [comment]
你好，您的联系方式是什么

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月11日 09:43 |
| 收件人 | chatchat-space/Langchain-Chatchat ***@***.***> |
| 抄送人 | leozz77 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] 华为晟腾910上的适配 (Issue #2172) |

已适配，欢迎交流，--昇腾910B

加个组织

**Comment by Danki4** [comment]
> 已适配，欢迎交流，--昇腾910B

求个联系方式，有偿请教一下，看见评论的话麻烦回复一下，万分感谢

**Comment by Nancy7zt** [comment]
我已经适配了，欢迎加 v : Leontief651

**Comment by bugrootof** [comment]
@Dioxideme @tommy3266 @zmh2000829 @Xavier-123 @loki-keroro 有人在跑起来3.0版本的没有？
