### ISSUE TITLE
在线 Embeddings如何设置？

### ISSUE THREAD

**Issue by vincil77** [chatchat-space/Langchain-Chatchat#2174]
1.在线 Embeddings，zhipu的在线 Embeddings如何设置？
2.采用最轻模式本地部署方案，如果只设置了LLM（比如智谱的key)，也能成功启动，这时Embeddings使用的是哪个模型及如何工作的？

**Comment by pepperdog999** [comment]
碰到同样的问题，题主解决了么？

**Comment by liunux4odoo** [comment]
使用"zhipu-api"作为embedding_model即可，注意token消耗

**Comment by huaka1** [comment]
请问题主，我也使用最轻模式本地部署方案，按照以下的配置：
EMBEDDING_MODEL = "zhipu-api"，
"zhipu-api": {
        "api_key": "xxxxx",
        "version": "chatglm_turbo",  # 可选包括 "chatglm_turbo"
        "provider": "ChatGLMWorker",
    },

但是报错如下：

 File "/Users/huangaokai/code/python/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 402, in embed_query
    query_embed = embeddings[0]
TypeError: 'NoneType' object is not subscriptable
2023-12-05 14:43:11,688 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

感觉是我的embedding使用有误，请问题主有遇到过这种问题吗？

**Comment by chenwenfeng** [comment]
同样 lite 跑遇到问题 不知道这个EMBEDDING_MODEL该怎么配置

**Comment by lcdisme** [comment]
> 请问题主，我也使用最轻模式本地部署方案，按照以下的配置： EMBEDDING_MODEL = "zhipu-api"， "zhipu-api": { "api_key": "xxxxx", "version": "chatglm_turbo", # 可选包括 "chatglm_turbo" "provider": "ChatGLMWorker", },
> 
> 但是报错如下：
> 
> File "/Users/huangaokai/code/python/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 402, in embed_query query_embed = embeddings[0] TypeError: 'NoneType' object is not subscriptable 2023-12-05 14:43:11,688 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
> 
> 感觉是我的embedding使用有误，请问题主有遇到过这种问题吗？

同样的问题，感觉是embedding的时候，和zhipu-api网络交互有问题，post的返回值是400

**Comment by vincil77** [comment]
配置文件只需要设置：LLM_MODELS = ["zhipu-api"]即可， EMBEDDING_MODEL 不用修改（我的是EMBEDDING_MODEL = "bge-large-zh"，也可以用m3e-base，注意配置文件后面的路径）
使用的时候，在新建知识库界面，从下拉列表选择zhipu-api即可
















在 2023-12-05 14:57:57，"chenwenfeng" ***@***.***> 写道：

同样 lite 跑遇到问题 不知道这个EMBEDDING_MODEL该怎么配置

**Comment by vincil77** [comment]
配置文件只需要设置：LLM_MODELS = ["zhipu-api"]即可， EMBEDDING_MODEL 不用修改（我的是EMBEDDING_MODEL = "bge-large-zh"，也可以用m3e-base，注意配置文件后面的路径，如MODEL_PATH = { "embed_model": { "bge-large-zh": "Embedding/bge-large-zh", 
        "m3e-base":"Embedding/m3e-base",    },），
使用的时候，在新建知识库界面，从下拉列表选择zhipu-api即可，下图
















在 2024-01-03 16:08:58，"lcd" ***@***.***> 写道：

请问题主，我也使用最轻模式本地部署方案，按照以下的配置： EMBEDDING_MODEL = "zhipu-api"， "zhipu-api": { "api_key": "xxxxx", "version": "chatglm_turbo", # 可选包括 "chatglm_turbo" "provider": "ChatGLMWorker", },

但是报错如下：

File "/Users/huangaokai/code/python/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 402, in embed_query query_embed = embeddings[0] TypeError: 'NoneType' object is not subscriptable 2023-12-05 14:43:11,688 - utils.py[line:188] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

感觉是我的embedding使用有误，请问题主有遇到过这种问题吗？

同样的问题，感觉是embedding的时候，和zhipu-api网络交互有问题，post的返回值是400

**Comment by voidreaming** [comment]
同问，使用线上 embedding API 的时候新建知识库显示找不到对应的知识库
<img width="359" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/104676193/a1c48e4a-e331-44b4-9594-e8a89cc53f68">
