### ISSUE TITLE
[BUG] AutoDL通过镜像部署后启动，WebUI界面一直卡在"Please wait..."

### ISSUE THREAD

**Issue by mtics** [chatchat-space/Langchain-Chatchat#2177]
**问题描述 / Problem Description**
我根据wiki中AutoDL部署的教程在AutoDL上部署了Langchain-ChatChat v11。在程序启动后，通过webui界面访问始终停留在"Please wait..."界面

**复现问题的步骤 / Steps to Reproduce**
1. 根据 [AutoDL 镜像](https://www.codewithgpu.com/i/chatchat-space/Langchain-Chatchat/Langchain-Chatchat)部署教程在AutoDL平台选购RTX 3090机器部署Langchain-ChatChat v11
2. 运行`python copy_config_example.py`后修改"configs/model_config.py"中`MODEL_ROOT_PATH`为本地模型存储路径，对应修改`m3e-base`和`chatglm2-6b`的路径
3. 运行`python init_database.py --recreate-vs`
4. 运行`python startup.py -a`

**预期的结果 / Expected Result**
通过 WebUI 进入正常的对话页面

**实际结果 / Actual Result**
WebUI 始终停留在 "Please wait ..." 界面

**环境信息 / Environment Information**
- langchain-ChatChat: v0.2.7，对应AutoDL镜像: v11
- 是否使用 Docker 部署（是/否）：是
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B, OpenAI api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：/root/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 20.04.4 LTS
- Python 版本 / Python version: 3.10.9
- 其他相关环境信息 / Other relevant environment information: langChain: 0.0.333,  fastchat版本：0.2.32

**附加信息 / Additional Information**
以下为运行日志：

python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-100-generic-x86_64-with-glibc2.31.
python版本：3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
项目版本：v0.2.7
langchain版本：0.0.333. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/autodl-tmp/models/llms/chatglm2-6b',
 'port': 20002}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda
==============================Langchain-Chatchat Configuration==============================

2023-11-26 05:27:16,623 - startup.py[line:649] - INFO: 正在启动服务：
2023-11-26 05:27:16,623 - startup.py[line:650] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-Chatchat/logs
2023-11-26 05:27:22 | ERROR | stderr | INFO:     Started server process [23233]
2023-11-26 05:27:22 | ERROR | stderr | INFO:     Waiting for application startup.
2023-11-26 05:27:22 | ERROR | stderr | INFO:     Application startup complete.
2023-11-26 05:27:22 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2023-11-26 05:27:23 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker 2a85997d ...
Loading checkpoint shards:   0%|                                      | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████▎                         | 1/7 [00:01<00:11,  1.89s/it]
Loading checkpoint shards:  29%|████████▌                     | 2/7 [00:03<00:09,  1.81s/it]
Loading checkpoint shards:  43%|████████████▊                 | 3/7 [00:05<00:07,  1.82s/it]
Loading checkpoint shards:  57%|█████████████████▏            | 4/7 [00:07<00:05,  1.78s/it]
Loading checkpoint shards:  71%|█████████████████████▍        | 5/7 [00:09<00:03,  1.81s/it]
Loading checkpoint shards:  86%|█████████████████████████▋    | 6/7 [00:10<00:01,  1.73s/it]
Loading checkpoint shards: 100%|██████████████████████████████| 7/7 [00:11<00:00,  1.41s/it]
Loading checkpoint shards: 100%|██████████████████████████████| 7/7 [00:11<00:00,  1.63s/it]
2023-11-26 05:27:35 | ERROR | stderr |
2023-11-26 05:27:38 | INFO | model_worker | Register to controller
INFO:     Started server process [23329]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-100-generic-x86_64-with-glibc2.31.
python版本：3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
项目版本：v0.2.7
langchain版本：0.0.333. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/autodl-tmp/models/llms/chatglm2-6b',
 'port': 20002}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： m3e-base @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:6006
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:6006

**Comment by mtics** [comment]
在Web端出现了如下错误：WebSocket connection to 'wss://u260100-83c6-049147b9.westx.seetacloud.com:8443/_stcore/stream' failed: 
(anonymous) @ main.ccfdda4f.js:2

**Comment by suqitian** [comment]
应该是AutoDL算力市场做的限制
请用这种方式打开WebUI
https://www.autodl.com/docs/visdom/

**Comment by Hurbery** [comment]
https://www.codewithgpu.com/i/issuedetail/chatchat-space/Langchain-Chatchat/Langchain-Chatchat/169933769345/0    可以看下这个

**Comment by mtics** [comment]
> https://www.codewithgpu.com/i/issuedetail/chatchat-space/Langchain-Chatchat/Langchain-Chatchat/169933769345/0 可以看下这个

这个回答解决了我的问题，很有帮助，谢谢！
