### ISSUE TITLE
请问如何修改相似度计算的方式，具体在项目的哪一块做修改

### ISSUE THREAD

**Issue by promisecc** [chatchat-space/Langchain-Chatchat#2179]
文档召回准确率不高，想试试换一个相似度计算方法，求各位大佬指教

**Comment by zaoqishibing** [comment]
相似度计算方法基本是向量数据库自带的函数里面的，看下对应库的方法下有没有度量参数可以改

**Comment by promisecc** [comment]
> 相似度计算方法基本是向量数据库自带的函数里面的，看下对应库的方法下有没有度量参数可以改

嗯嗯找到了，感谢大佬

**Comment by TZJ12** [comment]
我也遇到了这个问题，请问你是怎么修改的呢
