### ISSUE TITLE
有没有可能新增一个基于chatglm api调用的方式构建langchain

### ISSUE THREAD

**Issue by maolilai** [chatchat-space/Langchain-Chatchat#218]
我有两台8G GPU/40G内存的服务器，一个台做成了chatglm的api ；想基于另外一台服务器部署langchain；网上好像没有类似的代码。

**Comment by imClumsyPanda** [comment]
api支持会在近期加入master分支，并提供api调用demo。

如果您的chatglm也是api形式，建议将models/chatglm_llm.py中的ChatGLM类修改为调用api修改内容即可。

maolilai ***@***.***>于2023年5月2日 周二17:25写道：

**Comment by maolilai** [comment]
期待更新
