### ISSUE TITLE
[BUG] 新版本初始化知识库报错，csv，json，xlsx文件未能成功加载或初始化

### ISSUE THREAD

**Issue by plancktree** [chatchat-space/Langchain-Chatchat#2182]
环境按wiki内容推荐配置，系统是centos，但已按之前issue更新相关lib库和mesa库。
 python init_database.py --recreate-vs
recreating all vector stores
2023-11-27 00:21:47,166 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/m3e-base' from disk.
2023-11-27 00:21:47,551 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /data/model/m3e-base
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.63it/s]
2023-11-27 00:21:50,261 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2023-11-27 00:21:50,277 - loader.py[line:56] - INFO: Successfully loaded faiss with AVX2 support.
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .xlsx，已跳过
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .xlsx，已跳过
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .jsonl，已跳过
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .jsonl，已跳过
2023-11-27 00:21:50,289 - utils.py[line:292] - INFO: CSVLoader used for /home/Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.csv
2023-11-27 00:21:50,289 - utils.py[line:292] - INFO: UnstructuredFileLoader used for /home/Langchain-Chatchat-master/knowledge_base/samples/content/test_files/test.txt
2023-11-27 00:21:50,289 - utils.py[line:292] - INFO: CSVLoader used for /home/Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv
文档切分示例：page_content=': 0\ntitle: 效果如何优化\nfile: 2023-04-04.00\nurl: https://github.com/imClumsyPanda/langchain-ChatGLM/issues/14\ndetail: 如图所示，将该项目的README.md和该项目结合后，回答效果并不理想，请问可以从哪些方面进行优化\nid: 0' metadata={'source': '/home/Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.csv', 'row': 0}
正在将 samples/test_files/langchain-ChatGLM_open.csv 添加到向量库，共包含323条文档
Batches:   0%|                                                                                                                         | 0/11 [00:00<?, ?it/s]2023-11-27 00:21:50,755 - utils.py[line:373] - ERROR: RuntimeError: 从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /home、Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 11/11 [00:00<00:00, 12.57it/s]
('samples', 'test_files/langchain-ChatGLM_closed.csv', '从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /home/Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv')
2023-11-27 00:26:07,238 - utils.py[line:148] - INFO: Note: NumExpr detected 36 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2023-11-27 00:26:07,238 - utils.py[line:160] - INFO: NumExpr defaulting to 8 threads.
文档切分示例：page_content='ChatGPT是OpenAI开发的一个大型语言模型，可以提供各种主题的信息，\n\n# 如何向 ChatGPT 提问以获得高质量答案：提示技巧工程完全指南\n\n## 介绍\n\n我很高兴欢迎您阅读我的最新书籍《The Art of Asking ChatGPT for High-Quality Answers: A complete Guide to Prompt Engineering Techniques》。本书是一本全面指南，介绍了各种提示技术，用于从ChatGPT中生成高质量的答案。' metadata={'source': '/home/Langchain-Chatchat-master/knowledge_base/samples/content/test_files/test.txt'}
正在将 samples/test_files/test.txt 添加到向量库，共包含81条文档
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00,  8.90it/s]
2023-11-27 00:26:36,207 - faiss_cache.py[line:24] - INFO: 已将向量库 ('samples', 'm3e-base') 保存到磁盘
总计用时： 0:04:49.071831

sample中
test_files_langchain-ChatGLM_open.csv可正常添加到向量库
test_files_langchain-ChatGLM_close.csv无法添加，会报错Batches: 0%| | 0/11 [00:00<?, ?it/s]2023-11-27 00:21:50,755 - utils.py[line:373] - ERROR: RuntimeError: 从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /home、Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv
其他csv文件也是这样
langchain-ChatGLM 版本/commit 号：v2.0.7
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan2-13b
使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
Python 版本 / Python version: 3.10.12
GPU显存: 32G

**Comment by plancktree** [comment]
sample中
test_files_langchain-ChatGLM_open.csv可正常添加到向量库
test_files_langchain-ChatGLM_close.csv无法添加，会报错Batches: 0%| | 0/11 [00:00<?, ?it/s]2023-11-27 00:21:50,755 - utils.py[line:373] - ERROR: RuntimeError: 从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /home、Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv
其他csv文件也是这样

**Comment by zaoqishibing** [comment]
我也遇到这个问题

**Comment by plancktree** [comment]
> 我也遇到这个问题

主要是无法理解，为什么第一个CSV能加载第二个不行，我试着把编码统一修改成utf-8还是不行

**Comment by hechushitaoyuan** [comment]
我也遇到了~excel不行~

**Comment by plancktree** [comment]
> 我也遇到了~excel不行~

其他可以？csv或者jsonl

**Comment by zRzRzRzRzRzRzR** [comment]
csv肯定是可以，jsonl应该也没有问题，excel不行吧

**Comment by plancktree** [comment]
> csv肯定是可以，jsonl应该也没有问题，excel不行吧
2023-11-27 00:21:50,277 - loader.py[line:56] - INFO: Successfully loaded faiss with AVX2 support.
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .xlsx，已跳过
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .xlsx，已跳过
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .jsonl，已跳过
2023-11-27 00:21:50,288 - migrate.py[line:77] - ERROR: ValueError: 暂未支持的文件格式 .jsonl，已跳过
Batches: 0%| | 0/11 [00:00<?, ?it/s]2023-11-27 00:21:50,755 - utils.py[line:373] - ERROR: RuntimeError: 从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /home、Langchain-Chatchat-master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv

报错如上，sample文件中，CHATGLM_OPEN.csv只有一个可以，其他的包括我自己的csv文件都无法加载。
我的环境配置为：
python 3.10.12
Package                       Version
----------------------------- ------------
accelerate                    0.24.1
aiohttp                       3.9.0
aiosignal                     1.3.1
altair                        5.1.2
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
async-timeout                 4.0.3
attrs                         23.1.0
backoff                       2.2.1
beautifulsoup4                4.12.2
bitsandbytes                  0.41.2.post2
blinker                       1.7.0
blis                          0.7.11
Brotli                        1.1.0
cachetools                    5.3.2
catalogue                     2.0.10
certifi                       2023.7.22
cffi                          1.16.0
chardet                       5.2.0
charset-normalizer            3.3.2
click                         8.1.7
cloudpathlib                  0.16.0
coloredlogs                   15.0.1
confection                    0.1.3
contourpy                     1.2.0
cryptography                  41.0.5
cycler                        0.12.1
cymem                         2.0.8
dataclasses-json              0.6.1
distro                        1.8.0
effdet                        0.4.1
einops                        0.7.0
emoji                         2.8.0
et-xmlfile                    1.1.0
exceptiongroup                1.1.3
faiss-cpu                     1.7.4
fastapi                       0.104.1
filelock                      3.13.1
filetype                      1.2.0
flatbuffers                   23.5.26
fonttools                     4.44.0
frozenlist                    1.4.0
fschat                        0.2.32
fsspec                        2023.10.0
gitdb                         4.0.11
GitPython                     3.1.40
greenlet                      3.0.1
h11                           0.14.0
h2                            4.1.0
hpack                         4.0.0
httpcore                      1.0.1
httptools                     0.6.1
httpx                         0.25.1
huggingface-hub               0.17.3
humanfriendly                 10.0
hyperframe                    6.0.1
idna                          3.4
importlib-metadata            6.8.0
iniconfig                     2.0.0
install                       1.3.5
iopath                        0.1.10
Jinja2                        3.1.2
joblib                        1.3.2
jsonpatch                     1.33
jsonpointer                   2.4
jsonschema                    4.19.2
jsonschema-specifications     2023.7.1
kiwisolver                    1.4.5
langchain                     0.0.340
langchain-experimental        0.0.42
langcodes                     3.3.0
langdetect                    1.0.9
langsmith                     0.0.66
layoutparser                  0.3.4
lxml                          4.9.3
Markdown                      3.5.1
markdown-it-py                3.0.0
markdown2                     2.4.10
markdownify                   0.11.6
MarkupSafe                    2.1.3
marshmallow                   3.20.1
matplotlib                    3.8.1
mdurl                         0.1.2
mpmath                        1.3.0
msg-parser                    1.2.0
msgpack                       1.0.7
multidict                     6.0.4
murmurhash                    1.0.10
mypy-extensions               1.0.0
networkx                      3.2.1
nh3                           0.2.14
ninja                         1.11.1.1
nltk                          3.8.1
numexpr                       2.8.7
numpy                         1.24.4
nvidia-cublas-cu12            12.1.3.1
nvidia-cuda-cupti-cu12        12.1.105
nvidia-cuda-nvrtc-cu12        12.1.105
nvidia-cuda-runtime-cu12      12.1.105
nvidia-cudnn-cu12             8.9.2.26
nvidia-cufft-cu12             11.0.2.54
nvidia-curand-cu12            10.3.2.106
nvidia-cusolver-cu12          11.4.5.107
nvidia-cusparse-cu12          12.1.0.106
nvidia-nccl-cu12              2.18.1
nvidia-nvjitlink-cu12         12.3.52
nvidia-nvtx-cu12              12.1.105
olefile                       0.46
omegaconf                     2.3.0
onnx                          1.15.0
onnxruntime                   1.15.1
openai                        1.3.5
opencv-python                 4.8.1.78
openpyxl                      3.1.2
packaging                     23.2
pandas                        2.0.3
pathlib                       1.0.1
pdf2image                     1.16.3
pdfminer.six                  20221105
pdfplumber                    0.10.3
peft                          0.6.0
Pillow                        9.5.0
pip                           23.3.1
pluggy                        1.3.0
portalocker                   2.8.2
preshed                       3.0.9
prompt-toolkit                3.0.39
protobuf                      4.24.4
psutil                        5.9.6
pyarrow                       14.0.0
pyclipper                     1.3.0.post5
pycocotools                   2.0.7
pycparser                     2.21
pydantic                      1.10.13
pydeck                        0.8.1b0
Pygments                      2.16.1
PyMuPDF                       1.23.6
PyMuPDFb                      1.23.6
pypandoc                      1.12
pyparsing                     3.1.1
pypdfium2                     4.23.1
pytesseract                   0.3.10
pytest                        7.4.3
python-dateutil               2.8.2
python-decouple               3.8
python-docx                   1.1.0
python-dotenv                 1.0.0
python-iso639                 2023.6.15
python-magic                  0.4.27
python-multipart              0.0.6
python-pptx                   0.6.23
pytz                          2023.3.post1
PyYAML                        6.0.1
rapidfuzz                     3.5.2
rapidocr-onnxruntime          1.3.8
ray                           2.8.0
referencing                   0.30.2
regex                         2023.10.3
requests                      2.31.0
rich                          13.6.0
rpds-py                       0.12.0
safetensors                   0.4.0
scikit-learn                  1.3.2
scipy                         1.11.3
sentence-transformers         2.2.2
sentencepiece                 0.1.99
setuptools                    68.0.0
shapely                       2.0.2
shortuuid                     1.0.11
simplejson                    3.19.2
six                           1.16.0
smart-open                    6.4.0
smmap                         5.0.1
sniffio                       1.3.0
socksio                       1.0.0
soupsieve                     2.5
spacy                         3.7.2
spacy-legacy                  3.0.12
spacy-loggers                 1.0.5
SQLAlchemy                    2.0.19
srsly                         2.4.8
starlette                     0.27.0
streamlit                     1.27.2
streamlit-aggrid              0.3.4.post3
streamlit-antd-components     0.2.3
streamlit-chatbox             1.1.11
streamlit-feedback            0.1.2
streamlit-option-menu         0.3.6
strsimpy                      0.2.1
style                         1.1.0
svgwrite                      1.4.3
sympy                         1.12
tabulate                      0.9.0
tenacity                      8.2.3
thinc                         8.2.1
threadpoolctl                 3.2.0
tiktoken                      0.5.1
timm                          0.9.10
tokenizers                    0.13.3
toml                          0.10.2
tomli                         2.0.1
toolz                         0.12.0
torch                         2.1.0
torchaudio                    2.1.0
torchvision                   0.16.0
tornado                       6.3.3
tqdm                          4.66.1
transformers                  4.34.0.dev0
transformers-stream-generator 0.0.4
triton                        2.1.0
typer                         0.9.0
typing_extensions             4.8.0
typing-inspect                0.9.0
tzdata                        2023.3
tzlocal                       5.2
unstructured                  0.11.0
unstructured-inference        0.7.15
unstructured.pytesseract      0.3.12
update                        0.0.1
urllib3                       2.0.7
uvicorn                       0.23.2
uvloop                        0.19.0
validators                    0.22.0
vllm                          0.2.0
wasabi                        1.1.2
watchdog                      3.0.0
watchfiles                    0.21.0
wavedrom                      2.0.3.post3
wcwidth                       0.2.9
weasel                        0.3.4
websockets                    12.0
wheel                         0.41.2
wrapt                         1.16.0
xformers                      0.0.22.post7
xlrd                          2.0.1
XlsxWriter                    3.1.9
yarl                          1.9.2
zipp                          3.17.0

**Comment by plancktree** [comment]
使用0.2.8dev后，jsonl和xlsx问题解决，csv问题依然存在

**Comment by ExpressGit** [comment]
0.2.8dev版本没有看到

**Comment by plancktree** [comment]
> 0.2.8dev版本没有看到

我CSV还是有部分无法加载

**Comment by zRzRzRzRzRzRzR** [comment]
csv目前默认的是两列，第一类问题，第二列答案，寄了就是qa对，如果你的csv不只是两列，你需要自己写读入方式，一个简单的自定义模板已经在loader中写了

**Comment by qianma819** [comment]
最新版本没有这个问题了。用最新版本就可以
