### ISSUE TITLE
部署后本机可以访问 swagger  以及 webui  但是到外网的另一台机器 访问不到

### ISSUE THREAD

**Issue by fqdltd** [chatchat-space/Langchain-Chatchat#2183]
这是本机访问的截图
![1701051044626](https://github.com/chatchat-space/Langchain-Chatchat/assets/54496085/205592f6-5bfb-4f02-9cf5-fd4a36a8a150)

这是外网用IP+端口访问的截图
![Uploading 1701051194075.jpg…]()

**Comment by zRzRzRzRzRzRzR** [comment]
这肯定访问不到啊，如果是服务器肯定要放你局域网的IP啊放127没人连的到除非你是穿透的

**Comment by CapitaineNemo** [comment]
> 这肯定访问不到啊，如果是服务器肯定要放你局域网的IP啊放127没人连的到除非你是穿透的

但是我放局域网里面的IP也不行，但是另外一个LangChain的服务是可以的。

**Comment by CapitaineNemo** [comment]
@fqdltd  请问解决了吗，我的是同一个局域网也不行。总是服务决绝访问。
