### ISSUE TITLE
torch=2.0.1和xformers版本冲突

### ISSUE THREAD

**Issue by jersonal** [chatchat-space/Langchain-Chatchat#2184]
requirements.txt要求torch=2.0.1及以上，xformers要求0.0.22.post4，但该版本xformers要求torch=2.1.0，我现在安装的torch2.0.1不知道如何进行，重新安装torch2.1.0需要更换cuda11.8 ，还有其他解决方案吗？

**Comment by ShinyWey** [comment]
把xformers==0.0.22.post4后面的版本号删掉就行了
改成xformers

**Comment by zzflybird** [comment]
pip install xformers==0.0.22.post4 --index-url https://download.pytorch.org/whl/cu118

**Comment by zRzRzRzRzRzRzR** [comment]
现在应该更到pytorch 2.1 xformer 0.22.post7了吧，上面的方法也是可以的

**Comment by deeplearningers** [comment]
good job
