### ISSUE TITLE
上传文件耗时长 & 知识库容纳总量

### ISSUE THREAD

**Issue by Madilynalisa** [chatchat-space/Langchain-Chatchat#2185]
**问题描述 / Problem Description**
1. 上传pdf文档以及添加到向量库耗时太长

**复现问题的步骤 / Steps to Reproduce**
1. 知识库上传15M大小的PDF文档，耗时18min
2. 12个文档（都在6M以下）共同添加至向量库，耗时超过30min

**预期的结果 / Expected Result**
耗时减少

**实际结果 / Actual Result**
添加文档以及添加至向量库耗时过长

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-bge-large-Chinese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- Python 版本 / Python version: 3.10
- GPU显存: 24G

**附加信息 / Additional Information**
另外，想请教一下：文档总量可能超过100G（单个文档不超过200M），知识库能否容纳？上传文档是否可能因已存在的文档过多而报错？

**Comment by GAllllong** [comment]
蹲一个，向量化的时间确实太长了。

**Comment by a656418zz** [comment]
+1，其实是可以向量化100G的文件的，只不过不能通过webui上传，上传大小限制我认为是streamlit的问题，希望能解除这部分的限制

**Comment by zRzRzRzRzRzRzR** [comment]
> +1，其实是可以向量化100G的文件的，只不过不能通过webui上传，上传大小限制我认为是streamlit的问题，希望能解除这部分的限制

可以直接放在后台向量化
