### ISSUE TITLE
chatglm2-6b一直在输出重复内容

### ISSUE THREAD

**Issue by dbtzy** [chatchat-space/Langchain-Chatchat#2189]
**问题描述 / Problem Description**
chatglm2-6b一直在输出重复内容

**复现问题的步骤 / Steps to Reproduce**
1. 选择对话模式，模板default，输入问题如下（已经手动套入模板）
```
<指令>请根据提供的报错信息，用简洁且专业的语言给出解决该报错信息的处理流程，如有可能请一并给出导致该报错信息发生的根本原因。如果你无法得到答案，请说“无法解决该问题”。不允许在答案中添加编造成分，但可以给出建设性的合理化意见或建议，答案请使用中文。</指令>
<问题>“CTY-YZ-JS-YZ-MTDD-01D04F403-J01_09-13U19-H3C-S7606-DSW %%10DRVPLAT/4/SOFTCAR DROP: -Slot=2;   Cos=15, Drop at Stage=31, StageCnt=721788, TotalCnt=30711809, possible protocol ARP/RARP/VSI_ARP/VSI_RARP/ARP_DAI/ARP_DAI_VLAN/IPV6_RA_GUARD/IPV6_RAGUARD_ROLE/VSI_ARP_PROXY/MDNS/SADP/MDNS_GATE_WAY/ARP_DAI_PORT”这行报错信息你了解多少</问题>
```
3. 会持续输出相同内容
![FYW (9G%9YZ(QZLQYYBKFG0](https://github.com/chatchat-space/Langchain-Chatchat/assets/30386626/cfc7468e-a4d0-4880-88ef-4564127e320a)

**预期的结果 / Expected Result**
正常结束

**实际结果 / Actual Result**
持续输出

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.7.0
- 是否使用 Docker 部署（是/否）：在docker容器，但不是官方提供
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：beg-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu22.04
- Python 版本 / Python version: 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
这个是模型的问题了，重复几次试试，或者换glm3-6b，我们使用fschat接入的大模型
