### ISSUE TITLE
电脑是intel的集成显卡；  运行时告知我找不到nvcuda.dll，模型无法运行

### ISSUE THREAD

**Issue by ClintYue** [chatchat-space/Langchain-Chatchat#219]
您好，我的电脑是intel的集成显卡，不过CPU是i5-11400 @ 2.60GHz   ，内存64G；

运行时告知我找不到nvcuda.dll，模型无法运行；

装了几个Gnvidia的开发者包后，还是同样报错。网上找了nvcuda.dll，都太旧；全C盘搜索了这个文件，找不到。

请问如何直接用CPU运行，而绕过nvcuda这个要求呢？

已经将两处的选择项写死：
EMBEDDING_DEVICE = "cpu"
LLM_DEVICE = "cpu"

**Comment by imClumsyPanda** [comment]
请问报错发生的对应项目中代码是在什么位置

ClintYue ***@***.***>于2023年5月2日 周二19:29写道：

**Comment by ClintYue** [comment]
D:\anaconda4\python.exe D:\anaconda4\envs\langchain-ChatGLM\webui.py 
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Could not find module 'nvcuda.dll' (or one of its dependencies). Try using the full path with constructor syntax.
模型未成功加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

代码位置未知，我想过把整个cuda里相关代码注销掉，但是后来想到nvcuda找不到，webui还是正常运行的，这样即使注销掉相关代码，该运行不了的还是运行不了

**Comment by imClumsyPanda** [comment]
建议先使用cli_demo测试排故，测试没问题后再使用webui进行使用，gradio的报错信息目前看下来比较不友好。

ClintYue ***@***.***>于2023年5月2日 周二19:35写道：

**Comment by CYTand** [comment]
这个貌似是huggingface的模型下载机制导致的，你手动下载模型后改成本地路径试试？
