### ISSUE TITLE
[BUG] 无法使用CUDA加载模型

### ISSUE THREAD

**Issue by kenshintiti** [chatchat-space/Langchain-Chatchat#2190]
显卡4070TI，CUDA12.3，pytorch 12.1和11.8都试过，使用CUDA无法启动。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/122197125/4b3de791-27b8-447a-9092-880b23629f5f)

**Comment by WangXBruc** [comment]
same error

**Comment by HaoHaoDaYouXi** [comment]
cuda安装有问题，没有启用，无法使用

**Comment by HaoHaoDaYouXi** [comment]
py建议版本用10或11的

**Comment by zRzRzRzRzRzRzR** [comment]
pytorch或者cuda不对，建议查看pytorch官网查看windows如何下载pytorch
