### ISSUE TITLE
[bug] 无法只使用在线模型

### ISSUE THREAD

**Issue by hponiang** [chatchat-space/Langchain-Chatchat#2194]
**功能描述 / Feature Description**
我在本地做调式，大模型直接用 openai ，怎么设置参数啊，我已经完善 model_config 里key等参数设置，
要运行的 LLM 名称，可以包括本地模型和在线模型。
 第一个将作为 API 和 WEBUI 的默认模型
LLM_MODELS = ["openai-api"]

启动的时候使用参数
python startup.py -a --model-worker --model-name openai-api

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8768585/78de6063-803b-4879-87c9-d9f2666c7d28)
启动是报错截图，我应该怎么配置，本地调试机器一般怎么跑，请大神指教

**Comment by mes9s0** [comment]
请问解决了吗？我也遇到了一样的问题

**Comment by hponiang** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/2067
确认是 bug

**Comment by zRzRzRzRzRzRzR** [comment]
更新到0.2.8就行了
