### ISSUE TITLE
如何编写客户端代码来通过api使用服务器上本地模型的能力？

### ISSUE THREAD

**Issue by ijiami-01** [chatchat-space/Langchain-Chatchat#2196]
为什么我已经指定了使用本地模型了，可还是在走OpenAi的接口？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129148313/92200786-cc16-4d52-b956-67a4fd895a40)

我明明按照接口文档填写了啊。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129148313/180d9db8-e2f0-4d9c-b004-25c5b8f02b10)

**Comment by zRzRzRzRzRzRzR** [comment]
我们中间都会走Langchain的openai接口，封装成这样的

**Comment by ijiami-01** [comment]
> 我们中间都会走Langchain的openai接口，封装成这样的

可我要用自己的Qwen-LLM 问答模型，怎么写代码呢。
