### ISSUE TITLE
kb_config注释需更新

### ISSUE THREAD

**Issue by ShinyWey** [chatchat-space/Langchain-Chatchat#2197]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/43652786/69e539be-956c-44d1-86d0-bdeabf46ec5d)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/43652786/232c922c-be2f-4345-83d6-9567096d2512)
所以是以哪个为准

**Comment by zRzRzRzRzRzRzR** [comment]
有一些Embed模型的阈值会超过1，因此改成了2，取值范围以你的Embed模型为准

**Comment by ShinyWey** [comment]
> 有一些Embed模型的阈值会超过1，因此改成了2，取值范围以你的Embed模型为准

原来如此, 谢谢解惑.

**Comment by zixiaotan21** [comment]
> 有一些Embed模型的阈值会超过1，因此改成了2，取值范围以你的Embed模型为准

@zRzRzRzRzRzRzR 同样遇到这个问题，谢谢解答！想请教一下，如果我使用的是bge-large0zh-v1.5 embedding模型，这个模型的阈值会超过1吗
