### ISSUE TITLE
[BUG] 知识库查询新增报错

### ISSUE THREAD

**Issue by wenzhenkun** [chatchat-space/Langchain-Chatchat#2201]
0.2.6版本，查询知识库报错
knowledge_base/list_knowledge_bases
报错信息
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: knowledge_base
[SQL: SELECT knowledge_base.kb_name AS knowledge_base_kb_name 
FROM knowledge_base 
WHERE knowledge_base.file_count > ?]
[parameters: (-1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

新增知识库api 
create_knowledge_base
{
  "knowledge_base_name":"test2",
  "vector_store_type": "faiss",
  "embed_model": "text2vec"
}

报错信息
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: knowledge_base
[SQL: SELECT knowledge_base.id AS knowledge_base_id, knowledge_base.kb_name AS knowledge_base_kb_name, knowledge_base.kb_info AS knowledge_base_kb_info, knowledge_base.vs_type AS knowledge_base_vs_type, knowledge_base.embed_model AS knowledge_base_embed_model, knowledge_base.file_count AS knowledge_base_file_count, knowledge_base.create_time AS knowledge_base_create_time 
FROM knowledge_base 
WHERE knowledge_base.kb_name = ?
 LIMIT ? OFFSET ?]
[parameters: ('test2', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by WangXBruc** [comment]
same error
