### ISSUE TITLE
新版本cannot import name 'PromptTemplate' from 'langchain.prompts.chat'

### ISSUE THREAD

**Issue by GLY-123** [chatchat-space/Langchain-Chatchat#2203]
**问题描述 /执行startup.py时报错ImportError：cannot import name 'PromptTemplate' from 'langchain.prompts.chat'
**环境信息：
python                    3.8.18
langchain                 0.0.341
langchain-experimental    0.0.42

**解决办法
/data/anaconda3/envs/langchain/lib/python3.8/site-packages/你的运行环境/prompts/chat.py
到这个目录下将 from langchain.prompts import PromptTemplate增加进去

**Comment by liuzj288** [comment]
多谢，已解决报错问题
from langchain_core.prompts.chat import (
    AIMessagePromptTemplate,
    BaseChatPromptTemplate,
    BaseMessagePromptTemplate,
    BaseStringMessagePromptTemplate,
    ChatMessagePromptTemplate,
    ChatPromptTemplate,
    HumanMessagePromptTemplate,
    MessageLike,
    MessageLikeRepresentation,
    MessagePromptTemplateT,
    MessagesPlaceholder,
    PromptTemplate,
    SystemMessagePromptTemplate,
    _convert_to_message,
    _create_template_from_message_type,
)

**Comment by zRzRzRzRzRzRzR** [comment]
控制到0.0.340 不要在更新了，我们0.28会改一下依赖，之后要重写
