### ISSUE TITLE
[询问帖] 我该如何在该项目使用ChatGLM-LoRA呢

### ISSUE THREAD

**Issue by ShanJianSoda** [chatchat-space/Langchain-Chatchat#2204]
查阅了WiKi中的 **使用自定义的微调模型** 以及 **微调模型加载实操**， 但是看不太懂，望解答

附上：
已经微调好的chatglm
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/128208553/944373ee-0b58-4978-8664-be80701c3c21)

**Comment by zRzRzRzRzRzRzR** [comment]
wi如果你是用llama-factory那套来做的话，你应该按照wiki中的合并peft的方式或者直接用factory的导出成一个完整的大模型
