### ISSUE TITLE
请问如何实现前端的实时流式输出呢？

### ISSUE THREAD

**Issue by dongkuang** [chatchat-space/Langchain-Chatchat#2205]
接口当前流输出设置为“true”，也要等到全部结果生成后，再一点点推给前端，不能生成一部分就实时推一部分

希望能生成一部分就实时推一部分给前端

我看自带的webui是可以的，不知道怎么实现的？可否分享出来，谢谢！

**Comment by a994862495** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/1712
详细请查看这个文档
pip install sse_starlette
from sse_starlette.sse import EventSourceResponse
修改chat.py和knowledge_base_chat.py中的StreamingResponse替换为EventSourceResponse即可通过SSE的方式进行输出

**Comment by dongkuang** [comment]
> #1712 详细请查看这个文档 pip install sse_starlette from sse_starlette.sse import EventSourceResponse 修改chat.py和knowledge_base_chat.py中的StreamingResponse替换为EventSourceResponse即可通过SSE的方式进行输出

谢谢，已解决
