### ISSUE TITLE
[FEATURE] 企业型工程化部署架构和硬件部署要求

### ISSUE THREAD

**Issue by youbingchenyoubing** [chatchat-space/Langchain-Chatchat#2206]
**功能描述 / Feature Description**
工程化部署这个工程,并能支持一定的并发能力.

**解决的问题 / Problem Solved**
想在中型企业部署一个私有知识库问答,数据量TB级别,日活200+, 并发量算10次/s

**实现建议 / Implementation Suggestions**
提供分布式部署的架构,GPU、磁盘等基本估算方法.能否将数据导入,和问答分开,不让在数据导入,资源都被占用

**替代方案 / Alternative Solutions**
之前在单机稍微上传大一些资料,就会导致资源溢出,导致用户端界面模型失效(参考下面图片)
<img width="1188" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/10653481/cc995a69-7604-46a9-bd68-43dec4657ad5">

**Comment by zRzRzRzRzRzRzR** [comment]
建议提供PR，我们将根据PR来进行项目贡献
