### ISSUE TITLE
根据langchain官方的文档和使用模式，是否可以改Faiss为Elasticsearch？会需要做哪些额外调整？求解

### ISSUE THREAD

**Issue by hongzhew** [chatchat-space/Langchain-Chatchat#221]
本人新手小白，由于业务模式的原因（有一些自己的场景和优化），希望利用Elasticsearch做这个体系内部的检索机制，不知道是否可以替换，同时，还会涉及到哪些地方的改动？或者说可能会有哪些其他影响，希望作者和大佬们不吝赐教！

**Comment by imClumsyPanda** [comment]
需要在local_doc_qa.py中把FAISS相关代码修改一下

**Comment by guruhao** [comment]
我最近也在考虑用es实现，还没动手。但是大概的概念看了一下。

说简单也简单，说麻烦也麻烦，ElasticSearch默认是个全文搜索引擎，做不了向量搜索的。
但最近的版本加了一个data type是vector索引字段。可以用来做knn相似度的向量搜索。
所以理论上在改local_doc_qa的FAISS之前，要先改造你的es建立索引的过程，除了通常的全文索引之外，对于每一个document还要额外添加一个向量类型的字段，然后用任何一个向量模型，把你的待搜索的内容生成一个向量，然后存入这个新字段。

如何构造向量取决于你的业务场景，看你要做聊天机器人，还是知识问答。比如只做文献搜索的话，可以把只生成title, key word和abstract的向量之类的，因为通常es的库相比数个pdf文档实在太大了，上亿记录和TB级常见。 你如果所有的文档内容都向量化然后做知识问答的话，我怀疑向量生成，存储，还是查询，总有个环节会先死。

所以先考虑一下你的场景，在来看怎么改代码，工作量大部分应该不是在换个存储接口那里。
用ES的好处就是这样可以做hybrid search，他本身是半结构化的，可以同时匹配 关键字，全文搜索，以及向量搜索。ES还可以设置很复杂精准的搜索条件。比如"最近5年，有中国人参与的关于NLP/LLM的论文"，当然ES是不认识这种自然语言查询的，你可能还得先把这句话用LLM翻译成ES的查询接口。

官网有些blog，怎么在es里构造向量搜索的，比如这里和下面引用的一些文章
https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch

**Comment by hongzhew** [comment]
> 我最近也在考虑用es实现，还没动手。但是大概的概念看了一下。
> 
> 说简单也简单，说麻烦也麻烦，ElasticSearch默认是个全文搜索引擎，做不了向量搜索的。 但最近的版本加了一个data type是vector索引字段。可以用来做knn相似度的向量搜索。 所以理论上在改local_doc_qa的FAISS之前，要先改造你的es建立索引的过程，除了通常的全文索引之外，对于每一个document还要额外添加一个向量类型的字段，然后用任何一个向量模型，把你的待搜索的内容生成一个向量，然后存入这个新字段。
> 
> 如何构造向量取决于你的业务场景，看你要做聊天机器人，还是知识问答。比如只做文献搜索的话，可以把只生成title, key word和abstract的向量之类的，因为通常es的库相比数个pdf文档实在太大了，上亿记录和TB级常见。 你如果所有的文档内容都向量化然后做知识问答的话，我怀疑向量生成，存储，还是查询，总有个环节会先死。
> 
> 所以先考虑一下你的场景，在来看怎么改代码，工作量大部分应该不是在换个存储接口那里。 用ES的好处就是这样可以做hybrid search，他本身是半结构化的，可以同时匹配 关键字，全文搜索，以及向量搜索。ES还可以设置很复杂精准的搜索条件。比如"最近5年，有中国人参与的关于NLP/LLM的论文"，当然ES是不认识这种自然语言查询的，你可能还得先把这句话用LLM翻译成ES的查询接口。
> 
> 官网有些blog，怎么在es里构造向量搜索的，比如这里和下面引用的一些文章 https://www.elastic.co/blog/text-similarity-search-with-vectors-in-elasticsearch



> 需要在local_doc_qa.py中把FAISS相关代码修改一下



> 需要在local_doc_qa.py中把FAISS相关代码修改一下

感谢作者指出位置
