### ISSUE TITLE
多个用户同时对话时，界面反馈按钮报错

### ISSUE THREAD

**Issue by yph0925** [chatchat-space/Langchain-Chatchat#2215]
多个用户同时问问题时，前端界面的反馈按钮报错，Bad 'setIn' index 3 (should be between [0, 2])

**Comment by zRzRzRzRzRzRzR** [comment]
界面反馈按钮报错还没做，这个只是一个空的指令目前，可以先注释掉这部分代码，这个代码之后没有东西目前
