### ISSUE TITLE
vicuna模型加载不了，在llm_models的路径，要求不能包含小数点，但是vicuna的仓库就是v1.5，vicuna在这里疯狂报错。

### ISSUE THREAD

**Issue by Barry1915** [chatchat-space/Langchain-Chatchat#2217]
作者看看这个问题
 
![f7f079baf4f4d7e0153358d14feb69f](https://github.com/chatchat-space/Langchain-Chatchat/assets/76513632/73dddcc5-b05a-42df-8a62-e3c1d76a6db4)

**Comment by zRzRzRzRzRzRzR** [comment]
这个是huggingface的问题了，不是我们项目的问题，试着换个hf版本
