### ISSUE TITLE
模型选择那边只显示了一个模型,在线模型什么的都没了

### ISSUE THREAD

**Issue by miracletiger** [chatchat-space/Langchain-Chatchat#2225]
**问题描述 / Problem Description**
模型选择那边只显示了一个模型,在线模型什么的都没了,以前是能显示所有的本地模型和在线模型的,现在只显示了 LLM_MODELS 中的第一个,请问该如何配置
**复现问题的步骤 / Steps to Reproduce**
部署的0.2.7
**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
 
![screenshot-20231130-091526](https://github.com/chatchat-space/Langchain-Chatchat/assets/17160259/cef12e33-2096-44d5-98c4-62e76ce8dd72)

**环境信息 / Environment Information**
langchain                     0.0.340
直接部署  python startup.py -a
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）LLM_MODELS = ["wizardcoder-15b","chatglm2-6b", "openai-api"]    #"chatglm2-6b",  "openai-api"
新版本的LLM_MODELS 替换了0.2.5 的LLM_MODEL

- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
Duplicate of #2037
