### ISSUE TITLE
wiki文档感觉需要更新了，在研究agent这一块的时候发现文件目录与文档写的不匹配

### ISSUE THREAD

**Issue by Ginorva** [chatchat-space/Langchain-Chatchat#2227]

**Comment by zRzRzRzRzRzRzR** [comment]
emm，哪个地方不匹配，这个地方我写的文档我感觉是匹配的？

**Comment by Starlento** [comment]
> emm，哪个地方不匹配，这个地方我写的文档我感觉是匹配的？

抱歉打扰，一个quick question。现在默认来说chatglm3是可以直接用agent问答吗？
还是需要做https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84-agent-%E5%B7%A5%E5%85%B7的事情。
<img width="645" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/33574105/72376c8c-9193-47ec-acc7-c6c958694a7b">
我试了一下结果是不对的。
