### ISSUE TITLE
历史对话过程报错: utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by pengxianggui** [chatchat-space/Langchain-Chatchat#2228]
**问题描述 / Problem Description**
借助server api， 我发现以下问题：llm对话时(其他几个估计也有)，当请求参数中的history给值时，对话过程就会发生标题这个错误。如果将model_config中的HISTORY_LEN调大一些，那么可能能多对话几次，但在接近此值，或者达到此值仍然会报这个错误。

我的环境是在window本地，通过lite模式，调用的zhipu-api。这个错误也是发生在对话期间，而不是启动或者，一句对话都无法进行。

有没有大佬帮忙解答下，感激不尽！

**Comment by pengxianggui** [comment]
发现出现这个错误后，有时再次发问，又能回复，但概率很低。

**Comment by kkevin26** [comment]
同样的问题，我这边是本地部署的ChatGLM2，没有GPU所以LLM和Embedding都是CPU运行，只要对话就会报 
utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()，就是openai.py里面 392行 if len(chunk["choices"]) == 0: 这行报错。

我是不管调history条数多少都会报错，完全一句对话都进行不了。

**Comment by pengxianggui** [comment]
> 我的最后发现是显卡的显存爆满了导致的，把词嵌入模型归到cpu下，解决了

大佬，具体怎么操作呢？我不懂python呢

**Comment by pengxianggui** [comment]
> 我的最后发现是显卡的显存爆满了导致的，把词嵌入模型归到cpu下，解决了

@zaoqishibing 大佬，我是lite模式，用的zhipu-api的接口，应该不存在显存问题吧？

**Comment by pengxianggui** [comment]
如果入参的history重置为空数组，又可以。感觉是历史记录引起的问题，跟其他几个类似的issue完全不相同

**Comment by pengxianggui** [comment]
> 我的最后发现是显卡的显存爆满了导致的，把词嵌入模型归到cpu下，解决了

@zaoqishibing  是通过更改model_config.py里的EMBEDDING_DEVICE值为"cpu"吧？我改了并没用作用。我通过上面 @kkevin26 的指示，发现了chat_models\openai.py 里报错的那句代码，但真正原因是提示"'zhipu-api请求API时发生错误：__str__ returned non-string (type NoneType)'", 我截了个图：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/16299169/2dd5f823-04aa-4823-bc61-fb0e70cc535c)

比较奇怪了，莫非是zhipu-ai的接口给我报错了？

**Comment by onlineDu** [comment]
> 我在Error提示的openai.py中打印了chunk的log信息,如![1A86E8BFAF2783C15BCDA62E980FAF35](https://github.com/chatchat-space/Langchain-Chatchat/assets/53588397/d54e75e1-9e83-4b8f-a5e9-551ad7a00e93)下图所示 : 可以看到是由于cudart初始化失败引起的error.

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53588397/56e4ce13-94df-4b37-a8e4-3c91638877f8)

> 百度解决方案↓↓↓,导入对应cuda版本的cudatoolkit即可解决

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53588397/60bf5c70-0a93-4977-b7cc-09347997a461)
> 附:我本地langchain-chatchat配置
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53588397/8096a581-69e8-4823-8769-3bd64ae65540)

### 只是提供一个解决思路,如何不能帮到你,你也可以像我一样把相应的变量打印出来查看接口返回结果,然后再决定解决方案

**Comment by maxusheng123** [comment]
我也遇到类似的问题，我自己尝试过调整召回的向量数top_k,默认是3，我改成1的时候一般不会报错，我自己总结：是因为召回的内容过长的原因，可能是因为我的单个文件内容过长，但是除了这种方法不知道有没有更好的方法。以上只是我自己尝试的，也不知道对不对。

**Comment by Metasymbols** [comment]
> 的问题，我布拉格是本地部署的ChatGLM2，没有GPU所以LLM和Embedding都是相同的CPU运行，只要对话就会报 utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType ' 没有 len()，就是 openai.py 里面 392 行 if len(chunk["choices"]) == 0: 这行报错。 我是不管调历史条多少都会报错，完全一句对话都进行不了。
> 
> 编辑：发现问题了，我以为使用本地部署模型可以走不了openai的api，但好像不是这样的，不管怎么样都要走openai的api；把chunk出来就发现好像是openai api的问题。 { ' id'：无，'选择'：无，'创建'：无，'模型'：无，'对象'：无，'system_fingerp rint'：无，'文本'：'**由于高流量而出现网络错误。请重新生成或刷新此页面。**\n\n(mixed dtype (CPU): 所有输入必须共享相同的数据类型。)', 'error_code': 50001}，然后它解析不了这个块。

**Comment by Metasymbols** [comment]
这个问题是怎么解决的，我是调用通义qwenAPI的，一样的问题，流函数 返回的是空str类型，所以报错

**Comment by kaixuanjames** [comment]
同样的问题，我这边是本地部署的baichuan2-13b，LLM和Embedding都是GPU运行，只要对话就会报
utils.py[line:25] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()，请问有朋友解决了这个问题了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
baichuan2-13b 降级transomers，
