### ISSUE TITLE
[BUG] 删除知识库文件时，index.faiss和index.pkl的内容并没有同步删除

### ISSUE THREAD

**Issue by fsj621** [chatchat-space/Langchain-Chatchat#2232]
删除知识库文件值删除了info.db数据库的内容，而没有同步删除向量库的内容

我在删除知识库所有文件后查询向量库内容依然存在向量
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/126898251/9bdc505f-1cec-4a33-8cc8-b126f4a53c37)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到dev看看还在不在

**Comment by fsj621** [comment]
更新到dev还是有这个问题，而且出处都是none
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/126898251/9fcaa7b2-b32e-495a-98ce-ba7e08f56592)
