### ISSUE TITLE
请教一下如何添加Qwen-7B-Chat或者Qwen-14B-Chat模型

### ISSUE THREAD

**Issue by zheng-zy** [chatchat-space/Langchain-Chatchat#2234]
**问题描述 / Problem Description**
在部署0.2.7版本代码里面怎么添加Qwen-7B-Chat或者Qwen-14B-Chat模型，而且机器无法访问https://huggingface.co/网站下载资源，怎么处理吧本地模型添加进去，有没有相关文档

**复现问题的步骤 / Steps to Reproduce**
1. 修改配置vi configs/model_config.py，在LLM_MODELS = ["chatglm2-6b", "zhipu-api","Qwen-14B-Chat", "openai-api"]新增Qwen配置
2. 执行`python startup.py -a`启动程序报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13825054/07f93fb8-0d12-4df4-bb26-5991904586a1)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:ubutu
- Python 版本 / Python version:Python 3.10.9
- 其他相关环境信息 / Other relevant environment information: 使用chatchat-space/Langchain-Chatchat/Langchain-Chatchat:v11
镜像

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki中有导入本地模型的文档，情确定模型是否完整
