### ISSUE TITLE
[BUG] 新版本知识库导入 json文件，中文乱码

### ISSUE THREAD

**Issue by ExpressGit** [chatchat-space/Langchain-Chatchat#2236]
**问题描述 / Problem Description**
知识库导入 json文件，json文件格式为 UTF-8

**复现问题的步骤 / Steps to Reproduce**
知识库导入 json文件

**预期的结果 / Expected Result**
正确解析中文 json文件

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11694747/637cea7e-3991-46ea-86b4-af1dad774be5)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.27
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:centos7
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
这不是乱码，是unicode码，下个版本将进行修复。
