### ISSUE TITLE
前端使用eventsource无法触发onmessage

### ISSUE THREAD

**Issue by reddeath1985** [chatchat-space/Langchain-Chatchat#2237]
您好，我要使用vue自行开发前端界面，使用eventsource调用/chat/chat接口时无法通过eventstream获取到实时生成的文字。只能等到所有文字生成以后才能在response里面收到所有文字。

**Comment by zhangyou1010** [comment]
请问前端怎么调用/chat/chat接口，我用postman 调用http://192.168.128.98:7861/chat/knowledge_base_chat接口，没反应，难道是流式响应的原因？谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
目前，我们没有使用eventsource回包
关于请求的代码，直接curl请求，我们测试的时候做的就是curl请求

**Comment by dragoncdj** [comment]
就是说VUE无法使用流式输出这种方式吗
