### ISSUE TITLE
并发问题。api.py的接口目前在高并发处理时，是串行执行web请求。请问是什么问题呢？fastapi框架不是异步框架吗？

### ISSUE THREAD

**Issue by wgq910668** [chatchat-space/Langchain-Chatchat#2238]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21257140/130d5de8-2eb3-4ee6-9f52-0817bf3d88eb)

从图片可以看到web请求走到knowledge_base_chat的方法时，是走的先进先出的队列处理请求。那这个就没有并发处理，而且采用先进先出的同步队列一个一个处理请求

**Comment by zRzRzRzRzRzRzR** [comment]
接口肯定是并发的，但是模型跟不上啊

**Comment by liunux4odoo** [comment]
开发版已经进行了修正，方便的话请拉取最新dev分支测试一下。
