### ISSUE TITLE
[BUG] 知识库pdf解析添加向量库时耗时

### ISSUE THREAD

**Issue by walkwolf** [chatchat-space/Langchain-Chatchat#2242]
**问题描述 / Problem Description**
上传pdf文件，添加到向量库耗时太长，主要在 `RapidOCRPDFLoader context page `位置

文件大小大约6M，20页，上传没问题
RapidOCRPDFLoader解析 单个 pdf的时间太长，CPU满载，使用的是服务器CPU，解析完大约需要5分钟，能否优化？
不确定是否是的OCR识别的问题，本地测试PyPDF2 读取文件2秒。亦或者是向量库索引问题？

**我注意到在`Langchain-Chatchat/knowledge_base/xx知识库/` 下面有两个目录
content和 vector_store，content就是上传pdf放置的位置，vector_store里面有m3e-base，里面有index.pkl index.faiss，是否有可能本地创建pdf  基于m3e-base faiss 的 向量库，然后上传到知识库？**

**复现问题的步骤 / Steps to Reproduce**
知识库上传pdf文件

**预期的结果 / Expected Result**
1. 优化RapidOCRPDFLoader 速度
2. 本地创建pdf  基于m3e-base faiss 的向量库，可上传到知识库直接使用

**实际结果 / Actual Result**
20页PDF解析完成5分钟，10个文件并行目前来看需要大于1个小时，CPU满载，但在实际使用中并发的时间要远远高于1个小时（可能2-4个小时？）
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12028532/c6bca19b-c244-41c8-ae01-14be6f341b8b)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：CodeWithGPU v112023-11-10 20:36:23
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 ： faiss
- 操作系统及版本 : Ubuntu 20.04.4
- Python 版本 : 3.10.9
- 其他相关环境信息 : AutoDL v11

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
OCR识别确实很慢，建议换成GPU，CPU是非常慢的，我们的主要方向也是GPU

**Comment by Bo-LiangD** [comment]
> OCR识别确实很慢，建议换成GPU，CPU是非常慢的，我们的主要方向也是GPU

大佬 怎么确定 上传PDF 是用CPU 还是GPU 如何进行修改呢

**Comment by w62651515** [comment]
> > OCR识别确实很慢，建议换成GPU，CPU是非常慢的，我们的主要方向也是GPU
> 
> 大佬 怎么确定 上传PDF 是用CPU 还是GPU 如何进行修改呢
<img width="1184" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/5866141/6c9b5566-9a46-4216-a4eb-c15d72db3f9b">
安装这个包
#

**Comment by Bo-LiangD** [comment]
> > > OCR识别确实很慢，建议换成GPU，CPU是非常慢的，我们的主要方向也是GPU
> > 
> > 
> > 大佬 怎么确定 上传PDF 是用CPU 还是GPU 如何进行修改呢
> 
> <img alt="图像" width="1184" src="https://private-user-images.githubusercontent.com/5866141/309980084-6c9b5566-9a46-4216-a4eb-c15d72db3f9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjUyMjYsIm5iZiI6MTcxMDIyNDkyNiwicGF0aCI6Ii81ODY2MTQxLzMwOTk4MDA4NC02YzliNTU2Ni05YTQ2LTQyMTYtYTRlYi1jMTVkNzJkYjNmOWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDYyODQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJiNDljZGE2YTkwMTU1MTkyNmY0MTZmMzZiZGJmNDY3NDY1ZDI3Y2I0Nzk3MDUzYjZhNDY1YzdjOWE4YmU2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jQ4sXtguzRXUN_S7FUh6oces8HGHzmYT_JtB7Mdl0mA">安装这个包 #

大佬 我安装了这个
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/576b6d1c-1afd-46de-b3a4-d6c6a9656581)
但走的是CPU 我跟了下代码 提示 `  E0312 10:30:25.928704 24702 analysis_config.cc:125] Please use PaddlePaddle with GPU version  `   你有这些嘛，我安装了对应的 CUDA12.0 但是 这个版本 跟程序（0.2.10）不兼容跑不起来 你有遇到过这个问题嘛

**Comment by guodastanson** [comment]
@w62651515
大佬，我ocr现在用了paddle的gpu加速，能看到有一个GPU占用是起来了，而且cpu从48核心基本跑漫降到3到4个核心。但是想问下为什么另外一个GPU的compute一直是0
![微信图片_20240313175151](https://github.com/chatchat-space/Langchain-Chatchat/assets/26060938/fd4f93ec-b54f-4bf5-92ba-3031a8cb6171)

**Comment by guodastanson** [comment]
执行paddle的print(paddle.utils.run_check())，我输入python3进入环境然后复制代码跑，它会正常执行两个gpu，告诉我success。
但是我把print(paddle.utils.run_check())放到py文件再直接python3 xx.py执行同样的代码，它就告诉我meets problem with 2gpus，也是蛮奇怪的。
