### ISSUE TITLE
采用文档中加载peft的方式加载chatglm3微调模型权重报错

### ISSUE THREAD

**Issue by ghx2757** [chatchat-space/Langchain-Chatchat#2245]
**问题描述 / Problem Description**
采用文档中加载peft的方式加载chatglm3微调模型权重 运行时出现以下错误
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/141898896/23e7e7ce-a378-4373-961a-547ae22a7328)

**复现问题的步骤 / Steps to Reproduce**
 执行：set PEFT_SHARE_BASE_WEIGHTS=true && python startup.py -a

**环境信息 / Environment Information**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/141898896/3f995452-0176-45fe-b111-51f66efac018)

**Comment by ghx2757** [comment]
按照其他issue方案，删掉不必要的参数，正常启动

**Comment by HJYIS** [comment]
> 按照其他issue方案，删掉不必要的参数，正常启动

我想请问一下，你是用的chatglm3-6b微调后的模型吗？

**Comment by HJYIS** [comment]
> 按照其他issue方案，删掉不必要的参数，正常启动

步骤什么的都和wiki里面的一致吗？

**Comment by zaixiaxiaowu** [comment]
> 按照其他issue方案，删掉不必要的参数，正常启动

请问一下，是哪个issue吗，哪些参数是不必要的
