### ISSUE TITLE
postman无法正常调用/chat/knowledge_base_chat接口

### ISSUE THREAD

**Issue by zhangyou1010** [chatchat-space/Langchain-Chatchat#2248]
**问题描述 / Problem Description**
postman无法正常调用/chat/knowledge_base_chat接口

**复现问题的步骤 / Steps to Reproduce**
1. postman中调用http://192.168.128.98:7861/chat/knowledge_base_chat
2. header参数如下：
Content-Type  application/json
accept  application/json
4. 请求体参数如下
```
{
  "query": "你好",
  "knowledge_base_name": "samples",
  "top_k": 5,
  "score_threshold": 1,
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": false,
  "local_doc_url": false
}
```
**预期的结果 / Expected Result**
能正常看到响应.

**实际结果 / Actual Result**
1. postman请求接口，没有响应，也没有报错.
2. 在命令行下执行以下请求，有正常响应数据：
```
curl -X 'POST' \
  'http://localhost:7861/chat/knowledge_base_chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "你好",
  "knowledge_base_name": "samples",
  "top_k": 5,
  "score_threshold": 1,
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": false,
  "local_doc_url": false
}'
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by danyow-cheung** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/76671016/8d202b8a-0be1-406b-b582-9f653c126d60)

供参考
> 那应该如何调用呢？
