### ISSUE TITLE
[BUG]requirements.txt中duckduckgo-search依赖版本不对

### ISSUE THREAD

**Issue by maochunguang** [chatchat-space/Langchain-Chatchat#2250]
duckduckgo-search版本应该是>=3.9.3，写成了duckduckgo-search>=4.9.3。错误太低级了。

**Comment by hechushitaoyuan** [comment]
是的呢
ERROR: Ignored the following versions that require a different python version: 1.2.4 Requires-Python >=3.6,<=3.10; 1.2.5 Requires-Python >=3.6,<=3.10; 1.2.6 Requires-Python >=3.6,<=3.10; 1.2.7 Requires-Python >=3.6,<=3.10; 1.2.8 Requires-Python >=3.6,<=3.10
ERROR: Could not find a version that satisfies the requirement duckduckgo-search>=4.9.3 (from versions: 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.9.5, 1.0, 1.1, 1.2, 1.3, 1.3.5, 1.4, 1.5, 1.5.1, 1.5.2, 1.6, 1.6.2, 1.7.1, 1.8, 1.8.1, 1.8.2, 2.0.2, 2.1.3, 2.2.0, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.5.0, 2.6.0, 2.6.1, 2.7.0, 2.8.0, 2.8.1, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.9.0, 2.9.1, 2.9.2, 2.9.3, 2.9.4, 2.9.5, 3.0.2, 3.1.1, 3.2.0, 3.3.0, 3.4.1, 3.5.0, 3.6.0, 3.7.0, 3.7.1, 3.8.0, 3.8.1, 3.8.2, 3.8.3, 3.8.4, 3.8.5, 3.8.6, 3.9.3, 3.9.4, 3.9.5, 3.9.6, 3.9.8, 3.9.9)
ERROR: No matching distribution found for duckduckgo-search>=4.9.3
