### ISSUE TITLE
web页面并发的时候就会报错。高并发时还会有一个干脆不回答了。如何解决？

### ISSUE THREAD

**Issue by aoaokua** [chatchat-space/Langchain-Chatchat#2258]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37790337/ceec917a-174d-4856-b286-11df61c8b12f)

**Comment by XingchenMengxiang** [comment]
差不多一样的问题，跑一段时间就会卡死，没有任何响应

**Comment by XingchenMengxiang** [comment]
> 卡死是本地模型还是openai卡死

请问openai卡死，应该怎么处理呢 。

**Comment by aoaokua** [comment]
本地卡死的

**Comment by aoaokua** [comment]
咋回复大佬

**Comment by aoaokua** [comment]
> 卡死是本地模型还是openai卡死

本地模型卡死了

**Comment by aoaokua** [comment]
> > 卡死是本地模型还是openai卡死
> 
> 请问openai卡死，应该怎么处理呢 。

本地模型卡死了
