### ISSUE TITLE
webui无法启动是为什么？但是Chatchat API Server启动正常

### ISSUE THREAD

**Issue by kkkzhonghaiwei** [chatchat-space/Langchain-Chatchat#2269]
尝试更改了端口，也还是不行

**Comment by 1anglesmith1** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/134664658/0db25813-5f18-4f73-b11c-c609157f60fc)
我是正常启动项目后webui界面打不开，api的却可以

**Comment by qianma819** [comment]
> 更到0.2.8确保配置文件正确这个bug已经修了

更新到了0.2.8，配置文件只修改了ip，0.0.0.0=>10.244.4.81.webui还是打不开哎，端口没开

**Comment by liyiyiya** [comment]
> ![image](https://private-user-images.githubusercontent.com/134664658/287658600-0db25813-5f18-4f73-b11c-c609157f60fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NTc0MTksIm5iZiI6MTcxMzg1NzExOSwicGF0aCI6Ii8xMzQ2NjQ2NTgvMjg3NjU4NjAwLTBkYjI1ODEzLTVmMTgtNGY3My1iMTFjLWM2MDkxNTdmNjBmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyM1QwNzI1MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjQ0MTQ2NjliNzRkYmIyYjNhMzIyYzBkMWNlOGMzY2I4NjRmOGE4NTQwZWY3MjQ3ZmQ0NzgxY2I5M2FjYTNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KPS-0hZOC7pgnO06SMA-BZbFZF7qrS7SmJUcSfUl0xE) 我是正常启动项目后webui界面打不开，api的却可以

兄弟我也这样，你是怎么解决的

> 更到0.2.8确保配置文件正确这个bug已经修了

**Comment by liyiyiya** [comment]
> 0.2.

兄弟 你最后是怎么解决的呀

**Comment by ArronAI007** [comment]
我也出现了这种情况，我是因为内外网端口映射错误导致的，API可以访问，说明内网端口是正常的；WEBUI不能访问，说明外网是有问题的。
