### ISSUE TITLE
调用知识库问答，第一次返回的是知识库里的内容，之后的回答都是模型回答的，

### ISSUE THREAD

**Issue by wangziyii** [chatchat-space/Langchain-Chatchat#2273]
**问题描述 / Problem Description**
调用知识库问答，第一次返回的是知识库里的内容，之后的回答都是模型回答的，

**环境信息 / Environment Information**
操作系统：macOS-14.0-arm64-arm-64bit.
python版本：3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.33
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['xinghuo-api'] @ mps

**Comment by zRzRzRzRzRzRzR** [comment]
检查是否搜到内容？
