### ISSUE TITLE
[FEATURE] 希望能出一个简洁版本，默认直接连接在线模型

### ISSUE THREAD

**Issue by hponiang** [chatchat-space/Langchain-Chatchat#2275]
**功能描述 / Feature Description**
希望能出一个简洁版本，默认直接连接在线模型，这样就可以在普通的机器上调试 chatchat，便于用户学习与了解产品

**Comment by zRzRzRzRzRzRzR** [comment]
lite版本

**Comment by hponiang** [comment]
麻烦问下怎么获取这个 lite 版本
