### ISSUE TITLE
能否升级知识库文档上传的方式，目前的上传的方式跑不满GPU，多文件的时候很慢

### ISSUE THREAD

**Issue by 948726484** [chatchat-space/Langchain-Chatchat#2276]
十万文本文件上传知识库需要好几天，但把文本合为一个文件上传只需要几个小时

**Comment by zRzRzRzRzRzRzR** [comment]
大文件不要用webui，直接从后台进去content目录命令行向量化

**Comment by 948726484** [comment]
`
    def files2vs2(kb_files: List[KnowledgeFile],
                  llm_model: str = LLM_MODELS[0],
                  ):
        splitter_name = kb_files[0].text_splitter_name
        text_splitter_module = importlib.import_module('text_splitter')
        TextSplitter = getattr(text_splitter_module, splitter_name)
        if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "":
            config = get_model_worker_config(llm_model)
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"] = \
                config.get("model_path")
        tokenizer = AutoTokenizer.from_pretrained(
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
            trust_remote_code=True)
        text_splitter = TextSplitter.from_huggingface_tokenizer(
            tokenizer=tokenizer,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        )
        docs = []
        i =0
        for kb_file in kb_files:
            try:
                loader = get_loader(kb_file.document_loader_name, kb_file.filepath)

                kb_file.splited_docs = loader.load_and_split(text_splitter=text_splitter,)
                #
                # for doc in kb_file.splited_docs: #使用相对路径
                #     source = doc.metadata.get("source", "")
                #     rel_path = Path(source).relative_to(kb.doc_path)
                #     doc.metadata["source"] = str(rel_path.as_posix().strip("/"))

                print(kb_file.filename + f"{i} 分割成功，分割个数：{len(kb_file.splited_docs)} 示例：{kb_file.splited_docs[0]}")
                i+=1
                docs.extend(kb_file.splited_docs)
                # kb.delete_doc(kb_file)
            except:
                print(kb_file.filename + "   失败")
                pass

        print(f"开始向量化，总共的文本分割数量：{len(docs)}")
        data = kb._docs_to_embeddings(docs)
        with kb.load_vector_store().acquire() as vs:
            ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
                                    metadatas=data["metadatas"])
        all_infos = [{"id": id, "metadata": doc.metadata} for id, doc in zip(ids, docs)]
        print(f"{len(all_infos)}")

        all_meta = {doc.metadata["source"]: [] for doc in docs}
        for info in all_infos:
            all_meta[info["metadata"]["source"]].append(info)
        i=0
        for key in all_meta.keys():
            infos = all_meta[key]
            if len(infos) > 0:
                kb_file=KnowledgeFile(filename=key, knowledge_base_name=kb.kb_name)
                status = add_file_to_db(kb_file,
                                        custom_docs=False,
                                        docs_count=len(infos),
                                        doc_infos=infos)
                print(f"文件{i}已添加知识库：{infos[0]['metadata']['source']}")
                i += 1
        kb.save_vector_store()
        print("完成")

`
个人像这样改了

**Comment by 948726484** [comment]
`    def files2vs2(kb_files: List[KnowledgeFile],
                  llm_model: str = LLM_MODELS[0],
                  ):
        splitter_name = kb_files[0].text_splitter_name
        text_splitter_module = importlib.import_module('text_splitter')
        TextSplitter = getattr(text_splitter_module, splitter_name)
        if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "":
            config = get_model_worker_config(llm_model)
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"] = \
                config.get("model_path")
        tokenizer = AutoTokenizer.from_pretrained(
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
            trust_remote_code=True)
        text_splitter = TextSplitter.from_huggingface_tokenizer(
            tokenizer=tokenizer,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        )
        docs = []
        i =0
        for kb_file in kb_files:
            try:
                loader = get_loader(kb_file.document_loader_name, kb_file.filepath)
                kb_file.splited_docs = loader.load_and_split(text_splitter=text_splitter,)
                # for doc in kb_file.splited_docs: #使用相对路径
                #     source = doc.metadata.get("source", "")
                #     rel_path = Path(source).relative_to(kb.doc_path)
                #     doc.metadata["source"] = str(rel_path.as_posix().strip("/"))
                print(kb_file.filename + f"{i} 分割成功，分割个数：{len(kb_file.splited_docs)} 示例：{kb_file.splited_docs[0]}")
                i+=1
                docs.extend(kb_file.splited_docs)
                # kb.delete_doc(kb_file)
            except:
                print(kb_file.filename + "   失败")
                pass

        print(f"开始向量化，总共的文本分割数量：{len(docs)}")
        data = kb._docs_to_embeddings(docs)
        with kb.load_vector_store().acquire() as vs:
            ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
                                    metadatas=data["metadatas"])
        all_infos = [{"id": id, "metadata": doc.metadata} for id, doc in zip(ids, docs)]
        print(f"{len(all_infos)}")

        all_meta = {doc.metadata["source"]: [] for doc in docs}
        for info in all_infos:
            all_meta[info["metadata"]["source"]].append(info)
        i=0
        for key in all_meta.keys():
            infos = all_meta[key]
            if len(infos) > 0:
                kb_file=KnowledgeFile(filename=key, knowledge_base_name=kb.kb_name)
                status = add_file_to_db(kb_file,
                                        custom_docs=False,
                                        docs_count=len(infos),
                                        doc_infos=infos)
                print(f"文件{i}已添加知识库：{infos[0]['metadata']['source']}")
                i += 1
        kb.save_vector_store()
        print("完成")
`

**Comment by 948726484** [comment]
`  def files2vs2(kb_files: List[KnowledgeFile],
                  llm_model: str = LLM_MODELS[0],   ):
        splitter_name = kb_files[0].text_splitter_name
        text_splitter_module = importlib.import_module('text_splitter')
        TextSplitter = getattr(text_splitter_module, splitter_name)
        if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "":
            config = get_model_worker_config(llm_model)
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"] = \
                config.get("model_path")
        tokenizer = AutoTokenizer.from_pretrained(
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
            trust_remote_code=True)
        text_splitter = TextSplitter.from_huggingface_tokenizer(
            tokenizer=tokenizer,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        )
        docs = []
        i =0
        for kb_file in kb_files:
            try:
                loader = get_loader(kb_file.document_loader_name, kb_file.filepath)
                kb_file.splited_docs = loader.load_and_split(text_splitter=text_splitter,)
                # for doc in kb_file.splited_docs: #使用相对路径
                #     source = doc.metadata.get("source", "")
                #     rel_path = Path(source).relative_to(kb.doc_path)
                #     doc.metadata["source"] = str(rel_path.as_posix().strip("/"))
                print(kb_file.filename + f"{i} 分割成功，分割个数：{len(kb_file.splited_docs)} 示例：{kb_file.splited_docs[0]}")
                i+=1
                docs.extend(kb_file.splited_docs)
                # kb.delete_doc(kb_file)
            except:
                print(kb_file.filename + "   失败")
                pass
        print(f"开始向量化，总共的文本分割数量：{len(docs)}")
        data = kb._docs_to_embeddings(docs)
        with kb.load_vector_store().acquire() as vs:
            ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
                                    metadatas=data["metadatas"])
        all_infos = [{"id": id, "metadata": doc.metadata} for id, doc in zip(ids, docs)]
        print(f"{len(all_infos)}")
        all_meta = {doc.metadata["source"]: [] for doc in docs}
        for info in all_infos:
            all_meta[info["metadata"]["source"]].append(info)
        i=0
        for key in all_meta.keys():
            infos = all_meta[key]
            if len(infos) > 0:
                kb_file=KnowledgeFile(filename=key, knowledge_base_name=kb.kb_name)
                status = add_file_to_db(kb_file,
                                        custom_docs=False,
                                        docs_count=len(infos),
                                        doc_infos=infos)
                print(f"文件{i}已添加知识库：{infos[0]['metadata']['source']}")
                i += 1
        kb.save_vector_store()
        print("完成")

`

**Comment by 948726484** [comment]
` def files2vs2(kb_files: List[KnowledgeFile],llm_model: str = LLM_MODELS[0],   ):
        
        splitter_name = kb_files[0].text_splitter_name
        text_splitter_module = importlib.import_module('text_splitter')
        TextSplitter = getattr(text_splitter_module, splitter_name)
        if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "":
            config = get_model_worker_config(llm_model)
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"] = \
                config.get("model_path")
        tokenizer = AutoTokenizer.from_pretrained(
            text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
            trust_remote_code=True)
        text_splitter = TextSplitter.from_huggingface_tokenizer(
            tokenizer=tokenizer,
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap
        )
        docs = []
        i =0
        for kb_file in kb_files:
            try:
                loader = get_loader(kb_file.document_loader_name, kb_file.filepath)
                kb_file.splited_docs = loader.load_and_split(text_splitter=text_splitter,)
                # for doc in kb_file.splited_docs: #使用相对路径
                #     source = doc.metadata.get("source", "")
                #     rel_path = Path(source).relative_to(kb.doc_path)
                #     doc.metadata["source"] = str(rel_path.as_posix().strip("/"))
                print(kb_file.filename + f"{i} 分割成功，分割个数：{len(kb_file.splited_docs)} 示例：{kb_file.splited_docs[0]}")
                i+=1
                docs.extend(kb_file.splited_docs)
                # kb.delete_doc(kb_file)
            except:
                print(kb_file.filename + "   失败")
                pass
        print(f"开始向量化，总共的文本分割数量：{len(docs)}")
        data = kb._docs_to_embeddings(docs)
        with kb.load_vector_store().acquire() as vs:
            ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
                                    metadatas=data["metadatas"])
        all_infos = [{"id": id, "metadata": doc.metadata} for id, doc in zip(ids, docs)]
        print(f"{len(all_infos)}")
        all_meta = {doc.metadata["source"]: [] for doc in docs}
        for info in all_infos:
            all_meta[info["metadata"]["source"]].append(info)
        i=0
        for key in all_meta.keys():
            infos = all_meta[key]
            if len(infos) > 0:
                kb_file=KnowledgeFile(filename=key, knowledge_base_name=kb.kb_name)
                status = add_file_to_db(kb_file,
                                        custom_docs=False,
                                        docs_count=len(infos),
                                        doc_infos=infos)
                print(f"文件{i}已添加知识库：{infos[0]['metadata']['source']}")
                i += 1
        kb.save_vector_store()
        print("完成")
`

**Comment by zRzRzRzRzRzRzR** [comment]
# mark

**Comment by 278038551** [comment]
> 个人像这样改了，版本0.27 ` def files2vs2(kb_files: List[KnowledgeFile],llm_model: str = LLM_MODELS[0], ):
> 
> ```
>     splitter_name = kb_files[0].text_splitter_name
>     text_splitter_module = importlib.import_module('text_splitter')
>     TextSplitter = getattr(text_splitter_module, splitter_name)
>     if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "":
>         config = get_model_worker_config(llm_model)
>         text_splitter_dict[splitter_name]["tokenizer_name_or_path"] = \
>             config.get("model_path")
>     tokenizer = AutoTokenizer.from_pretrained(
>         text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
>         trust_remote_code=True)
>     text_splitter = TextSplitter.from_huggingface_tokenizer(
>         tokenizer=tokenizer,
>         chunk_size=chunk_size,
>         chunk_overlap=chunk_overlap
>     )
>     docs = []
>     i =0
>     for kb_file in kb_files:
>         try:
>             loader = get_loader(kb_file.document_loader_name, kb_file.filepath)
>             kb_file.splited_docs = loader.load_and_split(text_splitter=text_splitter,)
>             # for doc in kb_file.splited_docs: #使用相对路径
>             #     source = doc.metadata.get("source", "")
>             #     rel_path = Path(source).relative_to(kb.doc_path)
>             #     doc.metadata["source"] = str(rel_path.as_posix().strip("/"))
>             print(kb_file.filename + f"{i} 分割成功，分割个数：{len(kb_file.splited_docs)} 示例：{kb_file.splited_docs[0]}")
>             i+=1
>             docs.extend(kb_file.splited_docs)
>             # kb.delete_doc(kb_file)
>         except:
>             print(kb_file.filename + "   失败")
>             pass
>     print(f"开始向量化，总共的文本分割数量：{len(docs)}")
>     data = kb._docs_to_embeddings(docs)
>     with kb.load_vector_store().acquire() as vs:
>         ids = vs.add_embeddings(text_embeddings=zip(data["texts"], data["embeddings"]),
>                                 metadatas=data["metadatas"])
>     all_infos = [{"id": id, "metadata": doc.metadata} for id, doc in zip(ids, docs)]
>     print(f"{len(all_infos)}")
>     all_meta = {doc.metadata["source"]: [] for doc in docs}
>     for info in all_infos:
>         all_meta[info["metadata"]["source"]].append(info)
>     i=0
>     for key in all_meta.keys():
>         infos = all_meta[key]
>         if len(infos) > 0:
>             kb_file=KnowledgeFile(filename=key, knowledge_base_name=kb.kb_name)
>             status = add_file_to_db(kb_file,
>                                     custom_docs=False,
>                                     docs_count=len(infos),
>                                     doc_infos=infos)
>             print(f"文件{i}已添加知识库：{infos[0]['metadata']['source']}")
>             i += 1
>     kb.save_vector_store()
>     print("完成")
> ```
> 
> `
请问通过上面的方式，能提升向量化的效率吗？

**Comment by 948726484** [comment]
@278038551 其实我基本没有对原项目的向量化方式进行改动，只不过原项目在vs.add_embeddings时，只针对单个文档的切分文本进行向量化会出现GPU跑不满的情况，我的改动是将全部切分文本一起进行向量化
