### ISSUE TITLE
Fatal error in launcher: Unable to create process using 

### ISSUE THREAD

**Issue by shawnzhanglyp** [chatchat-space/Langchain-Chatchat#2277]
![Uploading error.PNG…]()

**Comment by shawnzhanglyp** [comment]
Fatal error in launcher: Unable to create process using '"D:\anaconda\envs\chatchat\python.exe"  "D:\anaconda3\envs\chatchat\Scripts\streamlit.exe" run webui.py --server.address 127.0.0.1 --server.port 8501 --theme.base light --theme.p
rimaryColor #165dff --theme.secondaryBackgroundColor #f5f5f5 --theme.textColor #000000': ???????????

**Comment by shawnzhanglyp** [comment]
已解决，python虚拟环境路径的问题~~

**Comment by Feihei** [comment]
would you pls share the way you solve this problem? I met with the same error, thanks

**Comment by shawnzhanglyp** [comment]
> would you pls share the way you solve this problem? I met with the same error, thanks
看报错信息，'"D:\anaconda\envs\chatchat\python.exe" "D:\anaconda3\envs\chatchat\Scripts\streamlit.exe" 
可以知道问题出在anaconda3，配置系统环境变量，将anaconda3变为anaconda
