### ISSUE TITLE
请求智谱 API 时发生错误：{'msg': 'JSON parse error: Unexpected end-of-input in VALUE_STRING; nested exception is com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in VALUE_STRING\n at [Source: (PushbackInputStream); line: 1, column: 277]', 'code': 500}

### ISSUE THREAD

**Issue by chenwenfeng** [chatchat-space/Langchain-Chatchat#2279]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
运行 lite 版本 使用 zhipuai的在线 embeding，知识库导入文件向量化时报这个错

**预期的结果 / Expected Result**

**实际结果 / Actual Result**

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8/6547005073eea0502fabb9d483fea6867a7f130e

- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： openai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：zhipuai
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: macos
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by chenwenfeng** [comment]
自己改用 api 方式请求智谱的接口能过  不知道为啥项目里 sdk 的方式报这个错

**Comment by zRzRzRzRzRzRzR** [comment]
项目也是用zhipu包请求的

**Comment by dark-lake** [comment]
我的也是报这错 0.2.8版本出现的,0.2.7的时候是好的

**Comment by suoqiLiu** [comment]
在```server/knowledge_base/utils.py```下有针对json.dumps的强制转化，导致zhipu接口报错，不用json相关loader的话可以先注释掉，代码如下：
```
# patch json.dumps to disable ensure_ascii
def _new_json_dumps(obj, **kwargs):
    kwargs["ensure_ascii"] = False
    return _origin_json_dumps(obj, **kwargs)

if json.dumps is not _new_json_dumps:
    _origin_json_dumps = json.dumps
    json.dumps = _new_json_dumps
```
