### ISSUE TITLE
在web页面点击上传文件出现AxiosError: Network Error

### ISSUE THREAD

**Issue by mayidu** [chatchat-space/Langchain-Chatchat#2287]
您好，请问一下，我现在按步骤部署了整个项目，然后我再页面选择文件对话，点击上传文件，出现AxiosError: Network Error
包括在知识库管理点击上传也同样是这样的问题，问答的话可以正常，目前就是上传文件出现问题，请帮忙看一下，感谢~

**Comment by zRzRzRzRzRzRzR** [comment]
方便给个详细报错复现吗？

**Comment by chenwenfeng** [comment]
我也遇到过 刷新下页面又正常了

**Comment by mayidu** [comment]
你好，后台没有相关错误的日志输出呢，具体的前端我给您截图看一下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29938271/bdaf5fe7-7cb6-4aa0-8553-1c56bb1b10d4)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29938271/70270353-05f2-44e7-9413-343e30b4a8f7)

在文件对话和知识库管理都会出现这个问题，我看这个调用的是files_upload接口，请问一下这个的具体端口号是多少呢

**Comment by zRzRzRzRzRzRzR** [comment]
在7860端口可以看到所有的接口

**Comment by mayidu** [comment]
你好，我再7861端口下看到上传知识库调用的是/knowledge_base/upload_docs，但是在前端页面这里直接点击上传的话，调用的是ip:8501/_stcore/upload_file/，请问一下，这里本来就是不一致的吗，还是需要修改哪里，我现在从7861那里上传可以成功，但是从前端页面直接上传的话就一直出现上面所说的错误。感谢~

**Comment by cca12138** [comment]
我现在也出现这种问题了，现在有解决方法吗

**Comment by mayidu** [comment]
这个我最好排查是跨域的问题，你在本地部署就不会

发自我的iPhone
