### ISSUE TITLE
 bge-large-zh-v1.5无法建立知识库

### ISSUE THREAD

**Issue by banbsyip** [chatchat-space/Langchain-Chatchat#2289]
![Uploading image.png…]()
使用m3e模型可以正常建立数据库，但是使用 bge-large-zh-v1.5无法建立知识库

**Comment by banbsyip** [comment]
<img width="1159" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/18277076/c8b8abbf-fb1c-43cc-bf7e-96c946526949">

**Comment by banbsyip** [comment]
torch                         2.1.0+cu118
torchaudio                    2.1.0
torchvision                   0.16.0
tornado                       6.3.3

**Comment by zRzRzRzRzRzRzR** [comment]
确定模型文件是huggingface下的吗？有可能模型没全
