### ISSUE TITLE
[BUG] 关于使用 openai 在线 embedding 模型进行量化

### ISSUE THREAD

**Issue by chenwenfeng** [chatchat-space/Langchain-Chatchat#2292]
**问题描述 / Problem Description**
1.修改model_config.py中 EMBEDDING_MODEL = "text-embedding-ada-002"；并将embed_model里的text-embedding-ada-002配置为 openai 的 key

2.lite 模式启动（python startup.py -a --lite）

**实际结果 / Actual Result**
打开管理后台，选择新建知识库，页面报错
<img width="854" alt="截屏2023-12-06 17 10 25" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/863159/71716d68-5427-41c7-bd55-6d07723ddb1c">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8(6547005073eea0502fabb9d483fea6867a7f130e)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： openai的gpt-3.5-turbo
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：openai 的text-embedding-ada-002
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: macos
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
也尝试使用 zhipuai 的在线 embeding 但也没成功，调用 api 时报错
<img width="1733" alt="截屏2023-12-06 17 15 33" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/863159/18e77c5e-dfa5-41f2-9523-3e145b348a6a">

**Comment by zRzRzRzRzRzRzR** [comment]
dev中已经修复
