### ISSUE TITLE
上传英文文件到知识库中,索引出来的内容不是正确的,且字数很少

### ISSUE THREAD

**Issue by WWeellkkiinn** [chatchat-space/Langchain-Chatchat#2295]
如题目所示,上传英文的txt文件到知识库中,无论使用中文还是英文提问,知识库搜索的内容都不太相似,而且即使设置了1000个词作为分割,但是索引出来每一段还是只有200~300字,希望大佬们指点

**Comment by WWeellkkiinn** [comment]
全默认,除了修改了上传知识库的时候的1000,且仅在txt文件中出现该问题,将文本复制到word后问题消失

**Comment by ShinyWey** [comment]
> 除提及的修改所有设置全默认,除了修改了上传知识库的时候的1000,且仅在txt文件中出现该问题,将文本复制到word后问题消失

默认的应该是中文的embedding模型吧, 你得换成英文的模型, 而且1000作为分割数, 默认的应该是bge? 不确定, 如果是bge, 应该超过了最大范围了, 设置为512试试
