### ISSUE TITLE
vllm+chatglm3-6b   无答案回复

### ISSUE THREAD

**Issue by shujun1992** [chatchat-space/Langchain-Chatchat#2298]
vllm: 0.2.3
model: chatglm3-6b 
gpu: 2块T4

日志如下:
INFO 12-07 11:31:36 async_llm_engine.py:379] Received request a1420f6a35604e2aa532ef3469bb75a9: prompt: '<|user|>\n 我们来玩成语接龙，我先来，生龙活虎<|assistant|>\n 虎头虎脑<|user|>\n 恼羞成怒<|assistant|>', sampling params: SamplingParams(n=1, best_of=1, presence_pena
lty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['', '<|user|>', '<|observation|>'], stop_token_ids=[], ignore_eos=False, max_tokens=8140, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: None.2023-12-07 11:31:36 | DEBUG | httpcore.http11 | receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'date', b'Thu, 07 Dec 2023 03:31:35 GMT'), (b'server', b'uvicorn'), (b'transfer-encoding', b'chunked')])
2023-12-07 11:31:36 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2023-12-07 11:31:36 | DEBUG | httpcore.http11 | receive_response_body.started request=<Request [b'POST']>
INFO 12-07 11:31:36 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
INFO 12-07 11:31:36 async_llm_engine.py:111] Finished request a1420f6a35604e2aa532ef3469bb75a9.
INFO 12-07 11:31:36 async_llm_engine.py:134] Aborted request a1420f6a35604e2aa532ef3469bb75a9.
2023-12-07 11:31:36 | DEBUG | httpcore.http11 | receive_response_body.complete
2023-12-07 11:31:36 | DEBUG | httpcore.http11 | response_closed.started
2023-12-07 11:31:36 | DEBUG | httpcore.http11 | response_closed.complete
2023-12-07 11:31:36 | DEBUG | httpcore.connection | close.started
2023-12-07 11:31:36 | DEBUG | httpcore.connection | close.complete

日志到这里就结束了，没有后续答案返回

**Comment by shujun1992** [comment]
[chain/start] [1:chain:LLMChain] Entering Chain run with input:
{
  "input": "恼羞成怒"
}
[llm/start] [1:chain:LLMChain > 2:llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "user: 我们来玩成语接龙，我先来，生龙活虎\nassistant: 虎头虎脑\nuser: 恼羞成怒"
  ]
}
[llm/end] [1:chain:LLMChain > 2:llm:ChatOpenAI] [302ms] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "",
        "generation_info": {
          "finish_reason": "stop"
        },
        "type": "ChatGeneration",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain_core",
            "messages",
            "ai",
            "AIMessage"
          ],
          "kwargs": {
            "content": "",
            "additional_kwargs": {},
            "example": false
          }
        }
      }
    ]
  ],
  "llm_output": null,
  "run": null
}
[chain/end] [1:chain:LLMChain] [306ms] Exiting Chain run with output:
{
  "text": ""
}



我看了下后续日志，这个是代表返回就是空吧？  触碰stop了？

**Comment by shujun1992** [comment]
我不用vllm，双卡可以正常回复

**Comment by shujun1992** [comment]
我又试了下单卡vllm+chatglm3-6b，也不行，跟上面日志一样的

**Comment by hzg0601** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/22924096/150098cf-7440-4ba3-8c4e-20abf0c89822)

**Comment by Victoriaheiheihei** [comment]
你好，请问找到解决的办法了吗？
知道为什么会有以下提示吗？
INFO 12-07 11:31:36 llm_engine.py:649] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.0%, CPU KV cache usage: 0.0%
