### ISSUE TITLE
[BUG] 知识库上传文件每次都生成 2 条记录

### ISSUE THREAD

**Issue by chenwenfeng** [chatchat-space/Langchain-Chatchat#2299]
**问题描述 / Problem Description**

知识库上传文件每次都生成 2 条记录，如图
<img width="1717" alt="截屏2023-12-07 11 53 39" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/863159/e02d2645-8ba7-4542-bd78-e3ffb3d771a2">

**Comment by liunux4odoo** [comment]
下个版本将会修复。

这是因为知识库文件的绝对路径和相对路径混用的问题：
https://github.com/chatchat-space/Langchain-Chatchat/pull/2256/commits/c32544f134e2be603225d780f3931227ba55607c
