### ISSUE TITLE
没有效果，是我的方法不对么？

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2301]
拉的最新代码，项目版本：0.2.8，都是按照wiki的配置，llm模型换成了chagglm2-6b-int4,m3e-base，想用下知识库的效果如何。步骤如下
1.新建知识库-brothertest，向量是faisss,embedding模型是m3e-base
2.上传了一个文件，nam.txt.里面就一行 ：the name of brother is brothertest
3.添加文件到向量库
4.依据源文件重建向量库
5.对话选择知识库问答，知识库是brothertest，temperature：0.1
6.对话框里提问，what is brother's name, 中文：brother的名字是什么，结果都是根据已知信息，无法回答该问题。但是知识库匹配结果显示出处【1】nam.txt,the name of brother is brothertest

这么简单的一个问答都回答不上来么？还是我的配置流程有啥问题？求大佬解惑

**Comment by zRzRzRzRzRzRzR** [comment]
换embed 和模型就是因为原来的效果太差了

第二个问题，如果已经搜到了，大概率是他认为搜到的这个信息没法回答问题，是模型的问题

**Comment by AaronFSJ** [comment]
> 换embed 和模型就是因为原来的效果太差了
> 
> 第二个问题，如果已经搜到了，大概率是他认为搜到的这个信息没法回答问题，是模型的问题

0.2.8 默认换了 bge-large-zh，感觉不如 m3e-base，我根据 wiki 预处理文件的方式去处理，包括直接使用 samples，无论是哪个 embed 查出来的效果都不是特别好，没有达到 wiki 里描述的效果。

**Comment by qianma819** [comment]
> > 换embed 和模型就是因为原来的效果太差了
> > 第二个问题，如果已经搜到了，大概率是他认为搜到的这个信息没法回答问题，是模型的问题
> 
> 0.2.8 默认换了 bge-large-zh，感觉不如 m3e-base，我根据 wiki 预处理文件的方式去处理，包括直接使用 samples，无论是哪个 embed 查出来的效果都不是特别好，没有达到 wiki 里描述的效果。

确实是，我实际测试效果感觉还是m3e-base效果好。excel基本无法使用，估计要特殊处理下。
我建了3个docx文档，文档1：
关于课桌的密码有这些：
1.	a56128
2.	abdga5
文档2
关于课桌的密码有这些：
1.	nidnagoaga
2.	ibnaidim484811
文档3
关于课桌的密码有这些：
1.	ndagaginga
2.	ibna484811
bge-large-zh就只检索出后面俩的回答，文档1的答案就是无法输出。换了m3e-base就可以。
还有那个匹配结果，我如果设置成4或者5，匹配结果总会出来莫名其妙的信息
