### ISSUE TITLE
[BUG] python init_database.py --recreate-vs 报错，好像是

### ISSUE THREAD

**Issue by hopeforus** [chatchat-space/Langchain-Chatchat#2305]
运行

AttributeError: module 'faiss._swigfaiss_avx2' has no attribute 'delete_GpuResourcesVector'

**Comment by hzg0601** [comment]
你为什么会调到GPU版的faiss？

**Comment by hopeforus** [comment]
我是GPU服务器啊

**Comment by hzg0601** [comment]
那就把faiss-cpu卸载掉，装faiss-gpu

**Comment by hopeforus** [comment]
我没有装faiss—cpu啊，我就是直接装的faiss-GPU呢，好奇怪啊

**Comment by hopeforus** [comment]
faiss 不需要做配置什么吧，按照官网的命令安装就行吧

**Comment by hzg0601** [comment]
记住要把cpu版本的删除干净，不止faiss-cpu,还有一个faiss

**Comment by hopeforus** [comment]
OK 我再试一下 多谢！

**Comment by hopeforus** [comment]
把 faiss 和faiss-cpu 都卸载 再重新安装了faiss-GPU 跑起来了，多谢兄弟啦！
