### ISSUE TITLE
Agent 功能中封装了一个OCR识别的任务，需要传入两个参数，但是使用过程中无法准确传入两个参数

### ISSUE THREAD

**Issue by diana1919zhong** [chatchat-space/Langchain-Chatchat#2308]
版本：0.2.8
Agent的tools中增加了一个OCR识别的任务，需要输入两个参数：
class OCRInput(BaseModel):
    query: str = Field()
    image_path: str = Field()

def ocr_text(query: str, image_path:str):
   recognized_text = get_ocr_content() # 文字识别
    model = model_container.MODEL
    llm_ocr = LLMChain(llm=model, verbose=True, prompt=OCR_PROMPT)
    ans = llm_ocr.run(question=query, image_content=recognized_text)
    print("OCR 答案：", ans)
    return ans

tools_select.py中添加内容如下：
    Tool.from_function(
        func=ocr_text,
        name="OCR识别工具",
        description="使用这个工具识别图片中的内容",
        args_schema=OCRInput,
    ),

使用时候，提问问题是：这张图片中是什么内容，路径为：D:\\a.jpg

然后报错：tils.py[line:27] - ERROR: ValidationError: Caught exception: 1 validation error for OCRInput image_path field required (type=value_error.missing)

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.8的Agent是单独传参的，只能传一个参数，未来三个版本内，Agent会升级到多参数
