### ISSUE TITLE
增加重新生成按钮

### ISSUE THREAD

**Issue by wuyiclover** [chatchat-space/Langchain-Chatchat#2309]
**功能描述 / Feature Description**
在对话中增加重新生成按钮

**解决的问题 / Problem Solved**
想生成多样性的内容，或生成内容不合适时，避免重复输入

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37546904/ac00b7d4-f194-4238-901d-f6b6036fcb96)

自己实现了一下重新生成的功能，但是发现每次生成出来的都很相似，调节了temperature也没有多大的区别。
清空内容开启新的会话，内容会和之前的会话有点区别

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37546904/9164f0ce-2fc2-4eae-8f1c-5e9817a18bc3)

**Comment by zRzRzRzRzRzRzR** [comment]
已经在计划中

**Comment by wuyiclover** [comment]
在同一个会话窗口中，输入同样的内容，每次生成的结果都很相似，调节了temperature也没有多大的区别。
得新开一个窗口输出才有一些区别。
请问是什么原因呢，测试了一下感觉是历史对话轮数的影响，
