### ISSUE TITLE
[BUG] v0.2.8 知识库上传文件会生成两份文件记录

### ISSUE THREAD

**Issue by Astlvk** [chatchat-space/Langchain-Chatchat#2310]
**问题描述 / Problem Description**
知识库上传一个文件，在文件列表内会生成两份记录，一份文件名携带了文件路径，并且未成功向量化并入库，但源文件那一列显示是√。另一份文件名正确且成功向量化并入库，但源文件那一列显示是×。具体可以看截图。
顺带，使用python init_database.py --recreate-vs初始化知识库后，samples知识库的文件列表内的文件名称也都是含有文件路径。

**复现问题的步骤 / Steps to Reproduce**
1. web界面，知识库管理上传一份文件或者使用api接口上传文件到知识库
2. 上传成功后在web界面知识库管理界面的知识库已有文件列表内会展示出这个文件的两条记录

**预期的结果 / Expected Result**
只正常展示一条记录，并且文件名不会包含文件路径。

**实际结果 / Actual Result**
实际上一份文件产生两条记录，且文件名含有路径，如图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12179680/f2a4a523-99b6-415a-a81b-c627e44f877d)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12179680/9b961eb9-9154-44d5-bb4a-6b7aa2f8e8e4)
初始化的知识库文件：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12179680/0f714f57-4a0f-4dbd-8bd9-ab941f878a39)

**环境信息 / Environment Information**
- langchain-chatchat版本：v0.2.8
- 是否使用 Docker 部署：否
- 使用的模型：openai-api
- 使用的 Embedding 模型：m3e-base
- 使用的向量库类型 ：faiss
- 操作系统及版本：win11
- Python 版本：3.11

**Comment by liunux4odoo** [comment]
这个问题将在下个版本修复，也可以拉取Dev分支再试一下。

**Comment by Justin18Chan** [comment]
根据Dev分支，如下改动本人试了有效.
server/knowledge_base/utils.py
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/35186292/17f41f90-3382-4756-99f9-e8a37cb1b10f)

**Comment by Astlvk** [comment]
@liunux4odoo 你好，想请教下，本项目如何启动可以进行热更新？方便调试代码。

**Comment by liunux4odoo** [comment]
Duplicate of #2299

**Comment by liunux4odoo** [comment]
> @liunux4odoo 你好，想请教下，本项目如何启动可以进行热更新？方便调试代码。

本项目仅支持 prompt_config 热加载，其它配置项改变必须重启服务器。
