### ISSUE TITLE
[BUG] 使用docker时无法加载GPU

### ISSUE THREAD

**Issue by yutong12** [chatchat-space/Langchain-Chatchat#2312]
**问题描述 / Problem Description**
启动docker项目时 进入发现auto没有自动检测到GPU  embedding和llm-model模型加载都是使用的CPU
强制执行后提示没有安装nvidia驱动

**复现问题的步骤 / Steps to Reproduce**
1. 使用docker run进入正在执行的容器内部
2. 执行python -> import torch  -> torch.cuda.is_available_() 
3. 返回False 证明没有成功加载GPU
2. 点击 '...' / Click '...'
4. 滚动到 '...' / Scroll to '...'
5. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.7 docker版本
- 是否使用 Docker 部署（是/否）：是 
- 操作系统及版本 
- Python 版本 / Python version: 
- 其他相关环境信息 / Other relevant environment information:

修复建议：建议从Nvidia NGC中下载自带CUDA的镜像并进行后续安装&&或者安装GPU版本torch  (torch官网版本)

**Comment by a994862495** [comment]
以下是自己编写的Dockerfile:

**Comment by a994862495** [comment]
以下是自己编写的Dockerfile:
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

RUN apt update \
    && apt install --no-install-recommends -y gcc git zip curl htop libgl1 libglib2.0-0 libpython3-dev gnupg g++ libusb-1.0-0

ADD . /usr/NuclearPower-LLM
WORKDIR /usr/NuclearPower-LLM

RUN pip install -r requirements.txt
RUN pip install -r requirements_api.txt
RUN pip install -r requirements_webui.txt

EXPOSE 8888
CMD ["python","startup.py","-a"]

**Comment by a994862495** [comment]
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

RUN apt update \
    && apt install --no-install-recommends -y gcc git zip curl htop libgl1 libglib2.0-0 libpython3-dev gnupg g++ libusb-1.0-0

ADD . /usr/Langchain-Chatchat
WORKDIR /usr/Langchain-Chatchat

RUN pip install -r requirements.txt
RUN pip install -r requirements_api.txt
RUN pip install -r requirements_webui.txt

EXPOSE 8501

CMD ["python","startup.py","-a"]

**Comment by yutong12** [comment]
对 你这样是可行的 
但是自己制作镜像就违背了 "一键启动"的初衷了哈哈
之前是本地环境老是报错 才想着改镜像的
现在没这个问题了哈

**Comment by drowninwater** [comment]
能请问下具体怎么解决吗
同样cuda版本不兼容

**Comment by a994862495** [comment]
> 能请问下具体怎么解决吗
> 同样cuda版本不兼容

错误信息提供下

**Comment by drowninwater** [comment]
问题描述 / Problem Description
docker一键部署后交互输入和输出都很慢，用log查看镜像信息发现没有使用上GPU。另外在build容器的时候也会有下面的报错。
```
UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at …/c10/cuda/CUDAFunctions.cpp:108.)
return torch._C._cuda_getDeviceCount() > 0
is_avail: False
```

复现问题的步骤 / Steps to Reproduce

使用docker run进入正在执行的容器内部
执行python -> import torch -> torch.cuda.is_available_()
返回False 证明没有成功加载GPU。
点击 '...' / Click '...'
滚动到 '...' / Scroll to '...'
问题出现 / Problem occurs
预期的结果 / Expected Result
描述应该出现的结果 / Describe the expected result.

实际结果 / Actual Result
描述实际发生的结果 / Describe the actual result.
目前已经排查出来了是cuda版本不兼容的问题。LanchainChatchat v0.2.6版本以 nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04 为基础镜像， 而与cuda12.1x相兼容的driver版本>=530.30.02.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104676193/5fe4e4aa-2ca2-4e2f-8156-6ccd35e4ecda)
而我目前用的服务器driver版本是525
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104676193/62fc46dd-8da8-467f-a19b-61b675134a13)
想请问一下如何用dockerfile定制镜像，把cuda换成11.8

**Comment by a994862495** [comment]
> 问题描述 / Problem Description docker一键部署后交互输入和输出都很慢，用log查看镜像信息发现没有使用上GPU。另外在build容器的时候也会有下面的报错。
> 
> ```
> UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 802: system not yet initialized (Triggered internally at …/c10/cuda/CUDAFunctions.cpp:108.)
> return torch._C._cuda_getDeviceCount() > 0
> is_avail: False
> ```
> 
> 复现问题的步骤 / Steps to Reproduce
> 
> 使用docker run进入正在执行的容器内部 执行python -> import torch -> torch.cuda.is_available_() 返回False 证明没有成功加载GPU。 点击 '...' / Click '...' 滚动到 '...' / Scroll to '...' 问题出现 / Problem occurs 预期的结果 / Expected Result 描述应该出现的结果 / Describe the expected result.
> 
> 实际结果 / Actual Result 描述实际发生的结果 / Describe the actual result. 目前已经排查出来了是cuda版本不兼容的问题。LanchainChatchat v0.2.6版本以 nvidia/cuda:12.1.1-cudnn8-devel-ubuntu22.04 为基础镜像， 而与cuda12.1x相兼容的driver版本>=530.30.02. ![image](https://private-user-images.githubusercontent.com/104676193/290976367-5fe4e4aa-2ca2-4e2f-8156-6ccd35e4ecda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzY2MzYsIm5iZiI6MTcwMjg3NjMzNiwicGF0aCI6Ii8xMDQ2NzYxOTMvMjkwOTc2MzY3LTVmZTRlNGFhLTJjYTItNGUyZi04MTU2LTZjY2QzNWU0ZWNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNTEyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWYzN2ZiNGMxYzIyZGI2MjkwNTE0YmY0YjhjZjM5YTg0ZGExYjFiODdiMDZmMjdjNDA4MjBmYjNkMDQ1NWY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GqcnRLvGYpQptgS5dBK-Ahy1bc75RfOJKfvI78Al2Ac) 而我目前用的服务器driver版本是525 ![image](https://private-user-images.githubusercontent.com/104676193/290976465-62fc46dd-8da8-467f-a19b-61b675134a13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI4NzY2MzYsIm5iZiI6MTcwMjg3NjMzNiwicGF0aCI6Ii8xMDQ2NzYxOTMvMjkwOTc2NDY1LTYyZmM0NmRkLThkYTgtNDY3Zi1hMTliLTYxYjY3NTEzNGExMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxOFQwNTEyMTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjM2MTRiNzVhNWZiMjlkNDdlZWNiNzYxMzQzMzY1MTgwZTIwZjlkNDJkZjg1ZDExYzg2ZDA1ZGFlY2JlZjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nAHwVelvid9CpL5moxkDJhfQgAVtoFQkXASSIP4mAgc) 想请问一下如何用dockerfile定制镜像，把cuda换成11.8

在项目中创建一个model文件夹，然后将语言模型和embeding的文件拷贝到model文件中，修改Langchain-Chatchat配置文件中语言模型的路径和embedding模型的路径，创建Dockerfile文件，文件中按下述方式写即可，保存后docker build -t LangChain-Chatchat:0.2.8 .
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

RUN apt update
&& apt install --no-install-recommends -y gcc git zip curl htop libgl1 libglib2.0-0 libpython3-dev gnupg g++ libusb-1.0-0

ADD . /usr/Langchain-Chatchat
WORKDIR /usr/Langchain-Chatchat

RUN pip install -r requirements.txt
RUN pip install -r requirements_api.txt
RUN pip install -r requirements_webui.txt

EXPOSE 8501

CMD ["python","startup.py","-a"]

或者直接docker run -d --gpus all -p 8501:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.7 直接更换0.2.5\0.2.6版本？

**Comment by drowninwater** [comment]
谢谢！！
