### ISSUE TITLE
0.2.8的文件对话问题

### ISSUE THREAD

**Issue by ShinyWey** [chatchat-space/Langchain-Chatchat#2313]
1. 使用milvus向量库, 上传文件好像没有可以选则向量库的地方, 尝试上传, 提示我pip install faiss-cpu;
2. 临时向量库中的文件保存多久, 是对话关闭就删除吗, 还是有定时删除策略.

**Comment by liunux4odoo** [comment]
文件对话使用到临时向量库，所以只支持 faiss
所有临时文件在服务器重启的时候会自动删除。
