### ISSUE TITLE
[BUG] 知识库问答时，在回答中点击文件，弹出页面无法显示或下载文件

### ISSUE THREAD

**Issue by Alen58** [chatchat-space/Langchain-Chatchat#2315]
**问题描述 / Problem Description**
使用自己构建的知识库进行知识库问答时，能够得到类似下图这样的回答，红框框出来的部分是回答的知识库文件
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/74636551/088945a9-2dc3-42ec-94f5-5fd7e5816cfc)
当我点击这个文件的时候会弹出一个页面，但是也页面上什么也不执行，也不会下载这个文件
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/74636551/cc4ac7d4-b969-48bb-8768-e95993fee12e)
右键页面进入检查，看到报错如下图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/74636551/e4ba1b26-f42d-4043-8f1a-1327d179cee2)
请问这是什么原因，如何解决呢？

**复现问题的步骤 / Steps to Reproduce**
1. 执行命令 python startup.py -a
2. 在弹出的可以对话的页面选择知识库问答问问题，得到知识库中的回答
3. 点击回答中的文件，弹出页面，但页面既不执行下载文件的操作也不会展示文件

**预期的结果 / Expected Result**
把回答中的文件下载下来

**实际结果 / Actual Result**
页面出错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型: 本地下载的ChatGLM3-6B
- 使用的 Embedding 模型：moka-ai/m3e-base模型
- 使用的向量库类型： faiss 
- 操作系统及版本 / Operating system and version: 服务器上的linux系统
- Python 版本 / Python version: 3.10.13

**Comment by xaseven** [comment]
同问，也就是说，知识库引用的源文件的URL的host是从哪里指定或配置的？

**Comment by o1064093406** [comment]
解决了吗？

**Comment by o1064093406** [comment]
![1703570559849](https://github.com/chatchat-space/Langchain-Chatchat/assets/144437418/316bc30e-e9eb-43a5-bc5c-51ba56a5572a)
直接改代码

**Comment by o1064093406** [comment]
> 同问，也就是说，知识库引用的源文件的URL的host是从哪里指定或配置的？

configs下的server_config.py里的API_SERVER

**Comment by Lj4040** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/117823125/e1cc243d-6f67-41c2-a883-e1d66ebdd761)
我的是直接拒绝，这个如何有修改，有大佬可以帮下吗
