### ISSUE TITLE
[BUG] 文件保存至本地磁盘时，前端第二次调用相关接口时保存前一次上传的文件

### ISSUE THREAD

**Issue by 1184565534** [chatchat-space/Langchain-Chatchat#2316]
目前只在项目启动后第一次上传文档时触发该bug
前端第一次调用文档上传接口时，该文档未被保存至本地磁盘中，在第二次调用该接口时，第一次上传的文档才会被正常保存。之后正常。

**Comment by zRzRzRzRzRzRzR** [comment]
mark，我们会关注这个问题
