### ISSUE TITLE
向量化后知识库无法查询,需要重启才能查询

### ISSUE THREAD

**Issue by starsliao** [chatchat-space/Langchain-Chatchat#2320]
因为我需要对QA文档根据自己的规则来做分词,然后写入向量库,我参照项目的代码写了个函数,执行后可以正常生成知识库并向量化,但是有一个问题就是必须重启Langchain-Chatchat 后,才能对这个向量库进行查询,否则查不到任何数据.
麻烦大佬帮忙看看我代码是少执行了啥函数吗?
```
def vector(knowledge_base_name,file_name,docs):
    kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
    kb_file = KnowledgeFile(filename=file_name,knowledge_base_name=knowledge_base_name)
    kb_file.splited_docs = docs
    kb.update_doc(kb_file, not_refresh_vs_cache=True)
    kb.save_vector_store()
```
`knowledge_base_name`是创建好的空知识库
`file_name`是txt文档的路径已经复制到知识库的content目录下.
`docs`是我处理好的一个包含所有`Document`的list

**Comment by zRzRzRzRzRzRzR** [comment]
确实要重启或者刷新webui页面才能做

**Comment by liunux4odoo** [comment]
这个问题应该是由于 FAISS 向量库缓存造成的。多进程同时写入一个 FAISS 向量库不是个好主意，我们需要考虑一下如何处理这种情况。

**Comment by liunux4odoo** [comment]
仔细考虑了一下，允许多进程同时访问同一个向量库有很大的不确定性，容易导致数据覆盖，还是不增加相关功能了。
作为替代，用户可以：在外部操作向量库A之前，先把 chatchat 中当前的知识库切换到B，因为默认缓存数量是1，这时候就会把A从缓存中移除；等外部操作结束后，再重新把 chatchat 的知识库切换成A。
