### ISSUE TITLE
执行python init_database.py --recreate-vs后报错

### ISSUE THREAD

**Issue by strLights** [chatchat-space/Langchain-Chatchat#2322]
**问题描述 / Problem Description**
执行python init_database.py --recreate-vs后报错，ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python init_database.py --recreate-vs' 
2. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
正常执行

**实际结果 / Actual Result**
提示缺少module

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B 
- 使用的 Embedding 模型：text2vec-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: miniconda
- Python 版本 / Python version: 3.10.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

Traceback (most recent call last):
  File "E:\code\python\an\Langchain-Chatchat\init_database.py", line 3, in <module>
    from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db,
  File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\migrate.py", line 11, in <module>
    from server.knowledge_base.kb_service.base import KBServiceFactory
  File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 29, in <module>
    from server.embeddings_api import embed_texts
  File "E:\code\python\an\Langchain-Chatchat\server\embeddings_api.py", line 3, in <module>
    from server.model_workers.base import ApiEmbeddingsParams
  File "E:\code\python\an\Langchain-Chatchat\server\model_workers\__init__.py", line 1, in <module>
    from .base import *
  File "E:\code\python\an\Langchain-Chatchat\server\model_workers\base.py", line 5, in <module>
    from fastchat.serve.base_model_worker import BaseModelWorker
ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'

**Comment by energy888666** [comment]
> **问题描述 / Problem Description** 执行python init_database.py --recreate-vs后报错，ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'
> 
> **复现问题的步骤 / Steps to Reproduce**
> 
> 1. 执行 'python init_database.py --recreate-vs'
> 2. 问题出现 / Problem occurs
> 
> **预期的结果 / Expected Result** 正常执行
> 
> **实际结果 / Actual Result** 提示缺少module
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：v0.2.8
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
> * 使用的 Embedding 模型：text2vec-base
> * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> * 操作系统及版本 / Operating system and version: miniconda
> * Python 版本 / Python version: 3.10.9
> * 其他相关环境信息 / Other relevant environment information:
> 
> **附加信息 / Additional Information**
> 
> Traceback (most recent call last): File "E:\code\python\an\Langchain-Chatchat\init_database.py", line 3, in from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db, File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\migrate.py", line 11, in from server.knowledge_base.kb_service.base import KBServiceFactory File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 29, in from server.embeddings_api import embed_texts File "E:\code\python\an\Langchain-Chatchat\server\embeddings_api.py", line 3, in from server.model_workers.base import ApiEmbeddingsParams File "E:\code\python\an\Langchain-Chatchat\server\model_workers__init__.py", line 1, in from .base import * File "E:\code\python\an\Langchain-Chatchat\server\model_workers\base.py", line 5, in from fastchat.serve.base_model_worker import BaseModelWorker ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'

我也是 你的解决了吗？

**Comment by wmt0206** [comment]
> > **问题描述 / Problem Description** 执行python init_database.py --recreate-vs后报错，ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'
> > **复现问题的步骤 / Steps to Reproduce**
> > 
> > 1. 执行 'python init_database.py --recreate-vs'
> > 2. 问题出现 / Problem occurs
> > 
> > **预期的结果 / Expected Result** 正常执行
> > **实际结果 / Actual Result** 提示缺少module
> > **环境信息 / Environment Information**
> > 
> > * langchain-ChatGLM 版本/commit 号：v0.2.8
> > * 是否使用 Docker 部署（是/否）：否
> > * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
> > * 使用的 Embedding 模型：text2vec-base
> > * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> > * 操作系统及版本 / Operating system and version: miniconda
> > * Python 版本 / Python version: 3.10.9
> > * 其他相关环境信息 / Other relevant environment information:
> > 
> > **附加信息 / Additional Information**
> > Traceback (most recent call last): File "E:\code\python\an\Langchain-Chatchat\init_database.py", line 3, in from server.knowledge_base.migrate import (create_tables, reset_tables, import_from_db, File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\migrate.py", line 11, in from server.knowledge_base.kb_service.base import KBServiceFactory File "E:\code\python\an\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 29, in from server.embeddings_api import embed_texts File "E:\code\python\an\Langchain-Chatchat\server\embeddings_api.py", line 3, in from server.model_workers.base import ApiEmbeddingsParams File "E:\code\python\an\Langchain-Chatchat\server\model_workers__init__.py", line 1, in from .base import * File "E:\code\python\an\Langchain-Chatchat\server\model_workers\base.py", line 5, in from fastchat.serve.base_model_worker import BaseModelWorker ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'
> 
> 我也是 你的解决了吗？

下载bge的时候看看是不是第一个那个1pooling的忘记下载了

**Comment by zRzRzRzRzRzRzR** [comment]
模型可能没有全，记得lfs装
