### ISSUE TITLE
[BUG] 在知识库中上传文件时遇到访问https://huggingface.co/None/resolve/main/tokenizer_config.json

### ISSUE THREAD

**Issue by WWeellkkiinn** [chatchat-space/Langchain-Chatchat#2325]
**问题描述 / Problem Description**
在知识库中上传文件时遇到了访问https://huggingface.co/None/resolve/main/tokenizer_config.json

**复现问题的步骤 / Steps to Reproduce**
1. 上传word文件到知识库
2. 然后显示访问https://huggingface.co/None/resolve/main/tokenizer_config.json
<img width="908" alt="1829fdcc22fc8dc643b879d1c5d1d30" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/93460558/b8b33af6-23b0-485c-8bc0-7a2330931363">

**预期的结果 / Expected Result**
正确向量化

**实际结果 / Actual Result**
访问不正确的网站

**环境信息 / Environment Information**
- langchain v0.2.8
- 是否使用 Docker 部署 否
- 使用的模型 zhipu-api
- 使用的 Embedding 模型 bge-large-zh-v1.5
- 使用的向量库类型 faiss
- 操作系统及版本 win11
- Python 版本 / Python version: 3.10

**Comment by zRzRzRzRzRzRzR** [comment]
模型没有正确安装吧，确保是hf下的
