### ISSUE TITLE
ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'

### ISSUE THREAD

**Issue by energy888666** [chatchat-space/Langchain-Chatchat#2327]
python startup.py -a  执行后 进入页面 http://127.0.0.1:8501 报错  
ModuleNotFoundError: No module named 'fastchat.serve.base_model_worker'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44359146/2a96df31-1dfb-4ed2-8735-52fb4cb6d4f4)

**Comment by zRzRzRzRzRzRzR** [comment]
fschat没有正确安装
