### ISSUE TITLE
[FEATURE] 简洁阐述功能 / Concise description of the feature  能否支持fastllm

### ISSUE THREAD

**Issue by zhuanyedecainiao** [chatchat-space/Langchain-Chatchat#2328]
当前直接调用的大模型使用个人PC跑起来非常慢，发现https://github.com/ztxz16/fastllm可在4090上能达到10000tokens/s。希望后期能够兼容，谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有这个计划，如果有PR我们会更快的执行
