### ISSUE TITLE
[BUG] 第一次提问后报错 /  utils.py[line:24] - ERROR: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by sleepyddl** [chatchat-space/Langchain-Chatchat#2329]
**问题描述 / Problem Description**
当我第一次提问 时，报错 utils.py[line:24] - ERROR: object of type 'NoneType' has no len()

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.8 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-1_8B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 操作系统及版本 / Operating system and version: windows
- Python 版本 / Python version: 3.10.10
![A1B0F879-A43A-40af-BB87-B21B2DE30D5C](https://github.com/chatchat-space/Langchain-Chatchat/assets/43658905/76e340c9-c366-45cf-a9cd-72f9ea140b9f)

**Comment by fxsome** [comment]
我也是这个问题，用的qwen-api，同样用的openai api没这个问题。

**Comment by sleepyddl** [comment]
> 我也是这个问题，centos下用的qwen-api，同样用的openai api没这个问题。

您好 请问有测试哪个离线的模型可以使用吗？

**Comment by fxsome** [comment]
> > 我也是这个问题，centos下用的qwen-api，同样用的openai api没这个问题。
> 
> 您好 请问有测试哪个离线的模型可以使用吗？

没试过

**Comment by Gavin-China** [comment]
同问题，用Qwen-14B-Chat启动正常无报错，但一提问就报错。

**Comment by zRzRzRzRzRzRzR** [comment]
应该是配置问题，这两个模型我这边是跑过的

**Comment by sleepyddl** [comment]
换成  bge-large-zh  和 chatglm2-6b  后 ，正常了

**Comment by kaixuanjames** [comment]
有朋友们解决了这个问题吗，我用的bge-large-zh和baichuan2-13B也是这个报错

**Comment by zRzRzRzRzRzRzR** [comment]
baichuan模型要降级transomers
