### ISSUE TITLE
能出一个api部署的描述文档吗

### ISSUE THREAD

**Issue by lilulu0702** [chatchat-space/Langchain-Chatchat#233]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by winie-hy** [comment]
加1

**Comment by Xavier-123** [comment]
看不太懂docs @imClumsyPanda

**Comment by ucas010** [comment]
我也是看不太懂咋请求，postman咋测试啊？对于知识库问答的

**Comment by zRzRzRzRzRzRzR** [comment]
请看最新代码，可以自己写一个model_factory 支持api接入
