### ISSUE TITLE
源模型非4bit，请问怎么配置4bit量化加载？

### ISSUE THREAD

**Issue by xxg98** [chatchat-space/Langchain-Chatchat#2330]
源模型非4bit，请问怎么配置4bit量化加载？

**Comment by zRzRzRzRzRzRzR** [comment]
你可以尝试用hf的方式载入，如果fschat没有适配，你只能自己写读入方法后转成openai或者model_worker的方式在fschat中注册

**Comment by xxg98** [comment]
> 你可以尝试用hf的方式载入，如果fschat没有适配，你只能自己写读入方法后转成openai或者model_worker的方式在fschat中注册

如何用hf的方式载入呢？
