### ISSUE TITLE
m3e-base和bge-large-zh-v1.5哪个效果好点？

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2331]
如题，哪个效果会好点？有没有人实际测试过？在下bge-large-zh-v1.5的模型了，想要试用下

**Comment by zRzRzRzRzRzRzR** [comment]
肯定是bge-large-zh-v1.5好啊

**Comment by qianma819** [comment]
> 肯定是bge-large-zh-v1.5好啊

感谢，待会试试效果。如果可以简单说下怎么个好法就更好了
