### ISSUE TITLE
[BUG] wiki文档中小错误（创建自己的Agent工具）

### ISSUE THREAD

**Issue by shishi11** [chatchat-space/Langchain-Chatchat#2332]
**问题描述 / Problem Description**
wiki的《使用自定义的 Agent 工具》中

创建自己的Agent工具
开发者在server/agent文件中创建一个自己的文件，并将其添加到tools.py------>（没有这个文件）中。这样就完成了Tools的设定。

**预期的结果 / Expected Result**
应该是tools_select.py的tools中

**Comment by zRzRzRzRzRzRzR** [comment]
收到，修改
