### ISSUE TITLE
建议修改以支持Apifox等API测试平台，正常解析流式调用结果

### ISSUE THREAD

**Issue by shiningxy** [chatchat-space/Langchain-Chatchat#2333]
**功能描述 / Feature Description**

支持Apifox等API测试平台，正常解析流式调用结果。

**解决的问题 / Problem Solved**

出现的错误据[Apifox帮助文档 常见问题](https://apifox.com/help/debugging-api/sse#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)显示：

请求 SSE 接口后，为什么底部的“时间线”没有输出有效消息？

这是因为服务器所返回的响应内容不符合 SSE 格式规范，Apifox 无法在时间线内展示消息。服务端可遵循以下 SSE 格式参考：

将消息内容放在 `data:` 之后
在每条消息结尾使用 2 个换行符，即每条消息之间空一行

将 server/chat/openai_chat.py 中的 get_response 函数进行修改

当前get_response函数：
```
    async def get_response(msg):
        data = msg.dict()

        try:
            response = await openai.ChatCompletion.acreate(**data)
            if msg.stream:
                async for data in response:
                    if choices := data.choices:
                        if chunk := choices[0].get("delta", {}).get("content"):
                            print(chunk, end="", flush=True)
                            yield chunk
            else:
                if response.choices:
                    answer = response.choices[0].message.content
                    print(answer)
                    yield(answer)
        except Exception as e:
            msg = f"获取ChatCompletion时出错：{e}"
            logger.error(f'{e.__class__.__name__}: {msg}',
                         exc_info=e if log_verbose else None)

```

**实现建议 / Implementation Suggestions**

修改：`get_response`函数中，当stream is true时，`yield f"data: {chunk}\n\n"`

建议修改后的get_response函数
```
    async def get_response(msg):
        data = msg.dict()

        try:
            response = await openai.ChatCompletion.acreate(**data)
            if msg.stream:
                async for data in response:
                    if choices := data.choices:
                        if chunk := choices[0].get("delta", {}).get("content"):
                            print(chunk, end="", flush=True)
                            yield f"data: {chunk}\n\n"
            else:
                if response.choices:
                    answer = response.choices[0].message.content
                    print(answer)
                    yield(answer)
        except Exception as e:
            msg = f"获取ChatCompletion时出错：{e}"
            logger.error(f'{e.__class__.__name__}: {msg}',
                        exc_info=e if log_verbose else None)

```

**替代方案 / Alternative Solutions**

**其他信息 / Additional Information**

修改前示例：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/55098508/e8891c3d-f20e-4087-aadf-0891d9ecc7bf)

修改后示例：

<img width="327" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/55098508/5d07303f-1608-428e-a041-6893e2cc9de4">

**Comment by suoqiLiu** [comment]
合理，在其他chat接口里也是一样的修改办法，返回的是json.dumps，用data再包一层才是规范的SSE
`        if stream:
            async for token in callback.aiter():
                answer += token
                # Use server-sent-events to stream the response
                res = json.dumps(
                    {"text": token, "chat_history_id": chat_history_id},
                    ensure_ascii=False)
                yield f"data: {res}\n\n"
                print(token)`

**Comment by fengzengfly** [comment]
希望支持

**Comment by liunux4odoo** [comment]
开发版中已做了修改（#1200）。
