### ISSUE TITLE
知识库召回文本最大字数好像设置不了

### ISSUE THREAD

**Issue by jhw0510** [chatchat-space/Langchain-Chatchat#2338]
**问题描述 / Problem Description**
知识库召回文本最大字数好像设置不了，我尝试修改了kb_config中的CHUNK_SIZE = 500，并没有生效，在搜索知识库时和设置CHUNK_SIZE = 250 一样，召回的文本怎么也超不过250字，但是我在chinese_recursive_text_splitter.py文件中测试了，当设置chunk_size是可以按照我想要的进行分块，比如将500个字分在一个块内，所有我现在有两个问题：
1、知识库召回文本最大字数该怎么设置，我想调大一点。
2、能不能直接看文本转向量的文本块是怎么分割的，我隐约记得原来可以看？

- langchain-ChatGLM 版本/commit 号：0.2.5-0.2.8都测试过不行
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss

**Comment by zRzRzRzRzRzRzR** [comment]
你设置的分词是多少，你召回的分词就是多少，因为 embed 模型是整块整块比对的

**Comment by jhw0510** [comment]
> 你设置的分词是多少，你召回的分词就是多少，因为 embed 模型是整块整块比对的

首先感谢您的回复。

可是我设置了kb_config中的CHUNK_SIZE = 500后，召回的文本还是不会超过250，是我修改的地方不对吗，我没看见代码里有其他设置这个的地方呀

**Comment by loredunk** [comment]
> > 你设置的分词是多少，你召回的分词就是多少，因为 embed 模型是整块整块比对的
> 
> 首先感谢您的回复。
> 
> 可是我设置了kb_config中的CHUNK_SIZE = 500后，召回的文本还是不会超过250，是我修改的地方不对吗，我没看见代码里有其他设置这个的地方呀

请问您 的解决了吗？

**Comment by jhw0510** [comment]
> > > 你设置的分词是多少，你召回的分词就是多少，因为 embed 模型是整块整块比对的
> > 
> > 
> > 首先感谢您的回复。
> > 可是我设置了kb_config中的CHUNK_SIZE = 500后，召回的文本还是不会超过250，是我修改的地方不对吗，我没看见代码里有其他设置这个的地方呀
> 
> 请问您 的解决了吗？

我当时解决了，你可以看我写的#2561 ，但是我不确定和你的问题是否一致

**Comment by loredunk** [comment]
> > > > 你设置的分词是多少，你召回的分词就是多少，因为 embed 模型是整块整块比对的
> > > 
> > > 
> > > 首先感谢您的回复。
> > > 可是我设置了kb_config中的CHUNK_SIZE = 500后，召回的文本还是不会超过250，是我修改的地方不对吗，我没看见代码里有其他设置这个的地方呀
> > 
> > 
> > 请问您 的解决了吗？
> 
> 我当时解决了，你可以看我写的#2561 ，但是我不确定和你的问题是否一致

我按照你的方法去分词强制修改了，改之后，在前端显示的每个块的数量没有变化
