### ISSUE TITLE
[FEATURE] 可以一个模型启动多个model_worker吗

### ISSUE THREAD

**Issue by Lijia0** [chatchat-space/Langchain-Chatchat#2339]
**功能描述 / Feature Description**
想要一个模型启动多个model_worker，以提高并发量，不知道该怎么改，或者有没有fastchat的文档。

**Comment by Lijia0** [comment]
得用到nginx，部署多个model_worker，反向代理到一个端口号

**Comment by zRzRzRzRzRzRzR** [comment]
可以，用 Fastchat 启动就行了
