### ISSUE TITLE
使用docs/API.md 出错

### ISSUE THREAD

**Issue by eeric** [chatchat-space/Langchain-Chatchat#234]
使用API.md文档2种方法，出错
一种是curl，一种是requests

**Comment by BrightXiaoHan** [comment]
目前api文档是widdershins自动生成的，可能有些问题，后序会进行更新。可以启动api服务后先使用 http://127.0.0.1:7861/docs访问fastapi网页文档

**Comment by eeric** [comment]
哦，希望早日更新，谢谢。

**Comment by ucas010** [comment]
have the same request question
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/465
