### ISSUE TITLE
加载chatglm3-6b lora自我认知的模型之后，无效果

### ISSUE THREAD

**Issue by yintju03** [chatchat-space/Langchain-Chatchat#2340]
用LLaMA-Factory lora微调的chatglm3-6b,用的self_cognition.json,导出模型之后，在mondel_config.py里面配置，启动没问题，问答的时候还是原来回答，self_cognition的内容没生效

**Comment by zRzRzRzRzRzRzR** [comment]
尝试合并成一个新的6b完整模型能否载入
如果你是分开的，你应该按照[Wiki](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89#%E4%BD%BF%E7%94%A8%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9A%84%E5%BE%AE%E8%B0%83%E6%A8%A1%E5%9E%8B)上的方式来操作

**Comment by ghx2757** [comment]
> 用LLaMA-Factory lora微调的chatglm3-6b,用的self_cognition.json,导出模型之后，在mondel_config.py里面配置，启动没问题，问答的时候还是原来回答，self_cognition的内容没生效

你好，请问你这个问题如何解决的啊？

**Comment by yintju03** [comment]
> > 用LLaMA-Factory lora微调的chatglm3-6b,用的self_cognition.json,导出模型之后，在mondel_config.py里面配置，启动没问题，问答的时候还是原来回答，self_cognition的内容没生效
> 
> 你好，请问你这个问题如何解决的啊？

没解决呢，我用fastchat加载也不行
