### ISSUE TITLE
生成的回答包含符号<|assistant|>，<user>等，首行还会出现逗号的问题

### ISSUE THREAD

**Issue by fengzengfly** [chatchat-space/Langchain-Chatchat#2341]
使用chatglm3-6b，回答结果如下：
1. 回答不完整，首行出现逗号
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/48151231/7000f791-8670-4150-9d31-d7326dcb1d93)
2. 出现符号<|assistant|>
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/48151231/98aad844-42b7-4d36-be85-7407bc7ca3a8)

**Comment by fengzengfly** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/48151231/f15eaad4-fbb8-4883-a0d2-48833dfeff10)

**Comment by fengzengfly** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/48151231/297e8bb3-0e51-444d-b73e-abe0e9b784cb)

**Comment by ghx2757** [comment]
尝试从新拉一下代码，然后更新一下fschat这个库版本到最新试试呢，之前也遇到了这个问题。

**Comment by misAdann** [comment]
之前也遇到过，解决方法是把所有东西都更新。包括chatglm3-6b

**Comment by fengzengfly** [comment]
重新拉了下chatglm3的模型，恢复正常了

**Comment by byrain** [comment]
更新了 modeling_chatglm.py 和 tokenization_chatglm.py 两个文件后正常了。

**Comment by BackMountainDevil** [comment]
[wiki->常见问题->Q20](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q20-chatglm3-6b%E5%AF%B9%E8%AF%9D%E4%B8%AD%E5%87%BA%E7%8E%B0user%E6%A0%87%E7%AD%BE%E4%B8%94%E8%87%AA%E9%97%AE%E8%87%AA%E7%AD%94)

**Comment by 572120986** [comment]
更新了GLM3和fschat为0.2.35 还是会自问自答

**Comment by ghx2757** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/issues/2341#issuecomment-1900023549
也得保证原始权重文件也是最新的

**Comment by PairZhu** [comment]
fastchat是必须从源码安装最新的才行吗？

**Comment by PairZhu** [comment]
感谢大佬们，我更新了fastchat就好了，但是作者是不是应该更新一下仓库里的requirements.txt

**Comment by PairZhu** [comment]
> 同样遇到这个问题，但我是在调用智谱api的时候出现的，想请教一下各位大佬，应该如何更新fastchat呀

pip uninstall再重新install这个包就行了啊

**Comment by zixiaotan21** [comment]
好的好的，我明白了，谢谢！

**Comment by aben1900** [comment]
chatglm3-6b-128k这个模型的问题，我用了chatglm3-6b正常版，就能用了，看来是128k的问题
