### ISSUE TITLE
初始化知识库的时候，csv文件报错。是否缺了某个依赖？

### ISSUE THREAD

**Issue by bytebit** [chatchat-space/Langchain-Chatchat#2342]
2023-12-10 16:24:56,552 - utils.py[line:368] - ERROR: RuntimeError: 从文件 samples//data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv

Batches: 100%|███████████████████████████████████████████████████████████████████████████████████| 11/11 [02:21<00:00, 12.88s/it]
('samples', '/data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv', '从文件 samples//data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv')

]2023-12-10 16:24:56,552 - utils.py[line:368] - ERROR: RuntimeError: 从文件 samples//data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading /data/gk/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.csv

**Comment by zRzRzRzRzRzRzR** [comment]
么有遇到，你是在init做的吗

**Comment by bytebit** [comment]
python init_database.py --recreate-vs在这个时候出现的，多次创建python环境安装都能复现这个问题

**Comment by liunux4odoo** [comment]
其他 csv 没有问题，就是这个 closed.csv 会出问题，应该是文件内容的原因。
