### ISSUE TITLE
[BUG] 单卡运行正常，多卡运行报错TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by yhaiqiang** [chatchat-space/Langchain-Chatchat#2347]
**问题描述 / Problem Description**
用单卡跑百川模型，选择LLM对话正常，用多卡跑百川模型，选择LLM对话报错，

TypeError: object of type 'NoneType' has no len()
2023-12-11 15:17:06,127 - utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by zhaoqianyue** [comment]
我也是

**Comment by hoiwanchang** [comment]
startup.py里面可以改配置虽然文档不推荐，但是可以改成类似
```python
173             args.gpus = "0,1" # GPU的编号,如果有多个GPU，可以设置为"0,1,2,3"
174             args.max_gpu_memory = "16GiB"
175             args.num_gpus = 2  # model worker的切分是model并行，这里填写显卡的数量
```

**Comment by kaixuanjames** [comment]
我也遇到同样的问题，请问有解决的办法了吗

**Comment by yhaiqiang** [comment]
> startup.py里面可以改配置虽然文档不推荐，但是可以改成类似
> 
> ```python
> 173             args.gpus = "0,1" # GPU的编号,如果有多个GPU，可以设置为"0,1,2,3"
> 174             args.max_gpu_memory = "16GiB"
> 175             args.num_gpus = 2  # model worker的切分是model并行，这里填写显卡的数量
> ```

我之前就是通过这种方式多卡部署的，还是报错

**Comment by ChaoDiDiaoAA** [comment]
多卡部署加载后回答出现乱码，有遇到这汇总情况的吗
