### ISSUE TITLE
[BUG] 如何保存对话？

### ISSUE THREAD

**Issue by yutong12** [chatchat-space/Langchain-Chatchat#2348]
如何保存对话？

langchain版本 v0.2.8
llm：Qwen-14b-chat-int4
问题：在工程文件中找不到保存对话的位置，似乎是Langchain项目组没有设置对话自动保存，目前期望有一个固定保存历史对话的功能，便于训练和微调

**Comment by maxusheng123** [comment]
可能是我不知道吧，我现在还在用redis存对话历史，通过uid-key取出来，做知识库多轮问答。

**Comment by yutong12** [comment]
你存在哪里的？没有地方显示有这个对话记录呀

**Comment by yutong12** [comment]
除了它自己有打印

**Comment by yutong12** [comment]
我找到了 在知识库那里  是个db文件
整体使用的SQLlite数据库

**Comment by Longleaves** [comment]
可以请教一下对话历史具体保存在哪个位置吗？

**Comment by yutong12** [comment]
在sqlite里面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月27日(周一) 下午2:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 如何保存对话？ (Issue #2348)




 
可以请教一下对话历史具体保存在哪个位置吗？

**Comment by Longleaves** [comment]
没有发现有db文件，也没有sqlite呀？
