### ISSUE TITLE
如何实现多机部署

### ISSUE THREAD

**Issue by IgnoranceSmile** [chatchat-space/Langchain-Chatchat#2352]
**功能描述 / Feature Description**
希望将模型和api开在不同的电脑上，请问应该如何实现？能否在Wiki中进行说明

**Comment by Lijia0** [comment]
python startup.py -m -c "http://xxxxxxx:20001"  可以用这个只启动model_worker

**Comment by IgnoranceSmile** [comment]
> python startup.py -m -c "http://xxxxxxx:20001" 可以用这个只启动model_worker

但是怎么在另一台电脑上访问到本机打开的模型呢，我尝试在online model中指定这些模型，但是并没有成功

**Comment by zRzRzRzRzRzRzR** [comment]
用APi传，类似openai的方法
