### ISSUE TITLE
运行pip install -r requirements_lite.txt报错

### ISSUE THREAD

**Issue by jimilabinfo** [chatchat-space/Langchain-Chatchat#2353]
ERROR: Cannot install -r requirements_lite.txt (line 3), -r requirements_lite.txt (line 4), -r requirements_lite.txt (line 61) and httpx~=0.24.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested httpx~=0.24.1
    fschat 0.2.33 depends on httpx
    openai 1.3.6 depends on httpx<1 and >=0.23.0
    duckduckgo-search 3.9.11 depends on httpx>=0.25.1
    The user requested httpx~=0.24.1
    fschat 0.2.33 depends on httpx
    openai 1.3.6 depends on httpx<1 and >=0.23.0
    duckduckgo-search 3.9.10 depends on httpx>=0.25.1
    The user requested httpx~=0.24.1
    fschat 0.2.33 depends on httpx
    openai 1.3.6 depends on httpx<1 and >=0.23.0
    duckduckgo-search 3.9.9 depends on httpx>=0.25.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by liunux4odoo** [comment]
dev 分支已经做了修改。

当前可以手动把 httpx~=0.24.1 改为 httpx[brotli,http2,socks]>=0.25.2
