### ISSUE TITLE
[BUG] 使用LLaMA-Factory二次训练后合并的模型，回复问题无法有效截止

### ISSUE THREAD

**Issue by szinstai** [chatchat-space/Langchain-Chatchat#2354]
问题描述 / Problem Description
使用LLaMA-Factory二次训练后合并的模型，回复问题无法有效截止，在LLaMA-Factory的chat中加载测试正常。
![20231211223204](https://github.com/chatchat-space/Langchain-Chatchat/assets/137600616/9904710e-4ccf-4bdf-bd0a-f8cdddfeab99)

后面尝试添加TOP_K参数，对bug同样无法解决。

是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-7B-chat 二次训练 ，训练参数 3轮，学习率1e-4，其他默认参数。学习自带json
使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version:ubuntu 22.04
Python 版本 / Python version:3.10.12

**Comment by yhfgyyf** [comment]
用llama-factory的api_demo.py启动openai api，然后去fastchat注册后可以使用

**Comment by yhfgyyf** [comment]
> @yhfgyyf 您好，有具体的操作方法吗，我也是这个问题，将微调后的模型合并后，部署在这里模型回答还是和原模型效果相同
可参考https://github.com/yhfgyyf/Langchain-Chatchat.git，third-party-openai-api分支，在textgeneration-api中配置

**Comment by GitYohoo** [comment]
@HBdingdang 我也遇到了同样的问题，在LLaMA-Factory的chat中加载测试正常，回答为微调后的内容，而使用langchain-chatchat加载就和原模型回答相同

**Comment by HBdingdang** [comment]
@GitYohoo 我直接用llama-factory中的api启动生成url，然后在langchain-chatchat设置其url为线上模型就行了

**Comment by zhanghx0905** [comment]
使用 llama-factory 的 api_demo.py 脚本能启动一个与 OpenAI 兼容的 API，顺利接入微调后的模型。
但我觉得这只是一个临时的解决方案，因为这样就不能使用fastchat的分布式管理了。

我在直接使用 fastchat 与微调后的模型进行命令行对话时，一切正常。但问题出现在使用 chatchat 启动 fastchat 进行对话时：我无法得到预期的回复。尽管我已经投入大量时间进行故障排查，问题的根源仍然是一个谜。

**Comment by yhfgyyf** [comment]
> 使用 llama-factory 的 api_demo.py 脚本能启动一个与 OpenAI 兼容的 API，顺利接入微调后的模型。
> 但我觉得这只是一个临时的解决方案，因为这样就不能使用fastchat的分布式管理了。
> 
> 我在直接使用 fastchat 与微调后的模型进行命令行对话时，一切正常。但问题出现在使用 chatchat 启动 fastchat 进行对话时：我无法得到预期的回复。尽管我已经投入大量时间进行故障排查，问题的根源仍然是一个谜。

我最近测试了chatglm3的微调模型，使用llama-factory微调，template为 chatglm3，我对比了下llama-factory中的template和fastchat conversation中chatglm3的template，主要区别是llama-factory中的template带有固定的system prompt，而fastchat中没有设定死system prompt（chatglm3的官方repo的readme中也没有设定死system prompt，而是根据chat，function call，code interpreter三种情况区分了system prompt）。
将lora合并后，使用llama-factory框架推理，微调效果还在，
直接使用fastchat启动合并后的微调模型，微调效果消失，所以我尝试在fastchat/conversation.py中增加了chatglm3的system prompt，然后启动，微调效果回来了，我不确定这是特例还是根本原因，也没有测试这种情况下function call能力是否会丢失（等有空了再测试）。
现在的情况下可以尝试在conversation中修改或者增加新的template，在langchain-chatchat的server_config.py中增加--conv-template参数来指定template，当然这样也同样非常麻烦，但是这已经是在fastchat框架内启动的方案了。

**Comment by zhanghx0905** [comment]
> > 使用 llama-factory 的 api_demo.py 脚本能启动一个与 OpenAI 兼容的 API，顺利接入微调后的模型。
> > 但我觉得这只是一个临时的解决方案，因为这样就不能使用fastchat的分布式管理了。
> > 我在直接使用 fastchat 与微调后的模型进行命令行对话时，一切正常。但问题出现在使用 chatchat 启动 fastchat 进行对话时：我无法得到预期的回复。尽管我已经投入大量时间进行故障排查，问题的根源仍然是一个谜。
> 
> 我最近测试了chatglm3的微调模型，使用llama-factory微调，template为 chatglm3，我对比了下llama-factory中的template和fastchat conversation中chatglm3的template，主要区别是llama-factory中的template带有固定的system prompt，而fastchat中没有设定死system prompt（chatglm3的官方repo的readme中也没有设定死system prompt，而是根据chat，function call，code interpreter三种情况区分了system prompt）。 将lora合并后，使用llama-factory框架推理，微调效果还在， 直接使用fastchat启动合并后的微调模型，微调效果消失，所以我尝试在fastchat/conversation.py中增加了chatglm3的system prompt，然后启动，微调效果回来了，我不确定这是特例还是根本原因，也没有测试这种情况下function call能力是否会丢失（等有空了再测试）。 现在的情况下可以尝试在conversation中修改或者增加新的template，在langchain-chatchat的server_config.py中增加--conv-template参数来指定template，当然这样也同样非常麻烦，但是这已经是在fastchat框架内启动的方案了。

我微调了chatglm2和baichuan2，都出现了回答不正常、胡言乱语的情况，看来问题出在template上？

**Comment by zixiaotan21** [comment]
同样好奇这个问题，想问问大家解决了吗
