### ISSUE TITLE
[BUG] 后台向量化命令求助

### ISSUE THREAD

**Issue by Madilynalisa** [chatchat-space/Langchain-Chatchat#2358]
**问题描述 / Problem Description**
webui文件向量化时间太长，求助在后台content目录下向量化的具体命令。

**复现问题的步骤 / Steps to Reproduce**
1. 将pdf文件添加至content目录下
2. 在webui进行向量化

**预期的结果 / Expected Result**
一定时间内完成向量化

**实际结果 / Actual Result**
耗时过长

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-14b-4bits
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- Python 版本 / Python version: 3.9

**Comment by liunux4odoo** [comment]
见 wiki

**Comment by xldistance** [comment]
> 见 wiki

wiki没找到cli向量化的命令
