### ISSUE TITLE
对于包含正反义词的语句召回，如何进行优化？

### ISSUE THREAD

**Issue by ryancurry-mz** [chatchat-space/Langchain-Chatchat#2360]
1. 问题描述：我目前遇到一个场景，两句query中只有一个词不同，但是两句话是相反的意思，导致召回时可能会检索到相反意思的答案。
2. 目前的思路：尝试过微调embedding模型，这种情况相似度会略微下降，感觉没有解决问题。想请问，有没有更好地方式从已检索出的结果中拿到正确答案。
3. 例子：
- query1：献血者不能献血的情况有哪些？
- query2：献血者能献血的情况有哪些？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/56419382/013182bd-8933-420e-b123-e46268a2520b)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/56419382/55e5aaae-057e-4045-a5bd-c40684b4c651)

**Comment by zRzRzRzRzRzRzR** [comment]
这种情况基本就是召回了但是大模型知道这不是答案所以不返回
或者你说微调embed
