### ISSUE TITLE
使用通义千问模型调用工具时候工具参数无法正确提取

### ISSUE THREAD

**Issue by reddeath1985** [chatchat-space/Langchain-Chatchat#2361]
自定义了一个agenttool，可以识别并调用tool。但是tool里面定义好的参数完全没有提取到，请问如何解决，报错和代码如下
以下是报错日志---------------------------------------------------
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/23158897/3a698123-152f-4158-b8da-13c8ab208766)

以下是代码---------------------------------------------------

# 自定义结构化查询工具
from pydantic import BaseModel, Field

def findeverything(location: str,color_of_tops: str,color_of_pants:str,starttime: str,endtime: str):
    ret=location+" "+color_of_tops+" "+color_of_pants +" "+starttime+" "+endtime
    return ret

class FindEverything(BaseModel):
    location: str = Field(description="location，事情发生的地点")
    color_of_tops: str = Field(description="color_of_tops，上衣的颜色, e.g.白色、黑色")
    color_of_pants:str=Field(description="color_of_pants，裤子的颜色, e.g.白色、黑色")
    starttime: str = Field(description="starttime，这是开始时间,要转化成YYYY-MM-DD HH-mm-ss格式")
    endtime: str = Field(description="endtime，这是结束时间,要转化成YYYY-MM-DD HH-mm-ss格式")

**Comment by reddeath1985** [comment]
已经解决，自定义多个参数的工具可以使用StructuredTool

**Comment by diana1919zhong** [comment]
> 已经解决，自定义多个参数的工具可以使用StructuredTool

请问自定义多参数的工具传参，应该怎么传呢，应该修改哪里的代码

**Comment by HappyWHoo** [comment]
@reddeath1985 你好，如果在问题中没有录入这个参数，怎么让提醒用户录入啊？
