### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by sisuad** [chatchat-space/Langchain-Chatchat#2362]
**问题描述 / Problem Description**
readme错别字

**复现问题的步骤 / Steps to Reproduce**
1. 目录
2. 解决的痛点
3. 第二段
4. 我们支持市面上主流的本地大**预言**模型和Embedding模型，支持开源的本地向量数据库。 

**预期的结果 / Expected Result**
我们支持市面上主流的本地大语言模型和Embedding模型，支持开源的本地向量数据库。 

**实际结果 / Actual Result**
我们支持市面上主流的本地大预言模型和Embedding模型，支持开源的本地向量数据库。 

**环境信息 / Environment Information**
无

**附加信息 / Additional Information**
无

**Comment by nanayashiki1215** [comment]
。。。厉害了
