### ISSUE TITLE
[BUG] docker一键部署命令无法使用GPU/在容器内部可以使用nvidai-smi命令，但没有显示正在占用进程

### ISSUE THREAD

**Issue by drowninwater** [chatchat-space/Langchain-Chatchat#2367]
**问题描述 / Problem Description**
使用 docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.7 命令后能在端口加载webui界面，但回答很慢，是没有用上GPU.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'sudo docker exec -it 587 /bin/bash' 
2. 执行 'nvidia-smi'
3. 滚动到进程部分·
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104676193/9202da3f-6183-4eb3-8e9d-8f49c5d723e0)

5. 问题出现 发现没有使用GPU

**Comment by tommyvinny** [comment]
看你是使用的什么使用DOCKER。我是用的UNRAID使用DOCKER。在使用时，要定义显卡调用才行。
机器得先安装nvidia的驱动的。UNRAID的话是安装插件[Nvidia Driver Package](https://forums.unraid.net/)
然后设定变量
NVIDIA_VISIBLE_DEVICES=GPU-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXX 
你这看起来是GPU没有到DOCKER中调用。所以是空的。如果DOCKER中调用显卡成功应该显示如下。
# nvidia-smi
Fri Dec 15 07:27:37 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.29.06              Driver Version: 545.29.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P40                      Off | 00000000:3B:00.0 Off |                  Off |
| N/A   41C    P0              49W / 250W |  13424MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
