### ISSUE TITLE
Lite方式运行系统，用webui的“知识库管理”导入txt和json格式文件，都出现这样的提示None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

### ISSUE THREAD

**Issue by bytebit** [chatchat-space/Langchain-Chatchat#2368]
2023-12-12 14:58:55,107 - utils.py[line:286] - INFO: UnstructuredFileLoader used for /data/Langchain-Chatchat/knowledge_base/samples/content/2023.txt
**None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`**
...........................................' metadata={'source': '/data/Langchain-Chatchat/knowledge_base/samples/content/2023.txt'}
Batches: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:12<00:00, 12.70s/it]
2023-12-12 14:59:09,898 - faiss_cache.py[line:24] - INFO: 已将向量库 ('samples', 'bge-large-zh') 保存到磁盘

**Comment by liunux4odoo** [comment]
参考 wiki， 确保 embedding_model 正确配置

**Comment by bytebit** [comment]
我提供了zhipu api key之后，还需要下载embedding_model吗？我真的把wiki和model_config.py代码看了好几篇，的确是比较愚钝，不知道应该怎么配置。求指教

**Comment by bytebit** [comment]
比较困惑的是，虽然有这个错误提示，但是初始化数据库好像又是成功的。

**Comment by zyf950120** [comment]
我也遇到了这个问题，加载不了jsonl和txt'文件
使用的是如下默认的配置
LLM: Chatglm2-6b
Embedding Models: m3e-base
TextSplitter: ChineseRecursiveTextSplitter
Kb_dataset: faiss

**Comment by liunux4odoo** [comment]
embedding_model 设为你可用的在线API，比如 zhipu-api。lite模式下没装torch，不支持任何本地模型

**Comment by bytebit** [comment]
embedding_model 设为你可用的在线API——请问怎么设？翻了所有wiki，都没有写这个配置方法。
本地消费级显卡，大家可以来玩一下。还有很多情况，是真的需要lite模式运行的。
下面是从model_config.py文件摘出来的，如何修改这个配置呢？
------------------------------
MODEL_PATH = {
    "embed_model": {
                 "bge-large-zh": "BAAI/bge-large-zh",

**Comment by bytebit** [comment]
整个代码库，也只有configs/model_config.py.example这里有涉及open.bigmodel.cn，哪里还能去配置智谱text_embedding啊？

**Comment by bytebit** [comment]
有没有可能LLM模型用zhipu API，而embed_model用本地的呢？

**Comment by liunux4odoo** [comment]
> ## embedding_model 设为你可用的在线API——请问怎么设？翻了所有wiki，都没有写这个配置方法。
> 本地消费级显卡，大家可以来玩一下。还有很多情况，是真的需要lite模式运行的。
> 下面是从model_config.py文件摘出来的，如何修改这个配置呢？
> MODEL_PATH = { "embed_model": { "bge-large-zh": "BAAI/bge-large-zh",
> 
> ## 还是说应该修改下面这个配置：
> 选用的 Embedding 名称

EMBEDDING_MODEL = "zhipu-api"

**Comment by bytebit** [comment]
EMBEDDING_MODEL = "zhipu-api"——修改了，问题依旧，导入文档到知识库的时候还是有这个错误信息。

**Comment by zRzRzRzRzRzRzR** [comment]
换一个模型试试， 之后zhipu AI的API要重写的

**Comment by Meaninles** [comment]
你好，请问解决了吗，遇到同样的问题

**Comment by AMAG-AB** [comment]
@zRzRzRzRzRzRzR 老板你好，使用了在线api和本地emb模型进行上传知识库的时候就会一直报：None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`
None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'                               导致向量化一直无法进行，程序卡在这个环节。请问是bug吗？或者我在哪里可以修改代码，不启动大模型也能运行项目呢？
