### ISSUE TITLE
更新langchain包后，上传知识报错

### ISSUE THREAD

**Issue by shujun1992** [chatchat-space/Langchain-Chatchat#2371]
langchain0.0.317版本正常使用，
升级langchain 至最新版本后报错
The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by jiusi9** [comment]
@shujun1992  请问下，现在还是使用的 langchain 0.0.317版本吗，对应的langchain-core和langchain-experimental是哪个版本呀
