### ISSUE TITLE
是否可以支持输入图片和文本，支持多模态模型

### ISSUE THREAD

**Issue by ArlanCooper** [chatchat-space/Langchain-Chatchat#2372]
**需求内容
希望可以支持多模态的模型，可以支持文本和图片的输入，以及支持gpt-4-turbo-vision版本的使用。

**解决的问题 / Problem Solved**
现在不支持gpt-4-V版本的输入，即不支持图片和文本同时输入。

**实现建议 / Implementation Suggestions**
另外开一个支持多模态输入的接口，可以进行文本，图片，甚至后面其他媒体形式的输入。

**Comment by yhfgyyf** [comment]
好像下个版本支持开源的多模态模型，到时候改下就可以，现在直接改工作量有点大
