### ISSUE TITLE
[BUG] 我无法调用该项目的api功能

### ISSUE THREAD

**Issue by lzl-hello** [chatchat-space/Langchain-Chatchat#2373]
我用autodl复现了该项目，webui功能中有一个模型可以正常对话，我想用python写代码访问提供的api，以此得到答复，但api界面的几个测试都无法返回答复：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/96810799/8ecf4e13-1009-4819-a6a4-d7dac9012bd0)
woy我用postman测试了后端也没有答复返回，想问一下怎么实现api功能

**Comment by didicn** [comment]
max_tokens 改成 2000 试试

**Comment by lzl-hello** [comment]
> 是新版吗，可以用apifox
> 
> 参看这个 #1200

sorry，我没看明白是怎么解决的；
![25d2026b02db87691b08025a1a4c4294](https://github.com/chatchat-space/Langchain-Chatchat/assets/96810799/e5224842-e11a-4c66-a8cc-4109f4da2fea)
ce测试第一个接口，它显示是版本不支持；
![d00d0b7520fc2bc4b4fa3f1e96045fb8](https://github.com/chatchat-space/Langchain-Chatchat/assets/96810799/8d590ed5-8e0f-48b7-bb71-13e53fc4cf5b)
ceshi测试第二个的话，返回textStatus: error


我如果想用python程序调用这个api，我需要修改哪些地方吗？我就是把autodl上的镜像克隆了一下，一键启动，启用ssh隧道，然后没有做任何修改

**Comment by lzl-hello** [comment]
我最近在别的地方购买了chatgpt的api，请问要修改哪部分代码配置来使用呢

**Comment by tommyvinny** [comment]
module.py
