### ISSUE TITLE
langchain调用自己部署的模型的api

### ISSUE THREAD

**Issue by fuxiaoiii** [chatchat-space/Langchain-Chatchat#2375]
我想在服务器部署chatglm3模型，然后再langchain中调用其API进行对话，我发现server_config.py.example文件中有较多api的篇幅，但是不清楚如何修改？

**Comment by liunux4odoo** [comment]
模型配置的方法见wiki和配置文件注释。

**Comment by fuxiaoiii** [comment]
> 模型配置的方法见wiki和配置文件注释。

我想要在昇腾环境部署glm3，然后在langchain中调用glm3的api，不是GPU环境。只是修改本项目中的model_config.py应该不行
