### ISSUE TITLE
[FEATURE] 如何让模型根据知识库的知识进行二次学习,具有分析的能力

### ISSUE THREAD

**Issue by youbingchenyoubing** [chatchat-space/Langchain-Chatchat#2378]
**功能描述 / Feature Description**
如何让模型根据知识库的知识进行二次学习,具有分析的能力

**解决的问题 / Problem Solved**
知识库,现在这个流程只是提供检索能力,然后通过模型整合出结果,如果有些垂直领域的相关性没被检索出来,就无法整合这些能力
**实现建议 / Implementation Suggestions**
如果有可能提供一些后台运行的方案,找出垂直领域知识相关性.或者进行垂直领域模型微调,方案二成本和技术门槛较高

**Comment by nanayashiki1215** [comment]
wiki中已有微调方案
