### ISSUE TITLE
加载pdf文档报错？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#238]
ew one with MEAN pooling.
Unable to get page count. Is poppler installed and in PATH?
caibao.pdf 未能成功加载
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/autodl-tmp/chatglm/langchain-ChatGLM-master/cli_demo.py:32 in <module>                     │
│                                                                                                  │
│   29 │   │   #filepath = "./zysbaoxian/zysjianli.txt"                                            │
│   30 │   │   #filepath = "./zysbaoxian/aodishouce.pdf"                                           │
│   31 │   │   filepath = "./zysbaoxian/caibao.pdf"                                                │
│ ❱ 32 │   │   vs_path, _ = local_doc_qa.init_knowledge_vector_store(filepath)                     │
│   33 │   history = []                                                                            │
│   34 │   while True:                                                                             │
│   35 │   │   query = input("Input your question 请输入问题：")                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot unpack non-iterable NoneType object

**Comment by warriorz007zn** [comment]
参考：https://github.com/Belval/pdf2image
试试：
conda install -c conda-forge poppler

但后面又遇到少东西加载不了pdf，暂时还没找到办法。

**Comment by biiigwang** [comment]
The same problem occurs

``` bash
Input your local knowledge file path 请输入本地知识文件路径：/content/1312.5602.pdf
WARNING 2023-05-10 10:21:06,541-1d: detectron2 is not installed. Cannot use the hi_res partitioning strategy. Falling back to partitioning with another strategy.
WARNING 2023-05-10 10:21:06,541-1d: Falling back to partitioning with ocr_only.
Unable to get page count. Is poppler installed and in PATH?
1312.5602.pdf 未能成功加载
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/drive/MyDrive/gitCode/langchain-ChatGLM/cli_demo.py:24 in <module>  │
│                                                                              │
│   21 │   │   # 判断 filepath 是否为空，如果为空的话，重新让用户输入,防止用户 │
│   22 │   │   if not filepath:                                                │
│   23 │   │   │   continue                                                    │
│ ❱ 24 │   │   vs_path, _ = local_doc_qa.init_knowledge_vector_store(filepath) │
│   25 │   history = []                                                        │
│   26 │   while True:                                                         │
│   27 │   │   query = input("Input your question 请输入问题：")               │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot unpack non-iterable NoneType object
```
