### ISSUE TITLE
[BUG] 文档加载器字典中值doc格式设置值错误

### ISSUE THREAD

**Issue by anyfeng** [chatchat-space/Langchain-Chatchat#2382]
**问题描述 / Problem Description**
文档加载器字典中值doc格式设置值错误，导致doc格式文档无法加载以及向量化

**复现问题的步骤 / Steps to Reproduce**
代码位于 utlis.py 中 LOADER_DICT UnstructuredWordDocumentLoader

**Comment by liunux4odoo** [comment]
Duplicate of #2326
