### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by blocbe** [chatchat-space/Langchain-Chatchat#2385]
**问题描述 / Problem Description**
LLM API访问无法访问，通过startup.py访问异常, 使用本地的ChatGLM2-6B-int4 模型

**复现问题的步骤 / Steps to Reproduce**
1. 执行  python startup.py -a
2. 浏览器自动打开LangChain-ChatchatWebUI页面
3. 选择LLM对话， LLM模型-“chatglm2-6b-int4 (Running)”，进行提问， 无应答
4.  后台出现报错： httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
2023-12-14 18:09:18,328 - utils.py[line:27] - ERROR: RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)
5： 再次提问， 出现 raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple widgets with the same `key=''`.

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatChat 版本/commit 号：V0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B/ChatGlM2-6B-int4 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Win11
- Python 版本 / Python version: V3.10.11
![11](https://github.com/chatchat-space/Langchain-Chatchat/assets/45092546/62c4b57b-0607-40ea-8f32-60aefdffc224)
![12](https://github.com/chatchat-space/Langchain-Chatchat/assets/45092546/8bbd4349-9297-4671-a26f-ae4d5d889082)

- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
int4模型不支持
