### ISSUE TITLE
[BUG] ptuning后的chatglm2-6B报错

### ISSUE THREAD

**Issue by DOVEEEEEEEEEEEEE** [chatchat-space/Langchain-Chatchat#2387]
本地部署，模型为chatGLM2-6B，经过ptuning微调，python=3.9 系统为linux 
按照wiki中的最佳实践修改peft和fastchat，输入PEFT_SHARE_BASE_WEIGHTS=true python startup.py -a 运行过程中报错
<img width="956" alt="屏幕截图 2023-12-15 132059" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/147513587/c1c4c6f2-7d9b-4160-8f71-81cfaf6f4dfd">

**Comment by hzg0601** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/22924096/6aa10d6a-780e-467e-9f8a-955052515039)
