### ISSUE TITLE
运行 python startup.py -a 的时候报错: TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by tengDeloitte** [chatchat-space/Langchain-Chatchat#2391]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

运行 python startup.py -a  以后出现以下报错:

Traceback (most recent call last):
  File "/Users/max/Documents/GitHub/Langchain-Chatchat/startup.py", line 880, in <module>
    loop.run_until_complete(start_main_server())
  File "/Users/max/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/max/Documents/GitHub/Langchain-Chatchat/startup.py", line 647, in start_main_server
    dump_server_info(args=args)
  File "/Users/max/Documents/GitHub/Langchain-Chatchat/startup.py", line 582, in dump_server_info
    pprint(get_model_worker_config(model))
  File "/Users/max/Documents/GitHub/Langchain-Chatchat/server/utils.py", line 349, in get_model_worker_config
    config.update(ONLINE_LLM_MODEL.get(model_name, {}).copy())
TypeError: unhashable type: 'list'

**环境信息 / Environment Information**
- langchain chatchat 版本: **v0.2.8**
- 向量库: **faiss**
- 操作系统: **mac os m3 max**
- Python 版本: **3.10.11**

**附加信息 / Additional Information**
当我使用 3.10.11 以上的 python 版本的话, 运行 pip install -r requirements.txt 也会报错

**Comment by zRzRzRzRzRzRzR** [comment]
mac没有测试，linux可以正常使用，更新到最新代码尝试

**Comment by JimJim2090** [comment]
> **问题描述 / Problem Description** 用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
> 
> 运行 python startup.py -a 以后出现以下报错:
> 
> Traceback (most recent call last): File "/Users/max/Documents/GitHub/Langchain-Chatchat/startup.py", line 880, in loop.run_until_complete(start_main_server()) File "/Users/max/.pyenv/versions/3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete return future.result() File "/Users/max/Documents/GitHub/Langchain-Chatchat/startup.py", line 647, in start_main_server dump_server_info(args=args) File "/Users/max/Documents/GitHub/Langchain-Chatchat/startup.py", line 582, in dump_server_info pprint(get_model_worker_config(model)) File "/Users/max/Documents/GitHub/Langchain-Chatchat/server/utils.py", line 349, in get_model_worker_config config.update(ONLINE_LLM_MODEL.get(model_name, {}).copy()) TypeError: unhashable type: 'list'
> 
> **环境信息 / Environment Information**
> 
> * langchain chatchat 版本: **v0.2.8**
> * 向量库: **faiss**
> * 操作系统: **mac os m3 max**
> * Python 版本: **3.10.11**
> 
> **附加信息 / Additional Information** 当我使用 3.10.11 以上的 python 版本的话, 运行 pip install -r requirements.txt 也会报错
注意，你可能在一个list后面加了一个逗号。我就犯了这个愚蠢的错误
LLM_MODELS = ["Qwen-1_8B-Chat", "zhipu-api", "openai-api"],
