### ISSUE TITLE
可以参考下exui整合 ExLlamaV2推理，增加chunk_size截断吗

### ISSUE THREAD

**Issue by xldistance** [chatchat-space/Langchain-Chatchat#2392]
exui地址：https://github.com/turboderp/exui
exui加载完模型后无论怎么回复显存都没有增加，回复速度超快，太令人惊讶了，要是chatchat也有这个能力就好了。chatchat加载Yi-34B-Chat-GPTQ 4bits后提问几次LLM对话就会爆显存，而且回复速度也很慢。我用exui加载Yi-34B-Chat-GPTQ 4bits怎么提问显存都不增加，长超提问显存都不变。
![QQ截图20231216132208](https://github.com/chatchat-space/Langchain-Chatchat/assets/29418474/2381ef56-1a84-41cf-a0c9-31b4aef42363)

**Comment by zRzRzRzRzRzRzR** [comment]
这是啥，确实没听过，之后参考一下，我们底座是fschat，是没有任何优化的

**Comment by xldistance** [comment]
> 这是啥，确实没听过，之后参考一下，我们底座是fschat，是没有任何优化的

我已经在exui里面整合了chatchat的知识库，完美了
