### ISSUE TITLE
OSError: [Errno 28] inotify watch limit reached

### ISSUE THREAD

**Issue by XYZ0288419** [chatchat-space/Langchain-Chatchat#2394]
**问题描述 / 
首次调用python startup.py -a后，成功显示web界面，但是跟模型对话超时，没有回复。

然后我重新进行初始化知识库和配置文件，再次调用python startup.py -a后，就出现了这个错误，并且在这之后一直有。

网上教程是用sudo增大参数，但是我没有管理员权限

请问有无其他方法解决问题

**Comment by hzg0601** [comment]
没有
