### ISSUE TITLE
[BUG] MAC m2 无法初始化数据库/ MAC m2 failed to initialize the database.

### ISSUE THREAD

**Issue by victoryangn** [chatchat-space/Langchain-Chatchat#2395]
**问题描述 / Problem Description**

MAC m2 failed to initialize the database.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'： Python init_database.py --recreate-vs
2. 问题出现 / Problem occurs:
2023-12-17 11:03:09,510 - faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2023-12-17 11:03:10,502 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
Batches: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.30it/s]
2023-12-17 11:03:13,307 - loader.py[line:64] - INFO: Loading faiss.
2023-12-17 11:03:13,327 - loader.py[line:66] - INFO: Successfully loaded faiss.

**预期的结果 / Expected Result**: 应该是要完成数据库初始化，并且向量化也完成，但是目前尝试多次都无法完成
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**： 一个晚上过去也没动静
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号: 最新版本
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipu api， 对话模式没问题
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base  / bge-large-en-v1.5 / bge-large-cn 全部都测试过了
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: sonama 14.0
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**Comment by zRzRzRzRzRzRzR** [comment]
没有办法复现，更新到新版本试试？
