### ISSUE TITLE
模型不能下载部署

### ISSUE THREAD

**Issue by dachn** [chatchat-space/Langchain-Chatchat#2397]
hi，我第一次安装部署本项目，根据安装说明：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46547576/96f3534f-8141-4fcb-8379-04ad8fd69554)

"将项目所需的模型下载至本地"，这里的模型是从github拉去到哪个路径下？又该如何部署？这里不慎很清楚，希望能详细说明安装步骤

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by victoryangn** [comment]
直接拉取到根目录就行，你可以在model_config.py里面设置模型路径
