### ISSUE TITLE
如何使用量化版本的ChatGLM呢？

### ISSUE THREAD

**Issue by danjuan-77** [chatchat-space/Langchain-Chatchat#2398]
想要使用
`model = AutoModel.from_pretrained(model_id, trust_remote_code=True).half().cuda()`
来调用量化版本的chatGLM

**Comment by zRzRzRzRzRzRzR** [comment]
不支持量化，你可以使用chatglm3官方仓库中的转openai的方式用openai的方法接入我们框架

**Comment by makeximu** [comment]
@zRzRzRzRzRzRzR 请问怎么用openai的方式接入呀，有文档吗？我没找到

**Comment by fuxiaoiii** [comment]
同问如何接入

**Comment by 541867329** [comment]
在startup.py 中将 args.load_8bit 更改为 True，即可实现量化int8模型，也能提升问答的速度

**Comment by 541867329** [comment]
> 同问如何接入



> @zRzRzRzRzRzRzR 请问怎么用openai的方式接入呀，有文档吗？我没找到

configs文件夹下的model_config.py，可以设置api，照着抄就行吧，应该是看chatglm3的api接口文档
