### ISSUE TITLE
运行embeddings/add_embedding_keywords.py报ImportError

### ISSUE THREAD

**Issue by raoly** [chatchat-space/Langchain-Chatchat#2399]
**问题描述 / Problem Description**
运行embeddings/add_embedding_keywords.py报ImportError: cannot import name 'MODEL_PATH' from 'configs' (/home/xxx/anaconda3/envs/env-langchain-chatchat/lib/python3.10/site-packages/configs/__init__.py)

**复现问题的步骤 / Steps to Reproduce**
1. 添加关键词
2. 执行embeddings/add_embedding_keywords.py
3. 问题出现

**预期的结果 / Expected Result**
希望正常执行关键词embeddings

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本:最新
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型：ChatGLM3-6B 
- 使用的 Embedding 模型：bge-large-zh
- 使用的向量库类型 faiss 
- 操作系统及版本 / linux: centos7
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by xuanyaoming** [comment]
确实有问题，我按照流程在ubuntu上安装configs目录下都没有__init__.py文件。需要自己补上再加上
```
from .basic_config import *
from .kb_config import *
from .model_config import *
from .prompt_config import *
from .server_config import *
```

**Comment by raoly** [comment]
卸载第三方configs模块后可以执行。
