### ISSUE TITLE
请问如何通过命令行 使用文档检索的能力啊

### ISSUE THREAD

**Issue by MAJIN1234** [chatchat-space/Langchain-Chatchat#2401]
请问如何通过命令行 使用文档检索的能力啊
目前我看知识检索都是在ui界面里面，我想直接通过命令行进行知识检索操作，请问如何低成本实现呀

**Comment by xjw00654** [comment]
不是有API么 0.0 本地curl一下 也算是伪CLI实现了吧 😂
