### ISSUE TITLE
[BUG] 使用在线大模型无法问答

### ISSUE THREAD

**Issue by TangKLSUSTC** [chatchat-space/Langchain-Chatchat#2402]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

使用在线大模型无法问答，问答选项中所有的模式都不行，LLM对话和知识库都无法问答

**复现问题的步骤 / Steps to Reproduce**
1. 配置设定使用zhipuai和相应的apikey，在gpt-academic中配置同样的信息可以使用，qianfan也无法使用
2. 执行 '对话框输入“hello”'，选项中选择“LLM对话”
3. 点击 '发送' 
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
预期应为LLM回答语句

**实际结果 / Actual Result**
实际什么都没有回复，命令行中报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipuai和qianfan
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：默认的 bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Windows 10 22H2
- Python 版本 / Python version:  Python 3.10.6
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
本地大模型ChatGLM3-6B-32k能够完美运行

**Comment by zRzRzRzRzRzRzR** [comment]
如果不是智谱官方的api，要自己转成openai api接入框架
