### ISSUE TITLE
[BUG] webui提问报错

### ISSUE THREAD

**Issue by DOVEEEEEEEEEEEEE** [chatchat-space/Langchain-Chatchat#2403]
使用经过P-tuning微调的本地ChatGLM2-6B模型，按照wiki步骤实现部署。输入PEFT_SHARE_BASE_WEIGHTS=true python startup.py -a后拉起webui，第一次提问没有回复，第二次提问web报错。
![1111](https://github.com/chatchat-space/Langchain-Chatchat/assets/147513587/e6740673-13a4-4751-9bcd-90544753e640)
![微信截图_20231218180626](https://github.com/chatchat-space/Langchain-Chatchat/assets/147513587/9c66732c-c93d-4402-92d7-ef854f124c17)

**Comment by zRzRzRzRzRzRzR** [comment]
更新一下web UI最新的代码，这个是streamlit 有问题

**Comment by MENGdecai** [comment]
> 更新一下web UI最新的代码，这个是streamlit 有问题

你好，我刚更新到最新版0.28但是还是有这个问题

**Comment by DOVEEEEEEEEEEEEE** [comment]
> 更新一下web UI最新的代码，这个是streamlit 有问题

更新了还是不行 现在还会提示APT通信错误
