### ISSUE TITLE
如何使用在线的Embedding模型呢

### ISSUE THREAD

**Issue by Pizzakk** [chatchat-space/Langchain-Chatchat#2404]
如题，并未在配置文件和wiki中找到配置在线的Embedding模型配置方式（除text-embedding-ada-002），求大佬解答

**Comment by liunux4odoo** [comment]
在 model_config.py 中设置 EMBEDDING_MODEL 为相应的在线 API 名称即可。
wiki 中已补充相关说明。

**Comment by goldSunshine** [comment]
同问，如何配置使用通义千问embedding在线api

**Comment by ZhiWeiLiuGitHub** [comment]
> 同问，如何配置使用通义千问embedding在线api

请问你的问题解决了吗？
