### ISSUE TITLE
qwen-14B-chat本地加载出现问题，模型是从huggingface手动下载下来的

### ISSUE THREAD

**Issue by wxzwxz131** [chatchat-space/Langchain-Chatchat#2407]
![1702953156063](https://github.com/chatchat-space/Langchain-Chatchat/assets/37330408/e4564408-382c-494a-9c18-6545121d6e79)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37330408/115e8f1d-51ac-4b06-86c2-babc98355c05)
报错：safetensors_rust.SafetensorError: Error while deserializing header: InvalidHeaderDeserialization

**Comment by zRzRzRzRzRzRzR** [comment]
降低transformers

**Comment by Genius-pig** [comment]
降低transformers没用啊，这个错还报
