### ISSUE TITLE
[BUG] 经常问题回答到一半就不回答，再问问题又能用，报错是 streamlit的key error，感觉像是多线程问题

### ISSUE THREAD

**Issue by H9990HH969** [chatchat-space/Langchain-Chatchat#2411]
求大佬解惑
问答或是知识库问答时，经常会出现第二次问答时，回答几个词就卡住的情况。
看后台报错，是session_state的key error，没有history这个key，而这个key是在chatbox里面用的。我进代码找了一圈（主要是streamlitchat-box里面）。发现赋值没问题，这个bug像是session_state突然就没值了（像是被什么初始化了），于是报错。但web页面上可以继续用，而且还能继续与大模型对话

我布在centos7上的，用的chatglm2-6b，在内网通过代理，代理到外网使用。
页面加载时，会有这个报错，但应该是个什么监控，应该影响不大吧
![1702974423703](https://github.com/chatchat-space/Langchain-Chatchat/assets/133352113/bdadb051-21cf-47d2-83f4-a7702b2af8a0)

**Comment by liunux4odoo** [comment]
这应该是 streamlit 的问题，参考[这里](https://github.com/streamlit/streamlit/issues/7290)
