### ISSUE TITLE
UI界面

### ISSUE THREAD

**Issue by lzl-hello** [chatchat-space/Langchain-Chatchat#2414]
请问自己部署了该项目后想修改ui界面更个性化一点，之前了解·过的前端是html，vue；在该项目中我好像没看到，请问应该阅读修改哪个源代码呢

**Comment by liunux4odoo** [comment]
请遵守 issue 规范，与 issue 无关的话题请移步讨论区或微信群。

**Comment by lzl-hello** [comment]
> 请遵守 issue 规范，与 issue 无关的话题请移步讨论区或微信群。

sorry,是个新人，我以为可以在这里问这种问题

**Comment by ai408** [comment]
> 请问自己部署了该项目后想修改ui界面更个性化一点，之前了解·过的前端是html，vue；在该项目中我好像没看到，请问应该阅读修改哪个源代码呢

之前分支是可以找到的。

**Comment by weigong1983** [comment]
目前项目的前端页面是webui_pages目录，基于streamlit开发的。
实际体验下来要进行个性化界面开发streamlit还是不够灵活。
我们也打算基于VUE+本项目的API接口（http://localhost:7861/ 可查看所有接口）重新开发一个界面。
