### ISSUE TITLE
如何使chatchat调用其他服务器部署好的模型的api

### ISSUE THREAD

**Issue by fuxiaoiii** [chatchat-space/Langchain-Chatchat#2417]
**问题描述 / Problem Description**
我在服务器A部署了ChatGLM3，部署并得到了openai-api；我想要在服务器B运行chatchat，而服务器B只运行embedding model，不运行LLM model，而是调用服务器A上ChatGLM3的openai-api。简单来说就是不希望chatchat直接控制LLM模型的运行，而是调用API来运行。
请问应该修改chatchat的哪个文件？

**附加信息 / Additional Information**
事实上我想在昇腾环境部署LLM model 和 chatchat，但是chatchat并没有做昇腾环境的适配，而我已经可以在昇腾环境运行LLM model并获取其调用的openai-api，所以我想要在昇腾环境上，用NPU（华为自研类似于GPU的处理器）运行LLM model，用CPU运行chatchat，从而达到融合的效果

**Comment by liunux4odoo** [comment]
你可以参考 openai-api 的配置方式，在 model_config.py 里增加一个模型配置项，指向服务器A的地址。
chatchat 与 fastchat保持完全兼容，由于不知道服务器A API的实现方式，不能保证兼容性。

**Comment by Huahhhhh** [comment]
> 你可以参考 openai-api 的配置方式，在 model_config.py 里增加一个模型配置项，指向服务器A的地址。 chatchat 与 fastchat保持完全兼容，由于不知道服务器A API的实现方式，不能保证兼容性。

可以详细讲一下openai-api 的配置方式吗，我的问题比较简单，小白不知道如何正确配置openai-api

**Comment by zRzRzRzRzRzRzR** [comment]
就会直接吧api 地址换成你的就行了呀

**Comment by Huahhhhh** [comment]
> 就会直接吧api 地址换成你的就行了呀

"openai-api": {
"model_name":gpt-4，
"api_base_url": "https://api.openai.com/v1",
"api_key": "sk-xxxxxxxxxxxxxxxxxxxxxxk",
"openai_proxy": "http://127.0.0.1:7890/",
},
是这样吗，配置了可用的apikey和梯子代理，但是进行知识库问答没有返回结果

**Comment by lamwin24** [comment]
大佬，问题解决了吗？

**Comment by fuxiaoiii** [comment]
> 大佬，问题解决了吗？

只知道是更换api，但是不知道哪个，还没有试

**Comment by zixiaotan21** [comment]
想问一下问题解决了吗，同遇到这个问题

**Comment by Maxliag** [comment]
> **问题描述 / Problem Description** 我在服务器A部署了ChatGLM3，部署并得到了openai-api；我想要在服务器B运行chatchat，而服务器B只运行embedding model，不运行LLM model，而是调用服务器A上ChatGLM3的openai-api。简单来说就是不希望chatchat直接控制LLM模型的运行，而是调用API来运行。 请问应该修改chatchat的哪个文件？
> 
> **附加信息 / Additional Information** 事实上我想在昇腾环境部署LLM model 和 chatchat，但是chatchat并没有做昇腾环境的适配，而我已经可以在昇腾环境运行LLM model并获取其调用的openai-api，所以我想要在昇腾环境上，用NPU（华为自研类似于GPU的处理器）运行LLM model，用CPU运行chatchat，从而达到融合的效果

请问在chatchat在昇腾上跑起来了吗
