### ISSUE TITLE
[BUG] 如何使用chatchat正确配置opanai LLM models

### ISSUE THREAD

**Issue by Huahhhhh** [chatchat-space/Langchain-Chatchat#2418]
**问题描述 / Problem Description**
目前chatchat的知识库问答是基于chatglm3的，我看到也支持openai于是进行了apikey和代理配置，我的更改如下

**复现问题的步骤 / Steps to Reproduce**
1. 在model_config.py 进行配置
 "openai-api": {
        "model_name": "gpt-4",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "sk-AXXXXXXXXXXe",
        "openai_proxy": "http://127.0.0.1:XXXX",
    },

**预期的结果 / Expected Result**
预期是在知识库问答时可以ChatGlm3/openai

**实际结果 / Actual Result**
点击：  OpenAI API Server: http://127.0.0.1:20000/v1返回404错误
点击： URL: http://0.0.0.0:8501 --知识库问答切换模型 openai-api--一直没有返回结果，在running

**环境信息 / Environment Information**
-阿里云服务器DSW 
- langchain-ChatGLM 版本/commit 号：v0.2.8 
- 是否使用 Docker 部署：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
没有返回结果是没有请求到，我在Linux 服务器上能请求到的

**Comment by blinkhor** [comment]
同样的问题，请问如何解决呢
