### ISSUE TITLE
在online_api中调用自己在openai微调的模型 出现找不到模型的情况

### ISSUE THREAD

**Issue by Fraudsterrrr** [chatchat-space/Langchain-Chatchat#2419]
**问题描述 / Problem Description**
在online_api中调用自己在openai微调的模型 出现找不到模型的情况。调用openai提供的gpt-3.5-turbo是没有问题的。
在本地调用两个模型接口地址和api_key都是一样的，只是model_name不同，为啥在本项目上不兼容了。

**复现问题的步骤 / Steps to Reproduce**

配置文件如下
    "openai-api": {
       "model_name": "ft:gpt-3.5-turbo-0613:myname::xxxxxxxxx",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "sk-xxxxxxxxxxxxxxxxxxxxxxk",
        "openai_proxy": "http://127.0.0.1:7890",
    },

报错信息：
INFO: message='OpenAI API response' path=https://api.openai.com/v1/chat/completions processing_ms=None request_id=xxxxxxxxxxxxxxxxxx response_code=404
INFO: error_code=model_not_found error_message='The model `ft:gpt-3.5-turbo-0613:myname::xxxxxxxxx` does not exist or you do not have access to it.' error_param=None error_type=invalid_request_error message='OpenAI API error received' stream_error=False
 - utils.py[line:24] - ERROR: The model `ft:gpt-3.5-turbo-0613:myname::xxxxxxxxx` does not exist or you do not have access to it.

openai.error.InvalidRequestError: The model `ft:gpt-3.5-turbo-0613:myname::xxxxxxxxx` does not exist or you do not have access to it.
ERROR: InvalidRequestError: Caught exception: The model `ft:gpt-3.5-turbo-0613:myname::xxxxxxxxx` does not exist or you do not have access to it.

**预期的结果 / Expected Result**
能够像gpt-3.5一样调用

**环境信息 / Environment Information**
- langchain-Chatchat = 0.2.8

感谢本项目各位的付出，如果能抽空解答，不胜感激。

**Comment by zRzRzRzRzRzRzR** [comment]
是的，因为走的是langchain，langchain根openai接口完全相同
