### ISSUE TITLE
[BUG] 自定义Agent功能函数添加Prompt模板

### ISSUE THREAD

**Issue by lyooyl** [chatchat-space/Langchain-Chatchat#2424]
**问题描述 / Problem Description**
chatchat框架中，仅简单的agent函数（如求平方和、数据库查询）可以实现，但带有Prompt模板的怎么传入进去呢？参考天气查询，感觉很复杂，请问有没有简单易懂的demo示例？

**复现问题的步骤 / Steps to Reproduce**，同步修改相关文件，不知道如何带入prompt模板。

**预期的结果 / Expected Result**
按照自定义模板，构建出含有llm、prompt的agent的LangChain对象。能够计算.run(query)结果。

**实际结果 / Actual Result**
不知道如何带入prompt模板。

**环境信息 / Environment Information**
chatchat v0.28

**Comment by lyooyl** [comment]
类似[这种](https://www.langchain.com.cn/modules/agents/tools/multi_input_tool)，但是prompt模板怎么写入呢？
![多输入](https://github.com/chatchat-space/Langchain-Chatchat/assets/69505403/58fb35af-2e86-4af0-95b0-49876c8ac2bd)

**Comment by zRzRzRzRzRzRzR** [comment]
0.3.x后会有
