### ISSUE TITLE
一种基于知识库多轮对话优化的思考

### ISSUE THREAD

**Issue by shujun1992** [chatchat-space/Langchain-Chatchat#2425]
优化思路
1）**把指令当成system角色 放在最前面**，当前多轮会导致最后一次提示语的指令处于整个多轮提示语的中间，大模型理解效果不好
2）可以考虑把多轮的问题拼接起来，让大模型以最新的问题为主，给出准确意图，再进行知识库的搜索(ps：这样会导致整个链路拉长)，**粗暴点，直接把多轮的问题拼接起来，带入知识库进行搜索**

提示语： '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，'
            '不允许在答案中添加编造成分，答案请使用中文。 </指令>\n'
            '<已知信息>{{ context }}</已知信息>\n'
          
**我试了下，chatglm3-6b为基座，效果比现在的模式要好一点** 
            
 代码变更：
##

[server]   server/chat/utils.py
            
            def to_msg_template(self, is_raw=True) -> ChatMessagePromptTemplate:
                    role_maps = {
                        "ai": "assistant",
                        "human": "user",
                        "system": "system"
                    }
                    role = role_maps.get(self.role, self.role)
                    if is_raw: # 当前默认历史消息都是没有input_variable的文本。
                        content = "{% raw %}" + self.content + "{% endraw %}"
                    else:
                        content = self.content
            
                    return ChatMessagePromptTemplate.from_template(
                        content,
                        "jinja2",
                        role=role,
                    )

##

[server]   server/chat/knowledge_base_chat.py
##
      prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
      system_prompt = History(role="system", content=prompt_template).to_msg_template(False)
      input_msg = History(role="user", content=query).to_msg_template(False)
      chat_prompt = ChatPromptTemplate.from_messages(
                  [system_prompt ]  +  [i.to_msg_template() for i in history] + [input_msg])
      
      chain = LLMChain(prompt=chat_prompt, llm=model)
     
      task = asyncio.create_task(wrap_done(
                  chain.acall({"context": context,}),
                  callback.done),
              )

##

**Comment by zRzRzRzRzRzRzR** [comment]
但是不是所有模型都有system_prompt的

**Comment by lurenyi4** [comment]
感谢您的思路，我也在用glm，试试看多轮对话的效果提升如何

**Comment by sevenandseven** [comment]
> 优化思路
> 1）**把指令当成system角色 放在最前面**，当前多轮会导致最后一次提示语的指令处于整个多轮提示语的中间，大模型理解效果不好
> 2）可以考虑把多轮的问题拼接起来，让大模型以最新的问题为主，给出准确意图，再进行知识库的搜索(ps：这样会导致整个链路拉长)，**粗暴点，直接把多轮的问题拼接起来，带入知识库进行搜索**

你好，想问下如果把多轮问题带入到知识库进行搜索，不会导致出现很多重复信息吗？
