### ISSUE TITLE
[FEATURE] 添加pdf文档到知识库，非常耗时，请问应该怎么解决

### ISSUE THREAD

**Issue by 278038551** [chatchat-space/Langchain-Chatchat#2426]
添加pdf文档到知识库，非常耗时，10个文件用了1个小时

翻了下大家提的相关问题，看到2个解决方案：
（1）在后台进行向量化
（2）使用GPU

但是针对这2个解决方案，没有具体的实现方式和操作步骤
**哪位大神可以提供一下具体方案的操作步骤？**

**Comment by zRzRzRzRzRzRzR** [comment]
paddle有GPU版本，就能解决问题2 问题1就是在程序后台吧内容丢到knowledgebase文件夹执行python init就行

**Comment by 278038551** [comment]
> 问题1就是在程序后台吧内容丢到knowledgebase文件夹执行python init就行

请问具体操作是：把内容放到到knowledge_base/知识库名称/content目录下，然后在Langchain代码库目录下执行python init_database.py --recreate-vs 这个命令吗？

**Comment by 278038551** [comment]
感谢您的回复，还想向您再请教个问题：
通过后台把pdf文件上传到knowledge_base，python init数据库之后，有没有后台的方式对文件进行向量化？
现在有800多个文件，保存到数据库之后，通过页面添加到向量库比较慢
&nbsp;


278038551
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月21日(星期四) 中午12:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] [FEATURE] 添加pdf文档到知识库，非常耗时，请问应该怎么解决 (Issue #2426)





 
paddle有GPU版本，就能解决问题2 问题1就是在程序后台吧内容丢到knowledgebase文件夹执行python init就行
