### ISSUE TITLE
对单一文件的问答功能

### ISSUE THREAD

**Issue by SSTato** [chatchat-space/Langchain-Chatchat#2429]
可不可以实现对某个文件的所有内容进行提问。
例如我上传了一个文档，我希望知道这个文档的大概内容是什么，或者生成这个文档的关键词之类的。
我的想法是在将文档向量化后，可以选择将某个文档的所有内容当成已知信息进行提问。
可以有这个增强功能吗

**Comment by liunux4odoo** [comment]
在文件对话模式里，把匹配条数设为一个较大的值不就可以了？有其他要求还可以使用自定义的prompt模板。
