### ISSUE TITLE
[BUG] 数据加载不进来

### ISSUE THREAD

**Issue by potong** [chatchat-space/Langchain-Chatchat#243]
![image](https://user-images.githubusercontent.com/10555409/236411329-64d8892a-8d0d-4b65-b0a6-68e60bc81485.png)

使用的.txt格式，utf-8编码，报以下错误

![Uploading image.png…]()

**Comment by potong** [comment]
![image](https://user-images.githubusercontent.com/10555409/236412889-62913756-6fb6-44df-953b-aaeaeb6fc879.png)

**Comment by potong** [comment]
使用的数据集：
![image](https://user-images.githubusercontent.com/10555409/236413150-d778128f-ebc2-4603-a49d-73ea318a93bc.png)

测试代码：
![image](https://user-images.githubusercontent.com/10555409/236413347-41805f16-8d99-415f-92f7-37f4f48de7e1.png)

**Comment by potong** [comment]
希望大佬帮忙解决下，谢谢😊

**Comment by AlexRainHao** [comment]
没有复现, 我在 langchain==0.0.146 上是可以的

**Comment by potong** [comment]
@AlexRainHao 我用的也是 langchain==0.0.146，但跑不通，安装包版本都是以requirements.txt下的

**Comment by AlexRainHao** [comment]
> @AlexRainHao 我用的也是 langchain==0.0.146，但跑不通，安装包版本都是以requirements.txt下的

那挺奇怪了, 我这边是 python3.10, linux 上运行, 试着检查下 `1.txt` 的编码格式呢

按照你给的代码, 我可以正确输出

![截屏2023-05-05 17 32 37](https://user-images.githubusercontent.com/39720357/236423992-acc51875-aed4-4d9f-8eb4-ef95ac8cb6c9.png)

**Comment by potong** [comment]
@AlexRainHao 好的，我再试试，非常感谢
