### ISSUE TITLE
[FEATURE] 通过后台添加pdf文档之后，请问如何完成向量化

### ISSUE THREAD

**Issue by 278038551** [chatchat-space/Langchain-Chatchat#2430]
把pdf文件上传到knowledge_base之后，再执行init数据库操作，文件就存储到数据库中了。

如何更加快捷的完成向量化？使问答时能使用新加入的文件？

**麻烦各个有经验的大神帮忙解答一下**

**Comment by liunux4odoo** [comment]
对于单个文件，知识库管理界面有入库按钮
