### ISSUE TITLE
[BUG] 建立向量库时，可以解析.docx文档，但是无法解析.doc文档

### ISSUE THREAD

**Issue by liudonglei** [chatchat-space/Langchain-Chatchat#2431]
**问题描述 / Problem Description**
webui启动后，上传word文件，建立向量库时，可以解析.docx文档，但是无法解析.doc文档

**复现问题的步骤 / Steps to Reproduce**
页面中，向知识库添加文件，.doc格式

**预期的结果 / Expected Result**

**实际结果 / Actual Result**
报错：
migrate.py[line:80] - ERROR: ValueError: 暂未支持的文件格式 /DDD/langchain1/knowledge_base/GZ-all/content/***.doc，已跳过

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-1.5B, etc.):
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  centos
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liudonglei** [comment]
经过排查发现，server/knowledge_base\utils.py 行106 有笔误
"UnstructuredWordDocumentLoader": ['.docx', 'doc'],
望修复

**Comment by liunux4odoo** [comment]
Duplicate of #2326 
Duplicate of #2382
