### ISSUE TITLE
[BUG] 上传知识库报错

### ISSUE THREAD

**Issue by cl165** [chatchat-space/Langchain-Chatchat#2432]
**问题描述 / Problem Description**
上传知识库并添加到向量库时总是卡主，等待很长时间，然后直接超时：post /knowledge_base/update_docs: timed out

发生问题时的详细日志：
2023-12-21 16:49:20,964 - utils.py[line:286] - INFO: RapidOCRPDFLoader used for /home/ubuntu/Langchain-Chatchat/knowledge_base/测试/content/6.pdf
RapidOCRPDFLoader context page index: 2: 100%|████████████████████████████████████████████████| 3/3 [00:00<00:00, 78.19it/s]Unknown encoding . Plugins found: ['tiktoken_ext.openai_public']
文档切分示例：page_content='车载音乐对驾驶员情绪状态和事故倾向性的影响\n\n马锦飞①\n\n高\n\n远\n\n邱\n\n欢\n\n董\n\n悦\n\n琚芳艳\n\n【摘要】 目的\n\n考察车载音乐对驾驶员情绪和事故倾向性的影响。方法\n\n随机选取 540 名驾驶员进行车载音乐收听情况问\n\n卷施测。结果\n\n77． 2% 的驾驶员频繁收听车载音乐( χ\n\n2 = 17． 286，df = 4，P ＜ 0． 001) ; 38． 5% 的驾驶员认为车载音乐能够提高警\n\n觉( χ' metadata={'source': '/home/ubuntu/Langchain-Chatchat/knowledge_base/测试/content/6.pdf'}
2023-12-21 16:51:56,937 - _base_client.py[line:952] - INFO: Retrying request to /embeddings in 0.938555 seconds

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新版本0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：openai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text-embedding-ada-002
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： fpg_vector
- 操作系统及版本 / Operating system and version: ubuntu22
- Python 版本 / Python version: python3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by surpasslll** [comment]
在国内可以直接使用text-embedding-ada-002嘛？不是需要用到open ai的key，我理解需要配置proxy才能使用

**Comment by cl165** [comment]
> 在国内可以直接使用text-embedding-ada-002嘛？不是需要用到open ai的key，我理解需要配置proxy才能使用

对的，配置了
