### ISSUE TITLE
希望在对话过程中加入图片输出，即llm可以按照要求在对话框中插入图片

### ISSUE THREAD

**Issue by SongWWWWWW** [chatchat-space/Langchain-Chatchat#2434]
希望可以在对话过程中加入图片输出的功能

**Comment by muzhi1991** [comment]
也有类似的需求，希望对文档里面图片可以通过md的链接 方式是直接输出到对话界面上，给的示例里面其实也很多图片。现在好像是图片的内容解析为文本加到检索里面了，只有文本的输出。

**Comment by liunux4odoo** [comment]
> 也有类似的需求，希望对文档里面图片可以通过md的链接 方式是直接输出到对话界面上，给的示例里面其实也很多图片。现在好像是图片的内容解析为文本加到检索里面了，只有文本的输出。

这个是 langchain md 文档加载器的原因，所有链接都被过滤掉了。如果确实需要，可能需要自己写一个文档加载器

**Comment by muzhi1991** [comment]
> > 也有类似的需求，希望对文档里面图片可以通过md的链接 方式是直接输出到对话界面上，给的示例里面其实也很多图片。现在好像是图片的内容解析为文本加到检索里面了，只有文本的输出。
> 
> 这个是 langchain md 文档加载器的原因，所有链接都被过滤掉了。如果确实需要，可能需要自己写一个文档加载器

感谢指导，看了一下langchain的代码的确是他里面的`UnstructuredMarkdownLoader`把图片的链接全部过滤了，他用的unstructured那个库，这个库的逻辑是先把md转化为htlm再用用了lxml这个库来解析htlm文档，问题就出在解析htlm文档这边（`HTMLDocument`类的`_parse_tag`）。可以加一下就行解析的图片路径保存到metadata里面，后面在提交给llm的时候再处理到文本里面。

**Comment by SwordHG** [comment]
> > 也有类似的需求，希望对文档里面图片可以通过md的链接 方式是直接输出到对话界面上，给的示例里面其实也很多图片。现在好像是图片的内容解析为文本加到检索里面了，只有文本的输出。
> 
> 这个是 langchain md 文档加载器的原因，所有链接都被过滤掉了。如果确实需要，可能需要自己写一个文档加载器

把链接直接放在文本里，靠llm来输出链接吗？llm输出链接如何稳定呢？

**Comment by LawlightXY** [comment]
@SwordHG 请问关于链接的输出有思路了吗？

**Comment by SongWWWWWW** [comment]
> @SwordHG 请问关于链接的输出有思路了吗？

我是以本地机器的路径来进行显示的，具体是通过匹配路径的方式，利用下面的调用方式进行图片输出, 不过这是agent方面的图片输出，具体检索文档的图片输出暂时还没有考虑


> image = Image.open(image_path)
> st.image(image, caption=" LLM's Image", use_column_width=True)
