### ISSUE TITLE
[BUG] chatglm3-6b开启8bit量化后报OoM但仍有可用显存

### ISSUE THREAD

**Issue by ChiNoel-osu** [chatchat-space/Langchain-Chatchat#2437]
**问题描述 / Problem Description**
模型是chatglm3-6b，跑在GPU上。Embedding是m3e-base，跑在CPU上。
显卡是RTX 4060 8G
load_8bit = False 时系统会分配运行内存给显卡，加载完成开启WebUI后专用+共享总占用显存12G多，可以正常进行LLM对话。
load_8bit = True  时加载会报以下错误：
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 4.44 GiB is free. Of the allocated memory 2.49 GiB is allocated by PyTorch, and 6.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
还有4.44GiB它咋不用呢🤔任务管理器也能看到只用了一半显存然后就突然没了
还是说我理解错了这个参数的含义😥

**复现问题的步骤 / Steps to Reproduce**
1. 设置加载chatglm3-6b `LLM_MODELS = ["chatglm3-6b"]`
2. 在`startup.py`中设置`load_8bit = True`
3. `python .\startup.py -a`
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
模型以8bit加载，并使用<12G的显存。

**实际结果 / Actual Result**
其中一个worker会报错，stdout中大概率不会显示：
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacty of 8.00 GiB of which 4.44 GiB is free. Of the allocated memory 2.49 GiB is allocated by PyTorch, and 6.49 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：c1a32d9f1ad60314eeaa4923b63e6ce4e434eeb5
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss-cpu
- 操作系统及版本 / Operating system and version: Windows 10 Pro 22H2
- Python 版本 / Python version: Python 3.11.7 venv
- 其他相关环境信息 / Other relevant environment information: None

**附加信息 / Additional Information**
Nope

**Comment by zRzRzRzRzRzRzR** [comment]
好像chatglm3不支持8bit吧

**Comment by ChiNoel-osu** [comment]
了解
