### ISSUE TITLE
请问为什么在加载Qwen-14B-Chat-Int8的时候会报错？

### ISSUE THREAD

**Issue by 123xpf** [chatchat-space/Langchain-Chatchat#2438]
![微信图片_20231221221415](https://github.com/chatchat-space/Langchain-Chatchat/assets/103637580/6c1721d5-f688-4bfb-8d49-1dc6588f3141)

**Comment by qiyueyuanwei** [comment]
你好，请问这个问题解决了吗，我也遇到这个问题了/
