### ISSUE TITLE
不能读取pdf

### ISSUE THREAD

**Issue by sssssshf** [chatchat-space/Langchain-Chatchat#244]
![image](https://user-images.githubusercontent.com/68574922/236425351-5982d6a7-8161-41d8-ab33-d3faaa6f4239.png)

**Comment by imClumsyPanda** [comment]
请问是webui还是cli_demo

**Comment by sssssshf** [comment]
> 请问是webui还是cli_demo

cli_demo.py.我是linux系统 ubuntu20.04,pytorch2.0.

**Comment by sssssshf** [comment]
> 请问是webui还是cli_demo

这是模型路径 下载到本地的模型
![image](https://user-images.githubusercontent.com/68574922/236589985-cb6b23d8-f5d1-4bc9-8e63-67b5a2c1bdc8.png)

**Comment by sssssshf** [comment]
> 请问是webui还是cli_demo

已解决，
![image](https://user-images.githubusercontent.com/68574922/236590429-ff395769-4715-46e3-89ec-7c4be8cead0d.png)
这样这样没问题，从终端输入文件路径可以读取。
![image](https://user-images.githubusercontent.com/68574922/236590463-8879e29c-81ed-4936-bb19-7ddac0a9a591.png)
在里面写入文件路径会报错

**Comment by sssssshf** [comment]
> 请问是webui还是cli_demo

已解决，请问传入的pdf文件大小是不是有限制？

**Comment by imClumsyPanda** [comment]
没有设置大小限制，但是因为目前处理逻辑是首先按照句号、问号、叹号等中文句子终止符进行分句，所以建议句子长度不要太长，建议选用中文文件

**Comment by sssssshf** [comment]
> 没有设置大小限制，但是因为目前处理逻辑是首先按照句号、问号、叹号等中文句子终止符进行分句，所以建议句子长度不要太长，建议选用中文文件

我传了一本关于c++的书这种 会显示 上传文件失败。
![image](https://user-images.githubusercontent.com/68574922/236602966-191f61e1-3bf5-48e5-8322-8ec210bac10e.png)

**Comment by HuangZhenyang** [comment]
> > 没有设置大小限制，但是因为目前处理逻辑是首先按照句号、问号、叹号等中文句子终止符进行分句，所以建议句子长度不要太长，建议选用中文文件
> 
> 我传了一本关于c++的书这种 会显示 上传文件失败。 ![image](https://user-images.githubusercontent.com/68574922/236602966-191f61e1-3bf5-48e5-8322-8ec210bac10e.png)

我也遇到了相同的问题，请问解决了吗~
