### ISSUE TITLE
agent调用工具报错，未终止，循环调用Open ai

### ISSUE THREAD

**Issue by HappyWHoo** [chatchat-space/Langchain-Chatchat#2440]
我并没有将整个chatchat项目下载下来并运行，而是复制了项目中的一些代码文件自己运行。

在调用天气工具的时候，程序多次调用open ai，导致报错。

调用这块的代码是这样的：
-----------------------------------------------------------------
callback = CustomAsyncIteratorCallbackHandler()

llm = ChatOpenAI(
    model="gpt-3.5-turbo-16k",
    streaming=True,
    temperature=0.2,
    callbacks=[callback],
)

model_container.MODEL = llm

prompt_template = get_prompt_template("agent_chat", "default")
prompt_template_agent = CustomPromptTemplate(
    template=prompt_template,
    tools=tools,
    input_variables=["input", "intermediate_steps", "history"]
)

output_parser = CustomOutputParser()

message_history = RedisChatMessageHistory(
    url="redis://localhost:6379/0", ttl=600, session_id="999"
)

memory = ConversationBufferMemory(
    k=20, memory_key="history", chat_memory=message_history, input_key='input', output_key="output",
    return_messages=True
)

llm_chain = LLMChain(llm=llm, prompt=prompt_template_agent)

agent = LLMSingleActionAgent(
    llm_chain=llm_chain,
    output_parser=output_parser,
    stop=["\nObservation:", "Observation"],
    allowed_tools=tool_names,
)
agent_executor = AgentExecutor.from_agent_and_tools(agent=agent,
                                                    tools=tools,
                                                    verbose=True,
                                                    memory=memory,
                                                    )

agent_executor.run("广州今晚热吗？", callbacks=[callback])
-------------------------------------------------------------------------------

控制台错误是这样的：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53430154/c450e25e-4f2d-4c15-ac94-34421c0e663f)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53430154/7fad392e-d415-48ed-95b6-74c09c3d8e7a)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/53430154/f71c4ecf-f251-4d1f-9732-6a36591cbb07)

是俺哪块少东西了吗？ agent一直在重复运行没有终止。而且我这问题应该没毛病啊，不必要非要将市和区都提出来问啊

求助求助

**Comment by zRzRzRzRzRzRzR** [comment]
你是用OpenAI做的吗

**Comment by HappyWHoo** [comment]
> 你是用OpenAI做的吗

用的是gpt-3.5-turbo-16k

**Comment by zRzRzRzRzRzRzR** [comment]
那估计能力不够，这个工具设计有点问题，对大模型要求有点高，我用4才能成功

**Comment by HappyWHoo** [comment]
所以，在工具里涉及到要使用chain对工具的入参进行校验，只有4才能成功是吗？ 我是想实现功能：针对某个工具，如果用户的问题中不存在工具要求录入的参数，就提醒用户提供入参。

**Comment by zRzRzRzRzRzRzR** [comment]
是的，只有4 我们会在3.x重写这些功能
