### ISSUE TITLE
[BUG]从elasticsearch 向量库删除某一个文档时，文档关联的知识库在es中并没有删除

### ISSUE THREAD

**Issue by wvivi2023** [chatchat-space/Langchain-Chatchat#2446]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 增加一个docx文档1 到知识库
2. 点击“添加文档到知识库”，验证已经向量化成功，可以正常问答。
3. 在知识库库里选择 刚添加的docx文档1 文件
4. 点击”从向量库删除“

**预期的结果 / Expected Result**
对docx文档1里的内容不能正常问答

**实际结果 / Actual Result**
1）对docx文档1里的内容仍可以正常问答
2）通过Multi elasticsearch Head 插件连接到es，选择对应的index，仍可以看到有docx文档1关联的向量和文字块在数据库里

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）：N
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： elasticseach
- 操作系统及版本 / Operating system and version:linux
- Python 版本 / Python version:3.10.12

**Comment by alanlaye617** [comment]
应该是从es index搜索要删除的id时，过滤条件中的source有问题，具体是在es_kb_service.py的do_delete_doc.py。

删除一个叫test.txt时query中的source是 '/root/workspace/projects/Langchain-Chatchat/knowledge_base/es-test/content/test.txt'，而index里对应字段保存的却是’test.txt‘。所以搜索出来要删除的doc_id是个空列表。

**Comment by AIdrinkhotWater** [comment]
0.2.10版本，同样也遇到该问题，向量数据库使用的es和milvus，两个数据库都不能从知识库管理页面点击“从向量库中删除”按钮对单个文件的向量删除成功
