### ISSUE TITLE
文件问答中请允许设置问答语言，比如英文

### ISSUE THREAD

**Issue by crazyn2** [chatchat-space/Langchain-Chatchat#2447]
**功能描述 / Feature Description**
文件问答中请允许设置问答语言，比如英文
**解决的问题 / Problem Solved**
英语文献，用中文回答存在翻译的问题，本人更喜欢用文献语言回答

**实现建议 / Implementation Suggestions**
可以考虑设置里面的中文prompt提供英语选项

**替代方案 / Alternative Solutions**
曾考虑过替换模型为其他模型

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有考虑多语言，你可以通过提示词指定语言
