### ISSUE TITLE
直接调用部署的openai接口出错

### ISSUE THREAD

**Issue by ConleyKong** [chatchat-space/Langchain-Chatchat#2449]
**问题描述 / Problem Description**
通过api中的chat/fastchat接口调用openai的接口出错，无消息返回
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15335349/4c9ce835-3a51-4a92-9a73-cba6fae2e952)

**复现问题的步骤 / Steps to Reproduce**
api.chat_fastchat(
            [{'role':'user','content':prompt},],        
          )

**预期的结果 / Expected Result**
需要正确返回大模型给出的response

**Comment by liunux4odoo** [comment]
/chat/fast_chat 是内部测试用的，项目中未实际使用。该接口与openai>1.0的版本不兼容

**Comment by zhipeng9802** [comment]
需要使用openai更新后的`AsyncOpenAI`

```python
from openai import AsyncOpenAI

client = AsyncOpenAI()

async def main():
    stream = await client.chat.completions.create(
        model="gpt-4",
        messages=[{"role": "user", "content": "Say this is a test"}],
        stream=True,
    )
    async for chunk in stream:
        print(chunk.choices[0].delta.content or "", end="")


asyncio.run(main())
```

e.g.

```python
...
from openai import AsyncOpenAI
...

async def openai_chat(msg: OpenAiChatMsgIn):
    config = get_model_worker_config(msg.model)
    client = AsyncOpenAI(
        api_key = config.get("api_key", "EMPTY"),
        base_url = config.get("api_base_url", fschat_openai_api_address()),
    )
    print(f"{client.api_key=}")
    print(f"{client.base_url=}")
    print(msg)

    async def get_response(msg):
        data = msg.dict()

        try:
            response = await client.chat.completions.create(**data)
            if msg.stream:
                async for data in response:
                    if choices := data.choices:
                        if chunk := choices[0].get("delta", {}).get("content"):
                            print(chunk, end="", flush=True)
                            yield chunk
            else:
                if response.choices:
                    answer = response.choices[0].message.content
                    print(answer)
                    yield(answer)
        except Exception as e:
            msg = f"获取ChatCompletion时出错：{e}"
            logger.error(f'{e.__class__.__name__}: {msg}',
                         exc_info=e if log_verbose else None)
```

更多信息参考：[openai-python](https://github.com/openai/openai-python)

**Comment by lamwin24** [comment]
你好，请问你是怎么调用本地部署的openai接口的？可以加QQ联系下吗，大佬

**Comment by zhipeng9802** [comment]
> 你好，请问你是怎么调用本地部署的openai接口的？可以加QQ联系下吗，大佬

本地部署的openai接口？我没理解是什么意思。

1.不过调用过程的话你可以仿照chat/fastchat这个接口里的调用方式，只需要修改AsyncOpenAI的base_url参数，指定调用的接口地址即可
2.也可以参考get_httpx_client()这个方法获取client后调用指定服务

上述调用接口的方法不知道是否涵盖了你描述的问题

**Comment by lamwin24** [comment]
> > 你好，请问你是怎么调用本地部署的openai接口的？可以加QQ联系下吗，大佬
> 
> 本地部署的openai接口？我没理解是什么意思。
> 
> 1.不过调用过程的话你可以仿照chat/fastchat这个接口里的调用方式，只需要修改AsyncOpenAI的base_url参数，指定调用的接口地址即可 2.也可以参考get_httpx_client()这个方法获取client后调用指定服务
> 
> 上述调用接口的方法不知道是否涵盖了你描述的问题

就是，我在服务器A部署了大模型，并用fastapi封装接口。现在，我想在服务器B部署ChatChat项目，怎么才能调用服务器A大模型接口呢？需要怎么修改model_config.py文件呢？

**Comment by zhipeng9802** [comment]
> > > 你好，请问你是怎么调用本地部署的openai接口的？可以加QQ联系下吗，大佬
> > 
> > 
> > 本地部署的openai接口？我没理解是什么意思。
> > 1.不过调用过程的话你可以仿照chat/fastchat这个接口里的调用方式，只需要修改AsyncOpenAI的base_url参数，指定调用的接口地址即可 2.也可以参考get_httpx_client()这个方法获取client后调用指定服务
> > 上述调用接口的方法不知道是否涵盖了你描述的问题
> 
> 就是，我在服务器A部署了大模型，并用fastapi封装接口。现在，我想在服务器B部署ChatChat项目，怎么才能调用服务器A大模型接口呢？需要怎么修改model_config.py文件呢？

是的，需要修改model_config.py配置文件及多个其他py文件，你可以参考qianfan.py中的代码逻辑，并填充一些针对性的处理逻辑，流式的话可能需要你A服务器的接口符合SSE协议
