### ISSUE TITLE
预处理知识库文件问题

### ISSUE THREAD

**Issue by lixianli1987** [chatchat-space/Langchain-Chatchat#2450]
官网的说明地址：https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#%E9%A2%84%E5%A4%84%E7%90%86%E7%9F%A5%E8%AF%86%E5%BA%93%E6%96%87%E4%BB%B6

我的原文设置如下，一个知识库中只存放一个txt文档
`

省会城市包括：石家庄、沈阳、哈尔滨、天津、兰州、长春、西宁、郑州、南京、武汉、长沙、杭州、南昌、广州、昆明、福州、台北、海口、太原、成都、西安、贵阳、合肥

职务：集团经理；差旅费补助标准：
1.生活补助标准：北京、上海、广州、深圳：160元/天，省会城市：70元/天，其他城市：60元/天；
2.市内交通补助标准：北京、上海、广州、深圳：60元/天，省会城市：60元/天，其他城市：40元/天；
3.住宿补助标准：北京、上海、广州、深圳：600元/天，省会城市：500元/天，其他城市：400元/天。

职务：总部二级部门部长；差旅费补助标准：
1.生活补助标准：北京、上海、广州、深圳：160元/天，省会城市：70元/天，其他城市：60元/天；
2.市内交通补助标准：北京、上海、广州、深圳：60元/天，省会城市：60元/天，其他城市：40元/天；
3.住宿补助标准：北京、上海、广州、深圳：350元/天，省会城市：300元/天，其他城市：250元/天。

职务：工程师；差旅费补助标准：
1.生活补助标准：北京、上海、广州、深圳：160元/天，省会城市：70元/天，其他城市：60元/天；
2.市内交通补助标准：北京、上海、广州、深圳：60元/天，省会城市：60元/天，其他城市：40元/天；
3.住宿补助标准：北京、上海、广州、深圳：280元/天，省会城市：220元/天，其他城市：170元/天。
`
我的检索的内容
`
我的职务是工程师，请问我的差旅费补助标准
`
检索出来的内容如下，我这里只有一个txt文档，不知道为啥检索出来的三段内容(top_k = 3)如下：
第一段内容如下：
`
3.住宿补助标准：北京、上海、广州、深圳：350元/天，省会城市：300元/天，其他城市：250元/天。
`
第二段内容如下：
`
职务：工程师；差旅费补助标准：
1.生活补助标准：北京、上海、广州、深圳：80元/天，省会城市：70元/天，其他城市：60元/天；
2.市内交通补助标准：北京、上海、广州、深圳：60元/天，省会城市：60元/天，其他城市：40元/天；
3.住宿补助标准：北京、上海、广州、深圳：600元/天，省会城市：500元/天，其他城市：400元/天。
`
第三段内容如下：
`职务：总部二级部门部长；差旅费补助标准：
职务：总部二级部门部长；差旅费补助标准：
1.生活补助标准：北京、上海、广州、深圳：80元/天，省会城市：70元/天，其他城市：60元/天；
2.市内交通补助标准：北京、上海、广州、深圳：60元/天，省会城市：60元/天，其他城市：40元/天；
`
检索出来的答案是：
`
1. 生活补助标准：北京、上海、广州、深圳：80元/天，省会城市：70元/天，其他城市：60元/天；
2. 市内交通补助标准：北京、上海、广州、深圳：60元/天，省会城市：60元/天，其他城市：40元/天；
3. 住宿补助标准：北京、上海、广州、深圳：350元/天，省会城市：300元/天，其他城市：250元/天。
`
请问：文档是如何切割的，官网有文档介绍么？

**Comment by zRzRzRzRzRzRzR** [comment]
wiki中有自动切割文档的方案，也可以直接定制

**Comment by lixianli1987** [comment]
> wiki中有自动切割文档的方案，也可以直接定制

你好，我看的是 https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5#%E9%A2%84%E5%A4%84%E7%90%86%E7%9F%A5%E8%AF%86%E5%BA%93%E6%96%87%E4%BB%B6
没太明白 自动切割文档 与 直接定制切割方案呢
