### ISSUE TITLE
英文版bge-large-en-v1.5 embeddings 向量无法加载

### ISSUE THREAD

**Issue by fashion-john** [chatchat-space/Langchain-Chatchat#2456]
会报错：faiss_cache.py[line:80] - INFO: loading vector store in 'samples/vector_store/bge-large-en-v1.5' from disk. AttributeError: 'NoneType' object has no attribute 'conjugate'

**Comment by Aye10032** [comment]
同样的问题，已经设置了使用本地模型，并且修改了配置文件，出现报错kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by ShinyWey** [comment]
一样, 怪的一匹, 上传docx可以正常向量化, 上传一个txt和你的报错一样, 换了其他embedding模型解决了
