### ISSUE TITLE
【帮忙求助】我想把本地知识库中的LLMChain 改为ConversationalRetrievalChain.from_llm 并传入chat_history，回调就出问题了。

### ISSUE THREAD

**Issue by pengkang1991** [chatchat-space/Langchain-Chatchat#2462]
`chain = ConversationalRetrievalChain.from_llm(
            llm=model,
            chain_type="stuff",
            retriever=retriever,
            #memory=memory,
            return_source_documents=True,
            return_generated_question=True,
            combine_docs_chain_kwargs={'prompt': prompt},
            # 独立llM
            condense_question_llm=model,
            verbose=True
        )
        print(chat_history)
        if len(chat_history) > 0:
            botHistory = [(i[0], i[1]) for i in chat_history]
        # Begin a task that runs in the background.
        task = asyncio.create_task(wrap_done(
            chain.acall({"question": query, "chat_history":botHistory}),
            callback.queue),
        )

        source_documents = []
        for inum, doc in enumerate(docs):
            filename = doc.metadata.get("source")
            parameters = urlencode({"knowledge_base_name": knowledge_base_name, "file_name": filename})
            base_url = request.base_url
            url = f"{base_url}knowledge_base/download_doc?" + parameters
            text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{doc.page_content}\n\n"""
            source_documents.append(text)

        if len(source_documents) == 0:  # 没有找到相关文档
            source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")

        if stream:
            async for token in callback.aiter():
                logger.info("comixgpt返回的数据是:{}", token)

                # Use server-sent-events to stream the response
                yield json.dumps({"answer": token}, ensure_ascii=False)
            yield json.dumps({"docs": source_documents}, ensure_ascii=False)
        else:
            answer = ""
            async for token in callback.aiter():
                answer += token
            yield json.dumps({"answer": answer,
                              "docs": source_documents},
                             ensure_ascii=False)
        await task
`
         当我把LLMchain修改为 ConversationalRetrievalChain.from_llm的时候，并且把chat_history传进去的时候，如下：  chain.acall({"question": query, "chat_history":botHistory}),   for token in callback.aiter()回调的是LLM加工后的我的提问，并不是回答，这是为什么啊？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49478192/0d5b883e-6e51-42c2-ba66-4c924ef953f9)

**Comment by pengkang1991** [comment]
程序能够运行，但是就是没有结果出来。

**Comment by zRzRzRzRzRzRzR** [comment]
emm，这个格式输入不一样呀，你得看langchain不同chain的格式

**Comment by pengkang1991** [comment]
感谢，已经解决了。代码附上：
from fastapi import Body, Request
from fastapi.responses import StreamingResponse
from configs import (LLM_MODELS, VECTOR_SEARCH_TOP_K, SCORE_THRESHOLD, TEMPERATURE)
from server.utils import wrap_done, get_ChatOpenAI
from server.utils import BaseResponse, get_prompt_template
from langchain.chains import LLMChain
from langchain.callbacks import AsyncIteratorCallbackHandler
from typing import AsyncIterable, List, Optional
import asyncio
from langchain.prompts.chat import ChatPromptTemplate
from server.chat.utils import History
from server.knowledge_base.kb_service.base import KBServiceFactory
from server.knowledge_base.utils import get_doc_path
import json,os
from pathlib import Path
from urllib.parse import urlencode
from server.knowledge_base.kb_doc_api import search_docs
from langchain.vectorstores import FAISS
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.chains import ConversationalRetrievalChain
from langchain import PromptTemplate
from server.utils import get_model_worker_config, fschat_openai_api_address
from loguru import logger
from langchain.memory import ConversationKGMemory
from langchain.chat_models import ChatOpenAI





async def knowledge_base_chat(query: str = Body(..., description="用户输入", examples=["你好"]),
                              knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]),
                              top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"),
                              score_threshold: float = Body(
                                  SCORE_THRESHOLD,
                                  description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右",
                                  ge=0,
                                  le=2
                              ),
                              history: List[History] = Body(
                                  [],
                                  description="历史对话",
                                  examples=[[
                                      {"role": "user",
                                       "content": "我们来玩成语接龙，我先来，生龙活虎"},
                                      {"role": "assistant",
                                       "content": "虎头虎脑"}]]
                              ),
                              chat_history = Body(...,description="历史对话"),
                              stream: bool = Body(False, description="流式输出"),
                              model_name: str = Body(LLM_MODELS[0], description="LLM 模型名称。"),
                              temperature: float = Body(TEMPERATURE, description="LLM 采样温度", ge=0.0, le=1.0),
                              max_tokens: Optional[int] = Body(
                                  None,
                                  description="限制LLM生成Token数量，默认None代表模型最大值"
                              ),
                              prompt_name: str = Body(
                                  "default",
                                  description="使用的prompt模板名称(在configs/prompt_config.py中配置)"
                              ),
                              request: Request = None,
                              ):
    kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
    if kb is None:
        return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")

    history = [History.from_data(h) for h in history]

    async def knowledge_base_chat_iterator(
            query: str,
            top_k: int,
            history: Optional[List[History]],
            chat_history,
            model_name: str = LLM_MODELS[0],
            prompt_name: str = prompt_name,
    ) -> AsyncIterable[str]:
        nonlocal max_tokens
        callback = AsyncIteratorCallbackHandler()
        if isinstance(max_tokens, int) and max_tokens <= 0:
            max_tokens = None

        model = get_ChatOpenAI(
            model_name=model_name,
            temperature=temperature,
            max_tokens=max_tokens,
            callbacks=[callback]
        )
        docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
        context = "\n".join([doc.page_content for doc in docs])
        # if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
        #     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
        # else:
        prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
        input_msg = History(role="user", content=prompt_template).to_msg_template(False)
        chat_prompt = ChatPromptTemplate.from_messages(
            [i.to_msg_template() for i in history] + [input_msg])
        embeddings = OpenAIEmbeddings()
        COMIXGPT_VECTOR = '/mnt/faiss/vector_store'
        db = FAISS.load_local(COMIXGPT_VECTOR, embeddings)

        retriever = db.as_retriever(search_type="similarity_score_threshold",
                                    search_kwargs={"score_threshold": score_threshold,
                                                   "k": VECTOR_SEARCH_TOP_K})
        prompt = PromptTemplate(
            input_variables=["chat_history", "context", "question"],
            template=prompt_template
        )
        llm = ChatOpenAI(
            temperature=0, max_tokens=1024,
            model_name="gpt-4-1106-preview"
        )
        #chain = LLMChain(prompt=chat_prompt, llm=model)
        #memory = ConversationKGMemory(llm=model,memory_key='chat_history',return_messages=True,output_key='answer')
        chain = ConversationalRetrievalChain.from_llm(
            llm=model,
            chain_type="stuff",
            retriever=retriever,
            #memory=memory,
            return_source_documents=True,
            return_generated_question=True,
            combine_docs_chain_kwargs={'prompt': prompt},
            rephrase_question=True,
            # 独立llM
            condense_question_llm=llm,
            verbose=True
        )
        print(chat_history)
        if len(chat_history) > 0:
            botHistory = [(i[0], i[1]) for i in chat_history]
        # Begin a task that runs in the background.
        task = asyncio.create_task(wrap_done(
            chain.acall({"question": query,"chat_history":botHistory}),
            callback.done),
        )

        source_documents = []
        for inum, doc in enumerate(docs):
            filename = doc.metadata.get("source")
            parameters = urlencode({"knowledge_base_name": knowledge_base_name, "file_name": filename})
            base_url = request.base_url
            url = f"{base_url}knowledge_base/download_doc?" + parameters
            text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{doc.page_content}\n\n"""
            source_documents.append(text)

        if len(source_documents) == 0:  # 没有找到相关文档
            source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")

        if stream:
            async for token in callback.aiter():
                logger.info("comixgpt返回的数据是:{}", token)
                # Use server-sent-events to stream the response
                yield json.dumps({"answer": token}, ensure_ascii=False)
            yield json.dumps({"docs": source_documents}, ensure_ascii=False)
        else:
            answer = ""
            async for token in callback.aiter():
                answer += token
            yield json.dumps({"answer": answer,
                              "docs": source_documents},
                             ensure_ascii=False)
        await task

    return StreamingResponse(knowledge_base_chat_iterator(query=query,
                                                          top_k=top_k,
                                                          history=history,
                                                          chat_history=chat_history,
                                                          model_name=model_name,
                                                          prompt_name=prompt_name),
                             media_type="text/event-stream")

**Comment by sevenandseven** [comment]
> 感谢，已经解决了。代码附上： from fastapi import Body, Request from fastapi.responses import StreamingResponse from configs import (LLM_MODELS, VECTOR_SEARCH_TOP_K, SCORE_THRESHOLD, TEMPERATURE) from server.utils import wrap_done, get_ChatOpenAI from server.utils import BaseResponse, get_prompt_template from langchain.chains import LLMChain from langchain.callbacks import AsyncIteratorCallbackHandler from typing import AsyncIterable, List, Optional import asyncio from langchain.prompts.chat import ChatPromptTemplate from server.chat.utils import History from server.knowledge_base.kb_service.base import KBServiceFactory from server.knowledge_base.utils import get_doc_path import json,os from pathlib import Path from urllib.parse import urlencode from server.knowledge_base.kb_doc_api import search_docs from langchain.vectorstores import FAISS from langchain.embeddings.openai import OpenAIEmbeddings from langchain.chains import ConversationalRetrievalChain from langchain import PromptTemplate from server.utils import get_model_worker_config, fschat_openai_api_address from loguru import logger from langchain.memory import ConversationKGMemory from langchain.chat_models import ChatOpenAI
> 
> async def knowledge_base_chat(query: str = Body(..., description="用户输入", examples=["你好"]), knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]), top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"), score_threshold: float = Body( SCORE_THRESHOLD, description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右", ge=0, le=2 ), history: List[History] = Body( [], description="历史对话", examples=[[ {"role": "user", "content": "我们来玩成语接龙，我先来，生龙活虎"}, {"role": "assistant", "content": "虎头虎脑"}]] ), chat_history = Body(...,description="历史对话"), stream: bool = Body(False, description="流式输出"), model_name: str = Body(LLM_MODELS[0], description="LLM 模型名称。"), temperature: float = Body(TEMPERATURE, description="LLM 采样温度", ge=0.0, le=1.0), max_tokens: Optional[int] = Body( None, description="限制LLM生成Token数量，默认None代表模型最大值" ), prompt_name: str = Body( "default", description="使用的prompt模板名称(在configs/prompt_config.py中配置)" ), request: Request = None, ): kb = KBServiceFactory.get_service_by_name(knowledge_base_name) if kb is None: return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")
> 
> ```
> history = [History.from_data(h) for h in history]
> 
> async def knowledge_base_chat_iterator(
>         query: str,
>         top_k: int,
>         history: Optional[List[History]],
>         chat_history,
>         model_name: str = LLM_MODELS[0],
>         prompt_name: str = prompt_name,
> ) -> AsyncIterable[str]:
>     nonlocal max_tokens
>     callback = AsyncIteratorCallbackHandler()
>     if isinstance(max_tokens, int) and max_tokens <= 0:
>         max_tokens = None
> 
>     model = get_ChatOpenAI(
>         model_name=model_name,
>         temperature=temperature,
>         max_tokens=max_tokens,
>         callbacks=[callback]
>     )
>     docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
>     context = "\n".join([doc.page_content for doc in docs])
>     # if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
>     #     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
>     # else:
>     prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
>     input_msg = History(role="user", content=prompt_template).to_msg_template(False)
>     chat_prompt = ChatPromptTemplate.from_messages(
>         [i.to_msg_template() for i in history] + [input_msg])
>     embeddings = OpenAIEmbeddings()
>     COMIXGPT_VECTOR = '/mnt/faiss/vector_store'
>     db = FAISS.load_local(COMIXGPT_VECTOR, embeddings)
> 
>     retriever = db.as_retriever(search_type="similarity_score_threshold",
>                                 search_kwargs={"score_threshold": score_threshold,
>                                                "k": VECTOR_SEARCH_TOP_K})
>     prompt = PromptTemplate(
>         input_variables=["chat_history", "context", "question"],
>         template=prompt_template
>     )
>     llm = ChatOpenAI(
>         temperature=0, max_tokens=1024,
>         model_name="gpt-4-1106-preview"
>     )
>     #chain = LLMChain(prompt=chat_prompt, llm=model)
>     #memory = ConversationKGMemory(llm=model,memory_key='chat_history',return_messages=True,output_key='answer')
>     chain = ConversationalRetrievalChain.from_llm(
>         llm=model,
>         chain_type="stuff",
>         retriever=retriever,
>         #memory=memory,
>         return_source_documents=True,
>         return_generated_question=True,
>         combine_docs_chain_kwargs={'prompt': prompt},
>         rephrase_question=True,
>         # 独立llM
>         condense_question_llm=llm,
>         verbose=True
>     )
>     print(chat_history)
>     if len(chat_history) > 0:
>         botHistory = [(i[0], i[1]) for i in chat_history]
>     # Begin a task that runs in the background.
>     task = asyncio.create_task(wrap_done(
>         chain.acall({"question": query,"chat_history":botHistory}),
>         callback.done),
>     )
> 
>     source_documents = []
>     for inum, doc in enumerate(docs):
>         filename = doc.metadata.get("source")
>         parameters = urlencode({"knowledge_base_name": knowledge_base_name, "file_name": filename})
>         base_url = request.base_url
>         url = f"{base_url}knowledge_base/download_doc?" + parameters
>         text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{doc.page_content}\n\n"""
>         source_documents.append(text)
> 
>     if len(source_documents) == 0:  # 没有找到相关文档
>         source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
> 
>     if stream:
>         async for token in callback.aiter():
>             logger.info("comixgpt返回的数据是:{}", token)
>             # Use server-sent-events to stream the response
>             yield json.dumps({"answer": token}, ensure_ascii=False)
>         yield json.dumps({"docs": source_documents}, ensure_ascii=False)
>     else:
>         answer = ""
>         async for token in callback.aiter():
>             answer += token
>         yield json.dumps({"answer": answer,
>                           "docs": source_documents},
>                          ensure_ascii=False)
>     await task
> 
> return StreamingResponse(knowledge_base_chat_iterator(query=query,
>                                                       top_k=top_k,
>                                                       history=history,
>                                                       chat_history=chat_history,
>                                                       model_name=model_name,
>                                                       prompt_name=prompt_name),
>                          media_type="text/event-stream")
> ```


你好，请问检索器的方法检索和向量匹配的方法有什么区别？
修改链式可以提高知识库对上下文的记忆功能吗？

**Comment by sevenandseven** [comment]
> 感谢，已经解决了。代码附上： from fastapi import Body, Request from fastapi.responses import StreamingResponse from configs import (LLM_MODELS, VECTOR_SEARCH_TOP_K, SCORE_THRESHOLD, TEMPERATURE) from server.utils import wrap_done, get_ChatOpenAI from server.utils import BaseResponse, get_prompt_template from langchain.chains import LLMChain from langchain.callbacks import AsyncIteratorCallbackHandler from typing import AsyncIterable, List, Optional import asyncio from langchain.prompts.chat import ChatPromptTemplate from server.chat.utils import History from server.knowledge_base.kb_service.base import KBServiceFactory from server.knowledge_base.utils import get_doc_path import json,os from pathlib import Path from urllib.parse import urlencode from server.knowledge_base.kb_doc_api import search_docs from langchain.vectorstores import FAISS from langchain.embeddings.openai import OpenAIEmbeddings from langchain.chains import ConversationalRetrievalChain from langchain import PromptTemplate from server.utils import get_model_worker_config, fschat_openai_api_address from loguru import logger from langchain.memory import ConversationKGMemory from langchain.chat_models import ChatOpenAI
> 
> async def knowledge_base_chat(query: str = Body(..., description="用户输入", examples=["你好"]), knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]), top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"), score_threshold: float = Body( SCORE_THRESHOLD, description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右", ge=0, le=2 ), history: List[History] = Body( [], description="历史对话", examples=[[ {"role": "user", "content": "我们来玩成语接龙，我先来，生龙活虎"}, {"role": "assistant", "content": "虎头虎脑"}]] ), chat_history = Body(...,description="历史对话"), stream: bool = Body(False, description="流式输出"), model_name: str = Body(LLM_MODELS[0], description="LLM 模型名称。"), temperature: float = Body(TEMPERATURE, description="LLM 采样温度", ge=0.0, le=1.0), max_tokens: Optional[int] = Body( None, description="限制LLM生成Token数量，默认None代表模型最大值" ), prompt_name: str = Body( "default", description="使用的prompt模板名称(在configs/prompt_config.py中配置)" ), request: Request = None, ): kb = KBServiceFactory.get_service_by_name(knowledge_base_name) if kb is None: return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")
> 
> ```
> history = [History.from_data(h) for h in history]
> 
> async def knowledge_base_chat_iterator(
>         query: str,
>         top_k: int,
>         history: Optional[List[History]],
>         chat_history,
>         model_name: str = LLM_MODELS[0],
>         prompt_name: str = prompt_name,
> ) -> AsyncIterable[str]:
>     nonlocal max_tokens
>     callback = AsyncIteratorCallbackHandler()
>     if isinstance(max_tokens, int) and max_tokens <= 0:
>         max_tokens = None
> 
>     model = get_ChatOpenAI(
>         model_name=model_name,
>         temperature=temperature,
>         max_tokens=max_tokens,
>         callbacks=[callback]
>     )
>     docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
>     context = "\n".join([doc.page_content for doc in docs])
>     # if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
>     #     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
>     # else:
>     prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
>     input_msg = History(role="user", content=prompt_template).to_msg_template(False)
>     chat_prompt = ChatPromptTemplate.from_messages(
>         [i.to_msg_template() for i in history] + [input_msg])
>     embeddings = OpenAIEmbeddings()
>     COMIXGPT_VECTOR = '/mnt/faiss/vector_store'
>     db = FAISS.load_local(COMIXGPT_VECTOR, embeddings)
> 
>     retriever = db.as_retriever(search_type="similarity_score_threshold",
>                                 search_kwargs={"score_threshold": score_threshold,
>                                                "k": VECTOR_SEARCH_TOP_K})
>     prompt = PromptTemplate(
>         input_variables=["chat_history", "context", "question"],
>         template=prompt_template
>     )
>     llm = ChatOpenAI(
>         temperature=0, max_tokens=1024,
>         model_name="gpt-4-1106-preview"
>     )
>     #chain = LLMChain(prompt=chat_prompt, llm=model)
>     #memory = ConversationKGMemory(llm=model,memory_key='chat_history',return_messages=True,output_key='answer')
>     chain = ConversationalRetrievalChain.from_llm(
>         llm=model,
>         chain_type="stuff",
>         retriever=retriever,
>         #memory=memory,
>         return_source_documents=True,
>         return_generated_question=True,
>         combine_docs_chain_kwargs={'prompt': prompt},
>         rephrase_question=True,
>         # 独立llM
>         condense_question_llm=llm,
>         verbose=True
>     )
>     print(chat_history)
>     if len(chat_history) > 0:
>         botHistory = [(i[0], i[1]) for i in chat_history]
>     # Begin a task that runs in the background.
>     task = asyncio.create_task(wrap_done(
>         chain.acall({"question": query,"chat_history":botHistory}),
>         callback.done),
>     )
> 
>     source_documents = []
>     for inum, doc in enumerate(docs):
>         filename = doc.metadata.get("source")
>         parameters = urlencode({"knowledge_base_name": knowledge_base_name, "file_name": filename})
>         base_url = request.base_url
>         url = f"{base_url}knowledge_base/download_doc?" + parameters
>         text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{doc.page_content}\n\n"""
>         source_documents.append(text)
> 
>     if len(source_documents) == 0:  # 没有找到相关文档
>         source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
> 
>     if stream:
>         async for token in callback.aiter():
>             logger.info("comixgpt返回的数据是:{}", token)
>             # Use server-sent-events to stream the response
>             yield json.dumps({"answer": token}, ensure_ascii=False)
>         yield json.dumps({"docs": source_documents}, ensure_ascii=False)
>     else:
>         answer = ""
>         async for token in callback.aiter():
>             answer += token
>         yield json.dumps({"answer": answer,
>                           "docs": source_documents},
>                          ensure_ascii=False)
>     await task
> 
> return StreamingResponse(knowledge_base_chat_iterator(query=query,
>                                                       top_k=top_k,
>                                                       history=history,
>                                                       chat_history=chat_history,
>                                                       model_name=model_name,
>                                                       prompt_name=prompt_name),
>                          media_type="text/event-stream")
> ```

可以指导一下提示词部分怎么写吗，在哪里加上chat_history？

**Comment by pengkang1991** [comment]
> 区别链式可以提高知识库对上下文的记忆功能吗？

感觉没什么区别，我现在没用langchain封装的检索器了，直接用向量库原生的。不过也没区别，只是尝试一下。上下文记忆我是直接传聊天记录进去的，langchain有不少记忆检索方式，比如内存记忆啥的，你都可以尝试尝试。chat_history是在            chain.acall({"question": query,"chat_history":botHistory}),
这里传进去的。异步的比较复杂，给你看看我之前写的，简单易懂。`def load_db(vs_path):
    embeddings = OpenAIEmbeddings()
    llm = ChatOpenAI(
        temperature=0, max_tokens=1024,
        model_name=LLM_MODEL
    )
    # llm = OpenAI(
    #     temperature=0, max_tokens=1024,
    #     model_name=LLM_MODEL
    # )

    # create vector database from data
    #db = FAISS.load_local(vs_path, embeddings)
    db = Chroma(persist_directory=vs_path, embedding_function=embeddings)
    prompt = PromptTemplate(
        input_variables=["chat_history", "context", "question"],
        template=TEMPLATE["wxx"]
    )
    # define retriever
    #retriever = db.as_retriever(search_type="similarity", search_kwargs={"k": VECTOR_SEARCH_TOP_K})
    #retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": VECTOR_SEARCH_SCORE_THRESHOLD,"k":VECTOR_SEARCH_TOP_K,"fetch_k":50})
    #retriever = db.as_retriever(search_type="mmr", search_kwargs={"k":VECTOR_SEARCH_TOP_K})

    #精度匹配方式
    # embed 向量
    # embed 向量作为入参:embedding_vector
    #docs_and_scores = db.similarity_search_with_score()
    retriever = db.as_retriever(search_type="similarity_score_threshold", search_kwargs={"score_threshold": VECTOR_SEARCH_SCORE_THRESHOLD,"k":VECTOR_SEARCH_TOP_K,"fetch_k":50})
    #让AI检索
    # from langchain.retrievers.multi_query import MultiQueryRetriever
    # retriever_from_llm = MultiQueryRetriever.from_llm(retriever=db.as_retriever(), llm=llm)
    # create a chatbot chain. Memory is managed externally.
    # 简单记忆交互模式
    # memory = ConversationBufferMemory(memory_key='chat_history', return_messages=True, output_key='answer')
    # 摘要记忆交互模式
    # memory = ConversationSummaryMemory(llm=llm,memory_key='chat_history',return_messages=True,output_key='answer')
    # 对话摘要缓存内存记忆模式，可设置缓存大小。
    # memory = ConversationSummaryBufferMemory(llm=llm,memory_key='chat_history',return_messages=True,output_key='answer', max_token_limit=1000)
    # 知识图谱记忆模式，可分析
    # memory = ConversationKGMemory(llm=llm,memory_key='chat_history',return_messages=True,output_key='answer')
    qa = ConversationalRetrievalChain.from_llm(
        llm=llm,
        chain_type="stuff",
        retriever=retriever,
        # memory=memory,
        return_source_documents=True,
        return_generated_question=True,
        combine_docs_chain_kwargs={'prompt': prompt},
        rephrase_question=True,
        #独立llM
        condense_question_llm=ChatOpenAI(temperature=0, model=LLM_MODEL),
        verbose=True
    )
    return qa
`

**Comment by sevenandseven** [comment]
> 感谢，已经解决了。代码附上： from fastapi import Body, Request from fastapi.responses import StreamingResponse from configs import (LLM_MODELS, VECTOR_SEARCH_TOP_K, SCORE_THRESHOLD, TEMPERATURE) from server.utils import wrap_done, get_ChatOpenAI from server.utils import BaseResponse, get_prompt_template from langchain.chains import LLMChain from langchain.callbacks import AsyncIteratorCallbackHandler from typing import AsyncIterable, List, Optional import asyncio from langchain.prompts.chat import ChatPromptTemplate from server.chat.utils import History from server.knowledge_base.kb_service.base import KBServiceFactory from server.knowledge_base.utils import get_doc_path import json,os from pathlib import Path from urllib.parse import urlencode from server.knowledge_base.kb_doc_api import search_docs from langchain.vectorstores import FAISS from langchain.embeddings.openai import OpenAIEmbeddings from langchain.chains import ConversationalRetrievalChain from langchain import PromptTemplate from server.utils import get_model_worker_config, fschat_openai_api_address from loguru import logger from langchain.memory import ConversationKGMemory from langchain.chat_models import ChatOpenAI
> 
> async def knowledge_base_chat(query: str = Body(..., description="用户输入", examples=["你好"]), knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]), top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"), score_threshold: float = Body( SCORE_THRESHOLD, description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右", ge=0, le=2 ), history: List[History] = Body( [], description="历史对话", examples=[[ {"role": "user", "content": "我们来玩成语接龙，我先来，生龙活虎"}, {"role": "assistant", "content": "虎头虎脑"}]] ), chat_history = Body(...,description="历史对话"), stream: bool = Body(False, description="流式输出"), model_name: str = Body(LLM_MODELS[0], description="LLM 模型名称。"), temperature: float = Body(TEMPERATURE, description="LLM 采样温度", ge=0.0, le=1.0), max_tokens: Optional[int] = Body( None, description="限制LLM生成Token数量，默认None代表模型最大值" ), prompt_name: str = Body( "default", description="使用的prompt模板名称(在configs/prompt_config.py中配置)" ), request: Request = None, ): kb = KBServiceFactory.get_service_by_name(knowledge_base_name) if kb is None: return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")
> 
> ```
> history = [History.from_data(h) for h in history]
> 
> async def knowledge_base_chat_iterator(
>         query: str,
>         top_k: int,
>         history: Optional[List[History]],
>         chat_history,
>         model_name: str = LLM_MODELS[0],
>         prompt_name: str = prompt_name,
> ) -> AsyncIterable[str]:
>     nonlocal max_tokens
>     callback = AsyncIteratorCallbackHandler()
>     if isinstance(max_tokens, int) and max_tokens <= 0:
>         max_tokens = None
> 
>     model = get_ChatOpenAI(
>         model_name=model_name,
>         temperature=temperature,
>         max_tokens=max_tokens,
>         callbacks=[callback]
>     )
>     docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
>     context = "\n".join([doc.page_content for doc in docs])
>     # if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
>     #     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
>     # else:
>     prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
>     input_msg = History(role="user", content=prompt_template).to_msg_template(False)
>     chat_prompt = ChatPromptTemplate.from_messages(
>         [i.to_msg_template() for i in history] + [input_msg])
>     embeddings = OpenAIEmbeddings()
>     COMIXGPT_VECTOR = '/mnt/faiss/vector_store'
>     db = FAISS.load_local(COMIXGPT_VECTOR, embeddings)
> 
>     retriever = db.as_retriever(search_type="similarity_score_threshold",
>                                 search_kwargs={"score_threshold": score_threshold,
>                                                "k": VECTOR_SEARCH_TOP_K})
>     prompt = PromptTemplate(
>         input_variables=["chat_history", "context", "question"],
>         template=prompt_template
>     )
>     llm = ChatOpenAI(
>         temperature=0, max_tokens=1024,
>         model_name="gpt-4-1106-preview"
>     )
>     #chain = LLMChain(prompt=chat_prompt, llm=model)
>     #memory = ConversationKGMemory(llm=model,memory_key='chat_history',return_messages=True,output_key='answer')
>     chain = ConversationalRetrievalChain.from_llm(
>         llm=model,
>         chain_type="stuff",
>         retriever=retriever,
>         #memory=memory,
>         return_source_documents=True,
>         return_generated_question=True,
>         combine_docs_chain_kwargs={'prompt': prompt},
>         rephrase_question=True,
>         # 独立llM
>         condense_question_llm=llm,
>         verbose=True
>     )
>     print(chat_history)
>     if len(chat_history) > 0:
>         botHistory = [(i[0], i[1]) for i in chat_history]
>     # Begin a task that runs in the background.
>     task = asyncio.create_task(wrap_done(
>         chain.acall({"question": query,"chat_history":botHistory}),
>         callback.done),
>     )
> 
>     source_documents = []
>     for inum, doc in enumerate(docs):
>         filename = doc.metadata.get("source")
>         parameters = urlencode({"knowledge_base_name": knowledge_base_name, "file_name": filename})
>         base_url = request.base_url
>         url = f"{base_url}knowledge_base/download_doc?" + parameters
>         text = f"""出处 [{inum + 1}] [{filename}]({url}) \n\n{doc.page_content}\n\n"""
>         source_documents.append(text)
> 
>     if len(source_documents) == 0:  # 没有找到相关文档
>         source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
> 
>     if stream:
>         async for token in callback.aiter():
>             logger.info("comixgpt返回的数据是:{}", token)
>             # Use server-sent-events to stream the response
>             yield json.dumps({"answer": token}, ensure_ascii=False)
>         yield json.dumps({"docs": source_documents}, ensure_ascii=False)
>     else:
>         answer = ""
>         async for token in callback.aiter():
>             answer += token
>         yield json.dumps({"answer": answer,
>                           "docs": source_documents},
>                          ensure_ascii=False)
>     await task
> 
> return StreamingResponse(knowledge_base_chat_iterator(query=query,
>                                                       top_k=top_k,
>                                                       history=history,
>                                                       chat_history=chat_history,
>                                                       model_name=model_name,
>                                                       prompt_name=prompt_name),
>                          media_type="text/event-stream")
> ```

我有尝试自己使用摘要记忆交互模式，但是总结的时候是不是单独还需要一个提示模板，这个是我写的一部分代码，但是每次会报输入变量错误。
# SUMMARY_PROMPT=PromptTemplate(input_variables=["summary", "new_lines"], template=get_prompt_template("knowledge_base_chat", "summary"))
        chat_prompt = PromptTemplate(template=prompt_template, input_variables=["question", "context", "chat_history"])
           # [i.to_msg_template() for i in history] + [input_msg])
        memory = ConversationBufferMemory(memory_key="chat_history")
        # llm = OpenAI(temperature=0,openai_api_key="OPENAI_API_KEY",model_name="text-davinci-003")
        # memory=ConversationSummaryBufferMemory(llm=llm,prompt=SUMMARY_PROMPT, max_token_limit=256)
        res2=memory.load_memory_variables({})
        print("history is one  #############################", res2)
        #memory = ConversationSummaryBufferMemory(llm=model, max_token_limit=40, return_messages=True) 
        message = [i.to_msg_template() for i in history] 
        for message in history:
            if message.role == 'user':
                # 添加用户消息
                memory.chat_memory.add_user_message(message.content)
            else:
                # 添加AI消息
                memory.chat_memory.add_ai_message(message.content)   
        res2=memory.load_memory_variables({})
        print("history is two  #############################", res2)     
        print("memory is ********************:", memory)
        chain = LLMChain(prompt=chat_prompt, llm=model, memory=memory)

        # Begin a task that runs in the background.
        task = asyncio.create_task(wrap_done(
            chain.acall({"question": query}),
            callback.done),
        )
