### ISSUE TITLE
pg向量库连接不上

### ISSUE THREAD

**Issue by ghx2757** [chatchat-space/Langchain-Chatchat#2464]
**问题描述 / Problem Description**
本机安装了postgresql 数据库，在初始化pg向量库的时候报密码验证错误的错误信息

具体信息截图如下：
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/141898896/b05c42f0-6abb-4410-a0d6-f7a2f2cb4081)

**Comment by 871052165** [comment]
一模一样的问题

**Comment by zRzRzRzRzRzRzR** [comment]
dev现在还会吗

**Comment by ghx2757** [comment]
> dev现在还会吗

没有测试这个分支，我我是在main分支测试的，这个问题是chatchat的问题吗？目前需求不在这里就没有继续推进，3.0版本会有这个问题的解决吗？

**Comment by zRzRzRzRzRzRzR** [comment]
我们自己调能通，所以暂时不能确定，代码不够鲁棒也有可能

**Comment by ghx2757** [comment]
嗯嗯，好的，感谢感谢，另外期待一手3.0版本~~
