### ISSUE TITLE
[BUG] 无法使用zhipu的在线embedding

### ISSUE THREAD

**Issue by Chal1ce** [chatchat-space/Langchain-Chatchat#2465]
**无法使用zhipu的api进行在线embedding**
LLM聊天正常，但是知识库导入文件时无法进行向量化，显示无法转化绝对路径到相对路径

**复现问题的步骤**
1. 将model_config.py中的嵌入模型改为zhipu-api
2. 清空knowledge_base文件夹并重建向量库
3. python startup.py -a --lite 轻量部署启动
4. 新建数据库 -> 导入文件 -> 无法生成向量文件

**预期的结果 / Expected Result**
预期的结果应该是向量库里既有源文件也有向量文件

**实际结果 / Actual Result**
实际结果：只有源文件，没有向量文件
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/103374522/f27494bb-d9a9-4450-bf12-a50f8480dbce)
报错信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/103374522/1e23b52c-4e12-499d-b4ba-980bc27a1142)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/103374522/cf0302e5-b09f-4a4e-b959-a6e588e074a7)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本：0.0.344
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：zhipu-api
- 使用的 Embedding 模型：zhipu-api
- 使用的向量库类型： faiss 
- 操作系统及版本: Ubuntu 22.04 LTS
- Python 版本: 3.11.5

**Comment by Chal1ce** [comment]
@dosu-bot EMBEDDING_MODEL 是从config传过来的，在config我已经设置为使用zhipu api

**Comment by xiqukuwa** [comment]
> @dosu-bot EMBEDDING_MODEL 是从config传过来的，在config我已经设置为使用zhipu api

请问解决了吗

**Comment by Chal1ce** [comment]
> > @dosu-bot EMBEDDING_MODEL 是从config传过来的，在config我已经设置为使用zhipu api
> 
> 请问解决了吗

还没有，现在暂时放弃用线上嵌入模型了，看下这边有无大神遇见过这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
3.x开始会全部重写接入模型，尽情期待

**Comment by xiangjieli96** [comment]
请问用api调用chatglm4中embedding error为什么还是出现了
