### ISSUE TITLE
[FEATURE] 请问如何修改配置，增加知识库对话时针对输入的搜索词在知识库文档中的匹配位数？

### ISSUE THREAD

**Issue by raoly** [chatchat-space/Langchain-Chatchat#2466]
**功能描述 / Feature Description**

HMSSCL2999118，比如该关键词总是匹配前10位，然后实际中前10位相同的情况较多，如何修改项目的配置来提高匹配的位数？

**Comment by zRzRzRzRzRzRzR** [comment]
目前还是改不了的
