### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue infer_turbo设置为vllm，agent无法获取正确结果

### ISSUE THREAD

**Issue by lunalulu** [chatchat-space/Langchain-Chatchat#2468]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
"infer_turbo": 'vllm',其他参数没变
from fastchat.serve.vllm_worker import VLLMWorker, app, worker_id ，这里多引入了worker_id
sys.modules["fastchat.serve.vllm_worker"].worker = worker，添加这句话，因为不添加报错NameError: name worker is not defiend
vllm使用v0.2.0，其他版本都会报vllm错误
fschat 版本0.2.32
程序能跑起来，但是调用的时候还没进入到工具就报error：Observation2023-12-26 10:46:44,855 - utils.py[line:25] - ERROR: SyntaxError: Caught exception: invalid syntax (<string>, line 2)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：master分支
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:Python 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
想要提升多用户并发性

**Comment by lunalulu** [comment]
使用最新版本（2023-12-27下载）vllm模式在的那个GPU上跑通了
但是多个GPU 试着跑了一下一直卡在开启ray上，没成功

**Comment by zRzRzRzRzRzRzR** [comment]
没有出现这个情况，不过有没有可能是使用了vllm模型性能掉了
