### ISSUE TITLE
多个页面或者多用户问答时，项目问答能力非常有限：1.不能正常对话或者不回复；2.不释放显存

### ISSUE THREAD

**Issue by zhuhaifengaaa** [chatchat-space/Langchain-Chatchat#2469]
**功能描述 / Feature Description**
这个项目问答在我打开很多页面（意味着很多用户使用的场景）有几个问题，希望能提供一个解决方案或者代码：
1.当关闭页面时，对应的页面暂用的显存不能释放，‘
2.当多个页面同时对话时，只用5个以内的页面能回答问题，并且这个五个页面回答会非常慢；5个意外的页面根本无法正常回答，一直说抱歉。
具体如下图：
图1：打开了多个页面

![多个页面](https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/7c199e01-322d-4a74-a7fd-d8c5be20f07c)

图2：五个以内的页面能正常对话，但是非常慢
![5以内](https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/14a589f9-0f64-4a79-a87d-64d5f2a0baa8)

图3：五个以外的页面根本不能正常问答，或者直接不回答
![5以外](https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/0c908a01-0d52-48a7-91af-d1b5cd9ee453)

**Comment by zhuhaifengaaa** [comment]
图1：打开了多个页面
![多个页面](https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/8c6454b1-417d-4bfb-89ca-01245931cdef)



图2：五个以内的页面能正常对话，但是非常慢
![5以内](https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/826bd662-70f5-4bcb-b32a-99c2e8c36558)


图3：五个以外的页面根本不能正常问答，或者直接不回答
![5以外](https://github.com/chatchat-space/Langchain-Chatchat/assets/69130513/e93c72ec-0d91-4177-b33a-943908e4c2b2)

**Comment by zRzRzRzRzRzRzR** [comment]
streanlit不是给多用户用的

**Comment by Unexpectedlyc** [comment]
这个问题现在还是没有解决方案吗？有人定位到在块代码了 吗
