### ISSUE TITLE
知识库上传文件重复显示

### ISSUE THREAD

**Issue by SSTato** [chatchat-space/Langchain-Chatchat#2473]
在知识库中上传一个文件，会显示两条记录，一条是content文档，一条是向量库文档，这是为什么？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/93987794/0d8d246a-ae79-4ad2-87fe-75e8840da725)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/93987794/83d1049c-64ba-4fd5-bea0-705fe297d176)

**Comment by liunux4odoo** [comment]
Duplicate of #2299 , #2310
