### ISSUE TITLE
百度千帆/ERNIE-Bot 调用报错：'error_code': 3

### ISSUE THREAD

**Issue by Flagami** [chatchat-space/Langchain-Chatchat#2475]
报错信息：
 ERROR | model_worker | 请求千帆 API 时发生错误：{'error_code': 3, 'text': 'Unsupported openapi method', 'error': {'message': 'Unsupported openapi method', 'type': 'invalid_request_error', 'param': None, 'code': None}}

配置信息【关键的信息已经隐藏掉】：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.92.1.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.8
langchain版本：0.0.344. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['qianfan-api'] @ cuda
{'api_key': '********',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21004,
 'provider': 'QianFanWorker',
 'secret_key': '*******',
 'version': 'ERNIE-Bot',
 'version_url': 'https://aip.baidubce.com/rpc/2.0/ai_custom/v1/wenxinworkshop/chat/completions',
 'worker_class': <class 'server.model_workers.qianfan.QianFanWorker'>}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

**Comment by liunux4odoo** [comment]
把配置项的 version_url 清空，不是这么配置的。

**Comment by git-miao-i** [comment]
这样配置
![Uploading Snipaste_2023-12-28_11-09-20.png…]()

**Comment by git-miao-i** [comment]
![Snipaste_2023-12-28_11-09-20](https://github.com/chatchat-space/Langchain-Chatchat/assets/73871649/93d8d455-27d2-40a9-a13a-ed30b76d5b5d)
这样配置，只把模型在url的名填上就行

**Comment by Flagami** [comment]
> ![Snipaste_2023-12-28_11-09-20](https://private-user-images.githubusercontent.com/73871649/293130025-93d8d455-27d2-40a9-a13a-ed30b76d5b5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDExNTUsIm5iZiI6MTcwMzg0MDg1NSwicGF0aCI6Ii83Mzg3MTY0OS8yOTMxMzAwMjUtOTNkOGQ0NTUtMjdkMi00MGE5LWExM2EtZWQzMGI3NmQ1YjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA5MDczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Mjc1NTA2NzU2YWU2MzQ4MmRiMGNkYzA1YjU4OTAzMjk1YzNiMjVhZTFlMjI1MDBiNTM5ODVlZGNhODBlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8pPDKo5W0_2rrRBtb39VZP64uicek7oXweJSJ4YardQ) 这样配置，只把模型在url的名填上就行

好的栓Q，等迁完服务器试试
