### ISSUE TITLE
[BUG] 批量上传文件数量较多时会卡住不动，init_database也同样有这个问题，推测是多线程的问题

### ISSUE THREAD

**Issue by 2496289471** [chatchat-space/Langchain-Chatchat#2477]
**问题描述 / Problem Description**
如题，执行力一会就卡住了，什么反应都没有，等多久都不会动，绝对不是运行效率的问题，而且每次卡住的位置都一样。百分百复现。

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/43463601/58115a09-6ddc-4324-a5eb-4152ca433f5c)
卡在这里，我直接ctrl c了

**Comment by liunux4odoo** [comment]
弄一个只有一个文件的测试知识库，手动运行重建知识库命令试试，看看是不是有依赖问题。

**Comment by 2496289471** [comment]
> 弄一个只有一个文件的测试知识库，手动运行重建知识库命令试试，看看是不是有依赖问题。

一个文件或两三个文件都可以，文件一多就卡住不动了

**Comment by liunux4odoo** [comment]
samples知识库也这样吗？我重建一遍4分钟就结束了
