### ISSUE TITLE
[Loader] PDF loader 应该可选，或者优先提取PDF文本层信息

### ISSUE THREAD

**Issue by lv-saharan** [chatchat-space/Langchain-Chatchat#2478]
**功能描述 / Feature Description**
PDF loader 应该可选，或者优先提取PDF文本层信息

**解决的问题 / Problem Solved**
OCR消耗更多的资源，且有识别率问题。

**实现建议 / Implementation Suggestions**
上传PDF文件时可以选择采用ORC还是直接提取文字层，也可以再处理过程中判断每一页是否有文字层，如果有文字层采用文字层信息，如果没有使用图片OCR

**Comment by liunux4odoo** [comment]
现在的实现就是这样，先提取文本，再对包含的图片做 ocr。

#2525 提供了一个新的配置项，可以控制过滤掉尺寸过小的图片，这样非扫描的 pdf 里面一些无意义的小图片可以不做 ocr。

**Comment by Zhaibeiebi** [comment]
from unstructured.partition.text import partition_text。。运行的时候会卡在这一行。程序也不终止，就是没反应了。。。
