### ISSUE TITLE
启动时报错 startup.py -a(安装另外两个依赖文件的截图下面省略了)

### ISSUE THREAD

**Issue by zhangyue2709** [chatchat-space/Langchain-Chatchat#2483]
**问题描述 / Problem Description**
版本是v0.2.7,但是v0.2.8也遇到了这个问题,下面的截图是v0.2.7的.

**复现问题的步骤 / Steps to Reproduce**
1,拉取仓库
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/b808efe7-fc26-49a1-aa39-75c1e610b2e1)
2,进入目录
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/ecf6674b-1d87-437e-9da5-861d04fba23a)
3,安装依赖
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/1ba124ac-3859-4b48-b065-c7c222fecfdb)
4,运行copy_config_example.py
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/5a3fc112-12c9-41e7-9fc2-a55e0f3e0026)
5,初始化
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/82aad496-bd88-4437-bba9-55855cf88b1b)
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/cbf5e220-8336-46d9-b61a-0ccc16cc3a01)
6,启动
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/137603553/397ff1c9-07b6-4c6b-9ccf-15945cb70c50)
请问这是什么原因呢

**Comment by liunux4odoo** [comment]
不要用 ipython 的 %run 命令启动，在终端或虚拟环境直接执行启动命令
