### ISSUE TITLE
[BUG] 知识库问答，无法支持上下文，请教各位大佬如何优化

### ISSUE THREAD

**Issue by XUshicong** [chatchat-space/Langchain-Chatchat#2488]
知识库问答配置界面如下：
![2023-10-19 16-20-38 的屏幕截图](https://github.com/chatchat-space/Langchain-Chatchat/assets/73678015/21542492-93bc-41f6-8aeb-3219dc9c3380)
进行问答，但是效果不行：
**我 ：**能介绍一下DELTA1300的规格吗

**AI ：**
DELTA 1300的规格包括：

交流输入功率：X-Stream快充，最高1000W
交流输入电压：200-240V~ 50Hz/60Hz
太阳能充电输入：最高10-65V，10A，最高400W
车充输入：支持12V/24V电池，8A
交流输出：X4
USB-A (x2)
USB-A 快速充电 (x2)
USB-C (x2)

知识库匹配结果

**我：**帮我翻译成英文

**AI**
I'm sorry, I cannot provide a translation for the given text as it is not in a language that I can understand.

**Comment by XUshicong** [comment]
> _🤖_
> 
> 你好，@XUshicong！我是[Dosu](https://dosu.dev)，一个帮助您解决bug，回答问题，甚至成为贡献者的机器人。在等待人类维护者的同时，我会在这里帮助您。请随时向我提问或寻求帮助！
> 
> 根据我找到的信息，Langchain-Chatchat 仓库中有两个类似的已解决问题，它们都涉及到了如何在知识库问答中加入上下文的问题。这两个问题的链接分别是：
> 
> 1. [如何能进行基于上下文的知识库问答，目前好像是只能一次问答，并不关联提问的上下文](https://github.com/chatchat-space/Langchain-Chatchat/issues/826)
> 2. [后面能否加入上下文对话功能？](https://github.com/chatchat-space/Langchain-Chatchat/issues/6)
> 
> 在这两个问题中，建议的解决方案是在 2023/04/10 的更新中加入历史记录传入。
> 
> 对于你的问题，我建议你可以尝试修改 `knowledge_base_chat_iterator` 函数，使其在 `chain.acall` 方法中包含上下文。目前，`context` 被设置为连接的文档页面内容的字符串，但在 `chain.acall` 方法中并未使用。你可以修改 `chain.acall` 方法，使其包含上下文，如下所示：
> 
> ```python
> chain.acall({"context": context, "question": query})
> ```
> 
> 这将会把上下文和查询传递给 `LLMChain` 对象的 `acall` 方法，然后使用上下文和问题生成回答。
> 
> 这是修改后的代码：
> 
> ```python
> chain = LLMChain(prompt=chat_prompt, llm=model)
> 
> # Begin a task that runs in the background.
> task = asyncio.create_task(wrap_done(
>     chain.acall({"context": context, "question": query}),
>     callback.done),
> )
> ```
> 
> 这个修改将允许 `LLMChain` 在生成回答时使用上下文，这应该可以提高回答的质量。
> 
> 你可以在这个链接中查看相关的代码：[server/chat/knowledge_base_chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/knowledge_base_chat.py)
> 
> 希望这个答案对你有所帮助，如果你有任何其他问题，欢迎随时提问。
> 
> ## Sources
> * [如何能进行基于上下文的知识库问答，目前好像是只能一次问答，并不关联提问的上下文](https://github.com/chatchat-space/Langchain-Chatchat/issues/826)
> * [后面能否加入上下文对话功能？](https://github.com/chatchat-space/Langchain-Chatchat/issues/6)
> * [server/chat/knowledge_base_chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/knowledge_base_chat.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

我下载的是最新的版本，代码和上面是一样的

**Comment by sevenandseven** [comment]
> ```python
> asyncio.create_task
> ```

你好，我想问一下，怎么保证知识库问答的时候具有上下文能力，我的代码也是跟这个是同样的代码。
