### ISSUE TITLE
[FEATURE] 如何通过脚本的方式实现"上传文件到知识库，并或进行向量化"

### ISSUE THREAD

**Issue by XUshicong** [chatchat-space/Langchain-Chatchat#2489]
现在**上传文件到知识库，并或进行向量化**这个接口功能，文件的上传是需要在ChatChat API界面上完成，如下图：
![2023-12-27_19-11](https://github.com/chatchat-space/Langchain-Chatchat/assets/73678015/3a22f125-b949-40c9-ac75-b00f849252a5)
点击Execute，执行成功后，会有Curl代码：
```
curl -X 'POST' \
  'http://10.20.168.30:8082/knowledge_base/upload_docs' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'to_vector_store=true' \
  -F 'override=false' \
  -F 'not_refresh_vs_cache=false' \
  -F 'chunk_size=800' \
  -F 'chunk_overlap=200' \
  -F 'zh_title_enhance=true' \
  -F 'files=@output.json;type=application/json' \
  -F 'knowledge_base_name=bbb' \
  -F 'docs={
  "test.txt": [
    {
      "page_content": "custom doc",
      "metadata": {},
      "type": "Document"
    }
  ]
}'
```
我尝试将这个代码转化为Python代码：
```
import requests
url = 'XXXXX/knowledge_base/upload_docs'
headers = {
    'accept': 'application/json',
}
files = {
    'to_vector_store': (None, 'true'),
    'override': (None, 'false'),
    'not_refresh_vs_cache': (None, 'false'),
    'chunk_size': (None, '800'),
    'chunk_overlap': (None, '200'),
    'zh_title_enhance': (None, 'true'),
    'files': ('/path/to/json_file/on/the/local/computer/output.json', open('/path/to/json_file/on/the/local/computer/output.json', 'rb'), 'application/json'),
    'knowledge_base_name': (None, 'bbb'),
    'docs': (None, '{"test.txt": [{"page_content": "custom doc", "metadata": {}, "type": "Document"}]}'),
}
response = requests.post(url, headers=headers, files=files)
```
运行上面代码，出现以下问题：
{"code":200,"msg":"文件上传与向量化完成","data":{"failed_files":{"/path/to/json_file/on/the/local/computer/output.json'":"从文件 bbb//home/efsz/Desktop/LangChain/langchain_demo/data/output.json 加载文档时出错：[Errno 20] Not a directory: '/path/to/json_file/on/the/local/computer/output.json''"}}}

设置：
Langchain-ChatChat服务是运行在远程服务器上
脚本是在本地电脑上
上传的文件是本地电脑的文件

如何将**上传文件到知识库，并或进行向量化**这个接口功能，在本地电脑上通过脚本的形式实现呢？求各位大佬指点一二

**Comment by XUshicong** [comment]
> _🤖_
> 
> 你好，@XUshicong！我是一款可以帮助解决bug、解答问题、甚至帮助你成为贡献者的机器人，名字叫做[Dosu](https://dosu.dev)。在等待人类维护者的过程中，我会尽力提供帮助。非常高兴与你相遇！
> 
> 您的Python代码看起来几乎正确，但是在处理文件路径时似乎出现了问题。在这种情况下，您需要确保文件路径是正确的，并且文件确实存在于该路径下。在您的代码中，文件路径似乎被硬编码为`/path/to/json_file/on/the/local/computer/output.json`，这可能不是实际的文件路径。
> 
> 此外，您需要注意，当您在本地运行脚本并尝试上传文件到远程服务器时，服务器实际上是无法访问您本地计算机上的文件的。因此，当您尝试上传一个本地文件时，服务器会返回一个错误，因为它无法找到该文件。
> 
> 解决这个问题的一种方法是将文件先上传到一个服务器可以访问的位置，例如一个公共的云存储桶。然后，您可以在您的POST请求中提供该文件的URL，而不是本地文件路径。这样，服务器就可以从该URL下载文件，然后进行处理。
> 
> 另一种可能的解决方案是使用一个支持文件上传的Python库，如`requests`库。这个库允许您在POST请求的body中包含文件的内容，而不是文件的路径。这样，服务器就可以直接从请求的body中读取文件的内容，而不需要访问文件系统。
> 
> 以下是一个使用`requests`库上传文件的示例：
> 
> ```python
> import requests
> 
> url = 'http://10.20.168.30:8082/knowledge_base/upload_docs'
> headers = {
>     'accept': 'application/json',
>     'Content-Type': 'multipart/form-data',
> }
> data = {
>     'to_vector_store': 'true',
>     'override': 'false',
>     'not_refresh_vs_cache': 'false',
>     'chunk_size': '800',
>     'chunk_overlap': '200',
>     'zh_title_enhance': 'true',
>     'knowledge_base_name': 'bbb',
>     'docs': '{"test.txt": [{"page_content": "custom doc", "metadata": {}, "type": "Document"}]}',
> }
> files = {
>     'files': open('/path/to/your/file', 'rb'),
> }
> 
> response = requests.post(url, headers=headers, data=data, files=files)
> ```
> 
> 在这个示例中，`files`参数是一个字典，其中的键是在服务器上接收文件的参数的名称，值是一个打开的文件对象。当您执行`requests.post`时，`requests`库会自动将文件的内容包含在请求的body中。
> 
> 请注意，您需要将`/path/to/your/file`替换为您要上传的文件的实际路径。
> 
> ## Sources
> * [webui_pages/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/utils.py)
> * [server/api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/api.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

方法有效，已解决

**Comment by lamwin24** [comment]
@dosu-bot 请问如何通过API方式上传文件？

**Comment by devstein** [comment]
Hi @lamwin24 as of now Dosu only responds to requests from the issue author and maintainers

**Comment by liunux4odoo** [comment]
该问题不属于项目代码问题。
可以参考 webui_papges/utils 里面 upload_docs 方法。
