### ISSUE TITLE
[FEATURE] 固定依赖减少BUG / 固定依赖版本

### ISSUE THREAD

**Issue by 107350qin** [chatchat-space/Langchain-Chatchat#2497]
**功能描述 / Feature Description**
requirement.txt中一些组件使用==或者>=某个版本，这是一个大坑。导致的结果是组件A在一个月前下载的是1.0版本，现在下载变成了2.0版本，版本不稳定会导致很多BUG

**解决的问题 / Problem Solved**
稳定依赖的版本，减少依赖问题

**实现建议 / Implementation Suggestions**
成功安装langchain-chatchat之后，通过pip freeze查看当前安装的版本，将版本号固定到requirement.txt文件

**Comment by liunux4odoo** [comment]
0.2.9 版本开始将会视情况固定主要依赖的版本或大版本。
