### ISSUE TITLE
[BUG] 局域网中访问web界面，知识库问答时返回的“知识库匹配结果”中的文档下载链接的url为127.0.0.1

### ISSUE THREAD

**Issue by qurikuduo** [chatchat-space/Langchain-Chatchat#2499]
**问题描述 / Problem Description**
知识库问答时返回的“知识库匹配结果”中的文档下载链接的url为127.0.0.1，如：
http://[127.0.0.1](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=%E7%94%B5%E5%8A%9B-%E6%B5%8B%E8%AF%95&file_name=%E5%9B%BD%E5%AE%B6%E7%94%B5%E7%BD%91%E5%85%AC%E5%8F%B8%E4%BE%9B%E7%94%B5%E7%94%B5%E5%8E%8B%E7%AE%A1%E7%90%86%E8%A7%84%E5%AE%9A.pdf):7861/knowledge_base/download_doc?knowledge_base_name=%E7%94%B5%E5%8A%9B-%E6%B5%8B%E8%AF%95&file_name=%E5%9B%BD%E5%AE%B6%E7%94%B5%E7%BD%91%E5%85%AC%E5%8F%B8%E4%BE%9B%E7%94%B5%E7%94%B5%E5%8E%8B%E7%AE%A1%E7%90%86%E8%A7%84%E5%AE%9A.pdf

**复现问题的步骤 / Steps to Reproduce**
1. 在服务器中启动: python startup.py -a
2. 在客户端pc中用局域网ip访问服务器的web界面，如：http://192.168.14.88:8501点击 知识库聊天
3. 输入问题，等待返回后
4. 问题出现 / Problem occurs
返回消息中“知识库匹配结果””中的文档下载链接的url为127.0.0.1
**预期的结果 / Expected Result**
能正常的下载文档。即，文档的下载链接应该是：http://192.168.14.88:7861/knowledge_base/download_doc?knowledge_base_name=xxx

**实际结果 / Actual Result**
[描述实际发生的结果 / Describe the actual result.](http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=xxx)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：4e69033
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: ubuntu 18.04
- Python 版本 / Python version: Python 3.10.12
- 其他相关环境信息 / Other relevant environment information: 

**附加信息 / Additional Information**
错误界面截图：
![88e02a3482a4162ab5d89d824e57455](https://github.com/chatchat-space/Langchain-Chatchat/assets/4517807/e3942994-80bb-4073-9f35-fc959184e7cb)

猜测应该跟此处赋值有关：
https://github.com/chatchat-space/Langchain-Chatchat/blob/af38f75b29f8db45f60f922e5e3b82ad4e1b32a5/server/chat/knowledge_base_chat.py#L97C15-L97C15

**Comment by liunux4odoo** [comment]
把 configs/server_config 中所有 host 改成你实际 IP

**Comment by qurikuduo** [comment]
> 把 configs/server_config 中所有 host 改成你实际 IP

OK，修改完之后可以了。非常感谢。
