### ISSUE TITLE
[FEATURE] 单段文本最大长度能不能大于1000个字符，在哪里设置，knowledge_base.py里改成3000，前端显示还是限制为1000

### ISSUE THREAD

**Issue by lvxian101** [chatchat-space/Langchain-Chatchat#2501]
![1703758247231](https://github.com/chatchat-space/Langchain-Chatchat/assets/114395535/8875eebd-b30f-4895-83ba-6e23f0958c08)

**Comment by lvxian101** [comment]
@dosu-bot 我就是用的你的方法，但是仍然提示最大长度不得超过1000

**Comment by lvxian101** [comment]
@dosu-bot是将文档向量化时限制的单段文本最大长度的修改方法，也就是向量库里单个文件的最大长度。不是chat输出是的最大文本长度

**Comment by lvxian101** [comment]
@dosu-bot是将文档向量化时限制的单段文本最大长度的修改方法，也就是向量库里单个文件的最大长度

**Comment by lvxian101** [comment]
> _🤖_
> 
> 你好，@lvxian101！我是[Dosu](https://dosu.dev), 一个专门帮助你解决问题，回答相关疑问和成为贡献者的机器人。在等待人类维护者的同时，我在此为你提供帮助。很高兴与你交流！
> 
> 在Langchain-Chatchat中，单段文本的最大长度可以在`knowledge_base.py`文件的`knowledge_base_page`函数中设置。具体来说，它在以下这行代码中设置：
> 
> ```python
> chunk_size = cols[0].number_input("单段文本最大长度：", 1, 1000, CHUNK_SIZE)
> ```
> 
> `number_input`函数的第三个参数是允许的最大值。在这种情况下，它被设置为1000。如果你想将最大字符限制增加到3000，你可以将这行改为：
> 
> ```python
> chunk_size = cols[0].number_input("单段文本最大长度：", 1, 3000, CHUNK_SIZE)
> ```
> 
> 然而，如果在做出这个更改后，前端仍然显示1000的限制，那么可能前端代码也设置了1000的限制。你需要找到前端代码中设置此限制的地方，并在那里也增加它。没有前端代码，我无法提供更具体的指导。
> 
> 关于你的问题，我在Langchain-Chatchat的存储库中找到了一个类似的已解决问题，你可以参考一下：[请问生成文本长度限制在哪设置。](https://github.com/chatchat-space/Langchain-Chatchat/issues/1423)
> 
> 如果你在前端代码中找不到设置最大字符限制的地方，或者有其他问题，欢迎继续提问。
> 
> ## Sources
> * [请问生成文本长度限制在哪设置。](https://github.com/chatchat-space/Langchain-Chatchat/issues/1423)
> * [webui_pages/knowledge_base/knowledge_base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/knowledge_base/knowledge_base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

已解决，这个方案可行，我当时可能没有把代码上传更新

**Comment by jhw0510** [comment]
@lvxian101 
您好，我想问问，我修改了单段文本最大长度为1000，知识库文件应该就是按照1000进行分块拆分对吧，但是我在知识库问答中，模型显示的知识库匹配结果还是近似为这个项目默认的250，我不知道哪里出了问题，这是我的图：
<img width="506" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/127382508/e2c60735-cdf4-44a9-9490-8f773c89f4f0">

**Comment by jhw0510** [comment]
> 你要把向量库中原来的向量块删除
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年1月4日(星期四) 凌晨1:07 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [chatchat-space/Langchain-Chatchat] [FEATURE] 单段文本最大长度能不能大于1000个字符，在哪里设置，knowledge_base.py里改成3000，前端显示还是限制为1000 (Issue #2501) @lvxian101 您好，我想问问，我修改了单段文本最大长度为1000，知识库文件应该就是按照1000进行分块拆分对吧，但是我在知识库问答中，模型显示的知识库匹配结果还是近似为这个项目默认的250，我不知道哪里出了问题，这是我的图： image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

感谢回复，上个礼拜已经解决啦，是项目里面的一个小bug，具体可以看 #2561 和 #2564
