### ISSUE TITLE
[FEATURE] 是否支持ipv6访问？

### ISSUE THREAD

**Issue by b9348** [chatchat-space/Langchain-Chatchat#2502]
[现在跑在我电脑上，但是提示访问被拒绝]([2408:8240:e18:2300:703c:1e3a:ee84:86a]:8501)
```
[2408:8240:e18:2300:703c:1e3a:ee84:86a]:8501
```

**Comment by b9348** [comment]
[2408:8240:e18:2300:703c:1e3a:ee84:86a]:8501

**Comment by zRzRzRzRzRzRzR** [comment]
不支持

**Comment by eric1932** [comment]
webui 部分改成 '::' 可以跑起来
`WEBUI_SERVER = {
    "host": '::',
    "port": 8501,
}`

主要是 Streamlit 监听 v6 的 ip:port 就行, 别的 API host 不需要改
