### ISSUE TITLE
[BUG]使用本地模型打开web界面进行对话，出现streamlit相关错误

### ISSUE THREAD

**Issue by aqi123** [chatchat-space/Langchain-Chatchat#2507]
langchaiin-chatchat0.2.8

采用qwen-1_8B-chat本地模型，运行startup.py可以正常打开web界面，第一次对话时后台报utils.py[line:27] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

第二次以及后续对话时，后台报streamlit.errors. DuplicateWidgetID: There are multiple widgets with the same `key=''`.，

不清楚这是为啥，也无从下手去修改，请各位大神指教，谢谢

**Comment by liunux4odoo** [comment]
把出错的log贴出来，光这点描述看不出来什么。

**Comment by aqi123** [comment]
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/daccfe91-1000-4501-9872-e49f8f7f9537)
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/dd53eb62-18ce-40a8-8e85-18a6778f665f)
![3](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/c7ba120a-4354-4012-8f96-8869faf99f6d)
![4](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/cf59ce09-72f9-47be-b9a4-7510ba78bcb0)

**Comment by aqi123** [comment]
> 把出错的log贴出来，光这点描述看不出来什么。

我上传了图片，可以看到吗，谢谢~

**Comment by liunux4odoo** [comment]
log太少，从服务器启动开始帖完整一些

**Comment by aqi123** [comment]
> log太少，从服务器启动开始帖完整一些

这是所有的了，我的cuda是11.7的，安装的是目前我电脑显卡支持的最高版本，程序修改的地方只有model_config.py中的MODEL_ROOT_PATH、EMBEDDING_MODEL、LLM_MODELS三个参数，其余全部使用原配置，其中device设置的auto，但是不强出为何还是在使用CPU，我尝试指定过cuda，没有作用，这个问题不知是否导致了对话出现错误


![5](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/3bae18a4-13c5-45fd-9f8d-0f60c9090dcc)
![6](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/e6d4395e-ca12-437e-bfd8-d035dec2456b)
![7](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/99666b33-943f-4f8b-8b0b-909d3eacc8e9)
![8](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/8c0f9f82-f124-430f-9b41-9e6b148280c3)
![9](https://github.com/chatchat-space/Langchain-Chatchat/assets/48171276/bde28775-73ce-414b-a17e-892b4c727a94)

**Comment by liunux4odoo** [comment]
你显卡驱动太旧了，更新一些再试试。

**Comment by aqi123** [comment]
> 你显卡驱动太旧了，更新一些再试试。

好朋友，它已经显示最新了/(ㄒoㄒ)/~~

**Comment by liunux4odoo** [comment]
> > 你显卡驱动太旧了，更新一些再试试。
> 
> 好朋友，它已经显示最新了/(ㄒoㄒ)/~~

你看第一张图里的报错信息，torch不是这么认为的。

**Comment by aqi123** [comment]
> > > 你显卡驱动太旧了，更新一些再试试。
> > 
> > 
> > 好朋友，它已经显示最新了/(ㄒoㄒ)/~~
> 
> 你看第一张图里的报错信息，torch不是这么认为的。

那我是不是该换显卡了😂

**Comment by kaixuanjames** [comment]
> LLM_MODELS三

与使用CPU跑应该没有关系，我用cuda跑的，也是显示相同的报错

**Comment by kaixuanjames** [comment]
在线跑模型要安装对应的SDK，通义千问为pip install dashscope

**Comment by aqi123** [comment]
> 在线跑模型要安装对应的SDK，通义千问为pip install dashscope

试了一下，本地模型不需要安装dashscope呢，请问你解决这个问题了吗
