### ISSUE TITLE
[BUG] 回答陷入死循环

### ISSUE THREAD

**Issue by Roger-G** [chatchat-space/Langchain-Chatchat#2511]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
回答问题后停止

**实际结果 / Actual Result**
回答问题后一直输出，无法停止
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37508579/e721e634-d7c5-48cb-8f15-b692209c2c82)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:3.8.18
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
hf更新chatglm的新配置

**Comment by Roger-G** [comment]
更新了，也不行
