### ISSUE TITLE
在使用WINDOS安装依赖时，就算是新环境也会出现error: [WinError 2] 系统找不到指定的文件。 ERROR: Failed building wheel for jq

### ISSUE THREAD

**Issue by 871052165** [chatchat-space/Langchain-Chatchat#2518]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'pip install -r  requirements.txt

2. 问题出现 / Problem occurs
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/f9ddfd90-857a-49f3-a930-8ff805736628)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.9
- 是否使用 Docker 部署（是/否）：No
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:Windos
- Python 版本 / Python version:3.10.13
- 其他相关环境信息 / Other relevant environment information:anaconda

**Comment by Marinzzz** [comment]
requirement.txt写了使用conda install jq来安装的

**Comment by wangqiuxiang1024** [comment]
> _🤖_
> 
> 你好 @871052165，我是[Dosu](https://dosu.dev)，一个可以帮助你解决错误、回答问题并成为贡献者的机器人。请放心，我会在人类维护者来临之前提供帮助。很高兴能为你服务！
> 
> 根据我在Langchain-Chatchat仓库中找到的信息，"[WinError 2] 系统找不到指定的文件。 ERROR: Failed building wheel for jq" 这个错误通常表示系统找不到指定的文件。这可能是由于以下几个原因：
> 
> 1. 所需的 'jq' 包没有在您的Python环境中安装或找不到。
> 2. 您正在使用的Python版本（Python 3.10.13）与'jq'包或其他依赖项可能存在兼容性问题。
> 3. 'jq'包的安装本身可能存在问题。
> 
> 为了解决这个问题，您可以尝试以下步骤：
> 
> 1. 确保您已正确克隆了Langchain-Chatchat仓库并导航到正确的目录：
> 
> ```shell
> $ git clone https://github.com/chatchat-space/Langchain-Chatchat.git
> $ cd Langchain-Chatchat
> ```
> 
> 2. 尝试再次安装依赖项。如果您正在使用虚拟环境，请确保它已激活：
> 
> ```shell
> $ pip install -r requirements.txt 
> $ pip install -r requirements_api.txt
> $ pip install -r requirements_webui.txt  
> ```
> 
> 3. 如果错误仍然存在，您可能需要尝试将Python版本降级到3.10.12，如README文件中所指定：
> 
> ```shell
> $ python --version
> Python 3.10.12
> ```
> 
> 4. 如果错误仍然存在，可能是'jq'包本身的问题。您可以尝试使用pip单独安装它：
> 
> ```shell
> $ pip install jq
> ```
> 
> 如果以上步骤都无法解决问题，那么可能是一个需要进一步调查的更复杂的问题。
> 
> 关于'jq'包在Langchain-Chatchat项目中的确切作用，我在仓库中没有找到答案，但答案可能在其他地方可用，或者我可能错过了它。
> 
> 参考资料：
> 
> * [README_en.md](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/README_en.md)
> * [系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1587)
> * [[BUG] [WinError 2] 系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1933)
> 
> ## Sources
> * [系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1587)
> * [[BUG] [WinError 2] 系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1933)
> * [README_en.md](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/README_en.md)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.



> _🤖_
> 
> 你好 @871052165，我是[Dosu](https://dosu.dev)，一个可以帮助你解决错误、回答问题并成为贡献者的机器人。请放心，我会在人类维护者来临之前提供帮助。很高兴能为你服务！
> 
> 根据我在Langchain-Chatchat仓库中找到的信息，"[WinError 2] 系统找不到指定的文件。 ERROR: Failed building wheel for jq" 这个错误通常表示系统找不到指定的文件。这可能是由于以下几个原因：
> 
> 1. 所需的 'jq' 包没有在您的Python环境中安装或找不到。
> 2. 您正在使用的Python版本（Python 3.10.13）与'jq'包或其他依赖项可能存在兼容性问题。
> 3. 'jq'包的安装本身可能存在问题。
> 
> 为了解决这个问题，您可以尝试以下步骤：
> 
> 1. 确保您已正确克隆了Langchain-Chatchat仓库并导航到正确的目录：
> 
> ```shell
> $ git clone https://github.com/chatchat-space/Langchain-Chatchat.git
> $ cd Langchain-Chatchat
> ```
> 
> 2. 尝试再次安装依赖项。如果您正在使用虚拟环境，请确保它已激活：
> 
> ```shell
> $ pip install -r requirements.txt 
> $ pip install -r requirements_api.txt
> $ pip install -r requirements_webui.txt  
> ```
> 
> 3. 如果错误仍然存在，您可能需要尝试将Python版本降级到3.10.12，如README文件中所指定：
> 
> ```shell
> $ python --version
> Python 3.10.12
> ```
> 
> 4. 如果错误仍然存在，可能是'jq'包本身的问题。您可以尝试使用pip单独安装它：
> 
> ```shell
> $ pip install jq
> ```
> 
> 如果以上步骤都无法解决问题，那么可能是一个需要进一步调查的更复杂的问题。
> 
> 关于'jq'包在Langchain-Chatchat项目中的确切作用，我在仓库中没有找到答案，但答案可能在其他地方可用，或者我可能错过了它。
> 
> 参考资料：
> 
> * [README_en.md](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/README_en.md)
> * [系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1587)
> * [[BUG] [WinError 2] 系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1933)
> 
> ## Sources
> * [系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1587)
> * [[BUG] [WinError 2] 系统找不到指定的文件](https://github.com/chatchat-space/Langchain-Chatchat/issues/1933)
> * [README_en.md](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/README_en.md)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

我遇到同样的问题，尝试步骤1、2、3 都没有解决，尝试步骤4的时候执行 pip install jq 后报错
Collecting jq
  Using cached jq-1.6.0.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: jq
  Building wheel for jq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for jq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Executing: ./configure CFLAGS=-fPIC --prefix=C:\Users\96211\AppData\Local\Temp\pip-install-e3xriz0r\jq_a1042376c6794f99b79915b38dee1740\_deps\build\onig-install-6.9.8
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jq
Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects

**Comment by Mgzchengzi** [comment]
正确的操作方式是：使用conda安装jq，然后在requirements.txt文件中注释调jq的安装
1.conda环境中执行：conda install jq
2.修改requirements.txt文件，注释掉jq（#jq>=1.6.0 # for .json and .jsonl files. suggest `conda install jq` on windows）

**Comment by PonySaye** [comment]
> 正确的操作方式是：使用conda安装jq，然后在requirements.txt文件中注释调jq的安装 1.conda环境中执行：conda install jq 2.修改requirements.txt文件，注释掉jq（#jq>=1.6.0 # for .json and .jsonl files. suggest `conda install jq` on windows）

我怎么弄完，还是一个报错的
