### ISSUE TITLE
[BUG] requirements_api.txt中关于zhipuai的依赖一行有一个中文逗号，会导致安装出错

### ISSUE THREAD

**Issue by Marinzzz** [chatchat-space/Langchain-Chatchat#2519]
**问题描述 / Problem Description**
requirements_api.txt中关于zhipuai的依赖一行有一个中文逗号，会导致安装出错
**复现问题的步骤 / Steps to Reproduce**
1. 执行 pip install -r requirement_api.txt
2. 执行错误
<img width="861" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/30408247/89d87c97-f604-41c2-8b13-f6764b12e661">
3. 问题根因（ requirements_api.txt，第55行）
<img width="173" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/30408247/c97f9ca1-82ed-40a2-8a39-045427e7b4a5">

**Comment by liunux4odoo** [comment]
感谢反馈。该问题在 master 已经修复。
