### ISSUE TITLE
there is a comma in Chinese encoded in requirements_api.txt

### ISSUE THREAD

**Issue by jack-kwok80** [chatchat-space/Langchain-Chatchat#2521]
there is a comma in Chinese encoded in requirements_api.txt

it will get "UnicodeDecodeError: 'gbk' codec can't decode byte 0x8c in position 1365: illegal multibyte sequence" error when run "pip install -r requirements_api.txt"

**Comment by liunux4odoo** [comment]
Thanks for feedback, the problem has been fixed.

**Comment by PittYao** [comment]
that's true
