### ISSUE TITLE
请问启动多个模型，postman该如何发起请求呢？

### ISSUE THREAD

**Issue by GXKIM** [chatchat-space/Langchain-Chatchat#2524]
例如：启动qwen14b-chat chatglm3-6b

http://xxxx:7861/chat/chat
怎么指定模型呢？
{"query":"今天吃饭了吗","messages":{"role": "user"}}
加一个字段model吗

**Comment by GXKIM** [comment]
> 是的，你看7860有介绍APi怎么用的

解决了 {"query":"今天吃饭了吗","messages":{"role": "user"},"model_name"}

**Comment by GXKIM** [comment]
> 是的，你看7860有介绍APi怎么用的

大佬现在openai更新到1.6之后接不了本地启动的服务了吗
model = OpenAI(openai_api_base="http://xxxx/v1",       
               model_name="chatglm3-6b",                              
               openai_api_key="NULL")                                 
                                                                   

from openai import OpenAI                                                   
client = OpenAI()                                                           
                                                                            
completion = client.chat.completions.create(                                
  model=model,                                                              
  messages=[{"role": "user", "content": "Hello! What is your name?"}]       
)                                                                           
# print the completion                                                      
print(completion.choices[0].message.content)

**Comment by zRzRzRzRzRzRzR** [comment]
你要按照最新的API来接，然后你后台能检测到是否有内容
