### ISSUE TITLE
DOCKER方式部署0.2.6版本，进入容器后执行：python copy_config_example.py，提示没有python命令

### ISSUE THREAD

**Issue by guyuejia** [chatchat-space/Langchain-Chatchat#2526]
docker方式部署，想要配置下模型，按照wiki文档首先执行：python copy_config_example.py，提示没有python命令。是不是容器部署的方式，是通过其他方式进行参数配置的呢

**Comment by goldSunshine** [comment]
python3 copy_config_example.py
