### ISSUE TITLE
[BUG] model_config.py中RERANKER_MAX_LENGTH=1024默认配置会导致tensor大小不匹配错误

### ISSUE THREAD

**Issue by yhfgyyf** [chatchat-space/Langchain-Chatchat#2528]
**问题描述 / Problem Description**
BAAI/bge-reranker-base和BAAI/bge-reranker-large两个reranker模型的config.json中显示max_position_embeddings为514
 "max_position_embeddings": 514,
model_config.py中默认RERANKER_MAX_LENGTH=1024，运行时会出现张量大小不匹配错误：
RuntimeError: The expanded size of the tensor (535) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [1, 535].  Tensor sizes: [1, 514]
建议修改这一默认配置为RERANKER_MAX_LENGTH=512

**Comment by aaalionaaa** [comment]
匹配的内容长度超过512了，修改了RERANKER_MAX_LENGTH没有效果

**Comment by michaelxu1107** [comment]
> 匹配的内容长度超过512了，修改了RERANKER_MAX_LENGTH没有效果
你好，有解决方案了吗，感觉像是检索出来的相似文档太长了，我看bge-ranker-large目录下"max_position_embeddings"配置为514

**Comment by aaalionaaa** [comment]
> > 匹配的内容长度超过512了，修改了RERANKER_MAX_LENGTH没有效果
> > 你好，有解决方案了吗，感觉像是检索出来的相似文档太长了，我看bge-ranker-large目录下"max_position_embeddings"配置为514

做截断再rerank吧

**Comment by Gzj369** [comment]
@aaalionaaa 我也遇到了这个问题，请问怎么先做截断再rarank呢，我是v0.2.9的版本，代码上哪里需要进行优化呢

**Comment by xxWeiDG** [comment]
> @aaalionaaa 我也遇到了这个问题，请问怎么先做截断再rarank呢，我是v0.2.9的版本，代码上哪里需要进行优化呢

现在我v0.2.10还是有这个问题，兄弟你怎么解决的呢

**Comment by Gzj369** [comment]
> > @aaalionaaa 我也遇到了这个问题，请问怎么先做截断再rarank呢，我是v0.2.9的版本，代码上哪里需要进行优化呢
> 
> 现在我v0.2.10还是有这个问题，兄弟你怎么解决的呢

应该是对输入的长度做限制，最长不超过 RERANKER_MAX_LENGTH 才行（比如字符串分割），我还没尝试，您可以试试
