### ISSUE TITLE
[BUG] gradio上传知识库后刷新之后 知识库就不见了  只有重启才能看到之前的上传的知识库  

### ISSUE THREAD

**Issue by cxj01** [chatchat-space/Langchain-Chatchat#253]
gradio上传知识库后刷新之后 知识库就不见了  只有重启才能看到之前的上传的知识库

**Comment by imClumsyPanda** [comment]
已经在着手解决这一bug，如果着急的话，可以先测试看看 https://github.com/imClumsyPanda/langchain-ChatGLM/pull/250

**Comment by cxj01** [comment]
@jiangbossB 你用的是哪个代码？我还是有同样的问题！
