### ISSUE TITLE
[BUG] requirement.txt中jq 安装错误解答 win 10或11

### ISSUE THREAD

**Issue by oldTomatoCN** [chatchat-space/Langchain-Chatchat#2533]
1.在windows系统中进行pip install -r ./requirement.txt的时候会提示错误：

``
Building wheel for jq (pyproject.toml) did not run successfully.
This error originates from a subprocess, and is likely not a problem with pip
``
其实这个时候去看代码中requirement.txt这个文件告诉咱们要用conda去安装，不要用pip install 
我去官网https://pypi.org/project/jq/ 也找不到amd64的包，应该是不支持windows系统

最后使用的是
conda install jq
安装上了

**Comment by zRzRzRzRzRzRzR** [comment]
使用conda下载

**Comment by TianYin123** [comment]
你这已经安装成功了，接下来需要去requirements那个文件里面，把jq那一行删掉，重新pip requirements
