### ISSUE TITLE
utils.py[line:177] - ERROR: JSONDecodeError: 接口返回json错误： ‘: ping - 

### ISSUE THREAD

**Issue by tommickey2020** [chatchat-space/Langchain-Chatchat#2536]
问题描述 / Problem Description
0.2.9版本在用qwen-14b-int8模型进行问答时，在回答问题后，后端报错：ERROR: JSONDecodeError: 接口返回json错误
0.2.8版本在相同环境下，工作正常。

**复现问题的步骤 **
使用Qwen-14B-Chat-Int8模型，进行问答。

问题异常详细报错信息：
2024-01-03 16:15:03 | INFO | httpx | HTTP Request: POST http://xz-2080ti:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-03 16:15:18,494 - utils.py[line:177] - ERROR: JSONDecodeError: 接口返回json错误： ‘: ping - 2024-01-03 08:15:18.493163

’。错误信息是：Expecting value: line 1 column 1 (char 0)。

环境信息 / Environment Information

langchain-ChatGLM 版本/commit 号：0.2.9
是否使用 Docker 部署（是/否）：否
Python 版本 / Python version: 3.10.13

**Comment by GitYohoo** [comment]
我也是这个问题

**Comment by wvivi2023** [comment]
Chatglm3-6b 在和知识库对话时不管是es 还是faiss 向量库也都有这个问题

**Comment by hponiang** [comment]
+1

**Comment by wvivi2023** [comment]
docs = search_docs(query, knowledge_base_name, top_k, score_threshold)
        # docs = await run_in_threadpool(search_docs,
        #                                query=query,
        #                                knowledge_base_name=knowledge_base_name,
        #                                top_k=10,
        #                                score_threshold=score_threshold)
我把这个异步改成同步暂时解决了

**Comment by hponiang** [comment]
建议官方多考虑直接用在线模型的场景，这样很多体验的人能效率高些，在本地测试对机器没有配置要求，本地真是太难成功了

**Comment by zzflybird** [comment]
我也是Chatglm3-6b，也遇到了这个错误：`ERROR: JSONDecodeError: 接口返回json错误： ‘: ping - 2024-01-04 06:55:01.445879
’。错误信息是：Expecting value: line 1 column 1 (char 0)`

**Comment by zzflybird** [comment]
> docs = search_docs(query, knowledge_base_name, top_k, score_threshold) # docs = await run_in_threadpool(search_docs, # query=query, # knowledge_base_name=knowledge_base_name, # top_k=10, # score_threshold=score_threshold) 我把这个异步改成同步暂时解决了

我全局搜索`await run_in_threadpool`，发现有三处使用，分别是**文本向量化、知识库问答和搜索引擎**，**我只改了知识库问答的**，改为了`docs = search_docs(query, knowledge_base_name, top_k, score_threshold)`，但是还是报这个错误。

**Comment by nathubs** [comment]
0.2.9版本，chat 和 knowlage_base_chat 都会出现 : ping - 脏数据，有固定规律每15秒出现一次，和模型无关

如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/86149023/e5155d97-4620-4a1b-85e8-229c613c8909)

**Comment by xieyh** [comment]
我的也有这个问题，关注一下

**Comment by ghx2757** [comment]
自定义agent测试也有这问题
大模型：chatglm3

**Comment by nathubs** [comment]
找到原因了，sse_starlette包的问题，每隔15秒发一个心跳包
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/86149023/787a5ad1-7ab4-40c4-a8ba-5a0300ea4f73)

**Comment by sevenandseven** [comment]
> 问题描述 / Problem Description 0.2.9版本在用qwen-14b-int8模型进行问答时，在回答问题后，后端报错：ERROR: JSONDecodeError: 接口返回json错误 0.2.8版本在相同环境下，工作正常。
> 
> **复现问题的步骤 ** 使用Qwen-14B-Chat-Int8模型，进行问答。
> 
> 问题异常详细报错信息： 2024-01-03 16:15:03 | INFO | httpx | HTTP Request: POST http://xz-2080ti:20002/worker_generate_stream "HTTP/1.1 200 OK" 2024-01-03 16:15:18,494 - utils.py[line:177] - ERROR: JSONDecodeError: 接口返回json错误： ‘: ping - 2024-01-03 08:15:18.493163
> 
> ’。错误信息是：Expecting value: line 1 column 1 (char 0)。
> 
> 环境信息 / Environment Information
> 
> langchain-ChatGLM 版本/commit 号：0.2.9 是否使用 Docker 部署（是/否）：否 Python 版本 / Python version: 3.10.13
你好，我遇到了同样的问题，请问怎么解决？
