### ISSUE TITLE
部署langchain连接ES做本地化知识库的问题

### ISSUE THREAD

**Issue by menglong988** [chatchat-space/Langchain-Chatchat#2539]
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.8
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： es
- 操作系统及版本 linux的centOS
- Python 版本 3.10.12
- 其他相关环境信息 
- langchain版本0.0.334  fastchat版本0.2.32

**问题描述 / Problem Description**
部署langchain连接ES做本地化知识库的问题
python导入es的包版本为8.8.2，报错：error connecting to elasticsearch the client noticed that the server is not elasticsearch product
在es的包版本7.12中未报错这个问题，比较了两个版本的代码看到在新版本中增加了响应状态码的验证，把新增的状态码验证关掉后，在知识库提问时候又报错knn方面的问题如图
![Snipaste_2024-01-03_16-17-01](https://github.com/chatchat-space/Langchain-Chatchat/assets/87074604/d49e422d-7542-4dd0-900a-8049ad7fd8de)

查看了代码发现是post访问es的_search方法返回响应状态码400抛出的异常，是否是knn字段有问题，与es版本不支持，是否有官方指定的es包版本，可以避免这种问题
官方docs文件下的es部署文件里边用docker启动的命令用的是es包8.8.2版本，我使用出现的问题，请帮我核实下，谢谢

**Comment by menglong988** [comment]
最后发现，公司的运维人员搭的ES服务器是7.12版本的，ES在8.0以后得版本才支持knn相似性算法的API

**Comment by XMX199659** [comment]
> 最后发现，公司的运维人员搭的ES服务器是7.12版本的，ES在8.0以后得版本才支持knn相似性算法的API

请问您最后怎么解决这个问题啦？
