### ISSUE TITLE
[FEATURE] 可以支持 OpenAI 的模型嘛？比如 GPT-3、GPT-3.5、GPT-4；embedding 增加 text-embedding-ada-002

### ISSUE THREAD

**Issue by daz2yy** [chatchat-space/Langchain-Chatchat#254]
**功能描述 / Feature Description**
1. 增加 OpenAI 的 Key 配置，以及选择 OpenAI 的语言模型：GPT-3、GPT-3.5、GPT-4
2. 增加 OpenAI 的 embedding 模型：text-embedding-ada-002

**Comment by biiigwang** [comment]
期待🎉

**Comment by Lukangkang123** [comment]
要用openai的大模型的话，你直接用langchain就行了吧。这个项目本来就是为了本地化而做的。

**Comment by imClumsyPanda** [comment]
已在 0.2.0 版本中支持 openai 的 gpt api；并在 https://github.com/chatchat-space/Langchain-Chatchat/pull/1119 中支持 openai 的 embedding，目前已汇入 dev 分支，将跟随下一版本发布。
