### ISSUE TITLE
请问有colab版本吗

### ISSUE THREAD

**Issue by immmor** [chatchat-space/Langchain-Chatchat#2542]
ipnb的部署文件

**Comment by zRzRzRzRzRzRzR** [comment]
没有

**Comment by cwyalpha** [comment]
> ipnb的部署文件

https://github.com/cwyalpha/Langchain-Chatchat-Colab 
可以试试这个，0.2.10的版本支持以Qwen1.5-1.8B-Chat + bge-large-zh-v1.5 在colab免费版上部署

**Comment by changxu33** [comment]
> > ipnb的部署文件
> 
> https://github.com/cwyalpha/Langchain-Chatchat-Colab 可以试试这个，0.2.10的版本支持以Qwen1.5-1.8B-Chat + bge-large-zh-v1.5 在colab免费版上部署

为什么url 打不开 8501

**Comment by flag2fish** [comment]
> > > ipnb的部署文件
> > 
> > 
> > https://github.com/cwyalpha/Langchain-Chatchat-Colab 可以试试这个，0.2.10的版本支持以Qwen1.5-1.8B-Chat + bge-large-zh-v1.5 在colab免费版上部署
> 
> 为什么url 打不开 8501

我这边还在导入模型，然后卡住了，超过了内存限制
