### ISSUE TITLE
temperature的最大值有误

### ISSUE THREAD

**Issue by zzflybird** [chatchat-space/Langchain-Chatchat#2543]
问题：
`temperature = st.slider("Temperature：", 0.0, 2.0, TEMPERATURE, 0.05)` 中，`temperature`的最大值应该是1吧。

https://github.com/chatchat-space/Langchain-Chatchat/blame/3d66899b0f4bfaf230c1749e03c7f462cbae0d86/webui_pages/dialogue/dialogue.py#L227

**Comment by zRzRzRzRzRzRzR** [comment]
chatglm能到2
