### ISSUE TITLE
[BUG]langchain_core.exceptions.OutputParserException: Could not parse function call: 'function_call'

### ISSUE THREAD

**Issue by Mr1994** [chatchat-space/Langchain-Chatchat#2546]
**问题描述 / Problem Description**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15978040/41edd4d9-2ba3-4b4a-9725-0c3ced786efa)

基于langchain-chat的接口 进行格式化操作。上面是代码；但是会提示这个错误 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15978040/a941f9fa-4b0a-471a-820a-ca66e872dcf8)

**Comment by byp020322** [comment]
请问这个问题解决了吗
