### ISSUE TITLE
cannot import name 'tracing_enabled' from 'langchain_core.tracers.context'

### ISSUE THREAD

**Issue by johnny37** [chatchat-space/Langchain-Chatchat#2549]
版本0.2.9
执行python startup -a 后报错：如下
cannot import name 'tracing_enabled' from 'langchain_core.tracers.context'

![微信图片_20240104141729](https://github.com/chatchat-space/Langchain-Chatchat/assets/32920699/6ca76087-6993-493a-817e-0f2b8daa5fdb)

**Comment by 631952531** [comment]
依赖里提供的langchain版本不对
pip install langchain==0.0.354  解决

**Comment by johnny37** [comment]
> 依赖里提供的langchain版本不对 pip install langchain==0.0.354 解决

非常感谢，确实是提供的依赖版本不对，已解决。
