### ISSUE TITLE
[FEATURE] langchain_core.exceptions.OutputParserException: Could not parse function call: 'function_call'

### ISSUE THREAD

**Issue by Mr1994** [chatchat-space/Langchain-Chatchat#2551]
使用放openai 基于langchain二次开发的时候会提示这个错误哦 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15978040/7384e055-3569-4129-a69e-6fa64d35daa6)

这个是我的代码
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15978040/0203573a-413c-4eaf-a601-dfc1462ad2f4)
我对比了一下直接使用openai请求的时候返回内容是这样子的
[ChatGeneration(message=AIMessage(content='', additional_kwargs={'function_call': {'name': 'output_formatter', 'arguments': '{\n  "name": "阿旧",\n  "age": 18,\n  "fav_food": "胡萝卜"\n}'}}))]

如果是使用langchain-chat的仿openai api 时候 是这样子的 [ChatGeneration(text='信息提取结果如下：\n\n- 姓名：阿旧\n- 年龄：18岁\n- 喜好：胡萝卜', message=AIMessage(content='信息提取结果如下：\n\n- 姓名：阿旧\n- 年龄：18岁\n- 喜好：胡萝卜'))]
 少了  function_call  这个算是langchain-chat做放openai的的bug嘛~

**Comment by Mr1994** [comment]
那我应该如何把这个特性加上呢？

**Comment by zRzRzRzRzRzRzR** [comment]
这个仓库用的还是react，不支持openai的function call的
