### ISSUE TITLE
[FEATURE] 知识库名称支持中文

### ISSUE THREAD

**Issue by shenyaojun** [chatchat-space/Langchain-Chatchat#2556]
**功能描述 / Feature Description**
知识库名称支持中文

**解决的问题 / Problem Solved**
知识库名称支持中文，更符合中文环境下的使用体验

**实现建议 / Implementation Suggestions**
不知道，为啥不能支持中文呢

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
无

**Comment by shenyaojun** [comment]
确实，windows下faiss不支持中文目录的读写，看报错：
2024-01-05 10:51:52,432 - kb_api.py[line:37] - ERROR: RuntimeError: 创建知识库出错： Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:98: Error: 'f' failed: could not open C:\work\Langchain-Chatchat\knowledge_base\测试中文4\vector_store\text2vec\index.faiss for writing: No such file or directory

解决这个问题的思路是可以加个映射，路径里把中文映射成英文，不知道哪个大神可以改一下

**Comment by shenyaojun** [comment]
I made a quick fix on this, but i don't know if there are some side effects....

change this file : server\knowledge_base\utils.py

```python
# change to pinyin for chinese words
from pypinyin import lazy_pinyin
def get_kb_path(knowledge_base_name: str):
      
    return os.path.join(KB_ROOT_PATH, ''.join(lazy_pinyin(knowledge_base_name)))
```

**Comment by shenyaojun** [comment]
还要修改这个：
server\knowledge_base\kb_service\base.py

```python
# add for pinyin shenyaojun added
from pypinyin import lazy_pinyin

def get_kb_details() -> List[Dict]:
    kbs_in_folder = list_kbs_from_folder()
    kbs_in_db = KBService.list_kbs()
    result = {}

    for kb in kbs_in_folder:
        result[kb] = {
            "kb_name": kb,
            "vs_type": "",
            "kb_info": "",
            "embed_model": "",
            "file_count": 0,
            "create_time": None,
            "in_folder": True,
            "in_db": False,
        }

    for kb in kbs_in_db:
        kb_detail = get_kb_detail(kb)
        kb_pinyin = ''.join(lazy_pinyin(kb)) # shenyaojun added
        if kb_detail:
            kb_detail["in_db"] = True
            if kb in result:
                result[kb].update(kb_detail)
            else:  # shenyaojun added
                if kb_pinyin in result:  # shenyaojun added
                    del result[kb_pinyin]  # shenyaojun added
                    result[kb] = kb_detail # shenyaojun added
                else:
                    kb_detail["in_folder"] = False
                    result[kb] = kb_detail
```

**Comment by kvstone** [comment]
> 确实，windows下faiss不支持中文目录的读写，看报错： 2024-01-05 10:51:52,432 - kb_api.py[line:37] - ERROR: RuntimeError: 创建知识库出错： Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\impl\io.cpp:98: Error: 'f' failed: could not open C:\work\Langchain-Chatchat\knowledge_base\测试中文4\vector_store\text2vec\index.faiss for writing: No such file or directory
> 
> 解决这个问题的思路是可以加个映射，路径里把中文映射成英文，不知道哪个大神可以改一下

个人还有个更简单的想法，知识库的名字可以不用中文，但希望界面显示中文名称，是否可以在数据库加一个 knowledge_base_label 字段，也不影响现有代码运行

**Comment by zRzRzRzRzRzRzR** [comment]
会考虑

**Comment by Tina291** [comment]
> I made a quick fix on this, but i don't know if there are some side effects....
> 
> change this file : server\knowledge_base\utils.py
> 
> ```python
> # change to pinyin for chinese words
> from pypinyin import lazy_pinyin
> def get_kb_path(knowledge_base_name: str):
>       
>     return os.path.join(KB_ROOT_PATH, ''.join(lazy_pinyin(knowledge_base_name)))
> ```

这种方法会产生同音字问题
