### ISSUE TITLE
知识库问答中answer包含“<回答>”和</回答>，麻烦大佬尽快帮忙解决，谢谢~

### ISSUE THREAD

**Issue by Modas-Li** [chatchat-space/Langchain-Chatchat#2557]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/40042370/61876839-c497-4227-b7a7-73d4581a2563)

**Comment by Modas-Li** [comment]
> _🤖_
> 
> 你好，@Modas-Li！我是[Dosu](https://dosu.dev), 一个专门帮助你解决问题，回答相关疑问，以及在等待人工维护者的过程中提供帮助的机器人。我很高兴能为你提供服务。
> 
> 根据您提供的截图和描述，我理解您遇到的问题是在Langchain-Chatchat的知识库问答中，答案包含了“<回答>”和"</回答>"这样的标签。这可能是由于在生成答案的过程中，某些部分的代码没有正确地处理这些标签。
> 
> 在Langchain-Chatchat的代码库中，生成答案的方法主要取决于使用的模型。如果模型名称包含"chatglm3"，则使用`initialize_glm3_agent`函数创建一个代理执行器，该执行器用于生成响应。如果模型名称不包含"chatglm3"，则创建一个`LLMSingleActionAgent`，并从该代理和工具中创建一个`AgentExecutor`，该执行器用于生成响应。在这两种情况下，代理执行器都被用来异步调用查询并生成响应。响应然后被处理并返回。
> 
> 答案的格式化主要在`CustomOutputParser`类和`agent_chat_iterator`函数中进行。`CustomOutputParser`类用于解析语言模型的输出。`agent_chat_iterator`函数是一个异步生成器，它生成格式化的答案。格式化取决于从回调接收的数据的状态。如果状态是`Status.error`，它格式化错误消息。如果状态是`Status.tool_finish`，它格式化工具的输出。如果状态是`Status.agent_finish`，它生成最终答案。如果状态不是上述任何一种，它生成语言模型的令牌。
> 
> 根据这些信息，我猜测问题可能出在`agent_chat_iterator`函数中。可能在处理`Status.agent_finish`状态时，没有正确地处理“<回答>”和"</回答>"这样的标签。但是，由于我没有足够的上下文信息，我无法确定这是否是问题的确切原因。
> 
> 为了更好地解决您的问题，我需要更多的信息，例如错误发生的具体情况，以及您使用的具体模型和工具。如果可能的话，您能提供一些更具体的信息吗？例如，当问题发生时，您正在尝试执行什么操作？您使用的是哪个模型？您能提供一些导致问题的输入示例吗？
> 
> 这些信息将帮助我更好地理解和解决您的问题。期待您的回复，谢谢！
> 
> [参考代码](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/agent_chat.py)
> 
> -[Dosu](https://dosu.dev)
> 
> ## Sources
> * [server/chat/agent_chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/agent_chat.py)
> * [knowledge_base/samples/content/test_files/langchain-ChatGLM_open.jsonl](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.jsonl)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

使用的是chatglm3-6b模型

**Comment by zRzRzRzRzRzRzR** [comment]
这个很明显是模型没有理解模板，你是什么模型啊

**Comment by Modas-Li** [comment]
chatglm3-6b


------------------ 原始邮件 ------------------
发件人: zR ***@***.***&gt;
发送时间: 2024年1月11日 18:01
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: Modas Li ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [chatchat-space/Langchain-Chatchat] 知识库问答中answer包含“<回答&gt;”和</回答&gt;，麻烦大佬尽快帮忙解决，谢谢~ (Issue #2557)





 
这个很明显是模型没有理解模板，你是什么模型啊

**Comment by zRzRzRzRzRzRzR** [comment]
检查一下是不是更新到了最新的模型和配置文件 1.1号那版

**Comment by Modas-Li** [comment]
> 检查一下是不是更新到了最新的模型和配置文件 1.1号那版

升级过后仍然会出现该问题

**Comment by zRzRzRzRzRzRzR** [comment]
要不换一种提示词？，我这边是没有出现这个问题的，你换一个提示词写写看能不能能跑 其实只要保留 {{contnent}}

**Comment by zixiaotan21** [comment]
同样遇到这个问题，使用的模型是qwen-14B 想问问各位大佬解决了吗

**Comment by sevenandseven** [comment]
> 

你好，我跟你使用的是同样的模型，出现了同样的问题，这个怎么解决？
