### ISSUE TITLE
如何添加自定义模板，是不是只在prompt_config.py文件里添加是不够的，还要在其他文件中定义标签的转化吗？还有一个疑问是输入history的时候，是否需要按照prompt模板中定义的一样，将标签也输入呢？这里是否有自动提取标签的模块

### ISSUE THREAD

**Issue by zhouhangtju** [chatchat-space/Langchain-Chatchat#2563]

**Comment by zhouhangtju** [comment]
我这里面的chat_prompt如下
ChatPromptTemplate(input_variables=['context', 'question'], messages=[ChatMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='{% raw %}查询用户（用户名为zhangxiaoqi，用户id为159681732267）从2023年2月1号0点到2023年3月1号0点的用户体验情况,你要做的是返回一个调用api的命令，请求体中的key全部在知识库中{% endraw %}', template_format='jinja2'), role='user'), ChatMessagePromptTemplate(prompt=PromptTemplate(input_variables=[], template='{% raw %}第一步：查询到的url为"http://127.0.0.1:8080/"\n第二步：查询到的api的路由为"playback/Result/display"\n第三步：查询到的请求方式为"post"\n第四步：由第二步查询到的路由推断得到的请求体为{"查询开始时间":"2023020100","查询结束时间":"2023030100","用户名":"zhangxiaoqi","手机号":"15968173267"}\n第五步：由前四步推断，请求的命令为curl -X POST "http://127.0.0.1:8080/playback/Result/display" -H "Content-Type: application/json" -d \'{"查询开始时间": "2023020100","查询结束时间": "2023030100","用户名": "zhangxiaoqi","手机号": "15968173267"}\'\n第六步：返回命令 curl -X POST "http://127.0.0.1:8080/playback/Result/display" -H "Content-Type: application/json" -d \'{"查询开始时间": "2023020100","查询结束时间": "2023030100","用户名": "zhangxiaoqi","手机号": "15968173267"}\'\n{% endraw %}', template_format='jinja2'), role='assistant'), ChatMessagePromptTemplate(prompt=PromptTemplate(input_variables=['context', 'question'], template='<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，不允许在答案中添加编造成分，答案请使用中文。 </指令>\n<已知信息>{{ context }}</已知信息>\n<问题>{{ question }}</问题>\n', template_format='jinja2'), role='user')])
这里面默认的prompt模板和history并不匹配，暴力的放在一起会不会有问题，是否要更换模板或者更换历史信息的提问方式

**Comment by zRzRzRzRzRzRzR** [comment]
不用啊，就是在prompt_config里改
