### ISSUE TITLE
pip install -r requirements.txt时报错Could not build wheels for jq, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by Mr-wangerniu** [chatchat-space/Langchain-Chatchat#2566]
pip install -r requirements.txt报错Could not build wheels for jq, which is required to install pyproject.toml-based projects

Building wheels for collected packages: jq
  Building wheel for jq (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for jq (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      Executing: ./configure CFLAGS=-fPIC --prefix=C:\Users\wang\AppData\Local\Temp\pip-install-r3womazv\jq_34b87edfc7a7412fb35c5509d35272d6\_deps\build\onig-install-6.9.8
      error: [WinError 2] 系统找不到指定的文件。
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jq
Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects

**Comment by zRzRzRzRzRzRzR** [comment]
先用conda 安装jq 在装req
