### ISSUE TITLE
同时上传多个doc文件时出错

### ISSUE THREAD

**Issue by SSTato** [chatchat-space/Langchain-Chatchat#2583]
当同时上传的.doc文件数量超过一个，也就是大于等于2时，file2docs中的loader.load()会卡住。
```
    def file2docs(self, refresh: bool = False):
        if self.docs is None or refresh:
            logger.info(f"{self.document_loader_name} used for {self.filepath}")
            loader = get_loader(loader_name=self.document_loader_name,
                                file_path=self.filepath,
                                loader_kwargs=self.loader_kwargs)
            self.docs = loader.load()
        return self.docs
```
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/93987794/4d50e07b-eb87-4962-8bd8-69467c3904d8)

我尝试上传别的文件是没有问题的，多个jpg+docx+1个doc是可以的，只要doc文件的数量超过一个就会有问题，这是什么原因。

**Comment by liunux4odoo** [comment]
处理 doc 文档时要调用系统安装的程序，可能是多线程同时调用造成了问题。可以转成 docx 或 pdf 再试试。

**Comment by SSTato** [comment]
> 处理 doc 文档时要调用系统安装的程序，可能是多线程同时调用造成了问题。可以转成 docx 或 pdf 再试试。

docx和pdf都没问题，单独一个doc也没问题，只有多个doc有问题，所以很疑惑。如果有可能的话还是解决一下吧。

**Comment by zRzRzRzRzRzRzR** [comment]
估计是线程调度的问题，因为这里是单线程的，这个我们考虑在后续版本解决
