### ISSUE TITLE
[FEATURE] 新的分词器的支持

### ISSUE THREAD

**Issue by orikey0** [chatchat-space/Langchain-Chatchat#2584]
**功能描述 / Feature Description**
现在的中文分词器用在中英文or中文 代码混杂的case中使用起来比较差

**解决的问题 / Problem Solved**
主要是本地文档中 会有一些 sql文档 / 数据库表子段定义文档，没有使用markdown格式定义，此时在向量数据库中进行相似度查询 召回效果较差

**实现建议 / Implementation Suggestions**
如果说一个文档英文字符占比超过 90%（拍脑袋想的） 或者识别出是有大量的代码块 保留前后一行中文 并且完整保留 代码块

**替代方案 / Alternative Solutions**
目前我在公司内部落地的是首先使用标题增强，然后对于匹配度较高的文档直接召回文档，而不是召回分片，效果提升比较明显

**其他信息 / Additional Information**

**Comment by orikey0** [comment]
> **功能描述 / Feature Description** 现在的中文分词器用在中英文or中文 代码混杂的case中使用起来比较差
> 
> **解决的问题 / Problem Solved** 主要是本地文档中 会有一些 sql文档 / 数据库表子段定义文档，没有使用markdown格式定义，此时在向量数据库中进行相似度查询 召回效果较差
> 
> **实现建议 / Implementation Suggestions** 如果说一个文档中英文字符占比超过 90%（拍脑袋想的） 或者识别出是有大量的代码块 保留前后一行中文 并且完整保留 代码块
> 
> **替代方案 / Alternative Solutions** 首先使用标题增强，然后对于匹配度较高的文档直接召回文档，而不是召回分片
> 
> **其他信息 / Additional Information**

另外感觉是否可以支持一些对召回结果在进行精排或者精确度评估的工具，现在召回的文档感觉精确度不是很高 ，比如搜索问题：红包SQL策略查询，会匹配到一些其他无关的策略

**Comment by zRzRzRzRzRzRzR** [comment]
分词功能主要由社区进行PR，开发组不会主动维护
