### ISSUE TITLE
文档分片结果怎么查看

### ISSUE THREAD

**Issue by lichuan-JD** [chatchat-space/Langchain-Chatchat#2587]
对文档分段完成后的文本有存数据库吗，不知道是否有： 文档名，文档片段，embedding的数据

**Comment by pessimo** [comment]
上面AI的回答好像不太对。 他回答的是 search_engine_chat.py 里面的内容，实际上应该看 knowldge_base_chat.py 里面的内容，我前几天研究了下，文档切分之后的 meta_data 没有保存页数。 也就是说以pdf举例，其实并没有保存分段前的页码。 所以，如果要做这个需要去修改 server/knowledge_base/utils.py 里面的 filee2docs 相关函数。 或者就是干脆搜出来之后做个全文检索。

**Comment by zRzRzRzRzRzRzR** [comment]
数据库保存在db中了，本身就是个向量数据库

**Comment by pessimo** [comment]
> 数据库保存在db中了，本身就是个向量数据库

以pdf文本为例，数据库中有存储分段文本所在页面信息吗？就是页码 我不知道我是否有看对。。。麻烦大佬解答

**Comment by zRzRzRzRzRzRzR** [comment]
没有，不会有页面
