### ISSUE TITLE
[BUG] 初始化数据库 python init_database.py --recreate-vs 报错/ couldn't find  config.json.

### ISSUE THREAD

**Issue by Dont666** [chatchat-space/Langchain-Chatchat#2588]
**问题描述 / Problem Description**
执行python init_database.py --recreate-vs 后报错：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11209643/51320f24-b346-4976-9abf-6c64032632d2)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本 0.2.9
- 
- 是否使用 Docker 部署：否
- 使用的模型：智浦API 
- 使用的 Embedding 模型：moka-ai/m3e-base 
- 使用的向量库类型 ： faiss
- 操作系统及版本 : CENTOS7
- Python 版本 : 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
目录结构如下：
![a752b112943f7d487db1018c86ad5e1](https://github.com/chatchat-space/Langchain-Chatchat/assets/11209643/9ecbb52e-0102-4fc6-a979-01c5c8e04b93)

**Comment by zRzRzRzRzRzRzR** [comment]
知识库位置一定要放在 knowledge_base/i你的名字/content 中
