### ISSUE TITLE
将model_config里的"model_name"改为"gpt-4", 调用的是gpt-3

### ISSUE THREAD

**Issue by HansShih** [chatchat-space/Langchain-Chatchat#2589]
在model_config里初始"model_name": "gpt-3.5-turbo", 调用的是gpt-3.5-turbo

但将"model_name"改为"gpt-4", 调用的却是gpt-3，是有别的地方需要修改吗？

**Comment by Yuyu7777777777777** [comment]
> 在model_config里初始"model_name": "gpt-3.5-turbo", 调用的是gpt-3.5-turbo
> 
> 但将"model_name"改为"gpt-4", 调用的却是gpt-3，是有别的地方需要修改吗？

调用gpt4成功了吗？为什么报JSONDecodeError的错误？
