### ISSUE TITLE
[FEATURE] 增加ollama方式支持本地模型

### ISSUE THREAD

**Issue by permanzh** [chatchat-space/Langchain-Chatchat#2592]
**功能描述 / Feature Description**
本地模型增加ollama方式支持，参考quvir实现

**解决的问题 / Problem Solved**
本地部署模型方便，且调用模型接口统一，可支持Ollama生态众多模型

**实现建议 / Implementation Suggestions**
参考quvir

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
无

**Comment by zRzRzRzRzRzRzR** [comment]
0.3.x开始本地模型会有新的load方式，不再绑定，大家可以自己加载

**Comment by sci268** [comment]
期待这个功能实现，毕竟Ollama的运行效率很好，同样的显卡，能跑的模型更大，langchain-chatchat的特色是知识库+助手，ollama方式可以强化助手功能

**Comment by KevinFanng** [comment]
ollama支持bge-large-zh-v1.5吗？如果不支持，ollama怎么解决EMBEDDING_MODEL？
