### ISSUE TITLE
企业用户在autodl里面的v13镜像一直卡在网页初始化界面

### ISSUE THREAD

**Issue by 871052165** [chatchat-space/Langchain-Chatchat#2594]
**问题描述 / Problem Description**
企业用户在autodl里面的v13镜像一直卡在网页初始化界面

**复现问题的步骤 / Steps to Reproduce**
1. 按照启动步骤执行启动
2. 点击自定义服务
3. 问题出现 / Problem occurs
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/27c46017-f59c-41da-bf96-392b65586df9)

**预期的结果 / Expected Result**
正常载入

**实际结果 / Actual Result**
卡在初始化

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.9版本，v13镜像
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge lag zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu 20.4
- Python 版本 / Python version:镜像提供

**Comment by 871052165** [comment]
新版本startup.py的写法都不一样了，机器人说的方法不适用
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/f15b09d8-048f-4fed-94f0-7993be9ef70a)

**Comment by zRzRzRzRzRzRzR** [comment]
这个估计是代理的问题吧，你启动6006端口？

**Comment by 871052165** [comment]
> 这个估计是代理的问题吧，你启动6006端口？
是的，启动了6006端口

**Comment by zRzRzRzRzRzRzR** [comment]
那估计是ngix的问题了autodl不应该出现这种问题的，确定是127.0.0.1:6006

**Comment by 871052165** [comment]
> 那估计是ngix的问题了autodl不应该出现这种问题的，确定是127.0.0.1:6006

我新开了一个实例，好了，确定是autodl的实例问题
