### ISSUE TITLE
m1，请问在生成回答时怎么看是否使用了mps or cpu？

### ISSUE THREAD

**Issue by ReefJones** [chatchat-space/Langchain-Chatchat#260]
m1，请问在生成回答时怎么看是否使用了mps or cpu？
我的好慢啊，知识库上传了1个5 kb的txt，
然后问了一个五六个字的问题，生成答案时半小时才出20多个字，这正常吗？

**Comment by imClumsyPanda** [comment]
默认支持mps时会直接调用mps，可以用import torch，torch.backends.mps.is_available() 进行校验

**Comment by Veken** [comment]
你的M1在安装环境以后，有出现过模型加载未成功的提示吗？问答就是报这个异常：
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'

**Comment by Veken** [comment]
> m1，请问在生成回答时怎么看是否使用了mps or cpu？ 我的好慢啊，知识库上传了1个5 kb的txt， 然后问了一个五六个字的问题，生成答案时半小时才出20多个字，这正常吗？
你的M1在安装环境以后，有出现过模型加载未成功的提示吗？问答就是报这个异常：
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'
