### ISSUE TITLE
This model's maximum context length is 2048 tokens.

### ISSUE THREAD

**Issue by diana1919zhong** [chatchat-space/Langchain-Chatchat#2600]
**问题描述 / Problem Description**
langchain-cahtchat V0.2.9 
使用模型是：Azure-openai

**复现问题的步骤 / Steps to Reproduce**
1. 调用Agent功能时候报错： This model's maximum context length is 2048 tokens. However, your messages resulted in 3503 tokens.

**附加信息 / Additional Information**
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 2048 tokens. However, your messages resulted in 3503 tokens. Please reduce the length of the messages.", 'code': 40303}
2024-01-10 14:36:22,694 - utils.py[line:27] - ERROR: BadRequestError: Caught exception: Error code: 400 - {'object': 'error', 'message': "This model's maximum context length is 2048 tokens. However, your messages resulted in 3503 tokens. Please reduce the length of the messages.", 'code': 40303}

**Comment by Camelia9704** [comment]
你是用远程API调用模型的吗，是的话可以先确认参数里的max_tokens对不对，然后试试创建model worker的时候设一下context_len这个变量，看/server/model_workers/base.py第100行，ApiModelWorker中context_len的默认值是2048

**Comment by diana1919zhong** [comment]
> 你是用远程API调用模型的吗，是的话可以先确认参数里的max_tokens对不对，然后试试创建model worker的时候设一下context_len这个变量，看/server/model_workers/base.py第100行，ApiModelWorker中context_len的默认值是2048

感谢，更改context_len后，成功运行
