### ISSUE TITLE
[BUG] 使用conda安装jq库之后，仓库仍然无法使用jq库。

### ISSUE THREAD

**Issue by ItsFated** [chatchat-space/Langchain-Chatchat#2605]
**问题描述 / Problem Description**
如题，以下是截图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13051752/e74f82a8-ee28-474c-b889-2434db073abe)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 conda install jq
2. 确认安装 conda list jq
3. 检验效果 python -c "import jq; print(type(jq))"
4. 报错：ModuleNotFoundError: No module named 'jq'

**预期的结果 / Expected Result**
导入jq库，并打印：<class 'module'>

**实际结果 / Actual Result**
报错：ModuleNotFoundError: No module named 'jq'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：448c99f969f22c23abcf3ec1b8646dad73d15960
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss-gpu
- 操作系统及版本 / Operating system and version: Windows 10
- Python 版本 / Python version: Python 3.10.13
- 其他相关环境信息 / Other relevant environment information: conda 23.11.0

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
你确定成功安装了啊 pip 或者conda list一下安装的库

**Comment by tomdogs1** [comment]
**问题描述** 
使用conda install jq 成功后，在python中import jq时，依然报ModuleNotFoundError: No module named 'jq'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42016093/58559570-ef55-4b5d-9d37-73ae60913e22)

**复现问题的步骤/重现步骤**
执行 conda install jq
确认安装conda list jq
检验效果 python -c "import jq; print(type(jq))"
报错：ModuleNotFoundError: 没有名为“jq”的模块

**预期的结果**
导入jq库，并打印：<class 'module'>

**实际结果** 
报错：ModuleNotFoundError: No module named 'jq'

**环境信息** 
langchain-ChatGLM 版本/提交号：0.2.09
是否使用Docker部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
使用的Embedding模型（moka-ai/m3e-base 等）：bge-large-zh
使用的支持库类型 (faiss / milvus / pg_vector 等)： faiss-gpu
操作系统及版本 / 操作系统及版本: Windows 10
Python版本/Python版本：Python 3.10.13
其他相关环境信息 / 其他相关环境信息：conda 23.11.0

**执行过程**
安装`conda install jq`
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42016093/bd1cd14b-1aa6-4a80-8aa7-3e19c9bc940e)

查看'conda list'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42016093/fbf8eac8-3a52-4e2d-bc7c-e594577bdb9e)

**Comment by Zhaibeiebi** [comment]
同样的问题，似乎没有解决啊。conda install之后在conda list里面能看到jq，但是import就会报错，没有这个库

**Comment by Zhaibeiebi** [comment]
> 同样的问题，似乎没有解决啊。conda install之后在conda list里面能看到jq，但是import就会报错，没有这个库

搞了一下午，才明白jq是不能在win上import的，最多搞个c++编译器命令行调用。有哪位大神可以解决不能import jq的问题吗
