### ISSUE TITLE
pdf文件添加到faiss向量库报错

### ISSUE THREAD

**Issue by Chopin-Xiao** [chatchat-space/Langchain-Chatchat#2608]
**问题描述 / Problem Description**
使用的百度在线API，创建知识库（faiss）后导入pdf文件时报错：

ERROR: RuntimeError: 从文件 Shanghai Online-Offline//mnt/storage/Langchain-Chatchat/knowledge_base/Shanghai Online-Offline/content/xxxxxx.pdf 加载文档时出错：Directory 'static/' does not exist

faiss组件faiss-cpu和faiss-gpu都下载过，版本分别是1.7.4和1.7.2

本人是Java开发，对python的相关问题不甚了解，望各位大佬帮忙指导指导

**Comment by zRzRzRzRzRzRzR** [comment]
如果是个别的pdf是ocr中的问题
