### ISSUE TITLE
[FEATURE] 能否支持本地的API调用

### ISSUE THREAD

**Issue by QYCin2020** [chatchat-space/Langchain-Chatchat#2609]
比如说我本地以openai的格式启动了一个大模型，如何让chatchat用这个api呢？这个api是开在本地localhost里的
首先我确保我这个api符合openai的格式，在别的项目里可以实现无缝切换

谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
直接替换掉openai就行了，openai那个base_url改成你自己
