### ISSUE TITLE
[FEATURE] 希望新增对system messages的支持

### ISSUE THREAD

**Issue by IgnoranceSmile** [chatchat-space/Langchain-Chatchat#2610]
**功能描述 / Feature Description**
对system message进行修改可以大幅度提升知识问答的精度，希望能够支持

**Comment by shenyaojun** [comment]
刚想写这个提议。+1
最好做在prompt的template里。

**Comment by zRzRzRzRzRzRzR** [comment]
不是所有的模型都有系统提示的，在fschat中也没有做成系统提示吧，等0.3.x我们重写会有的
