### ISSUE TITLE
怎么加载多个本地模型？

### ISSUE THREAD

**Issue by zhuhaifengaaa** [chatchat-space/Langchain-Chatchat#2615]
LLM_MODELS = ["chatglm3-6b", "Qwen-14B-Chat", "zhipu-api"] 
设置多个模型参数，智能加载一个本地模型和最后一个api模型
请问怎么加载多个本地模型？

**Comment by zRzRzRzRzRzRzR** [comment]
现在不就是全部加载吗，多个本地模型都加载
