### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by allen781105** [chatchat-space/Langchain-Chatchat#2618]
**问题描述 / Problem Description**
知识库问答结果在页面上会带上：
<指令>根据已知信息，简洁和专业的回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”。</指令> 
有的结果里面也会包含<|user|> 这种标签；
有的知识库问答有这种情况，有的没有，这个问题该如何解决？

**Comment by zRzRzRzRzRzRzR** [comment]
如果你是最新的chatglm3-6b （1.1日之后）的应该没有这个问题了
