### ISSUE TITLE
consult     agent_chat为什么会出现我没有的知识库名字？

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2619]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/138666362/cd461f15-56a2-442c-a02c-73366eecdc57)
我想知道左边栏红框里的这三种search_knowledgebase.py有什么区别？为什么lines中会出现我没有的知识库名字，如果出现我没有的知识库名字，搜索知识库的时候会找不到知识库导致无法根据知识库生成内容。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/138666362/2ae9ea81-329f-42e8-b28e-cbf463ab5dff)

**Comment by maxusheng123** [comment]
> _🤖_
> 
> 你好 @maxusheng123! 👋 我是 [Dosu](https://dosu.dev),一个自动化的助手。我可以帮助你解决问题、回答疑问，甚至帮你成为贡献者。在等待人类维护者的同时，我在这里为你提供帮助。很高兴遇见你！
> 
> 根据我在Langchain-Chatchat仓库中找到的信息，`search_knowledgebase_simple.py`脚本用于搜索知识库以回答给定的查询。这个脚本定义了两个主要的函数：`search_knowledge_base_iter`和`search_knowledgebase_simple`。
> 
> `search_knowledge_base_iter`函数是一个异步函数，它接收一个数据库名称和一个查询作为输入。它使用`knowledge_base_chat`模块中的`knowledge_base_chat`函数来搜索知识库中的查询。该函数使用了一些参数，如`model_name`、`temperature`、`history`、`top_k`、`max_tokens`、`prompt_name`、`score_threshold`和`stream`来自定义搜索。然后，该函数遍历响应体，加载JSON数据，并提取与查询相关的答案和文档。
> 
> `search_knowledgebase_simple`函数是一个包装函数，它使用`asyncio.run`方法运行`search_knowledge_base_iter`函数。它接收一个查询作为输入，并返回`search_knowledge_base_iter`函数的结果。
> 
> 脚本还包括一个主执行块，它使用一个样本查询运行`search_knowledgebase_simple`函数并打印结果。
> 
> 关于您提到的其他两种`search_knowledgebase.py`脚本的功能，我在仓库中没有找到相关信息。可能是我遗漏了，或者答案可能在其他地方。
> 
> 至于为什么`lines`中会出现您没有的知识库名字，这可能是因为在搜索知识库时，脚本可能会尝试搜索所有可用的知识库，包括那些您可能没有的知识库。如果出现您没有的知识库名字，搜索知识库的时候可能会找不到知识库，从而无法根据知识库生成内容。这可能是一个需要解决的问题，或者可能需要在搜索知识库时指定正确的知识库名称。
> 
> 如果您需要更多的帮助，或者有更多的信息可以提供，我会很乐意帮助您。
> 
> ## Sources
> * [server/agent/tools/search_knowledgebase_simple.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/search_knowledgebase_simple.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

我该用search_knowledgebase_complex还是search_knowledgebase_once？这取决于什么？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/138666362/c048af0b-5146-4b57-8001-b542df572652)

**Comment by zRzRzRzRzRzRzR** [comment]
模型意图识别的问题，模型自己编造了一个知识库估计，毕竟这边的是开放的，匹配的内容还是模型自己生成
