### ISSUE TITLE
输入Chatchat WEBUI Server: http://127.0.0.1:8501到浏览器显示无法访问此网站

### ISSUE THREAD

**Issue by darkdepth** [chatchat-space/Langchain-Chatchat#2622]
**问题描述 / Problem Description**
输入Chatchat WEBUI Server: http://127.0.0.1:8501到浏览器显示无法访问此网站.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a'
2. 没有报错
4. 问题出现：输入Chatchat WEBUI Server: http://127.0.0.1:8501到浏览器显示无法访问此网站.

**Comment by tommyvinny** [comment]
用DOCKER吧。环境构建太麻烦了。。。
看样子是在model_config.py里面没调整。本机运行应该要在里面修改0.0.0.0为127.0.0.1

**Comment by liyiyiya** [comment]
> 用DOCKER吧。环境构建太麻烦了。。。 看样子是在model_config.py里面没调整。本机运行应该要在里面修改0.0.0.0为127.0.0.1

兄弟，model_config.py里我没有找到修改的地方呀
