### ISSUE TITLE
跟agent_chat对话时，当agent_chat调用到knowledge_base_chat时,Request会是None

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2626]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/138666362/64b8e96d-0fdd-4e36-aa39-a3caa1bc52b7)
图中的request如果为None的话是没有base_url属性的，会报错。
直接跟知识库对话，request不是None，但是如果通过agent对话调到知识库对话时，request就会是None，但是这是不允许的，想知道怎么调整能让它不为None？

**Comment by CyanMystery** [comment]
@dosu-bot agent_executor.acall方法，该方法负责生成聊天机器人对用户输入的响应 但是为什么返回的数据时候是遍历async for chunk in callback.aiter():这个东西，这个和 agent_executor.acall返回的结果一样吗？

**Comment by zRzRzRzRzRzRzR** [comment]
不一样，agent excutor内其实有访问llmchain

**Comment by CyanMystery** [comment]
那我想返回agent_executor.acall这个结果怎么实现啊   我单独调试两个结果完全不一样  非要asyncio.create_task在里边不懂怎么整

**Comment by zRzRzRzRzRzRzR** [comment]
这个你可以只鹅几单独跑langchain了，在这里我们是封装好的，而且是移步的是没有办法调试的

**Comment by Alfer-Feng** [comment]
> 这个你可以只鹅几单独跑langchain了，在这里我们是封装好的，而且是异步的是没有办法调试的

有个疑问，不能直接同步chat直接生成结果吗？看了项目的代码都是异步的。
我想一个异步函数里，实现调用两次同步的大模型回答。

**Comment by GuoJuan911** [comment]
兄弟 咨询一下  最后是如何处理的呢？

**Comment by ELvis168** [comment]
可以这样用吗

**Comment by jhw0510** [comment]
答主没有说这个是怎么解决的，可以参考我的解决方法：
报错原因：这个应该是个小bug，在使用agent调用知识库回答问题时，会调用“knowledge_base/download_doc”的api，默认api 的url地址是http://localhost:7861/knowledge_base/download_doc，具体代码可以看/server/chat/knowledge_base_chat.py里面parameters参数，然后接下来是base_url，本来应该是可以获取本地的url地址，但是代码以及调试可以看出，原本的代码“base_url = request.base_url”中，request是None，因此会报错“NoneType' object has no attribute 'base_url”。
解决方法：简便点的，直接在http://localhost:7861   api里面查看你的url地址（默认应该是http://localhost:7861/   ，不知道的可以直接试试），然后把原本的“base_url = request.base_url”改为你自己的url地址（例如http://192.168.1.19:7861/），应该就解决了。

具体流程可以参考我的issue#3132
