### ISSUE TITLE
python start.py -a启动卡住

### ISSUE THREAD

**Issue by JenniferLiu-Tech** [chatchat-space/Langchain-Chatchat#2631]
![error](https://github.com/chatchat-space/Langchain-Chatchat/assets/69226247/d5fdf681-e166-419b-a3aa-d52b3922f32a)

**Comment by zRzRzRzRzRzRzR** [comment]
配置不够带不动吧

**Comment by JenniferLiu-Tech** [comment]
> 配置不够带不动吧，看到你是CPU

那这个项目需要多少配置呀？

**Comment by zRzRzRzRzRzRzR** [comment]
wiki有写
