### ISSUE TITLE
想问下 知识库格式要怎么传

### ISSUE THREAD

**Issue by ciaoyizhen** [chatchat-space/Langchain-Chatchat#2632]
我看别的issue说知识说一行是一条知识？
那比如我的docx中他换行了，还会被分到一起吗？
比方说我有下面的知识：
操作流程如下：
1. xxx
2. xxx
3. xxx

我是否需要将这几个写在一起？

**Comment by zRzRzRzRzRzRzR** [comment]
不，这是按照字数来切割的

**Comment by ciaoyizhen** [comment]
> 不，这是按照字数来切割的

按照字数切割是什么意思？   是有点像yolo的极大抑制那种选择知识吗？
