### ISSUE TITLE
调用Agent功能时候，经常显示： is not a valid tool。只有很少的时候，Agent才能正常调用

### ISSUE THREAD

**Issue by diana1919zhong** [chatchat-space/Langchain-Chatchat#2634]
**问题描述 / Problem Description**
调用Agent功能时候，经常显示： is not a valid tool。只有很少的时候，Agent才能正常调用

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/148304362/e6e40ed7-eb65-422d-ba0b-ab7f18c50bfb)

是为什么呢

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.x的Agent是老的Agent，效果比较差

**Comment by diana1919zhong** [comment]
> 0.2.x的Agent是老的Agent，效果比较差

现在有新的Agent了吗

**Comment by zRzRzRzRzRzRzR** [comment]
新的Agent没写完，0.2.10会优化一下，但是估计还是无法完成复杂工具，Agent目前还是建议使用GPT4

**Comment by diana1919zhong** [comment]
> 新的Agent没写完，0.2.10会优化一下，但是估计还是无法完成复杂工具，Agent目前还是建议使用GPT4

目前使用的是GPT-4，会出现上面的情况

**Comment by zRzRzRzRzRzRzR** [comment]
> > 新的Agent没写完，0.2.10会优化一下，但是估计还是无法完成复杂工具，Agent目前还是建议使用GPT4
> 
> 目前使用的是GPT-4，会出现上面的情况

我刚才试了一下，是没有的，比较奇怪

**Comment by diana1919zhong** [comment]
> > > 新的Agent没写完，0.2.10会优化一下，但是估计还是无法完成复杂工具，Agent目前还是建议使用GPT4
> > 
> > 
> > 目前使用的是GPT-4，会出现上面的情况
> 
> 我刚才试了一下，是没有的，比较奇怪

我使用的是微软GPT-4的API。
直接调用会有问题，然后修改了server -> model_workers -> azure.py -> AzureWorker中的do_chat方法，如下，会是跟这个有关系吗：
    def do_chat(self, params: ApiChatParams) -> Dict:
        params.load_config(self.model_names[0])
        try:
            client = AzureOpenAI(
                api_version=params.api_version,
                api_key=params.api_key,
                azure_endpoint=f"https://{params.resource_name}.openai.azure.com",
            )

            completion = client.chat.completions.create(
                model=params.deployment_name,
                messages=params.messages,
            )

            for choice in completion.choices:
                text = choice.message.content
                yield {"error_code": 0, "text": text}
        except Exception as e:
            print(f'Error in do_chat: {e}')
            return {"error_code": 1, "text": str(e)}

**Comment by diana1919zhong** [comment]
问题已解决，和上面的代码没有关系

**Comment by zhuohuaKing** [comment]
这个问题解决了吗？我也碰到这个问题

**Comment by zhuohuaKing** [comment]
> **问题描述 / Problem Description** 调用Agent功能时候，经常显示： is not a valid tool。只有很少的时候，Agent才能正常调用
> 
> ![image](https://private-user-images.githubusercontent.com/148304362/296109887-e6e40ed7-eb65-422d-ba0b-ab7f18c50bfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTk0MjYsIm5iZiI6MTcxMzE1OTEyNiwicGF0aCI6Ii8xNDgzMDQzNjIvMjk2MTA5ODg3LWU2ZTQwZWQ3LWViNjUtNDIyZC1iYTBiLWFiN2YxOGM1MGJmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwNTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2RlZWU4ZTNmMzQ2N2I3Mjc4NWNmNDZhOGZkNjkxNWU1NDdhOGUyZWMwNjc0OTJkYmFmMmU3YmMxYzQ1NTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8k8DMKkUsHumxjxfrHM88NaQ-J4gOK7rWSPHxB_w1rM)
> 
> 是为什么呢

你好，这个问题解决了吗？我也碰到这个问题
