### ISSUE TITLE
[BUG] v0.2.9添加文件到知识库，处理超时

### ISSUE THREAD

**Issue by Liuyanglong** [chatchat-space/Langchain-Chatchat#2641]
**问题描述 / Problem Description**
1、添加文件到知识库，处理超时，调用的接口为：/knowledge_base/upload_docs，超时时间已经设置为10000，上传文件为800KB的txt文档。
2、在上传期间，其他接口请求均hangup 超时，如/knowledge_base/list_knowledge_bases。

**复现问题的步骤 / Steps to Reproduce**
命令行命令：
curl --location --request POST 'http://127.0.0.1:7861/knowledge_base/upload_docs' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--form 'files=@"/Users/fxzk/Downloads/xaa.txt"' \
--form 'knowledge_base_name="faisslib"' \
--form 'override="true"' \
--form 'to_vector_store="true"' \
--form 'chunk_size="250"' \
--form 'chunk_overlap="50"'

**预期的结果 / Expected Result**
顺利上传成功
**实际结果 / Actual Result**
超时失败
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-7B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version: CentOS Linux release 7.9.2009 (Core)
- Python 版本 / Python version: Python 3.11.5
- 其他相关环境信息 / Other relevant environment information:

**Comment by zolibra** [comment]
遇到相同问题，换了几个embedding模型都不好用，感觉是向量库没有初始化成功，info.db里没有任何信息
os环境：mac M1

**Comment by Liuyanglong** [comment]
`其中，https://github.com/chatchat-space/Langchain-Chatchat/issues/1287这个问题的解决方案是在server/knowledge_base/utils.py的105行下面加上两行代码，让spacy启用gpu来做词义分析，速度比cpu快上千倍。代码如下：

text_splitter._tokenizer.max_length = 37016792
text_splitter._tokenizer.prefer_gpu()`

这个改动基于0.2.9版本应该在哪里加？

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="767" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/93239683/ac0eecdd-d02e-46a3-a5b3-8aee033d8fbd">

而且，只有spacy有个这个功能

**Comment by Liuyanglong** [comment]
改了没有用，该hangup还是hangup

**Comment by Liuyanglong** [comment]
@zolibra  请问最后解决了吗？ 加代码依然不好用

**Comment by zRzRzRzRzRzRzR** [comment]
hangup就是数据库没有初始化成功

**Comment by zolibra** [comment]
> 吗？ 加

没，感觉cpu就是各种问题，各种慢，换到cuda上就快很多了
