### ISSUE TITLE
[BUG] 调用阿里通义千问"qwen-api" 时候，阿里说，接口没有provider参数。

### ISSUE THREAD

**Issue by halfman2016** [chatchat-space/Langchain-Chatchat#2643]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
https://github.com/chatchat-space/Langchain-Chatchat/ 我用这个。model_config.py里面，# 阿里云通义千问 API，文档参考 https://help.aliyun.com/zh/dashscope/developer-reference/api-details
    "qwen-api": {
        "version": "qwen-turbo",  # 可选包括 "qwen-turbo", "qwen-plus"
        "api_key": "sk-94d954a****************87fcb731bf74",  # 请在阿里云控制台模型服务灵积API-KEY管理页面创建
        "provider": "
",
        "embed_model": "text-embedding-v1" # embedding 模型名称
    },有这一段，这里要求写provider

阿里说，接口没有provider参数。

于是通义千问联不上。
有知道的吗？
用最新版代码‘
ubuntu环境运行

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到类似问题，是这么配置的吗
<img width="993" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/93239683/6db5242d-1287-454a-82d3-8abab9b160a8">

我刚才这样运是没有问题的
