### ISSUE TITLE
Agent调用多工具的问题

### ISSUE THREAD

**Issue by diana1919zhong** [chatchat-space/Langchain-Chatchat#2655]
**问题描述 / Problem Description**
一个任务需要Agent调用2个工具，第1个工具的结果，作为第二个工具的输入。

上面的场景使用下来，发现调用第一个工具是正常的，但是将结果作为第二个工具的输入时，Agent直接模拟第二个工具的功能并给出回复，但是并没有真正的调用第二个工具，请问这种情况该如何让Agent能成功调用第二个工具呢

使用版本：langchain-chatchat V0.2.9    
使用模型：GPT-4

**Comment by zRzRzRzRzRzRzR** [comment]
GPT4应该是能连续执行不同的工具的，如果直接输出了大概率是模型没有理解，直接以为得到答案了，工具连续调用在0.2.x 系列对连续工具调用做的并不好，在0.3.x中要进行彻底改进
