### ISSUE TITLE
0.3.0 意见征集

### ISSUE THREAD

**Issue by zRzRzRzRzRzRzR** [chatchat-space/Langchain-Chatchat#2661]
## 即将更新
随着 LangChain 0.1.x 的更新和 LLM 技术的迭代，`Langchain-Chatchat 0.2.x` 已经无法满足日益增长的入门实战需求。

随着 `Langchain-Chatchat 0.2.10` 的发布，`0.2.x` 内容将不再进行维护和支持。

我们预计会在 2024 Q1 推出 **Langchain-Chatchat 0.3.0**.

如果你对这个话题感兴趣，请到讨论区

https://github.com/chatchat-space/Langchain-Chatchat/discussions/2660

提出！本Issue不讨论

**Comment by lunalulu** [comment]
增加上下文扩充开关（qwen-14B-chat/qwen-14B-chat-int4）

**Comment by lunalulu** [comment]
增加batch推理（qwen-14B-chat/qwen-14B-chat-int4）

**Comment by yuanzui0728** [comment]
RAG
