### ISSUE TITLE
为啥我文件传不上去，报错：AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by lewisliuyi** [chatchat-space/Langchain-Chatchat#2662]
一切运行都很正常，之前也都是好的，但是这两天传什么都文件，页面都是显示403：

<img width="420" alt="ed840c09581f54a797048c8b3f4b556" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/98192649/7c08f488-4b2d-45e1-8f5c-ae923cecb0cc">

**Comment by zRzRzRzRzRzRzR** [comment]
后台阻塞了吧，你代码有改吗（包括更新）

**Comment by lewisliuyi** [comment]
我更新到0.2.9之后这个问题解决了，但是用了没多久又出现了，服务器重启都没有用，怎么回事，这个是啥的问题，是streamlit的问题是吧，登录次数过多有影响吗，重装能解决吗

**Comment by zRzRzRzRzRzRzR** [comment]
streamlit是一个演示工具，各种工业生产要求达不到，bug很多。。

**Comment by lewisliuyi** [comment]
哎呀，终于解决了，更新就好了：pip install --upgrade streamlit

**Comment by wzhty86** [comment]
> 哎呀，终于解决了，更新就好了：pip install --upgrade streamlit

能否查看一下，你装的是哪个版本？

**Comment by murdonson** [comment]
> 哎呀，终于解决了，更新就好了：pip install --upgrade streamlit

thanks for your reply

**Comment by heidongqilin** [comment]
我用老版本问题从解决  pip install streamlit==1.28.*

**Comment by chunshengding** [comment]
同问

**Comment by adiligentpiggy** [comment]
https://wqmoran.com/streamlit-axioserror-status-code-403-solution/
