### ISSUE TITLE
知识库匹配阈值SCORE_THRESHOLD为什么设置[0,2]而不是[0,1]呢，标准是什么呢，怎样调整SCORE_THRESHOLD更合理呢？

### ISSUE THREAD

**Issue by qianbaidu1266** [chatchat-space/Langchain-Chatchat#2663]
kb_config中SCORE_THRESHOLD 设置默认值为1：

# 知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右
SCORE_THRESHOLD = 1

knowledge_base_chat方法里面，SCORE_THRESHOLD 设置取值范围为[0,2]:

    score_threshold: float = Body(
                                  SCORE_THRESHOLD,
                                  description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右",
                                  ge=0,
                                  le=2
                              ),

**Comment by ShinyWey** [comment]
#2197

**Comment by qianbaidu1266** [comment]
那么，为什么使用bge模型向量化时，阈值会超过1呢，我个人理解知识库匹配阈值SCORE_THRESHOLD，不应该是归一化处理过的吗，为什么会有超过1的情况呢？
