### ISSUE TITLE
关于初始化或者切换模型代码实现

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2665]
请问模型的加载或者切换实现是在此处吗？  q.put  ，所以是用shell cmd命令实现的？ 

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/0e908f95-bcb8-4749-b81b-d0b8260f3d8f)

如果不是的话    我在langchain项目里没找到模型的切换方法，类似像transformer那样的启动方法：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/0cde79ce-a4e2-4c5b-b112-2afbeaa8cbce)

请求大佬解答

**Comment by zRzRzRzRzRzRzR** [comment]
切换模型相当于执行fschat，这些读入的内容都在fscaht内

**Comment by 948024326** [comment]
> 切换模型相当于执行fschat，这些读入的内容都在fscaht内

好的感谢
