### ISSUE TITLE
调用/knowledge_base/update_docs返回docs的json类型错误

### ISSUE THREAD

**Issue by panpeng840715** [chatchat-space/Langchain-Chatchat#2666]
请求参数：
{
  "knowledge_base_name": "123456",
  "file_names": [
    "1.txt"
  ],
  "chunk_size": 250,
  "chunk_overlap": 50,
  "zh_title_enhance": false,
  "override_custom_docs": false,
  "docs": {
    "1.txt": [
      {
        "page_content": "测试更新内容",
        "metadata": {},
        "type": "Document"
      }
    ]
  },
  "not_refresh_vs_cache": false
}

返回结果：
{
  "detail": [
    {
      "loc": [
        "body",
        "docs"
      ],
      "msg": "JSON object must be str, bytes or bytearray",
      "type": "type_error.json"
    }
  ]
}

**Comment by panpeng840715** [comment]
我把/knowledge_base/update_docs端点的docs: JSON改成docs: Dict 问题解决

**Comment by zhangt-run** [comment]
请问改完dict，然后是把dict再转为document格式吗
