### ISSUE TITLE
GPU显存占用问题

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2668]
我在加载了模型问答后，随着我问答的次数增多，GPU的显存会一直慢慢增加，我在其他框架并没有出现这种情况，都是固定的，请问这是什么原因？
![4852477ac531f6b4b87cd4973782db3](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/1f4c69c0-9a80-4e77-9345-8e264780594f)

**Comment by zRzRzRzRzRzRzR** [comment]
按照常理，定期清理历史是不会有这个问题的

**Comment by 948024326** [comment]
> 按照常理，定期清理历史是不会有这个问题的

不好意思，没在项目里面找到这部分的代码诶，可以帮忙贴一下吗，感谢

**Comment by zRzRzRzRzRzRzR** [comment]
项目里确实没有这个代码，但是你可以把历史设置为0，或者直在UI清空历史

**Comment by 948024326** [comment]
> 项目里确实没有这个代码，但是你可以把历史设置为0，或者直在UI清空历史

好的
