### ISSUE TITLE
[BUG] 不能访问http://0.0.0.0:8501

### ISSUE THREAD

**Issue by chensisi0730** [chatchat-space/Langchain-Chatchat#2669]
**问题描述 ：不能访问http://0.0.0.0:8501**
运行LOG：
(langc$ python startup.py -a-38243-6488bdb9b4-cj2l5:/mnt/workspace/langchain-ChatGLM# $ python startup.py -a
bash: $: 未找到命令
(langcain_ChatGLM) root@dsw-38243-6488bdb9b4-cj2l5:/mnt/workspace/langchain-ChatGLM# $ python startup.py -a
2024-01-15 21:54:48,188 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:54:50,185 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-15 21:54:50,478 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
2024-01-15 21:54:50,479 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-01-15 21:54:50,479 - startup.py[line:651] - INFO: 正在启动服务：
2024-01-15 21:54:50,479 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /mnt/workspace/langchain-ChatGLM/logs
2024-01-15 21:54:52,662 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:54:55,218 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:54:55 | INFO | model_worker | Register to controller
2024-01-15 21:54:55,712 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:54:55,757 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:54:56 | ERROR | stderr | INFO:     Started server process [2174]
2024-01-15 21:54:56 | ERROR | stderr | INFO:     Waiting for application startup.
2024-01-15 21:54:56 | ERROR | stderr | INFO:     Application startup complete.
2024-01-15 21:54:56 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-01-15 21:54:56 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 60dbd8a0 ...
Loading checkpoint shards:   0%|                          | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|██▌               | 1/7 [00:09<00:55,  9.30s/it]
Loading checkpoint shards:  29%|█████▏            | 2/7 [00:20<00:51, 10.32s/it]
Loading checkpoint shards:  43%|███████▋          | 3/7 [00:31<00:42, 10.54s/it]
Loading checkpoint shards:  57%|██████████▎       | 4/7 [00:41<00:31, 10.41s/it]
Loading checkpoint shards:  71%|████████████▊     | 5/7 [00:52<00:21, 10.64s/it]
Loading checkpoint shards:  86%|███████████████▍  | 6/7 [01:03<00:10, 10.71s/it]
Loading checkpoint shards: 100%|██████████████████| 7/7 [01:09<00:00,  9.12s/it]
Loading checkpoint shards: 100%|██████████████████| 7/7 [01:09<00:00,  9.87s/it]
2024-01-15 21:56:56 | ERROR | stderr | 
2024-01-15 21:57:09 | INFO | model_worker | Register to controller
2024-01-15 21:57:11,847 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
INFO:     Started server process [2253]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
2024-01-15 21:57:17,950 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-15 21:57:18,235 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
2024-01-15 21:57:18,236 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： bge-large-zh @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

**Comment by zRzRzRzRzRzRzR** [comment]
改成127 试试 0.0.0.0的话Linux才行

**Comment by liyiyiya** [comment]
> **问题描述 ：不能访问http://0.0.0.0:8501** 运行LOG： (langc$ python startup.py -a-38243-6488bdb9b4-cj2l5:/mnt/workspace/langchain-ChatGLM# $ python startup.py -a bash: $: 未找到命令 (langcain_ChatGLM) root@dsw-38243-6488bdb9b4-cj2l5:/mnt/workspace/langchain-ChatGLM# $ python startup.py -a 2024-01-15 21:54:48,188 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:54:50,185 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
> 
> ==============================Langchain-Chatchat Configuration============================== 操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35. python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] 项目版本：v0.2.9 langchain版本：0.0.354. fastchat版本：0.2.34
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter 2024-01-15 21:54:50,478 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda {'device': 'cuda', 'host': '0.0.0.0', 'infer_turbo': False, 'model_path': 'THUDM/chatglm3-6b', 'port': 20002} {'api_key': '', 'device': 'auto', 'host': '0.0.0.0', 'infer_turbo': False, 'online_api': True, 'port': 21001, 'provider': 'ChatGLMWorker', 'version': 'chatglm_turbo', 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>} {'api_base_url': 'https://api.openai.com/v1', 'api_key': '', 'device': 'auto', 'host': '0.0.0.0', 'infer_turbo': False, 'model_name': 'gpt-3.5-turbo', 'online_api': True, 'openai_proxy': '', 'port': 20002} 2024-01-15 21:54:50,479 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 当前Embbedings模型： bge-large-zh @ cuda ==============================Langchain-Chatchat Configuration==============================
> 
> 2024-01-15 21:54:50,479 - startup.py[line:651] - INFO: 正在启动服务： 2024-01-15 21:54:50,479 - startup.py[line:652] - INFO: 如需查看 llm_api 日志，请前往 /mnt/workspace/langchain-ChatGLM/logs 2024-01-15 21:54:52,662 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:54:55,218 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:54:55 | INFO | model_worker | Register to controller 2024-01-15 21:54:55,712 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:54:55,757 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:54:56 | ERROR | stderr | INFO: Started server process [2174] 2024-01-15 21:54:56 | ERROR | stderr | INFO: Waiting for application startup. 2024-01-15 21:54:56 | ERROR | stderr | INFO: Application startup complete. 2024-01-15 21:54:56 | ERROR | stderr | INFO: Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit) 2024-01-15 21:54:56 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker 60dbd8a0 ... Loading checkpoint shards: 0%| | 0/7 [00:00<?, ?it/s] Loading checkpoint shards: 14%|██▌ | 1/7 [00:09<00:55, 9.30s/it] Loading checkpoint shards: 29%|█████▏ | 2/7 [00:20<00:51, 10.32s/it] Loading checkpoint shards: 43%|███████▋ | 3/7 [00:31<00:42, 10.54s/it] Loading checkpoint shards: 57%|██████████▎ | 4/7 [00:41<00:31, 10.41s/it] Loading checkpoint shards: 71%|████████████▊ | 5/7 [00:52<00:21, 10.64s/it] Loading checkpoint shards: 86%|███████████████▍ | 6/7 [01:03<00:10, 10.71s/it] Loading checkpoint shards: 100%|██████████████████| 7/7 [01:09<00:00, 9.12s/it] Loading checkpoint shards: 100%|██████████████████| 7/7 [01:09<00:00, 9.87s/it] 2024-01-15 21:56:56 | ERROR | stderr | 2024-01-15 21:57:09 | INFO | model_worker | Register to controller 2024-01-15 21:57:11,847 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 2024-01-15 21:57:15,436 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto INFO: Started server process [2253] INFO: Waiting for application startup. INFO: Application startup complete. INFO: Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit) 2024-01-15 21:57:17,950 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
> 
> ==============================Langchain-Chatchat Configuration============================== 操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35. python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0] 项目版本：v0.2.9 langchain版本：0.0.354. fastchat版本：0.2.34
> 
> 当前使用的分词器：ChineseRecursiveTextSplitter 2024-01-15 21:57:18,235 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda {'device': 'cuda', 'host': '0.0.0.0', 'infer_turbo': False, 'model_path': 'THUDM/chatglm3-6b', 'port': 20002} {'api_key': '', 'device': 'auto', 'host': '0.0.0.0', 'infer_turbo': False, 'online_api': True, 'port': 21001, 'provider': 'ChatGLMWorker', 'version': 'chatglm_turbo', 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>} {'api_base_url': 'https://api.openai.com/v1', 'api_key': '', 'device': 'auto', 'host': '0.0.0.0', 'infer_turbo': False, 'model_name': 'gpt-3.5-turbo', 'online_api': True, 'openai_proxy': '', 'port': 20002} 2024-01-15 21:57:18,236 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto 当前Embbedings模型： bge-large-zh @ cuda
> 
> 服务端运行信息： OpenAI API Server: http://127.0.0.1:20000/v1 Chatchat API Server: http://127.0.0.1:7861 Chatchat WEBUI Server: http://0.0.0.0:8501 ==============================Langchain-Chatchat Configuration==============================
> 
> Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.
> 
> You can now view your Streamlit app in your browser.
> 
> URL: http://0.0.0.0:8501

兄弟最后你是怎么解决的呀

**Comment by songxiaoxiao** [comment]
咋解决的呢
