### ISSUE TITLE
[BUG] 0.2.9版本samples (faiss @ bge-large-zh)知识库，csv和jpg文件添加至向量库失败

### ISSUE THREAD

**Issue by BingerOne** [chatchat-space/Langchain-Chatchat#2671]
【环境配置】
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-87-generic-x86_64-with-glibc2.35.
python版本：3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
项目版本：v0.2.9
langchain版本：0.0.334. fastchat版本：0.2.32

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-3.5-turbo',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

【BUG描述】
无论是使用命令（python init_database.py --recreate-vs）重建知识库，还是从WEB页面选择csv和jpg文件都会出现添加至向量库失败的情况。
csv文件：1	test_files_langchain-ChatGLM_closed.csv；
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32097973/6162bc43-347f-4c5a-ad50-e0a0a3ea1b35)

jpg文件：23	llm_img_大模型技术栈-算法与原理-幕布图片-299768-254064.jpg；
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32097973/84b0b889-204d-4eba-a682-593750d30e72)

**Comment by zRzRzRzRzRzRzR** [comment]
这个报错看上去怎么是模型没下呢，为什么访问hf

**Comment by BingerOne** [comment]
@zRzRzRzRzRzRzR 从环境信息里面就可以看出模型肯定是已经下载并正常运行的，至于这里为啥还有警告不太清楚

**Comment by zRzRzRzRzRzRzR** [comment]
环境信息跟模型没有关系，模型是要单独下载的
