### ISSUE TITLE
[ASK] 想请教一下本地向量知识库Faiss的用法

### ISSUE THREAD

**Issue by Zengfanxu1111** [chatchat-space/Langchain-Chatchat#2676]
我在webui新建了知识库后上传了制知识文件，文件是txt格式的，文件内容格式如下：
‘’‘
头痛，低烧，检查是新型隐球菌脑膜炎？头痛，低烧，检查是新型隐球菌脑膜炎。
口服抗病毒药物和感冒冲剂试试.有炎症还是应该加上抗生素。口服药物不见效的，建议输液治疗为好。在当地医生指导下使用。有痰的加上鲜竹沥口服试试。如果发烧还需要适当加上额外的退烧药物。

甲亢会影响怀孕吗？甲亢怀孕有什么危险？怀孕的适合能治疗么？
病情分析:如果怀孕期间发现甲亢,处理时既要控制甲亢的发展,又要保证胎儿的正常生长.需要严格做好产前检查,因为甲亢孕妇容易使胎儿早产,死胎,胎儿宫内发育不良以及并发妊高征等.另外定期检查血清中的总甲状腺素的水平,目前有观点认为该激素水平高于正常值的1.4倍才考虑用药物.丙基硫氧嘧啶为妊娠期间的首选药物,但剂量要小,而且控制症状后减成维持量,通过这样的适当治疗,轻,中度的甲亢患者的症状一般能得到很好的控制.不过预产期前3周内最好不用药物,此过程中除非出现严重的并发症如心脏病或高血压等,才考虑终止妊娠.甲亢病
’‘’

下面是控制台打印的文档切分示例：
‘’‘
文档切分示例：page_content='病情描述发病时间、主要症状、症状变化等）：经常腰疼，双腿无力，没有精神，手淫频繁，射精太快，这是肾虚吗？\n这种情况可能是由于手淫过度，导致的肾精不足，肾阴亏虚的问题建议使用中药治疗，常用的药物有六
地黄汤，左归丸等，平时注意休息，尽量戒除手淫\n颈3/4,4/5,5/6,6/7椎肩盘突出，脊髓受压变形，腰椎肩盘突出，相应水平黄韧带肥厚，下腰段椎管狭窄。，下腿无力，走路不稳，无，怎么治疗\n您好！建议您可以到正规医院采用微创针刀治疗，效   
果不错。\n往裤子里滴尿是怎么回事，吃点什么药\n你好，您的情况主要考虑是前列腺炎的可能，主要症状是尿后滴白，建议您去医院做下检查，确诊疾病，对症治疗，平时注意饮食，合理休息' metadata={'source': 'E:\\pythonworkspace\\Langchain-Chatchat\\knowledge_base\\medical\\content\\extracted_conversations.txt'}
’‘’
想请教一下我直接上传可以么，是否需要对数据再做一些预处理？

**Comment by Zengfanxu1111** [comment]
![Uploading QQ截图20240116155005.png…]()

**Comment by zRzRzRzRzRzRzR** [comment]
可以自己做预处理，直接上传默认按照字符进行切割
