### ISSUE TITLE
[FEATURE] 如何接入CustomLLM？

### ISSUE THREAD

**Issue by cauwulixuan** [chatchat-space/Langchain-Chatchat#2677]
**功能描述 / Feature Description**
目前只有FastChat支持列表里的LLM才可以接入进来。现在我想试用一个新的模型，没在支持列表里存在，应该如何接入？

**解决的问题 / Problem Solved**

**实现建议 / Implementation Suggestions**
项目是否有CustomLLM的计划？或者除了往FastChat中提pr接入新模型外，还有哪种方式可以快速接入一个新的模型？

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
另外，请问FastChat和vLLM两个项目都要集成才可以接入新模型吗？

**Comment by zRzRzRzRzRzRzR** [comment]
转成openai的格式接入

**Comment by cauwulixuan** [comment]
> 转成openai的格式接入

能详细一点吗？能否出个官方demo或者tutorial？谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
这个会在0.3.x开放，但是大概率不会有时间做demo，要开发者自行尝试
