### ISSUE TITLE
zhipu-api轻量版本，知识库问答报错‘未找到相关文档,该回答为大模型自身能力解答！’

### ISSUE THREAD

**Issue by lcdisme** [chatchat-space/Langchain-Chatchat#2682]
==============================Langchain-Chatchat Configuration==============================
操作系统：macOS-10.16-x86_64-i386-64bit.
python版本：3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['zhipu-api'] @ mps
{'api_key': '',
 'device': 'mps',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'chatglm_turbo',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
当前Embbedings模型： zhipu-api @ mps

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501

配置如上，和llm对话正常，和知识库问答，所有的提问都显示‘未找到相关文档,该回答为大模型自身能力解答！’，即使提问是知识库中的原话也这样。score_threshold调整到最小和最大都试了，没有效果，请专家支持一下！

<img width="820" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/46395989/ccb2c452-137e-4b1c-aade-5cfc3e31367e">
<img width="965" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/46395989/abb4d877-ab2f-407f-8908-09bd1a1c4efd">

**Comment by zRzRzRzRzRzRzR** [comment]
这个就是没找到内容，知识库搜到0条内容

**Comment by zRzRzRzRzRzRzR** [comment]
你可以打印出来检索的内容，如果是空，就是没有检索到，为什么没有检索到可能就是参数和文件类型问题了

**Comment by lcdisme** [comment]
> 你可以打印出来检索的内容，如果是空，就是没有检索到，为什么没有检索到可能就是参数和文件类型问题了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46395989/29e47f6e-235c-4a62-8612-7d0f925112df)

应该是这里的问题，默认传入的distance_strategy是metric_inner_product,改为MAX_INNER_PRODUCT可以了

**Comment by zixiaotan21** [comment]
同遇到这个问题，想问问楼主，你最后一张图片是在哪个文件的呀
