### ISSUE TITLE
[FEATURE]Langchain-chatchat 支持以Api接口的方式调用其他应用模型吗

### ISSUE THREAD

**Issue by qianbaidu1266** [chatchat-space/Langchain-Chatchat#2683]
目前langchian-chatchat  在model_config.py文件中配置LLM的 秘钥实现调用大模型，支持调用其他应用的api接口吗，有大佬尝试过配置api 接口调用其他应用吗，如果不支持接口配置的方式，就需要自己定义新的前后端接口来调用第三方的api接口了吧？目前想尝试通过Langchain-chatchat 调用 Dify的服务

**Comment by zRzRzRzRzRzRzR** [comment]
支持，但是你需要自己写fastchatworker

**Comment by qianbaidu1266** [comment]
> 支持，但是你需要自己写fastchatworker
fastchatworker是啥，有样例吗

**Comment by cauwulixuan** [comment]
同问，新的LLM等项目挨个适配太慢了，maintainer能不能出一个官方demo，如何接入新的LLM？

**Comment by Donovan-Ye** [comment]
> > 支持，但是你需要自己写fastchatworker
> > fastchatworker是啥，有样例吗

看起来是在[configs/server_config.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/d83de508cc8d09fc3ddbf0ef8672ab26b545552f/configs/server_config.py.example#L35)和[server/model_workers](https://github.com/chatchat-space/Langchain-Chatchat/tree/master/server/model_workers)里写自己的worker。

**Comment by zRzRzRzRzRzRzR** [comment]
是的，我们会在之后的版本陆续移除单个模型的支持，转而让想使用非主流模型的模型转变为openai格式进行输入，这样可以减少项目的复杂度，同时统一适配格式

**Comment by Yangshirui01** [comment]
太需要官方出一个模板来适配私有的http大模型服务，跪求

**Comment by Yangshirui01** [comment]
想使要http方式调用私有的大模型服务，有没有教程怎么完成，谢谢
