### ISSUE TITLE
显存相关

### ISSUE THREAD

**Issue by yph0925** [chatchat-space/Langchain-Chatchat#2684]
A10 24G使用chatglm3-6B，大概能够满足什么量级的用户数量正常使用？
多个用户同时提问会导致显存占用明显增大吗？

**Comment by 948024326** [comment]
我也想问

**Comment by zRzRzRzRzRzRzR** [comment]
本框架面向入门使用，没有设计并发，所以用户量非常少，10个就极限了

**Comment by yph0925** [comment]
> _🤖_
> 
> 你好 @yph0925！我是[Dosu](https://dosu.dev)，一个可以帮助你解决问题、回答问题并成为贡献者的机器人。在等待人类维护者的同时，我在这里为你提供帮助。非常高兴能为你提供服务！
> 
> 关于A10 24G使用ChatGLM 3-6B模型能够满足的用户数量，我在Langchain-Chatchat的仓库中没有找到具体的答案。这可能需要根据模型的具体内存占用以及并发处理能力来评估。你可能需要进行一些实际的性能测试来确定这个问题。
> 
> 至于多个用户同时提问是否会导致显存占用明显增大，Langchain-Chatchat通过使用单一模型实例并使用asyncio Semaphore来管理并发来处理多个同时的用户查询。这是从提供的`ApiModelWorker`类中可以看出的。
> 
> 在`ApiModelWorker`类的`__init__`方法中，创建了一个由`limit_worker_concurrency`参数定义的限制的Semaphore：
> 
> ```python
> self.semaphore = asyncio.Semaphore(self.limit_worker_concurrency)
> ```
> 
> `limit_worker_concurrency`参数默认设置为5：
> 
> ```python
> kwargs.setdefault("limit_worker_concurrency", 5)
> ```
> 
> Semaphore是一个同步原语，它在并发系统中控制多个进程对公共资源的访问。它用于限制可以向模型发出的同时请求的数量。这意味着Langchain-Chatchat使用单一模型实例来处理所有查询，但它将同时查询的数量限制为`limit_worker_concurrency`的值。
> 
> 因此，多个用户同时提问不会导致显存占用明显增大，因为Langchain-Chatchat使用的是单一模型实例来处理所有查询，并通过Semaphore来限制同时处理的查询数量。
> 
> 参考源代码：
> 
> * [server/model_workers/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/base.py)
> 
> ## Sources
> * [server/model_workers/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

在线api和本地模型都受limit_worker_concurrency的限制吗？limit_worker_concurrency可以调大吗？会有什么影响

**Comment by yph0925** [comment]
@dosu-bot 在线api和本地模型都受limit_worker_concurrency的限制吗？limit_worker_concurrency可以调大吗？会有什么影响？

**Comment by zRzRzRzRzRzRzR** [comment]
问题应该不是卡在limit_worker_concurrency，而是卡在载入数据的地方
