### ISSUE TITLE
[BUG] 使用VLLM加载模型偶遇生成速度慢的情况

### ISSUE THREAD

**Issue by Victoriaheiheihei** [chatchat-space/Langchain-Chatchat#2687]
**问题描述 / 使用VLLM加载模型偶遇生成速度慢的情况
用简洁明了的语言描述这个问题 / 大多数情况生成速度都会比直接使用fastchat快，偶尔遇到页面提示
INFO 01-17 10:06:40 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 0.5%, CPU KV cache usage: 0.0%
INFO 01-17 10:06:45 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.4 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 2.4%, CPU KV cache usage: 0.0%
INFO 01-17 10:06:50 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 36.9 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 4.4%, CPU KV cache usage: 0.0%
INFO 01-17 10:06:55 llm_engine.py:624] Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.5%, CPU KV cache usage: 0.0%

目前vllm参数设置如下：
使用4张gpu加载两个模型，每个模型的gpu_memory_utilization都为0.45
'tokenizer_mode':'auto',
        'trust_remote_code':True,
        'download_dir':None,
        'load_format':'auto',
        'dtype':'auto',
        'seed':0,
        'worker_use_ray':True,
        'pipeline_parallel_size':1,
        'tensor_parallel_size':4,
        'block_size':16,
        'swap_space':4 , # GiB
        'gpu_memory_utilization':0.45,
        'max_num_batched_tokens':None,
        'max_num_seqs':256,
        'disable_log_stats':False,
        'conv_template':"guanlan-chat",
        'limit_worker_concurrency':5,
        'no_register':False,
        'num_gpus': 4,
        'engine_use_ray': False,
        'disable_log_requests': False

**Comment by Victoriaheiheihei** [comment]
为什么会有下面这个提示呢？
Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 37.0 tokens/s, Running: 1 reqs, Swapped: 0 reqs, Pending: 0 reqs, GPU KV cache usage: 6.5%, CPU KV cache usage: 0.0%

**Comment by zRzRzRzRzRzRzR** [comment]
这个是vllm的提示，不是项目的
