### ISSUE TITLE
[FEATURE] 关于tests/api下一些test文件的用法

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2689]
我想请问下，这里面的test_xx的函数算法，是要怎么调用？  或者说，和swagger里的chat/chat接口有什么区别吗？、
假设我在其他项目中调用这个chat/chat接口需要怎么调用呢

![c84e1cf885827b73b7b4efd8fd1acec](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/117b4750-036b-4c3c-baaf-d8212d87db7f)

**Comment by zRzRzRzRzRzRzR** [comment]
这个test代码是当时开发人员测试能否调通用的，实际项目中其实没有用到，另外，0.3.x开始，api会重写

**Comment by 948024326** [comment]
> 这个test代码是当时开发人员测试能否调通用的，实际项目中其实没有用到，另外，0.3.x开始，api会重写 如何调用API，可以在部署成功后的7860中查看

好的
