### ISSUE TITLE
[BUG] 特定txt格式文档解析错误Error tokenizing data

### ISSUE THREAD

**Issue by mario2rio** [chatchat-space/Langchain-Chatchat#2690]
**问题描述 / Problem Description**
处理txt文档解析报错，导致向量化失败，完整错误日志
ERROR: ParserError: 从文件 /Langchain-Chatchat-0.2.8/knowledge_base/1111/content/text.txt 加载文档时出错：Error tokenizing data. C error: Expected 13 fields in line 2, saw 17

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：V0.2.8
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等） ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Ubuntu 22.04.1 LTS
- Python 版本 / Python version: Python 3.10.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information** 原始TXT文件如附件
[text.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/13959446/text.txt)

添加与问题相关的任何其他信息 / Add any other information related to the issue.
如果删除文本中Last year, 这里的逗号，文档解析成功

**Comment by zRzRzRzRzRzRzR** [comment]
应该是这个符号没有在词表或者刚好在这里截断出现问题

**Comment by mario2rio** [comment]
> 应该是这个符号没有在词表或者刚好在这里截断出现问题

你好，这看起来是一个普通的符号，一个英文逗号和空格。碰巧验证了一下，文本中Last year, 这组词复制一份到文本开头，文本解析就能成功，因此这个符号是在词表内的，那么有可能是因为截断的原因，这样的问题该如何解决或规避呢？

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题有点罕见了，每次都是这个地方出错的话，或许是并不是因为`,` 而是还有其他内容一起出现阶段出现，或许可以查看这里
https://towardsdatascience.com/fix-pandas-parser-error-tokenizing-data-889167292d38
因为我也没有遇到过，不太能给出解决办法

**Comment by cuichenxu** [comment]
It seems that your txt file contains Chinese and English punctuation marks, Unifying them may help you!
