### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain'

### ISSUE THREAD

**Issue by xzl12080** [chatchat-space/Langchain-Chatchat#2693]
大佬，想请问一下，我本来是可以成功启动项目，api和web都成功的，然后我换了个conda虚拟环境，重新安装依赖，web就出现这个错误了ModuleNotFoundError: No module named 'langchain'，具体错误源是这样的File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/home/xzl/RAG_LLM/Langchain-Chatchat/webui.py", line 2, in <module>
    from webui_pages.utils import *
File "/home/xzl/RAG_LLM/Langchain-Chatchat/webui_pages/utils.py", line 8, in <module>
    from configs import (
File "/home/xzl/RAG_LLM/Langchain-Chatchat/configs/__init__.py", line 1, in <module>
    from .basic_config import *
File "/home/xzl/RAG_LLM/Langchain-Chatchat/configs/basic_config.py", line 3, in <module>
    import langchain
我检查了一下langchain是安装了的，api界面是没有问题的

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到过相关问题，你的依赖版本和req一样吗

**Comment by xzl12080** [comment]
您好,上面的问题已经解决了，谢谢您，我还有个问题，就是我发现添加了一个大概300页的word文档进知识库，我一共测试了30个query发现只有五六个能够检索到知识库文档信息，其他的都是根据模型自身能力回答的，这是检索这个环节出了问题还是llm模型本身的问题呢，大佬有什么办法可以调优吗 @zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
检索出问题，`根据模型自身能力回答`是工程上在找不到知识库的时候固定返回的内容，解决方案的话可以在微信群里多聊，wiki上给了思路

**Comment by Belonger** [comment]
@xzl12080 您好，怎么解决的，我也遇到了相同的bug，如何解决呢
