### ISSUE TITLE
动态调用知识库检索功能

### ISSUE THREAD

**Issue by promisecc** [chatchat-space/Langchain-Chatchat#2694]
在做知识库检索前通过一个agent判断是否需要进行检索，如果阈值够高则LLM直接输出答案，否则在向量库中检索知识块
感觉有时候LLM本来知道答案的，检索玩反而会答错

**Comment by zRzRzRzRzRzRzR** [comment]
这个已经做了，在agentchat内，目前只有gpt4能做，0.3.x会做这个功能

**Comment by ELvis168** [comment]
希望早点实现，用agent能自动调知识库，工具，llm该多好
