### ISSUE TITLE
No module named 'fastchat'

### ISSUE THREAD

**Issue by justmore5mins** [chatchat-space/Langchain-Chatchat#2695]
我執行了python startup.py -a 的指令，然後跑出一段
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\chat_models\__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\llms\__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
2024-01-17 17:34:55,160 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\langchain\document_loaders\__init__.py:36: LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.document_loaders import JSONLoader`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Langchain-Chatchat\startup.py", line 39, in <module>
    from server.knowledge_base.migrate import create_tables
  File "D:\Langchain-Chatchat\server\knowledge_base\migrate.py", line 11, in <module>
    from server.knowledge_base.kb_service.base import KBServiceFactory
  File "D:\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 29, in <module>
    from server.embeddings_api import embed_texts, aembed_texts, embed_documents
  File "D:\Langchain-Chatchat\server\embeddings_api.py", line 3, in <module>
    from server.model_workers.base import ApiEmbeddingsParams
  File "D:\Langchain-Chatchat\server\model_workers\__init__.py", line 1, in <module>
    from .base import *
  File "D:\Langchain-Chatchat\server\model_workers\base.py", line 1, in <module>
    from fastchat.conversation import Conversation
ModuleNotFoundError: No module named 'fastchat'

之後就有了這個錯誤然後我再嘗試
pip install fastchat
之後，他就說沒有這個模組，那要怎麼辦?

**Comment by zRzRzRzRzRzRzR** [comment]
pip install fschat
