### ISSUE TITLE
[FEATURE] 关于流式输出接口

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2696]
我看了过去的issues，之前有人讨论过会话的流式输出接口，但好像后续接口删除了
想问下项目中有流式会话的接口吗？我在server/api.py中，只找到了这个/chat/chat  这个会话接口，但没有找到流式的，我想用postman的websocket请求去调流式接口需要怎么做呢？ 还是说有流式我没有找到？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/01995a5f-c934-467f-a9cf-d096218b6c51)

我在tests/api/test_stream_chat_api.py中看了下是设置了 stream=True,这样就可以实现？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/39e8875c-090c-405d-97d3-304450eeb628)

**Comment by 948024326** [comment]
> _🤖_

那我是用postman     用post请求  请求 stream=True?

**Comment by zRzRzRzRzRzRzR** [comment]
/chat/chat 可以设定为流，你需要在传入的地方设定就行，你指定的位置是对的

**Comment by 948024326** [comment]
> /chat/chat 可以设定为流，你需要在传入的地方设定就行，你指定的位置是对的

我这边建立websocket请求失败了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/0ca26714-d5ad-4ddf-9c6d-71e77454329a)
然后我在浏览器F12看了下，好像您并没有用websocket实现这个流式输出，像是在前端用了啥或者做了什么处理
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/f7cd255c-81f5-489d-9f31-702d46a92e19)

**Comment by liunux4odoo** [comment]
/chat/chat接口流式输出用的sse,不是websocket

**Comment by 948024326** [comment]
> /chat/chat接口流式输出用的sse,不是websocket

好的

**Comment by YangFW** [comment]
> /chat/chat接口流式输出用的sse,不是websocket

那这种情况下，用postman或者swagger请求，要怎么请求呀
我现在是带有history请求时，会报 await fn 相关的错误，如果不带有history请求，都正常的；而且web ui上是正常的，就是手动调api会报错

**Comment by fanxyu** [comment]
使用可以发送POST请求的库，import { fetchEventSource } from '@microsoft/fetch-event-source';
        fetchEventSource('/chat/knowledge_base_chat',
            {
                method: 'POST',
                withCredentials: true,
                headers: {
                    "Content-Type": 'application/json',
                },
                body: JSON.stringify({
                    "query": inputValue,
                    "knowledge_base_name": "",
                    "top_k": 3,
                    "score_threshold": 1,
                    "history": messages.length > 1 ? messages.slice(-2).map((item) => {
                        return {
                            'role': item.sender === 'chatbot' ? 'assistant' : 'user',
                            'content': item.text
                        }
                    }) : [],
                    "stream": true,
                    "model_name": "chatglm3-6b",
                    "temperature": 0.7,
                    "max_tokens": 0,
                    "prompt_name": "default"
                }),
                async onopen(response) {
                    console.log('open');
                },
                async onmessage(event) {
                    // console.log(event.data);
                    setText(revMessages => [...revMessages, parseJsonWithNumberValidation(event.data).text])
                },
                onerror(error) {
                    console.info(error);
                    setSysMsg(error)
                },
                onclose() {
                    console.log('close');
                    setInputValue('');
                    setLoading(false);
                }
            }
        )
     我目前遇到的一个问题是经过代理之后，不能流式输出，不经过代理是可以的

**Comment by azhe1234** [comment]
> 使用可以发送POST请求的库，import { fetchEventSource } from '@microsoft/fetch-event-source'; fetchEventSource('/chat/knowledge_base_chat', { method: 'POST', withCredentials: true, headers: { "Content-Type": 'application/json', }, body: JSON.stringify({ "query": inputValue, "knowledge_base_name": "", "top_k": 3, "score_threshold": 1, "history": messages.length > 1 ? messages.slice(-2).map((item) => { return { 'role': item.sender === 'chatbot' ? 'assistant' : 'user', 'content': item.text } }) : [], "stream": true, "model_name": "chatglm3-6b", "temperature": 0.7, "max_tokens": 0, "prompt_name": "default" }), async onopen(response) { console.log('open'); }, async onmessage(event) { // console.log(event.data); setText(revMessages => [...revMessages, parseJsonWithNumberValidation(event.data).text]) }, onerror(error) { console.info(error); setSysMsg(error) }, onclose() { console.log('close'); setInputValue(''); setLoading(false); } } ) 我目前遇到的一个问题是经过代理之后，不能流式输出，不经过代理是可以的

你好请问我也遇到了，经过代理也是无法流式输出，在本地测试时是可以的，请问通过nginx代理的方式你解决了吗
