### ISSUE TITLE
执行python init_database.py --recreate-vs时报错：No module named 'server.model_workers.conversation'

### ISSUE THREAD

**Issue by wusongbai139** [chatchat-space/Langchain-Chatchat#2698]
**问题描述 / Problem Description**
执行python init_database.py --recreate-vs时报错：No module named 'server.model_workers.conversation'

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python init_database.py --recreate-vs'
2.  出现报错：No module named 'server.model_workers.conversation'

model_workers文件内文件：
<img width="527" alt="微信图片_20240118090112" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/69897981/6d553c0a-f797-4300-ac1f-3fd672fcac71">

**环境信息 / Environment Information**
- langchain：0.0.354
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): 
- 操作系统及版本 / Operating system and version:win11
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**Comment by wusongbai139** [comment]
开发老师在吗？ 我应该是少了这个文件“conversation”但不知道这个文件有啥用，或者怎么来的，怎么设置的

**Comment by wusongbai139** [comment]
把相关代码注释掉是不是能解决这个问题呢

**Comment by zRzRzRzRzRzRzR** [comment]
更新一最新代码呢，最新代码没有这个文件，能运行的
