### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by fernandoXH** [chatchat-space/Langchain-Chatchat#2701]
**问题描述 / Problem Description**
服务启动运行一段时间后,20000端口存在大量的close_wait

**复现问题的步骤 / Steps to Reproduce**
正常运行服务等待一段时间观察20000端口

**预期的结果 / Expected Result**
不应该存在大量close_wait

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12929861/b75298a9-2ce9-4dde-8789-46f479519db7)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.9
- 是否使用 Docker 部署（是/否）：是
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan2-7b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-bge-large-chainese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:   Ubuntu 22.04.3
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
需要确认服务器型号和跳板机是否正常，我们自己没有遇到这个问题
@liunux4odoo 能看一下吗

**Comment by liunux4odoo** [comment]
这似乎是fschat造成的，这个不太好定位问题点。
