### ISSUE TITLE
[BUG] webui启动不起来

### ISSUE THREAD

**Issue by wcw1996119** [chatchat-space/Langchain-Chatchat#2705]
其他几个端口都可以运行起来，但是webui运行不起来，会显示连接错误

**Comment by zRzRzRzRzRzRzR** [comment]
web UI起不来很有可能是你stremalit的问题，你看一下是不是要你填写email，填写了就起来了

**Comment by wcw1996119** [comment]
> web UI起不来很有可能是你stremalit的问题，你看一下是不是要你填写email，填写了就起来了

谢谢，确实是这个问题，解决了！

**Comment by yao512954855** [comment]
这个问题我也碰到了，api可以调用，但是webui服务一直有问题，本来以为是端口没开，后来在云服务器上把端口也开了还是不行，最后把自己的email地址输入进去就行了，有点无语

**Comment by sh66666** [comment]
> 这个问题我也碰到了，api可以调用，但是webui服务一直有问题，本来以为是端口没开，后来在云服务器上把端口也开了还是不行，最后把自己的email地址输入进去就行了，有点无语

你好，请问这个邮箱在哪填
