### ISSUE TITLE
执行python init_database.py --recreate-vs时报错：L2 is not applicable for metric type: METRIC INNER_PRODUCT

### ISSUE THREAD

**Issue by scoprio** [chatchat-space/Langchain-Chatchat#2706]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

在初始化 faiss 数据库时  Successfully loaded faiss with AVX2 support.
后提示 Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
Segmentation fault: 11

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.354.
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：  faiss
- 操作系统及版本 / Operating system and version: mac 14.2
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该是你读取了一些图片或者pdf遇到的bug

**Comment by scoprio** [comment]
> 这个应该是你读取了一些图片或者pdf遇到的bug

我还没有把项目启动起来呢。在初始化 faiss 数据库时 就垮掉了😂

**Comment by zRzRzRzRzRzRzR** [comment]
是的，因为在初始化的时候会对知识库的内容进行读取

**Comment by scoprio** [comment]
> 是的，因为在初始化的时候会对知识库的内容进行读取

可以指教下 怎么操作吗？  
我降低faiss包的版本 退回到了1.7.0  但发现我的mac 安装不了 1.7.0 https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/252
感谢

**Comment by zRzRzRzRzRzRzR** [comment]
我没有mac设备，这个需要你去faiss的仓库问了
