### ISSUE TITLE
在7861端口测试chat/chat接口时，出现返回数据不完整的情况

### ISSUE THREAD

**Issue by strLights** [chatchat-space/Langchain-Chatchat#2708]
**问题描述 / Problem Description**
在7861端口测试chat/chat接口时，出现返回数据不完整的情况

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a' 
2. 点击 '0.0.0.0:7861/docs#/Chat/chat_chat_chat_post'
3. 填写好参数后，执行请求
4. 问题出现 / Problem occurs
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/43336297/b0bc61ab-d08b-46bd-bdea-996e8973afd5)

**预期的结果 / Expected Result**
应该正常返回data

**实际结果 / Actual Result**
在执行请求后，会在返回数据时出现: ping - 2024-01-18 06:05:31.569209

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / baichuan2-7b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  Ubuntu 20.04.6
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
请求参数：{
  "query": "如何学习langchain",
  "conversation_id": "",
  "history_len": -1,
  "history": [
  ],
  "stream": false,
  "model_name": "baichuan2-7b",
  "temperature": 0.7,
  "max_tokens": 0,
  "prompt_name": "default"
}
返回结果：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/43336297/7cf4defe-b280-4e85-94e4-771e636b4f85)

**Comment by litterGuy** [comment]
问下这个问题最后怎么解决的？
