### ISSUE TITLE
基于v0.2.9，使用faiss数据库，请问如何将基于embedding的搜索改进为基于bm25和embedding的混合搜索呢

### ISSUE THREAD

**Issue by wzjie** [chatchat-space/Langchain-Chatchat#2709]
基于v0.2.9，使用faiss数据库，请问如何将基于embedding的搜索改进为基于bm25和embedding的混合搜索呢

**Comment by wzjie** [comment]
get_all_docs_from_kb函数怎么在现有的基础上快速实现呢

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有这个计划，可能要自己改进

**Comment by yaoergogo** [comment]
> get_all_docs_from_kb函数怎么在现有的基础上快速实现呢

您好，请问您改进完成了吗，想参考一下您的代码，不知道可以吗

**Comment by hahayueqing** [comment]
> 基于v0.2.9，使用faiss数据库，请问如何将基于embedding的搜索改进为基于bm25和embedding的混合搜索呢

请问有实现的思路吗

**Comment by yaoergogo** [comment]
> > 基于v0.2.9，使用faiss数据库，请问如何将基于embedding的搜索改进为基于bm25和embedding的混合搜索呢
> 
> 请问有实现的思路吗

你在之前的issue里翻一下，有一个人家改好的在chatchat上改进混合搜索的代码，开源的，你可以参考改一下，具体地址我目前没找到，你可以翻一下，我就是参考别人改的
