### ISSUE TITLE
utils.py[line:38] - ERROR: Error code: 400 - {'object': 'error', 'message': 'Only zhipu-api allowed now, your model gpt-3.5-turbo', 'code': 40301}

### ISSUE THREAD

**Issue by GuoJuan911** [chatchat-space/Langchain-Chatchat#2710]
使用自定义agent 报这个错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39322886/fac71292-1c21-4582-aa59-d5d14e215d70)
我尝试着在 在 server_config中配置了 如下图但是还是报错 ，辛苦帮忙看看 是不是我理解不对
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39322886/b0d6d348-d6aa-44bb-8615-05a3c5016a46)

**Comment by zRzRzRzRzRzRzR** [comment]
这个不是API报错吗，跟agent似乎没有关系，你选错了在线的API吧
