### ISSUE TITLE
[BUG] 替换embedding模型例如bge-large-zh-v1.5能向量化，但是搜索不到

### ISSUE THREAD

**Issue by sssssssssh** [chatchat-space/Langchain-Chatchat#2711]
替换了embedding模型例如bge-large-zh-v1.5能向量化，但是搜索不到数据，返回是空的

**Comment by zRzRzRzRzRzRzR** [comment]
搜不到内容的话可以在chat中看能不能搜到，如果doc是空的就是搜不到，搜不到的话记得检查不同模型下的文档排列等提升作用，这个不需要根据你自己情况来优化了

**Comment by sssssssssh** [comment]
> 搜不到内容的话可以在chat中看能不能搜到，如果doc是空的就是搜不到，搜不到的话记得检查不同模型下的文档排列等提升作用，这个不需要根据你自己情况来优化了

好的我打印了doc是空的，那我先处理一下文档试一试
