### ISSUE TITLE
[BUG] 无法在服务器端部署轻量服务

### ISSUE THREAD

**Issue by wcw1996119** [chatchat-space/Langchain-Chatchat#2712]
现在的服务是有三个端口，似乎需要一台vm用docker来部署，但是官网的docker版本好像没有轻量模式。所以想在服务器端部署轻量服务的话，应该选用什么服务器？怎么配置环境？

**Comment by zRzRzRzRzRzRzR** [comment]
源码安装并用lite模式，看wiki
