### ISSUE TITLE
关于top_p参数

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2713]
请问是到目前 会话 chat/chat接口 还不支持top_p参数吗
在0.3.x会补上吗请问

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/0b9b16cc-fc81-46ec-bb72-e23096b34133)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/5b6cc035-3ca3-4f83-86b6-0e3ade8d3089)

**Comment by zRzRzRzRzRzRzR** [comment]
会
