### ISSUE TITLE
[BUG] 加载Qwen-14-chat-int4后显存超出提示错误

### ISSUE THREAD

**Issue by yutong12** [chatchat-space/Langchain-Chatchat#2715]
**问题描述 / Problem Description**
使用Qwen14bint4进行推理时，输入一串代码，模型进行分析后发现超出了最大显存量，返回list out of range错误，随后尝试清理掉这部分缓存，失败，模型无法清理，web界面也无法清理

**Comment by yutong12** [comment]
除了重启没有其他办法解决这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
显存爆了就只能重启了
