### ISSUE TITLE
agent_chat优化

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2718]
目前agent_chat的流式输出是包含了思考过程的流式输出，希望可以增加Final Answer的流式输出。

**Comment by zRzRzRzRzRzRzR** [comment]
之后会重写的

**Comment by monkeydone** [comment]
我使用master的代码，不管stream是true还是false，都不能得到最终答案

**Comment by monkeydone** [comment]
另外目前是需要选择对话模型来解决agent的调用的。如何解决在普通对话中，遇到支持的function calling就调用相应的函数
