### ISSUE TITLE
运行api.py后，执行curl -X POST "http://127.0.0.1:7861" 报错？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#272]
执行curl -X POST "http://127.0.0.1:7861" \      -H 'Content-Type: application/json' \      -d '{"prompt": "你好", "history": []}'，报错怎么解决

**Comment by tomFoxxxx** [comment]
你这个是调用ChatGLM api的写法，调用langchain+ChatGLM api的写法可以看参考文档
