### ISSUE TITLE
WEB-UI启动方式优化

### ISSUE THREAD

**Issue by 2luckydog** [chatchat-space/Langchain-Chatchat#2723]
在Langchain-Chatchat 0.1.x版本中，web-ui启动方式中有通过gradio进行内网透传的能力，
在Langchain-Chatchat 0.2.x版本中，该能力被取消，由于权限管控，我们的服务器看不到本机IP，无法直接通过IP访问，因此希望作者考虑恢复使用gradio进行内网透传的能力

**Comment by zRzRzRzRzRzRzR** [comment]
我们不会使用gradio了
