### ISSUE TITLE
agent_chat使用minimax-api对话bug

### ISSUE THREAD

**Issue by maxusheng123** [chatchat-space/Langchain-Chatchat#2724]
如果不确定的可以debug尝试看一下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/138666362/3c6be7ab-37f8-40b0-bd17-8d3c21fcef81)

**Comment by zRzRzRzRzRzRzR** [comment]
我们现在没有minimax的api，没法进行测试，而且我记得好像这个模型不支持lc的Agent吧
