### ISSUE TITLE
[BUG] api启动成功，但无法访问

### ISSUE THREAD

**Issue by yueyaww** [chatchat-space/Langchain-Chatchat#2726]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49739029/30db2a3d-a90e-4a18-8570-fedfe541ce06)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49739029/00c1cda8-62be-44e2-8e7d-e8cc3dcf8fd2)

**Comment by zRzRzRzRzRzRzR** [comment]
你这没启动啊不是307了，先正常启动吧
