### ISSUE TITLE
bing搜索API调用失败

### ISSUE THREAD

**Issue by ChaocunChen** [chatchat-space/Langchain-Chatchat#2730]
我申请了一个bing 搜索的免费API key ，填进去提示401（密钥无效），请问这个是用法问题还是需要申请收费的API密钥才可以调用？

**Comment by zRzRzRzRzRzRzR** [comment]
免费的也能用，是在Azure申请的才行

**Comment by ChaocunChen** [comment]
> 免费的也能用，是在Azure申请的才行

我已经申请了，也填写进去了，为啥还是显示401错误？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/41281366/e27ccb6d-c0af-44b5-b1b5-977c8c3e2f4b)

**Comment by zRzRzRzRzRzRzR** [comment]
你的订阅地址是v7版本吗，如果不是你应该设置你的api的访问地址

**Comment by ChaocunChen** [comment]
> 你的订阅地址是v7版本吗，如果不是你应该设置你的api的访问地址

是v7.0版本的 我写入终结点和api key 并且确定key正确无误 仍然显示401错误

**Comment by ChaocunChen** [comment]
> > 你的订阅地址是v7版本吗，如果不是你应该设置你的api的访问地址
> 
> 是v7.0版本的 我写入终结点和api key 并且确定key正确无误 仍然显示401错误

您这边有没有v7版本python可以跑通的示例

**Comment by zRzRzRzRzRzRzR** [comment]
现在就是跑通的呀，我一只在跑的

**Comment by ChaocunChen** [comment]
> 现在就是跑通的呀，我一只在跑的

那他下面这个python示例
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/41281366/589c78e4-9bc0-41f4-9038-e964ba4f5f81)
你跑通了嘛 这个

# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# You may need the below as well
# pip install pipenv
# pipenv install requests
# <importsAndVars>
import json
import os
from pprint import pprint
import requests 

'''
This sample uses the Bing Custom Search API to search for a query topic and get back user-controlled web page results.
Bing Custom Search API: https://docs.microsoft.com/en-us/bing/search-apis/bing-custom-search/overview 
'''

# Add your Bing Custom Search subscription key and endpoint to your environment variables.
subscriptionKey = os.environ['BING_CUSTOM_SEARCH_SUBSCRIPTION_KEY']
endpoint = os.environ['BING_CUSTOM_SEARCH_ENDPOINT']
customConfigId = os.environ["BING_CUSTOM_CONFIG"]  # you can also use "1"
searchTerm = "microsoft"
# </importsAndVars>
# <url>
# Add your Bing Custom Search endpoint to your environment variables.
url = endpoint + "/bingcustomsearch/v7.0/search?q=" + searchTerm + "&customconfig=" + customConfigId
# </url>
# <request>
r = requests.get(url, headers={'Ocp-Apim-Subscription-Key': subscriptionKey})
pprint(json.loads(r.text))
# </request>
里面的BING_CUSTOM_CONFIG是啥？

**Comment by Rex-Liu1027** [comment]
我也遇到了相同的问题，请问你解决了吗。。


> 我申请了一个bing 搜索的免费API key ，填进去提示401（密钥无效），请问这个是用法问题还是需要申请收费的API密钥才可以调用？



> 现在就是跑通的呀，我一只在跑的

只是改一下kb_config.py里面的BING_SUBSCRIPTION_KEY就好了嘛，我也遇到了相同的问题。。。试了好几次都是401

**Comment by Rex-Liu1027** [comment]
> 我也遇到了相同的问题，请问你解决了吗。。
> 
> > 我申请了一个bing 搜索的免费API key ，填进去提示401（密钥无效），请问这个是用法问题还是需要申请收费的API密钥才可以调用？
> 
> > 现在就是跑通的呀，我一只在跑的
> 
> 只是改一下kb_config.py里面的BING_SUBSCRIPTION_KEY就好了嘛，我也遇到了相同的问题。。。试了好几次都是401

@ChaocunChen 已解决，我是在创建bing搜索的时候选了第二个自定义搜索，所以出现了401；应该是选第一个bing搜索就行了，然后把key直接拷贝到配置文件里就好了，你可以试试
