### ISSUE TITLE
使用不了openai的embedding模型

### ISSUE THREAD

**Issue by lewisliuyi** [chatchat-space/Langchain-Chatchat#2731]
知识库初始化的时候，想使用openai的embedding模型，但是会报错说模型名字不匹配，是不是不是"text-embedding-ada-002"这个名字，用了的别的模型名。

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码也这样吗，模型名字没错的

**Comment by HuipengXu** [comment]
lite模式是不是不支持openai embedding

**Comment by lewisliuyi** [comment]
应该是版本更新，导致类失效了
![Uploading 4d5cb2d90b8692cc5ffeaf80dbe67bd.png…]()

**Comment by lewisliuyi** [comment]
应该是版本更新，导致类失效了
<img width="865" alt="4d5cb2d90b8692cc5ffeaf80dbe67bd" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/98192649/ca66d3cf-d460-4178-924b-2f9b0b209323">
<img width="515" alt="ce88c33328edceee68fc246d299e088" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/98192649/691078c6-06ac-45f4-9bd9-9d65602c0fc5">

**Comment by HuipengXu** [comment]
lite模式好像也用不了openai 的embedding

**Comment by HuipengXu** [comment]
> lite模式好像也用不了openai 的embedding

由于text-embedding-ada-002放在了local里，好像没啥优雅的方法通过通过配置解决，修改了knowledge_base.py一行代码

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/23466003/35b59d5d-e4f6-4494-b7bb-3de592137485)

**Comment by lewisliuyi** [comment]
你这个文件在哪里

**Comment by HuipengXu** [comment]
> 你这个文件在哪里

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/23466003/0422721c-efb8-40e7-ad4f-3336dd8fa163)

**Comment by lewisliuyi** [comment]
我找到了，但是改了好像也没用

**Comment by HuipengXu** [comment]
@lewisliuyi 报啥错呢

**Comment by zRzRzRzRzRzRzR** [comment]
现在还不行吗？

**Comment by shaoyie** [comment]
> 现在还不行吗？

到今天为止还不行。。。
