### ISSUE TITLE
openchat 3.5能否离线配置

### ISSUE THREAD

**Issue by ydh10002023** [chatchat-space/Langchain-Chatchat#2732]
openchat 3.5能否离线配置

**Comment by zRzRzRzRzRzRzR** [comment]
本地模型才能，这个模型我没听过，如果在fschat支持列表就可以

**Comment by ydh10002023** [comment]
@zRzRzRzRzRzRzR https://huggingface.co/openchat/openchat_3.5 ? 这个模型是不是可以？谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
那估计要自己试试了，fschat没写

**Comment by ydh10002023** [comment]
@ zRzRzRzRzRzRzR thanks
