### ISSUE TITLE
无法删除知识库

### ISSUE THREAD

**Issue by lewisliuyi** [chatchat-space/Langchain-Chatchat#2737]
知识库创建了之后，没有合法删除的地方，直接删除文件会导致报错一直保留。
<img width="1280" alt="971a7bcff3d4148b67dca7f98bad651" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/98192649/f7df017d-3450-45bb-84f1-28c0ad4b312b">

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.10恢复了
