### ISSUE TITLE
[BUG] 模型配置相关问题

### ISSUE THREAD

**Issue by XUshicong** [chatchat-space/Langchain-Chatchat#2743]
**问题1：**
在`configs/model_configs`文件将`LLM_MODELS = ["openai-api"] `，那么按照我的理解，webui界面应该只有openai模型可以选择，但还是会有chatglm3模型：
![20240122-103609](https://github.com/chatchat-space/Langchain-Chatchat/assets/73678015/92d3ac57-9e85-46cf-8d24-139cda469cba)

是因为和 `MODEL_ROOT_PATH = ”chatglm3所在的绝对路径“`  有关系吗？

**问题2：**
我想问一下怎么选择open-ai的embedding模型？我的做法是：
- 第一：`EMBEDDING_MODEL = "text-embedding-ada-002"`
- 第二：
```
ONLINE_LLM_MODEL = {
    "openai-api": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "已经设置了api",
        "openai_proxy": "",
    },
```
- 第三：
```
MODEL_PATH = {
    "embed_model": {
        "text-embedding-ada-002": "已经设置了api",
    },
```
经过上面三个步骤的设置，算是已经配置了open-ai的api了吗？但是这样设置好之后，用于知识库问答，效果很差，不如chatglm3

**Comment by zRzRzRzRzRzRzR** [comment]
LLM_MODELS = ["openai-api"] 是对的
server_config要把glm3 注释掉

**Comment by zRzRzRzRzRzRzR** [comment]
embedding设定是对的

**Comment by XUshicong** [comment]
> LLM_MODELS = ["openai-api"] 是对的 server_config要把glm3 注释掉

```
# 可以如下示例方式更改默认配置
    # "Qwen-1_8B-Chat": { # 使用default中的IP和端口
    #    "device": "cpu",
    # },
    # "chatglm3-6b": {  # 使用default中的IP和端口
    #     "device": "cuda",
    # },
```
已经注释了，但还是不行。
我调用`列出当前已经加载的模型`接口的时候，输出是：
```
{
  "code": 200,
  "msg": "success",
  "data": {
    "chatglm3-6b": {
      "host": "10.20.168.30",
      "port": 20002,
      "device": "cuda",
      "infer_turbo": false,
      "model_path": "THUDM/chatglm3-6b"
    }
  }
}
```

当我在webui界面选择  open-ai模型的时候，再次调用这个接口，还是输出一样的内容。
这是为什么呢？

**Comment by dcmouth** [comment]
你是不是设置之后没有保存，要不然你问题1，按照你的设置，不应该再出现别的模型选项
