### ISSUE TITLE
请问项目里面向量相似度使用了什么方法计算呀？

### ISSUE THREAD

**Issue by Sauloo-huen** [chatchat-space/Langchain-Chatchat#275]

**Comment by imClumsyPanda** [comment]
基本按照langchain里的FAISS.similarity_search_with_score_by_vector实现

**Comment by wmr484** [comment]
能否说下重写FAISS.similarity_search_with_score_by_vector方法的原因吗？谢谢哈

**Comment by wmr484** [comment]
能否说下重写FAISS.similarity_search_with_score_by_vector方法的原因吗？谢谢哈

**Comment by imClumsyPanda** [comment]
@wmr484 可以参考 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/296

**Comment by wmr484** [comment]
谢谢回复哈，我昨天下午翻了一遍issue list，也刚好看到。
