### ISSUE TITLE
切换模型后还关联上下文，如何解决？

### ISSUE THREAD

**Issue by CWJ-NB** [chatchat-space/Langchain-Chatchat#2757]
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/62415481/88ff1f6a-d10b-4afa-8a8c-a6348e1c89f4)
                                                                                  图1 chatglm3-6b模型

![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/62415481/0b740190-467d-49c7-8bf5-63cc7ff7aace)
                                                                 图2 没有清除对话，切换为qwen模型

![3](https://github.com/chatchat-space/Langchain-Chatchat/assets/62415481/1f21737d-0a66-45bd-81d4-a8b4befe87c7)
                                                                        图3 清除对话后的qwen模型

如同所示，当我没有清除对话，切换模型后，回答还存在上下文历史，如何使得当切换模型后自动清除上下文，让回答没有关联历史？

**Comment by CWJ-NB** [comment]
机器人回答的不对

**Comment by liunux4odoo** [comment]
切换模型时保持对话历史是必要的特性。

如果想清除历史，可以清除对话或者临时把history_len设为0。
