### ISSUE TITLE
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by yangy5443** [chatchat-space/Langchain-Chatchat#2760]
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by yangy5443** [comment]
<img width="1280" alt="微信图片_20240123032416" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/78999730/03bb82c8-90db-45f4-99ab-db20c5e38d86">

**Comment by MolianWH** [comment]
你的问题解决了吗？我也遇到了。 @yangy5443

**Comment by zRzRzRzRzRzRzR** [comment]
联网的key写了吗，然后这个问题我需要看后台日志

**Comment by yangy5443** [comment]
<img width="692" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/78999730/96372937-49a5-4aee-8491-3b7b579c8af2">
似乎没有填写api key的地方

**Comment by zRzRzRzRzRzRzR** [comment]
在kb config
