### ISSUE TITLE
[BUG] 与milvus整合时页面出现点击异常

### ISSUE THREAD

**Issue by AlexNilone** [chatchat-space/Langchain-Chatchat#2761]
LangchainChatChat 0.2.9
milvus 2.3.4
pymilvus 2.3.4

集成后在webui上点击知识库中某个文件后，出现红色报错：
![d065f2010c6f352a738e1fe19644bb7](https://github.com/chatchat-space/Langchain-Chatchat/assets/79305340/fb3016d9-d236-4d4c-9926-c27c236153ad)

具体看附件中的前台和后台报错日志。
[报错_后台.log](https://github.com/chatchat-space/Langchain-Chatchat/files/14017431/_.log)
[报错_前台.log](https://github.com/chatchat-space/Langchain-Chatchat/files/14017432/_.log)

**Comment by AlexNilone** [comment]
![b9e3258cb708c518b007136bcf9bb88](https://github.com/chatchat-space/Langchain-Chatchat/assets/79305340/525dc749-6b23-4283-8223-3b8d5ac7e65c)

![42a557b90436e224dca5650f8953188](https://github.com/chatchat-space/Langchain-Chatchat/assets/79305340/89ae4ea1-a76a-4c84-b079-8ee1b305a4fd)

**Comment by AlexNilone** [comment]
我发现在上传文件加入知识库的过程中服务日志也有报错（但是最终是录入进去了的），和数值转换精度有关

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/79305340/bd5e8f0e-ba17-4f5e-9a27-6010bc4a839b)

**Comment by wzjie** [comment]
我用faiss数据库也有这个问题，这个bug应该和用的哪个数据库无关

**Comment by AlexNilone** [comment]
> _🤖_
> 
> 您在webui上点击知识库中的文件时遇到的红色错误可能是因为在`server/knowledge_base/kb_doc_api.py`文件中，`files2docs`函数目前被注释掉了。这个函数负责将文件转换为文档并保存到知识库。由于它被注释掉，应用程序可能无法在知识库中找到文件，因此出现错误。
> 
> 关于在文件上传过程中出现的与数值转换精度有关的错误，没有更多信息很难说。但是，它可能与您文件中的字段的数据类型有关。如果一个字段预期是某种数值类型（如整数或浮点数），而文件中的数据无法转换为该类型，您可能会看到错误。
> 
> 请注意，这些只是基于提供的上下文的可能解释。要更准确的诊断，需要更多关于确切的错误消息和您文件中的数据的信息。
> 
> 源代码：
> 
>     * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> 
> 关于在webui上点击知识库中的文件时显示的红色错误的确切错误消息，提供的上下文中并未明确提到。然而，根据代码中的不同条件，可能会显示几个错误消息。以下是一些例子：
> 
>     1. 如果在获取知识库详情时出现异常，会显示以下错误消息："获取知识库信息错误，请检查是否已按照 `README.md` 中 `4 知识库初始化与迁移` 步骤完成初始化或迁移，或是否为数据库连接错误。"
> 
>     2. 如果在创建新的知识库时，知识库名称为空或已存在，分别会显示以下错误消息："知识库名称不能为空！" 和 "名为 {kb_name} 的知识库已经存在！"
> 
>     3. 如果 `api.upload_kb_docs` 函数返回错误消息，它会作为一个toast消息显示。
> 
> 
> 然而，没有具体的错误场景或更多的上下文，无法提供在webui上点击知识库中的文件时会显示的确切错误消息。
> 
> 源代码：
> 
>     * [webui_pages/knowledge_base/knowledge_base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/knowledge_base/knowledge_base.py)
> 
> 
> 如果您能提供更多的错误详情或者是错误的复现步骤，我将能更好地帮助您解决问题。
> ## Sources
> 
>     * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
>     * [webui_pages/knowledge_base/knowledge_base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/knowledge_base/knowledge_base.py)
> 
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

没有解决。我看这个问题也有别人提出，希望能跟进测下

**Comment by AlexNilone** [comment]
机器人回复没帮助

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题在0.2.10修复了，你拉一下最新的分支

**Comment by AlexNilone** [comment]
> 这个问题在0.2.10修复了，你拉一下最新的分支

0.2.10并未解决。

**Comment by aotsukiqx** [comment]
看起来不止是milvus，我看到milvus的repo里你创建了这个issue @AlexNilone ，正好我最近升级0.2.10也遇到这个问题，实在解决不了。
就在刚才，换了pgvector：看起来应该是向量化以后的代码逻辑问题
2024-01-29 21:19:14.733 Uncaught app exception
Traceback (most recent call last):
  File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/colin/Documents/Source/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/Users/colin/Documents/Source/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
  File "/Users/colin/Documents/Source/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context
    self.dialect.do_execute(
  File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "ARRAY"
LINE 1: ...ROM langchain_pg_embedding WHERE collection_id in ARRAY['fed...

**Comment by 948024326** [comment]
> LangchainChatChat 0.2.9 milvus 2.3.4 pymilvus 2.3.4
> 
> 集成后在webui上点击知识库中某个文件后，出现红色报错： ![d065f2010c6f352a738e1fe19644bb7](https://private-user-images.githubusercontent.com/79305340/298782379-fb3016d9-d236-4d4c-9926-c27c236153ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1Mzc3ODcsIm5iZiI6MTcwNjUzNzQ4NywicGF0aCI6Ii83OTMwNTM0MC8yOTg3ODIzNzktZmIzMDE2ZDktZDIzNi00ZDRjLTk5MjYtYzI3YzIzNjE1M2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDE0MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZmMyMjM2OTRiNzNjOTFmYTIyYzA1MmVlN2JlYWM3ZDg5NWNiYTA3MTZhMTNlYjU5NWEyNmQ1NGJiYzBjODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3jfH-BYMYnCtKS2aDmNsOYKm3qAgTf7PCJtqz781hYE)
> 
> 具体看附件中的前台和后台报错日志。 [报错_后台.log](https://github.com/chatchat-space/Langchain-Chatchat/files/14017431/_.log) [报错_前台.log](https://github.com/chatchat-space/Langchain-Chatchat/files/14017432/_.log)

请问解决了吗？ 我们问题一样

**Comment by AlexNilone** [comment]
没有解决。

**Comment by AlexNilone** [comment]
> > 这个问题在0.2.10修复了，你拉一下最新的分支
> 
> 2.10.0还是报错，刚刚试了，还有就是，删除这个向量库，返回200说返回成功，但我查milvus向量库里面并没有删除成功，导致知识库问答中会回答之前删除了的内容

情况基本一样。

**Comment by AlexNilone** [comment]
> 看起来不止是milvus，我看到milvus的repo里你创建了这个issue @AlexNilone ，正好我最近升级0.2.10也遇到这个问题，实在解决不了。 就在刚才，换了pgvector：看起来应该是向量化以后的代码逻辑问题 2024-01-29 21:19:14.733 Uncaught app exception Traceback (most recent call last): File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script exec(code, module.**dict**) File "/Users/colin/Documents/Source/Langchain-Chatchat/webui.py", line 64, in pages[selected_page]["func"](api=api, is_lite=is_lite) File "/Users/colin/Documents/Source/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page data = [ ^ File "/Users/colin/Documents/Source/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"), ~^^^^^^ TypeError: string indices must be integers, not 'str' ERROR: Exception in ASGI application Traceback (most recent call last): File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context self.dialect.do_execute( File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute cursor.execute(statement, parameters) psycopg2.errors.SyntaxError: syntax error at or near "ARRAY" LINE 1: ...ROM langchain_pg_embedding WHERE collection_id in ARRAY['fed...

0.2.9和0.2.10 都报错

**Comment by hollowdjj** [comment]
一模一样的情况，请问解决了吗

**Comment by nilin1998** [comment]
> 看起来不止是milvus，我看到milvus的repo里你创建了这个issue @AlexNilone ，正好我最近升级0.2.10也遇到这个问题，实在解决不了。 就在刚才，换了pgvector：看起来应该是向量化以后的代码逻辑问题 2024-01-29 21:19:14.733 Uncaught app exception Traceback (most recent call last): File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script exec(code, module.**dict**) File "/Users/colin/Documents/Source/Langchain-Chatchat/webui.py", line 64, in pages[selected_page]["func"](api=api, is_lite=is_lite) File "/Users/colin/Documents/Source/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page data = [ ^ File "/Users/colin/Documents/Source/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"), ~^^^^^^ TypeError: string indices must be integers, not 'str' ERROR: Exception in ASGI application Traceback (most recent call last): File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1965, in _exec_single_context self.dialect.do_execute( File "/Users/colin/miniforge3/envs/chatchat/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 921, in do_execute cursor.execute(statement, parameters) psycopg2.errors.SyntaxError: syntax error at or near "ARRAY" LINE 1: ...ROM langchain_pg_embedding WHERE collection_id in ARRAY['fed...

你好，我遇到了和你一模一样的问题，请问你解决了嘛

**Comment by nilin1998** [comment]
> 一模一样的情况，请问解决了吗

你好，请问你解决了嘛

**Comment by hollowdjj** [comment]
> > 一模一样的情况，请问解决了吗
> 
> 你好，请问你解决了嘛

还没有

**Comment by nilin1998** [comment]
> > > 一模一样的情况，请问解决了吗
> > 
> > 
> > 你好，请问你解决了嘛
> 
> 还没有

你好，我按照以下方式修改，解决了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/55744076/33632d90-6c52-468c-8499-83eaf891a557)
我的langchain-chat版本是v0.2.9

**Comment by hollowdjj** [comment]
> > > > 一模一样的情况，请问解决了吗
> > > 
> > > 
> > > 你好，请问你解决了嘛
> > 
> > 
> > 还没有
> 
> 你好，我按照以下方式修改，解决了 ![image](https://private-user-images.githubusercontent.com/55744076/307682786-33632d90-6c52-468c-8499-83eaf891a557.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5Mjg2NDMsIm5iZiI6MTcwODkyODM0MywicGF0aCI6Ii81NTc0NDA3Ni8zMDc2ODI3ODYtMzM2MzJkOTAtNmM1Mi00NjhjLTg0OTktODNlYWY4OTFhNTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI2VDA2MTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YWE1NTk5ZWUyNjJkZTk2ODk2NWI3OGQwMDYwM2U0MThjMjhiOWUyMmUwNzc2N2I2YTk4YjA4Njc1NzVjNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iTG4AikJ7nSxnlX-2ECctj-I4SZWxlxAPVWZeqBZ-1c) 将collection_id改为custom_id，将results语句中的ids外加tuple 我的langchain-chat版本是v0.2.9

有其他修改吗，是不是只用改这一处呀

**Comment by nilin1998** [comment]
> Reference

我向量库用的是pgvector，只改了pg_kb_service.py的这段代码

**Comment by xujiahao718** [comment]
> > Reference
> 
> 我向量库用的是pgvector，只改了pg_kb_service.py的这段代码

老哥，如果用milvus向量库，要怎么改呀

**Comment by nilin1998** [comment]
感觉也是类似的，你看看collection_id是不是mivlus库里也没有，也是custom_id



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月4日(周一) 下午2:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 与milvus整合时页面出现点击异常 (Issue #2761)




   
Reference
  
我向量库用的是pgvector，只改了pg_kb_service.py的这段代码
  
老哥，如果用milvus向量库，要怎么改呀

**Comment by xujiahao718** [comment]
最新代码已经修复了

**Comment by sanwei111** [comment]
> 一模一样的情况，请问解决了吗
你好，请问怎么解决

**Comment by Wangzhongxi** [comment]
> 最新代码已经修复了

怎么修改milvus呀，除了kb_config里面还有哪里需要修改呀

**Comment by Wangzhongxi** [comment]
> > > 最新代码已经修复了
> > 
> > 
> > 怎么修改milvus呀，除了kb_config里面还有哪里需要修改呀
> 
> 按wiki里的步骤来，拉最新的代码就行了，应该不用改其他的

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135239375/6e2e8f11-2fa7-4ec9-9921-9281dc4c29ab)
已经拉取最新的代码了，虽然没有报错，但源文件和向量库都是×，attu中查看也没有数据显示，但能查找到我创建的知识库名称

**Comment by Wangzhongxi** [comment]
> > > 最新代码已经修复了
> > 
> > 
> > 怎么修改milvus呀，除了kb_config里面还有哪里需要修改呀
> 
> 按wiki里的步骤来，拉最新的代码就行了，应该不用改其他的

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135239375/a10d0c4b-5fc0-4d77-86e0-6327e0db520e)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/135239375/f4ca3f1c-e476-490f-aecd-3b34b9cb4030)
已经拉取最新代码，虽然没有报错，但是使用attu可视化是没有数据显示，是因为上面源文件和向量库没有添加进去吗，有人知道这个怎么解决嘛

**Comment by blackwhites** [comment]
我也重现这个问题
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=cannot parse expression: pk in ['449689629463176736'], error: value ''449689629463176736'' in list cannot be casted to Int64)>
2024-05-16 01:12:07,241 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 500 Internal Server Error"
2024-05-16 01:12:07.242 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/langchain/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/root/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "/root/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 330, in knowledge_base_page
    data = [
  File "/root/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 331, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content":
