### ISSUE TITLE
[BUG] win11 pip install报错

### ISSUE THREAD

**Issue by geekcheng** [chatchat-space/Langchain-Chatchat#2763]
**问题描述 
win11 安装 pip install 的时候会出现错误，是否不支持win11? 或者说不支持win

Failed to build jq
ERROR: Could not build wheels for jq, which is required to install pyproject.toml-based projects

**Comment by geekcheng** [comment]
好像是windows不支持 jq ？

**Comment by zRzRzRzRzRzRzR** [comment]
wiki写了，conda安装

**Comment by tomdogs1** [comment]
conda安装已经过了，不过在import时依旧失败，提示ModuleNotFoundError: No module named 'jq'
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42016093/02a410ee-8428-4506-8105-ef7310d3f862)

**Comment by zRzRzRzRzRzRzR** [comment]
之前有issue提到，可能要先装jq在装requirement
这个我不是很清楚因为我也不是windows的系统
