### ISSUE TITLE
研究了知识库模块的代码，未找到faiss_kb_service.py中similarity_search_with_score_by_vector方法的代码

### ISSUE THREAD

**Issue by Harrold-Lee** [chatchat-space/Langchain-Chatchat#2764]
**问题描述 / Problem Description**
未找到faiss_kb_service.py中similarity_search_with_score_by_vector方法的代码

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a'
2. 点击 '知识库问答'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 
 能够完成相关文本匹配，但在研究代码时，未找到vs.similarity_search_with_score_by_vector方法的内容，不知道使用的是哪种相似度度量方法。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/54501008/b17ad7b5-7112-48a4-b857-f866e7caf9f9)

**预期的结果 / Expected Result**
能够打开similarity_search_with_score_by_vector方法的代码块

**实际结果 / Actual Result**
提示无相关代码
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/54501008/d2780d7b-b96a-4465-b7f5-203a01c663f9)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.7
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：XingHuo-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Ubuntu 20.04.3 LTS
- Python 版本 / Python version: Python 3.10.4
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by hydai99** [comment]
这是langchain的函数
参考：https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py

**Comment by Harrold-Lee** [comment]
> 这是langchain的函数 参考：https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py

非常感谢您，我是小白，我想请教一下，在chatchat项目中，使用vs.similarity_search_with_score_by_vector来查询相关文档时，无需在项目中包含这个方法的定义吗？

**Comment by hydai99** [comment]
> > 这是langchain的函数 参考：https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py
> 
> 非常感谢您，我是小白，我想请教一下，在chatchat项目中，使用vs.similarity_search_with_score_by_vector来查询相关文档时，无需在项目中包含这个方法的定义吗？

前面的代码有应该已经调用了。你说的定义是？

**Comment by lurenyi4** [comment]
我记得是L2

**Comment by lurenyi4** [comment]
server/knowledge_base/kb_cache/faiss_cache.py

class KBFaissPool(_FaissPool):
    def load_vector_store(
            self,
            kb_name: str,
            vector_name: str = None,
            create: bool = True,
            embed_model: str = EMBEDDING_MODEL,
            embed_device: str = embedding_device(),
    ) -> ThreadSafeFaiss:
        self.atomic.acquire()
        vector_name = vector_name or embed_model
        cache = self.get((kb_name, vector_name)) # 用元组比拼接字符串好一些
        if cache is None:
            item = ThreadSafeFaiss((kb_name, vector_name), pool=self)
            self.set((kb_name, vector_name), item)
            with item.acquire(msg="初始化"):
                self.atomic.release()
                logger.info(f"loading vector store in '{kb_name}/vector_store/{vector_name}' from disk.")
                vs_path = get_vs_path(kb_name, vector_name)

                if os.path.isfile(os.path.join(vs_path, "index.faiss")):
                    embeddings = self.load_kb_embeddings(kb_name=kb_name, embed_device=embed_device, default_embed_model=embed_model)
                    vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
                elif create:
                    # create an empty vector store
                    if not os.path.exists(vs_path):
                        os.makedirs(vs_path)
                    vector_store = self.new_vector_store(embed_model=embed_model, embed_device=embed_device)
                    vector_store.save_local(vs_path)
                else:
                    raise RuntimeError(f"knowledge base {kb_name} not exist.")
                item.obj = vector_store
                item.finish_loading()
        else:
            self.atomic.release()
        return self.get((kb_name, vector_name))

**Comment by Harrold-Lee** [comment]
> > > 这是langchain的函数 参考：https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py
> > 
> > 
> > 非常感谢您，我是小白，我想请教一下，在chatchat项目中，使用vs.similarity_search_with_score_by_vector来查询相关文档时，无需在项目中包含这个方法的定义吗？
> 
> 前面的代码有应该已经调用了。你说的定义是？

因为我在整个项目文件中未找到similarity_search_with_score_by_vector这个方法的代码，并且仅在我问题中给出的位置进行了一次调用，所以我比较疑惑为什么项目中没有这个方法的相关代码，但却可以调用这个方法来获得候选文档。

**Comment by hydai99** [comment]
> > > > 这是langchain的函数 参考：https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py
> > > 
> > > 
> > > 非常感谢您，我是小白，我想请教一下，在chatchat项目中，使用vs.similarity_search_with_score_by_vector来查询相关文档时，无需在项目中包含这个方法的定义吗？
> > 
> > 
> > 前面的代码有应该已经调用了。你说的定义是？
> 
> 因为我在整个项目文件中未找到similarity_search_with_score_by_vector这个方法的代码，并且仅在我问题中给出的位置进行了一次调用，所以我比较疑惑为什么项目中没有这个方法的相关代码，但却可以调用这个方法来获得候选文档。

因为它调用的faiss是来自langchain的，
`from langchain.vectorstores.faiss import FAISS`。这个库里面有定义这个方法，这里直接调用就好了
![1705996704968](https://github.com/chatchat-space/Langchain-Chatchat/assets/75218429/e9e31207-8937-4cfb-8f06-5104d1cb61af)
