### ISSUE TITLE
使用特定行业的文档做问答，出现匹配错乱问题

### ISSUE THREAD

**Issue by jiaxiaoniu** [chatchat-space/Langchain-Chatchat#2767]
使用地质行业的区域调查报告做文件输入，基于这个文件进行问答时，发现会胡乱生成答案的问题。如搜索测区内是否存在压扭性构造时，即使文档中没有压扭性构造的描述，系统也会检索出一些和构造有关系的内容，使用这些内容生成答案，实际上这些答案是错误的。这种情况需要我自己训练向量模型

**Comment by zRzRzRzRzRzRzR** [comment]
自己训练模型是一种办法
或者你自己定义分词的过程，不要用默认的按照多少个词切开分
