### ISSUE TITLE
[BUG] 使用ChatYuan-V2模型无法流式输出，会报错

### ISSUE THREAD

**Issue by busisiji** [chatchat-space/Langchain-Chatchat#277]
![image](https://user-images.githubusercontent.com/92677771/236779210-a2292bd6-c0a6-4a30-b906-9906cc141e9f.png)
![image](https://user-images.githubusercontent.com/92677771/236779281-481129f1-c388-40de-b183-a5ea8dfc2ed1.png)
![image](https://user-images.githubusercontent.com/92677771/236779371-f15d9f9f-f32a-41b9-924b-82f8db87d6ef.png)

**Comment by nameless0704** [comment]
一方面好像是ChatYuan本身不支持stream_chat，有人在clueai那边提了issue他们说还没开发，所以估计这个attribute调不起来；但是另一方面看报错好像是T5模型本身就不是decoder-only模型，所以不能流式输出吧（个人理解）

**Comment by nameless0704** [comment]
#282
