### ISSUE TITLE
[FEATURE] GLM3 的  P-Tuning v2 微调能支持吗

### ISSUE THREAD

**Issue by shaitao** [chatchat-space/Langchain-Chatchat#2773]
https://github.com/THUDM/ChatGLM3/tree/main/finetune_chatmodel_demo 
所采用的 P-Tuning v2 训练的模型bin文件

是否能加载，若不支持，将来是否有计划。

**Comment by zRzRzRzRzRzRzR** [comment]
不能，因为不是peft结构，chatglm3会重写微调代码，之后他们新的代码调出来的模型就能用了
