### ISSUE TITLE
[BUG] readme里的docker链接失效

### ISSUE THREAD

**Issue by Zhenyi-Wang** [chatchat-space/Langchain-Chatchat#2774]
**问题描述 / Problem Description**
Readme.md中的“Docker 容器”链接点进去404

问题简单，多的不说了，谢谢！

**Comment by zRzRzRzRzRzRzR** [comment]
正在做0.2.10的，之后更新一下0.2.x不维护了

**Comment by manchiy** [comment]
> 正在做0.2.10的，之后更新一下0.2.x不维护了

等待大佬更新0.2.10的镜像

**Comment by ansemz** [comment]
大佬，0.2.10的镜像啥时候可以更新好？

> 正在做0.2.10的，之后更新一下0.2.x不维护了
