### ISSUE TITLE
知识库问答对什么格式比较好？知识库文件什么格式比较好？txt or json ?

### ISSUE THREAD

**Issue by liushifu12138** [chatchat-space/Langchain-Chatchat#2776]
这是我的格式：
问题:一般是几个工作日，五个工作日才配送的，是吗?答案:目前统一由政务服务中心邮寄快递，邮寄时间约为3-5个工作日。

问题:一般送到一般配送的工作日是几个工作日？?答案:目前统一由政务服务中心邮寄快递，邮寄时间约为3-5个工作日。

**Comment by zRzRzRzRzRzRzR** [comment]
csv 第一列问题第二列答案
