### ISSUE TITLE
[BUG] 不同环境下，把同一个知识库文件上传，得到的结果是不同的，请问为什么？

### ISSUE THREAD

**Issue by helix-dan** [chatchat-space/Langchain-Chatchat#2777]
**问题描述 / Problem Description**
在不同主机上，使用相同的操作，但得到的结果不同

**复现问题的步骤**
本地环境B（下方白色背景图）
阿里云环境C（下方黑色背景图）
第一步、B 跟 C，都部署了相同版本的 chatchat v0.2.9
第二步、使用同样配置的向量库参数，上传了同一个知识库文件

**实际结果**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1751530/dda37c72-e6a2-4474-8f7f-44df8f5cf8e0)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1751530/25ee7ce8-f995-4f84-a0fc-eb17dbcc9dd3)

Q1：请问得到完全不同的“文档数量”结果，请问这个原因是什么？
Q2：请问这里的“文档数量”代表什么意思？哪些因素会决定这里的“文档数量”结果不同？

**环境信息**
- langchain-ChatGLM 版本号：0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：在线 ChatGLM API
- 使用的 Embedding 模型：m3e-base
- 使用的向量库类型： faiss
- 操作系统及版本: Ubuntu
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息: 本地是使用 RTX4080，阿里云目前是 CPU（无 GPU）

**Comment by helix-dan** [comment]
> _🤖_
> 
> 你好 @helix-dan！ 很高兴再次看到你这里。希望你一切都好！ 👽
> 
> 根据您提供的信息，我理解您在不同的环境中上传相同的知识库文件，但得到了不同的“文档数量”结果。这可能是由于以下几个原因：
> 
> 1. **知识库文件的处理方式**：在上传知识库文件时，Langchain-Chatchat 应用会对文件进行处理，包括分割、向量化等步骤。这些步骤可能会受到环境因素的影响，例如处理能力、内存限制等，从而导致在不同环境中得到不同的结果。
> 2. **环境中的其他因素**：除了上述的处理方式，环境中的其他因素也可能影响结果。例如，如果在一个环境中有其他进程正在使用大量的资源，那么这可能会影响 Langchain-Chatchat 应用的性能，从而影响结果。
> 
> 关于您的第二个问题，“文档数量”通常指的是知识库中的文档总数。这个数量可能会受到以下几个因素的影响：
> 
> 1. **上传新的文档**：当通过 `upload_docs` 函数上传新的文档到知识库时，这些文档会被保存到磁盘，然后进行向量化。这会增加文档数量。
> 2. **更新现有的文档**：`update_docs` 函数允许更新知识库中现有的文档。如果更新包括添加新的文档，这会增加文档数量。
> 3. **删除文档**：`delete_docs` 函数允许从知识库中删除文档。这会减少文档数量。
> 4. **重新创建向量存储**：`recreate_vector_store` 函数会从内容中重新创建向量存储。如果这个过程包括添加新的文档，它会增加文档数量。
> 
> 请注意，这些都是可能的因素，实际影响文档数量的因素会取决于这些函数的具体实现以及用户进行的操作。
> 
> 关于上传知识库文件的具体过程，您可以参考我在上文中的回答。如果您需要更多的帮助，或者有其他的问题，欢迎随时向我提问。
> 
> ## Sources
> * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> * [webui_pages/knowledge_base/knowledge_base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/knowledge_base/knowledge_base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

请问你是机器人回复的吗？还是有人工参与成分；这个答案我暂时不敢认可

**Comment by helix-dan** [comment]
我们原本想解决 AI 目前带来的 Bug，但解决的这个过程还拍一个 AI 来回复，感觉不太好呀~

**Comment by zRzRzRzRzRzRzR** [comment]
额你这两个机子配置和文件完全一样？

**Comment by helix-dan** [comment]
> 额你这两个机子配置和文件完全一样？

1、两台机器硬件配置完全不同
2、两台机器 chatchat 版本，配置，知识库文件完全相同；因为都是昨天新部署的

1台是：i7 CPU + RTX4080 GPU，跑在本地；这台机器 embedding 一个文件特别快，基本上几秒钟就可以
另1台是：阿里云的 ecs 云服务器，没有 GPU 的，就是普通的 8核16G 的云服务器；这台机器 embedding 一个上述同样的文件，则需要至少 2-5 分钟

**Comment by helix-dan** [comment]
发现
**在阿里云部署的 chatchat**
上传 txt 知识库后，embedding 切割成了 137 段，段落切割的很不完美（如下图）
回答效果差
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1751530/4d9dff5c-45c2-4f1e-8c98-9e5cd78e90e5)


**在本地 Ubuntu 部署的 chatchat**
上传 txt 知识库后，embedding 切割成了 88 段，段落切割的效果较好，段落头尾都正确（如下图）
回答效果好
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1751530/760ba3cd-a64a-48a8-b2af-8b1405e0b0a4)


chatchat 的版本，配置都是完全一样的；难不成是因为阿里云系统的问题？

**Comment by helix-dan** [comment]
> 额你这两个机子配置和文件完全一样？

找到了一个不一样的地方~

本地的 chatchat 加载了本地模型：ChatGLM2-6B
阿里云的 chatchat 没有加载任何本地模型，只有 zhipu-api

也就是说区别只有配置项里的这个（见下图）
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1751530/f6db938c-83d0-44fe-ad5f-e7f40772f414)

同时，我也验证了，就是这里的配置项导致本问题的存在；

这个是为啥呀？为何 embedding 还会依赖本地模型的能力？很奇怪，当前也并没有这个本地模型的能力

**Comment by zRzRzRzRzRzRzR** [comment]
那你选择的embedding模型应该是huggingface，而不是默认的，如果是huggingface，是会读取本地模型的tokenizer的

**Comment by helix-dan** [comment]
> 那你选择的embedding模型应该是huggingface，而不是默认的，如果是huggingface，是会读取本地模型的tokenizer的

这么说，读取本地模型的 tokenizer 效果会好很多对吧？
如果换成默认的，效果就差一些

**Comment by helix-dan** [comment]
> 那你选择的embedding模型应该是huggingface，而不是默认的，如果是huggingface，是会读取本地模型的tokenizer的

从哪里的配置项能看到我用的是 huggingface 还是 默认？
