### ISSUE TITLE
[BUG] 没有找到聊天提问框的图标在哪里修改

### ISSUE THREAD

**Issue by wcw1996119** [chatchat-space/Langchain-Chatchat#2778]
如图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63002387/cfafca8e-20cb-4a39-9689-290a38ee6c69)
在chatbox里的图像是回答框的图标，但是想替换提问框的图标，找不到在哪

**Comment by wcw1996119** [comment]
> _🤖_
> 
> 你好，@wcw1996119！很高兴再次与你交流，希望你近况还好。
> 
> 根据我对Langchain-Chatchat代码库的理解，UI元素如聊天框和图标在`webui.py`文件中进行管理。这个文件使用Streamlit库来设置web界面。聊天框可能在`webui_pages.dialogue.dialogue`模块的`chat_box`函数中定义，图标在`pages`字典中指定，如"icon": "chat"和"icon": "hdd-stack"等。
> 
> 然而，我没有找到具体的文件或模块来处理渲染聊天框和相关图标。这可能是因为这部分代码被封装在某个特定的模块或者库中，或者是在我没有提供的上下文中。
> 
> 如果你能提供更多关于你想要修改的图标的信息，比如它的名称或者它在哪个页面上，我可能能更好地帮助你找到修改它的方法。同时，你也可以尝试在`webui.py`文件或者相关的模块中搜索图标的名称或者相关的关键词，看是否能找到相关的代码。
> 
> 如果你有任何其他问题，或者需要更多的帮助，欢迎随时向我提问。
> 
> ## Sources
> * [server/model_workers/qianfan.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/qianfan.py)
> * [server/static/swagger-ui.css](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/static/swagger-ui.css)
> * [webui.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

以下是chat_box的定义，定义的是回答框，而不是提问框。此外，提问框的图标在img文件夹也找不到。
chat_box = ChatBox(
    assistant_avatar=os.path.join(
        "img",
        "chat.png"
    )
)

**Comment by zRzRzRzRzRzRzR** [comment]
问streamlit，我记得是改不了

**Comment by lzh1998-jansen** [comment]
> 问streamlit，我记得是改不了

这个为啥改不了，修改了webui.py的 图片地址和文字内容，他为啥不生效呢？
