### ISSUE TITLE
[BUG] 配置多个本地模型，UI端切换本地模型进行问答，回答模型信息错误

### ISSUE THREAD

**Issue by cardinals** [chatchat-space/Langchain-Chatchat#2780]
**环境信息 / Environment Information**
- Langchain-Chatchat-0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： chatglm3-6b, Qwen-1_8B-Chat, Yi-6B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: windows 11 
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:
model_config.py本地模型配置信息
LLM_MODELS = ["chatglm3-6b", "Qwen-1_8B-Chat", "Yi-6B-Chat"]  # "Qwen-1_8B-Chat",
"llm_model": {
        # 以下部分模型并未完全测试，仅根据fastchat和vllm模型的模型列表推定支持
        "chatglm3-6b": "D:\\yujiliworkspace\\model\\chatglm3-6b",
        "Qwen-1_8B-Chat": "D:\\yujiliworkspace\\model\\Qwen-1_8B-Chat",
        "Yi-6B-Chat": "D:\\yujiliworkspace\\model\\Yi-6B-Chat",

    },
server_config.py本地模型配置信息
    "Qwen-1_8B-Chat": {  # 使用default中的IP和端口
       "device": LLM_DEVICE,
       "port": 20003,
    },
    "chatglm3-6b": {  # 使用default中的IP和端口
        "device": LLM_DEVICE,
    },
    "Yi-6B-Chat": {  # 使用default中的IP和端口
        "device": LLM_DEVICE,
        "port": 20004,
    },
**附加信息 
1、运行项目，成功加载三个本地模型，三个本地模型都是running状态如下图所示：
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/3808302/f22a7d75-f3c4-4ab1-97ef-9ede3a63a1a7)

2、选择一个零一万物模型进行问答如下图所示：
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/3808302/02e12a88-1c64-4e00-b8d2-9b665da4e1bc)

3、切换到千问模型进行问答，但是回答错误，仍然是上一步骤的零一万物模型，如下图所示：
![3](https://github.com/chatchat-space/Langchain-Chatchat/assets/3808302/9a9062a8-12cd-4ea5-82b5-1daf0676f647)

4、人工手动刷新浏览器，然后再选择千问模型，回答正确，如下图所示：
![4](https://github.com/chatchat-space/Langchain-Chatchat/assets/3808302/273246bf-7fc3-46d3-8cf5-3129864c6ba8)

5、后台输出无错误信息，如下图所示：
![10](https://github.com/chatchat-space/Langchain-Chatchat/assets/3808302/d08c07fd-9419-4ad7-91dd-0fe351a1857a)

6、使用浏览器版本为Chrome 120.0.6099.225（正式版本） （64 位

**Comment by cardinals** [comment]
1、首先模型的加载不存在问题，输出如下：
python版本：3.10.12 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 19:01:18) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.352. fastchat版本：0.2.34


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'Qwen-1_8B-Chat', 'Yi-6B-Chat'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'D:\\yujiliworkspace\\model\\chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'D:\\yujiliworkspace\\model\\Qwen-1_8B-Chat',
 'model_path_exists': True,
 'port': 20003}
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'D:\\yujiliworkspace\\model\\Yi-6B-Chat',
 'model_path_exists': True,
 'port': 20004}
当前Embbedings模型： bge-large-zh @ cuda


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://127.0.0.1:8501

2、设备配置不存在问题
EMBEDDING_DEVICE = "auto"
LLM_DEVICE = "auto"
三个本地模型运行时显示的输出信息都是'device': 'cuda',

3、模型的可用性也不存在问题，三个本地模型都是处于running状态
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/3808302/079ab837-891b-4798-9ed0-886619c9b0ff)

4、按照建议一把model_config.py和server_config.py模型加载做了调整，如下：
LLM_MODELS = ["chatglm3-6b", "Qwen-1_8B-Chat", "Yi-6B-Chat"]  
"llm_model": {
        # 以下部分模型并未完全测试，仅根据fastchat和vllm模型的模型列表推定支持
        "chatglm3-6b": "D:\\yujiliworkspace\\model\\chatglm3-6b",
        "Qwen-1_8B-Chat": "D:\\yujiliworkspace\\model\\Qwen-1_8B-Chat",
        "Yi-6B-Chat": "D:\\yujiliworkspace\\model\\Yi-6B-Chat",
    }

FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        # fschat=0.2.33的代码有bug, 如需使用，源码修改fastchat.server.vllm_worker，
        # 将103行中sampling_params = SamplingParams的参数stop=list(stop)修改为stop= [i for i in stop if i!=""]
        "infer_turbo": False,

        # model_worker多卡加载需要配置的参数
        # "gpus": None, # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        # "num_gpus": 1, # 使用GPU的数量
        # "max_gpu_memory": "20GiB", # 每个GPU占用的最大显存

        # 以下为model_worker非常用参数，可根据需要配置
        # "load_8bit": False, # 开启8bit量化
        # "cpu_offloading": None,
        # "gptq_ckpt": None,
        # "gptq_wbits": 16,
        # "gptq_groupsize": -1,
        # "gptq_act_order": False,
        # "awq_ckpt": None,
        # "awq_wbits": 16,
        # "awq_groupsize": -1,
        # "model_names": LLM_MODELS,
        # "conv_template": None,
        # "limit_worker_concurrency": 5,
        # "stream_interval": 2,
        # "no_register": False,
        # "embed_in_truncate": False,

        # 以下为vllm_worker配置参数,注意使用vllm必须有gpu，仅在Linux测试通过

        # tokenizer = model_path # 如果tokenizer与model_path不一致在此处添加
        # 'tokenizer_mode':'auto',
        # 'trust_remote_code':True,
        # 'download_dir':None,
        # 'load_format':'auto',
        # 'dtype':'auto',
        # 'seed':0,
        # 'worker_use_ray':False,
        # 'pipeline_parallel_size':1,
        # 'tensor_parallel_size':1,
        # 'block_size':16,
        # 'swap_space':4 , # GiB
        # 'gpu_memory_utilization':0.90,
        # 'max_num_batched_tokens':2560,
        # 'max_num_seqs':256,
        # 'disable_log_stats':False,
        # 'conv_template':None,
        # 'limit_worker_concurrency':5,
        # 'no_register':False,
        # 'num_gpus': 1
        # 'engine_use_ray': False,
        # 'disable_log_requests': False

    },
    # 可以如下示例方式更改默认配置
    "chatglm3-6b": {  # 使用default中的IP和端口
        "device": LLM_DEVICE,
    },
    "Qwen-1_8B-Chat": {  # 使用default中的IP和端口
       "device": LLM_DEVICE,
       "port": 20003,
    },
    "Yi-6B-Chat": {  # 使用default中的IP和端口
        "device": LLM_DEVICE,
        "port": 20004,
    },
}

问题依旧存在

**Comment by liunux4odoo** [comment]
切换模型后要把历史消息清空，或者把 history_len 设为 0 .
