### ISSUE TITLE
创建知识库出错

### ISSUE THREAD

**Issue by ruanriqing** [chatchat-space/Langchain-Chatchat#2791]
当把文件添加到知识库中的时候，ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
运行python init_database.py --recreate-vs时候也报了相同的错误，  File "/root/autodl-tmp/Langchain-Chatchat/server/knowledge_base/kb_service/base.py", line 37, in normalize
    norm = np.linalg.norm(embeddings, axis=1)
  File "<__array_function__ internals>", line 200, in norm
  File "/root/miniconda3/lib/python3.10/site-packages/numpy/linalg/linalg.py", line 2541, in norm
    s = (x.conj() * x).real
TypeError: loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by maopai** [comment]
我也遇到了一样的报错

**Comment by ruanriqing** [comment]
> 我也遇到了一样的报错

怎么解决的呀

**Comment by zRzRzRzRzRzRzR** [comment]
我怎么感觉是这个文件有什么无法读入的问题，samples的话哪个文件报错的

**Comment by william20001120** [comment]
我也遇到了，不知道如何解决。
