### ISSUE TITLE
[BUG] 对于有旋转的PDF支持不佳

### ISSUE THREAD

**Issue by songpb** [chatchat-space/Langchain-Chatchat#2792]
**问题描述**
对于有旋转的PDF（page.rotation!=0），会直接用旋转的图片进行OCR，得到的文本内容和格式均不正确，导致问答结果不理想

**复现问题的步骤**
PDF为内部文档暂无法提供

**解决方法**
修改RapidOCRPDFLoader类，检测到page.rotation!=0时，对img_list中的图片做相应角度旋转后再送入ocr。不是contributer，无法提交，哪位大佬修复一下

**Comment by zRzRzRzRzRzRzR** [comment]
是的，目前没有对这方面进行优化，因为也没有太多开源的解决方案
