### ISSUE TITLE
[BUG] 知识库页面的表格出错

### ISSUE THREAD

**Issue by fsj621** [chatchat-space/Langchain-Chatchat#2795]
在和知识库对话时可以找到已经添加的文件，但是表格中一直显示"x"
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/126898251/f820ed8d-a2cb-4c07-ba73-3ea2849543ac)
终端报错：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/126898251/bafbd6c4-c650-4def-ab96-9b4caa58b738)

**Comment by fsj621** [comment]
终端错误信息：
2024-01-25 09:02:11.069 ComponentRequestHandler: GET /home/cxadmin/miniconda3/envs/langchain_v290/lib/python3.11/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map read error
Traceback (most recent call last):
  File "/home/cxadmin/miniconda3/envs/langchain_v290/lib/python3.11/site-packages/streamlit/web/server/component_request_handler.py", line 51, in get
    with open(abspath, "rb") as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/cxadmin/miniconda3/envs/langchain_v290/lib/python3.11/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map'

**Comment by fsj621** [comment]
> _🤖_
> 
> 你好，@fsj621！很高兴再次看到你在这里。希望你一切都好。
> 
> 根据您提供的信息，知识库页面的表格显示"x"可能是由于文件没有在数据库或本地知识库文件夹中正确注册。表格中的"in_folder"和"in_db"列使用了一个单元格渲染函数，该函数会检查文件是否存在于相应的位置。如果文件不存在，该函数将返回'×'。
> 
> 这是相关的代码段：
> 
> ```python
> cell_renderer = JsCode("""function(params) {if(params.value==true){return '✓'}else{return '×'}}""")
> ```
> 
> ```python
> gb = config_aggrid(
>     doc_details,
>     {
>         ("No", "序号"): {},
>         ("file_name", "文档名称"): {},
>         ("document_loader", "文档加载器"): {},
>         ("docs_count", "文档数量"): {},
>         ("text_splitter", "分词器"): {},
>         ("in_folder", "源文件"): {"cellRenderer": cell_renderer},
>         ("in_db", "向量库"): {"cellRenderer": cell_renderer},
>     },
>     "multiple",
> )
> ```
> 
> 如果在与知识库对话中可以找到文件，但表格仍显示'×'，那么可能需要检查`get_kb_file_details`函数和`file_exists`函数的实现，以确保它们正常工作。
> 
> 关于终端的错误信息，我无法从您提供的截图中看到具体的错误信息。如果可能的话，能否提供一下终端的错误信息？这将有助于我更好地理解和解决问题。
> 
> 相关源代码：
> 
> * [webui_pages/knowledge_base/knowledge_base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/knowledge_base/knowledge_base.py)
> 
> ## Sources
> * [webui_pages/knowledge_base/knowledge_base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/webui_pages/knowledge_base/knowledge_base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot 终端错误信息：
2024-01-25 09:02:11.069 ComponentRequestHandler: GET /home/cxadmin/miniconda3/envs/langchain_v290/lib/python3.11/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map read error
Traceback (most recent call last):
File "/home/cxadmin/miniconda3/envs/langchain_v290/lib/python3.11/site-packages/streamlit/web/server/component_request_handler.py", line 51, in get
with open(abspath, "rb") as file:
^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/cxadmin/miniconda3/envs/langchain_v290/lib/python3.11/site-packages/st_aggrid/frontend/build/bootstrap.min.css.map'

**Comment by 302658980** [comment]
我也遇到了这个问题 有解决吗 老哥

**Comment by fsj621** [comment]
> 我也遇到了这个问题 有解决吗 老哥

这两行注释掉就好了：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/126898251/7e4ad874-ea9f-4101-b151-1cb2834c570b)

**Comment by litongyun233** [comment]
我也遇到了这个问题
