### ISSUE TITLE
使用ggml量化后的模型怎么加载？

### ISSUE THREAD

**Issue by pingwujinchu** [chatchat-space/Langchain-Chatchat#2799]
对于量化后的文件，怎么加载？
<img width="315" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/18208104/6e0c2e53-25b3-473a-b565-3e9944f7de16">

使用chatgml本地api的怎么配置？
from langchain.llms import ChatGLM
llm = ChatGLM(endpoint_url="http://127.0.0.1:8000", max_token=2048, top_p=0.7, temperature=0.95, with_history=False)

**Comment by pingwujinchu** [comment]
试了一下，会提示:
 huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': '../chatglm.cpp/chatglm-ggml'. Use `repo_type` argument if needed.

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有对除了huggingface fp16推理之外的模型做适配
