### ISSUE TITLE
[BUG] 对文档切片内容修改后的错误

### ISSUE THREAD

**Issue by fsj621** [chatchat-space/Langchain-Chatchat#2800]
执行步骤：
1. 在知识库管理页面对某一文档切片内容进行修改
2. 在对话页面提问与刚刚切片内容相关的问题
3. 再次返回知识库管理页面
此时出现问题：刚刚被修改后的文档只剩下这一切片内容，其余内容都不见了，重新添加至向量库也没有用

**Comment by yang1111-gif** [comment]
> _🤖_
> 
> 你好，@fsj621！很高兴再次和你交流。希望你过得很好！
> 
> 您遇到的问题可能是由于 `update_docs_by_id` 函数的实现方式导致的。
> 
> 在 `update_docs_by_id` 函数中，文档是根据提供的 `docs` 字典进行更新的，该字典包含文档 ID 和相应的内容。如果 `docs` 字典只包含文档的修改后的切片，那么只有该切片会被更新，文档的其余部分将会丢失。
> 
> 这是 `update_docs_by_id` 函数的代码：
> 
> ```python
> def update_docs_by_id(
>         knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]),
>         docs: Dict[str, Document] = Body(..., description="要更新的文档内容，形如：{id: Document, ...}")
> ) -> BaseResponse:
>     '''
>     按照文档 ID 更新文档内容
>     '''
>     kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
>     if kb is None:
>         return BaseResponse(code=500, msg=f"指定的知识库 {knowledge_base_name} 不存在")
>     if kb.update_doc_by_ids(docs=docs):
>         return BaseResponse(msg=f"文档更新成功")
>     else:
>         return BaseResponse(msg=f"文档更新失败")
> ```
> 
> 要解决这个问题，您需要确保 `docs` 字典包含整个文档的内容，而不仅仅是修改后的切片。如果您只想修改文档的一部分，您应该首先获取整个文档，修改所需的切片，然后使用修改后的内容更新文档。
> 
> `update_docs_by_id` 函数在 `KBService` 类的 `update_doc_by_ids` 方法中被调用。这个方法接收一个文档的字典，其中键是文档 ID，值是 `Document` 对象。如果文档的值为 `None` 或其 `page_content` 为空，那么该文档将被删除。然后，将剩余的文档添加到知识库中。
> 
> 这是相关的代码：
> 
> ```python
> def update_doc_by_ids(self, docs: Dict[str, Document]) -> bool:
>     '''
>     传入参数为： {doc_id: Document, ...}
>     如果对应 doc_id 的值为 None，或其 page_content 为空，则删除该文档
>     TODO：是否要支持新增 docs ？
>     '''
>     self.del_doc_by_ids(list(docs.keys()))
>     docs = []
>     ids = []
>     for k, v in docs.items():
>         if not v or not v.page_content.strip():
>             continue
>         ids.append(k)
>         docs.append(v)
>     self.do_add_doc(docs=docs, ids=ids)
>     return True
> ```
> 
> 在这个方法中，首先调用 `self.del_doc_by_ids(list(docs.keys()))` 来删除给定 ID 的文档。然后，方法遍历 `docs` 字典。如果文档的值不为 `None` 并且其 `page_content` 不为空，那么文档 ID 将被添加到 `ids` 列表中，文档将被添加到 `docs` 列表中。最后，调用 `self.do_add_doc(docs=docs, ids=ids)` 将剩余的文档添加到知识库中。
> 
> 希望这个解答能帮助您解决问题。如果您有任何其他问题或需要进一步的澄清，请随时告诉我。
> 
> ## Sources
> * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> * [server/knowledge_base/kb_service/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

不对吧，在页面修改文档片段内容，没有调用update_docs_by_id函数吧，我标记了这个函数，在页面也测试了，没有走这个函数。但是确实修改了一个片段，其他的片段都没了，这是为什么？
