### ISSUE TITLE
[BUG] 简洁阐述问题 / 调用agent工具失败 ，实际是查询返回了

### ISSUE THREAD

**Issue by AlexNilone** [chatchat-space/Langchain-Chatchat#2801]
版本。2.0.9
qianwen7b-4int

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/79305340/1178876e-9f96-4139-9233-d4d7f49c337e)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/79305340/1c7100ef-b8e7-42b8-827f-513fd4d94e25)

**Comment by zRzRzRzRzRzRzR** [comment]
应该是因为qianwen7b-4int不是在Agent_Models里面的原因？在后台的处理方法是不一样的

**Comment by AlexNilone** [comment]
Agent_Models是在哪儿加？SUPPORT_AGENT_MODEL？

**Comment by zRzRzRzRzRzRzR** [comment]
SUPPORT_AGENT_MODEL 是的

**Comment by AlexNilone** [comment]
> SUPPORT_AGENT_MODEL 是的

不是这个问题。加了也一样。
