### ISSUE TITLE
私有化部署完成之后，下载知识库文档，域名是127.0.0.1

### ISSUE THREAD

**Issue by ggjjlldd** [chatchat-space/Langchain-Chatchat#2803]
**问题描述 / Problem Description**
我的访问域名，chat.nhnao.com
私有化部署完成之后，下载知识库文档，域名是127.0.0.1, 应该是 chat.nhnao.com

**复现问题的步骤 / Steps to Reproduce**
1. 点击知识库，文档下载

**预期的结果 / Expected Result**
http://chat.nhnao.com/knowledge_base/download_doc?knowledge_base_name=

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
http://127.0.0.1:7861/knowledge_base/download_doc?knowledge_base_name=

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
默认启动时127.0.0.1，你需要改启动的ip地址为你的局域网网址

**Comment by Adsryen** [comment]
> 默认启动时127.0.0.1，你需要改启动的ip地址为你的局域网网址

如何修改启动ip呀？使用的默认的faiss数据库

**Comment by zRzRzRzRzRzRzR** [comment]
server config
