### ISSUE TITLE
关于windows 10 安装jq问题

### ISSUE THREAD

**Issue by tomdogs1** [chatchat-space/Langchain-Chatchat#2804]
**问题描述 / Problem Description**
windows 10 使用conda install jq后，python import jq失败

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'conda install jq' 完成安装
2. 导入 'import jq' 进行导入
3. 问题出现 'ModuleNotFoundError: No module named 'jq''
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42016093/931b8f8c-dde0-4f9a-afd1-adbe200bc083)

**预期的结果 / Expected Result**
python 可以正常导入jq包

**实际结果 / Actual Result**
提示错误 'ModuleNotFoundError: No module named 'jq''

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: windows 10
- Python 版本 / Python version:3.10.13
- 其他相关环境信息 / Other relevant environment information:
conda 23.11.0

**Comment by zRzRzRzRzRzRzR** [comment]
查看一下wiki有写，如果还不行，那就 conda jq要先装，在装requirement

**Comment by yumu7777777** [comment]
Windows 安装数据库插件编译是怎么通过的呢
