### ISSUE TITLE
在知识库管理页面文档编辑有字符限制

### ISSUE THREAD

**Issue by fsj621** [chatchat-space/Langchain-Chatchat#2806]
在知识库管理页面编辑文档内容时，超出一定字符数则无法输入

**Comment by zRzRzRzRzRzRzR** [comment]
大概是多少，也有可能是达到了streamlit的上限，毕竟是个演示的demo页面

**Comment by zRzRzRzRzRzRzR** [comment]
对的，streamlit有最大上限

**Comment by fsj621** [comment]
> 对的，streamlit有最大上限

请问可以通过参数修改最大上限吗
