### ISSUE TITLE
API通信超时，请确认已启动FastChat与API服务

### ISSUE THREAD

**Issue by aaalionaaa** [chatchat-space/Langchain-Chatchat#2807]
使用的是chatglm3-6b模型，在进行知识库问答时，有时候会出不来回答，后台会出现“API通信超时，请确认已启动FastChat与API服务“的报错。请问这是什么原因？有没有解决办法？

**Comment by aaalionaaa** [comment]
> _🤖_
> 
> 你好 @aaalionaaa，很高兴再次与你交流！希望你今天一切顺利。🚀
> 
> 您收到的“API通信超时，请确认已启动FastChat与API服务”错误提示表明Langchain-Chatchat应用无法与FastChat服务或API服务进行通信。这可能有以下几个原因：
> 
> 1. FastChat服务或API服务未运行：请确保这两个服务都已启动并运行。您通常可以在终端或命令提示符中运行这些服务，并检查是否有任何错误消息。
> 2. 服务在不同的端口上运行：Langchain-Chatchat应用需要在特定的端口上与FastChat服务和API服务进行通信。如果这些服务在不同的端口上运行，应用将无法建立连接。请检查您的设置中的端口配置，确保它们匹配。
> 3. 网络问题：如果您的网络速度慢或不稳定，可能会导致超时错误。检查您的网络连接，然后再试一次。
> 
> 在提供的上下文中，API服务器默认在主机"0.0.0.0"和端口7861上运行。您可以在以下代码行中确认这些设置：
> 
> ```python
> parser.add_argument("--host", type=str, default="0.0.0.0")
> parser.add_argument("--port", type=int, default=7861)
> ```
> 
> 并且服务器在以下行中使用这些设置启动：
> 
> ```python
> run_api(host=args.host,
>         port=args.port,
>         ssl_keyfile=args.ssl_keyfile,
>         ssl_certfile=args.ssl_certfile,
>         )
> ```
> 
> 请确保FastChat服务和API服务在正确的主机和端口上运行，Langchain-Chatchat应用配置为在正确的主机和端口上连接到这些服务。如果问题仍然存在，您可能需要检查FastChat服务和API服务的日志以查找任何错误消息。
> 
> 关于FastChat服务在Langchain-Chatchat应用中的具体功能，您可以参考[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/chat.py)的解释。
> 
> 如果您有任何其他问题，或者需要进一步的帮助，请随时告诉我。
> 
> ## Sources
> * [server/api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/api.py)
> * [server/chat/chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/chat.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

将server_config中的HTTPX_DEFAULT_TIMEOUT参数调大是否可以缓解这个问题？

**Comment by zRzRzRzRzRzRzR** [comment]
能提供一下报错么

**Comment by aaalionaaa** [comment]
> 能提供一下报错么
2024-01-22 10:20:03 | INFO | stdout | INFO:     127.0.0.1:44724 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-01-22 10:20:03 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-22 10:20:03 | INFO | httpx | HTTP Request: POST http://0.0.0.0:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-22 10:23:44 | ERROR | root | API通信超时，请确认已启动FastChat与API服务（详见RADME '5. 启动 API 服务或 Web UI'）。（timed out）

**Comment by zRzRzRzRzRzRzR** [comment]
这个证明没有找到你的fschat服务啊，跟server_config中的HTTPX_DEFAULT_TIMEOUT没有关系，估计是你fscaht发送的端口和框架接受的端口不符合，或者fschat没有正确启动（只是你看上去启动了）

**Comment by aaalionaaa** [comment]
> 这个证明没有找到你的fschat服务啊，跟server_config中的HTTPX_DEFAULT_TIMEOUT没有关系，估计是你fscaht发送的端口和框架接受的端口不符合，或者fschat没有正确启动（只是你看上去启动了）

想请问下为什么会出现这种情况？因为并不是总连不上。通常是一次服务启动后，几十次提问中会出现一次这种现象

**Comment by aaalionaaa** [comment]
> 这个证明没有找到你的fschat服务啊，跟server_config中的HTTPX_DEFAULT_TIMEOUT没有关系，估计是你fscaht发送的端口和框架接受的端口不符合，或者fschat没有正确启动（只是你看上去启动了）

并且在发生API通信超时后，重新提问一下立刻就能恢复

**Comment by zRzRzRzRzRzRzR** [comment]
那很有可能是fschat不稳定了，如果你的硬件设备不行fschat在推理大模型的时候会有bug也有可能，这些框架鲁棒性都比较垃。。如果你是联网的模型，那么大概率该改HTTPX_DEFAULT_TIMEOUT能解决问题

比较常见的情况是：回答特别长然后断掉了，或者网络不稳定

这个暂时没有什么好的办法
