### ISSUE TITLE
请问下本地模型是如何对齐openai_api-key调用agent的

### ISSUE THREAD

**Issue by iaoxuesheng** [chatchat-space/Langchain-Chatchat#2808]
"Qwen",  # 所有Qwen系列本地模型
    "chatglm3-6b",
    "internlm2-chat-20b",
    "Orion-14B-Chat-Plugin",
这里面的本地模型是如何做到的，怎么生成api-key呢

**Comment by zRzRzRzRzRzRzR** [comment]
没有对其啊，Agent时在lc内实现的，lc的Agent不是openai的Agent，而是采用了截断的方式
