### ISSUE TITLE
请问能否增加网络搜索功能

### ISSUE THREAD

**Issue by jacky68147527** [chatchat-space/Langchain-Chatchat#281]
请问能否增加网络搜索功能
e.g: https://github.com/yanqiangmiffy/Chinese-LangChain

**Comment by xx-zhang** [comment]
可以读取 url 开发，这个好像在规划中。 loader的类型，以及对应的工具和插件的使用，都在开发中，但是本质都是langchain读取结构化/非结构化数据，这些数据的上面一层套要给工具。
