### ISSUE TITLE
[BUG] model_worker 报错，cuda devices数量识别错误参数问题

### ISSUE THREAD

**Issue by yujiang0030** [chatchat-space/Langchain-Chatchat#2810]
**问题描述 / Problem Description**
不能正确识别gpu数量

**复现问题的步骤 / Steps to Reproduce**
1. python环境和项目设置如下：
[env.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/14071230/env.txt)
[model_config.py.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/14071231/model_config.py.txt)
[server_config.py.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/14071233/server_config.py.txt)

2. 执行 'python startup.py --all-api' 

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58059348/5141c01d-acde-4ffe-abcd-e825ea57bb76)
[model_worker_35515e7a.log](https://github.com/chatchat-space/Langchain-Chatchat/files/14071232/model_worker_35515e7a.log)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): 否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 操作系统及版本 / Operating system and version: ubuntu 22.04
- Python 版本 / Python version: 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
在2024-01-17 20:59下载的master代码中可以正常跑

**Comment by yujiang0030** [comment]
实际结果截图那里显示异常的字符是<0x01>

**Comment by zRzRzRzRzRzRzR** [comment]
这个估计是你环境初始化有问题的，我们仓库基本没有动cuda内部的东西，如果你是识别错误，可以看看是不是ocr用了gpu触发了你环境问题，请确保你的显卡和pytorch cuda等都匹配，cuda需要是apt 安装的不是py包
