### ISSUE TITLE
[BUG] v0.2.10版本启动一切正常，但api文档访问报错 "GET /static-offline-docs/swagger-ui.css.map HTTP/1.1" 404 Not Found

### ISSUE THREAD

**Issue by LiYuanHaooo** [chatchat-space/Langchain-Chatchat#2812]
**问题描述 / Problem Description**

访问api文档http://xxxx:7861 ,页面一片空白什么都没显示，日志报错:
```
 "GET /static-offline-docs/swagger-ui.css.map HTTP/1.1" 404 Not Found
```

**环境信息 / Environment Information**
- Langchain-Chatchat版本：v0.2.10
- 是否使用 Docker 部署：是
- 使用的模型：chatglm3-6b-32k
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型 ： milvus
- 操作系统及版本 / Operating system and version: Linux-6.1.0-13-amd64-x86_64-with-glibc2.35.
- Python 版本 / Python version: 3.10.12

**Comment by LiYuanHaooo** [comment]
浏览器控制台报错：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26320670/beaa8060-59cd-4d4a-a4cb-f42cb5619f46)

**Comment by zRzRzRzRzRzRzR** [comment]
好像没有遇到这个问题，尝试降级到0.2.9的streamlit版本 1.29试试？

**Comment by BlueCestbon** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/65054570/458617af-6334-4cf4-a617-b289b72464eb)
一样的报错。

**Comment by LiYuanHaooo** [comment]
我已经解决啦，把源码中的'/server/static/swagger-ui-bundle.js'退回到上个版本就ok了

> ![image](https://private-user-images.githubusercontent.com/65054570/300355004-458617af-6334-4cf4-a617-b289b72464eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTAzNDAsIm5iZiI6MTcwNjUxMDA0MCwicGF0aCI6Ii82NTA1NDU3MC8zMDAzNTUwMDQtNDU4NjE3YWYtNjMzNC00Y2Y0LWE2MTctYjI4OWI3MjQ2NGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA2MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmM2UwZmVjMDc4NDAyNWMzMjQzOGUzZjkzMzYwOTg2ZjQ1OGI2ZDJhMTRmMWZlM2NlMTM3NDRjMGY0N2Y0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVTqS109zeD2gyb1TH5B5XF7H00yQwjzXmbQ56owElk) 一样的报错。

**Comment by BlueCestbon** [comment]
> 我已经解决啦，把源码中的'/server/static/swagger-ui-bundle.js'退回到上个版本就ok了
> 
> > ![image](https://private-user-images.githubusercontent.com/65054570/300355004-458617af-6334-4cf4-a617-b289b72464eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTAzNDAsIm5iZiI6MTcwNjUxMDA0MCwicGF0aCI6Ii82NTA1NDU3MC8zMDAzNTUwMDQtNDU4NjE3YWYtNjMzNC00Y2Y0LWE2MTctYjI4OWI3MjQ2NGViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA2MzQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmM2UwZmVjMDc4NDAyNWMzMjQzOGUzZjkzMzYwOTg2ZjQ1OGI2ZDJhMTRmMWZlM2NlMTM3NDRjMGY0N2Y0MjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZVTqS109zeD2gyb1TH5B5XF7H00yQwjzXmbQ56owElk) 一样的报错。

好嘞，蟹蟹

**Comment by lichangmao** [comment]
一样的问题，回退到v0.2.9 这个版本吗，我这边不行呢

**Comment by BlueCestbon** [comment]
> 一样的问题，回退到v0.2.9 这个版本吗，我这边不行呢

我的也没好，但是部署的另一个0.2.10的就没问题，一模一样的代码和环境

**Comment by lichangmao** [comment]
找到解决方案了，麻烦call我一下

**Comment by ELvis168** [comment]
替换js后，浏览器清理下缓存就好了
