### ISSUE TITLE
autodl 镜像v0.2.10，启动后不报错，但web端打不开

### ISSUE THREAD

**Issue by angelOnly** [chatchat-space/Langchain-Chatchat#2817]
**启动日志**

(/root/pyenv) root@autodl-container-17644a8b4e-fd4c3ebd:~/Langchain-Chatchat# python startup.py -a

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-78-generic-x86_64-with-glibc2.31.
python版本：3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/model/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-01-28 16:36:29,689 - startup.py[line:655] - INFO: 正在启动服务：
2024-01-28 16:36:29,689 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /root/Langchain-Chatchat/logs

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-78-generic-x86_64-with-glibc2.31.
python版本：3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/root/model/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cuda

服务端运行信息：
    Chatchat WEBUI Server: http://0.0.0.0:6006
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:6006

打开后一直加载
<img width="1260" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/18018532/2c837918-7264-4e91-b25c-2ca5e5b9ed0f">

**Comment by zRzRzRzRzRzRzR** [comment]
autodl的有的宿主机有这个问题，之前我遇到这个情况是更换一个宿主机解决的问题
你的机器不是北京区的估计就没有这个问题了。
