### ISSUE TITLE
使用qwen-api进行agent调用，出现IndexError: list index out of range报错

### ISSUE THREAD

**Issue by jayofhust** [chatchat-space/Langchain-Chatchat#2818]
本人环境如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.34

当前使用的分词器：ChineseRecursiveTextSplitter
2024-01-28 20:53:41,580 - utils.py[line:525] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前启动的LLM模型：['qwen-api'] @ cuda
{'api_key': 'sk-94b1cc99847749698f881326612082ca',
 'device': 'auto',
 'embed_model': 'text-embedding-v1',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'online_api': True,
 'port': 21006,
 'provider': 'QwenWorker',
 'version': 'qwen-turbo',
 'worker_class': <class 'server.model_workers.qwen.QwenWorker'>}
2024-01-28 20:53:41,581 - utils.py[line:543] - WARNING: device not in ['cuda', 'mps', 'cpu','xpu'], device = auto
当前Embbedings模型： bge-large-zh @ cuda
-----------------------------------------------------------
报错为：
2024-01-28 20:55:46,438 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-01-28 20:55:46 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21006/worker_generate_stream "HTTP/1.1 200 OK"
2024-01-28 20:55:48,434 - utils.py[line:25] - ERROR: list index out of range
Traceback (most recent call last):
  File "E:\Langchain-CHAT\Langchain-Chatchat\server\utils.py", line 23, in wrap_done
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\agents\agent.py", line 1164, in <listcomp>
    [
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\agents\agent.py", line 1192, in _aiter_next_step
    output = await self.agent.aplan(
  File "F:\Anaconda\envs\langchainpang\lib\site-packages\langchain\agents\agent.py", line 562, in aplan
    return self.output_parser.parse(output)
  File "E:\Langchain-CHAT\Langchain-Chatchat\server\agent\custom_template.py", line 55, in parse
    action_input = parts[1].split("Action Input:")[1].strip()
IndexError: list index out of range
2024-01-28 20:55:48,435 - utils.py[line:28] - ERROR: IndexError: Caught exception: list index out of range
--------------------------------------------------------------------------------------------------

**Comment by jayofhust** [comment]
调用成功之后发现qwen-api还是无法将我的问题回答
我的提问：帮我查询一下现在沈阳的温度
它的回答为：我需要使用weather_check工具来查询天气信息，输入城市名：沈阳。
这是什么问题呢？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142560164/6c945265-ed40-435c-86ee-4550aaa94328)

**Comment by Outstanding** [comment]
> 调用成功之后发现qwen-api还是无法将我的问题回答 我的提问：帮我查询一下现在沈阳的温度 它的回答为：我需要使用weather_check工具来查询天气信息，输入城市名：沈阳。 这是什么问题呢？ ![image](https://private-user-images.githubusercontent.com/142560164/300266663-6c945265-ed40-435c-86ee-4550aaa94328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTM2MjQsIm5iZiI6MTcwNjQ5MzMyNCwicGF0aCI6Ii8xNDI1NjAxNjQvMzAwMjY2NjYzLTZjOTQ1MjY1LWVkNDAtNDM1Yy04NmVlLTQ1NTBhYWE5NDMyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwMTU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjhlMGJmOTA0OWJkZjgzOWJhM2JiNDJkYWI1ZGNmZTRlNGE0NjAzMThmZjU5NzBhYjY0MTUzNTVmZGJmOWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VEjL2K3RtBDX_mHfgkb33TSsH5dU6kjZ3oG3CmLe1YI)

同样问题，请问解决了吗？

**Comment by jayofhust** [comment]
> > 调用成功之后发现qwen-api还是无法将我的问题回答 我的提问：帮我查询一下现在沈阳的温度 它的回答为：我需要使用weather_check工具来查询天气信息，输入城市名：沈阳。 这是什么问题呢？ ![image](https://private-user-images.githubusercontent.com/142560164/300266663-6c945265-ed40-435c-86ee-4550aaa94328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTM2MjQsIm5iZiI6MTcwNjQ5MzMyNCwicGF0aCI6Ii8xNDI1NjAxNjQvMzAwMjY2NjYzLTZjOTQ1MjY1LWVkNDAtNDM1Yy04NmVlLTQ1NTBhYWE5NDMyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwMTU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjhlMGJmOTA0OWJkZjgzOWJhM2JiNDJkYWI1ZGNmZTRlNGE0NjAzMThmZjU5NzBhYjY0MTUzNTVmZGJmOWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VEjL2K3RtBDX_mHfgkb33TSsH5dU6kjZ3oG3CmLe1YI)
> 
> 同样问题，请问解决了吗？

没有解决 抱歉 看看官方的回答吧

**Comment by jayofhust** [comment]
> > 调用成功之后发现qwen-api还是无法将我的问题回答 我的提问：帮我查询一下现在沈阳的温度 它的回答为：我需要使用weather_check工具来查询天气信息，输入城市名：沈阳。 这是什么问题呢？ ![image](https://private-user-images.githubusercontent.com/142560164/300266663-6c945265-ed40-435c-86ee-4550aaa94328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTM2MjQsIm5iZiI6MTcwNjQ5MzMyNCwicGF0aCI6Ii8xNDI1NjAxNjQvMzAwMjY2NjYzLTZjOTQ1MjY1LWVkNDAtNDM1Yy04NmVlLTQ1NTBhYWE5NDMyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwMTU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjhlMGJmOTA0OWJkZjgzOWJhM2JiNDJkYWI1ZGNmZTRlNGE0NjAzMThmZjU5NzBhYjY0MTUzNTVmZGJmOWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VEjL2K3RtBDX_mHfgkb33TSsH5dU6kjZ3oG3CmLe1YI)
> 
> 同样问题，请问解决了吗？

哥们 我以及解决了 在server/chat/agent_chat 86行 修改为：if "chatglm3" in model_container.MODEL.model_name or "Qwen" in model_container.MODEL.model_name: 就可以进行工具调用了

**Comment by zRzRzRzRzRzRzR** [comment]
不对吧，你是不是没有在 config中的Agent_Model 加上 Qwen chatglm3这个是glm3的模板，能用也是巧合了

**Comment by Outstanding** [comment]
> > > 调用成功之后发现qwen-api还是无法将我的问题回答 我的提问：帮我查询一下现在沈阳的温度 它的回答为：我需要使用weather_check工具来查询天气信息，输入城市名：沈阳。 这是什么问题呢？ ![image](https://private-user-images.githubusercontent.com/142560164/300266663-6c945265-ed40-435c-86ee-4550aaa94328.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTM2MjQsIm5iZiI6MTcwNjQ5MzMyNCwicGF0aCI6Ii8xNDI1NjAxNjQvMzAwMjY2NjYzLTZjOTQ1MjY1LWVkNDAtNDM1Yy04NmVlLTQ1NTBhYWE5NDMyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwMTU1MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjhlMGJmOTA0OWJkZjgzOWJhM2JiNDJkYWI1ZGNmZTRlNGE0NjAzMThmZjU5NzBhYjY0MTUzNTVmZGJmOWY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VEjL2K3RtBDX_mHfgkb33TSsH5dU6kjZ3oG3CmLe1YI)
> > 
> > 
> > 同样问题，请问解决了吗？
> 
> 哥们 我以及解决了 在server/chat/agent_chat 86行 修改为：if "chatglm3" in model_container.MODEL.model_name or "Qwen" in model_container.MODEL.model_name: 就可以进行工具调用了

我还一直是API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by jayofhust** [comment]
> 不对吧，你是不是没有在 config中的Agent_Model 加上 Qwen chatglm3这个是glm3的模板，能用也是巧合了

config中的Agent_Model 本来就有 Qwen 啊 我修改了server/chat/agent_chat 原来我是if "chatglm3" in model_container.MODEL.model_name or "qwen-api" in model_container.MODEL.model_name: 还不好使呢
改成if "chatglm3" in model_container.MODEL.model_name or "Qwen" in model_container.MODEL.model_name: 就可以进行工具调用了 把qwen-api变成qwen就好使了

**Comment by sl82976818** [comment]
我没有用Qwen，只用了GLM3-6B，有时候也会出这个问题。似乎与提问的问法有关。
