### ISSUE TITLE
v0.2.10版本部署之后。前端7861/docs的接口文档不可用，前端报错。有遇到这个问题吗

### ISSUE THREAD

**Issue by wgq910668** [chatchat-space/Langchain-Chatchat#2823]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/21257140/a5b62ff7-124d-429a-a4f3-586279e32028)

接口调用是通的。但是swagger 文档是有问题的。希望博主给看一下咋回事。是部署的问题吗？

**Comment by jiatj** [comment]
同样的问题

**Comment by Samuel0807** [comment]
同样的问题，steamlit降到1.29.0依然如此

**Comment by ChenZiHong-Gavin** [comment]
同样的问题

**Comment by shabooboo86** [comment]
将 server/static/swagger-ui-bundle.js 文件还原为 v0.2.9 版本即可。

**Comment by zhanghaotian123** [comment]
同样的问题将 server/static/swagger-ui-bundle.js 文件还原为 v0.2.9 版本也不行

**Comment by Samuel0807** [comment]
Langchain-Chatchat/server/api.py 注销掉39行MakeFastAPIOffline(app)   亲测好用

**Comment by zhanghaotian123** [comment]
@Samuel0807 只需注销掉39行，别的您还改了哪里呀。我注释掉还是不行.

**Comment by zhanghaotian123** [comment]
@Samuel0807 重新试了一下，好使了兄弟，谢谢您。

**Comment by zRzRzRzRzRzRzR** [comment]
已经修复并合并到master分支，感谢发现错误❤️

**Comment by haonanye** [comment]
> 已经修复并合并到master分支，感谢发现错误❤️

master最新代码依然会出现这个问题

**Comment by akrio714** [comment]
1.从swagger官方重新下载[swagger-ui.css](https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui.css)和[swagger-ui-bundle.js](https://github.com/swagger-api/swagger-ui/blob/master/dist/swagger-ui-bundle.js),然后替换服务中server/static 中对应的2个文件。
2.重启项目，也许不需要重启
3.**chrome打开f12关闭缓存**，否则因为文件名相同，浏览器会一直读取旧文件
![微信截图_20240318104901](https://github.com/chatchat-space/Langchain-Chatchat/assets/9791902/fab672f4-e8ce-4176-9319-931539cfad76)

**Comment by danny-zhu** [comment]
我用0.2.7版本中的swagger-ui-bundle.js替换掉0.2.10中的文件，刷新一下浏览器就正常了

**Comment by LGY-111** [comment]
同样的问题，我把上面的方法都尝试了，但是都不起作用。请问解决了吗，可以分享下吗
