### ISSUE TITLE
将60M的csv文件作为知识库的语料上传到Langchain-Chatchat 0.2.9中，总是向量化失败

### ISSUE THREAD

**Issue by Gzj369** [chatchat-space/Langchain-Chatchat#2824]
将60M的csv文件作为知识库的语料上传到Langchain-Chatchat 0.2.9中，总是向量化失败

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.9
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-72B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：gte-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux/ Ubuntu
- Python 版本 / Python version: 3.10

结果查看日志，接口返回了200，实际上向量化总是不成功，除了webui外，我也尝试了 ip:7861/docs/knowledge_base/upload_docs 接口上传同样的文件，发现向量化也不行，如下图所示：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/9278b07d-4d70-413a-956d-0b2c99f293b2)

实际上我看linux服务器下对应路径是存在output5.csv这个文件的，不知道为什么会“加载文档时出错：Error loading”，麻烦各位大佬帮忙看看，非常感谢

**Comment by zRzRzRzRzRzRzR** [comment]
太大了，装不下，文件大小超过10MB就会炸的，这个好像是因为faiss在读写时候的问题

**Comment by zRzRzRzRzRzRzR** [comment]
目前是的
