### ISSUE TITLE
[BUG] 知识库问答多次之后，精度明显下降

### ISSUE THREAD

**Issue by guchengxi1994** [chatchat-space/Langchain-Chatchat#2826]
**问题描述 / Problem Description**
创建了一个简历的知识库，对同一个候选人提问多次（中间清空了几次对话），本来精度还可以的但是之后都反馈的是“很抱歉，无法找到相关信息”

**环境信息 / Environment Information**

- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：baichuan2-13B-chat-4bit
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / ubuntu 22.04
- Python 版本 / Python version: 3.10

因为显存的问题，不清楚是4bit量化导致的还是别的逻辑问题

**Comment by zRzRzRzRzRzRzR** [comment]
额，这能复现吗，我咋复现呢

**Comment by songpb** [comment]
出现“很抱歉，无法找到相关信息”时，能看下命中的知识库内容是否正确么

**Comment by guchengxi1994** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/33513462/ff08f611-c95a-4b4a-b059-9ed5a63d748c)
能够正常对话的时候也没有命中，不清楚是知识库质量不行还是模型量化后精度降低的原因

**Comment by zRzRzRzRzRzRzR** [comment]
> 出现“很抱歉，无法找到相关信息”时，能看下命中的知识库内容是否正确么

如果出现这个，就是没有命中任何东西，这个是写死的

**Comment by zRzRzRzRzRzRzR** [comment]
> ![image](https://private-user-images.githubusercontent.com/33513462/300646271-ff08f611-c95a-4b4a-b059-9ed5a63d748c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1ODQwNTgsIm5iZiI6MTcwNjU4Mzc1OCwicGF0aCI6Ii8zMzUxMzQ2Mi8zMDA2NDYyNzEtZmYwOGY2MTEtYzk1YS00YjRhLWIwNTktOWVkNWE2M2Q3NDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDAzMDIzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4MTNhYmRhNGEzYzJjM2NmYTZhMjU2NjdhNmFjYzdlZjQwY2Y0NTQ3ZDNlN2QwZTY1Y2M2NTJjZTI5MzJlNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h7R9TF8ovD0crr1d1Wo0BznALqR3NfLoPEX5HOps6eg) 能够正常对话的时候也没有命中，不清楚是知识库质量不行还是模型量化后精度降低的原因

标题是不被命中的，只命中文字

**Comment by TKevin0v0** [comment]
请问一下，你用langchain chatchat启动Int4量化需要改哪些配置么。我用chaglm3的量化可以正常启动。但是用langchain chatchat启动就显示显存不足

**Comment by zRzRzRzRzRzRzR** [comment]
因为chatcaht是基于fscaht做的模型读入，所以没有对int4做支持，要的话需要修改fschat的代码

**Comment by zixiaotan21** [comment]
同样在做简历的知识库，想问问楼主大佬选用的是什么分词器呀？感觉无论上传.doc文档还是.pdf文档，使用ChineseRecursiveTextSplitter 分块效果都很差~

**Comment by guchengxi1994** [comment]
简历这种任务，我还是比较建议结构化处理，某些基于大模型能力的任务，比如分析人员特长对公司有没有帮助，可以用大模型，但是单纯从检索上来看，结构化存储更合适

**Comment by zixiaotan21** [comment]
> 简历这种任务，我还是比较建议结构化处理，某些基于大模型能力的任务，比如分析人员特长对公司有没有帮助，可以用大模型，但是单纯从检索上来看，结构化存储更合适

谢谢大佬建议！我是想做一个简历评分模型，把简历放在知识库里，然后根据几个指标建立一个评价模型。

我在想能不能基于langchain-chatchat的框架去做，但感觉分词器这块有点鸡肋，似乎不太需要分词器这个步骤。而且用了分词器，容易出现像之前“帮我介绍一下谢芳这个候选人”类似的检索问题。

**Comment by guchengxi1994** [comment]
如果只是评分的话，可以把评分标准写到prompt里，比如三年以上工作经验5分。之后把简历整个扔给大模型让他出一个最终结果就行了。还有一种做法是自己写评分的相关代码，通过信息抽取把要的信息结构化之后对比一下

**Comment by zixiaotan21** [comment]
谢谢大佬建议！

我是想直接用llm来建立评分模型。比如根据知识库里候选人的工作经历、项目经验、教育背景，三个指标建立层次分析模型，给出一个分数这样。我在gpt里这样做是容易的，但我在langchain chatchat实现效果不太好，不知道是不是llm能力的缘故。

**Comment by guchengxi1994** [comment]
模型能力比较弱的时候，需要通过一些额外的手段提高检索的精准度。比如你要给建立评分，首先要做的是通过技术手段把工作经历、项目经验、教育背景这几块内容找出来，可以是通过大模型，也可以通过一些文档解析工具，然后再根据你的评分规则打分，不能够一股脑想着把事情都做完。GPT底下处理文档多少也有自己的一套方法论，不会是直接ocr提取完成就结束了

**Comment by zixiaotan21** [comment]
好的好的，谢谢大佬！确实不应该一股脑想着把事情都做完，还是要一步一步处理~

想请教一下，文档加载这一步，大佬当时是将: 简历1.pdf, 简历2.pdf 每个文档单独地上传到知识库，没有用分词器做切分是吗？

我是将每个简历以.txt的形式上传，没有用分词器切分，这样每个简历都是单独的一条知识。但似乎这样，会造成每一条的知识特别长，影响到向量检索的精度？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/5d0eddc2-8a97-4090-b78b-ea0e88bc901e)


> ![image](https://private-user-images.githubusercontent.com/33513462/300646271-ff08f611-c95a-4b4a-b059-9ed5a63d748c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTc3MzYsIm5iZiI6MTcxNjc5NzQzNiwicGF0aCI6Ii8zMzUxMzQ2Mi8zMDA2NDYyNzEtZmYwOGY2MTEtYzk1YS00YjRhLWIwNTktOWVkNWE2M2Q3NDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDA4MTAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMTI2ZTk4YzM1MWJmNzFiMTgwMWI1OGE2ZjUxNjE1NWQyYTE1NDk3YjU4N2QxYmQ5NmE3NTFiMjZmODRkMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMFawyOYRDjowfIgmqISwD83OdGf_dQY1eecuog6lYw) 能够正常对话的时候也没有命中，不清楚是知识库质量不行还是模型量化后精度降低的原因

**Comment by guchengxi1994** [comment]
chatchat默认向量切分应该是250长度，如果觉得匹配有问题可以适当增加切分的长度或者匹配的条目数量或者提问的时候更加详细，当然这个取决于你机器显存大小
