### ISSUE TITLE
[BUG] 上传知识文件时，遇到大于2MB的文件易出现卡死现象

### ISSUE THREAD

**Issue by honeyandme** [chatchat-space/Langchain-Chatchat#2827]
**问题描述 / Problem Description**
<img width="856" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/14360860/5fd9148c-1590-46a9-8eb7-3999c8f68612">
上传文件时卡死在这个界面，进度条一直不动，此文件仅3.6MB。(此时还没有上传到向量数据库)
但是当我把这个文件里的图片删去，文件不到1MB后，就可以上传成功。
估计是streamlit的问题？

**Comment by zRzRzRzRzRzRzR** [comment]
这是你网络的问题，有网络有限制单个上传文件大小，nginx等配置查看一下
