### ISSUE TITLE
[FEATURE] 结构化数据sql、excel、csv啥时会支持呐。

### ISSUE THREAD

**Issue by ThinkInFuture** [chatchat-space/Langchain-Chatchat#283]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by bosir** [comment]
同问

**Comment by hunter2009pf** [comment]
excel可以使用pandas库转json，然后再指定单元切割json chunk。现在英文测试一切正常，请问pandas库怎么在linux下支持GB2312编码的中文excel文件解码啊，急啊！

**Comment by youbingchenyoubing** [comment]
已经支持了吗
