### ISSUE TITLE
[BUG] 使用知识库问答时报错，总是不能回答最新的一个问题

### ISSUE THREAD

**Issue by 1838171762** [chatchat-space/Langchain-Chatchat#2830]
我想使用知识库问答，但是报错NotFoundError： 无法在“节点”上执行“removeChild”：要删除的节点不是此节点的子节点。它总是回答不了最新的问题，但是总会在我提出新的问题之后，正确的返回之前问题的回答。
![微信图片_20240129153727](https://github.com/chatchat-space/Langchain-Chatchat/assets/156059459/1a936a51-7a5a-4c32-b6ac-bf7b2cd35c07)

**Comment by zRzRzRzRzRzRzR** [comment]
刷新会吗，估计是有个进程不对导致id错了

**Comment by shu1ao2han3** [comment]
> 刷新会吗，估计是有个进程不对导致id错了

刷新之后也会有这个报错，和题主描述的一样。
