### ISSUE TITLE
[BUG]在知识库创建完成后，上传文档时无论选择何种格式的文档，报错：AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by Luminous-seed** [chatchat-space/Langchain-Chatchat#2831]
**问题描述 / Problem Description**
在知识库创建完成后，上传文档时无论选择何种格式的文档，无论大小，都会报错：AxiosError: Request failed with status code 403

**复现问题的步骤 / Steps to Reproduce**
1. 使用python startup.py -a 可以正常启动各个worker，过程中未见到控制台出现报错。 
2. 打开webUI界面，”对话“选项卡下，本地的ChatGLM3-6B和讯飞星火都可以正常运行，回答功能流畅
3. 打开webUI界面，”知识库管理“选项卡下，创建知识库没有问题，可以直接生成；但是选择某一知识库，准备进行文档上传操作时，在选择本地文档后，文档后不出现进度条，直接出现报错：AxiosError: Request failed with status code 403

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.9
- 是否使用 Docker 部署：否
- 使用的模型：ChatGLM3-6B和讯飞星火
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux：Ubuntu22.04
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
1、在”知识库管理“界面进行文档选择直至报错的过程中，控制台无消息反馈。
2、我曾在5天前成功的创建了知识库，并且成功传入了本地知识文件。

**Comment by Luminous-seed** [comment]
我可以确认以下几点：
1、目前的报错并没有出现”code403”以及“donot attack me“的字样，而是出现了”AxiosError: Request failed with status code 403“，出现报错代码在webUI界面的位置是【上传的文档之后】
2、可以确定【知识库的名称】没有问题，因为该知识库在之前已经创建成功，且已经已经成功上传了一些文档；同时也可以确定【上传的文件】的名称没有任何特殊字符，仅由汉字组成。

**Comment by zak834** [comment]
你好，请问这个问题解决了吗

**Comment by pengkuo-110** [comment]
兄弟們 啥問題

**Comment by mashagua** [comment]
@dosubot 这个..是knowledge_base_id,可是我文件里并没有..，所以我怎么知道我的knowledge_base_id里有..?

**Comment by murdonson** [comment]
一样 我也遇到了这个问题 怎么办啊

**Comment by Luminous-seed** [comment]
> 一样 我也遇到了这个问题 怎么办啊

目前还没有解决，我以为是项目可能哪些地方调出问题了。
就把项目重新下载了一遍，相关的config文件配置好之后，新项目可以正常运行到web界面，一切运行正常。
但是在上传文档时仍然遇到了这个问题，错误代码也没有变化，有点小绝望，

**Comment by murdonson** [comment]
> > 一样 我也遇到了这个问题 怎么办啊
> 
> 目前还没有解决，我以为是项目可能哪些地方调出问题了。 就把项目重新下载了一遍，相关的config文件配置好之后，新项目可以正常运行到web界面，一切运行正常。 但是在上传文档时仍然遇到了这个问题，错误代码也没有变化，有点小绝望，

你用audodl 别人做好的镜像 试试 就没有这个问题了 https://www.codewithgpu.com/i/chatchat-space/Langchain-Chatchat/Langchain-Chatchat

**Comment by mashagua** [comment]
> > > 一样 我也遇到了这个问题 怎么办啊
> > 
> > 
> > 目前还没有解决，我以为是项目可能哪些地方调出问题了。 就把项目重新下载了一遍，相关的config文件配置好之后，新项目可以正常运行到web界面，一切运行正常。 但是在上传文档时仍然遇到了这个问题，错误代码也没有变化，有点小绝望，
> 
> 你用audodl 别人做好的镜像 试试 就没有这个问题了 https://www.codewithgpu.com/i/chatchat-space/Langchain-Chatchat/Langchain-Chatchat

所以别人的镜像中是改了哪部分？

**Comment by youbingchenyoubing** [comment]
不行啊,我直接用master分支的代码,也出现了AxiosError: Request failed with status code 403

**Comment by Joeking-around** [comment]
跨域问题吗 把CORS设成true试试

**Comment by murdonson** [comment]
很奇怪 别人autodl镜像 有时候没有这个问题 有时候又有这个问题

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索

**Comment by LeoQianQY** [comment]
后台报的这个错误ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by DharmaBums1991** [comment]
安装不同版本streamlit试试，我降级到1.28.0解决了

**Comment by TongDog** [comment]
> 安装不同版本streamlit试试，我降级到1.28.0解决了

确实解决了！感谢

**Comment by mayiwei** [comment]
上传任何文件都是 AxiosError: Network Error 错误 ，各位遇到过吗？

**Comment by ocpinfo** [comment]
创建.streamlit目录下的config.toml，加入如下内容：
[server]
enableXsrfProtection = false
可以解决403这个问题

**Comment by NasaWu** [comment]
> 安装不同版本streamlit试试，我降级到1.28.0解决了

我永远的哥

**Comment by tianqi1614** [comment]
这个问题我绕了很久，他们都不肯多说一句，升级streamlit>=1.33.0回报另外的错误，需要同时升级streamlit1.1.12以上，然而升级没有什么用，修改目录权限也没有用，我时试了新建config.toml 在.streamlit下
[server]
enableXsrfProtection = false
enableCORS = false
但是这个目录不是建在streamlit安装目录下，而是建在工程目录下新建一个streamlit 把config.toml复制进去，再修改文件名为.streamlit，重启后可以了

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索
