### ISSUE TITLE
Langchain-Chatchat 支持知识库 上传音频么？直接语音回答问题。

### ISSUE THREAD

**Issue by TzyTman** [chatchat-space/Langchain-Chatchat#2832]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by TzyTman** [comment]
谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: dosubot[bot] ***@***.***&gt;
发送时间: 2024年1月29日 16:45
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: tuzhengyao ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [chatchat-space/Langchain-Chatchat] Langchain-Chatchat 支持知识库 上传音频么？直接语音回答问题。 (Issue #2832)





 
🤖
 
***@***.***！很高兴再次看到你在这里。希望你一切都好！
 
根据我对Langchain-Chatchat代码库的理解，当前版本并不支持音频文件的上传和处理。虽然它支持文件上传，但是并没有明确指出支持音频文件。文件上传功能是通过Streamlit库的st.file_uploader函数实现的，接受的文件类型由LOADER_DICT变量决定。然而，LOADER_DICT并未包含音频文件扩展名（如.mp3，.wav等），因此，音频文件无法被上传。
 
如果要支持音频文件的处理，需要对代码库进行以下更改：
  
 
添加音频文件加载器：当前的代码库使用文档加载器加载文本文件。需要添加一个音频文件加载器来加载音频文件。这可能涉及使用librosa或pydub等库将音频文件加载到可以处理的格式。
 
 
 
添加音频处理功能：一旦音频文件被加载，就需要对其进行处理。这可能涉及使用SpeechRecognition或Google Speech-to-Text API等语音识别库将音频转换为文本。然后，处理后的文本可以输入到现有的文本处理管道中。
 
 
 
更新文件上传器以接受音频文件：当前的文件上传器只接受某些文件类型。需要更新它以接受音频文件类型（例如.wav，.mp3）。
 
 
 
更新知识库以存储音频文件信息：知识库当前存储的是文本文件的信息。需要更新它以存储音频文件的信息，例如音频文件的持续时间，音频文件的格式等。
 
  
请注意，这些都是高级更改，实际的实现将取决于项目的具体要求和约束。
 
关于LOADER_DICT变量在Langchain-Chatchat代码库中支持的具体文件类型，可以参考以下信息：
  
UnstructuredHTMLLoader: .html
 
MHTMLLoader: .mhtml
 
UnstructuredMarkdownLoader: .md
 
JSONLoader: .json
 
JSONLinesLoader: .jsonl
 
CSVLoader: .csv
 
RapidOCRPDFLoader: .pdf
 
RapidOCRLoader: .png, .jpg, .jpeg, .bmp
 
UnstructuredEmailLoader: .eml, .msg
 
UnstructuredEPubLoader: .epub
 
UnstructuredExcelLoader: .xlsx, .xls, .xlsd
 
NotebookLoader: .ipynb
 
UnstructuredODTLoader: .odt
 
PythonLoader: .py
 
UnstructuredRSTLoader: .rst
 
UnstructuredRTFLoader: .rtf
 
SRTLoader: .srt
 
TomlLoader: .toml
 
UnstructuredTSVLoader: .tsv
 
UnstructuredWordDocumentLoader: .docx, .doc
 
UnstructuredXMLLoader: .xml
 
UnstructuredPowerPointLoader: .ppt, .pptx
 
EverNoteLoader: .enex
 
UnstructuredFileLoader: .txt
  
以上信息可以在LOADER_DICT变量定义中找到。
 
希望这些信息对您有所帮助。如果您有任何其他问题或需要进一步的澄清，请随时告诉我。
 
Sources
  
webui_pages/knowledge_base/knowledge_base.py
 
server/knowledge_base/utils.py
  
 
This response is meant to be useful and save you time. It is not meant to be a precise solution, but rather a starting point for your own research.
 
Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
 
If you want to continue the conversation, start your reply with @dosu-bot.

**Comment by zRzRzRzRzRzRzR** [comment]
不支持 0.3.x会做
