### ISSUE TITLE
[BUG] 使用zhipu-api运行自定义Agent问答时，返回结果异常

### ISSUE THREAD

**Issue by Aghenim** [chatchat-space/Langchain-Chatchat#2835]
# 中文

**问题描述**
使用zhipu-api运行自定义Agent问答时，返回结果异常。

**复现问题的步骤**
1. 选择对话模式：自定义Agent问答
2. 选择模型：zhipu-api（version无论是glm-4还是glm-3-turbo都异常）
3. 选择Prompt模板：无论是default还是ChatGLM3都异常
4. 其他设置保持默认
5. 输入问题：帮我找几个关于Langchain的youtube视频

**预期的结果**
<img width="732" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/35476773/1be270a4-c6d4-43f2-9d78-f46e27b86208">

**实际结果**

控制台提示：
```
Action: 
{"action": "Final Answer", "action_input": "Thought: The task is to find YouTube videos about Langchain. I should use the tool designed for this purpose, which is 'search_youtube'.\n\n"}
```

页面显示：
<img width="738" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/35476773/d52fa725-25ce-45e0-a41d-ea369de08ece">

**环境信息**
- 操作系统：macOS-14.2.1-arm64-arm-64bit.
- python版本：3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
- 项目版本：v0.2.10
- langchain版本：0.0.354. fastchat版本：0.2.34
- 是否使用 Docker 部署：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：zhipu-api（version无论是glm-4还是glm-3-turbo都异常）

**补充信息**
- 模型选择openai-api时没有此问题
- 项目版本v0.2.9时没有此问题。

# English

**Issue Description**
Abnormal return results when running custom Agent Q&A with zhipu-api.

**Steps to Reproduce**
1. Select dialogue mode: Custom Agent Q&A.
2. Select model: zhipu-api (both glm-4 and glm-3-turbo versions exhibit the issue).
3. Select Prompt template: The issue occurs with both default and ChatGLM3 templates.
4. Other settings are kept as default.
5. Enter question: Help me find some YouTube videos about Langchain.

**Expected Result**
![Expected Result](https://github.com/chatchat-space/Langchain-Chatchat/assets/35476773/1be270a4-c6d4-43f2-9d78-f46e27b86208)

**Actual Result**

Console prompt:
```
Action: 
{"action": "Final Answer", "action_input": "Thought: The task is to find YouTube videos about Langchain. I should use the tool designed for this purpose, which is 'search_youtube'.\n\n"}
```

Page display:
![Actual Result](https://github.com/chatchat-space/Langchain-Chatchat/assets/35476773/d52fa725-25ce-45e0-a41d-ea369de08ece)

**Environment Information**
- Operating System: macOS-14.2.1-arm64-arm-64bit.
- Python Version: 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
- Project Version: v0.2.10
- Langchain Version: 0.0.354. Fastchat Version: 0.2.34
- Deployment via Docker: No
- Model Used (e.g., ChatGLM2-6B / Qwen-7B): zhipu-api (both glm-4 and glm-3-turbo versions exhibit the issue)

**Additional Information**
- There is no such issue when selecting the openai-api model.
- This issue was not present in project version v0.2.9.

**Comment by zRzRzRzRzRzRzR** [comment]
你这个是模型调用失败了，正常应该输出plan的内容
