### ISSUE TITLE
[BUG] 简洁阐述问题 / 使用glm3的agemt时 text中无法发现tool_call

### ISSUE THREAD

**Issue by huzili** [chatchat-space/Langchain-Chatchat#2836]
使用glm3专用的agent ChatGLM3Agent时 text里从来没出现过tool_call
以下是text记录

由于需要查询的是指定人员的个人资产，这里直接使用工具个人资产查询工具，传入该人员的eid进行查询。

Action:
```
{
  "action": "个人资产查询工具",
  "action_input": "xxxxx"
}
```

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/158033212/e93a06f7-a896-4d0c-b8ce-1124f378b6cc)

导致工具不会被调用

**Comment by zRzRzRzRzRzRzR** [comment]
你提示词换成glm3的了吗
这个模型鲁棒性比较差 Agent领域，10次出来一次属于正常现象

**Comment by huzili** [comment]
> 你提示词换成glm3的了吗 这个模型鲁棒性比较差 Agent领域，10次出来一次属于正常现象

是glm3的 试了n次 确实能出来一次，感觉不如0.27时好用 等0.3时 再关注一下
