### ISSUE TITLE
[BUG] 多GPU下，部分模型能加载但是没法返回回答内容

### ISSUE THREAD

**Issue by IvanLuLyf** [chatchat-space/Langchain-Chatchat#2837]
**问题描述 / Problem Description**

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5052848/0571e497-f4a5-488b-aae7-62b706e24c1b)

之前是一块4090，后来再装了三块

**预期的结果 / Expected Result**
应该回答内容

**实际结果 / Actual Result**
第一次问没有结果、第二次问出现报错

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5052848/f69fc922-bcdf-411f-9b64-efd4ebc738a2)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5052848/dc9635d5-6c62-4746-a9fc-89bc626b3cab)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm3-6b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5052848/a76bd331-b93f-4516-888e-ac3a42b22aa8)

**附加信息 / Additional Information**

如果指定多张卡，glm3能分片加载但是不能返回内容、Qwen14B会出现乱码、baichuan2-7b乱码
如果设置CUDA_VISIBLE的，glm3能加载但是不能返回内容、baichuan2-7b能正常使用

**Comment by zRzRzRzRzRzRzR** [comment]
如果你不是vllm 是不能多GPU加载的

**Comment by IvanLuLyf** [comment]
> 如果你不是vllm 是不能多GPU加载的

您好，vllm相关的配置在哪里开启，文档里面好像没提到这块

**Comment by zRzRzRzRzRzRzR** [comment]
wiki有提到，你可以在server config开，不是所有的模型都支持vllm的

**Comment by zRzRzRzRzRzRzR** [comment]
另外，这里多GPU只是为了满足显存不够能读入，速度会更慢的

**Comment by IvanLuLyf** [comment]
> wiki有提到，你可以在server config开，不是所有的模型都支持vllm的

把这块全部开起来对吧
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5052848/f76b3a3e-94ca-4d2a-a9be-5fc1c2434b9f)

**Comment by IvanLuLyf** [comment]
> 不是的，建议看一下wiki吧

其实问题在于，指定了gpu_nums为1的情况下，glm3模型也没法正常的返回结果

**Comment by zRzRzRzRzRzRzR** [comment]
如果是vllm 则glm有问题是正常的，如果不是vllm 你只能单卡加载glm 然后能正常回复

**Comment by MickeyYannng** [comment]
您好，遇到了一样的问题，请问博主解决了嘛

**Comment by IvanLuLyf** [comment]
> 您好，遇到了一样的问题，请问博主解决了嘛

换了一种方式，使用vllm跑模型生成openai兼容的接口，然后在chatchat里面用API方式接入，就可以用多卡了

**Comment by MickeyYannng** [comment]
> > 您好，遇到了一样的问题，请问博主解决了嘛
> 
> 换了一种方式，使用vllm跑模型生成openai兼容的接口，然后在chatchat里面用API方式接入，就可以用多卡了
谢谢！

**Comment by MickeyYannng** [comment]
> > 您好，遇到了一样的问题，请问博主解决了嘛
> 
> 换了一种方式，使用vllm跑模型生成openai兼容的接口，然后在chatchat里面用API方式接入，就可以用多卡了

谢谢！
