### ISSUE TITLE
[BUG] 创建知识库后，添加文件或删除知识库，提示未找到知识库

### ISSUE THREAD

**Issue by chesp** [chatchat-space/Langchain-Chatchat#2838]
**问题描述 / Problem Description**
创建知识库后，知识库文件夹已存在，但添加文件或删除知识库，提示未找到知识库
![1706521633726](https://github.com/chatchat-space/Langchain-Chatchat/assets/8938818/f42b9dad-5244-406f-b8ae-cc64be8277b4)
![1706521713759](https://github.com/chatchat-space/Langchain-Chatchat/assets/8938818/90ff29b8-ed4d-4866-a75b-e698b5202ee7)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-7B-Chat-Int4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-small-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu Server 18.04
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by chesp** [comment]
调了一下代码，是load_kb_from_db这个函数从db中找不到对应的知识库。知识库的初始化和加载没有报错，权限我也设置了，但是还是找不到知识库。

**Comment by chesp** [comment]
我重新初始化了数据库，现在创建知识库报错AttributeError: 'NoneType' object has no attribute 'conjugate'

**Comment by XARKUR** [comment]
琢磨了很久，终于搞清楚是什么原因了，原因是Embedding 模型没有在模型文件夹，然后按脚本的下载又下载不下来就一直报错，生成的知识库有问题，解决办法是先下载好模型导入模型文件夹

**Comment by 2412412** [comment]
> 琢磨了很久，终于搞清楚是什么原因了，原因是Embedding 模型没有在模型文件夹，然后按脚本的下载又下载不下来就一直报错，生成的知识库有问题，解决办法是先下载好模型导入模型文件夹
大佬，能教教我怎么搞的嘛
