### ISSUE TITLE
知识库提问和回答没有在message保存及接收输入的提问的input在哪？

### ISSUE THREAD

**Issue by CWJ-NB** [chatchat-space/Langchain-Chatchat#2839]
在info数据库message表中为什么没有保存知识库的提问和回答信息？怎么将知识库的提问和回答保存到message表中，我看可以调用add_message_to_db方法，但是回答没有保存，知识库的回答怎么保存？
接收知识库输入的input的代码是哪个呢？因为后面想要根据输入调用不同的知识库。哪个大哥解答一下，感谢！

**Comment by zRzRzRzRzRzRzR** [comment]
我们没有保存历史记录到数据库内呀

**Comment by CWJ-NB** [comment]
## 一、对于将知识库的提问和回答保存到message表中，通过以下方法实现：
仿照保存LLM模型对话的代码修改，在`knowledge_base_chat.py`中：
```python
# ......
    async def knowledge_base_chat_iterator(
            query: str,
            top_k: int,
            history: Optional[List[History]],
            model_name: str = model_name,
            prompt_name: str = prompt_name,
    ) -> AsyncIterable[str]:
        nonlocal max_tokens
        callback = AsyncIteratorCallbackHandler()

        # 保存到message db
        callbacks = [callback]
        message_id = add_message_to_db(chat_type="knowledge_chat", query=query, conversation_id=conversation_id)
        conversation_callback = ConversationCallbackHandler(conversation_id=conversation_id, message_id=message_id,
                                    chat_type="knowledge_chat",
                                    query=query)
        callbacks.append(conversation_callback)

        if isinstance(max_tokens, int) and max_tokens <= 0:
            max_tokens = None

        model = get_ChatOpenAI(
            model_name=model_name,
            temperature=temperature,
            max_tokens=max_tokens,
            # callbacks=[callback],
            callbacks=callbacks,
        )
        docs = await run_in_threadpool(search_docs,
                                       query=query,
                                       knowledge_base_name=knowledge_base_name,
                                       top_k=top_k,
                                       score_threshold=score_threshold)
# ......
```
## 二、对于根据不同的输入调用不同的知识库，通过以下方法实现：
1.在`knowledge_base_chat.py`文件中新建`detect_hot_words`方法：代码如下：
```python
# 根据query输入的内容中出现某些热词来调用相应的知识库
def detect_hot_words(query: str):
    hot_words_mapping = {
        "default": "ai-ag",
        "梅花": "ai-flower",
        "xx信息科技": "xx-info",
        # 其他热词和对应知识库的映射关系
    }
    for hot_word, knowledge_base_name in hot_words_mapping.items():
        if hot_word in query:
            return knowledge_base_name
    # 没有找到指定默认知识库
    return hot_words_mapping["default"]
```
2.然后在`knowledge_base_chat`方法中调用：
```python
# ......
async def knowledge_base_chat(query: str = Body(..., description="用户输入", examples=["你好"]),
                              # TODO CWJ
                              conversation_id: str = Body("", description="对话框ID"),
                              knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]),
                              top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"),
                              score_threshold: float = Body(
                                  SCORE_THRESHOLD,
                                  description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右",
                                  ge=0,
                                  le=2
                              ),
                              history: List[History] = Body(
                                  [],
                                  description="历史对话",
                                  examples=[[
                                      {"role": "user",
                                       "content": "我们来玩成语接龙，我先来，生龙活虎"},
                                      {"role": "assistant",
                                       "content": "虎头虎脑"}]]
                              ),
                              stream: bool = Body(False, description="流式输出"),
                              model_name: str = Body(LLM_MODELS[0], description="LLM 模型名称。"),
                              temperature: float = Body(TEMPERATURE, description="LLM 采样温度", ge=0.0, le=1.0),
                              max_tokens: Optional[int] = Body(
                                  None,
                                  description="限制LLM生成Token数量，默认None代表模型最大值"
                              ),
                              prompt_name: str = Body(
                                  "default",
                                  description="使用的prompt模板名称(在configs/prompt_config.py中配置)"
                              ),
                              request: Request = None,
                              ):
    # 根据用户输入的内容中的热词来选择知识库
    knowledge_base_name = detect_hot_words(query)

    kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
    if kb is None:
        return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")
# ......
```

通过api测试，功能是实现了的，有没有其他的问题，小白的我就不知道了。

**Comment by sevenandseven** [comment]
> ## 一、对于将知识库的提问和回答保存到message表中，通过以下方法实现：
> 仿照保存LLM模型对话的代码修改，在`knowledge_base_chat.py`中：
> 
> ```python
> # ......
>     async def knowledge_base_chat_iterator(
>             query: str,
>             top_k: int,
>             history: Optional[List[History]],
>             model_name: str = model_name,
>             prompt_name: str = prompt_name,
>     ) -> AsyncIterable[str]:
>         nonlocal max_tokens
>         callback = AsyncIteratorCallbackHandler()
> 
>         # 保存到message db
>         callbacks = [callback]
>         message_id = add_message_to_db(chat_type="knowledge_chat", query=query, conversation_id=conversation_id)
>         conversation_callback = ConversationCallbackHandler(conversation_id=conversation_id, message_id=message_id,
>                                     chat_type="knowledge_chat",
>                                     query=query)
>         callbacks.append(conversation_callback)
> 
>         if isinstance(max_tokens, int) and max_tokens <= 0:
>             max_tokens = None
> 
>         model = get_ChatOpenAI(
>             model_name=model_name,
>             temperature=temperature,
>             max_tokens=max_tokens,
>             # callbacks=[callback],
>             callbacks=callbacks,
>         )
>         docs = await run_in_threadpool(search_docs,
>                                        query=query,
>                                        knowledge_base_name=knowledge_base_name,
>                                        top_k=top_k,
>                                        score_threshold=score_threshold)
> # ......
> ```
> 
> ## 二、对于根据不同的输入调用不同的知识库，通过以下方法实现：
> 1.在`knowledge_base_chat.py`文件中新建`detect_hot_words`方法：代码如下：
> 
> ```python
> # 根据query输入的内容中出现某些热词来调用相应的知识库
> def detect_hot_words(query: str):
>     hot_words_mapping = {
>         "default": "ai-ag",
>         "梅花": "ai-flower",
>         "xx信息科技": "xx-info",
>         # 其他热词和对应知识库的映射关系
>     }
>     for hot_word, knowledge_base_name in hot_words_mapping.items():
>         if hot_word in query:
>             return knowledge_base_name
>     # 没有找到指定默认知识库
>     return hot_words_mapping["default"]
> ```
> 
> 2.然后在`knowledge_base_chat`方法中调用：
> 
> ```python
> # ......
> async def knowledge_base_chat(query: str = Body(..., description="用户输入", examples=["你好"]),
>                               # TODO CWJ
>                               conversation_id: str = Body("", description="对话框ID"),
>                               knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]),
>                               top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"),
>                               score_threshold: float = Body(
>                                   SCORE_THRESHOLD,
>                                   description="知识库匹配相关度阈值，取值范围在0-1之间，SCORE越小，相关度越高，取到1相当于不筛选，建议设置在0.5左右",
>                                   ge=0,
>                                   le=2
>                               ),
>                               history: List[History] = Body(
>                                   [],
>                                   description="历史对话",
>                                   examples=[[
>                                       {"role": "user",
>                                        "content": "我们来玩成语接龙，我先来，生龙活虎"},
>                                       {"role": "assistant",
>                                        "content": "虎头虎脑"}]]
>                               ),
>                               stream: bool = Body(False, description="流式输出"),
>                               model_name: str = Body(LLM_MODELS[0], description="LLM 模型名称。"),
>                               temperature: float = Body(TEMPERATURE, description="LLM 采样温度", ge=0.0, le=1.0),
>                               max_tokens: Optional[int] = Body(
>                                   None,
>                                   description="限制LLM生成Token数量，默认None代表模型最大值"
>                               ),
>                               prompt_name: str = Body(
>                                   "default",
>                                   description="使用的prompt模板名称(在configs/prompt_config.py中配置)"
>                               ),
>                               request: Request = None,
>                               ):
>     # 根据用户输入的内容中的热词来选择知识库
>     knowledge_base_name = detect_hot_words(query)
> 
>     kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
>     if kb is None:
>         return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")
> # ......
> ```
> 
> 通过api测试，功能是实现了的，有没有其他的问题，小白的我就不知道了。

你好，想问一下，在知识检索模块中，我该怎么将历史的数据放入到memory模块中，然后把历史信息作为上下文信息，后续在进行检索？
