### ISSUE TITLE
初始化知识库不成功

### ISSUE THREAD

**Issue by caoziyang1997** [chatchat-space/Langchain-Chatchat#2840]
Traceback (most recent call last):
  File "/home/czy/project/lc-chat/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/czy/project/lc-chat/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/czy/project/lc-chat/Langchain-Chatchat/server/knowledge_base/migrate.py", line 110, in files2vs
    print(f"正在将 {kb_name}/{filename} 添加到向量库，共包含{len(docs)}条文档")
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 20-21: surrogates not allowed

**Comment by caoziyang1997** [comment]
根据你给的提示 修改之后 还是报了同样的错误

**Comment by zRzRzRzRzRzRzR** [comment]
编码需要改成utf8，这个报错也是这个错误，你估计是中文汉字有在utf8编码之外的

**Comment by caoziyang1997** [comment]
> 编码需要改成utf8，这个报错也是这个错误，你估计是中文汉字有在utf8编码之外的
我就是运行这个python init_database.py --recreate-vs 初始化知识库， 然后报了UnicodeEncodeError: 'utf-8' codec can't encode characters in position 20-21: surrogates not allowed这个错误。  具体怎么改呢，用的chatglm3-6b 和 m3e-base  具体怎么改呢  其他的什么也没改

**Comment by zRzRzRzRzRzRzR** [comment]
这个是文件的问题吧，文件不是utf8编码的

**Comment by caoziyang1997** [comment]
> 这个是文件的问题吧，文件不是utf8编码的

这是初始化知识库报的错，源码都是github上面的，什么也没改，就初始化python init_database.py --recreate-vs ，报错了，我也没传文件什么的

**Comment by zRzRzRzRzRzRzR** [comment]
初始化的文件是samples吗，中间有打开过么，因为有遇到过修改文件编码变了

**Comment by caoziyang1997** [comment]
我没打开过， 初始化过程中，他会自动读取，然后报错了

**Comment by zRzRzRzRzRzRzR** [comment]
估计是设备上有点问题了，今天再次测试了没有遇到，我是linux

**Comment by zRzRzRzRzRzRzR** [comment]
尝试一下报错代码文件的第一行强制使用utf8编码吧，复现不出来
