### ISSUE TITLE
解决milvus向量库文件删除后并没有从向量库中删除问题

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2846]
milvus数据库删除之前是直接用的filepath，但是绝对路径会导致 milvus库的source字段出错导致找不到值，最后导致delete_list为空，造成假删除
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/e0573148-a99b-4469-99f2-88bc66122613)

我的改进如下，验证过了，拿filename即可

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/67676177-f2c8-4ede-b350-a971869ee46d)

**Comment by zRzRzRzRzRzRzR** [comment]
这个问题我在dev改了一半没做完，晚点继续尝试

**Comment by zRzRzRzRzRzRzR** [comment]
加上了，是注释状态，有需要的可自行打开
