### ISSUE TITLE
[BUG] zhipuapi 和pydantic不兼容

### ISSUE THREAD

**Issue by GXKIM** [chatchat-space/Langchain-Chatchat#2847]
**问题描述 / Problem Description**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125621025/9ba2d3d0-fae5-4aa5-9563-8512a5bb62f0)

**Comment by zRzRzRzRzRzRzR** [comment]
是的，所以使用了临时方案采用http请求的方式来做的
