### ISSUE TITLE
关于api.py的一些bug和设计逻辑问题？

### ISSUE THREAD

**Issue by 1148330040** [chatchat-space/Langchain-Chatchat#285]
首先冒昧的问一下，这个api.py，开发者大佬们是在自己电脑上测试后确实没问题吗？
还是我打开的方式有问题啊....

传递的数据格式：
data = {
  "knowledge_base_id": "math_men_QA.txt",
  "question": "王奇锋是谁",
  "history": []
}

url：print(requests.post(url="http://113.xx.xxx.168:12100/chat-docs/chat", headers=headers, data=data).json())

如果不动源代码的话，直接传递数据，它会保这个错误：
![1683596556287](https://user-images.githubusercontent.com/34124260/236972846-0700eb3d-186c-4aba-8df4-bd205160ca65.png)

经过测试和debug我找了上生成faiss.index，因此我在源代码里面加了这行语句：
![1683596457967](https://user-images.githubusercontent.com/34124260/236972652-98774986-0c9b-461e-9655-4461ea1d4ddb.png)

它可以访问了，但是只能访问一次，之后回报这个错误：
访问成功：
![1683596774165](https://user-images.githubusercontent.com/34124260/236973260-4fe805b3-d4a7-42d2-b004-09fd0d6d8e3f.png)
报错提示：
![1683596792429](https://user-images.githubusercontent.com/34124260/236973318-4a146ab0-1476-44d1-abad-c42f2487cfd0.png)

所以我就很纳闷，这到底是我打开的方式有问题，还是代码本身的问题，亦或是我传入的jason数据格式有问题？
其次就算再次访问成功了，他还是会有问题，那就是它会再创建一个文件夹用以创建faiss.index
![1683596891223](https://user-images.githubusercontent.com/34124260/236973491-3deb5458-4156-4625-b494-b40a29df535a.png)

这点我直接在api.py文件里面访问chat（）函数也是这个原因。
最后给个小小提议，用http://113.xxx.xxx.168:12100/docs来展示文档对我来说确实很高大上，但是我觉得不如直接弄一个小小实例或者demo更好一点，比如那个cli_Demo就很好，但是api.py文件，我个人觉得设计的确实太花哨了...
一点小意见，再次感谢大佬们的开源，希望代码能更好更完善

**Comment by cristianohello** [comment]
@1148330040 
你好，你的本地的curl请求是怎么写的？
我这有写的，报错了。
curl -X POST "http://127.0.0.1:7861" \
     -H 'Content-Type: application/json' \
     -d '{"knowledge_base_id": "./vector_store/baoxian_FAISS_20230508_111456","question": "你好","history": []}'

**Comment by 1148330040** [comment]
> @1148330040 你好，你的本地的curl请求是怎么写的？ 我这有写的，报错了。 curl -X POST "http://127.0.0.1:7861" -H 'Content-Type: application/json' -d '{"knowledge_base_id": "./vector_store/baoxian_FAISS_20230508_111456","question": "你好","history": []}'

图片上有呀
![image](https://user-images.githubusercontent.com/34124260/236978119-3fdfc826-829b-48da-a7f4-0660560a3590.png)

**Comment by cristianohello** [comment]
@1148330040 
我的curl报错？哪里出问题了
curl -X POST "http://127.0.0.1:7861/"
-H 'Content-Type: application/json'
-d '{"knowledge_base_id": "./vector_store/baoxian_FAISS_20230508_111456","question": "你好","history": []}'

**Comment by cristianohello** [comment]
@1148330040 

你好，我遇到api部署问题了？能私聊吗？有偿解答！我的邮箱：zyssmiletol@163.com

**Comment by 1148330040** [comment]
你直接问吧，能解决我直接告诉你就是了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月15日(周一) 中午1:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] 关于api.py的一些bug和设计逻辑问题？ (Issue #285)




 
@1148330040
 
***@***.***

**Comment by Xavier-123** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/58240404/fc6a6c5b-7cbf-4ec4-85be-43f418072934)
咋返回这个

**Comment by tomFoxxxx** [comment]
你好，请问可以分享一下您访问api的代码吗，感谢

**Comment by Xavier-123** [comment]
![Uploading image.png…]()
是这个吗

**Comment by Xavier-123** [comment]
![1689582695082](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/58240404/1dfa326d-18f3-4ce3-9462-756d1f058e71)
这个吗

**Comment by tomFoxxxx** [comment]
> ![1689582695082](https://user-images.githubusercontent.com/58240404/253889334-1dfa326d-18f3-4ce3-9462-756d1f058e71.jpg) 这个吗

是的是的 目前我是运行了 api.py 生成了接口 但是不清楚这个接口如何后续使用

**Comment by Xavier-123** [comment]
要么在它的接口上改；要么你自己写个接口调用它的接口，然后加自己的功能
![1689583085992](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/58240404/505a19a1-1107-4c26-8fea-8468246afb11)

**Comment by tomFoxxxx** [comment]
> 要么在它的接口上改；要么你自己写个接口调用它的接口，然后加自己的功能 ![1689583085992](https://user-images.githubusercontent.com/58240404/253890687-505a19a1-1107-4c26-8fea-8468246afb11.jpg)

谢谢 我试一下您发的第一张图片的代码（按照理解应该是用来调用api.py生成的接口吧），再次感谢！

**Comment by tomFoxxxx** [comment]
> @1148330040 我的curl报错？哪里出问题了 curl -X POST "http://127.0.0.1:7861/" -H 'Content-Type: application/json' -d '{"knowledge_base_id": "./vector_store/baoxian_FAISS_20230508_111456","question": "你好","history": []}'

你好 请问现在您的错误解决了嘛 我遇到了类似的错误 可以分享一下您的请求代码吗 感谢
