### ISSUE TITLE
大佬解惑请问用户问题与文档的embedding 的匹配方式是什么

### ISSUE THREAD

**Issue by GetUsernametsy** [chatchat-space/Langchain-Chatchat#2851]
**功能描述 / Feature Description**
我想知道 用户的问题与文档的embedding 的匹配方式是什么，在代码中我看到 在 kb_doc_api.py 中 调用的是docs = kb.search_docs(query, top_k, score_threshold)，请问怎么进行的阈值匹配 使用的是什么计算方式？

**Comment by zRzRzRzRzRzRzR** [comment]
余弦相似度匹配

**Comment by 1hfq** [comment]
在哪看出的余弦相似度匹配

**Comment by xiaohundun** [comment]
> 在哪看出的余弦相似度匹配

看你用的哪个数据库，反正 pgvector 是 L2 distance
