### ISSUE TITLE
[BUG] 初始化知识库python init_database.py --recreate-vs报错：

### ISSUE THREAD

**Issue by caoziyang1997** [chatchat-space/Langchain-Chatchat#2852]
python版本3.11，该项目版本也是最新的
初始化知识库python init_database.py --recreate-vs报错：
文档切分示例：page_content='title\nfile\nurl\ndetail\nid\n0.0\n效果如何优化\n2023-04-04.00\nhttps://github.com/imClumsyPanda/langchain-ChatGLM/issues/14\n如图所示，将该项目的README.md和该项目结合后，回答效果并不理想，请问可以从哪些方面进行优化\n0\n1.0\n怎么让模型严格根据检索的数据进行回答，减少胡说八道的回答呢\n2023-04-04.00\nhttps://github.com/imClumsyPanda/langchain-ChatGLM/issues/15\n举个例子：\n1' metadata={'source': '/home/czy/project/lc-chat1/Langchain-Chatchat/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.xlsx'}
文档切分示例：page_content='ChatGPT是OpenAI开发的一个大型语言模型，可以提供各种主题的信息，\n# 如何向 ChatGPT 提问以获得高质量答案：提示技巧工程完全指南\n## 介绍\n我很高兴欢迎您阅读我的最新书籍《The Art of Asking ChatGPT for High-Quality Answers: A complete Guide to Prompt Engineering Techniques》。本书是一本全面指南，介绍了各种提示技术，用于从ChatGPT中生成高质量的答案。\n我们将探讨如何使用不同的提示工程技术来实现不同的目标。ChatGPT是一款最先进的语言模型，能够生成类似人类的文本。然而，理解如何正确地向ChatGPT提问以获得我们所需的高质量输出非常重要。而这正是本书的目的。' metadata={'source': '/home/czy/project/lc-chat1/Langchain-Chatchat/knowledge_base/samples/content/test_files/test.txt'}
Traceback (most recent call last):
  File "/home/czy/project/lc-chat1/Langchain-Chatchat/init_database.py", line 107, in <module>
    folder2db(kb_names=args.kb_name, mode="recreate_vs", embed_model=args.embed_model)
  File "/home/czy/project/lc-chat1/Langchain-Chatchat/server/knowledge_base/migrate.py", line 128, in folder2db
    files2vs(kb_name, kb_files)
  File "/home/czy/project/lc-chat1/Langchain-Chatchat/server/knowledge_base/migrate.py", line 110, in files2vs
    print(f"正在将 {kb_name}/{filename} 添加到向量库，共包含{len(docs)}条文档")
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 20-21: surrogates not allowed

**Comment by zRzRzRzRzRzRzR** [comment]
utf8问题需要将你的文件转换为utf8格式，这个显然是编码错误

**Comment by caoziyang1997** [comment]
> utf8问题需要将你的文件转换为utf8格式，这个显然是编码错误

安装虚拟环境pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple碰到这样的情况Ignoring python-magic-bin: markers 'sys_platform == "win32"' don't match your environment
可以忽略吗？
