### ISSUE TITLE
[query] 关于加载模型 比如 chatGLM3-6b 的问题

### ISSUE THREAD

**Issue by Bannerli** [chatchat-space/Langchain-Chatchat#2854]
我在翻看源代码的时候，想找到加载模型的地方
model = get_ChatOpenAI(model_name=LLM_MODELS[0], temperature=TEMPERATURE)

配置文件里面LLM_MODELS[0]应该指代的是chatGLM3，但是我看了这个wrapper里面的，是调用的langchain的chatOpenai的那个方法
`def get_ChatOpenAI(
        model_name: str,
        temperature: float,
        max_tokens: int = None,
        streaming: bool = True,
        callbacks: List[Callable] = [],
        verbose: bool = True,
        **kwargs: Any,
) -> ChatOpenAI:
    config = get_model_worker_config(model_name)
    if model_name == "openai-api":
        model_name = config.get("model_name")

    model = ChatOpenAI(
        streaming=streaming,
        verbose=verbose,
        callbacks=callbacks,
        openai_api_key=config.get("api_key", "EMPTY"),
        openai_api_base=config.get("api_base_url", fschat_openai_api_address()),
        model_name=model_name,
        temperature=temperature,
        max_tokens=max_tokens,
        openai_proxy=config.get("openai_proxy"),
        **kwargs
    )
    return model`
    
所以比较疑惑，这里可以完成任意模型比方说chagGLM3系列的加载吗？

**Comment by zRzRzRzRzRzRzR** [comment]
所有的模型都是通过fschat转换为langchain 的ChatOpenAI的方式接入的

**Comment by Bannerli** [comment]
可是里面难道不是调用的 ChatOpenAI 这个 函数吗？他和哪些模型是兼容的呢？

**Comment by Bannerli** [comment]
> 所有的模型都是通过fschat转换为langchain 的ChatOpenAI的方式接入的

您好，可以指点一下这一部分代码在哪里看呢？多谢

**Comment by zRzRzRzRzRzRzR** [comment]
这个部分是fscaht作为底座代码的，你要去fschat的仓库看，在github搜索fastchat
