### ISSUE TITLE
[FEATURE] 能否使用ChatGLM以外的其他模型比如Phi-2？ / Can the ChatGLM be changed to other models such like Phi-2? 

### ISSUE THREAD

**Issue by pangdulu** [chatchat-space/Langchain-Chatchat#2855]
**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

对于配置较低的用户，以及英语为主的用户，使用phi-2之类的小模型或许更为可行。现在项目中所用的ChatGLM可以由用户自行选择使用其他模型么？就像是llam.cpp那样支持众多模型，是否可行？

For users with lower configurations, and English-dominated users, it might be more feasible to use a smaller model like the phi-2. Can the current ChatGLM used in the project be used with another model of the user's choice? Is it feasible to support many models like llam.cpp?

**Comment by zRzRzRzRzRzRzR** [comment]
可以的，我们是基于fschat底座，所以你的模型只要fschat能正常读取就行了
