### ISSUE TITLE
[FEATURE] 对于知识图谱的支持 / 支持将知识图谱作为知识库，利用图查询而非向量相似度进行检索增强

### ISSUE THREAD

**Issue by longmingg** [chatchat-space/Langchain-Chatchat#2863]
是否会支持将知识图谱作为知识库，利用图查询而非向量相似度进行检索增强。
若会支持，预计推出时间。

**Comment by longmingg** [comment]
> dosubot



> 你有用这个langchain-chatchat实现连接Neo4j的知识图谱与向量检索相结合吗

有类似的工作，但不是用的这个框架，llamaindex和langchain都可以

**Comment by Wangzhongxi** [comment]
> > 多苏博特
> 
> > 你有用这个langchain-chatchat实现连接Neo4j的知识图谱与向量检索相结合吗
> 
> 有类似的工作，但不是用的这个框架，llamaindex和langchain都可以

好的，谢谢，想问一下有对应开源项目代码吗，有的话能否推我一份

**Comment by SKRY1412** [comment]
同问
