### ISSUE TITLE
使用glm-4模型调用agent时报错

### ISSUE THREAD

**Issue by zuoxiang95** [chatchat-space/Langchain-Chatchat#2865]
**问题描述 / Problem Description**
目前在测试用glm4当agent的基础模型，但是发现在[生成prompt](https://github.com/chatchat-space/Langchain-Chatchat/blob/845adfbc0bcabacff7c2b78e7e4ef1006f68da11/server/agent/custom_agent/ChatGLM3Agent.py#L158)的时候，默认生成的是SystemMessagePrompt，到LLMChain里去调模型时，只有system message，导致调用glm4的模型失败了

**Comment by zuoxiang95** [comment]
是需要传入_memory_prompts这个变量么？

**Comment by zuoxiang95** [comment]
把prompt拆开成两部分，就可以了好像
`python
human_agent_prompt = (
    'Begin! Reminder to ALWAYS respond with a valid json blob of a single action. Use tools if necessary. '
    'Respond directly if appropriate. Format is Action:```$JSON_BLOB```then Observation:.\n'
    'history: {history}\n\n'
    'Question: {input}\n\n'
    'Thought: {agent_scratchpad}')
human_template = human_agent_prompt.format(
            history="None",
            input="{input}",
            agent_scratchpad="{agent_scratchpad}"
        )
messages = [
            SystemMessagePromptTemplate.from_template(template),
            HumanMessagePromptTemplate.from_template(human_template),
            *_memory_prompts,
        ]
`

**Comment by zuoxiang95** [comment]
貌似agent逻辑有点问题，能得到thought之后要再运行一次才能得到answer，目前我测试好像是直接把thought结果输出了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20696420/dfafc430-4cda-49b3-97c0-c01d2d8ae1b7)

**Comment by zRzRzRzRzRzRzR** [comment]
用了GLM的模板了吗

**Comment by zuoxiang95** [comment]
> 用了GLM的模板了吗

prompt是用的GLM的模版

**Comment by zRzRzRzRzRzRzR** [comment]
现在GLM好像是没有第二次Thought的直接出结果，这个根lc不太一样，可能会出点问题，0.3.x可能考虑优化一下，0.2.x不在做技术升级了

**Comment by zRzRzRzRzRzRzR** [comment]
已经加了，但是模型一般没法调动
