### ISSUE TITLE
我的PDF里有一个表格，切片后原表格结构打乱了，每一行和列都没有分割标记，请问这种情况如何解决，感谢大佬解答

### ISSUE THREAD

**Issue by zhanghaotian123** [chatchat-space/Langchain-Chatchat#2866]
这是我的原pdf的表格内容：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59438626/ce0ee203-110c-47dc-b1b8-2387cda5638f)

这是目前chatchat项目分割后的：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59438626/9c8ca70e-b708-44be-b8a8-b3d893316924)

我想要的切分后的效果：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59438626/e086ceb3-b838-4e88-8cf4-b1fd7661ec06)

**Comment by zRzRzRzRzRzRzR** [comment]
乱了是很正常的，因为是OCR识别，这个暂时没办法
