### ISSUE TITLE
目前的分词器无法满足需求，需要重新自己开发

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2867]
目前大量的数据文件是通过excel表生成的pdf。在excel表中，需要检索的数据是通过固定的格式来进行区分的。比如这样的一个格式：
1.xxx
   ddddd
   dddd
      ddddd
2.xxx
在1.xxx中记录的数据很随意，也可能跟1.xxx无关，但是需要检索出来。需要检索1.xxx的数据就是完整的ddd。
但是根据目前的分词器，250个字进行切分，很大程度上输出的结果是在胡言乱语。出处也只显示一部分。因为如果没有肉眼的格式区分，把所有的数据都塞在一个txt文件中，个人其实也很难进行区分问题的答案是从哪到哪。
问题：
这种分词器要怎么开发呢？什么样的思路？求大佬解惑

**Comment by zRzRzRzRzRzRzR** [comment]
这个你要根据wiki中的自定义粉词方法来进行切割，详见github上我们的wiki
