### ISSUE TITLE
[BUG] 使用阿里云的在线EMBEDDING模型，在创建知识库的时候报错了

### ISSUE THREAD

**Issue by jinhaowen123** [chatchat-space/Langchain-Chatchat#2874]
![微信截图_20240131100050](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/80328209-b463-47ad-9091-49afe9ba1218)

这是我在model_config中的配置
EMBEDDING_MODEL = "text-embedding-v2"

    # 阿里云通义千问 API，文档参考 https://help.aliyun.com/zh/dashscope/developer-reference/api-details
    "qwen-api": {
        "version": "qwen-turbo",  # 可选包括 "qwen-turbo", "qwen-plus"
        "api_key": "key",  # 请在阿里云控制台模型服务灵积API-KEY管理页面创建
        "provider": "QwenWorker",
    },

MODEL_PATH = {
    "embed_model": {
        "m3e-small": "moka-ai/m3e-small",
        "m3e-base": "moka-ai/m3e-base",
        "m3e-large": "moka-ai/m3e-large",
        "bge-small-zh": "BAAI/bge-small-zh",
        "bge-base-zh": "BAAI/bge-base-zh",
        "bge-large-zh": "BAAI/bge-large-zh",
        "text-embedding-v2": "key",
    },

是配置文件的问题吗？

**Comment by zRzRzRzRzRzRzR** [comment]
你没有选embedding model，参考wiki来选择模型

**Comment by jinhaowen123** [comment]
![qqq](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/9919747c-d7af-4bc1-8320-38200b6c340f)
![微信截图_20240131100050](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/e9c5d4fa-69f4-460c-8238-6e030aecf0b9)

大佬，我在EMBEDDING_MODEL这里选择模型了，但是创建知识库的时候还是报错了

**Comment by jinhaowen123** [comment]
> 你没有选embedding model，参考wiki来选择模型

![qqq](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/7b15206f-1f10-447f-be49-0ae3cde85271)
![微信截图_20240131100050](https://github.com/chatchat-space/Langchain-Chatchat/assets/101104566/894ee01e-fbff-41ff-b423-136c023e9551)
大佬，我在EMBEDDING_MODEL这里选择模型了，但是创建知识库的时候还是报错了

**Comment by liunux4odoo** [comment]
> > 你没有选embedding model，参考wiki来选择模型
> 
> ![qqq](https://private-user-images.githubusercontent.com/101104566/301060412-7b15206f-1f10-447f-be49-0ae3cde85271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODIwMjEsIm5iZiI6MTcwNjg4MTcyMSwicGF0aCI6Ii8xMDExMDQ1NjYvMzAxMDYwNDEyLTdiMTUyMDZmLTFmMTAtNDQ3Zi1iZTQ5LTBhZTNjZGU4NTI3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxMzQ4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kM2Y2ZDFmYjJhYjlhYTJhNjRlZWVjZDdhOTZlYWI3N2UzZGI2ZjczOTkyNTEyZjZmMzA5N2ZmOGJmNDk4YjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PO_Ly8Rj9H4aVH0CUbEOuBG3lkcw_RO2z29hP7zgfP8) ![微信截图_20240131100050](https://private-user-images.githubusercontent.com/101104566/301060426-894ee01e-fbff-41ff-b423-136c023e9551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4ODIwMjEsIm5iZiI6MTcwNjg4MTcyMSwicGF0aCI6Ii8xMDExMDQ1NjYvMzAxMDYwNDI2LTg5NGVlMDFlLWZiZmYtNDFmZi1iNDIzLTEzNmMwMjNlOTU1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQxMzQ4NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYWUxMDY3YWFmYzc1NjQ1Nzg5YTFhYTZjMGFmMDk2OGQ0N2MwNTRkNGY2YjU1MmVhZDgxYmExMzE2ODZiZjIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o9K8ui0olwtvQtGx9yogU60MMpm5z6IXASuqL4rfKPQ) 大佬，我在EMBEDDING_MODEL这里选择模型了，但是创建知识库的时候还是报错了

EMBEDDING_MODEL 设为 "qwen-api"
