### ISSUE TITLE
[BUG] 模型未预先加载时，切换其他模型也失败

### ISSUE THREAD

**Issue by nikelius** [chatchat-space/Langchain-Chatchat#2877]
**问题描述 / Problem Description**
1，本地模型未预先加载时（即 model_config.py 中 LLM_MODELS 未配置本地模型）
2，在首页左侧界面中选择LLM模型

**复现问题的步骤 / Steps to Reproduce**
1. 配置：model_config.py 中 LLM_MODELS 设置为[]，或不配置任何本地LLM模型（只有在线模型）。
2. 执行：首页左侧“选择LLM模型”，选择任意未启动的LLM模型，如”Qwen-1_8B-Chat-i4“。
3. 问题出现：新LLM模型未启动。
4. 错误提示——指定的模型'chatglm2-6b-i4'没有运行。当前运行模型：{'zhipu-api': {'host': '0.0.0.0', 'port': 21001, 'device': 'auto', 'infer_turbo': False, 'version': 'glm-4', 'provider': 'ChatGLMWorker', 'online_api': True}}

**预期的结果 / Expected Result**
1. 第一步：如果当前模型未启动（或者名称无效），则忽略，而不是直接返回500错误。
2. 第二步：如果新模型未启动（且名称有效），则启动新LLM模型。

**实际结果 / Actual Result**
1. 第一步：当前模型未启动，直接返回500错误，并在webUI上显示错误提示。
2. 未进入第二步（即未启动新模型）。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本：v0.2.8、v0.2.9、v0.2.10 均存在同样问题。
- 是否使用 Docker 部署（是/否）：否（与本issues无关）
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / Qwen-7B /...（与本issues无关）
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge/bte/m3e/text2vec（与本issues无关）
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：faiss（与本issues无关）
- 操作系统及版本 / Operating system and version:Linux/Ubuntu（与本issues无关）
- Python 版本 / Python version: 3.11.x（与本issues无关）
- 其他相关环境信息 / Other relevant environment information: 无

**附加信息 / Additional Information**

**修复方式（修改 webui_utils.py 和 startup.py）**：

**1，修改代码 webui_utils.py，注释如下代码段（分别在ret_sync()和ret_async()函数内）。**
<pre>
            # if model_name not in running_models:
            #     return {
            #         "code": 500,
            #         "msg": f"指定的模型'{model_name}'没有运行。当前运行模型：{running_models}"
            #     }
            # pass
</pre>

**2，修改代码 startup.py，注释如下代码段。**
<pre>
        # if model_name not in available_models:
        #     msg = f"the model {model_name} is not available"
        #     logger.error(msg)
        #     return {"code": 500, "msg": msg}
        # pass
        # worker_address = app._controller.get_worker_address(model_name)
        # if not worker_address:
        #     msg = f"can not find model_worker address for {model_name}"
        #     logger.error(msg)
        #     return {"code": 500, "msg": msg}
        # pass
        # with get_httpx_client() as client:
        #     r = client.post(worker_address + "/release",
        #                 json={"new_model_name": new_model_name, "keep_origin": keep_origin})
        #     if r.status_code != 200:
        #         msg = f"failed to release model: {model_name}"
        #         logger.error(msg)
        #         return {"code": 500, "msg": msg}
        # pass
</pre>

修改为：
<pre>
        if model_name not in available_models:
            logger.error(f"the model {model_name} is not available")
        else:
            worker_address = app._controller.get_worker_address(model_name)
            if not worker_address:
                logger.error(f"can not find model_worker address for {model_name}")
            else:
                with get_httpx_client() as client:
                    r = client.post(worker_address + "/release", json={"new_model_name": new_model_name, "keep_origin": keep_origin})
                    if r.status_code != 200:
                        msg = f"failed to release model: {model_name}"
                        logger.error(msg)
                        return {"code": 500, "msg": msg}
                    pass
                pass
            pass
        pass
</pre>

**Comment by nikelius** [comment]
@dosu-bot 建议0.2.10中修复，并合并到0.3.x中。

**Comment by zRzRzRzRzRzRzR** [comment]
我们设计的时候就是一定要先加载模型的，保证后续代码能运行，因此在启动的时候就必须要加载模型

**Comment by nikelius** [comment]
@zRzRzRzRzRzRzR 预先配置加载的模型，可以是在线模型。但是切换其他模型时，不认可原模型为在线模型。
