### ISSUE TITLE
知识库问答的对话框传入的文本，一直传到 knowledge_base_chat_iterator这个函数的时候还未经拆分吗？

### ISSUE THREAD

**Issue by zhangwzhang** [chatchat-space/Langchain-Chatchat#2878]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zRzRzRzRzRzRzR** [comment]
知识库是拆分完的放到知识库，匹配的函数不在对话中，在对话中只会调用检索后的结果传入给大模型

**Comment by zhangwzhang** [comment]
> 知识库是拆分完的放到知识库，匹配的函数不在对话中，在对话中只会调用检索后的结果传入给大模型

也就是说完成拆分的只有上传知识库的时候，知识库问答的问题就不会拆分，对吗？
