### ISSUE TITLE
[FEATURE] 建议统一增加py源代码的文件头信息，明确解释器和字符集

### ISSUE THREAD

**Issue by nikelius** [chatchat-space/Langchain-Chatchat#2879]
**功能描述 / Feature Description**
建议对每个py文件统一增加文件头信息（按照linux和py相关规范，明确解释器和字符集）

**解决的问题 / Problem Solved**
1，规范化py代码形式（按照linux规范，明确解释器和字符集）
2，精简执行命令。

**实现建议 / Implementation Suggestions**
1，建议对每个py文件统一增加文件头信息（第1、2行）
<pre>
#! /usr/bin/env python3
# -*- coding: utf-8 -*-
</pre>

2，用增加py文件的可执行权限后，就可直接执行。
- 修改权限：chmod +x startup.py
- 原命令行：python3 ./startup.py -a
- 可缩短为：./startup.py -a

**替代方案 / Alternative Solutions**
- 手工修改 startup.py也可。

**其他信息 / Additional Information**
- 无

**Comment by zRzRzRzRzRzRzR** [comment]
好的
