### ISSUE TITLE
请问一下项目中有用到文档段落切割方法吗？

### ISSUE THREAD

**Issue by Sauloo-huen** [chatchat-space/Langchain-Chatchat#288]
text_load中的文档切割方法用上了吗？在代码中看好像没有用到？

**Comment by Sauloo-huen** [comment]
请问一下这个能实现跨文档回答吗？

**Comment by imClumsyPanda** [comment]
可以 同一知识库可以存储不同文档，提问针对选定的知识库

**Comment by xx-zhang** [comment]
@imClumsyPanda 我看文档都是 ` vector_store.add_documents(docs)` 是可以加载整个路径，可以把所有的知识放在一起回答是吧。

**Comment by imClumsyPanda** [comment]
是的 每个知识库可以添加多个文档 问答会基于单个知识库进行

枫 ***@***.***>于2023年5月9日 周二18:47写道：
