### ISSUE TITLE
构建知识库时，embedding模型怎么选，有什么依据吗

### ISSUE THREAD

**Issue by Gzj369** [chatchat-space/Langchain-Chatchat#2881]
构建知识库时，embedding模型怎么选，有什么依据吗
开始使用的m3e-base，发现效果一般，然后查看网上的embedding排名，改用了检索得分排名更靠前的 gte-large-zh，结果发现问答效果更差

https://huggingface.co/spaces/mteb/leaderboard
如下所示，gte-large-zh 排名第6，m3e-base排名第35
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/29de9bd3-fee0-4eee-bd57-11acc7b4f44c)

【补充信息】上传到知识库的语料都是做成了Q&A对（只有2列）的csv文件

环境信息 / Environment Information
langchain-ChatGLM 版本/commit 号：v0.2.9
是否使用 Docker 部署（是/否）：是
使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-72B-Chat
使用的 Embedding 模型（moka-ai/m3e-base 等）：gte-large-zh
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: Linux/ Ubuntu
Python 版本 / Python version: 3.10

**Comment by zRzRzRzRzRzRzR** [comment]
这个自己觉得顺手就行了我们只是放了一个好用的
