### ISSUE TITLE
ModuleNotFoundError: No module named 'server.minx_chat_openai'

### ISSUE THREAD

**Issue by liujie316316** [chatchat-space/Langchain-Chatchat#2886]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44899079/02f7bf8b-6e05-4b01-a7af-e9b69f78bca8)

python copy_config_example.py这个命令可以正常执行，执行到python init_database.py --recreate-vs这个命令时报错，执行其他命令也是报这个错误。

**Comment by zRzRzRzRzRzRzR** [comment]
确保你的代码是全的，使用默认配置不会到这个文件
