### ISSUE TITLE
[BUG] 配置在线千问/文心一言模型出错 

### ISSUE THREAD

**Issue by Liam-Ji** [chatchat-space/Langchain-Chatchat#2887]
**问题描述 / Problem Description**
使用通义千问在线API接入时，webui对话出现错误
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12816092/62c0ba43-22f3-4aae-9069-bafe14eafa7a)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12816092/c201e290-f87e-404e-93c1-d89021c987d3)

**复现问题的步骤 / Steps to Reproduce**
1. 执行python startup.py -a
2. 选择qwen-api对话
3. 输入框中输入“你好”
4. 问题出现
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12816092/04b5e618-9799-4d13-a793-298ee8e1dff9)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：5afbae56fc1a4af8946489db36b062d61653c27a
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-max
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text-embedding-v1
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: ubuntu22
- Python 版本 / Python version: python3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by hidacow** [comment]
dashscope等Qwen所需的依赖是否安装？我之前也遇到了该问题，这个报错提示确实很迷惑

**Comment by Liam-Ji** [comment]
dashscope装了，同样的python环境我运行官方的python样例是正常的，你还能想起怎么解决的吗？

**Comment by hidacow** [comment]
可能造成该问题的地方还有很多，我是之前就装了dashscope就好了，你可以排查一下依赖相关问题，是否全部安装成功
类似issue还有#2228, #2226

**Comment by Liam-Ji** [comment]
qwen api的错误确实是dashscope没装（环境搞混了），装了之后错误没有了，感谢感谢
