### ISSUE TITLE
报错   raise ValueError(f"Knowledge base {knowledge_base_id} not found") ValueError: Knowledge base ./vector_store not found

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#289]
File "/root/autodl-tmp/chatglm/langchain-ChatGLM-master/api.py", line 183, in chat
    raise ValueError(f"Knowledge base {knowledge_base_id} not found")
ValueError: Knowledge base ./vector_store not found

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码尝试
