### ISSUE TITLE
v0.2.9版本使用reranker功能时，提示RuntimeError: The expanded size of the tensor (829) must match the existing size (514) at non-singleton dimension 1

### ISSUE THREAD

**Issue by Gzj369** [chatchat-space/Langchain-Chatchat#2890]
v0.2.9版本使用reranker功能时，提示RuntimeError: The expanded size of the tensor (829) must match the existing size (514) at non-singleton dimension 1
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/13391430/0b9a94d6-3619-40fb-bf1a-1da1e780d445)

环境信息 / Environment Information
langchain-ChatGLM 版本/commit 号：v0.2.9
是否使用 Docker 部署（是/否）：是
使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-72B-Chat
使用的 Embedding 模型（moka-ai/m3e-base 等）：gte-large-zh
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: Linux/ Ubuntu
Python 版本 / Python version: 3.10
reranker  RERANKER_MAX_LENGTH = 512
块大小参数：250 和 50

原始语料为只有2列的Q&A对，格式为 csv 文件

**Comment by Gzj369** [comment]
@liuxjerry  对，我这边的Answer长度有可能超过1024 token，看报错信息好像跟长度关系不大，可能我理解有误

**Comment by Gzj369** [comment]
@liuxjerry 请问token的长度怎么计算，比如我现在分块、每块的大小为250，然后采用top3的文本块，按道理 250 *3 + prompt的长度 不会超过 1024 token，才对

**Comment by liuxjerry** [comment]
> @liuxjerry 对，我这边的Answer长度有可能超过1024 token，看报错信息好像跟长度关系不大，可能我理解有误

跟长度有关系的，长度短就不会报你这个错

**Comment by Gzj369** [comment]
> > @liuxjerry 对，我这边的Answer长度有可能超过1024 token，看报错信息好像跟长度关系不大，可能我理解有误
> 
> 跟长度有关系的，长度短就不会报你这个错

好的，请问具体该怎么解决呢

**Comment by liuxjerry** [comment]
> > > @liuxjerry 对，我这边的Answer长度有可能超过1024 token，看报错信息好像跟长度关系不大，可能我理解有误
> > 
> > 
> > 跟长度有关系的，长度短就不会报你这个错
> 
> 好的，请问具体该怎么解决呢

这就有点难度了。我目前是把超过长度的内容截断了，这也不是最优方案，期待各位大牛。

**Comment by nicole828** [comment]
> > > > @liuxjerry 对，我这边的Answer长度有可能超过1024 token，看报错信息好像跟长度关系不大，可能我理解有误
> > > 
> > > 
> > > 跟长度有关系的，长度短就不会报你这个错
> > 
> > 
> > 好的，请问具体该怎么解决呢
> 
> 这就有点难度了。 我目前是把超过长度的内容截断了，这也不是最优方案，期待各位大牛。

请问一下，您是怎么截断的？就强行截断么？
