### ISSUE TITLE
reranker模型没有启用是为什么

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2893]
代码里面有配置reranker模型
# 选用的reranker模型
RERANKER_MODEL = "bge-reranker-large"
# 是否启用reranker模型
USE_RERANKER = False

# 加入reranker
        if USE_RERANKER:
            reranker_model_path = MODEL_PATH["reranker"].get(RERANKER_MODEL,"BAAI/bge-reranker-large")
            print("-----------------model path------------------")
            print(reranker_model_path)
            reranker_model = LangchainReranker(top_n=top_k,
                                            device=embedding_device(),
                                            max_length=RERANKER_MAX_LENGTH,
                                            model_name_or_path=reranker_model_path
                                            )
            print(docs)
            docs = reranker_model.compress_documents(documents=docs,
                                                     query=query)
            print("---------after rerank------------------")
            print(docs)
但是为啥设置成了False？用起来有什么问题还是？

**Comment by zRzRzRzRzRzRzR** [comment]
不是所有人显卡都带的起来

**Comment by caopengfeigit** [comment]
reranker模型是不是要和embedding模型保持一致，比如都是用bge模型，如果embedding模型用的m3e-base的话是不是reranker模型就不能用bge

**Comment by qianma819** [comment]
这我就不晓得了哎。你可以自己试试。我测试效果感觉没啥用，就放弃了。要想效果好，我们现在做的就是文档整理格式+分词器设计。效果还可以

**Comment by caopengfeigit** [comment]
我看huggingface上bge是有对应的reranker模型的，但是m3e没有，google搜是没有搜到相关信息，问了下chatgpt，回答说是要对应统一。
文档格式整理具体是指的什么？分词器这个框架有吗？
我刚玩这个框架，还不知道都有什么

**Comment by qianma819** [comment]
分词器就是怎么分段，原先默认的是chineserecuxx什么的，可以处理所有的文档，效果不好。自己开发比较好，看看issues，很多提到的

**Comment by caopengfeigit** [comment]
感谢

**Comment by caopengfeigit** [comment]
我测试pdf的文件向量化，感觉结果并不好。看了一下代码，document loader和 text splitter都是框架自己写的。想问下你的方案，你的loader是用的框架里的自带的吗？在分块这块你具体是怎么处理的？还有你说的格式整理，具体是保持什么样的格式？能不能给说下我学习下，谢谢了

**Comment by qianma819** [comment]
我们的文档特殊处理过。目前只上传了两部分资料，一部分是自己写自己上传，每次都是一段一段的。我这边把文档处理了下。
1.xxxxx
sss
<<<<<<<<<<
2.xxxxx
ssss
<<<<<<<<<<
在每次都加了这个<<<作为分割符。采用的是alitextsplitter，然后修改了下，让它使用<<<作为分隔符。这样上传后检索的时候，每次都会检索出1.xxx对应的那一整段。
还有一部分资料也是固定格式，针对格式开发了分词器。
至于其他没有这样格式的其他文档还在讨论要怎么修改，目前用的还是默认的那个，效果不好的，肯定是要改的

**Comment by caopengfeigit** [comment]
好的，感谢回复
目前来看你们的处理方式是从文档内容格式以及分块的逻辑进行处理。
也可是尝试下使用不同的embedding模型以及大语言模型，看到网上有这样的说法换了大语言模型回答质量有显著提升。
