### ISSUE TITLE
vllm加载peft文件报错

### ISSUE THREAD

**Issue by vilinx6** [chatchat-space/Langchain-Chatchat#2894]
使用vllm加载peft文件后报错，请问再vllm加速的情况下应该如何加载lora后的权重
OSError: /home/ubuntu/workspace/tune-model/peft12 does not appear to have a file named config.json. Checkout 'https://huggingface.co//home/ubuntu/workspace/tune-model/peft12/None' for available files.

**Comment by zRzRzRzRzRzRzR** [comment]
vllm 加载peft本来就有问题吧，peft只能用fschat加载，vllm我记得一直有问题没能解决
