### ISSUE TITLE
wiki中和README中默认使用的模型不一致

### ISSUE THREAD

**Issue by NRISRcd** [chatchat-space/Langchain-Chatchat#2895]
在[wiki](https://github.com/chatchat-space/Langchain-Chatchat/wiki/%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2)中，模型下载小节，默认使用的 LLM 模型 [THUDM/chatglm2-6b](https://huggingface.co/THUDM/chatglm2-6b) 与 Embedding 模型 [moka-ai/m3e-base](https://huggingface.co/moka-ai/m3e-base)；而在[README.md](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/README.md)中，模型下载小节，默认使用的 LLM 模型 [THUDM/ChatGLM3-6B](https://huggingface.co/THUDM/chatglm3-6b) 与 Embedding 模型 [BAAI/bge-large-zh](https://huggingface.co/BAAI/bge-large-zh)。

**Comment by zRzRzRzRzRzRzR** [comment]
修改，readme是对的
