### ISSUE TITLE
在用Agent时候使用工具报错

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2900]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/c0b4135a-b4b0-4a5c-bde8-d9ed8adc0615)

报错信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/29d9c421-703d-4a63-8f1b-a8192aca2cc5)

**Comment by hidacow** [comment]
Agent默认使用bing，且你没有配置bing的apikey或者调用了不支持的搜索引擎导致它返回了BaseResponse，与正常搜索返回的EventSourceResponse类型不匹配导致了问题
<https://github.com/chatchat-space/Langchain-Chatchat/blob/4f67f4a841500c07d41abac3f6e13acd3ccffe7c/server/chat/search_engine_chat.py#L138>
<https://github.com/chatchat-space/Langchain-Chatchat/blob/4f67f4a841500c07d41abac3f6e13acd3ccffe7c/server/chat/search_engine_chat.py#L141>
