### ISSUE TITLE
[BUG] 当前 langchain对于并发的支持不够强健，或者有什么其他方式能加强对并发的支持吗

### ISSUE THREAD

**Issue by wangyh-strat** [chatchat-space/Langchain-Chatchat#2905]
当前对于并发的支持不强健，有什么办法能对并发的支持高一点吗？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型ChatGLM3
- 使用的 Embedding 模型: moka-ai/m3e-base 
- 使用的向量库类型 :  faiss
- Python 版本 / Python version: 3.11.7

**Comment by zRzRzRzRzRzRzR** [comment]
这个框架设计的时候是不考虑并发的
