### ISSUE TITLE
加载Qwen-72B-chat LLM model 出现OOM

### ISSUE THREAD

**Issue by hegang1-tal** [chatchat-space/Langchain-Chatchat#2906]
**问题描述 / Problem Description**
启动app, 加载Qwen-72B-chat LLM model 出现OOM

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python startup.py -a
2. 点击 LLM下拉框加载Qwen72B模型
3 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
加载到单卡上，出现OOM ， A100 80G

**环境信息 / Environment Information**
- langchain-Chatchat 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM3-6B / Qwen-14B  Qwen-72B 等）：ChatGLM3-6B / Qwen14B / Qwen-72B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux
- Python 版本 / Python version: 3.8

**Comment by zRzRzRzRzRzRzR** [comment]
要准备144GB显存，但是fschat只支持单卡，所以你只能vllm 多卡 144G显存
