### ISSUE TITLE
多人使用时，推理速度显著下降

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#2907]
多人使用时大模型推理速度显著下降的问题，有什么解决方法吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这个框架没设置并发啊，streamlit多人直接卡死很正常的

**Comment by rabum** [comment]
> 这个框架没考虑并发啊，streamlit多人直接卡死很正常的

啊，那有什么框架是支持并发的呢
