### ISSUE TITLE
rapidocr_paddle[gpu] is not working.

### ISSUE THREAD

**Issue by 17Reset** [chatchat-space/Langchain-Chatchat#2913]
I want to use GPU in OCR, but after installing the library rapidocr_paddle[gpu], I get an error parsing pdf files, and after uninstalling the library, it's normal, can you fix this bug?

**Comment by zRzRzRzRzRzRzR** [comment]
我在Linux 上使用 GPU 和CPU 都进行了测试， 都是正常的呀，没有遇到这个bug
