### ISSUE TITLE
使用知识库问答，为什么检索出来的前几条知识库都是重复的呢？

### ISSUE THREAD

**Issue by phphappy** [chatchat-space/Langchain-Chatchat#2922]
**问题描述 / Problem Description**
使用知识库问答，为什么检索出来的前几条知识库都是重复的呢？

**复现问题的步骤 / Steps to Reproduce**
使用知识库问答模型，输入知识库能够匹配到的问题
**预期的结果 / Expected Result**
知识库匹配结果不同
**实际结果 / Actual Result**
知识库匹配出来的前3条记录都是重复的

**Comment by phphappy** [comment]
![1707032000639](https://github.com/chatchat-space/Langchain-Chatchat/assets/2278180/cf2c6c24-c90e-4f71-82b3-d0ef10d9fab3)
我的疑问是知识库中检索出来的三条记录是一样的

**Comment by zhengwanbo** [comment]
不知道你使用的是哪个向量库，你需要注意在同一个知识库中，上传相同的文件的时候，之前的是否在向量库中真正删除了。如果没有真正删除，查找出来的就会多条相同的数据。

**Comment by zRzRzRzRzRzRzR** [comment]
同一个文件里面多个相似的文本就算多个答案

**Comment by sevenandseven** [comment]
> ```python
> docs = remove_duplicates(docs)
> ```

你好，请问在哪里设置搜索引擎的类型呢？看着好像直接默认设置为bing是吗？
