### ISSUE TITLE
[BUG] doc docx 文件加载失败是怎么回事

### ISSUE THREAD

**Issue by sssssssssh** [chatchat-space/Langchain-Chatchat#2926]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/54253683/06275bd9-cb1e-4690-bf36-2ebf0bd8c7b0)
我的doc和docx格式的文件有些加载一致失败是怎么回事

**Comment by Qiaoxl** [comment]
遇到类似的问题，上传docx文件报错ModuleNotFoundError, No module named 'docx', No module named 'exceptions'

**Comment by toasun** [comment]
我安装了python-docx，也报这个错，不知道如何解决
