### ISSUE TITLE
v0.2.10 版本添加到向量库的条目显示可能有问题

### ISSUE THREAD

**Issue by MarshalW** [chatchat-space/Langchain-Chatchat#2927]
**问题描述 / Problem Description**

v0.2.10 版本添加到向量库的条目显示可能有问题。

markdown 文件，上传和添加到知识库都没有报错。

可以正常在知识库问答模式下匹配结果。

问题出在显示上：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/931976/73ac378b-0e46-4065-9211-88e78f7ac0c7)

以前版本这里都是✅。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v0.2.10) 
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5 @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu 22.04.3
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**Comment by MarshalW** [comment]
这个 issue 涉及的环境，没有用到 es。

**Comment by zhengwanbo** [comment]
根据我的使用，注释掉：knowledge_base.py 中的202和203 这两行就好了。

**Comment by pakchoily** [comment]
> 根据我的使用，注释掉：knowledge_base.py 中的202和203 这两行就好了。

确实能够解决，请问你有遇到doc无法向量的问题吗?docx向量没问题。由win11运行anaconda。
