### ISSUE TITLE
[BUG] 使用API Server的chat/chat执行报错

### ISSUE THREAD

**Issue by gabrielpondc** [chatchat-space/Langchain-Chatchat#2929]
**问题描述 / Problem Description**
使用API形式进行模型调用，执行chat/chat时候会报错
```
发生异常: AssertionError
exception: no description
  File "/Langchain-Chatchat-master/server/utils.py", line 22, in wrap_done
    await fn
  File "/Langchain-Chatchat-master/startup.py", line 441, in run_api_server
    uvicorn.run(app, host=host, port=port)
  File "<string>", line 1, in <module>
AssertionError: 
```
**复现问题的步骤 / Steps to Reproduce**
```sh
curl -X 'POST' \
  'http://127.0.0.1:7861/chat/chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "query": "恼羞成怒",
  "conversation_id": "1",
  "history_len": 3,
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": true,
  "model_name": "ChatGLM-API",
  "temperature": 0.7,
  "max_tokens": 3000,
  "prompt_name": "default"
}'
```
**预期的结果 / Expected Result**
对内容进行回复
**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
```
发生异常: AssertionError
exception: no description
  File "/Langchain-Chatchat-master/server/utils.py", line 22, in wrap_done
    await fn
  File "/Langchain-Chatchat-master/startup.py", line 441, in run_api_server
    uvicorn.run(app, host=host, port=port)
  File "<string>", line 1, in <module>
AssertionError: 
```
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Centos 7
- Python 版本 / Python version:3.10.13
- 其他相关环境信息 / Other relevant environment information:
使用Chatglm的openai api开启的模型服务
<img width="1002" alt="截屏2024-02-05 10 07 35" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/26787778/79b7a00c-97bd-45a0-b93f-5c5498fb954c">

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by gabrielpondc** [comment]
如果没有history就正常，但是有history就报错

**Comment by gabrielpondc** [comment]
而且在webui里面聊天就是正常，但是使用API直接调用就报错都是带着history对

**Comment by gabrielpondc** [comment]
> 如果没有history就正常，但是有history就报错

如果没有history就正常，但是有history就报错,而且在webui里面聊天就是正常，但是使用API直接调用就报错都是带着history对

**Comment by zRzRzRzRzRzRzR** [comment]
history格式正确吗，history不是openai格式

**Comment by gabrielpondc** [comment]
> history格式正确吗，history不是openai格式

正确的，查看了chatglm_openaiapi那边的log是正常接收到的，在Langchain的chat函数里面调试调swagger api所产生的变量的值和直接在webui聊天所产生的变量的值都是一样的。如果使用Langchain加载模型好像没有这个问题，但是如果使用模型的官方方法开类openai的api就会报这个错

**Comment by zRzRzRzRzRzRzR** [comment]
openai的方法应该替换掉openai的那个部分，改url而不是使用fscaht载入

**Comment by YangFW** [comment]
> openai的方法应该替换掉openai的那个部分，改url而不是使用fscaht载入

现在是单独开了一个chatglm3的api服务，然后langchain里面设置了openai的url用chagtlm3的那个地址，这个时候调用langchain的/chat/chat 接口，当带有history时就报错了，不带history正常
后又在langchain里用fschat载入了一个chatglm3模型，这个时候用langchain载入的模型调用langchain的/chat/chat接口，不管带不带history都正常
