### ISSUE TITLE
[BUG] 调用API接口knowledge_base/upload_docs时候，显示调用成功但是最后文件上传失败

### ISSUE THREAD

**Issue by bolshyfantasy** [chatchat-space/Langchain-Chatchat#2930]
问题描述 / Problem Description
我从容器外调用api接口，上传容器外的文件，调用结果是success，但实际文件并没有上传上去
换成别的文件格式也是一样

Respense Body
{
  "code": 200,
  "msg": "文件上传与向量化完成",
  "data": {
    "failed_files": {
      "huodong.csv": "从文件 quan/huodong.csv 加载文档时出错：libGL.so.1: cannot open shared object file: No such file or directory"
    }
  }
}

环境信息 / Environment Information

langchain-ChatGLM 版本/commit 号：v0.2.10
是否使用 Docker 部署（是/否）：是
使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-api
使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-small-zh
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: Ubuntu22.04

**Comment by maxusheng123** [comment]
> 问题描述 / Problem Description 我从容器外调用api接口，上传容器外的文件，调用结果是success，但实际文件并没有上传上去 换成别的文件格式也是一样
> 
> Respense Body { "code": 200, "msg": "文件上传与向量化完成", "data": { "failed_files": { "huodong.csv": "从文件 quan/huodong.csv 加载文档时出错：libGL.so.1: cannot open shared object file: No such file or directory" } } }
> 
> 环境信息 / Environment Information
> 
> langchain-ChatGLM 版本/commit 号：v0.2.10 是否使用 Docker 部署（是/否）：是 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-api 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-small-zh 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 操作系统及版本 / Operating system and version: Ubuntu22.04

你可以去这个链接pip安装教程中的模块，大概率能解决，一样的情况，容器中显示上传成功，实则没有。
https://blog.csdn.net/qq_50195602/article/details/124188467?ref=https://githubhelp.com
亲测有效。

**Comment by bolshyfantasy** [comment]
已经解决好问题了，因为直接拉的python镜像，所以有个依赖没装，libglib2.0-dev

**Comment by azhe1234** [comment]
> _🤖_
> 
> 嘿，@bolshyfantasy！我们又见面了😄 希望你今天状态不错！
> 
> 您遇到的问题可能是由于您尝试从容器外部上传的文件路径在容器内部无法访问。当您在容器内运行应用程序时，它有自己的文件系统，除非您明确地使它们可用，否则无法访问容器外部的文件。
> 
> 在提供的上下文中，文件路径是相对于应用程序的根路径定义的：
> 
> ```python
> test_files = {
>     "FAQ.MD": str(root_path / "docs" / "FAQ.MD"),
>     "README.MD": str(root_path / "README.MD"),
>     "test.txt": get_file_path("samples", "test.txt"),
> }
> ```
> 
> 如果您尝试上传位于此根路径（因此位于容器外部）之外的文件，应用程序将无法找到它们，从而导致文件上传失败。
> 
> 要解决此问题，您需要确保您尝试上传的文件可以从容器内部访问。这可以通过在容器中挂载一个指向您的文件所在目录的卷来完成。一旦挂载了卷，您应该能够使用指向挂载卷的路径从容器内部访问文件。
> 
> 关于 "knowledge_base/upload_docs" API端点在Langchain-Chatchat代码库中的确切功能，它用于将文档上传到指定的知识库，并可选择将它们向量化。具体功能如下：
> 
> 1. 首先验证知识库的名称。如果名称无效，它将返回一个403错误，消息为 "Don't attack me"。
> 2. 检查指定的知识库是否存在。如果不存在，它将返回一个404错误，消息指出找不到知识库。
> 3. 然后将上传的文件保存到磁盘。如果已存在同名文件并且 'override' 参数设置为False，它将不会覆盖现有文件。如果任何文件无法保存，它将记录文件名和错误消息。
> 4. 如果 'to_vector_store' 参数设置为True，它将向量化保存的文件。它用向量化的文档更新知识库中的文档。如果任何文件无法向量化，它将记录文件名和错误消息。
> 5. 最后，它返回一个状态码为200的响应，并显示文件上传和向量化已完成的消息。它还包括未能保存或向量化的文件列表。
> 
> 相关代码可以在这里找到：[server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> ## Sources
> * [tests/api/test_kb_api_request.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/tests/api/test_kb_api_request.py)
> * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

我想要从本地上传文件到服务器上，但是报错显示chatchat.server.knowledge_base.utils:files2docs_in_thread_file2docs:419 - PackageNotFoundError: 从文件 工作流论文知识库/925 - 副本.docx 加载文档时出错：Package not found at '/home/lxuekun/Langchain-Chatchat/libs/chatchat-server/chatchat/chatchat_data/data/knowledge_base/工作流论文知识库/content/925 - 副本.docx'
但是接口显示调用成功，INFO:     127.0.0.1:50350 - "POST /knowledge_base/update_docs HTTP/1.1" 200 OK
怎么解决？

**Comment by azhe1234** [comment]
> _🤖_
> 
> 嘿，@bolshyfantasy！我们又见面了😄 希望你今天状态不错！
> 
> 您遇到的问题可能是由于您尝试从容器外部上传的文件路径在容器内部无法访问。当您在容器内运行应用程序时，它有自己的文件系统，除非您明确地使它们可用，否则无法访问容器外部的文件。
> 
> 在提供的上下文中，文件路径是相对于应用程序的根路径定义的：
> 
> ```python
> test_files = {
>     "FAQ.MD": str(root_path / "docs" / "FAQ.MD"),
>     "README.MD": str(root_path / "README.MD"),
>     "test.txt": get_file_path("samples", "test.txt"),
> }
> ```
> 
> 如果您尝试上传位于此根路径（因此位于容器外部）之外的文件，应用程序将无法找到它们，从而导致文件上传失败。
> 
> 要解决此问题，您需要确保您尝试上传的文件可以从容器内部访问。这可以通过在容器中挂载一个指向您的文件所在目录的卷来完成。一旦挂载了卷，您应该能够使用指向挂载卷的路径从容器内部访问文件。
> 
> 关于 "knowledge_base/upload_docs" API端点在Langchain-Chatchat代码库中的确切功能，它用于将文档上传到指定的知识库，并可选择将它们向量化。具体功能如下：
> 
> 1. 首先验证知识库的名称。如果名称无效，它将返回一个403错误，消息为 "Don't attack me"。
> 2. 检查指定的知识库是否存在。如果不存在，它将返回一个404错误，消息指出找不到知识库。
> 3. 然后将上传的文件保存到磁盘。如果已存在同名文件并且 'override' 参数设置为False，它将不会覆盖现有文件。如果任何文件无法保存，它将记录文件名和错误消息。
> 4. 如果 'to_vector_store' 参数设置为True，它将向量化保存的文件。它用向量化的文档更新知识库中的文档。如果任何文件无法向量化，它将记录文件名和错误消息。
> 5. 最后，它返回一个状态码为200的响应，并显示文件上传和向量化已完成的消息。它还包括未能保存或向量化的文件列表。
> 
> 相关代码可以在这里找到：[server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> ## Sources
> * [tests/api/test_kb_api_request.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/tests/api/test_kb_api_request.py)
> * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosubot

> _🤖_
> 
> 嘿，@bolshyfantasy！我们又见面了😄 希望你今天状态不错！
> 
> 您遇到的问题可能是由于您尝试从容器外部上传的文件路径在容器内部无法访问。当您在容器内运行应用程序时，它有自己的文件系统，除非您明确地使它们可用，否则无法访问容器外部的文件。
> 
> 在提供的上下文中，文件路径是相对于应用程序的根路径定义的：
> 
> ```python
> test_files = {
>     "FAQ.MD": str(root_path / "docs" / "FAQ.MD"),
>     "README.MD": str(root_path / "README.MD"),
>     "test.txt": get_file_path("samples", "test.txt"),
> }
> ```
> 
> 如果您尝试上传位于此根路径（因此位于容器外部）之外的文件，应用程序将无法找到它们，从而导致文件上传失败。
> 
> 要解决此问题，您需要确保您尝试上传的文件可以从容器内部访问。这可以通过在容器中挂载一个指向您的文件所在目录的卷来完成。一旦挂载了卷，您应该能够使用指向挂载卷的路径从容器内部访问文件。
> 
> 关于 "knowledge_base/upload_docs" API端点在Langchain-Chatchat代码库中的确切功能，它用于将文档上传到指定的知识库，并可选择将它们向量化。具体功能如下：
> 
> 1. 首先验证知识库的名称。如果名称无效，它将返回一个403错误，消息为 "Don't attack me"。
> 2. 检查指定的知识库是否存在。如果不存在，它将返回一个404错误，消息指出找不到知识库。
> 3. 然后将上传的文件保存到磁盘。如果已存在同名文件并且 'override' 参数设置为False，它将不会覆盖现有文件。如果任何文件无法保存，它将记录文件名和错误消息。
> 4. 如果 'to_vector_store' 参数设置为True，它将向量化保存的文件。它用向量化的文档更新知识库中的文档。如果任何文件无法向量化，它将记录文件名和错误消息。
> 5. 最后，它返回一个状态码为200的响应，并显示文件上传和向量化已完成的消息。它还包括未能保存或向量化的文件列表。
> 
> 相关代码可以在这里找到：[server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> ## Sources
> * [tests/api/test_kb_api_request.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/tests/api/test_kb_api_request.py)
> * [server/knowledge_base/kb_doc_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_doc_api.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot 我想要从本地上传文件到服务器上，但是报错显示chatchat.server.knowledge_base.utils:files2docs_in_thread_file2docs:419 - PackageNotFoundError: 从文件 工作流论文知识库/925 - 副本.docx 加载文档时出错：Package not found at '/home/lxuekun/Langchain-Chatchat/libs/chatchat-server/chatchat/chatchat_data/data/knowledge_base/工作流论文知识库/content/925 - 副本.docx'
但是接口显示调用成功，INFO: 127.0.0.1:50350 - "POST /knowledge_base/update_docs HTTP/1.1" 200 OK
怎么解决？
