### ISSUE TITLE
上文文件向量化接口报错：  key error 'pk'

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#2932]
代码如下：

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/b50040c2-3ff0-4c92-a882-e2493fc3d892)
我先通过设置auto_id=True,解决了  invalid list的问题，然后现在又出现这个错误  ，请问怎么解决：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/016237d6-d76e-403e-9101-d803605562ac)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/805cb40f-94a9-479e-82fb-8598cda9e8b9)

这个issues和我问题一样：
https://github.com/langchain-ai/langchain/issues/17006

**Comment by 948024326** [comment]
已经解决

**Comment by ntd-jiaojie** [comment]
> 已经解决

怎么解决的？遇到了同样的问题。

**Comment by yuanzhiwei** [comment]
怎么解决的?

**Comment by shadowinkstar** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/132779283/75605500-d209-4b65-ba30-a103ce700545)
在langchain_community/vectorstores/milvus.py中的586行可以看到报错，有个治标不治本的方法就是按照上面把self.fields中的pk移除
