### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by TongDog** [chatchat-space/Langchain-Chatchat#2933]
**问题描述 / Problem Description**
在知识库管理中，samples库显示“知识库 samples 中暂无文件”（并没有动过samples文件夹里的任何文件），建立新的知识库并上传文件后仍然无文件

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： bge-large-zh
- 操作系统及版本 / Operating system and version: linux

**Comment by TongDog** [comment]
经过我的检查，发现load_kb_from_db中kb = session.query(KnowledgeBaseModel).filter(KnowledgeBaseModel.kb_name.ilike(kb_name)).first()语句返回的kb为none.但我没有找到原因

**Comment by zRzRzRzRzRzRzR** [comment]
你初始化知识库了吗

**Comment by TongDog** [comment]
> 你初始化知识库了吗

嗯。。。好像没有。
