### ISSUE TITLE
好像没有针对正在向量化的文件进行终止的API

### ISSUE THREAD

**Issue by Bo-LiangD** [chatchat-space/Langchain-Chatchat#2936]
现在通过API 进行上传 有时候会进行批量上传，但批量上传有时候会卡住，文件无法全部上传并向量化，向终止某个文件，然后在重新向量化

**Comment by zRzRzRzRzRzRzR** [comment]
文件多建议直接放在本地文件夹直接想量化来做，确实没有对工业化场景（大并发，大文件）做太多适配

**Comment by AMAG-AB** [comment]
@zRzRzRzRzRzRzR 在贵项目代码的基础上，假如我想设计处理大并发和大文件的向量化过程。使用多进程的emb 您觉得行得通吗？我尝试在es_kb_service.py设计了多进程emb，但是无法运行。  或许您可以给我一些方向性的建议  thank u
