### ISSUE TITLE
使用requirements安装，PyTorch安装的是CPU版本

### ISSUE THREAD

**Issue by congrongdeyu** [chatchat-space/Langchain-Chatchat#294]
如题目，使用requirements安装，PyTorch安装的是CPU版本，运行程序的时候，也是使用CPU在工作。
解决办法：卸载torch包，重新安装GPU版本的PyTorch。
我是在虚拟机上使用，系统是Windows 2016，GPU是A10。
不确定是我系统的问题，还是其他问题。

**Comment by imClumsyPanda** [comment]
建议按照pytorch官网按照引导安装指定版本cuda及对应pytorch版本

DingYu ***@***.***>于2023年5月10日 周三12:00写道：
