### ISSUE TITLE
模型配置文件，直接新增模型会不会有问题？

### ISSUE THREAD

**Issue by huaguzi** [chatchat-space/Langchain-Chatchat#2944]
通义千问有第二代模型了。
我直接这样新增配置，是否可以运行呢？
![1-screenshot-20240206-111950](https://github.com/chatchat-space/Langchain-Chatchat/assets/5173833/c8a572ab-384b-4562-b9cf-0a089bdbd389)

**Comment by zRzRzRzRzRzRzR** [comment]
不会，因为恰好兼容，不然会乱码
