### ISSUE TITLE
这个项目跟fastGPT相比，知识库功能哪个好？

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#2947]
不知道有没有用过fastGPT?相比较哪个效果会好点

**Comment by qianma819** [comment]
> 不是一个类型的

能不能简单的说下有什么不同？不是一个类型是什么意思？

**Comment by 546285455** [comment]
我测试了csv格式数据的识别，（fastgpt+m3e+glm3/星火3.1） 大概率可以完成100条以内的数据的加减乘除，200条以上正确率只有50%；（langchain-chatchat+m3e+gpt3.5/gpt4/星火3.1）基本都是错的

**Comment by qianma819** [comment]
> 我测试了csv格式数据的识别，（fastgpt+m3e+glm3/星火3.1） 大概率可以完成100条以内的数据的加减乘除，200条以上正确率只有50%；（langchain-chatchat+m3e+gpt3.5/gpt4/星火3.1）基本都是错的

其他还有测试啥么？效果好的话打算体验下

**Comment by qianma819** [comment]
> > > 我测试了csv格式数据的识别，（fastgpt+m3e+glm3/星火3.1） 大概率可以完成100条以内的数据的加减乘除，200条以上正确率只有50%；（langchain-chatchat+m3e+gpt3.5/gpt4/星火3.1）基本都是错的
> > 
> > 
> > 请问其他还有测试啥么？效果好的话打算体验下
> 
> 文本也测过，整体效果fastgpt会比较好，还可以定制工作流程，可玩性高一些

好的，多谢。我去试试

**Comment by donggoing** [comment]
> 我测试了csv格式数据的识别，（fastgpt+m3e+glm3/星火3.1） 大概率可以完成100条以内的数据的加减乘除，200条以上正确率只有50%；（langchain-chatchat+m3e+gpt3.5/gpt4/星火3.1）基本都是错的

你好，我想请教一下你在用fastgpt+glm3的时候有没有出现第一次对话正常，但是第二次就报错”对话接口报错或返回为空“的情况？
