### ISSUE TITLE
无法创建知识库，文件索引和向量化都失败‘X’，但是可以正常上传，并且测试了多个embedding模型都是这样

### ISSUE THREAD

**Issue by AndersonHuangEDU** [chatchat-space/Langchain-Chatchat#2954]
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/72554297/8d3d4a00-df58-410f-8478-748472bf1343)
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/72554297/7fa182ce-da95-4044-ba38-ff1c88276f87)

**Comment by zhengwanbo** [comment]
根据我的使用，注释掉：knowledge_base.py 中的202和203 这两行就好了。

**Comment by liunux4odoo** [comment]
似乎与 #2927 是相同的问题，可能是字符显示的问题？

**Comment by AndersonHuangEDU** [comment]
> 根据我的使用，注释掉：knowledge_base.py 中的202和203 这两行就好了。

okok，谢谢了，确实解决了
