### ISSUE TITLE
[BUG] requirements.txt 缺少了 httpx-sse 模块依赖 / The requirements.txt is missing the httpx-sse module dependency.

### ISSUE THREAD

**Issue by ni00** [chatchat-space/Langchain-Chatchat#2955]
**问题描述 / Problem Description**
requirements.txt 缺少了 httpx-sse 模块依赖。
The requirements.txt is missing the httpx-sse module dependency.

**复现问题的步骤 / Steps to Reproduce**
1. 安装全部依赖库
2. 运行之后，提示缺少'httpx_sse'模块
```
ubuntu:~/langchain-main$ pip install -r requirements.txt 
ubuntu:~/langchain-main$ python3 startup.py -a
Traceback (most recent call last):
  File "/home/ubuntu/langchain-main/startup.py", line 37, in <module>
    from server.knowledge_base.migrate import create_tables
  File "/home/ubuntu/langchain-main/server/knowledge_base/migrate.py", line 11, in <module>
    from server.knowledge_base.kb_service.base import KBServiceFactory
  File "/home/ubuntu/langchain-main/server/knowledge_base/kb_service/base.py", line 29, in <module>
    from server.embeddings_api import embed_texts, aembed_texts, embed_documents
  File "/home/ubuntu/langchain-main/server/embeddings_api.py", line 3, in <module>
    from server.model_workers.base import ApiEmbeddingsParams
  File "/home/ubuntu/langchain-main/server/model_workers/__init__.py", line 2, in <module>
    from .zhipu import ChatGLMWorker
  File "/home/ubuntu/langchain-main/server/model_workers/zhipu.py", line 5, in <module>
    from httpx_sse import EventSource
ModuleNotFoundError: No module named 'httpx_sse'
```

**预期的结果 / Expected Result**
不应该提示找不到模块/There should not be a prompt saying the module cannot be found.

**实际结果 / Actual Result**
`ModuleNotFoundError: No module named 'httpx_sse'`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: 3.10.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

**Comment by zRzRzRzRzRzRzR** [comment]
已经在今天下午加上，相关文件还没合并

**Comment by LGRY** [comment]
pip install httpx_sse解决
