### ISSUE TITLE
如何CPU部署？

### ISSUE THREAD

**Issue by morego123** [chatchat-space/Langchain-Chatchat#2959]
安装CPU版torch 后  生成向量库，命令可以运行，但是向量库里没有内容
python startup.py -a 命令无法执行，卡在那儿，也没有报错输出

**Comment by zRzRzRzRzRzRzR** [comment]
配置文件指定为cpu了吗

**Comment by liudonglei** [comment]
> 

配置文件指定为cpu了吗

修改哪几个配置文件？是configs/model_config.py里的那2个'auto'改为‘cpu’吗？

**Comment by morego123** [comment]
> 配置文件指定为cpu了吗

配置文件指定为cpu了吗

修改哪几个配置文件？是configs/model_config.py里的那2个'auto'改为‘cpu’吗？
