### ISSUE TITLE
chat-chat cpu启动chatglm3-6b 卡主，但是不用chatchat框架单独启动chatglm3-6b模型都能正常运行

### ISSUE THREAD

**Issue by theFarHorizon** [chatchat-space/Langchain-Chatchat#2961]
![无标题](https://github.com/chatchat-space/Langchain-Chatchat/assets/68138351/bf377713-7143-4655-95ae-99e93c003a55)

**Comment by zRzRzRzRzRzRzR** [comment]
因为chatchat是用fschat启动的glm 3-6b，这个框架会将你的启动放到一个进程，然后如果内存带不动就不跑了，偶尔会有，但是不应该。尝试检查你的server config 和model config是否已经制定为cpu 而不是auto

**Comment by theFarHorizon** [comment]
@zRzRzRzRzRzRzR  都配置过来看了，我cpu i3 10代，内存16g，还是起不来`==============================Langchain-Chatchat Configuration==============================               
操作系统：Windows-10-10.0.19045-SP0.                                                                       
python版本：3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.10                                                                                          
langchain版本：0.0.354. fastchat版本：0.2.35                                                               
                                                                                                           
                                                                                                           
当前使用的分词器：ChineseRecursiveTextSplitter                                                             
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu                                        
{'device': 'cpu',                                                                                          
 'host': '127.0.0.1',                                                                                      
 'infer_turbo': False,                                                                                     
 'model_path': 'E:\\chatchat\\chatglm3-6b',                                                                
 'model_path_exists': True,                                                                                
 'port': 20002}                                                                                            
{'api_key': '',                                                                                            
 'device': 'cpu',                                                                                          
 'host': '127.0.0.1',                                                                                      
 'infer_turbo': False,                                                                                     
 'online_api': True,                                                                                       
 'port': 21001,                                                                                            
 'provider': 'ChatGLMWorker',                                                                              
 'version': 'glm-4',                                                                                       
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}                                       
{'api_base_url': 'https://api.openai.com/v1',                                                              
 'api_key': '',                                                                                            
 'device': 'cpu',                                                                                          
 'host': '127.0.0.1',                                                                                      
 'infer_turbo': False,                                                                                     
 'model_name': 'gpt-4',                                                                                    
 'online_api': True,                                                                                       
 'openai_proxy': '',                                                                                       
 'port': 20002}                                                                                            
当前Embbedings模型： bge-large-zh @ cpu                                                                    
==============================Langchain-Chatchat Configuration==============================               


2024-02-07 11:59:00,380 - startup.py[line:655] - INFO: 正在启动服务：
2024-02-07 11:59:00,380 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 E:\gpt\Langchain-Chatchat\logs
E:\gpt\Langchain-Chatchat\venv\Lib\site-packages\langchain_core\_api\deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-02-07 11:59:06 | INFO | model_worker | Register to controller
2024-02-07 11:59:06 | ERROR | stderr | INFO:     Started server process [228]
2024-02-07 11:59:06 | ERROR | stderr | INFO:     Waiting for application startup.
2024-02-07 11:59:06 | ERROR | stderr | INFO:     Application startup complete.
2024-02-07 11:59:06 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-02-07 11:59:07 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker a5eb03e1 ...
`

**Comment by zRzRzRzRzRzRzR** [comment]
16G带不起来的，因为chatchat还要启动embedding模型额外占用一定的内存

**Comment by murdonson** [comment]
> 16G带不起来的，因为chatchat还要启动embedding模型额外占用一定的内存

16G都带不起来 那个人一般的笔记本电脑估计都带不起来啊 
显存4G 16G内存个人笔记本推荐用什么model 什么embedding呢？

**Comment by zRzRzRzRzRzRzR** [comment]
配置不够推荐使用0.5 B的Qwen小模型 就占用1个G显存
