### ISSUE TITLE
linux利用docker部署，如何使用CPU

### ISSUE THREAD

**Issue by bbzcx** [chatchat-space/Langchain-Chatchat#2962]
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

如何只使用cpu，虚拟机没有GPU

**Comment by bbzcx** [comment]
然后就停止了

**Comment by qianma819** [comment]
没有gpu，请问你运行此项目的意义何在？别折腾了

**Comment by zRzRzRzRzRzRzR** [comment]
docker封装的都是GPU的，CPU要本地安装
