### ISSUE TITLE
[BUG] 使用Mac Apple silicon运行Langchain-Chatchat几轮对话之后内存占用一直增加

### ISSUE THREAD

**Issue by southkorea2013** [chatchat-space/Langchain-Chatchat#2965]
**问题描述 / Problem Description**
使用Mac Apple silicon运行Langchain-Chatchat几轮对话之后内存占用一直增加，最后导致使用swap区，回答速度变慢。

操作系统：macOS-14.3-arm64-arm-64bit.
python版本：3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ]
项目版本：v0.2.9
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ mps
{'device': 'mps',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': '/Applications/work/llm/models/chatglm2-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh @ mps

知识库问答，历史对话轮数设置为0
初始启动startup.py -a之后，内存占用12.38G
<img width="801" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45256048/1398b274-f9f2-414b-89c7-8b375761a8f7">
第一轮KB问答后，内存占用13.62G
<img width="810" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45256048/1b7fed41-cdf2-41dd-97ac-b42da19bf6bc">
第二轮KB问答，内存占用13.86G
<img width="815" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45256048/0ec5ee8b-61c6-4a60-8394-e66f35189895">
第三轮KB问答，答案的内容较多。内存占用飙升到20.19G
<img width="809" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45256048/f019e3d2-f8e6-4f07-b95e-840195cecca0">

请问这是哪里有内存泄露吗？谢谢！

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.9
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version: macOS Sonoma 14.3
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:
torch                         2.3.0.dev20240206
torchaudio                2.2.0.dev20240206
torchvision                0.18.0.dev20240206

**Comment by southkorea2013** [comment]
> 内存增加很正常吧，因为历史会增加内存

谢谢回复。我如果把历史对话轮数设置为0，这部分内存还是会一直增加吗？祝春节快乐！

**Comment by zRzRzRzRzRzRzR** [comment]
理论不会，如果还增加大概率是模型设计的问题了，chatglm3-6b确实有少量反馈是关闭历史还在增加的
