### ISSUE TITLE
上传doc文件出错 

### ISSUE THREAD

**Issue by murdonson** [chatchat-space/Langchain-Chatchat#2966]
![图片1](https://github.com/chatchat-space/Langchain-Chatchat/assets/20641803/b67436ab-0884-428f-98b2-571d3be532f0)

上传doc文件 使用RapidOCRDocLoader 报错 加载q/1.doc  list index out of range

**Comment by zRzRzRzRzRzRzR** [comment]
文章太长了？

**Comment by murdonson** [comment]
> 文章太长了？

我测试了一下 确实跟文章长度有关系 我本来很多页 减少到3页卡到百分之90多  我减少到两页就可以了
但是这是个bug吧 咋才支持两页word文档呢。。。。我word文档有图 有表格

**Comment by murdonson** [comment]
> 有图肯定是会被过滤掉的，因为图也不会被嵌入。
> 
> 我觉得是字数的问题，嵌入式长度支持1024可能是langchain读入分块的时候超过1024 token

那应该怎么避免这个问题 让他读入分块不超过1024token

**Comment by zRzRzRzRzRzRzR** [comment]
我看了一下，好像确实会chunksize 自动分到1024内，在kb_config 有

**Comment by zRzRzRzRzRzRzR** [comment]
但是你这个问题我确实没有遇到过

**Comment by murdonson** [comment]
我自己debug到了 是复杂多级表头表格无法解析 谢谢
