### ISSUE TITLE
读取带图片的pdf文件传给服务报错

### ISSUE THREAD

**Issue by wkw1542673895** [chatchat-space/Langchain-Chatchat#2967]
用java应用读取带图片的pdf文件传给项目，报错
报错内容如下：
加载文档时出错：OpenCV(4.9.0) /io/opencv/modules/imgproc/src/imgwarp.cpp:3547: error: (-215:Assertion failed) src.checkVector(2, CV_32F) == 4 && dst.checkVector(2, CV_32F) == 4 in function 'getPerspectiveTransform'\n"}

**Comment by zRzRzRzRzRzRzR** [comment]
这个很正常，是ocr的bug，分辨率问题，目前没有很好的解决办法，这张图片是没办法被扫描的

**Comment by wkw1542673895** [comment]
我用strealit框架传同样的文件是可以的，但是通过java来传就报错

**Comment by wkw1542673895** [comment]
> 这个很正常，是ocr的bug，分辨率问题，目前没有很好的解决办法，这张图片是没办法被扫描的

我用strealit框架传同样的文件是可以的，但是通过java来传就报错

**Comment by wkw1542673895** [comment]
> 这个很正常，是ocr的bug，分辨率问题，目前没有很好的解决办法，这张图片是没办法被扫描的

我用strealit框架传同样的文件是可以的，但是通过java服务传同样的文件给python服务就报错

**Comment by lailuboy** [comment]
@wkw1542673895 参考这个中描述的修改看是否能解决：https://github.com/chatchat-space/Langchain-Chatchat/issues/2530

**Comment by wkw1542673895** [comment]
> @wkw1542673895 参考这个中描述的修改看是否能解决：#2530

非常感谢，可以用哈
