### ISSUE TITLE
[FEATURE] 什么时候支持qwen-vl-chat？openai api或者chatchat api支持都可以，哪位提示一下在哪里更改代码来支持

### ISSUE THREAD

**Issue by Liam-Ji** [chatchat-space/Langchain-Chatchat#2969]
**功能描述 / Feature Description**
支持qwen-vl-chat

**Comment by zRzRzRzRzRzRzR** [comment]
可是没有多模态知识库啊，加入了多模态模型的意义是

**Comment by Liam-Ji** [comment]
是这样的，我有个场景：识别图像场景的内容作为标签，qwen-vl-chat不能直接给出标签，但是他可以描述图像的内容，可以根据这个内容与知识库匹配得到标签。这个过程第一步用qwen-vl-chat得到描述，第二步用qwen-vl-chat+知识库得到标签。所以想看看LangChain-Chatchat能不能支持qwen-vl-chat

**Comment by Liam-Ji** [comment]
不需要多模态知识库，现有的文字知识库就能用。

**Comment by Liam-Ji** [comment]
这个发送“你是谁”，后台出来的错误信息，只拿到了返回的两个字“我是”
![Uploading image.png…]()

**Comment by Zhiqfu** [comment]
请问您的问题解决了吗？我也遇到同样的问题了

**Comment by Liam-Ji** [comment]
还没有

**Comment by jackeyke** [comment]
同样的问题，有没有解决？

**Comment by seabean1999** [comment]
引入多模态的场景，解决方案的设计思路这里面提到的应该可以满足 [如何借助LLMs构建支持文本、表格、图片的知识库 - 知乎](https://zhuanlan.zhihu.com/p/668950830)
