### ISSUE TITLE
知识库问答 出错 NoneType has no len()

### ISSUE THREAD

**Issue by murdonson** [chatchat-space/Langchain-Chatchat#2970]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
知识库问答的时候，回答不了问题 空白 但是有知识库匹配结果 报错NoneType has no len()
![bug1](https://github.com/chatchat-space/Langchain-Chatchat/assets/20641803/b10314b2-324f-49fd-842c-ac5120d986ca)

![bug2](https://github.com/chatchat-space/Langchain-Chatchat/assets/20641803/7308d698-4f96-4094-a9d1-d0d6f9d34162)

自己建立知识库 然后上传doc文件 然后向量化成功 然后开始问答的的时候 回答不了问题

操作系统：Linux-6.5.0-17-generic-x86_64-with-glibc2.35.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

环境信息
当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen-1_8B-Chat', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/m/project/Langchain-Chatchat/Qwen-1_8B-Chat',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh @ cpu

**Comment by murdonson** [comment]
我自己下载的Qwen-1_8B-Chat 改了model config文件 模型应该是访问到了啊 本地模型

**Comment by zRzRzRzRzRzRzR** [comment]
不知道你这么弄的模型，这个错误应该是模型读取失败，也就是模型有问题，你检查一下模型文件吧

**Comment by murdonson** [comment]
> 不知道你这么弄的模型，这个错误应该是模型读取失败，也就是模型有问题，你检查一下模型文件吧
今天除夕 等过几天我检查检查 祝你春节快乐😁

**Comment by murdonson** [comment]
> 不知道你这么弄的模型，这个错误应该是模型读取失败，也就是模型有问题，你检查一下模型文件吧

我用官方示例测试了下载的模型 没有问题 证明模型文件没有问题  但是放在langchainchatchat这里就是报错。。。。

**Comment by zRzRzRzRzRzRzR** [comment]
是chat模型吗，chatglm3-6B不出现这个错误呀，看报错事generate的地方错

**Comment by murdonson** [comment]
> 是chat模型吗，chatglm3-6B不出现这个错误呀，看报错事generate的地方错

model_path': '/home/m/project/Langchain-Chatchat/Qwen-1_8B-Chat 我用的这个模型

**Comment by murdonson** [comment]
> 是chat模型吗，chatglm3-6B不出现这个错误呀，看报错事generate的地方错

我没用默认模型 就是下载的/home/m/project/Langchain-Chatchat/Qwen-1_8B-Chat 和  /home/m/project/Langchain-Chatchatbge-large-zh  在model config py 里面指定了绝对路径  然后运行python startup.py -a 然后报这个错 是为什么呢 我本地测试下载的Qwen模型 能回答问题

**Comment by murdonson** [comment]
> 是chat模型吗，chatglm3-6B不出现这个错误呀，看报错事generate的地方错

我是不是哪里漏了什么操作 我就下载了小模型 然后改绝对路径 然后启动python startup.py -a

**Comment by zRzRzRzRzRzRzR** [comment]
配置文件改了吗

**Comment by murdonson** [comment]
> 配置文件改了吗

改了model config py这个文件

**Comment by zRzRzRzRzRzRzR** [comment]
server cofing配置一下Qwen，其他地方应该不用改，如果是这样的话我也不太清楚了，因为我改了server config 和 model config就行了

**Comment by KOBEBRYANTand** [comment]
你好，请问怎么解决的

**Comment by Autism-al** [comment]
请问解决了吗
