### ISSUE TITLE
chatchat哪里可以修改模型输出字数限制？model_config那个改了没有用

### ISSUE THREAD

**Issue by kynow2** [chatchat-space/Langchain-Chatchat#2972]
问下，chatchat哪里可以修改模型输出字数限制？model_config那个改了没有用？
我的模型是根据通义千问7b微调后的模型，在chatchat中加载后，会一直输入，几千个字之后才会停。
请问什么原因，哪里可以修改限制？
另外，chatchat是否支持直接加载lora？

**Comment by zRzRzRzRzRzRzR** [comment]
没办法改，因为没有传入到fschat中
