### ISSUE TITLE
lite 版本 还是依赖 torch

### ISSUE THREAD

**Issue by wtry** [chatchat-space/Langchain-Chatchat#2982]
**问题描述 / Problem Description**
lite 版本 还是依赖 torch

**复现问题的步骤 / Steps to Reproduce**
pip install -r requirements_lite.txt 
还是会依赖 lite，Ubuntu 22.04 和 macOS 都有同样的问题

python 3.11.7
pip 24

**Comment by zRzRzRzRzRzRzR** [comment]
能知道是哪个库依赖吗
