### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by youngin13147** [chatchat-space/Langchain-Chatchat#2987]
通过Langchain-Chatchat API Server页面
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/160338225/a8b35d2a-f091-4990-b4b2-8d9dae762691)
执行
chat/chat接口耗时要1分钟以上
是否没有用到gpu?哪里可以配置api是用gpu来执行？

另外通过LangChain-chatchat webui执行秒出
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/160338225/516a0cc0-276b-4f80-82e0-912459912036)

Langchain-Chatchat搭的本地服务

**Comment by zRzRzRzRzRzRzR** [comment]
大概率是没启动GPU，建议查看wiki
