### ISSUE TITLE
 Error(s) in loading state_dict for ChatGLMForConditionalGeneration:

### ISSUE THREAD

**Issue by wa2003** [chatchat-space/Langchain-Chatchat#299]
运行中出现的问题，7860的端口页面显示不出来，求助。
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/11847871/c2c4c53f-1bc8-4ddf-b9b7-d33d93bcf35c)

**Comment by songpb** [comment]
请问这个问题解决了么？

**Comment by wa2003** [comment]
没有
