### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue"Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by JachinLan** [chatchat-space/Langchain-Chatchat#2991]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/154945381/b8608192-3745-48b6-a85e-f844ac4f475e)

**Comment by zRzRzRzRzRzRzR** [comment]
检查环境配置

**Comment by LiuZheng60** [comment]
configs/server_config.py中FSCHAT_MODEL_WORKERS的"chatglm3-6b": {
        "device": LLM_DEVICE,#cuda
    },cuda改为cpu
