### ISSUE TITLE
本地数据集加载700MB要8个小时正常吗

### ISSUE THREAD

**Issue by zhonggegege** [chatchat-space/Langchain-Chatchat#2994]
i5-10400 ,3.95Ghz满载8个小时加载，尝试两次700MBpdf及word需要8个小时，没有报错，只是时间很长，感觉有点不科学，前来请教下有没有同问题的。

**Comment by zRzRzRzRzRzRzR** [comment]
不正常，你是CPU吗，word估计在ocr卡住了

**Comment by zRzRzRzRzRzRzR** [comment]
那肯定慢了，cpu慢的离谱

**Comment by linaiyue** [comment]
怎么用gpu跑
