### ISSUE TITLE
知识库创建完成后（本地knowledge_base目录下已经有了），但上传文件提示找不到知识库

### ISSUE THREAD

**Issue by shengruicai** [chatchat-space/Langchain-Chatchat#2995]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by shengruicai** [comment]
使用的向量库是faiss，Embedding 模型为：bge-large-zh-v1.5，Embedding模型已经在模型文件夹中，但是创建完知识库后，删除知识库提示就是未找到知识库...
定位发现是在
    kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
    if kb is not None:
        return BaseResponse(code=404, msg=f"已存在同名知识库 {knowledge_base_name}")
  这块代码抛出的。  
使用faiss有什么要求吗？是必须要用faiss-gpu吗？

**Comment by kuhot** [comment]
1.确认模型 bge-large-zh
/
1_Pooling下面的文件名是 config.json
2.修改模型配置文件，模型名称设置如果用的是绝对路径，试一下设置模型路径变量MODEL_ROOT_PATH为文件夹绝对路径，模型名称设置相对路径

**Comment by heidongqilin** [comment]
我解决了，调用python init_database.py --recreate-vs就好了。
