### ISSUE TITLE
对话框提问带有英文，比如cardiomy- opathies，系统回答不应该错误翻译成“卡iomy- opathies”[BUG] 

### ISSUE THREAD

**Issue by TyphoonTong** [chatchat-space/Langchain-Chatchat#2996]
将英文版论文导入知识库后，在对话框输入“cardiomy- opathies ，与什么因素有关？”

回答内容如下：

根据已知信息，卡iomy- opathies与年龄有关。

**Comment by zRzRzRzRzRzRzR** [comment]
你换个英文的embeding模型，bge-zh只能做中文
