### ISSUE TITLE
[BUG] 已经创建的知识库，如何导出或拷贝出来，直接放入另一个系统中？

### ISSUE THREAD

**Issue by jingzl** [chatchat-space/Langchain-Chatchat#2997]
**问题描述 / Problem Description**
当前已经在一台内网服务器上部署，已创建了一个本地化的知识库，并上传了不少文档。
现在想将其导出或者拷贝出来，放入另一个服务器上部署的版本中。
这两台电脑上部署的版本代码差异不大，数据应该可以兼容。
请问这个如何操作？

**Comment by zRzRzRzRzRzRzR** [comment]
做不了吧，如果你只是要复制向量数据库可以的，直接去你对应知识库位置的代码下面那个vector_store复制就好了
