### ISSUE TITLE
startup中的vLLM并发设置

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#3001]
请问args.limit_worker_concurrency这个值有什么限制吗？目前在8*4090上部署internlm2-20b-chat，显存空余还是很大的，能把值调多高呢？

**Comment by zRzRzRzRzRzRzR** [comment]
这个项目是顺发的，你在检索的时候是会遇到顺发的代码写法的你并发调多高都没用啊

**Comment by AIdrinkhotWater** [comment]
顺发指的是串行吗
