### ISSUE TITLE
[BUG] 双卡4090推理时有一卡一直没有用上

### ISSUE THREAD

**Issue by zhitianzhidao** [chatchat-space/Langchain-Chatchat#3002]
请教大神，报错信息是这样，不知道是什么情况啊？
http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
C:\Users\PS\.cache\huggingface\modules\transformers_modules\chatglm3-6b\modeling_chatglm.py:226: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)

server_condig.py已经修改了设定了：
FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        "infer_turbo": False,

        # model_worker多卡加载需要配置的参数
        "gpus": "0,1", # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 2, # 使用GPU的数量
        "max_gpu_memory": "24GiB", # 每个GPU占用的最大显存

系统环境是win11，pytorch安的12.1版本，用官网上的pip语句安装的。

**Comment by zhitianzhidao** [comment]
是不是fschat不支持多卡推理，vllm只支持linux导致的？

**Comment by zRzRzRzRzRzRzR** [comment]
fschat只能单卡，对的
