### ISSUE TITLE
ModuleNotFoundError: No module named 'pwd'

### ISSUE THREAD

**Issue by zrmzack** [chatchat-space/Langchain-Chatchat#3003]
ModuleNotFoundError: No module named 'pwd'
有大佬遇到这个问题么

**Comment by zrmzack** [comment]
我使用的是window11，cpu32g内存， 在python init_database.py --recreate-vs 的时候 出现了ModuleNotFoundError: No module named 'pwd'

**Comment by matureshadow** [comment]
关于 ModuleNotFoundError: No module named 'pwd' ，可如下解决（我刚刚用这个方法解决了）
1. 创建 pwd.py 文件，内容如下
from os import * 
from pwd import * 

def get_username():
    return getpwuid(getuid())[0]
2. 将 pwd.py 文件拷贝到 Python安装路径/Lib/ 下
3. 重新运行 python init_database.py --recreate-vs

**Comment by foxchen** [comment]
> 关于 ModuleNotFoundError: No module named 'pwd' ，可如下解决（我刚刚用这个方法解决了）
> 
> 首先，创建 pwd.py 文件，内容如下
> 
> ```python
> from os import * 
> from pwd import * 
> 
> def get_username():
>     return getpwuid(getuid())[0]
> ```
> 
> 然后，将 pwd.py 文件拷贝到 Python安装路径/Lib/ 下
> 
> 最后，重新运行 python init_database.py --recreate-vs

 我刚试了下= =好像还是一样，其他东西都是照着b站教程来弄的，然后我的python是用conda安装的，是把文件复制到miniconda3目录下的pkgs里面那个python文件夹里面的lib么。。

**Comment by foxchen** [comment]
> 你是否使用了langchain==0.1.7,langchain-community==0.0.20，这个版本有这个问题，尝试更新langchain到0.1.8或者降级langchain应该可以解决

我用的最新的教程安装的。。貌似也会有pwd这个问题

**Comment by hidacow** [comment]
请尝试确认你的langchain版本，务必更新（重新安装）到刚发布的0.1.8新版本或降级到0.1.6以前。
```
pip install -U langchain>=0.1.8
```
langchain相关的issue：https://github.com/langchain-ai/langchain/issues/17514

**Comment by cq1982** [comment]
> > 关于 ModuleNotFoundError: No module named 'pwd' ，可如下解决（我刚刚用这个方法解决了）
> > 首先，创建 pwd.py 文件，内容如下
> > ```python
> > from os import * 
> > from pwd import * 
> > 
> > def get_username():
> >     return getpwuid(getuid())[0]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 然后，将 pwd.py 文件拷贝到 Python安装路径/Lib/ 下
> > 最后，重新运行 python init_database.py --recreate-vs
> 
> 我刚试了下= =好像还是一样，其他东西都是照着b站教程来弄的，然后我的python是用conda安装的，是把文件复制到miniconda3目录下的pkgs里面那个python文件夹里面的lib么。。

我 也试了一下，这个方法确实可以。
创建pwd.py，放到C:\ProgramData\Miniconda3\envs\l2\Lib目录中，然后运行初始化数据库的命令就成功了。

**Comment by Nancy-wangxixi** [comment]
> > > > 关于 ModuleNotFoundError: No module named 'pwd' ，可如下解决（我刚刚用这个方法解决了）
> > > > 首先，创建 pwd.py 文件，内容如下
> > > > ```python
> > > > from os import * 
> > > > from pwd import * 
> > > > 
> > > > def get_username():
> > > >     return getpwuid(getuid())[0]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 然后，将 pwd.py 文件拷贝到 Python安装路径/Lib/ 下
> > > > 最后，重新运行 python init_database.py --recreate-vs
> > > 
> > > 
> > > 我刚试了下= =好像还是一样，其他东西都是照着b站教程来弄的，然后我的python是用conda安装的，是把文件复制到miniconda3目录下的pkgs里面那个python文件夹里面的lib么。。
> > 
> > 
> > 我 也试了一下，这个方法确实可以。 创建pwd.py，放到C:\ProgramData\Miniconda3\envs\l2\Lib目录中，然后运行初始化数据库的命令就成功了。
> 
> 卧槽，谢谢，我这步好像也可以了，之前我给丢到conda的pkgs文件里面的py去了，原来是丢错目录

我好像放错位置了，还是不好用。我是pycharm在工程下创建的虚拟环境，放到了E:\Langchain-Chatchat\venv\Lib里，还是不行

**Comment by kiritoaurora** [comment]
可以看看langchain-community是不是0.0.20，回退到0.0.19可以解决

**Comment by liunux4odoo** [comment]
请按照 requirements.txt 版本安装依赖。

**Comment by Morningstarsvp** [comment]
> 可以看看langchain-community是不是0.0.20，回退到0.0.19可以解决

非常有效的解决方案！

**Comment by player162136** [comment]
> 可以看看langchain-community是不是0.0.20，回退到0.0.19可以解决

很好的解决了问题，谢谢

**Comment by star305604118** [comment]
> > > > 关于 ModuleNotFoundError： No module named 'pwd' ，可如下解决（我刚刚用这个方法解决了） 首先，创建 pwd.py 文件，内容如下
> > > > ```python
> > > > from os import * 
> > > > from pwd import * 
> > > > 
> > > > def get_username():
> > > >     return getpwuid(getuid())[0]
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 然后，将 pwd.py 文件拷贝到 Python安装路径/Lib/ 下
> > > > 最后，重新运行 python init_database.py --recreate-vs
> > > 
> > > 
> > > 我刚试了下= =好像还是一样，其他东西都是照着b站教程来弄的，然后我的python是用conda安装的，是把文件复制到miniconda3目录下的pkgs里面那个python文件夹里面的lib么。。
> > 
> > 
> > 我 也试了一下，这个方法确实可以。创建 pwd.py，放到C：\ProgramData\Miniconda3\envs\l2\Lib目录中，然后运行初始化数据库的命令就成功了。
> 
> 卧槽，谢谢，我这步好像也可以了，之前我给丢到conda的pkgs文件里面的py去了，原来是丢错目录

如果是venv的环境可以放在{venv环境目录}\Lib\site-packages

**Comment by swqqhduwq** [comment]
> > > > > 关于 ModuleNotFoundError: No module named 'pwd' ，可如下解决（我刚刚用这个方法解决了）
> > > > > 首先，创建 pwd.py 文件，内容如下
> > > > > ```python
> > > > > from os import * 
> > > > > from pwd import * 
> > > > > 
> > > > > def get_username():
> > > > >     return getpwuid(getuid())[0]
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 然后，将 pwd.py 文件拷贝到 Python安装路径/Lib/ 下
> > > > > 最后，重新运行 python init_database.py --recreate-vs
> > > > 
> > > > 
> > > > 我刚试了下= =好像还是一样，其他东西都是照着b站教程来弄的，然后我的python是用conda安装的，是把文件复制到miniconda3目录下的pkgs里面那个python文件夹里面的lib么。。
> > > 
> > > 
> > > 我 也试了一下，这个方法确实可以。 创建pwd.py，放到C:\ProgramData\Miniconda3\envs\l2\Lib目录中，然后运行初始化数据库的命令就成功了。
> > 
> > 
> > 卧槽，谢谢，我这步好像也可以了，之前我给丢到conda的pkgs文件里面的py去了，原来是丢错目录
> 
> 我好像放错位置了，还是不好用。我是pycharm在工程下创建的虚拟环境，放到了E:\Langchain-Chatchat\venv\Lib里，还是不行
我也是这个问题，请问你解决了吗

**Comment by benaldzhou** [comment]
> > > > > 关于 ModuleNotFoundError: No module named 'pwd' ，可以如下解决（我刚刚用这个方法解决了）
> > > > > 首先，创建 pwd.py 文件，内容如下
> > > > > ```python
> > > > > from os import * 
> > > > > from pwd import * 
> > > > > 
> > > > > def get_username():
> > > > >     return getpwuid(getuid())[0]
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 然后，将 pwd.py 文件拷贝到 Python 安装路径/Lib/ 下
> > > > > 最后，重新运行 python init_database.py --recreate-vs
> > > > 
> > > > 
> > > > 我刚试了下=想要还是一样，其他东西都是照着b站教程来弄的，然后我的python是用conda安装的，就是把文件复制到miniconda3目录下的pkgs里面那个python文件夹里面的lib么。。
> > > 
> > > 
> > > 我也试了一下，这个方法确实可以。创建pwd.py，放到C:\ProgramData\Miniconda3\envs\l2\Lib目录中，然后运行成功初始化数据库的命令就了。
> > 
> > 
> > 卧槽，谢谢，我这个步想要也可以了，之前我给丢到conda的pkgs文件里面的py去了，原来是丢错目录
> 
> 我想放错位置了，还是不好用。我是pycharm在工程下创建的虚拟环境，放到了E:\Langchain-Chachat\venv\Lib里，还是不行
得放在Python的Lib文件里面

**Comment by ovjust** [comment]
Name: langchain-community
Version: 0.0.19

python init_database.py --recreate-vs

2024-07-08 16:40:41,959 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020B7A755250>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: 969f33a8-cced-4ab8-a785-66e8d1207caf)')
AttributeError: 'NoneType' object has no attribute 'conjugate'
