### ISSUE TITLE
[BUG] 执行python init_database.py --recreate-vs时报错：MouduleNotFounndError:No module named 'pwd'

### ISSUE THREAD

**Issue by Dorry-wangxixi** [chatchat-space/Langchain-Chatchat#3004]
**问题描述 / Problem Description**
执行python init_database.py --recreate-vs时报错：MouduleNotFounndError:No module named 'pwd'

**复现问题的步骤 / Steps to Reproduce**
1. 下载依赖
pip install -r requirements.txt 
pip install -r requirements_api.txt
pip install -r requirements_webui.txt
2. 下载embedding模型和chaglm3模型放入model文件夹
3. 运行 python copy_config_example.py
4. 执行 python init_database.py --recreate-vs
5. 问题出现 / MouduleNotFounndError:No module named 'pwd'

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：langchain 0.2.10，chatglm3
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 操作系统及版本 / Operating system and version:  windows10
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by OuIChien** [comment]
pip install langchain-community==0.0.19
先降级到这个版本，0.0.20的issue他们将会修复后再发布。
参考 https://github.com/langchain-ai/langchain/discussions/17513

**Comment by zRzRzRzRzRzRzR** [comment]
lc的问题应该
