### ISSUE TITLE
[BUG] 访问超时

### ISSUE THREAD

**Issue by King98k** [chatchat-space/Langchain-Chatchat#3006]
upstream connect error or disconnect/reset before headers. retried and the latest reset reason: connection failure, transport failure reason: delayed connect error: 111
浏览器 长时间不操作的时候会出现上述问题，导致无法访问

**Comment by Ameliayaya** [comment]
与楼主同样的问题，下面是截图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46893181/0e61b80c-8ab9-4945-be6b-d6cfb0a52a80)
后来尝试使用nohup python startup.py > startup.log 2>&1 &，返回了[1] 31872，但是http端口并不能正常打开。还是需要执行python startup.py -a。
