### ISSUE TITLE
怎么接入Chroma数据库

### ISSUE THREAD

**Issue by HO-UN** [chatchat-space/Langchain-Chatchat#3007]

**Comment by zRzRzRzRzRzRzR** [comment]
配置文件改一下就行了 kb config

**Comment by HO-UN** [comment]
kb config是没有chroma的

**Comment by HO-UN** [comment]
启动了chromadb后，我发现不管怎么提问都是匹配相同的片段，
![1708498132565](https://github.com/chatchat-space/Langchain-Chatchat/assets/85060766/c8df9d9b-46ff-4d18-b744-c41dd5a41eb1)
在cmd一看score有320分这么高

**Comment by HO-UN** [comment]
chroma都是匹配同一个片段
