### ISSUE TITLE
lite模式启动，新建知识库报错

### ISSUE THREAD

**Issue by theFarHorizon** [chatchat-space/Langchain-Chatchat#3012]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/68138351/e97c5e30-ee6b-4278-a325-69e808abd81e)

2024-02-20 15:46:17.709 Uncaught app exception
Traceback (most recent call last):
  File "E:\gpt\Langchain-Chatchat\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "E:\gpt\Langchain-Chatchat\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "E:\gpt\Langchain-Chatchat\webui_pages\knowledge_base\knowledge_base.py", line 117, in knowledge_base_page
    index=embed_models.index(EMBEDDING_MODEL),
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'bge-large-zh' is not in list

**Comment by theFarHorizon** [comment]
@zRzRzRzRzRzRzR  请问下，knowledge_base_chat.py 文件。和知识库对话时，如果在数据库里面匹配不到相关数据，则不调用大模型回答了，直接返回，改怎么写呢
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/68138351/a56b6669-05ed-4447-a1ea-8dc5656130d2)

**Comment by jet2you** [comment]
> ![image](https://private-user-images.githubusercontent.com/68138351/306175933-e97c5e30-ee6b-4278-a325-69e808abd81e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODE3OTYsIm5iZiI6MTcwOTc4MTQ5NiwicGF0aCI6Ii82ODEzODM1MS8zMDYxNzU5MzMtZTk3YzVlMzAtZWU2Yi00Mjc4LWEzMjUtNjllODA4YWJkODFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDAzMTgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTIxY2IxMzUzZmJjYjA2NWIyZGI0M2Q3NTJhZmZiZmMxOWQzOTBlNWExYjIyNDU3YWFjOGY4YjU1NjE3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iKZR61M6H0AedjJAmdYPzWULBW_ZiRd0dDy5ZdEtGWc)
> 
> 2024-02-20 15:46:17.709 Uncaught app exception Traceback (most recent call last): File "E:\gpt\Langchain-Chatchat\venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script exec(code, module.**dict**) File "E:\gpt\Langchain-Chatchat\webui.py", line 64, in pages[selected_page]["func"](api=api, is_lite=is_lite) File "E:\gpt\Langchain-Chatchat\webui_pages\knowledge_base\knowledge_base.py", line 117, in knowledge_base_page index=embed_models.index(EMBEDDING_MODEL), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ValueError: 'bge-large-zh' is not in list

你好，问题解决了吗，我也遇到同样的问题'bge-large-zh-v1.5' is not in list

**Comment by theFarHorizon** [comment]
@jet2you  用在线的EMBEDDING_MODEL
