### ISSUE TITLE
[FEATURE] 上传知识库文件的编码问题

### ISSUE THREAD

**Issue by ryancurry-mz** [chatchat-space/Langchain-Chatchat#3014]
**文件格式似乎只支持utf8**
各位大佬，我目前遇到一个场景，我上传csv文件到知识库中，由于csv文件是用office或wps等工具进行编辑保存的，保存后默认文件格式为GB2312。但是上传至知识库时会报错，排查后发现是文件编码问题，请问除了手动更改格式，还有其他好的方案吗？

**尝试**：
1、在上传文件的过程中，将字符编码从gb2312更改为utf8，乱码。
2、能不能支持多种文件编码上传？

**Comment by zRzRzRzRzRzRzR** [comment]
自己写个脚本转为UTF8吧，这个项目是UTF8编码
