### ISSUE TITLE
0.2.10版本，初始化知识库时报错“pwd”找不到，请帮忙解决！

### ISSUE THREAD

**Issue by codeyearn** [chatchat-space/Langchain-Chatchat#3016]
初始化知识库
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44339043/dedffd08-26f1-412e-9af1-ed59171b4104)
本地环境：win 10、conda环境安装py 3.11，执行了pip install -r requirements.txt没有报错

**Comment by codeyearn** [comment]
本地运行0.2.10版本，用conda专门新建的环境，不会有其他项目的依赖影响，py版本是3.11，所有的依赖都是按照requirements.txt规定安装的。

**Comment by shengyujia9** [comment]
两个方法，一个是更换site-packages中langchain_community的版本到0.0.13，我自己就是这样。另外一个是把site-packages中p\langchain_community\document_loaders\pebblo.py的import pwd注释掉，这个我没试过，听别人说的

**Comment by T-equation** [comment]
> 两个方法，一个是更换site-packages中langchain_community的版本到0.0.13，我自己就是这样。另外一个是把site-packages中p\langchain_community\document_loaders\pebblo.py的import pwd注释掉，这个我没试过，听别人说的

第二个目前能跑起来 但BUG不确定

**Comment by roaringmyshallowwater** [comment]
> > 两个方法，一个是更换site-packages中langchain_community的版本到0.0.13，我自己就是这样。另外一个是把site-packages中p\langchain_community\document_loaders\pebblo.py的import pwd注释掉，这个我没试过，听别人说的
> 
> 第二个目前能跑起来 但BUG不确定

我也是

**Comment by Nancy-wangxixi** [comment]
我也是，是不是winndows系统不能用pwd模块？

**Comment by liyue1997** [comment]
hi, 请教一下怎么更换site-packages中langchain_community的版本到0.0.13
@roaringmyshallowwater @T-equation

**Comment by Moyuyanli** [comment]
我解决了，参考这个里面的解决放 #3003
