### ISSUE TITLE
文件对话doc文件上传失败

### ISSUE THREAD

**Issue by gj6956** [chatchat-space/Langchain-Chatchat#3018]
1.选择"文件对话"
![微信截图_20240221104215](https://github.com/chatchat-space/Langchain-Chatchat/assets/19953246/8323d809-9596-4209-a58d-176cd055f2e6)

2.选择需要上传的文件
![微信截图_20240221104231](https://github.com/chatchat-space/Langchain-Chatchat/assets/19953246/52e5e30a-291e-4415-8df5-f7a1dffc1db2)

3.点击"开始上传"

4.后台显示文件向量化成功
![微信截图_20240221104416](https://github.com/chatchat-space/Langchain-Chatchat/assets/19953246/16fba4a3-1ab3-4c8f-b53d-d392f1b2a22d)

5.临时文件夹中没有对应的doc文件
![微信截图_20240221104428](https://github.com/chatchat-space/Langchain-Chatchat/assets/19953246/20679e6f-3380-41e4-aa1d-37618aa10c3c)

**Comment by iuhiyuh** [comment]
@dosubot
现在msg的消息有返回给前段ui吗？
