### ISSUE TITLE
怎么使用kb_summary的功能

### ISSUE THREAD

**Issue by HO-UN** [chatchat-space/Langchain-Chatchat#3019]
我在源码中看到了总结知识库摘要的功能，但是在实际的程序并未运行，请问想使用这个kb_summary的功能的话该怎么设置

**Comment by HO-UN** [comment]
怎么样修改使其在知识库配置的streamlit页面中显示处理好的摘要

**Comment by zRzRzRzRzRzRzR** [comment]
这个摘要功能没做完，需要自己探索一下
