### ISSUE TITLE
使用线上模式不部署开源大模型的方式无法命中知识库

### ISSUE THREAD

**Issue by 1097886344** [chatchat-space/Langchain-Chatchat#3021]
知识库文件上传以及向量化正常
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46391293/22fd92f9-fd86-46c3-845c-eb655161232b)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46391293/d6aad885-8169-4fc7-a1b6-b86dd70b12be)
但是通过知识库问答无法命中上传的文档
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46391293/30e8a777-8f08-462e-bdca-ae3c8acf04a3)
请问可能是什么原因呢
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/46391293/064e5a7c-ce0b-426c-b509-3ff2b01e2786)

**Comment by Rheron1848** [comment]
遇到了同样的问题 表现类似

**Comment by zRzRzRzRzRzRzR** [comment]
你这个搜索出来的东西有问题吧，怎么那么多特殊符号，检查一下是否根你问题有没有关系
