### ISSUE TITLE
[FEATURE] 在autoDL上按照镜像执行后，只有ui界面，没有fastapi的页面

### ISSUE THREAD

**Issue by aa386400024** [chatchat-space/Langchain-Chatchat#3023]
**实现建议 / Implementation Suggestions**
在autoDL上按照镜像执行后，只有对话的ui界面，没有fastapi的页面，如果可能，请加上一个这个页面，谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
autodl是0.2.10的初版镜像，有这个bug，现在主仓库已经修复

**Comment by aa386400024** [comment]
那autodl上面的镜像是否也已经是最新版本了呢
