### ISSUE TITLE
[BUG]chroma向量数据库匹配结果不正确

### ISSUE THREAD

**Issue by HO-UN** [chatchat-space/Langchain-Chatchat#3025]
**问题描述 / Problem Description**
在使用chroma作为向量数据库时，不管提问的问题是什么总是返回3个相同的匹配文段，并且返回的匹配文段与问题毫不相关。

**复现问题的步骤 / Steps to Reproduce**
使用chroma进行文段向量存储，进行提问

**预期的结果 / Expected Result**
应该匹配到正确的文段并正确回答

**实际结果 / Actual Result**
一直返回错误却重复的3个文段
![Uploading 1708498132565.jpg…]()

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：chroma
- 操作系统及版本 / Operating system and version:win10
- Python 版本 / Python version:3.10

**Comment by HO-UN** [comment]
![1708498132565](https://github.com/chatchat-space/Langchain-Chatchat/assets/85060766/1c8f34fb-31fa-4180-b2f8-d85843088281)

**Comment by zRzRzRzRzRzRzR** [comment]
估计是数据准备的有问题，匹配困难

**Comment by tongtie** [comment]
这个应该是没做归一化的问题，我有空看看

**Comment by Shame-fight** [comment]
请问这个问题解决了吗

**Comment by showmecodett** [comment]
> 请问这个问题解决了吗

试试：https://github.com/chatchat-space/Langchain-Chatchat/pull/3640

**Comment by showmecodett** [comment]
@HO-UN 试试： https://github.com/chatchat-space/Langchain-Chatchat/issues/3025#issue-2146049267
