### ISSUE TITLE
版本0.2.10添加知识库成功，但界面显示‘x'

### ISSUE THREAD

**Issue by AIBlocker** [chatchat-space/Langchain-Chatchat#3032]
v0.2.10版本给知识库添加文档时候，界面添加成功，后台日志没有报错，但是界面显示’x‘
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/154792175/5a6497a6-eb3c-45a8-a5b9-2c2302034fa7)

**Comment by cheney369** [comment]
注释掉webui_pages/knowledge_base/knowledge_base.py中的
`            # doc_details["in_folder"] = doc_details["in_folder"].replace(True, "✓").replace(False, "×")
            # doc_details["in_db"] = doc_details["in_db"].replace(True, "✓").replace(False, "×")`
