### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain'

### ISSUE THREAD

**Issue by Belonger** [chatchat-space/Langchain-Chatchat#3036]
**Problem Description**
I install langchain this package. but when i run startup.py and in the browser open the address, give me this error.

**Steps to Reproduce**
1. in the terminal input python startup.py -a
2. in the browser input address
3. give me this error
![QQ截图20240222103247](https://github.com/chatchat-space/Langchain-Chatchat/assets/57164274/be0eb1ad-bbcc-4567-95bf-b12cd3729fb4)
i don`t know how to solve this problem, hope you help me, thanks!

**Comment by Belonger** [comment]
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.0-94-generic-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.344. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda  these version

**Comment by Belonger** [comment]
the python version is 3.11.7

**Comment by Belonger** [comment]
also solve this problem. only pip install streamlit --upgrade. update streamlit this package!

**Comment by Chenleader0219** [comment]
also solved my error!thank u!

**Comment by Goku17** [comment]
> error

问题怎么解决的呀？

**Comment by Goku17** [comment]
> **Problem Description** I install langchain this package. but when i run startup.py and in the browser open the address, give me this error.
> 
> **Steps to Reproduce**
> 
> 1. in the terminal input python startup.py -a
> 2. in the browser input address
> 3. give me this error
>    ![QQ截图20240222103247](https://private-user-images.githubusercontent.com/57164274/306833677-be0eb1ad-bbcc-4567-95bf-b12cd3729fb4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NjI3MjMsIm5iZiI6MTcxMzc2MjQyMywicGF0aCI6Ii81NzE2NDI3NC8zMDY4MzM2NzctYmUwZWIxYWQtYmJjYy00NTY3LTk1YmYtYjEyY2QzNzI5ZmI0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA1MDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYTE5Nzg5YzM1MDhhNmYwZDUwNGU2NjFlYmIzNTQ0Y2E3ZTVhNTYyNDM5MzU4OGIyMzQ0MDU5YTUwMGJiNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WFwsXCfct1vK9wY6J2yumoFqpCFdQdgcqIgPHxbsdCo)
>    i don`t know how to solve this problem, hope you help me, thanks!

问题是怎么解决的呀？
