### ISSUE TITLE
[BUG] langchain加载chatGLM3模型预测结果出现"<|user|>"标签，且自问自答，但fschat加载模型预测结果基本正常

### ISSUE THREAD

**Issue by justforyou2017** [chatchat-space/Langchain-Chatchat#3037]
![微信图片_20240222102006](https://github.com/chatchat-space/Langchain-Chatchat/assets/30369560/7bc0b719-39b1-495e-940e-f83f998c3f98)
![微信图片_20240222102556](https://github.com/chatchat-space/Langchain-Chatchat/assets/30369560/12472058-c3ad-48bc-aedb-2542ccc3bd8c)

![langchain2](https://github.com/chatchat-space/Langchain-Chatchat/assets/30369560/698f3156-b79b-414f-b6b9-17dbab899685)
![langchain1](https://github.com/chatchat-space/Langchain-Chatchat/assets/30369560/585c4ed7-714c-49b3-8abd-66c215392c43)

关于“wiki中Q20: chatglm3-6b对话中出现"<|user|>"标签，且自问自答”， 现象如图。
正常结果是从startup.py里的create_model_worker_app函数中worker直接调用worker.model和worker.tokenizer测试的结果是不含user标签的，结果是正常的
异常结果是从项目chain文件夹中chains.llmchain_with_history代码和UI测试结果

langchain： 0.0.354
fschat： 0.2.35
使用的模型：ChatGLM3-6B经lora合并后模型
非 Docker 部署
其他环境默认
但是使用原ChatGLM3-6B未见异常结果！

**Comment by yumu7777777** [comment]
您好老师，能未问下怎么更新吗

**Comment by zRzRzRzRzRzRzR** [comment]
huggingface有呀，直接git pull就能更新了

**Comment by ZhuXuesong7423** [comment]
这个问题还是会出现啊，怎么解决呢？
