### ISSUE TITLE
[BUG] zhipu-api  前端页面显示时少了 一些字符串

### ISSUE THREAD

**Issue by musexiaoluo** [chatchat-space/Langchain-Chatchat#3038]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31032620/5aaf739d-7ccb-4567-af3b-0e8165671653)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31032620/c69c080e-db13-47c5-bbd6-eb3cf2bce45d)

**Comment by musexiaoluo** [comment]
流式访问时

**Comment by Macbook-Specter** [comment]
请问你是用的zhipu embedding嘛，想问一下怎样配置的

**Comment by zRzRzRzRzRzRzR** [comment]
没有开流就是因为这个问题，默认是非流失的

**Comment by musexiaoluo** [comment]
> 没有开流就是因为这个问题，默认是非流失的

您好，有找到原因和解决方法吗？

**Comment by musexiaoluo** [comment]
> zhipu embedding
我也在弄，没成功。我想封装成openai embedding 的格式，但报错了。我在老的版本上改的。你弄成功了 通知我一下

**Comment by ImmNaruto** [comment]
请问下这个问题有思路了吗，我最近也遇到这个问题尝试解决，目前还没找到方法

**Comment by zRzRzRzRzRzRzR** [comment]
目前http请求应该是就是有这个问题，只能非流，sdk不会有问题，但是会和本版本0.2.x 依赖冲突

**Comment by musexiaoluo** [comment]
目前临时解决了。我调试后，发现是fastchat 截掉的字。

临时解决方法：
1、卸载fastchat包。直接用fastchat源码。
2、修改openai_api_server.py。加入以下判断
if model_name=="zhipu-api":
    delta_text=content["text"]

如图：                 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31032620/3f584809-13aa-4313-bce8-6a90c1a31197)

**Comment by musexiaoluo** [comment]
> 请问下这个问题有思路了吗，我最近也遇到这个问题尝试解决，目前还没找到方法

看我后面的评论。

**Comment by musexiaoluo** [comment]
> 目前http请求应该是就是有这个问题，只能非流，sdk不会有问题，但是会和本版本0.2.x 依赖冲突

回头可以看以下 sdk的源码，是不是做了特殊字符串处理的操作

**Comment by ImmNaruto** [comment]
@musexiaoluo 感谢大佬，用第二种方式修改openai server解决了，非常感谢

**Comment by zRzRzRzRzRzRzR** [comment]
这个可以提个PR，因为目前sdk没问题，主要是兼容上过不去所以没加

**Comment by zhjjoin** [comment]
> 目前临时解决了。我调试后，发现是fastchat 截掉的字。
> 
> 临时解决方法： 1、卸载fastchat包。直接用fastchat源码。 2、修改openai_api_server.py。加入以下判断 if model_name=="zhipu-api": delta_text=content["text"]
> 
> 如图： ![image](https://private-user-images.githubusercontent.com/31032620/308417823-3f584809-13aa-4313-bce8-6a90c1a31197.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDE2NDEsIm5iZiI6MTcxNzc0MTM0MSwicGF0aCI6Ii8zMTAzMjYyMC8zMDg0MTc4MjMtM2Y1ODQ4MDktMTNhYS00MzEzLWJjZTgtNmE5MGMxYTMxMTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA2MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMTM0OTU2MWE3YWNhNzRjNWUzOTFkN2IzNTQzYTg0MTVkMWJjZDhhZTYwNGRlNmExMjNkN2U4NjI3YTJmZTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EfGMDzxVpP4YQDylnjWAtNcN2rOBu4svym45xIb3LgE)


感谢大佬，用第二种方法，可以解决问题。
