### ISSUE TITLE
重启服务后，无法针对已有知识库进行对话

### ISSUE THREAD

**Issue by cl12191718** [chatchat-space/Langchain-Chatchat#3045]
**问题描述 / Problem Description**
将服务重启之后，无法与已经创建过的知识库进行问答，只能新建知识库才可以

**复现问题的步骤 / Steps to Reproduce**
1.创建知识库
![Uploading 1.png…]()

在`knowledge_base/test1`可以看到文档和向量库
![Uploading 2.png…]()

2.进行知识库问答
![Uploading 3.png…]()

3.重启服务，再对test1知识库进行提问，就无法根据已有的知识库进行问答了
![Uploading 4.png…]()

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：openai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：jinaai/jina-embeddings-v2-base-en
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux-5.4.0-100-generic-x86_64-with-glibc2.27
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information: langchain版本：0.0.354. fastchat版本：0.2.35

**Comment by zRzRzRzRzRzRzR** [comment]
没有遇到相关问题，复现不出来。。。你更新一下最新代码吧
