### ISSUE TITLE
"删除知识库内指定文件"接口是不是有BUG

### ISSUE THREAD

**Issue by luojihaohuawei** [chatchat-space/Langchain-Chatchat#3048]
在调用”/knowledge_base/delete_docs“删除知识库内文件时，能返回200并提示删除成功，文件所保存的目录下也没有该文件，但是再用”/knowledge_base/list_files“进行搜索时却又能获取到刚刚提示已删除的文件，请问这个是BUG吗

**Comment by zRzRzRzRzRzRzR** [comment]
这是删除知识库，不是删除文件，相当于删除vector stor那个文件夹

**Comment by zRzRzRzRzRzRzR** [comment]
是删除这个文件并重新弄一个没有这个文件的vector store

**Comment by luojihaohuawei** [comment]
> 是删除这个文件并重新弄一个没有这个文件的vector store

抱歉，这里我不是很理解清楚，我的理解是：按照您的说法重新弄的vector store不是应该覆盖旧的vector store吗？，这样才能实现删除DB里面该文件的功能呀。
如果不是我理解的这样，目前项目有无实现删除包括指定知识库和存储路径下文件的接口呢？

**Comment by xxWeiDG** [comment]
请问一下，我这也出现了这个问题，您那最后怎么解决的啊
