### ISSUE TITLE
[BUG] 上传知识库文件报错

### ISSUE THREAD

**Issue by gedehua** [chatchat-space/Langchain-Chatchat#305]
![19621e29eaa547d01213bee53d81e6a](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/84606552/7f6ceb46-e494-4b0e-939c-23b585a6d9d8)

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/84606552/5cdc8b00-59a1-4296-a5b4-746ed615dded)

**Comment by walker83** [comment]
问题一样

**Comment by zfanswer** [comment]
+1
用文件夹传会一直跑不完

**Comment by xjwspeak** [comment]
切老版本可以加载了， 看来是master的bug，需要尽快修复
