### ISSUE TITLE
知识库导入文件时，后台报错，但是前台没有报错，而且导入后的知识库问答不可用

### ISSUE THREAD

**Issue by xxWeiDG** [chatchat-space/Langchain-Chatchat#3053]
**问题描述 / Problem Description**
知识库导入文件时，后台报错，但是前台没有报错，而且导入后的知识库问答不可用

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
报错结果如下图
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/140797957/d4c0cf30-87cd-4cad-a099-a5ca926af6c9)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:ubuntu22.04
- Python 版本 / Python version:3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
报错了肯定没成功，你这个大概率也是依赖问题，正常不会出现这种import的错误
