### ISSUE TITLE
在知识库问答中，如何提高模型的数学计算正确率？

### ISSUE THREAD

**Issue by chillizex** [chatchat-space/Langchain-Chatchat#3056]
**问题描述 / Problem Description**
在知识库问答中，如何提高模型的数学计算正确率？

在涉及到知识库问答且带有简单四则运算的场景中，模型难以得出正确的计算结果。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：QWEN1.5-72B-INT4-GPTQ
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bce-embedding-base + bce-reranker-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: ubuntu 22.04
- Python 版本 / Python version: 3.10.9

**Comment by zRzRzRzRzRzRzR** [comment]
换更大的模型，模型能力与知识库无关
