### ISSUE TITLE
How to realize hierarchical index retrieval and fusion retrieval?

### ISSUE THREAD

**Issue by liurf2-dev** [chatchat-space/Langchain-Chatchat#3058]
1. Hierarchical index retrieval:
For example, there are two datasets: one contains the title of articles, the other contains the specific content of the articles. I want to retrieve title and match it with the article first, and then transmit article to LLM and answer the user. Is this function available in Langchain_Chatchat?

2. Fusion retrieval:
For example, I want to use Faiss and BM25. Is this available? And which algorithm is used to ensemble those retrievals?

**Comment by glide-the** [comment]
Unfortunately, the current version of this project does not support relational retrieval. However, in the next version, we will use knowledge graph and text2sql to support similar functionality.

For fusion retrieval，unsupported  
In theory, for implementing top k retrieval with multi-stage retrieval and re-ranking, you can refer to the runable and RunnableParallel in langchain.

**Comment by liurf2-dev** [comment]
> Unfortunately, the current version of this project does not support relational retrieval. However, in the next version, we will use knowledge graph and text2sql to support similar functionality.
> 
> For fusion retrieval，unsupported In theory, for implementing top k retrieval with multi-stage retrieval and re-ranking, you can refer to the runable and RunnableParallel in langchain.

Thanks a lot for your reply. May I know when the next version will be released approximately?
