### ISSUE TITLE
[BUG] AssertionError: <class 'gradio.layouts.Accordion'> Component with id 41 not a valid input component.

### ISSUE THREAD

**Issue by abbhay** [chatchat-space/Langchain-Chatchat#306]
**问题描述 / Problem Description**
shang上传知识库文件的时候报了错误，上传不了文件

![1683722066299](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/36267615/ee99439b-eed4-42be-bd35-9dc7a53ebee9)

**Comment by aiwenForGit** [comment]
我刚才升级的时候也碰到同样的问题了。之前版本可以的

**Comment by zfanswer** [comment]
0.1.11可以了

**Comment by dancemanUK** [comment]
同样的问题，5.17号，

**Comment by zRzRzRzRzRzRzR** [comment]
请更新到最新代码重试，应该能解决这个问题
