### ISSUE TITLE
[BUG] 数据库初始化的问题 / 无法继续

### ISSUE THREAD

**Issue by Ryan512527** [chatchat-space/Langchain-Chatchat#3063]
执行python init_database.py --recreate-vs后报warning

2024-02-24 02:22:55,031 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2024-02-24 02:22:55,069 - loader.py[line:56] - INFO: Successfully loaded faiss with AVX2 support.
/Users/ryan/miniconda3/envs/chatchat/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
Segmentation fault: 11
(chatchat) bogon:Langchain-Chatchat-master ryan$ /Users/ryan/miniconda3/envs/chatchat/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by Ryan512527** [comment]
如果faiss对macos的支持不好，能否用其他进行替换使用

**Comment by Ryan512527** [comment]
> _🤖_
> 
> 嘿，@Ryan512527！很高兴再次见到你。希望一切顺利！
> 
> 根据您提供的日志，问题可能与`faiss`包有关，这个包在Langchain-Chatchat中用于高效的相似性搜索和密集向量的聚类。错误信息`Segmentation fault: 11`通常表示程序试图访问的内存区域是禁止访问的，或者程序试图执行的操作系统不允许执行。这可能是由于`faiss`包的版本问题，或者是`faiss`包与其他包的兼容性问题。
> 
> 在Langchain-Chatchat的问题库中，我找到了几个类似的已解决问题，可能对您有所帮助：
> 
> 1. [[BUG] 3. 初始化知识库和配置文件 报错  python init_database.py --recreate-vs](https://github.com/chatchat-space/Langchain-Chatchat/issues/2283)：这个问题的解决方案是确保正确安装了`sentence-transformers`包，手动下载`bge-large-zh`模型，并在`model_config.py`文件中更新`EMBEDDING_MODEL`和`MODEL_PATH`。
> 2. [[BUG] python init_database.py --recreate-vs 无反应](https://github.com/chatchat-space/Langchain-Chatchat/issues/2828)：这个问题的解决方案是检查您的Python环境和Langchain-Chatchat代码库，如果命令长时间无响应，可能是由于数据量大或Python环境问题。
> 3. [执行python init_database.py --recreate-vs时报错：L2 is not applicable for metric type: METRIC INNER_PRODUCT](https://github.com/chatchat-space/Langchain-Chatchat/issues/2706)：这个问题的解决方案是降级`faiss`包的版本，将`normalize_L2=True`改为`normalize_L2=False`，并在`model_config.py`中调整`SCORE_THRESHOLD`的值。
> 
> 根据这些解决方案，我建议您首先尝试降级`faiss`包的版本，看看是否能解决问题。如果问题仍然存在，您可以尝试修改`normalize_L2=True`为`normalize_L2=False`，并调整`SCORE_THRESHOLD`的值。如果以上步骤都不能解决问题，您可能需要检查您的Python环境和Langchain-Chatchat代码库，看看是否有其他可能的问题。
> 
> 希望这些信息对您有所帮助，如果您有任何其他问题或需要进一步的帮助，请随时告诉我。
> 
> ## Sources
> * [[BUG] 3. 初始化知识库和配置文件 报错  python init_database.py --recreate-vs](https://github.com/chatchat-space/Langchain-Chatchat/issues/2283)
> * [[BUG] python init_database.py --recreate-vs 无反应](https://github.com/chatchat-space/Langchain-Chatchat/issues/2828)
> * [执行python init_database.py --recreate-vs时报错：L2 is not applicable for metric type: METRIC INNER_PRODUCT](https://github.com/chatchat-space/Langchain-Chatchat/issues/2706)
> * [init_database.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/init_database.py)
> * [server/knowledge_base/kb_service/faiss_kb_service.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/faiss_kb_service.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

如果faiss对macos的支持不好，能否用其他进行替换使用。@dosu-bot

**Comment by zRzRzRzRzRzRzR** [comment]
可以，另外几个比如chroma都行的，faiss可以他们官方的github查询mac怎么一步一步安装
