### ISSUE TITLE
调用自定义Agent，查询天气，没有任何返回

### ISSUE THREAD

**Issue by jingzl** [chatchat-space/Langchain-Chatchat#3069]
**问题描述 / Problem Description**
选择对话，对话模式为自定义Agent问答，LLM模型为 chatglm3-6b。在kb_config.py中已配置好 SENIVERSE_API_KEY。

**复现问题的步骤 / Steps to Reproduce**
询问：今天北京的天气

**预期的结果 / Expected Result**
应该正常返回北京的天气信息。

**实际结果 / Actual Result**
Thought: 我需要使用weather_check工具来检查天气预报。
然后没有结果。感觉没有调用 weather_check 工具，如何才能有结果呢？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5 @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:  ubuntu 20.04
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2803602/6af05294-6cff-4bbc-adf0-dab73d8ce55b)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/2803602/bdc67ea1-09ef-4e2e-a39c-dc8d586e0d4a)

**Comment by jingzl** [comment]
好像智能助手 没有理解我的意思，我已经设置好了 心知天气 API KEY。
有其他人碰到这个问题吗？
现在是一个agent都没有调用成功，是哪里配置出了问题？

现在的情况如下：

今天武汉的天气如何？
I will use the 'weather_check' tool to find out the current weather in Wuhan.
思考过程：
I will use the 'weather_check' tool to find out the current weather in Wuhan.

然后就没有下文了。

**Comment by zRzRzRzRzRzRzR** [comment]
chatglm3要用glm的格式，其他事default

**Comment by monkeydone** [comment]
@zRzRzRzRzRzRzR  你回复的这个是啥意思,有文档吗?

**Comment by jingzl** [comment]
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/2803602/138ee031-f40f-411b-ba50-5bd22ca94b22)
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/2803602/6c5c01ef-e69a-4beb-a61d-810f4ad63e99)

**Comment by zRzRzRzRzRzRzR** [comment]
temper拉到0.01 ，其他的话我没雨遇到了，我这是正常运行的

**Comment by HARUCCC** [comment]
请问解决了吗，我也是这个问题

**Comment by pyyj** [comment]
我也是遇到调用tool不成功的情况，即使是使用自带的计算器工具也基本和楼主的情况一样，思考过程表示需要调用相应的工具，然后就没有输出了

**Comment by victorxst** [comment]
遇到相同的问题，请问问题解决了吗

**Comment by pyyj** [comment]
> chatglm3要用glm的格式，其他事default

请问chatglm3需要特有的什么格式，是提示的格式还是什么

**Comment by jingzl** [comment]
没有解决，问题依旧

**Comment by liujie316316** [comment]
同样的问题，有人解决了吗？？？？？

**Comment by Leiyanzangxiangsi** [comment]
相同的问题，有人解决吗？

**Comment by liushaoqian** [comment]
> 好像智能助手 没有理解我的意思，我已经设置好了 心知天气 API KEY。 有其他人碰到这个问题吗？ 现在是一个agent都没有调用成功，是哪里配置出了问题？
> 
> 现在的情况如下：
> 
> 今天武汉的天气如何？ I will use the 'weather_check' tool to find out the current weather in Wuhan. 思考过程： I will use the 'weather_check' tool to find out the current weather in Wuhan.
> 
> 然后就没有下文了。
你们解决了吗，我也碰到了这个问题，我用的qwen的大模型

**Comment by JungHo-sudo** [comment]
> > 同样的问题，有人解决了吗？？？？
> 
> 有解决了吗，我也遇到了这个问题，我用的是qwen2-instruct的模型

你解决了吗

**Comment by liushaoqian** [comment]
你看看你的apikey是不是填错了，那个apikey是私钥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月17日(周一) 下午3:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] 调用自定义Agent，查询天气，没有任何返回 (Issue #3069)


     
同样的问题，有人解决了吗？？？？
  
有解决了吗，我也遇到了这个问题，我用的是qwen2-instruct的模型
  
你解决了吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  JungHo-sudo left a comment (chatchat-space/Langchain-Chatchat#3069)
   
同样的问题，有人解决了吗？？？？
  
有解决了吗，我也遇到了这个问题，我用的是qwen2-instruct的模型
  
你解决了吗
