### ISSUE TITLE
第二次运行时上传文本过程中超时间以及在删除列填入 Y 无法删除那一行

### ISSUE THREAD

**Issue by goodmaney** [chatchat-space/Langchain-Chatchat#3070]
**问题描述 / Problem Description**
初次运行能上传文件成功，第二次上传不成功。第一次上传文件解析成功后无法删除任意一行文档列表，对任意一行文档列表进行修改后其他行会被全部删除。第二次上传后web页面文件内文档列表为空
**复现问题的步骤 / Steps to Reproduce**
1. 执行上传文件
2. 点击添加到知识库
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/upload_docs: timed out; 新建知识库页面文件解析不出文档，但上传过程中终端能打印解析后文档文字

**预期的结果 / Expected Result**
描述应该出现的结果 / 知识库 中已有文件:

**实际结果 / Actual Result**
描述实际发生的结果 / 文档没任何内容加载

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.10 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-m3
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / windows10
- Python 版本 / Python version:3.11.4
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 /

**Comment by SmilEzzh94** [comment]
删除列没有正确保存吧，webui_pages/knowledge_base/knowledge_base.py 文件注释掉几行代码就行
<img width="841" alt="截屏2024-02-26 16 59 41" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/55201890/9a255284-2219-4b5f-8ebe-5cc27e8c85ff">
