### ISSUE TITLE
【BUG】使用API和WEBUI进行对话时出现“no such table: message”对应表不存在的问题

### ISSUE THREAD

**Issue by WilkinsLiu** [chatchat-space/Langchain-Chatchat#3071]
使用webui进行对话时出现
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: message
    | [SQL: INSERT INTO message (id, conversation_id, chat_type, "query", response, meta_data, feedback_score, feedback_reason, create_time) VALUES (?, ?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP) RETURNING create_time]
    | [parameters: ('e9f54b52ff324abf8bf407488d50f091', 'debcdd278ce64387b756840ffee2de3f', 'llm_chat', '你好', '', '{}', -1, '')]
    | (Background on this error at: https://sqlalche.me/e/20/e3q8)
模型使用的是chatglm2-6b，像是初始化之后没有建message表，导致查询向量数据库的时候报错

**Comment by zRzRzRzRzRzRzR** [comment]
怎么感觉是你没有初始化模型和数据库呢

**Comment by WilkinsLiu** [comment]
@dosu-bot我反复执行了python init_database.py --recreate-vs 和 python init_database.py --create-tables 两个命令，其中python init_database.py --recreate-vs 可以看到重新加载了知识库数据，python init_database.py --create-tables 执行后没有任何反应，仍然出现no such table: message的错误，MessageModel这个源代码查看过但是没有修改过。python init_database.py --recreate-vs执行过程中出现
ERROR: RuntimeError: 从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading F:\Github\Langchain-Chatchat\knowledge_base\samples\content\test_files/langchain-ChatGLM_closed.csv
2024-02-26 21:36:31,341 - utils.py[line:377] - ERROR: ImportError: 从文件 samples/test_files/langchain-ChatGLM_closed.jsonl 加载文档时出错：jq package not found, please install it with `pip install jq`
两个错误，无其他错误，完成后显示2024-02-26 21:39:18,127 - faiss_cache.py[line:38] - INFO: 已将向量库 ('samples', 'm3e-base') 保存到磁盘
总计用时： 0:05:23.308167
不知道是否跟上述两个Error有关，问题未得到解决

**Comment by liunux4odoo** [comment]
> @dosu-bot我反复执行了python init_database.py --recreate-vs 和 python init_database.py --create-tables 两个命令，其中python init_database.py --recreate-vs 可以看到重新加载了知识库数据，python init_database.py --create-tables 执行后没有任何反应，仍然出现no such table: message的错误，MessageModel这个源代码查看过但是没有修改过。python init_database.py --recreate-vs执行过程中出现 ERROR: RuntimeError: 从文件 samples/test_files/langchain-ChatGLM_closed.csv 加载文档时出错：Error loading F:\Github\Langchain-Chatchat\knowledge_base\samples\content\test_files/langchain-ChatGLM_closed.csv 2024-02-26 21:36:31,341 - utils.py[line:377] - ERROR: ImportError: 从文件 samples/test_files/langchain-ChatGLM_closed.jsonl 加载文档时出错：jq package not found, please install it with `pip install jq` 两个错误，无其他错误，完成后显示2024-02-26 21:39:18,127 - faiss_cache.py[line:38] - INFO: 已将向量库 ('samples', 'm3e-base') 保存到磁盘 总计用时： 0:05:23.308167 不知道是否跟上述两个Error有关，问题未得到解决

你是先停止 startup.py，再 init_database，然后再 启动 startup 服务的吗？

**Comment by skywolf123** [comment]
建议删除Langchain-Chatchat/knowledge_base下面的info.db文件及Langchain-Chatchat\knowledge_base\samples\vector_store文件夹，重新进行初始化python init_database.py --recreate-vs
