### ISSUE TITLE
pdf中含有”->"字符，读取出来后只有">"一个字符

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#3079]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/147676947/73d12fa5-cf54-401f-a6b9-45e2a1b4c0d6)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/147676947/d943aba7-a9f6-46f0-9bce-2a5f15ffd842)
如题，实际pdf中有个"->"符号，采用pdfloader加载后，实际读取出来的只有">"符号，而且进行了换行。这个bug要怎样修改呢

**Comment by zRzRzRzRzRzRzR** [comment]
OCR识别后还分词，这种丢失很正常，你要不直接用txt
