### ISSUE TITLE
将langchain和微调后的chatglm3结合

### ISSUE THREAD

**Issue by 153zml** [chatchat-space/Langchain-Chatchat#3080]
请问后续会添加将langchain和与微调后的chatglm3结合的功能吗
由于chatglm3是目前国内主流的开源大模型，在国内有很大的需求。理论上讲，使用垂域的数据集微调chatglm3，结合langchain模型能够极大提升模型的表现性能

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki
