### ISSUE TITLE
ImportError: cannot import name 'AsyncOpenAI' from 'openai'

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#3082]
**问题描述 / Problem Description**
一开始出现peer closed connection without sending complete message body (incomplete chunked read)这个问题
看到网上说把openai由原来的1.9改为0.28.1。
改完后，上面的问题没有了，但又出现了ImportError: cannot import name 'AsyncOpenAI' from 'openai'这个问题。

**复现问题的步骤 / Steps to Reproduce**
1.提问问题时报第一个错误，修改openai版本后
2.执行python start.py -a，出现第二个错误

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-14b-int8
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:centos7.9
- Python 版本 / Python version:3.11

**Comment by guiniao** [comment]
已解决，跟openai的版本没有直接的关系，我的问题在于把服务器的gcc从4.85升级到9.5，导致报了第一个错误，gcc版本重新回到4.85就没问题了

**Comment by cackako** [comment]
> 已解决，跟openai的版本没有直接的关系，我的问题在于把服务器的gcc从4.85升级到9.5，导致报了第一个错误，gcc版本重新回到4.85就没问题了

我把gcc和g++都改为4.85了，还是报peer closed connection without sending complete message body (incomplete chunked read)，请问您具体是怎么解决的捏

**Comment by linaiyue** [comment]
> > 已解决，跟openai的版本没有直接的关系，我的问题在于把服务器的gcc从4.85升级到9.5，导致报了第一个错误，gcc版本重新回到4.85就没问题了
> 
> 我把gcc和g++都改为4.85了，还是报peer closed connection without sending complete message body (incomplete chunked read)，请问您具体是怎么解决的捏

请问你解决了嘛？我的报错跟你一样

**Comment by characterma** [comment]
我也遇到了同样的问题
`
from openai import AsyncOpenAI

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_83542/2583188620.py in <module>
----> 1 from openai import AsyncOpenAI

ImportError: cannot import name 'AsyncOpenAI' from 'openai' (/opt/conda/lib/python3.8/site-packages/openai/__init__.py)
​`
我认为这是openai版本引发的问题，我当前使用的openai 0.28.0,此版本中没有这个方法，也没有找到可以替换AsyncOpenAI的办法

**Comment by characterma** [comment]
> 已解决，跟openai的版本没有直接的关系，我的问题在于把服务器的gcc从4.85升级到9.5，导致报了第一个错误，gcc版本重新回到4.85就没问题了

我觉得和gcc没有关系

**Comment by heavi715** [comment]
openai==1.55.2
