### ISSUE TITLE
怎么增加推理速度，tokens生成速度

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#3084]
目前用的时qwen14b的模型，embedding模型是bge-large-zh-v1.5，环境是双卡A40，不管是llm对话，还是知识库问答，回答的都很慢，有比较好的方法，可以加快推理速度吗

**Comment by zRzRzRzRzRzRzR** [comment]
可以自己魔改模型推理代码，fschat是hf包装的，一定是最慢最稳的，你可以自己写模型加速框架并用openai-api引入到这个项目，模型加速不在这个项目的范围
