### ISSUE TITLE
[DOC] API 文档 / 在 Wiki 内新增 API 文档

### ISSUE THREAD

**Issue by BertieGo** [chatchat-space/Langchain-Chatchat#3086]
使用阿里云 PAI 的 DSW 和 AutoDL 来部署 Chatchat 都访问不了 API 文档，各种资源访问报错😭，可以直接把 API 文档放在 Wiki 里面吗？谢谢

**Comment by BertieGo** [comment]
/chat/knowledge_base_chat 接口具体要传递什么参数？

**Comment by zRzRzRzRzRzRzR** [comment]
建议源代码安装，autodl那个有bug，源码已经修复了
