### ISSUE TITLE
How to use Knowledge Base Chat and Search Engine Chat at the same query?

### ISSUE THREAD

**Issue by liurf2-dev** [chatchat-space/Langchain-Chatchat#3087]
Is there any function to merge information that retrieved from search engine and local knowledge base in one query. If no, will it be added in the next version?

For example:
User Question: Is there any climate change that may affect the highway between Beijing and Shenzhen recently?
Local Info: the highway info from traffic database
Online Info: the climate change news about Beijing and Shenzhen
Answer: the analysis that based on the merged info.

**Comment by zRzRzRzRzRzRzR** [comment]
理论上可以，你需要自己修改代码。相当于把两个代码文件合并到一起就可以了
