### ISSUE TITLE
[BUG] 大模型回答陷入死循环，回答内容出入较大

### ISSUE THREAD

**Issue by yumu7777777** [chatchat-space/Langchain-Chatchat#3088]
**问题描述 / Problem Description**
大模型回答陷入死循环，回答内容出入较大，示例0.2.8、0.2.9、0.2.10都是一样的问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104643678/dd89d5ee-e767-49a5-842b-38657d1109d1)

**复现问题的步骤 / Steps to Reproduce**
运行项目，web端问答时

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： langchain：0.0.344、langchain：0.0.344、langchain-community：0.0.20、langchain-core、0.0.13 、langchain-experimental:0.0.43
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm3-6b-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：  pg_vector
- 操作系统及版本 / Operating system and version:   Description:	Ubuntu 22.04.1 LTS  Release:	22.04
- Python 版本 / Python version: 3.10.13 
- 其他相关环境信息  

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by yumu7777777** [comment]
已经是0.2.8版本了，并且fschat版本为0.2.33 。希望有回复。

**Comment by zRzRzRzRzRzRzR** [comment]
glm模型文件没更新吧，更新到0223最新版本

**Comment by qianma819** [comment]
我全部更新的最新，有时候还是有这个问题的。凑合用吧，一个开源项目指望多高的要求呢

**Comment by yumu7777777** [comment]
我把模型换成chatglm2-6b，这个没问题

**Comment by qianma819** [comment]
是嘛，还真是模型的问题啊。我机器只能跑量化模型，chatglm2-6b-int效果太拉了，还不如千问。千问有时候也是会出现一个死循环，只是某些特殊场景
