### ISSUE TITLE
chatchat调用自己部署的模型API

### ISSUE THREAD

**Issue by fuxiaoiii** [chatchat-space/Langchain-Chatchat#3093]
**问题描述 / Problem Description**
我想要自己部署模型并可通过openai形式的API调用，但是chatchat报错：invalue http request

**复现问题的步骤 / Steps to Reproduce**
1. 部署chatglm3的openai API
2. 在文件 /configs/model_config.py文件中修改openai-api 为
    "glm-api": {
        "model_name": "chatglm3-6b",
        "api_base_url": "https://####:8000/v1/chat",
        "api_key": "empty",
        "openai_proxy": "",
    },
4. 在文件/configs/server_config.py文件中修改其为
     "glm-api": {  # 使用default中的IP和端口
        "port": "22000",
    },

6. 问题出现 / Problem occurs
部署chatglm3的终端：WARNING:  Invalid HTTP request received.
部署chatchat的终端：ERROR: APIConnectionError: 获取ChatCompletion时出错：Error communicating with OpenAI
**预期的结果 / Expected Result**
回复模型的回复结果

- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5

**Comment by fuxiaoiii** [comment]
解决了，"api_base_url": "https://api.openai.com/v1"  替换https为http即可

**Comment by hyy666168** [comment]
你好，我想了解下这个glm3是本地单独起的服务吗？

**Comment by fuxiaoiii** [comment]
> 你好，我想了解下这个glm3是本地单独起的服务吗？

不是本地，是云端，但和chatchat服务不在一个服务器

**Comment by hyy666168** [comment]
感谢及时回复哈，我这边的服务和您的部署方式类似，也是远程服务器启动的一个大模型的服务，大模型的调用方式如下：curl --location 'https://xxxxx/generate' --header 'Content-Type: application/json' --data '{"inputs":"你好","parameters":{"max_new_tokens":1000}}'那么按照您的经验，我这边需要怎么接入这个大模型服务呢，我的大模型是自己微调的千问7B模型
&nbsp;


黄于晏
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月7日(星期天) 下午5:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] chatchat调用自己部署的模型API (Issue #3093)














  
你好，我想了解下这个glm3是本地单独起的服务吗？
  
不是本地，是云端，但和chatchat服务不在一个服务器

**Comment by hyy666168** [comment]
感谢及时回复哈，我这边的服务和您的部署方式类似，也是远程服务器启动的一个大模型的服务，大模型的调用方式如下：curl --location 'https://xxxxx/generate' --header 'Content-Type: application/json' --data '{"inputs":"你好","parameters":{"max_new_tokens":1000}}'那么按照您的经验，我这边需要怎么接入这个大模型服务呢，我的大模型是自己微调的模型

**Comment by fuxiaoiii** [comment]
将大模型部署为openai api，在model_config文件中添加信息，你可以参考我的代码
&nbsp; &nbsp; "model-api": {
&nbsp; &nbsp; &nbsp; &nbsp; "model_name": "chatglm3-6b",
&nbsp; &nbsp; &nbsp; &nbsp; "api_key": "EMPTY",
&nbsp; &nbsp; &nbsp; &nbsp; "api_base_url": "http://17.52.213.63:8000/v1",
&nbsp; &nbsp; &nbsp; &nbsp;# "version": "chatglm3-6b",&nbsp; # 可选包括 "chatglm_turbo"
&nbsp; &nbsp; },
同时需要在server_config中添加端口信息


但是我发现您的url后缀并不是v1，我不清楚这符不符合openai api以及是否可以直接替换其中的url




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Bayesian ***@***.***&gt;; 
发送时间: 2024年4月7日(星期天) 下午5:19
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] chatchat调用自己部署的模型API (Issue #3093)














 感谢及时回复哈，我这边的服务和您的部署方式类似，也是远程服务器启动的一个大模型的服务，大模型的调用方式如下：curl --location 'https://xxxxx/generate' --header 'Content-Type: application/json' --data '{"inputs":"你好","parameters":{"max_new_tokens":1000}}'那么按照您的经验，我这边需要怎么接入这个大模型服务呢，我的大模型是自己微调的千问7B模型 
 &amp;nbsp; 
 
 
 黄于晏 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2024年4月7日(星期天) 下午5:14 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [chatchat-space/Langchain-Chatchat] chatchat调用自己部署的模型API (Issue #3093) 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
    
 你好，我想了解下这个glm3是本地单独起的服务吗？ 
    
 不是本地，是云端，但和chatchat服务不在一个服务器

**Comment by hyy666168** [comment]
明白，我在部署自己微调的大模型之前，也尝试过kimi的调用方式，通过官方文档我发觉kimi也有支持openai形式的接口，您是否有尝试过接入kimi呢？我接入发现也会报错
  # kimi api https://platform.moonshot.cn/docs/api-reference#python-%E8%B0%83%E7%94%A8%E6%96%B9%E6%B3%95
    "kimi-api": {
        "model_name": "moonshot-v1-8k",
        "api_base_url": "https://api.moonshot.cn/v1/chat/completions",
        "api_key": "sk-x",
    },
 报错：# openai.NotFoundError: Error code: 404 - {'code': 5, 'error': 'url.not_found', 'message': '没找到对象', 'method': 'POST', 'scode': '0x5', 'status': False, 'ua': 'OpenAI/Python 1.3.2', 'url': '/v1/chat/completions/chat/completions'}
按照你的方法修改https为http之后好像也无法生效，想请教下你

**Comment by BANGzys** [comment]
我也是服务器起了模型并设置好了openai-api，然后在个人pc本地去通过openai-api调用服务器的模型，但是webui问问题不出结果，报错 utils.py[line:40] - ERROR: APIConnectionError: Caught exception: Connection error.

**Comment by hyy666168** [comment]
> 我也是服务器起了模型并设置好了openai-api，然后在个人pc本地去通过openai-api调用服务器的模型，但是webui问问题不出结果，报错 utils.py[line:40] - ERROR: APIConnectionError: Caught exception: Connection error.

我也是不行，那个openai_proxy也不会搞。不过后来在在 server/utils.py加代理好像可以了，代理要自己搞一个，可以试试改下两个函数

def get_OpenAI(
        model_name: str,
        temperature: float,
        max_tokens: int = None,
        streaming: bool = True,
        echo: bool = True,
        callbacks: List[Callable] = [],
        verbose: bool = True,
        **kwargs: Any,
) -> OpenAI:
    config = get_model_worker_config(model_name)
    if model_name in ["openai-api"]:
        model_name = config.get("model_name")
        **os.environ['http_proxy'] = 'http://xxxxx:1234'
        os.environ['https_proxy'] = 'http://xxxxx:1234'**
......
def get_ChatOpenAI(
        model_name: str,
        temperature: float,
        max_tokens: int = None,
        streaming: bool = True,
        callbacks: List[Callable] = [],
        verbose: bool = True,
        **kwargs: Any,
) -> ChatOpenAI:
    config = get_model_worker_config(model_name)
    if model_name in ["openai-api"]:
        model_name = config.get("model_name")
        **os.environ['http_proxy'] = 'http://xxxxx:1234'
        os.environ['https_proxy'] = 'http://xxxxx:1234'**

然后configs/model_config.py ，这样写就ok
    "openai-api": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "",
    },

**Comment by hyy666168** [comment]
> > 明白，我在部署自己微调的大模型之前，也尝试过kimi的调用方式，通过官方文档我发觉kimi也有支持openai形式的接口，您是否有尝试过接入kimi呢？我接入发现也会报错
> > # kimi api https://platform.moonshot.cn/docs/api-reference#python-%E8%B0%83%E7%94%A8%E6%96%B9%E6%B3%95
> > ```
> > "kimi-api": {
> >     "model_name": "moonshot-v1-8k",
> >     "api_base_url": "https://api.moonshot.cn/v1/chat/completions",
> >     "api_key": "sk-x",
> > },
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 报错：# openai.NotFoundError: Error code: 404 - {'code': 5, 'error': 'url.not_found', 'message': '没找到对象', 'method': 'POST', 'scode': '0x5', 'status': False, 'ua': 'OpenAI/Python 1.3.2', 'url': '/v1/chat/completions/chat/completions'} 按照你的方法修改https为http之后好像也无法生效，想请教下你
> 
> 我并不了解该模型，也没有接入过kimi，但是你的api_base_url 应该去掉后面的chat/completions，即修改为https://api.moonshot.cn/v1 。此外，我认为你在部署为openai api形式后，应该手动写程序去调用该API，确认可以得到回复后再融入chatchat使用

感谢，我已经接入了
配置如下
    "kimi-api": {
        "model_name": "moonshot-v1-8k",
        "api_base_url": "https://api.moonshot.cn/v1",
        "api_key": "sk-x",
    },

**Comment by newstargo** [comment]
> > > 明白，我在部署自己微调的大模型之前，也尝试过kimi的调用方式，通过官方文档我发觉kimi也有支持openai形式的接口，您是否有尝试过接入kimi呢？我接入发现也会报错
> > > # Kimi API https://platform.moonshot.cn/docs/api-reference#python-%E8%B0%83%E7%94%A8%E6%96%B9%E6%B3%95
> > > ```
> > > "kimi-api": {
> > >     "model_name": "moonshot-v1-8k",
> > >     "api_base_url": "https://api.moonshot.cn/v1/chat/completions",
> > >     "api_key": "sk-x",
> > > },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 报错：# openai.NotFoundError： 错误代码： 404 - {'code'： 5， 'error'： 'url.not_found'， 'message'： '没找到对象'， 'method'： 'POST'， 'scode'： '0x5'， 'status'： False， 'ua'： 'OpenAI/Python 1.3.2'， 'url'： '/v1/chat/completions/chat/completions'} 按照你的方法修改https为http之后好像也无法生效，想请教下你
> > 
> > 
> > 我并不了解该模型，也没有接入过kimi，但是你的api_base_url 应该去掉后面的chat/completions，即修改为 https://api.moonshot.cn/v1 。此外，我认为你在部署为openai api形式后，应该手动写程序去调用该API，确认可以得到回复后再融入chatchat使用
> 
> 感谢，我已经接入了 配置如下 “kimi-api”： { “model_name”： “大胆创新计划-v1-8k”， “api_base_url”： “https://api.moonshot.cn/v1”， “api_key”： “sk-x”， }，

为何我按你的脚本执行，还是连不上kimi?
ERROR: NotFoundError: Caught exception: Error code: 404 - {'error': {'message': 'not found the model or permission denied', 'type': 'resource_not_found_error'}}

**Comment by chengxiangwang** [comment]
在configs.model_config.py的ONLINE_LLM_MODEL中添加一项即可，以云端部署的chatglm3-6b api_server为例：
`ONLINE_LLM_MODEL = {
    "openai-api": {
        "model_name": "gpt-4",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "",
        "openai_proxy": "",
    },
    "chatglm3-6b-api":{
        "model_name":"chatglm3-6b",
        "api_key":"EMPTY",
        "api_base_url": "http://xxx.xxx.xxx/v1",
    },
   ...
}
`

**Comment by jmsking** [comment]
> > > 明白，我在部署自己微调的大模型之前，也尝试过kimi的调用方式，通过官方文档我发觉kimi也有支持openai形式的接口，您是否有尝试过接入kimi呢？我接入发现也会报错
> > > # kimi api https://platform.moonshot.cn/docs/api-reference#python-%E8%B0%83%E7%94%A8%E6%96%B9%E6%B3%95
> > > ```
> > > "kimi-api": {
> > >     "model_name": "moonshot-v1-8k",
> > >     "api_base_url": "https://api.moonshot.cn/v1/chat/completions",
> > >     "api_key": "sk-x",
> > > },
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 报错：# openai.NotFoundError: Error code: 404 - {'code': 5, 'error': 'url.not_found', 'message': '没找到对象', 'method': 'POST', 'scode': '0x5', 'status': False, 'ua': 'OpenAI/Python 1.3.2', 'url': '/v1/chat/completions/chat/completions'} 按照你的方法修改https为http之后好像也无法生效，想请教下你
> > 
> > 
> > 我并不了解该模型，也没有接入过kimi，但是你的api_base_url 应该去掉后面的chat/completions，即修改为https://api.moonshot.cn/v1 。此外，我认为你在部署为openai api形式后，应该手动写程序去调用该API，确认可以得到回复后再融入chatchat使用
> 
> 感谢，我已经接入了 配置如下 "kimi-api": { "model_name": "moonshot-v1-8k", "api_base_url": "https://api.moonshot.cn/v1", "api_key": "sk-x", },

你好，请问下，你这边也是通过chatchat里面的get_ChatOpenAI或者get_OpenAI这个方法来调用自己部署的OpenAI服务吗？
