### ISSUE TITLE
[BUG] 添加知识库文件doc,docx文件失败

### ISSUE THREAD

**Issue by toasun** [chatchat-space/Langchain-Chatchat#3094]
**问题描述 / Problem Description**
添加知识库文件doc,docx文件失败

**复现问题的步骤 / Steps to Reproduce**
添加doc，docx文件

**预期的结果 / Expected Result**
正常分割文件

**实际结果 / Actual Result**
文件正常上传未正常分割/读取
```
2024-02-27 22:32:20,629 - utils.py[line:298] - INFO: RapidOCRDocLoader used for C:\ai\Langchain-Chatchat\knowledge_base\test\content\jq1.doc
***fuckfuck55
RapidOCRDocLoader
C:\ai\Langchain-Chatchat\knowledge_base\test\content\jq1.doc
{}
***fuckfuck66
***fuckfuck1122
2024-02-27 22:32:21,007 - utils.py[line:394] - ERROR: PackageNotFoundError: 从文件 test/jq1.doc 加载文档时出错：Package not found at 'C:\ai\Langchain-Chatchat\knowledge_base\test\content\jq1.doc'
```

异常定位在utils.py的66打印下
```
def file2docs(self, refresh: bool = False):
        print("***fuckfuck33")
        if self.docs is None or refresh:
            print("***fuckfuck44")
            logger.info(f"{self.document_loader_name} used for {self.filepath}")
            print("***fuckfuck55")
            
            print(self.document_loader_name);
            print(self.filepath);
            print(self.loader_kwargs);

            loader = get_loader(loader_name=self.document_loader_name,
                                file_path=self.filepath,
                                loader_kwargs=self.loader_kwargs)
            print("***fuckfuck66")
            self.docs = loader.load()--------------------------------------->出错
            print("***fuckfuck77")
        return self.docs
```

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / win11，anaconda
- Python 版本 / 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

有大神可以给个解决方案吗

**Comment by bycode** [comment]
这个问题我也遇到了，doc解析失败，docx成功，排查了一下，`PackageNotFoundError` 应该指的是soffice依赖库没有安装造成的，运行 `apt-get install libreoffice-writer` 应该能解决问题，由于我用的是WSL2，没有继续尝试，遇到问题的可以试一试。

**Comment by toasun** [comment]
> 这个问题我也遇到了，doc解析失败，docx成功，排查了一下，`PackageNotFoundError` 应该指的是soffice依赖库没有安装造成的，运行 `apt-get install libreoffice-writer` 应该能解决问题，由于我用的是WSL2，没有继续尝试，遇到问题的可以试一试。

我也安装了libreoffice，不知道是什么原因，就是读doc报错，难道我是win11直接在anaconda上跑的？
我看到项目依赖的库是python-docx，但是我python-docx都是安装好的，没道理一个python项目读写doc文件需要用到跨系统的其他工具……
再等一个大神解我心头之惑

**Comment by pakchoily** [comment]
和你一样，win11直接运行anaconda,上传都没问题，就是不能向量doc,向量docx没问题。

**Comment by yumu7777777** [comment]
您好，问题解决了吗

**Comment by zRzRzRzRzRzRzR** [comment]
doc应该是langchian的问题，尝试回滚到之前的lc，不然也没办法的，这部分用的是lc

**Comment by murdonson** [comment]
> doc应该是langchian的问题，尝试回滚到之前的lc，不然也没办法的，这部分用的是lc

一直想问lc是啥

**Comment by pakchoily** [comment]
> > doc应该是langchian的问题，尝试回滚到之前的lc，不然也没办法的，这部分用的是lc
> 
> 一直想问lc是啥

langchian的缩写。。

**Comment by toasun** [comment]
> doc应该是langchian的问题，尝试回滚到之前的lc，不然也没办法的，这部分用的是lc

你好，这里建议的lc版本是多少呢？

**Comment by yumu7777777** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104643678/a451e169-a56f-4503-8928-6650cc860002)
您好，lc是他吗
