### ISSUE TITLE
[FEATURE] 如何将高效参数微调训练的模型加载起来

### ISSUE THREAD

**Issue by goodmaney** [chatchat-space/Langchain-Chatchat#3095]
**功能描述 / Feature Description**
比如使用lora进行训练后将微调模型加载起来，没找到在哪里修改

**解决的问题 / Problem Solved**
就是想自己微调模型能生成符合某种措辞的回答，然后结合langchain文章检索功能生成类似报告的回答

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki
