### ISSUE TITLE
基于ChatGLM3-6B微调后，本地化部署的OpenAI API调用问题

### ISSUE THREAD

**Issue by jingzl** [chatchat-space/Langchain-Chatchat#3104]
**问题描述 / Problem Description**
目前基于ChatGLM3-6B进行了微调，并部署发布了API（遵循openAI的接口规则）。
如何在Langchain-Chatchat中进行调用呢？

**Comment by zRzRzRzRzRzRzR** [comment]
把openai api的endpoint换成你的就行了，然后模型名称就是openai-api

**Comment by jingzl** [comment]
谢谢
