### ISSUE TITLE
[BUG] 网页可以正常打开，但是API页面打开后一片空白

### ISSUE THREAD

**Issue by ChoCoo1** [chatchat-space/Langchain-Chatchat#3114]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/92215977/f3e9119a-f821-4b6e-b105-96c418874a21)

**Comment by ChoCoo1** [comment]
已经解决，https://github.com/swagger-api/swagger-ui/tree/master/dist中下载swagger-ui-bundle.js文件，替换在server/static/目录下就可以正常使用

**Comment by yuanzhenjie** [comment]
@ChoCoo1 你是如何解决的，同样 的问题
