### ISSUE TITLE
[FEATURE] 是否能更换Faiss使用的向量匹配引擎和距离度量方式

### ISSUE THREAD

**Issue by liuchuan01** [chatchat-space/Langchain-Chatchat#3115]
在配置文件中，我已经看到了kbs_config = {
    "faiss": {
    },
我也观察了日志，去寻找了
2024-02-29 14:34:03,340 - loader.py[line:54] - INFO: Loading faiss with AVX2 support.
2024-02-29 14:34:03,358 - loader.py[line:56] - INFO: Successfully loaded faiss with AVX2 support.
的出处，但依然找不到初始化faiss时的参数，希望解惑

**Comment by liuchuan01** [comment]
现在已经去挖掘了源码，能看到faiss.py初始化时使用的是flat引擎和内积距离，请问我如何改变？

**Comment by liuchuan01** [comment]
@dosu-bot after your mention .i find this    vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT") in faiss_cache.py
now i can change distance_strategy
but still i want to change this type of index like : flat,IVF,PQ...
can you help me?

**Comment by liuchuan01** [comment]
@zRzRzRzRzRzRzR 维护者你好，我深入阅读源码后了解了加载kb的机制，梳理出这张流图（在知识库问答函数最外层加载时有所不同，因为看的版本被团队其他人做过修改）
![image-20240301124635271](https://github.com/chatchat-space/Langchain-Chatchat/assets/80431571/f766da41-65a5-455c-ba7e-53e4a02cfd50)
我注意到在faiss_cache.py中new_vector_store函数加载时指定了距离度量方式，源码：
```python
vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
```
对应的是新建知识库的场景
可是当我继续挖掘源码时我发现，最终会调用langchain源码的faiss.py中的__from函数
在该函数中，逻辑为
```python
if distance_strategy == DistanceStrategy.MAX_INNER_PRODUCT:
        index = faiss.IndexFlatIP(len(embeddings[0]))
else:
        # Default to L2, currently other metric types not initialized.
        index = faiss.IndexFlatL2(len(embeddings[0]))
```
其中的常量定义为：
```python
MAX_INNER_PRODUCT = "MAX_INNER_PRODUCT"
```
这意味着new_vector_store函数加载时传递的参数并不是正确的。最终向量距离度量方式还是L2距离。请问我的理解有误吗？
我是否可以提交一个PR，将传递的参数改为EUCLIDEAN_DISTANCE，这样可以在不造成实际影响的状态下减少误解。

目前我所在的团队正在持续研究本项目向量数据库（faiss）的使用优化中，也将开始测试内积、余弦相似度匹配的召回精度，希望后续可以为本项目作出更大贡献，感谢！

**Comment by liangpn** [comment]
> @zRzRzRzRzRzRzR 维护者你好，我深入阅读源码后了解了加载kb的机制，梳理出这张流图（在知识库问答函数最外层加载时有所不同，因为看的版本被团队其他人做过修改） ![image-20240301124635271](https://private-user-images.githubusercontent.com/80431571/309475141-f766da41-65a5-455c-ba7e-53e4a02cfd50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4ODQ3NzksIm5iZiI6MTcwOTg4NDQ3OSwicGF0aCI6Ii84MDQzMTU3MS8zMDk0NzUxNDEtZjc2NmRhNDEtNjVhNS00NTVjLWJhN2UtNTNlNGEwMmNmZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA4VDA3NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4ZDdmYTA0M2YwYzhlZTNmODkwMTBhZTczNWFmMmM5YjBlZTM5OWY3ODNjNTE4NzhlZWJkNTYwYzQ2MjdmOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HjCy5G2maLfDLBYfcTSTpeoqp3uv-KUaN0rmH0GPJ2c) 我注意到在faiss_cache.py中new_vector_store函数加载时指定了距离度量方式，源码：
> 
> ```python
> vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
> ```
> 
> 对应的是新建知识库的场景 可是当我继续挖掘源码时我发现，最终会调用langchain源码的faiss.py中的__from函数 在该函数中，逻辑为
> 
> ```python
> if distance_strategy == DistanceStrategy.MAX_INNER_PRODUCT:
>         index = faiss.IndexFlatIP(len(embeddings[0]))
> else:
>         # Default to L2, currently other metric types not initialized.
>         index = faiss.IndexFlatL2(len(embeddings[0]))
> ```
> 
> 其中的常量定义为：
> 
> ```python
> MAX_INNER_PRODUCT = "MAX_INNER_PRODUCT"
> ```
> 
> 这意味着new_vector_store函数加载时传递的参数并不是正确的。最终向量距离度量方式还是L2距离。请问我的理解有误吗？ 我是否可以提交一个PR，将传递的参数改为EUCLIDEAN_DISTANCE，这样可以在不造成实际影响的状态下减少误解。
> 
> 目前我所在的团队正在持续研究本项目向量数据库（faiss）的使用优化中，也将开始测试内积、余弦相似度匹配的召回精度，希望后续可以为本项目作出更大贡献，感谢！

请问最后的结果怎么样？这一段代码我这边跑也是有所疑惑，解析器提示
2024-03-08 15:49:35,289 - loader.py[line:64] - INFO: Loading faiss.
2024-03-08 15:49:35,320 - loader.py[line:66] - INFO: Successfully loaded faiss.
/home/hvuser/.local/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
不知道是否会有影响

**Comment by liuchuan01** [comment]
出现这个报错的原因是本地加载知识库时，会指定距离度量方式为 METRIC_INNER_PRODUCT ，但该加载不经过__from，故度量类型不会被纠正，在faiss.py的init方法调用时会有代码如下
```python
 if (
            self.distance_strategy != DistanceStrategy.EUCLIDEAN_DISTANCE
            and self._normalize_L2
        ):
            warnings.warn(
                "Normalizing L2 is not applicable for metric type: {strategy}".format(
                    strategy=self.distance_strategy
                )
            )
```
当发现距离度量方式不为L2且使用L2归一化就会出现这个报错。
在dev的最新版上面已经修复了该方法，修复的方法是在faiss_cahce.py中
```python
vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True)
```
去除了手动指定的距离度量方式，最终加载时也就是默认的L2距离。


最后，创建知识库的流程也进行了纠错，可见PullRequest#3206

**Comment by liangpn** [comment]
> 出现这个报错的原因是本地加载知识库时，会指定距离度量方式为 METRIC_INNER_PRODUCT ，但该加载不经过__from，故度量类型不会被纠正，在faiss.py的init方法调用时会有代码如下
> 
> ```python
>  if (
>             self.distance_strategy != DistanceStrategy.EUCLIDEAN_DISTANCE
>             and self._normalize_L2
>         ):
>             warnings.warn(
>                 "Normalizing L2 is not applicable for metric type: {strategy}".format(
>                     strategy=self.distance_strategy
>                 )
>             )
> ```
> 
> 当发现距离度量方式不为L2且使用L2归一化就会出现这个报错。 在dev的最新版上面已经修复了该方法，修复的方法是在faiss_cahce.py中
> 
> ```python
> vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True)
> ```
> 
> 去除了手动指定的距离度量方式，最终加载时也就是默认的L2距离。
> 
> 最后，创建知识库的流程也进行了纠错，可见PullRequest#3206

faiss_cache.py 文件_FaissPool方法大概61行，不是 也有这个方法？这一段不需要改吗？
vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")

**Comment by liuchuan01** [comment]
> > 出现这个报错的原因是本地加载知识库时，会指定距离度量方式为 METRIC_INNER_PRODUCT ，但该加载不经过__from，故度量类型不会被纠正，在faiss.py的init方法调用时会有代码如下
> > ```python
> >  if (
> >             self.distance_strategy != DistanceStrategy.EUCLIDEAN_DISTANCE
> >             and self._normalize_L2
> >         ):
> >             warnings.warn(
> >                 "Normalizing L2 is not applicable for metric type: {strategy}".format(
> >                     strategy=self.distance_strategy
> >                 )
> >             )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 当发现距离度量方式不为L2且使用L2归一化就会出现这个报错。 在dev的最新版上面已经修复了该方法，修复的方法是在faiss_cahce.py中
> > ```python
> > vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 去除了手动指定的距离度量方式，最终加载时也就是默认的L2距离。
> > 最后，创建知识库的流程也进行了纠错，可见PullRequest#3206
> 
> faiss_cache.py 文件_FaissPool方法大概61行，不是 也有这个方法？这一段不需要改吗？ vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")

61行的也要改的，在我开启的PR里改的就是61行。61行是新建知识库的情况，111行左右load_local是本地加载的情况

**Comment by liangpn** [comment]
> > > 出现这个报错的原因是本地加载知识库时，会指定距离度量方式为 METRIC_INNER_PRODUCT ，但该加载不经过__from，故度量类型不会被纠正，在faiss.py的init方法调用时会有代码如下
> > > ```python
> > >  if (
> > >             self.distance_strategy != DistanceStrategy.EUCLIDEAN_DISTANCE
> > >             and self._normalize_L2
> > >         ):
> > >             warnings.warn(
> > >                 "Normalizing L2 is not applicable for metric type: {strategy}".format(
> > >                     strategy=self.distance_strategy
> > >                 )
> > >             )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 当发现距离度量方式不为L2且使用L2归一化就会出现这个报错。 在dev的最新版上面已经修复了该方法，修复的方法是在faiss_cahce.py中
> > > ```python
> > > vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 去除了手动指定的距离度量方式，最终加载时也就是默认的L2距离。
> > > 最后，创建知识库的流程也进行了纠错，可见PullRequest#3206
> > 
> > 
> > faiss_cache.py 文件_FaissPool方法大概61行，不是 也有这个方法？这一段不需要改吗？ vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True,distance_strategy="METRIC_INNER_PRODUCT")
> 
> 61行的也要改的，在我开启的PR里改的就是61行。61行是新建知识库的情况，111行左右load_local是本地加载的情况

好的

**Comment by zixiaotan21** [comment]
楼主大佬你好，同样研究faiss向量数据库的内积、余弦相似度的优化， 谢谢楼主的细致分析！小弟还想请教一下：
1. 有点没搞明白 MAX_INNER_PRODUCT 和 Metric Inner product 两种距离度量方式有何不同？
2.  Faiss 向量库默认的距离度量方式是L2 度量吗 ，也就是后面设置的score_threshold, 值越低，相似性越高？

**Comment by liuchuan01** [comment]
> 楼主大佬你好，同样研究faiss向量数据库的内积、余弦相似度的优化， 谢谢楼主的细致分析！小弟还想请教一下：
> 
> 1. 有点没搞明白 MAX_INNER_PRODUCT 和 Metric Inner product 两种距离度量方式有何不同？
> 2. Faiss 向量库默认的距离度量方式是L2 度量吗 ，也就是后面设置的score_threshold, 值越低，相似性越高？

1. MAX_INNER_PRODUCT是langchain原码中规定的一个常量，用来初始化faiss， Metric Inner product 可能是LangchainChatchat开发者的笔误，暂时没有意义
2. 是L2,由于 Metric Inner product 并不是langchian原码中列举出来的，所以实际在初始化时还是会变回欧式距离也就是L2，值越低，相似性越高
后续你如果使用内积得到了和欧式距离的对比结果，可以再交流交流哦

**Comment by zixiaotan21** [comment]
谢谢楼主，我明白了，Metric Inner product 估计确实是笔误，所以就是按你上面所说的，把61行里最后的 distance_strategy="METRIC_INNER_PRODUCT，删掉，这样就没有歧义了，对吧？

**Comment by zixiaotan21** [comment]
我大概想明白了：

1. 如果是vector_store = FAISS.load_local(vs_path, embeddings, normalize_L2=True) 最终加载的就是默认的L2距离。值越低，相似性越高。
2. 如果修改为vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True, distance_strategy="MAX_INNER_PRODUCT" ) 加载的应该是最大内积距离，也就是余弦相似度。值越高，相似性越高。

在langchain-chatchat的使用中，感觉使用法1, 知识库问答匹配知识的时候，总会匹配出很多不太相关的知识，想问问楼主有没有试过用2 的方法 采用内积的方式 去检索相似向量呀，我现在准备试试 对比一下效果~

**Comment by zixiaotan21** [comment]
尝试2 之后发现，若指定“[距离度量方式]”为"MAX_INNER_PRODUCT"，（内积/余弦相似度度量），会出现楼上一样的 UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT 报错，想问问这种情况楼主有遇到不？

**Comment by 1hfq** [comment]
大佬，太牛了，我也在搞这个faiss优化，看了你写的之后，感觉明白了许多，强

**Comment by 1hfq** [comment]
指定度量方式改为"MAX_INNER_PRODUCT"后，知识库问答就检索不到文档了，变成大语言模型自身解答了，不知道为什么。大佬，有解决的办法吗？求

**Comment by YeQiuO** [comment]
@zixiaotan21 您好，请问您试验后内积和L2的结果有什么区别呢？
