### ISSUE TITLE
[BUG] 知识库管理界面，设置的关键字不能保存

### ISSUE THREAD

**Issue by wobo-hydsoft-dragon** [chatchat-space/Langchain-Chatchat#3118]
**问题描述 / Problem Description**
无法使用知识库管理界面里的相关设置生效，如果查询关键字和匹配条数

**复现问题的步骤 / Steps to Reproduce**
1. 点击知识库管理界面
2. 输入查询关键字并回车
3. 点击对话界面
4. 再次点击知识库管理界面

**预期的结果 / Expected Result**
显示保留下来的之前的设置

**实际结果 / Actual Result**
显示为默认/初始设置

**环境信息 / Environment Information**
- langchain-Chatchat 版本/commit 号：([caf502d](https://github.com/chatchat-space/Langchain-Chatchat/commit/caf502d141ca3a544db55f1b4dd46d3594d8457d)) 
- 是否使用 Docker 部署（是/否）：No
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Azure-OpenAI
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： default
- 操作系统及版本 / Operating system and version: maxOS Sonoma 14.2.1 
- Python 版本 / Python version: 3.11.5
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

https://github.com/chatchat-space/Langchain-Chatchat/assets/105832642/888e10a1-65ef-46b9-ac8a-f118e7b7f41a

**Comment by litongyun233** [comment]
我也遇到相同的问题，期待解决！

**Comment by duyikang** [comment]
设置查询关键字不能生效原因是knowledge_base.py中keyword = st.text_input()未被其他变量引用，起作用
