### ISSUE TITLE
[BUG] python init_database.py --recreate-vs时报错

### ISSUE THREAD

**Issue by skywolf123** [chatchat-space/Langchain-Chatchat#3121]
**问题描述 / Problem Description**
python init_database.py --recreate-vs时报错

第一个问题：
(MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /None/resolve/main/tokenizer_config.json (Caused by SSLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for \'huggingface.co\'. (_ssl.c:1006)")))'), '(Request ID: 4826469f-6904-4873-a7c7-291a84614162)')

第二个问题：
None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

第三个问题：
('samples', 'test_files/langchain-ChatGLM_closed.jsonl', '从文件 samples/test_files/langchain-ChatGLM_closed.jsonl 加载文档时出错：jq package not found, please install it with `pip install jq`')

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Openai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Windows11
- Python 版本 / Python version: v3.11.8
- 其他相关环境信息 / Other relevant environment information: 
  - langchain版本：0.0.354. fastchat版本：0.2.35
  - 当前使用的分词器：ChineseRecursiveTextSplitter

**附加信息 / Additional Information**
不管是否翻墙都会报错

**Comment by skywolf123** [comment]
第三个问题我通过修改JSONLoader类实现了无需jq库，因为windows不支持安装jq库

**Comment by skywolf123** [comment]
第二个问题我查到是`server\knowledge_base\utils.py`文件中的`make_text_splitter`函数在执行`tokenizer = AutoTokenizer.from_pretrained(text_splitter_dict[splitter_name]["tokenizer_name_or_path"], trust_remote_code=True)`时报的异常，由于ChineseRecursiveTextSplitter的tokenizer_name_or_path是None，这该怎么办？

**Comment by limoou** [comment]
> 第三个问题我通过修改JSONLoader类实现了无需jq库，因为windows不支持安装jq库

可以上传代码么？我不知道如何修改，谢谢。

**Comment by lovepoy** [comment]
> 第三个问题我通过修改JSONLoader类实现了无需jq库，因为windows不支持安装jq库

请教一下是怎么改的呢  我也是window环境
