### ISSUE TITLE
调用百度千帆大模型平台，没有返回结果

### ISSUE THREAD

**Issue by WSDzju** [chatchat-space/Langchain-Chatchat#3122]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/147698475/63df3417-5eb1-474d-93d2-062cfcb7f76c)
 配置文件如下：
<img width="1191" alt="屏幕截图 2024-03-01 053134" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/147698475/3bb35f74-8b83-4cdf-810f-223a4f3e1e56">
看了 model_worker 文档 这里的 url或者version配置一个即可。 另外，这里是不是只要url填写正确，只要是千帆平台上的大模型都能调用？

**Comment by shanfasheng** [comment]
这个问题解决了吗？

**Comment by shanfasheng** [comment]
> _🤖_
> 
> 嘿，@WSDzju！很高兴再次见到你在这里提问 😜
> 
> 根据您的问题，我理解您想要知道在正确填写URL的情况下，是否可以调用千帆平台上的任何大模型，而不考虑版本配置。在Langchain-Chatchat的实现中，不是所有的大模型都可以被调用。能否调用一个模型取决于代码中定义的`MODEL_VERSIONS`字典，该字典将模型名称映射到它们各自的版本配置。如果一个模型的版本没有在`MODEL_VERSIONS`字典中列出，那么它就不能使用这个实现来调用。您可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/qianfan.py)查看相关的源代码。
> 
> 关于`MODEL_VERSIONS`字典的结构和内容，您可以参考以下代码片段：
> 
> ```python
> MODEL_VERSIONS = {
>     "ernie-bot-4": "completions_pro",
>     "ernie-bot": "completions",
>     "ernie-bot-turbo": "eb-instant",
>     "bloomz-7b": "bloomz_7b1",
>     "qianfan-bloomz-7b-c": "qianfan_bloomz_7b_compressed",
>     "llama2-7b-chat": "llama_2_7b",
>     "llama2-13b-chat": "llama_2_13b",
>     "llama2-70b-chat": "llama_2_70b",
>     "qianfan-llama2-ch-7b": "qianfan_chinese_llama_2_7b",
>     "chatglm2-6b-32k": "chatglm2_6b_32k",
>     "aquilachat-7b": "aquilachat_7b",
>     # "linly-llama2-ch-7b": "", # 暂未发布
>     # "linly-llama2-ch-13b": "", # 暂未发布
>     # "chatglm2-6b": "", # 暂未发布
>     # "chatglm2-6b-int4": "", # 暂未发布
>     # "falcon-7b": "", # 暂未发布
>     # "falcon-180b-chat": "", # 暂未发布
>     # "falcon-40b": "", # 暂未发布
>     # "rwkv4-world": "", # 暂未发布
>     # "rwkv5-world": "", # 暂未发布
>     # "rwkv4-pile-14b": "", # 暂未发布
>     # "rwkv4-raven-14b": "", # 暂未发布
>     # "open-llama-7b": "", # 暂未发布
>     # "dolly-12b": "", # 暂未发布
>     # "mpt-7b-instruct": "", # 暂未发布
>     # "mpt-30b-instruct": "", # 暂未发布
>     # "OA-Pythia-12B-SFT-4": "", # 暂未发布
>     # "xverse-13b": "", # 暂未发布
> 
>     # # 以下为企业测试，需要单独申请
>     # "flan-ul2": "",
>     # "Cerebras-GPT-6.7B": ""
>     # "Pythia-6.9B": ""
> }
> ```
> 
> 这个字典将模型名称映射到它们各自的版本标识符或代码。有些条目被注释掉了，表示这些模型还没有发布。您可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/qianfan.py)查看相关的源代码。
> 
> Langchain-Chatchat的代码库通过`ApiModelParams`类（继承自`ApiConfigParams`）使用URL和版本配置来调用千帆平台的模型。这个类包括`version`、`version_url`和`api_version`等可选字段，可以设置这些字段来配置模型版本和API调用的URL。配置参数通过`get_model_worker_config`基于`worker_name`加载，并可能被覆盖。这种机制允许动态配置API端点和模型版本，方便调用像千帆这样的平台上的不同模型。
> 
> `ApiModelWorker`类（继承自`BaseModelWorker`）在其操作中使用这些配置。例如，在通过`generate_stream_gate`方法生成响应时，它可以使用`ApiChatParams`实例（继承自`ApiModelParams`）的`version`字段来在API调用中指定模型版本。然而，在提供的代码片段中，API调用的实际实现（`do_chat`、`do_completion`、`do_embeddings`）是抽象的，表明使用`api_base_url`、`version`和其他配置来向千帆平台或任何其他API发出请求的具体逻辑将在子类或代码库的其他地方实现。
> 
> 总的来说，URL和版本的配置设计得很灵活，可以根据工作器名称动态加载，但是直接使用这些配置来调用千帆平台的模型的具体实现将在像`do_chat`这样的方法中实现，这些方法在提供的代码片段中没有详细说明。您可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/base.py)查看相关的源代码。
> 
> ## Sources
> * [server/model_workers/qianfan.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/qianfan.py)
> * [server/model_workers/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/base.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

这个看源码中的配置，都配了，还是报楼主截图的报错
