### ISSUE TITLE
能否使用MQTT协议完成对langchain的远程通讯？

### ISSUE THREAD

**Issue by 1838171762** [chatchat-space/Langchain-Chatchat#3125]
想让不同客户端的人都能访问本机的langchain，和chatgpt进行对话，使用MQTT获取用户的问题并返还给langchain的大语言模型，并将模型的回答通过MQTT再返还给用户，使用MQTT协议是否是一种可行的方案？

**Comment by zRzRzRzRzRzRzR** [comment]
没有写过，机器人的方案可以，目前是sse
