### ISSUE TITLE
怎样判断大模型回答是基于给定上下文的

### ISSUE THREAD

**Issue by ZTurboX** [chatchat-space/Langchain-Chatchat#3126]
怎样判断大模型回答是基于给定上下文的

**Comment by zRzRzRzRzRzRzR** [comment]
能看到参考链接呀，如果没有就是大模型自身回答

**Comment by ZTurboX** [comment]
> 能看到参考链接呀，如果没有就是大模型自身回答

就是想做个评价方法或者模型，并不是通过人工来看参考链接和大模型回答的正确性

**Comment by sevenandseven** [comment]
> 能看到参考链接呀，如果没有就是大模型自身回答

我想请问一下，我多次让大模型用知识检索功能生成一篇文章，怎么能保证整个文章的主题是一样的呢？
