### ISSUE TITLE
使用vllm怎么配置多卡并行推理

### ISSUE THREAD

**Issue by Wimeremce7** [chatchat-space/Langchain-Chatchat#3128]
我的配置如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.10.0-153.34.0.111.oe2203sp2.x86_64-x86_64-with-glibc2.34.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b-32k'] @ cuda
{'device': 'cuda',
 'enforce_eager': True,
 'gpus': '0,1,2',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'max_context_len_to_capture': 2048,
 'max_gpu_memory': '23GiB',
 'max_parallel_loading_workers': 5,
 'model_path': '/home/llm/chatglm3-6b-32k',
 'model_path_exists': True,
 'num_gpus': 3,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
==============================Langchain-Chatchat Configuration==============================
但是显示只有一张卡被使用，请问应该怎么配置
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/95208496/28049930-7a65-4904-925d-3e9bba3b983e)

**Comment by Wimeremce7** [comment]
试了还是不行，有具体配置信息吗

**Comment by tx-anin** [comment]
配置 configs/server_config.py 

        # model_worker多卡加载需要配置的参数
        "gpus": "0,1", #None, # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 2, # 使用GPU的数量
        "max_gpu_memory": "11GiB", # 每个GPU占用的最大显存

**Comment by elbadaernU404** [comment]
> 配置 configs/server_config.py
> 
> ```
>     # model_worker多卡加载需要配置的参数
>     "gpus": "0,1", #None, # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
>     "num_gpus": 2, # 使用GPU的数量
>     "max_gpu_memory": "11GiB", # 每个GPU占用的最大显存
> ```

server_config.py 和 startup.py都配置了相同的参数，启动界面参数打印是双卡，但是实际操作nvidia-smi还是单卡运行
```python
FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        "infer_turbo": "vllm",

        # # model_worker多卡加载需要配置的参数
        # "gpus": "0,1",  # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        # "num_gpus": 2,  # 使用GPU的数量
        # "max_gpu_memory": "22GiB",  # 每个GPU占用的最大显存
        # "max_parallel_loading_workers": 2,
        # "enforce_eager": False,
        # "max_context_len_to_capture": 2048,
        # "max_model_len": 2048

        # 以下为model_worker非常用参数，可根据需要配置
        # "load_8bit": False, # 开启8bit量化
        # "cpu_offloading": None,
        # "gptq_ckpt": None,
        # "gptq_wbits": 16,
        # "gptq_groupsize": -1,
        # "gptq_act_order": False,
        # "awq_ckpt": None,
        # "awq_wbits": 16,
        # "awq_groupsize": -1,
        # "model_names": LLM_MODELS,
        # "conv_template": None,
        # "limit_worker_concurrency": 5,
        # "stream_interval": 2,
        # "no_register": False,
        # "embed_in_truncate": False,

        # 以下为vllm_worker配置参数,注意使用vllm必须有gpu，仅在Linux测试通过

        # tokenizer = model_path # 如果tokenizer与model_path不一致在此处添加
        'tokenizer_mode': 'auto',
        'trust_remote_code': True,
        'download_dir': None,
        'load_format': 'auto',
        'dtype': 'auto',
        'seed': 0,
        'worker_use_ray': False,
        'pipeline_parallel_size': 1,
        'tensor_parallel_size': 1,
        'block_size': 16,
        'swap_space': 4,  # GiB
        'gpu_memory_utilization': 0.90,
        'max_num_batched_tokens': None,
        'max_num_seqs': 256,
        'disable_log_stats': False,
        'conv_template': None,
        'limit_worker_concurrency': 5,
        'no_register': False,
        'gpus': "0,1",
        'num_gpus': 2,
        'max_gpu_memory': "22GiB",  # 每个GPU占用的最大显存
        'engine_use_ray': False,
        'disable_log_requests': False,

        "max_parallel_loading_workers": 2,
        "enforce_eager": False,
        "max_context_len_to_capture": 2048,
        "max_model_len": 2048

    },
```

**Comment by tx-anin** [comment]
建议先 最少参数配置，server_config.py 中 

```
FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        "infer_turbo": False,

        # model_worker多卡加载需要配置的参数
        "gpus": "0,1", #None, # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 2, # 使用GPU的数量
        "max_gpu_memory": "11GiB", # 每个GPU占用的最大显存
```
其他参数都先隐藏

**Comment by elbadaernU404** [comment]
> 建议先 最少参数配置，server_config.py 中
> 
> ```
> FSCHAT_MODEL_WORKERS = {
>     # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
>     "default": {
>         "host": DEFAULT_BIND_HOST,
>         "port": 20002,
>         "device": LLM_DEVICE,
>         # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
>         # vllm对一些模型支持还不成熟，暂时默认关闭
>         "infer_turbo": False,
> 
>         # model_worker多卡加载需要配置的参数
>         "gpus": "0,1", #None, # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
>         "num_gpus": 2, # 使用GPU的数量
>         "max_gpu_memory": "11GiB", # 每个GPU占用的最大显存
> ```
> 
> 其他参数都先隐藏

`"infer_turbo": False`这样启动是没有问题的，但是改用vllm启动始终是单卡加载,不知道什么情况，请问有vllm多卡成功启动的相关配置吗？

**Comment by tx-anin** [comment]
我没用vllm，看看其他人有配置成功的

**Comment by elbadaernU404** [comment]
> 试了还是不行，有具体配置信息吗

https://github.com/chatchat-space/Langchain-Chatchat/issues/3202#issuecomment-1980491172
