### ISSUE TITLE
[help wanted] 如何提高加载文档的速度？

### ISSUE THREAD

**Issue by xiaohundun** [chatchat-space/Langchain-Chatchat#3130]
**问题描述 / Problem Description**

知识库文件夹下放了 85000 个 md 文件，使用 init_database --increment 导入知识库非常非常慢，最慢的是处理文件和分割，导入 pg 向量倒是还行，整个流程下来可能要三四个小时了，请问是否有提高速度的方法？只能单纯的提高ThreadPoolExecutor的线程数量么？

**Comment by shilei4260** [comment]
解决了吗
