### ISSUE TITLE
[BUG] 添加知识库文件doc,文件，向量化会失败，docx文件没有问题

### ISSUE THREAD

**Issue by yumu7777777** [chatchat-space/Langchain-Chatchat#3134]
**问题描述 / Problem Description**
[BUG] 添加知识库文件doc,文件，向量化会失败，docx文件没有问题
![lQLPJyJwfXpyQVvMvM0FN7C3qXdPN4ZKgwXQABzFvp0A_1335_188](https://github.com/chatchat-space/Langchain-Chatchat/assets/104643678/38db129a-d324-4bb4-a73b-399a6726be90)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs
5. 
2024-03-01 10:11:09,245 - utils.py[line:295] - INFO: RapidOCRDocLoader used for /home/someray/Langchain-Chatchat-0.2.10/knowledge_base/66e9d321-1db9-4fd9-ac2f-df992f41e94a_public/content/新建 DOC 文档.doc
2024-03-01 10:11:09,389 - utils.py[line:376] - ERROR: PackageNotFoundError: 从文件 66e9d321-1db9-4fd9-ac2f-df992f41e94a_public/新建 DOC 文档.doc 加载文档时出错：Package not found at '/home/someray/Langchain-Chatchat-0.2.10/knowledge_base/66e9d321-1db9-4fd9-ac2f-df992f41e94a_public/content/新建 DOC 文档.doc'
2024-03-01 10:11:09,406 - faiss_cache.py[line:92] - INFO: loading vector store in '66e9d321-1db9-4fd9-ac2f-df992f41e94a_public/vector_store/m3e-base' from disk.
/home/someray/miniconda3/envs/chatchat/lib/python3.10/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：V0.2.10
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： pg
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by yumu7777777** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104643678/40736652-8a5c-4121-ba7b-3e22997debc6)
配置没问题就是 ['.docx', '.doc']

**Comment by zRzRzRzRzRzRzR** [comment]
估计是lc的问题，这个估计暂时没办法

**Comment by yumu7777777** [comment]
您好，之前提到说降低lc版本试试，请问是这个吗？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104643678/8bd72cad-dc56-46ee-bf1a-92afb9b7dcb8)
有版本推荐吗

**Comment by Jan-jia** [comment]
> 您好，之前提到说降低lc版本试试，请问是这个吗？ ![image](https://private-user-images.githubusercontent.com/104643678/310717255-8bd72cad-dc56-46ee-bf1a-92afb9b7dcb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0NzA1OTEsIm5iZiI6MTcxMDQ3MDI5MSwicGF0aCI6Ii8xMDQ2NDM2NzgvMzEwNzE3MjU1LThiZDcyY2FkLWRjNTYtNDZlZS1iZjFhLTkyYWZiOWI3ZGNiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNVQwMjM4MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yzg3ZWZmODBlMjIxYTUxYzEyZDQ2YzFiNjNmZGY2ZWE1Zjc3NzdhMmQ1ZDgzN2FiYmE3OWJlOGQ3NjcwNjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MvENkzpb3Vz0qGeEoqoEuEWBw2F7vOYhp6SOArv3zWA) 有版本推荐吗
我也是doc文件会失败，请问解决了吗？
