### ISSUE TITLE
[FEATURE] 简洁阐述功能 / Concise description of the feature

### ISSUE THREAD

**Issue by mwang12345** [chatchat-space/Langchain-Chatchat#3139]
1.查询知识库时能否增加权限，当用户权限不足时，提示“对不起，您暂时无权访问”。
2.系统没有用户管理和登录功能，当前会话是什么意思，默认是default，如何配置新的会话，可以给不同的会话来配权限吗。

**Comment by zRzRzRzRzRzRzR** [comment]
不会做这功能，这个可以自己二次开发
