### ISSUE TITLE
[BUG] langchain-ChatGLM_closed.csv包含emoji会导致导入报错

### ISSUE THREAD

**Issue by skywolf123** [chatchat-space/Langchain-Chatchat#3144]
**问题描述 / Problem Description**
langchain-ChatGLM_closed.csv包含emoji 🤣会导致导入报错，删除🤣🤣🤣后可正常导入

**复现问题的步骤 / Steps to Reproduce**
执行python init_database.py --recreate-vs时报错，langchain-ChatGLM_closed.csv导入失败

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Openai
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Windows11
- Python 版本 / Python version: v3.11.8

**Comment by zRzRzRzRzRzRzR** [comment]
这个emoji为啥会报错，应该会因为找不到属于词表中的位置而被忽略呀

**Comment by skywolf123** [comment]
不明白为什么，我在初始化数据库的时候就会报错，自带的里面有两个csv文件，一个open一个closed，open那个没问题，closed这个怎么都过不了，我尝试复制内容到新建的csv文件里去就试出这个emoji会导致导入失败，删掉这三个emoji就好了，具体原因也就没调试了。

**Comment by skywolf123** [comment]
我查issues里面有个2342，好像跟我的现象一致

**Comment by liunux4odoo** [comment]
感谢反馈。
这可能是因为 emoji 属于 unstructured 不能处理的特殊字符。
我们将会保留这个内容作为测试，看以后新版 unstructured 是否会解决这个问题。
