### ISSUE TITLE
使用本地大模型时GPU显存一直慢慢增加

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#3146]
使用本地大模型时GPU显存一直慢慢增加，请问是什么原因？
我搜了下，说是用了  ConversationBufferWindowMemory  这个api，进行了上下文会话记忆所以会增加，但是这不是已经限制了最大数吗？ 那应该最多会停在某个值了，为什么还会继续增加呢？ 导致只能手动再重启服务释放资源，之前用openai框架加载模型没有出现这种情况，GPU占用一直稳定不会增加，有大佬解答下吗？ 感激

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/59902823/5c38e9be-4e0f-4d86-8efe-33bfe26d2863)

**Comment by xxWeiDG** [comment]
兄弟，最后怎么解决的呀
