### ISSUE TITLE
如何使用多卡部署，多个gpu

### ISSUE THREAD

**Issue by goudemaoningsir** [chatchat-space/Langchain-Chatchat#315]
机器上有多个gpu,如何全使用了

**Comment by imClumsyPanda** [comment]
默认就会利用accelerate实现多卡部署

三猫码士 ***@***.***>于2023年5月11日 周四11:19写道：

**Comment by fjwon** [comment]
同问

**Comment by zhubao315** [comment]
默认没安装 accelerate，多个GPU时，要把requirements.txt 中的注释去掉 
#accelerate~=0.18.0
