### ISSUE TITLE
启动成功了，但是请求api 的文档返回的是如下信息

### ISSUE THREAD

**Issue by griftt** [chatchat-space/Langchain-Chatchat#3153]
启动成功了，但是请求api文档页面返回了如下的错误信息：Invalid request url: /docs,补充一下，我访问web-ui是能正常打开的

**Comment by loveHao** [comment]
我也遇到一样的问题

**Comment by 302658980** [comment]
我也是 报错是
GET http://region-9.autodl.pro:43612/static-offline-docs/swagger-ui.css net::ERR_ABORTED 404 (Not Found)
docs:12 
       GET http://region-9.autodl.pro:43612/static-offline-docs/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
docs:15 Uncaught ReferenceError: SwaggerUIBundle is not defined
看起来是找不到css js

**Comment by New-King** [comment]
我也遇到这个问题了，请问你解决了吗？我使用dsw部署的，webui也是正常，但是 Chatchat  API  Server: http://127.0.0.1:7861   点进去就是Invalid request url: /docs  ，没有报错，响应就是这几个字符串

**Comment by chenxin03** [comment]
> 我也遇到这个问题了，请问你解决了吗？我使用dsw部署的，webui也是正常，但是 Chatchat API Server: http://127.0.0.1:7861 点进去就是Invalid request url: /docs ，没有报错，响应就是这几个字符串

一样 请问有找到解决方案吗

**Comment by New-King** [comment]
> > 我也遇到这个问题了，请问你解决了吗？我使用dsw部署的，webui也是正常，但是 Chatchat API Server: http://127.0.0.1:7861 点进去就是Invalid request url: /docs ，没有报错，响应就是这几个字符串
> 
> 一样 请问有找到解决方案吗
> 
> 如果是dsw部署可以试试我的解决办法 [#3435 (comment)](https://github.com/chatchat-space/Langchain-Chatchat/issues/3435#issuecomment-2008618078)

👍👍👍
