### ISSUE TITLE
想要将LLM模型更换为更小的本地模型，除了在model_config.py中添加以下字段，还需要什么操作

### ISSUE THREAD

**Issue by zzxb1** [chatchat-space/Langchain-Chatchat#3156]
"llm_model": {
        "ChatLM-mini-Chinese": "D:\models\ChatGLM3-6B\ChatLM-mini-Chinese",
}

**Comment by qqlww1987** [comment]
LLM_MODELS  里搞上你加的模型，然后你对应的模型有对应的依赖。装上然后试试看
