### ISSUE TITLE
[BUG] 开启vllm后，输入模型的知识库文本很长时，返回结果为空

### ISSUE THREAD

**Issue by Leo4zhou** [chatchat-space/Langchain-Chatchat#3159]
**问题描述 / Problem Description**
不开启vllm，知识库文本很长时，可以有正常返回，只是速度很慢。开启vllm后，速度会提升很多，但是知识库文本很长时，返回结果为空。控制台没有报错，就是马上打印出answer为空。
显卡用的是两张4090，显存占用都是21439MiB /  24564MiB。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：是
- 使用的模型：Qwen-14B-Chat
- 使用的 Embedding 模型：m3e-base
- 使用的向量库类型 ： faiss
- 操作系统及版本: ubuntu
- Python 版本: 3.10

**Comment by Leo4zhou** [comment]
> 你好 @Leo4zhou！很高兴再次看到你。希望一切都好！
> 
> 您好，Leo4zhou，
> 
> 关于您提到的问题，Langchain-Chatchat v0.2.10在启用vllm并且输入模型的知识库文本很长时返回空结果，可能与处理大量文本数据的限制或未针对非常长的文本优化的特定配置有关。然而，根据提供的上下文，`langchain-ChatGLM` GitHub issues中并没有直接提及或证据指向此行为的特定原因。
> 
> 没有明确的错误信息、系统配置或关于vllm（非常大的语言模型）如何实现或预期处理大知识库文本的具体细节，很难确定确切的原因。这种行为可能是由于模型设计的限制、文本预处理的问题，或者在提供的上下文中不明显的内存管理策略。
> 
> 关于vllm可以处理的知识库文本的最大长度，是由`MAX_TOKENS`变量决定的，如`search_knowledge_base_iter`函数中所见。然而，给定的上下文中并未提供`MAX_TOKENS`的实际值，这意味着无法从提供的信息中确定具体的最大长度（以token为单位）。
> 
> ```python
> max_tokens=MAX_TOKENS,
> ```
> 
> 源码：
> 
> * [server/agent/tools/search_knowledgebase_complex.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/search_knowledgebase_complex.py)
> 
> 如果您能提供更多关于您遇到的问题的信息，例如具体的错误消息、系统配置或vllm的实现细节，可能会有助于我们更好地理解和解决这个问题。
> 
> ## Sources
> * [knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.jsonl](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/knowledge_base/samples/content/test_files/langchain-ChatGLM_closed.jsonl)
> * [server/agent/tools/search_knowledgebase_complex.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/search_knowledgebase_complex.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

这里max_tokens 和 max_num_batched_tokens 都设置为了None

**Comment by Leo4zhou** [comment]
> ```python
> context_len
> ```

context_len 默认就是2048，没有改动过

**Comment by Leo4zhou** [comment]
> The issue you're experiencing with Langchain-Chatchat v0.2.10 returning an empty result when the `vllm` is enabled and a very long knowledge base text is inputted, despite having no error messages in the console and having set both `max_tokens` and `max_num_batched_tokens` to `None` in the `search_knowledge_base_iter` function, can be attributed to the handling of the `context` size before it is passed to the LLM for generating the response.
> 
> In the provided code snippet, the context for the LLM is constructed by concatenating the page content of documents found by the `search_docs` function:
> 
> ```python
> context = "\n".join([doc.page_content for doc in docs])
> ```
> 
> However, there are no checks or limitations applied to the size of the `context` string. Large knowledge base texts can result in a `context` that exceeds the maximum context size allowed by the underlying LLM model, even if `max_tokens` is set to `None`. Most LLMs, including those from OpenAI (e.g., GPT-3), have a maximum context size limit (in terms of tokens) that they can process in a single request. Exceeding this limit can lead to the model not generating any output, which could be why an empty result is observed.
> 
> The absence of error messages in the console suggests that the issue is not being caught or logged effectively. The code does not include explicit handling or logging for cases where the context size exceeds the model's limitations.
> 
> To address this issue, you could implement a mechanism to check the size of the `context` and split or truncate it as necessary before passing it to the LLM. Additionally, introducing logging for cases where truncation occurs or the context size exceeds known limits could help in diagnosing similar issues in the future. You can refer to the source code [here](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/knowledge_base_chat.py).
> 
> Regarding the maximum context size allowed by the underlying LLM model used in Langchain-Chatchat v0.2.10, it is 2048 tokens. This is specified in the `ApiModelWorker` class constructor with the parameter `context_len` set to 2048.
> 
> ```python
> def __init__(
>     self,
>     model_names: List[str],
>     controller_addr: str = None,
>     worker_addr: str = None,
>     context_len: int = 2048,
>     no_register: bool = False,
>     **kwargs,
> ):
> ```
> 
> You can refer to the source code [here](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/base.py).
> 
> ## Sources
> * [server/chat/knowledge_base_chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/knowledge_base_chat.py)
> * [server/model_workers/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/model_workers/base.py)
> 
> #### About Dosu

context_len 默认就是2048，没有改动过

**Comment by yuanxiaobin876-cn** [comment]
通过max_model_len参数和max_num_batched_tokends参数进行配置,设置到合适的值就可以解决了
