### ISSUE TITLE
启动报错AttributeError: 'Namespace' object has no attribute 'max_parallel_loading_workers'

### ISSUE THREAD

**Issue by rabum** [chatchat-space/Langchain-Chatchat#3160]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58140899/b505a2b7-4470-468d-a66c-5918148488ef)

**Comment by rabum** [comment]
我把vllm关了就好了，之前用qwen-72b-int4都支持vllm，怎么14b-chat就不行呢

**Comment by Andy1018** [comment]
这个配置在哪关闭？另外问下怎么开启单机多卡模式？
