### ISSUE TITLE
[BUG] 知识库问答，知识库有匹配结果，但用模型的回答或者返回无法回答该问题

### ISSUE THREAD

**Issue by liangpn** [chatchat-space/Langchain-Chatchat#3162]
**问题描述 / Problem Description**
知识库问答，知识库有匹配结果，但用模型的回答或者返回无法回答该问题

**预期的结果 / Expected Result**
应该是用知识库匹配结果来回答

**实际结果 / Actual Result**
但用了模型的回答或者返回无法回答该问题

**环境信息 / Environment Information**
- langchain-Chatchat 版本/commit 号：v2.0.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型 ：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 : CentOS Linux release 7.5.1804 (Core) 
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 :

**附加信息 / Additional Information**
能不能如果有匹配结果，是使用匹配结果，而不是用模型的回复。

**Comment by zRzRzRzRzRzRzR** [comment]
模型请求错误了，查询一下是不是填的token超过了4096

**Comment by liangpn** [comment]
> 模型请求错误了，查询一下是不是填的token超过了4096

如何测试打印这个token数？
