### ISSUE TITLE
启动程序后，无法打开网页版，应该从哪些方面去排查问题

### ISSUE THREAD

**Issue by zzxb1** [chatchat-space/Langchain-Chatchat#3166]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/157022515/5b4bb682-7c26-418c-bd72-fec2017e6fa9)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/157022515/1c562a3b-577d-442b-903a-d09f4e657249)

**Comment by CRonaldo1997** [comment]
我把服务器防火墙关了就好了：
service firewalld stop
