### ISSUE TITLE
关于swagger空白问题，重新下载swagger-ui-bundle.js即可

### ISSUE THREAD

**Issue by mygcdr** [chatchat-space/Langchain-Chatchat#3167]
关于swagger空白页面，控制台报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/131455436/aa7cb126-42ee-41eb-baa8-38fc66b0ae65)

```
Uncaught SyntaxError: Unexpected identifier 'LinkElement' (at swagger-ui-bundle.js:8:494194)
docs:15  Uncaught ReferenceError: SwaggerUIBundle is not defined
    at docs:15:16
```

前往
`https://github.com/swagger-api/swagger-ui/tree/master/dist`
重新下载
swagger-ui-bundle.js和css即可，但是样式会有问题
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/131455436/84de7976-aade-4df6-854f-e5642c8684d6)

**Comment by mygcdr** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/131455436/00b6f61f-5ed5-4bad-ba9d-106fc7a062b6)
刷新一下又好了

**Comment by huiyuanaiya** [comment]
还是不行,重新替换了依旧是空白的

**Comment by filefi** [comment]
> 前往
https://github.com/swagger-api/swagger-ui/tree/master/dist
重新下载
swagger-ui-bundle.js和css即可

same issue, solved. thx.
