### ISSUE TITLE
多用户并发参数在哪里设置，单机部署2人以上使用会报错

### ISSUE THREAD

**Issue by cwqJim2023** [chatchat-space/Langchain-Chatchat#3168]
问题描述：
1. chatglm3-6B+本地知识库，知识库文档不超过300条问答对
2. 内存256，显存48G
3. 超过1个用户在前端页面点击查询知识库，会报错如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/146075381/0a2f9d26-67d8-4312-9a89-ecbb8107a6b3)
4.如何设置多个用的并发

**Comment by zRzRzRzRzRzRzR** [comment]
框架没做并发

**Comment by Robert-Hopkins** [comment]
那到底能不能多用户同时使用呢

**Comment by ATP-BME** [comment]
同问

**Comment by ShawnHoo7256** [comment]
同时有这个需求。

**Comment by zixiaotan21** [comment]
同问，想问问langchain-chatchat 支持并发吗

**Comment by tankGe** [comment]
> 框架没做并发

2.10版本也没有做并发吗？
