### ISSUE TITLE
[BUG] startup.py无法启动

### ISSUE THREAD

**Issue by HhhBbWw** [chatchat-space/Langchain-Chatchat#3169]
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/162102157/e01959d5-654e-4a67-a0a6-be0e74e655df)

使用Docker run一键运行时，发生如上的问题，模型加载到一半不动了。（启动的命令是Readme中给的：docker run -d --gpus all -p 80:8501 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.7）我是使用docker run命令下载完之后，
使用WSL运行python startup.py -a时，出现过同样的问题。
请问可能是什么原因？

**Comment by zRzRzRzRzRzRzR** [comment]
配置不够
