### ISSUE TITLE
[BUG] 知识库管理使用milvus上传文档报错

### ISSUE THREAD

**Issue by jiyang2024** [chatchat-space/Langchain-Chatchat#3174]
问题描述 
部署完成后，使用默认的向量库faiss进行上传文档成功，然后本地部署了milvus向量库，在知识库管理新建milvus向量库成功，往milvus向量库中添加doc文档报错。

1、部署完成后，使用faiss没有问题。
2、启用milvus向量库，修改了configs/kb_config.py的值DEFAULT_VS_TYPE = "milvus"和配置milvus信息：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/161665612/3355ef83-06ef-43b5-8a79-60c723d6ab68)
milvus可以正常访问。
3、通过python startup.py -a重启后，往milvus添加文档，报错，错误信息如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/161665612/3a4d7c56-29c5-4d4b-8394-0ebc48d110f0)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/161665612/1aa235d8-2059-457e-a27e-56e2ddce5aa0)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/161665612/4146c087-9eaa-4965-b915-c7440c0efa3e)

初始化过faiss向量库，是否还是需要初始化一次milvus向量库？

**Comment by hollowdjj** [comment]
没有提供id
