### ISSUE TITLE
請問 langchain-chatchat 有支持 NVlink 運行多張 GPU 卡片嗎?

### ISSUE THREAD

**Issue by alanywlee** [chatchat-space/Langchain-Chatchat#3176]
我有兩張 RTX-A5000 用 NV-link 連接，但是我即使是是修改 config/server_config.conf 使用 vllm 模式，也還是只能用一張卡的 GPU RAM，好奇想確認一下，是否是我不會配置，還是 chatchat 0.2.7 版還沒有支持 NV-link 多卡使用? 或是要更新的版本才會有支持? 不知有沒有用過的先進可以分享一下

**Comment by zRzRzRzRzRzRzR** [comment]
等0.3.x后可以支持，现在都是transformers读入的方式，被封装好了
