### ISSUE TITLE
prompt template的配置说明

### ISSUE THREAD

**Issue by Zhaobo0119** [chatchat-space/Langchain-Chatchat#3181]
**功能描述 / Feature Description**
请问哪里有关于prompt_config.py中，prompt模板的详细使用，我在 PROMPT_TEMPLATES 中的 llm_chat设置了自定义prompt，效果似乎不太理想

**Comment by zRzRzRzRzRzRzR** [comment]
记得按照 langchain的格式，继承Langchain的写法，因此不在做说明
