### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Bobby-Zheng** [chatchat-space/Langchain-Chatchat#3186]
**问题描述 / Problem Description**
Traceback (most recent call last):
  File "F:\ProgramData\anaconda3\envs\soaring-dragon\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "E:\4_Python_workspace\SoaringDragon\webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
  File "E:\4_Python_workspace\SoaringDragon\webui_pages\knowledge_base\knowledge_base.py", line 335, in knowledge_base_page
    data = [
  File "E:\4_Python_workspace\SoaringDragon\webui_pages\knowledge_base\knowledge_base.py", line 336, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
TypeError: string indices must be integers

**复现问题的步骤 / Steps to Reproduce**
背景：我选用的Milvus向量库
现象：上传完知识库文件，加载到向量库后，调用/knowledge_base/search_docs加载页面就报错了。
初步定位：这个search_docs返回的元素不是json
data = kb.list_docs(file_name=file_name, metadata=metadata)
如下是前端输出日志：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/96476912/f7999db2-f4fc-4780-b532-cb466b76bdca)

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by xiaohundun** [comment]
一样的问题

**Comment by aben1900** [comment]
in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
TypeError: string indices must be integers, not 'str'
不知怎么处理，有人成功处理了吗，这么明显的出错，完成跑不起来。。
