### ISSUE TITLE
chatchat是否支持长文本总结？

### ISSUE THREAD

**Issue by cauwulixuan** [chatchat-space/Langchain-Chatchat#3193]
本地知识库对于小文本/多文本知识检索是没问题的。
我的问题是：如果模型本身支持的序列长度为4k，能否用这个项目做到长篇小说(几十万字)的阅读理解和总结？或者langchain能否做到这一步？

**Comment by zRzRzRzRzRzRzR** [comment]
langchain行，我们不支持
