### ISSUE TITLE
向量库使用 pg，导入文件之后 UI 查看单条详情会报错 string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by xiaohundun** [chatchat-space/Langchain-Chatchat#3199]
**问题描述 / Problem Description**
向量库使用 pg，导入文件之后 UI 查看单条详情会报错 string indices must be integers, not 'str'

**复现问题的步骤 / Steps to Reproduce**

**预期的结果 / Expected Result**

**实际结果 / Actual Result**
```
TypeError: string indices must be integers, not 'str'
Traceback:
File "/home/admin1/.pyenv/versions/3.11.7/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/home/admin1/Langchain-Chatchat/webui.py", line 64, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "/home/admin1/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 328, in knowledge_base_page
    data = [
           ^
File "/home/admin1/Langchain-Chatchat/webui_pages/knowledge_base/knowledge_base.py", line 329, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),
                         ~^^^^^^
```
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： pg_vector
- 操作系统及版本 / Operating system and version: Ubuntu
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by xiaohundun** [comment]
<img width="750" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/38812912/d09009da-357b-4dec-94b9-68f14aecc590">

**Comment by xiaohundun** [comment]
same as https://github.com/chatchat-space/Langchain-Chatchat/issues/3186

**Comment by xxWeiDG** [comment]
兄弟，你最后是怎么解决的啊

**Comment by Aikoin** [comment]
同问，我用的默认的faiss，在文件数不多的时候没问题，上传了600多个pdf重建之后就也出现了这个问题

**Comment by xixia03** [comment]
一样，使用pg数据库时，上传json和docx都遇到该问题

**Comment by ajiader** [comment]
我也遇到了

**Comment by Wangzhongxi** [comment]
将上传的文档添加到向量库（milvus）遇到类似的错误了
TypeError: string indices must be integers
怎么解决呀

**Comment by lzh1998-jansen** [comment]
怎么更换成pg数据库呀，要先安装postgresql吗，还有这个应该如何配置，"pg": {
        "connection_uri": "postgresql://postgres:postgres@127.0.0.1:5432/langchain_chatchat",
    }

**Comment by xiaohundun** [comment]
> 兄弟，你最后是怎么解决的啊

没有解决，这个问题提的人太多了

**Comment by ftrako** [comment]
把docs日志打印出来，大概率是因为docs没有获取到数据导致 for i, x in enumerate(docs) 中的x数据不是{}，所以你查下search_docs接口

**Comment by nilin1998** [comment]
> > 兄弟，你最后是怎么解决的啊
> 
> 没有解决，这个问题提的人太多了

请问这个问题您最后解决了嘛

**Comment by aben1900** [comment]
这个问题解决了吗，有兄弟大哥搞定了吗，any one fix this bug??i meet the same bug
