### ISSUE TITLE
[BUG] vllm多卡启动显示成功，但是实际上只有一张显卡被占用

### ISSUE THREAD

**Issue by elbadaernU404** [chatchat-space/Langchain-Chatchat#3202]
**问题描述 / Problem Description**
在`server_config.py`中配置`"infer_turbo": "vllm"`，成功启动项目但是控制台执行`nvidia-smi`显示仅单卡运行

我控制台输出的环境配置如下：
```
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b'] @ cuda
{'block_size': 16,
 'conv_template': None,
 'device': 'cuda',
 'disable_log_requests': False,
 'disable_log_stats': False,
 'download_dir': None,
 'dtype': 'auto',
 'enforce_eager': False,
 'engine_use_ray': False,
 'gpu_memory_utilization': 0.9,
 'gpus': '0,1',
 'host': '0.0.0.0',
 'infer_turbo': 'vllm',
 'limit_worker_concurrency': 5,
 'load_format': 'auto',
 'max_context_len_to_capture': 2048,
 'max_gpu_memory': '22GiB',
 'max_model_len': 2048,
 'max_num_batched_tokens': None,
 'max_num_seqs': 256,
 'max_parallel_loading_workers': 2,
 'model_path': '/root/huggingface/chatglm2-6b',
 'model_path_exists': True,
 'no_register': False,
 'num_gpus': 2,
 'pipeline_parallel_size': 1,
 'port': 20002,
 'seed': 0,
 'swap_space': 4,
 'tensor_parallel_size': 1,
 'tokenizer_mode': 'auto',
 'trust_remote_code': True,
 'worker_use_ray': False}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda


服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================
```
对应`server_config.py`中的配置如下
```python
FSCHAT_MODEL_WORKERS = {
    # 所有模型共用的默认配置，可在模型专项配置中进行覆盖。
    "default": {
        "host": DEFAULT_BIND_HOST,
        "port": 20002,
        "device": LLM_DEVICE,
        # False,'vllm',使用的推理加速框架,使用vllm如果出现HuggingFace通信问题，参见doc/FAQ
        # vllm对一些模型支持还不成熟，暂时默认关闭
        "infer_turbo": "vllm",

        # # model_worker多卡加载需要配置的参数
        "gpus": "0,1",  # 使用的GPU，以str的格式指定，如"0,1"，如失效请使用CUDA_VISIBLE_DEVICES="0,1"等形式指定
        "num_gpus": 2,  # 使用GPU的数量
        "max_gpu_memory": "22GiB",  # 每个GPU占用的最大显存
        # "max_parallel_loading_workers": 2,
        # "enforce_eager": False,
        # "max_context_len_to_capture": 2048,
        # "max_model_len": 2048

        # 以下为model_worker非常用参数，可根据需要配置
        # "load_8bit": False, # 开启8bit量化
        # "cpu_offloading": None,
        # "gptq_ckpt": None,
        # "gptq_wbits": 16,
        # "gptq_groupsize": -1,
        # "gptq_act_order": False,
        # "awq_ckpt": None,
        # "awq_wbits": 16,
        # "awq_groupsize": -1,
        # "model_names": LLM_MODELS,
        # "conv_template": None,
        # "limit_worker_concurrency": 5,
        # "stream_interval": 2,
        # "no_register": False,
        # "embed_in_truncate": False,

        # 以下为vllm_worker配置参数,注意使用vllm必须有gpu，仅在Linux测试通过

        # tokenizer = model_path # 如果tokenizer与model_path不一致在此处添加
        'tokenizer_mode': 'auto',
        'trust_remote_code': True,
        'download_dir': None,
        'load_format': 'auto',
        'dtype': 'auto',
        'seed': 0,
        'worker_use_ray': False,
        'pipeline_parallel_size': 1,
        'tensor_parallel_size': 1,
        'block_size': 16,
        'swap_space': 4,  # GiB
        'gpu_memory_utilization': 0.90,
        'max_num_batched_tokens': None,
        'max_num_seqs': 256,
        'disable_log_stats': False,
        'conv_template': None,
        'limit_worker_concurrency': 5,
        'no_register': False,
        # 'gpus': "0,1",
        # 'num_gpus': 2,
        # 'max_gpu_memory': "22GiB",  # 每个GPU占用的最大显存
        'engine_use_ray': False,
        'disable_log_requests': False,

        "max_parallel_loading_workers": 2,
        "enforce_eager": False,
        "max_context_len_to_capture": 2048,
        "max_model_len": 2048

    },
```
启动方式：`CUDA_VISIBLE_DEVICES="0,1" python startup.py -a`

**Comment by elbadaernU404** [comment]
看了下源码，目前的解决方案：
在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
```python
'tensor_parallel_size': 2,
```
再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）

**Comment by Wimeremce7** [comment]
> 看了下源码，目前的解决方案： 在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
> 
> ```python
> 'tensor_parallel_size': 2,
> ```
> 
> 再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）

这样是可以的吗

**Comment by Wimeremce7** [comment]
> > > 看了下源码，目前的解决方案： 在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
> > > ```python
> > > 'tensor_parallel_size': 2,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）
> > 
> > 
> > 这样是可以的吗
> 
> 我测试了一下成功加载到双卡了，vllm的参数`num_gpus`本身在代码里最终会被同步给`tensor_parallel_size`这个参数，直接修改就好了

我试了下也加载成功了，但是不是共担显存的，是两个显卡都跑满了

**Comment by elbadaernU404** [comment]
> > > > 看了下源码，目前的解决方案： 在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
> > > > ```python
> > > > 'tensor_parallel_size': 2,
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）
> > > 
> > > 
> > > 这样是可以的吗
> > 
> > 
> > 我测试了一下成功加载到双卡了，vllm的参数`num_gpus`本身在代码里最终会被同步给`tensor_parallel_size`这个参数，直接修改就好了
> 
> 我试了下也加载成功了，但是不是共担显存的，是两个显卡都跑满了

gpu_memory_utilization这个参数默认给了0.9，两张卡都使用了90%，我实际测试50个并发会排队，但目前还未发生OOM

**Comment by Wimeremce7** [comment]
> > > > > 看了下源码，目前的解决方案： 在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
> > > > > ```python
> > > > > 'tensor_parallel_size': 2,
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > 再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）
> > > > 
> > > > 
> > > > 这样是可以的吗
> > > 
> > > 
> > > 我测试了一下成功加载到双卡了，vllm的参数`num_gpus`本身在代码里最终会被同步给`tensor_parallel_size`这个参数，直接修改就好了
> > 
> > 
> > 我试了下也加载成功了，但是不是共担显存的，是两个显卡都跑满了
> 
> gpu_memory_utilization这个参数默认给了0.9，两张卡都使用了90%，我实际测试50个并发会排队，但目前还未发生OOM

所以实际vllm是可以共担显存的是吗？比如我有一个需要40g显存的模型，我有两张24g显存的显卡，使用vllm可以跑起来吗？

**Comment by elbadaernU404** [comment]
> > > > > > 看了下源码，目前的解决方案： 在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
> > > > > > ```python
> > > > > > 'tensor_parallel_size': 2,
> > > > > > ```
> > > > > > 
> > > > > > 
> > > > > >     
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >       
> > > > > >     
> > > > > > 
> > > > > >     
> > > > > >   
> > > > > > 再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）
> > > > > 
> > > > > 
> > > > > 这样是可以的吗
> > > > 
> > > > 
> > > > 我测试了一下成功加载到双卡了，vllm的参数`num_gpus`本身在代码里最终会被同步给`tensor_parallel_size`这个参数，直接修改就好了
> > > 
> > > 
> > > 我试了下也加载成功了，但是不是共担显存的，是两个显卡都跑满了
> > 
> > 
> > gpu_memory_utilization这个参数默认给了0.9，两张卡都使用了90%，我实际测试50个并发会排队，但目前还未发生OOM
> 
> 所以实际vllm是可以共担显存的是吗？比如我有一个需要40g显存的模型，我有两张24g显存的显卡，使用vllm可以跑起来吗？

应该是共享的，单卡vllm带不动baichuan2-13b，但是双卡测了没有问题

**Comment by Wimeremce7** [comment]
> > > > > > > 看了下源码，目前的解决方案： 在`server_config.py`文件中，将vllm配置中`tensor_parallel_size`手动修改为显卡数量，例如
> > > > > > > ```python
> > > > > > > 'tensor_parallel_size': 2,
> > > > > > > ```
> > > > > > > 
> > > > > > > 
> > > > > > >     
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >       
> > > > > > >     
> > > > > > > 
> > > > > > >     
> > > > > > >   
> > > > > > > 再将vllm包降级为0.2.6（0.2.7vllm会报错`NotImplementedError: max_concurrent_workers is not supported yet.`）
> > > > > > 
> > > > > > 
> > > > > > 这样是可以的吗
> > > > > 
> > > > > 
> > > > > 我测试了一下成功加载到双卡了，vllm的参数`num_gpus`本身在代码里最终会被同步给`tensor_parallel_size`这个参数，直接修改就好了
> > > > 
> > > > 
> > > > 我试了下也加载成功了，但是不是共担显存的，是两个显卡都跑满了
> > > 
> > > 
> > > gpu_memory_utilization这个参数默认给了0.9，两张卡都使用了90%，我实际测试50个并发会排队，但目前还未发生OOM
> > 
> > 
> > 所以实际vllm是可以共担显存的是吗？比如我有一个需要40g显存的模型，我有两张24g显存的显卡，使用vllm可以跑起来吗？
> 
> 应该是共享的，单卡vllm带不动baichuan2-13b，但是双卡测了没有问题

好的，谢谢

**Comment by Andy1018** [comment]
@elbadaernU404 非常感谢，按照上述解决方案可以用vllm模式启动，有个问题咨询下，vllm模式启动的模型是不是推理能力下降，而且问问题有时候会出现不回答或回答一半的情况。
sever_config.py里面有哪些配置影响吗？

**Comment by elbadaernU404** [comment]
> @elbadaernU404 非常感谢，按照上述解决方案可以用vllm模式启动，有个问题咨询下，vllm模式启动的模型是不是推理能力下降，而且问问题有时候会出现不回答或回答一半的情况。 sever_config.py里面有哪些配置影响吗？

vllm是从显存出发去做优化的，模型被分层提供给GPU，中间可能出现问题，只支持linux和部分模型。配置文件我没有挨个测过，可以参考这个博客调试一下https://blog.51cto.com/u_15854304/9863338
