### ISSUE TITLE
[BUG] 搜索知识库search_docs的文件名称查询，document里边的metadata会返回多字键值对，导致接口返回值转json的时候报错

### ISSUE THREAD

**Issue by congziqi** [chatchat-space/Langchain-Chatchat#3209]
**问题描述 / Problem Description**
[BUG] milvus查询没有返回id，导致知识库管理查看文件内文档列表报错

TypeError: string indices must be integers
Traceback:
File "/usr/local/lib/python3.10/dist-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
File "/chatGLM/webui.py", line 85, in <module>
    pages[selected_page]["func"](api=api, is_lite=is_lite)
File "/chatGLM/webui_pages/knowledge_base/knowledge_base.py", line 341, in knowledge_base_page
    data = [
File "/chatGLM/webui_pages/knowledge_base/knowledge_base.py", line 342, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),

**复现问题的步骤 / Steps to Reproduce**

点击 知识库管理-选择某一个文档-下边显示报错

File "/chatGLM/webui_pages/knowledge_base/knowledge_base.py", line 342, in <listcomp>
    {"seq": i + 1, "id": x["id"], "page_content": x["page_content"], "source": x["metadata"].get("source"),

这个x["id"]，id是null，调search_docs接口也能看到返回的id是null。
kb_doc_api.py里的search_docs方法，
第42行 data = [DocumentWithVSId(**x[0].dict(), score=x[1], id=x[0].metadata.get("id")) for x in docs] 这句里边的id=x[0].metadata.get("id")，metadata里边id是null。

好像是因为milvus_kb_service.py的do_search方法，
第73行        docs = self.milvus.similarity_search_with_score_by_vector(embeddings, top_k)，这个返回内容里边metadata好像就是没有id。

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.10 
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-7B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus 
- 操作系统及版本 / Operating system and version: 
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Aikoin** [comment]
我用faiss也突然出现了这个问题（某次上传了700个文档后）

**Comment by Aikoin** [comment]
> 找到问题的真正原因了，search_docs的根据file_name名称查询会调用base.py的list_docs，在这个返回的list[DocumentWithVSId]中， metadata这个字典里有pk，vector，source这3个键值对，然后接口返回结果转json的时候就报错了。 一种方案是把metadata里只保留一个键值对，在 base.py的list_docs方法里 doc_info = self.get_doc_by_ids([x["id"]])[0] if doc_info is not None: doc_info.metadata.pop("pk") # 删掉多的pk doc_info.metadata.pop("vector") # 删掉多的vector 另一个方案就是看看转json的时候怎么给处理一下


我这边metadata好像是source和id诶
