### ISSUE TITLE
[BUG] 知识库 上传csv，“单段文本最大长度” 不起作用 

### ISSUE THREAD

**Issue by cooller111** [chatchat-space/Langchain-Chatchat#3212]
**问题描述 / Problem Description**
知识库 上传csv，设置“单段文本最大长度”  250， 相邻文本重合长度50，
<img width="560" alt="1709746074135" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/141322861/ee28b08f-1a07-419c-bc7b-d81921b91bec">

但是不起作用，csv每一行的所有内容，被分到的一段（远超过250文本）

这里csv有12行数据，结果分为12段
<img width="579" alt="1709746104239" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/141322861/97a5bac1-e46a-48f0-9ba1-babb3671a7d4">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：QWwen
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: ubuntu22.04
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**Comment by 545089467** [comment]
同样遇到了这个错误，chunk_size无效了

**Comment by zRzRzRzRzRzRzR** [comment]
csv没有chunksize是根据单元格一行一个chunk的
