### ISSUE TITLE
pdfloader为什么要加图片尺寸检测？

### ISSUE THREAD

**Issue by jinceon** [chatchat-space/Langchain-Chatchat#3214]
https://github.com/chatchat-space/Langchain-Chatchat/blob/021d635af0137a3ab5f896b5cbfdec1afd4819bf/document_loaders/mypdfloader.py#L55

tests/samples/orc_test.pdf里的图片直接被continue过去了。

pdf文件里的内容：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1641265/acaab914-a6fd-41d9-850d-a7861311fd51)

开启图片尺寸阈值检测后的结果：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1641265/bb262013-af9a-4efe-a5d7-73ac39e1831b)

注释掉图片尺寸阈值检测后的结果：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1641265/8dfa2fa5-7ab0-427a-8ecd-adf2f0d10eae)

**Comment by Nancy7zt** [comment]
你好，请问有人遇到过 cannot import name 'PDF_OCR_THRESHOLD' from 'configs'
