### ISSUE TITLE
未找到相关文档,该回答为大模型自身能力解答！ 

### ISSUE THREAD

**Issue by jiasongyuan** [chatchat-space/Langchain-Chatchat#3215]
上传了一个1.1M的pdf，然后去问答，一直说找不到文档
用简洁明了的语言描述这个问题 / 未找到相关文档,该回答为大模型自身能力解答！

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python startup -a
3. 点击文本对话
4. 上传文件
5. 问题出现任务对话一直搜索不到文档

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：chatglm3-6b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5 @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统：Linux-5.15.0-94-generic-x86_64-with-glibc2.35.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by dingziyang2022** [comment]
我也遇到了这个问题，我想知道你是如何解决的

**Comment by ReverseSystem001** [comment]
> 我也遇到了这个问题，我想知道你是如何解决的

哥们，你怎么解决的
