### ISSUE TITLE
多卡推理模型回复乱码

### ISSUE THREAD

**Issue by Wimeremce7** [chatchat-space/Langchain-Chatchat#3217]
**问题描述 / Problem Description**
使用多张卡共担显存时，回复乱码

**环境信息 / Environment Information**
- langchain-chatchat版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B-32k 、Qwen-72B-Int4-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu 20.04、openeuler 22.04 都试过不行
- Python 版本 / Python version: 3.11、3.10、3.9 都试过了
- 其他相关环境信息 / Other relevant environment information:  4090*3  cuda 12.1

首先回复界面是：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/95208496/562bebf4-bfb8-4c67-9d9a-aeabe7ac54cd)
控制台界面是：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/95208496/adc30a7d-6f42-4da2-9a5d-28747f5a418b)

server_config.py的配置是：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/95208496/32fcd4cf-029c-4349-8224-4fdbbffe61ba)
只改动了这块
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/95208496/1e893644-1b88-4ee7-b291-0de5c36de054)

麻烦帮忙看下是怎么回事，需要修改哪些配置

**Comment by Wimeremce7** [comment]
单张卡没问题

**Comment by Wimeremce7** [comment]
有遇到这个情况的没？使用vllm多卡是可以的，fschat多卡就是乱码

**Comment by hyxrpk** [comment]
同样遇到该情况+1，多卡部署要不就乱码或者后端报错

**Comment by Zephyr69** [comment]
同样这个情况，官方docker部署。

但是在wsl2+cu118里面fschat多卡就正常

**Comment by zRzRzRzRzRzRzR** [comment]
用vllm作为后端
