### ISSUE TITLE
怎样访问docker中部署的langchain？

### ISSUE THREAD

**Issue by HhhBbWw** [chatchat-space/Langchain-Chatchat#3218]
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/162102157/d352df14-bea7-4db7-b2ec-452093671a65)

使用readme中给的docker命令：docker run -it -d --gpus all -p 8080:80 registry.cn-beijing.aliyuncs.com/chatchat/chatchat:0.2.7 /bin/bash 
运行后查看docker ip地址为172.17.0.3
浏览器中输入172.17.0.3:8080，未能成功访问。
请问其中问题可能出在哪？

**Comment by Tim-Saijun** [comment]
`-p 8080:80`意味着将docker的8080端口映射到了本地的80端口，因此你应该访问http://127.0.0.1:8080
