### ISSUE TITLE
匹配结果中的文件直接在线预览

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#3220]
匹配结果中包含文件，点击文件后，自动下载。下载后再打开比较麻烦，怎样可以做到点击匹配结果中的pdf文件，立马在浏览器中打开进行预览

**Comment by HuntZhaozq** [comment]
请问除了这个方法还有别的设置可以进行问答的出处文件点击后在浏览器内预览吗？ @dosu-bot

**Comment by qianma819** [comment]
if os.path.exists(kb_file.filepath):
            print("ppppppppppppppppp")
            print(kb_file.filename)
            response = FileResponse(
                path=kb_file.filepath,
                media_type="application/pdf",
                filename=kb_file.filename,
                #media_type="multipart/form-data",
                
                #content_disposition_type=content_disposition_type,
                #headers={"Content-Type":"application/pdf"}
            )
            response.headers["Content-Disposition"]=f"inline;filename={kb_file.filename}"
            return response
这样修改后pdf文件可以在线预览了

**Comment by HuntZhaozq** [comment]
@qianma819 会出现error: latin-1 codec can't encode characters in posistion 16-24: ordinal not in range(256)，还有请问这个设置能预览doc吗

**Comment by qianma819** [comment]
doc没试过，因为我们所有资料都转成了pdf。doc导入有时候都会失败，你可以试试

**Comment by HuntZhaozq** [comment]
修改后，有的pdf可以直接预览了，但是有的pdf还是会直接下载，请问你有遇到这个情况吗？应该如何解决？ @qianma819

**Comment by qianma819** [comment]
这个情况没遇到，遇到的是
{
    "code": 500,
    "msg": "【ポスコン】KnowHow共有内容一覧11.pdf 读取文件失败，错误信息是：'latin-1' codec can't encode characters in position 16-21: ordinal not in range(256)",
    "data": null
}这样的错误。但是直接访问原文件却没有问题。蛋疼

**Comment by HuntZhaozq** [comment]
这个问题是因为header，可以把这个response.headers["Content-Disposition"]=f"inline;filename={kb_file.filename}"去掉

**Comment by qianma819** [comment]
什么？去掉了我们就只能下载无法在线预览了呀

**Comment by HuntZhaozq** [comment]
可以试试这个
```
import os
from fastapi import Query, Response
from fastapi.responses import FileResponse
from your_module_name import KBServiceFactory, KnowledgeFile, BaseResponse, validate_kb_name

def download_doc(
        knowledge_base_name: str = Query(..., description="知识库名称", examples=["samples"]),
        file_name: str = Query(..., description="文件名称", examples=["test.txt"]),
        preview: bool = Query(False, description="是：浏览器内预览；否：下载"),
):
    """
    下载知识库文档
    """
    if not validate_kb_name(knowledge_base_name):
        return BaseResponse(code=403, msg="Don't attack me")

    kb = KBServiceFactory.get_service_by_name(knowledge_base_name)
    if kb is None:
        return BaseResponse(code=404, msg=f"未找到知识库 {knowledge_base_name}")

    if preview:
        # Determine media type and content disposition based on file extension
        file_extension = os.path.splitext(file_name)[1].lower()
        media_type = None
        if file_extension == '.pdf':
            media_type = 'application/pdf'
            content_disposition_type = 'inline'
        elif file_extension in ['.doc', '.docx']:
            # For DOC files, you can choose either of the following media types:
            # media_type = 'application/msword'
            media_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
            content_disposition_type = 'inline'
        else:
            # For other file types, force download
            content_disposition_type = None
    else:
        content_disposition_type = None

    try:
        kb_file = KnowledgeFile(filename=file_name,
                                knowledge_base_name=knowledge_base_name)

        if os.path.exists(kb_file.filepath):
            headers = {
                "Content-Type": media_type,
                "Accept-Ranges": "none",  # Disable range requests
            }

            return FileResponse(
                path=kb_file.filepath,
                filename=kb_file.filename,
                media_type=media_type,
                content_disposition_type=content_disposition_type,
                headers=headers,
            )
    except Exception as e:
        msg = f"{kb_file.filename} 读取文件失败，错误信息是：{e}"
        logger.error(f'{e.__class__.__name__}: {msg}',
                     exc_info=e if log_verbose else None)
        return BaseResponse(code=500, msg=msg)

    return BaseResponse(code=500, msg=f"{kb_file.filename} 读取文件失败")
```

**Comment by qianma819** [comment]
@HuntZhaozq 
这样改确实没有那个问题了

**Comment by HuntZhaozq** [comment]
但是有的pdf还是不能预览，要下载，大部分是可以预览的

**Comment by qianma819** [comment]
什么样的pdf不能预览？我这边测试没遇到

**Comment by HuntZhaozq** [comment]
知网下载的一小部分，大部分都可以预览

**Comment by qianma819** [comment]
奥，那不管了，凑合用吧。反正下载了也能看

**Comment by HuntZhaozq** [comment]
还有个问题，在本机可以下载文件，但是同一网段下的其他机器就下载不了，请问你遇到过吗

**Comment by qianma819** [comment]
那我是配置在服务器然后去访问的，都能预览。

**Comment by HuntZhaozq** [comment]
我也是配置在服务器，但是文件前缀是127.0.0.1访问不到，你有修改那些配置吗？

**Comment by qianma819** [comment]
DEFAULT_BIND_HOST 修改成实际ip，就不用127.0.0.1访问了

**Comment by qianma819** [comment]
@HuntZhaozq
      if  file_extension == '.txt':
            media_type = 'text/plain'
            content_disposition_type = 'inline'
txt文件预览中文乱码，你知道怎样修改不

**Comment by HuntZhaozq** [comment]
可以问问chatgpt，你的word文档可以预览嘛？我按这个来word还是会下载

**Comment by qianma819** [comment]
我没有word文档，原先只有pdf，后面增加了txt

**Comment by qianma819** [comment]
elif file_extension in ['.doc', '.docx']:  
        if file_extension == '.doc':  
            media_type = 'application/msword'  
        else:  
            media_type = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'  
doc文件跟docx文件是不一样的

**Comment by Lj4040** [comment]
我的是匹配结果下载不了，点击就是127.0.0.1拒绝访问，如何解决？大佬们
