### ISSUE TITLE
[BUG] 在agent中的tool里增加了对特定网页的request请求但是不能正确获取网页内容/ Concise description of the issue

### ISSUE THREAD

**Issue by saltedfish2** [chatchat-space/Langchain-Chatchat#3226]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

在自定义agent中新增了一个对特定网页(携程网)的requests请求获取网页的功能，在本地的main函数里测试的时候可以正确获取网页，但是使用agent进行调用时没有正确网页返回，返回的是404网页。我查看了BING的API访问的实现方式，Langchain中也是使用requests库来实现的，好像没有另外做设置。不清楚是否与FASTAPI的网络相关设置有关。
关于调试我做了以下分析：
1、使用fastapi.concurrency中的 run_in_threadpool方式进行请求，main调用可以获得网页，agent调用不能获取。
2、输出了请求体内容，main调用与agent调用得到的请求体内容完全一致。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'    python startup.py -a --lite
2. 点击 '...' / Click '...'  选择对话自定义agent问答
3. 滚动到 '...' / Scroll to '...' 进行正常提问，要求调用新增的tool工具
4. 问题出现 / Problem occurs 在tool成功调用后，对特定的网址接口进行request请求，请求只有404网页返回。

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
应该正常输出请求的网页内容

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
实际返回404网页
<!doctype html><html><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge"><meta name=robots content="noindex, nofollow"><meta content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui" name=viewport><title>携程旅行网</title><style type=text/css>blockquote,body,button,code,dd,div,dl,dt,em,fieldset,form,h1,h2,h3,h4,h5,h6,html,input,legend,li,ol,p,pre,td,textarea,th,ul{margin:0;padding:0}body{font-size:12px;font-family:Simsun,sans-serif;color:#333}fieldset,img{border:0 none}input,textarea{font-size:12px}textarea{resize:none}table{border-collapse:collapse;border-spacing:0}a{color:#003d7e;text-decoration:none}a:hover{text-decoration:underline}h1,h2,h3,h4,h5,h6{font-family:"Times New Roman",Simsun}li,ol,ul{list-style:none outside none}dfn{font-style:normal}@media screen and (min-width:751px){#footer,.content,.errorinfo{width:800px}.wrap{background:#016eca;width:100%;min-width:1200px;overflow:hidden}.content{position:relative;z-index:1;height:480px;margin:0 auto;padding-top:100px}.logo{position:relative;z-index:5;width:144px;height:54px;margin:0 auto;overflow:hidden;text-indent:-500px;background-position:0 0}.errorinfo{color:#fff;display:block;font-family:"microsoft yahei",simhei,sans-serif;font-size:24px;font-weight:400;text-align:center;margin:30px auto;padding:0}a.goback{display:block;position:relative;z-index:4;width:112px;margin:20px auto;padding:8px 0;color:#fff;font-family:"microsoft yahei",simhei,sans-serif;font-size:16px;text-align:center;text-decoration:none;background-color:#0f4dc5}a.goback:hover{background-color:#3f92f0}.tower{position:absolute;transform:translateZ(300px);z-index:2;top:143px;left:291px;width:116px;height:264px;background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/tower.png) no-repeat}.beam{position:absolute;z-index:1;left:-10px;top:0;width:749px;height:359px;background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/light.png) no-repeat;-webkit-animation:6s cubic-bezier(.25,0,.75,1) 0s none infinite beam;-moz-animation:6s cubic-bezier(.25,0,.75,1) 0s none infinite beam;animation:6s cubic-bezier(.25,0,.75,1) 0s none infinite beam}.wave1{position:absolute;z-index:99;top:400px;height:180px;width:1200px;left:0;right:0;margin:auto;opacity:0;background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/wave.png) repeat-x 0 0;-webkit-animation:50s linear 0s none infinite tweenxxpc;-moz-animation:50s linear 0s none infinite tweenxxpc;animation:50s linear 0s none infinite tweenxxpc}.wave{position:absolute;z-index:100;top:400px;height:180px;width:1200px;left:0;right:0;margin:auto;background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/wave.png) repeat-x 0 0;-webkit-animation:50s linear 0s none infinite tweenxpc;-moz-animation:50s linear 0s none infinite tweenxpc;animation:50s linear 0s none infinite tweenxpc}#footer{margin:0 auto;text-align:center;color:#0053aa;font-family:arial;line-height:1.6;padding:8px 0 0 0;width:1200px}#footer a{color:#0053aa}.copyright{color:#333}.star1{background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png) no-repeat;position:relative;top:164px;left:592px;height:60px;width:60px;opacity:0;-webkit-animation:2s linear 0s none infinite staracta;-moz-animation:2s linear 0s none infinite staracta;animation:2s linear 0s none infinite staracta}.star2{background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png) no-repeat;position:relative;top:234px;left:245px;height:60px;width:60px;opacity:.8;-webkit-animation:2s linear 0s none infinite staract;-moz-animation:2s linear 0s none infinite staract;animation:2s linear 0s none infinite staract}.star3{background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png) no-repeat;position:relative;top:252px;left:644px;height:60px;width:60px;opacity:.8;-webkit-animation:2s linear 0s none infinite staract;-moz-animation:2s linear 0s none infinite staract;animation:2s linear 0s none infinite staract}.star4{background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png) no-repeat;position:relative;top:268px;left:264px;height:60px;width:60px;opacity:0;-webkit-animation:2s linear 0s none infinite staracta;-moz-animation:2s linear 0s none infinite staracta;animation:2s linear 0s none infinite staracta}.top{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/top.png);background-repeat:no-repeat;position:absolute;top:0;left:0;width:1200px;height:580px;z-index:999;right:0;margin:auto}.bg{background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/404_PC_bg.png) no-repeat center bottom;position:absolute;z-index:0;width:1200px;height:580px;min-width:1200px;left:0;right:0;margin:auto;overflow:hidden}.adv_t{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/PC_btA.png);background-repeat:no-repeat;position:relative;top:350px;left:470px;width:262px;height:28px;z-index:10000;cursor:pointer;display:none}.back_t{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/PC_btB.png);background-repeat:no-repeat;position:relative;top:433px;left:551px;width:98px;height:38px;z-index:10000;cursor:pointer}}@media screen and (max-width:750px){body html{overflow-x:hidden}.top{position:absolute;top:0;left:0;max-width:750px;width:100%;height:755px;z-index:999;right:0;margin:auto;min-width:350px}.mengceng{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/h5_top_1.png);height:755px;background-size:auto 910px;background-repeat:no-repeat;width:415px;position:relative;margin:0 auto}.wrap{background:#016eca;width:100%;min-width:400px}.bg{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/404_H5_bg.png);background-repeat:no-repeat;margin:0 auto;background-size:contain;height:755px;width:350px;overflow:hidden}.bg:before{content:"";display:block;padding-top:180%}#footer{margin:0 auto;text-align:center;color:#0053aa;font-family:arial;line-height:1.6;padding:8px 0 0 0}#footer a{color:#0053aa}.copyright{color:#333}.wave1{position:absolute;z-index:99;top:444px;height:180px;width:350px;left:0;right:0;margin:auto;opacity:0;background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/wave.png) repeat-x 0 0;-webkit-animation:50s linear 0s none infinite tweenxx;-moz-animation:50s linear 0s none infinite tweenxx;animation:50s linear 0s none infinite tweenxx}.wave{position:absolute;z-index:100;top:444px;height:180px;width:350px;left:0;right:0;margin:auto;background:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/wave.png) repeat-x 0 0;-webkit-animation:50s linear 0s none infinite tweenx;-moz-animation:50s linear 0s none infinite tweenx;animation:50s linear 0s none infinite tweenx}@-webkit-keyframes tweenx{0%{background-position:100vw 0}50%{opacity:0}100%{background-position:0 0;opacity:1}}@-moz-keyframes tweenx{0%{background-position:100vw 0}50%{opacity:0}100%{background-position:0 0;opacity:1}}@keyframes tweenx{0%{background-position:100vw 0}50%{opacity:0}100%{background-position:0 0;opacity:1}}@keyframes tweenxx{0%{background-position:0 0;opacity:0}50%{opacity:1}100%{background-position:-100vw 0;opacity:0}}.tower{position:relative;transform:translateZ(300px);z-index:2;top:-370px;left:-53px;width:180px;height:180px;background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/tower_h5.png);background-repeat:no-repeat;background-size:contain}.beam{position:relative;z-index:1;left:-176px;top:-640px;width:484px;height:232px;background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/light.png);background-repeat:no-repeat;background-size:contain;-webkit-animation:6s cubic-bezier(.25,0,.75,1) 0s none infinite beam;-moz-animation:6s cubic-bezier(.25,0,.75,1) 0s none infinite beam;animation:6s cubic-bezier(.25,0,.75,1) 0s none infinite beam}.star1{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png);background-repeat:no-repeat;background-size:contain;position:relative;top:-856px;left:235px;height:30px;width:30px;opacity:0;-webkit-animation:2s linear 0s none infinite staracta;-moz-animation:2s linear 0s none infinite staracta;animation:2s linear 0s none infinite staracta}.star2{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png);background-repeat:no-repeat;background-size:contain;position:relative;top:-724px;left:6px;height:30px;width:30px;opacity:.8;-webkit-animation:2s linear 0s none infinite staract;-moz-animation:2s linear 0s none infinite staract;animation:2s linear 0s none infinite staract}.star4{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/star.png);background-repeat:no-repeat;background-size:contain;position:relative;top:-651px;left:14px;height:30px;width:30px;opacity:0;-webkit-animation:2s linear 0s none infinite staracta;-moz-animation:2s linear 0s none infinite staracta;animation:2s linear 0s none infinite staracta}.adv_t{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/H5_btA.png);background-repeat:no-repeat;background-size:contain;position:relative;margin:0 auto;top:-288px;width:300px;height:35px;z-index:10000;cursor:pointer}.back_t{background-image:url(https://webresource.c-ctrip.com/ares2/nfes/pc-home/*/default/others/H5_btB.png);background-repeat:no-repeat;background-size:100% auto;position:relative;margin:0 auto;top:-253px;width:92px;height:38px;z-index:10000;cursor:pointer}}@-moz-keyframes staract{0%{opacity:.8}50%{opacity:0}100%{opacity:.8}}@-webkit-keyframes staract{0%{opacity:.8}50%{opacity:0}100%{opacity:.8}}@keyframes staract{0%{opacity:.8}50%{opacity:0}100%{opacity:.8}}@-moz-keyframes staracta{0%{opacity:0}50%{opacity:.8}100%{opacity:0}}@-webkit-keyframes staracta{0%{opacity:0}50%{opacity:.8}100%{opacity:0}}@keyframes staracta{0%{opacity:0}50%{opacity:.8}100%{opacity:0}}@-webkit-keyframes beam{0%{transform:rotateY(0)}30%{transform:rotateY(45deg)}60%{transform:rotateY(45deg)}100%{transform:rotateY(0)}}@-moz-keyframes beam{0%{transform:rotateY(0)}30%{transform:rotateY(45deg)}60%{transform:rotateY(45deg)}100%{transform:rotateY(0)}}@keyframes beam{0%{transform:rotateY(0)}30%{transform:rotateY(45deg)}60%{transform:rotateY(45deg)}100%{transform:rotateY(0)}}@-moz-keyframes tweenxpc{0%{background-position:1110px 0}50%{opacity:0}100%{background-position:0 0;opacity:1}}@-webkit-keyframes tweenxpc{0%{background-position:1110px 0}50%{opacity:0}100%{background-position:0 0;opacity:1}}@keyframes tweenxpc{0%{background-position:1110px 0}50%{opacity:0}100%{background-position:0 0;opacity:1}}@-moz-keyframes tweenxxpc{0%{background-position:0 0;opacity:0}50%{opacity:1}100%{background-position:-1110px 0;opacity:0}}@-webkit-keyframes tweenxxpc{0%{background-position:0 0;opacity:0}50%{opacity:1}100%{background-position:-1110px 0;opacity:0}}@keyframes tweenxxpc{0%{background-position:0 0;opacity:0}50%{opacity:1}100%{background-position:-1110px 0;opacity:0}}</style></head><body><div class=wrap><div class=top><div class=mengceng></div><div class=adv_t></div><div class=back_t></div></div><div class=bg><div class=tower></div><div class=beam></div><div class=star1></div><div class=star2></div><div class=star3></div><div class=star4></div></div><div class=content></div><div class=wave></div><div class=wave1></div></div><div id=footer><p class=copyright><a href=http://pages.ctrip.com/public/copyright.htm>Copyright&copy;</a>1999-<script>document.write((new Date).getFullYear())</script>, <a href=http://pages.ctrip.com/public/ctripab/abctrip.htm>ctrip.com</a>. all rights reserved.</p></div><input type=hidden id=page_id value=600001375><script>!function(){function t(){window.location.href="https://m.ctrip.com/webapp/you/cranking/crankingCity/100200078435.html?ishideheader=true&isHideNavBar=YES&useLocationId=true&allianceid=3769318&sid=20621919"}try{document.getElementsByClassName("back_t")[0].addEventListener("click",function(){try{var i=navigator&&navigator.userAgent;/(CtripWireless|sml_wireless|gs_wireless|we_wireless|TieyouWireless)/i.test(i)?"undefined"!=typeof CtripUtil?CtripUtil.app_open_url("ctrip://wireless/",1):window.location.href="https://www.ctrip.com/":/(iphone|ios|android|mini|mobile|mobi|Nokia|Symbian|iPod|iPad|Windows\s+Phone|MQQBrowser|wp7|wp8|UCBrowser7|UCWEB|360\s+Aphone\s+Browser)/i.test(i)?window.location.href="https://m.ctrip.com/html5/":window.location.href="https://www.ctrip.com/"}catch(i){window.location.href="https://www.ctrip.com/"}}),document.getElementsByClassName("adv_t")[0].addEventListener("click",function(){try{var i=(window.location||document.location).hostname,e=navigator&&navigator.userAgent;/(CtripWireless|sml_wireless|gs_wireless|we_wireless|TieyouWireless)/i.test(e)?"undefined"!=typeof CtripUtil?CtripUtil.app_open_url("ctrip://wireless/h5?path=cranking&page=index.html#cranking/crankingCity/100200078435.html&ishideheader=true&isHideNavBar=YES&useLocationId=true",1):t():("m.ctrip.com"!==i&&/(iphone|ios|android|mini|mobile|mobi|Nokia|Symbian|iPod|iPad|Windows\s+Phone|MQQBrowser|wp7|wp8|UCBrowser7|UCWEB|360\s+Aphone\s+Browser)/i.test(e),t())}catch(i){t()}})}catch(i){console.log(i.message)}}()</script><script type=text/javascript>!function(n,r,a,e,t){function o(e){var t,o,i;n.$_bf&&n.$_bf.loaded||n.$LAB||n.CtripJsLoader||(t=!1,o="?v="+(i=new Date).getFullYear()+i.getMonth()+"_"+i.getDate(),(i=r.createElement(a)).type="text/javascript",i.charset="utf-8",i.async=!0,i.src="//webresource.c-ctrip.com/code/ubt/"+e+".min.js"+o,(t=r.getElementsByTagName(a)[0]).parentNode.insertBefore(i,t))}e=(n.location||r.location).hostname,n.__bfi=[],n.__bfi.push(["_config","rms",!1]),n.__bfi.push(["_config","markting",!1]),t=navigator.userAgent,"m.ctrip.com"===e||/(iphone|ios|android|mini|mobile|mobi|Nokia|Symbian|iPod|iPad|Windows\s+Phone|MQQBrowser|wp7|wp8|UCBrowser7|UCWEB|360\s+Aphone\s+Browser)/i.test(t)?o("_mubt"):o("_bfa")}(window,document,"script")</script></body></html>
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v 2.10
- 是否使用 Docker 部署（是/否）：是
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM-4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by saltedfish2** [comment]
> Hello @saltedfish2! 👋 I'm [Dosu](https://dosu.dev), a bot here to lend a hand with bugs, answer your questions, and guide you on contributing while we await a human maintainer. I'm diving into your issue and will get back to you with a full answer shortly. Stay tuned! 🤖

请问什么时候才能回复我的问题呢？

**Comment by saltedfish2** [comment]
@dosu-bot 以下是我发送请求的代码

def flights_query(dcity, acity, date, output_file):

    print("在访问接口.......")
    print("在得到城市代码.......")

    dcityCode = str(cityCodes.get(dcity))

    acityCode = str(cityCodes.get(acity))

    print("得到的城市代码为：", dcityCode,acityCode)

    headers = {

        "User-Agent": "Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0",

        "Content-Type": "application/json",

        "referer": "https://flights.ctrip.com/itinerary/oneway/"+dcityCode+"-"+acityCode+"?date="+date

    }

    url = 'http://flights.ctrip.com/itinerary/api/12808/products'

    request_payload = {"flightWay": "Oneway",

                       "classType": "ALL",

                       "hasChild": 'false',

                       "hasBaby": 'false',

                       "searchIndex": 1,

                       "airportParams": [

                           {"dcity": dcityCode, "acity": acityCode, "dcityname": dcity, "acityname": acity,

                            "date": date}]}

    print("开始请求.....\n")

    print("请求参数：", request_payload)

    print("请求时环境变量.....\n")

    import os

    for key, value in os.environ.items():

        print(f"{key}: {value}")

    try:

        response = requests.post(url, data=json.dumps(

            request_payload), headers=headers).text

    except Exception as e:

        print("请求时出错：", e )

        return e

    # print("\n\n得到的回复：", response)

    routeList = None

    try:

        routeList = json.loads(response).get('data').get('routeList')

    except Exception as e:

        print("jsonload出错：\t", e)

        raise e

  

    route_filter = []

    if routeList != None:

        for route in routeList:

            if len(route.get('legs')) == 1:

                route_filter.append(route)


    print("route_filter长度：",(len(route_filter)),"\n")

    return json.dumps(route_filter, ensure_ascii=False, indent=4)

**Comment by zRzRzRzRzRzRzR** [comment]
那应该对内容以str的形式返回给大模型
