### ISSUE TITLE
在知识库中添加txt文档后无报错，但是显示文档数量为0

### ISSUE THREAD

**Issue by GolfHotelSierra** [chatchat-space/Langchain-Chatchat#3231]
**问题描述**
- 在知识库中添加txt文档，在页面中没有可见的报错信息，但是文档数量为0
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/88077751/e0cab0e3-557a-4192-9ec8-1ecd902b09fe)
- 此外，文档加载器为空，分词器为空，对该txt文档可以“从知识库中删除”，不会产生报错
- 在文档更改的区域，同样为空，不显示任何信息

**运行环境**
- 在 `docker` 容器中运行
- 单卡部署，使用 `python startup.py --all-web-ui` 仅启动 web

**复现问题的步骤**
1. 点击知识库管理
2. 选择已经创建的知识库，知识库名称为 `medical_books`（该知识库中本身无任何文档），使用的向量库为 `faiss`，嵌入模型为 `bge-large-zh-v1.5`，模型和向量库均存储在本地
3. 点击 `Browse files`，选择要添加的 `.txt` 文档
4. 点击 `添加文件到知识库`
5. 看到页面上出现信息，`知识库 medical_books 中已有文件`

**预期的结果**
官方提供的 `sample` 知识库中的显示如下，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/88077751/58e06296-a8c9-4e8f-ac76-0e7344903473)

**实际结果**
1. 实际的显示结果如下，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/88077751/08ef7012-66d6-4261-9a91-3410203b3002)

2. 此外，点击 `对话`，使用 `知识库问答`，询问txt文档中存在的问题，无法依据知识库给出问答，应该是确实没有添加成功
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/88077751/1085730c-c96b-455e-b9bb-bb69a3b73a8c)

这个问题对应的原文为，
```
\section{精神病学的概念与任务}

精神病学（psychiatry）是临床医学的一个分支，是以研究各种精神疾病的病因、发病机制、临床表现、疾病的发生发展规律以...
```

**Comment by Wangzhongxi** [comment]
> **问题描述**
> 
> * 在知识库中添加txt文档，在页面中没有可见的报错信息，但是文档数量为0
>   ![image](https://private-user-images.githubusercontent.com/88077751/311130241-e0cab0e3-557a-4192-9ec8-1ecd902b09fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzAyNDEtZTBjYWIwZTMtNTU3YS00MTkyLTllYzgtMWVjZDkwMmIwOWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTFhOWM3MGI4MTQ4N2I3MjkxYzViYjQ3YzU2MjQ4MDQxNDRkZTExZDJiNTI2OGRjNjM1YTdjNzE4ZWRkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1oJ1VxsFl5D0Khn2B37f2uKLYiserlZObKcs-XFT1g)
> * 此外，文档加载器为空，分词器为空，对该txt文档可以“从知识库中删除”，不会产生报错
> * 在文档更改的区域，同样为空，不显示任何信息
> 
> **运行环境**
> 
> * 在 `docker` 容器中运行
> * 单卡部署，使用 `python startup.py --all-web-ui` 仅启动 web
> 
> **复现问题的步骤**
> 
> 1. 点击知识库管理
> 2. 选择已经创建的知识库，知识库名称为 `medical_books`（该知识库中本身无任何文档），使用的向量库为 `faiss`，嵌入模型为 `bge-large-zh-v1.5`，模型和向量库均存储在本地
> 3. 点击 `Browse files`，选择要添加的 `.txt` 文档
> 4. 点击 `添加文件到知识库`
> 5. 看到页面上出现信息，`知识库 medical_books 中已有文件`
> 
> **预期的结果** 官方提供的 `sample` 知识库中的显示如下， ![image](https://private-user-images.githubusercontent.com/88077751/311131439-58e06296-a8c9-4e8f-ac76-0e7344903473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzE0MzktNThlMDYyOTYtYThjOS00ZThmLWFjNzYtMGU3MzQ0OTAzNDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjUyMjFkYzQ4OTc2ZDJkYTViOWI0OGNiYjA3MjBiZjcyM2E5MjliNzA3NzFjNzIyNDIyNWVjOGNhZGFlYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYSTequjPPhweksVUsOHK6rMwvkgwcMtb2dsSw6WhGk)
> 
> **实际结果**
> 
> 1. 实际的显示结果如下，
>    ![image](https://private-user-images.githubusercontent.com/88077751/311131604-08ef7012-66d6-4261-9a91-3410203b3002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzE2MDQtMDhlZjcwMTItNjZkNi00MjYxLTlhOTEtMzQxMDIwM2IzMDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NTZmZTc5OTA0ZTRhMjJiN2NmYmZkNzE5NzNlMzM5NDA1NzFiYjk2YTA1MTQ3Y2UyYjQzZjYyZjIyZmU0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFJB11HcwF70r30NAPQGP6vfm5Bmu2z0cNk0yzLzpqA)
> 2. 此外，点击 `对话`，使用 `知识库问答`，询问txt文档中存在的问题，无法依据知识库给出问答，应该是确实没有添加成功
>    ![image](https://private-user-images.githubusercontent.com/88077751/311131916-1085730c-c96b-455e-b9bb-bb69a3b73a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzE5MTYtMTA4NTczMGMtYzk2Yi00NTVlLWI5YmItYmI2OWEzYjczYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZjZjNWRhNzQxODM0MTNmZDliZGMwZWVhMzUwYTgzYWE4ZDc1MzZjZmIxZjk1ZjVkZDI2NWE1MmVkY2EwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OuP4JKxmEH4S5fzKwk95Hkdn8fkWAWYFHIq9T6Z0JWo)
> 
> 这个问题对应的原文为，
> 
> ```
> \section{精神病学的概念与任务}
> 
> 精神病学（psychiatry）是临床医学的一个分支，是以研究各种精神疾病的病因、发病机制、临床表现、疾病的发生发展规律以...
> ```

解决了吗？

**Comment by GolfHotelSierra** [comment]
> > **问题描述**
> > 
> > * 在知识库中添加txt文档，在页面中没有可见的报错信息，但是文档数量为0
> >   ![image](https://private-user-images.githubusercontent.com/88077751/311130241-e0cab0e3-557a-4192-9ec8-1ecd902b09fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzAyNDEtZTBjYWIwZTMtNTU3YS00MTkyLTllYzgtMWVjZDkwMmIwOWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZTFhOWM3MGI4MTQ4N2I3MjkxYzViYjQ3YzU2MjQ4MDQxNDRkZTExZDJiNTI2OGRjNjM1YTdjNzE4ZWRkOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.X1oJ1VxsFl5D0Khn2B37f2uKLYiserlZObKcs-XFT1g)
> > * 此外，文档加载器为空，分词器为空，对该txt文档可以“从知识库中删除”，不会产生报错
> > * 在文档更改的区域，同样为空，不显示任何信息
> > 
> > **运行环境**
> > 
> > * 在 `docker` 容器中运行
> > * 单卡部署，使用 `python startup.py --all-web-ui` 仅启动 web
> > 
> > **复现问题的步骤**
> > 
> > 1. 点击知识库管理
> > 2. 选择已经创建的知识库，知识库名称为 `medical_books`（该知识库中本身无任何文档），使用的向量库为 `faiss`，嵌入模型为 `bge-large-zh-v1.5`，模型和向量库均存储在本地
> > 3. 点击 `Browse files`，选择要添加的 `.txt` 文档
> > 4. 点击 `添加文件到知识库`
> > 5. 看到页面上出现信息，`知识库 medical_books 中已有文件`
> > 
> > **预期的结果** 官方提供的 `sample` 知识库中的显示如下， ![image](https://private-user-images.githubusercontent.com/88077751/311131439-58e06296-a8c9-4e8f-ac76-0e7344903473.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzE0MzktNThlMDYyOTYtYThjOS00ZThmLWFjNzYtMGU3MzQ0OTAzNDczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjYjUyMjFkYzQ4OTc2ZDJkYTViOWI0OGNiYjA3MjBiZjcyM2E5MjliNzA3NzFjNzIyNDIyNWVjOGNhZGFlYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYSTequjPPhweksVUsOHK6rMwvkgwcMtb2dsSw6WhGk)
> > **实际结果**
> > 
> > 1. 实际的显示结果如下，
> >    ![image](https://private-user-images.githubusercontent.com/88077751/311131604-08ef7012-66d6-4261-9a91-3410203b3002.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzE2MDQtMDhlZjcwMTItNjZkNi00MjYxLTlhOTEtMzQxMDIwM2IzMDAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NTZmZTc5OTA0ZTRhMjJiN2NmYmZkNzE5NzNlMzM5NDA1NzFiYjk2YTA1MTQ3Y2UyYjQzZjYyZjIyZmU0ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFJB11HcwF70r30NAPQGP6vfm5Bmu2z0cNk0yzLzpqA)
> > 2. 此外，点击 `对话`，使用 `知识库问答`，询问txt文档中存在的问题，无法依据知识库给出问答，应该是确实没有添加成功
> >    ![image](https://private-user-images.githubusercontent.com/88077751/311131916-1085730c-c96b-455e-b9bb-bb69a3b73a8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwODcxOTAsIm5iZiI6MTcxNTA4Njg5MCwicGF0aCI6Ii84ODA3Nzc1MS8zMTExMzE5MTYtMTA4NTczMGMtYzk2Yi00NTVlLWI5YmItYmI2OWEzYjczYThjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDEzMDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlZjZjNWRhNzQxODM0MTNmZDliZGMwZWVhMzUwYTgzYWE4ZDc1MzZjZmIxZjk1ZjVkZDI2NWE1MmVkY2EwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OuP4JKxmEH4S5fzKwk95Hkdn8fkWAWYFHIq9T6Z0JWo)
> > 
> > 这个问题对应的原文为，
> > ```
> > \section{精神病学的概念与任务}
> > 
> > 精神病学（psychiatry）是临床医学的一个分支，是以研究各种精神疾病的病因、发病机制、临床表现、疾病的发生发展规律以...
> > ```
> 
> 解决了吗？

md文档是可以正常添加的，把txt转为md文档可以解决问题
