### ISSUE TITLE
[BUG] 创建知识库时，名称带有“-”号会导致出错

### ISSUE THREAD

**Issue by ngbruce** [chatchat-space/Langchain-Chatchat#3244]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
创建知识库时，名称带有“-”号会导致出错

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/68752507/7d247586-9faf-4418-a790-253d1c11e3c3)

**复现问题的步骤 / Steps to Reproduce**
1. 在页面上选择创建新的知识库
2. 输入知识库名称，其中带有“-”号，例如：esp32-s2技术规格书知识库
3. 观察命令行输出的信息，可以发现以下出错提示:

`
2024-03-09 23:19:13,451 - kb_api.py[line:34] - ERROR: RuntimeError: 创建知识库出错： Error in __cdecl faiss::FileIOWriter::FileIOWriter(const char *) at D:\a\faiss-wheels\faiss-wheels\faiss\faiss\i
mpl\io.cpp:98: Error: 'f' failed: could not open D:\My_Doc\PyTorchProj\ChatGLM\Langchain-Chatchat\knowledge_base\esp32-s2技术规格书知识库\vector_store\text2vec\index.faiss for writing: No such file
 or directory
`

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：commit 021d635af0137a3ab5f896b5cbfdec1afd4819bf (HEAD -> master, origin/master,
origin/HEAD)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:  Win10
- Python 版本 / Python version: 3.10.9
- 其他相关环境信息 / Other relevant environment information: 无

**Comment by GitYohoo** [comment]
不能用中文名？

**Comment by Nancy-wangxixi** [comment]
是不是知识库名字里不能有中文呢？我记得有提示
