### ISSUE TITLE
关于agent调用tool的返回问题

### ISSUE THREAD

**Issue by saltedfish2** [chatchat-space/Langchain-Chatchat#3248]
使用agent调用tool的流程是怎么样的，列出所有调用流程，并解释agent工作的逻辑。现在我调用了自定义tool，有返回内容但是前端显示的是：调用agent工具失败，该回答为大模型自身能力的回答:  ` 和返回内容。

**Comment by dalunzi-dreamers** [comment]
后来跑通了没？

**Comment by saltedfish2** [comment]
> 后来跑通了没？

还没有，应该是模型输出的格式与输出解析器能处理的不同。要对输出解析器做更新。

**Comment by liushaoqian** [comment]
> > 后来跑通了没？
> 
> 还没有，应该是模型输出的格式与输出解析器能处理的不同。要对输出解析器做更新。

这个问题你们解决了，我调用agent没有任何回答，也不报错，日志也没有输出，不知道是什么情况
