### ISSUE TITLE
对于数据库的操作能否支持异步操作？

### ISSUE THREAD

**Issue by luojihaohuawei** [chatchat-space/Langchain-Chatchat#3250]
**问题描述 / Problem Description**
对于faiss数据库的操作（增删改查）能否支持异步操作？如果需要实现，是否需要把 create_tables, folder2db, upload_docs, 和 delete_docs等函数自定义修改成异步方式调用？

**预期的结果 / Expected Result**
异步调用数据库操作的功能

**实际结果 / Actual Result**
同步调用

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：V2.0.28
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss)： faiss 
- 操作系统及版本 / Operating system and version:LINUX
- Python 版本 / Python version: 3.10

**Comment by zRzRzRzRzRzRzR** [comment]
没支持，这个框架也没有考虑并发
