### ISSUE TITLE
LLM+知识库如何提升用户关键词提问准确性？

### ISSUE THREAD

**Issue by cwqJim2023** [chatchat-space/Langchain-Chatchat#3253]
**问题描述 / Problem Description**
采用LLM+知识库形式进行问答，当用户输入关键词或者模糊问题时，如何提升知识库返回准确性？

**Comment by seabean1999** [comment]
> **问题描述 / Problem Description** 采用LLM+知识库形式进行问答，当用户输入关键词或者模糊问题时，如何提升知识库返回准确性？

这个链接里文章的思路看看对你有没有用？基础应用架构一致的 [用 LLM 构建企业专属的用户助手
](https://zhuanlan.zhihu.com/p/645658201)

**Comment by zRzRzRzRzRzRzR** [comment]
wiki有相关方案，但是更多需要靠自己探索
