### ISSUE TITLE
怎么指定Embedding 用一个gpu 然后vllm 用另外的gpu

### ISSUE THREAD

**Issue by momomobinx** [chatchat-space/Langchain-Chatchat#3256]
怎么指定Embedding 用一个gpu 然后vllm 用另外的gpu
如题使用 export CUDA_VISIBLE_DEVICES=1
指定显卡后，vllm 会将大模型运行到这些卡上
但是使用知识库问答时 Embedding 模型也会加载到同样的gpu ，尝试过下面方法：
1.代码中在 Embedding模型部署前使用 os.environ["CUDA_VISIBLE_DEVICES"] = 0 没有效果还是 gpu 1
2.在 配置中配置 EMBEDDING_DEVICE = cuda:0  也没有效果
3.在代码中修改 embedding_device 返回 cuda:0 也没有效果
4.在llm加载完成 chat 正常后，export CUDA_VISIBLE_DEVICES=0 再进行知识库问答，Embedding 模型还是加载到 gpu1

**Comment by zRzRzRzRzRzRzR** [comment]
哦似乎没办法，fschat不支持
