### ISSUE TITLE
管理权限和普通权限分开

### ISSUE THREAD

**Issue by qianma819** [chatchat-space/Langchain-Chatchat#3257]
没有权限管理功能，只要登录就可以增加删除知识库。想要登录后显示不同的画面。比如管理者登录一个网址后显示目前的画面，普通用户登录另外的网址后只显示对话画面。不知道怎么操作

**Comment by litongyun233** [comment]
@qianma819 有同样的需求，请问作者解决了吗？

**Comment by qianma819** [comment]
@litongyun233 
 query_param = st.query_params.get('admin')
通过网址是否含有admin来判断是否admin登录。xx.xx.xx.xx/?admin这样就可以admin登录

**Comment by WoNeiDieA** [comment]
您好作者，能看一下您对于代码的修改么，对streamlit不太了解，没有修改的头绪

**Comment by qianma819** [comment]
@WoNeiDieA  
上面的回答不是写了么？在webui.py增加代码
query_param = st.query_params.get('admin')

    if query_param is not None:
        pages = {
            "对话": {
                "icon": "chat",
                "func": dialogue_page,
           },
            "知识库管理": {
                "icon": "hdd-stack",
                "func": knowledge_base_page,
            },
        }
    else:
        pages = {
            "对话": {
                "icon": "chat",
                "func": dialogue_page,
            },
            "增加knowHow": {
                "icon": "pen",
                "func": add_knowhow_page,
            },
        } 
通过网址是否含有admin来判断是否admin登录。xx.xx.xx.xx/?admin这样就可以admin登录。
