### ISSUE TITLE
[BUG] 使用/file-chat api的回答跟在网页端的回答不一样，经常会没有匹配到内容

### ISSUE THREAD

**Issue by SolarKnight1** [chatchat-space/Langchain-Chatchat#3259]
**问题描述 / Problem Description**
rt, 
![微信截图_20240311142709](https://github.com/chatchat-space/Langchain-Chatchat/assets/131108176/ff9cb84c-6897-4dc0-aa88-dd62161f23a2)

**复现问题的步骤 / Steps to Reproduce**
1. python startup.py -a
2. post了/knowledge_base/upload_temp_docs，上传了一个文本对话的临时文件，返回一个id
3. 再post/chat/file-chat，在knowledge_id中填入了刚才返回的id
4. 返回data: {"answer": "很抱歉，您提到的“文中”并没有在您的问题中给出。为了准确回答关于投保年龄范围的问题，我需要相关的文本信息或者上下文。如果您能提供具体的文本内容或详细描述，我会很乐意帮助您确定投保年龄范围。"}

data: {"docs": ["<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>"]}

**预期的结果 / Expected Result**
![微信截图_20240311142302](https://github.com/chatchat-space/Langchain-Chatchat/assets/131108176/11c74c40-a8b2-49e3-b0a1-7cb3f2c3353a)

**实际结果 / Actual Result**

data: {"answer": "很抱歉，您提到的“文中”并没有在您的问题中给出。为了准确回答关于投保年龄范围的问题，我需要相关的文本信息或者上下文。如果您能提供具体的文本内容或详细描述，我会很乐意帮助您确定投保年龄范围。"}

data: {"docs": ["<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>"]}

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: v2.10
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): zhipu-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-large
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by SolarKnight1** [comment]
中间是不是还有什么我不知道的环节，求教啊

**Comment by SolarKnight1** [comment]
在网页上：![微信图片_20240313134944](https://github.com/chatchat-space/Langchain-Chatchat/assets/131108176/1c64c619-a56a-4efc-8f15-82ac8d8c71ab)
在api上：
![微信图片_20240313135038](https://github.com/chatchat-space/Langchain-Chatchat/assets/131108176/ebdb8bf7-3086-4179-84d5-f43e7d75c287)

**Comment by ananSpace** [comment]
这个问题最终解决了吗
