### ISSUE TITLE
配置了nginx之后 找不到swagger的页面了 

### ISSUE THREAD

**Issue by 302658980** [chatchat-space/Langchain-Chatchat#3261]
GET http://region-9.autodl.pro:43612/static-offline-docs/swagger-ui.css net::ERR_ABORTED 404 (Not Found)
docs:12 
GET http://region-9.autodl.pro:43612/static-offline-docs/swagger-ui-bundle.js net::ERR_ABORTED 404 (Not Found)
docs:15 Uncaught ReferenceError: SwaggerUIBundle is not defined

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该不在本项目的范围内吧，只要做端口映射就行了

**Comment by 302658980** [comment]
location /swagger-ui/ {
    alias autodl-tmp/Langchain-Chatchat/server/static/;
}
我按照这样的配置之前确实从404 变成了403  但是还是报错 就是访问不到这个资源 能不能帮帮我解决这个问题  我找了好些资料都没能解决掉
