### ISSUE TITLE
使用Agent功能，调用天气工具，能够正确识别需要调用什么类型的工具，但是并没有执行

### ISSUE THREAD

**Issue by dalunzi-dreamers** [chatchat-space/Langchain-Chatchat#3268]
**问题描述 / Problem Description**
如题，心知天气已经注册好，也已经将私钥写在了配置文件中，包括工具注册等代码已经检查无误，但是我期待的结果应该是调用
server/agent/tools/weather_check.py，帮我查询到了杭州的天气，并告诉我杭州的今天的天气是晴天。但是并没有，只有如下提示，不知道这句是在哪里输出的？应该如何才能够让工具被调用呢？
`
Action:
```
{"action": "Final Answer", "action_input": "需要查询杭州今天的天气，因此可以使用“天气工具”来获取相关信息。\n"}
```

> Finished chain.
`

**环境信息 / Environment Information**
- langchain chatchat-ChatGLM3-6B

**Comment by dalunzi-dreamers** [comment]
> 嗨，@dalunzi-dreamers！很高兴再次见到你。希望你今天过得不错！
> 
> 根据您的描述，我理解您在尝试使用天气工具查询杭州的天气时遇到了问题。根据我在Langchain-Chatchat仓库中找到的相关问题，我有一些可能的解决方案可以提供。
> 
> 首先，您需要确保在初始化`StructuredGLM3ChatAgent`时，天气工具已经包含在`tools`序列中。这一步骤在`initialize_glm3_agent`函数中完成。您可以参考[这里的源代码](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/custom_agent/ChatGLM3Agent.py)。
> 
> 其次，您需要验证`StructuredChatOutputParserWithRetries`类的`parse`方法是否正确识别了工具的名称。如果工具名称没有被正确识别，那么工具将无法被调用。
> 
> 另外，您需要检查工具的配置文件是否被`tool_config_from_file`函数找到并正确读取。如果配置文件没有被正确读取，那么工具将无法正常工作。
> 
> 最后，您需要确保工具的名称已经包含在`StructuredGLM3ChatAgent`类的`allowed_tools`属性中。如果工具名称没有被包含在这个属性中，那么工具将无法被调用。
> 
> 此外，您的自定义工具的YAML配置应该遵循提供的结构和内容示例。您可以参考[这里的源代码](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/calculate.yaml)。
> 
> 如果在检查了这些点之后问题仍然存在，那么可能需要提供更多的错误信息或详细的使用场景以便进一步的帮助。
> 
> 希望这些信息能对您有所帮助。如果您有任何其他问题或需要进一步的澄清，请随时告诉我。
> 
> ## Sources
> * [从前端agent问答debug后工具无法正确调用到](https://github.com/chatchat-space/Langchain-Chatchat/discussions/2586)
> * [[BUG] 简洁阐述问题 / 使用glm3的agemt时 text中无法发现tool_call](https://api.github.com/repos/chatchat-space/Langchain-Chatchat/issues/2836)
> * [使用agent_chat调自定义工具，无法调到自定义工具](https://api.github.com/repos/chatchat-space/Langchain-Chatchat/issues/2494)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

calculate.yaml文件是不是老版本的？已经被弃用？目前tools相关注册应该是在 __init__.py文件里面吧？

**Comment by zRzRzRzRzRzRzR** [comment]
清使用GLM3模板，另外要填写天气的key

**Comment by zgz757183190** [comment]
> 清使用GLM3模板，另外要填写天气的关键

大神，请教一下这个是什么意思呢？有案例啥的不，帮忙分享一下呢，感谢！！！

**Comment by Leiyanzangxiangsi** [comment]
一样的问题，有人解决吗

**Comment by BANGzys** [comment]
此框架下chatglm3-6b模型不行，换了qwen好使了







------------------ 原始邮件 ------------------
发件人: 黄锦雕 ***@***.***&gt;
发送时间: 2024年4月23日 14:17
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: BANGzys ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[chatchat-space/Langchain-Chatchat] 使用Agent功能，调用天气工具，能够正确识别需要调用什么类型的工具，但是并没有执行 (Issue #3268)

**Comment by Leiyanzangxiangsi** [comment]
> 此框架下chatglm3-6b模型不行，换了qwen好使了
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: 黄锦雕 ***@***.***&gt; 发送时间: 2024年4月23日 14:17 收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt; 抄送: BANGzys ***@***.***&gt;, Comment ***@***.***&gt; 主题: 回复：[chatchat-space/Langchain-Chatchat] 使用Agent功能，调用天气工具，能够正确识别需要调用什么类型的工具，但是并没有执行 (Issue #3268)

好，我试试，多谢老哥
