### ISSUE TITLE
切换MOSS的时候报错

### ISSUE THREAD

**Issue by baolixiong** [chatchat-space/Langchain-Chatchat#327]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/48472462/52492f11-2223-4eaa-9bb1-0fbf90704c62)
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/48472462/baab719d-9760-40ec-8364-428866a57b75)
danshi但是发布的源码中，
get_class_from_dynamic_module（）函数没有设置这两个参数

**Comment by KyonCN** [comment]
请问，这个问题你解决了吗？我也碰到了这个问题。

**Comment by baolixiong** [comment]
@KyonCN 我把transformers更新到4.29.1，没报这个错了，但是出现了别的问题，你解决了吗
