### ISSUE TITLE
[BUG] 用LLaMA-Factory微调后放入peft文件夹中运行项目，训练后模型未被加载

### ISSUE THREAD

**Issue by goodmaney** [chatchat-space/Langchain-Chatchat#3270]
**问题描述 / Problem Description**
使用LLaMA-Factory-0.5.3的lora进行微调后，将训练生成的文件复制到本项目路径下带有peft的目录中，启动项目后未发现训练后的模型被加载，只加载了基础模型。LLaMA-Factory中能加载训练后模型

LLaMA-Factory生成文件及本项目peft路径如下。chatglm2是名字写错了，训练用的glm3
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/401566be-78b2-43dd-9146-bd3596367eb5)

adapter_config.json配置如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/bf3976b0-5731-4369-b21c-e7f64cd44c57)

基础模型路径如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/9b00612b-74be-4829-88ce-fbe83196c132)

startup.py中添加的peft路径
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/8b7ce3cb-3de5-4200-a5a2-45392c3659fe)

model_config.py中添加的模型名和路径
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/ceb40098-20c0-49ea-862c-1e819faac588)

项目成功启动，控制台中有报错信息的地方如下
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/5811fd22-1b1d-474b-8fb3-e84ee653d5b7)

在页面模型栏选择添加的模型，加载完成后报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/9881434b-45f6-40a5-8a1e-fdaf19a11d3a)

尝试使用LLaMA-Factory导出功能，导出会自动合并。将合并模型放入基础模型目录下项目启动失败并报错
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/a3ec55cb-558f-4424-8609-92da9d72a180)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/a31ed6e7-96cd-4113-8615-c94ffadec9b8)

**预期的结果 / Expected Result**
使用LLaMA-Factory自带加载模型功能能产生预期结果

**环境信息 / Environment Information**
- langchain-ChatGLM 版本v2.0.1 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 操作系统及版本 / win10安装wsl2 ubuntu22.04虚拟机
- Python 版本 / Python version:conda 安装python3.10.12

**Comment by zRzRzRzRzRzRzR** [comment]
这不是报错了吗？ 尝试先解决报错的问题。我们是要放入peft模型，不知道你用的是什么模型

**Comment by nolynn** [comment]
这个问题怎么解决的，我也遇到该问题了。

**Comment by goodmaney** [comment]
> 这个问题怎么解决的，我也遇到该问题了。 @goodmaney

把路径全部换成绝对路径解决了。但是把合并后的模型放项目里还报错

**Comment by nolynn** [comment]
文档中要求有.bin 我看你微调后也没有 pytorch的.bin 文件，这个问题是怎么解决的。 @goodmaney 我现在想用 chatchat 集成 lora 切片遇到了点问题，有时间的话希望指教一下。

**Comment by ribun123** [comment]
> 文档中要求有.bin 我看你微调后也没有 pytorch的.bin 文件，这个问题是怎么解决的。 @goodmaney 我现在想用 chatchat 集成 lora 切片遇到了点问题，有时间的话希望指教一下。

不需要.bin文件，直接用llama-factory微调出来的lora，填好绝对路径即可

**Comment by ZhongQiyu** [comment]
单独拉一个镜像再合并下看吧
