### ISSUE TITLE
agent模式下以下代码if语句走chatglm3 initialize_glm3_agent逻辑如何能调用到工具？

### ISSUE THREAD

**Issue by Andy1018** [chatchat-space/Langchain-Chatchat#3271]
if "chatglm3" in model_container.MODEL.model_name or "zhipu-api" in model_container.MODEL.model_name:
            agent_executor = initialize_glm3_agent(
                llm=model,
                tools=tools,
                callback_manager=None,
                prompt=prompt_template,
                input_variables=["input", "intermediate_steps", "history"],
                memory=memory,
                verbose=True,
            )
        else:
            agent = LLMSingleActionAgent(
                llm_chain=llm_chain,
                output_parser=output_parser,
                stop=["\nObservation:", "Observation"],
                allowed_tools=tool_names,
            )
            agent_executor = AgentExecutor.from_agent_and_tools(agent=agent,
                                                                tools=tools,
                                                                verbose=True,
                                                                memory=memory,
                                                                )

**Comment by zRzRzRzRzRzRzR** [comment]
因为chatglm3格式和其他模型不太一样，得专门适配，本质还是langchian的react agent
