### ISSUE TITLE
http 调用大模型应该怎么实现呢？

### ISSUE THREAD

**Issue by renoyuan** [chatchat-space/Langchain-Chatchat#3281]
您好，我有多个大模型服务。可能对于不同大模型服务会封装一些方法。希望通过Langchain-Chatchat 以http的方式来进行统一的调度，请问我该怎去实现会比较合适呢？

我阅读 server/chat/chat.py 源码试图去找到答案，但是代码嵌套以及langchain中的异步调用链让我眼花缭乱。

**Comment by renoyuan** [comment]
和我需要的不太一样，我希望是不新增改变服务原有接口的基础上实现，并且之前的参数信息也尽可能的去复用这样子，不过也谢谢你的智能建议

**Comment by zRzRzRzRzRzRzR** [comment]
好像不增加不能改吧。。一定要新增服务

**Comment by Yangshirui01** [comment]
怎么链接私有的大模型服务
