### ISSUE TITLE
如果要在知识库返回的内容中附带图片连接该怎么处理呢？

### ISSUE THREAD

**Issue by goldmei** [chatchat-space/Langchain-Chatchat#3282]
如果要在知识库返回的内容中附带图片连接该怎么处理呢？

**Comment by guodastanson** [comment]
第三个问题: 模型回答的时候有时候会给回答加<回答></回答>的标签，这种如何去除？
![微信图片_20240313100011](https://github.com/chatchat-space/Langchain-Chatchat/assets/26060938/a45ccad8-9a44-4e69-8d38-09738f5cd816)
第四个问题:在你提一个问题时，模型有时候会自己重复提问回答，生成<Round2> <Round3>，而且有时候Round都是一模一样的内容，这种又是什么原因呢

**Comment by zRzRzRzRzRzRzR** [comment]
知识库直接跳过了图片不处理的。
自问自答是你没有更新chatglm3最新的huggingface配置文件

**Comment by guodastanson** [comment]
@zRzRzRzRzRzRzR 我用modelscope下的模型，我再看看更新。谢谢！

**Comment by zixiaotan21** [comment]
@goldmei 同样遇到这个问题 想问问楼主解决了吗
