### ISSUE TITLE
PDF文件采用RapidOCRPDFLoader解析然后嵌入向量库速度很慢  / 知识库问答大模型兜底配置

### ISSUE THREAD

**Issue by guodastanson** [chatchat-space/Langchain-Chatchat#3286]
问题1:PDF解析用的python工具RapidOCRPDFLoader，我48核的服务器，解析起来都是占满了，速率一般20-40s/it，求问这个过程能否调GPU进行加速解析。
问题2:知识库问答没检索到相关内容时怎么让模型直接回答预设的模板，而不是通过它自己的知识乱答？之前用星火的api是在接口上有调用的兜底选项的，求问langchain-chat这里是否可以配置，还是说要自己封装或者修改代码

**Comment by guodastanson** [comment]
第二个问题详细描述：使用langchain-chat选取知识库问答，模型选择chatGLM3-6b（其他模型其实也一样），在prompt中描述为当知识库中未搜索到相关内容时请直接回答“暂未找到相关内容”，不使用模型自己生产答案。实际操作时提问，模型未从milvus向量库中的知识库找到匹配内容时，模型仍然会自己回答一段内容。请问如何在此种情况让模型不要做出自行回答的动作？

**Comment by guodastanson** [comment]
![Uploading 微信图片_20240313100011.png…]()

第三个问题: 模型回答的时候有时候会给回答加<回答></回答>的标签，这种如何去除？
第四个问题:在你提一个问题时，模型有时候会自己重复提问回答，生成 ，而且有时候Round都是一模一样的内容，这种又是什么原因呢

**Comment by guodastanson** [comment]
@dosubot

**Comment by zRzRzRzRzRzRzR** [comment]
安装GPU版本就行
