### ISSUE TITLE
增加知识库问答界面的用户反馈功能

### ISSUE THREAD

**Issue by xzl12080** [chatchat-space/Langchain-Chatchat#3292]
我想在项目中增加知识库问答的界面用户反馈功能，因为目前好像只有llm对话才有这个功能，但是我发现在代码dialogue.py里面如果要增加反馈需要用到message_id，所以我就找到knowledge_base_chat这个异步函数给它加上了message_id，但我发现好像这个反馈功能只能用一次，下一次再问的话如果不点击清空对话就无法使用
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/139093739/62ee2d0f-4b0c-4f1f-acea-4cf29f864821)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/139093739/b2636229-fd35-47d7-8349-d19456e6c70f)

**Comment by zRzRzRzRzRzRzR** [comment]
是的，这部分没做，0.2.x不在维护了，所以可能得自己加

**Comment by linaiyue** [comment]
请问大佬，你解决了吗，可以分享一下如何增加这块吗我也有这个需求

**Comment by xzl12080** [comment]
> 请问大佬，你解决了吗，可以分享一下如何增加这块吗我也有这个需求

我写了篇帖子，你可以参考这篇帖子修改，http://t.csdnimg.cn/faRHd

**Comment by Shujie-Wu** [comment]
> > 请问大佬，你解决了吗，可以分享一下如何增加这块吗我也有这个需求
> 
> 我写了篇帖子，你可以参考这篇帖子修改，http://t.csdnimg.cn/faRHd

您好，帖子好像找不到了，可以重新分享一下吗
