### ISSUE TITLE
[BUG] 使用chatglm-6-b-128k出现自问自答，停不下来的情况

### ISSUE THREAD

**Issue by nmbtwzt** [chatchat-space/Langchain-Chatchat#3295]
**问题描述 / Problem Description**
使用chatglm-6-b-128k出现自问自答，停不下来的情况

![微信图片_20240313110149](https://github.com/chatchat-space/Langchain-Chatchat/assets/50111234/67c9ef0e-d288-43f2-b5ed-a62e2bc288a5)

**复现问题的步骤 / Steps to Reproduce**
1.使用chatglm3-6b-128k
2.无论问答什么内容，都会出现自问自答情况。

**预期的结果 / Expected Result**
回答完毕后停止。

**实际结果 / Actual Result**
回答当前问题后，不停自问自答，无法停止。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B-128k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
想通过添加repetition_penalty来解决，但是未找到参数修改位置，希望可以指明。

**Comment by zRzRzRzRzRzRzR** [comment]
或许应该去128k模型提个issue，6b正常吗

**Comment by nmbtwzt** [comment]
> 或许应该去128k模型提个issue，6b正常吗

感谢回复，6b正常，32k在知识库问答时也会无限重复，但是总体上还可以使用，128k完全无法使用。
