### ISSUE TITLE
Vllm模式启动模型推理能力会下降吗，会出现问问题回答不完整甚至不返回的现象，server_config.py里面有哪些配置影响上述问题吗？另外load_format':'auto'这有哪几个配置，到哪去查看？

### ISSUE THREAD

**Issue by Andy1018** [chatchat-space/Langchain-Chatchat#3303]
Vllm模式启动模型推理能力会下降吗，会出现问问题时回答不完整甚至不返回的现象，server_config.py里面有哪些配置影响上述问题吗？另外load_format':'auto'有哪几个配置项，到哪去查看？

**Comment by Andy1018** [comment]
@dosu-bot 这是vllm模式chatglm3-6b模型的输出，为什么带着<br/>,如何配置处理
好的，北京是一座拥有悠久历史和丰富文化的城市。以下是一些建议的旅游景点和活动：<br><br>1. 故宫博物院：北京的故宫是中国古代皇家宫殿，也是世界上最大的古代木质建筑群。<br><br>2. 天安门广场：作为北京的标志性地标，天安门广场是中国的象征之一，也是世界上最大的城市广场之一。<br><br>3. 颐和园：颐和园是北京著名的皇家园林，被誉为“皇家园林博物馆”，是中国古代建筑和园林艺术的杰出代表。<br><br>4. 长城：长城是中国古代的军事防御工事，也是世界文化遗产之一，是中国的象征之一。<br><br>5. 王府井大街：王府井大街是北京的著名商业街，拥有各种古老的店铺和品牌，也是品尝北京美食的好去处。<br><br>此外，您还可以尝试北京的特色美食，如北京烤鸭、炸酱面等。希望这些建议能对您有所帮助，祝您在北京旅途愉快！

**Comment by zRzRzRzRzRzRzR** [comment]
vllm 模型效果运行能力下降了，掉到原来的8成吧，不返回应该不对

**Comment by Andy1018** [comment]
@dosu-bot vllm启动高并发时，问答交互，回答时候偶尔带着<|assistant|> “br/”等标签
