### ISSUE TITLE
[BUG] 阿里千问请求报错，似乎阿里升级了，需要适配

### ISSUE THREAD

**Issue by xike110** [chatchat-space/Langchain-Chatchat#3306]
模型服务灵积-通义千问qwen-max 模型 请求报错
2024-03-12 16:39:32 | INFO | httpx | HTTP Request: POST http://127.0.0.1/:21006/worker_generate_stream "HTTP/1.1 200 OK"
2024-03-12 16:39:32 | ERROR | model_worker | 请求千问 API 时发生错误：{'error_code': <httpstatus.internal_server_error:>, 'text': 'Preprocessor error', 'error': {'message': 'Preprocessor error', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-03-12 16:39:32,883 - utils.py[line:38] - ERROR: An error occurred during streaming</httpstatus.internal_server_error:>
![Snipaste_2024-03-12_16-43-41](https://github.com/chatchat-space/Langchain-Chatchat/assets/39672048/8d66fc32-e9e8-480d-8f39-4c8517ab3296)

**Comment by zRzRzRzRzRzRzR** [comment]
在0.3.x会都统一为openai格式

**Comment by xike110** [comment]
> 在0.3.x会都统一为openai格式

能不能说一下什么问题，我切换线上qwen-max-1201  接口没问题，其他千问接口都会出这个错

**Comment by xike110** [comment]
我项目再线上跑不能，等更新，我自己尝试修复下

**Comment by zixiaotan21** [comment]
同样遇到这个问题，想问问楼主解决了吗

**Comment by xike110** [comment]
我是楼主，已经解决了，问题在与阿里那边升级了API  你提交的历史消息，要保证一问，一答得顺序

**Comment by xike110** [comment]
> 同样遇到这个问题，想问问楼主解决了吗

我是楼主，已经解决了，问题在与阿里那边升级了API  你提交的历史消息，要保证一问，一答得顺序

**Comment by zixiaotan21** [comment]
噢噢，我是调用的qwen-max 模型来做知识库问答，我目前的情况是：
1. 答案能检索出来，但LLM回答不上来
2. 显示的是和楼主一样的 请求千问 API 时发生错误：{'error_code': <HTTPStatus.INTERNAL_SERVER_ERROR: 500>, 'text': 'Role must be user or assistant and Content length must be greater than 0', 'error': {'message': 'Role must be user or assistant and Content length must be greater than 0', 'type': 'invalid_request_error', 'param': None, 'code': None}}
想请教一下，一问，一答的顺序是指什么呀

**Comment by zixiaotan21** [comment]
我换了qwen-max-1201去跑，好像就没有出现qwen-max的问题了

**Comment by xike110** [comment]
> 我换了qwen-max-1201去跑，好像就没有出现qwen-max的问题了

qwen-max-1201  升级延后，早晚也是不能用得，我换了qwen-max-1201也正常了，你换qwen-max  不带历史记录，也会正常得，重点是，你提交的history历史聊天，记录要保持每个提问，都会有一个回答
![Uploading 03_11-17-53.png…]()

**Comment by xike110** [comment]
![03_11-17-53](https://github.com/chatchat-space/Langchain-Chatchat/assets/39672048/52307ab9-49d1-4068-8712-be4865ed0696)

**Comment by xike110** [comment]
> 我换了qwen-max-1201去跑，好像就没有出现qwen-max的问题了

阿里会检查，每个回答是不是一对（一问一答），如果不带历史记录正常，带历史记录是一对（一问一答）正常，

**Comment by zixiaotan21** [comment]
噢噢我明白了，就是要保证“一问一答”的形式，谢谢楼主大佬解答！
但我换回qwen-max模型，出现的问题是：LLM根本就不回答，

<img width="946" alt="屏幕截图 2024-04-03 112553" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/4de9a4a3-b941-4667-9f5f-46993ac1e1b8">

所以会出现如下报错，想问问楼主会出现这种情况吗？
2024-04-03 11:25:02 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21006/worker_generate_stream "HTTP/1.1 200 OK"
2024-04-03 11:25:03 | ERROR | model_worker | 请求千问 API 时发生错误：{'error_code': <HTTPStatus.INTERNAL_SERVER_ERROR: 500>, 'text': 'Role must be user or assistant and Content length must be greater than 0', 'error': {'message': 'Role must be user or assistant and Content length must be greater than 0', 'type': 'invalid_request_error', 'param': None, 'code': None}}
2024-04-03 11:25:03,255 - utils.py[line:38] - ERROR: An error occurred during streaming
Traceback (most recent call last):
  File "C:\Users\butterfly\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "C:\Users\butterfly\anaconda3\envs\chatchat_env\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
2024-04-03 11:25:03,271 - utils.py[line:40] - ERROR: APIError: Caught exception: An error occurred during streaming

**Comment by zixiaotan21** [comment]
网络搜索结果那里是有结果的，所以我觉得应该不是搜索引擎bing的问题，可能问题还是在LLM那里~

**Comment by zhichengzhou98** [comment]
> 噢噢我明白了，就是要保证“一问一答”的形式，谢谢楼主大佬解答！ 但我换回qwen-max模型，出现的问题是：LLM根本就不回答，
> 
> <img alt="屏幕截图 2024-04-03 112553" width="946" src="https://private-user-images.githubusercontent.com/142043181/319022965-4de9a4a3-b941-4667-9f5f-46993ac1e1b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMzkzMDYsIm5iZiI6MTcxNzAzOTAwNiwicGF0aCI6Ii8xNDIwNDMxODEvMzE5MDIyOTY1LTRkZTlhNGEzLWI5NDEtNDY2Ny05ZjVmLTQ2OTkzYWMxZTFiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQwMzE2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWMxM2I2ZThlOTA2NTgxNmQ3ZjNhN2Q0ODBiYzc2NDRmMWU5YjIxNTM3ZmY0ZWQ5YjgyNjg3MjhlMDgyNDI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WLPMR9W9kWHBCs1rx2pX8o8ZpWOm4T6S7Xp8ngVuEzs">
> 所以会出现如下报错，想问问楼主会出现这种情况吗？ 2024-04-03 11:25:02 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21006/worker_generate_stream "HTTP/1.1 200 OK" 2024-04-03 11:25:03 | ERROR | model_worker | 请求千问 API 时发生错误：{'error_code': <HTTPStatus.INTERNAL_SERVER_ERROR: 500>, 'text': 'Role must be user or assistant and Content length must be greater than 0', 'error': {'message': 'Role must be user or assistant and Content length must be greater than 0', 'type': 'invalid_request_error', 'param': None, 'code': None}} 2024-04-03 11:25:03,255 - utils.py[line:38] - ERROR: An error occurred during streaming Traceback (most recent call last): File "C:\Users\butterfly\Langchain-Chatchat\server\utils.py", line 36, in wrap_done await fn File "C:\Users\butterfly\anaconda3\envs\chatchat_env\Lib\site-packages\langchain\chains\base.py", line 385, in acall raise e 2024-04-03 11:25:03,271 - utils.py[line:40] - ERROR: APIError: Caught exception: An error occurred during streaming

我也出过类似的问题，层主解决了吗？ 我用的Spring Cloud Starter Alibaba AI 2023.0.1.0，默认模型"qwen-turbo"
com.alibaba.dashscope.exception.ApiException: {"statusCode":400,"message":"Range of input length should be [1, 6000]","code":"InvalidParameter","isJson":true,}

**Comment by RRRoger** [comment]
> 噢噢，我是调用的qwen-max 模型来做知识库问答，我目前的情况是：
> 
> 1. 答案能检索出来，但LLM回答不上来
> 2. 显示的是和楼主一样的 请求千问 API 时发生错误：{'error_code': <HTTPStatus.INTERNAL_SERVER_ERROR: 500>, 'text': 'Role must be user or assistant and Content length must be greater than 0', 'error': {'message': 'Role must be user or assistant and Content length must be greater than 0', 'type': 'invalid_request_error', 'param': None, 'code': None}}
>    想请教一下，一问，一答的顺序是指什么呀

请问您解决了吗 好像我内容多了 就报这个错误了
