### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 7.652161GB memory on GPU 0, 20.428650GB memory has been allocated 

### ISSUE THREAD

**Issue by guodastanson** [chatchat-space/Langchain-Chatchat#3315]
使用RapidOCRPDFLoader解析PDF，用的paddle-gpu进行GPU处理。一开始是正常的，现在解析一个3MB的PDF就报内存不足。
我这边是两个3090GPU，paddle只调了GPU0，nvidia-smi占用是6G/24G，还剩接近18G的显存。
报错如下:
----------------------
Error Message Summary:
----------------------
ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 7.652161GB memory on GPU 0, 20.428650GB memory has been allocated and available memory is only 3.255493GB.

显存占用如下图:
![微信图片_20240314094606](https://github.com/chatchat-space/Langchain-Chatchat/assets/26060938/0b213c89-9ae0-45c3-a568-7bfa88db3b57)

**Comment by zRzRzRzRzRzRzR** [comment]
或许应该去paddle 那边提出issue，我们没有修改任何paddle ocr的代码
