### ISSUE TITLE
能增加API的多用户访问接口部署吗？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#333]
默认部署程序仅支持单用户访问，多用户则需要排队访问。测试过相关的几个Github多用户工程，但是其中一些仍然不满足要求。本节将系统介绍如何实现多用户同时访问ChatGLM的部署接口，包括http、websocket（流式输出，stream）和web页面等方式，主要目录如下所示。

        （1）api.py http多用户并行

        （2）api.py websocket多用户并行（流式输出，stream）

        （3）web_demo.py多用户并行
————————————————
版权声明：本文为CSDN博主「Coding的叶子」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/suiyingy/article/details/130412307

**Comment by 18591789167** [comment]
还是看不懂 需要改哪里
