### ISSUE TITLE
[BUG] 上传CSV文件。在CSVLoader中修改了Page_Content和Metadata的抓取逻辑后，log显示未生效

### ISSUE THREAD

**Issue by XienXX** [chatchat-space/Langchain-Chatchat#3332]
**问题描述 / Problem Description**
上传CSV文件。在CSVLoader中修改了Page_Content和Metadata的抓取逻辑后，log显示未生效

**复现问题的步骤 / Steps to Reproduce**
1. 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125440255/f3d2c229-dd0e-412d-85b8-ce088744f641)
这是我在FilteredCSVloader.py文件中做的修改，目的是想抓取csv中的1、2列作为Page_Content，剩下所有列作为Metadata。
2. 
修改后运行，后台却显示
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125440255/e7ac12fe-6d03-4186-a317-d10dd85b3e0c)
可以看到，metadata里面只有默认的source和row两对。经过检查，与修改前是一样的，也就是csvloader处的修改并没有生效

**预期的结果 / Expected Result**
请帮忙检查下是否哪一块操作有问题，还是说这一块的抓取逻辑是在别的文件下修改，谢谢！

**Comment by XienXX** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125440255/55a3cf87-653d-44c0-a4e2-c93f1749fddb)
看了下，FilteredCSVLoader默认是被注释掉了。请问该如何启用它呢？另外，CSVLoader的文件又是在哪个路径呢

**Comment by Sololololo** [comment]
CSVLoader是底层库中的类，FilteredCSVLoader继承了这个类

**Comment by XienXX** [comment]
> CSVLoader是底层库中的类，FilteredCSVLoader继承了这个类

那目前FilteredCSVLoader是否可用呢？不知道该如何指定。

**Comment by Sololololo** [comment]
可用呀，我已经验证过了，你把dict list里面CSVLoader注释掉，把FilteredCSVLoader取消注释就好了。剩下的就是一些简单的import操作，溯源一下就好。import一下这个Class，然后document_loader那个文件夹里的init更新一下。知识库需要重新构建，要不然会报错

**Comment by XienXX** [comment]
> FilteredCSVloader

能麻烦问下您import的时候是怎么操作的吗？需要修改langchain库中的csvloader不？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125440255/f4f24016-b211-434d-84d1-83ae29a2b1d9)
我目前试了下，直接修改csvloader，然后跑recreate重建知识库。可以看到我在csvloader的metadata中专门加了一组test键，但是在log中还是未见到这个test键的内容

**Comment by zixiaotan21** [comment]
想问问楼主，上传csv文件你是在知识库中上传，还是在对话中选择文件对话上传呀？我也想将FAQ文档的csv格式上传到知识库，但没搞懂该怎么上传呢？

**Comment by Chengyang852** [comment]
> 想问问楼主，上传csv文件你是在知识库中上传，还是在对话中选择文件对话上传呀？我也想将FAQ文档的csv格式上传到知识库，但没搞懂该怎么上传呢？

请问实现了么
