### ISSUE TITLE
当问题描述不够详细时是否能够引导提问

### ISSUE THREAD

**Issue by goldmei** [chatchat-space/Langchain-Chatchat#3335]
例如我在知识库上传了几条记录：
1、登录失败了，提示账号不对，此时需要检查账号是否正确。
2、登录失败了，提示密码不对，此时需要检查密码是否正确。

当我输入问题：登录失败了，是否可以根据以下两种情况回答
第一种情况：
提问：登陆失败了
回答：登录失败了，能否描述以下失败原因，是账号不对还是密码不对
提问：账号不对
回答：登录失败了，提示账号不对，此时需要检查账号是否正确

第二种情况：
提问：登陆失败了
回答：登录失败了，可能的原因是
1、账号不对
2、密码不对
请选择你要了解的原因
提问：2
回答：登录失败了，提示密码不对，此时需要检查密码是否正确

如果要实现上面的效果改怎么处理

**Comment by zRzRzRzRzRzRzR** [comment]
暂时没有相关计划
