### ISSUE TITLE
[BUG] Chatglm3-6b的Agent模式，无法调用tools 

### ISSUE THREAD

**Issue by CSZHK** [chatchat-space/Langchain-Chatchat#3337]
**问题描述 / Problem Description**
Chatglm3-6b的Agent模式，无法调用tools 
**复现问题的步骤 / Steps to Reproduce**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5602838/c519564c-9f12-410e-aae1-e252f08e88c4)

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/5602838/842a76cc-becb-4581-a693-32b5935966f9)

**Comment by CSZHK** [comment]
其他工具也不行

**Comment by zRzRzRzRzRzRzR** [comment]
温度拉低

是在不行

加上 使用计算器工具计算 xxx

glm3-6b模型是比较早的模型了，tools能力跟最新的开源模型没法比

**Comment by CSZHK** [comment]
> 温度拉低
> 
> 是在不行
> 
> 加上 使用计算器工具计算 xxx
> 
> glm3-6b模型是比较早的模型了，tools能力跟最新的开源模型没法比

试了还是不行。温度参数有什么影响？
然后推荐使用什么模型进行agent对话
