### ISSUE TITLE
如何使用高级知识库工具，智能选择调用多个或者单个知识库并查询内容。

### ISSUE THREAD

**Issue by zeqi2000** [chatchat-space/Langchain-Chatchat#3339]
wiki中提到可以智能选择调用多个或者单个知识库并查询内容，请问这个功能在哪里使用呢？

**Comment by zeqi2000** [comment]
@zRzRzRzRzRzRzR 您好，打扰一下，在更新说明中有看到您对wiki的维护，可以帮忙看一下wiki中所说高级（或者进阶）知识库工具如何使用吗，感谢！
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/48551609/07a79817-82c8-4fd2-ba77-fbf41117fbae)

**Comment by yumu7777777** [comment]
您好，您找到怎么从多个知识库中问答了吗

**Comment by zRzRzRzRzRzRzR** [comment]
这个仓库没支持
