### ISSUE TITLE
多卡部署

### ISSUE THREAD

**Issue by ZTurboX** [chatchat-space/Langchain-Chatchat#334]
用单机多卡或多机多卡，fastapi部署模型，怎样提高并发

**Comment by imClumsyPanda** [comment]
可能可以通过每个卡部署一个chatglm模型，并单独执行一个api，再通过消息队列分配到各卡执行的方式避免并发消息的等待处理时长过长

**Comment by dizhenx** [comment]
> 可能可以通过每个卡部署一个chatglm模型，并单独执行一个api，再通过消息队列分配到各卡执行的方式避免并发消息的等待处理时长过长

不能多卡部署一个模型吗？然后并发请求一个端口

**Comment by Gy1900** [comment]
请问你做到了吗？你现在的并行部署方案是啥啊

**Comment by ZTurboX** [comment]
> 请问你做到了吗？你现在的并行部署方案是啥啊

每张卡单独起个服务，用nginx做负载均衡

**Comment by Gy1900** [comment]
请问你每张卡起一个服务，代码咋改的？我改了 
1. /configs/model_config.py 设置 LLM_DEVICE = "cuda:数字"   

2. /models/loader/loader.py num_gpus = 1 +
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27496549/22471aa3-541c-4660-bdc6-ad388e696dd6)
但是只有第一张卡上的gpu使用率拉高了，启动第三个服务就OOM了。

 @ZTurboX 大佬可以说下你是怎么改的吗？
