### ISSUE TITLE
估计是你nginx或者服务器的限制，streanlit是200mb的

### ISSUE THREAD

**Issue by litongyun233** [chatchat-space/Langchain-Chatchat#3344]
估计是你nginx或者服务器的限制，streanlit是200mb的

_Originally posted by @zRzRzRzRzRzRzR in https://github.com/chatchat-space/Langchain-Chatchat/issues/3307#issuecomment-1994282861_

**Comment by litongyun233** [comment]
上传大于2MB的文件出现报错：AxiosError: Request failed with status code 413
看到说可能是nginx或者服务器的限制，streamlit是200mb的，请问应该如何排查是否是Nginx或者服务器的限制呢？@dosu-bot

**Comment by zRzRzRzRzRzRzR** [comment]
你可以在本地试试 localhost
