### ISSUE TITLE
WEBUI能否指定知识库目录？

### ISSUE THREAD

**Issue by xuji755** [chatchat-space/Langchain-Chatchat#335]
**功能描述 / Feature Description**
webui.py能否在配置种直接指定某个知识库目录，而不是必须通过上传。这样便于定期自动更新知识库。

**实现建议 / Implementation Suggestions**
建议在configs中增加知识库目录的配置项，最好支持多个目录。这样就便于自动更新知识库，也更便于用于生产。

**Comment by imClumsyPanda** [comment]
请问这样操作的话，是还要检测一下增量更新的文件有哪些吗？因为目前知识库相当于每次知识上传后文件加载、分句、向量化后形成的向量库
