### ISSUE TITLE
[BUG] Cannot read properties of undefined (reading 'error')

### ISSUE THREAD

**Issue by xuji755** [chatchat-space/Langchain-Chatchat#336]
**问题描述 / Problem Description**
启动后不管怎么样，对话都显示下面错误：
Cannot read properties of undefined (reading 'error')

**Comment by asteriskni** [comment]
使用api+vue前端碰到一样的问题，有什么解决的办法吗？

**Comment by guojishuo** [comment]
一样的问题. [愁眉苦脸]

**Comment by elven2016** [comment]
也遇到这个问题了，用了api方式，这个问题现在有找到问题原因了吗？

**Comment by yunchang123** [comment]
请问这个问题有人解决了吗
