### ISSUE TITLE
[BUG] web页面打不开,Chatchat WEBUI Server端口开启不了但也没报错，头天能打开隔天就不行了

### ISSUE THREAD

**Issue by goodmaney** [chatchat-space/Langchain-Chatchat#3366]
**问题描述 / Problem Description**
运行后显示启动成功，控制台没报错
：You can now view your Streamlit app in your browser.
OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
 You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

但是控制台看监听的端口里没Chatchat WEBUI Server端口8501，OpenAI API Server和Chatchat  API  Server端口都正常监听且能通过web页面访问。头天运行没什么问题能正常打开WEBUI Server，什么也没动第二天就这样了，也没挂代理。Chatchat WEBUI Server网页显示 拒绝了我们的连接请求，页面也没http报错码，日志里也没相关记录。更换WEBUI Server端口后重启无法修复

**Comment by Vincent-ch99** [comment]
请问你有解决这个问题吗，我也遇到了同样的问题

**Comment by wo2ow** [comment]
我也有一样的问题，想请问你们解决了吗
