### ISSUE TITLE
[BUG] 1 validation error for HuggingFaceEmbeddings model_kwargs extra fields not permitted.

### ISSUE THREAD

**Issue by realalexsun** [chatchat-space/Langchain-Chatchat#337]
模型加载到 100% 后出现问题：
1 validation error for HuggingFaceEmbeddings model_kwargs extra fields not permitted.
模型未能成功加载

**Comment by imClumsyPanda** [comment]
请问方便截图提供一下更详细的报错信息吗

**Comment by realalexsun** [comment]
<img width="589" alt="截屏" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/76617477/c8673584-ff38-41f2-98d0-dc2eb07e429c">
重新加载后报同样的错误

**Comment by imClumsyPanda** [comment]
应该是因为langchain版本0.0.146版本以上才支持项目中的调用方式，所以需要保证langchain最低为0.0.146版本
