### ISSUE TITLE
API 接口新增功能

### ISSUE THREAD

**Issue by zhanland** [chatchat-space/Langchain-Chatchat#3370]
是否能在 api接口中添加 以下功能  
1、获取知识库中文件的详细信息 ，现在只能获取到文件名称。
2 单个文件重新添加向量库 
3 单个文件 从向量库中删除

**Comment by zRzRzRzRzRzRzR** [comment]
0.2版本不会在更新，0.3可能可以做，但是不是优先级高的需求
