### ISSUE TITLE
[BUG] 使用windows 英伟达显卡启动 对话chatglm3-6b-int8模型报错

### ISSUE THREAD

**Issue by MerCry** [chatchat-space/Langchain-Chatchat#3377]
**问题描述
使用本地模型, chatglm3-6b-int8 (chatglm3-6b int8量化后模型)，启动后 对话后台会报错。
 

**复现问题的步骤 
1. 修改 modelConfig为量化模型，并且地址修改为本地路径
2. 启动 python startup.py -a
3. 界面可以正常显示，模型也可以正常加载（使用单独的chatglm3-6b-int8是可以对话的）
4. 发送任何语句后，后台报错。

**预期的结果
和使用单独的 chatglm3-6b-int8 相同正常对话

**实际结果 / Actual Result**
报错ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "H:\trainModel\Langchain-Chatchat\server\utils.py", line 36, in wrap_done
    await fn
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain\chains\base.py", line 385, in acall
    raise e
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain\chains\base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain\chains\llm.py", line 275, in _acall
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain_core\language_models\chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain_core\language_models\chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain_community\chat_models\openai.py", line 523, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain_core\language_models\chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "D:\anaconda\envs\langchain\Lib\site-packages\langchain_community\chat_models\openai.py", line 494, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

**环境信息 
- langchain-ChatGLM 版本0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型： chatglm3-6b-int8
- 使用的 Embedding 模型：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：  faiss
- 操作系统及版本 ：win10专业版
- Python 版本 / Python version: 3.11
- 其他相关环境信息 torch版本  2.1.2+cu121
-

**Comment by MerCry** [comment]
打印了报错的trunk值内容如下 ：
| INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'text': '**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(probability tensor contains either
 `inf`, `nan` or element < 0)', 'error_code': 50001}

**Comment by brian95827** [comment]
你windows是怎么启动的？我直接启动不了。。`python startup.py -a` 直接报错
```    
import pwd
ModuleNotFoundError: No module named 'pwd'
```
一查，windows系统就没有这个包。。

**Comment by l784669877** [comment]
> 你windows是怎么启动的？我直接启动不了。。`python startup.py -a` 直接报错
> 
> ```
> import pwd
> ModuleNotFoundError: No module named 'pwd'
> ```
> 
> 一查，windows系统就没有`pwd`这个包。。

网上有解决办法

**Comment by jxslykx** [comment]
> 你windows是怎么启动的？我直接启动不了。。`python startup.py -a`直接报错
> 
> ```
> import pwd
> ModuleNotFoundError: No module named 'pwd'
> ```
> 
> 一查，windows系统就没有`pwd`这个包。。

我也遇到过这个，我是这样修改的：
import platform

if platform.system() != 'Windows':
    import pwd
# import pwd，你可以试试

**Comment by brian95827** [comment]
> > 你windows是怎么启动的？我直接启动不了。。`python startup.py -a`直接报错
> > ```
> > import pwd
> > ModuleNotFoundError: No module named 'pwd'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 一查，windows系统就没有`pwd`这个包。。
> 
> 我也遇到过这个，我是这样修改的： import platform
> 
> if platform.system() != 'Windows': import pwd 找到报错的虚拟环境路径，找到那个文件里把import pwd注释了，替换成上面这个

我没改它，直接给它注释了，好像运行也没报错，不知道是不是没用，怕是个多余的`import`。

**Comment by l784669877** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David ***@***.***&gt;; 
发送时间: 2024年3月22日(星期五) 晚上6:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 使用windows 英伟达显卡启动 对话chatglm3-6b-int8模型报错 (Issue #3377)





  
你windows是怎么启动的？我直接启动不了。。python startup.py -a直接报错
 import pwd ModuleNotFoundError: No module named 'pwd'  
一查，windows系统就没有pwd这个包。。
  
我也遇到过这个，我是这样修改的：
 import platform
 
if platform.system() != 'Windows':
 import pwd
 
import pwd，你可以试试

**Comment by l784669877** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月22日(星期五) 晚上10:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] [BUG] 使用windows 英伟达显卡启动 对话chatglm3-6b-int8模型报错 (Issue #3377)





   
你windows是怎么启动的？我直接启动不了。。python startup.py -a直接报错
 import pwd ModuleNotFoundError: No module named 'pwd'  
一查，windows系统就没有pwd这个包。。
  
我也遇到过这个，我是这样修改的： import platform
 
if platform.system() != 'Windows': import pwd 找到报错的虚拟环境路径，找到那个文件里把import pwd注释了，替换成上面这个
  
我没改它，直接给它注释了，好像运行也没报错，不知道是不是没用，怕是个多余的import。

**Comment by MerCry** [comment]
已解决，量化模型需要添加如图内容 ，修改fastapi中对 chatglm模型的加载过程

**Comment by MerCry** [comment]
文件为 model_adapter.py   826行修改为 model = AutoModel.from_pretrained(
            model_path, trust_remote_code=True, **from_pretrained_kwargs
        ).half().cuda()

**Comment by Mioooooo** [comment]
请问你是怎么更改为[chatglm3-6b-int8模型，我这边怎么都替换不成功，麻烦指点

**Comment by MerCry** [comment]
1.替换model_config .py   所有chatglm3-6b  改为  chatglm3-6b-int8  ，地址改为本地路径地址
2.替换server_config.py   所有chatglm3-6b  改为  chatglm3-6b-int8 
3.解决pwd报错
4.修改fastapi中的文件  model_adapter.py 826行修改为 model = AutoModel.from_pretrained(
model_path, trust_remote_code=True, **from_pretrained_kwargs
).half().cuda()

**Comment by Mioooooo** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37464936/0be81605-ee67-43d8-982c-1613471f3951)
@MerCry

**Comment by MerCry** [comment]
哪里都可以，model_config中 所有 int8对应key的值 全部改为本地路径即可。 我下载的 模型 git地址为  https://huggingface.co/THUDM/chatglm-6b-int8   不是只有一个文件，按这个步骤来应该就可以，不行的话 我也没招。。

**Comment by Mioooooo** [comment]
啊，你这应该不是3-6b吧

**Comment by Mioooooo** [comment]
麻烦问下fastapi中的文件 model_adapter.py 这个文件在哪里呢
