### ISSUE TITLE
如何设置CPU运行

### ISSUE THREAD

**Issue by Yogier** [chatchat-space/Langchain-Chatchat#3380]
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cuda',
//此处cuda如何改为CPU

**Comment by Yogier** [comment]
不对 问题没有解决 依然在GPU上运行

**Comment by zRzRzRzRzRzRzR** [comment]
去server config中改
