### ISSUE TITLE
[BUG] 简洁阐述问题 / 模型reranker不成功

### ISSUE THREAD

**Issue by ShawnHoo7256** [chatchat-space/Langchain-Chatchat#3382]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
使用“Xorbits/bge-reranker-large”在reranker时不成功，并报错，模型本身没有问题，按照bge-reranker-large的demo测试过。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...' 在config文件中修改USE_RERANKER为True，模型是“bge-reranker-large”。
2. 点击 '...' / Click '...' 在知识库中直接提问
3. 滚动到 '...' / Scroll to '...'  -----------------model path------------------
4. 问题出现 / Problem occurs ERROR:    Exception in ASGI application

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
Exception in ASGI application 和 httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read) 报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.10.0  / langchain-ChatGLM3 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / ChatGLM3-6B-32k
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 20.04
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

运行知识库后问答：
2024-03-17 20:25:22,214 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
2024-03-17 20:25:22,215 - base.py[line:36] - INFO: thread 233356 开始操作：('bge-large-zh-v1.5', 'cuda')。初始化
2024-03-17 20:25:22,215 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/hoo/.cache/modelscope/hub/AI-ModelScope/bge-large-zh-v1___5
2024-03-17 20:25:23,840 - base.py[line:40] - INFO: thread 233356 结束操作：('bge-large-zh-v1.5', 'cuda')。初始化
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.68it/s]
2024-03-17 20:25:24,916 - base.py[line:36] - INFO: thread 233356 开始操作：('samples', 'bge-large-zh-v1.5')。初始化
2024-03-17 20:25:24,917 - faiss_cache.py[line:92] - INFO: loading vector store in 'samples/vector_store/bge-large-zh-v1.5' from disk.
2024-03-17 20:25:24,921 - loader.py[line:64] - INFO: Loading faiss.
2024-03-17 20:25:24,938 - loader.py[line:66] - INFO: Successfully loaded faiss.
/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/langchain_community/vectorstores/faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: METRIC_INNER_PRODUCT
  warnings.warn(
2024-03-17 20:25:24,948 - base.py[line:40] - INFO: thread 233356 结束操作：('samples', 'bge-large-zh-v1.5')。初始化
2024-03-17 20:25:24,948 - base.py[line:36] - INFO: thread 233356 开始操作：('samples', 'bge-large-zh-v1.5')。
2024-03-17 20:25:24,948 - base.py[line:40] - INFO: thread 233356 结束操作：('samples', 'bge-large-zh-v1.5')。
-----------------model path------------------
Xorbits/bge-reranker-large
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 580, in receive
    await self.message_event.wait()
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fcd857d5f10

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    |     sock = connection.create_connection(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    |     raise err
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    |     sock.connect(sa)
    | OSError: [Errno 101] Network is unreachable
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    |     response = self._make_request(
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    |     raise new_e
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    |     self._validate_conn(conn)
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1096, in _validate_conn
    |     conn.connect()
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connection.py", line 611, in connect
    |     self.sock = sock = self._new_conn()
    |                        ^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    |     raise NewConnectionError(
    | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fcd6af45950>: Failed to establish a new connection: [Errno 101] Network is unreachable
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    |     resp = conn.urlopen(
    |            ^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    |     retries = retries.increment(
    |               ^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Xorbits/bge-reranker-large/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcd6af45950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1261, in hf_hub_download
    |     metadata = get_hf_file_metadata(
    |                ^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    |     return fn(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1667, in get_hf_file_metadata
    |     r = _request_wrapper(
    |         ^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 385, in _request_wrapper
    |     response = _request_wrapper(
    |                ^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    |     response = get_session().request(method=method, url=url, **params)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    |     resp = self.send(prep, **send_kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    |     r = adapter.send(request, **kwargs)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    |     return super().send(request, *args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    |     raise ConnectionError(e, request=request)
    | requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Xorbits/bge-reranker-large/resolve/main/config.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fcd6af45950>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 720adbd5-8183-4102-8569-97b36de18da7)')
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/transformers/utils/hub.py", line 385, in cached_file
    |     resolved_file = hf_hub_download(
    |                     ^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    |     return fn(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1406, in hf_hub_download
    |     raise LocalEntryNotFoundError(
    | huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/media/hoo/Competition/ChatProject/Langchain-Chatchat_210/server/chat/knowledge_base_chat.py", line 92, in knowledge_base_chat_iterator
    |     reranker_model = LangchainReranker(top_n=top_k,
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/media/hoo/Competition/ChatProject/Langchain-Chatchat_210/server/reranker/reranker.py", line 49, in __init__
    |     self._model = CrossEncoder(model_name=model_name_or_path, max_length=1024, device=device)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/sentence_transformers/cross_encoder/CrossEncoder.py", line 39, in __init__
    |     self.config = AutoConfig.from_pretrained(model_name)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/transformers/models/auto/configuration_auto.py", line 1100, in from_pretrained
    |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/transformers/configuration_utils.py", line 634, in get_config_dict
    |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/transformers/configuration_utils.py", line 689, in _get_config_dict
    |     resolved_config_file = cached_file(
    |                            ^^^^^^^^^^^^
    |   File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/transformers/utils/hub.py", line 425, in cached_file
    |     raise EnvironmentError(
    | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like Xorbits/bge-reranker-large is not the path to a directory containing a file named config.json.
    | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
    +------------------------------------
2024-03-17 20:25:34,996 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_transports/default.py", line 111, in __iter__
    for part in self._httpcore_stream:
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
    raise exc from None
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
    for part in self._stream:
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 349, in __iter__
    raise exc
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 341, in __iter__
    for chunk in self._connection._receive_response_body(**kwargs):
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
    event = self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 220, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/hoo/Competition/ChatProject/Langchain-Chatchat_210/webui_pages/utils.py", line 168, in ret_sync
    for chunk in r.iter_text(None):
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_models.py", line 850, in iter_text
    for byte_content in self.iter_bytes():
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_models.py", line 829, in iter_bytes
    for raw_bytes in self.iter_raw():
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_models.py", line 887, in iter_raw
    for raw_stream_bytes in self.stream:
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_client.py", line 124, in __iter__
    for chunk in self._stream:
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_transports/default.py", line 110, in __iter__
    with map_httpcore_exceptions():
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/hoo/Workspace/env/conda3/envs/Langchain/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

**Comment by charleybin** [comment]
我也遇到同样的问题了。 一开始困惑了半天，发觉问题并不在网络上，实际原因是由于reranker出错引起。

错误信息如下：
---------error in rerank------------------ 
The expanded size of the tensor (874) must match the existing size (514) at non-singleton dimension 1.  Target sizes: [3, 874].  Tensor sizes: [1, 514]


得到这个错误信息需要修改一点代码。具体修改如下：

代码修改位置：knowledge_ase-chat.py

修改方法：把的docs = reranker_model.compress_documents(documents=docs, query=query) 加上try,catch如下：
            try:
                docs = reranker_model.compress_documents(documents=docs, query=query)
            except Exception as e:
                print("---------error in rerank------------------\n", e)



硬件配置： Apple M2 Pro Max  内存：64G  
运行系统： 14.4 (23E214)

**Comment by XienXX** [comment]
有解决办法不，我也遇到这个问题

**Comment by cc8476** [comment]
看了一些答案，有说截断的，如果截断了topK,那意义也就不大了

**Comment by UnknowZang** [comment]
看了这部分的代码，我观察到的还是在huggingface下载的过程中产生了报错，我奇怪的是这部分似乎没有做模型本地加载的处理，就是一定要连接去下载，可是我自己下载另行下载时问题不大的就是慢一些而已

**Comment by UnknowZang** [comment]
看了这部分的代码，我观察到的还是在huggingface下载的过程中产生了报错，我奇怪的是这部分似乎没有做模型本地加载的处理，就是一定要连接去下载，可是我自己下载另行下载时问题不大的就是慢一些而已，这部分代码会将模型下载到默认的.cache路径，而不是配置的模型路径

**Comment by Longleaves** [comment]
同样遇到了，解决了吗

**Comment by UnknowZang** [comment]
我先停用了该配置，晚点儿再研究一下


| |
张晋
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月18日 16:43 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] [BUG] 简洁阐述问题 / 模型reranker不成功 (Issue #3382) |

同样遇到了，解决了吗
