### ISSUE TITLE
[BUG] 自定义Agent问答，server/agent/custom_template.py中31行，这个if判断有何意义？？？？

### ISSUE THREAD

**Issue by liangpn** [chatchat-space/Langchain-Chatchat#3391]
**问题描述 / Problem Description**
自定义Agent问答，server/agent/custom_template.py中31行，这个if判断有何意义？？？？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/52708183/9d8ca6b2-3cb0-48dc-b17f-861287e8983f)
if not any(agent in model_container.MODEL for agent in SUPPORT_AGENT_MODEL) and self.begin:
其中model_container.MODEL是一个对象，而SUPPORT_AGENT_MODEL是一个字符串集合，这个if代码
肯定是会进去的，所以这个判断是为了什么？？？？

**复现问题的步骤 / Steps to Reproduce**
选择对话->自定义agent问答

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: centos
- Python 版本 / Python version: 3.10.12
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liangpn** [comment]
> @liangpn 嘿，又见面了！很高兴再次看到你提出的问题。希望一切都好。
> 
> 根据您提供的信息，我理解您在询问`server/agent/custom_template.py`文件中第31行的`if`判断的目的。这个`if`判断的目的是检查`SUPPORT_AGENT_MODEL`中指定的模型是否都没有在`model_container.MODEL`中加载，并且`CustomOutputParser`实例的`begin`属性是否为`True`。如果两个条件都满足，它会将`self.begin`设置为`False`，然后处理`llm_output`字符串，将其在第一次出现任何指定的`stop_words`的地方截断，这种情况下是"Observation:"。这样做是为了可能去除`llm_output`中与进一步处理无关的部分，专注于指定的`stop_words`之前的内容。
> 
> `SUPPORT_AGENT_MODEL`变量的目的是指定一个支持或需要自定义输出解析器正确功能的代理模型的列表或集合。这个变量用于条件检查，以确定生成输出的模型是否在这些支持的模型中。如果模型不受支持，解析器会通过删除某些停止词后的内容来修改输出，以防止在最终输出中包含无关或无意的信息。这确保了输出是根据支持模型定义的特定需求或约束进行定制和相关的。
> 
> 至于`server/agent/custom_template.py`文件中第31行的确切代码，它是：
> 
> ```python
>         action_input = parts[1].split("Action Input:")[1].strip()
> ```
> 
> 这行代码的目的是从`parts[1]`字符串中提取"Action Input:"后的内容，并去除前后的空格。
> 
> 如果您需要更多的解释或有其他问题，请随时提问。
> 
> ## Sources
> * [server/agent/custom_template.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/custom_template.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

我的问题是model_container.MODEL与SUPPORT_AGENT_MODEL根本没有可比性，SUPPORT_AGENT_MODEL是一个字符串集合、model_container.MODEL是一个对象，两者都没有可以比较的字段

**Comment by zRzRzRzRzRzRzR** [comment]
判断 model_container.MODEL 有没有在这个列表中

**Comment by liangpn** [comment]
> 判断 model_container.MODEL 有没有在这个列表中

可以说仔细点？？？？？我当然理解这段if的写法是为了判断 model_container.MODEL 有没有在这个列表中，
重点是，model_container.MODEL是一个ModelContainer类的实例，它是一个可迭代对象？能使用in操作符进行迭代？

**Comment by liangpn** [comment]
> 判断 model_container.MODEL 有没有在这个列表中

agent in model_container.MODEL 一个ChatOpenAI对象实例的键如何跟SUPPORT_AGENT_MODEL中的字符串元素比对？？？
按我理解是想将model_container.MODEL的model_name对应的值与SUPPORT_AGENT_MODEL中的字符串元素比对，如果相同则返回True，否则返回False；
if not model_container.MODEL.get('model_name') in SUPPORT_AGENT_MODEL and self.begin:
所以进行以上修改，请确认！！！！！ @zRzRzRzRzRzRzR

**Comment by liangpn** [comment]
> 判断 model_container.MODEL 有没有在这个列表中

agent in model_container.MODEL 将ChatOpenAI对象实例的属性值跟SUPPORT_AGENT_MODEL中的字符串元素值做比对？？？
按我理解，你是想将model_container.MODEL的model_name对应的值与SUPPORT_AGENT_MODEL中的字符串元素比对，如果相同则返回True，否则返回False
if not (model_container.MODEL.model_name in SUPPORT_AGENT_MODEL) and self.begin:
所以进行以上修改，请确认！！！！！ @zRzRzRzRzRzRzR
