### ISSUE TITLE
生成引用来源（citation）

### ISSUE THREAD

**Issue by BrightXiaoHan** [chatchat-space/Langchain-Chatchat#3395]
https://python.langchain.com/docs/use_cases/question_answering/citations
请问在生成答案时，是否能够支持生成引用来源（citation）呢，
![img_v3_0293_bd2d38b0-39d6-457d-b31b-2f40a8a4da5g](https://github.com/chatchat-space/Langchain-Chatchat/assets/25839309/fc62db05-7eee-4859-9e93-f779cb182457)
类似于这样，再回答旁边可以有一个链接，链接到知识库中的参考知识。

**Comment by zRzRzRzRzRzRzR** [comment]
这个是智谱清言的，我们暂时没考虑做这个功能

**Comment by BrightXiaoHan** [comment]
跟智谱轻言无关啊，langchain也支持这个功能。https://python.langchain.com/docs/use_cases/question_answering/citations
