### ISSUE TITLE
超算运行后startup.py一键启动后 部署成功 但是只能打开API的连接 无法打开WEBUI的连接

### ISSUE THREAD

**Issue by A-runaaaa** [chatchat-space/Langchain-Chatchat#3396]
![微信图片_20240318162513](https://github.com/chatchat-space/Langchain-Chatchat/assets/131651962/a09acac7-e19c-422b-893e-2308b04c0d8d)
在超算服务器上运行startup.py一件启动后 也是正常的读取模型部署模型，全部部署完之后有上面图片的日志，能够打开Streamlit的API界面但是无法打开webui的界面是什么原因呢，需要修改哪个地方么

**Comment by CRonaldo1997** [comment]
@A-runaaaa 同样的问题，请问解决了吗

**Comment by CRonaldo1997** [comment]
我把服务器防火墙关了就好了：
service firewalld stop
