### ISSUE TITLE
Agent问答是已经被禁用了吗？

### ISSUE THREAD

**Issue by willwilling** [chatchat-space/Langchain-Chatchat#3397]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/18168678/cf1c1479-a0cc-474a-a77b-a3e1ec06a0a5)

**Comment by willwilling** [comment]
不对呀  我发任何指令，agent的回复都是这样的，这是什么情况？
<img width="1072" alt="c79f87491ed36e2a8c93724db3367b4" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/18168678/41cef00e-7dd6-4c21-8472-2bc8ee725646">

**Comment by willwilling** [comment]
如上图，并没有调用到agent/tool_select中的函数

**Comment by devilmoom** [comment]
看不见你的后台调用逻辑，正常是可以调用的

**Comment by SWT-AITeam** [comment]
我执行agent妈也是不会执行tool，```
{"action": "Final Answer", "action_input": "Thought: To calculate 3^3, I need to call the calculate function with the argument '3'.\n"}
```
action每次都是Final Answer，可能是这个导致的，但是也不知道怎么调整？

**Comment by zRzRzRzRzRzRzR** [comment]
这个奶茶给你是能调用的，直接final answer是因为模型没有意识到想调用工具

**Comment by willwilling** [comment]
> 这个奶茶给你是能调用的，直接final answer是因为模型没有意识到想调用工具

怎么样才能测试下调用工具呢？

**Comment by willwilling** [comment]
> 如上图，并没有调用到agent/tool_select中的函数

源码  log输出见第一张图

**Comment by SWT-AITeam** [comment]
> 这个奶茶给你是能调用的，直接final answer是因为模型没有意识到想调用工具

我测试了很多次，甚至都能把参数写出来，就是不会调用，action每次都是final answer

**Comment by willwilling** [comment]
> > 这个奶茶给你是能调用的，直接final answer是因为模型没有意识到想调用工具
> 
> 我测试了很多次，甚至都能把参数写出来，就是不会调用，action每次都是final answer

我测试的现象也一样  直接忽视了工具tools

**Comment by ACFFF** [comment]
同样的问题+1,始终调用不了工具，输出日志如下

`#########自定义Agent问答start#########
INFO:     127.0.0.1:47058 - "POST /chat/agent_chat HTTP/1.1" 200 OK
/home/darren/miniconda3/envs/langchain/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
2024-03-22 15:09:25,952 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/agent_chat "HTTP/1.1 200 OK"


> Entering new AgentExecutor chain...


> Entering new LLMChain chain...
Prompt after formatting:
System: You can answer using the tools, or answer directly using your knowledge without using the tools. Respond to the human as helpfully and accurately as possible.
You have access to the following tools:
calculate: Useful for when you need to answer questions about simple calculations, args: {\'query\': {\'title\': \'Query\', \'type\': \'string\'}}
arxiv: A wrapper around Arxiv.org for searching and retrieving scientific articles in various fields., args: {\'query\': {\'title\': \'Query\', \'description\': \'The search query title\', \'type\': \'string\'}}
weather_check: Query the weather conditions at a certain time and place, args: {\'location\': {\'title\': \'Location\', \'description\': \'City name,include city and county\', \'type\': \'string\'}}
shell: Use Shell to execute Linux commands, args: {\'query\': {\'title\': \'Query\', \'description\': \'一个能在Linux命令行运行的Shell命令\', \'type\': \'string\'}}
search_knowledgebase_complex: Use Use this tool to search local knowledgebase and get information, args: {\'location\': {\'title\': \'Location\', \'description\': \'The query to be searched\', \'type\': \'string\'}}
search_internet: Use this tool to use bing search engine to search the internet, args: {\'location\': {\'title\': \'Location\', \'description\': \'Query for Internet search\', \'type\': \'string\'}}
Wolfram: Useful for when you need to calculate difficult formulas, args: {\'location\': {\'title\': \'Location\', \'description\': \'需要运算的具体问题\', \'type\': \'string\'}}
search_youtube: use this tools to search youtube videos, args: {\'location\': {\'title\': \'Location\', \'description\': \'Query for Videos search\', \'type\': \'string\'}}
Use a json blob to specify a tool by providing an action key (tool name) and an action_input key (tool input).
Valid "action" values: "Final Answer" or  [['calculate', 'arxiv', 'weather_check', 'shell', 'search_knowledgebase_complex', 'search_internet', 'Wolfram', 'search_youtube']]Provide only ONE action per $JSON_BLOB, as shown:

```
{
  "action": $TOOL_NAME,
  "action_input": $INPUT
}
```

Follow this format:

Question: input question to answer
Thought: consider previous and subsequent steps
Action:
```
$JSON_BLOB
```
Observation: action result
... (repeat Thought/Action/Observation N times)
Thought: I know what to respond
Action:
```
{
  "action": "Final Answer",
  "action_input": "Final response to human"
}
Begin! Reminder to ALWAYS respond with a valid json blob of a single action. Use tools if necessary. Respond directly if appropriate. Format is Action:```$JSON_BLOB```then Observation:.
history: None

Question: 计算2的三次方

Thought: 
2024-03-22 15:09:25 | INFO | stdout | INFO:     127.0.0.1:44430 - "POST /list_models HTTP/1.1" 200 OK
2024-03-22 15:09:25 | INFO | controller | names: ['http://127.0.0.1:20002'], queue_lens: [0.0], ret: http://127.0.0.1:20002
2024-03-22 15:09:25 | INFO | stdout | INFO:     127.0.0.1:44446 - "POST /get_worker_address HTTP/1.1" 200 OK
2024-03-22 15:09:25 | INFO | stdout | INFO:     127.0.0.1:56146 - "POST /worker_get_conv_template HTTP/1.1" 200 OK
2024-03-22 15:09:25 | INFO | stdout | INFO:     127.0.0.1:56150 - "POST /model_details HTTP/1.1" 200 OK
2024-03-22 15:09:25 | INFO | stdout | INFO:     127.0.0.1:56160 - "POST /count_token HTTP/1.1" 200 OK
2024-03-22 15:09:25 | INFO | stdout | INFO:     127.0.0.1:52876 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-22 15:09:26,010 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-03-22 15:09:26 | INFO | stdout | INFO:     127.0.0.1:56164 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2024-03-22 15:09:26 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"
2024-03-22 15:09:26 | INFO | model_worker | Send heart beat. Models: ['qwen-api']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: 10154492. 
2024-03-22 15:09:26 | INFO | controller | Receive heart beat. http://127.0.0.1:21006
2024-03-22 15:09:26 | INFO | stdout | INFO:     127.0.0.1:44456 - "POST /receive_heart_beat HTTP/1.1" 200 OK
2024-03-22 15:09:26 | INFO | model_worker | Send heart beat. Models: ['zhipu-api']. Semaphore: Semaphore(value=5, locked=False). call_ct: 0. worker_id: bb7c818e. 
2024-03-22 15:09:26 | INFO | controller | Receive heart beat. http://127.0.0.1:21001
2024-03-22 15:09:26 | INFO | stdout | INFO:     127.0.0.1:44472 - "POST /receive_heart_beat HTTP/1.1" 200 OK

> Finished chain.

Action:
```
{"action": "Final Answer", "action_input": ""}
```

> Finished chain.
#########自定义Agent问答end#########`
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/32565864/1268125d-21ae-4c2c-89da-b34882f6dbfd)

**Comment by ACFFF** [comment]
同样的问题+1,始终调用不了工具，输出日志如下：

**#########自定义Agent问答start#########
INFO:     127.0.0.1:33306 - "POST /chat/agent_chat HTTP/1.1" 200 OK
2024-03-22 15:14:31,073 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/agent_chat "HTTP/1.1 200 OK"


> Entering new AgentExecutor chain...


> Entering new LLMChain chain...
Prompt after formatting:
System: You can answer using the tools, or answer directly using your knowledge without using the tools. Respond to the human as helpfully and accurately as possible.
You have access to the following tools:
calculate: Useful for when you need to answer questions about simple calculations, args: {\'query\': {\'title\': \'Query\', \'type\': \'string\'}}
arxiv: A wrapper around Arxiv.org for searching and retrieving scientific articles in various fields., args: {\'query\': {\'title\': \'Query\', \'description\': \'The search query title\', \'type\': \'string\'}}
weather_check: Query the weather conditions at a certain time and place, args: {\'location\': {\'title\': \'Location\', \'description\': \'City name,include city and county\', \'type\': \'string\'}}
shell: Use Shell to execute Linux commands, args: {\'query\': {\'title\': \'Query\', \'description\': \'一个能在Linux命令行运行的Shell命令\', \'type\': \'string\'}}
search_knowledgebase_complex: Use Use this tool to search local knowledgebase and get information, args: {\'location\': {\'title\': \'Location\', \'description\': \'The query to be searched\', \'type\': \'string\'}}
search_internet: Use this tool to use bing search engine to search the internet, args: {\'location\': {\'title\': \'Location\', \'description\': \'Query for Internet search\', \'type\': \'string\'}}
Wolfram: Useful for when you need to calculate difficult formulas, args: {\'location\': {\'title\': \'Location\', \'description\': \'需要运算的具体问题\', \'type\': \'string\'}}
search_youtube: use this tools to search youtube videos, args: {\'location\': {\'title\': \'Location\', \'description\': \'Query for Videos search\', \'type\': \'string\'}}
Use a json blob to specify a tool by providing an action key (tool name) and an action_input key (tool input).
Valid "action" values: "Final Answer" or  [['calculate', 'arxiv', 'weather_check', 'shell', 'search_knowledgebase_complex', 'search_internet', 'Wolfram', 'search_youtube']]Provide only ONE action per $JSON_BLOB, as shown:

```
{
  "action": $TOOL_NAME,
  "action_input": $INPUT
}
```

Follow this format:

Question: input question to answer
Thought: consider previous and subsequent steps
Action:
```
$JSON_BLOB
```
Observation: action result
... (repeat Thought/Action/Observation N times)
Thought: I know what to respond
Action:
```
{
  "action": "Final Answer",
  "action_input": "Final response to human"
}
Begin! Reminder to ALWAYS respond with a valid json blob of a single action. Use tools if necessary. Respond directly if appropriate. Format is Action:```$JSON_BLOB```then Observation:.
history: None

Question: 使用计算工具计算2的三次方

Thought: 
2024-03-22 15:14:31 | INFO | stdout | INFO:     127.0.0.1:33170 - "POST /list_models HTTP/1.1" 200 OK
2024-03-22 15:14:31 | INFO | controller | names: ['http://127.0.0.1:20002'], queue_lens: [0.0], ret: http://127.0.0.1:20002
2024-03-22 15:14:31 | INFO | stdout | INFO:     127.0.0.1:33184 - "POST /get_worker_address HTTP/1.1" 200 OK
2024-03-22 15:14:31 | INFO | stdout | INFO:     127.0.0.1:35374 - "POST /model_details HTTP/1.1" 200 OK
2024-03-22 15:14:31 | INFO | stdout | INFO:     127.0.0.1:35388 - "POST /count_token HTTP/1.1" 200 OK
2024-03-22 15:14:31 | INFO | stdout | INFO:     127.0.0.1:58318 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-03-22 15:14:31,112 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
2024-03-22 15:14:31 | INFO | stdout | INFO:     127.0.0.1:35394 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2024-03-22 15:14:31 | INFO | httpx | HTTP Request: POST http://127.0.0.1:20002/worker_generate_stream "HTTP/1.1 200 OK"

> Finished chain.

Action:
```
{"action": "Final Answer", "action_input": ""}
```

> Finished chain.
#########自定义Agent问答end#########
![截图 2024-03-22 15-14-44](https://github.com/chatchat-space/Langchain-Chatchat/assets/32565864/9f755d4e-501b-488f-baa4-779eb853d614)
**

**Comment by ACFFF** [comment]
![截图 2024-03-22 15-14-44](https://github.com/chatchat-space/Langchain-Chatchat/assets/32565864/9d7effc5-52ae-427e-9bd4-ff0c3c354daf)

**Comment by HhhBbWw** [comment]
你好，我也是在自定义Agent问答中遇到相同的问题，思考过程下拉显示调用工具名称为invalid tool，也输出不了结果


> ![截图 2024-03-22 15-14-44](https://private-user-images.githubusercontent.com/32565864/315918769-9d7effc5-52ae-427e-9bd4-ff0c3c354daf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDE3MDIsIm5iZiI6MTcxMTQ0MTQwMiwicGF0aCI6Ii8zMjU2NTg2NC8zMTU5MTg3NjktOWQ3ZWZmYzUtNTJhZS00MjdlLTliZDQtZmYwYzNjMzU0ZGFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA4MjMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NzU1NDcwNWExYzk0MWI4NTRiOTM2NDhjZmM5ZmJmYzBkNzY4MGRlYmE1MGYwNzg2NTBiN2Q3Njg5ZDJlNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I47IfS2QoDyzsDJ2yrvCQ9nbdNIoxduwmOpGI72_v4s)

**Comment by liangpn** [comment]
解决了吗，遇到一样的问题了

**Comment by shisheng660** [comment]
一樣的問題，有人解決了嗎？後臺看到是有調用工具鏈的，但是web端就顯示第一句話，沒有返回最終的結果
![Uploading image.png…]()
