### ISSUE TITLE
想请教大佬为什么运行速度这么快

### ISSUE THREAD

**Issue by litongyun233** [chatchat-space/Langchain-Chatchat#3399]
单独测试chatGLM2-6b模型（不涉及RAG，embedding等等，即简单的输入prompt调用模型），在1200个token的时候回答要4s，而在3800个token的时候，回答要28s。但是使用本项目，不论token多长（即不论设置的匹配知识条数有多少条），模型总是能在1s内流式输出结果，请问这是做了什么优化能让模型的回答速度提升这么多呢？
本来以为是上下文压缩减少了token数量，但看到只有在rerank阶段涉及到上下文压缩，但不启用rerank也有如此快的速度。

**Comment by litongyun233** [comment]
但是在不适用rerank的上下文压缩时，速率也很快，是为什么呢@dosu-bot

**Comment by zRzRzRzRzRzRzR** [comment]
首token和总体没关系，而且有可能是你传入的maxtoken是1024，后面的内容都没看，项目默认的max token为1024
