### ISSUE TITLE
直接调用智谱报错，已更新key

### ISSUE THREAD

**Issue by Rodgers6** [chatchat-space/Langchain-Chatchat#3402]
![1710472031777](https://github.com/chatchat-space/Langchain-Chatchat/assets/161576739/373859df-29e5-4552-836b-d47645bf3169)

这是啥原因呢，只有GLM模型调用是好使的

**Comment by Rodgers6** [comment]
没有历史对话

**Comment by zRzRzRzRzRzRzR** [comment]
不用装sdk ，使用glm4

**Comment by willwilling** [comment]
> 不用装sdk ，使用glm4

什么意思？就是使用的glm4的api_key

**Comment by Rodgers6** [comment]
> 不用装sdk ，使用glm4

参数配置里就是glm4，我没装什么sdk，只填了自己的key

**Comment by 871052165** [comment]
遇到了同样的问题，没有装SDK，直接调用直接报错

**Comment by qibaizhang** [comment]
一样的，用不了智谱

**Comment by zRzRzRzRzRzRzR** [comment]
emm 报错看看 请求有吗

**Comment by QuanSir07** [comment]
一样的，报错，我在服务器上面部署就报错，自己电脑跑就不报错。

**Comment by liunux4odoo** [comment]
建议使用oneapi将智谱API转接为openai兼容的接口再使用。
