### ISSUE TITLE
知识库文件删除后，知识库列表中不存在，但是knowledge_base/search_docs匹配能匹配到

### ISSUE THREAD

**Issue by zhengyoutan** [chatchat-space/Langchain-Chatchat#3403]
环境配置：按官方建议配置的
代码：最新的
数据库：elasticsearch
问题：知识库文件删除后，知识库列表中不存在，但是knowledge_base/search_docs匹配能匹配到
疑问：lssue看到过类似问题，但是没有解决方案，要是说删完向量库会覆盖，那应该不会检索到了呀

**Comment by StephenZKCurry** [comment]
不知道是不是这个原因
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/23159320/208bd694-8545-4ed7-a2ae-14081590726c)
es_kb_service中的do_delete_doc()函数只会删除50条向量库中的记录，如果文件分段超过50的话就会导致向量库中的向量没有删除干净，可能还会匹配到

**Comment by liudichen** [comment]
是删除doc的方法里有问题应该（do_delete_doc），删除时是根据meta.source的文件路径查询并删除，但是保存时用的是相对路径（有的是直接用的文件名，代码比较乱行为不一致，不过默认情况下最终都是文件名），查询时用的是绝对路径(kb_file.filepath)，所以查不到，就删除不了向量库里的内容。我尝试提了个pr你可以试下.
