### ISSUE TITLE
针对上传的文件配置不同的TextSpliter

### ISSUE THREAD

**Issue by oushu1zhangxiangxuan1** [chatchat-space/Langchain-Chatchat#341]
1. 目前的ChineseTextSpliter切分对英文尤其是代码文件不友好，而且限制固定长度；导致对话结果不如人意
2. AliTextSpliter也只支持中文
3. 需要允许为不同文件配置不同的Spliter
4. 更进一步支持智能选择Spliter或者弄一个UniTextSpliter

**Comment by imClumsyPanda** [comment]
已在计划开发其他splitter，将会提供不同textsplitter以供选择，后续会再提供更智能的选择方式，感谢提出的建议
