### ISSUE TITLE
您好，关于业务应用，请教个问题

### ISSUE THREAD

**Issue by yumu7777777** [chatchat-space/Langchain-Chatchat#3410]
**功能描述 / Feature Description**
我这边想用户在提问时可以通过用户权限从不同知识库、不同文件中回答，只检索用户有权限的文件，应该怎么做呢？
现在用户文件的权限我这边已经管理起来了，就是不知道怎么在回答是做处理，能给个方向吗？
需求具体是：
1. 回答问题可以从多个知识库检索。
2. 根据权限筛选文件来回答

求思路。
**解决的问题 / Problem Solved**
数据权限安全问题

**Comment by wz96cj** [comment]
请问下你的用户权限操作页面，是在原先页面的基础上用那个streamlit实现的吗
