### ISSUE TITLE
关于上传文件到知识库出现We couldn't connect to 'https://huggingface.co' to load this file

### ISSUE THREAD

**Issue by 302658980** [chatchat-space/Langchain-Chatchat#3416]
RapidOCRPDFLoader context page index: 9: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [05:21<00:00, 32.14s/it]
We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like None is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
文档切分示例：page_content='《百度推广服务协议》\n\n0447763\n\n合同编号：\n\n深圳大拿智能设备有限公司\n\n方：\n\n方：百度国际科技（深圳）有限公司\n\n法定代表人：\n\n法定代表人：崔珊珊\n\n联系地址：\n\n联系地址：深圳市南山区粤海街道滨海社区海天一\n\n路8号百度国际大厦西塔楼3层\n\n联系人：\n\n联系人：\n\n电话：\n\n电话：售前：4008060018、售后：4009200000\n\n电子邮件：\n\n电子邮箱：zxhelp@sh.baidu.com\n\n开户行：\n\n开户行：招商银行深圳分行创维大厦支行\n\n账号：' metadata={'source': '/root/autodl-tmp/Langchain-Chatchat/knowledge_base/doc-1701875989560164354/content/526062814771613696-百度推广签约合同(2).pdf'}

我想知道这是报错还是提醒，如果是报错该如何解决 如果是提醒该怎么做

**Comment by jersonal** [comment]
这是提醒，你应该用的在线模型吧？当使用config.get("model_path")时候，model_path不存在，会将text_splitter_dict[splitter_name]["tokenizer_name_or_path"]=None
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/5946c5b0-9d9b-4dbe-bb5f-0bbd2abe3604)
然后在调用AutoTokenizer.from_pretrained(text_splitter_dict[splitter_name]["tokenizer_name_or_path"],trust_remote_code=True)时候，由于text_splitter_dict[splitter_name]["tokenizer_name_or_path"]=None，所以会警告
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/ab88efa0-35c2-42bc-b212-17f0347df3ed)
你可以使用下载到本地的模型做测试，比如chatglm3等
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/84516417-d787-48e0-8d50-0cab7b7bafaf)

**Comment by 302658980** [comment]
> 这是提醒，你应该用的在线模型吧？当使用config.get("model_path")时候，model_path不存在，会将text_splitter_dict[splitter_name]["tokenizer_name_or_path"]=None ![image](https://private-user-images.githubusercontent.com/34061443/315073101-5946c5b0-9d9b-4dbe-bb5f-0bbd2abe3604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDM5MTIsIm5iZiI6MTcxMTAwMzYxMiwicGF0aCI6Ii8zNDA2MTQ0My8zMTUwNzMxMDEtNTk0NmM1YjAtOWQ5Yi00ZGJlLWJiNWYtMGJiZDJhYmUzNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVmZDE1NjM5NTgzMDEwMDNjYjMxNTRhNzhmYjE3YWJjZGUxNjNmNWEwNGY3MDdjNDZlMWExYjc1NThkMTYyODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BWUtqserARZ7IWNTPwj3wvi05HTKXMzyTLEZI907HuY) 然后在调用AutoTokenizer.from_pretrained(text_splitter_dict[splitter_name]["tokenizer_name_or_path"],trust_remote_code=True)时候，由于text_splitter_dict[splitter_name]["tokenizer_name_or_path"]=None，所以会警告 ![image](https://private-user-images.githubusercontent.com/34061443/315075801-ab88efa0-35c2-42bc-b212-17f0347df3ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDM5MTIsIm5iZiI6MTcxMTAwMzYxMiwicGF0aCI6Ii8zNDA2MTQ0My8zMTUwNzU4MDEtYWI4OGVmYTAtMzVjMi00MmJjLWIyMTItMTdmMDM0N2RmM2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNDAyNDFmZjVjZmE3OWYwY2Q0MjkzMzMyNWIzZmM2ZjllZDNjOTE3YjI0MzQ1YTM2YjY5ODhmZjQ1YzExMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z841_DyRwe2uBkruCr-mF-9iO9h9ZvxGEP0vl9qkRqo) 你可以使用下载到本地的模型做测试，比如chatglm3等 ![image](https://private-user-images.githubusercontent.com/34061443/315093239-84516417-d787-48e0-8d50-0cab7b7bafaf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDM5MTIsIm5iZiI6MTcxMTAwMzYxMiwicGF0aCI6Ii8zNDA2MTQ0My8zMTUwOTMyMzktODQ1MTY0MTctZDc4Ny00OGUwLThkNTAtMGNhYjdiN2JhZmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA2NDY1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyM2JmMGEyNzU5YjUxYWU2YTc5ZWYyYWM5ZjlhMmZkMjM0MDIyMjMxYTIwMzA4YWRiN2MyZjZhZWM0MDU2YzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mYJUCxKuqGOMBkUiSh_EN07zPQ1Ix2tMbGpU9SemqMk)

首先谢谢你的回复，但是我的model.config.py如下：
LLM_MODELS = ["qwen-14b",  "yi-34b"] # "Qwen-1_8B-Chat",

# AgentLM模型的名称 (可以不指定，指定之后就锁定进入Agent之后的Chain的模型，不指定就是LLM_MODELS[0])
Agent_MODEL = None

# LLM 运行设备。设为"auto"会自动检测，也可手动设定为"cuda","mps","cpu"其中之一。
LLM_DEVICE = "auto"

# 历史对话轮数
HISTORY_LEN = 3

# 大模型最长支持的长度，如果不填写，则使用模型默认的最大长度，如果填写，则为用户设定的最大长度
MAX_TOKENS = None

# LLM通用对话参数
TEMPERATURE = 0.7
# TOP_P = 0.95 # ChatOpenAI暂不支持该参数

ONLINE_LLM_MODEL = {
    # 线上模型。请在server_config中为每个在线API设置不同的端口

    "qwen-14b": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "http://region-9.seetacloud.com:25530/v1",
        "api_key": "none",
        "openai_proxy": "",
    },
    "yi-34b": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "http://region-9.seetacloud.com:19636/v1",
        "api_key": "none",
        "openai_proxy": "",
    },
那也应该是去找这里的模型 为什么会去https://huggingface.co/

**Comment by 302658980** [comment]
> 可以使用下载到本地的模型做测试，比如chatglm3等

既然是提醒的话，是不是就没有问题

**Comment by jersonal** [comment]
> > 可以使用下载到本地的模型做测试，比如chatglm3等
> 
> 既然是提醒的话，是不是就没有问题
是的，没有影响。
这个是大模型的分词器，本地模型会在MODEL_ROOT_PATH下去找该模型对应的分词器。在线模型没有model_path参数，默认会调用text_splitter.chinese_recursive_text_splitter.ChineseRecursiveTextSplitter分词器，所以没有影响
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/71e870a4-416a-4f6e-80e4-24a255323c7f)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/dc3040d2-ab6b-4d43-8fd9-6f29891aec70)

**Comment by 302658980** [comment]
> > > 可以使用下载到本地的模型做测试，比如chatglm3等
> > 
> > 
> > 既然是提醒的话，是不是就没有问题
> > 是的，没有影响。
> > 这个是大模型的分词器，本地模型会在MODEL_ROOT_PATH下去找该模型对应的分词器。在线模型没有model_path参数，默认会调用text_splitter.chinese_recursive_text_splitter.ChineseRecursiveTextSplitter分词器，所以没有影响
> > ![image](https://private-user-images.githubusercontent.com/34061443/315188570-71e870a4-416a-4f6e-80e4-24a255323c7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDU4NjEsIm5iZiI6MTcxMTAwNTU2MSwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxODg1NzAtNzFlODcwYTQtNDE2YS00ZjZlLTgwZTQtMjRhMjU1MzIzYzdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA3MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiOGQ0YjgzZTgzMzdhYjEwYjllYzQ0ZGZiOGU5ZmRhNWU0MWEzZjQ2OWVmOTk2ZDI2ZTYxMmYzOWMwYjJiMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKolj2DH3NR1S6FwzqnlozZgvXUPmFSmc7UwY1K7aXg)
> > ![image](https://private-user-images.githubusercontent.com/34061443/315190003-dc3040d2-ab6b-4d43-8fd9-6f29891aec70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDU4NjEsIm5iZiI6MTcxMTAwNTU2MSwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxOTAwMDMtZGMzMDQwZDItYWI2Yi00ZDQzLThmZDktNmYyOTg5MWFlYzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA3MTkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMjZlOGY2NjkwMzQ5NWZiOWUxNDYzZTM5NWVlNjIzYTgwMmUwMDhhNjdmNDgyNzAxZjRhMmY5MzJjY2U2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ivzw6_5NbS6H3akcxEAWP8aYRWnzizoMtcmy91H6ft8)

好的，非常感谢您。那么我的大模型应该是调用的我上面设置的LLM_MODELS = ["qwen-14b", "yi-34b"]，
然后# 选用的 Embedding 名称
EMBEDDING_MODEL = "bge-large-zh"
MODEL_PATH = { "bge-large-zh": "/root/model/bge-large-zh",。

那我有什么好点的方式解决这个提醒呢 还是不用管它

**Comment by jersonal** [comment]
不用管，看着不爽就把print(e)注释了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/34061443/551d5cb5-afc1-49e3-9f58-82e9ea4d9f4f)

**Comment by 302658980** [comment]
> 不用管，看着不爽就把print(e)注释了 ![image](https://private-user-images.githubusercontent.com/34061443/315192299-551d5cb5-afc1-49e3-9f58-82e9ea4d9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMDYzNDYsIm5iZiI6MTcxMTAwNjA0NiwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxOTIyOTktNTUxZDVjYjUtYWZjMS00OWUzLTlmNTgtODJlOWVhNGQ5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA3MjcyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkOTc5YmIxZTQzNGY4YjY5M2Q0MjNkMTk3OWQzMTVmZjk2ZTM3NTFmMDFiMjBlNDQyZTU2ODI1NzRhMTA1Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJ7wGRd1LODQ0agdaPAezYHhKhIfsIv4CcIUD-ff1Y4)

哈哈哈 好

**Comment by 302658980** [comment]
> 不用管，看着不爽就把print(e)注释了 ![image](https://private-user-images.githubusercontent.com/34061443/315192299-551d5cb5-afc1-49e3-9f58-82e9ea4d9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTM5MTEsIm5iZiI6MTcxMTAxMzYxMSwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxOTIyOTktNTUxZDVjYjUtYWZjMS00OWUzLTlmNTgtODJlOWVhNGQ5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTlmYmU0ZDlmMGY2YTVhZWI0Zjg2MWZiY2ZkY2Q4Njk4YzdjYWRmYzEwNWU5Y2MzZGRkMjJlMjJhZjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_mzTEcJ95qZxBiAp1DyMHGEp7mpXWM50q-WB1Hbxxw)

大佬，还有个问题方便解答一下吗? 我本身模型用的是EMBEDDING_MODEL = "bge-large-zh"，但是在创建知识库的哪里有模型选择，这里是只能选择我配置里的EMBEDDING_MODEL = "bge-large-zh" 吗 我刚刚测试选择了1.5的 报错如下：
2024-03-21 17:31:27,847 - faiss_cache.py[line:80] - INFO: loading vector store in '中文测试删除/vector_store/bge-large-zh-v1.5' from disk.
2024-03-21 17:31:27,891 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
2024-03-21 17:33:39,028 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f996bdc6950>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: cad101f9-04ec-4caa-8f0f-72ac1ed10f99)')
2024-03-21 17:33:39,033 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by jersonal** [comment]
> > 不用管，看着不爽就把print(e)注释了 ![image](https://private-user-images.githubusercontent.com/34061443/315192299-551d5cb5-afc1-49e3-9f58-82e9ea4d9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTM5MTEsIm5iZiI6MTcxMTAxMzYxMSwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxOTIyOTktNTUxZDVjYjUtYWZjMS00OWUzLTlmNTgtODJlOWVhNGQ5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTlmYmU0ZDlmMGY2YTVhZWI0Zjg2MWZiY2ZkY2Q4Njk4YzdjYWRmYzEwNWU5Y2MzZGRkMjJlMjJhZjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_mzTEcJ95qZxBiAp1DyMHGEp7mpXWM50q-WB1Hbxxw)
> 
> 大佬，还有个问题方便解答一下吗? 我本身模型用的是EMBEDDING_MODEL = "bge-large-zh"，但是在创建知识库的哪里有模型选择，这里是只能选择我配置里的EMBEDDING_MODEL = "bge-large-zh" 吗 我刚刚测试选择了1.5的 报错如下： 2024-03-21 17:31:27,847 - faiss_cache.py[line:80] - INFO: loading vector store in '中文测试删除/vector_store/bge-large-zh-v1.5' from disk. 2024-03-21 17:31:27,891 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5 2024-03-21 17:33:39,028 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f996bdc6950>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: cad101f9-04ec-4caa-8f0f-72ac1ed10f99)') 2024-03-21 17:33:39,033 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

是的，你可以把需要选择的embedding模型下载到本地，然后选择。
如果你的bge-large-zh-v1.5没有下载到本地，默认会huggingface加载，国内网络访问huggingface就会报这个错

**Comment by 302658980** [comment]
> > > 不用管，看着不爽就把print(e)注释了 ![image](https://private-user-images.githubusercontent.com/34061443/315192299-551d5cb5-afc1-49e3-9f58-82e9ea4d9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTM5MTEsIm5iZiI6MTcxMTAxMzYxMSwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxOTIyOTktNTUxZDVjYjUtYWZjMS00OWUzLTlmNTgtODJlOWVhNGQ5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTlmYmU0ZDlmMGY2YTVhZWI0Zjg2MWZiY2ZkY2Q4Njk4YzdjYWRmYzEwNWU5Y2MzZGRkMjJlMjJhZjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_mzTEcJ95qZxBiAp1DyMHGEp7mpXWM50q-WB1Hbxxw)
> > 
> > 
> > 大佬，还有个问题方便解答一下吗? 我本身模型用的是EMBEDDING_MODEL = "bge-large-zh"，但是在创建知识库的哪里有模型选择，这里是只能选择我配置里的EMBEDDING_MODEL = "bge-large-zh" 吗 我刚刚测试选择了1.5的 报错如下： 2024-03-21 17:31:27,847 - faiss_cache.py[line:80] - INFO: loading vector store in '中文测试删除/vector_store/bge-large-zh-v1.5' from disk. 2024-03-21 17:31:27,891 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5 2024-03-21 17:33:39,028 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f996bdc6950>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: cad101f9-04ec-4caa-8f0f-72ac1ed10f99)') 2024-03-21 17:33:39,033 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
> 
> 是的，你可以把需要选择的embedding模型下载到本地，然后选择。 如果你的bge-large-zh-v1.5没有下载到本地，默认会huggingface加载，国内网络访问huggingface就会报这个错

大佬，我今天在云服务器把梯子打开了。curl huggingface.co 是可以的 ，但是在创建知识库的时候还是报错：
2024-03-25 14:42:00,397 - faiss_cache.py[line:80] - INFO: loading vector store in '测试知识库删除embedding/vector_store/bge-large-zh-v1.5' from disk.
2024-03-25 14:42:01,556 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5
2024-03-25 14:44:12,755 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f06d8521a50>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: e8d96c45-59be-4593-ab4b-81bee8414ab9)')
2024-03-25 14:44:12,757 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
INFO:     127.0.0.1:39486 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 200 OK
2024-03-25 14:44:12,768 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 200 OK"

**Comment by 302658980** [comment]
> > > > 不用管，看着不爽就把print(e)注释了 ![image](https://private-user-images.githubusercontent.com/34061443/315192299-551d5cb5-afc1-49e3-9f58-82e9ea4d9f4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMTM5MTEsIm5iZiI6MTcxMTAxMzYxMSwicGF0aCI6Ii8zNDA2MTQ0My8zMTUxOTIyOTktNTUxZDVjYjUtYWZjMS00OWUzLTlmNTgtODJlOWVhNGQ5ZjRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDA5MzMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYyZTlmYmU0ZDlmMGY2YTVhZWI0Zjg2MWZiY2ZkY2Q4Njk4YzdjYWRmYzEwNWU5Y2MzZGRkMjJlMjJhZjhlM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b_mzTEcJ95qZxBiAp1DyMHGEp7mpXWM50q-WB1Hbxxw)
> > > 
> > > 
> > > 大佬，还有个问题方便解答一下吗? 我本身模型用的是EMBEDDING_MODEL = "bge-large-zh"，但是在创建知识库的哪里有模型选择，这里是只能选择我配置里的EMBEDDING_MODEL = "bge-large-zh" 吗 我刚刚测试选择了1.5的 报错如下： 2024-03-21 17:31:27,847 - faiss_cache.py[line:80] - INFO: loading vector store in '中文测试删除/vector_store/bge-large-zh-v1.5' from disk. 2024-03-21 17:31:27,891 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5 2024-03-21 17:33:39,028 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f996bdc6950>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: cad101f9-04ec-4caa-8f0f-72ac1ed10f99)') 2024-03-21 17:33:39,033 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
> > 
> > 
> > 是的，你可以把需要选择的embedding模型下载到本地，然后选择。 如果你的bge-large-zh-v1.5没有下载到本地，默认会huggingface加载，国内网络访问huggingface就会报这个错
> 
> 大佬，我今天在云服务器把梯子打开了。curl huggingface.co 是可以的 ，但是在创建知识库的时候还是报错： 2024-03-25 14:42:00,397 - faiss_cache.py[line:80] - INFO: loading vector store in '测试知识库删除embedding/vector_store/bge-large-zh-v1.5' from disk. 2024-03-25 14:42:01,556 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: BAAI/bge-large-zh-v1.5 2024-03-25 14:44:12,755 - embeddings_api.py[line:39] - ERROR: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /api/models/BAAI/bge-large-zh-v1.5 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f06d8521a50>, 'Connection to huggingface.co timed out. (connect timeout=None)'))"), '(Request ID: e8d96c45-59be-4593-ab4b-81bee8414ab9)') 2024-03-25 14:44:12,757 - kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method INFO: 127.0.0.1:39486 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 200 OK 2024-03-25 14:44:12,768 - _client.py[line:1013] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 200 OK"

不好意思，原来是我再不通终端启动的梯子只能在那个终端访问，现在可以了。但是之前的报错导致了一些不存在的知识库在页面上，但是接口得到知识库的没有的，我以为是缓存 但是刷新之后也还存在 删除该知识库时还报该知识库不存在
