### ISSUE TITLE
query在线embedding以及与知识库向量匹配

### ISSUE THREAD

**Issue by cwqJim2023** [chatchat-space/Langchain-Chatchat#3419]
您好，有以下几个问题请教下：
1.query是在项目什么位置进行在线embeding？
2.query向量化后在项目什么位置进行知识库语义检索匹配的？

**Comment by CyanMystery** [comment]
@dosu-bot 文档召回效果很差怎么结局

**Comment by CyanMystery** [comment]
@dosu-bot 匹配的文档相似度很低怎么办
