### ISSUE TITLE
问答如何进行文件过滤呢

### ISSUE THREAD

**Issue by yumu7777777** [chatchat-space/Langchain-Chatchat#3426]
文件如何根据用户权限区过滤，部分文件不允许没权限用户问答

**Comment by yang1111-gif** [comment]
直接加在表里面加个权限级别字段。或者自己创建一个权限表，再映射到向量库中，就那个db目录下的model里面，仿写就好了。然后在update_docs函数里面更新传值，有个叫data_info，进去传值。
