### ISSUE TITLE
[BUG] 简洁阐述问题 / 想要让langchain-chatchat实现一个功能

### ISSUE THREAD

**Issue by ccdisk** [chatchat-space/Langchain-Chatchat#3436]
想要让langchain-chatchat实现把一大段无标点符号的中文字，正确标注标点符号：，。“”、……并且正确分段，但是不能修改任何文字的功能，如何才能实现？目前langchain-chatchat会自动总结。或者如何关闭langchain-chatchat自动总结这个功能。

**Comment by zRzRzRzRzRzRzR** [comment]
不该代码没办法实现

**Comment by ccdisk** [comment]
> 不该代码没办法实现
你是指关闭总结功能吗？这个需要在哪几个文件修改代码啊？麻烦告知一下。谢谢。
