### ISSUE TITLE
zhipu-api无法流式输出

### ISSUE THREAD

**Issue by SSTato** [chatchat-space/Langchain-Chatchat#3437]
使用zhipu-api的时候无法流式输出，使用别的api或者本地大模型时可以正常流式输出，这是为什么？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/93987794/2510ca75-a2d2-474a-9397-5b3746eb4ec9)

**Comment by zRzRzRzRzRzRzR** [comment]
因为zhipu 流输出有bug，所以在程序里写成了非流，这个没办法

**Comment by liuhuatao** [comment]
我也遇到了，打开了注释代码，本地是可以实现对话的。但是一直报错ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

**Comment by SSTato** [comment]
Lib\site-packages\langchain_community\chat_models\openai.py中的493加一个判断就不会报ERROR了
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/93987794/428b4b4c-ef56-470f-900e-b88660c19e9d)

**Comment by SSTato** [comment]
> 因为zhipu 流输出有bug，所以在程序里写成了非流，这个没办法

我这样改还会有bug吗

**Comment by liuhuatao** [comment]
@SSTato 确实不会报错了  但是这个是langchain依赖的 langchain_community  貌似不好提取到项目中吧

**Comment by zyy26-zyy** [comment]
我按照以下这样改api可以流式输出，webui页面不可以，但是我也不用页面所以我按照以下方式改的
model_config.py配置如下：
![20240326-093956](https://github.com/chatchat-space/Langchain-Chatchat/assets/59223170/eccf142a-e9a4-4db5-8182-67051be3378f)
然后在./server/utils.py文件的get_ChatOpenAI()函数里这样改，就可以api调用zhipu流式了:
![20240326-094003](https://github.com/chatchat-space/Langchain-Chatchat/assets/59223170/ab359a80-8c6e-4ca2-b7d4-73672f2c1bd6)

**Comment by jersonal** [comment]
> 我按照以下这样改api可以流式输出，webui页面不可以，但是我也不用页面所以我按照以下方式改的 model_config.py配置如下： ![20240326-093956](https://private-user-images.githubusercontent.com/59223170/316698638-eccf142a-e9a4-4db5-8182-67051be3378f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Nzk4ODMsIm5iZiI6MTcxODY3OTU4MywicGF0aCI6Ii81OTIyMzE3MC8zMTY2OTg2MzgtZWNjZjE0MmEtZTlhNC00ZGI1LTgxODItNjcwNTFiZTMzNzhmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAyNTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNGEyNmQwMDJjZTQ3MTBmMWY0ZjAzOGMyODNlY2RlZDMxNTg3M2U2ZmNjZTM0ODViYzEwOTk4MzM4OTliNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SDWXYABZTqGpSnuZcm9RbVU2JlWCmxxFgAbcrpBglzY) 然后在./server/utils.py文件的get_ChatOpenAI()函数里这样改，就可以api调用zhipu流式了: ![20240326-094003](https://private-user-images.githubusercontent.com/59223170/316698906-ab359a80-8c6e-4ca2-b7d4-73672f2c1bd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Nzk4ODMsIm5iZiI6MTcxODY3OTU4MywicGF0aCI6Ii81OTIyMzE3MC8zMTY2OTg5MDYtYWIzNTlhODAtOGM2ZS00Y2EyLWI3ZDQtNzM2NzJmMmMxYmQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAyNTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzYjU0MzEyYzhiYzhhZGI2YWFjMjFlYWQ0ZmVlMWVmYjFmNGJkNDQ3ZjQ5M2VjNGU2NWFkNTJlMGJlMTEwYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEugUD88Rlp_pYRJ8JD1LXe2Ld1ABeFGkqS3lJkbk_0)

你好，请问generate_token()函数在哪儿调用的啊
