### ISSUE TITLE
分割器切分文档的存储位置

### ISSUE THREAD

**Issue by yang1111-gif** [chatchat-space/Langchain-Chatchat#3443]
切分好的文档片段是存储在sqlite里面？还是存储在内存中？还是在docstore? sqlite的表中我没有找到切分好的文档片段。我看到切分片段切好之后传给了kowledgefile中的splited_docs参数临时存储，但是后面向量匹配的时候，通过docstore.search去获取docs的，请问切分的文档片段是存在哪里面的？我目前是写道了pg数据库中，但是如果项目已经有存储位置了，我就不用重复存储了，请解答谢谢。

**Comment by yang1111-gif** [comment]
> self.doc_path

不对吧，self.doc_path不是存放原上传的文件位置吗？这里存储的数据是没有切分的，难道不是吗？

**Comment by yang1111-gif** [comment]
> 嗨，@yang1111-gif！很高兴再次见到你🚀
> 
> 在Langchain-Chatchat中，切分好的文档片段是存储在`self.doc_path`指定的目录下。这是通过`self.doc_path = get_doc_path(self.kb_name)`在`KBService`类的初始化方法中设置的。`get_doc_path`函数根据知识库的名称生成文档的存储路径。你可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)查看相关代码。
> 
> 至于你提到的`splited_docs`参数，它在`KnowledgeFile`类中代表已经被切分成较小块或段落的文档。这个切分是由`KnowledgeFile`类的`docs2texts`方法完成的，该方法接收原始文档（`docs`），如果它们是中文并且设置了`zh_title_enhance`标志，则可选地增强它们，然后根据指定的块大小和重叠使用文本分割器将它们切分成较小的部分。结果切分的文档存储在`splited_docs`属性中以供进一步处理或分析。这种机制对于处理大型文档或为处理输入大小有限制的模型准备文档至关重要。你可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/utils.py)查看相关代码。
> 
> 关于SQLite数据库的结构，根据提供的上下文，`SummaryChunkModel`类在`knowledge_metadata_model.py`中定义的SQLite数据库结构，是为了存储从文档中提取的摘要块的信息。这个结构对于在Langchain-Chatchat应用中存储和检索切分文档至关重要。你可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/db/models/knowledge_metadata_model.py)查看相关代码。
> 
> 至于`docstore`中切分文档的存储，Langchain-Chatchat代码库通过首先检查是否提供了文档（`docs`）来处理。如果提供了文档，它将`custom_docs`设置为`True`，并使用源文件名更新每个文档的元数据。如果没有提供文档，它使用`file2text()`方法将与`KnowledgeFile`对象关联的文件转换为文本文档，将`custom_docs`设置为`False`。然后，它删除与`KnowledgeFile`关联的知识库和数据库中的任何现有文档。然后，它通过调用`do_add_doc()`方法将新的或更新的文档添加到知识库，该方法应由子类实现，以处理将文档添加到不同类型的向量存储或数据库的具体细节。然后，使用`add_file_to_db()`函数将添加的文档的详细信息（包括它们的计数和任何自定义文档标志）存储在数据库中。你可以在[这里](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)查看相关代码。
> 
> 希望这些信息能帮助你理解Langchain-Chatchat中切分文档的存储位置和处理方式。如果你还有其他问题，欢迎继续提问。
> 
> ## Sources
> * [server/knowledge_base/kb_service/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)
> * [server/knowledge_base/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/utils.py)
> * [server/db/models/knowledge_metadata_model.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/db/models/knowledge_metadata_model.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

我的问题是切分好的文档，表示的是一个完整的文件被切分成n个document对象的文本片段，这些被切分好的文本片段是存储在哪里？

**Comment by yang1111-gif** [comment]
> Based on the context provided, the split document segments generated by the `docs2texts` method of the `KnowledgeFile` class in the Langchain-Chatchat system are stored in a database, specifically within the `FileDocModel` table. This is evident from the `add_docs_to_db` function, which takes `doc_infos` (a list of dictionaries containing document IDs and metadata) and adds each document to the `FileDocModel` table using the provided `kb_name` (knowledge base name) and `file_name`. Each document is represented as an instance of `FileDocModel` with attributes for the knowledge base name (`kb_name`), file name (`file_name`), document ID (`doc_id`), and metadata (`meta_data`). You can find more details in the [knowledge_file_repository.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/db/repository/knowledge_file_repository.py) file.
> 
> The structure of the `FileDocModel` table in the database, along with the specific fields and their data types, is as follows:
> 
> * `id`: Integer, primary key, autoincrement
> * `kb_name`: String(50), knowledge base name
> * `file_name`: String(255), file name
> * `doc_id`: String(50), vector library document ID
> * `meta_data`: JSON, default is an empty dictionary
> 
> This information can be found in the [knowledge_file_model.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/db/models/knowledge_file_model.py) file.
> 
> Regarding the `docs2texts` method, the provided context does not include the implementation details of this method. However, there is a method named `add_doc` in the `KBService` class that seems relevant to the process of handling documents, which includes a call to `kb_file.file2text()` when no documents are explicitly provided. This suggests that the conversion of documents into text or smaller blocks might be handled by the `file2text` method of the `KnowledgeFile` class or similar. You can find this in the [base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py) file.
> 
> To accurately answer how the `KnowledgeFile` class's `docs2texts` method (or a method with a similar purpose like `file2text`) processes and splits documents, the implementation details or code of the `KnowledgeFile` class would be necessary. If you have access to this code, it would be helpful in providing a more accurate answer.
> 
> ## Sources
> * [server/db/repository/knowledge_file_repository.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/db/repository/knowledge_file_repository.py)
> * [server/db/models/knowledge_file_model.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/db/models/knowledge_file_model.py)
> * [server/knowledge_base/kb_service/base.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/kb_service/base.py)
> 
> #### About Dosu

你的回复还是不对，filedocmodel是存储的切分文档的详细信息，但是没有存储每个切分文档的内容。请告诉我，切分文档到底存储在哪里？或者说，在进行向量匹配的时候，是如何将匹配得到的向量，转成对应的文本片段信息。

**Comment by glide-the** [comment]
目前是创建矢量后，将docId存储sqlite中的file_doc表格，详细内容通过vector_store检索获取
