### ISSUE TITLE
[BUG] 对话报错openai.APIConnectionError: Connection error

### ISSUE THREAD

**Issue by quinbyjoe** [chatchat-space/Langchain-Chatchat#3451]
**问题描述 / Problem Description**
离线部署[Langchain-Chatchat](https://github.com/chatchat-space/Langchain-Chatchat)，使用服务器（无GPU）CPU部署，问答时报错：openai.APIConnectionError: Connection error

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python startup.py -a
2. 输入'hi'点击 '发送'
3. 问答界面无回答结果
4. 问题出现，后台报错：openai.APIConnectionError: Connection error

附件：[chatchat_error.zip](https://github.com/chatchat-space/Langchain-Chatchat/files/14664393/chatchat_error.zip)
配置见：附件中的*_config.py
错误log见：附件中的run_err_2024_0320_1738.log

**预期的结果 / Expected Result**
使用离线模型回答问题。

现的结果 / Describe the expected result.

**实际结果 / Actual Result**
问答界面无回答结果，后台报错：openai.APIConnectionError: Connection error

**环境信息 / Environment Information**
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.5.0-25-generic-x86_64-with-glibc2.35.
python版本：3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.36

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/qiaoquanbin/project/chatgpt/Langchain-Chatchat/Langchain-Chatchat-demo/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu
==============================Langchain-Chatchat Configuration==============================

**附加信息 / Additional Information**
如何在CPU上离线部署和使用，不使用openai-api。

**Comment by quinbyjoe** [comment]
@zRzRzRzRzRzRzR 您好，麻烦帮忙分析解答，感谢。

**Comment by quinbyjoe** [comment]
model_config.py做如下修改，依然无法解决问题：
`ONLINE_LLM_MODEL = {                                                                                                      
    "chatglm3-6b": {                                                                                                      
        "model_name": "chatglm3-6b",                                                                                      
        "api_base_url": "http://127.0.0.1,20000/v1",                                                                      
        "api_key": "EMPTY",                                                                                               
        "local_model_path": "/home/qiaoquanbin/project/chatgpt/Langchain-Chatchat/Langchain-Chatchat-demo/chatglm3-6b",   
    },                                                                                                                    
                                                                                                                          
    "openai-api": {                                                                                                       
        "model_name": "glm-4",                                                                                            
        "api_base_url": "http://127.0.0.1,20000/v1",                                                                      
        "api_key": "EMPTY",                                                                                               
        "openai_proxy": "",                                                                                               
    },                                                                                                                    
`

**Comment by ThePiii** [comment]
我也遇到了一样的问题，请问你解决了吗

**Comment by Autism-al** [comment]
我也遇到了这个问题 为什么用的本地的离线模型还会一直报openai的连接错误

**Comment by quinbyjoe** [comment]
> 我也遇到了一样的问题，请问你解决了吗

没有解决。

**Comment by quinbyjoe** [comment]
> 我也遇到了这个问题 为什么用的本地的离线模型还会一直报openai的连接错误

应该是配置的问题，但是无法解决。
