### ISSUE TITLE
报错：'NoneType' object has no attribute 'conjugate'

### ISSUE THREAD

**Issue by Gaki1993** [chatchat-space/Langchain-Chatchat#3459]
在python init_database.py --recreate-vs这一步出错
bge-large-zh是完整的
请问在model_config.py中填写Embedding的正确路径的格式是什么？
        "bge-small-zh": "BAAI/bge-small-zh",
        "bge-base-zh": "BAAI/bge-base-zh",
        "bge-large-zh": "BAAI/bge-large-zh",
        "bge-large-zh-noinstruct": "BAAI/bge-large-zh-noinstruct",
        "bge-base-zh-v1.5": "BAAI/bge-base-zh-v1.5",
        "bge-large-zh-v1.5": "D:\AI LLM\Langchain-Chatchat\bge-large-zh-v1.5",
这样填写正确吗？

**Comment by visionaries787** [comment]
解决了吗？我也遇到这个问题了

**Comment by Lam-ssan** [comment]
重新下载embedding模型，放在BAAI文件夹下

**Comment by Gaki1993** [comment]
> 重新下载embedding模型，放在BAAI文件夹下

感谢，解决了
