### ISSUE TITLE
[FEATURE] 未来可增加Bloom系列模型吗？根据甲骨易的测试，这系列中文评测效果不错

### ISSUE THREAD

**Issue by SaraiQX** [chatchat-space/Langchain-Chatchat#346]
**功能描述 / Feature Description**
Bloom系列模型，包括 Bloomz_560m, bloomz_1b1, bloomz_3b, bloomz_7b1_mt
平均评测表现均超过MOSS模型。后两个模型接近ChatGLM.
感谢团队的大爱~~

参考文章：https://www.geekpark.net/news/318946

**Comment by imClumsyPanda** [comment]
好的 收到建议，会尽快进行测试
