### ISSUE TITLE
【源文件】和【向量库】有× （打叉）是什么意思啊 

### ISSUE THREAD

**Issue by Thunderltx** [chatchat-space/Langchain-Chatchat#3460]
![微信截图_20240321113606](https://github.com/chatchat-space/Langchain-Chatchat/assets/37621028/9497600b-c900-4e0a-b377-40babec429dd)

**Comment by glide-the** [comment]
0.2.10更新后的bug，可以忽略这个问题

**Comment by apsyang** [comment]
我也遇到同样的问题，报错如下：

：cannot import name 'KO_NAMES' from 'charset_normalizer.constant' (/root/anaconda3/envs/chatchat/lib/python3.11/site-packages/charset_normalizer/constant.py)
- ERROR: ImportError: 从文件 samples/本地知识库.txt 加载文档时出错：cannot import name 'partition' from 'unstructured.partition.auto' (/root/anaconda3/envs/chatchat/lib/python3.11/site-packages/unstructured/partition/auto.py)

**Comment by Thunderltx** [comment]
> 0.2.10更新后的bug，可以忽略这个问题
原来是bug啊，好的，了解了

**Comment by weigong1983** [comment]
# 已使用cell_renderer做替换处理，此处就不需要重复处理
            # doc_details["in_folder"] = doc_details["in_folder"].replace(True, "✓").replace(False, "×")
            # doc_details["in_db"] = doc_details["in_db"].replace(True, "✓").replace(False, "×")

            gb = config_aggrid(
                doc_details,
                {
                    ("No", "序号"): {},
                    ("file_name", "文档名称"): {},
                    # ("file_ext", "文档类型"): {},
                    # ("file_version", "文档版本"): {},
                    ("document_loader", "文档加载器"): {},
                    ("docs_count", "文档数量"): {},
                    ("text_splitter", "分词器"): {},
                    # ("create_time", "创建时间"): {},
                    ("in_folder", "源文件"): {"cellRenderer": cell_renderer},
                    ("in_db", "向量库"): {"cellRenderer": cell_renderer},
                },
                "multiple",
            )

**Comment by DreamZhongJu** [comment]
同问
