### ISSUE TITLE
支持Google的gemma模型

### ISSUE THREAD

**Issue by xiyueliuyun** [chatchat-space/Langchain-Chatchat#3463]
gemma 2b在个人电脑上能流畅运行，可以为Langchain-Chatchat增加更多的可能性

**Comment by hw1481826110** [comment]
可以说一下使用gemma:2b的具体方法吗？我的电脑配置比较低，只能跑gemma:2b这样的轻量级模型，期待您的回答

**Comment by zRzRzRzRzRzRzR** [comment]
现在就支持，更新transformer和fschat就行了
