### ISSUE TITLE
新建知识库时选择bge-large-zh或者bge-large-zh-v1.5 embedding模型时不能够成功创建

### ISSUE THREAD

**Issue by lrn201** [chatchat-space/Langchain-Chatchat#3464]
**问题描述 / Problem Description**
新建知识库时选择bge-large-zh或者bge-large-zh-v1.5时不能够成功创建 

**实际结果 / Actual Result**

> INFO:     127.0.0.1:48626 - "POST /knowledge_base/search_docs HTTP/1.1" 200 OK
> 2024-03-21 19:19:54,388 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 200 OK"
> 2024-03-21 19:22:13,855 - faiss_cache.py[line:92] - INFO: loading vector store in '11/vector_store/bge-large-zh-v1.5' from disk.
> 2024-03-21 19:22:13,872 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh-v1.5
> 2024-03-21 19:22:13,883 - embeddings_api.py[line:39] - **_ERROR_:** Error while deserializing header: HeaderTooLarge
> 2024-03-21 19:22:13,884 - kb_api.py[line:34] - **_ERROR_:** TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
> INFO:     127.0.0.1:38382 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 200 OK
> 2024-03-21 19:22:13,888 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 200 OK"

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：ChatGLM3-6B 
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型 ： faiss

**Comment by Gaki1993** [comment]
好多人都遇到这个问题

**Comment by lrn201** [comment]
> **问题描述 / Problem Description** 新建知识库时选择bge-large-zh或者bge-large-zh-v1.5时不能够成功创建
> 
> **实际结果 / Actual Result**
> 
> > INFO:     127.0.0.1:48626 - "POST /knowledge_base/search_docs HTTP/1.1" 200 OK
> > 2024-03-21 19:19:54,388 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/search_docs "HTTP/1.1 200 OK"
> > 2024-03-21 19:22:13,855 - faiss_cache.py[line:92] - INFO: loading vector store in '11/vector_store/bge-large-zh-v1.5' from disk.
> > 2024-03-21 19:22:13,872 - SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh-v1.5
> > 2024-03-21 19:22:13,883 - embeddings_api.py[line:39] - **_ERROR_:** Error while deserializing header: HeaderTooLarge
> > 2024-03-21 19:22:13,884 - kb_api.py[line:34] - **_ERROR_:** TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method
> > INFO:     127.0.0.1:38382 - "POST /knowledge_base/create_knowledge_base HTTP/1.1" 200 OK
> > 2024-03-21 19:22:13,888 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/knowledge_base/create_knowledge_base "HTTP/1.1 200 OK"
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：v0.2.10
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型：ChatGLM3-6B
> * 使用的 Embedding 模型：bge-large-zh-v1.5
> * 使用的向量库类型 ： faiss


我重新下载模型之后就好了

**Comment by lrn201** [comment]
换了qwen-7b还是这样
