### ISSUE TITLE
关于知识库无法被正确添加，但是可以使用的问题。

### ISSUE THREAD

**Issue by ccdisk** [chatchat-space/Langchain-Chatchat#3469]
在wiki中有一段描述：在WebUI界面上传知识库，则必须保证知识库进行向量化，成功之后，文件会被切分并在向量位置打钩。 下图展示了成功上传知识库的画面。

我上传了知识库文件，被分词，但是在向量库，以及源文件位置是打叉×的。如图：
![微信截图_20240322093343](https://github.com/chatchat-space/Langchain-Chatchat/assets/154208224/ff86be26-c281-4d69-8a03-16c8a8547594)
这个不知道是什么情况。

**Comment by wxwwt** [comment]
> 在wiki中有一段描述：在WebUI界面上传知识库，则必须保证知识库进行向量化，成功之后，文件会被切分并在向量位置打钩。 下图展示了成功上传知识库的画面。
> 
> 我上传了知识库文件，被分词，但是在向量库，以及源文件位置是打叉×的。如图： ![微信截图_20240322093343](https://private-user-images.githubusercontent.com/154208224/315852834-ff86be26-c281-4d69-8a03-16c8a8547594.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyMDE0MTcsIm5iZiI6MTcxMTIwMTExNywicGF0aCI6Ii8xNTQyMDgyMjQvMzE1ODUyODM0LWZmODZiZTI2LWMyODEtNGQ2OS04YTAzLTE2YzhhODU0NzU5NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyM1QxMzM4MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNGIxZTlkNzIyMjRkZDMxNzJjYzVjM2RmNjRlZTdhODM2OGFkMDI1NjQ5NDE5NDJhNDc0MDhjZDhlMDE3MzEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bcrE32hSp7EQc7KnwSEVybPXVYul-fLep7yOL7dLM2I) 这个不知道是什么情况。

我也是类似的情况 兄弟 你最后解决了这个问题吗

**Comment by glide-the** [comment]
这是0.2.10的bug，下个版本修复
