### ISSUE TITLE
[BUG] 使用微调模型进行对话异常，其他工具调用正常

### ISSUE THREAD

**Issue by Wo272362956** [chatchat-space/Langchain-Chatchat#3473]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / 使用微调后的模型，对话返回异常，但是其他系统正常

**复现问题的步骤 / Steps to Reproduce**
使用llama-factorty微调模型后，导出模型，加载新模型，进行对话，回答正常，在langchain进行llm对话，返回英文并且对话异常

**预期的结果 / Expected Result**
描述应该出现的结果 /对话正常，反回中文微调后数据

**实际结果 / Actual Result**
描述实际发生的结果 / 返回英文，不是微调的结果

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen1.5-0.5B微调后的模型
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: windows
- Python 版本 / Python version: python3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/15905436/18795a71-1242-4e65-b479-f4781ee7ecea)
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/15905436/990fdda5-4641-4364-ad52-f4fad5ad343a)

**Comment by Wo272362956** [comment]
我已经成功设置了具体的模型配置 并且在前台做了模型切换，应该不是你所说的问题
![Uploading 3.png…]()

**Comment by zzp1230** [comment]
我也遇到同样的问题

**Comment by manchiy** [comment]
可以测试下原生加载和vllm加载对比结果，看是否因为vllm加速导致的。

**Comment by zRzRzRzRzRzRzR** [comment]
清按照wiki的方式加载微调模型
