### ISSUE TITLE
[BUG] webui_pages/utils.py search_kb_docs函数score_threshold参数应该为float类型

### ISSUE THREAD

**Issue by weigong1983** [chatchat-space/Langchain-Chatchat#3476]
Line 553 行：    
def search_kb_docs(
            self,
            knowledge_base_name: str,
            query: str = "",
            top_k: int = VECTOR_SEARCH_TOP_K,
            # score_threshold: **int** = SCORE_THRESHOLD,
            # FIX BUG:   int -> float
            score_threshold: **float** = SCORE_THRESHOLD,
            file_name: str = "",
            metadata: dict = {},
    ) -> List:

**Comment by zRzRzRzRzRzRzR** [comment]
是的啊，默认是0.6吧
