### ISSUE TITLE
[BUG] 如果我不加载任何本地大模型，只使用在线的api，应该怎么设置

### ISSUE THREAD

**Issue by estuday** [chatchat-space/Langchain-Chatchat#3478]
你好，
请求如题，如果在model_config.py 中留空，会报错。

**Comment by hotdogarea** [comment]
是不是无法只使用在线模型？
本地现在不需要跑大模型，直接调用千问api，报错如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/11146882/45696c42-ca61-4f56-9a04-996ea507cac9)
