### ISSUE TITLE
上传的excel如何让每一行当作作为一个向量内容

### ISSUE THREAD

**Issue by goldmei** [chatchat-space/Langchain-Chatchat#3479]
上传的excel如何让每一行作为一个切割，每行内容作为 一个向量存储

**Comment by zRzRzRzRzRzRzR** [comment]
查考CSV的办法

**Comment by zhjjoin** [comment]
尝试增加下表头，然后保存成csv格式，可以识别成一行是一个向量的效果。
![Uploading 微信截图_20240613172942.png…]()
