### ISSUE TITLE
知识库回答模式中，没有匹配到相关信息，但仍然给出了三条知识库匹配结果

### ISSUE THREAD

**Issue by LHY-Distance** [chatchat-space/Langchain-Chatchat#3488]
**问题描述 / Problem Description**
在知识库回答模式中，没有匹配到相关信息，但仍然会给出三条知识库匹配结果
![Uploading 1.png…]()

**预期的结果 / Expected Result**
我认为，在知识库回答模式中，若是匹配到相关信息，则显示知识库匹配结果
若是没有匹配到相关信息，应当只回答没有查询到，不应该显示“√ 知识库匹配结果”

**Comment by zRzRzRzRzRzRzR** [comment]
这个是因为框架是这么写的吧，匹配结果应该是空的

**Comment by LHY-Distance** [comment]
不是的诶，是有显示三条匹配结果的，但是是毫无关系的。比如下面的图






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/Langchain-Chatchat"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月9日(星期二) 晚上6:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/Langchain-Chatchat] 知识库回答模式中，没有匹配到相关信息，但仍然给出了三条知识库匹配结果 (Issue #3488)





 
这个是因为框架是这么写的吧，匹配结果应该是空的

**Comment by zRzRzRzRzRzRzR** [comment]
哦那应该是embed模型的问题，没有匹配到了

**Comment by 488283943** [comment]
> 哦那应该是embed模型的问题，没有匹配到了

我能匹配到消息但是还是没回答
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/73679865/fa5502a8-b85a-400c-85c7-155923ad905c)
