### ISSUE TITLE
如何添加其他的功能

### ISSUE THREAD

**Issue by WoNeiDieA** [chatchat-space/Langchain-Chatchat#3489]
正在用该框架作为毕设，毕设内容是面向校内用户的一个知识问答系统。想要添加“知识卡片推荐”模块，例如当向模型提问“一等奖学金政策”时，模型也会给出其他奖学金政策。该从哪里添加这个功能/需要调用哪个接口

**Comment by glide-the** [comment]
如果您需要做二次开发，您需要了解的是前端交互代码
如果您想使用LLm推荐相似内容，这是个复杂的问题，建议使用langchain的模块自己设计业务需求，llama-index也适合这类的需求

**Comment by lzh1998-jansen** [comment]
> 如果您需要做二次开发，您需要了解的是前端交互代码 如果您想使用LLm推荐相似内容，这是个复杂的问题，建议使用langchain的模块自己设计业务需求，llama-index也适合这类的需求

我对webui.py中的部分文字内容进行了修改，但是不生效，这是什么问题？
