### ISSUE TITLE
 AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by jidandan666** [chatchat-space/Langchain-Chatchat#3490]
**问题描述 / AttributeError: 'NoneType' object has no attribute 'get'
 文件对话时，上传文件，上传英文文件不报错，上传中文出现这个错。大概因为什么原因？

 python10 ,使用docker部署，环境配置按照requirements.txt

**Comment by zixiaotan21** [comment]
同样遇到这个问题，我是上传txt文档，分词器选用的是markdownheader textsplitter,想问问楼主解决了吗~

**Comment by ReverseSystem001** [comment]
> 同样遇到这个问题，我是上传txt文档，分词器选用的是markdownheader textsplitter,想问问楼主解决了吗~

问题解决了吗
