### ISSUE TITLE
[BUG] 使用LLM模型问答 报错 （  --all-api 模式启动）

### ISSUE THREAD

**Issue by zhanland** [chatchat-space/Langchain-Chatchat#3491]
**问题描述 / Problem Description**
     使用API  接口      /chat/chat  与LLM模型对话   报错 

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-glibc2.28.
python版本：3.11.7 (main, Mar 17 2024, 18:54:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': 'e017dfbe9c13efd1578b80cddccd8f6a.wm4LpRwDyjLVEwHw',
 'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu
==============================Langchain-Chatchat Configuration==============================

2024-03-23 13:14:17,624 - startup.py[line:655] - INFO: 正在启动服务：
2024-03-23 13:14:17,624 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /root/pyproject/Langchain-Chatchat/logs
/usr/local/python3.11/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-03-23 13:14:22 | INFO | model_worker | Register to controller
2024-03-23 13:14:22 | ERROR | stderr | INFO:     Started server process [5348]
2024-03-23 13:14:22 | ERROR | stderr | INFO:     Waiting for application startup.
2024-03-23 13:14:22 | ERROR | stderr | INFO:     Application startup complete.
2024-03-23 13:14:22 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-03-23 13:14:24 | INFO | model_worker | Loading the model ['chatglm3-6b'] on worker f507e34e ...
2024-03-23 13:14:24 | WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting eos_token is not supported, use the default one.
2024-03-23 13:14:24 | WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting pad_token is not supported, use the default one.
2024-03-23 13:14:24 | WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting unk_token is not supported, use the default one.
Loading checkpoint shards:   0%|                                                              | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|███████▋                                              | 1/7 [00:09<00:54,  9.00s/it]
Loading checkpoint shards:  29%|███████████████▍                                      | 2/7 [00:18<00:47,  9.58s/it]
Loading checkpoint shards:  43%|███████████████████████▏                              | 3/7 [00:28<00:37,  9.34s/it]
Loading checkpoint shards:  57%|██████████████████████████████▊                       | 4/7 [00:37<00:27,  9.22s/it]
Loading checkpoint shards:  71%|██████████████████████████████████████▌               | 5/7 [00:47<00:18,  9.49s/it]
Loading checkpoint shards:  86%|██████████████████████████████████████████████▎       | 6/7 [00:57<00:09,  9.66s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████| 7/7 [01:02<00:00,  8.14s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████| 7/7 [01:02<00:00,  8.86s/it]
2024-03-23 13:15:27 | ERROR | stderr | 
2024-03-23 13:15:27 | INFO | model_worker | Register to controller
INFO:     Started server process [7866]
INFO:     Waiting for application startup.
INFO:     Application startup complete.

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-glibc2.28.
python版本：3.11.7 (main, Mar 17 2024, 18:54:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-4)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b', 'zhipu-api', 'openai-api'] @ cpu
{'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'THUDM/chatglm3-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': 'e017dfbe9c13efd1578b80cddccd8f6a.wm4LpRwDyjLVEwHw',
 'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'cpu',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
==============================Langchain-Chatchat Configuration==============================

INFO:     127.0.0.1:45494 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     127.0.0.1:45498 - "GET / HTTP/1.1" 307 Temporary Redirect

INFO:     127.0.0.1:45572 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     115.148.152.153:57635 - "GET /docs HTTP/1.1" 200 OK
INFO:     115.148.152.153:57635 - "GET /static-offline-docs/swagger-ui.css HTTP/1.1" 200 OK
INFO:     115.148.152.153:57636 - "GET /static-offline-docs/swagger-ui-bundle.js HTTP/1.1" 200 OK
INFO:     115.148.152.153:57636 - "GET /openapi.json HTTP/1.1" 200 OK
INFO:     115.148.152.153:57636 - "GET /static-offline-docs/favicon.png HTTP/1.1" 200 OK
INFO:     115.148.152.153:57639 - "POST /chat/search_engine_chat HTTP/1.1" 200 OK
/usr/local/python3.11/lib/python3.11/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: The class `langchain_community.chat_models.openai.ChatOpenAI` was deprecated in langchain-community 0.0.10 and will be removed in 0.2.0. An updated version of the class exists in the langchain-openai package and should be used instead. To use it run `pip install -U langchain-openai` and import as `from langchain_openai import ChatOpenAI`.
  warn_deprecated(
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/python3.11/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/python3.11/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/usr/local/python3.11/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/usr/local/python3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 571, in receive
    await self.message_event.wait()
  File "/usr/local/python3.11/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7fda1ce025d0

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 412, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/usr/local/python3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    |     yield
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 231, in handle_request
    |     resp = self._pool.handle_request(req)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    |     raise exc from None
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    |     response = connection.handle_request(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    |     raise exc
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    |     stream = self._connect(request)
    |              ^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    |     stream = self._network_backend.connect_tcp(**kwargs)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    |     with map_exceptions(exc_map):
    |   File "/usr/local/python3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    |     raise to_exc(exc) from exc
    | httpcore.ConnectError: [Errno 101] Network is unreachable
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 44, in _get_url
    |     resp = self._client.request(method, url, follow_redirects=True, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_client.py", line 828, in request
    |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_client.py", line 915, in send
    |     response = self._send_handling_auth(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_client.py", line 943, in _send_handling_auth
    |     response = self._send_handling_redirects(
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_client.py", line 980, in _send_handling_redirects
    |     response = self._send_single_request(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_client.py", line 1016, in _send_single_request
    |     response = transport.handle_request(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 230, in handle_request
    |     with map_httpcore_exceptions():
    |   File "/usr/local/python3.11/lib/python3.11/contextlib.py", line 158, in __exit__
    |     self.gen.throw(typ, value, traceback)
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    |     raise mapped_exc(message) from exc
    | httpx.ConnectError: [Errno 101] Network is unreachable
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/root/pyproject/Langchain-Chatchat/server/chat/search_engine_chat.py", line 164, in search_engine_chat_iterator
    |     docs = await lookup_search_engine(query, search_engine_name, top_k, split_result=split_result)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/pyproject/Langchain-Chatchat/server/chat/search_engine_chat.py", line 112, in lookup_search_engine
    |     results = await run_in_threadpool(search_engine, query, result_len=top_k, split_result=split_result)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/root/pyproject/Langchain-Chatchat/server/chat/search_engine_chat.py", line 37, in duckduckgo_search
    |     return search.results(text, result_len)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/langchain_community/utilities/duckduckgo_search.py", line 111, in results
    |     for r in self._ddgs_text(query, max_results=max_results)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/langchain_community/utilities/duckduckgo_search.py", line 57, in _ddgs_text
    |     return [r for r in ddgs_gen]
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/langchain_community/utilities/duckduckgo_search.py", line 57, in <listcomp>
    |     return [r for r in ddgs_gen]
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 105, in text
    |     for i, result in enumerate(results, start=1):
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 133, in _text_api
    |     vqd = self._get_vqd(keywords)
    |           ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 63, in _get_vqd
    |     resp = self._get_url("POST", "https://duckduckgo.com", data={"q": keywords})
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/python3.11/lib/python3.11/site-packages/duckduckgo_search/duckduckgo_search.py", line 57, in _get_url
    |     raise HTTPException(f"_get_url() {url} HttpError: {ex}")
    | duckduckgo_search.exceptions.HTTPException: _get_url() https://duckduckgo.com HttpError: [Errno 101] Network is unreachable
    +------------------------------------
INFO:     115.148.152.153:57643 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
严格依赖版本安装
