### ISSUE TITLE
如何让知识库都进行向量化？

### ISSUE THREAD

**Issue by xx59469xx** [chatchat-space/Langchain-Chatchat#3494]
我使用提供的指令初始化了知识库 python init_database.py --recreate-vs，然后发现源文件和向量库下面没有打勾，但是当我使用该知识库问问题时确实能回答问题并且出处的匹配是正确的，请问这是什么原因呢？

**Comment by xx59469xx** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44127236/4bb9db5f-d49a-4cae-950b-bd5bb48f7922)

**Comment by AlvinAi96** [comment]
> ![图像](https://private-user-images.githubusercontent.com/44127236/316299205-4bb9db5f-d49a-4cae-950b-bd5bb48f7922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM1OTYsIm5iZiI6MTcxMTM1MzI5NiwicGF0aCI6Ii80NDEyNzIzNi8zMTYyOTkyMDUtNGJiOWRiNWYtZDQ5YS00Y2FlLTk1MGItYmQ1YmI0OGY3OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTk3MTFjZWY0N2E4MGNlMjExMDM2MGIzMDVmNGUxYzE5NDZmZDFmMGQzYWNkYTNhMjc5MjgzYWRkMzZjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_iVGYg8m_eIDPouf87J0wPtg_CLdLgxDuXwK6SLjpc)

我也遇到相同的问题。

**Comment by AlvinAi96** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/44127236/316299205-4bb9db5f-d49a-4cae-950b-bd5bb48f7922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM1OTYsIm5iZiI6MTcxMTM1MzI5NiwicGF0aCI6Ii80NDEyNzIzNi8zMTYyOTkyMDUtNGJiOWRiNWYtZDQ5YS00Y2FlLTk1MGItYmQ1YmI0OGY3OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTk3MTFjZWY0N2E4MGNlMjExMDM2MGIzMDVmNGUxYzE5NDZmZDFmMGQzYWNkYTNhMjc5MjgzYWRkMzZjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_iVGYg8m_eIDPouf87J0wPtg_CLdLgxDuXwK6SLjpc)
> 
> 我也遇到相同的问题。

找到问题了，前端处理逻辑重复了。该下图修改就行。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/42187008/d1eca026-a343-4bc4-aee3-e639f83261bb)

**Comment by xx59469xx** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/44127236/316299205-4bb9db5f-d49a-4cae-950b-bd5bb48f7922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM1OTYsIm5iZiI6MTcxMTM1MzI5NiwicGF0aCI6Ii80NDEyNzIzNi8zMTYyOTkyMDUtNGJiOWRiNWYtZDQ5YS00Y2FlLTk1MGItYmQ1YmI0OGY3OTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NTk3MTFjZWY0N2E4MGNlMjExMDM2MGIzMDVmNGUxYzE5NDZmZDFmMGQzYWNkYTNhMjc5MjgzYWRkMzZjM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p_iVGYg8m_eIDPouf87J0wPtg_CLdLgxDuXwK6SLjpc)
> > 
> > 
> > 我也遇到相同的问题。
> 
> 找到问题了，前端处理逻辑重复了。该下图修改就行。 ![image](https://private-user-images.githubusercontent.com/42187008/316471443-d1eca026-a343-4bc4-aee3-e639f83261bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MzExMDksIm5iZiI6MTcxMTQzMDgwOSwicGF0aCI6Ii80MjE4NzAwOC8zMTY0NzE0NDMtZDFlY2EwMjYtYTM0My00YmM0LWFlZTMtZTYzOWY4MzI2MWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA1MjY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTg3NjJmNzk4MTc4ZTA1YWQ1YzNlYjg0MjM4ZGQwOTY0ZGFiOTYwNjkxNmZlNjJjZmQyODk0YzI1Y2YyNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wx-4R5X5iD_BMTnxeqvqMFRpycHFLLyKdf-e58vv4c0)

谢谢，真的有用！
