### ISSUE TITLE
最新版本是否支持chatglm2-6b-int4它

### ISSUE THREAD

**Issue by qwerasdf555** [chatchat-space/Langchain-Chatchat#3495]
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22000-SP0.
python版本：3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b-int4'] @ cpu
{'device': 'cpu',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'D:\\mx\\Langchain-Chatchat\\model\\chatglm2-6b-int4',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cpu
2024-03-24 18:13:05 | ERROR | stderr | INFO:     Uvicorn running on http://127.0.0.1:20000 (Press CTRL+C to quit)
2024-03-24 18:13:06 | INFO | model_worker | Loading the model ['chatglm2-6b-int4'] on worker 87ee7829 ...
一直卡在这不动

cpu运行16G
或者有其他cup可以运行的小模型吗

**Comment by qwerasdf555** [comment]
那个模型可以只用cpu 不用gup

**Comment by zRzRzRzRzRzRzR** [comment]
只用CPU就行了，其他int4要有专门的库做
