### ISSUE TITLE
[FEATURE] 在知识库问答中添加keyBERT支持

### ISSUE THREAD

**Issue by liurhino** [chatchat-space/Langchain-Chatchat#3498]
**功能描述 / Feature Description**
在知识库问答中，先试用keyBERT提取query中的关键字，然后使用提取出的关键字进行向量搜索

**解决的问题 / Problem Solved**
当用户的提出问题的句子和知识库中句子相差较大时，直接搜索无法查询到结果。使用关键词搜索应该可以提高召回成功率

**实现建议 / Implementation Suggestions**
keyBERT实现https://maartengr.github.io/KeyBERT

**替代方案 / Alternative Solutions**
使用LLM加prompt提取关键词。但是尝试本地LLM无法返回结果。

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by glide-the** [comment]
对于这个需求，我们准备了3.0的需求收集表，您可以选择在这里面详细描述您的需求，我们会选择一部分功能加入开发计划
https://github.com/chatchat-space/Langchain-Chatchat/issues/2661
