### ISSUE TITLE
[BUG] 解析老版本word的.doc文件时，报错PackageNotFoundError

### ISSUE THREAD

**Issue by madog1983** [chatchat-space/Langchain-Chatchat#3499]
**问题描述 / Problem Description**
在向知识库中添加老版本word的.doc文件（非.docx）时，提示以下错误：
`
2024-03-25 09:45:44,663 - utils.py[line:377] - ERROR: PackageNotFoundError: 从文件 samples/test.doc 加载文档时出错：Package not found at 'G:\langchain-chatchat\Langchain-Chatchat\knowledge_base\samples\content\test.doc'
`

经过调试，发现问题出在项目中/document_loader/mydocloader.py中的RapidOCRDocLoader类中，_get_elements方法内的doc2text方法。其中用于**解析word文档所使用的库是docx库，该库只支持.docx格式，不支持老的.doc格式**。该库在解析文件时会检查文件是否为zip格式，然而老版本的.doc文件非zip格式，会抛出PackageNotFoundError。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.354
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen1.5-1.8B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Windows 11
- Python 版本 / Python version: 3.10.13
- 其他相关环境信息 / Other relevant environment information:

**Comment by 302658980** [comment]
你看看你代码这里是不是doc 而不是.doc 
LOADER_DICT = {"UnstructuredHTMLLoader": ['.html'],
               "UnstructuredMarkdownLoader": ['.md'],
               "JSONLoader": [".json"],
               "JSONLinesLoader": [".jsonl"],
               "CSVLoader": [".csv"],
               # "FilteredCSVLoader": [".csv"], # 需要自己指定，目前还没有支持
               "RapidOCRPDFLoader": [".pdf"],
               "RapidOCRLoader": ['.png', '.jpg', '.jpeg', '.bmp'],
               "UnstructuredEmailLoader": ['.eml', '.msg'],
               "UnstructuredEPubLoader": ['.epub'],
               "UnstructuredExcelLoader": ['.xlsx', '.xlsd'],
               "NotebookLoader": ['.ipynb'],
               "UnstructuredODTLoader": ['.odt'],
               "PythonLoader": ['.py'],
               "UnstructuredRSTLoader": ['.rst'],
               "UnstructuredRTFLoader": ['.rtf'],
               "SRTLoader": ['.srt'],
               "TomlLoader": ['.toml'],
               "UnstructuredTSVLoader": ['.tsv'],
               "UnstructuredWordDocumentLoader": ['.docx','.doc'],
               "UnstructuredXMLLoader": ['.xml'],
               "UnstructuredPowerPointLoader": ['.ppt', '.pptx'],
               "UnstructuredFileLoader": ['.txt'],
               }
               
                              "UnstructuredWordDocumentLoader": ['.docx','.doc'],

**Comment by madog1983** [comment]
![Uploading 20240325154810.png…]()

**Comment by madog1983** [comment]
> 你看看你代码这里是不是doc 而不是.doc LOADER_DICT = {"UnstructuredHTMLLoader": ['.html'], "UnstructuredMarkdownLoader": ['.md'], "JSONLoader": [".json"], "JSONLinesLoader": [".jsonl"], "CSVLoader": [".csv"], # "FilteredCSVLoader": [".csv"], # 需要自己指定，目前还没有支持 "RapidOCRPDFLoader": [".pdf"], "RapidOCRLoader": ['.png', '.jpg', '.jpeg', '.bmp'], "UnstructuredEmailLoader": ['.eml', '.msg'], "UnstructuredEPubLoader": ['.epub'], "UnstructuredExcelLoader": ['.xlsx', '.xlsd'], "NotebookLoader": ['.ipynb'], "UnstructuredODTLoader": ['.odt'], "PythonLoader": ['.py'], "UnstructuredRSTLoader": ['.rst'], "UnstructuredRTFLoader": ['.rtf'], "SRTLoader": ['.srt'], "TomlLoader": ['.toml'], "UnstructuredTSVLoader": ['.tsv'], "UnstructuredWordDocumentLoader": ['.docx','.doc'], "UnstructuredXMLLoader": ['.xml'], "UnstructuredPowerPointLoader": ['.ppt', '.pptx'], "UnstructuredFileLoader": ['.txt'], }
> 
> ```
>                           "UnstructuredWordDocumentLoader": ['.docx','.doc'],
> ```

![20240325154810](https://github.com/chatchat-space/Langchain-Chatchat/assets/6943019/6f6ca8c3-c4bb-448e-a509-4692d78c4beb)
