### ISSUE TITLE
[BUG] pdf文档加载失败

### ISSUE THREAD

**Issue by liwenzheng** [chatchat-space/Langchain-Chatchat#350]
**问题描述 / Problem Description**
pdf存在特殊字符的时候 无法解析 导致整个文档无法加载
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1767832/905b52ce-e2e0-47f1-8d58-271af512e7b5)

**Comment by imClumsyPanda** [comment]
请问可否提供一下具体特殊字符或含有特殊字符的测试文件？
