### ISSUE TITLE
[BUG] 依据源文件重建向量库 总是失败

### ISSUE THREAD

**Issue by myfeelyou** [chatchat-space/Langchain-Chatchat#3500]
我在 某个知识库 test里面的content里面传了2000个txt 每个txt 只有几kb，然后在web页面 在知识库那里 点击  依据源文件重建向量库。

控制台 里面在不停地输出 文档分割片段，  但是页面上 只重建了几个，  那个重建就停止了，  停止的时候，控制台仍然还在分割【因为文件比较多，但是分割完后，整个过程也就完了。】

如果我只在content里面保存100个文件，，他就能重建成功。这是咋回事呢。服务器是  32G内存 16G显存。

**Comment by myfeelyou** [comment]
解决了，不知道是不是我用的测试服务器的原因，我换成api调用去生成，就能正常生成全部2000个数据的向量了

**Comment by zRzRzRzRzRzRzR** [comment]
大文件建议用命令行在后台
