### ISSUE TITLE
[BUG] 知识库上传文件报错403

### ISSUE THREAD

**Issue by zealze** [chatchat-space/Langchain-Chatchat#3502]
对话之类的都可用.只有创建知识库上传文件时报错：AxiosError: Request failed with status code 403
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/17687319/59494844-c577-4024-b698-fa07a377a2ad)

**Comment by zealze** [comment]
临时解决办法：
`cd Langchain-Chatchat`
`mkdir .streamlit && cd streamlit`
`vim config.toml`
追加以下内容
`[server]`
`enableXsrfProtection = false`

**Comment by lujingyu** [comment]
It works for me.
`pip install streamlit==1.28.*`
