### ISSUE TITLE
[FEATURE] 支持kimi大模型

### ISSUE THREAD

**Issue by jiaolongxue** [chatchat-space/Langchain-Chatchat#3504]
**功能描述 / Feature Description**
kimi大模型具备超长上下文的特性，希望能够适配超长大模型

**Comment by glide-the** [comment]
您提交的这个需求我们已经加入了跟进计划
目前项目组正常实现3.0的业务代码，在这个版本中已经初步支持了很多在线和离线模型加载工作
master分支的模型适配代码不会被放入3.0的工作，如果您需要在历史版本中提供支持工作，欢迎pr
