### ISSUE TITLE
关于更换分词器该如何配置？

### ISSUE THREAD

**Issue by 302658980** [chatchat-space/Langchain-Chatchat#3509]
`# TextSplitter配置项，如果你不明白其中的含义，就不要修改。
text_splitter_dict = {
    "ChineseRecursiveTextSplitter": {
        "source": "huggingface",   # 选择tiktoken则使用openai的方法
        "tokenizer_name_or_path": "",
    },
    "SpacyTextSplitter": {
        "source": "huggingface",
        "tokenizer_name_or_path": "gpt2",
    },
    "RecursiveCharacterTextSplitter": {
        "source": "tiktoken",
        "tokenizer_name_or_path": "cl100k_base",
    },
    "MarkdownHeaderTextSplitter": {
        "headers_to_split_on":
            [
                ("#", "head1"),
                ("##", "head2"),
                ("###", "head3"),
                ("####", "head4"),
            ]
    },
}

# TEXT_SPLITTER 名称
TEXT_SPLITTER_NAME = "ChineseRecursiveTextSplitter"

# Embedding模型定制词语的词表文件
EMBEDDING_KEYWORD_FILE = "embedding_keywords.txt"`

我想替换为：
zh-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/zh_core_web_sm-3.7.0/zh_core_web_sm-3.7.0-py3-none-any.whl#sha256=f51075665749e07406d629d1055ce5a68635fae6ab3c34257ee798c62b4fc431
text_splitter = SpacyTextSplitter(pipeline='zh_core_web_sm',chunk_size=1000)

**Comment by 302658980** [comment]
> 嗨，@302658980！很高兴再次看到你。希望你一切都好！
> 
> 根据您提供的代码和上下文，您想要将当前的文本分词器替换为使用'zh_core_web_sm'管道的`SpacyTextSplitter`。您需要修改`make_text_splitter`函数以实现这一点。具体来说，当`splitter_name`设置为使用`SpacyTextSplitter`时，它应使用'zh_core_web_sm'管道。
> 
> 以下是您可以实现的步骤：
> 
> 1. 在代码中找到`make_text_splitter`函数。
> 2. 在此函数内部，找到初始化`SpacyTextSplitter`的部分。
> 3. 修改初始化以显式使用'zh_core_web_sm'管道。
> 
> 根据提供的上下文，需要修改的相关部分似乎是使用`pipeline`参数初始化`TextSplitter`的地方。然而，提供的代码并未明确显示一个分支，其中`SpacyTextSplitter`直接使用'zh_core_web_sm'管道进行实例化。最接近的匹配是一个通用的实例化`TextSplitter`，带有一个`pipeline`参数，这可能是为`SpacyTextSplitter`或另一个分词器准备的。
> 
> 鉴于此，确保`SpacyTextSplitter`使用'zh_core_web_sm'的直接修改可能如下所示：
> 
> ```python
> # 这是一个假设的修改，因为在提供的上下文中并未直接使用确切的类名SpacyTextSplitter。
> if splitter_name == "SpacyTextSplitter":  # 假设SpacyTextSplitter是预期的类名
>     text_splitter = TextSplitter(
>         pipeline="zh_core_web_sm",
>         chunk_size=chunk_size,
>         chunk_overlap=chunk_overlap
>     )
> ```
> 
> 然而，由于提供的上下文并未明确包含`SpacyTextSplitter`的分支，且修改基于其使用的假设，您应该审查`make_text_splitter`的实现，以确保它与代码库的结构和命名约定相符。如果`SpacyTextSplitter`是一个自定义的或间接引用的分词器，确保其实例化与'zh_core_web_sm'管道的预期使用相符。
> 
> 关于`text_splitter_dict`的具体作用和与`TEXT_SPLITTER_NAME`配置的交互方式，由于在提供的上下文中并未明确提及`text_splitter_dict`，因此无法直接回答这个问题。如果您能提供更多关于`text_splitter_dict`的使用情况或代码示例，我可能能提供更具体的帮助。
> 
> 参考资料：
> 
> * [server/knowledge_base/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/utils.py)
> * [[FEATURE] 0.2.0版本如何自定义知识库文档切分方式？](https://github.com/chatchat-space/Langchain-Chatchat/issues/1175)
> 
> ## Sources
> * [[FEATURE] 0.2.0版本如何自定义知识库文档切分方式？](https://github.com/chatchat-space/Langchain-Chatchat/issues/1175)
> * [server/knowledge_base/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/knowledge_base/utils.py)
> * [text_splitter/chinese_recursive_text_splitter.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/text_splitter/chinese_recursive_text_splitter.py)
> * [text_splitter/chinese_text_splitter.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/text_splitter/chinese_text_splitter.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

def make_text_splitter(
        splitter_name: str = TEXT_SPLITTER_NAME,
        chunk_size: int = CHUNK_SIZE,
        chunk_overlap: int = OVERLAP_SIZE,
        llm_model: str = LLM_MODELS[0],
):
    """
    根据参数获取特定的分词器
    """
    splitter_name = splitter_name or "SpacyTextSplitter"
    try:
        if splitter_name == "MarkdownHeaderTextSplitter":  # MarkdownHeaderTextSplitter特殊判定
            headers_to_split_on = text_splitter_dict[splitter_name]['headers_to_split_on']
            text_splitter = langchain.text_splitter.MarkdownHeaderTextSplitter(
                headers_to_split_on=headers_to_split_on)
        else:

            try:  ## 优先使用用户自定义的text_splitter
                text_splitter_module = importlib.import_module('text_splitter')
                TextSplitter = getattr(text_splitter_module, splitter_name)
            except:  ## 否则使用langchain的text_splitter
                text_splitter_module = importlib.import_module('langchain.text_splitter')
                TextSplitter = getattr(text_splitter_module, splitter_name)

            if text_splitter_dict[splitter_name]["source"] == "tiktoken":  ## 从tiktoken加载
                try:
                    text_splitter = TextSplitter.from_tiktoken_encoder(
                        encoding_name=text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
                        pipeline="zh_core_web_sm",
                        chunk_size=chunk_size,
                        chunk_overlap=chunk_overlap
                    )
                except:
                    text_splitter = TextSplitter.from_tiktoken_encoder(
                        encoding_name=text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
                        chunk_size=chunk_size,
                        chunk_overlap=chunk_overlap
                    )
            elif text_splitter_dict[splitter_name]["source"] == "huggingface":  ## 从huggingface加载
                if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "":
                    config = get_model_worker_config(llm_model)
                    text_splitter_dict[splitter_name]["tokenizer_name_or_path"] = \
                        config.get("model_path")

                if text_splitter_dict[splitter_name]["tokenizer_name_or_path"] == "gpt2":
                    from transformers import GPT2TokenizerFast
                    from langchain.text_splitter import CharacterTextSplitter
                    tokenizer = GPT2TokenizerFast.from_pretrained("gpt2")
                else:  ## 字符长度加载
                    from transformers import AutoTokenizer
                    tokenizer = AutoTokenizer.from_pretrained(
                        text_splitter_dict[splitter_name]["tokenizer_name_or_path"],
                        trust_remote_code=True)
                text_splitter = TextSplitter.from_huggingface_tokenizer(
                    tokenizer=tokenizer,
                    chunk_size=chunk_size,
                    chunk_overlap=chunk_overlap
                )
            else:
                try:
                    text_splitter = TextSplitter(
                        pipeline="zh_core_web_sm",
                        chunk_size=chunk_size,
                        chunk_overlap=chunk_overlap
                    )
                except:
                    text_splitter = TextSplitter(
                        chunk_size=chunk_size,
                        chunk_overlap=chunk_overlap
                    )
    except Exception as e:
        print(e)
        text_splitter_module = importlib.import_module('langchain.text_splitter')
        TextSplitter = getattr(text_splitter_module, "RecursiveCharacterTextSplitter")
        text_splitter = TextSplitter(chunk_size=250, chunk_overlap=50)
    return text_splitter
    我看源码里有这个，zh_core_web_sm  怎么配置使用呢

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki....
