### ISSUE TITLE
建议可以在后期增强一波注释，这样也有助于更多人跟进提PR

### ISSUE THREAD

**Issue by hongzhew** [chatchat-space/Langchain-Chatchat#351]
知道作者和团队在疯狂更新审查代码，只是建议后续稳定后可以把核心代码进行一些注释的补充，从而能帮助更多人了解各个模块作者的思路从而提出更好的优化。

**Comment by imClumsyPanda** [comment]
收到建议，会尽快完善文档和注释

**Comment by yhyu13** [comment]
@imClumsyPanda https://github.com/context-labs/autodoc 自动解释源码并添加到知识库，不过好像不是源码注释。这个repo好像也是知识库，只不过暂时和openai绑定。
