### ISSUE TITLE
[BUG] azure-api报错object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by devillaws** [chatchat-space/Langchain-Chatchat#3514]
项目跑离线模型都没问题，但使用azure-api跟openai-api报错：
File "/home/panyang/anaconda3/envs/chat240325/lib/python3.10/site-packages/langchain_community/chat_models/openai.py", line 493, in _astream
    if len(chunk["choices"]) == 0:
TypeError: object of type 'NoneType' has no len()
ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/5940a348-d8c4-4b86-a887-5f1c4a971152)

**Comment by zRzRzRzRzRzRzR** [comment]
没有成功访问到模型就会报错这个错误，建议检查是否能ping通模型

**Comment by devillaws** [comment]
> 没有成功访问到模型就会报错这个错误，建议检查是否能ping通模型

感恩，您说对了，resource_name要注意填写格式
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/8604432/89d2ad02-5d38-49a7-9923-3da5792bbd10)
