### ISSUE TITLE
训练时给出有符号的答案，回答的时候为什么符号没有了，或者有的有符号有的没有符号

### ISSUE THREAD

**Issue by liaoqingjian** [chatchat-space/Langchain-Chatchat#3518]
![123](https://github.com/chatchat-space/Langchain-Chatchat/assets/68636520/878cc083-b9ca-4800-956a-9966d439caf7)

**Comment by liaoqingjian** [comment]
![Uploading 122.png…]()

**Comment by glide-the** [comment]
关于表情符号，请选择 Unicode 编码
