### ISSUE TITLE
[BUG] 在使用知识库问答的时候，上传文档，出现了错误，

### ISSUE THREAD

**Issue by lzh1998-jansen** [chatchat-space/Langchain-Chatchat#3530]
**问题描述 / Problem Description**
将文档上传到知识库的这一步骤出现了错误，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/c9739a9d-2930-4676-afdb-90bfca09cbe7)
文档是docx格式，

**Comment by lzh1998-jansen** [comment]
1.尝试将docx转doc尝试，报错，报错信息为，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/874d1644-febf-489f-8c5d-291facfebbb5)
2.原始的docx文档报错信息如下，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/09becf63-f1b0-4160-b1ee-4da031b12fc4)
3.转pdf，是可以成功的

**Comment by lzh1998-jansen** [comment]
4.报错全都定位到，这个函数，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/17465644-648f-4d9c-aac5-610051f7e57b)

**Comment by lzh1998-jansen** [comment]
定位到这里的代码报错，导致的异常，
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/2f7eec9c-8476-42b9-ade3-0206ab1b1742)
然后定位到docx包中的异常，但是这个函数我无法debug进入
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/82a73283-cd29-4a5e-841d-1913dcfd5129)

**Comment by lzh1998-jansen** [comment]
最后定位到这了，怎么修改呢 ==。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/61367424/3aaff5b8-067b-4c5c-8218-50b8088de91a)

**Comment by lzh1998-jansen** [comment]
> **问题描述 / Problem Description** 将文档上传到知识库的这一步骤出现了错误， ![image](https://private-user-images.githubusercontent.com/61367424/316810576-c9739a9d-2930-4676-afdb-90bfca09cbe7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1OTA0NTAsIm5iZiI6MTcxMTU5MDE1MCwicGF0aCI6Ii82MTM2NzQyNC8zMTY4MTA1NzYtYzk3MzlhOWQtMjkzMC00Njc2LWFmZGItOTBiZmNhMDljYmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI4VDAxNDIzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5ZWZjZjQyN2FmNTNjNjAyN2U0OTljOGExMThjNTU1OGIzNDUwNjU5M2RkZDFkZjM2ZDM4NjJiNjE0ZDZhMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zZ4K_mlWpFqhFNYHocPDjL4DLAA47m6xbfDFW1bIito) 文档是docx格式，

没有解决问题 ==。

**Comment by zRzRzRzRzRzRzR** [comment]
paddle ocr读取图片的bug，没发处理
