### ISSUE TITLE
[FEATURE] /chat/chat等接口中能把底层调用LLM的具体返回信息比如usage返回传出吗？

### ISSUE THREAD

**Issue by zhoufurong2022** [chatchat-space/Langchain-Chatchat#3531]
**功能描述 / Feature Description**
/chat/chat 接口目前只接收了正常返回的text内容，但是异常的情况下其他所有信息基本都被内部catch掉了，想要在模型返回异常的时候能直接返回模型本身返回的error_code和error_mgs.

**解决的问题 / Problem Solved**
现在调用的时候排查问题特别不方便，很多异常直接被干掉了，服务端本地可以打印，但是客户端总是需要通过运维日志才能查询到具体异常的信息.

**实现建议 / Implementation Suggestions**
建议把模型的常见参数比如是否结束、使用的token数、异常信息等通过/chat/chat等接口进行直接返回

**Comment by glide-the** [comment]
3.0目前正在推进这一工作
https://github.com/chatchat-space/Langchain-Chatchat/issues/2661
