### ISSUE TITLE
OSError: Incorrect path_or_model_id

### ISSUE THREAD

**Issue by javachens** [chatchat-space/Langchain-Chatchat#3535]
OSError: Incorrect path_or_model_id: ''. Please provide either the path to a local folder or the repo_id of a model on the Hub

**Comment by Fdioa** [comment]
请问解决了吗？我也遇到这种情况了

**Comment by zRzRzRzRzRzRzR** [comment]
降级huggingface hub到 0.20

**Comment by gaojiaran** [comment]
将
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/74803597/7f61ba24-d203-4052-93ff-4df99d3a1f5f)
这个模型设置为公开的大模型，训练时候可以是之前自己保存的训练模型，保存export的时候需要为公开的大模型，我这样解决的
