### ISSUE TITLE
 Unable to access any port application

### ISSUE THREAD

**Issue by javachens** [chatchat-space/Langchain-Chatchat#3537]
The project has been successfully launched，But I can't access the application on any port。I visited http://127.0.0.1:20000，
The error message shows 404 not found

**Comment by javachens** [comment]
@dos

> Hey there, @javachens! Nice to see you around here again. 🚀
> 
> Based on the information provided, it seems that you are trying to access the Langchain-Chatchat application on a port that is not configured for use by the application. The default port configuration in the Langchain-Chatchat application is as follows:
> 
> * Controller port: 21001
> * Worker port: 21002
> * Server port: 8888
> 
> You can find these configurations in the [server/llm_api_stale.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/llm_api_stale.py) file.
> 
> Therefore, if you are trying to access the application via http://127.0.0.1:20000, you are likely trying to connect to a port that is not in use by the application. You should try accessing the application through one of the configured ports, such as:
> 
> * http://127.0.0.1:21001 for the controller,
> * http://127.0.0.1:21002 for the worker, or
> * http://127.0.0.1:8888 for the server.
> 
> If you intended to use port 20000 for a specific part of the application, you would need to adjust the corresponding port configuration in the script to match this intention.
> 
> In addition, there are several similar issues in the Langchain-Chatchat repository that might be helpful:
> 
> * [[BUG] 简洁阐述问题 / Concise description of the issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/3142)
> * [无法访问chachat的api](https://github.com/chatchat-space/Langchain-Chatchat/issues/2670)
> * [autodl 镜像v0.2.10，启动后不报错，但web端打不开](https://github.com/chatchat-space/Langchain-Chatchat/issues/2817)
> * [卡在这不往下走了--Register to controller，用的chatglm2-6b-int4](https://github.com/chatchat-space/Langchain-Chatchat/issues/1970)
> * [ POST /chat/knowledge_base_chat HTTP/1.1" 404 Not Found](https://github.com/chatchat-space/Langchain-Chatchat/issues/2035)
> 
> These issues suggest checking the server configuration, firewall settings, API endpoints, and port tunneling. They also suggest re-pulling the repository and reconfiguring the environment if necessary.
> 
> I hope this information helps you resolve the issue. If you have any further questions or need more clarification, please let me know.
> 
> ## Sources
> * [[BUG] 简洁阐述问题 / Concise description of the issue](https://github.com/chatchat-space/Langchain-Chatchat/issues/3142)
> * [无法访问chachat的api](https://github.com/chatchat-space/Langchain-Chatchat/issues/2670)
> * [autodl 镜像v0.2.10，启动后不报错，但web端打不开](https://github.com/chatchat-space/Langchain-Chatchat/issues/2817)
> * [卡在这不往下走了--Register to controller，用的chatglm2-6b-int4](https://github.com/chatchat-space/Langchain-Chatchat/issues/1970)
> * [ POST /chat/knowledge_base_chat HTTP/1.1" 404 Not Found](https://github.com/chatchat-space/Langchain-Chatchat/issues/2035)
> * [server/llm_api_stale.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/llm_api_stale.py)
> 
> #### About Dosu

I didn't access any port

**Comment by javachens** [comment]
@dosu-bot. 
I cannot access any port application, including knowledge base, pages, etc.

**Comment by javachens** [comment]
@dosu-bot。I checked logs but no useful information found

**Comment by glide-the** [comment]
can you print log file

**Comment by zRzRzRzRzRzRzR** [comment]
你要访问8000端口
