### ISSUE TITLE
reranker问题

### ISSUE THREAD

**Issue by loki-keroro** [chatchat-space/Langchain-Chatchat#3539]
问题：
1.如何启用rerenaker模块，更改参数’USE_RERANKER = True‘就可以了吗？
2.reranker模块在什么阶段中启用，search_engine_chat还是knowledge_base_chat阶段？
3.reranker的使用步骤和细节是怎么样的？

**Comment by zRzRzRzRzRzRzR** [comment]
1. 是的
2. 都用到
3. 重排提高精度，具体可以在chat knowlege代码查询
