### ISSUE TITLE
如何通过上传一份带有题目和答案的文档测试数据库效果

### ISSUE THREAD

**Issue by misi0202** [chatchat-space/Langchain-Chatchat#3543]
**功能描述 / Feature Description**
在构建向量库之后，我希望通过上传一个同时带有问题和答案的文档 通过答案的正确程度 来评估数据库的效果

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zRzRzRzRzRzRzR** [comment]
不行，目前智能对文字进行检索，不能mask一部分
