### ISSUE TITLE
能多线程 批量 embadding吗

### ISSUE THREAD

**Issue by myfeelyou** [chatchat-space/Langchain-Chatchat#3547]
假设我有几十万数据，，分词和向量化 好像都是单线程的，一天也只能处理几万啊 但是只占用2G左右的GPU ，而GPU是16G的 大大的浪费了

**Comment by Zhaibeiebi** [comment]
@dosu-bot  如何利用gpu并发的处理向量化过程，能否具体点呢，是不是只需要修改startup里的参数就可以了。我使用的milvus数据库。  阿里嘎多

**Comment by myfeelyou** [comment]
太慢了啊 怎么修改下啊，，分割3秒1个，我看源代码kb_doc_api.py 里面的recreate_vector_store函数里面 分割是 3多线程的吧，，向量化保存的时候 是 单线程的，大概2秒一个 ，16G的GPU 一直只占用了两个多G， 有人知道怎么改下这个地方吗

**Comment by glide-the** [comment]
dev分支已经对这个问题做了优化

**Comment by myfeelyou** [comment]
@glide-the  那个是直接把dev分支下载下来  然后 定位到 Langchain-Chatchat-dev/chatchat-server/chatchat# python startup.py 这里面运行吗 提示 运行不起来  

  File "startup.py", line 28, in <module>
    from server.utils import FastAPI
  File "/mnt/workspace/langchain-dev/Langchain-Chatchat-dev/chatchat-server/chatchat/server/utils.py", line 11, in <module>
    from langchain_openai.chat_models import ChatOpenAI
ModuleNotFoundError: No module named 'langchain_openai'

**Comment by glide-the** [comment]
目前dev当前分支功能还在迭代，如果您想参与dev的测试，请参考 项目的readme

**Comment by AMAG-AB** [comment]
@myfeelyou 解决了吗 哥们
