### ISSUE TITLE
[BUG] 程序正常运行，就是回答太慢了，一个字一个字的要输出2分钟

### ISSUE THREAD

**Issue by Mioooooo** [chatchat-space/Langchain-Chatchat#3549]
**问题描述 / Problem Description**
程序正常运行，就是回答太慢了，一个字一个字的要输出2分钟，使用的显卡为2块1066TI 6G，配置文件配置了4G的显存，但运算时显卡使用率0%，为啥？我的版本是2.10 cuda为12.1
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37464936/ff2913b7-a7d9-424b-8790-fd4839472ecd)

**Comment by Mioooooo** [comment]
我没有编写任何代码，只是单纯启动了Langchain-Chachat v0.2.10应用程序，理论上显卡使用率应该居高不下，但它现在却为0，我是配置文件哪里没写对吗？或者是我的显卡太过于古老导致了这样的后果呢？

**Comment by Mioooooo** [comment]
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22621-SP0.
python版本：3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm3-6b'] @ cuda
{'device': 'cuda',
 'gpus': '0,1',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'max_gpu_memory': '4GiB',
 'model_path': 'THUDM\\chatglm3-6b',
 'model_path_exists': True,
 'num_gpus': 2,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

**Comment by Mioooooo** [comment]
@dosu-bot

**Comment by Mioooooo** [comment]
@dosu-bot WARNING | transformers_modules.chatglm3-6b.tokenization_chatglm | Setting unk_token is not supported, use the default one 是什么错误

**Comment by Hang-shao** [comment]
这是机器人吧

**Comment by oymclihui** [comment]
我也遇到这个问题 我的显卡是8张 RTX5000每个16G ，也是这个问题，回答一秒要给字输出。显卡使用率是0. 
其中setup.py 我修改一下代码
        else:
            from fastchat.serve.model_worker import app, GptqConfig, AWQConfig, ModelWorker, worker_id

            args.gpus = "0,1,2,3,4,5,6,7"  # GPU的编号,如果有多个GPU，可以设置为"0,1,2,3"
            args.max_gpu_memory = "16GiB"
            args.num_gpus = 8  # model worker的切分是model并行，这里填写显卡的数量

**Comment by oymclihui** [comment]
# 以下为model_worker非常用参数，可根据需要配置
        "load_8bit": False, # 开启8bit量化
        "cpu_offloading": None,
        "gptq_ckpt": None,
        "gptq_wbits": 16,
        "gptq_groupsize": -1,
        "gptq_act_order": False,
        "awq_ckpt": None,
        "awq_wbits": 16,
        "awq_groupsize": -1,
        "model_names": "chatglm3-6b-32k",
        "conv_template": None,
        "limit_worker_concurrency": 5,
        "stream_interval": 2,
        "no_register": False,
        "embed_in_truncate": False,

        # 以下为vllm_worker配置参数,注意使用vllm必须有gpu，仅在Linux测试通过

        # tokenizer = model_path # 如果tokenizer与model_path不一致在此处添加
        'tokenizer_mode':'auto',
        'trust_remote_code':True,
        'download_dir':None,
        'load_format':'auto',
        'dtype':'auto',
        'seed':0,
        'worker_use_ray':False,
        'pipeline_parallel_size':1,
        'tensor_parallel_size':1,
        'block_size':16,
        'swap_space':4 , # GiB
        'gpu_memory_utilization':0.90,
        'max_num_batched_tokens':2560,
        'max_num_seqs':256,
        'disable_log_stats':False,
        'conv_template':None,
        'limit_worker_concurrency':5,
        'no_register':False,
        'num_gpus': 8,
        'engine_use_ray': False,
        'disable_log_requests': False

    },
    "chatglm3-6b-32k": {
        "device": "cuda",
    },
    "chatglm3-6b": {
        "device": "cuda",
    },
    "Qwen1.5-0.5B-Chat": {
        "device": "cuda",
    },
    # 以下配置可以不用修改，在model_config中设置启动的模型
    "zhipu-api": {
        "port": 21001,
    },
    "minimax-api": {
        "port": 21002,
    },
    "xinghuo-api": {
        "port": 21003,
    },
    "qianfan-api": {
        "port": 21004,
    },
    "fangzhou-api": {
        "port": 21005,
    },
    "qwen-api": {
        "port": 21006,
    },
    "baichuan-api": {
        "port": 21007,
    },
    "azure-api": {
        "port": 21008,
    },
    "tiangong-api": {
        "port": 21009,
    },
    "gemini-api": {
        "port": 21010,
    },
}

FSCHAT_CONTROLLER = {
    "host": DEFAULT_BIND_HOST,
    "port": 20001,
    "dispatch_method": "shortest_queue",
}

**Comment by Mioooooo** [comment]
> Referen

感谢回复，我这个可能只是单纯的显存不足
