### ISSUE TITLE
在进行ES引擎问答时报错

### ISSUE THREAD

**Issue by iaoxuesheng** [chatchat-space/Langchain-Chatchat#3554]
+-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/data/rjs/Langchain-Chatchat-master/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    |     docs = await run_in_threadpool(search_docs,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/rjs/Langchain-Chatchat-master/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
    |     docs = kb.search_docs(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/rjs/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 182, in search_docs
    |     docs = self.do_search(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/rjs/Langchain-Chatchat-master/server/knowledge_base/kb_service/es_kb_service.py", line 154, in do_search
    |     docs = self.db_init.similarity_search_with_score(query=query,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 733, in similarity_search_with_score
    |     return self._search(query=query, k=k, filter=filter, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 815, in _search
    |     response = self.client.search(
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    |     return api(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/elasticsearch/_sync/client/__init__.py", line 3857, in search
    |     return self.perform_request(  # type: ignore[return-value]
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    |     raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
    | elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: the query vector has a different dimension [1024] than the index vectors [512]')
    +------------------------------------
2024-03-28 13:52:20,727 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)
2024-03-28 13:54:46,618 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:32768 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-28 13:54:46,619 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
2024-03-28 13:54:46,654 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:20001/list_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:32768 - "POST /llm_model/list_running_models HTTP/1.1" 200 OK
2024-03-28 13:54:46,656 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_running_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:32768 - "POST /llm_model/list_config_models HTTP/1.1" 200 OK
2024-03-28 13:54:46,677 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/llm_model/list_config_models "HTTP/1.1 200 OK"
INFO:     127.0.0.1:32768 - "GET /knowledge_base/list_knowledge_bases HTTP/1.1" 200 OK
2024-03-28 13:54:46,688 - _client.py[line:1027] - INFO: HTTP Request: GET http://127.0.0.1:7861/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK"
2024-03-28 13:54:46,866 - _transport.py[line:349] - INFO: PUT http://10.6.51.206:9200/es1 [status:400 duration:0.003s]
2024-03-28 13:54:46,866 - es_kb_service.py[line:53] - ERROR: 创建索引失败,重新
2024-03-28 13:54:46,866 - es_kb_service.py[line:54] - ERROR: BadRequestError(400, 'resource_already_exists_exception', 'index [es1/T7x-O2B6R1GpRXjrwikKxg] already exists')
2024-03-28 13:54:46,868 - _transport.py[line:349] - INFO: GET http://10.6.51.206:9200/ [status:200 duration:0.002s]
2024-03-28 13:54:46,871 - _transport.py[line:349] - INFO: HEAD http://10.6.51.206:9200/es1 [status:200 duration:0.002s]
INFO:     127.0.0.1:32768 - "POST /chat/knowledge_base_chat HTTP/1.1" 200 OK
2024-03-28 13:54:46,960 - _client.py[line:1027] - INFO: HTTP Request: POST http://127.0.0.1:7861/chat/knowledge_base_chat "HTTP/1.1 200 OK"
2024-03-28 13:54:46,964 - _transport.py[line:349] - INFO: PUT http://10.6.51.206:9200/es1 [status:400 duration:0.002s]
2024-03-28 13:54:46,964 - es_kb_service.py[line:53] - ERROR: 创建索引失败,重新
2024-03-28 13:54:46,964 - es_kb_service.py[line:54] - ERROR: BadRequestError(400, 'resource_already_exists_exception', 'index [es1/T7x-O2B6R1GpRXjrwikKxg] already exists')
2024-03-28 13:54:46,966 - _transport.py[line:349] - INFO: GET http://10.6.51.206:9200/ [status:200 duration:0.001s]
2024-03-28 13:54:46,968 - _transport.py[line:349] - INFO: HEAD http://10.6.51.206:9200/es1 [status:200 duration:0.002s]
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 49.09it/s]
2024-03-28 13:54:47,000 - _transport.py[line:349] - INFO: POST http://10.6.51.206:9200/es1/_search [status:400 duration:0.004s]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    await func()
  File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 568, in receive
    await self.message_event.wait()
  File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f2590fe0090

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 258, in wrap
    |     await func()
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/sse_starlette/sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "/data/rjs/Langchain-Chatchat-master/server/chat/knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    |     docs = await run_in_threadpool(search_docs,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/rjs/Langchain-Chatchat-master/server/knowledge_base/kb_doc_api.py", line 38, in search_docs
    |     docs = kb.search_docs(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/rjs/Langchain-Chatchat-master/server/knowledge_base/kb_service/base.py", line 182, in search_docs
    |     docs = self.do_search(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/data/rjs/Langchain-Chatchat-master/server/knowledge_base/kb_service/es_kb_service.py", line 154, in do_search
    |     docs = self.db_init.similarity_search_with_score(query=query,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 733, in similarity_search_with_score
    |     return self._search(query=query, k=k, filter=filter, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/langchain_community/vectorstores/elasticsearch.py", line 815, in _search
    |     response = self.client.search(
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    |     return api(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/elasticsearch/_sync/client/__init__.py", line 3857, in search
    |     return self.perform_request(  # type: ignore[return-value]
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/renjinshan/anaconda3/envs/rag_210/lib/python3.11/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    |     raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
    | elasticsearch.BadRequestError: BadRequestError(400, 'search_phase_execution_exception', 'failed to create query: the query vector has a different dimension [1024] than the index vectors [512]')
    +------------------------------------
2024-03-28 13:54:47,003 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by Yaoisss** [comment]
这个机器人也不专业，就一个问题你安装的elasticsearch是不是旧版本，8.8.2还是什么自己检查一下docs = self.db_init.similarity_search_with_score(query=query....)使用的是POST请求_search，这个参数需要GET请求。升级包就可以了
pip install elasticsearch==8.13.0
