### ISSUE TITLE
希望支持量化模型

### ISSUE THREAD

**Issue by ysyx2008** [chatchat-space/Langchain-Chatchat#3559]
**功能描述 / Feature Description**
希望支持Int4量化模型

**解决的问题 / Problem Solved**
消费级显卡可以使用能力更加强大的模型，推理速度也更快

**实现建议 / Implementation Suggestions**
支持GPTQ等

**Comment by zRzRzRzRzRzRzR** [comment]
0.3.x版本 可以自由搭配了。0.2.x版本基于fschat没做这个优化

**Comment by ysyx2008** [comment]
改为调用ollama运行量化模型后的API接口，实现了这个需求。多谢！

**Comment by Mioooooo** [comment]
@ysyx2008 请问怎么实现的，求指教

**Comment by ysyx2008** [comment]
> @ysyx2008 请问怎么实现的，求指教

ollama serve启动服务
chatchat中配置使用openai api，设置本机url，以及要使用的模型名称
大致就这样，很好用

**Comment by Mioooooo** [comment]
> > @ysyx2008 请问怎么实现的，求指教
> 
> ollama serve启动服务 chatchat中配置使用openai api，设置本机url，以及要使用的模型名称 大致就这样，很好用

    "openai-api": {
        "model_name": "gpt-4",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "",
        "openai_proxy": "",
    },，是这样吗？

**Comment by junfhu** [comment]
将
"openai-api": {
    "model_name": "gpt-4",
    "api_base_url": "https://api.openai.com/v1",
    "api_key": "",
    "openai_proxy": "",
}
改成
"openai-api": {
        "model_name": "llama3",
        "api_base_url": "http://127.0.0.1:11434/v1",
        "api_key": "ollama",
    },

然后重启就行

**Comment by ysyx2008** [comment]
> > > @ysyx2008 请问怎么实现的，求指教
> > 
> > 
> > ollama serve启动服务 chatchat中配置使用openai api，设置本机url，以及要使用的模型名称 大致就这样，很好用
> 
> ```
> "openai-api": {
>     "model_name": "gpt-4",
>     "api_base_url": "https://api.openai.com/v1",
>     "api_key": "",
>     "openai_proxy": "",
> },，是这个吗？
> ```

是的没错。楼上已经回复了

**Comment by Mioooooo** [comment]
> > > > @ysyx2008 请问怎么实现的，求指教
> > > 
> > > 
> > > ollama serve启动服务 chatchat中配置使用openai api，设置本机url，以及要使用的模型名称 大致就这样，很好用
> > 
> > 
> > ```
> > "openai-api": {
> >     "model_name": "gpt-4",
> >     "api_base_url": "https://api.openai.com/v1",
> >     "api_key": "",
> >     "openai_proxy": "",
> > },，是这个吗？
> > ```
> 
> 是的没错。楼上已经回复了

更新回复
