### ISSUE TITLE
请问现在支持部署经过lora微调后合并的模型吗

### ISSUE THREAD

**Issue by Longleaves** [chatchat-space/Langchain-Chatchat#3561]
直接在model_config.py加入了合并后的模型，但是推理的时候发现并没有微调的效果。现在支持部署经过lora微调后合并的模型吗？谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
建议查看wiki

**Comment by Zhangyiming0039** [comment]
请问你得出结果了吗支持lora微调的合并的大模型吗

**Comment by AaronFSJ** [comment]
> 请问你得出结果了吗支持lora微调的合并的大模型吗

我试了，可以。我用 LLaMA-Factory 微调了一个 ChatGLM3 的模型并合并，一开始直接导入有问题，后来将原模型的除了 bin 和 index.json 之外的覆盖到合并的模型中。然后 model_config.py 里的配置修改一下，就可以运行了。

<img width="621" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/23305845/ab1a9f56-31cf-41a7-a1ed-49de86df8687">


<img width="293" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/23305845/b9815898-47da-4fbf-b6e4-8bcc61cf0f7d">


<img width="595" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/23305845/2b12a9b9-399e-4bde-84df-7ee4b89f1fbe">

<img width="656" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/23305845/9381c95c-e559-4bdf-b856-4b78e7a6030b">
