### ISSUE TITLE
层级索引问题

### ISSUE THREAD

**Issue by loki-keroro** [chatchat-space/Langchain-Chatchat#3565]
目前项目支持层级索引吗，即对文档内容在标题层级从上至下索引，先索引一级标题再索引二级标题...
如果支持是怎么样个索引逻辑，如果不支持日后项目组是否有考虑上线该功能？

**Comment by glide-the** [comment]
层级索引问题我们目前没有开发计划，您可以关注3.0的问题收集，后续我们会参考这个issue
https://github.com/chatchat-space/Langchain-Chatchat/issues/2661
