### ISSUE TITLE
向量化速度很慢啊 10W txt文档要几天呢 怎么解决呢

### ISSUE THREAD

**Issue by myfeelyou** [chatchat-space/Langchain-Chatchat#3569]
有10W  txt文档 每个只有几K，，已经上传到  content目录下， 调用 /knowledge_base/recreate_vector_store 进行向量化，，，

分割的时候 3个每秒 ，batch的时候 2秒1个，按照找个速度10W数据处理完成 要50多个小时 这个正常吗，，服务器是 十多个线程  32Gcpu   16G gpu,   启动api的时候 显存显示占用了两个多GPU，用的是bge-large-zh-v1  ，faiss   。

**Comment by zRzRzRzRzRzRzR** [comment]
这个速度已经对额吧，你这10万个txt很大了，要处理一段时间

**Comment by AMAG-AB** [comment]
@dosubot 我有100G的文件，该怎么办呢？挺容易卡死的

**Comment by ftrako** [comment]
> @dosubot 我有100G的文件，该怎么办呢？挺容易卡死的

100G的文本文件做RAG？ 忒大了吧

**Comment by AMAG-AB** [comment]
@ftrako 业务需求，我也莫得办法

**Comment by Zifeng-Jiang** [comment]
> @dosubot 我有100G的文件，该怎么办呢？挺容易卡死的
请问后来怎么处理的100G的数据的RAG，我现在这边有350G数据，感觉根本处理不了

**Comment by Zifeng-Jiang** [comment]
> @dosubot 我有100G的文件，该怎么办呢？挺容易卡死的

请问后来怎么处理的100G的数据的RAG，我现在这边有350G数据，感觉根本处理不了
