### ISSUE TITLE
qwen72B-chat（int4）知识库问答报错

### ISSUE THREAD

**Issue by xiusidunhuren** [chatchat-space/Langchain-Chatchat#3572]
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/86663794/433a3595-320a-4575-8460-186cbc0b084c)

**Comment by xiusidunhuren** [comment]
只有知识库会报错，而且也回答不出来任何问题，llm对话则不会

**Comment by zRzRzRzRzRzRzR** [comment]
你初始化了吗

**Comment by xiusidunhuren** [comment]
初始化了，我是用两张4090一起跑的

**Comment by xiusidunhuren** [comment]
没有 我换别的框架了
