### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by HuaidongLi** [chatchat-space/Langchain-Chatchat#3577]
error whlie attempting to bind on address ('127.0.0.1',20001):address already in use 
how to deal with this problem?
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/85067013/b6e15363-63da-49f6-8cd5-9249d6a27074)
<img width="1076" alt="1" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/85067013/725df7e4-ab62-4d7b-a2f9-5741419b769b">
<img width="890" alt="2" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/85067013/cbcc69d0-270d-429f-9ef6-628dba6229a8">

**Comment by zRzRzRzRzRzRzR** [comment]
- [ ]
