### ISSUE TITLE
[BUG] 查询知识库时，当搜索一些关键词，经常有出息查询不到的情况，有办法添加关键词搜索比如BM25么

### ISSUE THREAD

**Issue by gz-simon** [chatchat-space/Langchain-Chatchat#3578]
**问题描述 / Problem Description**
查询知识库时，当搜索一些关键词，经常有出息查询不到的情况，有办法添加关键词搜索比如BM25么，我看有介绍说，可以使用BM25和向量搜索，按照权重来混合查询，这样精度会更高一些，但具体代码怎么改，我不清楚

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by lzh1998-jansen** [comment]
使用混合搜索的情况下，VECTOR_SEARCH_TOP_K 应该如何修改，

**Comment by yo-WASSUP** [comment]
您好，请问您改完了吗

**Comment by Sololololo** [comment]
> 使用混合搜索的情况下，VECTOR_SEARCH_TOP_K 应该如何修改，

混合检索就是混合了向量库检索和其它检索的一种策略，你可以理解成n中方法检索后通过权重取个新top_k，你得自己去实现。VECTOR_SEARCH_TOP_K是向量库检索自己的参数，不是一个概念

**Comment by Fanxhion** [comment]
请问有详细实现混合检索吗？help!

**Comment by toulzx** [comment]
> 请问有详细实现混合检索吗？help!

https://github.com/chatchat-space/Langchain-Chatchat/blob/f9e38951142eb272616db70e89cad02bfd063b13/libs/chatchat-server/chatchat/server/file_rag/retrievers/ensemble.py#L42-L45

已经实现混合检索了吧
