### ISSUE TITLE
如何保存向量数据库中的索引、向量、以及对应的文本块索引、文本块

### ISSUE THREAD

**Issue by Shame-fight** [chatchat-space/Langchain-Chatchat#3580]
**功能描述 / Feature Description**
如何保存向量数据库中的索引、向量、以及对应的文本块索引、文本块
embedding模型：m3e-base
向量数据库：faiss
代码块版本：0.2.10

**解决的问题 / Problem Solved**
我需要将向量及对应的文本块做可视化，但了解到.faiss：向量存储的faiss索引，如何获取知识库中向量以及对应的文本块用作可视化展示呢

**实现建议 / Implementation Suggestions**
应该如何修改代码，faiss是否支持

**Comment by WeiminLee** [comment]
Thanks , Good job
