### ISSUE TITLE
[FEATURE] 开启对话时，能否由AI先发起对话；输入问题后，能否在输入框前面举出更加符合的问题方式

### ISSUE THREAD

**Issue by gz-simon** [chatchat-space/Langchain-Chatchat#3581]
**功能描述 / Feature Description**
开启对话时，能否由AI先发起对话；输入问题后，能否在输入框前面举出更加符合的问题方式

**实现建议 / Implementation Suggestions**
<img width="485" alt="1" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/132644727/23be28a7-0008-45f2-b1cd-5057dff4b5f7">
<img width="470" alt="2" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/132644727/c82169b2-9807-4d6a-bfe8-628da909a6f6">
<img width="470" alt="2" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/132644727/9857b24c-6a28-4916-92c2-64cccaf9d3d2">

**Comment by zRzRzRzRzRzRzR** [comment]
没有做这个功能
