### ISSUE TITLE
如何与本地的mysql数据库进行连接并查询

### ISSUE THREAD

**Issue by XbbXbbX** [chatchat-space/Langchain-Chatchat#3587]
1、我观察到项目中有sql相关包，那么要如何配置可以连接上本地的mysql数据库？
2、连接后，是否可以根据现有的模块编写一个自然语言查询sql的tool并通过agent使用它？

**Comment by ln410** [comment]
我已经按你说的SQLALCHEMY_DATABASE_URI = "mysql+pymysql://<username>:<password>@<host>/<dbname>"，改成自己的了，然后我启动python startup -a服务，在知识库问答功能中并没有任何关于mysql数据库的使用啊
