### ISSUE TITLE
知识库问答与搜索引擎回答相结合

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3588]
我尝试将知识库问答功能，与搜索引擎回答相结合，目标是：
1. Langchain-Chatchat首先试图用知识库中的知识回答问题。
2. 如果知识库中搜索不到结果，转为用搜索引擎回答（我已配置好Bing Subscription key)

想问问各位大佬，应该如何实现这个功能?

**Comment by zixiaotan21** [comment]
process_search_engine_response(search_engine_response)  process_kb_response(kb_response) kb_response_is_insufficient(kb_response) 这三个函数 如何定义 放在哪里

**Comment by nauyiahc** [comment]
请问这个问题解决了么？我也有这个困扰

**Comment by zixiaotan21** [comment]
我尝试了一下，可以另外写一个脚本，用if-else语句，处理知识库问答的api和搜索引擎的api，这样可以实现知识库问答与搜索引擎回答相结合。

但机器人说的在dialogue.py修改代码的方法 我没有试过。
