### ISSUE TITLE
是否有大语言模型的启停功能

### ISSUE THREAD

**Issue by A-runaaaa** [chatchat-space/Langchain-Chatchat#3593]
是否可以添加功能：检测没有人使用时不部署语言模型，避免内存资源的浪费，当检测到有人使用时，添加使用者选用的大语言模型

**Comment by A-runaaaa** [comment]
换种说法就是 startup.py 部署时 不部署大语言模型，用户 通过streamlit界面进来之后可以自行选择模型，然后用户不再使用后再退出当前模型，这个可以实现么，或者提供一些代码支持 @dosu-bot

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有这个功能
