### ISSUE TITLE
提问知识库将回答数据列表生成【柱图表】，结果给出了列表数据，确提示图片无法显示

### ISSUE THREAD

**Issue by tanliang3377** [chatchat-space/Langchain-Chatchat#3594]
**功能描述 /提问知识库**
将回答数据列表生成【柱图表】 结果给出了列表数据，确提示图片无法显示如下图：
![90d4a6b425e36e35c474a3033034ecc](https://github.com/chatchat-space/Langchain-Chatchat/assets/163307366/a60f7030-cd55-468d-a310-f516b8649729)

问题：不知道是否真的生成了柱图表，如果生成了，那么图片存在哪里，又如何显示？

**Comment by imClumsyPanda** [comment]
建议检查下返回图片的路径是否是streamlit显示图片时支持的形式
