### ISSUE TITLE
webui界面输入内容后出现报错：RemoteProtocolError: Caught exception: peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by HhhBbWw** [chatchat-space/Langchain-Chatchat#3598]
**问题描述 / Problem Description**
问题如题目所示，下面是docker日志的截图
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/162102157/19bd6de1-7b14-4c92-ada6-3edb72e8d475)
webui页面卡住：
![图片](https://github.com/chatchat-space/Langchain-Chatchat/assets/162102157/6f8a81ec-769a-456f-b3b8-66b1eb1bd518)

**环境信息 / Environment Information**
- langchain版本：v0.2.7
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zhin2929** [comment]
我也是同样的问题，不知道怎么解决

**Comment by Surge-Dan** [comment]
> 我也是同样的问题，不知道怎么解决

请问解决了吗？

**Comment by ASan1527** [comment]
> > 我也是同样的问题，不知道怎么解决
> 
> 请问解决了吗？

哥，你解决了吗
