### ISSUE TITLE
Agent 不会调用工具

### ISSUE THREAD

**Issue by xiaohundun** [chatchat-space/Langchain-Chatchat#3601]
**问题描述 / Problem Description**
 Agent chat 的时候知道该用什么工具，但是并不会调用工具
调用记录：
<img width="667" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/38812912/abb35e93-8163-4011-a104-fd5bb2ba194f">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：2.10
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：pg_vector

我看有人提出这样的 issue，但是没有解决方法，有人有经验么

**Comment by RHY-bit** [comment]
同样的问题，不清楚还有没有在维护这个。

**Comment by BANGzys** [comment]
同问，急！！！

**Comment by ATP-BME** [comment]
cy

**Comment by zRzRzRzRzRzRzR** [comment]
0.3.x会重新做，这个agent太老了，我是在写这个部分的

**Comment by xqxls** [comment]
> 0.3.x会重新做，这个agent太老了，我是在写这个部分的

大概什么时候会出0.3.x
