### ISSUE TITLE
pip安装依赖文件

### ISSUE THREAD

**Issue by Illusionist0** [chatchat-space/Langchain-Chatchat#3605]
<img width="601" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45280235/2c0e6d48-d3e5-4fd3-95f6-32a2b3ce9e77">
![error0](https://github.com/chatchat-space/Langchain-Chatchat/assets/45280235/8f58ea4d-d211-44fe-b1d6-e7962bad5539)
具体问题如图所示

**Comment by Illusionist0** [comment]
> Hey there @Illusionist0! 🎩 I'm [Dosu](https://dosu.dev), a friendly bot here to help you squash bugs, answer your queries, and guide you on your journey to becoming a contributor, all while we wait for a human maintainer to arrive. I'm diving into your issue and will get back to you with a full answer shortly. Hang tight! 🤖🔍

thank u sir

**Comment by xingener** [comment]
@Illusionist0 请问，怎么解决的？

**Comment by xingener** [comment]
This solved my problem: https://github.com/facebookresearch/xformers/issues/740#issuecomment-1780727152
