### ISSUE TITLE
更换Faiss使用距离度量方式为余弦相似度

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3610]
**问题描述 / Problem Description**
尝试更换Faiss使用距离度量方式为余弦相似度, 但是报错

**复现问题的步骤 / Steps to Reproduce**
1. 在"Langchain-Chatchat\server\knowledge_base\kb_cache\faiss_cache.py"中：
61行： vector_store = FAISS.from_documents([doc], embeddings, normalize_L2=True, distance_strategy="MAX_INNER_PRODUCT" ) distance_strategy 修改为最大内积。
97行同理。

2. 问题出现 / Problem occurs
C:\Users\butterfly\anaconda3\envs\chatchat_env\Lib\site-packages\langchain_community\vectorstores\faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: MAX_INNER_PRODUCT
  warnings.warn(

**预期的结果 / Expected Result**
无bug

**实际结果 / Actual Result**
C:\Users\butterfly\anaconda3\envs\chatchat_env\Lib\site-packages\langchain_community\vectorstores\faiss.py:121: UserWarning: Normalizing L2 is not applicable for metric type: MAX_INNER_PRODUCT
  warnings.warn(

**环境信息 / Environment Information**

- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-api
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ：Windows-10-10.0.22631-SP0.
- Python 版本 / Python version: ：3.11.8
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
@zRzRzRzRzRzRzR 维护者你好,请问langchain-chatchat 目前是不支持使用"MAX_INNER_PRODUCT"，内积 余弦相似度 进行向量检索吗？

**Comment by zixiaotan21** [comment]
"METRIC_INNER_PRODUCT" 并不是 FAISS.from_documents 有效的distance_strategy 参数

**Comment by Ptianyu** [comment]
知识库问答使用的是内积还是欧氏距离呢？
