### ISSUE TITLE
离线部署成功后，webui页面正常启动，docs文档不能加载出来

### ISSUE THREAD

**Issue by guoxiaoyue111111** [chatchat-space/Langchain-Chatchat#3611]
您好，离线部署了langchain-0.2.10版本，服务启动正常，如下：
![4eb4fe92c078e350ef8f01d8cdd7339](https://github.com/chatchat-space/Langchain-Chatchat/assets/45383666/e3da5b52-edfb-4933-95fb-387fba0a46f3)

但是访问http://10.247.22.3:8080/docs，页面显示如下：
![18aee41e31e5c511275cf25cea4e672](https://github.com/chatchat-space/Langchain-Chatchat/assets/45383666/9cdcdd54-8885-4544-b9d9-93d861e16ded)

前端界面为：
![bd9fa1d00898f2a8f18da51f5e7460f](https://github.com/chatchat-space/Langchain-Chatchat/assets/45383666/ba0a668c-c710-4ced-ba0e-21072fb1dc76)

请问，这种情况的原因是什么？

**Comment by LGY-111** [comment]
一样的问题，楼主解决了吗，可以分享下吗

**Comment by umbraclet16** [comment]
我的chrome版本比较老，浏览器console报错TypeError: Object.hasOwn is not a function。这个函数是es2022的新特性，93以前的版本不兼容。在swagger-ui-bundle.js中增加一行解决了：

```
if (!Object.hasOwn){Object.hasOwn = (obj, prop) => Object.prototype.hasOwnProperty.call(obj, prop);}
```

ref: https://github.com/remarkjs/react-markdown/issues/772
