### ISSUE TITLE
知识库Embedding模型问题

### ISSUE THREAD

**Issue by 4ART1ST** [chatchat-space/Langchain-Chatchat#3614]
在做不同Embedding模型对比的工作，已成功完成m3e-base, bge-base, text2vec-paragraph和piccolo-base，本来打算增加ernie-base但发现它基本都无法回答，匹配不到正确文档，不知道为啥效果这么差
![Uploading image.png…]()
发现Langchain不支持gte和stella，现在只能考虑达摩院那个了，nlp_gte只能部署large吗，有没有人试过base，因为是横向对比所以感觉base更公平一些

**Comment by guijuzhejiang** [comment]
@4ART1ST 老兄对比有结果吗？我用bge-large-zh-v1.5感觉效果不太好啊。用民法典做向量库，搜第三十六条是什么都不对。看了下匹配结果：出来第一百三十一条。。。。。，第三百六十七条。。。。。。就是没有第三十六条。。。。。应该是ebedding 模型的特征表达不够好啊，还有更好的embedding模型吗？不想用openai的，想用本地化开源的

**Comment by liaohaoxiang** [comment]
m3e-base更好，但是得用LLM模型以中文训练为主的，我对比了qwen-max和GPT-4-preview，感觉qwen的更好
