### ISSUE TITLE
Chat Chat API server 的对话历史可以删去或者修改为特定内容吗

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3621]
**问题描述 / Problem Description**
Chat Chat API server 的对话历史可以删去或者修改为特定内容吗

**复现问题的步骤 / Steps to Reproduce**
1. 点击 Chatchat  API  Server: http://127.0.0.1:7861
2. 在request body 中：
{
  "query": "RCEP证书可以自助打印吗",
  "knowledge_base_name": "text_3",
  "top_k": 3,
  "score_threshold": 1,
  "history": [
    {
      "role": "user",
      "content": "我们来玩成语接龙，我先来，生龙活虎"
    },
    {
      "role": "assistant",
      "content": "虎头虎脑"
    }
  ],
  "stream": false,
  "model_name": "qwen-api",
  "temperature": 0.7,
  "max_tokens": 0,
  "prompt_name": "default"
}
3. 这里的history部分 可以删去 或者自定义修改吗

**Comment by Lu0Key** [comment]
你可以设为一个空数组，或者自己去修改内容，只是要符合格式{”role“:xxx,"content":xxx}

**Comment by zixiaotan21** [comment]
> 你可以设为一个空数组，或者自己去修改内容，只是要符合格式{”role“:xxx,"content":xxx}

嗯嗯，我明白了，谢谢！
