### ISSUE TITLE
如何调试启动服务器端？我调试启动startup.py，但是不会命中server端代码的断点

### ISSUE THREAD

**Issue by zpp99love** [chatchat-space/Langchain-Chatchat#3636]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zpp99love** [comment]
我想以调试模式启动整个项目，在任何代码打断点都能命中，如何做？

**Comment by zpp99love** [comment]
怎么能通过swagger文档命中api.py中接口断点？

**Comment by haishangbuyexing** [comment]
1. 目前看使用Process 创建的多进程， pycharm 断点不能触发， 使用subprocess 可以
2. 通过尝试，controller, model_worker, server 都是独立的， startup.py -a 只是帮助同时把进程都拉起来， 可通过 -llm-api 等只启动目标进程，即pycharm 多配置几个启动configure,  传递不同的启动参数， 独立启动进程， 就可以加断点了
