### ISSUE TITLE
【功能请求】对话框头像修改！！！

### ISSUE THREAD

**Issue by li-yanliang** [chatchat-space/Langchain-Chatchat#3637]
想更换一下这个人头的图片没有找到！应该如何修改。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31643880/26e42f43-ce6f-4eb3-a2b6-59fcece87e9d)

**Comment by zRzRzRzRzRzRzR** [comment]
streamlit固定组件，不能改吧

**Comment by FYLLYF** [comment]
求问求问

**Comment by FYLLYF** [comment]
请问楼主解决了更改用户头像的问题吗？
