### ISSUE TITLE
比有道QAnything部署简单，不知道准确率相比如何？

### ISSUE THREAD

**Issue by ILG2021** [chatchat-space/Langchain-Chatchat#3639]

**Comment by fivegg** [comment]
我也在对比qanything。感觉qanything介绍要厉害一些，部署有点困难，刚用纯python部署成功。

**Comment by positive666** [comment]
> 我也在对比qanything。感觉qanything介绍要厉害一些，部署有点困难，刚用纯python部署成功。

你看下代码基本和chat 几乎一样，OCR本质上都是用的PADDLE的，只是网易加了URL的解析文件，EMBED RERANK LLM都是可以切换的，模型端无所谓了

**Comment by e68862230** [comment]
逻辑上，好像qanything的知识库问答是支持上下文关联的，问小明是谁，他在哪里工作，工作具体包含什么这样的三句话它是能互相关联的，chatchat好像不行。。。

**Comment by positive666** [comment]
em..我从架构层面没看出什么问题，那个和历史消息有关或者有什么BUG 没解决





CR
***@***.***







                       
原始邮件
                       
                     

发件人："e68862230"< ***@***.*** &gt;;

发件时间：2024/5/10 16:06

收件人："chatchat-space/Langchain-Chatchat"< ***@***.*** &gt;;

抄送人："Cheng Rui"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

主题：Re: [chatchat-space/Langchain-Chatchat] 比有道QAnything部署简单，不知道准确率相比如何？ (Issue #3639)




 
逻辑上，好像qanything的知识库问答是支持上下文关联的，问小明是谁，他在哪里工作，工作具体包含什么这样的三句话它是能互相关联的，chatchat好像不行。。。
