### ISSUE TITLE
[BUG] pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

### ISSUE THREAD

**Issue by gedehua** [chatchat-space/Langchain-Chatchat#364]
我的python是3.8.5的
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/84606552/0ee33d33-a997-4a66-b963-9ad8d318ab10)

**Comment by imClumsyPanda** [comment]
那可能是清华源里这个版本没有，可以看看百度官方关于paddlepaddle的安装指令说明

**Comment by gedehua** [comment]
> 那可能是清华源里这个版本没有，可以看看百度官方关于paddlepaddle的安装指令说明

那应该怎么下载呢

**Comment by lemon-simple** [comment]
pip install -r requirements.txt
Collecting pymupdf (from -r requirements.txt (line 1))
  Using cached PyMuPDF-1.22.3-cp311-cp311-macosx_11_0_arm64.whl (12.7 MB)
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.4.2 (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.4.2

**Comment by lemon-simple** [comment]
一样的问题

**Comment by zluckymn** [comment]
改成阿里云
pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

**Comment by zluckymn** [comment]
> 我的python是3.8.5的 ![image](https://user-images.githubusercontent.com/84606552/238265888-0ee33d33-a997-4a66-b963-9ad8d318ab10.png)
阿里云的可以用
pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

**Comment by Nicole19960319** [comment]
你直接去复制无法连接的那个网址（https),然后去下载paddlepaddle.. .whl,文件，再用pip install paddlepaddle.. .whl就可以了。如果不行就用pip3 install paddlepaddle.. .whl

**Comment by zhuiyi6** [comment]
> 

具体该怎么操作的呀
