### ISSUE TITLE
在使用ChatGLM3-6b模型中报错 ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers_modules.THUDM.chatglm3-6b.103caa40027ebfd8450289ca2f278eac4ff26405.configuration_chatglm.ChatGLMConfig'> and you passed <class 'transformers_modules.THUDM.chatglm3-6b.a5ba5501eb873d40d48bd0983bd2a8dd006bb838.configuration_chatglm.ChatGLMConfig'>. Fix one of those so they match!

### ISSUE THREAD

**Issue by lukeewin** [chatchat-space/Langchain-Chatchat#3641]
**问题描述 / Problem Description**
在使用ChatGLM3-6b模型中报错 ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers_modules.THUDM.chatglm3-6b.103caa40027ebfd8450289ca2f278eac4ff26405.configuration_chatglm.ChatGLMConfig'> and you passed <class 'transformers_modules.THUDM.chatglm3-6b.a5ba5501eb873d40d48bd0983bd2a8dd006bb838.configuration_chatglm.ChatGLMConfig'>. Fix one of those so they match!

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456) chatglm3-6b
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: ubuntu 22.04
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**Comment by zRzRzRzRzRzRzR** [comment]
去hf官方下模型
