### ISSUE TITLE
知识库问答如何与搜索引擎duckduckgo回答相结合

### ISSUE THREAD

**Issue by hw1481826110** [chatchat-space/Langchain-Chatchat#3642]
相对接bing但是有没有VISA卡，相对接duckduckgo又不会用。（网络环境已配置好）

**Comment by zixiaotan21** [comment]
和楼主有同样的想法，对接duckduckgo确实比较麻烦，后来换了bing作为搜索引擎，现在可以做到知识库问答+搜索引擎回答了~

**Comment by zRzRzRzRzRzRzR** [comment]
其实这俩本身后期嗲代码一样，只要吧联网搜索中搜索的部分放到知识库就行了
