### ISSUE TITLE
如何实现chatchat的调用？

### ISSUE THREAD

**Issue by litongyun233** [chatchat-space/Langchain-Chatchat#3649]
chatchat已经部署好了，如何实现我调chatchat的知识库，通过几行代码传入“问题”，chatchat直接返回检索的答案？请问如何实现这一过程，现在只有web界面，我想把chatchat返回的内容作为我另一个需求的输入。@dosu-bot

**Comment by zRzRzRzRzRzRzR** [comment]
我们有API，你看7860端口的界面
