### ISSUE TITLE
[BUG]显存使用率不平均（显存使用率40%和60%），推理过程中GPU负载也不平均（分别为35%和59%）

### ISSUE THREAD

**Issue by lhtpluto** [chatchat-space/Langchain-Chatchat#3652]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
[BUG]显存使用率不平均（显存使用率40%和60%），推理过程中GPU负载也不平均（分别为35%和59%）

尝试通过device map映射方式，通过设置device_map参数（例如"auto", "balanced", "balanced_low_0", "sequential"）改善，但找不到更改的位置

两张4090
 ubuntu2204
 Driver Version: 550.54.14      CUDA Version: 12.4 
transformers                  4.39.3
torch                         2.1.2
torchaudio                    2.1.2
torchvision                   0.16.2
autoawq                       0.2.3+cu121  /home/test/Langchain-Chatchat/AutoAWQ
autoawq-kernels               0.0.6+cu121  /home/test/Langchain-Chatchat/AutoAWQ_kernels-main
 

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：操作系统：Linux-6.5.0-26-generic-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen1.5-32B-Chat-AWQ'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'Qwen/Qwen1.5-32B-Chat-AWQ',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bce-embedding-base_v1 @ cuda

- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen1.5-32B-Chat-AWQ
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bce-embedding-base_v1 @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:  ubuntu2204
- Python 版本 / Python version:   3.11.7
- 其他相关环境信息 / Other relevant environment information:

![屏幕截图 2024-04-07 161843](https://github.com/chatchat-space/Langchain-Chatchat/assets/132045861/548f1751-c79c-4e5e-89c0-7a3127d52eff)
![屏幕截图 2024-04-07 162216](https://github.com/chatchat-space/Langchain-Chatchat/assets/132045861/61d308ed-9906-463d-b953-1bc97ae129e0)

**Comment by ilovesouthpark** [comment]
在fschat的model_adapter.py的def load_model这里进行修改。你再试试，我改好的文件被我升级fschat覆盖了，我好像没做备份，只能再去调试了哈哈。
