### ISSUE TITLE
处理markdown形式的txt文档

### ISSUE THREAD

**Issue by litongyun233** [chatchat-space/Langchain-Chatchat#3665]
预处理文档，把PDF转换为markdown形式的txt文档，发现分割效果不是很好，想优化一下，请给我返回针对txt文本（UnstructuredFileLoader）的读取方式和chunk的切分方式的代码路径。@dosu-bot

**Comment by zRzRzRzRzRzRzR** [comment]
你可以用markdowm的分词方式分词txt没问题的
