### ISSUE TITLE
[FEATURE] 申请支持新BCE embedding / Update of BCE embedding suport

### ISSUE THREAD

**Issue by RudRho** [chatchat-space/Langchain-Chatchat#3667]
**功能描述 / Feature Description**
申请支持最新的BCE embedding
https://huggingface.co/maidalun1020/bce-embedding-base_v1

根据官方测评，此embedding效果明显优于 BGE，有望提升使用效果。希望研发团队支持。

如果因为开发人员不够的话，能否告知如何适配此 embedding，我可以负责PR

**Comment by ilovesouthpark** [comment]
没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。

**Comment by Zephyr69** [comment]
这东西怎么才能离线调用？repo已经下载到cache里了，也设置了access token到环境变量，但一直提示无法连接Gated Repo。是因为使用了镜像站吗？但是关闭镜像站的话就完全无法连接了。

**Comment by zRzRzRzRzRzRzR** [comment]
bce是支持的

**Comment by sevenandseven** [comment]
> 没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。


你好，你的意思是bge-m3可以直接加载到langchain-chatchat中对吗？为什么我把embedding模型替换为bge_m3之后，什么都匹配不出来了？

**Comment by ilovesouthpark** [comment]
> > 没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。
> 
> 你好，你的意思是bge-m3可以直接加载到langchain-chatchat中对吗？为什么我把embedding模型替换为bge_m3之后，什么都匹配不出来了？

有具体的例子吗，截图什么的

**Comment by sevenandseven** [comment]
> > > 没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。
> > 
> > 
> > 你好，你的意思是bge-m3可以直接加载到langchain-chatchat中对吗？为什么我把embedding模型替换为bge_m3之后，什么都匹配不出来了？
> 
> 有具体的例子吗，截图什么的

就是我不管输入啥，问他都匹配不出来，找不到内容。

**Comment by ilovesouthpark** [comment]
> > > > 没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。
> > > 
> > > 
> > > 你好，你的意思是bge-m3可以直接加载到langchain-chatchat中对吗？为什么我把embedding模型替换为bge_m3之后，什么都匹配不出来了？
> > 
> > 
> > 有具体的例子吗，截图什么的
> 
> 就是我不管输入啥，问他都匹配不出来，找不到内容。

知识库确认正常吗？有时换了embeddinig模型会出错。再建一个试试。

**Comment by hahayueqing** [comment]
> > > > 没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。
> > > 
> > > 
> > > 你好，你的意思是bge-m3可以直接加载到langchain-chatchat中对吗？为什么我把embedding模型替换为bge_m3之后，什么都匹配不出来了？
> > 
> > 
> > 有具体的例子吗，截图什么的
> 
> 就是我不管输入啥，问他都匹配不出来，找不到内容。

请问   问题解决了吗

**Comment by hahayueqing** [comment]
> > 没有其它地方的调用，你只需要修改model_config.py文件即可，把这个embedding模型加进去就好。我手上刚好有个文件向量化测试bge large v1.5会失败，m3是成功的（但是和chatchat好像有点兼容性问题，只要不是一开始运行就进行向量化，后期都会显示内存不足），我拿它用bce也是成功的，没有进一步比较了，至少bce这个好像兼容性好一点目前没有碰到啥问题。
> 
> 你好，你的意思是bge-m3可以直接加载到langchain-chatchat中对吗？为什么我把embedding模型替换为bge_m3之后，什么都匹配不出来了？

请问，换成bge_m3后的问题，解决了吗
