### ISSUE TITLE
pip install gradio  报错

### ISSUE THREAD

**Issue by gedehua** [chatchat-space/Langchain-Chatchat#367]
大佬帮我一下
![006f9249c0b231869f9300dfd21a01e](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/84606552/9f014a30-fe42-476c-a4c6-d1b4b318da2f)

**Comment by yfangyan1989** [comment]
我也遇到了，换一个python版本，我用3.9不行，换了3.8就好了
