### ISSUE TITLE
针对知识库文档的合适分词器

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3680]
**功能描述 / Feature Description**
希望有针对知识库文档，合适的Text Splitter

**解决的问题 / Problem Solved**
1.原来使用的分词器ChineseRecursiveTextSplitter
对输入的知识库文档进行切分时，但会出现“问题1+答案1，问题2+答案2”出现在同一分块的情况，在回答的时候，提问问题1，回答会出现问题2的答案；

2.改用MarkdownHeaderTextSplitter作为分词器
可以将“问题1+答案1“ ”问题2+答案2”划分在不同的分块(chunk),但需要预处理知识库文档为markdown格式，回答的时候，提问问题1，回答答案1，不会出现问题2的答案；

**实现建议 / Implementation Suggestions**
改用MarkdownHeaderTextSplitter作为分词器，需要预处理知识库文档为markdown格式，比较麻烦。

**替代方案 / Alternative Solutions**
1.希望有更加合适的分词器，可以自动分割知识库文本，为将“问题1+答案1“ ”问题2+答案2”划分在不同的分块(chunk)。
2.或者有合适的LLM，专门处理文本分块的问题吗，例如Agentic Splitting.

**Comment by zRzRzRzRzRzRzR** [comment]
目前确实是有这个缺陷，在0.3.x考虑改进
