### ISSUE TITLE
数据库错误

### ISSUE THREAD

**Issue by sevenandseven** [chatchat-space/Langchain-Chatchat#3681]
其他文件推理正常，但是到某个pdf文件时，它可以正常创建向量库，但是无法进行推理。请问这个怎么解决。

![Image_20240409133223](https://github.com/chatchat-space/Langchain-Chatchat/assets/63324925/3549377c-31e9-4303-9187-343bab891e1d)

**Comment by zRzRzRzRzRzRzR** [comment]
感觉是paddle ocr的问题
