### ISSUE TITLE
[BUG] 知识库有多篇文档，他回答的时候只回复第一篇文档的内容，具体模型如下

### ISSUE THREAD

**Issue by huai-ying** [chatchat-space/Langchain-Chatchat#3684]
现在的情况是，我在知识库有多篇文档，他回答的时候只回复第一篇文档的内容，具体模型如下

使用的是百川大模型，用的faiss

可能会是哪方面出问题，大伙们

**Comment by zRzRzRzRzRzRzR** [comment]
搜到什么就回答什么，你把K调高，就会返回更多相似文档，你看看有没有其他文档呢
