### ISSUE TITLE
如何将工具调用之后结果作为Final Answer输出

### ISSUE THREAD

**Issue by zgz757183190** [chatchat-space/Langchain-Chatchat#3685]
工具名称: weather_check

工具状态: 调用成功

工具输入: 北京

工具输出: {'temperature': '13', 'description': '阴'}

大佬，请教一下，如何将Observation输出的数据作为Final Answer最终输出的结果呢？

**Comment by zgz757183190** [comment]
> 你好，@zgz757183190! 我是[Dosu](https://dosu.dev)，一个特别设计来帮助解决问题、回答问题并协助成为贡献者的机器人。虽然我是机器人，但我在等待人类维护者的同时，我在这里为你提供帮助。我会立刻查看你的问题，并很快给你一个完整的答案。🤖

请问我这个问题如何解决呢，帮忙提供一个案例，多谢！

**Comment by zgz757183190** [comment]
> Based on your request, you want to use the output data from the `weather_check` tool as the final answer in your application. Here's how you can do it:
> 
> 1. Import the `weathercheck` function from the `weather_check.py` module.
> 2. Call the `weathercheck` function with the location string (e.g., "北京") as its argument.
> 3. Use the returned dictionary directly in your application as needed.
> 
> Here's an example code snippet demonstrating these steps:
> 
> ```python
> from server.agent.tools.weather_check import weathercheck
> 
> # Call the weathercheck function with the desired location
> weather_data = weathercheck("北京")
> 
> # Use the weather_data in your application
> print(f"Temperature: {weather_data['temperature']}°C, Description: {weather_data['description']}")
> ```
> 
> This code imports the `weathercheck` function, calls it with "北京" as the input, and then prints the temperature and weather description. You can replace the print statement with any other logic in your application that requires the weather data.
> 
> The `weather_check` tool is included in the Langchain-Chatchat codebase and is defined in the `server/agent/tools_select.py` file with the name `"weather_check"`. It is intended to be used for weather checking purposes, as indicated by its inclusion in the `tools` list with a corresponding `args_schema=WeatherInput`.
> 
> You can find more details in the following sources:
> 
> * [server/agent/tools/weather_check.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/weather_check.py)
> * [server/agent/tools_select.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools_select.py)
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> -[Dosu](https://dosu.dev)
> 
> ## Sources
> * [server/agent/tools/weather_check.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools/weather_check.py)
> * [server/agent/tools_select.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/agent/tools_select.py)
> 
> #### About Dosu

我想要的结果是，Final Answer的结果为Observation的源数据

**Comment by zgz757183190** [comment]
> Final Answer 已经是Agent结束了，为什么还能做Observation呢

是这样子的大佬，我想通过工具调用之后，直接将工具返回的结果直接返回，不要通过大模型进行总结

**Comment by zgz757183190** [comment]
> Final Answer 已经是Agent结束了，为什么还能做Observation呢

相当于，通过调用API工具后，直接将API返回的结果作为Final Answer，模型无需总结和加工处理。

工具返回什么结果，Final Answer最终显示什么内容就行。

**Comment by linjt325** [comment]
```
@classmethod
    def from_function(
        cls,
        func: Optional[Callable] = None,
        coroutine: Optional[Callable[..., Awaitable[Any]]] = None,
        name: Optional[str] = None,
        description: Optional[str] = None,
        return_direct: bool = False,
        args_schema: Optional[Type[BaseModel]] = None,
        infer_schema: bool = True,
        **kwargs: Any,
    ) -> StructuredTool:
        """Create tool from a given function.

        A classmethod that helps to create a tool from a function.

        Args:
            func: The function from which to create a tool
            coroutine: The async function from which to create a tool
            name: The name of the tool. Defaults to the function name
            description: The description of the tool. Defaults to the function docstring
            return_direct: Whether to return the result directly or as a callback
            args_schema: The schema of the tool's input arguments
            infer_schema: Whether to infer the schema from the function's signature
            **kwargs: Additional arguments to pass to the tool

        Returns:
            The tool
```
试试return_direct=True

**Comment by AKA-WDNMD** [comment]
在工程文件的server/chat/agent_chat.py里找到 final_answer 的参数，再把你想要的东西拼接起来就好了
