### ISSUE TITLE
如何添加新的对话模式

### ISSUE THREAD

**Issue by WSC741606** [chatchat-space/Langchain-Chatchat#3695]
希望对知识库问答进行修改并作为一种新的对话模式并加入到Web UI中，我应该在源码的哪里修改？ @dosu-bot

**Comment by WSC741606** [comment]
@dosu-bot，在`webui_pages/dialogue/dialogue.py`的`dialogue_page`函数里面有`api.knowledge_base_chat(prompt,
                                                 knowledge_base_name=selected_kb,
                                                 top_k=kb_top_k,
                                                 score_threshold=score_threshold,
                                                 history=history,
                                                 model=llm_model,
                                                 prompt_name=prompt_template_name,
                                                 temperature=temperature)`这个`api.knowledge_base_chat`是在哪个文件呢？

**Comment by 1920853199** [comment]
> @dosu-bot，在`webui_pages/dialogue/dialogue.py`的`dialogue_page`函数里面有`api.knowledge_base_chat(prompt, knowledge_base_name=selected_kb, top_k=kb_top_k, score_threshold=score_threshold, history=history, model=llm_model, prompt_name=prompt_template_name, temperature=temperature)`这个`api.knowledge_base_chat`是在哪个文件呢？

api.py 文件里的 knowledge_base_chat 方法

**Comment by WSC741606** [comment]
> > @dosu-bot，在`webui_pages/dialogue/dialogue.py`的`dialogue_page`函数里面有`api.knowledge_base_chat(prompt, knowledge_base_name=selected_kb, top_k=kb_top_k, score_threshold=score_threshold, history=history, model=llm_model, prompt_name=prompt_template_name, temperature=temperature)`这个`api.knowledge_base_chat`是在哪个文件呢？
> 
> api.py 文件里的 knowledge_base_chat 方法

谢谢大佬回复，已经找到了~
