### ISSUE TITLE
Qwen-1_8B-Chat文字对答出现乱码

### ISSUE THREAD

**Issue by YiLin198** [chatchat-space/Langchain-Chatchat#3698]
**问题描述 / Problem Description**
将模型切换为Qwen-1_8B-Chat后，文字对答出现乱码的情况，ChatGLM2-6B没有问题
<img width="1511" alt="截屏2024-04-10 下午3 25 00" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/43268291/b33bc45f-0f75-4252-a6ad-00307504ae10">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.10 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-1_8B-Chat
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: M1 pro芯片
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
检查transformer版本
