### ISSUE TITLE
如何修改文件上传时的块大小？

### ISSUE THREAD

**Issue by w-JiqQian** [chatchat-space/Langchain-Chatchat#3700]
**功能描述 / Feature Description**
由于YI-34B-chat等模型用于200k的上下文，在文件问答(非知识库问答)功能中我希望能够修改文件块大小，让每个块的大小大一些

**解决的问题 / Problem Solved**
可以根据模型上下文长度，自由选择文件问答(非知识库问答)的块大小

**Comment by zRzRzRzRzRzRzR** [comment]
这个目前不行，不过改代码很简单，就是设置一个很大的k然后如果超过模型支持 长度就不在传
