### ISSUE TITLE
[FEATURE] 增加知识库文档来自confluence，直接使用ConfluenceLoader

### ISSUE THREAD

**Issue by 666yiyoung666** [chatchat-space/Langchain-Chatchat#3701]
**功能描述 / Feature Description**
希望增加知识库文档来源confluence，导入文档通过url和token进行导入文档到知识库，并且存储到向量数据库。

**Comment by 666yiyoung666** [comment]
像这样：

`Personal Access Token (Server/On-Prem only)
This method is valid for the Data Center/Server on-prem edition only. For more information on how to generate a Personal Access Token (PAT) check the official Confluence documentation at: https://confluence.atlassian.com/enterprise/using-personal-access-tokens-1026032365.html. When using a PAT you provide only the token value, you cannot provide a username. Please note that ConfluenceLoader will run under the permissions of the user that generated the PAT and will only be able to load documents for which said user has access to.

from langchain_community.document_loaders import ConfluenceLoader

loader = ConfluenceLoader(url="https://yoursite.atlassian.com/wiki", token="12345")
documents = loader.load(
    space_key="SPACE", include_attachments=True, limit=50, max_pages=50
)`

**Comment by zRzRzRzRzRzRzR** [comment]
之后考虑加入，可以提一个PR
