### ISSUE TITLE
[BUG] Prompt config中的修改没有效果，已测试GLM3-6B, QWEN1.5 13B

### ISSUE THREAD

**Issue by XienXX** [chatchat-space/Langchain-Chatchat#3703]
**问题描述 / Problem Description**
Prompt config中的修改没有效果，目前已测试GLM3-6B, QWEN1.5 13B。

![d3334f1e4b568284983a19e961fd0d0](https://github.com/chatchat-space/Langchain-Chatchat/assets/125440255/04a3d912-126e-42c7-98a1-a39dcb70380e)
![ad8f846b95d3270c949200ea0a55613](https://github.com/chatchat-space/Langchain-Chatchat/assets/125440255/13f31070-93a6-4302-9126-6ff6fce952ee)

**环境信息 / Environment Information**
- langchain-chatchat：v0.2.9
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / QWEN1.5 13B

求助，请问是提示词本身的问题还是提示词修改没有接到应用层？该如何操作

**Comment by EthanChenLi** [comment]
我也没有效果

**Comment by zixiaotan21** [comment]
同样遇到这个问题，我尝试了一下下面的步骤，可能可以这样解决？

Langchain chatchat 启动后，WebUI界面左侧【请选择Prompt模板】那里，选择定义好的模板。
修改webui_pages\dialogue下面的dialogue.py，将143行
text = f"已切换为 {prompt_template_name} 模板。"
修改为：
text = f"已切换为 {st.session_state.prompt_template_select} 模板。"
具体可以参考 https://github.com/chatchat-space/Langchain-Chatchat/issues/1827 这个issue的方法

我修改之后，好像回答中，会出现想要的提示。

**Comment by EthanChenLi** [comment]
> 同样遇到这个问题，我尝试了一下下面的步骤，可能可以这样解决？
> 
> 1. Langchain chatchat 启动后，WebUI界面左侧【请选择Prompt模板】那里，选择定义好的模板。
> 2. 修改webui_pages\dialogue下面的dialogue.py，将143行
>    text = f"已切换为 {prompt_template_name} 模板。"
>    修改为：
>    text = f"已切换为 {st.session_state.prompt_template_select} 模板。"
> 
> 具体可以参考 #1827 这个issue的方法。
> 
> 我修改之后，好像回答中，会出现想要的提示。

尝试过了，依然不会出现，你那边如果会出现可能是他本身有短时记忆

**Comment by zixiaotan21** [comment]
> > 同样遇到这个问题，我尝试了一下下面的步骤，可能可以这样解决？
> > 
> > 1. Langchain chatchat 启动后，WebUI界面左侧【请选择Prompt模板】那里，选择定义好的模板。
> > 2. 修改webui_pages\dialogue下面的dialogue.py，将143行
> >    text = f"已切换为 {prompt_template_name} 模板。"
> >    修改为：
> >    text = f"已切换为 {st.session_state.prompt_template_select} 模板。"
> > 
> > 具体可以参考 #1827 这个issue的方法。
> > 我修改之后，好像回答中，会出现想要的提示。
> 
> 尝试过了，依然不会出现，你那边如果会出现可能是他本身有短时记忆

确实有点奇怪~我现在尝试的时候也发现，比如说prompt模板里写“在回答末尾加上：”谢谢“。

有些回答会加上“谢谢”。问多几次，好像就不加“谢谢”了。
