### ISSUE TITLE
选择知识库问答是当对话的次数过多后，滚动条每次都会从最上面划下来

### ISSUE THREAD

**Issue by goldmei** [chatchat-space/Langchain-Chatchat#3705]
选择知识库问答是当对话的次数过多后，滚动条每次都会从最上面划下来，而不是从之前的位置划到最下面

**Comment by goldmei** [comment]
在出结果之前滚动条直接停留了最上面了，结果出来后就从最上面划到了最下面

**Comment by akkkkkkkkki** [comment]
我也遇到了这个问题，环境如下：
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.4.0-150-generic-x86_64-with-glibc2.10.
python版本：3.8.1 (default, Jan  8 2020, 22:29:32) 
[GCC 7.3.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35


当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['zhipu-api'] @ cuda
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': &lt;class 'server.model_workers.zhipu.ChatGLMWorker'&gt;}
当前Embbedings模型： text2vec-base-chinese @ cuda

**Comment by zRzRzRzRzRzRzR** [comment]
streamlit渲染的问题，我们之后考虑改进一下
