### ISSUE TITLE
Where is the code for add context

### ISSUE THREAD

**Issue by CVer2022** [chatchat-space/Langchain-Chatchat#3709]
我想知道问题匹配到文本后扩充上下文的逻辑是在哪一部分代码实现的？

**Comment by CVer2022** [comment]
> Hey @CVer2022! 👋 Good to see you back diving into the depths of Langchain-Chatchat. How's the coding journey treating you lately?
> 
> The logic for expanding context after a question matches a text is primarily located in the `server/chat/chat.py` file within the Langchain-Chatchat v0.2.10 codebase. This file handles the construction of prompts with history, either provided by the frontend or fetched from the database, to expand the context for the language model. Here's a brief overview:
> 
> 1. **Frontend-Provided History:** If history is provided by the frontend, it's used to construct the chat prompt with the user's input and the historical messages.
> 2. **Fetching History from Database:** If a conversation ID and history length are provided, the system fetches history from the database to construct the prompt.
> 3. **Default Case without History:** Without history, the prompt is constructed with just the user's input message.
> 
> Classes like `History` and `ConversationBufferDBMemory` are utilized for representing messages and managing conversation history, respectively. For detailed implementation, you might want to look into the following files:
> 
> * `server/chat/chat.py`
> * `server/chat/utils.py`
> * `server/memory/conversation_db_buffer_memory.py`
> 
> These files contain the mechanisms for handling history and expanding context in conversations.
> 
> ## Sources
> * [server/chat/chat.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/chat.py)
> * [server/chat/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/utils.py)
> * [server/memory/conversation_db_buffer_memory.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/memory/conversation_db_buffer_memory.py)
> 
> #### About Dosu

这自动回复的也不对啊

**Comment by zRzRzRzRzRzRzR** [comment]
0.2.x没有扩充上下文
