### ISSUE TITLE
[FEATURE] 简洁阐述功能 / Concise description of the feature

### ISSUE THREAD

**Issue by xxll88** [chatchat-space/Langchain-Chatchat#371]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

2. IP地址8.8.8.8 分词后只保留8
3. pdf在configs/model_config.py中可选文本模式还是ocr模式
4.  给个例子加载整个知识库目录
5.  display_answer显示第几页

**Comment by zRzRzRzRzRzRzR** [comment]
感谢你提出的建议，我们将在之后的更新中逐渐完善这些功能
