### ISSUE TITLE
能否同时支持多输入或通过用户上传文件的方式来一次性读入多个问题？

### ISSUE THREAD

**Issue by Invis-Beholder** [chatchat-space/Langchain-Chatchat#3712]
**问题描述 / Problem Description**
能否同时支持多输入或通过用户上传文件的方式来一次性读入多个问题？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号:v2.0.1
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss

**Comment by zRzRzRzRzRzRzR** [comment]
不改代码的情况确实不行哦
