### ISSUE TITLE
改两个地方快速接入openai 和kimi

### ISSUE THREAD

**Issue by hyy666168** [chatchat-space/Langchain-Chatchat#3718]
1、修改configs/model_config.py
"openai-api": {
        "model_name": "gpt-3.5-turbo",
        "api_base_url": "https://api.openai.com/v1",
        "api_key": "sk-x",
    },

"kimi-api": {
        "model_name": "moonshot-v1-8k",
        "api_base_url": "https://api.moonshot.cn/v1/chat/completions",
        "api_key": "sk-x",
    },

2、搞两个代理ip + 端口号
os.environ['http_proxy'] = 'http://xxxxx:xxxx'
os.environ['https_proxy'] = 'http://xxxx:xxxx'

3、修改server/utils.py里面的两个函数
import os
from loguru import logger

def get_ChatOpenAI(
        model_name: str,
        temperature: float,
        max_tokens: int = None,
        streaming: bool = True,
        callbacks: List[Callable] = [],
        verbose: bool = True,
        **kwargs: Any,
) -> ChatOpenAI:
    config = get_model_worker_config(model_name)
    if model_name in ["openai-api"]:
        model_name = config.get("model_name")
        os.environ['http_proxy'] = 'http://xxxxx:xxxx'
        os.environ['https_proxy'] = 'http://xxxx:xxxx'
        logger.warning(f"http代理启用!")
    elif model_name in ["kimi-api"]:
        model_name = config.get("model_name")
    ChatOpenAI._get_encoding_model = MinxChatOpenAI.get_encoding_model
    model = ChatOpenAI(
        streaming=streaming,
        verbose=verbose,
        callbacks=callbacks,
        openai_api_key=config.get("api_key", "EMPTY"),
        openai_api_base=config.get("api_base_url", fschat_openai_api_address()),
        model_name=model_name,
        temperature=temperature,
        max_tokens=max_tokens,
        openai_proxy=config.get("openai_proxy"),
        **kwargs
    )
    return model
    
def get_OpenAI(
        model_name: str,
        temperature: float,
        max_tokens: int = None,
        streaming: bool = True,
        echo: bool = True,
        callbacks: List[Callable] = [],
        verbose: bool = True,
        **kwargs: Any,
) -> OpenAI:
    config = get_model_worker_config(model_name)
    if model_name in ["openai-api"]:
        model_name = config.get("model_name")
      	os.environ['http_proxy'] = 'http://xxxxx:xxxx'
        os.environ['https_proxy'] = 'http://xxxx:xxxx'
    elif model_name in ["kimi-api"]:
        model_name = config.get("model_name")
    model = OpenAI(
        streaming=streaming,
        verbose=verbose,
        callbacks=callbacks,
        openai_api_key=config.get("api_key", "EMPTY"),
        openai_api_base=config.get("api_base_url", fschat_openai_api_address()),
        model_name=model_name,
        temperature=temperature,
        max_tokens=max_tokens,
        openai_proxy=config.get("openai_proxy"),
        echo=echo,
        **kwargs
    )
    return model

**Comment by applepieiris** [comment]
`1、修改configs/model_config.py
"openai-api": {
"model_name": "gpt-3.5-turbo",
"api_base_url": "https://api.openai.com/v1",
"api_key": "sk-x",
},

"kimi-api": {
"model_name": "moonshot-v1-8k",
"api_base_url": "https://api.moonshot.cn/v1",
"api_key": "sk-x",
},

2、搞两个代理ip + 端口号
os.environ['http_proxy'] = 'http://xxxxx:xxxx/'
os.environ['https_proxy'] = 'http://xxxx:xxxx/'

3、修改server/utils.py里面的两个函数
import os
from loguru import logger

def get_ChatOpenAI(
model_name: str,
temperature: float,
max_tokens: int = None,
streaming: bool = True,
callbacks: List[Callable] = [],
verbose: bool = True,
**kwargs: Any,
) -> ChatOpenAI:
config = get_model_worker_config(model_name)
if model_name in ["openai-api"]:
model_name = config.get("model_name")
os.environ['http_proxy'] = 'http://xxxxx:xxxx/'
os.environ['https_proxy'] = 'http://xxxx:xxxx/'
logger.warning(f"http代理启用!")
elif model_name in ["kimi-api"]:
model_name = config.get("model_name")
ChatOpenAI._get_encoding_model = MinxChatOpenAI.get_encoding_model
model = ChatOpenAI(
streaming=streaming,
verbose=verbose,
callbacks=callbacks,
openai_api_key=config.get("api_key", "EMPTY"),
openai_api_base=config.get("api_base_url", fschat_openai_api_address()),
model_name=model_name,
temperature=temperature,
max_tokens=max_tokens,
openai_proxy=config.get("openai_proxy"),
**kwargs
)
return model

def get_OpenAI(
model_name: str,
temperature: float,
max_tokens: int = None,
streaming: bool = True,
echo: bool = True,
callbacks: List[Callable] = [],
verbose: bool = True,
**kwargs: Any,
) -> OpenAI:
config = get_model_worker_config(model_name)
if model_name in ["openai-api"]:
model_name = config.get("model_name")
os.environ['http_proxy'] = 'http://xxxxx:xxxx/'
os.environ['https_proxy'] = 'http://xxxx:xxxx/'
elif model_name in ["kimi-api"]:
model_name = config.get("model_name")
model = OpenAI(
streaming=streaming,
verbose=verbose,
callbacks=callbacks,
openai_api_key=config.get("api_key", "EMPTY"),
openai_api_base=config.get("api_base_url", fschat_openai_api_address()),
model_name=model_name,
temperature=temperature,
max_tokens=max_tokens,
openai_proxy=config.get("openai_proxy"),
echo=echo,
**kwargs
)
return model`

**Comment by applepieiris** [comment]
别人本来就在configs/model_config.py那里留了openai_proxy代理设置的地方

**Comment by hyy666168** [comment]
> 别人本来就在configs/model_config.py那里留了openai_proxy代理设置的地方

对不起，是我错了
