### ISSUE TITLE
在自己的程序中去调用langchain-chatchat项目。

### ISSUE THREAD

**Issue by asleepforest** [chatchat-space/Langchain-Chatchat#3721]
在本地完成了部署langchain-chatchat项目，并且可以正常地进行使用，将其中configs\server_config.py的地址改为了本机的IP地址。因此我想要在我自己的函数’ask‘中实现一个该函数发送用户的问题（即prompt）和之前的聊天历史（即chat_history列表）到一个本地运行的服务，并处理这个服务返回的响应。我理解的是一个基于基于LangChain和某个大语言模型的本地API，来完成这个目标。
![微信图片_20240411152454](https://github.com/chatchat-space/Langchain-Chatchat/assets/118661325/5753efa3-0572-4e21-9719-5a11fa19ba5a)
但是却一直出现Http错误: 403 Client Error: Forbidden for url: http://192.168.1.100:8501/这个错误。不知道是要对服务器重新进行配置嘛？还是怎么解决？

**Comment by litterGuy** [comment]
api请求端口是7861
可以对照swagger文档查看:http://127.0.0.1:7861/docs
