### ISSUE TITLE
我想使用的LLM，此框架暂不支持，我需要怎么把它加入进来呢，是在微调LLM部分还是自己写api文件调用

### ISSUE THREAD

**Issue by xiaoma444** [chatchat-space/Langchain-Chatchat#3722]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zRzRzRzRzRzRzR** [comment]
写成OpenAI 用OpenAI接入或者自己写fastchat的修改方式

**Comment by xiaoma444** [comment]
我使用的是电信公司的Telechat，但是市面大部分框架不支持将其编写成openai-api，有什么详细点的步骤吗

**Comment by BANGzys** [comment]
> 我使用的是电信公司的Telechat，但是市面大部分框架不支持将其编写成openai-api，有什么详细点的步骤吗

朋友您好，我这边也是和您一样的问题，想使用langchain调用telechat，请问您解决了吗?如果解决了可以简单指导一下吗，不胜感激！
