### ISSUE TITLE
问答看不到生成信息

### ISSUE THREAD

**Issue by wu15936935780** [chatchat-space/Langchain-Chatchat#3723]
**问题描述 / Problem Description**
![4](https://github.com/chatchat-space/Langchain-Chatchat/assets/166684531/0aa6ea43-ecae-402a-8232-a5c3694d2ddd)
![5](https://github.com/chatchat-space/Langchain-Chatchat/assets/166684531/542118fe-0c1c-4a1e-ac64-86721ed1b52f)

**Comment by summerforwish** [comment]
同样的问题，本地调用Qwen1.5-0.5B-chat，改了路径和LLM_MODELS，也关了代理，还是不行。

**Comment by Autism-al** [comment]
同样的问题，请问解决了吗，确定embeding模型和LLM的路径都是正确的，就是对话不了，报连接错误。

**Comment by caaaattt** [comment]
请问解决了吗？我也是同样的问题。为什么每次都要连接Openai？
