### ISSUE TITLE
代码input_msg = History(role="user", content=prompt_template).to_msg_template(False)是有什么作用，把False设置成True对回复会有什么影响

### ISSUE THREAD

**Issue by liaoqingjian** [chatchat-space/Langchain-Chatchat#3724]

**Comment by sevenandseven** [comment]
> 该行`input_msg = History(role="user", content=prompt_template).to_msg_template(False)`对于格式化 Langchain-Chachat 应用程序中的对话历史记录至关重要。该方法通过将历史条目转换为合适的提示格式来为语言模型准备消息内容。当布尔参数设置为`False`或 时`True`，会影响此格式，可能会改变元数据的包含或消息的样式，这可能会影响模型的响应生成。
> 
> 将参数从 更改为`False`可能`True`会调整对话向模型呈现的方式，例如通过添加或省略某些信息（例如时间戳或发件人 ID），或者通过更改呈现样式以更清楚地显示谁在说话。这些变化可能会影响对话的流程以及模型对上下文的理解程度。
> 
> 为了更深入地理解， Langchain-Chachat 应用程序文件中的类`to_msg_template()`中的方法实现提供了具体信息。此方法处理消息内容和角色，根据布尔参数应用不同的格式。[chain/llmchain_with_history.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/chains/llmchain_with_history.py)和[server/chat/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/utils.py)中的源代码将让您最准确地了解此参数如何影响消息格式以及与语言模型的交互。`History``server/chat/utils.py`[](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/chains/llmchain_with_history.py)[](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/utils.py)
> 
> ## 来源
> * [链/llmchain_with_history.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/chains/llmchain_with_history.py)
> * [服务器/聊天/utils.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/chat/utils.py)
> 
> #### 关于多苏

你好，这个是相当于在设置历史对话吗？将以前的对话信息全部记录下来。

**Comment by zRzRzRzRzRzRzR** [comment]
这个是保存历史对话，不用OpenAI的模板
