### ISSUE TITLE
[FEATURE] 简洁阐述功能 / 控制用户提问文字长度，或者说是对话的输入长度

### ISSUE THREAD

**Issue by pdwfree** [chatchat-space/Langchain-Chatchat#3725]
简单搜索了一下代码中文注释，可能有遗漏
所以麻烦大神告知，是否有控制用户提问的文字长度的功能（不区分是对话还是知识库等选项）
因为可能用户会直接往对话框弄个10K长的文字
但是后端大模型只能处理8K
源头上能控制自然是最好的
但是没找到设置，或者是源代码对应的位置。
能提供一个设置界面自然最好
如果没有，请问哪位大神知道，用户提交问题的输入在源代码哪里
是否已经有代码可以控制？
非常感谢。

**Comment by zRzRzRzRzRzRzR** [comment]
有界面的，现在进来就是streamlit界面，在webui通过api传入内容
