### ISSUE TITLE
[BUG] ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by lhtpluto** [chatchat-space/Langchain-Chatchat#3727]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

使用Qwen1.5-72B-Chat时，chat回答一半报错ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
使用Qwen1.5-72B-Chat-GPTQ-Int8时，chat回答直接报错ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()

操作系统：Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen1.5-72B-Chat'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'Qwen1.5-72B-Chat',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen1.5-72B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: WSL
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

![屏幕截图 2024-04-11 225632](https://github.com/chatchat-space/Langchain-Chatchat/assets/132045861/cebfb15b-bee3-4096-925e-4af4ce054ec5)
![屏幕截图 2024-04-11 225659](https://github.com/chatchat-space/Langchain-Chatchat/assets/132045861/154e1b1c-7409-4493-a6ab-ae53b69c4575)

**Comment by zRzRzRzRzRzRzR** [comment]
模型没有正常返回的错误都是这样的

**Comment by xinshang091720** [comment]
这个错误怎么修改啊
