### ISSUE TITLE
升级替换Embedding model

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3732]
我现在使用的embedding model 是bge-large-zh，我想换成bge-large-zh-v1.5
是将"C:\Users\.cache\torch\sentence_transformers\BAAI_bge-large-zh"下的bge-large-zh文件夹删除，然后换成下载的bge-large-zh-v1.5文件吗

**Comment by zRzRzRzRzRzRzR** [comment]
不用，换成绝对地址就行
