### ISSUE TITLE
升级langchain-chatchat和Fast chat版本

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3733]
我现在的langchain-chatchat和Fast chat版本分别是v0.2.9 和0.2.34，我想升级版本，是通过下面这个命令吗：
 安装全部依赖
$ pip install -r requirements.txt

**Comment by zRzRzRzRzRzRzR** [comment]
要制定版本，不要乱升级，langchian 0.1.x 不兼容
