### ISSUE TITLE
知识库（向量库类型faiss embedding模型bge-large-zh-v1.5），向量化文档时将符号"-"解析为换行，请教一下这个要怎么解决呢？

### ISSUE THREAD

**Issue by y-xie-stu** [chatchat-space/Langchain-Chatchat#3737]
![5637c51df3de4736ee8056044fc5863](https://github.com/chatchat-space/Langchain-Chatchat/assets/73353244/dbcedc0e-1315-4a44-b392-a3a09f110c96)

**Comment by zRzRzRzRzRzRzR** [comment]
这个应为对应的词表没有，没办法处理
