### ISSUE TITLE
[BUG] 最轻量部署依然安装torch、nvidia-XXX系列的依赖

### ISSUE THREAD

**Issue by Mydreamandreality** [chatchat-space/Langchain-Chatchat#3748]
**问题描述 / Problem Description**
最轻量用的都是线上的api，确依然安装了torch等依赖

**复现问题的步骤 / Steps to Reproduce**
pip install -r requirements_lite.txt

**预期的结果 / Expected Result**
安装web相关的依赖

**实际结果 / Actual Result**
安装torch，naidia-XXX一大堆系列的依赖

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：8721aad18d9f41d0c0687f12cd252b37e82c3b73
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 ubuntu22
- Python 版本 / Python version: 11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
torch还是要的，但是应该是cpu的

**Comment by EscaticZheng** [comment]
是里面的unstructured默认需要torch2.2.0，导致默认安装torch，而linux下直接安装torch默认会安装gpu版的，所以应该先pip3 install torch==2.2.0 --index-url https://download.pytorch.org/whl/cpu。

**Comment by EscaticZheng** [comment]
顺带一提，在线api里的qianfan里的cachetools的依赖没有加上。我真不知道这是怎么写出来的

**Comment by EscaticZheng** [comment]
还有strsimpy这个依赖在requirements_lite.txt里也没有加上

**Comment by EscaticZheng** [comment]
还有markdownify， sentence_transformers, streamlit，  这些都没有，要不咱把requirements_lite.txt删了吧亲 @zRzRzRzRzRzRzR
