### ISSUE TITLE
如何提升知识库对话文档检索的准确率

### ISSUE THREAD

**Issue by mwang12345** [chatchat-space/Langchain-Chatchat#3752]
我有两个SAP事务代码的使用文档投喂给知识库，分别是ME21N.txt和ME22N.txt。我在提问“ME21N”的相关信息时，总是先检索“ME22N”的文档内容，请问如何提升检索准确度？
![微信截图_20240415155223](https://github.com/chatchat-space/Langchain-Chatchat/assets/14009055/588c399c-06b5-4c64-9764-b4e5c5dec327)
![微信截图_20240415155320](https://github.com/chatchat-space/Langchain-Chatchat/assets/14009055/8abaf888-ce0f-4b5a-b810-340c49d6e245)

**Comment by mwang12345** [comment]
Prompt用的是知识库对话默认prompt
    "knowledge_base_chat": {
        "default":
            '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，'
            '不允许在答案中添加编造成分，答案请使用中文。 </指令>\n'
            '<已知信息>{{ context }}</已知信息>\n'
            '<问题>{{ question }}</问题>\n',

**Comment by mwang12345** [comment]
这个知识库是faiss @ m3e-base 配置的

**Comment by guanyuwl** [comment]
换成 pdf 试一下

**Comment by zRzRzRzRzRzRzR** [comment]
可以查看wiki和先前的issue
