### ISSUE TITLE
使用api接口调用方式实现config配置文件功能

### ISSUE THREAD

**Issue by Shame-fight** [chatchat-space/Langchain-Chatchat#3754]
**功能描述 / Feature Description**
1.使用api调用方式（如post/get请求）获得数据，实现本地、在线大模型和embedding模型的配置读取
2.实现接口调用后实时生效，如接口中新加了一个在线大模型名称和对应调用链接（以openai或你推荐的格式封装），chat相关接口全部生效（输入名称即可立马调用，无需重启项目）
3.model_config.py文件中，如果”LLM_MODELS“字段未添加某个模型，即使在”ONLINE_LLM_MODEL“或”MODEL_PATH--llm_model“中配置了路径或链接，也无法访问；但"embed_model"可以访问，即使”EMBEDDING_MODEL“字段没有指定该embedding模型。如何实现”LLM_MODELS“字段之外的模型调用
**解决的问题 / Problem Solved**
1.实现大模型实时调用
2.以接口的形式接入模型配置文件

**实现建议 / Implementation Suggestions**

**替代方案 / Alternative Solutions**

**其他信息 / Additional Information**

**Comment by Shame-fight** [comment]
机器人快来解答~

**Comment by xiaoma444** [comment]
你想调用的api是wiki里没有，你手搓一个出来封装成openai的格式是吗

**Comment by Shame-fight** [comment]
> 你想调用的api是wiki里没有，你手搓一个出来封装成openai的格式是吗

是的
