### ISSUE TITLE
将模型配置文件model_config.py修改为接口调用方式

### ISSUE THREAD

**Issue by Shame-fight** [chatchat-space/Langchain-Chatchat#3763]
**问题描述 / Problem Description**
将模型文件model_config.py中的配置封装成fastapi接口，使用post或get请求调用，并实时生效，应该如何修改
解决如下问题：
1.修改模型配置文件后需要结束代码，重新执行python startup.py -a才能生效
2.实现模型配置接口封装，支持在线修改参数

**Comment by zRzRzRzRzRzRzR** [comment]
本来就是fastapi啊
正常启动就有了，查看7861端口
