### ISSUE TITLE
[BUG] Qwen1.5 RTX 5880 ADA 四卡推理比双卡还慢

### ISSUE THREAD

**Issue by lhtpluto** [chatchat-space/Langchain-Chatchat#3764]
**问题描述 / Problem Description**
[BUG] Qwen1.5 RTX 5880 ADA 四卡推理比双卡还慢
Qwen1.5  RTX 5880 四卡推理速度非常慢，比单卡双卡三卡都慢，四卡时GPU运行平吕由2.7GHz降低到0.6-0.8GHZ,GPU功率由160W到235W下降至60W到80W

双卡速度还是很快的，三卡稍微慢点，也能接受，但用四卡后就卡成狗了

启动命令  python startup.py --all-webui --model-name Qwen1.5-32B-Chat

是否启用VLLM：否

ubuntu

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-6.5.0-27-generic-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen1.5-32B-Chat'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'Qwen1.5-14B-Chat',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

WIN11
==============================Langchain-Chatchat Configuration==============================
操作系统：Windows-10-10.0.22631-SP0.
python版本：3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen1.5-32B-Chat'] @ cuda
{'device': 'cuda',
 'host': '127.0.0.1',
 'infer_turbo': False,
 'model_path': 'Qwen\\Qwen1.5-32B-Chat',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

WSL
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen1.5-32B-Chat'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': 'Qwen1.5-32B-Chat',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen1.5-32B-Chat、Qwen1.5-72B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）： bge-large-zh-v1.5 @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:  ubuntu、WIN、WSL
- Python 版本 / Python version:  3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by ilovesouthpark** [comment]
我的想法是这样的，不一定对，欢迎大家指正探讨。你是跑32B是吗，fp16的话好像一共86g显存消耗（这么多吗？gpuz4图相加，当然这可能是已加载了部分token的情况）。2张5880 48x2已经有96g了 ，其实你是让2张的计算量摊到4张上，张量并行，它的计算和通讯不是同步的，所以是一张张卡按顺序计算，而外部卡间带宽远小于内部的（内部传输带宽5880 960G/S，外部5880支持p2p估计实际也就50G/S多一点），单卡的运算负荷被你降低了，增加了大量的通讯（不消耗算力）这就造成你卡越多越慢。

**Comment by YeQiuO** [comment]
没有配置 nvlink 就别多卡了，性能不升属于正常，开销都在通讯上了。直接 fastchat 部署没有这部分的优化，它只是很简单的把模型分摊到了多张卡上

**Comment by ilovesouthpark** [comment]
量化版本的模型如果sequential不能起作用，更新一下量化的那一些依赖看。fp16的应该不需要更新这些依赖。

**Comment by a442509097** [comment]
> 试试这个办法，手动更改一下fastchat里多gpu的参数，在model_adapter.py里， 217行开始 elif device == "cuda": kwargs = {"torch_dtype": torch.float16} if num_gpus != 1: kwargs["device_map"] = "sequential" # Auto 改为 sequential, 从第一张显卡开始填满内存， if max_gpu_memory is None: kwargs[ "device_map" ] = "sequential" # This is important for not the same VRAM sizes available_gpu_memory = get_gpu_memory(num_gpus) kwargs["max_memory"] = { i: str(int(available_gpu_memory[i] * 0.85)) + "GiB" for i in range(num_gpus) } else: kwargs["max_memory"] = {i: max_gpu_memory for i in range(num_gpus)} #这里可以max_gpu_memory直接改为“31GiB”或者去server.py里改。然后再四卡运行看看速度看，可能最大显存大小需要自己调整看看。

感谢! 我是12G + 6G的组合, 默认显存应该是平均分配的, 现在改成sequential, 就可以跑起来了.
