### ISSUE TITLE
kimi api调用出错：Error code: 404 - {'error': {'message': 'not found the model or permission denied',怎么办？

### ISSUE THREAD

**Issue by newstargo** [chatchat-space/Langchain-Chatchat#3767]
在ONLINE_LLM_MODEL增加了kimi-api，如下
   "kimi-api": {
        "model_name": "moonshot-v1-8k",
        "api_base_url": "https://api.moonshot.cn/v1",
        "api_key": "sk-i...",
        "openai_proxy": "",
    },
执行后出现错误提示，如下：
2024-04-16 15:53:39,136 - utils.py[line:40] - ERROR: NotFoundError: Caught exception: Error code: 404 - {'error': {'message': 'not found the model or permission denied', 'type': 'resource_not_found_error'}}

请教大佬们，是什么原因？

**Comment by newstargo** [comment]
没发现有什么问题，有大佬能详细说说吗

**Comment by XuZhirong** [comment]
`server/utils.py` 中做如下替换即可
```python
if model_name == "openai-api"
```
替换为 
```python
if model_name in ["openai-api", "kimi-api"]
```
