### ISSUE TITLE
[FEATURE] 简洁阐述功能 /文本文件的知识点之间使用什么分隔符可以分割？

### ISSUE THREAD

**Issue by xuji755** [chatchat-space/Langchain-Chatchat#377]
**功能描述 / Feature Description**
文本文件的知识点之间使用什么分隔符可以分割？

**Comment by imClumsyPanda** [comment]
，。！？；”等中/英文常用标点符号

xuji755 ***@***.***>于2023年5月16日 周二13:09写道：

**Comment by mxzgn** [comment]
包含知识点包含特殊字符ip那种情况怎么处理
