### ISSUE TITLE
[BUG]启动时报错

### ISSUE THREAD

**Issue by MokoKing666** [chatchat-space/Langchain-Chatchat#3774]
ImportError: cannot import name 'model_schema' from 'pydantic.schema' (C:\Users\mhy55\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\schema.py)

**Comment by xqxls** [comment]
> ImportError: cannot import name 'model_schema' from 'pydantic.schema' (C:\Users\mhy55\AppData\Local\Programs\Python\Python312\Lib\site-packages\pydantic\schema.py)

我也遇到了这个问题，你后来解决了吗？
我是将requirements.txt调整到vllm==0.3.3之后遇到的

**Comment by caosena5101** [comment]
安装pip install pydantic==1.10.13这个版本后，没再报上面的错
