### ISSUE TITLE
[BUG] 简洁阐述[BUG] 当使用LLaMA-Factory 使用.bin格式训练合并之后的模型，然后使用langchain-chatchat，加载训练的模型出现TypeError: PeftConfig.__init__() got an unexpected keyword argument '_name_or_path'问题 / Concise description of the issue

### ISSUE THREAD

**Issue by caijx168** [chatchat-space/Langchain-Chatchat#3792]
[BUG] 简洁阐述[BUG] 当使用LLaMA-Factory 使用.bin格式训练合并之后的模型，然后使用langchain-chatchat，加载训练的模型出现TypeError: PeftConfig.__init__() got an unexpected keyword argument '_name_or_path'问题 / Concise description of the issue

**Comment by TC10127** [comment]
不能直接把config.json文件名字改成adapter_config.json
