### ISSUE TITLE
The app is attempting to load the component from ****, and hasn't received its "streamlit " message.

### ISSUE THREAD

**Issue by supergangchao** [chatchat-space/Langchain-Chatchat#3796]
前端页面提示以下错误信息
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/129723199/30867a38-dfda-4549-b10a-0e7365d6d94a)

`Your app is having trouble loading the streamlit_option_menu.option_menu component.

(The app is attempting to load the component from ****, and hasn't received its "streamlit
" message.)

If this is a development build, have you started the dev server?
If this is a release build, have you compiled the frontend?
For more troubleshooting help, please see the [Streamlit Component docs](https://docs.streamlit.io/library/components) or visit our [forums](https://discuss.streamlit.io/).`

**Comment by zRzRzRzRzRzRzR** [comment]
无视就行，刷新就好

**Comment by zixiaotan21** [comment]
同样出现这个问题，想问问楼主解决了吗
