### ISSUE TITLE
知识库数据集比较大,大概有100多G，全部进行切分向量化用了一周，但是无法查询了，一直都在运行中，这怎么解决？

### ISSUE THREAD

**Issue by zmwstu** [chatchat-space/Langchain-Chatchat#3798]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zmwstu** [comment]
<img width="472" alt="Snipaste_2024-04-18_00-56-59" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/153530377/bbdc322e-ba66-4f12-a760-074fbb7b294d">
<img width="1413" alt="Snipaste_2024-04-18_01-00-42" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/153530377/172dffac-593b-43fe-aaed-02eb0753a253">

**Comment by zmwstu** [comment]
我用的向量数据库是faiss

**Comment by zmwstu** [comment]
> To address the issue of your system remaining in a running state without completing queries on your 100GB vectorized dataset, consider the following targeted solutions:要解决系统在未完成对 100GB 矢量化数据集的查询时仍处于运行状态的问题，请考虑以下有针对性的解决方案：
> 
> 1. **Optimize FAISS Index Configuration**: Different index types and settings can significantly impact performance. Experiment with various configurations to find the most efficient for your dataset.优化 FAISS 索引配置：不同的索引类型和设置会显著影响性能。尝试各种配置，以找到最适合数据集的配置。
> 2. **Implement Parallel Processing**: Distribute the workload across multiple cores or GPUs to speed up query processing, if your hardware supports it.实现并行处理：将工作负载分布在多个内核或 GPU 之间，以加快查询处理速度（如果硬件支持）。
> 3. **Check Docker Resource Allocation**: Ensure the Docker container has sufficient CPU, RAM, and swap space allocated to handle the workload.检查 Docker 资源分配：确保 Docker 容器分配了足够的 CPU、RAM 和交换空间来处理工作负载。
> 4. **Model and FAISS Library Compatibility**: Verify that all components, including langchain-ChatGLM, FAISS, and Docker, are up to date and compatible with each other. Incompatibilities can cause unexpected behavior.模型和 FAISS 库兼容性：验证所有组件（包括 langchain-ChatGLM、FAISS 和 Docker）是否都是最新的并且彼此兼容。不兼容可能会导致意外行为。
> 5. **Enable Detailed Logging**: Turn on logging for both the langchain-ChatGLM application and Docker to identify where the process might be hanging.启用详细日志记录：打开 langchain-ChatGLM 应用程序和 Docker 的日志记录，以确定进程可能挂起的位置。
> 6. **System Monitoring**: Use tools to monitor CPU, RAM, or I/O wait times to pinpoint bottlenecks.系统监控：使用工具监控 CPU、RAM 或 I/O 等待时间，以查明瓶颈。
> 
> For a more precise solution, providing logs or profiling information that indicates where the system is getting stuck would be helpful. Additionally, ensure there's no antivirus or firewall interference with your setup, as this can sometimes cause issues with file access or network communication.为了获得更精确的解决方案，提供日志或分析信息来指示系统卡住的位置会很有帮助。此外，请确保您的设置没有防病毒或防火墙干扰，因为这有时会导致文件访问或网络通信出现问题。
> 
> If these steps do not resolve your issue, please provide more details about your operating system, Python version, Docker version, and any specific error messages or logs for further assistance.如果这些步骤不能解决您的问题，请提供有关您的操作系统、Python 版本、Docker 版本以及任何特定错误消息或日志的更多详细信息，以获得进一步的帮助。
> 
> ## Sources 来源
> * [[BUG] 简洁阐述问题 /卡死在| INFO | root | UnstructuredFileLoader used for [BUG] 简洁阐述问题 /卡死在|资讯 |根 |UnstructuredFileLoader 用于](https://github.com/chatchat-space/Langchain-Chatchat/issues/1642)
> * [knowledge_base/samples/content/test_files/langchain-ChatGLM_open.jsonl](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/knowledge_base/samples/content/test_files/langchain-ChatGLM_open.jsonl)
> * [configs/**init**.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/configs/__init__.py)
> 
> #### About Dosu 关于Dosu

没有任何报错信息，就是单纯的一直在运行，一个小时都没有进行回答，这个怎么解决？

**Comment by zmwstu** [comment]
> 2\. 在 FAISS 中启用 GPU 支持

怎么在 FAISS 中启用 GPU 支持？代码该怎么更改？

**Comment by YeQiuO** [comment]
FAISS 不适合大量数据，试试其他的向量数据库吧

**Comment by zdxkcsc** [comment]
我也遇到这样的问题

**Comment by zdxkcsc** [comment]
zmwstu 你怎么解决的换数据库吗？

**Comment by AMAG-AB** [comment]
为什么没解决都closed

**Comment by zmwstu** [comment]
> zmwstu 你怎么解决的换数据库吗？
用milvus数据库可以的，但是只能在linux系统部署
