### ISSUE TITLE
[BUG] 对话函数在编写时的参数传递；chatGLM4做Agent对话时的轮次问题

### ISSUE THREAD

**Issue by saltedfish2** [chatchat-space/Langchain-Chatchat#3803]
**问题描述 / 项目代码使用的疑问**
用简洁明了的语言描述这个问题 / 对于项目中的函数编写提出的问题

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

你好，我在学习代码的过程中有两个问题想要询问，
1、项目里对于几个对话功能使用了不同的定义调用方式。比如Langchain-Chatchat/server/chat/chat.py和/Langchain-Chatchat/server/chat/file_chat.py中的的异步生成器都没有试用参数的定义，而在其他的对话模块中都对异步生成器做了参数的传入定义，这是为什么呢？
2、我使用zhipu-api进行agent问答的时候，不能读取到对话的历史记录，而使用
```agent = LLMSingleActionAgent(

                llm_chain=llm_chain,

                output_parser=output_parser,

                stop=["\nObservation:", "Observation"],

                allowed_tools=tool_names,

            )

            agent_executor = AgentExecutor.from_agent_and_tools(agent=agent,
                                                                tools=tools,
verbose=True,                                                       memory=memory, )
```
时就可以正常获取历史对话记录了，这是bug还是我哪里的更改出问题了呢？

**Comment by zRzRzRzRzRzRzR** [comment]
memory 中带了历史
