### ISSUE TITLE
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by supergangchao** [chatchat-space/Langchain-Chatchat#3806]
只要zhi知识检索条数3条，就会报下面错误，如果改成1条就正常。
<img width="784" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/129723199/42af1a72-b1a5-45f5-b396-2bd1b3597ada">

API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by 488283943** [comment]
你去查日志 应该能看到cuda out of memory

**Comment by lhtpluto** [comment]
> 只要zhi知识检索条数3条，就会报下面错误，如果改成1条就正常。 <img alt="image" width="784" src="https://private-user-images.githubusercontent.com/129723199/323732334-42af1a72-b1a5-45f5-b396-2bd1b3597ada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTc3MjQsIm5iZiI6MTcxMzUxNzQyNCwicGF0aCI6Ii8xMjk3MjMxOTkvMzIzNzMyMzM0LTQyYWYxYTcyLWIxYTUtNDVmNS1iMzk2LTJiZDFiMzU5N2FkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOVQwOTAzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNzFkYWNjNjllZTNiYzhlOTVmZGVkODIyZGNlZWEyOGI2Mzg2NDBhZWRjMWQzNzY2NDhiMDdmMjc2ZjI5NGUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bdWjyw01klrD-OeSvHXL60LdaGXqMeUa5ktAOCS-0lI">
> 
> API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

https://github.com/chatchat-space/Langchain-Chatchat/issues/3424#issuecomment-2044692553


应该是加入了知识库内容后，超过了大模型token输入的上限，尝试用更大的token的大模型或者maxtoken改高，在model config应该

**Comment by 488283943** [comment]
我在运行之前设置了maxtoken为65536 没啥用的，之前是在另一个issue的评论里面也是看到了他们跟我一样，能运行，问两句就直接显存爆了，设置显存占用也没辙。开发者说在3.x版本修复这个问题

**Comment by supergangchao** [comment]
> 你去查日志 应该能看到cuda out of memory

不是，只有单挑记录的时候现实这个问题，用的embedding bge-large-1.5-zh出现的。

**Comment by 488283943** [comment]
> > 你去查日志 应该能看到cuda out of memory
> 
> 不是，只有单挑记录的时候现实这个问题，用的embedding bge-large-1.5-zh出现的。

我试了很多个embedding模型 都是出现类似问题 我看他们基本上换张显存更大的卡就好了 我设置了最大使用显存 没起作用的

**Comment by supergangchao** [comment]
> > > 你去查日志 应该能看到cuda out of memory
> > 
> > 
> > 不是，只有单挑记录的时候现实这个问题，用的embedding bge-large-1.5-zh出现的。
> 
> 我试了很多个embedding模型 都是出现类似问题 我看他们基本上换张显存更大的卡就好了 我设置了最大使用显存 没起作用的

是的，我感觉也是这样，最好用更多的gpu服务器去跑这个，否则各种问题

**Comment by linaiyue** [comment]
> 你去查日志 应该能看到cuda out of memory

请问大佬我查了内核日志是out of memory ，用的embedding ：bge-large-1.5-zh，该怎么解决的？
