### ISSUE TITLE
知识库问答中，答案部分出现<回答>

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3814]
**问题描述 / Problem Description**
本地部署,LLM选用qwen 1.5-14B, embedding model为bge-large-zh-v1.5, 知识库问答中，answer中有<回答>

**预期的结果 / Expected Result**
无报错

**实际结果 / Actual Result**
<img width="600" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/6de2859d-2289-418a-a5e1-45a547479387">

**环境信息 / Environment Information**
angchain-ChatGLM 版本/commit 号：v0.2.10
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-1.5-14B
使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: ：Windows-10-10.0.22631-SP0.
Python 版本 / Python version: ：3.10.8
其他相关环境信息 / Other relevant environment information:

**Comment by zRzRzRzRzRzRzR** [comment]
因为指令跟随了 <问题>

可以适当修改提示词

**Comment by zixiaotan21** [comment]
好的，谢谢解答！想请教一下，修改提示词是在prompt_config.py文件，修改promt模板的内容吗~
