### ISSUE TITLE
[BUG] 在sever/chat/chat.py中，加入API接口无返回，ERROR: API通信超时，请确认已启动FastChat与API服务（详见Wiki '5. 启动 API 服务或 Web UI'）。（timed out）

### ISSUE THREAD

**Issue by jiaweiLL** [chatchat-space/Langchain-Chatchat#3816]
` if history: # 优先使用前端传入的历史消息
            history = [History.from_data(h) for h in history]
            print("history = "+str(history))
            prompt_template = get_prompt_template("llm_chat", prompt_name)
            input_msg = History(role="user", content=prompt_template).to_msg_template(False)
            chat_prompt = ChatPromptTemplate.from_messages(
                [i.to_msg_template() for i in history] + [input_msg])
        elif conversation_id and history_len > 0: # 前端要求从数据库取历史消息
            # 使用memory 时必须 prompt 必须含有memory.memory_key 对应的变量
            prompt = get_prompt_template("llm_chat", "with_history")
            chat_prompt = PromptTemplate.from_template(prompt)
            # 根据conversation_id 获取message 列表进而拼凑 memory
            memory = ConversationBufferDBMemory(conversation_id=conversation_id,
                                                llm=model,
                                                message_limit=history_len)
            print("memory = " + str(memory))
        else:
                CaseJudge = {
                    "query": query,
                    "stream": True,
                    "temperature": 0.7,
                    "model_name": "chatglm3-6b",
                    "prompt_name": "案件要素"
                }
                url = 'http://127.0.0.1:7861/chat/chat'
                Factor_judgement_Response = requests.post(url, headers=headers, json=CaseJudge, stream=True)`

在问答过程中，出现下面错误

**Comment by jiaweiLL** [comment]
2024-04-19 15:53:36,300 - utils.py[line:193] - ERROR: API通信超时，请确认已启动FastChat与API服务（详见Wiki '5. 启动 API 服务或 Web UI'）。（timed out）
2024-04-19 15:54:14,890 - utils.py[line:95] - ERROR: ReadTimeout: error when post /llm_model/list_running_models: timed out

**Comment by jiaweiLL** [comment]
> The errors you're encountering indicate a timeout issue when making API requests, which could be due to network latency, server-side processing delays, or incorrect configuration. Here are steps to address the issue:
> 
> 1. **Ensure Services Are Running**: Confirm that both FastChat service and API service are operational. Check for any error messages in their logs.
> 2. **Verify Configuration**: Make sure the services are running on their correct ports and that your application is configured to connect to these services properly.
> 3. **Network Check**: Look into any potential network connection issues that might be causing timeouts.
> 4. **Adjust Timeout Settings**: If the issue is related to slow server responses, consider increasing the timeout value in your request function. This can be done by setting the `timeout` parameter.
> 5. **Implement Retry Logic**: To handle `ReadTimeout` errors, you can implement a retry mechanism. This can be manually done or by using libraries that support retries. Here's an example using `requests`:
> 
> ```python
> import requests
> from requests.adapters import HTTPAdapter
> from urllib3.util.retry import Retry
> 
> def requests_retry_session(retries=3, backoff_factor=0.3, status_forcelist=(500, 502, 504), session=None):
>     session = session or requests.Session()
>     retry = Retry(total=retries, read=retries, connect=retries, backoff_factor=backoff_factor, status_forcelist=status_forcelist)
>     adapter = HTTPAdapter(max_retries=retry)
>     session.mount('http://', adapter)
>     session.mount('https://', adapter)
>     return session
> 
> try:
>     response = requests_retry_session().post('YOUR_API_ENDPOINT', json={'your': 'data'})
>     response.raise_for_status()
>     # Handle your response here
> except requests.exceptions.HTTPError as errh:
>     print(f'Http Error: {errh}')
> except requests.exceptions.ConnectionError as errc:
>     print(f'Error Connecting: {errc}')
> except requests.exceptions.Timeout as errt:
>     print(f'Timeout Error: {errt}')
> except requests.exceptions.RequestException as err:
>     print(f'OOps: Something Else: {err}')
> ```
> 
> This approach helps in automatically retrying the request in case of a timeout and can be adjusted based on your specific needs.
> 
> If these steps do not resolve the issue, further investigation into the performance of the FastChat service, API service, or network optimization might be necessary.
> 
> ## Sources
> * [API通信超时，请确认已启动FastChat与API服务](https://github.com/chatchat-space/Langchain-Chatchat/issues/2807)
> * [server/api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/api.py)
> * [startup.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/startup.py)
> * [server/llm_api_stale.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/llm_api_stale.py)
> * [server/llm_api.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/server/llm_api.py)
> 
> #### About Dosu

不对，为什么webUI.py -a启动后，chat.py中无法添加API的方式进行对话问题？？

**Comment by jiusi9** [comment]
我也遇到了这个问题，langchain启动时是能使用llm的。
大概过1-2小时，再打开就出现了报错

API通信超时，请确认已启动FastChat与API服务（详见Wiki '5. 启动 API 服务或 Web UI'）。（timed out）
--
- ERROR: ReadTimeout: error when post /llm_model/list_running_models: timed out
