### ISSUE TITLE
知识库问答，提问同一个问题，第一次问无法回答，第二次问才能正确回答

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3817]
**问题描述 / Problem Description**
知识库问答，提问同一个问题，第一次问无法回答，第二次问，或者多次提问之后，才能正确回答
使用的是Qwen-14B模型，在本地部署，是大模型推理能力问题导致的吗？

**复现问题的步骤 / Steps to Reproduce**
<img width="586" alt="9abf5efc967a9dcbefac6de9d939faf" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/fd64b692-d10b-4c2e-a9da-804a9ead1a53">

<img width="573" alt="6a565e6bc6e6f3c120e01029d95dcf0" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/46bade76-6ffc-4df4-b41e-3d57e3bff82c">

**Comment by zixiaotan21** [comment]
1. Langchain-Chatchat 首先会运行knowledge_base_chat.py这个文件。

```python
if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
    prompt_template = get_prompt_template("knowledge_base_chat", "empty")
else:
    prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
```

**Comment by zRzRzRzRzRzRzR** [comment]
可能你问的太快了，第一次需要启动embed模型
