### ISSUE TITLE
新出的Llama-3-8B模型如何设置？

### ISSUE THREAD

**Issue by lededev** [chatchat-space/Langchain-Chatchat#3820]
目前版本支持这个模型吗，如果可以，应该如何设置？

**Comment by liaohaoxiang** [comment]
> ```
> "llm_model": {
>     "chatglm3-6b": "D:/Models/chatglm3-6b",
>     "baichuan-7b-chat": "D:/Models/Baichuan-7B-Chat",
>     "Qwen-7B-Chat": "D:/Models/Qwen-7B-Chat",
>     "Meta-Llama-3-8B": "D:/Models/Meta-Llama-3-8B",
> }
> ```
> 
> 亲测可用

本地自己跑的话需要多大显存呀？
