### ISSUE TITLE
[BUG] 在知识库中配置提示词无效

### ISSUE THREAD

**Issue by EthanChenLi** [chatchat-space/Langchain-Chatchat#3823]
<img width="915" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/6337626/f6e961f4-6d12-41d1-8fac-516ca6aabf5e">
在知识库模板中配置提示词，在界面中使用知识库回答的时候，配置中的提示词无效果。

**Comment by zRzRzRzRzRzRzR** [comment]
要选中为你的提示词名字，default就是你截图的这个
