### ISSUE TITLE
我已经使用做好了知识图谱的内容，如何将我的内容让LLM知道并输出

### ISSUE THREAD

**Issue by hOVOzw** [chatchat-space/Langchain-Chatchat#3824]
例如这是一个关系：
('精品牛肉面(清泰街店)', '联系电话', '18597024920')

人问：精品牛肉面的信息
AI回答：精品牛肉面(清泰街店)的联系电话是18597024920

需要修改哪部分的代码呢

**Comment by YeQiuO** [comment]
建议你去学一下 `from langchain.chains import GraphCypherQAChain` 这个类的使用方法
