### ISSUE TITLE
这么好的项目，我为什么找不到可以实时更新知识库设置？

### ISSUE THREAD

**Issue by running-frog** [chatchat-space/Langchain-Chatchat#3831]
每天有一些资料要实时加到知识库，但知识库中已有几万的文件，如何不重建知识库让新知识自动更新呢？实在不行手动更新也行，每次重建知识库太痛苦了！！！

**Comment by davidjia1972** [comment]
你看一下创建知识库的程序的代码吧，人家本来就是支持手动增量更新的
