### ISSUE TITLE
知识库中，添加记忆模块，保留上下文信息，使每次问答具有关联性

### ISSUE THREAD

**Issue by sevenandseven** [chatchat-space/Langchain-Chatchat#3833]
**功能描述 / Feature Description**
知识库中，添加记忆模块，保留上下文信息，使每次问答具有关联性

**解决的问题 / Problem Solved**
多次知识问答不具备上下文关联性

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
使用ConversationSummaryBufferMemory保留多次对话的记忆.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by davidjia1972** [comment]
这个接口功能是支持传入对话历史的，所以你可以自己在客户端维护上下文信息的

**Comment by sevenandseven** [comment]
> 



> 这个接口功能是支持传入对话历史的，所以你可以自己在客户端维护上下文信息的

我目前将记忆内容加入LLMChain中，发现该类不支持memory参数，我是需要换一个链使用吗？

以下是我的代码：
chat_prompt = ChatPromptTemplate.from_messages([input_msg])
        print("************************************knowledge_base_chat chat prompt in")
        print("***************************************chat_prompt:", chat_prompt)
        memory = ConversationSummaryBufferMemory(llm=model, max_token_limit=100)
        print("***************************************memory:", memory)
        for message in history:
            # 检查消息的角色
            if message.role == 'user':
                # 添加用户消息
                memory.chat_memory.add_user_message(message.content)
            else:
                # 添加AI消息
                memory.chat_memory.add_ai_message(message.content)
        
        chain = LLMChain(prompt=chat_prompt, llm=model, memory=memory, verbose=True)

**Comment by sevenandseven** [comment]
> 



> 这个接口功能是支持传入对话历史的，所以你可以自己在客户端维护上下文信息的

我目前将记忆内容加入LLMChain中，发现该类不支持memory参数，我是需要换一个链使用吗？

以下是我的代码：
chat_prompt = ChatPromptTemplate.from_messages([input_msg])
        print("************************************knowledge_base_chat chat prompt in")
        print("***************************************chat_prompt:", chat_prompt)
        memory = ConversationSummaryBufferMemory(llm=model, max_token_limit=100)
        print("***************************************memory:", memory)
        for message in history:
            # 检查消息的角色
            if message.role == 'user':
                # 添加用户消息
                memory.chat_memory.add_user_message(message.content)
            else:
                # 添加AI消息
                memory.chat_memory.add_ai_message(message.content)
        
        chain = LLMChain(prompt=chat_prompt, llm=model, memory=memory, verbose=True)

**Comment by sevenandseven** [comment]
目前碰到了两个问题，这两个地方不知道该怎么修改：
chain = LLMChain(prompt=chat_prompt, llm=model, memory=memory, verbose=True)
                
        # Begin a task that runs in the background.
        task = asyncio.create_task(wrap_done(
            chain.acall({"context": context, "question": query}),
            callback.done),
        )

**Comment by loredunk** [comment]
hello，我发现知识库对话的时候，他没法结合上一轮对话的内容，这个怎么做呢

**Comment by zixiaotan21** [comment]
同样遇到这个问题，我在issue#3883看到有相关的讨论，可以尝试上面的方法解决~
