### ISSUE TITLE
[BUG] vllm docker部署模型对话完成后无法自动结束，报错：<|endoftext|><|im_end|> <|im_start|>

### ISSUE THREAD

**Issue by huangshengfu** [chatchat-space/Langchain-Chatchat#3834]
聊天对话回答完问题后无法结束聊天一直在重复打印<|im_start|>

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/70123250/3bbe304d-5b9c-464b-9d66-14677c2aab80)

docker 运行参数命令：
docker run  --runtime nvidia --gpus all  --name vllm-qwen14b     -v  ~/.cache/huggingface:/root/.cache/huggingface    \
   -v /data1/Download/models/Qwen-14B-Chat-Int4:/data/shared/Qwen/Qwen-Chat     -p 8901:8000     --ipc=host  \
   vllm/vllm-openai:latest --model /data/shared/Qwen/Qwen-Chat     --max-model-len 2048  --trust-remote-code \
   --tensor-parallel-size 2   --gpu-memory-utilization 0.7  --api-key "xxxxx"

应该设置什么参数才能实现？stop_token_ids，我不知道该如何传？

**预期的结果 / Expected Result**
希望回答完毕后正常结束

**实际结果 / Actual Result**
如上图所示

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-72B,

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by huangshengfu** [comment]
I don't necessarily need to pass stop_token_ids to solve this problem, or do you have a better way for Docker?

**Comment by huangshengfu** [comment]
请问下这段配置应该加到哪个文件中？

**Comment by zRzRzRzRzRzRzR** [comment]
vllm 你应该自己设置 special token吧
