### ISSUE TITLE
[BUG] 大模型的API端口接入仅能回答知识库里的内容，当回答知识库以外的内容，则会回答，根据已知知识无法回答该问题

### ISSUE THREAD

**Issue by WellAllIn** [chatchat-space/Langchain-Chatchat#3835]
**问题描述 / Problem Description**
使用大模型的API端口接入，如智谱API，仅能回答知识库里的内容，当回答知识库以外的内容，则会回答，根据已知知识无法回答该问题。但是调用本地的大模型，如qwen 1.5 14B，就能够通过大模型的自生成能力去回答。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.1
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen 1.5 14B 与智谱API
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-small
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: windows
- Python 版本 / Python version: python 3.11

**Comment by zixiaotan21** [comment]
同样遇到这个问题。
但我用本地的大模型qwen 1.5 14B做知识库问答，即便是问知识库里的问题，也会显示”根据已知知识无法回答该问题“
问多几次，又能正确回答了，有点奇怪~
想问问楼主用的是qwen 1.5 14B，还是qwen 1.5 14B-chat呀？我用qwen 1.5 14B 感觉问答效果不理想，甚至不如qwen 1.5 7B-chat

**Comment by 513901** [comment]
> 同样遇到这个问题。 但我用本地的大模型qwen 1.5 14B做知识库问答，即便是问知识库里的问题，也会显示“根据已知知识无法回答该问题” 问多几次，又能正确回答了，有点奇怪~ 想问问楼主用的是qwen 1.5 14B，还是qwen 1.5 14B-chat呀？我用qwen 1.5 14B 感觉问答效果不理想，甚至不如qwen 1.5 7B-chat

我用的是qwen 1.5 14B。在回答时，修改了一点chain里面的内容调用基底模型都能回答问题，但是使用API问答在知识库以外的问题仍然回答根据已知知识无法回答该问题。具体修改的是knowledge_base_chat.py这个文件，修改如下，希望能够帮助你。
if len(source_documents) == 0:  # 没有找到相关文档
            print('没有找到相关文档，开始进行LLM的自身回答')
            extendchain = LLMChain(prompt=chat_prompt, llm=model)
            extendResponse = extendchain._call({"context": context, "question": query});
            print("repo---->"+json.dumps(extendResponse))
            source_documents.append(extendResponse['text'])

        if stream:
            async for token in callback.aiter():
                # Use server-sent-events to stream the response
                yield json.dumps({"answer": token}, ensure_ascii=False)
            yield json.dumps({"docs": source_documents}, ensure_ascii=False)

**Comment by zixiaotan21** [comment]
谢谢楼主大佬！我大概明白了，原来是修改这里的代码：
if len(source_documents) == 0: # 没有找到相关文档

其实我还有点好奇，Langchain-Chatchat 是在什么条件下，会判断为"据已知知识无法回答该问题",楼主有找到这一字段的源代码在哪个.py文件吗？

**Comment by 513901** [comment]
> 谢谢楼主大佬！我大概明白了，原来是修改这里的代码： if len(source_documents) == 0: # 没有找到相关文档
> 
> 其实我还有点好奇，Langchain-Chatchat 是在什么条件下，会判断为"据已知知识无法回答该问题",楼主有找到这一字段的源代码在哪个.py文件吗？

  这个"据已知知识无法回答该问题"字段出现在config/prompt_config.py里面，我不太懂怎么设置prompt,做了一些修改都没有用。

**Comment by zixiaotan21** [comment]
谢谢楼主！原来是在config/prompt_config.py这里，我找到啦，我也不太会修改prompt哈哈哈~

> > 谢谢楼主大佬！我大概明白了，原来是修改这里的代码： if len(source_documents) == 0: # 没有找到相关文档
> > 其实我还有点好奇，Langchain-Chatchat 是在什么条件下，会判断为"据已知知识无法回答该问题",楼主有找到这一字段的源代码在哪个.py文件吗？
> 
> 这个"据已知知识无法回答该问题"字段出现在config/prompt_config.py里面，我不太懂怎么设置prompt,做了一些修改都没有用。

**Comment by zixiaotan21** [comment]
我尝试了一下设置prompt的方法，应该是直接改指令那一行就行了，但修改之前还有一些配置要改，可以参考issue #1827

**Comment by zixiaotan21** [comment]
楼主大佬，这个问题我重新想了一下，不知道这样理解对不对？（我参考了 #2458)

1. Langchain-Chatchat 首先会运行knowledge_base_chat.py这个文件。

```python
if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
    prompt_template = get_prompt_template("knowledge_base_chat", "empty")
else:
    prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
``` 

1）如果提问知识库以外的内容，提问词与知识库完全没联系（e.g.今天星期几这种问题）
属于len(docs) == 0的情形，prompt模板会切换为config/prompt_config.py里面的empty模板，转为通过大模型的自生成能力去回答问题。同时会显示下面内容：

```python
        if len(source_documents) == 0:  # 没有找到相关文档
            source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
``` 

2）如果提问知识库以外的内容，但提问词与知识库有联系。
（e.g.提问：原产地证书是什么？
         知识库原问题：原产地证书自助打印流程？）
属于len(docs) 不等于0的情形，prompt模板是你自己设置的模板，运行config/prompt_config.py。

2.（接1 的2）部分）再运行config/prompt_config.py
```python
"knowledge_base_chat": {
        "default":
            '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，'
            '不允许在答案中添加编造成分，答案请使用中文。 </指令>\n'
            '<已知信息>{{ context }}</已知信息>\n'
            '<问题>{{ question }}</问题>\n',

``` 
1）如果你的大模型推理能力弱，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，不能推断整合出所问问题（原产地证书是什么？）的答案，会回答“根据已知信息无法回答该问题“。

2）如果你的大模型推理能力强，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，可以推断整合出所问问题（原产地证书是什么？）的答案。

PS：我上面都是用本地大模型跑的，因为zhipu-api过期了。

**Comment by 513901** [comment]
> 楼主大佬，这个问题我重新想了一下，不知道这样理解对不对？（我参考了 #2458)
> 
> 1. Langchain-Chatchat 首先会运行knowledge_base_chat.py这个文件。
> 
> ```python
> if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
>     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
> else:
>     prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
> ```
> 
> 1）如果提问知识库以外的内容，提问词与知识库完全没联系（e.g.今天星期几这种问题） 属于len(docs) == 0的情形，prompt模板会切换为config/prompt_config.py里面的empty模板，转为通过大模型的自生成能力去回答问题。同时会显示下面内容：
> 
> ```python
>         if len(source_documents) == 0:  # 没有找到相关文档
>             source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
> ```
> 
> 2）如果提问知识库以外的内容，但提问词与知识库有联系。 （e.g.提问：原产地证书是什么？ 知识库原问题：原产地证书自助打印流程？） 属于len(docs) 不等于0的情形，prompt模板是你自己设置的模板，运行config/prompt_config.py。
> 
> 2.（接1 的2）部分）再运行config/prompt_config.py
> 
> ```python
> "knowledge_base_chat": {
>         "default":
>             '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，'
>             '不允许在答案中添加编造成分，答案请使用中文。 </指令>\n'
>             '<已知信息>{{ context }}</已知信息>\n'
>             '<问题>{{ question }}</问题>\n',
> ```
> 
> 1）如果你的大模型推理能力弱，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，不能推断整合出所问问题（原产地证书是什么？）的答案，会回答“根据已知信息无法回答该问题“。
> 
> 2）如果你的大模型推理能力强，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，可以推断整合出所问问题（原产地证书是什么？）的答案。
> 
> PS：我上面都是用本地大模型跑的，因为zhipu-api过期了。

我也是一个小菜鸟~
谢谢你的整理！
我也去研究了https://github.com/chatchat-space/Langchain-Chatchat/issues/2458，然后调用本地模型一直一直都没有问题。但是调用API，提问“你好”，他就会回答知识库里不相关的内容。
我也尝试过根据知识库的相关度得分去修改逻辑，当得分低于0.5就调用LLM回答，但是没有得到改善。仍然是本地模型能够实现推理，但是API调用的结合知识库回答能力很差。
我后去再去研究一下不使用LANGCHAIN CHATCHAT，单独调用API的对于RAG和AGENT的效果~
非常感谢你的回答呀

**Comment by zixiaotan21** [comment]
> > 楼主大佬，这个问题我重新想了一下，不知道这样理解对不对？（我参考了 #2458)
> > 
> > 1. Langchain-Chatchat 首先会运行knowledge_base_chat.py这个文件。
> > 
> > ```python
> > if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
> >     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
> > else:
> >     prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 1）如果提问知识库以外的内容，提问词与知识库完全没联系（e.g.今天星期几这种问题） 属于len(docs) == 0的情形，prompt模板会切换为config/prompt_config.py里面的empty模板，转为通过大模型的自生成能力去回答问题。同时会显示下面内容：
> > ```python
> >         if len(source_documents) == 0:  # 没有找到相关文档
> >             source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 2）如果提问知识库以外的内容，但提问词与知识库有联系。 （e.g.提问：原产地证书是什么？ 知识库原问题：原产地证书自助打印流程？） 属于len(docs) 不等于0的情形，prompt模板是你自己设置的模板，运行config/prompt_config.py。
> > 2.（接1 的2）部分）再运行config/prompt_config.py
> > ```python
> > "knowledge_base_chat": {
> >         "default":
> >             '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，'
> >             '不允许在答案中添加编造成分，答案请使用中文。 </指令>\n'
> >             '<已知信息>{{ context }}</已知信息>\n'
> >             '<问题>{{ question }}</问题>\n',
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 1）如果你的大模型推理能力弱，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，不能推断整合出所问问题（原产地证书是什么？）的答案，会回答“根据已知信息无法回答该问题“。
> > 2）如果你的大模型推理能力强，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，可以推断整合出所问问题（原产地证书是什么？）的答案。
> > PS：我上面都是用本地大模型跑的，因为zhipu-api过期了。
> 
> 我也是一个小菜鸟~ 谢谢你的整理！ 我也去研究了[https://github.com/chatchat-space/Langchain-Chatchat/issues/2458，然后调用本地模型一直一直都没有问题。但是调用API，提问“你好”，他就会回答知识库里不相关的内容。](https://github.com/chatchat-space/Langchain-Chatchat/issues/2458%EF%BC%8C%E7%84%B6%E5%90%8E%E8%B0%83%E7%94%A8%E6%9C%AC%E5%9C%B0%E6%A8%A1%E5%9E%8B%E4%B8%80%E7%9B%B4%E4%B8%80%E7%9B%B4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98%E3%80%82%E4%BD%86%E6%98%AF%E8%B0%83%E7%94%A8API%EF%BC%8C%E6%8F%90%E9%97%AE%E2%80%9C%E4%BD%A0%E5%A5%BD%E2%80%9D%EF%BC%8C%E4%BB%96%E5%B0%B1%E4%BC%9A%E5%9B%9E%E7%AD%94%E7%9F%A5%E8%AF%86%E5%BA%93%E9%87%8C%E4%B8%8D%E7%9B%B8%E5%85%B3%E7%9A%84%E5%86%85%E5%AE%B9%E3%80%82) 我也尝试过根据知识库的相关度得分去修改逻辑，当得分低于0.5就调用LLM回答，但是没有得到改善。仍然是本地模型能够实现推理，但是API调用的结合知识库回答能力很差。 我后去再去研究一下不使用LANGCHAIN CHATCHAT，单独调用API的对于RAG和AGENT的效果~ 非常感谢你的回答呀

不客气！我也是小白，也在摸索哈哈哈~有问题可以多交流呀~

关于API调用的结合知识库回答能力的话，我之前也试过用zhipu-api和qwen-api去做，我个人感觉qwen的效果会比zhipu好，zhipu-api回答有时候确实不太行，或许你可以试试qwen的。

**Comment by 513901** [comment]
> > > 楼主大佬，这个问题我重新想了一下，不知道这样理解对不对？（我参考了 #2458)
> > > 
> > > 1. Langchain-Chatchat 首先会运行knowledge_base_chat.py这个文件。
> > > 
> > > ```python
> > > if len(docs) == 0:  # 如果没有找到相关文档，使用empty模板
> > >     prompt_template = get_prompt_template("knowledge_base_chat", "empty")
> > > else:
> > >     prompt_template = get_prompt_template("knowledge_base_chat", prompt_name)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 1）如果提问知识库以外的内容，提问词与知识库完全没联系（e.g.今天星期几这种问题） 属于len(docs) == 0的情形，prompt模板会切换为config/prompt_config.py里面的empty模板，转为通过大模型的自生成能力去回答问题。同时会显示下面内容：
> > > ```python
> > >         if len(source_documents) == 0:  # 没有找到相关文档
> > >             source_documents.append(f"<span style='color:red'>未找到相关文档,该回答为大模型自身能力解答！</span>")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 2）如果提问知识库以外的内容，但提问词与知识库有联系。 （e.g.提问：原产地证书是什么？ 知识库原问题：原产地证书自助打印流程？） 属于len(docs) 不等于0的情形，prompt模板是你自己设置的模板，运行config/prompt_config.py。
> > > 2.（接1 的2）部分）再运行config/prompt_config.py
> > > ```python
> > > "knowledge_base_chat": {
> > >         "default":
> > >             '<指令>根据已知信息，简洁和专业的来回答问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题”，'
> > >             '不允许在答案中添加编造成分，答案请使用中文。 </指令>\n'
> > >             '<已知信息>{{ context }}</已知信息>\n'
> > >             '<问题>{{ question }}</问题>\n',
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 1）如果你的大模型推理能力弱，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，不能推断整合出所问问题（原产地证书是什么？）的答案，会回答“根据已知信息无法回答该问题“。
> > > 2）如果你的大模型推理能力强，根据已知信息（知识库原问题：原产地证书自助打印流程？）的内容，可以推断整合出所问问题（原产地证书是什么？）的答案。
> > > PS：我上面都是用本地大模型跑的，因为zhipu-api过期了。
> > 
> > 
> > 我也是一个小菜鸟~ 谢谢你的整理！ 我也去研究了[https://github.com/chatchat-space/Langchain-Chatchat/issues/2458，然后调用本地模型一直一直都没有问题。但是调用API，提问“你好”，他就会回答知识库里不相关的内容。](https://github.com/chatchat-space/Langchain-Chatchat/issues/2458%EF%BC%8C%E7%84%B6%E5%90%8E%E8%B0%83%E7%94%A8%E6%9C%AC%E5%9C%B0%E6%A8%A1%E5%9E%8B%E4%B8%80%E7%9B%B4%E4%B8%80%E7%9B%B4%E9%83%BD%E6%B2%A1%E6%9C%89%E9%97%AE%E9%A2%98%E3%80%82%E4%BD%86%E6%98%AF%E8%B0%83%E7%94%A8API%EF%BC%8C%E6%8F%90%E9%97%AE%E2%80%9C%E4%BD%A0%E5%A5%BD%E2%80%9D%EF%BC%8C%E4%BB%96%E5%B0%B1%E4%BC%9A%E5%9B%9E%E7%AD%94%E7%9F%A5%E8%AF%86%E5%BA%93%E9%87%8C%E4%B8%8D%E7%9B%B8%E5%85%B3%E7%9A%84%E5%86%85%E5%AE%B9%E3%80%82) 我也尝试过根据知识库的相关度得分去修改逻辑，当得分低于0.5就调用LLM回答，但是没有得到改善。仍然是本地模型能够实现推理，但是API调用的结合知识库回答能力很差。 我后去再去研究一下不使用LANGCHAIN CHATCHAT，单独调用API的对于RAG和AGENT的效果~ 非常感谢你的回答呀
> 
> 不客气！我也是小白，也在摸索哈哈哈~有问题可以多交流呀~
> 
> 关于API调用的结合知识库回答能力的话，我之前也试过用zhipu-api和qwen-api去做，我个人感觉qwen的效果会比zhipu好，zhipu-api回答有时候确实不太行，或许你可以试试qwen的。


好滴，谢谢呀，我多去试几个API
