### ISSUE TITLE
streamlit webui.py如何实现跨域？ 即在server/chat/chat.py中加入requests.post，调用FastAPI

### ISSUE THREAD

**Issue by jiaweiLL** [chatchat-space/Langchain-Chatchat#3836]
CaseJudge = {
                    "query": query,
                    "stream": True,
                    "temperature": 0.7,
                    "model_name": "chatglm3-6b",
                    "prompt_name": "案件要素"
                }
url = 'http://127.0.0.1:7861/chat/chat'
                
Factor_judgement_Response = requests.post(url, headers=headers, json=CaseJudge, stream=True)

**Comment by jiaweiLL** [comment]
> To enable CORS in your FastAPI application and allow your Streamlit app to make requests to it, you need to configure CORS on the FastAPI side. Here's how you can do it:
> 
> 1. Install `fastapi` and `uvicorn` if you haven't already.
> 2. Use `CORSMiddleware` from `starlette.middleware.cors` to add CORS headers to your FastAPI app.
> 
> Here's a quick example:
> 
> ```python
> from fastapi import FastAPI
> from starlette.middleware.cors import CORSMiddleware
> 
> app = FastAPI()
> 
> # List of allowed origins (you can use ["*"] to allow all origins)
> origins = [
>     "http://localhost:8501",  # Assuming your Streamlit app runs on the default port
>     # Add other origins as needed
> ]
> 
> app.add_middleware(
>     CORSMiddleware,
>     allow_origins=origins,
>     allow_credentials=True,
>     allow_methods=["*"],  # Allows all methods
>     allow_headers=["*"],  # Allows all headers
> )
> 
> @app.post("/your-endpoint")
> async def your_endpoint():
>     return {"message": "This is your FastAPI endpoint response"}
> ```
> 
> Replace `http://localhost:8501` with the actual URL of your Streamlit app if it's hosted elsewhere, and adjust the endpoint in the `@app.post("/your-endpoint")` decorator to match your specific case.
> 
> By configuring CORS in your FastAPI app as shown, you'll allow your Streamlit app to make `requests.post` calls to your FastAPI server without being blocked by CORS policies.
> 
> #### Details
> _To continue the conversation, mention @dosu._

不行  2024-04-22 10:12:32,488 - utils.py[line:193] - ERROR: API通信超时，请确认已启动FastChat与API服务（详见Wiki '5. 启动 API 服务或 Web UI'）。（timed out）

**Comment by jiaweiLL** [comment]
还是不行

**Comment by jiaweiLL** [comment]
我请求baidu.com就可以    请求fastAPI就一直2024-04-22 10:12:32,488 - utils.py[line:193] - ERROR: API通信超时，请确认已启动FastChat与API服务（详见Wiki '5. 启动 API 服务或 Web UI'）。（timed out）

**Comment by zRzRzRzRzRzRzR** [comment]
仙子啊不就是跨域的吗，你在server config设置就行了
