### ISSUE TITLE
对于问答对的 存储与检索

### ISSUE THREAD

**Issue by nauyiahc** [chatchat-space/Langchain-Chatchat#3839]
**功能描述 / Feature Description**
对于不同文件的存储的考虑：
    1. 段落型知识文件-全部向量化
    2. 问答对文件(jsonl个数)-只对query进行向量化，将answer存到metadata中，检索时，基于用户query和vs中的query进行匹配
    3. 段落型和问答对两种类型可以分别设置不同的阈值，一般情况问答对的阈值会低一些
**解决的问题 / Problem Solved**
   应对段落行知识文件和问答对两种情景
   提高检索能力

现在我想用问答对jsonl文件存储到向量库，但只想向量化query部分，这个目前有实现吗？

**Comment by zixiaotan21** [comment]
同样有这个想法，想问问楼主解决了吗
