### ISSUE TITLE
构建自定义的model_workers后，利用知识库问答出错。

### ISSUE THREAD

**Issue by jinyilun718** [chatchat-space/Langchain-Chatchat#3841]
**问题描述 / Problem Description**
自己构建了一个自定义的model_workers,使用LLM对话一切正常，但是使用知识库问答就会报如下错误：

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

2024-04-22 16:51:55 | INFO | stdout | INFO:     127.0.0.1:6400 - "POST /v1/chat/completions HTTP/1.1" 200 OK
2024-04-22 16:51:55,608 - _client.py[line:1758] - INFO: HTTP Request: POST http://127.0.0.1:20000/v1/chat/completions "HTTP/1.1 200 OK"
{'id': 'chatcmpl-4S48dT6JLVyr6NRUvmoiAn', 'choices': [{'delta': {'content': None, 'function_call': None, 'role': 'assistant', 'tool_calls': None}, 'finish_reason': None, 'index': 0, 'logprobs': None}], 'created': None, 'model': 'zhipu-api', 'object': None, 'system_fingerprint': None}
2024-04-22 16:51:55 | INFO | httpx | HTTP Request: POST http://127.0.0.1:21001/worker_generate_stream "HTTP/1.1 200 OK"
{'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'error_code': 500, 'text': 'zhipu-api请求API时发生错误：unknown role in msg:  1. 账号申请\n首先，您需要拥有一个北京大学高性能计算平台的账号。通常，账号的申请需要通过学校或研究所的相关流程进行，具体可以咨询您所在单位的信息技术部门或是直接访问北京大学高性能计算平台的官方网站查看申请指南。\n'}
2024-04-22 16:51:55,613 - utils.py[line:38] - ERROR: object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/home/jinyilun/学术/LLM_PKU/Langchain-Chatchat/server/utils.py", line 36, in wrap_done
    await fn
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain/chains/base.py", line 385, in acall
    raise e
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain/chains/base.py", line 379, in acall
    await self._acall(inputs, run_manager=run_manager)
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain/chains/llm.py", line 275, in _acall
    response = await self.agenerate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain/chains/llm.py", line 142, in agenerate
    return await self.llm.agenerate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 554, in agenerate_prompt
    return await self.agenerate(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 514, in agenerate
    raise exceptions[0]
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 617, in _agenerate_with_cache
    return await self._agenerate(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 525, in _agenerate
    return await agenerate_from_stream(stream_iter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain_core/language_models/chat_models.py", line 87, in agenerate_from_stream
    async for chunk in stream:
  File "/home/jinyilun/anaconda3/envs/llm/lib/python3.11/site-packages/langchain_community/chat_models/openai.py", line 496, in _astream
    if len(chunk["choices"]) == 0:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-04-22 16:51:55,614 - utils.py[line:40] - ERROR: TypeError: Caught exception: object of type 'NoneType' has no len()
agenerateof type 'NoneType' has no len()

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
后来发现一旦搜索到的知识库里面存在"/n"字符就会报错。简单过滤掉以后可以运行，但是一旦LLM的历史信息中有'/n'字符就会报同样的错误。

自定义的model_worker如下：
```

from contextlib import contextmanager

import httpx
from fastchat.conversation import Conversation
from httpx_sse import EventSource

from server.model_workers.base import *
from fastchat import conversation as conv
import sys
from typing import List, Dict, Iterator, Literal, Any
import jwt
import time
import json
from configs import logger, log_verbose
from server.utils import get_httpx_client

@contextmanager
def connect_sse(client: httpx.Client, method: str, url: str, **kwargs: Any):
    with client.stream(method, url, **kwargs) as response:
        yield EventSource(response)


def generate_token(apikey: str, exp_seconds: int):
    try:
        id, secret = apikey.split(".")
    except Exception as e:
        raise Exception("invalid apikey", e)

    payload = {
        "api_key": id,
        "exp": int(round(time.time() * 1000)) + exp_seconds * 1000,
        "timestamp": int(round(time.time() * 1000)),
    }

    return jwt.encode(
        payload,
        secret,
        algorithm="HS256",
        headers={"alg": "HS256", "sign_type": "SIGN"},
    )


class PkuOpenaiWorker(ApiModelWorker):
    DEFAULT_EMBED_MODEL = "embedding-2"

    def __init__(
            self,
            *,
            model_names: List[str] = ["zhipu-api"],
            controller_addr: str = None,
            worker_addr: str = None,
            version: Literal["glm-4"] = "gpt-4-0125-preview",
            **kwargs,
    ):
        kwargs.update(model_names=model_names, controller_addr=controller_addr, worker_addr=worker_addr)
        kwargs.setdefault("context_len", 4096)
        super().__init__(**kwargs)
        self.version = version

    def do_chat(self, params: ApiChatParams) -> Iterator[Dict]:
        params.load_config(self.model_names[0])

        access_code = ""


        data = {
            "model": params.version,
            "messages": params.messages,
            # "max_tokens":10000,
            "temperature": params.temperature,
            "presence_penalty": 0,
            "frequency_penalty": 0,
            "top_p": 1,
            "stream": True
        }
        url = ""
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer nk-{access_code}"
        }
        print("custom_openai的结果",params.messages)
        text = ""
        if log_verbose:
            logger.info(f'{self.__class__.__name__}:url: {url}')
            logger.info(f'{self.__class__.__name__}:headers: {headers}')
            logger.info(f'{self.__class__.__name__}:data: {data}')

        with get_httpx_client() as client:
            with client.stream("POST", url, headers=headers, json=data) as response:
                # print(data)
                for line in response.iter_lines():
                    if not line.strip() or "[DONE]" in line:
                        continue
                    if line.startswith("data: "):
                        line = line[6:]
                    resp = json.loads(line)
                    if choices := resp["choices"]:
                        if chunk := choices[0].get("delta", {}).get("content"):
                            text += chunk
                            yield {
                                    "error_code": 0,
                                    "text": text
                                }
                        print(text)
                    else:
                        self.logger.error(f"请求 PKU API 时发生错误：{resp}")




    def do_embeddings(self, params: ApiEmbeddingsParams) -> Dict:

        params.load_config(self.model_names[0])

        access_code = ""  # 访问密码
        url = ""

        headers = {
            'Authorization': f'Bearer nk-{access_code}',
            'Content-Type': 'application/json'
        }

        i = 0
        batch_size = 1
        result = []
        while i < len(params.texts):
            data = {
                "model": params.embed_model or "text-embedding-3-small",
                "input": "".join(params.texts[i: i + batch_size])
            }

            payload = json.dumps(data)
            response = requests.post(url, headers=headers, data=payload)
            ans = response.json()
            result.extend(ans["data"][0]["embedding"])
            i += batch_size


        return {"code": 200, "data": result}

    def get_embeddings(self, params):
        print("embedding")
        print(params)

    def make_conv_template(self, conv_template: str = None, model_path: str = None) -> Conversation:
        return conv.Conversation(
            name=self.model_names[0],
            system_message="你是智谱AI小助手，请根据用户的提示来完成任务",
            messages=[],
            roles=["user", "assistant", "system"],
            sep="\n###",
            stop_str="###",
        )

```

**Comment by SwordHG** [comment]
LLM的历史信息中有'/n'字符就会报同样的错误，对于这个错误，应该如何修复呢

**Comment by SwordHG** [comment]
> def make_conv_template(self, conv_template: str = None, model_path: str = None) -> Conversation:
>         return conv.Conversation(
>             name=self.model_names[0],
>             system_message="你是智谱AI小助手，请根据用户的提示来完成任务",
>             messages=[],
>             roles=["user", "assistant", "system"],
>             sep="\n###",
>             stop_str="###",
>         )

当模型回答的时候是markdown格式，文字里面会有#标识，和上面的sepsep="\n###" 冲突，造成不正确的拆分，然后大模型不能识别，报错，有小概率，但是对于固定问题会比较经常发生

**Comment by bspeng922** [comment]
修改server/model_workers/base.py文件中的prompt_to_messages方法，通过正则表达式进行匹配


```
    def prompt_to_messages(self, prompt: str) -> List[Dict]:
        '''
        将prompt字符串拆分成messages.
        '''
        result = []
        user_role = self.user_role
        ai_role = self.ai_role

        pattern = rf"{self.conv.sep}({user_role}|{ai_role}):(.+?)(?={self.conv.sep}({user_role}|{ai_role}):|$)"

        # 使用正则查找所有匹配
        matches = re.findall(pattern, prompt, re.DOTALL)

        for role, content, _ in matches:
            content = content.strip()
            if role == "user":
                result.append({"role": user_role, "content": content})
            elif role == "assistant":
                result.append({"role": ai_role, "content": content})
            else:
                raise RuntimeError(f"unknown role in msg: {role} - {content}")
        return result

```
