### ISSUE TITLE
知识库中有图片的在线链接，想要把图片也展示在知识库聊天的内容中，怎么修改代码呢？

### ISSUE THREAD

**Issue by zmwstu** [chatchat-space/Langchain-Chatchat#3846]
['en', 'https://en.wikipedia.org/wiki/Maine%27s_3rd_congressional_district', 'https://upload.wikimedia.org/wikipedia/commons/7/7d/SamuelWGould.jpg', "Maine's 3rd congressional district", 'List of members representing the district', "Maine's 3rd congressional district [/](https://vscode-remote+ssh-002dremote-002b49-002e232-002e228-002e90.vscode-resource.vscode-cdn.net/) List of members representing the district", '', 'English: Samuel W. Gould, US Representative from Maine', '', 'image/jpeg', '1870', '1421', 'false', 'true', 'false', "Maine's 3rd congressional district is an obsolete congressional district. It was created in 1821 after Maine achieved statehood in 1820 as part of the enactment of the Missouri Compromise. It was eliminated in 1963 after the 1960 U.S. Census. Its last congressman was Clifford McIntire.", '']
这是我的数据集内容，并且知识库回答引用的时候会引用出来，我想要把引用的图片例如这个https://upload.wikimedia.org/wikipedia/commons/7/7d/SamuelWGould.jpg，直接在回答完知识库之后，将图片显示出来，怎么修改代码呢？小机器人！

**Comment by bk112** [comment]
你好，我也有这样的需求，具体怎么实现呢
