### ISSUE TITLE
不支持面壁的MiniCPM多模态模型吗？

### ISSUE THREAD

**Issue by rogermayo182** [chatchat-space/Langchain-Chatchat#3850]
切到OmniLMM-12B模型的时候提示模型格式不对

**Comment by running-frog** [comment]
> 切到OmniLMM-12B模型的时候提示模型格式不对

MiniCPM有什么好？个人使用体验完全没法了qwen-VL相比，慢+弱智

**Comment by rogermayo182** [comment]
> > 切到OmniLMM-12B模型的时候提示模型格式不对
> 
> MiniCPM有什么好？个人使用体验完全没法和qwen-VL相比，慢+弱智

本来是想本地跑起来看下效果怎么样，看他们宣传的很厉害，各种投资，各种吊打友商

**Comment by zRzRzRzRzRzRzR** [comment]
多模态都不支持

**Comment by sevenandseven** [comment]
> 切到OmniLMM-12B模型的时候提示模型格式不对

你好，请问是怎么在langchain中调用MiniCPM-2B-dpo-fp32模型的，我也想在langchain中加载，求解答。
