### ISSUE TITLE
各位大佬，请教下，我一键启动后无法打开网页是为什么呀

### ISSUE THREAD

**Issue by liyiyiya** [chatchat-space/Langchain-Chatchat#3851]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/166470931/9acee7fd-b310-42e0-9cd0-78b96da4ace5)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/166470931/f21a7844-ba89-4eb6-8357-065f5c65801f)

**Comment by zmwstu** [comment]
如果是在服务器上跑的，本地当然打不开，需要端口转发。

**Comment by liyiyiya** [comment]
> 如果是在服务器上跑的，本地当然打不开，需要端口转发。
我用ssh连接了云服务器，可以在本地调用云服务器的内容了，可还是打不开本地连接TT....
大佬还有啥办法呀

**Comment by yhzhou688** [comment]
你可以试试将0.0.0.0:8501当中的**0.0.0.0**改为你的服务器地址，我就是这样解决的

**Comment by liyiyiya** [comment]
嗯呐，刚刚解决啦，改成了127.0.0.1，配置了SSH，调整了ipv6的顺序。也不知道哪步解决的，。，最后能用了
