### ISSUE TITLE
跑不动，完全跑不动

### ISSUE THREAD

**Issue by running-frog** [chatchat-space/Langchain-Chatchat#3859]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/64595207/c45d10d2-0634-4a57-888e-2dec64c55bab)
停了好长时间了，跑不动了。。

**Comment by zRzRzRzRzRzRzR** [comment]
大文件很吃配置，尽量用GPU来做OCR，CPU很慢甚至卡死
