### ISSUE TITLE
在线大模型对话报异常

### ISSUE THREAD

**Issue by mwang12345** [chatchat-space/Langchain-Chatchat#3865]
langchain-chatchat v0.2.10版本，本地连接qwen和chatglm3-6b模型都没有问题，但连接在线qwen或智普AI时，对话都报这个异常。请问是哪里配错了，或别的什么原因。
model_config.py配置如下：
LLM_MODELS = ["qwen-api"]
...
    # 阿里云通义千问 API，文档参考 https://help.aliyun.com/zh/dashscope/developer-reference/api-details
    "qwen-api": {
        "version": "qwen-max",
        "api_key": "sk-5287039896***********",
        "provider": "QwenWorker",
        "embed_model": "text-embedding-v1"  # embedding 模型名称
    },

对话报错如下：
![c94b720252acb87189cc0f6288b4b14](https://github.com/chatchat-space/Langchain-Chatchat/assets/14009055/61aa27ae-535e-42e8-b4db-9a3aa990c380)

**Comment by Ptianyu** [comment]
我本地Qwen-7B-chat也报这个问题，您知道到原因么？
