### ISSUE TITLE
[BUG] 使用langchain+qwen，页面上连续提问多个问题后回答异常。

### ISSUE THREAD

**Issue by lumeng1005** [chatchat-space/Langchain-Chatchat#3874]
**问题描述 / Problem Description**
知识库是“问题种类-问题描述”excel清单，
验证集是若干问题描述，千问回答问题的分类。
在页面上连续提问，发现以下问题：
1. 向模型连续提问10-20个问题后，答案重复。（如：提问前10个问题可以正常回答，问题11、12、13….答案与问题10一模一样。）
2. 基于问题1清空对话rerun，提问前几个问题模型依据已知信息无法作答（知识库没变，重新运行之前可以正常回答），多问几个不同问题后可恢复作答。

**环境信息 / Environment Information**
- langchain-Chatchat版本：v0.2.10 ,langchain版本0.0.354
- 使用的模型：Qwen-14B
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version: 3.11.8

**Comment by zRzRzRzRzRzRzR** [comment]
那就是embedding不一定有检索到
