### ISSUE TITLE
[BUG] ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by oymclihui** [chatchat-space/Langchain-Chatchat#3875]
-----------------model path------------------
BAAI/bge-reranker-large
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    await func()
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1e38f329150

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    |     sock = connection.create_connection(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    |     raise err
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    |     sock.connect(sa)
    | TimeoutError: timed out
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    |     response = self._make_request(
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    |     raise new_e
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    |     self._validate_conn(conn)
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connectionpool.py", line 1096, in _validate_conn
    |     conn.connect()
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connection.py", line 611, in connect
    |     self.sock = sock = self._new_conn()
    |                        ^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connection.py", line 212, in _new_conn
    |     raise ConnectTimeoutError(
    | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x000001E384C35050>, 'Connection to huggingface.co timed out. (connect timeout=10)')
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\requests\adapters.py", line 486, in send
    |     resp = conn.urlopen(
    |            ^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    |     retries = retries.increment(
    |               ^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    |     raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /BAAI/bge-reranker-large/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E384C35050>, 'Connection to huggingface.co timed out. (connect timeout=10)'))
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\file_download.py", line 1261, in hf_hub_download
    |     metadata = get_hf_file_metadata(
    |                ^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    |     return fn(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\file_download.py", line 1674, in get_hf_file_metadata
    |     r = _request_wrapper(
    |         ^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\file_download.py", line 369, in _request_wrapper
    |     response = _request_wrapper(
    |                ^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\file_download.py", line 392, in _request_wrapper
    |     response = get_session().request(method=method, url=url, **params)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\requests\sessions.py", line 589, in request
    |     resp = self.send(prep, **send_kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\requests\sessions.py", line 703, in send
    |     r = adapter.send(request, **kwargs)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\utils\_http.py", line 68, in send
    |     return super().send(request, *args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\requests\adapters.py", line 507, in send
    |     raise ConnectTimeout(e, request=request)
    | requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /BAAI/bge-reranker-large/resolve/main/config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001E384C35050>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: a087738b-fb11-44b6-b639-efa19b279bda)')
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\transformers\utils\hub.py", line 385, in cached_file
    |     resolved_file = hf_hub_download(
    |                     ^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\utils\_validators.py", line 119, in _inner_fn
    |     return fn(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\huggingface_hub\file_download.py", line 1406, in hf_hub_download
    |     raise LocalEntryNotFoundError(
    | huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
    |
    | The above exception was the direct cause of the following exception:
    |
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    |     await func()
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\chat\knowledge_base_chat.py", line 92, in knowledge_base_chat_iterator
    |     reranker_model = LangchainReranker(top_n=top_k,
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\reranker\reranker.py", line 49, in __init__
    |     self._model = CrossEncoder(model_name=model_name_or_path, max_length=1024, device=device)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py", line 39, in __init__
    |     self.config = AutoConfig.from_pretrained(model_name)
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\transformers\models\auto\configuration_auto.py", line 1100, in from_pretrained
    |     config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
    |                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\transformers\configuration_utils.py", line 634, in get_config_dict
    |     config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\transformers\configuration_utils.py", line 689, in _get_config_dict
    |     resolved_config_file = cached_file(
    |                            ^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\transformers\utils\hub.py", line 425, in cached_file
    |     raise EnvironmentError(
    | OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like BAAI/bge-reranker-large is not the path to a directory containing a file named config.json.
    | Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
    +------------------------------------
2024-04-25 12:07:56,208 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by zRzRzRzRzRzRzR** [comment]
没链接上模型，看报错就是没找到模型
