### ISSUE TITLE
[FEATURE] 性能优化

### ISSUE THREAD

**Issue by gcodepeak** [chatchat-space/Langchain-Chatchat#388]
**功能描述 / Feature Description**
请问有什么性能调节的参数或者方法吗？

1.5G的txt文本（大概3万个文件），导入需要2小时，生成向量库需要16小时
机器配置：40C，E5-2630；3卡的3090

CPU使用率和GPU的使用率看起来没有并行

**Comment by imfht** [comment]
+1
