### ISSUE TITLE
知识库问答—LLM模型求推荐

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3881]
**问题描述 / Problem Description**
进行知识库问答时，本地部署qwen-1.5-7B-chat, qwen-1.5-14B-chat，回答效果不好，使用qwen-1.5-72B-chat 运行又太慢了。

想请教一下各位大佬，有好用的LLM模型推荐不？

**Comment by zixiaotan21** [comment]
@dosu

MAX_TOKENS参数如何设置

**Comment by zixiaotan21** [comment]
> 这大概率不是模型的问题，是你知识库组成和配置的问题

1. 我的知识库是下面这样的：

```
# 问题1

## 问题
XXX

## 回答
XXX

#问题2

## 问题
XXX

## 回答
XXX

``` 
text splitter 算法用MarkdownHeaderTextsplitter，可以将不同的问答对，QA1，QA2切分为不同的向量。

实际提问问题1的时候，也确实能将答案1 检索出来，但回答的时候，没有完全按照答案1来回答，会加入一些编造的内容，这是我的模型推理能力不足吗？

2. 配置的话，我是用4090显卡去跑的，现在用的模型是qwen-1.5-14B-chat 。

**Comment by Zephyr69** [comment]
> > 这大概率不是模型的问题，是你知识库组成和配置的问题
> 
> 1. 我的知识库是下面这样的：
> 
> ```
> # 问题1
> 
> ## 问题
> XXX
> 
> ## 回答
> XXX
> 
> #问题2
> 
> ## 问题
> XXX
> 
> ## 回答
> XXX
> ```
> 
> text splitter 算法用MarkdownHeaderTextsplitter，可以将不同的问答对，QA1，QA2切分为不同的向量。
> 
> 实际提问问题1的时候，也确实能将答案1 检索出来，但回答的时候，没有完全按照答案1来回答，会加入一些编造的内容，这是我的模型推理能力不足吗？
> 
> 2. 配置的话，我是用4090显卡去跑的，现在用的模型是qwen-1.5-14B-chat 。

模型会添加自主成分的话，可以把这种模式下的温度调低，0.01或0.1之类的。

**Comment by zixiaotan21** [comment]
> > > 这大概率不是模型的问题，是你知识库组成和配置的问题
> > 
> > 
> > 
> > 1. 我的知识库是下面这样的：
> > 
> > ```
> > # 问题1
> > 
> > ## 问题
> > XXX
> > 
> > ## 回答
> > XXX
> > 
> > #问题2
> > 
> > ## 问题
> > XXX
> > 
> > ## 回答
> > XXX
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > text splitter 算法用MarkdownHeaderTextsplitter，可以将不同的问答对，QA1，QA2切分为不同的向量。
> > 实际提问问题1的时候，也确实能将答案1 检索出来，但回答的时候，没有完全按照答案1来回答，会加入一些编造的内容，这是我的模型推理能力不足吗？
> > 
> > 2. 配置的话，我是用4090显卡去跑的，现在用的模型是qwen-1.5-14B-chat 。
> 
> 模型会添加自主成分的话，可以把这种模式下的温度调低，0.01或0.1之类的。

谢谢建议！确实将temperature调低，效果会稍微好一点~
