### ISSUE TITLE
如何提高知识库问答的准确性

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#3882]
**问题描述 / Problem Description**
目前尝试了各种方法，知识库回答可以准确的检索到答案问答，但回答的准确性仍然不高。

**复现问题的步骤 / Steps to Reproduce**
尝试了如下方法：

1. 数据清洗
所有的QA文档转为markdown格式如下：
```
# 问题1

## 问题
XXX

## 回答
XXX

#问题2

## 问题
XXX

## 回答
XXX

``` 

2.优化text splitter 算法 

text splitter 算法 采用MarkdownHeaderTextsplitter，可以将不同的问答对，QA1，QA2切分为不同的向量。

疑问: 不太清楚是否将Q和A分开，把Q导入到向量库。只对Q进行向量匹配，根据相似度及TOP1过滤后，有结果则在关系数据库匹配A。这种QA分开处理的效果会更好？

3. 搜索匹配

top_K 设置为1， 实际知识库问答时，确实能匹配出答案所在的问答。

4. 优化LLM模型

1) prompt模板里加上“不要在答案里添加已知信息不存在的内容”，但似乎没有效果，模型还是会胡编。
2) temperature调低点，也没有太大效果。
3) LLM尝试过qwen 1.5-7b, 14b。14b效果略好。

@zRzRzRzRzRzRzR，维护者你好，目前上述方法都尝试过了，知识库回答效果仍不太理想，是否需要微调模型来提高准确性，或更换B值更大的LLM？谢谢！

**Comment by zixiaotan21** [comment]
@dosu

如何集成外部搜索引擎？

**Comment by zRzRzRzRzRzRzR** [comment]
因为超过4096 token了吧

**Comment by shushenghong** [comment]
我在尝试将每个问答转成独立一个markdown，然后控制在1000文字以内，再讲chunk size设置到1000，这样一个问答肯定就不会被拆分了
