### ISSUE TITLE
知识库没有多轮对话能力

### ISSUE THREAD

**Issue by loredunk** [chatchat-space/Langchain-Chatchat#3883]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/33904017/e84ebce2-6cc4-4e3b-9e3d-a403a1eb6971)

第一轮其实是已经检索到了相关的法律法规以及相关的案例chunk，但是第二轮对话中，检索到的相关的chunk都是与第一轮对话不相关的。就想没有记住第一轮的对话，这个怎么解决的？

**环境信息 / Environment Information**
- langchain-chain 0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu22.04
- Python 版本 / Python version: 3.11.9
- 其他相关环境信息 / Other relevant environment information:

**Comment by zixiaotan21** [comment]
同样关注这个问题，想问问楼主有解决吗？

**Comment by loredunk** [comment]
> 同样关注这个问题，想问问楼主有解决吗？

你用的llm大模型和embedding模型分别都是什么？具体型号？

**Comment by Wbbetty** [comment]
个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步

**Comment by loredunk** [comment]
> 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步

哈，这个需要手动去做吗？我本来以为是基础能力，感谢提醒

**Comment by zixiaotan21** [comment]
> 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步

我觉得有道理，直接将第二个问题抛给知识库搜索，确实会搜索不出来。当然langchain-chatchat 在设计中没有考虑这一点，确实不太智能～方不方便问问具体在knowledge_base_chat.py要如何修改呀？

**Comment by loredunk** [comment]
> To address the issue of incorporating conversation history into your queries with the langchain-chatchat library, you can modify the `knowledge_base_chat.py` file. Here's a concise guide on how to do it:
> 
> 1. **Format the Conversation History and Current Question:** Combine the history and the current question into a single string. This will be your enhanced query.
> 2. **Modify the Chat Handling Function:** In the function that handles the chat interaction (likely named `knowledge_base_chat` or similar), update it to concatenate the conversation history and the current question into one query string.
> 3. **Search the Knowledge Base with the Enhanced Query:** Use this concatenated string as the query for your knowledge base search. This should be done in the part of your code where you're calling a function to search the knowledge base, likely `search_knowledge_base_iter` or a similar function.
> 
> Here's a simplified code snippet to illustrate these steps:
> 
> ```python
> async def knowledge_base_chat(
>         query: str,
>         top_k: int,
>         history: Optional[List[History]],
>         model_name: str = "ChatGLM3-6B",
>         prompt_name: str = "knowledge_base_chat",
> ) -> AsyncIterable[str]:
>     # Concatenate history and current question
>     history_str = "\n".join([f"{h.role}: {h.content}" for h in history]) + f"\nUser: {query}"
>     
>     # Use the enhanced query for knowledge base search
>     contents = await search_knowledge_base_iter(
>         database="your_knowledge_base_name_here",
>         query=history_str,
>         model_name=model_name,
>         top_k=top_k,
>         prompt_name=prompt_name,
>     )
> 
>     # Return the search results
>     return contents
> ```
> 
> This approach ensures that the LLM uses both the conversation history and the current question for generating more contextually relevant search results from the knowledge base. Adjust the function names and parameters as needed to fit your specific implementation and file structure.
> 
> #### Details
> _To continue the conversation, mention @dosu._

你的这个代码有点奇怪

**Comment by Wbbetty** [comment]
> > 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步
> 
> 我觉得有道理，直接将第二个问题抛给知识库搜索，确实会搜索不出来。当然langchain-chatchat 在设计中没有考虑这一点，确实不太智能～方不方便问问具体在knowledge_base_chat.py要如何修改呀？

就是在docs = await run_in_threadpool之前插入一步，completed_query = await complete_query(query, history)，将后面步骤的query替换成补全后的complete_query，我不会python，实现的思路是这样的，然后chatgpt帮我写的

**Comment by zixiaotan21** [comment]
> > > 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步
> > 
> > 
> > 我觉得有道理，直接将第二个问题抛给知识库搜索，确实会搜索不出来。当然langchain-chatchat 在设计中没有考虑这一点，确实不太智能～方不方便问问具体在knowledge_base_chat.py要如何修改呀？
> 
> 就是在docs = await run_in_threadpool之前插入一步，completed_query = await complete_query(query, history)，将后面步骤的query替换成补全后的complete_query，我不会python，实现的思路是这样的，然后chatgpt帮我写的

好的好的，我试试看，谢谢啦！

**Comment by loredunk** [comment]
> > > > 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步
> > > 
> > > 
> > > 我觉得有道理，直接将第二个问题抛给知识库搜索，确实会搜索不出来。当然langchain-chatchat 在设计中没有考虑这一点，确实不太智能～方不方便问问具体在knowledge_base_chat.py要如何修改呀？
> > 
> > 
> > 就是在docs = await run_in_threadpool之前插入一步，completed_query = await complete_query(query, history)，将后面步骤的query替换成补全后的complete_query，我不会python，实现的思路是这样的，然后chatgpt帮我写的
> 
> 好的好的，我试试看，谢谢啦！

`        def history_list_to_str(history_list):
            result = ""
            for item in history_list:
                result += str(item) + "\n"
            return result + "\n这是以上我和你的对话记录，请参考\n" 
        if len(history):
            query  =  history_list_to_str(history) + query
        
        docs = await run_in_threadpool(search_docs,
                                       query=query,
                                       knowledge_base_name=knowledge_base_name,
                                       top_k=top_k,
                                       score_threshold=score_threshold)`
                                       
 我在knowledge_base_chat是这么加了简单的一串代码，的确包括了之前的对话和后面的query，聊胜于无把

**Comment by loredunk** [comment]
> > > > 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步
> > > 
> > > 
> > > 我觉得有道理，直接将第二个问题抛给知识库搜索，确实会搜索不出来。当然langchain-chatchat 在设计中没有考虑这一点，确实不太智能～方不方便问问具体在knowledge_base_chat.py要如何修改呀？
> > 
> > 
> > 就是在docs = await run_in_threadpool之前插入一步，completed_query = await complete_query(query, history)，将后面步骤的query替换成补全后的complete_query，我不会python，实现的思路是这样的，然后chatgpt帮我写的
> 
> 好的好的，我试试看，谢谢啦！

```
        def history_list_to_str(history_list):
            result = ""
            for item in history_list:
                result += str(item) + "\n"
            return result + "\n这是以上我和你的对话记录，请参考\n" 
        if len(history):
            query  =  history_list_to_str(history) + query
        
        docs = await run_in_threadpool(search_docs,
                                       query=query,
                                       knowledge_base_name=knowledge_base_name,
                                       top_k=top_k,
                                       score_threshold=score_threshold)
```

我在knowledge_base_chat是这么加了简单的一串代码，的确包括了之前的对话和后面的query，聊胜于无把

**Comment by zixiaotan21** [comment]
> def history_list_to_str(history_list):
>             result = ""
>             for item in history_list:
>                 result += str(item) + "\n"
>             return result + "\n这是以上我和你的对话记录，请参考\n" 
>         if len(history):
>             query  =  history_list_to_str(history) + query

我刚刚按你的方法尝试了一下，也成功了，现在知识库多轮对话没问题啦，谢谢楼主!

**Comment by jersonal** [comment]
> > > > > 个人理解的是，应该先将上下文的历史消息+问题投喂给大模型，让大模型将问题补充完整 “有没有广告中包含饮酒情节导致违法的案件摘要”，再去知识库中检索，才能从知识库检索出相关的案件，直接“有没有相关案件摘要”拿去知识库检索是检索不出来东西的，我是在knowledge_base_chat.py加的这一步
> > > > 
> > > > 
> > > > 我觉得有道理，直接将第二个问题抛给知识库搜索，确实会搜索不出来。当然langchain-chatchat 在设计中没有考虑这一点，确实不太智能～方不方便问问具体在knowledge_base_chat.py要如何修改呀？
> > > 
> > > 
> > > 就是在docs = await run_in_threadpool之前插入一步，completed_query = await complete_query(query, history)，将后面步骤的query替换成补全后的complete_query，我不会python，实现的思路是这样的，然后chatgpt帮我写的
> > 
> > 
> > 好的好的，我试试看，谢谢啦！
> 
> ```
>         def history_list_to_str(history_list):
>             result = ""
>             for item in history_list:
>                 result += str(item) + "\n"
>             return result + "\n这是以上我和你的对话记录，请参考\n" 
>         if len(history):
>             query  =  history_list_to_str(history) + query
>         
>         docs = await run_in_threadpool(search_docs,
>                                        query=query,
>                                        knowledge_base_name=knowledge_base_name,
>                                        top_k=top_k,
>                                        score_threshold=score_threshold)
> ```
> 
> 我在knowledge_base_chat是这么加了简单的一串代码，的确包括了之前的对话和后面的query，聊胜于无把

感谢楼主提供的思路，对于这种方法修改后有2个疑问想跟您请教一下：1.search_docs的时候query无关信息过大，是否会影响检索效果；2.与LLM对话时history和query都携带了历史对话记录，增加了prompt的复杂度，会有更大的上下文信息。

**Comment by xunshuoyang** [comment]
> > def history_list_to_str(history_list):
> > result = ""
> > for item in history_list:
> > result += str(item) + "\n"
> > return result + "\n这是以上我和你的对话记录，请参考\n"
> > if len(history):
> > query  =  history_list_to_str(history) + query
> 
> 我刚刚按你的方法尝试了一下，也成功了，现在知识库多轮对话没问题啦，谢谢楼主!
knowledge_base_chat在哪里啊

**Comment by ShirleyJi-gitub** [comment]
> > def history_list_to_str(history_list):
> > result = ""
> > for item in history_list:
> > result += str(item) + "\n"
> > return result + "\n这是以上我和你的对话记录，请参考\n"
> > if len(history):
> > query  =  history_list_to_str(history) + query
> 
> 我刚刚按你的方法尝试了一下，也成功了，现在知识库多轮对话没问题啦，谢谢楼主!

![Image](https://github.com/user-attachments/assets/94bbde19-7662-4433-8836-028b331ff625)
我的加了同样的代码，但是报错

![Image](https://github.com/user-attachments/assets/cf296365-ebf1-46b2-975c-de61881e835e)
是加的位置不对吗

**Comment by dtiosd** [comment]
> > > def history_list_to_str（history_list）： result = “” 对于history_list中的项目： result += str（item） + “\n” return result + “\n这是以上我和你的对话记录，请参考\n” if len（history）： query = history_list_to_str（history） + query
> > 
> > 
> > 我刚刚按你的方法尝试了一下，也成功了，现在知识库多轮对话没问题啦，谢谢楼主!
> 
> ![Image](https://github.com/user-attachments/assets/94bbde19-7662-4433-8836-028b331ff625)我的加了同样的代码，但是报错
> 
> ![Image](https://github.com/user-attachments/assets/cf296365-ebf1-46b2-975c-de61881e835e)是加的位置不对吗

@ShirleyJi-gitub 错误是因为在 knowledge_base_chat_iterator 函数内部尝试使用 query 变量，但 Python 将其视为局部变量而非外部作用域的变量。需要在在内部函数中声明 query 为 nonlocal，才可以访问外部函数的 query 参数。

![Image](https://github.com/user-attachments/assets/d154617d-48e6-4c07-acca-22bc7b243cd0)

![Image](https://github.com/user-attachments/assets/f2e2bb41-1957-47fc-a6a4-93b73bf6e493)
