### ISSUE TITLE
[BUG] 项目提供的openai兼容接口，访问向量化模型时模型名字需要填正在运行的LLM名字

### ISSUE THREAD

**Issue by mrkingsun** [chatchat-space/Langchain-Chatchat#3888]
例如，项目运行LLM是chatglm3-6b，向量化模型是m3e-base。用postman尝试调用向量化模型的接口时（ip:port/v1/embeddings），发现model名字一定要填写chatglm3-6b。填写m3e-base时返回“只有chatglm3-6b允许调用”。

**Comment by zRzRzRzRzRzRzR** [comment]
一定要是现在运行的模型才行

**Comment by mrkingsun** [comment]
> 一定要是现在运行的模型才行

LLM模型是需要运行的，这没问题。但是向量模型接口调用，model名字不应该写LLM的名字吧？
