### ISSUE TITLE
支持多模态大模型需要做的修改

### ISSUE THREAD

**Issue by dorameng2023** [chatchat-space/Langchain-Chatchat#3891]
**功能描述 / Feature Description**
支持多模态大模型，例如chatgpt4v 或者qwen-vl，以及视觉embedding模型，例如multimodal-embedding-one-peace-v1
**解决的问题 / Problem Solved**
实现图片问答&定位功能

**实现建议 / Implementation Suggestions**
请问如果想要实现该功能，现有版本具体需要做哪些改动

**Comment by zRzRzRzRzRzRzR** [comment]
那需要修改的太多了，从模型载入和langchain支持都得改，而且目前embed没办法支持多模态，比较好的方式是做成tools

**Comment by dorameng2023** [comment]
能不能展开说一下做成tools具体指的是什么 多谢

**Comment by dorameng2023** [comment]
@zRzRzRzRzRzRzR 能不能展开说说做成tools指的是什么 多谢
