### ISSUE TITLE
[FEATURE] 我需要在检索milvus向量库的时候返回pk字段，目前langchain_community最新版本把pk字段的返回移除了

### ISSUE THREAD

**Issue by zhoufurong2022** [chatchat-space/Langchain-Chatchat#3893]
**功能描述 / Feature Description**
langchain_community/vectorstores/milvus.py中self.col.search时传入的output_fields不希望将primary_field字段的返回remove

**解决的问题 / Problem Solved**
后期返回我需要用pk字段做文档还原

**实现建议 / Implementation Suggestions**
保持原来的
        output_fields = self.fields[:]
        output_fields.remove(self._vector_field)
或者支持该参数返回的控制

**Comment by zRzRzRzRzRzRzR** [comment]
用旧的版本， 我们应该有指定版本

**Comment by Wangzhongxi** [comment]
> 用旧的版本， 我们应该有指定版本

指定的是哪个版本呢
