### ISSUE TITLE
知识匹配分数阈值应该怎么设置？

### ISSUE THREAD

**Issue by blackwhites** [chatchat-space/Langchain-Chatchat#3895]
我生成好了知识库 用了bge-large-zh 这个向量数据库，我的Temperature设置为0.1当我设置了阈值0.7招回不了数据，选择0.4就招回啦数据，这个阈值是怎么设置的？

**Comment by zRzRzRzRzRzRzR** [comment]
Temperature 根数据库没有关系啊？
