### ISSUE TITLE
[BUG] 简洁阐述问题 /怎么加载ChatGLM-6B微调出来的模型

### ISSUE THREAD

**Issue by LGghost** [chatchat-space/Langchain-Chatchat#3897]
**问题描述 /怎么加载ChatGLM-6B微调出来的模型**

你好，我现在通过[ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B)的chatglm-6b模型在加上自己的数据微调出了一个adgen-chatglm-6b-pt-45，我现在想吧这个也使用到[Langchain-Chatchat上来，请问我需要这么修改

**Comment by LGghost** [comment]
好的，请问我该这么把[ChatGLM-6B](https://github.com/THUDM/ChatGLM-6B)的chatglm-6b模型在这个上面使用

**Comment by LGghost** [comment]
自己微调的数据

**Comment by zRzRzRzRzRzRzR** [comment]
查看wiki
