### ISSUE TITLE
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by oymclihui** [chatchat-space/Langchain-Chatchat#3898]
D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
2024-04-26 16:03:56,433 - embeddings_api.py[line:39] - ERROR: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\chatglm_ai\Langchain-Chatchat\models\bge-large-zh-v1.5'.
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 269, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    await func()
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 215, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 535, in receive
    await self.message_event.wait()
  File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 1e0781cd090

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 407, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\applications.py", line 119, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
  |     raise exc
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 762, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 782, in app
  |     await route.handle(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 297, in handle
  |     await self.app(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 77, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\routing.py", line 75, in app
  |     await response(scope, receive, send)
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 255, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 258, in wrap
    |     await func()
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\sse_starlette\sse.py", line 245, in stream_response
    |     async for data in self.body_iterator:
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\chat\knowledge_base_chat.py", line 81, in knowledge_base_chat_iterator
    |     docs = await run_in_threadpool(search_docs,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    |     return await anyio.to_thread.run_sync(func, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "D:\ProgramData\anaconda3\envs\langchainChatchat\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\knowledge_base\kb_doc_api.py", line 38, in search_docs
    |     docs = kb.search_docs(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 182, in search_docs
    |     docs = self.do_search(query, top_k, score_threshold)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\knowledge_base\kb_service\faiss_kb_service.py", line 66, in do_search
    |     embeddings = embed_func.embed_query(query)
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\chatglm_ai\Langchain-Chatchat\server\knowledge_base\kb_service\base.py", line 443, in embed_query
    |     query_embed = embeddings[0]
    |                   ~~~~~~~~~~^^^
    | TypeError: 'NoneType' object is not subscriptable
    +------------------------------------
2024-04-26 16:03:56,467 - utils.py[line:197] - ERROR: RemoteProtocolError: API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**Comment by danny-zhu** [comment]
根据你提供的报错信息的头部错误提示：2024-04-26 16:03:56,433 - embeddings_api.py[line:39] - ERROR: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'D:\chatglm_ai\Langchain-Chatchat\models\bge-large-zh-v1.5'.
ERROR: Exception in ASGI application

看起来是model_config中配置的EMBEDDING_MODEL模型文件id有问题，检查一下路径，模型目录文件下级文件或者目录是否有缺失。
