### ISSUE TITLE
[BUG] Moss模型问答，RuntimeError: probability tensor contains either inf, nan or element < 0

### ISSUE THREAD

**Issue by JovenChu** [chatchat-space/Langchain-Chatchat#390]
**问题描述 / Problem Description**
在使用moss的时候，成功加载了模型和文件，但是提问的时候出现【RuntimeError: probability tensor contains either inf, nan or element < 0】的报错
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/26185132/189bdce3-a0a2-4b09-b13c-23c85fdd8c60)

**尝试解决**
有个issues的建议是去掉moss_llm.py中的【do_sample=True】，不报错但是卡着不动了～

**环境信息 / Environment Information**
- 2张V100S-32G显卡
- ubuntu18.04，云vscode
- transformers使用4.27.1、4.28.1
- 使用chatglm-6b正常问答

**Comment by mianzhiwj** [comment]
同样的问题

**Comment by dxysharon** [comment]
一样的问题

**Comment by jiangbossB** [comment]
+1 我是用adgen数据集训练后 加载后出现的问题

**Comment by perfece** [comment]
一样问题。
推理报错：**NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.**\n\n(probability tensor contains either `inf`, `nan` or element < 0)', 'error_code': 50001
