### ISSUE TITLE
[FEATURE] 上传知识文件的格式

### ISSUE THREAD

**Issue by scorpionfeng** [chatchat-space/Langchain-Chatchat#3906]
**功能描述 / Feature Description**
在'知识库管理',功能中上传'上传知识文件'时,上传文件内容的格式是什么样的?  如果是json文件,应该是使用什么样的属性?
目前有文件 [{'prompt':'test',message:'answer'}] 这样的内容格式的json文件,上传提示失败,请问要上传的文件的格式是什么样的?
并给出示例模板

**Comment by scorpionfeng** [comment]
if I want to upload a group answers ,what formatter shall I support?  is the below formatter right?
{
  "prompt": "test",
  "message": "answer"
},
{
  "prompt": "test2",
  "message": "answer2"
}

**Comment by zRzRzRzRzRzRzR** [comment]
嗯
