### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by starry-sky-domain** [chatchat-space/Langchain-Chatchat#3907]
**问题描述 / Problem Description**
开发者有没有验证过基于在线模型 Gemini 、Claude 的在线API调用？根本就跑不通。是拿来凑数的吗？
使用 Gemini 在线模型，调用 Gemini 接口的时候，直接就阻塞了。毫无反应。

**Comment by JesseXYF** [comment]
你是不是搭建的有什么问题，我搭建的在线模型 Gemini 还在正常使用

**Comment by JesseXYF** [comment]
邮件已收到，谢谢。
