### ISSUE TITLE
知识库回答输出提示词

### ISSUE THREAD

**Issue by sevenandseven** [chatchat-space/Langchain-Chatchat#3909]
用的chatglm3-6b模型，在知识检索过程中，输出内容会包含“您好，根据您的问题，我需要对已知信息进行进一步的扩充。以下是。。。”
"您好，根据您的问题，我可以回答您关于....."    

希望输出结果中，直接输出检索总结之后的内容，而不是输出提示词中的部分内容。

**Comment by zRzRzRzRzRzRzR** [comment]
你去prompt template换个模板，自己写模板
