### ISSUE TITLE
fastchat 服务如何使用，我想在其他平台使用，我私有的模型，应该如何填写

### ISSUE THREAD

**Issue by yumu7777777** [chatchat-space/Langchain-Chatchat#3914]
API endpoint URL如何写，貌似不是 http://ip:20000 de 服务

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/104643678/e782c70c-db05-4631-a11b-aacc51717357)

**Comment by yumu7777777** [comment]
Langchain-Chatchat 不是集成了fastchat吗？我看server_config.py 中提到的端口就是 20000啊，或者我应该在哪去找相关文档呢

**Comment by ghyaauoo** [comment]
如果model_worker配置端口没改的话，默认20002
