### ISSUE TITLE
启动失败，卡在模型加载前。

### ISSUE THREAD

**Issue by SeanWong17** [chatchat-space/Langchain-Chatchat#3920]
==============================Langchain-Chatchat Configuration==============================

2024-04-29 10:15:19,850 - startup.py[line:655] - INFO: 正在启动服务：
2024-04-29 10:15:19,850 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /data/wangshuo/LLM/Langchain-Chatchat/logs
/data/wangshuo/.miniconda3/envs/chat/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
![Uploading D2346601-86B2-4ad3-BBDC-F09D08B290A1.png…]()

**Comment by zRzRzRzRzRzRzR** [comment]
配置不够，或者模型位置没有指定，导致加载huggingface
