### ISSUE TITLE
如何构建prompt和history 能够让知识库检索回答按照选择题返回

### ISSUE THREAD

**Issue by misi0202** [chatchat-space/Langchain-Chatchat#3930]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): Qwen7B-Chat 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-m3
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
在使用知识库检索生成对话时，我希望使用模型生成单选题答案，且只生成答案，不做解释
我编辑了历史对话 为其加入两个标准的选择题回答
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/101965629/69ba2738-72e7-41bb-ace2-08fa564f4114)
并使用自定义的prompt模板
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/101965629/4633a312-9039-482e-b6dc-995e6ddaaf69)
但在回答时还是有部分回答 无法正确输出选项 其中大部分是无法找到知识库内容 小部分是找到知识库内容 但不输出选项 我该怎么做 提高标准问答的次数

**Comment by zRzRzRzRzRzRzR** [comment]
现在就是吧，知识库的时候历史的作用很弱，所以你只能在提示词模板哪指定严格按照知识库回答
