### ISSUE TITLE
[BUG] 在利用api创建微调任务的时候报错

### ISSUE THREAD

**Issue by DinnerMythology** [chatchat-space/Langchain-Chatchat#3939]
**问题描述 / Problem Description**
上传文件成功后，创建微调任务，返回报错
zhipuai.core._errors.APIInternalError: Error code: 500, with error text {"error":{"code":"400","message":"账户余额不足，冻结余额失败"}}，
但是我在控制台看账户还是有钱的，不知道为什么？？？金额是有最低限制吗？

**复现问题的步骤 / Steps to Reproduce**
'''
from zhipuai import ZhipuAI

client = ZhipuAI(api_key="")

job = client.fine_tuning.jobs.create(
    model="chatglm3-6b",
    training_file="file-20240502103429346-7wthh",
    validation_file="file-20240502103138505-b6wlr",
    suffix="jr_first",
)
job_id = job.id

print(job_id)
'''

**Comment by zRzRzRzRzRzRzR** [comment]
上传文件成功后，创建微调任务，返回报错
微调当然是另外收钱的，你用的是智谱的吧

**Comment by DinnerMythology** [comment]
> 上传文件成功后，创建微调任务，返回报错 微调当然是另外收钱的，你用的是智谱的吧

是的，微调的钱是跟智谱控制台分开的是吗
