### ISSUE TITLE
请问如何设置才可以从远程，比如手机端访问自己搭建的服务？

### ISSUE THREAD

**Issue by sunbird84** [chatchat-space/Langchain-Chatchat#3940]
感谢作者开发这么好用的东西。
似乎这个只能通过127这个地址来访问，连192这个IP地址都无法访问本地服务。
远程更是不可能。请问有没有办法解决这个问题呢？

**Comment by sunbird84** [comment]
多谢了。
我找到了server_config.py这个文件里的DEFAULT_BIND_HOST，已经是0.0.0.0.
我试图把下方的XX_SERVER改成0.0.0.0，但是运行后报错。
不知道是不是我找错地方了。

**Comment by sunbird84** [comment]
it's work! thank you @dosubot

**Comment by zRzRzRzRzRzRzR** [comment]
server config 设置ip访问地址

**Comment by juyuanjuyuan** [comment]
只需要改server_config.py里的DEFAULT_BIND_HOST吗，为什么我改完后跑python3 startup.py --all-webui 还是没有办法通过服务器的外部ip地址来访问网站？
