### ISSUE TITLE
向量知识库添加内容错误，但没有报错，显示为×

### ISSUE THREAD

**Issue by lceCre4m** [chatchat-space/Langchain-Chatchat#3941]
请问有大佬遇到这种情况吗？该怎么解决
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49328751/dc8c7f04-3599-4400-8cc4-4ec3365c4e54)
1、源文件和向量库都为×

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49328751/e101162f-6f9f-4b4b-ae1a-072bc00d937c)
2、检索上传过的文档一模一样的内容查找不到

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/49328751/27a5a9ef-02ef-4019-a7a6-9233fd4ba0e9)
3、对话一直为“未找到相关文档,该回答为大模型自身能力解答！”

**Comment by lceCre4m** [comment]
而且都启动和文档上传及添加向量数据库过程都没有报错

**Comment by zRzRzRzRzRzRzR** [comment]
能提问正常回答就是向量化了，否则后台会报错

**Comment by HanqiaoZheng** [comment]
> 能提问正常回答就是向量化了，否则后台会报错

不行，我也遇到同样问题了，回答知识库点开显示红色字体，未找到相关文档,该回答为大模型自身能力解答！

**Comment by HanqiaoZheng** [comment]
楼主解决了吗，我也遇到这个问题了

**Comment by mrkingsun** [comment]
我也遇到了，0.2.10版本，上传后源文件和向量库都是x，这什么bug？

**Comment by lwh8915** [comment]
我也遇到了，请问解决了吗

**Comment by ZG688** [comment]
我也遇到了 一点错误没有 就是找不到文档

**Comment by danny-zhu** [comment]
我这边也遇到相同的问题，可以试试把model_config中用的模型路径写完整就可以解决了。MODEL_ROOT_PATH这参数可能是有的地方没有自动拼接上，我还没来得及去逐行排查代码，你们遇到可以试试看。

**Comment by ZG688** [comment]
> 我这边也遇到相同的问题，可以试试把model_config中用的模型路径写完整就可以解决了。MODEL_ROOT_PATH这参数可能是有的地方没有自动拼接上，我还没来得及去逐行排查代码，你们遇到可以试试看。

model_config.py这个文件里面的模型路径绝对的相对的都能用，LLM问答里面没有问题，构建向量库也没有报错，就是知识库问答找不到相关文档，后台也没错误，成功加载向量库 麻了
![微信图片_20240527001417](https://github.com/chatchat-space/Langchain-Chatchat/assets/83052500/e20d644e-f913-404d-bb27-fecd150d519e)

**Comment by linlangq** [comment]
> > 我这边也遇到相同的问题，可以试试把model_config中用的模型路径写完整就可以解决了。MODEL_ROOT_PATH这参数可能是有的地方没有自动拼接上，我还没来得及去逐行排查代码，你们遇到可以试试看。
> 
> model_config.py这个文件里面的模型路径绝对的相对的都能用，LLM问答里面没有问题，构建向量库也没有报错，就是知识库问答找不到相关文档，后台也没错误，成功加载向量库 麻了 ![微信图片_20240527001417](https://private-user-images.githubusercontent.com/83052500/333893984-e20d644e-f913-404d-bb27-fecd150d519e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTMyNTUsIm5iZiI6MTcxNjk1Mjk1NSwicGF0aCI6Ii84MzA1MjUwMC8zMzM4OTM5ODQtZTIwZDY0NGUtZjkxMy00MDRkLWJiMjctZmVjZDE1MGQ1MTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAzMjIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTU4NTJjYjJkZjczYzM0YTVlNWQwNGEwY2JiMGIwNDEyODE2YmY5NTM5N2Y5OTRiZGM5MTM1ZDFlNjI3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9w6Cg1uTfUZMzqYtz1hbTT46ZzoUAV-om2OLbPv0mec)

问题解决了吗

**Comment by ReverseSystem001** [comment]
> > > 我这边也遇到相同的问题，可以试试把model_config中用的模型路径写完整就可以解决了。MODEL_ROOT_PATH这参数可能是有的地方没有自动拼接上，我还没来得及去逐行排查代码，你们遇到可以试试看。
> > 
> > 
> > model_config.py这个文件里面的模型路径绝对的相对的都能用，LLM问答里面没有问题，构建向量库也没有报错，就是知识库问答找不到相关文档，后台也没错误，成功加载向量库 麻了 ![微信图片_20240527001417](https://private-user-images.githubusercontent.com/83052500/333893984-e20d644e-f913-404d-bb27-fecd150d519e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTMyNTUsIm5iZiI6MTcxNjk1Mjk1NSwicGF0aCI6Ii84MzA1MjUwMC8zMzM4OTM5ODQtZTIwZDY0NGUtZjkxMy00MDRkLWJiMjctZmVjZDE1MGQ1MTllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAzMjIzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MTU4NTJjYjJkZjczYzM0YTVlNWQwNGEwY2JiMGIwNDEyODE2YmY5NTM5N2Y5OTRiZGM5MTM1ZDFlNjI3MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9w6Cg1uTfUZMzqYtz1hbTT46ZzoUAV-om2OLbPv0mec)
> 
> 问题解决了吗

哥们，问题解决了吗？
