### ISSUE TITLE
在prompt_config.py里加内容后模型有时不能准确执行prompt

### ISSUE THREAD

**Issue by goodmaney** [chatchat-space/Langchain-Chatchat#3942]
我这样写的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25651447/abd43aeb-c297-4bff-9f71-8d53fa8227ee)
生成内容有时我输入你好后它会提示我继续输入基础信息，有时直接就生成一篇文章模板
模型试过ChatGLM3-6B和Yi-34B-int4，Temperature试过从0.1、0.5、0.7、1.0，都有概率出现这样的情况。

**Comment by zRzRzRzRzRzRzR** [comment]
你的模板没对吧， system 你要填入什么呢
input是会被替换成你的问题的

这个框架没做system角色
