### ISSUE TITLE
[FEATURE] 增加问题的向量化和排名靠前的本地向量模型

### ISSUE THREAD

**Issue by chuanSir123** [chatchat-space/Langchain-Chatchat#3945]
**功能描述 / Feature Description**
加问题的向量化和排名靠前的本地向量模型

**解决的问题 / Problem Solved**
目前我用qwen-api对知识库进行向量化后，后续的提问并不会向量化（没有访问qwen-api），不清楚是怎么做到精准的向量比对和score排序的

**实现建议 / Implementation Suggestions**
创建知识库时把每行数据进行向量化存库，查询知识库时，先对问题进行量化，然后向量比对得出知识库数据和分数。
本地向量化模型排行：https://huggingface.co/spaces/mteb/leaderboard

**Comment by zRzRzRzRzRzRzR** [comment]
一次向量化之后就不会了，后续都是召回，会调用模型进行召回

**Comment by chuanSir123** [comment]
> 召回

多谢解答，继续问下这个没有向量索引么，那一开始的一次性向量化有什么用呢（小白的理解是使用相同的模型对知识库和问题进行向量化才能够比对）
