### ISSUE TITLE
我在Fastchat中依照说明添加了一款新的大模型，如何将其更新到此框架中，使我可以在此框架中使用

### ISSUE THREAD

**Issue by xiaoma444** [chatchat-space/Langchain-Chatchat#3946]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by zRzRzRzRzRzRzR** [comment]
可以仿写我们的model_worker 写

**Comment by xiaoma444** [comment]
我看到过pull  claude这个模型的代码修改，一共要改的那几个文件也都有。但是我想通过chatglm3-6b这种改地址的方式就不可以是吧，一定要用ONLINE_LLM_MODEL中模型调用的方法吗？
