### ISSUE TITLE
启动之后，打开web界面只能显示输入框，其它前端页面不显示

### ISSUE THREAD

**Issue by 12wjj** [chatchat-space/Langchain-Chatchat#3948]
![QIOE4(X}H1O I1C2`1197XI](https://github.com/chatchat-space/Langchain-Chatchat/assets/107795264/06a4c6fa-506a-4044-8300-78d469699530)

**Comment by zRzRzRzRzRzRzR** [comment]
检查你的nginx或者streamlit bug，非框架问题
