### ISSUE TITLE
> 这个问题我也碰到了，api可以调用，但是webui服务一直有问题，本来以为是端口没开，后来在云服务器上把端口也开了还是不行，最后把自己的email地址输入进去就行了，有点无语

### ISSUE THREAD

**Issue by wang199395** [chatchat-space/Langchain-Chatchat#3953]
> 这个问题我也碰到了，api可以调用，但是webui服务一直有问题，本来以为是端口没开，后来在云服务器上把端口也开了还是不行，最后把自己的email地址输入进去就行了，有点无语

你好，请问这个邮箱在哪填

_Originally posted by @sh66666 in https://github.com/chatchat-space/Langchain-Chatchat/issues/2705#issuecomment-2084007845_
          同问，邮箱地址在哪填？

**Comment by zRzRzRzRzRzRzR** [comment]
随便填一个
