### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by albertyou2** [chatchat-space/Langchain-Chatchat#3954]
请问如何配置本地的嵌入模型啊？我的服务器无法连接国外服务器所以，手动下载了模型传到服务器上。

**配置的嵌入模型路径**
MODEL_ROOT_PATH = "models/embedding_models/"
EMBEDDING_MODEL = "bge-large-zh-v1.5"

**实际存放路径：**
models/embedding_models/bge-large-zh-v1.5/里面就是模型全部文件了

**# 选用的reranker模型，默认的，这个模型没有下载**
RERANKER_MODEL = "bge-reranker-large"

总是报错。请问有没有人，正确的下载了本地嵌入模型并跑起来的？

**Comment by zRzRzRzRzRzRzR** [comment]
直接换成绝对路径吧

**Comment by albertyou2** [comment]
两种方法都试过了，就是无法读取这个模型
1 在MODEL_PATH中配置绝对路径：
MODEL_PATH = {
    "embed_model": {
        "bge-large-zh-v1.5": "/data/Langchain-Chatchat-master/BAAI/bge-large-zh-v1.5", # 保证路径存在

2 在MODEL_ROOT_PATH 配置也是绝对路径
MODEL_ROOT_PATH = "/data/Langchain-Chatchat-master/BAAI"
EMBEDDING_MODEL = "bge-large-zh-v1.5"

我是从https://hf-mirror.com/下载的模型，不知道有没有影响
