### ISSUE TITLE
未找到相关文档,该回答为大模型自身能力解答！

### ISSUE THREAD

**Issue by Odeliaws** [chatchat-space/Langchain-Chatchat#3959]
**问题描述 / Problem Description**
将需要添加的文档放入knowledge_base/samples/content/test_files里之后，初始化知识库和配置文件，一键启动。模型回答了问题，但是出现：未找到相关文档,该回答为大模型自身能力解答！

**复现问题的步骤 / Steps to Reproduce**
1. 将需要添加的文档放入knowledge_base/samples/content/test_files里
2. 初始化知识库和配置文件：`python copy_config_example.py`，`python init_database.py --recreate-vs`
3. 一键启动：`python startup.py -a`
4. 模型回答了问题，但是末尾出现：未找到相关文档,该回答为大模型自身能力解答！

**预期的结果 / Expected Result**
模型回答问题，不会出现：未找到相关文档,该回答为大模型自身能力解答！

**实际结果 / Actual Result**
“模型的回答…………………………     未找到相关文档,该回答为大模型自身能力解答！”

**环境信息 / Environment Information**
- langchain-ChatGLM 版本：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Baichuan2-7B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：text2vec-large-chinese
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本：Debian，bookworm/sid
- Python 版本：Python 3.10.8

**Comment by ZG688** [comment]
解决了吗楼主，我也是同样的问题，不报错，源文件和向量库显示×，知识库问答未找到相关文档

**Comment by TZJ12** [comment]
> 解决了吗楼主，我也是同样的问题，不报错，源文件和向量库显示×，知识库问答未找到相关文档

同问

**Comment by Alan-zhong** [comment]
解决了吗

**Comment by liunux4odoo** [comment]
把配置项里的 score_threashold 调高一些试，比如 2.0

**Comment by puppy-tyq** [comment]
解决了吗楼主，我也是同样的问题，不报错，源文件和向量库显示✔，知识库问答未找到相关文档

**Comment by zhuheng-mark** [comment]
我也遇到了类似问题，检索文档是成功的，但是大模型回答"根据已知信息无法回答该问题"。
修改score_threashold （config/kb_config.py 里面的SCORE_THRESHOLD参数）为 2 后回答正确。

**Comment by Alan-zhong** [comment]
> 我也遇到了类似问题，检索文档是成功的，但是大模型回答"根据已知信息无法回答该问题"。 修改score_threashold （config/kb_config.py 里面的SCORE_THRESHOLD参数）为 2 后回答正确。

我是换个embeeding模型就行了

**Comment by Longbaoxu** [comment]
> > 我也遇到了类似问题，检索文档是成功的，但是大模型回答"根据已知信息无法回答该问题"。 修改score_threashold （config/kb_config.py 里面的SCORE_THRESHOLD参数）为 2 后回答正确。
> 
> 我是换个embeeding模型就行了

换的什么模型呀
