### ISSUE TITLE
知识库检索的代码

### ISSUE THREAD

**Issue by misi0202** [chatchat-space/Langchain-Chatchat#3964]
我想修改一下知识库检索的代码 因为目前的召回率比较差 想改为混合检索的方式 请问在哪个位置
好像0.1版本的检索是根据上下文的，请问一下代码位置 想做参考
还有注意到0.3.x版本有改进这个检索模式的想法 问一下什么时候能上线呢

**Comment by AMAG-AB** [comment]
@DosuBot 混合检索和父子级文档召回，应该在哪里添加？可以通过修改项目代码实现吗

**Comment by Shujie-Wu** [comment]
请问您找到优化召回算法部分的代码了吗，在哪个文集可以分享一下吗
