### ISSUE TITLE
感觉知识库问答的逻辑很奇怪，不支持追问

### ISSUE THREAD

**Issue by e68862230** [chatchat-space/Langchain-Chatchat#3980]
**问题描述 / Problem Description**
我问关键词“实验室”有哪些人，它可以回答，但是我追问说xxx是做什么的，它就无法查询到答案。。

**预期的结果 / Expected Result**
正常不是应该它带着人名和上下文中的实验室这个关键词一起去查找么

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v2.0.1
- 是否使用 Docker 部署：是 
- 使用的模型：Qwen-14B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：milvus
- 操作系统及版本 / Operating system and version:Ubuntu

**Comment by lr13953301387** [comment]
你有试过从api里调用么？ 我看他api里 knowledgebasechat里是有history这一项的

**Comment by e68862230** [comment]
> 你有试过从api里调用么？ 我看他api里 knowledgebasechat里是有history这一项的
没试过，只用了webui的，但是上面好像也有历史对话选项的也开启了

**Comment by e68862230** [comment]
> 你有试过从api里调用么？ 我看他api里 knowledgebasechat里是有history这一项的

都是webui上面试的，历史会话也打开了

**Comment by xiaohundun** [comment]
看`knowledge_base_chat.py`这个文件的实现，这块没做好，正常情况下应该要根据历史会话去向大模型获取新的向量查询 query 的，但是现在看代码只是拿当前用户的 query 去查的，跟上下文没关系，可以自己改一下

**Comment by mazisuki** [comment]
有人实现了吗，用了下确实效果很差
