### ISSUE TITLE
pip安装jq包 和启动

### ISSUE THREAD

**Issue by shusuxiang** [chatchat-space/Langchain-Chatchat#3983]
![c474b43465bc3b0cd2043b09f5da9bdb](https://github.com/chatchat-space/Langchain-Chatchat/assets/106244328/79fd81d9-58e1-4a45-a4c7-beae22f9c226)
![1715312241071](https://github.com/chatchat-space/Langchain-Chatchat/assets/106244328/b4015cac-754b-4912-8e33-707fcd2244d7)

**Comment by zRzRzRzRzRzRzR** [comment]
windows的安装方法要用conda

**Comment by Hiroshi230** [comment]
> windows的安装方法要用conda

我condalist里面安装成功jq，pip无法安装，但是startup启动的时候，仍然会报缺少jq库，我看到有人用jsonloader来解决，请问下要在代码哪个地方改动？
![1715743984746](https://github.com/chatchat-space/Langchain-Chatchat/assets/70248533/8c5e5ad6-a4e0-4850-b6af-359ad685dad2)
