### ISSUE TITLE
如何加载自定义embedding模型

### ISSUE THREAD

**Issue by WSC741606** [chatchat-space/Langchain-Chatchat#3987]
@dosu-bot
我希望使用Alibaba-NLP/gte-large-en-v1.5作为embedding模型，我需要如何修改model_config.py？我已经从HF下载了该模型，或者由程序自动从HF下载也可以

**Comment by WSC741606** [comment]
@dosu，上述操作后报错kb_api.py[line:34] - ERROR: TypeError: 创建知识库出错： loop of ufunc does not support argument 0 of type NoneType which has no callable conjugate method

**Comment by PaoBuDongYu** [comment]
@WSC741606 请问解决了吗？

**Comment by WSC741606** [comment]
> @WSC741606 请问解决了吗？

@PaoBuDongYu 没有解决，后来发现这个embedding模型不适合我这边的目标场景，就放弃了
