### ISSUE TITLE
向量化数据库使用中的一些问题

### ISSUE THREAD

**Issue by hepj987** [chatchat-space/Langchain-Chatchat#3991]
请问一下我再初始化向量数据库的时候成功了，
脚本如下：python init_database.py --recreate-vs
其中使用了默认配置，只在model_config.py中修改了MODEL_ROOT_PATH = "/public/RAG/model"为我的本地模型路径，以及bge-large-zh-v1.5为我对应的保存路径
"bge-large-zh-v1.5": "AI-ModelScope/bge-large-zh"
初始化向量数据库显示成功：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/117699100/0432e997-6272-42a7-b9bf-27c88d2b1363)

LLM模型问答服务正常，但是在使用知识库的时候一直查询不到知识库。
对比官方的展示图片发现问题，在管理页面中虽然可以看到初始化的数据文件，但是源文件和向量库 都是 × 而不是 √。不知道是哪里出了问题？
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/117699100/3c7da929-b3ad-4f47-98b1-85e38a873450)
并且选中其中一个文件以后报如下错误：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/117699100/ff97ada8-703a-4b14-82ef-cca4a8a0ce3d)

请问大家在使用中是否遇到同样的问题，是怎么解决的

**Comment by hepj987** [comment]
向量数据库添加文件失败只是显示问题，修改202 203行的替换操作以后 结果显示正常。
但是还是存在向量数据库匹配不到的问题，更换vs.similarity_search_with_score_by_vector(embeddings, k=top_k, score_threshold=score_threshold)为docs=vs.similarity_search_with_score(query)打印可以看到分数都在100以上
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/117699100/04e7f6d1-e743-468e-9f86-65c4d9c4fca5)

**Comment by Zhaitizi** [comment]
同样问题，一直不知道大家说的202.203行在哪里，找不到knowledge_base.py文件，求大佬们指点

**Comment by ZG688** [comment]
大佬解决了吗？同样显示×知识库问答检索不到文档

**Comment by ZG688** [comment]
> 同样问题，一直不知道大家说的202.203行在哪里，找不到knowledge_base.py文件，求大佬们指点
langchain-ChatGLM\webui_pages\knowledge_base 这个目录下，文档搜一下也能搜到

**Comment by zixiaotan21** [comment]
同样有这个问题，想问问vs.similarity_search_with_score_by_vector(embeddings, k=top_k, score_threshold=score_threshold)为docs=vs.similarity_search_with_score(query) 这行代码是在哪个文件下面呀，谢谢！

**Comment by wll0307** [comment]
我是的知识库库可以查询但是我的管理页面上面源文件和向量库显示X
