### ISSUE TITLE
支持模型问答与检索问答

### ISSUE THREAD

**Issue by dywlegend1002** [chatchat-space/Langchain-Chatchat#401]
不同的query，根据意图不一致，回答也应该不一样。

比如：你好 

如果走检索的话，可以检索到最近的文本就是介绍三国演义的，这样会造成回答会基于检索内容进行生成，这样就有问题了～

**Comment by cindymuji** [comment]
检索时应该把相关的文档尽可能都返回，至于不同query，不同意图，丢个模型自己去生成。如果走意图拆分，不就又回到传统的问答流程上了？
