### ISSUE TITLE
[BUG] reranker.py 加载模型时输入长度传入错误

### ISSUE THREAD

**Issue by blizzardwj** [chatchat-space/Langchain-Chatchat#4016]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/19178835/d53368d4-d87e-4d2d-897f-cada4e5a4b84)

应该由`1024`改为`max_length`，否则会造成rerank模型predict长度过长的文本时出错。

**Comment by web3aipro** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/166089210/b5c4efd7-e5f8-4955-bf81-654f05462207)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/166089210/9e1f77eb-4903-4731-af1b-192d0da311a4)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/166089210/aa4f7f27-29c9-465e-a253-e4fa434e4e5d)
这么改了，还是报图1错误

**Comment by 309283175** [comment]
这个原因是reranker模型本身的限制，你这个模型最大支持514个长度，换个支持更长的reranker模型即可

**Comment by blizzardwj** [comment]
> 报得错： ![image](https://private-user-images.githubusercontent.com/166089210/330344897-b5c4efd7-e5f8-4955-bf81-654f05462207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjE2MTYsIm5iZiI6MTcxNTc2MTMxNiwicGF0aCI6Ii8xNjYwODkyMTAvMzMwMzQ0ODk3LWI1YzRlZmQ3LWU1ZjgtNDk1NS1iZjgxLTY1NGYwNTQ2MjIwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwODIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYjZmNjdhYTdmNjRjZDY3MDI2NjU3NGVhMTkxNDdhNjkwNTM3YTk0ZGFlMDAwYjNhYTc0YTVlMjViOWU5MzcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KrDlgkR353jN94qH9UClmxm-PBgofqBTvfXgcZuXKb8) 配置文件里面配置： ![image](https://private-user-images.githubusercontent.com/166089210/330344953-9e1f77eb-4903-4731-af1b-192d0da311a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjE2MTYsIm5iZiI6MTcxNTc2MTMxNiwicGF0aCI6Ii8xNjYwODkyMTAvMzMwMzQ0OTUzLTllMWY3N2ViLTQ5MDMtNDczMS1hZjFiLTE5MmQwZGEzMTFhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwODIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDMwZmY5YTEzNWMwMjJhNDZkODZmZWVmZTQzODg4YTUyOGJjMmQyZjZjZmI0MDkxMjY1N2I4NzVmNjVlNTI4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.96MLBYdOd5JrhSDmDhaGuIacChZi3EC4OZy4R01zblA) rerank文件得配置： ![image](https://private-user-images.githubusercontent.com/166089210/330345048-aa4f7f27-29c9-465e-a253-e4fa434e4e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NjE2MTYsIm5iZiI6MTcxNTc2MTMxNiwicGF0aCI6Ii8xNjYwODkyMTAvMzMwMzQ1MDQ4LWFhNGY3ZjI3LTI5YzktNDY1ZS1hMjUzLWU0ZmE0MzRlNGU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQwODIxNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDczNjk4MTlkZDVjOTc1MDk2YmQ5MzRiMmUyYjZjOTRiMjU4OGI5MTA5Y2E3NWQ1ZTgwOTM4YjBlYTU4ZmZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pERdcPmzSEpdMT4P7yPeGlCK-TF6EcN2wk5txL0v-3w) 这么改了，还是报图1错误

`RERANKER_MAX_LENGTH = 512`，这是模型的输入限制，1024超出了。

**Comment by web3aipro** [comment]
开源的reranker模型都是1024，是不是只能做截断啊
