### ISSUE TITLE
[BUG] 知识问答报错：API通信遇到错误

### ISSUE THREAD

**Issue by linaiyue** [chatchat-space/Langchain-Chatchat#4023]
**问题描述 / Problem Description**
知识库问答，出现API通信错误，检索条目3变成1条也出错

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '$ python startup.py -a'
2. 点击 '知识库问答'
3. 输入问题
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
能正确检索文档

**实际结果 / Actual Result**
API通信遇到错误：peer closed connection without sending complete message body (incomplete chunked read)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.0.354. fastchat版本：0.2.35
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5 @ cuda
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: Linux-5.15.136-tegra-aarch64-with-glibc2.35
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:  cuda 12.1

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
[log.txt](https://github.com/chatchat-space/Langchain-Chatchat/files/15319318/log.txt)

**Comment by danny-zhu** [comment]
把知识检索结果排序功能禁用掉（USE_RERANKER = False）就不会报这个错了，我看报错日志在排序过程中报错了
