### ISSUE TITLE
自定义Agent问答调用知识库时返回'BaseResponse' object has no attribute 'body_iterator'

### ISSUE THREAD

**Issue by li775176364** [chatchat-space/Langchain-Chatchat#4024]
自定义Agent问答模式下，调用search_knowledgebase_complex搜索知识库，始终返回'BaseResponse' object has no attribute 'body_iterator'

```
工具名称: search_knowledgebase_complex
工具状态: 调用成功
工具输入: MacbookAir M1 8+256 颜色
工具输出:  输入的信息有误或不存在知识库,错误信息如下:
'BaseResponse' object has no attribute 'body_iterator'
```

我把包含上述信息的文档存为.txt，添加到了我新建的知识库test1中，直接使用知识库问答是可以查到信息的，但是在Agent下查不到任何信息

**Comment by li775176364** [comment]
问答对话是这样的
<img width="748" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/129644604/f6d4d613-a728-40fa-bf7f-e9d51a9a637f">

**Comment by ReverseSystem001** [comment]
> 问答对话是这样的 <img alt="image" width="748" src="https://private-user-images.githubusercontent.com/129644604/330753392-f6d4d613-a728-40fa-bf7f-e9d51a9a637f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3ODksIm5iZiI6MTcxNjQ1MTQ4OSwicGF0aCI6Ii8xMjk2NDQ2MDQvMzMwNzUzMzkyLWY2ZDRkNjEzLWE3MjgtNDBmYS1iZjdmLWU5ZDUxYTlhNjM3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzQxOGQ2NzM3NDIzNTY4NzZmNThhNjBmZDEyYjJkMTIyYTQzYTQ3YjhhZDM1MzM5NGRmMzYwNzFiY2Q4YzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XkaKclTjb1OVZg9XWTVGjp3G_sVd3Os-PIkDqv9hEZQ">
你那现在调用agent好使不，我这按照脚本里调用本地知识库直接回复：I need to use the search_knowledgebase_complex tool to search the knowledge base for information about bigdata and its employment情况.然后没下文了

**Comment by li775176364** [comment]
> > 问答对话是这样的 <img alt="image" width="748" src="https://private-user-images.githubusercontent.com/129644604/330753392-f6d4d613-a728-40fa-bf7f-e9d51a9a637f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTE3ODksIm5iZiI6MTcxNjQ1MTQ4OSwicGF0aCI6Ii8xMjk2NDQ2MDQvMzMwNzUzMzkyLWY2ZDRkNjEzLWE3MjgtNDBmYS1iZjdmLWU5ZDUxYTlhNjM3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwODA0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMzQxOGQ2NzM3NDIzNTY4NzZmNThhNjBmZDEyYjJkMTIyYTQzYTQ3YjhhZDM1MzM5NGRmMzYwNzFiY2Q4YzQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XkaKclTjb1OVZg9XWTVGjp3G_sVd3Os-PIkDqv9hEZQ">
> > 你那现在调用agent好使不，我这按照脚本里调用本地知识库直接回复：I need to use the search_knowledgebase_complex tool to search the knowledge base for information about bigdata and its employment情况.然后没下文了

没有，我到现在也没调通

**Comment by ReverseSystem001** [comment]
那你换的哪个代码库啊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月23日(周四) 下午4:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chatchat-space/Langchain-Chatchat] 自定义Agent问答调用知识库时返回'BaseResponse' object has no attribute 'body_iterator' (Issue #4024)




   
问答对话是这样的 
 你那现在调用agent好使不，我这按照脚本里调用本地知识库直接回复：I need to use the search_knowledgebase_complex tool to search the knowledge base for information about bigdata and its employment情况.然后没下文了
   
没有，我到现在也没调通
