### ISSUE TITLE
本地部署模型，启动error，Register to controller报错socket.gaierror: Name or service not known

### ISSUE THREAD

**Issue by yanli789** [chatchat-space/Langchain-Chatchat#4025]
**问题描述 / Problem Description**
http://127.0.0.1:20000启动error，Register to controller报错：
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /gpt-2/encodings/main/vocab.bpe (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f505ddc7e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
运行环境没有访问互联网权限，所有模型离线安装好，按理说不应该有访问互联网域名的情况，烦请大佬指导我的步骤和配置是哪里有问题，万分感激。

**复现问题的步骤 / Steps to Reproduce**
1.  安装好pg_vector后，运行python init_database.py --recreate-vs，提示添加到向量库成功。
2.  配置 kb_config.py里pg数据库地址
3.  配置model_config.py、server_config.py
4.  执行 python startup.py -a  就报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：Langchain-Chatchat v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-1_8B-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：pg_vector
- 操作系统及版本 / Operating system and version: Linux version 3.10.0-1160.el7.x86_64 
- Python 版本 / Python version: Python 3.10.9
- 其他相关环境信息 / Other relevant environment information: 
- transformers-4.37.2
- cuda_11.7.r11.7

# ### **model_config.py 配置如下：**

MODEL_ROOT_PATH = "/mnt"
EMBEDDING_MODEL = "bge-large-zh"
EMBEDDING_DEVICE = "cuda"
RERANKER_MODEL = "bge-reranker-large"

USE_RERANKER = False
RERANKER_MAX_LENGTH = 1024

EMBEDDING_KEYWORD_FILE = "keywords.txt"
EMBEDDING_MODEL_OUTPUT_PATH = "output"
LLM_MODELS = ["Qwen-1_8B-Chat"]
Agent_MODEL = None

LLM_DEVICE = "cuda"
HISTORY_LEN = 3
MAX_TOKENS = 2048
TEMPERATURE = 0.7
ONLINE_LLM_MODEL = {
}

MODEL_PATH = {
    "embed_model": {
        "bge-large-zh": "/mnt/bge-large-zh",
    },
    "llm_model": {
        "Qwen-1_8B-Chat": "/mnt/Qwen-1_8B-Chat",
    },
    "reranker": {
        "bge-reranker-large": "/mnt/bge-reranker-large",
    }
}

NLTK_DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "nltk_data")

VLLM_MODEL_DICT = {
    "Qwen-1_8B-Chat": "/mnt/Qwen-1_8B-Chat",
}

SUPPORT_AGENT_MODEL = [
    "Qwen",  # 所有Qwen系列本地模型
]

# **### server_config.py 配置如下：**
OPEN_CROSS_DOMAIN = False

DEFAULT_BIND_HOST = "127.0.0.1"

WEBUI_SERVER = {
    "host": "127.0.0.1",
    "port": 8501,
}

API_SERVER = {
    "host": "127.0.0.1",
    "port": 7861,
}

FSCHAT_OPENAI_API = {
    "host": "127.0.0.1",
    "port": 20000,
}

FSCHAT_MODEL_WORKERS = {
    "default": {
        "host": "127.0.0.1",
        "port": 20002,
        "device": LLM_DEVICE,
    },
    "Qwen-1_8B-Chat": {
        "device": "cuda",
    },
}

FSCHAT_CONTROLLER = {
    "host": "127.0.0.1",
    "port": 20001,
    "dispatch_method": "shortest_queue",
}

# **### kb_config.py配置如下：**
kbs_config = {
    "pg": {
        "connection_uri": "postgresql://postgres:postgres@10.7.212.217:5432/langchain_chatchat",
    },

    "es": {
        "host": "10.7.212.157",
        "port": "23200",
        "index_name": "test_index",
        "user": "",
        "password": ""
    },
    "milvus_kwargs":{
        "search_params":{"metric_type": "L2"}, #在此处增加search_params
        "index_params":{"metric_type": "L2","index_type": "HNSW"} # 在此处增加index_params
    },
    "chromadb": {}
}

![11125](https://github.com/chatchat-space/Langchain-Chatchat/assets/166580746/79293d77-be2a-4b4c-bcf5-5d024cc754b5)
![2234](https://github.com/chatchat-space/Langchain-Chatchat/assets/166580746/4688c8e9-a369-41af-85da-26cfb69ad95f)

**Comment by yanli789** [comment]
问题已解决

**Comment by zoupengfeiagent** [comment]
> 问题已解决

请问怎么解决的。
