### ISSUE TITLE
ollama本地或docker启动，ollama pull llama3 或deepseek-llm，在model_config.py中选择列表中加上，同时online llm中加上ollama的OLLAMA_BASE_URL (http://127.0.0.1:11434)

### ISSUE THREAD

**Issue by Ptianyu** [chatchat-space/Langchain-Chatchat#4028]
ollama本地或docker启动，ollama pull llama3 或deepseek-llm，在model_config.py中选择列表中加上，同时online llm中加上ollama的OLLAMA_BASE_URL (http://127.0.0.1:11434)

llama3 要每次提醒他用简体中文回答，或设置在prompt中

**Comment by blackwhites** [comment]
llama3 可以设置系统提示词，让他必须用中文输出
