### ISSUE TITLE
[询问] 方舟豆包依赖pydantic和fschat冲突

### ISSUE THREAD

**Issue by china-gcg** [chatchat-space/Langchain-Chatchat#4033]
在更改使用方舟的调用方式，为了调用豆包，他更新调用了方式，导致使用pydantic，他要在2.x。但是由于项目的冲突依赖，会卡住
![图片1](https://github.com/chatchat-space/Langchain-Chatchat/assets/112814800/911e8fff-b780-4da4-8398-660a4af6a5e3)
有没有大佬有建议

**Comment by china-gcg** [comment]
不用了，我自己解决了

**Comment by flyuuo9** [comment]
@china-gcg 请问下如何解决的，方便分享一下吗？我想加openparse进来，也是依赖了pydantic 2

**Comment by china-gcg** [comment]
额，他是方舟3升级了，我用原本的方式搭建搭建进去的，也是没有解决这个问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年05月30日 11:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [chatchat-space/Langchain-Chatchat] [询问] 方舟豆包依赖pydantic和fschat冲突 (Issue #4033) |

@china-gcg 请问下如何解决的，方便分享一下吗？我想加openparse进来，也是依赖了pydantic 2
