### ISSUE TITLE
文件比较多时，要运行几十个小时，一旦出错或者意外终止，数据库就损害了要重新生成。这里每处理100个重新保存一下

### ISSUE THREAD

**Issue by zmwstu** [chatchat-space/Langchain-Chatchat#4040]
文件比较多时，要运行几十个小时，一旦出错或者意外终止，数据库就损害了要重新生成。在哪里修改代码，能够每处理100个重新保存一下或者多线程添加到向量数据库。

**Comment by KevinFanng** [comment]
python init_database.py -help
usage: init_database.py [-h] [-r] [--create-tables] [--clear-tables] [--import-db IMPORT_DB] [-u] [-i] [--prune-db] [--prune-folder] [-n KB_NAME [KB_NAME ...]]
                        [-e EMBED_MODEL]

please specify only one operate method once time.

options:
  -h, --help            show this help message and exit
  -r, --recreate-vs     recreate vector store. use this option if you have copied document files to the content folder, but vector store has not been populated
                        or DEFAUL_VS_TYPE/EMBEDDING_MODEL changed.
  --create-tables       create empty tables if not existed
  --clear-tables        create empty tables, or drop the database tables before recreate vector stores
  --import-db IMPORT_DB
                        import tables from specified sqlite database
  -u, --update-in-db    update vector store for files exist in database. use this option if you want to recreate vectors for files exist in db and skip files
                        exist in local folder only.
  -i, --increment       update vector store for files exist in local folder and not exist in database. use this option if you want to create vectors
                        incrementally.
  --prune-db            delete docs in database that not existed in local folder. it is used to delete database docs after user deleted some doc files in file
                        browser
  --prune-folder        delete doc files in local folder that not existed in database. is is used to free local disk space by delete unused doc files.
  -n KB_NAME [KB_NAME ...], --kb-name KB_NAME [KB_NAME ...]
                        specify knowledge base names to operate on. default is all folders exist in KB_ROOT_PATH.
  -e EMBED_MODEL, --embed-model EMBED_MODEL
                        specify embeddings model.
