### ISSUE TITLE
使用文件对话上传文件能够正常的检索文件，但使用知识库上传相同文件却显示知识库无法匹配

### ISSUE THREAD

**Issue by Dannissss0704** [chatchat-space/Langchain-Chatchat#4045]
如题
![图片1](https://github.com/chatchat-space/Langchain-Chatchat/assets/116017507/85a7d7a4-ff61-4840-992e-80f9a2716e92)

**Comment by grossmetal** [comment]
你是用的哪个embedding model？我尝试用最新版本的代码m3e和m3e-large就会有这种情况，用bge-large-zh-v1.5就没问题。我回滚到一个月之前版本就都能用了。

**Comment by Dannissss0704** [comment]
> 你是用的哪个embedding model？我尝试用最新版本的代码m3e和m3e-large就会有这种情况，用bge-large-zh-v1.5就没问题。我回滚到一个月之前版本就都能用了。

我用的是普通的bge-large-zh但是只有文件上传对话能检索，如果是改成bge-large-zh-v1.5可以用知识模型吗

**Comment by grossmetal** [comment]
> > 你是用的哪个embedding model？我尝试用最新版本的代码m3e和m3e-large就会有这种情况，用bge-large-zh-v1.5就没问题。我回滚到一个月之前版本就都能用了。
> 
> 我用的是普通的bge-large-zh但是只有文件上传对话能检索，如果是改成bge-large-zh-v1.5可以用知识模型吗

你可以试一下哈。

**Comment by Dannissss0704** [comment]
> > > 你是用的哪个embedding model？我尝试用最新版本的代码m3e和m3e-large就会有这种情况，用bge-large-zh-v1.5就没问题。我回滚到一个月之前版本就都能用了。
> > 
> > 
> > 我用的是普通的bge-large-zh但是只有文件上传对话能检索，如果是改成bge-large-zh-v1.5可以用知识模型吗
> 
> 你可以试一下哈。

可以用了，感恩

**Comment by danny-zhu** [comment]
我这边也遇到相同的问题，可以试试把model_config中用的模型路径写完整就可以解决了。MODEL_ROOT_PATH这参数可能是有的地方没有自动拼接上，我还没来得及去逐行排查代码，你们遇到可以试试看。

**Comment by wangsen1110** [comment]
我用的chatglm3-6b和bge-large-zh，也是和楼主一样，在文件对话中可以正常检索到文件内容，在知识库中上传的全部显示未找到文档

**Comment by Qacket** [comment]
> 我用的chatglm3-6b和bge-large-zh，也是和楼主一样，在文件对话中可以正常检索到文件内容，在知识库中上传全部显示未找到文档

请问解决了吗
