### ISSUE TITLE
[询问]文件对话的存储与释放机制

### ISSUE THREAD

**Issue by yiyangshen** [chatchat-space/Langchain-Chatchat#4050]
请教各位，文件对话模式下上传的文件应该是新建了一个知识库，那这个知识库的临时存储的目录在哪里？如何才能删除掉呢？

**Comment by liunux4odoo** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/blob/b9827529aad9d565e2f2ef90e96632ed628a7d40/configs/basic_config.py.example#L27

在一个临时目录里。服务器重启的时候会自动删除。
