### ISSUE TITLE
为什么升级到.10后 它的LLm对话也好，知识库问答也好，它的速度会比.09要慢一些

### ISSUE THREAD

**Issue by Bo-LiangD** [chatchat-space/Langchain-Chatchat#4057]
操作系统：Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['Qwen1.5-14B-Chat-GPTQ-Int4'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/home/wb/models/Qwen1.5-14B-Chat-GPTQ-Int4',
 'model_path_exists': True,
 'port': 20002}
当前Embbedings模型： bge-large-zh-v1.5 @ cuda
配置都是相同的，求解答

**Comment by zzyoung8** [comment]
老哥，我想问下这个.10版本比以前的版本知识库回答效果上会好一点吗

**Comment by Bo-LiangD** [comment]
> 老哥，我想问下这个.10版本比以前的版本知识库回答效果上会好一点吗
不确定是不是会好很多。因为要自己进行参数调整，文件内容调整，和一些模型上的选择（已经处理过，所以感觉上不是很大）

**Comment by zzyoung8** [comment]
> > 老哥，我想问下这个.10版本比以前的版本知识库回答效果上会好一点吗
> > 不确定是不是会好很多。因为要自己进行参数调整，文件内容调整，和一些模型上的选择（已经处理过，所以感觉上不是很大）

好的，谢谢哥
