### ISSUE TITLE
为什么找到出处了,但是还是无法回答该问题?

### ISSUE THREAD

**Issue by starsliao** [chatchat-space/Langchain-Chatchat#406]
![图片](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/3349611/1fc81d61-2409-4330-9065-fdda1a27c86a)
部署的最新的master版本, 我看了下出处的内容就是答案呀.但是一直回复无法回答该问题

**Comment by imClumsyPanda** [comment]
说明是prompt template或llm理解能力问题

**Comment by xx-zhang** [comment]
建议这种情况多换几个问法尝试。不要用复杂的倒装语法。

后面生产环境下前面再套接一个prompt优化

**Comment by HarveyPhoenix** [comment]
> 后面生产环境下前面再套接一个prompt优化

可以举个例子么？我也遇到了类似的问题，不太会怎么套一个prompt优化

**Comment by ffy-FFRain** [comment]
这个问题令我苦恼，我修改prompt很长时间也还是存在，我的资料已经是问题回答，但是要么就是回答不全，要么就是回答不准，明明答案已在出处内。

**Comment by zRzRzRzRzRzRzR** [comment]
最新的代码中解决了部分这样的问题，但是仍然还存在如issue所说的情况，我们也会尽力完善这个功能。
这个问题可能来自我们的框架，大模型原始能力，可以更换模式，更新代码试试
