### ISSUE TITLE
关于reranker重排的使用方式

### ISSUE THREAD

**Issue by mrx-data** [chatchat-space/Langchain-Chatchat#4067]
`
docs = await run_in_threadpool(search_docs,
                                       query=query,
                                       knowledge_base_name=knowledge_base_name,
                                       top_k=top_k,
                                       score_threshold=score_threshold)

        # 加入reranker
        if USE_RERANKER:
            reranker_model_path = MODEL_PATH["reranker"].get(RERANKER_MODEL,"BAAI/bge-reranker-large")
            print("-----------------model path------------------")
            print(reranker_model_path)
            reranker_model = LangchainReranker(top_n=top_k,
                                            device=embedding_device(),
                                            max_length=RERANKER_MAX_LENGTH,
                                            model_name_or_path=reranker_model_path
                                            )
            print(docs)
            docs = reranker_model.compress_documents(documents=docs,
                                                     query=query)
            print("---------after rerank------------------")
            print(docs)
`
关于reranker这个相关模型的使用，如果只是把其他Embedding 模型已经查出来的数据，重新微调排序，然后topk又不变，这个东西的意义好像不大啊，还会造成额外耗时
能否解答一下我这个疑惑呢？

**Comment by XiaoTongDeng** [comment]
代码是在哪个位置啊
