### ISSUE TITLE
inotify watch limit reached

### ISSUE THREAD

**Issue by SKRY1412** [chatchat-space/Langchain-Chatchat#4071]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/56523374/e29be54a-6555-4b5c-9b96-0fe17a2714d0)
由于没有权限无法更改inotify watch数量，请问在代码的哪个部分可以关闭？

**Comment by Tiandishihua** [comment]
> ![image](https://private-user-images.githubusercontent.com/56523374/333140438-e29be54a-6555-4b5c-9b96-0fe17a2714d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDU5NTcsIm5iZiI6MTcyMDc0NTY1NywicGF0aCI6Ii81NjUyMzM3NC8zMzMxNDA0MzgtZTI5YmU1NGEtNjU1NS00YjVjLTliOTYtMGZlMTdhMjcxNGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAwNTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0N2RlN2M1MDYyMTg3OTcyOGUwMDg5NDY3YTlkNTc1MzJjMDFiMmEyNzc0MmVhZGQwMjkwOGYxMjlkMTFlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Go3buib7Hkj4ohPEgL0uxiFUKKP4YUsq0sTEPrvq1BQ) 由于没有权限无法更改inotify watch数量，请问在代码的哪个部分可以关闭？

您好！请问您解决了这个问题吗？
