### ISSUE TITLE
与excel交互时，数据经常查不全

### ISSUE THREAD

**Issue by dongkuang** [chatchat-space/Langchain-Chatchat#4075]
在与excel交互时，数据经常查不全，如有15条数据，就展示12条，怎么改提示词，都是12条，但时而12条数据还不是同一批，说明数据向量化是成功的，就是每次调用时调不全，不知道为什么？大家有遇到过吗？我用的是qwen110b的模型测试的

**Comment by tf18536** [comment]
excel转成html格式试试
