### ISSUE TITLE
调用api接口知识库问答怎么设置历史对话轮数？

### ISSUE THREAD

**Issue by mazisuki** [chatchat-space/Langchain-Chatchat#4079]

**Comment by mazisuki** [comment]
似乎不能设置"history_len"

**Comment by XiaoTongDeng** [comment]
看了源代码template，不支持，可以自己改代码

**Comment by mazisuki** [comment]
> 看了源代码template，不支持，可以自己改代码

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/123860392/6a7b89e2-d30e-4f1a-a9cd-7da740f7a3b2)
在webui中的这个设置是怎么调用的呢

**Comment by XiaoTongDeng** [comment]
> > 看了源代码template，不支持，可以自己改代码
> 
> ![image](https://private-user-images.githubusercontent.com/123860392/333532548-6a7b89e2-d30e-4f1a-a9cd-7da740f7a3b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NzY1MDgsIm5iZiI6MTcxNjU3NjIwOCwicGF0aCI6Ii8xMjM4NjAzOTIvMzMzNTMyNTQ4LTZhN2I4OWUyLWQzMGUtNGYxYS1hOWNkLTdkYTc0MGY3YTNiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxODQzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjViYTZhYjc4YjI2MGVhYTQxZTQzY2NiZjNhNjFlZGRkZjRmNTEwZjU2ZjUxNWYwNjMzYzY0MzgyODA0ODI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QAc91klUBnm99ux5uJY85BiX2uifnkgPN0m2pUwvQAw) 在webui中的这个设置是怎么调用的呢

webui中的这个历史对话轮次是无效的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/162091806/2e879a7b-e2b8-4b7b-b86f-519992912357)
