### ISSUE TITLE
添加PDF文件到知识库时报错：

### ISSUE THREAD

**Issue by tf18536** [chatchat-space/Langchain-Chatchat#4083]
添加PDF文件到知识库时报错
utils.py[line:377] - ERROR: RuntimeError: 从文件 tantang/ccc.pdf 加载文档时出错：Directory 'static/' does not exist

**Comment by tf18536** [comment]
已解决，pip install pyMupdf

**Comment by java668** [comment]
解析pdf 有些文件解析出现乱码了，遇到过吗
<img width="896" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/124699758/9723f178-92f1-43bc-9ef7-1d2e56d39d8d">
