### ISSUE TITLE
[BUG] 知识库管理页面查看文档报错：The truth value of a DataFrame is ambiguous 

### ISSUE THREAD

**Issue by fengzengfly** [chatchat-space/Langchain-Chatchat#4086]
**问题描述 / Problem Description**
在可视化界面查看知识库文档，报错：ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/48151231/ef400870-9207-4bbf-8990-e52a5bf5a6ad)

**复现问题的步骤 / Steps to Reproduce**
1. 打开 “web_ui界面”
2. 点击 “知识库管理”
3. 点击任一文档
4. 报错 ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**预期的结果 / Expected Result**
可以正确下载所选文档

**实际结果 / Actual Result**
报错：ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**环境信息 / Environment Information**
- langchain-ChatGLM 版本号：v0.2.10 
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen-14B-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  Rocky Linux v9.4
- Python 版本 / Python version: 3.10

**Comment by jiusi9** [comment]
我也遇到了同样的问题

**Comment by x18-1** [comment]
解决了吗

**Comment by x18-1** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/84564929/784e2eca-be57-4f8c-858b-bf1f36c2bbd7)

可能是由于pandas版本导致的。改成这样就可以了

**Comment by liunux4odoo** [comment]
streamlit-aggrid 升级导致 selected_rows 发生变化，0.3.x 版本已经修复。0.2.x 版本可以将 aggrid 降级

**Comment by liuhongbao** [comment]
streamlit-aggrid降级到什么版本

**Comment by keedo** [comment]
streamlit-aggrid 1.0.0 可以

**Comment by fengzengfly** [comment]
你看下上面热佬X18-1给的解决方案~> 请问这个问题后来是怎么解决的？streamlit-aggrid 1.0.4与1.0.2试了都不行，当前用的是1.0.5
