### ISSUE TITLE
[BUG] 数据上传失败，无法添加到向量库中

### ISSUE THREAD

**Issue by Ricco567** [chatchat-space/Langchain-Chatchat#4089]
**问题描述 / Problem Description**
执行python init_database.py --recreate-vs
显示warning：
tokenization_chatglm.py[line:164] - WARNING: Setting eos_token is not supported, use the default one.
tokenization_chatglm.py[line:160] - WARNING: Setting pad_token is not supported, use the default one.
tokenization_chatglm.py[line:156] - WARNING: Setting unk_token is not supported, use the default one.

执行python startup.py -a，在WebUI界面上显示知识库文件没有成功添加到向量库中：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/69997806/f7f8c1e1-1aca-41d2-868d-ef268355d718)

在WebUI界面上新建数据库，并上传文件，仍显示以上warning，并且没有成功将文件添加到向量库中：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/69997806/939299d0-aab0-4406-a2b2-0c73b17db966)

**Comment by Qacket** [comment]
我也碰到了相同的问题，请问解决了吗

**Comment by liunux4odoo** [comment]
看第二行文档数量已经入库成功了，"X"是显示错误，0.2.final和0.3.x 分支已经修复

**Comment by liunux4odoo** [comment]
same of #4015
