### ISSUE TITLE
RapidOCRPDFLoader 解析pdf 出现乱码的情况

### ISSUE THREAD

**Issue by java668** [chatchat-space/Langchain-Chatchat#4090]
**问题描述 / Problem Description**
RapidOCRPDFLoader 解析pdf 出现乱码的情况

**复现问题的步骤 / Steps to Reproduce**
运行 RapidOCRPDFLoader main方法 解析本地pdf文档出现乱码
<img width="896" alt="企业微信截图_598bc3a2-5f68-4c27-bf0d-7a56880f5b7d" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/124699758/018aeff2-165c-43e7-a9a4-254cdc3f7b54">

**预期的结果 / Expected Result**
应该正确解析出中文

**实际结果 / Actual Result**
中文乱码 
<img width="896" alt="企业微信截图_598bc3a2-5f68-4c27-bf0d-7a56880f5b7d" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/124699758/489289e7-785c-4993-ac4f-79f6d80dcc7d">

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g.,

**Comment by historyliao** [comment]
这都没有说怎么解决怎么就关闭了？ @liunux4odoo
