### ISSUE TITLE
加载Qwen1.5-7B-Chat-int4 效果不好

### ISSUE THREAD

**Issue by TC10127** [chatchat-space/Langchain-Chatchat#4093]
**问题描述 / Problem Description**
加载自己微调过的Qwen1.5-7B-Chat，然后做auto-gptq，int4量化，A100-40G加载时显存占用变小，但是推理速度没有加快，推理效果不好。

**预期的结果 / Expected Result**
推理速度变快

**实际结果 / Actual Result**
推理速度很慢，每秒10个左右token
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/165656865/bb33cb0e-e404-456d-8d56-aa597303071f)

**Comment by ln410** [comment]
你做微调是全量微调吗，还是ptuning或者lora的形式微调

**Comment by TC10127** [comment]
> 你做微调是全量微调吗，还是ptuning或者lora的形式微调

lora微调

**Comment by ln410** [comment]
lora微调的模型能直接用在langchain-chatchat中吗？是不是要模型融合才行

**Comment by TC10127** [comment]
> lora微调的模型能直接用在langchain-chatchat中吗？是不是要模型融合才行

合并或者不合并都能用

**Comment by ln410** [comment]
> > lora微调的模型能直接用在langchain-chatchat中吗？是不是要模型融合才行
> 
> 合并或者不合并都能用

但是我微调训练出来的模型只有三个，最后langchain-chatchat加载模型数量必须是7个，你怎么解决的
