### ISSUE TITLE
知识库匹配需要原文回答，而不是润色的内容

### ISSUE THREAD

**Issue by chenusername** [chatchat-space/Langchain-Chatchat#4102]
### 问题描述 ：
知识库匹配需要原文回答，而不是润色的内容。怎么调整回答的问题是否经过润色

**复现问题的步骤 / Steps to Reproduce**
1. 执行 ：导入知识：
爱莫能助：虽然同情但无力帮助。(正：同情；误：喜爱)
2. 点击知识库问答：爱莫能助
3. 问题出现 / Problem occurs
回答为：”爱莫能助是一个成语，表示虽然同情但无力帮助。其中，“爱”表示同情，“莫”表示没有能力，“能”表示能够，“助”表示帮助。这个成语常用来形容面对一些无法解决的问题或困境时，感到无助和无奈的心情。“

**预期的结果 / Expected Result**
虽然同情但无力帮助。(正：同情；误：喜爱)
描述应该出现的结果 / Describe the expected result.
虽然同情但无力帮助。(正：同情；误：喜爱)

**Comment by yanzengyun** [comment]
更改prompt

**Comment by ddnoodle** [comment]
这个需求我也遇到过，更改prompt就可以简单实现，在prompt中告诉LLM只需要将<已知信息>中的内容原文输出，不要做任何修改就行。
