### ISSUE TITLE
UnstructuredMarkdownLoader会丢失Markdown的结构标识

### ISSUE THREAD

**Issue by sxrketialy** [chatchat-space/Langchain-Chatchat#4105]
**问题描述 / Problem Description**
Markdown文件在经过LangChain中的UnstructuredMarkdownLoader后丢失了标题的标识，导致最终分片结果还是基于字数进行的分片，不能按照标题结构分片

**实际结果 / Actual Result**
例如有一个Markdown文本：
```
# 1 标题
## 1.1 标题
### 1.1.1 标题
#### 1.1.1.1 标题
1.1.1.1 内容

# 2 标题
2 内容
## 2.2 标题
2.2 内容
```
经过UnstructuredMarkdownLoader加载后就变成了
```
1 标题
1.1 标题
1.1.1 标题
1.1.1.1 标题
1.1.1.1 内容

2 标题
2 内容
2.2 标题
2.2 内容
```

上述情况导致MarkdownHeaderTextSplitter分割器没有办法识别到标题信息，有什么办法可以保留Markdown的结构信息加载进去呢

**Comment by hahayueqing** [comment]
我也遇见了这个问题

**Comment by hahayueqing** [comment]
请问解决了吗

**Comment by sxrketialy** [comment]
> 请问解决了吗

也没有太好的解决办法，目前是手动判断md文件的话就重新用open去加载一次

**Comment by hahayueqing** [comment]
> > 请问解决了吗
> 
> 也没有太好的解决办法，目前是手动判断md文件的话就重新用open去加载一次

与知识库对话的时候  有没有不能显示出处文件的名字呀
![Uploading 微信图片_20240607145446.png…]()

**Comment by sxrketialy** [comment]
在每个分片的metadata里面加个source="文件名"就可以了

**Comment by liunux4odoo** [comment]
这是 langchain 自身的限制，想做更精细的拆分需要自己写 DocumentLoader 或者转化为其它格式，你也可以给 loader 加上 `mode='elements'` 参数，但效果还不如前者。
