### ISSUE TITLE
[FEATURE] 搜索引擎支持百度api

### ISSUE THREAD

**Issue by fengzengfly** [chatchat-space/Langchain-Chatchat#4107]
**功能描述 / Feature Description**
搜索引擎问答希望支持百度搜索的api接入

**解决的问题 / Problem Solved**
国内用户使用bing和ddg都不太方便，metaphor搜出的相关度不高，望支持百度搜索api

**实现建议 / Implementation Suggestions**
无

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
无

**Comment by liunux4odoo** [comment]
百度向个人提供搜索 API 服务吗？给个文档链接去看看。

**Comment by henbucuoshanghai** [comment]
langcahain怎样直接百度搜索？解决了吗
