### ISSUE TITLE
问答的第二个问题就会卡住中断

### ISSUE THREAD

**Issue by geraldjin** [chatchat-space/Langchain-Chatchat#4111]
知识库问答，第一个问题能够正常回答，接着再问第二个问题时就会卡住中断，刷新页面后还是第一个问题正常，第二个问题就卡住。
看了下显存还没有满

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.2.10
- 是否使用 Docker 部署：是 
- 使用的模型：ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: centOS 7
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12570106/3cf9fe66-bf11-4b11-946f-6b91ca72a522)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12570106/e62dddb8-a267-4d94-90db-9e6cc0534faf)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
