### ISSUE TITLE
如何同时接入多个封装好的openai api格式大模型

### ISSUE THREAD

**Issue by Shame-fight** [chatchat-space/Langchain-Chatchat#4113]
**功能描述 / Feature Description**
我在云服务器上部署了多个本地大模型，并将其封装为openai api 可以访问。
本存储库的model_config.py中通过配置"ONLINE_LLM_MODEL"中的"qianfan-api"，可以进行接入生效，但只能接入一个模型，如何同时接入多个openai api模型以便于不同模块使用。

**解决的问题 / Problem Solved**
解决只能接入一个openai api的问题

**Comment by YuanWind** [comment]
可以看看这个操作是不是你想要的： https://zhuanlan.zhihu.com/p/701234484

**Comment by Shame-fight** [comment]
> 可以看看这个操作是不是你想要的： https://zhuanlan.zhihu.com/p/701234484

感谢回复，和该篇文章所述非常相像。但model_workers文件夹下没有为openai模型单独写一个文件，我不知道应该如何修改代码实现我的需求

**Comment by liunux4odoo** [comment]
2个办法：
1、在 model_config.py 中按照 openai 格式配置多个不同名称的模型
2、使用 oneapi 进行转接。
