### ISSUE TITLE
调用讯飞星火api，没有输出回答

### ISSUE THREAD

**Issue by zixiaotan21** [chatchat-space/Langchain-Chatchat#4115]
**问题描述 / Problem Description**
调用讯飞星火api时，无论是LLM对话，还是知识库问答，都没有输出回答。但命令行也没有显示报错

**预期的结果 / Expected Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/6dbb1402-619f-4e45-b978-fbf1b5d0a422)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/142043181/2cdd10de-e8bc-463f-9adc-9498b8b9b7e9)

环境信息 / Environment Information
langchain-ChatGLM 版本/commit 号：v0.2.10
是否使用 Docker 部署（是/否）：否
使用的模型（ChatGLM2-6B / Qwen-7B 等）：qwen-api
使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
操作系统及版本 / Operating system and version: ：Windows-10-10.0.22631-SP0.
Python 版本 / Python version: ：3.11.8
其他相关环境信息 / Other relevant environment information:
附加信息 / Additional Information
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by YuanWind** [comment]
看看是不是这里的ws设置原因 https://zhuanlan.zhihu.com/p/701234484

**Comment by zixiaotan21** [comment]
谢谢！我解决啦！我发现是我星火api-key 开通的时候出了点问题，好像是有个“开通服务”没有点，导致api-key不生效。现在没问题啦，谢谢！
