### ISSUE TITLE
[BUG] 知识库问答匹配不到/ Concise description of the issue

### ISSUE THREAD

**Issue by pyxiaoxiaobo** [chatchat-space/Langchain-Chatchat#4116]
**问题描述 / 知识库问答匹配不到**
新建知识库并上传文件之后，选择知识库问答并选择该知识库，提示未找到相关文档,该回答为大模型自身能力解答 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '知识库管理-新建知识库-上传文件'
2. 点击 '...' / Click '对话-选择知识库问答-选择知识库'
3. 滚动到 '...' / Scroll to '输入框提问'
4. 问题出现 / 未找到相关文档,该回答为大模型自身能力解答

**预期的结果 / Expected Result**
描述应该出现的结果 / 乐乐的好朋友是孙少华

**实际结果 / Actual Result**
描述实际发生的结果 / 未找到相关文档,该回答为大模型自身能力解答.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM3-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:Linux-3.10.0-1160.el7.x86_64-x86_64-with-glibc2.17
- Python 版本 / Python version:3.11.7 (main, Apr  2 2024, 12:09:49) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
- 其他相关环境信息 / Other relevant environment information:langchain版本：0.0.354. fastchat版本：0.2.35

**附加信息 / Additional Information**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31797152/3d7cacdb-401c-43cc-99e1-83df48dda632)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31797152/83006904-8d3e-4333-a80d-83b66f1283f3)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31797152/811d0419-bdb2-4e1a-9a4d-27ca5360bb1c)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31797152/22de6a5c-ffd0-4432-9ed9-a9de595925ca)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/31797152/1362a370-fdec-44fd-93ae-bfc86a94e7c2)

添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zixiaotan21** [comment]
同样经常出现类似的问题，想问问楼主解决了吗？

我自己猜测，不知道是chatglm3大模型能力的问题，还是向量检索的时候出问题？

**Comment by wangsen1110** [comment]
在终端重新执行 知识库的初始化，再提问，就有了

**Comment by herryRiver** [comment]
> 在终端重新执行 知识库的初始化，再提问，就有了

怎么初始化？init_database？

**Comment by liunux4odoo** [comment]
把 prompt_config.py 中 `{{ }}` 改成 `{ }` 试试？

**Comment by zlltmy3631** [comment]
mark 同样问题.
要把匹配条数调高才有可能找到
