### ISSUE TITLE
是否可以支持用户中断模型输出

### ISSUE THREAD

**Issue by ciaoyizhen** [chatchat-space/Langchain-Chatchat#4120]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

-------------------------------功能描述----------------------------------
用户问了一个问题，用户发现，模型回复不正确，想要重复提问，但是模型仍在输出，用户不得不等待模型的输出结束才可以提问，如果可以之间中断模型的输出，像chatglm4官方以及chatgpt，现在都支持中断模型输出
-------------------------------功能描述----------------------------------

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

-------------------------------解决的问题----------------------------------
可以增加用户体验！！！
-------------------------------解决的问题----------------------------------

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

-------------------------------实现建议----------------------------------
我所能想到的方法就是说，之间前端中断掉，但这个方法大模型还在输出，还是浪费显存。
-------------------------------实现建议----------------------------------

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by liunux4odoo** [comment]
暂不支持。
