### ISSUE TITLE
分词和分块逻辑顺序

### ISSUE THREAD

**Issue by loki-keroro** [chatchat-space/Langchain-Chatchat#4127]
一个包含文本的文档，是如何根据分词和分块逻辑切分成一个个chunk的？是先使用TextSplitter？还是先按CHUNK_SIZE？两者的先后逻辑是如何？
麻烦赐教

**Comment by liunux4odoo** [comment]
基础知识请自行学习，这里是项目的问题反馈区，不是教学区。
