### ISSUE TITLE
[BUG] 使用es作向量数据库时，某些markdown文档向量化失败

### ISSUE THREAD

**Issue by yuxin-ashley** [chatchat-space/Langchain-Chatchat#4129]
**问题描述 / Problem Description**
使用es作为向量库，添加markdown文档到知识库并向量化失败

**复现问题的步骤 / Steps to Reproduce**
1. 在一个知识库中共有7个markdown文档，只有三个被正确向量化，剩下三个的文档加载器和分词器均未有显示。如图：
![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/136757103/fc064f46-0542-4343-b758-717ec4c1c25c)
2. 选中某一未向量化的文档，点击“重新添加至向量库”

**预期的结果 / Expected Result**
选中的文档应正确向量化

**实际结果 / Actual Result**
后台报错“创建索引失败”，“索引已经存在”，如图：
![2](https://github.com/chatchat-space/Langchain-Chatchat/assets/136757103/7ac0c193-7648-4293-9c51-f8de16ad2cc9)
![3](https://github.com/chatchat-space/Langchain-Chatchat/assets/136757103/e0ede218-3a05-4bd0-8890-9924e557a2c5)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： Langchain-Chatchat version 0.2.10
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-14B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： es
- 操作系统及版本 / Operating system and version: Ubuntu 22.04
- Python 版本 / Python version: 3. 11
- 其他相关环境信息 / Other relevant environment information:

**Comment by yuxin-ashley** [comment]
@dosu-bot

**Comment by MSZheng20** [comment]
检查一下ES里面是不是已经存在了？

**Comment by liunux4odoo** [comment]
可能和 #4351 有关。0.3.1 已经发布，欢迎更新测试
