### ISSUE TITLE
[BUG] 无法配置知识库

### ISSUE THREAD

**Issue by woshicqy** [chatchat-space/Langchain-Chatchat#413]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python -u webui.py
2. 点击 添加至知识库选项
3. 问题出现 / Problem occurs
成功加载后，如下图所示：
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38115801/947aeacf-8b96-43dd-a647-61d3c00a434d)
按照步骤3点击后，问题如下图所示：
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38115801/a80aa700-9388-40bb-985c-a1ec9d4c98f2)

**预期的结果 / Expected Result**
描述应该出现的结果 可以添加新的知识库，并且上传新的文档

**实际结果 / Actual Result**
描述实际发生的结果 不能成功新建知识库

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新版
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: windows
- Python 版本 / Python version: 3.10.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by haonanye** [comment]
刷新页面，无法显示新建知识库，除非重启服务。

**Comment by woshicqy** [comment]
刷新后，还是无法添加新的知识库

**Comment by dunbin** [comment]
应该也是vector_store文件夹中缺少了index.faiss和index.pkl这2个文件。

**Comment by woshicqy** [comment]
我已经解决了，排除下来是因为proxy的问题。
在webui.py中添加：
```
import os
os.environ["no_proxy"] = "localhost,0.0.0.0,::8090"
```
我的server_port=8090

**Comment by dunbin** [comment]
您好！信件已收到，感谢您的来信。
