### ISSUE TITLE
The request client is not a secure context and the resource is in more-private address space。特殊跨域问题如何解决。

### ISSUE THREAD

**Issue by czs208112** [chatchat-space/Langchain-Chatchat#4132]
**问题描述 / Problem Description**
本地局域网部署后，开启跨域后跨服务器访问一切正常。
部署到用户线上服务器后，无论如何配置跨域，调用api后都提示跨域。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/7848823/a0f4ec25-72b9-4f4e-b21c-9206f3ba9038)

用户的网络环境比较复杂，应该是从公网访问了私网，查了资料似乎加一个Access-Control-Allow-Private-Network的响应头可以解决问题。但是再Langchain-Chatchat的配置文件中没有看到这个配置项。

能否处理下这种特殊跨域问题？

https://www.cnblogs.com/whm-blog/p/16418314.html

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： ChatGLM3-6B
- 操作系统及版本 / Operating system and version: windowsServer
- Python 版本 / Python version: 3.11

**Comment by liunux4odoo** [comment]
非项问题，网络环境问题需要自行解决。
