### ISSUE TITLE
求助：如何不使用api，批量进行预测

### ISSUE THREAD

**Issue by chenyulu2000** [chatchat-space/Langchain-Chatchat#4134]
目前需求只是离线对大量数据进行预测，不想使用api以避免引入额外的网络请求时间，请问如何指定启动方式。

**Comment by HuYunhai-Alex** [comment]
默认使用的glm3就是本地的离线模型，运行前需要下载对应的模型

**Comment by chenyulu2000** [comment]
> 默认使用的glm3就是本地的离线模型，运行前需要下载对应的模型

您好，感谢您的解答。不过我已经下载离线大模型了，我想问的是：repo中的推理方式是根据request发送query，然后结果以response形式返回，我目前是有很多的数据需要推理，request和response会消耗另外的时间，所以我只想调用核心代码逻辑（即knowledge_chat_base.py里的函数）进行本地化的推理，请问提供了该种启动方式吗？

**Comment by liunux4odoo** [comment]
> > 默认使用的glm3就是本地的离线模型，运行前需要下载对应的模型
> 
> 您好，感谢您的解答。不过我已经下载离线大模型了，我想问的是：repo中的推理方式是根据request发送query，然后结果以response形式返回，我目前是有很多的数据需要推理，request和response会消耗另外的时间，所以我只想调用核心代码逻辑（即knowledge_chat_base.py里的函数）进行本地化的推理，请问提供了该种启动方式吗？

不提供，绝大部分功能都是走 api.py
