### ISSUE TITLE
[BUG] 部署在阿里PAI平台的EAS上访问页面是白屏

### ISSUE THREAD

**Issue by dravinbox** [chatchat-space/Langchain-Chatchat#414]
**问题描述 / Problem Description**
部署在阿里PAI平台的EAS上访问页面是白屏，可能是路由代码写成../asset导致丢失一段路由信息，导致加载js代码报404

**Comment by zhangjunqiang** [comment]
遇到了同样的问题

**Comment by zhangjunqiang** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/5388898/327e97a2-6d89-4b62-b847-189a4664e457)

**Comment by zhangjunqiang** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/5388898/a1c2de28-1587-42fb-b034-681e447d7ee1)

**Comment by zhangjunqiang** [comment]
因为要加域名转发，因此url中是增加了子path的，导致文件找不到。
本地容器中curl http://localhost:7860/assets/index-a14466cb.js 是可以的
