### ISSUE TITLE
bge-m3无法检索到内容

### ISSUE THREAD

**Issue by sevenandseven** [chatchat-space/Langchain-Chatchat#4143]
你好，我用bge-m3作为embedding模型，进行知识检索，发现不管输入什么问题，他都会报：未找到相关文档。
请问怎么解决？是我的那个参数设置的不合适吗？我把SCORE_THRESHOLD = 0.15还是无法检索？

**Comment by hahayueqing** [comment]
> 你好，我用bge-m3作为embedding模型，进行知识检索，发现不管输入什么问题，他都会报：未找到相关文档。 请问怎么解决？是我的那个参数设置的不合适吗？我把SCORE_THRESHOLD = 0.15还是无法检索？

请问问题解决了吗

**Comment by sevenandseven** [comment]
> > 你好，我用bge-m3作为embedding模型，进行知识检索，发现不管输入什么问题，他都会报：未找到相关文档。 请问怎么解决？是我的那个参数设置的不合适吗？我把SCORE_THRESHOLD = 0.15还是无法检索？
> 
> 请问问题解决了吗


解决了，bge检索时，计算出来的分数都比较大，有很多是大于1的，你可以把阈值设置成一个很大的值，就可以检索出来了。

**Comment by hahayueqing** [comment]
> > > 你好，我用bge-m3作为embedding模型，进行知识检索，发现不管输入什么问题，他都会报：未找到相关文档。 请问怎么解决？是我的那个参数设置的不合适吗？我把SCORE_THRESHOLD = 0.15还是无法检索？
> > 
> > 
> > 请问问题解决了吗
> 
> 解决了，bge检索时，计算出来的分数都比较大，有很多是大于1的，你可以把阈值设置成一个很大的值，就可以检索出来了。

好的  谢谢
