### ISSUE TITLE
能支持glm-4-9b-chat吗模型配置文件里面好像没有

### ISSUE THREAD

**Issue by blvyoucan** [chatchat-space/Langchain-Chatchat#4146]
**功能描述 / Feature Description**
现在还没没有支持glm-4-9b-chat模型吗，模型配置文件里没有找到glm-4-9b-chat相关配置？
[https://github.com/THUDM/GLM-4](https://github.com/THUDM/GLM-4)

**解决的问题 / Problem Solved**

**实现建议 / Implementation Suggestions**

**替代方案 / Alternative Solutions**

**其他信息 / Additional Information**

**Comment by yuzh0816** [comment]
#4141 中已经提出临时解决办法，实测有用。

**Comment by liunux4odoo** [comment]
Duplicate of #4141
