### ISSUE TITLE
[FEATURE] agent对话时，使用工具如何让用户确认是否执行工具呢？

### ISSUE THREAD

**Issue by joveth1** [chatchat-space/Langchain-Chatchat#4148]
**功能描述 / Feature Description**
比如我有一个工具，需要用户确认后才能执行，这个确认过程应该怎么添加呢，或者有什么参考的吗，已经看过官方的human_in_the_loop文档，说实话不是特别明白，实在抱歉我也是刚接触在这一块。

简单的例子
```
tools = [
    StructuredTool.from_function(
        func=calculate,
        name="calculate",
        description="Useful for when you need to answer questions about simple calculations",
        args_schema=CalculatorInput,
    ),
    StructuredTool.from_function(
        func=toolsNeedApproval ,
        name="toolsNeedApproval",
        description="这个工具需要用户确认.",
        args_schema=toolsNeedApprovalInput,
    ),
  StructuredTool.from_function(
        func=normalTool,
        name="normalTool",
        description="这是一个普通工具，不需要确认 .",
        args_schema=normalToolInput,
    ),
]
```

**解决的问题 / Problem Solved**
可以解决需要用户确认的东西。

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**

这两个我都有参考过，但是...
[human_in_the_loop ](https://python.langchain.com/v0.1/docs/use_cases/tool_use/human_in_the_loop/)

https://github.com/langchain-ai/langchain/discussions/21524

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by liunux4odoo** [comment]
目前不支持。
