### ISSUE TITLE
[BUG] 容器化项目，添加文件到知识库卡住，一直running,成功上传，但是没有添加到向量库

### ISSUE THREAD

**Issue by chenusername** [chatchat-space/Langchain-Chatchat#4150]
**问题描述 / Problem Description**
容器化项目，添加文件到知识库卡住，一直running,成功上传，但是没有添加到向量库
后台日志：
2024-06-07 14:35:00,274 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/upload_docs: timed out

**复现问题的步骤 / Steps to Reproduce**
1. 执行 
本地测试没有问题，将项目容器化
2. 点击 
上传文件，点击添加文件到知识库
3. 问题出现 / Problem occurs
右上角一直running的状态，然后后台日志显示上传成功，没多久报错
2024-06-07 14:35:00,274 - utils.py[line:95] - ERROR: ReadTimeout: error when post /knowledge_base/upload_docs: timed out

**预期的结果 / Expected Result**
容器化，可以正常上传文件

**实际结果 / Actual Result**
容器化上传报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新代码
- 是否使用 Docker 部署（是/否）：是
- 使用的模型      Qwen1.5-14B
- 使用的 Embedding 模型    bge-large-zh-v1.5
- 使用的向量库类型  ： faiss 
- Python 版本 / Python version:3.10.9

**Comment by zhaoweihan2017** [comment]
感觉新版本有问题

**Comment by Hoyxxx** [comment]
相同的问题，蹲一手

**Comment by chenusername** [comment]
已经解决了，我是前几天用命令重新新建知识库，然后过几天之后，docker关闭，在重启docker以及docker服务，现在就可以正常上传了
