### ISSUE TITLE
langchain agents executor throws: assert generation is not None #22585

### ISSUE THREAD

**Issue by 1920853199** [chatchat-space/Langchain-Chatchat#4151]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/28426364/84d39985-9b4b-44cd-aecd-0d53899681ce)

**Comment by 1920853199** [comment]
无法聊天，输入你好，直接报错了

**Comment by evanhon0110** [comment]
你好，我也遇到了同样的问题，请问解决了吗

**Comment by liunux4odoo** [comment]
0.2.x 的 agent 很不稳定，可以试试 0.3.0 (pre-release分支）
