### ISSUE TITLE
API部署后调用/local_doc_qa/local_doc_chat 返回Knowledge base samples not found

### ISSUE THREAD

**Issue by ixjx** [chatchat-space/Langchain-Chatchat#416]
入参
{
  "knowledge_base_id": "samples",
  "question": "chatglm-6b 的局限性具体体现在哪里，如何实现改进",
  "history": []
}
返回
{
  "question": "chatglm-6b 的局限性具体体现在哪里，如何实现改进",
  "response": "Knowledge base samples not found",
  "history": [],
  "source_documents": []
}
是调用知识库方式不对么？

**Comment by kangking2019** [comment]
您好，请问解决了吗，我这边也碰到了一样的，在web端上传文档后，提问，返回“Knowledge base samples not found”
