### ISSUE TITLE
glm-4-9b-chat输出结果停不下来的原因

### ISSUE THREAD

**Issue by panda4444ssdfs** [chatchat-space/Langchain-Chatchat#4168]

**Comment by imClumsyPanda** [comment]
v0.3.0最新版本代码已经push到pre-release分支，已支持glm4和qwen2，文档完善中，大家有兴趣的话可以参考以下链接试试看，如果有bug反馈会优先处理

https://github.com/chatchat-space/Langchain-Chatchat/blob/pre-release/libs/chatchat-server/README.md

0.3.0 主要变化：
- 使用 model-provider 代替 fschat 提供模型服务，支持 fschat/xinference/ollama等框架
- 移除对在线 API 模型的支持。可使用 oneapi 提供相关服务，在chatchat 中配置接入即可
- 所有 chat 接口改造为兼容 openai
- file rag增加bm25+embedding的ensemble retriever
- 重写 ChatGLM3 和 Qwen 的 agent，使其工作更稳定
- 更新 Streamlit WEBUI，更好的多会话支持
- chatchat 主服务发布到 pypi
- 其它更多细节更新，请自行探索

**Comment by a442509097** [comment]
> v0.3.0最新版本代码已经push到pre-release分支，已支持glm4和qwen2，文档完善中，大家有兴趣的话可以参考以下链接试试看，如果有bug反馈会优先处理
> 
> https://github.com/chatchat-space/Langchain-Chatchat/blob/pre-release/libs/chatchat-server/README.md
> 
> 0.3.0 主要变化：
> 
> * 使用 model-provider 代替 fschat 提供模型服务，支持 fschat/xinference/ollama等框架
> * 移除对在线 API 模型的支持。可使用 oneapi 提供相关服务，在chatchat 中配置接入即可
> * 所有 chat 接口改造为兼容 openai
> * file rag增加bm25+embedding的ensemble retriever
> * 重写 ChatGLM3 和 Qwen 的 agent，使其工作更稳定
> * 更新 Streamlit WEBUI，更好的多会话支持
> * chatchat 主服务发布到 pypi
> * 其它更多细节更新，请自行探索

显示这个
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
autoawq 0.1.8 requires transformers>=4.35.0, but you have transformers 4.31.0 which is incompatible.
```
