### ISSUE TITLE
[BUG] 服务启动时的ERROR日志是什么原因

### ISSUE THREAD

**Issue by liujiachang** [chatchat-space/Langchain-Chatchat#4169]
**问题描述 / Problem Description**
通过fastchat启动服务后，日志每次都存在ERROR，但是我理解服务应该是正常启动了。

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/25957122/da7ca437-0597-4d43-8c5b-34a295026f3c)

**Comment by liunux4odoo** [comment]
fastchat 写的 log 代码有问题。
