### ISSUE TITLE
知识库加载doc文档出现问题

### ISSUE THREAD

**Issue by mazisuki** [chatchat-space/Langchain-Chatchat#4187]
**问题描述 / Problem Description**
utils.py[line:377] -ERROR: KeyError: 从文件  doc文档测试/doc_old.doc 加载文档时出错： "no relationship of type 'http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' in collection"
<img width="445" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/123860392/0114090a-47c6-499f-8581-874537f3c3ab">

**复现问题的步骤 / Steps to Reproduce**
前端添加文件到知识库时出错，pdf文件没有问题

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.2.10 / langchain-ChatGLM version/commit number: v0.2.10
- 是否使用 Docker 部署（是/否）：否 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): Qwen-1.5-32B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5 / Embedding model used (moka-ai/m3e-base, etc.): bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.11.7
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by mazisuki** [comment]
部分docx文件也会出错：cannot find loader for this WMF file

**Comment by ppzzhh** [comment]
将doc文件另存为docx文件试试
