### ISSUE TITLE
求教，希望LLM对话，知识库对话调用LLM的API能添加自定义请求头，请问在哪里修改好

### ISSUE THREAD

**Issue by WordLin** [chatchat-space/Langchain-Chatchat#4195]
**问题描述 / Problem Description**
自己部署了个大模型，但接口有些不同。希望在LLM对话和知识库问答，调用LLM的API的时候能够添加自定义请求头，但不知道在哪里配置，请问在哪里修改，添加好呢？

**Comment by codewen77** [comment]
请问如何解决。
