### ISSUE TITLE
[FEATURE] 简洁阐述功能 / 大语言模型单个apikey的qps太低，能否支持多个apikey轮训使用提高并发量

### ISSUE THREAD

**Issue by zhangmain666** [chatchat-space/Langchain-Chatchat#4196]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 /大语言模型单个apikey的qps太低，能否支持多个apikey轮训使用提高并发量

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / 申请多个第三方apikey，配置到项目配置文件，解决单个key的qps瓶颈

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / 暂无

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / 暂无

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / 暂无

**Comment by liunux4odoo** [comment]
本项目不支持模型调度。
