### ISSUE TITLE
[BUG] lite轻量部署，还是报No module named 'torch'依赖错误

### ISSUE THREAD

**Issue by Giftedcat** [chatchat-space/Langchain-Chatchat#4198]
**问题描述 / Problem Description**
使用了官方给到的-a --lite命令启动，结果还是报了torch库缺失的错误
```
$ pip install -r requirements_lite.txt
$ python startup.py -a --lite
```

**预期的结果 / Expected Result**
可以正常启动

**实际结果 / Actual Result**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/26926105/a5c60bb1-b3ac-400b-8a5b-eb0ab58885ac)

**环境信息 / Environment Information**
- 是否使用 Docker 部署（是/否）：是 
- 操作系统及版本：centos7.9
- Python 版本 / Python version:3.11.7

**附加信息 / Additional Information**
倒不是不能解决，只是服务器存储有限，能省一点是一点，想着可以轻量部署的话是最好的，不用下nvidia和pytorch了

**Comment by imClumsyPanda** [comment]
目前 0.3.0 版本已经没有 lite 版本，建议参考 README 安装最新版

**Comment by Giftedcat** [comment]
好的，感谢解答
