### ISSUE TITLE
[BUG] feedback的结果在哪里

### ISSUE THREAD

**Issue by gabrielpondc** [chatchat-space/Langchain-Chatchat#4204]
**问题描述 / Problem Description**
进行反馈后，反馈的结果在哪里记录或者查询

**复现问题的步骤 / Steps to Reproduce**
1. 执行 按赞的反馈
2. 点击 submit
3. 提交成功
4. 找不到反馈的结果

**预期的结果 / Expected Result**
应该找到反馈的内容或者类似于sqlite的文件等内容

**实际结果 / Actual Result**
找不到相关的文件

**环境信息 / Environment Information**
- langchain-ChatGLM 版本 v0.2.10
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu 24.04
- Python 版本 / Python version: 3.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
看 kb_config 中数据库的配置。

**Comment by Shujie-Wu** [comment]
你好，请问您是如何修改当前的代码，实现反馈的功能
