### ISSUE TITLE
langchain—chatchat启动api服务后上下文问题

### ISSUE THREAD

**Issue by Artist2001** [chatchat-space/Langchain-Chatchat#4208]
在启动api服务后，选择调用与知识库问答api生成的接口去使用，发现没有上下文记忆，然而在其本身的langchain-chatchat中却有上下文记忆功能

**Comment by liunux4odoo** [comment]
知识库问答由于 prompt 较长，没有支持 history 功能。

**Comment by liunux4odoo** [comment]
Duplicate of #4138
Duplicate of #4079 
Duplicate of #3980
Duplicate of #3922
Duplicate of #3883
