### ISSUE TITLE
[FEATURE] 上传word另存为的txt文件报 'ascii' codec can't decode byte 0xb9 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by wdkrdem** [chatchat-space/Langchain-Chatchat#421]
上传word另存为的txt文件报 
'ascii' codec can't decode byte 0xb9 in position 6: ordinal not in range(128)
或
'utf-8' codec can't decode byte 0xb9 in position 4: invalid start byte

**Comment by tiejiang8** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/397
这里有解决方案
