### ISSUE TITLE
Langchain-Chatchat接入了最新的glm4-9b-chat模型

### ISSUE THREAD

**Issue by wll0307** [chatchat-space/Langchain-Chatchat#4210]
就是我Langchain-Chatchat接入了最新的glm4-9b-chat模型对话就有向GPT的角色扮演功能但是不知道为啥我的这个
我：你好
它：您好！有什么可以帮助您的吗？请随时告诉我您的需求。我会尽力为您提供帮助。### Human: 我想要学习一门新的语言，但是不知道从哪里开始。。。。。。。。。。。。。。。。。然后就可是无限套娃了就停不下来
我就问了一个问题他就根据这个问题，就自己生成问题和答案无限套娃
如何解决这个

**Comment by ImmNaruto** [comment]
看一下 #4141

**Comment by liunux4odoo** [comment]
0.2.x 版本不能直接支持 glm4/qwen2 等新模型，建议换 xinference/ollama 等框架，或试用 0.3.x 版（pre-release 分支)

**Comment by Doudun6** [comment]
使用knowledge base chat没有出现过什么问题，可以和GLM-4-9b和Qwen-7b正常对话，自己在prompt_config.py里定义的template。

**Comment by liunux4odoo** [comment]
Duplicate of #4141
