### ISSUE TITLE
[FEATURE] 父文档检索

### ISSUE THREAD

**Issue by Jhmcforever** [chatchat-space/Langchain-Chatchat#4213]
我放进某法规，进行按条文分块后，由于某些条文块过大，提问时，无法匹配到很长的法条块，所以想尝试父文档检索。我可以从哪一块入手进行增删代码？或者有什么其他较好的方案吗？

**Comment by jsxyhelu** [comment]
表示关注，langchain应该也是提供了父文档搜索的

**Comment by liunux4odoo** [comment]
这种特定目的，需要自己去做文档切分和召回，通用方案是很难解决的。
