### ISSUE TITLE
导入.md文件后报错无法正确解析，提示common.py[line:601] - INFO: HTML element instance has no attribute type

### ISSUE THREAD

**Issue by guanhd** [chatchat-space/Langchain-Chatchat#4219]
我的TEXT_SPLITTER_NAME 配置为MarkdownHeaderTextSplitter，创建知识库，导入.txt文件能正确解析拆分内容，导入.md文件无法按markdown分隔符拆分，提示common.py[line:601] - INFO: HTML element instance has no attribute type
导入文件内容如下：
~~~~
# 1 标题
## 1.1 标题
### 1.1.1 标题
#### 1.1.1.1 标题
1.1.1.1 内容ffffffffffffff
# 2 标题
2 内容3343
## 2.2 标题
2.2 内容ggggggggggggggg
~~~~

**Comment by fengzengfly** [comment]
我也有这个问题，不过貌似好像解析成功了的，我知识库能正确回答

**Comment by fengzengfly** [comment]
只是不太清楚为什么会出现这个info
