### ISSUE TITLE
ModuleNotFoundError: No module named 'streamlit_option_menu'

### ISSUE THREAD

**Issue by Hotlat6077** [chatchat-space/Langchain-Chatchat#4228]
![Snipaste_2024-06-20_11-48-35](https://github.com/chatchat-space/Langchain-Chatchat/assets/52187584/cecba060-6a1b-4b95-acd0-c5c5e35a40de)

**Comment by Hotlat6077** [comment]
大佬们

**Comment by imClumsyPanda** [comment]
请问是否使用"pip install langchain-chatchat"方式安装项目？
