### ISSUE TITLE
缺少获取单个上传到知识库文档解析的内容的API

### ISSUE THREAD

**Issue by TaylorSwift5201314** [chatchat-space/Langchain-Chatchat#4229]
![1718858096190](https://github.com/chatchat-space/Langchain-Chatchat/assets/37954175/a45c8abd-ed80-447d-b685-0d8d774c069a)
如何获取单个上传的文档中的分析内容呢，在Swagger上没有看到对应的api呢

**Comment by liunux4odoo** [comment]
由于不同的向量库操作差异较大，现在向量库 API 都是以文件为整体的，不提供单个 chunk 的操作
