### ISSUE TITLE
[BUG] 用colab运行，无法加载模型，报错：'NoneType' object has no attribute 'message_types_by_name'

### ISSUE THREAD

**Issue by eleven-monkey** [chatchat-space/Langchain-Chatchat#423]
**问题描述 / Problem Description**
用colab运行，无法加载模型，报错：'NoneType' object has no attribute 'message_types_by_name'

**复现问题的步骤 / Steps to Reproduce**
我的colab笔记本如下：
```
# 拉取仓库
!git clone https://github.com/imClumsyPanda/langchain-ChatGLM.git
%cd /content/langchain-ChatGLM/
!pip install -r requirements.txt
!pip install gradio==3.28.3


#Download models
!git lfs install
%cd /content/langchain-ChatGLM
!git clone https://huggingface.co/THUDM/chatglm-6b-int4
!git clone https://huggingface.co/GanymedeNil/text2vec-large-chinese

#修改web.py和model_config.py文件
!sed -i 's/share=False/share=True/g' /content/langchain-ChatGLM/webui.py
!sed -i 's/GanymedeNil\/text2vec-large-chinese/\/content\/langchain-ChatGLM\/text2vec-large-chinese/g' /content/langchain-ChatGLM/configs/model_config.py
!sed -i 's/THUDM\/chatglm-6b-int4/\/content\/langchain-ChatGLM\/chatglm-6b-int4/g' /content/langchain-ChatGLM/configs/model_config.py
!sed -i 's/LLM_MODEL = "chatglm-6b"/LLM_MODEL = "chatglm-6b-int4"/g' /content/langchain-ChatGLM/configs/model_config.py

%cd /content/langchain-ChatGLM
!python webui.py
```
运行之后可以出现连接，打开后也可以显示webui，但提示模型未成功加载。colab笔记本最后一个cell的运行信息如下：
/content/langchain-ChatGLM
INFO  2023-05-21 07:02:28,810-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /content/langchain-ChatGLM
flagging username: 2c5e3b0147284178ac0bfe9d0ab382e6

Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
ERROR 2023-05-21 07:02:39,906-1d: 'NoneType' object has no attribute 'message_types_by_name'
Running on local URL:  http://0.0.0.0:7860/
Running on public URL: https://89b5153e349292fae6.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces

**Comment by GXKIM** [comment]
同样的问题路过

**Comment by coder-czw** [comment]
See this issue: https://github.com/imClumsyPanda/langchain-ChatGLM/issues/398
update protobuf to 3.19.6, it works for me on Colab

**Comment by kaikee-Snow** [comment]
> See this issue: #398 update protobuf to 3.19.6, it works for me on Colab

GOOD!升级以后完美解决
