### ISSUE TITLE
我想要加上問題優化的功能，我應該怎麼做?

### ISSUE THREAD

**Issue by tonto85144** [chatchat-space/Langchain-Chatchat#4234]
**功能描述 / Feature Description**
我想要在提出問題前，把問題先丟給AI補齊問題缺失的訊息得到一個更全面完整的問題後再提問，可以增加知識庫搜索的精度。

**解决的问题 / Problem Solved**
目前常常會遇到知識庫找不到答案的訊息，但可能只是我詞不達意或是換了個說法。

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

如果有人幫助我我會真心的感謝你!

**Comment by SwordHG** [comment]
先对query进行改写和扩增，并发检索就行
