### ISSUE TITLE
请问是否需要用到向量数据库？以及什么时候需要用到向量数据库？

### ISSUE THREAD

**Issue by alexhmyang** [chatchat-space/Langchain-Chatchat#424]
目前用的是 text2vec  ， 请问是否需要用到向量数据库？以及什么时候需要用到向量数据库？

**Comment by guotao** [comment]
我想知道向量数据是否可以保存，如何保存。

**Comment by Amoteamame** [comment]
很多向量库啊，向量数据库就是保存知识库的embedding结果，query的时候根据query去向量库中匹配topk.
