### ISSUE TITLE
0.3 版本是否能够支持 本地加载 embedding 模型

### ISSUE THREAD

**Issue by a136214808** [chatchat-space/Langchain-Chatchat#4244]
0.3 版本感觉用 其他平台加载embedding模型比较困难，是否能够继续支持本地加载embedding 模型

**Comment by yhfgyyf** [comment]
可以使用xinference加载本地embedding模型

**Comment by vincentyan2023** [comment]
> 可以使用xinference加载本地embedding模型

可否用ollama加载本地embedding模型？

**Comment by yhfgyyf** [comment]
> > 可以使用xinference加载本地embedding模型
> 
> 可否用ollama加载本地embedding模型？

ollama可以加载embedding模型，但是我不确定是否使用了openai 接口

**Comment by houliangxue** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58758212/930a7900-7ba4-4e22-9814-1225681dc747)
，使用ollama部署qwen-7b-chat模型，怎么修改model_providers.yaml呀？我按上图修改，报错connect erro
