### ISSUE TITLE
知识库添加太慢

### ISSUE THREAD

**Issue by zhanglaplace** [chatchat-space/Langchain-Chatchat#4246]
- 你好，这边添加知识库存在1w个左右的md文件，每个md文件大概拆分的splits_docs大概是50个，查看代码发现这边在使用多线程构建数据库的时候，是处理完文本embedding后都会去操作数据库；这会导致在后续写入过程中效率越来越低，想问下，是否可以在构建知识库的时候，先同步提取文档的特征、texts和metas后，一并写入数据库吗？这样子只会操作一次数据库。是否效率会更高效呢。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/12178974/799e01a8-b45d-4fd1-ade7-448c2ff5bada)

**Comment by liunux4odoo** [comment]
FAISS 不支持并发写入。你可以自己用不同的实现对比一下效率，欢迎反馈。

**Comment by zhanglaplace** [comment]
> FAISS 不支持并发写入。你可以自己用不同的实现对比一下效率，欢迎反馈。

嗯，是的，我这边后续是使用先split_docs后再提取Embedding，整体Embedding提取完成后一次构建Faiss的检索索引。大概1w个md文件处理耗时是1.5h。但是我只是自己实验，没有尝试动态更新。
