### ISSUE TITLE
刚部署的3.0版本，遇到一些问题

### ISSUE THREAD

**Issue by wz96cj** [chatchat-space/Langchain-Chatchat#4253]
1.请问如何设置/chat/chat/completions接口请求时的 max_tokens参数长度
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44886437/efad0504-40d5-4b0d-9119-c15f82c021e8)
尝试通过配置chatchat-config model --max_tokens 命令，还是无法修改
2.web界面 为何会出现重复的xinference
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44886437/558ee2b8-71b3-4fbe-8e94-08df97d99992)

**Comment by yhfgyyf** [comment]
删掉~/.config/chatchat 文件夹试下

**Comment by wz96cj** [comment]
> 删掉~/.config/chatchat 文件夹试下

我尝试删了 \root\.chatchat\workspace\workspace_config.json 中的 "MODEL_PLATFORMS"里的 xinference配置 可以了 所以这里的路径才是项目缓存的配置信息吗 请问问题1你知道怎么配置吗
