### ISSUE TITLE
知识库问答：当找回知识内容过多时候，模型回答为空，部分模型没问题部分存在问题

### ISSUE THREAD

**Issue by dingidng** [chatchat-space/Langchain-Chatchat#4265]
知识库问答：当找回知识内容过多时候，模型回答为空
- Qwen1.5-14B 当召回6条知识库内容时候，无结果返回
- Qwen1.5-7B 当召回6条知识库内容时候，有结果返回

>还是说可以修改prompt字符长度(prompt长度依赖原始本地模型能力还是说有地方修改)

**Comment by frankSARU** [comment]
这个问题我也遇到过，然后我打开另一个终端查看nvidia-smi可以看到，回答为空的时候显存是几乎吃满的。你的终端输出窗口应该会输出类似ERROR: TypeError: Caught exception: object of type 'NoneType' has no len() 这样的错误。这时它实际上的意思是你的显存被大量取回的内容吃满了，这个报错很容易让人误解。你可以选择在建立知识库的时候减小chunk size或者在webui减少历史对话轮数和匹配知识条数。至于你说的两个模型表现不同的现象，很明显是因为两个模型参数量级不同，所以占用显存大小自然不同。
