### ISSUE TITLE
qwen2_7b_instruct这个模型回答内容不完整

### ISSUE THREAD

**Issue by acbp1379** [chatchat-space/Langchain-Chatchat#4266]
![屏幕截图 2024-06-21 165313](https://github.com/chatchat-space/Langchain-Chatchat/assets/68890356/f155f8d8-b5d9-440f-8927-80db8b074f35)
像这个问题，后面明显还有答案。但是却在这个地方终止了。

**Comment by wz96cj** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/44886437/a29cb504-31d6-48a6-86ff-230c6b428194)
和我同样的问题，应该是请求时的max_token长度限制，但是没找到修改的地方

**Comment by lzt9746** [comment]
#4294
