### ISSUE TITLE
[BUG] 修改config配置时的问题。本人实力不高，勿喷。

### ISSUE THREAD

**Issue by yangtengze** [chatchat-space/Langchain-Chatchat#4270]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/162447928/f69b040a-8664-4ea3-bfb9-3c7934853533)
![屏幕截图 2024-06-21 222901](https://github.com/chatchat-space/Langchain-Chatchat/assets/162447928/5b69f96e-8e5e-481f-b633-9a55fb99bcfa)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/162447928/51c34ac1-25a5-4667-9868-ce4df74cac29)

### 这里在使用
```
chatchat-config model   --set_model_platforms TEXT 模型平台配置 as a JSON string.
```
的时候，要是在使用上面命令得时候能够像修改这个参数。
![ba05770ef44a6fae775f09831470d83](https://github.com/chatchat-space/Langchain-Chatchat/assets/162447928/1fa2e98a-bcd0-48e8-9297-7380b4a8488d)
改这个参数的时候能直接输入chatchat-config model   --set_model_platforms[1]['api_key'] = 'your_api_key'就好了.
不然是得全部带上是吗？

**Comment by liunux4odoo** [comment]
不能。
0.3.0 版本可以直接修改 ~/.chatchat 下的 json 文件。
