### ISSUE TITLE
centos7基于源码启动0.3版本报错-ModuleNotFoundError: No module named 'chatchat.server'

### ISSUE THREAD

**Issue by zhenlong-zhu** [chatchat-space/Langchain-Chatchat#4272]
**问题描述 / Problem Description**
在centos7部署langchain-chatchat0.3版本，想基于源码启动。下载源码，修改model_providers.yaml后，在Langchain-Chatchat/libs/chatchat-server/chatchat下初始化数据仓库：python init_database.py --recreate-vs
提示，没有chatchat.server模块：ModuleNotFoundError: No module named 'chatchat.server'
无法通过pip单独安装chatchat.server。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/20551179/cda0d85e-7a44-4c10-bfea-e9877721b712)

参考链接：https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md

**Comment by sangyuxiaowu** [comment]
windows 的dev也存在同样的问题，用pip安装的正式版也是报错，没办法用：openai.InternalServerError: Error code: 500 - {'detail': "[ollama] Error: Completions.create() got an unexpected keyword argument 'num_predict'"}

**Comment by sangyuxiaowu** [comment]
启动目录错了，要用  `python chatchat/startup.py -a`

**Comment by imClumsyPanda** [comment]
请执行"pip install langchain-chatchat"进行项目库安装

目前初始化知识库命令已经变更为 `chatchat-kb -r`，具体请参考 README.md。
