### ISSUE TITLE
[BUG] 3.0版本，配置为ollama，运行qwen1.5-32b报错

### ISSUE THREAD

**Issue by vincentyan2023** [chatchat-space/Langchain-Chatchat#4275]
3.0版本，配置为ollama，运行qwen1.5-32b，配置文件如下：
ollama:
  model_credential:
    - model: 'qwen-32b'
      model_type: 'llm'
      model_credentials:
        base_url: 'http://localhost:11434/v1'
        mode: ''
    - model: 'bge-large-zh'
      model_type: 'text-embedding'
      model_credentials:
        server_url: 'http://localhost:11434'
        model_uid: 'bge-large-zh' 

现象：输出答案后报错

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/153694218/08d8d452-2775-4d2e-9f9b-b38d6ab6fc41)

后台报错信息：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/153694218/3456d057-a9dd-498a-ae15-4fbcd376aa66)

**Comment by Pan06da** [comment]
1. pip install langchain-chatchat -U  先升级一下到最新的version
2. 激活环境后，在默认路径下，通过下面的配置加载Ollama 生效，你可以参考
chatchat-config model --set_model_platforms '[{    
    "platform_name": "ollama",
    "platform_type": "ollama",
    "api_base_url": "http://127.0.0.1:11434/v1",
    "api_key": "EMPT",
    "api_concurrencies": 5,
    "llm_models": [
        "qwen:32b"
    ],
    "embed_models": [
        "milkey/m3e"
    ],
    "image_models": [],
    "reranking_models": [],
    "speech2text_models": [],
    "tts_models": []
}]'

**Comment by 871052165** [comment]
我这里是无法设置，WINDOS平台报错如下:Error: Got unexpected extra argument (platform_name: ollama,platform_type: ollama,api_base_url: http://localhost:11434/v1, api_key: ollama,openai_proxy: ollama, api_concurrencies: 5,llm_models: [qwen2:0.5b],embed_models: [znbang/bge:large-en-v1.5-q4_k_m,milkey/m3e], image_models: [],reranking_models: [],speech2text_models: [],tts_models: []}])
