### ISSUE TITLE
初始化知识库问题

### ISSUE THREAD

**Issue by XiaoTongDeng** [chatchat-space/Langchain-Chatchat#4277]
我的默认模型为glm4-chat，但在chatchat-kb -r初始化知识库的时候，xinference拉起的服务报错ValueError: [address=xxx, pid=xxxx] Model not found in the model list, uid: qwen1.5-chat

{
    "DEFAULT_LLM_MODEL": "glm4-chat",
    "DEFAULT_EMBEDDING_MODEL": "bge-large-zh-v1.5",
    "Agent_MODEL": null,
    "HISTORY_LEN": 3,
    "MAX_TOKENS": null,
    "TEMPERATURE": 0.7,
    "SUPPORT_AGENT_MODELS": [
        "chatglm3-6b",
        "openai-api",
        "Qwen-14B-Chat",
        "Qwen-7B-Chat",
        "qwen-turbo"
    ],

**Comment by 9050350** [comment]
maybe you used other model and set the config of langchain-chatchat. when you init your chatchat kb : chatchat-kb -r. you should do it first : chatchat-kb -r --embed-model=text-embedding-3-small
