### ISSUE TITLE
 运行 chatchat -a 命令之后，点击下面0.0.0.0：7861的连接进去的是http://0.0.0.0:7861/docs ，没有出现 langchain-chatchat 的web页面，又没有报错，在readme看的要出现langchain-chatchat的web页面才是成功

### ISSUE THREAD

**Issue by cqray1990** [chatchat-space/Langchain-Chatchat#4278]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

运行 chatchat -a 命令之后，点击下面0.0.0.0：7861的连接进去的是http://0.0.0.0:7861/docs ，没有出现 langchain-chatchat 的web页面，又没有报错，在readme看的要出现langchain-chatchat的web页面才是成功

  Started server process [4104234]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)
2024-06-22 17:29:34.233 Port 8501 is already in use
INFO:     127.0.0.1:45668 - "GET / HTTP/1.1" 307 Temporary Redirect

8501 端口怎么说是已经被使用了

**Comment by Hoyxxx** [comment]
0.0.0.0换127.0.0.1试试
