### ISSUE TITLE
logging error

### ISSUE THREAD

**Issue by XiaoTongDeng** [chatchat-space/Langchain-Chatchat#4279]
--- Logging error ---
Traceback (most recent call last):
  File "E:\Anaconda\envs\xinference\lib\logging\handlers.py", line 73, in emit
    if self.shouldRollover(record):
  File "E:\Anaconda\envs\xinference\lib\logging\handlers.py", line 196, in shouldRollover
    msg = "%s\n" % self.format(record)
  File "E:\Anaconda\envs\xinference\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "E:\Anaconda\envs\xinference\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "E:\Anaconda\envs\xinference\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "E:\Anaconda\envs\xinference\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "E:\Anaconda\envs\xinference\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "E:\Anaconda\envs\xinference\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Anaconda\envs\xinference\lib\concurrent\futures\thread.py", line 83, in _worker
    work_item.run()
  File "E:\Anaconda\envs\xinference\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "E:\Anaconda\envs\xinference\lib\site-packages\xoscar\api.py", line 402, in _wrapper
    return next(_gen)
  File "E:\Anaconda\envs\xinference\lib\site-packages\xinference\core\model.py", line 301, in _to_json_generator
    for v in gen:
  File "E:\Anaconda\envs\xinference\lib\site-packages\xinference\model\llm\utils.py", line 544, in _to_chat_completion_chunks
    for i, chunk in enumerate(chunks):
  File "E:\Anaconda\envs\xinference\lib\site-packages\xinference\model\llm\pytorch\chatglm.py", line 173, in _stream_generator
    for chunk_text, _ in self._model.stream_chat(
  File "E:\Anaconda\envs\xinference\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\DengXiaoTong\.cache\huggingface\modules\transformers_modules\glm4-chat-pytorch-9b\modeling_chatglm.py", line 1012, in stream_chat
    for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
  File "E:\Anaconda\envs\xinference\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "C:\Users\DengXiaoTong\.cache\huggingface\modules\transformers_modules\glm4-chat-pytorch-9b\modeling_chatglm.py", line 1061, in stream_generate
    logger.warn(
Message: 'Both `max_new_tokens` (=256) and `max_length`(=659) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)'
Arguments: (<class 'UserWarning'>,)

**Comment by hkxxxxx** [comment]
I met the same error and haven't solved.

**Comment by XiaoTongDeng** [comment]
> I met the same error and haven't solved.

i guess it is a problem in xinference instead of chatchat,because when i only use xinference to chat with glm4-chat the terminate give the same error.However,the error dont block us to use llm,so i think we can ignore it ?

**Comment by hkxxxxx** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/77883069/32518190-a24d-49a4-93b4-7a8d18e1ffa2)
I think this error still need to be addressed because in the case above, it did not complete the response, which can negatively impact the user experience.

**Comment by XiaoTongDeng** [comment]
> ![image](https://private-user-images.githubusercontent.com/77883069/342042459-32518190-a24d-49a4-93b4-7a8d18e1ffa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzA1ODMsIm5iZiI6MTcxOTEzMDI4MywicGF0aCI6Ii83Nzg4MzA2OS8zNDIwNDI0NTktMzI1MTgxOTAtYTI0ZC00OWE0LTkzYjQtN2E4ZDE4ZTFmZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA4MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlODBiMWEwZjUzNjdjZWMxZTRhMWMyN2YxNGQ3NmUzYWRjMWIxMTEwMmFjZjUzYmQ3MzYwZjQ1ZjhiNmNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UV-DykY9qnUU5hv2iRs3E_s-C-HrQ5SIzr6Q5A8yt4Q) I think this error still need to be addressed because in the case above, it did not complete the response, which can negatively impact the user experience.

which model are u using?

**Comment by hkxxxxx** [comment]
> > ![image](https://private-user-images.githubusercontent.com/77883069/342042459-32518190-a24d-49a4-93b4-7a8d18e1ffa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzA1ODMsIm5iZiI6MTcxOTEzMDI4MywicGF0aCI6Ii83Nzg4MzA2OS8zNDIwNDI0NTktMzI1MTgxOTAtYTI0ZC00OWE0LTkzYjQtN2E4ZDE4ZTFmZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA4MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlODBiMWEwZjUzNjdjZWMxZTRhMWMyN2YxNGQ3NmUzYWRjMWIxMTEwMmFjZjUzYmQ3MzYwZjQ1ZjhiNmNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UV-DykY9qnUU5hv2iRs3E_s-C-HrQ5SIzr6Q5A8yt4Q) I think this error still need to be addressed because in the case above, it did not complete the response, which can negatively impact the user experience.
> 
> which model are u using?

glm4-9b-chat

**Comment by XiaoTongDeng** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/77883069/342042459-32518190-a24d-49a4-93b4-7a8d18e1ffa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzA1ODMsIm5iZiI6MTcxOTEzMDI4MywicGF0aCI6Ii83Nzg4MzA2OS8zNDIwNDI0NTktMzI1MTgxOTAtYTI0ZC00OWE0LTkzYjQtN2E4ZDE4ZTFmZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA4MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlODBiMWEwZjUzNjdjZWMxZTRhMWMyN2YxNGQ3NmUzYWRjMWIxMTEwMmFjZjUzYmQ3MzYwZjQ1ZjhiNmNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UV-DykY9qnUU5hv2iRs3E_s-C-HrQ5SIzr6Q5A8yt4Q) I think this error still need to be addressed because in the case above, it did not complete the response, which can negatively impact the user experience.
> > 
> > 
> > which model are u using?
> 
> glm4-9b-chat

i find if u use xinference in Linux system the error could be avoided

**Comment by XiaoTongDeng** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/77883069/342042459-32518190-a24d-49a4-93b4-7a8d18e1ffa2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxMzA1ODMsIm5iZiI6MTcxOTEzMDI4MywicGF0aCI6Ii83Nzg4MzA2OS8zNDIwNDI0NTktMzI1MTgxOTAtYTI0ZC00OWE0LTkzYjQtN2E4ZDE4ZTFmZmEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDA4MTEyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlODBiMWEwZjUzNjdjZWMxZTRhMWMyN2YxNGQ3NmUzYWRjMWIxMTEwMmFjZjUzYmQ3MzYwZjQ1ZjhiNmNiYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UV-DykY9qnUU5hv2iRs3E_s-C-HrQ5SIzr6Q5A8yt4Q) I think this error still need to be addressed because in the case above, it did not complete the response, which can negatively impact the user experience.
> > 
> > 
> > which model are u using?
> 
> glm4-9b-chat

u can refer to another reply https://github.com/huggingface/transformers/issues/22636
