### ISSUE TITLE
本地python，如何调用远端服务器的“本地知识库”对话？ 有示例吗？

### ISSUE THREAD

**Issue by lettergod** [chatchat-space/Langchain-Chatchat#4287]
远程服务器0.3版本已经安装完成，用web方式可以正常使用。
在自己电脑上，用python如何调用远程服务器上的"本地知识库“接口访问，有python的例子吗？

**Comment by lettergod** [comment]
是[https://github.com/chatchat-space/Langchain-Chatchat/blob/master/libs/chatchat-server/tests/api/test_stream_chat_api.py](url)这个吗？
运行 def test_knowledge_chat(api="/chat/knowledge_base_chat"): 这部份代码后
如果指定web端口:8501，运行结果：返回<Response [403]>
如果指定api端口:7861，运行结果：返回<Response [404]>

**Comment by liunux4odoo** [comment]
https://github.com/chatchat-space/Langchain-Chatchat/blob/dev/docs/contributing/api.md

**Comment by lettergod** [comment]
梦里寻她千百度

**Comment by SquareMask** [comment]
knowledge_base_chat这个接口现在没了吗，api文档里没看到

**Comment by SquareMask** [comment]
http://127.0.0.1:7861/docs#/里也没有 测试调用也没有
