### ISSUE TITLE
Ollama 模型接入发生报错

### ISSUE THREAD

**Issue by SWT-AITeam** [chatchat-space/Langchain-Chatchat#4289]
**问题描述 / 当使用Ollama调用llama3模型是报错**
用简洁明了的语言描述这个问题 / 使用ollama报错.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 /模型正常返回大模型回答的结果

**实际结果 / Actual Result**
ERROR    Error while creating chat completion: [ollama] Error: Completions.create() got an unexpected keyword argument 'num_predict'
2024-06-23 22:14:06,985 uvicorn.access 248 INFO     127.0.0.1:55109 - "POST /ollama/v1/chat/completions HTTP/1.1" 500
2024-06-23 22:14:06,988 httpx        23468 INFO     HTTP Request: POST http://127.0.0.1:20000/ollama/v1/chat/completions "HTTP/1.1 500 Internal Server Error"

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：llama3
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：~
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： ~
- 操作系统及版本 / Operating system and version: win11
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by SWT-AITeam** [comment]
使用zhipu模型不会报错，ollama报错，求帮助！！！

**Comment by maceygo** [comment]
同样的报错

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，可以更新尝试。
