### ISSUE TITLE
怎么能让正在回答的大模型停止回答 ，并且不影响其他的并发回答

### ISSUE THREAD

**Issue by Lee-Array** [chatchat-space/Langchain-Chatchat#4292]
使用版本：0.2.x
1.要求：我的目标是在其他服务调用我们的聊天项目时，能够通过一个专门的接口来实现对大型语言模型回答过程的即时终止。确保服务可以根据用户需求或系统状态灵活调整模型的行为。

2.尝试：我已经尝试使用了stop_llm_model接口，但发现它执行的操作过于粗放——该接口会完全关闭整个语言模型，而非仅仅中止正在进行中的某个特定会话或回答。这显然不符合您对于精准控制的要求。
说明：请给一个实现思路或者大致的方向  如果有现有接口 那更好了

**Comment by bennyji** [comment]
同求
