### ISSUE TITLE
关于源码安装的配置相关流程,不是很明白

### ISSUE THREAD

**Issue by wang-sheng-pu1002** [chatchat-space/Langchain-Chatchat#4297]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/51901366/df037f19-c4bc-400c-a982-0612971028bb)

chatchat-config由ConfigWorkSpace接口提供知识库配置载入存储

具体实现可以参考basic_config.py
这部分在源码启动的时候怎么去指定配置文件,怎么创建配置文件?.chatchat/workspace/workspace_config.json需要手动创建吗?
还是说源码启动的时候配置都需要写到代码里?

**Comment by songboxue** [comment]
我是执行python config_work_space.py，和文档中“以Python 库形式的安装方式”，执行的chatchat-config命令效果一样。对应着将模型、知识库都配置完成后，执行start.py即可启动。

**Comment by ZeroCc7** [comment]
源码启动的流程要参考 https://github.com/chatchat-space/Langchain-Chatchat/blob/dev/docs/contributing/README_dev.md ， 后续就可以直接修改workspace_config.json  生效了。
