### ISSUE TITLE
0.3.0启动后的WEB UI界面中的工具选项有哪些？为什么没有LLM对话选项？

### ISSUE THREAD

**Issue by buaamy** [chatchat-space/Langchain-Chatchat#4299]
![0 3 0界面](https://github.com/chatchat-space/Langchain-Chatchat/assets/38455030/68302f31-a12c-4ce7-bb48-e9f65e48dc72)

**Comment by Hoyxxx** [comment]
默认的应该就是吧

**Comment by liunux4odoo** [comment]
readme 里都写了。。。
