### ISSUE TITLE
[BUG] 必要包缺失

### ISSUE THREAD

**Issue by yangjun19950118** [chatchat-space/Langchain-Chatchat#4301]
3.0 新建知识库后,导入excl,向量的时候会提示缺少No module named 'openpyxl',导入word时提示:No module named 'docx'以及No module named 'exceptions',这些必要包是不是需要提前安装,能否提供

**Comment by glide-the** [comment]
这些包是第三方工具中的依赖，我们为了整体项目的稳定，排除了这些非必要的软件包
