### ISSUE TITLE
0.3.0 中本地模型如何设置 Max Tokens 

### ISSUE THREAD

**Issue by zhubao315** [chatchat-space/Langchain-Chatchat#4305]
webui对话总被截断，如何设置 Max Tokens

模型平台：xinference
LLM模型：autodl-tmp-glm-4-9b-chat

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/1206487/51773ddd-2104-48b8-b38a-cb437ccbc1b1)

**Comment by glide-the** [comment]
chatchat-config命令有描述
