### ISSUE TITLE
修改默认的向量库bug

### ISSUE THREAD

**Issue by GXKIM** [chatchat-space/Langchain-Chatchat#4313]
chatchat-config kb  --set_default_vs_type "milvus"
报错找不到参数set_default_vs_type
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125621025/8bc194a2-28a4-4ad2-93b6-0976ab3bac79)

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/125621025/7a1db404-3308-4ec8-837d-91f673ff2682)

**Comment by ywancit** [comment]
/chatchat-server/chatchat/configs/_kb_config.py
188行做如下更改          
 ######## default_vs_type=kwargs["set_default_vs_type"]
 vs_type = kwargs["set_default_vs_type"]
就可以了，代码出bug了，函数的参数名没有对上，输入给的参数名default_vs_type接收的地方是vs_type

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
