### ISSUE TITLE
0.2版本的knowledge_base_chat接口未在0.3中找到

### ISSUE THREAD

**Issue by blvyoucan** [chatchat-space/Langchain-Chatchat#4320]
**功能描述 / Feature Description**
0.2版本中我们用chat/knowledge_base_chat接口，似乎找不到替代的接口

**解决的问题 / Problem Solved**
0.2的接口在0.3中找不到

**实现建议 / Implementation Suggestions**
希望能按0.2的参数和响应实现一样功能的接口

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
无

**Comment by imClumsyPanda** [comment]
已统一修改为chat接口

**Comment by blvyoucan** [comment]
> 已统一修改为chat接口

比方说我有一个“test”的知识库，该如何调用？
