### ISSUE TITLE
创建知识库，插入文档调用embbding接口报错，Retrying request to /embeddings 

### ISSUE THREAD

**Issue by yangy996** [chatchat-space/Langchain-Chatchat#4323]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15188456/bd89f77f-694d-48f4-9055-1e541b3131bb)

xinference中已经部署了“bge-large-zh-v1.5”模型，如图：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15188456/34023873-5856-4653-a013-52751504e9bb)

而且创建知识库的时候，还好出现这个错误：
出现es创建索引失败
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15188456/328840de-2524-4183-a29b-39acdc66e74b)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
