### ISSUE TITLE
同一个知识库，向量库使用faiss，正常回答，使用pg，检索不到文件

### ISSUE THREAD

**Issue by lrw-lee** [chatchat-space/Langchain-Chatchat#4325]
pg:
<img width="835" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/33407226/67ca65e4-a3f6-400f-aa65-0c766c81dcb5">
faiss:
<img width="916" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/33407226/5746b8a6-0dce-4897-93f1-9eac3963b7d3">

**Comment by dongkuang** [comment]
同样问题，附议，请兄弟们帮助！

**Comment by frankSARU** [comment]
我的问题和您正好相反，同样的文档，用chormadb格式可以检索到回答，但是faiss不能匹配

**Comment by yhfgyyf** [comment]
pg向量库，先把阈值改高

**Comment by sugar5727** [comment]
> pg向量库，先把阈值改高

调到1都没用

**Comment by sugar5727** [comment]
通过调试发现
使用 pg 向量库时调用的参数 `_model_config.py` 中 `self.TOOL_CONFIG` 项，而非 `_kb_config.py` 中的 `__init__` 项
并且 当 `score_threshold` 过大时 pg 会匹配不到相关内容
综上， 修改 `_model_config.py` 中 `self.TOOL_CONFIG` 会解决该问题
```python
"search_local_knowledgebase": {
                "use": False,
                "top_k": 5,
                "score_threshold": 0.5,
                "conclude_prompt": {
                    "with_result":
                        '<指令>根据已知信息，简洁和专业的来回答问题。如果【已知信息】是“没有找到文档”，请在回答开始用“知识库中不存在此类问题，该回答由大模型自身能力生成”说明，不允许在答案中编造成分，答案请使用中文。 </指令>\n'
                        '<已知信息>{{ context }}</已知信息>\n'
                        '<问题>{{ question }}</问题>\n',
                    "without_result":
                        '请你根据我的提问回答我的问题:\n'
                        '{{ question }}\n'
                        '请注意，你必须在回答结束后强调，你的回答是根据你的经验回答而不是参考资料回答的。\n',
                }
            },
```

**Comment by lrw-lee** [comment]
@sugar5727 上传excel文件，还是检索不到文档

**Comment by sugar5727** [comment]
> @sugar5727 上传excel文件，还是检索不到文档

你可以调用api看看数据库中是否有文档

**Comment by Atomthin** [comment]
@sugar5727 上传excel文件，还是检索不到文档
你应该修改你的home目录下的workspace_config.json中的配置，可以通过命令行，也可以通过直接编辑这个文件的方式实现

**Comment by Atomthin** [comment]
@lrw-lee 你应该修改你的home目录下的workspace_config.json中的配置，可以通过命令行，也可以通过直接编辑这个文件的方式实现
