### ISSUE TITLE
首页的交流群入口均已失效

### ISSUE THREAD

**Issue by dohooo** [chatchat-space/Langchain-Chatchat#4326]
<img width="735" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/32405058/b03b6198-4a66-4301-9ab1-7f144a0e43b1">

- 微信群已超过200人，无法申请，需要群主邀请才可以，是否可以开2群？
- tg无法加入

**Comment by imClumsyPanda** [comment]
微信群二维码经测试可以正常使用，建议再试一下。
