### ISSUE TITLE
SCORE_THRESHOLD修改无效，改成别的数后，还是1.0

### ISSUE THREAD

**Issue by yangy996** [chatchat-space/Langchain-Chatchat#4327]
通过命令修改改参数：
chatchat-config kb --set_score_threshold 0.3
workspace_config.json文件中的值也变的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15188456/80c01c3c-46be-41e5-a90f-892a7bc30651)

但是，查询的时候，改值还是1.0
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/15188456/ecffc5fe-2438-42b0-ab62-7ad2ffe38faf)

**Comment by liunux4odoo** [comment]
改完之后重启服务器了吗？

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
