### ISSUE TITLE
0.3版本中关于chatchat-config修改参数的问题咨询

### ISSUE THREAD

**Issue by lizhao-8202** [chatchat-space/Langchain-Chatchat#4328]
本机发布了ollama，运行有llama3:8b,nomic-embed-tet:latest和qwen:7b模型
Langchain-Chatchat使用0.3版本

想咨询3问题：
1，README.md中，3.3 通过chatchat-config model命令修改配置 和4 自定义模型接入配置，是否只需要采取一种方式。
2，通过chatchat-config model 修改模型配置 比如chatchat-config model  --set_model_platforms "[{  \"llm_models\": [ \"autodl-tmp-glm-4-9b-chat\" ],\"embed_models\": [ \"bge-large-zh-v1.5\" ], }]" 这里的llm_models如果是qwen:7b，embed_modes如果是nomic-embed-tet:latest。对应配置是否应该为chatchat-config model  --set_model_platforms "[{  \"llm_models\": [ \"qwen:7b\" ],\"embed_models\": [ \"[bge-large-zh-v1.5](nomic-embed-tet:latest)\" ], }]" 
3，README.md中4 自定义模型接入配置里，model_providers.yaml 中的model是否需要配带参数的模型名字还是只是配模型，对于ollama的片段配置，看了下模板里只有model_type为llm的，是否还需要配置一个type为text-embedding的model配置

**Comment by Pan06da** [comment]
我是基于macbook的，
1. pip install langchain-chatchat -U  先升级一下到最新的version
2. 激活环境后，在默认路径下，通过下面的配置加载Ollama 生效，你可以参考
chatchat-config model --set_model_platforms '[{    
    "platform_name": "ollama",
    "platform_type": "ollama",
    "api_base_url": "http://127.0.0.1:11434/v1",
    "api_key": "EMPT",
    "api_concurrencies": 5,
    "llm_models": [
        "qwen:32b"
    ],
    "embed_models": [
        "milkey/m3e"
    ],
    "image_models": [],
    "reranking_models": [],
    "speech2text_models": [],
    "tts_models": []
}]'

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
