### ISSUE TITLE
如何为知识库的切片文件增加附加属性

### ISSUE THREAD

**Issue by XiaoTongDeng** [chatchat-space/Langchain-Chatchat#4329]
根据我的观察，知识库中返回的文件切片内容为{'page_content':'xxxx', 'metadata':{'source':文件路径,'id':切片id},'type':文件类型,'id':文件id,'score':评分}。如果我要为它增加新的key-value，应该在哪个文件下进行修改。

**Comment by blizzardwj** [comment]
你是下载源码自己开发，还是从pip安装的？

**Comment by XiaoTongDeng** [comment]
> 你是下载源码自己开发，还是从pip安装的？

pip安装的，在包安装位置哪个文件下进行修改呢。
