### ISSUE TITLE
部署启动小问题，小弟初学求大佬解答

### ISSUE THREAD

**Issue by MiracleCatcher** [chatchat-space/Langchain-Chatchat#433]
1.python loader/image_loader.py时，提示ModuleNotFoundError: No module named 'configs'，但是跑python webui.py还是还能跑
2.跑python webui.py的时候，报8bit 模型需要 CUDA 支持，或者改用量化后模型！请问如何更改模型呢，在哪里配置 求大佬解答

**Comment by suntao-china** [comment]
pip uninstall configs
pip uninstall config
避免命名空间污染

**Comment by npbcts** [comment]
针对问题2: 模型配置文件的位置在 README.md 文件中 [开发部署部分](https://github.com/imClumsyPanda/langchain-ChatGLM#2-%E8%AE%BE%E7%BD%AE%E6%A8%A1%E5%9E%8B%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0)提到, [configs/model_config.py](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/configs/model_config.py)

针对问题1: 不知道你单独执行`python loader/image_loader.py`的目的；由于`loader`文件夹和`configs`文件夹平行，执行你的脚本命令会提示你所说的错误；可以查下 python 模块调用相关知识。
启动这个项目只需执行`python webui.py`或README.md中的另外两种方法即可。

**Comment by MiracleCatcher** [comment]
> pip uninstall configs pip uninstall config 避免命名空间污染

感谢感谢

**Comment by MiracleCatcher** [comment]
> 针对问题2: 模型配置文件的位置在 README.md 文件中 [开发部署部分](https://github.com/imClumsyPanda/langchain-ChatGLM#2-%E8%AE%BE%E7%BD%AE%E6%A8%A1%E5%9E%8B%E9%BB%98%E8%AE%A4%E5%8F%82%E6%95%B0)提到, [configs/model_config.py](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/configs/model_config.py)
> 
> 针对问题1: 不知道你单独执行`python loader/image_loader.py`的目的；由于`loader`文件夹和`configs`文件夹平行，执行你的脚本命令会提示你所说的错误；可以查下 python 模块调用相关知识。 启动这个项目只需执行`python webui.py`或README.md中的另外两种方法即可。

感谢感谢

**Comment by IcingTomato** [comment]
安装 里面提到需要运行 `python loader/image_loader.py`

[https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/docs/INSTALL.md](url)

**Comment by IlIIIIIIlI** [comment]
> 安装 里面提到需要运行 `python loader/image_loader.py`
> 
> [https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/docs/INSTALL.md](url)

确实。
“# 验证paddleocr是否成功，首次运行会下载约18M模型到~/.paddleocr
$ python loader/image_loader.py“

最后”注：使用 langchain.document_loaders.UnstructuredFileLoader 进行非结构化文件接入时，可能需要依据文档进行其他依赖包的安装，请参考 [langchain 文档](https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/unstructured_file.html)。“
其实就是确保python版本为3.10以上就行。
