### ISSUE TITLE
关于embedding的两个疑问

### ISSUE THREAD

**Issue by lingyezhixing** [chatchat-space/Langchain-Chatchat#4345]
1. chatchat-config model 中 "DEFAULT_EMBEDDING_MODEL": "bge-large-zh-v1.5"和平台配置里的"embed_models": []是什么关系？DEFAULT_EMBEDDING_MODEL是从平台配置里选择其中一个吗？
2. 我尝试使用ollama提供embedding，但是总是报错。ollama的模型命名含有冒号，这个名字在windows上无法创建文件夹，是否是这个原因导致无法创建数据库？

**Comment by imClumsyPanda** [comment]
@lingyezhixing 

1. 是的 DEFAULT_EMBEDDING_MODEL 应该是平台配置 embedding 模型中的一个
2. 该问题开发组已经了解到，正在解决。

**Comment by lingyezhixing** [comment]
> @lingyezhixing
> 
> 1. 是的 DEFAULT_EMBEDDING_MODEL 应该是平台配置 embedding 模型中的一个
> 2. 该问题开发组已经了解到，正在解决。

关于第二个问题我找到了一个规避的方法，将embedding重命名为不含冒号的名字即可，虽然ollama还是会加上“:latest”后缀，但是直接使用重命名后的名字可以正常调用

**Comment by lingyezhixing** [comment]
> @lingyezhixing
> 
> 1. 是的 DEFAULT_EMBEDDING_MODEL 应该是平台配置 embedding 模型中的一个
> 2. 该问题开发组已经了解到，正在解决。

关于第二个问题有一个可以规避的方法，将embedding重命名为不含冒号的名字即可，虽然ollama还是会加上“:latest”后缀，但是直接使用重命名后的名字可以正常调用

**Comment by Qi0716** [comment]
如何ollama重命名哇?

**Comment by ftrako** [comment]
> 如何ollama重命名哇?

同问

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

**Comment by lingyezhixing** [comment]
> 如何ollama重命名哇?

ollama教程里不是有从modelfile创建新模型吗？利用这个创建一个新名字的模型，再删除原模型，不就是变相重命名了吗？
