### ISSUE TITLE
v0.3 不支持多轮问答吗？V0.2 agent是支持多轮问答的吧，这个怎么取消了

### ISSUE THREAD

**Issue by houliangxue** [chatchat-space/Langchain-Chatchat#4348]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/58758212/fc91ef45-3291-452b-a630-4f1be1fd5123)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，RAG对话支持多轮，可以更新尝试。
