### ISSUE TITLE
求助"MODEL_PROVIDERS_CFG_PATH_CONFIG": "TEXT",     "MODEL_PROVIDERS_CFG_HOST": "127.0.0.1",     "MODEL_PROVIDERS_CFG_PORT": 20000,阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by Hoyxxx** [chatchat-space/Langchain-Chatchat#4350]
"MODEL_PROVIDERS_CFG_PATH_CONFIG": "TEXT"   这里原本是啥啊，不小心改成TEXT了，求助

**Comment by liudong-ch** [comment]
"MODEL_PROVIDERS_CFG_PATH_CONFIG": "/home/anaconda3/envs/new-langchain/lib/python3.11/site-packages/chatchat/configs/model_providers.yaml",

**Comment by Hoyxxx** [comment]
> "MODEL_PROVIDERS_CFG_PATH_CONFIG": "/home/anaconda3/envs/new-langchain/lib/python3.11/site-packages/chatchat/configs/model_providers.yaml",

谢谢谢谢
