### ISSUE TITLE
[BUG] chatchat 重启后出现了 找不到知识库的情况

### ISSUE THREAD

**Issue by suiquantong** [chatchat-space/Langchain-Chatchat#4354]
**问题描述 / Problem Description**
当我将我的langchain chatchat 服务重启后 本地的知识库都会消失 

**复现问题的步骤 / Steps to Reproduce**
1. 重启chatchat 
2. 点击知识库 

3.如果点击一下 依据源文件重建向量库 即可恢复 这是一个bug 
**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/37520861/49f4dd7e-73c1-40c9-904e-2308409f6e9c)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4-9b-Chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:  linux
- Python 版本 / Python version: 3.11

**Comment by cccomego** [comment]
我的也出现了带有`@` 符号的知识库找不到的情况

**Comment by jiusi9** [comment]
> 我的也出现了带有`@` 符号的知识库找不到的情况

kb的目录没有做持久化吧，0.2版本的目录是Langchain-ChatChat/knowledge_base

**Comment by chinaperrin** [comment]
我也存在着样的问题，在数据目录下knowledge_base存在命名该知识库的文件夹（content和vector_store文件下都有内容），但是示例samples知识库存在。这是什么原因？

**Comment by jiusi9** [comment]
> 我也存在着样的问题，在数据目录下knowledge_base存在命名该知识库的文件夹（content和vector_store文件下都有内容），但是示例samples知识库存在。这是什么原因？

启动的时候是不是做了初始化， 应该是改变了知识库的配置路径了，检查一下

**Comment by bobo0311** [comment]
> > 我也存在着样的问题，在数据目录下knowledge_base存在命名该知识库的文件夹（content和vector_store文件下都有内容），但是示例samples知识库存在。这是什么原因？
> 
> 启动的时候是不是做了初始化， 应该是改变了知识库的配置路径了，检查一下
遇到相同的问题，没有初始化，重启之后，包括samples知识库里面新上传的文件在向量库中也找不到了

**Comment by bobo0311** [comment]
遇到相同的问题。重启之后，包括samples知识库中之前上传的文件，也无法在向量库中找到了
确定没有重新初始化过

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，经测试无此问题，可以更新尝试。
