### ISSUE TITLE
【chatchat-v0.2.10版本-lite启动-知识库匹配问题】请问下使用了lite方案，LLM和embedding模型都选择的qwen-turbo，启动和LLM问答正常，但是使用知识库问答，在使用了text-embedding-v1模型一直匹配不到知识库内容，使用本地模型和本地嵌入模型都是正常的。这是为啥呢

### ISSUE THREAD

**Issue by TonyHmx** [chatchat-space/Langchain-Chatchat#4357]
请问下使用了lite方案，LLM和embedding模型都选择的qwen-turbo，启动和LLM问答正常，但是使用知识库问答，在使用了text-embedding-v1模型一直匹配不到知识库内容，这是为啥呢
![problem](https://github.com/chatchat-space/Langchain-Chatchat/assets/39474055/189d1247-dbec-4e78-9eb9-9279b1838faa)

_Originally posted by @TonyHmx in https://github.com/chatchat-space/Langchain-Chatchat/issues/3100#issuecomment-2196299849_

**Comment by TonyHmx** [comment]
1.models配置是正常的
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39474055/4722a224-82da-4eae-936e-9ef3d85c3b06)
2.
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39474055/3df15acd-b328-41bd-9735-af06e3ca4849)

**Comment by TonyHmx** [comment]
打日志看到qwen.py中的do_embeddings方法也获取到向量数据了。
不清楚为什么知识库问答一直无法匹配到，
知识库本身也是使用faiss+qwen_api的方式
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/39474055/7237f30f-b249-4604-891b-d4a091ff0b1e)
求助~~~

**Comment by liunux4odoo** [comment]
0.2.x版本不再维护，0.3.1 版已经发布，优化了配置方式，可以更新尝试。
