### ISSUE TITLE
求助，有3个关于Langchain-Chatchat配置模型的疑问

### ISSUE THREAD

**Issue by BaoxingZhang** [chatchat-space/Langchain-Chatchat#4360]
1、`pip install langchain-chatchat -U` 这种形式安装的，在这个yaml中`/lib/python3.10/site-packages/chatchat/configs/model_providers.yaml`有如下配置：

<img width="1380" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/45478660/83593d09-f9d5-4c75-8a75-c17366c5c1b0">

2、在模型启动前，需要执行以下设置：

```
chatchat-config model --set_model_platforms "[{
    \"platform_name\": \"xinference\",
    \"platform_type\": \"xinference\",
    \"api_base_url\": \"http://127.0.0.1:9997/v1\",
    \"api_key\": \"EMPT\",
    \"api_concurrencies\": 5,
    \"llm_models\": [
        \"chatglm3\"
    ],
    \"embed_models\": [
        \"bge-large-zh-v1.5\"
    ],
    \"image_models\": [],
    \"reranking_models\": [],
    \"speech2text_models\": [],
    \"tts_models\": []
}]"
```

3、还有一个设置默认模型的地方：
```
chatchat-config model --default_llm_model chatglm3
```

而对应到Xinference之后会有模型ID、模型Name，当在Xinferenec上面注册模型的时候ID和Name可以不一致，这样的话对应关系稍微有些分不清楚，以及优先级。是否需要全部检查一遍，全部设置好之后再启动 Langchain-Chatchat

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，可以更新尝试。
