### ISSUE TITLE
initialize knowledge base failed

### ISSUE THREAD

**Issue by umbraclet16** [chatchat-space/Langchain-Chatchat#4362]
I registered an embedding model 'autodl-tmp-bge-large-zh' in xinference and configured it in /root/chatchat-data/model_providers.yaml to use custom platform loading.

Running command chatchat-kb -r failed.

relevant log:

model_providers.bootstrap_web.openai_bootstrap_web 2700 WARNING Warning: model not found. Using cl100k_base encoding.

Internet is unavailable so the default model cannot be downloaded.

I wonder if model_providers only supports builtin embedding models? Or did I miss any configuration?

Thx.

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
