### ISSUE TITLE
[BUG] 前端没有及时收到后端大模型SSE的分片消息

### ISSUE THREAD

**Issue by shiyf111** [chatchat-space/Langchain-Chatchat#4366]
**问题描述 / Problem Description**
0.3.0版本，使用星火大模型，stream流的方式，发现后端已经接收到大模型的多个steam输出，但是前端没有及时显示输出结果；在大模型输出完后，前端页面才显示结果，没有实时显示多个steam流的分片结果。
星火大模型存在该问题，其他的大模型没有测试，不确定是否存在相同问题。

**预期的结果 / Expected Result**
期望在大模型输出后，前端能及时更新页面，显示模型的输出结果

**附加信息 / Additional Information**
发现模型的websocket处理正常，可以实时接收到消息，但是在 openai_request 函数中没有实时接收到模型的stream输出，而是在模型输出完后，一次性接收到全部的stream分片结果：

![1](https://github.com/chatchat-space/Langchain-Chatchat/assets/26531880/c5629750-c523-4f0d-8cc6-0245b31b72a6)

**Comment by liunux4odoo** [comment]
你的星火是通过什么接入的？oneapi吗？

**Comment by shiyf111** [comment]
我是通过修改 model_providers.yaml 文件使用的

xinference:
  model_credential:
    - model: 'm3e-base'
      model_type: 'text-embedding'
      model_credentials:
        server_url: 'http://127.0.0.1:9997/'
        model_uid: 'm3e-base'

spark:
  model_credential:
    - model: 'spark-3.5'
      model_type: 'llm'
      model_credentials:
        app_id: 'xxxx'
        api_key: 'xxxx'
        api_secret: 'xxxx'

**Comment by Cnzboy** [comment]
same issue

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

0.3.x 中在线 API 建议通过 oneapi 接入。
