### ISSUE TITLE
[BUG] docker-compose部署上传知识文件向量化不成功

### ISSUE THREAD

**Issue by CyanMystery** [chatchat-space/Langchain-Chatchat#4371]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner. 

上传文件 没反应

**复现问题的步骤 / Steps to Reproduce** 
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

访问上传文件时只到这
kb_doc_api.py[line:111] - WARNING: 文件 beiying.txt 已存在。
2024-07-02 09:48:58,072 - utils.py[line:299] - INFO: UnstructuredFileLoader used for F:\python_project\Langchain-Chatchat\knowledge_base//33042501\my_knowledge_base\content\beiying.txt

到这的时候 apifox 显示socket hang up后，后续所有就没反应了，后续的所有请求都是connect ECONNREFUSED ，但是docker容器端口7861还在启动着

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v2.0.1 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v2.0.1 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM3-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.):bge-m3
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): milvus

- 操作系统及版本 / Operating system and version: ubuntu 22.04
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/51013526/79908113-a822-4a93-a3c5-88c1c0b238a9)

**Comment by CyanMystery** [comment]
langchain-chatchat:
    # 也可以从Dockerfile构建该服务镜像↓
#    image: chatchat
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    environment:
      TZ: Asia/Shanghai
    ports:
      - 7861:7861
    volumes:
      - .:/langchain-chatchat
    depends_on:
      - "milvus"
    command: /usr/bin/python3 startup.py --api

docker-compose 启动文件

**Comment by CyanMystery** [comment]
正常是SentenceTransformer.py[line:66] - INFO: Load pretrained SentenceTransformer: embed_model\bge-m3打印这个嵌入模型启动就可以向量化了 可是容器没有出现 后面所有请求都是connect ECONNREFUSED docker端口还开着

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

把 text_splitter_dict 中你选用分词器的 source/model_name_or_path 全部清空。
