### ISSUE TITLE
[BUG] 执行chatchat-config kb --set_default_vs_type milvus 修改配置时报错:  unexpected keyword argument 'default_vs_type'

### ISSUE THREAD

**Issue by 2345free** [chatchat-space/Langchain-Chatchat#4375]
**问题描述**
 执行chatchat-config kb --set_default_vs_type milvus 修改配置时报错:  
  File "/home/develop/miniconda3/envs/langchain-chatchat-0.3.0/lib/python3.11/site-packages/chatchat/config_work_space.py", line 187, in kb
    config_kb_workspace.set_default_vs_type(
TypeError: ConfigKbWorkSpace.set_default_vs_type() got an unexpected keyword argument 'default_vs_type'

**环境信息**
- langchain-ChatGLM 版本：0.3.0
- 是否使用 Docker 部署：否
- 使用的模型： Qwen2-7B-Instruct
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型： faiss
- 操作系统及版本: Ubuntu24.04
- Python 版本: conda python3.11

**Comment by jiusi9** [comment]
遇到了同样的问题

**Comment by fosfree** [comment]
改源码~
venv\LangChain03Demo\Lib\site-packages\chatchat\configs\_kb_config.py文件280行（左右）
修改前：
    def set_default_vs_type(self, vs_type: str):
        self._config_factory.DEFAULT_VS_TYPE = vs_type
        self.store_config()
修改后：
    def set_default_vs_type(self, default_vs_type: str):
        self._config_factory.DEFAULT_VS_TYPE = default_vs_type
        self.store_config()

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
