### ISSUE TITLE
多线程，多设备输入，页面提示“Bad 'setIn' index 6 (should be between [0, 1])”

### ISSUE THREAD

**Issue by chai991014** [chatchat-space/Langchain-Chatchat#4380]
多个设备同时输入，同一时间点击发送，返回结果报错，如下图。但是实际情况是后台llm返回的数据没问题，当点击关闭报错页面后，再一次输入时，上一轮的输出结果就显示出来了。
![328128196-4df4f8ab-bbf9-4077-a213-ebd7217147af](https://github.com/chatchat-space/Langchain-Chatchat/assets/97151084/20f0fd4c-c9ef-42ce-a340-d505cdc0db3d)

**复现问题的步骤 / Steps to Reproduce**
1. 通过autodl中的自定义服务的url实现多设备访问。
2. 两台设备同一时间输入对话并点击发送。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss

**Comment by liunux4odoo** [comment]
重复问题
