### ISSUE TITLE
数据库对话功能，如何配置 sqlserver 或者其他数据库

### ISSUE THREAD

**Issue by BenjaminXin** [chatchat-space/Langchain-Chatchat#4381]
**问题描述 / Problem Description**
要对接 sqlserver 数据库，实现数据库对话；没找到具体的配置方法

**Comment by CSYNARUTO** [comment]
你那边数据库也是没法读取吗？我用text2sql工具的时候数据库好像加载不上，直接打印数据库信息为空，导致后续也无法正常对话。

**Comment by LULU-LULULA** [comment]
> 你那边数据库也是没法读取吗？我用text2sql工具的时候数据库好像加载不上，直接打印数据库信息为空，导致后续也无法正常对话。

你好，请问你是怎么使用text2sql工具的，能详细说说吗？我和楼主一样没找到配置方法！
