### ISSUE TITLE
是否支持阿里云在线的 text-embedding-v2 和 qwen-plus 调用

### ISSUE THREAD

**Issue by Briskwind** [chatchat-space/Langchain-Chatchat#4387]
"MODEL_PLATFORMS": [
                {
                    "platform_name": "qianwen",
                    "platform_type": "qianwen",
                   "api_base_url": "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation",
                    "api_key": "sk-xxxxx",
                    "api_concurrencies": 5,
                    "llm_models": [
                        "qwen-plus"
                    ],
                    "embed_models": [
                        "text-embedding-v2"
                    ],
                    "image_models": [],
                    "reranking_models": [],
                    "speech2text_models": [],
                    "tts_models": []
                }
            ],

后提示：

^C2024-07-03 15:28:19,763 - before_sleep.py[line:65] - WARNING: Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised BadRequestError: Error code: 400 - {'code': 'BadRequest.IllegalInput', 'message': 'The input parameter requires json format.', 'request_id': '3ac46774-348f-9c34-bc4c-1855aafdb813'}.

**Comment by ihadu** [comment]
同问

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
在线 API 需要通过 oneapi 转接
