### ISSUE TITLE
不启动任何工具情况下直接对话，报“‘openai’ has no attribute 'NOT_GIVEN'”错误

### ISSUE THREAD

**Issue by mrkingsun** [chatchat-space/Langchain-Chatchat#4388]
大模型接的xinference的glm4-chat，工具选择知识库问答时倒是正常，但是直接进行大模型问答报“‘openai’ has no attribute 'NOT_GIVEN'”错误

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
