### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue上传60m的txt文件报错，显示超时，请问这个能上传的文件大小有限制吗

### ISSUE THREAD

**Issue by xiaochaich** [chatchat-space/Langchain-Chatchat#439]
ERROR 2023-05-23 11:13:09,627-1d: Timeout reached while detecting encoding for ./docs/GLM模型格式数据.txt
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ H:\duoduo\langchain-ChatGLM-master\cli_demo.py:56 in <module>               │
│                                                                             │
│   53                                                                        │
│   54                                                                        │
│   55 if __name__ == "__main__":                                             │
│ > 56 │   main()                                                             │
│   57                                                                        │
│                                                                             │
│ H:\duoduo\langchain-ChatGLM-master\cli_demo.py:33 in main                   │
│                                                                             │
│   30 │   │   # 判断 filepath 是否为空，如果为空的话，重新让用户输入,防止用  │
│   31 │   │   if not filepath:                                               │
│   32 │   │   │   continue                                                   │
│ > 33 │   │   vs_path, _ = local_doc_qa.init_knowledge_vector_store(filepath │
│   34 │   history = []                                                       │
│   35 │   while True:                                                        │
│   36 │   │   query = input("Input your question 请输入问题：")              │
└─────────────────────────────────────────────────────────────────────────────┘
TypeError: cannot unpack non-iterable NoneType object

**Comment by robator0127** [comment]
langchain 的安装目录，langchain的版本为0.0.174，langchain/document_loaders/help.py的 第37行，
detect_file_encodings(file_path: str, timeout: int = 5) -> List[FileEncoding]timeout: int = None，
上面函数中timeout 改为更大的值或为None
