### ISSUE TITLE
[BUG] 简洁阐述问题 //knowledge_base/update_docs_by_id  没法请求

### ISSUE THREAD

**Issue by zhuzongjian1** [chatchat-space/Langchain-Chatchat#4393]
/knowledge_base/update_docs_by_id  
这个接口的请求是
{
    "knowledge_base_name": "test"
        "additionalProp1": {
            "page_content": "This is the content of document 1.",
            "metadata": {},
            "type": "Document"
        },
        "additionalProp2": {
            "page_content": "This is the content of document 2.",
            "metadata": {},
            "type": "Document"
        },
        "additionalProp3": {
            "page_content": "This is the content of document 3.",
            "metadata": {},
            "type": "Document"
        }
    }
}
目前没法请求

**Comment by liunux4odoo** [comment]
这个接口有bug，并未正式使用。更新 docs 请使用 /update_docs 接口进行整体更新。
