### ISSUE TITLE
[BUG] 0.3版本知识库查询控制台报UserWarning: No relevant docs were retrieved using the relevance score threshold 1.0

### ISSUE THREAD

**Issue by bclovetkd** [chatchat-space/Langchain-Chatchat#4395]
**问题描述 / Problem Describption**
0.3版本知识库查询控制台报UserWarning: No relevant docs were retrieved using the relevance score threshold 1.0，向量库有知识库数据

**复现问题的步骤 / Steps to Reproduce**
1. 选择本地知识库工具
2. 输入问题

**预期的结果 / Expected Result**
返回与知识库有关的回答

**实际结果 / Actual Result**
1、参考资料是空的
2、回答：根据已知信息无法回答该问题。
3、后台报：/home/joel/anaconda3/envs/lccc03x/lib/python3.11/site-packages/langchain_core/vectorstores.py:342: UserWarning: No relevant docs were retrieved using the relevance score threshold 1.0

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.0
- 是否使用 Docker 部署：否
- 使用的模型：Qwen-7B
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型 ：pg_vector
- 操作系统及版本: ubuntu
- Python 版本: 3.11.9
- langchain版本：0.1.17
- 大模型平台：Xinference

不清楚是bug还是哪里的配置没配好

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
可以把 score_threshold 调高到 2.0 试试。
