### ISSUE TITLE
建议恢复使用配置文件的方式对模型知识库等参数进行配置

### ISSUE THREAD

**Issue by coolshibacoolshiba** [chatchat-space/Langchain-Chatchat#4397]
**功能描述 / Feature Description**
最新版本中仅能支持使用命令行形式来配置各项参数，但是存在如下问题：
1. 命令行中仍然使用json格式，在命令行中键入json不友好，会误输部分json格式特有字符
2. 无法纯粹依赖help中的提示完成配置，需要看readme文档，但文档中仅有一个简单示例，无法体现较为复杂的配置需求，无法体现比如增加一个配置等方式，例如我想在不同的平台跑模型，就无法用这样的配置实现

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

恢复到原先版本的可以依靠配置文件的方式即可

**Comment by ajiader** [comment]
确实如此

**Comment by liunux4odoo** [comment]
下个版本中将改用 yaml 配置文件，支持热加载。现在dev分支已经完成修改，欢迎测试反馈。

**Comment by psy-mas** [comment]
> 下个版本中将改用 yaml 配置文件，支持热加载。现在dev分支已经完成修改，欢迎测试反馈。

but when？
