### ISSUE TITLE
[FEATURE] 简洁阐述功能 / 3.0版本在哪里配置本地模型的地址？

### ISSUE THREAD

**Issue by NlMay** [chatchat-space/Langchain-Chatchat#4400]
3.0版本在哪里配置本地模型的地址？看到好像配置的都是线上的地址

**Comment by NlMay** [comment]
3.0版本在哪里配置本地模型的地址？看到好像配置的都是显示的地址

**Comment by jiusi9** [comment]
0.3版本把这个事交给langchain-chatchat调用的模型框架了，如果你用的xinference，可以把本地模型注册到xinference。
其他模型也类似

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
