### ISSUE TITLE
[BUG] 新建milvus 向量知识库，传入多个大文件后点击添加文件到知识库，一直在重复添加(v0.3.0)

### ISSUE THREAD

**Issue by JiadiLee** [chatchat-space/Langchain-Chatchat#4401]
**问题描述 / Problem Description**
新建milvus 向量知识库，传入4个180M左右的文件后，点击添加文件到知识库，后台一直显示在添加，24h后仍未停止

**复现问题的步骤 / Steps to Reproduce**
1. 在知识库管理界面点击新建知识库，向量库类型选择为milvus，embedding框架为xinference
2. 在上传知识文件的地方，选择3个160M的文件，1个180M的文件进行上传，文件格式都为正常的json文件
3. trunk-250，overlap-50，点击[添加文件到知识库]，查看后台开始embedding
4. 24h后后台仍在embedding，将chatchat -a启动的后台用crtl + c强行退出，重新启动
5. 在知识库管理界面，选中之前新建的知识库，点击[依据源文件重建向量库]进行测试

**预期的结果 / Expected Result**
利用[添加文件到知识库]应该能正常将embedding后的结果存入milvus向量库

**实际结果 / Actual Result**
1.利用[添加文件到知识库]，24h后后台仍然在进行embedding，查看前端知识库管理界面-知识库中已有文件，已经正常显示文档加载器和分词器的文件，又被重新添加了一遍，不确定是否由于[time out]的一些报错，导致了文件的重复添加。**在对话界面查询一直报"知识库中找不到对应信息"**
2.利用[依据源文件重建向量库]重新embedding并添加到向量库，操作正常，12h后向量全部保存完毕，**但是添加成功后发现向量库实际使用的为faiss**。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：edg-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： milvus
- 操作系统及版本 / Operating system and version: ubuntu20.04
- Python 版本 / Python version: python3.10
- 其他相关环境信息 / Other relevant environment information: chatchat和xinference安装在同一台机器，milvus安装在另一台机器，向量库之间正常通信

**Comment by tianxiajianghu** [comment]
post所有命令都使用的有默认超时，这个超时时间不长，大文件如果一致没上传完就会重复，可以在上传文件的时候修改超时时间就可以了，所有的修改都在这个里面Langchain-Chatchat/webui_pages/utils.py，针对的是0.2x版本,0.3应该也要找到这个文件修改就可以了。
1、先把这个默认的超时时间在这个文件定义出来
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50093942/2ac8367b-4c19-4a41-bc40-a414de3f238f)
2、给self.post函数添加超时的参数
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50093942/5f4f70e8-7bdd-4299-9400-d99695779b50)
3、在上传文件的地方设置超时时间，单位是秒
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50093942/fcf5d7a3-1267-4018-840a-6b71972c58ff)

**Comment by JiadiLee** [comment]
> post所有命令都使用的有默认超时，这个超时时间不长，大文件如果一致没上传完就会重复，可以在上传文件的时候修改超时时间就可以了

感谢回复，因为我没有在0.2版本用过milvus数据库，所以不确定这是否是个通用的问题，我会修改一下超时时间测试一下。
还有两个问题想咨询一下，谢谢：
1.faiss向量库并没有这个问题，200M以下的文件都能正常上传，这两个库在添加文件的处理上是有区别的吗？
2.在我已经创建milvus向量库，文件添加失败的情况下，点击【依据源文件重建向量库】会默认按照faiss向量库重新建库添加吗？

**Comment by tianxiajianghu** [comment]
1、这个改的是通用配置，和向量化的方式无关吧，我es也会出现这问题，如果没出现，我认为是加入faiss向量库速度太快，加入其他数据库速度慢，导致超时
2、数据库会记录你的参数，数据库的名字对应的配置一旦创建无法修改，还会按照你原来的配置重建，这是经验之谈，哈哈哈
