### ISSUE TITLE
0.3 还支持rerank不  配置文件貌似没有地方配置呢

### ISSUE THREAD

**Issue by ajiader** [chatchat-space/Langchain-Chatchat#4403]
config没有找到地方配置

**Comment by 634085586** [comment]
同问 :-）

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
因为0.3.x 所有模型都是通过 API 接入，也没有统一的 rerank 接口，现在只有 Xinference 支持 rerank 模型，后续会考虑接入。

**Comment by ja3592** [comment]
> 0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。 因为0.3.x 所有模型都是通过 API 接入，也没有统一的 rerank 接口，现在只有 Xinference 支持 rerank 模型，后续会考虑接入。

期待。。。
rerank 在rag中还是蛮重要的呢
