### ISSUE TITLE
0.3.0版本，请教如何配置在线大模型api。

### ISSUE THREAD

**Issue by Fulin-Guo** [chatchat-space/Langchain-Chatchat#4404]
**安装方式**
我是以包的方式安装的
```python
pip install langchain-chatchat -U
```
**本地环境**
Ubunt20.04
CPU服务器，无显卡

**问题**
因为本地算力有限，所以想接入在线大模型的api，但是一直没配置成功，没有在文档中找到具体的示例，有没有哪位朋友配置成功的，可以给一个示例参考一下嘛。

**Comment by liunux4odoo** [comment]
先安装 oneapi， 然后按照文档把它的 url/key/models 配置进来即可。

**Comment by Fulin-Guo** [comment]
> 先安装 oneapi， 然后按照文档把它的 url/key/models 配置进来即可。

好的谢谢，我试试~

**Comment by SuMiaoALi** [comment]
oneapi部署成功了，正确填入了模型配置的相关配置项,但还是报错找不到embedding。
oneapi模型平台不支持使用embedding吗？例如OpenAI的在线embedding？必须要使用xinference或ollama平台部署本地模型吗？

报错信息：

2024-08-06 14:33:54.409 | WARNING  | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet
2024-08-06 14:33:54.410 | WARNING  | chatchat.server.utils:detect_xf_models:104 - auto_detect_model needs xinference-client installed. Please try "pip install xinference-client". 
2024-08-06 14:33:54.431 | WARNING  | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet
2024-08-06 14:33:54.431 | WARNING  | chatchat.server.utils:get_default_embedding:214 - default embedding model bge-large-zh-v1.5 is not found in available embeddings, using quentinz/bge-large-zh-v1.5 instead 



模型配置信息：

# # 是否自动获取平台可用模型列表。设为 True 时下方不同模型类型可自动检测
auto_detect_model: true

MODEL_PLATFORMS:
  - platform_name: oneapi
    platform_type: oneapi
    api_base_url: http://*******/v1
    api_key: sk-***************
    api_proxy: ''
    api_concurrencies: 5
    auto_detect_model: true
    llm_models:
      - gpt-4o
      - gpt-3.5-turbo
    embed_models:
      - text-embedding-3-small
      - text-embedding-3-large
    text2image_models: [ ]
    image2text_models: [ ]
    rerank_models: [ ]
    speech2text_models: [ ]
    text2speech_models: [ ]

**Comment by Woodude97** [comment]
> oneapi部署成功了，正确填入了模型配置的相关配置项,但还是报错找不到embedding。 oneapi模型平台不支持使用embedding吗？例如OpenAI的在线embedding？必须要使用xinference或ollama平台部署本地模型吗？
> 
> 报错信息：
> 
> 2024-08-06 14:33:54.409 | WARNING | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet 2024-08-06 14:33:54.410 | WARNING | chatchat.server.utils:detect_xf_models:104 - auto_detect_model needs xinference-client installed. Please try "pip install xinference-client". 2024-08-06 14:33:54.431 | WARNING | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet 2024-08-06 14:33:54.431 | WARNING | chatchat.server.utils:get_default_embedding:214 - default embedding model bge-large-zh-v1.5 is not found in available embeddings, using quentinz/bge-large-zh-v1.5 instead
> 
> 模型配置信息：
> 
> # # 是否自动获取平台可用模型列表。设为 True 时下方不同模型类型可自动检测
> auto_detect_model: true
> 
> MODEL_PLATFORMS:
> 
> * platform_name: oneapi
>   platform_type: oneapi
>   api_base_url: http://_**/v1
>   api_key: sk-**_********
>   api_proxy: ''
>   api_concurrencies: 5
>   auto_detect_model: true
>   llm_models:
>   
>   * gpt-4o
>   * gpt-3.5-turbo
>     embed_models:
>   * text-embedding-3-small
>   * text-embedding-3-large
>     text2image_models: [ ]
>     image2text_models: [ ]
>     rerank_models: [ ]
>     speech2text_models: [ ]
>     text2speech_models: [ ]

请问oneapi如何填写密钥和代理呢？一直测试失败

**Comment by Woodude97** [comment]
> oneapi部署成功了，正确填入了模型配置的相关配置项,但还是报错找不到embedding。 oneapi模型平台不支持使用embedding吗？例如OpenAI的在线embedding？必须要使用xinference或ollama平台部署本地模型吗？
> 
> 报错信息：
> 
> 2024-08-06 14:33:54.409 | WARNING | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet 2024-08-06 14:33:54.410 | WARNING | chatchat.server.utils:detect_xf_models:104 - auto_detect_model needs xinference-client installed. Please try "pip install xinference-client". 2024-08-06 14:33:54.431 | WARNING | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet 2024-08-06 14:33:54.431 | WARNING | chatchat.server.utils:get_default_embedding:214 - default embedding model bge-large-zh-v1.5 is not found in available embeddings, using quentinz/bge-large-zh-v1.5 instead
> 
> 模型配置信息：
> 
> # # 是否自动获取平台可用模型列表。设为 True 时下方不同模型类型可自动检测
> auto_detect_model: true
> 
> MODEL_PLATFORMS:
> 
> * platform_name: oneapi
>   platform_type: oneapi
>   api_base_url: http://_**/v1
>   api_key: sk-**_********
>   api_proxy: ''
>   api_concurrencies: 5
>   auto_detect_model: true
>   llm_models:
>   
>   * gpt-4o
>   * gpt-3.5-turbo
>     embed_models:
>   * text-embedding-3-small
>   * text-embedding-3-large
>     text2image_models: [ ]
>     image2text_models: [ ]
>     rerank_models: [ ]
>     speech2text_models: [ ]
>     text2speech_models: [ ]

请问您修改配置文件就修改两行就可以了吗？我这边一直连接错误

**Comment by SuMiaoALi** [comment]
> > oneapi部署成功了，正确填入了模型配置的相关配置项,但还是报错找不到embedding。 oneapi模型平台不支持使用embedding吗？例如OpenAI的在线embedding？必须要使用xinference或ollama平台部署本地模型吗？
> > 报错信息：
> > 2024-08-06 14:33:54.409 | WARNING | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet 2024-08-06 14:33:54.410 | WARNING | chatchat.server.utils:detect_xf_models:104 - auto_detect_model needs xinference-client installed. Please try "pip install xinference-client". 2024-08-06 14:33:54.431 | WARNING | chatchat.server.utils:get_config_models:153 - auto_detect_model not supported for oneapi yet 2024-08-06 14:33:54.431 | WARNING | chatchat.server.utils:get_default_embedding:214 - default embedding model bge-large-zh-v1.5 is not found in available embeddings, using quentinz/bge-large-zh-v1.5 instead
> > 模型配置信息：
> > # # 是否自动获取平台可用模型列表。设为 True 时下方不同模型类型可自动检测
> > auto_detect_model: true
> > MODEL_PLATFORMS:
> > 
> > * platform_name: oneapi
> >   platform_type: oneapi
> >   api_base_url: http://_**/v1
> >   api_key: sk-**_********
> >   api_proxy: ''
> >   api_concurrencies: 5
> >   auto_detect_model: true
> >   llm_models:
> >   
> >   * gpt-4o
> >   * gpt-3.5-turbo
> >     embed_models:
> >   * text-embedding-3-small
> >   * text-embedding-3-large
> >     text2image_models: [ ]
> >     image2text_models: [ ]
> >     rerank_models: [ ]
> >     speech2text_models: [ ]
> >     text2speech_models: [ ]
> 
> 请问您修改配置文件就修改两行就可以了吗？我这边一直连接错误

你是报什么错误？我已经没有问题了
