### ISSUE TITLE
怎么把text2sql的输出只保留结果，其他输出删掉

### ISSUE THREAD

**Issue by zjxxsr** [chatchat-space/Langchain-Chatchat#4405]
姓名2是汉族人吗?如果不是那是什么民族的人?
Thought:为了回答这个问题，我需要查询数据库中关于姓名2的民族信息。我应该使用
text2sqlAPI来执行查询。
Action:text2sql
Action Input:{"query": "SELECT 民族FROM 员工信息WHERE姓名='姓名2'"}
姓名2不是汉族人，他是满族人

这个是web页面使用text2sql的输出，怎么只保留“姓名2不是汉族人，他是满族人”的输出，其他输出不打印出来

**Comment by ganwumeng** [comment]
workspace_config.json里的return_intermediate_steps参数修改下试试？

**Comment by zjxxsr** [comment]
> workspace_config.json里的return_intermediate_steps参数修改下试试？

不是在workspace_config.json这个文件里修改，跟这个文件没有关系
