### ISSUE TITLE
0.3版本的agent对话  如何携带历史对话呢  好像没有多轮对话能力

### ISSUE THREAD

**Issue by yang9366** [chatchat-space/Langchain-Chatchat#4407]
0.3版本的agent对话  如何携带历史对话呢  好像没有多轮对话能力

**Comment by wanmuchun0** [comment]
怎么改轮数呀，我现在尝试了一下只能进行三次，从yml文件设置的不管用

**Comment by Smile-L-up** [comment]
> 0.3版本的agent对话 如何携带历史对话呢 好像没有多轮对话能力

老哥，你解决这个问题了吗？我也遇到了这个问题，我debug了，发现历史信息有传过来，但是就是没有识别到好像。

**Comment by azhe1234** [comment]
> > 0.3版本的agent对话 如何携带历史对话呢 好像没有多轮对话能力
> 
> 老哥，你解决这个问题了吗？我也遇到了这个问题，我debug了，发现历史信息有传过来，但是就是没有识别到好像。

![Image](https://github.com/user-attachments/assets/cf384520-65aa-454b-88e4-59509e1b2d87)
您好，请问你的知识库对话的历史对话有传过来吗，为什么我调试了下，发现历史什么都没有，谢谢！

![Image](https://github.com/user-attachments/assets/18646643-8894-4407-85eb-fa0f6efd0cba)

**Comment by Smile-L-up** [comment]
> > > 0.3版本的agent对话 如何携带历史对话呢 好像没有多轮对话能力
> > 
> > 
> > 老哥，你解决这个问题了吗？我也遇到了这个问题，我debug了，发现历史信息有传过来，但是就是没有识别到好像。
> 
> ![Image](https://github.com/user-attachments/assets/cf384520-65aa-454b-88e4-59509e1b2d87) 您好，请问你的知识库对话的历史对话有传过来吗，为什么我调试了下，发现历史什么都没有，谢谢！
> 
> ![Image](https://github.com/user-attachments/assets/18646643-8894-4407-85eb-fa0f6efd0cba)

rag问答一直都有多轮对话能力，界面上有个历史对话轮数配置。agent好像才没有，或者说配置了不生效，简单的方式是将历史对话拼接到query里面。
