### ISSUE TITLE
执行python3 webui.py后，一直提示”模型未成功加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮“

### ISSUE THREAD

**Issue by Superkimi** [chatchat-space/Langchain-Chatchat#441]
**问题描述 / Problem Description**
本地下载'chatglm-6b-int4'，英特尔芯片mac执行python3 webui.py后，一直提示”模型未成功加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮“，页面是启动了。

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python3 webui.py

**实际结果 / Actual Result**

Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: './chatglm'.
INFO  2023-05-23 12:41:14,815-1d: 模型未成功加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮
Running on local URL:  http://0.0.0.0:7860
Running on public URL: https://b95fe2d02f01f2d91d.gradio.live

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：V0.1.11
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）： chatglm-6b-int4
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-large-chinese
- Python 版本 / Python version: 3.9.6
- 其他相关环境信息 / Other relevant environment information: 英特尔芯片MAC Book

**Comment by jwh5566** [comment]
请问你的问题解决了吗？？？我pull的最新的代码  现在也是遇到这个问题

**Comment by jwh5566** [comment]
感觉现在好像没人维护了啊   都没人回复issue

**Comment by hanhunhan** [comment]
同问

**Comment by BJFQHSM** [comment]
+1

**Comment by BJFQHSM** [comment]
> 

下载了text2vec的embedding模型，修改配置文件路径之后加载成功了

**Comment by anrsue** [comment]
请问是从这个网址下载的吗，我也重新下了，但还是不行
https://huggingface.co/GanymedeNil/text2vec-large-chinese

**Comment by BJFQHSM** [comment]
> 请问是从这个网址下载的吗，我也重新下了，但还是不行 https://huggingface.co/GanymedeNil/text2vec-large-chinese

是这个，我下载好修改了embedding模型路径就可以了

**Comment by anrsue** [comment]
可以尝试安装CUDA Toolkit

**Comment by xazaj** [comment]
> 请问是从这个网址下载的吗，我也重新下了，但还是不行 https://huggingface.co/GanymedeNil/text2vec-large-chinese

我用这个方法也成功了
