### ISSUE TITLE
在web页面点击上传文件出现AxiosError: Network Error

### ISSUE THREAD

**Issue by zjxxsr** [chatchat-space/Langchain-Chatchat#4410]
后台没有报错，web页面显示错误，没法上传文件

**Comment by zkbaba** [comment]
我也遇到过这个问题，搞定了吗，老哥。

**Comment by zjxxsr** [comment]
> 我也遇到过这个问题，搞定了吗，老哥。

我重做服务器了，你先试试重新安装ncll和cuda吧

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
