### ISSUE TITLE
[BUG]  运行时显示连接失败

### ISSUE THREAD

**Issue by webzhao9125** [chatchat-space/Langchain-Chatchat#4413]
运行”chatchat -a“以后打开界面，对话时发生错误显示连接失败
![issue1](https://github.com/chatchat-space/Langchain-Chatchat/assets/30112149/60538a73-8eda-4a55-ac09-98f8d2dc34ce)
我本地已经部署好了Xinference，运行了embedding模型以及LLM模型，但是LangChain中运行不了。
![issue2](https://github.com/chatchat-space/Langchain-Chatchat/assets/30112149/35903be0-e2dd-4acf-b04c-2ae52efccf77)
![issue3](https://github.com/chatchat-space/Langchain-Chatchat/assets/30112149/50a7bdcc-9a00-49a4-b2f6-b05d2ae5dd74)

**Comment by aaronchen2k** [comment]
解决了？

**Comment by webzhao9125** [comment]
> 解决了？

没有，换了conda环境和python版本依然不行

**Comment by tianxiajianghu** [comment]
和你一样，困扰好几天了

**Comment by tianxiajianghu** [comment]
我都不行，一直镜像搭建的

**Comment by webzhao9125** [comment]
我全部环境都换成python3.12以后，再部署以后成功了，但不确定一定是python环境的问题，也可能是重装的时候其他设置导致的，只是提供个思路orz

**Comment by tianxiajianghu** [comment]
你是容器还是conda,是chatchat升级为3.12么，xinference需要升级么

**Comment by webzhao9125** [comment]
> 你是容器还是conda,是chatchat升级为3.12么，xinference需要升级么

conda，chatchat和Xinference各自的conda环境的python版本改成了3.12，Xinference和chatchat本身用的都是默认install的版本。

**Comment by zx1159652666** [comment]
我也遇到了，有的模型不支持tool_choice=None的情况，如果等于None的情况下，删除这个键再去调用大模型就没问题了

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
