### ISSUE TITLE
源码启动+ollama+qwen2部署成功

### ISSUE THREAD

**Issue by joveth1** [chatchat-space/Langchain-Chatchat#4417]
### 1. ollama 

ollama 保证最新版（部署时的版本: 0.1.48），部署参考官方文档。

```
ollama pull qwen2:7b(根据自己的需求拉取大模型)

ollama pull quentinz/bge-large-zh-v1.5:latest(根据自己的需求拉取向量模型)
```

### 2. 环境配置

[参考文档](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/code.md)中的说明。

由于我使用的是 Pyenv 管理环境。

所以只执行了以下两个命令：

```
pip install poetry
poetry config virtualenvs.prefer-active-python true

```

之后按照说明执行：
```
cd  Langchain-Chatchat/libs/chatchat-server/
poetry install --with lint,test

```

### 3. 源码启动

[参考文档](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md)

不清楚什么原因，按照文档中的脚本执行，发现回报chatchat模块不存在，于是我把init_database.py 文件移动到 chatchat-server 目录下，同时为方便后续的启动，将chatchat/startup.py 、chatchat/webui.py 文件都移动到了chatchat-server目录

此时chatchat-server目录内容如下:
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60052224/9d9cffd0-998c-41d8-b745-8672dea1b206)

修改chatchat/configs/_model_config.py 文件

self.DEFAULT_LLM_MODEL = "glm4-chat" 修改为 self.DEFAULT_LLM_MODEL = "qwen2:7b" # 此处模型根据自己的拉取模型填写

self.DEFAULT_EMBEDDING_MODEL = "bge-large-zh-v1.5" 修改为  self.DEFAULT_EMBEDDING_MODEL = "quentinz/bge-large-zh-v1.5:latest"  # 此处模型根据自己的拉取模型填写

self.MODEL_PLATFORMS 修改为如下:
```
self.MODEL_PLATFORMS = [
            {
                "platform_name": "oneapi",
                "platform_type": "oneapi",
                "api_base_url": "http://127.0.0.1:3000/v1",
                "api_key": "sk-",
                "api_concurrencies": 5,
                "llm_models": [
                    # 智谱 API
                    "chatglm_pro",
                    "chatglm_turbo",
                    "chatglm_std",
                    "chatglm_lite",
                    # 千问 API
                    "qwen-turbo",
                    "qwen-plus",
                    "qwen-max",
                    "qwen-max-longcontext",
                    # 千帆 API
                    "ERNIE-Bot",
                    "ERNIE-Bot-turbo",
                    "ERNIE-Bot-4",
                    # 星火 API
                    "SparkDesk",
                ],
                "embed_models": [
                    # 千问 API
                    "text-embedding-v1",
                    # 千帆 API
                    "Embedding-V1",
                ],
                "image_models": [],
                "reranking_models": [],
                "speech2text_models": [],
                "tts_models": [],
            },
            {
                "platform_name": "ollama",
                "platform_type": "ollama",
                "api_base_url": "http://127.0.0.1:11434/v1",
                "api_key": "sk",
                "api_concurrencies": 5,
                "llm_models": [
                    "qwen2:7b",
                ],
                "embed_models": [
                    "quentinz/bge-large-zh-v1.5:latest",
                ],
                "image_models": [],
                "reranking_models": [],
                "speech2text_models": [],
                "tts_models": [],
            },
        ]

```

在 chatchat-server 目录下

初始化：python init_database.py --recreate-vs

> 初始化时遇到问题，由于没看到有啥影响也就没管：ERROR: ImportError: 从文件 samples/test_files/langchain.pdf 加载文档时出错：libmupdf.so: cannot open shared object file: No such file or directory

启动：python startup.py -a

浏览器访问 http://127.0.0.1:8501/

![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/60052224/c4e0fa80-be05-42a3-acf3-ba01e01baee7)

**Comment by tianxiajianghu** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50093942/77c7e41c-ac87-4214-9c17-18a321841394)
为什么在访问这个端口

**Comment by joveth1** [comment]
> ![image](https://private-user-images.githubusercontent.com/50093942/345994758-77c7e41c-ac87-4214-9c17-18a321841394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTc3MzYsIm5iZiI6MTcyMDE1NzQzNiwicGF0aCI6Ii81MDA5Mzk0Mi8zNDU5OTQ3NTgtNzdjN2U0MWMtYWM4Ny00MjE0LTljMTctMThhMzIxODQxMzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjJhNjJkNDY4YzE3ODJkZThjNjdiMDQwYWM5NTk0MWI1NWRhM2NmMThiMjZjZGIxYTM2MzY1NDkzZDdhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BehDmPFpsfFrbWmxHfjs0PG96Bd5YXoD471gi25KEQw) 为什么在访问这个端口

应该是你的向量模型跟配置不匹配，它没找到，它去huggingface下载，然后这玩意需要翻墙，下载不到

> ![image](https://private-user-images.githubusercontent.com/50093942/345994758-77c7e41c-ac87-4214-9c17-18a321841394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTc3MzYsIm5iZiI6MTcyMDE1NzQzNiwicGF0aCI6Ii81MDA5Mzk0Mi8zNDU5OTQ3NTgtNzdjN2U0MWMtYWM4Ny00MjE0LTljMTctMThhMzIxODQxMzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzZjJhNjJkNDY4YzE3ODJkZThjNjdiMDQwYWM5NTk0MWI1NWRhM2NmMThiMjZjZGIxYTM2MzY1NDkzZDdhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BehDmPFpsfFrbWmxHfjs0PG96Bd5YXoD471gi25KEQw) 为什么在访问这个端口

你的这个向量模型，它没找到，自己去下载报错了估计，你自己拉取向量模型，修改一下配置文件试试呢

**Comment by joveth1** [comment]
> embed_models 里面要把 :latest 去掉，不然使用 FAISS 向量库的时候会出错。

非常感谢

**Comment by tianxiajianghu** [comment]
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50093942/2a2fa558-3b8d-4883-8630-46b9859f1c92)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50093942/3500154f-7f55-4ab8-9a76-5991202b8998)
都是按照你的配的，不知道问什么不访问ollama端口

**Comment by liunux4odoo** [comment]
> ![image](https://private-user-images.githubusercontent.com/50093942/346028635-2a2fa558-3b8d-4883-8630-46b9859f1c92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjUxOTEsIm5iZiI6MTcyMDE2NDg5MSwicGF0aCI6Ii81MDA5Mzk0Mi8zNDYwMjg2MzUtMmEyZmE1NTgtM2I4ZC00ODgzLTg2MzAtNDZiOTg1OWYxYzkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliY2ZhNWNiMGYyZGZiOTc3NDM0MTk4MjU0MGEyOTgxYzE4N2EzYTk2MDdjNWFiZGIzYzQ4MjA0ZWE3ZjE0YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RnXKBlZraTg5vzv6cEGzg-oCm73wtxXXwjxY1Icunqc) ![image](https://private-user-images.githubusercontent.com/50093942/346028925-3500154f-7f55-4ab8-9a76-5991202b8998.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjUxOTEsIm5iZiI6MTcyMDE2NDg5MSwicGF0aCI6Ii81MDA5Mzk0Mi8zNDYwMjg5MjUtMzUwMDE1NGYtN2Y1NS00YWI4LTlhNzYtNTk5MTIwMmI4OTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA3MzQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4YWRmNjVkMzIxN2I2NjA0MmJjM2IyYWUzNTdkZGVkOTIzM2IxZTE5NTUwNmIwODBjYTAyMDFjYjNlN2RmZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8Ig9PYj4mRdR1FxTw3m8Q0teEufXArnocUejm4kq46I) 都是按照你的配的，不知道问什么不访问ollama端口

如果只有一个 LLM，那么 DEFAULT_LLM_MODEL/LLM_MODEL_CONFIG 里的名称和 platforms["llm_models"]里的名称要一致。你一个叫 "qwen:0.5b", 另一个叫"qwen2:0.5b"。

**Comment by tianxiajianghu** [comment]
我已经改带掉了，但是这些都和bge没有关系，bge访问的地址是什么服务，为什么去这里查找模型在不在

**Comment by joveth1** [comment]
> 我已经改带掉了，但是这些都和bge没有关系，bge访问的地址是什么服务，为什么去这里查找模型在不在

你的 self.DEFAULT_EMBEDDING_MODEL 和 self.MODEL_PLATFORMS里面的 embed_models不一致，要么都去掉 

![1720168116849_CA0EB9B9-F3F6-46e4-B920-B0EF3235A842](https://github.com/chatchat-space/Langchain-Chatchat/assets/60052224/848f5f04-f1f2-479b-a511-8891e2c508b6)


![1720168128849_69A5A1D8-8708-4cca-8F21-339CE77241BC](https://github.com/chatchat-space/Langchain-Chatchat/assets/60052224/6c020cf9-69ec-4ff6-90ab-3863bc7bb944)

**Comment by wangyingle666** [comment]
> > 我已经改带掉了，但是这些都和bge没有关系，bge访问的地址是什么服务，为什么去这里查找模型在不在
> 
> 你的 self.DEFAULT_EMBEDDING_MODEL 和 self.MODEL_PLATFORMS里面的 embed_models不一致，要么都去掉 latest
> 
> ![1720168116849_CA0EB9B9-F3F6-46e4-B920-B0EF3235A842](https://private-user-images.githubusercontent.com/60052224/346060758-848f5f04-f1f2-479b-a511-8891e2c508b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDQxMDksIm5iZiI6MTcyMDUwMzgwOSwicGF0aCI6Ii82MDA1MjIyNC8zNDYwNjA3NTgtODQ4ZjVmMDQtZjFmMi00NzliLWE1MTEtODg5MWUyYzUwOGI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1NDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyNWUzNjQwYTM2MWUzYzlkYWM1ZjdkOTA3MTU4YjQxYThmYjZlN2UyODRmMDAxZWFmNGEyYmQ3Y2QyZDNmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BDmuPr0osHEZaSe8fdS5YGDVgUB-7--k0zlL1--zGhY)
> 
> ![1720168128849_69A5A1D8-8708-4cca-8F21-339CE77241BC](https://private-user-images.githubusercontent.com/60052224/346060803-6c020cf9-69ec-4ff6-90ab-3863bc7bb944.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MDQxMDksIm5iZiI6MTcyMDUwMzgwOSwicGF0aCI6Ii82MDA1MjIyNC8zNDYwNjA4MDMtNmMwMjBjZjktNjllYy00ZmY2LTkwYWItMzg2M2JjN2JiOTQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDA1NDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1NTY0MDRiOGZlZDMxMTMzNGUxNTFhMjY4NmEzMTM5ZDNkZDM4NTBjZmNjY2RhYTc2OTdiMDhkODA1ZGRiNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SLXKKrH3uFdnPsHd_G6gBdyQYiVsFOiX8IKDfv7ngIQ)

请问下，api_Key 怎么设置啊

**Comment by wangyingle666** [comment]
我按照你的步骤部署，为什么会有这个错误
<img width="789" alt="5e970fdd161291c8ab28d4cdc6adb2f" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/72133128/df2f5066-3111-4650-b630-07c17f6cba99">

**Comment by joveth1** [comment]
> 我按照你的步骤部署，为什么会有这个错误 <img alt="5e970fdd161291c8ab28d4cdc6adb2f" width="789" src="https://private-user-images.githubusercontent.com/72133128/346883335-df2f5066-3111-4650-b630-07c17f6cba99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1OTIxMTIsIm5iZiI6MTcyMDU5MTgxMiwicGF0aCI6Ii83MjEzMzEyOC8zNDY4ODMzMzUtZGYyZjUwNjYtMzExMS00NjUwLWI2MzAtMDdjMTdmNmNiYTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA2MTAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNTEwNDFhZjE3YWRkZTI5ODc4ZDQwZDkxZmQzMThlOTVlNTYxYzgxZGY1NDA4YWJhNDMwMGU0MTk4YzU2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AbQkpPOPaUrMPSzDelOC0R-VsX7gTNy-2EEvGgUjWzk">

检查一下_model_config.py里面向量模型的名称，跟你拉取的是不是一个

**Comment by xiaof3ngfeng** [comment]
感谢分享❤我用pip安装包也成功了，这么写就能改配置文件chatchat-config model --set_model_platforms "[{ \"platform_name\": \"ollama\",\"platform_type\": \"ollama\",\"api_base_url\": \"http://127.0.0.1:11434/v1\",\"api_key\": \"sk\", \"api_concurrencies\": 5,\"llm_models\": [\"qwen2:7b\"],\"embed_models\": [\"quentinz/bge-large-zh-v1.5:latest\"],\"image_models\": [], \"reranking_models\": [],\"speech2text_models\": [],\"tts_models\": []}]"

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

**Comment by kelinkong** [comment]
成功解决问题，感谢
