### ISSUE TITLE
【api调用失败】通过文档的api无法正确返回信息

### ISSUE THREAD

**Issue by silence-dxs-v2** [chatchat-space/Langchain-Chatchat#4422]
<img width="1506" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/174102027/f1c1d9f2-f4a6-431e-aa6b-01945f11e652">
<img width="1509" alt="image" src="https://github.com/chatchat-space/Langchain-Chatchat/assets/174102027/9f939f43-757b-49e3-b7d5-b1a40ab2bdcf">

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，API 调用给出了详细文档，可以更新尝试。
