### ISSUE TITLE
这个版本有文件对话吗？

### ISSUE THREAD

**Issue by lingyezhixing** [chatchat-space/Langchain-Chatchat#4431]
我看readme的图片里有文件对话，但是我启动后界面上没有上传的位置。
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/144504450/9318936a-348b-466c-b7b6-49a9b780e5e5)

**Comment by zhuzongjian1** [comment]
哪个版本不都有吗

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，添加了专门的RAG界面，可以更新尝试。
