### ISSUE TITLE
[求助]使用Xinference平台进行模型部署，在对话时没有流式输出，查看log  stream的设置是true

### ISSUE THREAD

**Issue by zhenxianga** [chatchat-space/Langchain-Chatchat#4439]
使用Xinference平台进行模型部署，在对话时没有流式输出，查看log  stream的设置是true
![log](https://github.com/chatchat-space/Langchain-Chatchat/assets/44467447/5650955f-9862-41e1-b426-113177d2d25f)

**Comment by HhhBbWw** [comment]
我也是这个问题，xinference + chatglm3，win10平台

**Comment by Cnzboy** [comment]
same issue. xinference + glm4-chat

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，不再使用 model_provider，可以更新尝试。
