### ISSUE TITLE
docker pull chatimage/chatchat:0.3.0-2024-0624 不能下载

### ISSUE THREAD

**Issue by foam103** [chatchat-space/Langchain-Chatchat#4442]
之前的0.2是可以正常下载的，但是目前0.3版本放出来的docker不能下载。

**Comment by huangjunli864** [comment]
主流的docker镜像源现在都封了，可以找一下镜像加速站。我用的是这个，供参考
https://hub.uuuadc.top，https://docker.anyhub.us.kg

**Comment by foam103** [comment]
> 主流的docker镜像源现在都封了，可以找一下镜像加速站。我用的是这个，供参考 [https://hub.uuuadc.top，https://docker.anyhub.us.kg](https://hub.uuuadc.top%EF%BC%8Chttps://docker.anyhub.us.kg)

感谢，通过docker pull docker.anyhub.us.kg/chatimage/chatchat:0.3.0-2024-0624  可以了。
