### ISSUE TITLE
[BUG] text2sql功能模块bug

### ISSUE THREAD

**Issue by ln410** [chatchat-space/Langchain-Chatchat#4443]
![截图 2024-07-08 17-44-03](https://github.com/chatchat-space/Langchain-Chatchat/assets/113881211/a2a60955-ed4a-4cd1-9ab0-11c555eea119)
![截图 2024-07-08 17-44-57](https://github.com/chatchat-space/Langchain-Chatchat/assets/113881211/dfc740df-caa5-433e-b058-59f4fd1b178b)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
