### ISSUE TITLE
[BUG] 知识库API调用报错

### ISSUE THREAD

**Issue by plancktree** [chatchat-space/Langchain-Chatchat#4445]
**问题描述 我用/chat/chat/completions接口，使用postman如下报文调用知识库失败，单纯模型对话正常，
报错内容：
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.hub.langchain.com', port=443): Max retries exceeded with url: /commits/hwchase17/structured-chat-agent/?limit=100&offset=0 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3d75afd4e0>, 'Connection to api.hub.langchain.com timed out. (connect timeout=None)'))

报文：
{
"messages": [
{"role": "user", "content": "如何提问以获得高质量答案"}
],
"model": "qwen",
"tool_choice": "search_local_knowledgebase",
"extra_body": {"tool_input": {"database": "samples", "query": "如何提问以获得高质量答案"}},
"stream": true,
}

**Comment by plancktree** [comment]
@liunux4odoo 所以大佬有相关issue的解决方案吗

**Comment by y-xie-stu** [comment]
{
"messages": [
{"role": "user", "content": "如何提问以获得高质量答案"}
],
"model": "qwen",
"tool_choice": "search_local_knowledgebase",
"tool_input": {"database": "samples", "query": "如何提问以获得高质量答案"},
"stream": true,
}
你的版本可能不是最新的，试试这个请求参数，api文档更新过

**Comment by Silenceang** [comment]
> { "messages": [ {"role": "user", "content": "如何提问以获得高质量答案"} ], "model": "qwen", "tool_choice": "search_local_knowledgebase", "tool_input": {"database": "samples", "query": "如何提问以获得高质量答案"}, "stream": true, } 你的版本可能不是最新的，试试这个请求参数，api文档更新过

"tool_input": {"database": "samples", "query": "如何提问以获得高质量答案"},

请问这个“query”具体是什么作用？
