### ISSUE TITLE
[BUG] win11系统下anaconda环境安装说明文档修改配置 文件报错

### ISSUE THREAD

**Issue by conan4977** [chatchat-space/Langchain-Chatchat#4447]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
![微信图片_20240709115419](https://github.com/chatchat-space/Langchain-Chatchat/assets/161542237/8d4b134e-868b-4f07-8a7f-728dd40b9d55)

**复现问题的步骤 / Steps to Reproduce**
执行命令：
chatchat-config model --set_model_platforms "[{`"platform_name`":`"xinference`",`"platform_type`":`"xinference`",`"api_base_url`":`"http://127.0.0.1:9997/v1`",`"api_key`":`"EMPT`",`"api_concurrencies`":5,`"llm_models`":[`"glm-4v`"],`"embed_models`":[`"bge-large-zh-v1.5`"],`"image_models`":[],`"reranking_models`":[],`"speech2text_models`":[],`"tts_models`:[]}]"
后报错

- 操作系统及版本 / Operating system and version: WIN11
- Python 版本 / Python version: 3.11
- 其他相关环境信息 / Other relevant environment information:  anaconda powershell窗口执行修改配置文件命令，出错

**附加信息 / Additional Information**
求助应该如何修改配置文件啊。换成自己已运行的模型。
目前环境没有问题，运行和配置文件默认模型相同名称的模型已经可以正常对话，现在想要修改为名称不同的模型，不会改配置文件了。

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
