### ISSUE TITLE
API 方式无法正确使用。且回答不对，文档中很多并无注释的等

### ISSUE THREAD

**Issue by Bo-LiangD** [chatchat-space/Langchain-Chatchat#4448]
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(0.3.0）
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen2-7B-Instruct-GPTQ-Int8
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.35.
python版本：3.11.7 (main, Dec 15 2023, 18:12:31) [GCC 11.2.0]
项目版本：v0.3.0
langchain版本：0.1.17

相比 2.10版本
在新版中 
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/29296518/cff9db2c-fe76-4a79-b3e8-10a68660c082)
API调用会存在问题
回答不正确
文档无过多注释，有些参数需要查看代码

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

很多开源模型的Agent能力并不稳定，0.3.1 增加了专门的RAG接口和页面。
