### ISSUE TITLE
[BUG] WINDOS平台无法进行chatchat-config model --set_model_platforms 

### ISSUE THREAD

**Issue by 871052165** [chatchat-space/Langchain-Chatchat#4452]
前期正常安装，进行到chatchat-config model --set_model_platforms 这一步时就出错了：
如果按照提示给的命令输入报错如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/ceae22b8-7b93-4a7c-930b-4e6a1cdfd111)
如果按照WINDOS命令格式输入报错如下：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/09f1bd96-e951-4a08-898a-f288b676d11a)
希望作者能够给一个WINDOS平台用于chatchat-config model --set_model_platforms的范例

**Comment by 871052165** [comment]
LINUX平台不存在这个问题，已测试通过

**Comment by lelofraser** [comment]
Windows的话 开头和结尾的 “ 要改成 ‘

**Comment by 871052165** [comment]
> Windows的话 开头和结尾的 “ 要改成 ‘

一样的提示格式不正确哈哈：
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/a0271aab-bd5b-4410-aa87-c9f004279e7d)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/50550790/43a1933e-1805-4cc0-a224-161b0f506a1e)

**Comment by sj154087598** [comment]
全改成一行就能执行了

**Comment by lelofraser** [comment]
> > Windows的话 开头和结尾的 “ 要改成 '
> 
> 一样的提示格式不正确哈哈： ![image](https://private-user-images.githubusercontent.com/50550790/347243590-a0271aab-bd5b-4410-aa87-c9f004279e7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjU4NTUsIm5iZiI6MTcyMDY2NTU1NSwicGF0aCI6Ii81MDU1MDc5MC8zNDcyNDM1OTAtYTAyNzFhYWItYmQ1Yi00NDEwLWFhODctYzlmMDA0Mjc5ZTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAyMzkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkODljNjhhZjljMTIxNTNmOWFhM2U0MTkzYzRkYjVjMmE5YjJlNjdjOGJlYWIzNjY0YWI5N2I3NWE5Mjg4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3_VwcbexbQ3NhRa8u3jJMeSB3SqRTwdf_34lXjHG2Uc) ![image](https://private-user-images.githubusercontent.com/50550790/347243624-43a1933e-1805-4cc0-a224-161b0f506a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2NjU4NTUsIm5iZiI6MTcyMDY2NTU1NSwicGF0aCI6Ii81MDU1MDc5MC8zNDcyNDM2MjQtNDNhMTkzM2UtMTgwNS00Y2MwLWEyMjQtMTYxYjBmNTA2YTFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzExVDAyMzkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5N2QxM2EwMmJiNDU2YWEwZjIxMjBiYTFkYmViMTNkYzk3NmFkYTkxZDgzOTY5MWI1NzA5MWMwNTc2MDlmNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T-osjuhEjGSzKUM4EvKkDc-aDJrXCS8ldXitYjy-eOY)

每个键对都要加\啊 参考文档那样加

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
