### ISSUE TITLE
[BUG] 前端会话设置中删除多个会话后，造成对话框不可用

### ISSUE THREAD

**Issue by xinghuiiiiiiiii** [chatchat-space/Langchain-Chatchat#4454]
**问题描述 / Problem Description**
前端会话设置中删除多个会话后，造成对话框不可用

**复现问题的步骤 / Steps to Reproduce**
1. 执行``` chatchat -a```启动服务
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/174009442/34d81816-6b7e-4831-b995-a1bc5177f10a)

2. 新建多个会话
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/174009442/e3fffaf5-1211-48e4-8006-383c6b0f36c7)

3. 删除这些会话
4. 问题出现 / Problem occurs
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/174009442/f0cd9ada-e888-46fc-810c-57fbe8d9ecf1)

**预期的结果 / Expected Result**
描述应该出现的结果 
  当我不新建会话（默认一个会话的时候），删除会话会提示我```这是最后一个会话```不可删除，并且这个会话确实不可删除；这是正确的；

**实际结果 / Actual Result**
   当我新建多个会话后，可以删除掉 所有会话，并报错；造成对话框不可用

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B / Model used (ChatGLM2-6B / Qwen-7B, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：moka-ai/m3e-base / Embedding model used (moka-ai/m3e-base, etc.): moka-ai/m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
该问题将在下个版本修复。
