### ISSUE TITLE
[BUG] 图片对话错误

### ISSUE THREAD

**Issue by zx1159652666** [chatchat-space/Langchain-Chatchat#4458]
**添加知识库错误**
ERROR    | chatchat.server.api_server.chat_routes:chat_completions:191 - failed to add message to db
**查看大模型输入，即openai_routes.py文件中的params，如下显示**
{'messages': [{'content': SerializationIterator(index=0, iterator=ValidatorIterator(index=0, schema=Some(Union(UnionValidator { mode: Smart, choices: [(TypedDict(TypedDictValidator { fields: [TypedDictField { name: "text", look
up_key: Simple { key: "text", py_key: Py(0x18f97f5e8f0), path: LookupPath([S("text", Py(0x18f97f5e970))]) }, name_py: Py(0x7ff8e1795eb8), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false
 }) }, TypedDictField { name: "type", lookup_key: Simple { key: "type", py_key: Py(0x18f97f5ec70), path: LookupPath([S("type", Py(0x18f97f5eb70))]) }, name_py: Py(0x7ff8e1670970), required: true, validator: Literal(LiteralValid
ator { lookup: LiteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"text": 0}), expected_py_dict: None, expected_py_list: None, values: [Py(0x7ff8e1795eb8)] }, expected_repr: "'text'", name: "literal['t
ext']" }) }], extra_behavior: Allow, extras_validator: None, strict: false, loc_by_alias: true }), None), (TypedDict(TypedDictValidator { fields: [TypedDictField { name: "image_url", lookup_key: Simple { key: "image_url", py_ke
y: Py(0x18f97f5e470), path: LookupPath([S("image_url", Py(0x18f97f5e4f0))]) }, name_py: Py(0x18f9691ff30), required: true, validator: TypedDict(TypedDictValidator { fields: [TypedDictField { name: "url", lookup_key: Simple { ke
y: "url", py_key: Py(0x18f97f5e9f0), path: LookupPath([S("url", Py(0x18f97f5e830))]) }, name_py: Py(0x18ff92995b0), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false }) }, TypedDictField 
{ name: "detail", lookup_key: Simple { key: "detail", py_key: Py(0x18f97f5ed70), path: LookupPath([S("detail", Py(0x18f97f5e7f0))]) }, name_py: Py(0x18ffff22030), required: false, validator: Literal(LiteralValidator { lookup: L
iteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"low": 1, "auto": 0, "high": 2}), expected_py_dict: None, expected_py_list: None, values: [Py(0x18ff8bef3b0), Py(0x18ff8c08df0), Py(0x18ff8c08e30)] }, 
expected_repr: "'auto', 'low' or 'high'", name: "literal['auto','low','high']" }) }], extra_behavior: Allow, extras_validator: None, strict: false, loc_by_alias: true }) }, TypedDictField { name: "type", lookup_key: Simple { ke
y: "type", py_key: Py(0x18f97f5ee70), path: LookupPath([S("type", Py(0x18f97f5ebf0))]) }, name_py: Py(0x7ff8e1670970), required: true, validator: Literal(LiteralValidator { lookup: LiteralLookup { expected_bool: None, expected_
int: None, expected_str: Some({"image_url": 0}), expected_py_dict: None, expected_py_list: None, values: [Py(0x18f9691ff30)] }, expected_repr: "'image_url'", name: "literal['image_url']" }) }], extra_behavior: Allow, extras_val
idator: None, strict: false, loc_by_alias: true }), None)], custom_error: None, strict: false, name: "union[typed-dict,typed-dict]" })))), 'role': 'user'}], 'model': 'cogvlm', 'max_tokens': None, 'stream': False, 'tool_choice':
 None}
**使用模型是oneapi的在线模型cogvlm，但是显示500 Internal Server Error，会重新尝试请求，但是都没有请求成功，我用postman去请求该模型时，请求体为**
{
    "model": "cogvlm",
    "messages": [
        {
            "role": "user", 
            "content": [
                {"type": "text", "text": "图片中发生了什么"}, 
                {"type": "image_url", "image_url": {"url": "base64格式"
            ]
        }
    ],
    "temperature": 0.7
}
**能够成功访问，猜测是输入问题，当我把输入修改为base64格式，会显示输入过长，导致返回413错误。
错误如下**
openai.APIStatusError: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
**请问该如何修改？**

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

这个问题是因为图片对话返回的response不是纯文本，导致history入表出错，新版已经修复

**Comment by zx1159652666** [comment]
请问在哪儿修复了，我下载新版还是不行

**Comment by jiusi9** [comment]
> 请问在哪儿修复了，我下载新版还是不行

请问解决了吗
