### ISSUE TITLE
0.3版本切换和修改text_splitter方法

### ISSUE THREAD

**Issue by lwd-2018** [chatchat-space/Langchain-Chatchat#4459]
**问题描述**
没有找到在哪可以切换text_splitter方法，也没有找到在哪可以修改text_splitter的源码，想修改ChineseRecursiveTextSplitter方法的separator

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
