### ISSUE TITLE
重启服务之后出现数据库消失的情况，需要根据源文件重建向量库后才能使用并显示

### ISSUE THREAD

**Issue by bobo0311** [chatchat-space/Langchain-Chatchat#4461]
**问题描述 / Problem Description**
重启服务之后出现数据库消失的情况。需要根据源文件重建向量库后才能使用并显示

**复现问题的步骤 / Steps to Reproduce**
chatchat -a 重启服务之后，除了最早的samples库，其他的全不能用了，但是能显示名称。查看文件仍在，knowledge_base 中content文件夹和vector_store文件夹中均存在文件。
无论是网页界面，还是api调用都无法访问到其他数据库，但是点击“根据源文件重建向量库”之后，重建完成又能显示或者调用。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）： Qwen-7B
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Linux

**Comment by liunux4odoo** [comment]
Duplicate of #4354
