### ISSUE TITLE
希望可以新增动态知识库向量构建功能

### ISSUE THREAD

**Issue by LULU-LULULA** [chatchat-space/Langchain-Chatchat#4464]
**功能描述 / Feature Description**
动态的知识库调整有利于知识的不断更新，且避免“过期的”知识对问题的正确回答造成时延性，当知识库中新增文件时，新增文件自动转化为向量，添加到知识库向量中，当该知识库中的文件被删除时，向量也对应删除。

**解决的问题 / Problem Solved**
动态知识库调整的方法可以帮助系统保持知识库内容的时效性、准确性和一致性，提高系统的智能化程度和用户满意度，比如公司在月底更新了上个月的技术更新项和经验总结项，这些新的知识被添加进知识库后希望立刻进行向量化，保证实施人员在第一时间就能通过大模型找到最新的解决问题方法，或者经验。又或是分析当下最新数据特性，给出最佳建议和判断。

**实现建议 / Implementation Suggestions**
使用自动化流程：您可以设置自动化流程来监测知识库文件夹中的变化。当有新文件添加或旧文件删除时，触发相应的操作。
一致性维护：确保知识库内容与向量库的一致性。即使文件被删除，与之相关的向量也应该被及时删除，以保持知识库向量的准确性。

**Comment by liunux4odoo** [comment]
这种功能不是目前考虑的重点。
对于 FAISS 向量库，多进程写入很容易造成数据不一致。对于其他向量库，自己写一个文件监视系统或定期任务就可以了，根据disk 文件刷新向量库的代码都是现成的。
