### ISSUE TITLE
重新启动服务时，找不到上次建立的知识库

### ISSUE THREAD

**Issue by sunnnyu** [chatchat-space/Langchain-Chatchat#4465]
**问题描述 / Problem Description**
启动服务后，新建知识库功能可以正常使用，上传文件、向量化均正常。但关掉服务再次启动后，上次建的知识库就找不到了，但是在知识库确实存在Langchain-Chatchat-0.3.0/libs/chatchat-server/chatchat/data/knowledge_base里。
![5d4bbdfc801f9c7ff41e9019ea937ab](https://github.com/chatchat-space/Langchain-Chatchat/assets/63385747/0cc101b8-8f38-4115-81aa-e79916fd6137)
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/63385747/61fccd47-3206-44c3-97b6-0855f73b531b)
![14479c231a573e7f568f553c744df91](https://github.com/chatchat-space/Langchain-Chatchat/assets/63385747/1f347d9e-7168-468c-9bd8-c18ccba309a1)

**复现问题的步骤 / Steps to Reproduce**
1 按源码部署方式部署该项目，启动服务后各项功能经测试均正常
2 关掉服务，再次启动，上一次建的知识库找不到，在ui界面仅能显示知识库名字，但无法上传文件、无法删除。
3 执行chatchat-config kb --show显示：
"KB_ROOT_PATH": "/home/XX/Langchain-Chatchat-0.3.0/libs/chatchat-server/chatchat/data/knowledge_base",
    "DB_ROOT_PATH": "/home/XX/Langchain-Chatchat-0.3.0/libs/chatchat-server/chatchat/data/knowledge_base/info.db",
在相应的目录下能找到上次建立的知识库。

**预期的结果 / Expected Result**
每次重启服务，知识库不应丢失

**实际结果 / Actual Result**
重启服务后，之前建立的知识库丢失

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： langchain-Chatchat0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM-6B 
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version:Ubuntu 9.4.0-1ubuntu1~20.04.2
- Python 版本 / Python version:3.10.4

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
Duplicate of #4354
