### ISSUE TITLE
[BUG] kb_config description 

### ISSUE THREAD

**Issue by kwunhang** [chatchat-space/Langchain-Chatchat#4466]
**问题描述 / Problem Description**
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101049505/8772aa4b-1e7b-4fa6-8209-4f2243ed384c)
Langchain v0.3中，configs/_kb_config.py的对SCORE_THRESHOLD的描述是不是说返了？

**附加信息 / Additional Information**
Langchain 在similarity_search_with_relevance_scores function 中的code:
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/101049505/51d12174-1ae2-412e-b6e7-4a5fca17ddd3)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
