### ISSUE TITLE
最后一步一键启动后，出现诸多bug。请教是此行代码需要修改吗还是如何解决呢

### ISSUE THREAD

**Issue by BigShawnZhang** [chatchat-space/Langchain-Chatchat#4470]
**问题描述 / Problem Description**
按照步骤提示进行到最后一部一键启动，但是跑不通，求解答
![1720687489293](https://github.com/chatchat-space/Langchain-Chatchat/assets/128217128/1f71b212-5826-494e-babb-190c19d690fd)
![1720687535659](https://github.com/chatchat-space/Langchain-Chatchat/assets/128217128/9e99ab55-c25e-4fb9-a9dd-476398c190a9)
![1720687549903](https://github.com/chatchat-space/Langchain-Chatchat/assets/128217128/4d6587cf-b3fc-48da-af0a-c922bc53cec6)
![1720687566736](https://github.com/chatchat-space/Langchain-Chatchat/assets/128217128/52dd9cb9-52dc-46db-8ff3-cef20c04a02e)

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。
