### ISSUE TITLE
请问langchain-ChatGLM如何删除一条本地知识库的数据？

### ISSUE THREAD

**Issue by javabloger** [chatchat-space/Langchain-Chatchat#448]
例如：用户刚刚提交了一条错误的数据到本地知识库中了，现在如何在本地知识库从找到，并且对此删除。
如果不删除，总是有错误的回答。
有哪位大神知道请告知，万分感谢。

**Comment by liaoweiguo** [comment]
目前似乎只能删除vector_store下面的子目录，重建这个知识库
