### ISSUE TITLE
本地知识库的回答顺序问题。

### ISSUE THREAD

**Issue by lettergod** [chatchat-space/Langchain-Chatchat#4481]
目前状态：
本地知识库有的内容，可以正确回答
本地知识库没有的内容，程序去问大语言模型来回复。

期盼状态：
如何设置，设置本地知识库没有的内容，回答“不知道”或其它
**_目的是不要再去问大语言模型回复。_**

例如：
问：天为什么是蓝的？ ##（这个问题，本地知识里**没有相关内容**）
答：不知道或无法回答或什么固定都可以。##（只要**别去问大语言**来回答就可以）

### 在哪里设置，设置哪个文件？

**Comment by lettergod** [comment]
现在是kb_settings.yaml吧，这里的参数，看了好几遍了。
真心真心没找到是哪个参数。指点一下吧

**Comment by lettergod** [comment]
prompt_settings.yaml 这个看了一脸懵状态。

**Comment by liunux4odoo** [comment]
你这个需求只能改代码了。

**Comment by lettergod** [comment]
只想要个纯本地知识库问答。
您这个系统太庞大了，小弟能力不够，改不了啊。
