### ISSUE TITLE
[BUG] 正常对话出现 RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by ASan1527** [chatchat-space/Langchain-Chatchat#4486]
**问题描述 / Problem Description**
在服务器上部署的Xinfernece成功，加载的是离线模型glm4，路径啥的都没有问题，webui也能正确显示，但是对话报错。
![image](https://github.com/user-attachments/assets/02f746a9-e254-4f07-81c9-68806f72499f)

![image](https://github.com/user-attachments/assets/d40818d0-10c5-45f6-ad4b-5e8e87d49a0b)

![image](https://github.com/user-attachments/assets/b91abccb-7284-40a6-adbd-d5e1869815b5)

**环境信息 / Environment Information**
- langchain-chatchat版本/commit 号：0.3.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4-chat
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 操作系统及版本 / Operating system and version:  ubantu
- Python 版本 / Python version:  py3.10.13

**Comment by ASan1527** [comment]
> **问题描述 / Problem Description** 在服务器上部署的Xinfernece成功，加载的是离线模型glm4，路径啥的都没有问题，webui也能正确显示，但是对话报错。 ![image](https://private-user-images.githubusercontent.com/115404764/348157010-02f746a9-e254-4f07-81c9-68806f72499f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzA3MTIsIm5iZiI6MTcyMDc3MDQxMiwicGF0aCI6Ii8xMTU0MDQ3NjQvMzQ4MTU3MDEwLTAyZjc0NmE5LWUyNTQtNGYwNy04MWM5LTY4ODA2ZjcyNDk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGE2YjlhZDE0MjFmYzQ2OTFjZDY3OWRhMjA1ZWUzMGMxODdhYzc4OGY0ZWQ4ZmRmZTYwNTMzYTVjNTBiMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IEiWajpba3Sp_8Jto7v2fF88jwMZOz4w0m0afZ1VXLQ)
> 
> ![image](https://private-user-images.githubusercontent.com/115404764/348157426-d40818d0-10c5-45f6-ad4b-5e8e87d49a0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzA3MTIsIm5iZiI6MTcyMDc3MDQxMiwicGF0aCI6Ii8xMTU0MDQ3NjQvMzQ4MTU3NDI2LWQ0MDgxOGQwLTEwYzUtNDVmNi1hZDRiLTVlOGU4N2Q0OWEwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDVmZjhiYjA1MGVmNjY2NWY2MGUwNTI4ZDdmYmJiYjFmMjI0N2UzN2E5Nzc0ZmVjZjliMmYwYjg4MWU1MzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lr1ZQrM_2syIVICHarxcZlsse2oDDcdO0ZkprhHii28)
> 
> ![image](https://private-user-images.githubusercontent.com/115404764/348157333-b91abccb-7284-40a6-adbd-d5e1869815b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzA3MTIsIm5iZiI6MTcyMDc3MDQxMiwicGF0aCI6Ii8xMTU0MDQ3NjQvMzQ4MTU3MzMzLWI5MWFiY2NiLTcyODQtNDBhNi1hZGJkLWQ1ZTE4Njk4MTViNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmM5MDViM2I0Zjc5ZmU0NmY4MWIwOTk3YjFjYzc1ZDNiYmExYjdhNWEyZmMzZTI2YzJjMWE3OThiMzE5NzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pAD_TMHD0VBP5CM2psqXLDsvhXSWVd8ElHZfcVi_cao)
> 
> **环境信息 / Environment Information**
> 
> * langchain-chatchat版本/commit 号：0.3.0
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4-chat
> * 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
> * 操作系统及版本 / Operating system and version:  ubantu
> * Python 版本 / Python version:  py3.10.13

已经解决了

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

**Comment by daigang896** [comment]
遇到了相同的问题，一直报错，2024-07-15 10:47:24,260 xinference.api.restful_api 12342 ERROR    Chat completion stream got an error: [address=0.0.0.0:46663, pid=14317] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'

**Comment by Modas-Li** [comment]
> > **问题描述 / Problem Description** 在服务器上部署的Xinfernece成功，加载的是离线模型glm4，路径啥的都没有问题，webui也能正确显示，但是对话报错。 ![image](https://private-user-images.githubusercontent.com/115404764/348157010-02f746a9-e254-4f07-81c9-68806f72499f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzA3MTIsIm5iZiI6MTcyMDc3MDQxMiwicGF0aCI6Ii8xMTU0MDQ3NjQvMzQ4MTU3MDEwLTAyZjc0NmE5LWUyNTQtNGYwNy04MWM5LTY4ODA2ZjcyNDk5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGE2YjlhZDE0MjFmYzQ2OTFjZDY3OWRhMjA1ZWUzMGMxODdhYzc4OGY0ZWQ4ZmRmZTYwNTMzYTVjNTBiMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IEiWajpba3Sp_8Jto7v2fF88jwMZOz4w0m0afZ1VXLQ)
> > ![image](https://private-user-images.githubusercontent.com/115404764/348157426-d40818d0-10c5-45f6-ad4b-5e8e87d49a0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzA3MTIsIm5iZiI6MTcyMDc3MDQxMiwicGF0aCI6Ii8xMTU0MDQ3NjQvMzQ4MTU3NDI2LWQ0MDgxOGQwLTEwYzUtNDVmNi1hZDRiLTVlOGU4N2Q0OWEwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDVmZjhiYjA1MGVmNjY2NWY2MGUwNTI4ZDdmYmJiYjFmMjI0N2UzN2E5Nzc0ZmVjZjliMmYwYjg4MWU1MzJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lr1ZQrM_2syIVICHarxcZlsse2oDDcdO0ZkprhHii28)
> > ![image](https://private-user-images.githubusercontent.com/115404764/348157333-b91abccb-7284-40a6-adbd-d5e1869815b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzA3MTIsIm5iZiI6MTcyMDc3MDQxMiwicGF0aCI6Ii8xMTU0MDQ3NjQvMzQ4MTU3MzMzLWI5MWFiY2NiLTcyODQtNDBhNi1hZGJkLWQ1ZTE4Njk4MTViNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMlQwNzQ2NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZmM5MDViM2I0Zjc5ZmU0NmY4MWIwOTk3YjFjYzc1ZDNiYmExYjdhNWEyZmMzZTI2YzJjMWE3OThiMzE5NzE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pAD_TMHD0VBP5CM2psqXLDsvhXSWVd8ElHZfcVi_cao)
> > **环境信息 / Environment Information**
> > 
> > * langchain-chatchat版本/commit 号：0.3.0
> > * 是否使用 Docker 部署（是/否）：否
> > * 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4-chat
> > * 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
> > * 操作系统及版本 / Operating system and version:  ubantu
> > * Python 版本 / Python version:  py3.10.13
> 
> 已经解决了

老哥，怎么解决的呀？

**Comment by lrn201** [comment]
> 遇到了相同的问题，一直报错，2024-07-15 10：47：24,260 xinference.api.restful_api 12342 错误 聊天完成流出现错误：[address=0.0.0.0：46663， pid=14317] GenerationMixin._get_logits_warper（） 缺少 1 个必需的位置参数：“device”

请问这个问题解决了吗

**Comment by Modas-Li** [comment]
换了模型



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vectors ***@***.***&gt;
发送时间: 2024年7月20日 23:36
收件人: chatchat-space/Langchain-Chatchat ***@***.***&gt;
抄送: Modas Li ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [chatchat-space/Langchain-Chatchat] [BUG] 正常对话出现 RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read) (Issue #4486)





  
遇到了相同的问题，一直报错，2024-07-15 10：47：24,260 xinference.api.restful_api 12342 错误 聊天完成流出现错误：[address=0.0.0.0：46663， pid=14317] GenerationMixin._get_logits_warper（） 缺少 1 个必需的位置参数：“device”
  
请问这个问题解决了吗
