### ISSUE TITLE
是否支持使用本地embedding模型+基于api的在线llm？

### ISSUE THREAD

**Issue by yuzh0816** [chatchat-space/Langchain-Chatchat#4488]
**问题描述 / Problem Description**
请问现在0.3.0的chatchat能否做到使用xinference的embedding模型+基于openai api的在线llm？使用xinference的embedding模型+基于openai api的在线llm？

**Comment by liunux4odoo** [comment]
0.3.1 版已经发布，优化了配置方式，修改配置项无需重启服务器，可以更新尝试。

0.3.x 版本中所有模型都是通过 API 接入。
