### ISSUE TITLE
[BUG]本地知识库对话top_k参数未生效

### ISSUE THREAD

**Issue by umbraclet16** [chatchat-space/Langchain-Chatchat#4493]
修改工具search_local_knowledgebase的top_k参数，重启服务后不生效，仍返回5条。

定位问题位于：

..../server/file_rag/retrievers/ensemble.py最后

```
return EnsembleRetrieverService(retriever=ensemble_retriever)
```

未传入top_k参数。

p.s. 使用vectorstore时，retrievers/vectorstore.py存在相同问题。

**Comment by liunux4odoo** [comment]
你用的什么版本？0.3.1 测试没有该问题。

**Comment by umbraclet16** [comment]
0.3.0。但我看最新的代码这里也没改，难倒没用这段逻辑？

**Comment by liunux4odoo** [comment]
> 0.3.0。但我看最新的代码这里也没改，感觉这块逻辑确实有问题啊？

不要凭感觉，你有没有测试过？

**Comment by umbraclet16** [comment]
我当然是先遇到问题才去看的代码。环境是0.3.0版本AutoDL的镜像，传入了top_k参数就正常了。

**Comment by liunux4odoo** [comment]
0.3.1.1 已经上传，请更新安装后再试一下。

**Comment by liunux4odoo** [comment]
已经测试确认，本地知识库工具配置项中的参数未生效。计划下个版本修复。

**Comment by eric1932** [comment]
不只是 faiss，milvus 也有同样的问题，忘记传参数了
稍后会发个 PR

**Comment by tankGe** [comment]
目前都还没有修复这个问题吗？

**Comment by guhao17** [comment]
还是没有解决啊

**Comment by tankGe** [comment]
ensemble.py中修改代码即可return EnsembleRetrieverService(retriever=ensemble_retriever, top_k=top_k)
