### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by fjzuser** [chatchat-space/Langchain-Chatchat#4495]
**问题描述 / Problem Description**
依据源文件重建向量库这步都出错，已经完成向量化了，还是报错

**复现问题的步骤 / Steps to Reproduce**
依据源文件重建向量库这步都出错
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
chatchat.server.knowledge base.kb doc api:output:4577.- 添加文件'新建文本文档(2).xt’到知识库'双’时出错:从文件 xx/新建文本文档(2).txt 加载文档时出铻:No module named'exceptions已跳过NoneType: None5

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.1
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：ChatGLM4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：m3e
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: win10
- Python 版本 / Python version:3.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by BaoxingZhang** [comment]
刚好遇到“No module named 'exceptions'”这个报错。
应该是安装了错误的包导致，实际应该安装python-docx这个包，需要先卸载掉docx(如果有安装)，然后再安装python-docx这个包
pip  uninstall  docx

pip  install python-docx
