### ISSUE TITLE
 Chat with model internVL does not support stream

### ISSUE THREAD

**Issue by libai-lab** [chatchat-space/Langchain-Chatchat#4499]
1.Chat with model internVL does not support stream
2.xinference在使用接口测试internvl图片描述准确，但是使用chatchat后描述不沾边
3.创建向量数据库的时候一直卡在downloading package punkt to root/nltk_Data

**Comment by liunux4odoo** [comment]
第1、2个问题，请提供一下操作步骤，后台输出
第3个问题，0.3.1已经修复。0.3.0的话可以手动把项目目录下的 nltk_data 拷到你数据目录下。

**Comment by Maekfei** [comment]
> 第1、2个问题，请提供一下操作步骤，后台输出 第3个问题，0.3.1已经修复。0.3.0的话可以手动把项目目录下的 nltk_data 拷到你数据目录下。

关于第三个问题 在linux下 copy过去还是一直卡着
![image](https://github.com/user-attachments/assets/3f80e356-0af7-42f8-b642-8a1c22142c85)

**Comment by Maekfei** [comment]
chatchat_data 下的 nltk_data 在完成前面部署之后 文件夹内容为空 这个情况正常吗

**Comment by Maekfei** [comment]
> > 第1、2个问题，请提供一下操作步骤，后台输出 第3个问题，0.3.1已经修复。0.3.0的话可以手动把项目目录下的 nltk_data 拷到你数据目录下。
> 
> 关于第三个问题 在linux下 copy过去还是一直卡着 ![image](https://private-user-images.githubusercontent.com/60313724/354523164-3f80e356-0af7-42f8-b642-8a1c22142c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1ODY5NDgsIm5iZiI6MTcyMjU4NjY0OCwicGF0aCI6Ii82MDMxMzcyNC8zNTQ1MjMxNjQtM2Y4MGUzNTYtMGFmNy00MmY4LWI2NDItOGExYzIyMTQyYzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA4MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MjliNzUwZjI4ODY2N2M1MzQ3NzFjYTA0YWZlZjhmOGE5YjM2Njk0ZDgyMzRlMmVhNDA5MTRlYTIwMTlkMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aNZ6el8PUW-DToVyjGG7q4Y8Tb5ChPa83m6hy2PXLiU)
问题已解决 重新删除文件夹又复制了一遍
