### ISSUE TITLE
[BUG] 简洁阐述问题 / UnboundLocalError: local variable 'resp' referenced before assignment

### ISSUE THREAD

**Issue by aappaappoo** [chatchat-space/Langchain-Chatchat#450]
在最新一版的代码中， 运行api.py 出现了以上错误（UnboundLocalError: local variable 'resp' referenced before assignment）， 通过debug的方式观察到local_doc_qa.llm.generatorAnswer(prompt=question, history=history,streaming=True)可能不返回任何值。

**Comment by daxian-lh** [comment]
怎么解决，我也遇到了

**Comment by daxian-lh** [comment]
希望有大佬能帮助下

**Comment by lushun666** [comment]
这个问题解决了吗，我也遇到这个问题了

**Comment by zhoucz97** [comment]
遇到相同问题

**Comment by zhaozhiming** [comment]
+1

**Comment by zhaozhiming** [comment]
> 有个bug必现的步骤，就是在调用api 的websocket接口时，传入 history 参数，就会导致这个错误，如果没有传hisotry或者history=[]则不会报错。
> 
> 在api.py文件：
> 
> ```python
> async def stream_chat(websocket: WebSocket):
>     ......
>         last_print_len = 0
>         for resp, history in local_doc_qa.get_knowledge_based_answer(
>                 query=question, vs_path=vs_path, chat_history=history, streaming=True
>         ):
>             await asyncio.sleep(0)
>             await websocket.send_text(resp["result"][last_print_len:])
>             last_print_len = len(resp["result"])
> 
>         source_documents = [
>             f"""出处 [{inum + 1}] {os.path.split(doc.metadata['source'])[-1]}：\n\n{doc.page_content}\n\n"""
>             f"""相关度：{doc.metadata['score']}\n\n"""
>             for inum, doc in enumerate(resp["source_documents"]) # 这里报错
>         ]
>   ......
> ```

发现是我的history参数传错了，应该传`[['a', 'b']]`这种格式，我传成了`['a', 'b']`
