### ISSUE TITLE
[BUG] python cli.py init时默认去连xinference，若xinference服务不存在或不在默认端口时会报错

### ISSUE THREAD

**Issue by songpb** [chatchat-space/Langchain-Chatchat#4508]
**问题描述 / Problem Description**
python cli.py init时默认去连xinference，若xinference服务不存在或不在默认端口时会报错

**复现问题的步骤 / Steps to Reproduce**
1. 不启动xinference
2. 执行python cli.py init
3. 问题出现 
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=9997): Max retries exceeded with url: /v1/cluster/auth (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1254a6e50>: Failed to establish a new connection: [Errno 61] Connection refused'))

初始化项目配置文件和数据目录时并不需要模型服务，建议初始化时不要连接xinference，或者至少在README中指引修改settings.py中的默认配置项

**Comment by liunux4odoo** [comment]
0.3.1.1 中已经修复，请更新安装后再试一下。

**Comment by snowpalm** [comment]
是否该语句有问题？  server\utils.py     if not m.get("platform_type") == "xinference":  -->  if not m.get("platform_type") == "xinference_auto":  # TODO：当前仅支持 xf 自动检测模型
