### ISSUE TITLE
0.2版运行本地的大模型，卡住或报错 

### ISSUE THREAD

**Issue by ovjust** [chatchat-space/Langchain-Chatchat#4509]
0.2版 运行本地的chatglm, 卡在了  Loading the model ['chatglm3-6b'] on worker ca45e0c6 ...

本地运行 Qwen-1_8B-Chat  报错MemoryError

win10, cuda11.8,  torch   2.1.1+cu118

![image](https://github.com/user-attachments/assets/362a7d6b-73b3-46db-8009-77c6641a4a1a)
![image](https://github.com/user-attachments/assets/7d464c3c-b5bc-42d2-a916-0cd4a7b4de43)

**Comment by liunux4odoo** [comment]
0.2.x 已经停止维护。如果要使用建议以 API 的形式接入模型。
