### ISSUE TITLE
引入0.3.0版本仍然无法使用0.3.0版本的配置步骤

### ISSUE THREAD

**Issue by wuwenxun777** [chatchat-space/Langchain-Chatchat#4513]
**引入0.3.0版本仍然无法使用0.3.0版本的配置步骤，0.3.1无法导入docx文件**
尝试引入0.3.0版本，并使用chatchat-config方式去配置，但是显示没有这个命令

我运行了`!pip install langchain-chatchat[xinference]==0.3.0`尝试去安装0.3.0版本的，之后在配置过程中显示`command not found`，包括`!chatchat -a`也无法启动

使用0.3.1的时候，导入docx格式文件，但是无法创造向量库

**Comment by ShinyWey** [comment]
> 使用0.3.1的时候，导入docx格式文件，但是无法创造向量库

+1,  我记得0.2.x版本都可以的, api实测也不行
![image](https://github.com/user-attachments/assets/88c70357-1a01-49b9-9e36-549e1d4d667a)

**Comment by lrw-lee** [comment]
@ShinyWey pip install python-docx

**Comment by ShinyWey** [comment]
> @ShinyWey pip install python-docx

thx
