### ISSUE TITLE
知识库管理中添加docx格式文件报错：zipfile.BadZipFile: File is not a zip file

### ISSUE THREAD

**Issue by Jiweipy** [chatchat-space/Langchain-Chatchat#4520]
**问题描述 / Problem Description**
知识库管理中，添加文件到知识库，md格式文件正常处理， 然而docx、txt和pdf格式文件，点击“添加文件到知识库”时候报错。

**复现问题的步骤 / Steps to Reproduce**
1. 点击按钮：知识库管理
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
![image](https://github.com/user-attachments/assets/3e99eb46-c24d-48bc-a0b0-e30a91911889)

**实际结果 / Actual Result**
![image](https://github.com/user-attachments/assets/8ec21489-ea4a-43ab-b2ab-58cd1234d5d4)

![image](https://github.com/user-attachments/assets/a76e6f21-e7db-439f-85b5-8893957ce841)

![image](https://github.com/user-attachments/assets/2a30afe8-0e6c-4956-bc3a-5b6ccafdeb38)

**环境信息 / Environment Information**
依赖版本号：
unstructured==0.11.0
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：glm-4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：embedding-2
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu
- Python 版本 / Python version: 3.10
- 其他相关环境信息 / Other relevant environment information: Linux localhost.localdomain 3.10.0-1160.105.1.el7.x86_64 #1 SMP Thu Dec 7 15:39:45 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by Jiweipy** [comment]
已解决：

项目启动前，设置环境变量：`export NLTK_DATA=/path/to/nltk_data`

**Comment by 1223243** [comment]
我也是这个问题，请问怎么解决，

**Comment by 1223243** [comment]
![Uploading 微信图片_20240731184724.png…]()

**Comment by 1223243** [comment]
我也是这个问题，请问怎么解决，
![Uploading 微信图片_20240731184724.png…]()

**Comment by 1223243** [comment]
我也是这个问题，请问怎么解决，
![Uploading 1.png…]()

**Comment by weiyuan0727** [comment]
去看这个 博客 https://blog.csdn.net/zywmac/article/details/136872046
