### ISSUE TITLE
[BUG] Langchain-Chatchat API Server  v0.3.0 OAS 3.1调用错误

### ISSUE THREAD

**Issue by swvincent8498** [chatchat-space/Langchain-Chatchat#4529]
https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/api.md ，这个API说明和项目中API描述有出入。
项目API信息：Langchain-Chatchat API Server  v0.3.0 OAS 3.1
我使用了项目中/chat/chat 对话/chat_chat_chat_post接口里面例子，调用出错，后台抛错看不出什么错误。

项目中的/chat/chat 对话接口，例子中的json请求是不是缺少了数据呢？

![image](https://github.com/user-attachments/assets/1bc5cca1-4c00-4ee5-a29f-98ddef256e95)

**Comment by liunux4odoo** [comment]
/chat/chat 接口已经废弃。
https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/api.md 描述了对 /chat/chat/completions, /knowledge_base/chat/completions 接口的调用方式。

**Comment by swvincent8498** [comment]
我整理了一下：

MediaType JSON = MediaType.get("application/json; charset=utf-8");
		String API_URL="http://192.168.11.6:7861/chat/chat/completions";
		String MODEL="glm4_9b_chat";
		
		String input="你好！";
		
		OkHttpClient.Builder builder = new OkHttpClient.Builder();

        builder.connectTimeout(10, TimeUnit.SECONDS);
        builder.readTimeout(60, TimeUnit.SECONDS);
        
		OkHttpClient client = builder.build();

		JSONObject req = new JSONObject();
		req.put("model", MODEL);
		req.put("stream", false);
		req.put("temperature", 0.7);

		
		req.put("tool_choice", "search_local_knowledgebase");
		JSONObject tool_input=new JSONObject();
		tool_input.put("database","samples");//对应页面“本地知识库”中“Database”名称
		tool_input.put("query",input);
		req.put("tool_input", tool_input);
		
		JSONArray msgs=new JSONArray();
		JSONObject msg=new JSONObject();
		msg.put("role","user");
		msg.put("content",input);
		msgs.add(msg);
		req.put("messages", msgs);



		RequestBody body = RequestBody.create(req.toString(), JSON);
		Request request = new Request.Builder().url(API_URL).post(body).build();
		try (Response response = client.newCall(request).execute()) {

//			System.out.println(response.body().string());
			String str=response.body().string();
			JSONObject json=JSONObject.parse(str);

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
