### ISSUE TITLE
知识库问答报错RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)

### ISSUE THREAD

**Issue by Ash-swz** [chatchat-space/Langchain-Chatchat#4530]
**问题描述 / Problem Description**
我查看源代码发现出错在usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/kb_doc_api.py
71行处的data = [DocumentWithVSId(**x.dict(), id=x.metadata.get("id")) for x in docs]与
与/usr/local/lib/python3.11/site-packages/chatchat/server/knowledge_base/kb_service/milvus_kb_service.py83行处的
# retriever = get_Retriever("vectorstore").from_vectorstore(
        #     self.milvus,
        #     top_k=top_k,
        #     score_threshold=score_threshold,
        # )
        # docs = retriever.get_relevant_documents(query)
但是在代码文件中会发现在这两个地方有另外注释的一些代码，将原有代码注释掉换成它本身注释的
data = [DocumentWithVSId(**x[0].dict(), score=x[1], id=x[0].metadata.get("id")) for x in docs]与
self._load_milvus()
        embed_func = get_Embeddings(self.embed_model)
        embeddings = embed_func.embed_query(query)
        docs = self.milvus.similarity_search_with_score_by_vector(embeddings, top_k)
知识库可以正常问答了。这是为什么？

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：3.0.1
- 是否使用 Docker 部署（是/否）：是 
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：GLM4
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)：MILVUS
- 操作系统及版本 / Operating system and version: Linux-5.15.0-78-generic-x86_64-with-glibc2.36.
- Python 版本 / Python version:3.11.9
- 其他相关环境信息 / Other relevant environment information:

**Comment by zlpmetyou** [comment]
你这个看起来是milvus连接失败了，你首先确定你修改了kb_settings.yaml里面52行的milvus配置

**Comment by liunux4odoo** [comment]
duplicate of #4525
