### ISSUE TITLE
[BUG] 不添加工具（None）时使用多功能对话报错

### ISSUE THREAD

**Issue by ganwumeng** [chatchat-space/Langchain-Chatchat#4533]
**问题描述 / Problem Description**
不添加工具（None）时使用多功能对话报错，使用工具（如本地知识库工具）或RAG对话功能等均正常

**复现问题的步骤 / Steps to Reproduce**
1. 工具为None（默认）
2. 输入问题并提交
3. 出现错误

**预期的结果 / Expected Result**
问题结果

**实际结果 / Actual Result**
报错：
......
pydantic.v1.error_wrappers.ValidationError: [address=127.0.0.1:50208, pid=63508] 1 validation error for CreateCompletion
tool_choice
  extra fields not permitted (type=value_error.extra)
......

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.3.1
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：Qwen2-1.5b
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：jina-embeddings-v2-base-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: macOS
- Python 版本 / Python version: 3.8.10

**附加信息 / Additional Information**
设置工具后可正常对话

**Comment by liunux4odoo** [comment]
你 pydantic langchain 和 openai 的版本都是多少？

**Comment by ganwumeng** [comment]
xinference：
pydantic_core                 2.16.3
openai                        1.35.12

chatchat：
pydantic                    2.7.4
pydantic_core               2.18.4
openai                      1.35.14


![image](https://github.com/user-attachments/assets/41ab4bcc-5280-4f82-ae19-484cd168ec2e)
![image](https://github.com/user-attachments/assets/8a3d4bff-3754-4a78-8617-b00c645454c7)

好像仅在Xinference平台出现问题，Ollama正常
之前0.3.0正常

**Comment by liunux4odoo** [comment]
你这个报错信息不会是 xinf 里面的吧

**Comment by ganwumeng** [comment]
是xinference里的
刚试了下，把 webui_pages/dialogue/dialogue.py里的第426行的
```python3
for d in client.chat.completions.create(
                messages=messages,
                model=llm_model,
                stream=stream, # TODO：xinference qwen-vl-chat 流式输出会出错，后续看更新
                tools=tools or openai.NOT_GIVEN,
                tool_choice=tool_choice,
                extra_body=extra_body,
                max_tokens=Settings.model_settings.MAX_TOKENS,
            ):
```
改成
```python3
            params = {
                "messages": messages,
                "model": llm_model,
                "stream": stream,  # TODO：xinference qwen-vl-chat 流式输出会出错，后续看更新
                "tools": tools or openai.NOT_GIVEN,
                "extra_body": extra_body,
                "max_tokens": Settings.model_settings.MAX_TOKENS,
            }

            if tool_choice is not None:
                params["tool_choice"] = tool_choice

            result = client.chat.completions.create(**params)

            for d in result:
```
可以解决这一个问题。tool_choice为none的时候，传过去会报错，不传没问题

**Comment by liunux4odoo** [comment]
那跟 tools 参数一样，是 pydantic 校验的问题。我们这边会修改一下。
感谢反馈。
