### ISSUE TITLE
[BUG] chatchat kb -r时候会下载nltk_data

### ISSUE THREAD

**Issue by zlpmetyou** [chatchat-space/Langchain-Chatchat#4535]
**问题描述 / Problem Description**
当我在一个没有网络的环境中部署之后，知识库初始化会downloading nltk，默认会在$HOME中查找nltk_data，但实际上项目DATA_ROOT/data中已经有了nltk_data

问题：这是否是一个bug，使用nltk部分是否可以指定正确的路径DATA_ROOT/data/nltk_data, 或者在chatchat init的时候copy nltk_data到$HOME下（目前我的解决方法，应该是可以指定，不用再复制一份）

**Comment by liunux4odoo** [comment]
Duplicate of #4520 #4523
