### ISSUE TITLE
如何注册tool？

### ISSUE THREAD

**Issue by lelofraser** [chatchat-space/Langchain-Chatchat#4538]
在tools_factory 文件夹模仿其他已有工具新建了py文件 也在 tool_settings,yaml中加了tool项
为什么启动之后工具下拉框里没有增加的工具，到底如何注册新的工具呢？

**Comment by ganwumeng** [comment]
chatchat/server/agent/tools_factory/__init__.py 里检查一下添加了吗？

**Comment by 948024326** [comment]
> 在tools_factory 文件夹模仿其他已有工具新建了py文件 也在 tool_settings,yaml中加了tool项 为什么启动之后工具下拉框里没有增加的工具，到底如何注册新的工具呢？

我也是改了代码，重启没有生效，debug也没进断点，好像直接走的源码去了，和0.2版本不一样。 想请问下解决了嘛？

**Comment by 948024326** [comment]
> chatchat/server/agent/tools_factory/**init**.py 里检查一下添加了吗？

请问您是改了代码后怎么启动程序的哈？

**Comment by ganwumeng** [comment]
> > chatchat/server/agent/tools_factory/**init**.py 里检查一下添加了吗？
> 
> 请问您是改了代码后怎么启动程序的哈？

我是本地源码部署的，没用pip install langchain-chatchat

**Comment by yuehua-s** [comment]
> > 在tools_factory 文件夹模仿其他已有工具新建了py文件 也在 tool_settings,yaml中加了tool项 为什么启动之后工具下拉框里没有增加的工具，到底如何注册新的工具呢？
> 
> 我也是改了代码，重启没有生效，debug也没进断点，好像直接走的源码去了，和0.2版本不一样。 想请问下解决了嘛？

这里有注册吗？
![image](https://github.com/user-attachments/assets/a7472437-9546-449b-9924-d57a69d4a06e)

**Comment by yuehua-s** [comment]
> > chatchat/server/agent/tools_factory/**init**.py 里检查一下添加了吗？
> 
> 请问您是改了代码后怎么启动程序的哈？

建议你看下这个文档
https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md
