### ISSUE TITLE
0.3.1.1版本调用知识库对话接口返回信息中没有模型回答

### ISSUE THREAD

**Issue by CopyPermission** [chatchat-space/Langchain-Chatchat#4562]
**问题描述 / Problem Description**
在7861端口页面测试知识库问答接口（/chat/kb_chat）时发现返回信息中没有模型回答（返回参数中content为空字符串）

**复现问题的步骤 / Steps to Reproduce**
直接在7861端口界面调用知识库问答接口
{
  "query": "你好",
  "mode": "local_kb",
  "kb_name": "samples",
  "top_k": 3,
  "score_threshold": 2,
  "history": [
  ],
  "stream": true,
  "model": "glm-4-flash",
  "temperature": 0.7,
  "max_tokens": 0,
  "prompt_name": "default",
  "return_direct": false
}

**实际结果 / Actual Result**
{
    "data": {
        "id": "chat99f68ca5-1042-4c9c-979a-06c193f658d9",
        "object": "chat.completion.chunk",
        "model": "glm-4-flash",
        "created": 1721292932,
        "status": null,
        "message_type": 1,
        "message_id": null,
        "is_ref": false,
        "docs": [
            "出处 [1] [gt.csv](http://10.0.0.57:7861//knowledge_base/download_doc?knowledge_base_name=gt&file_name=gt.csv) \n\n问题: 停止说话\n答案: 好的，请问还有什么可以帮您？\n\n",
            "出处 [2] [gt.csv](http://10.0.0.57:7861//knowledge_base/download_doc?knowledge_base_name=gt&file_name=gt.csv) \n\n问题: 不用继续说了\n答案: 好的，请问还有什么可以帮您？\n\n"
        ],
        "choices": [
            {
                "delta": {
                    "content": "",
                    "tool_calls": []
                },
                "role": "assistant"
            }
        ]
    }
}

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：0.3.1.1
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM2-6B / Qwen-7B 等）：智普在线api glm-4-flash
- 使用的 Embedding 模型（moka-ai/m3e-base 等）：xinference加载的m3e-base
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:  CentOS7
- Python 版本 / Python version: 3.9

**Comment by liunux4odoo** [comment]
max_tokens 去掉，或者改个大点的值
