### ISSUE TITLE
[BUG] 知识库匹配相关度阈值问题

### ISSUE THREAD

**Issue by umbraclet16** [chatchat-space/Langchain-Chatchat#4565]
配置文件中对于SCORE_THRESHOLD的描述是“score越小，相关度越高，取到2相当于不筛选”。

根据langchain的源码，检索时distance越小越相似是正确的，但在使用threshold进行过滤时，score是转换过的，比如faiss默认应该用了_euclidean_relevance_score_fn()，即:
1 - distance / sqrt(2)

因此，实际是SCORE_THRESHOLD阈值越高越严格。设为2.0时，日志中也打出了警告信息：No relevant docs were retrieved using the relevance score threshold 2.0，实际返回的知识库信息都是bm25的检索结果。

![IMG_20240718_203037.jpg](https://github.com/user-attachments/assets/8ced4735-2f38-4559-af0e-cf516b23130b)

- 版本：v0.3.x
- 是否使用 Docker 部署：是，AutoDL 0.3.0版本镜像
- 使用的模型：Qwen2-instruct
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型: faiss

**Comment by LULU-LULULA** [comment]
> 配置文件中对于SCORE_THRESHOLD的描述是“score越小，相关度越高，取到2相当于不筛选”。
> 
> 根据langchain的源码，检索时distance越小越相似是正确的，但在使用threshold进行过滤时，score是转换过的，比如faiss默认应该用了_euclidean_relevance_score_fn()，即: 1 - distance / sqrt(2)
> 
> 因此，实际是SCORE_THRESHOLD阈值越高越严格。设为2.0时，日志中也打出了警告信息：No relevant docs were retrieved using the relevance score threshold 2.0，实际返回的知识库信息都是bm25的检索结果。
> 
> ![IMG_20240718_203037.jpg](https://private-user-images.githubusercontent.com/13113857/349954554-8ced4735-2f38-4559-af0e-cf516b23130b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NzQzMDMsIm5iZiI6MTcyMTk3NDAwMywicGF0aCI6Ii8xMzExMzg1Ny8zNDk5NTQ1NTQtOGNlZDQ3MzUtMmYzOC00NTU5LWFmMGUtY2Y1MTZiMjMxMzBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA2MDY0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NjAyODQyNDdlMzgyM2Y1YWIyNjU0MmE0MjMzMjVmMTU5MjgwZjE0YzdhYmJmZGY2MDE2YWU3NzAyMmI5ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KLzst4d6eiewFKLQg_FI8de2lonRErT9L1asNa7Dspk)
> 
> * 版本：v0.3.x
> * 是否使用 Docker 部署：是，AutoDL 0.3.0版本镜像
> * 使用的模型：Qwen2-instruct
> * 使用的 Embedding 模型：bge-large-zh-v1.5
> * 使用的向量库类型: faiss

我也遇到了和你一样的问题，向量根本没检索到，返回答案的时间特别长足足100秒，这到底是哪里的问题？

**Comment by firrice** [comment]
![image](https://github.com/user-attachments/assets/a05a2b3e-bec2-4883-aab0-43bd5ca7b693)
debug看了，耗时的是这个jieba的预处理函数，即：每一个query都对所有chunk做一次预处理。。改的话应该也比较容易，预先进行bm25_retriever的初始化，然后作为kb_chat()的参数传进去，而不要每次回答时都做bm25初始化操作。

**Comment by txy6666yr** [comment]
> 配置文件中对于SCORE_THRESHOLD的描述是“score越小，相关度越高，取到2相当于不筛选”。
> 
> 根据langchain的源码，检索时distance越小越相似是正确的，但在使用threshold进行过滤时，score是转换过的，比如faiss默认应该用了_euclidean_relevance_score_fn()，即: 1 - distance / sqrt(2)
> 
> 因此，实际是SCORE_THRESHOLD阈值越高越严格。设为2.0时，日志中也打出了警告信息：No relevant docs were retrieved using the relevance score threshold 2.0，实际返回的知识库信息都是bm25的检索结果。
> 
> ![IMG_20240718_203037.jpg](https://private-user-images.githubusercontent.com/13113857/349954554-8ced4735-2f38-4559-af0e-cf516b23130b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzc5NTEsIm5iZiI6MTcyNDMzNzY1MSwicGF0aCI6Ii8xMzExMzg1Ny8zNDk5NTQ1NTQtOGNlZDQ3MzUtMmYzOC00NTU5LWFmMGUtY2Y1MTZiMjMxMzBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YzA2ODliZjE5ZDZmYzNhOTljMTdmNWMxODM2NzZhY2M0MWZiMDAxOTNiMTZiYWU2Yjg2NTYzNWUzZTQ0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzIi67ldqK0PdpyqJPibtfk2mAdyEmmWs_MCKbNnQj0)
> 
> * 版本：v0.3.x
> * 是否使用 Docker 部署：是，AutoDL 0.3.0版本镜像
> * 使用的模型：Qwen2-instruct
> * 使用的 Embedding 模型：bge-large-zh-v1.5
> * 使用的向量库类型: faiss

所以是值越高越准确吗？是开发者写反了吗？

**Comment by firrice** [comment]
> 配置文件中对于SCORE_THRESHOLD的描述是“score越小，相关度越高，取到2相当于不筛选”。
> 
> 根据langchain的源码，检索时distance越小越相似是正确的，但在使用threshold进行过滤时，score是转换过的，比如faiss默认应该用了_euclidean_relevance_score_fn()，即: 1 - distance / sqrt(2)
> 
> 因此，实际是SCORE_THRESHOLD阈值越高越严格。设为2.0时，日志中也打出了警告信息：No relevant docs were retrieved using the relevance score threshold 2.0，实际返回的知识库信息都是bm25的检索结果。
> 
> ![IMG_20240718_203037.jpg](https://private-user-images.githubusercontent.com/13113857/349954554-8ced4735-2f38-4559-af0e-cf516b23130b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzOTY1MTcsIm5iZiI6MTcyNDM5NjIxNywicGF0aCI6Ii8xMzExMzg1Ny8zNDk5NTQ1NTQtOGNlZDQ3MzUtMmYzOC00NTU5LWFmMGUtY2Y1MTZiMjMxMzBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDA2NTY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkM2RjNDAxMzdjNmU3NDAyNjJjY2IyODBkZWEwNmFkY2YxYWE2MTZhZGJkNzZjMzBiNWQxM2NjNDU4NGIwZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kZw170XbfV0_6a2ip4KPmxDUPQgA5H0OW62WI_ODfso)
> 
> * 版本：v0.3.x
> * 是否使用 Docker 部署：是，AutoDL 0.3.0版本镜像
> * 使用的模型：Qwen2-instruct
> * 使用的 Embedding 模型：bge-large-zh-v1.5
> * 使用的向量库类型: faiss

我也有类似的问题。在faiss retriever中，首先在langchain_community/vectorstores/faiss.py:similarity_search_with_score_by_vector()中对query vector做了L2-normalize，然后和knowlgdge_base中的vectors计算euclidean distance，即有:
![image](https://github.com/user-attachments/assets/481e9fc0-1f6e-4093-9e3b-d8bddf94bc0a)
然后在_euclidean_relevance_score_fn()中将距离转换为相似度，那理论上转换后的应该为:
![image](https://github.com/user-attachments/assets/21439902-925e-4cd0-8ac9-7d1f2d2f3c93)
这个值看起来比较奇怪，更合理的操作更像是 1 - (distance / sqrt(2))^2 = cos(query, knowledge)，不知可有哪位能帮忙解答一下~

**Comment by firrice** [comment]
> > 配置文件中对于SCORE_THRESHOLD的描述是“score越小，相关度越高，取到2相当于不筛选”。
> > 根据langchain的源码，检索时distance越小越相似是正确的，但在使用threshold进行过滤时，score是转换过的，比如faiss默认应该用了_euclidean_relevance_score_fn()，即: 1 - distance / sqrt(2)
> > 因此，实际是SCORE_THRESHOLD阈值越高越严格。设为2.0时，日志中也打出了警告信息：No relevant docs were retrieved using the relevance score threshold 2.0，实际返回的知识库信息都是bm25的检索结果。
> > ![IMG_20240718_203037.jpg](https://private-user-images.githubusercontent.com/13113857/349954554-8ced4735-2f38-4559-af0e-cf516b23130b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzc5NTEsIm5iZiI6MTcyNDMzNzY1MSwicGF0aCI6Ii8xMzExMzg1Ny8zNDk5NTQ1NTQtOGNlZDQ3MzUtMmYzOC00NTU5LWFmMGUtY2Y1MTZiMjMxMzBiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YzA2ODliZjE5ZDZmYzNhOTljMTdmNWMxODM2NzZhY2M0MWZiMDAxOTNiMTZiYWU2Yjg2NTYzNWUzZTQ0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nzIi67ldqK0PdpyqJPibtfk2mAdyEmmWs_MCKbNnQj0)
> > 
> > * 版本：v0.3.x
> > * 是否使用 Docker 部署：是，AutoDL 0.3.0版本镜像
> > * 使用的模型：Qwen2-instruct
> > * 使用的 Embedding 模型：bge-large-zh-v1.5
> > * 使用的向量库类型: faiss
> 
> 所以是值越高越准确吗？是开发者写反了吗？

其实是v0.3之前版本和之后版本使用了两种不同用法导致的。老版本里score表示的是L2-normalize之后的向量之间的euclidean diatance,等价于sqrt(2-2*cosine_similarity)，值域为[0,2]，值越小表示越接近。而v0.3及之后的版本里将distance做了一步转换，转换为similarity，即：1 - distance / sqrt(2)，因此值越大越相近。

**Comment by ArronAI007** [comment]
翻看源码得知 FAISS 默认采用的距离策略是 **DistanceStrategy.EUCLIDEAN_DISTANCE**

@staticmethod
def _euclidean_relevance_score_fn(distance: float) -> float:
    """Return a similarity score on a scale [0, 1]."""
    # The 'correct' relevance function
    # may differ depending on a few things, including:
    # - the distance / similarity metric used by the VectorStore
    # - the scale of your embeddings (OpenAI's are unit normed. Many
    #  others are not!)
    # - embedding dimensionality
    # - etc.
    # This function converts the euclidean norm of normalized embeddings
    # (0 is most similar, sqrt(2) most dissimilar)
    # to a similarity function (0 to 1)
    **return 1.0 - distance / math.sqrt(2)**
