### ISSUE TITLE
[FEATURE] 添加配置项，以便使用云服务器或反向代理时生成正确的公网 API 地址

### ISSUE THREAD

**Issue by pkunight** [chatchat-space/Langchain-Chatchat#4566]
**解决的问题 / Problem Solved**  
在点击检索到的文档, 进行下载时, 目前的逻辑是跳转到api服务去.
![image](https://github.com/user-attachments/assets/d4b7f3ef-6cdc-414c-92b4-a9f8ff282d5a)

但是在从webui服务跳转到api服务时存在两个问题, 会导致访问失败:
1. 跳转链接直接取的api服务的host地址, 如果api.host配的是0.0.0.0, 那么在api_address()方法里面会被转成127.0.0.1; 如果在云服务器上配成公网IP, 则会bind失败(因为公网IP并不在云服务器的网卡上). 这两种情况导致没办法让webui能够正确跳转到api服务的公网ip上.
2. port后面多了一个"/", 也会导致访问失败.

(如果是本机启动服务, 然后在本地开浏览器, 是不会发现这个问题的. 但是在云服务器上启动服务, 要从本地访问, 就有问题了)

![image](https://github.com/user-attachments/assets/de88f386-bb49-4aec-8333-ce41c99079b7)

经检查源码, 主要是这里的问题.
![image](https://github.com/user-attachments/assets/d1d334ed-2ac0-4fb9-a33e-20bed3d811c7)

**实现建议 / Implementation Suggestions**  
在api服务的host配置之外额外增加一个public_host之类的配置, 如果要从webui服务跳转到api服务, 需要使用这个IP地址, 而不是直接取host地址(很多时候都是0.0.0.0).

![image](https://github.com/user-attachments/assets/44ed9463-2711-4ebd-b8dd-529b04605a26)

**Comment by liunux4odoo** [comment]
dev 分支已经修改，下个版本将会实现。

**Comment by pkunight** [comment]
感谢作者快速升级了这个功能! @liunux4odoo 

不过那个跳转链接有两个"/"的问题还未解决, 目前阅读源码暂时没发现为啥跳转链接会带两个"/", 还在寻找中.

目前直接点击链接跳转是这样, 因为有两个"/"会是404, 手动删掉一个"/"才能成功
![image](https://github.com/user-attachments/assets/8b84b2d3-03cc-4d43-b730-8e3bad3388b1)

**Comment by liunux4odoo** [comment]
> 感谢作者快速升级了这个功能! @liunux4odoo
> 
> 不过那个跳转链接有两个"/"的问题还未解决, 目前阅读源码暂时没发现为啥跳转链接会带两个"/", 还在寻找中.
> 
> 目前直接点击链接跳转是这样, 因为有两个"/"会是404, 手动删掉一个"/"才能成功 ![image](https://private-user-images.githubusercontent.com/27330881/350186828-8b84b2d3-03cc-4d43-b730-8e3bad3388b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI1OTIsIm5iZiI6MTcyMTM1MjI5MiwicGF0aCI6Ii8yNzMzMDg4MS8zNTAxODY4MjgtOGI4NGIyZDMtMDNjYy00ZDQzLWI3MzAtOGUzYmFkMzM4OGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzZlOGJlYjIyY2MyZDc3ODJjZjcwZTMwMDBmMGQ1OGUzYjY1Nzc1NTVmNWZhMjQ4NzRhNjdlNDUzY2I5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HoDLciAUbWKwmadF_u1y02KI6piiLpG8W3Vi-wkrnmI)

下载链接带双下划线的问题之前已经修复过了，但目前都还在 dev 分支，得等下个版本发布。

**Comment by liunux4odoo** [comment]
> 感谢作者快速升级了这个功能! @liunux4odoo
> 
> 不过那个跳转链接有两个"/"的问题还未解决, 目前阅读源码暂时没发现为啥跳转链接会带两个"/", 还在寻找中.
> 
> 目前直接点击链接跳转是这样, 因为有两个"/"会是404, 手动删掉一个"/"才能成功 ![image](https://private-user-images.githubusercontent.com/27330881/350186828-8b84b2d3-03cc-4d43-b730-8e3bad3388b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzNTI1OTIsIm5iZiI6MTcyMTM1MjI5MiwicGF0aCI6Ii8yNzMzMDg4MS8zNTAxODY4MjgtOGI4NGIyZDMtMDNjYy00ZDQzLWI3MzAtOGUzYmFkMzM4OGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDAxMjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYzZlOGJlYjIyY2MyZDc3ODJjZjcwZTMwMDBmMGQ1OGUzYjY1Nzc1NTVmNWZhMjQ4NzRhNjdlNDUzY2I5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HoDLciAUbWKwmadF_u1y02KI6piiLpG8W3Vi-wkrnmI)

下载链接带双下划线的问题之前已经修复过了，但目前都还在 dev 分支，得等下个版本发布。
