### ISSUE TITLE
[FEATURE] 有两个文档需要完善的地方

### ISSUE THREAD

**Issue by pkunight** [chatchat-space/Langchain-Chatchat#4570]
1. 源代码安装的流程中, poetry install命令执行前需要先执行`export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`, 否则会报错`Failed to create the collection: Prompt dismissed`;

2. 需要安装`python-docx`依赖库, 否则导入docx文件的时候无法转向量;

3. (目前发现但暂未解决的问题)OCRLoader会漏掉docx文件中的很多内容, 原因暂时不明, 我们先全部使用Unstructed的Loader解决了.

**Comment by liunux4odoo** [comment]
第一个问题没有普遍性，可能是特定环境问题。
第二个不算问题，手动安装一下就可以。
第三个需要后续排查。
