### ISSUE TITLE
本地知识库内 没有 所问的答案，请不要用大语言回答。

### ISSUE THREAD

**Issue by lettergod** [chatchat-space/Langchain-Chatchat#4576]
功能描述 / Feature Description
**目前是本地知识库没有的内容，程序去问大语言模型来回复。**

解决的问题 / Problem Solved
**只搜索本地知识库，没有的答案，不要问大语言来回答。
只想要个，纯本地知识"库"问答。**

**Comment by lettergod** [comment]
期待.....

**Comment by lettergod** [comment]
期盼......

**Comment by lettergod** [comment]
等待......

**Comment by lettergod** [comment]
期望......

**Comment by lettergod** [comment]
> 基本所有的生产环境都有这个需求，如果容忍模型自己乱答，终归只能是个玩具。

是啊，生产环境，不可能允许随意回答的。只能回答行业内的答案（也就是本地知识库我提交的内容），不能用大语言的答案。
可以回答不知道，但不能随意回答。

**Comment by lettergod** [comment]
垫着脚尖，瞅呀瞅。

**Comment by lettergod** [comment]
在回复的信息中，我能否判断出，回复的内容，是本地知识库的答案，还是大语言的答案？

**Comment by liunux4odoo** [comment]
个性化需求请自行修改。
