### ISSUE TITLE
提问时，出现错误An error occurred during streaming

### ISSUE THREAD

**Issue by lrn201** [chatchat-space/Langchain-Chatchat#4579]
### 问题描述 
按照所给流程执行后，出现了界面，但是提问时出现“An error occurred during streaming”

### 复现问题的步骤
1. 在输入框中输入“你好”.'
2. 出现错误“An error occurred during streaming”'

### 预期的结果 
应该输出对“你好”的回复

### 实际结果
输出错误“An error occurred during streaming”

### 环境信息
- langchain-ChatGLM 版本/commit 号：3.1.2
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：本地模型ChatGLM3-6B
- 使用的 Embedding 模型：bge-large-zh
- 使用的向量库类型 ： faiss 
- 操作系统及版本 :linux
- Python 版本:3.11

### 附加信息 
![1](https://github.com/user-attachments/assets/64437ff2-dd1b-4e68-adcc-2da6bd01a8e0)
**日志文件中为**：| ERROR    | chatchat.server.api_server.openai_routes:generator:105 - openai request error: An error occurred during streaming

**Comment by lrn201** [comment]
本地知识库提问时又出现错误：| ERROR    | chatchat.server.utils:wrap_done:46 - APIError: Caught exception: An error occurred during streaming

**Comment by liunux4odoo** [comment]
你把 basic_settings.yaml 里面的 log_verbose 设为 true，看看更详细的错误信息

**Comment by lrn201** [comment]
按照您给的修改后，日志中的显示为：

> 2024-07-22 00:58:30.141 | INFO     | chatchat.startup:start_main_server:257 - 正在启动服务：
> 2024-07-22 00:58:30.142 | INFO     | chatchat.startup:start_main_server:258 - 如需查看 llm_api 日志，请前往 /home/lrn/ALL/Langchain-Chatchat-master/libs/chatchat-server/chatchat/data/logs
> 2024-07-22 00:58:31.359 | INFO     | chatchat.startup:run_api_server:55 - Api MODEL_PLATFORMS: [PlatformConfig(platform_name='xinference', platform_type='xinference', api_base_url='http://127.0.0.1:9997/v1', api_key='EMPTY', api_proxy='', api_concurrencies=5, auto_detect_model=True, llm_models=['chatglm3_6b'], embed_models=['bge_large_zh'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[]), PlatformConfig(platform_name='ollama', platform_type='ollama', api_base_url='http://127.0.0.1:11434/v1', api_key='EMPTY', api_proxy='', api_concurrencies=5, auto_detect_model=False, llm_models=['qwen:7b', 'qwen2:7b'], embed_models=['quentinz/bge-large-zh-v1.5'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[]), PlatformConfig(platform_name='oneapi', platform_type='oneapi', api_base_url='http://127.0.0.1:3000/v1', api_key='sk-', api_proxy='', api_concurrencies=5, auto_detect_model=False, llm_models=['chatglm_pro', 'chatglm_turbo', 'chatglm_std', 'chatglm_lite', 'qwen-turbo', 'qwen-plus', 'qwen-max', 'qwen-max-longcontext', 'ERNIE-Bot', 'ERNIE-Bot-turbo', 'ERNIE-Bot-4', 'SparkDesk'], embed_models=['text-embedding-v1', 'Embedding-V1'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[]), PlatformConfig(platform_name='openai', platform_type='openai', api_base_url='https://api.openai.com/v1', api_key='sk-proj-', api_proxy='', api_concurrencies=5, auto_detect_model=False, llm_models=['gpt-4o', 'gpt-3.5-turbo'], embed_models=['text-embedding-3-small', 'text-embedding-3-large'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[])]
> 2024-07-22 00:58:32.146 | INFO     | chatchat.startup:run_webui:80 - Webui MODEL_PLATFORMS: [PlatformConfig(platform_name='xinference', platform_type='xinference', api_base_url='http://127.0.0.1:9997/v1', api_key='EMPTY', api_proxy='', api_concurrencies=5, auto_detect_model=True, llm_models=['chatglm3_6b'], embed_models=['bge_large_zh'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[]), PlatformConfig(platform_name='ollama', platform_type='ollama', api_base_url='http://127.0.0.1:11434/v1', api_key='EMPTY', api_proxy='', api_concurrencies=5, auto_detect_model=False, llm_models=['qwen:7b', 'qwen2:7b'], embed_models=['quentinz/bge-large-zh-v1.5'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[]), PlatformConfig(platform_name='oneapi', platform_type='oneapi', api_base_url='http://127.0.0.1:3000/v1', api_key='sk-', api_proxy='', api_concurrencies=5, auto_detect_model=False, llm_models=['chatglm_pro', 'chatglm_turbo', 'chatglm_std', 'chatglm_lite', 'qwen-turbo', 'qwen-plus', 'qwen-max', 'qwen-max-longcontext', 'ERNIE-Bot', 'ERNIE-Bot-turbo', 'ERNIE-Bot-4', 'SparkDesk'], embed_models=['text-embedding-v1', 'Embedding-V1'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[]), PlatformConfig(platform_name='openai', platform_type='openai', api_base_url='https://api.openai.com/v1', api_key='sk-proj-', api_proxy='', api_concurrencies=5, auto_detect_model=False, llm_models=['gpt-4o', 'gpt-3.5-turbo'], embed_models=['text-embedding-3-small', 'text-embedding-3-large'], text2image_models=[], image2text_models=[], rerank_models=[], speech2text_models=[], text2speech_models=[])]
> 2024-07-22 00:59:14.558 | ERROR    | chatchat.server.api_server.openai_routes:generator:105 - openai request error: An error occurred during streaming

在启动xinference框架后，启动本地模型chatglm3-6b和bge-large-zh，以及在langchainchatchat网页启动后，输入你好的终端显示信息如下：

> 2024-07-22 00:57:51,857 xinference.model.llm.llm_family 241882 INFO     Caching from URI: /home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b
> 2024-07-22 00:57:51,857 xinference.model.llm.llm_family 241882 INFO     Cache /home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b exists
> 2024-07-22 00:57:52,378 transformers.tokenization_utils_base 242110 INFO     loading file tokenizer.model
> 2024-07-22 00:57:52,378 transformers.tokenization_utils_base 242110 INFO     loading file added_tokens.json
> 2024-07-22 00:57:52,378 transformers.tokenization_utils_base 242110 INFO     loading file special_tokens_map.json
> 2024-07-22 00:57:52,378 transformers.tokenization_utils_base 242110 INFO     loading file tokenizer_config.json
> 2024-07-22 00:57:52,378 transformers.tokenization_utils_base 242110 INFO     loading file tokenizer.json
> 2024-07-22 00:57:52,416 transformers.configuration_utils 242110 INFO     loading configuration file /home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b/config.json
> 2024-07-22 00:57:52,416 transformers.configuration_utils 242110 INFO     loading configuration file /home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b/config.json
> 2024-07-22 00:57:52,417 transformers.configuration_utils 242110 INFO     Model config ChatGLMConfig {
>   "_name_or_path": "/home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b",
>   "add_bias_linear": false,
>   "add_qkv_bias": true,
>   "apply_query_key_layer_scaling": true,
>   "apply_residual_connection_post_layernorm": false,
>   "architectures": [
>     "ChatGLMModel"
>   ],
>   "attention_dropout": 0.0,
>   "attention_softmax_in_fp32": true,
>   "auto_map": {
>     "AutoConfig": "configuration_chatglm.ChatGLMConfig",
>     "AutoModel": "modeling_chatglm.ChatGLMForConditionalGeneration",
>     "AutoModelForCausalLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
>     "AutoModelForSeq2SeqLM": "modeling_chatglm.ChatGLMForConditionalGeneration",
>     "AutoModelForSequenceClassification": "modeling_chatglm.ChatGLMForSequenceClassification"
>   },
>   "bias_dropout_fusion": true,
>   "classifier_dropout": null,
>   "eos_token_id": 2,
>   "ffn_hidden_size": 13696,
>   "fp32_residual_connection": false,
>   "hidden_dropout": 0.0,
>   "hidden_size": 4096,
>   "kv_channels": 128,
>   "layernorm_epsilon": 1e-05,
>   "model_type": "chatglm",
>   "multi_query_attention": true,
>   "multi_query_group_num": 2,
>   "num_attention_heads": 32,
>   "num_layers": 28,
>   "original_rope": true,
>   "pad_token_id": 0,
>   "padded_vocab_size": 65024,
>   "post_layer_norm": true,
>   "pre_seq_len": null,
>   "prefix_projection": false,
>   "quantization_bit": 0,
>   "rmsnorm": true,
>   "seq_length": 8192,
>   "tie_word_embeddings": false,
>   "torch_dtype": "float16",
>   "transformers_version": "4.42.4",
>   "use_cache": true,
>   "vocab_size": 65024
> }
> 
> 2024-07-22 00:57:52,659 transformers.modeling_utils 242110 INFO     loading weights file /home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b/pytorch_model.bin.index.json
> 2024-07-22 00:57:52,659 transformers.modeling_utils 242110 INFO     Instantiating ChatGLMForConditionalGeneration model under default dtype torch.float16.
> 2024-07-22 00:57:52,659 transformers.generation.configuration_utils 242110 INFO     Generate config GenerationConfig {
>   "eos_token_id": 2,
>   "pad_token_id": 0
> }
> 
> Loading checkpoint shards: 100%|█████████████████████████| 7/7 [00:02<00:00,  3.08it/s]
> 2024-07-22 00:57:56,095 transformers.modeling_utils 242110 INFO     All model checkpoint weights were used when initializing ChatGLMForConditionalGeneration.
> 
> 2024-07-22 00:57:56,095 transformers.modeling_utils 242110 INFO     All the weights of ChatGLMForConditionalGeneration were initialized from the model checkpoint at /home/lrn/ALL/Langchain-Chatchat/models/chatglm3-6b.
> If your task is similar to the task the model of the checkpoint was trained on, you can already use ChatGLMForConditionalGeneration for predictions without further training.
> 2024-07-22 00:57:56,096 transformers.modeling_utils 242110 INFO     Generation config file not found, using a generation config created from the model config.
> 2024-07-22 00:58:15,016 xinference.model.utils 241882 INFO     Model caching from URI: /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh
> 2024-07-22 00:58:15,016 xinference.model.utils 241882 INFO     cache /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh exists
> 2024-07-22 00:58:16,537 transformers.configuration_utils 242537 INFO     loading configuration file /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh/config.json
> 2024-07-22 00:58:16,537 transformers.dynamic_module_utils 242537 INFO     Patched resolve_trust_remote_code: (False, '/home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh', True, False) {}
> 2024-07-22 00:58:16,538 transformers.configuration_utils 242537 INFO     Model config BertConfig {
>   "_name_or_path": "/home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh",
>   "architectures": [
>     "BertModel"
>   ],
>   "attention_probs_dropout_prob": 0.1,
>   "bos_token_id": 0,
>   "classifier_dropout": null,
>   "directionality": "bidi",
>   "eos_token_id": 2,
>   "hidden_act": "gelu",
>   "hidden_dropout_prob": 0.1,
>   "hidden_size": 1024,
>   "id2label": {
>     "0": "LABEL_0"
>   },
>   "initializer_range": 0.02,
>   "intermediate_size": 4096,
>   "label2id": {
>     "LABEL_0": 0
>   },
>   "layer_norm_eps": 1e-12,
>   "max_position_embeddings": 512,
>   "model_type": "bert",
>   "num_attention_heads": 16,
>   "num_hidden_layers": 24,
>   "output_past": true,
>   "pad_token_id": 0,
>   "pooler_fc_size": 768,
>   "pooler_num_attention_heads": 12,
>   "pooler_num_fc_layers": 3,
>   "pooler_size_per_head": 128,
>   "pooler_type": "first_token_transform",
>   "position_embedding_type": "absolute",
>   "torch_dtype": "float32",
>   "transformers_version": "4.42.4",
>   "type_vocab_size": 2,
>   "use_cache": true,
>   "vocab_size": 21128
> }
> 
> 2024-07-22 00:58:16,561 transformers.dynamic_module_utils 242537 INFO     Patched resolve_trust_remote_code: (False, '/home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh', True, False) {}
> 2024-07-22 00:58:16,563 transformers.modeling_utils 242537 INFO     loading weights file /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh/model.safetensors
> 2024-07-22 00:58:16,897 transformers.modeling_utils 242537 INFO     All model checkpoint weights were used when initializing BertModel.
> 
> 2024-07-22 00:58:16,897 transformers.modeling_utils 242537 INFO     All the weights of BertModel were initialized from the model checkpoint at /home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh.
> If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
> 2024-07-22 00:58:16,916 transformers.dynamic_module_utils 242537 INFO     Patched resolve_trust_remote_code: (False, '/home/lrn/ALL/Langchain-Chatchat/models/bge-large-zh', True, False) {}
> 2024-07-22 00:58:16,916 transformers.tokenization_utils_base 242537 INFO     loading file vocab.txt
> 2024-07-22 00:58:16,916 transformers.tokenization_utils_base 242537 INFO     loading file tokenizer.json
> 2024-07-22 00:58:16,916 transformers.tokenization_utils_base 242537 INFO     loading file added_tokens.json
> 2024-07-22 00:58:16,916 transformers.tokenization_utils_base 242537 INFO     loading file special_tokens_map.json
> 2024-07-22 00:58:16,916 transformers.tokenization_utils_base 242537 INFO     loading file tokenizer_config.json
> --- Logging error ---
> Traceback (most recent call last):
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/logging/handlers.py", line 73, in emit
>     if self.shouldRollover(record):
>        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/logging/handlers.py", line 196, in shouldRollover
>     msg = "%s\n" % self.format(record)
>                    ^^^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/logging/__init__.py", line 953, in format
>     return fmt.format(record)
>            ^^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/logging/__init__.py", line 687, in format
>     record.message = record.getMessage()
>                      ^^^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/logging/__init__.py", line 377, in getMessage
>     msg = msg % self.args
>           ~~~~^~~~~~~~~~~
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/threading.py", line 995, in _bootstrap
>     self._bootstrap_inner()
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
>     self.run()
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/threading.py", line 975, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
>     work_item.run()
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 402, in _wrapper
>     return next(_gen)
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 318, in _to_json_generator
>     for v in gen:
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/utils.py", line 558, in _to_chat_completion_chunks
>     for i, chunk in enumerate(chunks):
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/pytorch/chatglm.py", line 259, in _stream_generator
>     for chunk_text, _ in self._model.stream_chat(
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/home/lrn/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1069, in stream_chat
>     for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>   File "/home/lrn/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1118, in stream_generate
>     logger.warn(
> Message: 'Both `max_new_tokens` (=1024) and `max_length`(=1032) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)'
> Arguments: (<class 'UserWarning'>,)
> 2024-07-22 00:59:14,554 xinference.api.restful_api 241707 ERROR    Chat completion stream got an error: [address=0.0.0.0:44797, pid=242110] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'
> Traceback (most recent call last):
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/api/restful_api.py", line 1584, in stream_results
>     async for item in iterator:
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 340, in __anext__
>     return await self._actor_ref.__xoscar_next__(self._uid)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 231, in send
>     return self._process_result_message(result)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
>     raise message.as_instanceof_cause()
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 656, in send
>     result = await self._run_coro(message.message_id, coro)
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/backends/pool.py", line 367, in _run_coro
>     return await coro
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 384, in __on_receive__
>     return await super().__on_receive__(message)  # type: ignore
>     ^^^^^^^^^^^^^^^^^
>   File "xoscar/core.pyx", line 558, in __on_receive__
>     raise ex
>   File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
>     async with self._lock:
>     ^^^^^^^^^^^^^^^^^
>   File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
>     with debug_async_timeout('actor_lock_timeout',
>     ^^^^^^^^^^^^^^^^^
>   File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
>     result = await result
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 431, in __xoscar_next__
>     raise e
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 417, in __xoscar_next__
>     r = await asyncio.to_thread(_wrapper, gen)
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/asyncio/threads.py", line 25, in to_thread
>     return await loop.run_in_executor(None, func_call)
>       ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/concurrent/futures/thread.py", line 58, in run
>     result = self.fn(*self.args, **self.kwargs)
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xoscar/api.py", line 402, in _wrapper
>     return next(_gen)
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/core/model.py", line 318, in _to_json_generator
>     for v in gen:
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/utils.py", line 558, in _to_chat_completion_chunks
>     for i, chunk in enumerate(chunks):
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/xinference/model/llm/pytorch/chatglm.py", line 259, in _stream_generator
>     for chunk_text, _ in self._model.stream_chat(
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1069, in stream_chat
>     for outputs in self.stream_generate(**inputs, past_key_values=past_key_values,
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/anaconda3/envs/xinference/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
>     response = gen.send(None)
>     ^^^^^^^^^^^^^^^^^
>   File "/home/lrn/.cache/huggingface/modules/transformers_modules/chatglm3-6b/modeling_chatglm.py", line 1149, in stream_generate
>     logits_warper = self._get_logits_warper(generation_config)
>     ^^^^^^^^^^^^^^^^^
> TypeError: [address=0.0.0.0:44797, pid=242110] GenerationMixin._get_logits_warper() missing 1 required positional argument: 'device'

**Comment by lrn201** [comment]
我更换了其他的本地模型：glm-4v-9b，还是不能正常的提问

**Comment by liunux4odoo** [comment]
这是模型加载的问题，你可以换 qwen 或 ollama 试试。

**Comment by Solenyalyl** [comment]
不换模型可以解决吗？chatglm3也出现了这样的问题，怎样可以加载好？

**Comment by tyler326** [comment]
是xinference的问题，不是langchain-chatchat的问题，需要降低transformer的版本4.41.2

**Comment by 0zyl** [comment]
求解决办法 大佬

**Comment by Solenyalyl** [comment]
换模型

**Comment by jdx2099** [comment]
请问问题有解决吗，Xinference的web端界面，那个模型问答报错

**Comment by Solenyalyl** [comment]
换成qwen系列的模型

**Comment by Alan-zhong** [comment]
> 换成qwen系列的模型

qwen也同样报错

**Comment by shenshaowei** [comment]
我也遇到这个问题了，请问怎么解决？

**Comment by xuechaofei** [comment]
都是同样的问题 ，没人能解决吗

**Comment by sqxiangxin** [comment]
2024-11-20 20:40:13.852 | ERROR    | chatchat.server.api_server.openai_routes:generator:105 - openai request error: An error occurred during streaming
我也是同样的问题。不知道什么情况。不知道怎么解决

**Comment by xiushu2012** [comment]
@lrn201 我之前用千问搭建是ok的，后来换到glm发现就有这个问题
折腾一番发现在如下情况下可以执行，仅供参考：
1.Name: transformers Version: 4.46.3
2.xinference launch --model-engine vllm --model-name qwen-chat --size-in-billions 7 --model-format pytorch --quantization none

**Comment by xiushu2012** [comment]
qwen用的vllm 正常；glm用  transformer就会报错

**Comment by xwd627917648** [comment]
有人解决了吗？
![image](https://github.com/user-attachments/assets/9b830d81-c10a-41b1-af38-3b15f5057e9a)

**Comment by caixianyu** [comment]
解决了，原因是因为httpx包版本为0.28以上， 不支持代理参数。
只需要降级该包
pip install httpx==0.27.2

**Comment by whq-27** [comment]
+1，网上到处都没有解决方案

**Comment by klauselee07** [comment]
请问解决了吗？也是同样的问题
