### ISSUE TITLE
[BUG] webui 部署后样式不正确

### ISSUE THREAD

**Issue by zhaozhiming** [chatchat-space/Langchain-Chatchat#458]
**问题描述 / Problem Description**
执行`python webui.py`命令部署了web页面后，发现部署后的页面样式不正确，如下图所示：
<img width="1288" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1436694/7d4b119e-b0b5-477c-9276-3e7dd420022c">

**复现问题的步骤 / Steps to Reproduce**
1. 执行 'python webui.py'
2. 浏览器访问 127.0.0.1:7860

**预期的结果 / Expected Result**
页面样式正确，跟仓库中的截图一样

**实际结果 / Actual Result**
页面样式不正确，无法进行页面操作

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456)  
- commit eeea00e294327d27037cb
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）: ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）: GanymedeNil/text2vec-large-chinese
- 操作系统及版本 : ubuntu 20.04
- Python 版本 :  Python 3.9.15
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
有没有换个浏览器试试？看起来不像css丢失，挺像一些浏览器的主题模式的。

**Comment by zhaozhiming** [comment]
> 有没有换个浏览器试试？看起来不像css丢失，挺像一些浏览器的主题模式的。

换过safari也是同样的问题
