### ISSUE TITLE
[BUG] 点击 “依据源文件重建向量库” 会无视原定向量库类型，并使用Faiss重建向量库

### ISSUE THREAD

**Issue by kwunhang** [chatchat-space/Langchain-Chatchat#4587]
**问题描述 / Problem Description**
点击 “依据源文件重建向量库” 会无视原定向量库类型，并使用Faiss重建向量库

**复现问题的步骤 / Steps to Reproduce**
1. 切換到以Milvus做向量库的知識庫
2. 点击 '依据源文件重建向量库' 
3. 向量库會使用Faiss重建向量库並覆寫原本設定

**预期的结果 / Expected Result**
重建的知識庫重建成功並使用Milvus做向量库

**实际结果 / Actual Result**
重建的知識庫變成使用Faiss做向量库

**环境信息 / Environment Information**
- langchain-ChatGLM 版本v0.3.1
- 是否使用 Docker 部署（是/否）：否
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： Faiss / Milvus
- 操作系统及版本 / Operating system and version: Linux Ubuntu
- Python 版本 / Python version: Python 3.11
- 其他相关环境信息 / Other relevant environment information:

**Comment by JiadiLee** [comment]
我也发现了这个问题，一开始选择milvus向量库，传的文件比较大，一直在重复添加，而且不能正常使用。
我把后台强制kill掉之后重新start，然后选择对应的向量库点击重建，添加成功之后发现建的是Faiss库。

**Comment by eric1932** [comment]
重建会使用 yaml 内配置的默认数据库类型，我目前的做法是在重建某个数据库之前临时更改这个值
![CleanShot 2024-07-25 at 00 48 15@2x](https://github.com/user-attachments/assets/0eda080d-b005-4def-8ac4-995a71db4501)

**Comment by liunux4odoo** [comment]
#4682 已经做了修复，能用最新版再试试看吗
