### ISSUE TITLE
[BUG] 使用agent对话时候，模型不能给出正确的工具调用参数

### ISSUE THREAD

**Issue by inrelif** [chatchat-space/Langchain-Chatchat#4588]
**问题描述 / Problem Description**
使用agent对话时候，模型不能给出正确的工具调用参数

当我想搜索印度高温的时候，得到如下模型过程：
Thought: To provide a disaster report on the recent heatwave in India, I need to gather information from reliable news sources.
Action:
```{"action": "search_internet", "action_input": {"query": {"title": "recent India heatwave disaster report", "description": "search for recent heatwave disaster news in India", "type": "string"}}}
```2024-07-22 17:25:15.843 | ERROR    | chatchat.server.utils:wrap_done:46 - ValidationError: Caught exception: 1 validation error for search_internetSchema
query
  str type expected (type=type_error.str)

这里action_input后面的query后面的内容应该是搜索的query，但是这里给出了title，description，type等，
请问这个问题如何解决，是要额外训练agent调用能力吗

**Comment by cc3389** [comment]
我用qwen2-7b也遇到了同样的问题，最后将setting.py里的qwen提示词稍微改了下：
`"Thought: you should always think about the correct input format and what to do\n"`
效果会好一点点，但不多。

系统内存是多少

assistant avatar
Thought: 我需要使用shell API来执行命令以获取系统内存信息。

Action: shell

Action Input: {"query": "cat /proc/meminfo | grep MemTotal"}

系统内存是65662912 kB。

埃尔登法环dlc中有哪些轮椅

assistant avatar
Thought: 我需要搜索关于《艾登法环》DLC中的轮椅的信息。 Action: search_internet Action Input: {"query": {"title": "艾登法环 DLC 中的轮椅", "description": "需要找到《艾登法环》DLC中所有与轮椅相关的物品或内容。"}}

埃尔登法环dlc中有哪些轮椅武器

assistant avatar
Thought: 我需要从互联网上搜索有关《艾尔登法环》DLC中的轮椅武器的信息。

Action: search_internet

Action Input: {"query": "艾尔登法环dlc 轮椅武器"}

《艾尔登法环》DLC中包含多种强大的轮椅流派，如盾戳流、血血怪铁王八、突刺盾、双小曲跳劈吸血、法师拒绝的刺以及最强大的癫火调香瓶等。这些流派在没有收集幽影树碎片的情况下也能单杀梅瑟莫等强大敌人。在黄金树之影DLC中，玩家可以体验到这些轮椅流派带来的高效推图和打boss体验。

**Comment by inrelif** [comment]
> 我用qwen2-7b也遇到了同样的问题，最后将setting.py里的qwen提示词稍微改了下： `"Thought: you should always think about the correct input format and what to do\n"` 效果会好一点点，但不多。
> 
> 系统内存是多少
> 
> assistant avatar Thought: 我需要使用shell API来执行命令以获取系统内存信息。
> 
> Action: shell
> 
> Action Input: {"query": "cat /proc/meminfo | grep MemTotal"}
> 
> 系统内存是65662912 kB。
> 
> 埃尔登法环dlc中有哪些轮椅
> 
> assistant avatar Thought: 我需要搜索关于《艾登法环》DLC中的轮椅的信息。 Action: search_internet Action Input: {"query": {"title": "艾登法环 DLC 中的轮椅", "description": "需要找到《艾登法环》DLC中所有与轮椅相关的物品或内容。"}}
> 
> 埃尔登法环dlc中有哪些轮椅武器
> 
> assistant avatar Thought: 我需要从互联网上搜索有关《艾尔登法环》DLC中的轮椅武器的信息。
> 
> Action: search_internet
> 
> Action Input: {"query": "艾尔登法环dlc 轮椅武器"}
> 
> 《艾尔登法环》DLC中包含多种强大的轮椅流派，如盾戳流、血血怪铁王八、突刺盾、双小曲跳劈吸血、法师拒绝的刺以及最强大的癫火调香瓶等。这些流派在没有收集幽影树碎片的情况下也能单杀梅瑟莫等强大敌人。在黄金树之影DLC中，玩家可以体验到这些轮椅流派带来的高效推图和打boss体验。

感谢，我改prompt试试

**Comment by inrelif** [comment]
> 我用qwen2-7b也遇到了同样的问题，最后将setting.py里的qwen提示词稍微改了下： `"Thought: you should always think about the correct input format and what to do\n"` 效果会好一点点，但不多。
> 
> 系统内存是多少
> 
> assistant avatar Thought: 我需要使用shell API来执行命令以获取系统内存信息。
> 
> Action: shell
> 
> Action Input: {"query": "cat /proc/meminfo | grep MemTotal"}
> 
> 系统内存是65662912 kB。
> 
> 埃尔登法环dlc中有哪些轮椅
> 
> assistant avatar Thought: 我需要搜索关于《艾登法环》DLC中的轮椅的信息。 Action: search_internet Action Input: {"query": {"title": "艾登法环 DLC 中的轮椅", "description": "需要找到《艾登法环》DLC中所有与轮椅相关的物品或内容。"}}
> 
> 埃尔登法环dlc中有哪些轮椅武器
> 
> assistant avatar Thought: 我需要从互联网上搜索有关《艾尔登法环》DLC中的轮椅武器的信息。
> 
> Action: search_internet
> 
> Action Input: {"query": "艾尔登法环dlc 轮椅武器"}
> 
> 《艾尔登法环》DLC中包含多种强大的轮椅流派，如盾戳流、血血怪铁王八、突刺盾、双小曲跳劈吸血、法师拒绝的刺以及最强大的癫火调香瓶等。这些流派在没有收集幽影树碎片的情况下也能单杀梅瑟莫等强大敌人。在黄金树之影DLC中，玩家可以体验到这些轮椅流派带来的高效推图和打boss体验。

改prompt不太管用，查了半天发现可以通过修改search_internet.py里面工具的输入参数格式来解决：

from typing import Dict, List,Union,Any

QueryType = Dict[str, str]

@regist_tool(title="互联网搜索")
def search_internet(query: QueryType = Field(description="query for Internet search")):
    """Use this tool to use bing search engine to search the internet and get information."""
    return BaseToolOutput(search_engine(query=query['title']), format=format_context)

**Comment by liunux4odoo** [comment]
你用的glm4吧？建议换qwen试试。后面可能会针对glm4 tool call做适配。
