### ISSUE TITLE
[FEATURE] 从v0.2升级到v0.3，重建向量数据库太慢了，有方法可以加快吗？

### ISSUE THREAD

**Issue by andyzhou1982** [chatchat-space/Langchain-Chatchat#4590]
**功能描述 / Feature Description**
800M的doc文档重建向量库总共用了四个多小时，随着以后文档越来越多，如果要重建一次向量库估计要以天来计算。迫切希望能够有新的方法加快重建向量库的过程，这对我们非常重要，再次感谢项目组一直以来的工作

**Comment by zqt996** [comment]
在改了
