### ISSUE TITLE
agent数据库对话功能不能连接mysql数据库，UnicodeEncodeError：'latin-1' codec can't encode characters in position 0-1: ordinal not in range(256

### ISSUE THREAD

**Issue by ln410** [chatchat-space/Langchain-Chatchat#4591]
报错显示字符编码有问题：
![截图 2024-07-22 11-33-11](https://github.com/user-attachments/assets/b46071bd-1884-4fed-80e4-05284749060c)
但是我把latin-1改成utf8，他又报错说连不上数据库：sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '主机地址' ([Errno -3] Temporary failure in name resolution)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
我确认我的用户名密码库名都是正确的 因为之前连接过 没有任何改动

**Comment by a2382625920** [comment]
我也有同样的问题，如何解决的？

**Comment by charlie6208** [comment]
> 我也有同样的问题，如何解决的？
老哥您解决了吗，求教
