### ISSUE TITLE
[BUG]Docker部署后重建向量库会重新下载nltk_data导致卡顿

### ISSUE THREAD

**Issue by zhaochuninhefei** [chatchat-space/Langchain-Chatchat#4596]
**问题描述 / Problem Description**
Docker部署后，chatchat容器内的nltk_data目录在`/root/chatchat_data/data/nltk_data`。但如果在知识库页面执行[依据源文件重建向量库]，或直接在容器内执行`chatchat kb -r`，则会重新下载nltk_data到`/root/nltk_data`，日志如下:
```
[nltk_data] Downloading package punkt to /root/nltk_data...
```
应该是代码中对nltk_data目录的管理不统一。
目前我直接在容器内将`/root/chatchat_data/data/nltk_data`复制一份到`/root/nltk_data`可解决该问题。

**复现问题的步骤 / Steps to Reproduce**
略。。。

**预期的结果 / Expected Result**
略。。。

**实际结果 / Actual Result**
略。。。

**环境信息 / Environment Information**
langchain-Chatchat 版本/commit 号：0.3.1.2-2024-0720

**附加信息 / Additional Information**
无

**Comment by liunux4odoo** [comment]
这是个 bug，可以按你的方法先工作起来，下个版本会修复。
