### ISSUE TITLE
[BUG] 0.3.1用源码部署运行后报错时还是chatchat包的路径

### ISSUE THREAD

**Issue by radiant22** [chatchat-space/Langchain-Chatchat#4599]
![afdc7ba19f4b6850a6e77895f2bfe2f](https://github.com/user-attachments/assets/1308f9bb-3997-4ebe-b333-58df6dfe2b03)
![ed262db70faa7e3509a5e9a8122c93d](https://github.com/user-attachments/assets/b6723899-55ff-4ff8-964a-dac4fca812f5)

**Comment by andyzhou1982** [comment]
你是用chatchat start -a命令启动的服务？

**Comment by radiant22** [comment]
> 你是用chatchat start -a命令启动的服务？

对的
