### ISSUE TITLE
针对非utf8的txt文档添加到知识库的时候会报embedding错误

### ISSUE THREAD

**Issue by joyyu007** [chatchat-space/Langchain-Chatchat#4601]
**问题描述 / Problem Description**
新建知识库，添加gb2312的txt文档，会抛出如下图所示的错误
![image](https://github.com/user-attachments/assets/d64d246e-2fe2-4bbc-9e9f-b9e7ecc494bc)

将该文档修改为utf8的编码后，成功添加

**Comment by liunux4odoo** [comment]
只支持 utf-8 编码，这不是 bug.
