### ISSUE TITLE
ValueError: samples is not in iterable

### ISSUE THREAD

**Issue by sevenandseven** [chatchat-space/Langchain-Chatchat#4602]

**Comment by sevenandseven** [comment]
> 你好，我在按照上述操作进行执行，创建完知识库进行知识问答时出现： 2024-07-25 09:50:27,918 httpx 18967 INFO HTTP Request: GET http://127.0.0.1:7863/knowledge_base/list_knowledge_bases "HTTP/1.1 200 OK" 2024-07-25 09:50:27.919 Uncaught app exception Traceback (most recent call last): File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script exec(code, module.**dict**) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/chatchat/webui.py", line 71, in kb_chat(api=api) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/chatchat/webui_pages/kb_chat.py", line 119, in kb_chat selected_kb = st.selectbox( File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/streamlit/runtime/metrics_util.py", line 397, in wrapped_func result = non_optional_func(*args, **kwargs) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/streamlit/elements/widgets/selectbox.py", line 203, in selectbox return self._selectbox( File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/streamlit/elements/widgets/selectbox.py", line 305, in _selectbox serialized_value = serde.serialize(widget_state.value) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/streamlit/elements/widgets/selectbox.py", line 66, in serialize return index_(self.options, v) File "/home/ai/anaconda3/envs/langchain_chatchat/lib/python3.10/site-packages/streamlit/util.py", line 155, in index_ raise ValueError(f"{str(x)} is not in iterable") ValueError: samples is not in iterable
> 
> 请问这个怎么解决？目前使用的时0.3.1.2版本，streamlit 1.34.0 streamlit-aggrid 1.0.5 streamlit-antd-components 0.3.1 streamlit-camera-input-live 0.2.0 streamlit-card 1.0.2 streamlit-chatbox 1.1.12.post4 streamlit-embedcode 0.1.2 streamlit-extras 0.4.2 streamlit-faker 0.0.3 streamlit-feedback 0.1.3 streamlit-image-coordinates 0.1.9 streamlit-keyup 0.2.4 streamlit-modal 0.1.0 streamlit-option-menu 0.3.12 streamlit-paste-button 0.1.2 streamlit-toggle-switch 1.0.2 streamlit-vertical-slider 2.5.5

**Comment by 1907010218** [comment]
你好，请问该问题解决了吗？
