### ISSUE TITLE
[Olloma] 該框架是否支援ollama 3.1

### ISSUE THREAD

**Issue by Glen-Chen-Blue** [chatchat-space/Langchain-Chatchat#4606]
想知道這個框架是否可以使用ollama 3.1，同時model_settings.yaml該如何配置

**Comment by fangxuehouwuming** [comment]
同问

**Comment by yhfgyyf** [comment]
ollama3.1是哪个版本，ollama最近才出0.3.0版本。
如果是llama3.1，可以使用xinference，按照llama3注册（需要更新transformers和vllm），也可以使用ollama pull llama3.1，但是现在可能还有点问题，主要是rope的问题

**Comment by lizhenkai5008** [comment]
主要怎么使用OLLAM运行大模型，OLLAMA安装简单，现在最新版本支持LLAMA3.1
