### ISSUE TITLE
请教：对话调用的/chat/chat接口实际上与哪个端口相关，与20002端口相关吗？

### ISSUE THREAD

**Issue by Longleaves** [chatchat-space/Langchain-Chatchat#4607]
想请教一下，对话调用的/chat/chat接口实际上与哪个端口相关？/chat/chat为以下：
    app.post("/chat/chat",
             tags=["Chat"],
             summary="与llm模型对话(通过LLMChain)",
             )(chat)

是与startup.py中的run_model_worker启动的20002端口相关吗？是怎么样联动/chat/chat接口的？希望大佬们告知一下相关位置在哪里，感激不尽！

**Comment by SwordHG** [comment]
遵循的是openai的接口，所以你可以看到get openai这个，它里面有第一fastchat的openai地址，就是这么交互的

**Comment by SwordHG** [comment]
fastchat就是又做了一层，实际意义就是可以各种模型返回结构

**Comment by Longleaves** [comment]
> 遵循的是openai的接口，所以你可以看到get openai这个，它里面有第一fastchat的openai地址，就是这么交互的

@SwordHG 感谢大佬！
我看代码确实如此，再请教一下：那实际上在使用本地模型的时候，就是再调用fastchat封装后的20002端口是吗？那是不是意味着我把20002端口改成gunicorn多进程启动就能实现并发呀？
