### ISSUE TITLE
/chat/chat/completions 兼容 openai 的统一 chat 接口，怎么调用？可以举例调用？ 

### ISSUE THREAD

**Issue by as100863** [chatchat-space/Langchain-Chatchat#4612]
{
  "user": "string",
  "extra_headers": {},
  "extra_query": {},
  "extra_body": {},
  "timeout": 0,
  "messages": [
    {
      "content": "string",
      "role": "system",
      "name": "string"
    },
    {
      "content": "string",
      "role": "user",
      "name": "string"
    },
    {
      "content": "string",
      "role": "assistant",
      "name": "string",
      "function_call": {
        "arguments": "string",
        "name": "string"
      },
      "tool_calls": [
        {
          "id": "string",
          "function": {
            "arguments": "string",
            "name": "string"
          },
          "type": "function"
        }
      ]
    },
    {
      "content": "string",
      "role": "tool",
      "name": "string",
      "tool_call_id": "string"
    },
    {
      "content": "string",
      "role": "function",
      "name": "string"
    }
  ],
  "model": "glm4",
  "frequency_penalty": 0,
  "function_call": "none",
  "functions": [
    {
      "name": "string",
      "description": "string",
      "parameters": {}
    }
  ],
  "logit_bias": {
    "additionalProp1": 0,
    "additionalProp2": 0,
    "additionalProp3": 0
  },
  "logprobs": true,
  "max_tokens": 0,
  "n": 0,
  "presence_penalty": 0,
  "response_format": {
    "type": "text"
  },
  "seed": 0,
  "stop": "string",
  "stream": true,
  "temperature": 0.7,
  "tool_choice": "none",
  "tools": [
    {
      "function": {
        "name": "string",
        "description": "string",
        "parameters": {}
      },
      "type": "function"
    },
    "string"
  ],
  "top_logprobs": 0,
  "top_p": 0,
  "additionalProp1": {}
}

**Comment by wny2050** [comment]
提问、model name 应该填写在哪个字段？

**Comment by wny2050** [comment]
/Chat/chat 与llm模型对话(通过LLMChain) ，想要使用langchain 0.2 这个接口的功能，应该怎么调用

**Comment by njzfw1024** [comment]
{
  "model": "qw72Blora",
  "messages": [
    {
      "role": "system",
      "content": "你是一个人工智能助手."
    },
    {
      "role": "user",
      "content": "你会做计算题嘛，帮我计算100*99"
    }
  ],
  "stream": true,
  "tool_choice": "calculate"
}

**Comment by as100863** [comment]
{
"model": "custom-glm4-chat",
"messages": [
{
"role": "system",
"content": "你是一个人工智能助手."
},
{
"role": "user",
"content": "朋友借钱不还，怎么办？"
}
],
"stream": true,
"tool_choice": "calculate"
}
有些问题，回答的答案是英文，是什么问题？

data: {"id": "chatde768a5a-957f-468c-95f6-e918e284f41e", "object": "chat.completion.chunk", "model": "custom-glm4-chat", "created": 1722244732, "status": 3, "message_type": 1, "message_id": null, "is_ref": false, "choices": [{"delta": {"content": "Thought: The user is asking for advice on how to handle a friend who has not returned a borrowed amount. This is a personal and legal matter, and the response should be general and not specific to any legal jurisdiction.\n\nAction:\n```json\n{\n  \"action\": \"Final Answer\",\n  \"action_input\": \"It is advisable to communicate with your friend and remind them of the borrowed amount. If they are unwilling to return the money, you may consider seeking legal advice or involving a mediator to resolve the issue.\"\n}\n```", "tool_calls": []}, "role": "assistant"}]}

**Comment by njzfw1024** [comment]
> { "model": "custom-glm4-chat", "messages": [ { "role": "system", "content": "你是一个人工智能助手." }, { "role": "user", "content": "朋友借钱不还，怎么办？" } ], "stream": true, "tool_choice": "calculate" } 有些问题，回答的答案是英文，是什么问题？
> 
> data: {"id": "chatde768a5a-957f-468c-95f6-e918e284f41e", "object": "chat.completion.chunk", "model": "custom-glm4-chat", "created": 1722244732, "status": 3, "message_type": 1, "message_id": null, "is_ref": false, "choices": [{"delta": {"content": "Thought: The user is asking for advice on how to handle a friend who has not returned a borrowed amount. This is a personal and legal matter, and the response should be general and not specific to any legal jurisdiction.\n\nAction:\n`json\n{\n \"action\": \"Final Answer\",\n \"action_input\": \"It is advisable to communicate with your friend and remind them of the borrowed amount. If they are unwilling to return the money, you may consider seeking legal advice or involving a mediator to resolve the issue.\"\n}\n`", "tool_calls": []}, "role": "assistant"}]}

试试修改提示词，让他用中文回答

**Comment by as100863** [comment]
部分回答英文，日志报错如下：

2024-07-30 14:52:51,552 httpx        239 INFO     HTTP Request: POST http://127.0.0.1:9997/v1/chat/completions "HTTP/1.1 200 OK"
2024-07-30 14:53:01.826 | ERROR    | chatchat.server.utils:wrap_done:46 - TypeError: Caught exception: argument of type 'NoneType' is not iterable
Thought: I need to find a tool to help answer this question
Action:
```{"action": "translate", "action_input": "朋友借钱不还，怎么办？", "source_language": "zh", "target_language": "en"}```

**Comment by sy960923** [comment]
选中多个工具怎么传？

**Comment by njzfw1024** [comment]
> { "model": "custom-glm4-chat", "messages": [ { "role": "system", "content": "你是一个人工智能助手." }, { "role": "user", "content": "朋友借钱不还，怎么办？" } ], "stream": true, "tool_choice": "calculate" } 有些问题，回答的答案是英文，是什么问题？
> 
> data: {"id": "chatde768a5a-957f-468c-95f6-e918e284f41e", "object": "chat.completion.chunk", "model": "custom-glm4-chat", "created": 1722244732, "status": 3, "message_type": 1, "message_id": null, "is_ref": false, "choices": [{"delta": {"content": "Thought: The user is asking for advice on how to handle a friend who has not returned a borrowed amount. This is a personal and legal matter, and the response should be general and not specific to any legal jurisdiction.\n\nAction:\n`json\n{\n \"action\": \"Final Answer\",\n \"action_input\": \"It is advisable to communicate with your friend and remind them of the borrowed amount. If they are unwilling to return the money, you may consider seeking legal advice or involving a mediator to resolve the issue.\"\n}\n`", "tool_calls": []}, "role": "assistant"}]}

tools 参数里面选择多个，{"tools": ["a", "b"]}最终会调用一个合适的
