### ISSUE TITLE
[BUG！！！]Chatchat API和Open API无法打开，但Webui可以运行

### ISSUE THREAD

**Issue by haohao0725** [chatchat-space/Langchain-Chatchat#4614]
**问题描述 / Problem Description**

部署langchain0.2.10+ChatGLM2-6B，启动后，点击 Chatchat WEBUI Server: http://0.0.0.0:8501 可以正常使用。
但是Chatchat API和Open API无法打开。并报错：
INFO:     10.224.165.7:0 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     10.224.165.7:0 - "GET /docs HTTP/1.1" 200 OK
2024-07-26 10:56:16 | INFO | stdout | INFO:     10.224.171.175:0 - "GET /v1 HTTP/1.1" 404 Not Found
![image](https://github.com/user-attachments/assets/69aa780a-c35e-4194-92b4-cb21de8b3d3f)
显示空白

**环境信息 / Environment Information**

root@dsw-416753-7c45f9f5c4-zfcnr:/mnt/workspace/Langchain-Chatchat-0.2.10# python startup.py -a
==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/mnt/workspace/chatglm2-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： text2vec @ cuda
==============================Langchain-Chatchat Configuration==============================

2024-07-26 10:55:40,043 - startup.py[line:655] - INFO: 正在启动服务：
2024-07-26 10:55:40,044 - startup.py[line:656] - INFO: 如需查看 llm_api 日志，请前往 /mnt/workspace/Langchain-Chatchat-0.2.10/logs
/opt/conda/lib/python3.10/site-packages/langchain_core/_api/deprecation.py:117: LangChainDeprecationWarning: 模型启动功能将于 Langchain-Chatchat 0.3.x重写,支持更多模式和加速启动，0.2.x中相关功能将废弃
  warn_deprecated(
2024-07-26 10:55:45 | ERROR | stderr | INFO:     Started server process [4240]
2024-07-26 10:55:45 | ERROR | stderr | INFO:     Waiting for application startup.
2024-07-26 10:55:45 | ERROR | stderr | INFO:     Application startup complete.
2024-07-26 10:55:45 | ERROR | stderr | INFO:     Uvicorn running on http://0.0.0.0:20000 (Press CTRL+C to quit)
2024-07-26 10:55:45 | INFO | model_worker | Register to controller
2024-07-26 10:55:45 | INFO | model_worker | Loading the model ['chatglm2-6b'] on worker daf6d5ee ...
Loading checkpoint shards:   0%|                                                                                                  | 0/7 [00:00<?, ?it/s]
Loading checkpoint shards:  14%|████████████▊                                                                             | 1/7 [00:01<00:07,  1.27s/it]
Loading checkpoint shards:  29%|█████████████████████████▋                                                                | 2/7 [00:02<00:06,  1.27s/it]
Loading checkpoint shards:  43%|██████████████████████████████████████▌                                                   | 3/7 [00:03<00:05,  1.35s/it]
Loading checkpoint shards:  57%|███████████████████████████████████████████████████▍                                      | 4/7 [00:05<00:03,  1.30s/it]
Loading checkpoint shards:  71%|████████████████████████████████████████████████████████████████▎                         | 5/7 [00:06<00:02,  1.29s/it]
Loading checkpoint shards:  86%|█████████████████████████████████████████████████████████████████████████████▏            | 6/7 [00:07<00:01,  1.27s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.10s/it]
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:08<00:00,  1.21s/it]
2024-07-26 10:55:54 | ERROR | stderr | 
2024-07-26 10:55:59 | INFO | model_worker | Register to controller
INFO:     Started server process [4313]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:7861 (Press CTRL+C to quit)

==============================Langchain-Chatchat Configuration==============================
操作系统：Linux-4.19.24-7.34.cbp.al7.x86_64-x86_64-with-glibc2.35.
python版本：3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
项目版本：v0.2.10
langchain版本：0.0.354. fastchat版本：0.2.35

当前使用的分词器：ChineseRecursiveTextSplitter
当前启动的LLM模型：['chatglm2-6b', 'zhipu-api', 'openai-api'] @ cuda
{'device': 'cuda',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_path': '/mnt/workspace/chatglm2-6b',
 'model_path_exists': True,
 'port': 20002}
{'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'online_api': True,
 'port': 21001,
 'provider': 'ChatGLMWorker',
 'version': 'glm-4',
 'worker_class': <class 'server.model_workers.zhipu.ChatGLMWorker'>}
{'api_base_url': 'https://api.openai.com/v1',
 'api_key': '',
 'device': 'auto',
 'host': '0.0.0.0',
 'infer_turbo': False,
 'model_name': 'gpt-4',
 'online_api': True,
 'openai_proxy': '',
 'port': 20002}
当前Embbedings模型： text2vec @ cuda

服务端运行信息：
    OpenAI API Server: http://127.0.0.1:20000/v1
    Chatchat  API  Server: http://127.0.0.1:7861
    Chatchat WEBUI Server: http://0.0.0.0:8501
==============================Langchain-Chatchat Configuration==============================

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to False.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:8501

INFO:     10.224.165.7:0 - "GET / HTTP/1.1" 307 Temporary Redirect
INFO:     10.224.165.7:0 - "GET /docs HTTP/1.1" 200 OK

  A new version of Streamlit is available.

  See what's new at https://discuss.streamlit.io/c/announcements

  Enter the following command to upgrade:
  $ pip install streamlit --upgrade

2024-07-26 10:56:16 | INFO | stdout | INFO:     10.224.171.175:0 - "GET /v1 HTTP/1.1" 404 Not Found

**附加信息 / Additional Information**

根据已有问题信息，已经尝试关闭VPN，开启跨域和添加windows防火墙端口等方案，但都没法解决。求助，救救孩子！！

**Comment by andyzhou1982** [comment]
http://127.0.0.1:7861/docs试试

**Comment by haohao0725** [comment]
> [http://127.0.0.1:7861/docs试试](http://127.0.0.1:7861/docs%E8%AF%95%E8%AF%95)

谢谢建议@andyzhou1982，我尝试了您说的方法，清除了缓存后，可以打开Chatchat  API  Server: http://127.0.0.1:7861了
但是，OpenAI API Server: http://127.0.0.1:20000/v1 仍无法打开
仍报错：2024-07-26 11:32:02 | INFO | stdout | INFO:     10.224.171.175:0 - "GET /v1 HTTP/1.1" 404 Not Found
请问有没有建议方法尝试？

**Comment by andyzhou1982** [comment]
http://127.0.0.1:20000/v1肯定打不开啊，那是仿openAI的接口，是用在代码里面的

**Comment by haohao0725** [comment]
> [http://127.0.0.1:20000/v1肯定打不开啊，那是仿openAI的接口，是用在代码里面的](http://127.0.0.1:20000/v1%E8%82%AF%E5%AE%9A%E6%89%93%E4%B8%8D%E5%BC%80%E5%95%8A%EF%BC%8C%E9%82%A3%E6%98%AF%E4%BB%BFopenAI%E7%9A%84%E6%8E%A5%E5%8F%A3%EF%BC%8C%E6%98%AF%E7%94%A8%E5%9C%A8%E4%BB%A3%E7%A0%81%E9%87%8C%E9%9D%A2%E7%9A%84)

原来如此，谢谢您！@andyzhou1982

**Comment by yao512954855** [comment]
我跟你碰到差不多的问题，然后找到了这个issue"关于swagger空白问题，重新下载swagger-ui-bundle.js即可 #3167"，然后更新了swagger的两个文件就可以访问了
