### ISSUE TITLE
可以出一个自定义Agent的详细教程吗？

### ISSUE THREAD

**Issue by oucyangshuai** [chatchat-space/Langchain-Chatchat#4623]
我最近在用0.3.2版本，源码部署的，想自己做几个Agent。看以前老版本的wiki，学习怎么自定义Agent，感觉很混乱。请问能不能出个源码配置自定义Agent的教程，甚至新增是“傻瓜式自定义Agent”的功能？

微调和知识库的能力确实有限，所以想通过自定义Agent的方法增强LLM能力。谢谢~

**Comment by azhe1234** [comment]
> 我最近在用0.3.2版本，源码部署的，想自己做几个Agent。看以前老版本的wiki，学习怎么自定义Agent，感觉很混乱。请问能不能出个源码配置自定义Agent的教程，甚至新增是“傻瓜式自定义Agent”的功能？
> 
> 微调和知识库的能力确实有限，所以想通过自定义Agent的方法增强LLM能力。谢谢~

同求，请问你现在研究的如何啦，我今天刚部署成功，准备自己定一个Agent，提示词都不知道在哪里设置

**Comment by liunux4odoo** [comment]
docs/contributing 里面已经添加。
