### ISSUE TITLE
请问0.3.1版本要对代码修改要怎么改？

### ISSUE THREAD

**Issue by tankGe** [chatchat-space/Langchain-Chatchat#4639]
**问题描述 / Problem Description**
我在0.2.10中改了一些代码，现在我在\libs\chatchat-server\chatchat\server中修改了对应的代码，但是重新启动程序后好像没有生效，请问我要怎么操作？

**Comment by tankGe** [comment]
我在kb_chat.py将top_k参数改成了20，但是重启之后问答还是只返回了5条，有没有大大指点一下？
`if mode == "local_kb":
                kb = KBServiceFactory.get_service_by_name(kb_name)
                ok, msg = kb.check_embed_model()
                if not ok:
                    raise ValueError(msg)
                docs = await run_in_threadpool(search_docs,
                                                query=query,
                                                knowledge_base_name=kb_name,
                                                top_k=20,
                                                score_threshold=score_threshold,
                                                file_name="",
                                                metadata={})
                source_documents = format_reference(kb_name, docs, api_address(is_public=True))`

**Comment by imClumsyPanda** [comment]
参考源代码安装方式，使用python执行对应脚本命令启动项目可以使代码即时生效。

请注意，需要将项目中libs/chatchat-server作为项目中的根目录。

**Comment by tankGe** [comment]
> 参考源代码安装方式，使用python执行对应脚本命令启动项目可以使代码即时生效。
> 
> 请注意，需要将项目中libs/chatchat-server作为项目中的根目录。

这种方式是指本地开发环境调试运行，我现在是在服务器上部署了0.3.1，然后想在本地修改后更新到服务器，那我要怎么更新服务器文件？
