### ISSUE TITLE
API版本能否提供WEBSOCKET的流式接口

### ISSUE THREAD

**Issue by wangts108** [chatchat-space/Langchain-Chatchat#464]
webui 版本中，采用了WS的流式输出，整体感知反应很快
api版本中chat接口是get请求的，要等到内容全部响应完成才输出，等待时间过长

**Comment by imClumsyPanda** [comment]
api.py中是有websocket接口的

**Comment by Ayo616** [comment]
希望VUE前端也能实现流式接口

**Comment by aappaappoo** [comment]
api版本中chat接口是否可以返回回复

> webui 版本中，采用了WS的流式输出，整体感知反应很快 api版本中chat接口是get请求的，要等到内容全部响应完成才输出，等待时间过长

**Comment by evanweiguohua** [comment]
补充一下：测试用的url为：ws://3e78s46749.imdo.co:18101/stream-chat/motor_t700s，motor_t700s是我用接口上传的一个小的知识库

**Comment by shaolongcai** [comment]
> 补充一下：测试用的url为：ws://3e78s46749.imdo.co:18101/stream-chat/motor_t700s，motor_t700s是我用接口上传的一个小的知识库

我看了一下接口应该是：/local_doc_qa/stream-chat/{knowledge_base_id}。
你打开postman新开一个ws的请求，然后链接填 {公网ip：端口}/local_doc_qa/stream-chat/test1 ，message选择JSON
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/29476298/c2049b02-79a5-4f81-b85f-caff9f818d2d)

**Comment by ucas010** [comment]
have  a similar question about the api request,
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/465

**Comment by tomiezhang** [comment]
+1 报错 返回Status Code: 400 Bad Request

**Comment by tomiezhang** [comment]
搞定了，postman里要在url前面显式的加一下wss:// url:port//local_doc_qa/stream-chat/{knowledge_base_id} 要不默认是http去请求。。。 脑残

**Comment by cristianohello** [comment]
@tomiezhang @imClumsyPanda @Ayo616 @ucas010 

问一下，stream-chat函数能使用curl1调用吗？
我下面这样调用，为什么报错：

curl -X 'POST' \
  'http://127.0.0.1:8000/local_doc_qa/stream-chat/baoxian_FAISS_20230602_172352' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "question": "卡塔尔世界杯冠军是谁",
  "history": [],
  "knowledge_base_id": "baoxian_FAISS_20230602_172352",
}'

**Comment by wufxgtihub123** [comment]
> 

stream-chat流式调用应该用的是websocket吧？ 所以应该是ws://ip:port/local_doc_qa/stream-chat/{knowledge_base_id}, 我认为应该是这样的，我还没测

**Comment by ucas010** [comment]
测试结果不对：
ws://172.168.705.72:861/local_doc_qa/stream-chat/100270
{
"question": "向量数据库是什么？",
"history": [],
"knowledge_base_id": "100270"
}
返回：
{
    "detail": "Not Found"
}

**Comment by imClumsyPanda** [comment]
url里去掉knowledge_id之后是可行的吗

Lychee X ***@***.***>于2023年6月9日 周五11:41写道：

**Comment by ucas010** [comment]
No
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/3d436d76-4e82-4d3d-87d8-d46859b00d07)
@imClumsyPanda

**Comment by wufxgtihub123** [comment]
前面的post选项换掉，建议使用postman进行测试，apifox好像暂时不支持websocket测试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lychee X ***@***.***&gt;
发送时间: 2023年6月9日 11:41
收件人: imClumsyPanda/langchain-ChatGLM ***@***.***&gt;
抄送: Flylyy ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [imClumsyPanda/langchain-ChatGLM] API版本能否提供WEBSOCKET的流式接口 (Issue #464)





 
测试结果不对：
 ws://172.168.705.72:861/local_doc_qa/stream-chat/100270
 {
 "question": "向量数据库是什么？",
 "history": [],
 "knowledge_base_id": "100270"
 }
 返回：
 {
 "detail": "Not Found"
 }

**Comment by ucas010** [comment]
post换成啥？我这就是postman

**Comment by wufxgtihub123** [comment]
> post换成啥？我这就是postman

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/74227869/8f6ab8bb-eaf3-4965-b59c-56f2ff19885c)
这样试一下

**Comment by ucas010** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/641c2ed1-f448-48f1-afdc-6897b8327dd9)

**Comment by wufxgtihub123** [comment]
> ![image](https://user-images.githubusercontent.com/50656998/244603220-641c2ed1-f448-48f1-afdc-6897b8327dd9.png)

我的url后面跟了knowledge-base-id是可以调通的，你加上knowledge-base-id试一下？

**Comment by ucas010** [comment]
返回数据呢？
connected，，，
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/c71e7320-da64-4800-b18f-46a2f8b3d083)

**Comment by wufxgtihub123** [comment]
> 返回数据呢？ connected，，， ![image](https://user-images.githubusercontent.com/50656998/244604800-c71e7320-da64-4800-b18f-46a2f8b3d083.png)

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/74227869/1a6c0084-cda5-49b7-a4fa-6c37dfbbedb9)
connect后有没有点击发送？

**Comment by ucas010** [comment]
点击send后断开链接了，，，
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/a7222768-9d17-41e2-8a3d-d0691b1ddc37)

**Comment by wufxgtihub123** [comment]
> 点击send后断开链接了，，， ![image](https://user-images.githubusercontent.com/50656998/244605649-a7222768-9d17-41e2-8a3d-d0691b1ddc37.png)

看下后端服务有无报错信息？

**Comment by ucas010** [comment]
OK了，感谢
@wufxgtihub123
@wufxgtihub123

**Comment by lqhLoveSmy** [comment]
为什么有时候会无限输出，一直在重复返回结果，这个接口stream_chat

**Comment by brealisty** [comment]
> OK了，感谢 @wufxgtihub123 @wufxgtihub123

请问下这个base-id是从哪里得到的？我的只有个base-name，另外ip地址设置的位置是那些地方？，我设置server_config.p里面的DEFAULT_BIND_HOST为0.0.0.0之后就报错了

**Comment by duanfakai** [comment]
我怎么搜索不到WEBSOCKET的接口，stream_chat还有吗，哪个分支
