### ISSUE TITLE
知识库匹配向量数量不一致

### ISSUE THREAD

**Issue by guhao17** [chatchat-space/Langchain-Chatchat#4646]
![image](https://github.com/user-attachments/assets/f62d0137-cd3c-4be2-95f5-4049333b7322)
我在yaml文件中设置的知识匹配数量是15条，实际网页上只有5条，该如何解决
![395ad927fb67e974fcc577faaaba3dc](https://github.com/user-attachments/assets/06ac31b9-d510-4e6c-af96-c0b188ebf6ea)

**Comment by guhao17** [comment]
当我要求列出10条时，它显示无法回答

**Comment by liunux4odoo** [comment]
duplicate of #4493

**Comment by guhao17** [comment]
我用的就是最新的版本啊

**Comment by guhao17** [comment]
页面的数字改了，但是真实匹配的还是只有5条

**Comment by guhao17** [comment]
![image](https://github.com/user-attachments/assets/06c87c6a-604e-48de-88bd-e2bc4f0aef79)

**Comment by INSKYBE** [comment]
我也是，还是没解决呀
