### ISSUE TITLE
连接数据库后，生成的sql有其他的字符串

### ISSUE THREAD

**Issue by urgack** [chatchat-space/Langchain-Chatchat#4653]
![image](https://github.com/user-attachments/assets/ec225006-a278-4c4a-905e-684d2a637c7b)
用LangChain-Chatchat连接mysql数据库时，生成sql数据会多出字符串
SQLQuery:
` ``sql
SELECT COUNT(*) AS total_articles FROM t_article;
```INFO
，会多出```sql和```INFO


**环境信息 **
- Langchain-Chatchat 版本 / commit 号：0.3.1
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi 安装 
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：glm4-chat 
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-m3
- 操作系统及版本 / Operating system and version: Ubuntu 2204
- Python 版本 / Python version: 3.10
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU

**Comment by danealiu** [comment]
我也遇到同样问题了，求大佬解疑

**Comment by GoGo-UpUp** [comment]
我也碰到了，这个是langchain框架内部提取大模型回答中sql语句的问题，我修改了langchain中的源码

**Comment by GoGo-UpUp** [comment]
我也碰到了，这个是langchain框架内部提取大模型回答中sql语句的问题，我修改了langchain中的源码
angchain_experimental-sql-base.py中SQLDatabaseChain类中的_call函数中对大模型预测sql语句的提取代码
![image](https://github.com/user-attachments/assets/9da6c851-5585-453f-8e26-3f031b9ea302)
我增加了这两行代码

**Comment by urgack** [comment]
> 我也碰到了，这个是langchain框架内部提取大模型回答中sql语句的问题，我修改了langchain中的源码 angchain_experimental-sql-base.py中SQLDatabaseChain类中的_call函数中对大模型预测sql语句的提取代码 ![image](https://private-user-images.githubusercontent.com/177207792/354169929-9da6c851-5585-453f-8e26-3f031b9ea302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mjc5NzMsIm5iZiI6MTcyMjkyNzY3MywicGF0aCI6Ii8xNzcyMDc3OTIvMzU0MTY5OTI5LTlkYTZjODUxLTU1ODUtNDUzZi04ZTI2LTNmMDMxYjllYTMwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQwNzAxMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjMzZjMzZmUxZTlhMzVmOWNkNGFjNjQyNTQyMGZkODgzODgzMjlhNzIzNzY0ZTkyOWZkZDBlMWI4MWQxOTVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OBXAsq4XjZV3FoIWdT1lxTOxW5ceUHHaVJ12zFXFwdw) 我增加了这两行代码

感谢大佬，已解决

**Comment by panda4444ssdfs** [comment]
miniconda3/envs/chat_0.3.1/lib/python3.11/site-packages/langchain_experimental/sql/base.py
