### ISSUE TITLE
0.3.1版本 text pdf html文件添加到向量数据库时when post /knowledge_base/update_docs: timed out

### ISSUE THREAD

**Issue by jiusi9** [chatchat-space/Langchain-Chatchat#4654]
**问题描述 / Problem Description**
UnstructuredFileLoader used for /opt/chatchat_data/knowledge_base/samples/content/test_files/test.txt

对text pdf html文件添加到向量数据库时, 卡在
when post /knowledge_base/update_docs: timed out

**环境信息 / Environment Information**
python 3.10
`
langchain                   0.1.17
langchain-chatchat          0.3.1.1
langchain-community         0.0.36
langchain-core              0.1.52
langchain-experimental      0.0.58
langchain-openai            0.0.6
langchain-text-splitters    0.0.2
langchainhub                0.1.14
`

**附加信息 / Additional Information**

2024-07-31 12:48:23.354 \| INFO \| chatchat.server.knowledge_base.utils:file2docs:336 - UnstructuredFileLoader used for /opt/chatchat_data/knowledge_base/samples/content/test_files/test.txt
--
Wed, Jul 31 2024 12:53:23 pm | 2024-07-31 12:53:23.353 \| ERROR \| chatchat.webui_pages.utils:post:87 - ReadTimeout: error when post /knowledge_base/update_docs: timed out
Wed, Jul 31 2024 12:53:23 pm | Traceback (most recent call last):
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
Wed, Jul 31 2024 12:53:23 pm | yield
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
Wed, Jul 31 2024 12:53:23 pm | resp = self._pool.handle_request(req)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ <Request [b'POST']>
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <function ConnectionPool.handle_request at 0x7fc23fcca200>
Wed, Jul 31 2024 12:53:23 pm | │ └ <ConnectionPool [Requests: 0 active, 0 queued \| Connections: 0 active, 0 idle]>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.HTTPTransport object at 0x7fc231087790>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
Wed, Jul 31 2024 12:53:23 pm | raise exc from None
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
Wed, Jul 31 2024 12:53:23 pm | response = connection.handle_request(
Wed, Jul 31 2024 12:53:23 pm | │ └ <function HTTPConnection.handle_request at 0x7fc23fcc95a0>
Wed, Jul 31 2024 12:53:23 pm | └ <HTTPConnection ['http://127.0.0.1:6565', HTTP/1.1, CLOSED, Request Count: 1]>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
Wed, Jul 31 2024 12:53:23 pm | return self._connection.handle_request(request)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ <Request [b'POST']>
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <function HTTP11Connection.handle_request at 0x7fc23fcab370>
Wed, Jul 31 2024 12:53:23 pm | │ └ <HTTP11Connection ['http://127.0.0.1:6565', CLOSED, Request Count: 1]>
Wed, Jul 31 2024 12:53:23 pm | └ <HTTPConnection ['http://127.0.0.1:6565', HTTP/1.1, CLOSED, Request Count: 1]>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
Wed, Jul 31 2024 12:53:23 pm | raise exc
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
Wed, Jul 31 2024 12:53:23 pm | ) = self._receive_response_headers(**kwargs)
Wed, Jul 31 2024 12:53:23 pm | │ │ └ {'request': <Request [b'POST']>}
Wed, Jul 31 2024 12:53:23 pm | │ └ <function HTTP11Connection._receive_response_headers at 0x7fc23fcc8820>
Wed, Jul 31 2024 12:53:23 pm | └ <HTTP11Connection ['http://127.0.0.1:6565', CLOSED, Request Count: 1]>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
Wed, Jul 31 2024 12:53:23 pm | event = self._receive_event(timeout=timeout)
Wed, Jul 31 2024 12:53:23 pm | │ │ └ 300.0
Wed, Jul 31 2024 12:53:23 pm | │ └ <function HTTP11Connection._receive_event at 0x7fc23fcc8940>
Wed, Jul 31 2024 12:53:23 pm | └ <HTTP11Connection ['http://127.0.0.1:6565', CLOSED, Request Count: 1]>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
Wed, Jul 31 2024 12:53:23 pm | data = self._network_stream.read(
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <function SyncStream.read at 0x7fc23fc849d0>
Wed, Jul 31 2024 12:53:23 pm | │ └ <httpcore._backends.sync.SyncStream object at 0x7fc2310858d0>
Wed, Jul 31 2024 12:53:23 pm | └ <HTTP11Connection ['http://127.0.0.1:6565', CLOSED, Request Count: 1]>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
Wed, Jul 31 2024 12:53:23 pm | with map_exceptions(exc_map):
Wed, Jul 31 2024 12:53:23 pm | │ └ {<class 'TimeoutError'>: <class 'httpcore.ReadTimeout'>, <class 'OSError'>: <class 'httpcore.ReadError'>}
Wed, Jul 31 2024 12:53:23 pm | └ <function map_exceptions at 0x7fc23fe47880>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
Wed, Jul 31 2024 12:53:23 pm | self.gen.throw(typ, value, traceback)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ │ └ <traceback object at 0x7fc231e72dc0>
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ └ TimeoutError('timed out')
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ <class 'TimeoutError'>
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <method 'throw' of 'generator' objects>
Wed, Jul 31 2024 12:53:23 pm | │ └ <generator object map_exceptions at 0x7fc231b6a9d0>
Wed, Jul 31 2024 12:53:23 pm | └ <contextlib._GeneratorContextManager object at 0x7fc231ed3bb0>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
Wed, Jul 31 2024 12:53:23 pm | raise to_exc(exc) from exc
Wed, Jul 31 2024 12:53:23 pm | └ <class 'httpcore.ReadTimeout'>
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm | httpcore.ReadTimeout: timed out
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm | The above exception was the direct cause of the following exception:
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm | Traceback (most recent call last):
Wed, Jul 31 2024 12:53:23 pm |  
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/threading.py", line 973, in _bootstrap
Wed, Jul 31 2024 12:53:23 pm | self._bootstrap_inner()
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Thread._bootstrap_inner at 0x7fc30cfd8d30>
Wed, Jul 31 2024 12:53:23 pm | └ <Thread(ScriptRunner.scriptThread, started 140472033752832)>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Wed, Jul 31 2024 12:53:23 pm | self.run()
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Thread.run at 0x7fc30cfd8a60>
Wed, Jul 31 2024 12:53:23 pm | └ <Thread(ScriptRunner.scriptThread, started 140472033752832)>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/threading.py", line 953, in run
Wed, Jul 31 2024 12:53:23 pm | self._target(*self._args, **self._kwargs)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ │ └ {}
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ └ <Thread(ScriptRunner.scriptThread, started 140472033752832)>
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ ()
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <Thread(ScriptRunner.scriptThread, started 140472033752832)>
Wed, Jul 31 2024 12:53:23 pm | │ └ <bound method ScriptRunner._run_script_thread of ScriptRunner(_session_id='758144c4-f9d2-48c6-9c03-530f99fec3a1', _main_scrip...
Wed, Jul 31 2024 12:53:23 pm | └ <Thread(ScriptRunner.scriptThread, started 140472033752832)>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 307, in _run_script_thread
Wed, Jul 31 2024 12:53:23 pm | self._run_script(request.rerun_data)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ <property object at 0x7fc23e9d11c0>
Wed, Jul 31 2024 12:53:23 pm | │ │ └ ScriptRequest(type=<ScriptRequestType.RERUN: 'RERUN'>, _rerun_data=RerunData(widget_states=widgets {
Wed, Jul 31 2024 12:53:23 pm | │ │ id: "$$WIDGET_ID-4be88...
Wed, Jul 31 2024 12:53:23 pm | │ └ <function ScriptRunner._run_script at 0x7fc23e9e2e60>
Wed, Jul 31 2024 12:53:23 pm | └ ScriptRunner(_session_id='758144c4-f9d2-48c6-9c03-530f99fec3a1', _main_script_path='/usr/local/lib/python3.10/site-packages/c...
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
Wed, Jul 31 2024 12:53:23 pm | exec(code, module.__dict__)
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <member '__dict__' of 'module' objects>
Wed, Jul 31 2024 12:53:23 pm | │ └ <module '__main__' from '/usr/local/lib/python3.10/site-packages/chatchat/webui.py'>
Wed, Jul 31 2024 12:53:23 pm | └ <code object <module> at 0x7fc23e4f2ef0, file "/usr/local/lib/python3.10/site-packages/chatchat/webui.py", line 1>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/chatchat/webui.py", line 69, in <module>
Wed, Jul 31 2024 12:53:23 pm | knowledge_base_page(api=api, is_lite=is_lite)
Wed, Jul 31 2024 12:53:23 pm | │ │ └ False
Wed, Jul 31 2024 12:53:23 pm | │ └ <chatchat.webui_pages.utils.ApiRequest object at 0x7fc231baa800>
Wed, Jul 31 2024 12:53:23 pm | └ <function knowledge_base_page at 0x7fc232108d30>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/chatchat/webui_pages/knowledge_base/knowledge_base.py", line 299, in knowledge_base_page
Wed, Jul 31 2024 12:53:23 pm | api.update_kb_docs(
Wed, Jul 31 2024 12:53:23 pm | │ └ <function ApiRequest.update_kb_docs at 0x7fc23d5aaa70>
Wed, Jul 31 2024 12:53:23 pm | └ <chatchat.webui_pages.utils.ApiRequest object at 0x7fc231baa800>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/chatchat/webui_pages/utils.py", line 579, in update_kb_docs
Wed, Jul 31 2024 12:53:23 pm | response = self.post(
Wed, Jul 31 2024 12:53:23 pm | │ └ <function ApiRequest.post at 0x7fc23d5aa050>
Wed, Jul 31 2024 12:53:23 pm | └ <chatchat.webui_pages.utils.ApiRequest object at 0x7fc231baa800>
Wed, Jul 31 2024 12:53:23 pm | > File "/usr/local/lib/python3.10/site-packages/chatchat/webui_pages/utils.py", line 84, in post
Wed, Jul 31 2024 12:53:23 pm | return self.client.post(url, data=data, json=json, **kwargs)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ │ └ {}
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ └ {'knowledge_base_name': 'samples', 'file_names': ['test_files/test.txt'], 'override_custom_docs': False, 'chunk_size': 750, '...
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ None
Wed, Jul 31 2024 12:53:23 pm | │ │ └ '/knowledge_base/update_docs'
Wed, Jul 31 2024 12:53:23 pm | │ └ <property object at 0x7fc23d5a5ee0>
Wed, Jul 31 2024 12:53:23 pm | └ <chatchat.webui_pages.utils.ApiRequest object at 0x7fc231baa800>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1145, in post
Wed, Jul 31 2024 12:53:23 pm | return self.request(
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Client.request at 0x7fc23fc06a70>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.Client object at 0x7fc23f3e5780>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
Wed, Jul 31 2024 12:53:23 pm | return self.send(request, auth=auth, follow_redirects=follow_redirects)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ └ <httpx._client.UseClientDefault object at 0x7fc23fdbe590>
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ <httpx._client.UseClientDefault object at 0x7fc23fdbe590>
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <Request('POST', 'http://127.0.0.1:6565/knowledge_base/update_docs')>
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Client.send at 0x7fc23fc06c20>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.Client object at 0x7fc23f3e5780>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
Wed, Jul 31 2024 12:53:23 pm | response = self._send_handling_auth(
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Client._send_handling_auth at 0x7fc23fc06cb0>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.Client object at 0x7fc23f3e5780>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
Wed, Jul 31 2024 12:53:23 pm | response = self._send_handling_redirects(
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Client._send_handling_redirects at 0x7fc23fc06d40>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.Client object at 0x7fc23f3e5780>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
Wed, Jul 31 2024 12:53:23 pm | response = self._send_single_request(request)
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <Request('POST', 'http://127.0.0.1:6565/knowledge_base/update_docs')>
Wed, Jul 31 2024 12:53:23 pm | │ └ <function Client._send_single_request at 0x7fc23fc06dd0>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.Client object at 0x7fc23f3e5780>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
Wed, Jul 31 2024 12:53:23 pm | response = transport.handle_request(request)
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <Request('POST', 'http://127.0.0.1:6565/knowledge_base/update_docs')>
Wed, Jul 31 2024 12:53:23 pm | │ └ <function HTTPTransport.handle_request at 0x7fc23fc04a60>
Wed, Jul 31 2024 12:53:23 pm | └ <httpx.HTTPTransport object at 0x7fc231087790>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
Wed, Jul 31 2024 12:53:23 pm | with map_httpcore_exceptions():
Wed, Jul 31 2024 12:53:23 pm | └ <function map_httpcore_exceptions at 0x7fc23fe45900>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
Wed, Jul 31 2024 12:53:23 pm | self.gen.throw(typ, value, traceback)
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ │ └ <traceback object at 0x7fc23103d580>
Wed, Jul 31 2024 12:53:23 pm | │ │ │ │ └ ReadTimeout(TimeoutError('timed out'))
Wed, Jul 31 2024 12:53:23 pm | │ │ │ └ <class 'httpcore.ReadTimeout'>
Wed, Jul 31 2024 12:53:23 pm | │ │ └ <method 'throw' of 'generator' objects>
Wed, Jul 31 2024 12:53:23 pm | │ └ <generator object map_httpcore_exceptions at 0x7fc23070e340>
Wed, Jul 31 2024 12:53:23 pm | └ <contextlib._GeneratorContextManager object at 0x7fc2310862f0>
Wed, Jul 31 2024 12:53:23 pm | File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
Wed, Jul 31 2024 12:53:23 pm | raise mapped_exc(message) from exc
Wed, Jul 31 2024 12:53:23 pm | │ └ 'timed out'
Wed, Jul 31 2024 12:53:23 pm | └ <class 'httpx.ReadTimeout'>

**Comment by jiusi9** [comment]
已解决. 

原因是, 当时的nlkt_data不知道是下载的哪个版本的，莫名其妙的不行。 
又重新下载放到/root目录下就正常了。
同时也测试了langchain-chatchat带的nlkt_data，放到/root目录也能正常使用。

**Comment by tdouguo** [comment]
nlkt_data 在那里了啊
