### ISSUE TITLE
VUE的pnmp i执行失败的修复-用npm i命令即可

### ISSUE THREAD

**Issue by Sowhat007** [chatchat-space/Langchain-Chatchat#466]
感谢作者！非常棒的应用，用的很开心。
有个小问题，VUE前端展示那里第二行命令要改为npm i，否则不能执行。

```
$ cd views 

$ npm i

$ npm run dev
```

**Comment by weigong1983** [comment]
> 感谢作者！非常棒的应用，用的很开心。 有个小问题，VUE前端展示那里第二行命令要改为npm i，否则不能执行。
> 
> ```
> $ cd views 
> 
> $ npm i
> 
> $ npm run dev
> ```

您是自己开发的VUE前端吗？还是本项目有VUE前端的分支版本
