### ISSUE TITLE
[BUG] 知识库RAG中对无关问题的处理

### ISSUE THREAD

**Issue by runningREAL** [chatchat-space/Langchain-Chatchat#4664]
使用版本0.3.1，llm：llama3.1-8b，embeddings：bge-large-zh-v1.5，

当使用知识库提问时，提问和知识库检索结果无关的内容，
比如输入一句“你好”，
如果是tools中的search_local_knowledgebase就会报错，
 | ERROR    | chatchat.server.utils:wrap_done:46 - ValueError: Caught exception: not enough values to unpack (expected 2, got 0)
测试中什么也不会返回，
![Snipaste_2024-08-01_15-22-54](https://github.com/user-attachments/assets/8030654e-5bb5-4381-8336-eb53639db7cd)

如果是用普通的知识库提问接口，就会返回“根据已知信息无法回答该问题”

不会像0.2版本时那样，如果是知识库无关问题，会自动返回prompt中rag.empty不使用知识库对话的结果，因为这是上个版本有的功能，所以不清楚这是bug，还是功能缺失

**Comment by eric4note** [comment]
This issue could be attributed to incorrect reading or loading of the original knowledge files when creating the knowledge base.
Errors look like "'ascii' codec can't decode byte 0xbf in position 11: ordinal not in range(128)"...
