### ISSUE TITLE
调用文生图功能时报错ValidationError: Caught exception: 1 validation error for text2imagesSchema prompt   str type expected (type=type_error.str)

### ISSUE THREAD

**Issue by GoGo-UpUp** [chatchat-space/Langchain-Chatchat#4665]
使用0.3.1版本文生图功能，模型调用的是xinference部署的glm-4-9b-chat使用文生图功能时会报错
![image](https://github.com/user-attachments/assets/4ba003f6-84a4-4b83-86c4-6d9a2efde66a)
查看日志发现报错内容
![image](https://github.com/user-attachments/assets/4506c54c-4b0c-4527-aea6-fd291c465235)
有大佬知道是哪里出了问题吗

**Comment by zhanghailong00** [comment]
这个问题解决了吗
