### ISSUE TITLE
在kb_chat.py中加入reranker，会在向量数据库查询过程中崩溃

### ISSUE THREAD

**Issue by zhanxiaokai** [chatchat-space/Langchain-Chatchat#4666]
**问题描述 / Problem Description**
在kb_chat.py中加入reranker，实际只引用了sentence_transformers里面的CrossEncoder
`from sentence_transformers import CrossEncoder`
就会在RAG查询中报错如下：

> 
> 2024-08-01 17:31:16,555 httpx        12943 INFO     HTTP Request: POST http://127.0.0.1:3000/v1/embeddings "HTTP/1.1 200 OK"
> 2024-08-01 17:31:16.564 Uncaught app exception
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 113, in __iter__
>     for part in self._httpcore_stream:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 367, in __iter__
>     raise exc from None
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 363, in __iter__
>     for part in self._stream:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 349, in __iter__
>     raise exc
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 341, in __iter__
>     for chunk in self._connection._receive_response_body(**kwargs):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 210, in _receive_response_body
>     event = self._receive_event(timeout=timeout)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 220, in _receive_event
>     with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/wenchang/Desktop/langchain/Langchain-Chatchat/libs/chatchat-server/chatchat/webui_pages/kb_chat.py", line 225, in kb_chat
>     for d in client.chat.completions.create(messages=messages, model=llm_model, stream=True, extra_body=extra_body):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 46, in __iter__
>     for item in self._iterator:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 58, in __stream__
>     for sse in iterator:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 50, in _iter_events
>     yield from self._decoder.iter_bytes(self.response.iter_bytes())
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 280, in iter_bytes
>     for chunk in self._iter_chunks(iterator):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/openai/_streaming.py", line 291, in _iter_chunks
>     for chunk in iterator:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_models.py", line 829, in iter_bytes
>     for raw_bytes in self.iter_raw():
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_models.py", line 883, in iter_raw
>     for raw_stream_bytes in self.stream:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_client.py", line 126, in __iter__
>     for chunk in self._stream:
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 112, in __iter__
>     with map_httpcore_exceptions():
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 158, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
>     exec(code, module.__dict__)
>   File "/Users/wenchang/Desktop/langchain/Langchain-Chatchat/libs/chatchat-server/chatchat/webui.py", line 71, in <module>
>     kb_chat(api=api)
>   File "/Users/wenchang/Desktop/langchain/Langchain-Chatchat/libs/chatchat-server/chatchat/webui_pages/kb_chat.py", line 236, in kb_chat
>     st.error(e.body)
>              ^^^^^^
> AttributeError: 'RemoteProtocolError' object has no attribute 'body'
> 
> 

**复现问题的步骤 / Steps to Reproduce**
1. 我在Mac电脑上源码安装了chatchat与one-api
2. 想打开reranker，自己写的单元测试或者直接将注释的reranker部分打开，都会出上边的错误

**预期的结果 / Expected Result**
可以使用reranker

**实际结果 / Actual Result**
发生错误

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：master分支
- 部署方式：源码部署
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference / Model serve method（Xinference / Ollama / OpenAI API, etc.): Xinference 
- 使用的 LLM 模型：one-api的GLM
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：GLM的embedding2
- 使用的向量库类型 ：faiss
- 操作系统及版本 / Operating system and version: MacOS
- Python 版本 / Python version: 3.8
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): CPU 
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**

**Comment by liunux4odoo** [comment]
reranker 已经重新添加，方便的话可以再测试一下。
