### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by tutan123** [chatchat-space/Langchain-Chatchat#4667]
**问题描述 / Problem Description**
当前我将txt文档上传到了知识库中，发现它将里面的"-" 换行了，而且删除了。 但是如果连续两个"-"， 他就只会删一个，然后换行。请问我该怎么办? 我不想让他转义换行或者删除任何的"-" , 因为他有可能是我的图片链接里面的东西，删除了，图片就打不开了。 @dosu-bot

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.2.final

**Comment by liunux4odoo** [comment]
0.2 版本已经停止维护
