### ISSUE TITLE
想要让LLM帮忙编写文档，编写过程需要借鉴知识库的相关内容，能不能指明一下开放方向

### ISSUE THREAD

**Issue by tankGe** [chatchat-space/Langchain-Chatchat#4670]
**问题描述 / Problem Description**
自定义或者使用框架Agent，告诉LLM模型编写过程中先从知识库检索相关内容，如果有则引用内容，没有则使用互联网搜索或者LLM自身知识进行完善。

**环境信息 / Environment Information**
- Langchain-Chatchat 版本号：0.3.1
- 部署方式：源码部署
- 使用的模型推理框架：Xinference
- 使用的 LLM 模型：Qwen2-7B-Instruct
- 使用的 Embedding 模型：bge-large-zh-v1.5
- 使用的向量库类型 ： faiss

**Comment by liunux4odoo** [comment]
与 issue 无关的内容请到微信群等地方讨论。

**Comment by Unexpectedlyc** [comment]
> 与 issue 无关的内容请到微信群等地方讨论。

微信群的二维码失效了
