### ISSUE TITLE
Langchain-chatchat能自己设计前端界面吗？或者能否提供接口给前端框架来设计自己界面？

### ISSUE THREAD

**Issue by soundmemories** [chatchat-space/Langchain-Chatchat#4672]
如题目所示，目前的前端界面不太适用于生产环境，能否提供接口，用来集成Langchain-chatchat功能的前端方案呢？

**Comment by xxy-cn** [comment]
源码部署的话 cli.py start -api 启动 API 服务，访问你的 API 地址有接口文档 [api.md](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/api.md)，pip 部署 chatchat start --api 启动 api 服务吧
