### ISSUE TITLE
[BUG] linux启动报错 ModuleNotFoundError: No module named 'chatchat'

### ISSUE THREAD

**Issue by chengyi3192** [chatchat-space/Langchain-Chatchat#4673]
**问题描述 / Problem Description**
linux启动报错 ModuleNotFoundError: No module named 'chatchat'

**复现问题的步骤 / Steps to Reproduce**
1. 执行 python3 chatchat/cli.py init

**预期的结果 / Expected Result**
初始化配置文件完成

**实际结果 / Actual Result**
```python
Traceback (most recent call last):
  File "/opt/module/chatchat/libs/chatchat-server/chatchat/cli.py", line 6, in <module>
    from chatchat.startup import main as startup_main
ModuleNotFoundError: No module named 'chatchat'
```

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：dev deployment
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Ollama 
- 操作系统及版本 / Operating system and version: centos-7.8
- Python 版本 / Python version: 3.10.0

**附加信息 / Additional Information**
使用的conda环境，poetry完成后，并没有在site-packages里面找到langchain-chatchat-0.3.1.dist-info文件夹（在windows环境是有的）

**Comment by Crazyalltnt** [comment]
同样的问题已使用下面的方法二解决。

使用`pip list`检查你是否成功安装如下依赖包：
```
langchain                   0.1.17
langchain-chatchat          0.3.1.3
poetry                      1.8.3
xinference-client           0.13.3
```
如果没有，说明`poetry install --with lint,test -E xinference`没有成功安装所有依赖。参考如下方法：

**方法一**

参考[#4392](https://github.com/chatchat-space/Langchain-Chatchat/issues/4392)使用`poetry update`更新依赖。

**方法二**

1.清理`poetry`的缓存`pypoetry`文件夹，请自行搜索不同操作系统下的路径。
2.检查`Langchain-Chatchat\libs\chatchat-server`文件夹下是否有`poetry.lock`文件，请删除。
3.再次执行`poetry install --with lint,test -E xinference`
4.检查安装过程有没有报错，没有报错再次使用`pip list`检查你是否成功安装前面所说的依赖包。

**Comment by 2069348297** [comment]
佬按您的方法二还是报错 提示Installing onnxruntime (1.20.1): Failed

![Image](https://github.com/user-attachments/assets/9fa524d2-aa7d-430d-bc50-3775fa3dc45a) 
能救一下吗
