### ISSUE TITLE
想请问下怎么在本地pycharm进行debug调试

### ISSUE THREAD

**Issue by 948024326** [chatchat-space/Langchain-Chatchat#4674]
之前在0.2.x系列中，通过pycharm这样配置可以debug启动项目
![image](https://github.com/user-attachments/assets/95275237-200f-430d-898d-0b66e333aa26)

今天跑0.3.x，先是走推荐的命令安装了环境
pip install langchain-chatchat -U
然后启动和对话是正常，xinference也正常接入，然后用如下配置debug也跑起来，但是并没有进入断点，控制台也没根据我代码输出内容
![image](https://github.com/user-attachments/assets/515bd3de-80a0-47ee-9253-d51785a7346d)

有些地方的库导入pycharm暴红了

1. 请问能怎么实现3系列版本的本地调试
2. 在改动代码后重启能够更新

**Comment by xxy-cn** [comment]
script 换成 cli.py 参数 start -a 试下，我 vscode 正常debug。

**Comment by 948024326** [comment]
> script 换成 cli.py 参数 start -a 试下，我 vscode 正常debug。

您好，我现在是按照这样配置的
![image](https://github.com/user-attachments/assets/e100d863-d31a-48e3-b3a2-f31c9e990b55)

发现debug启动后还是没进断点
![image](https://github.com/user-attachments/assets/6db240e8-dd86-416c-b502-1418a0130c16)

**Comment by xxy-cn** [comment]
<img width="1263" alt="image" src="https://github.com/user-attachments/assets/bd023cc1-34e0-4d14-872d-dd74aa7a4345">
我vscode正常断住，你这个编辑器我不了解🧐

**Comment by Yogurtder** [comment]
这个问题可能是代码去pip包的逻辑了，没有走本地代码。可以试试设置源代码根目录为Langchain-Chatchat/libs/chatchat-server/chatchat

**Comment by 948024326** [comment]
> 这个问题可能是代码去pip包的逻辑了，没有走本地代码。可以试试设置源代码根目录为Langchain-Chatchat/libs/chatchat-server/chatchat

好的，我之前也尝试了这个方法， 没成功，现在用其他方法解决这个问题了

**Comment by 948024326** [comment]
> 请问最后是如何解决的这个问题

不用他给的命令装环境，看上面的回复

**Comment by jersonal** [comment]
别用pip安装chatchat，那样会默认调用site-package里面的函数，所以本地debug没用，源码安装chatchat.
https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md

**Comment by hankiwii** [comment]
> <img alt="image" width="1263" src="https://private-user-images.githubusercontent.com/58839118/354941513-bd023cc1-34e0-4d14-872d-dd74aa7a4345.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczMzE4ODUsIm5iZiI6MTcyNzMzMTU4NSwicGF0aCI6Ii81ODgzOTExOC8zNTQ5NDE1MTMtYmQwMjNjYzEtMzRlMC00ZDE0LTg3MmQtZGQ3NGFhN2E0MzQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI2VDA2MTk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NzQ1NWVlM2RjYzQ4ZWRjYmM0YzFkZWM5Y2Y3YjFlMzgzZTFmOTFjZGY1NjM5NTMxNmQ2ODU4Y2Y5Y2YxMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XOKHgSFogzVWt9HwP1wsVSCqz4K2PtGz-ckyLicbLcc"> 我vscode正常断住，你这个编辑器我不了解🧐

请问你的vscode是怎么配置的
