### ISSUE TITLE
请问有实现多轮问答中基于问题的搜索上下文关联么

### ISSUE THREAD

**Issue by wenzitracyliu** [chatchat-space/Langchain-Chatchat#468]
在基于知识库的多轮问答中，第一个问题讲述了一个主题，后续的问题描述没有包含这个主题的关键词，但又存在上下文的关联。如果用后续问题去搜索知识库有可能会搜索出无关的信息，从而导致大模型无法正确回答问题。请问这个项目要考虑这种情况吗？
我目前只想到两种解决办法，一个是将多个问题一起去搜索，但这种效果不一定好。另一个是通过大模型先去判断之前的问题哪些是关联的，然后挑选出来，然后再去搜。不过这样可能很耗时

**Comment by zlei0251** [comment]
这两种方式都可能会改变提问者的原意，造成答非所问的情况，不知道有没有有更合理的方式来解决这个多轮会话的问题？

**Comment by zlei0251** [comment]
> 在基于知识库的多轮问答中，第一个问题讲述了一个主题，后续的问题描述没有包含这个主题的关键词，但又存在上下文的关联。如果用后续问题去搜索知识库有可能会搜索出无关的信息，从而导致大模型无法正确回答问题。请问这个项目要考虑这种情况吗？ 我目前只想到两种解决办法，一个是将多个问题一起去搜索，但这种效果不一定好。另一个是通过大模型先去判断之前的问题哪些是关联的，然后挑选出来，然后再去搜。不过这样可能很耗时


这两种方式都可能会改变提问者的原意，造成答非所问的情况，不知道有没有有更合理的方式来解决这个多轮会话的问题？

**Comment by qmaolong** [comment]
可以用函数调用解决这个问题，将知识库搜索定义成一个函数，大模型会根据上下文生成query作为向量匹配的入参，比如第二个问题问“详细一点”，大模型会根据上次的提问生成向量匹配参数，而不会直接将“详细一点”作为向量匹配入参

**Comment by zuoxiang95** [comment]
> 可以用函数调用解决这个问题，将知识库搜索定义成一个函数，大模型会根据上下文生成query作为向量匹配的入参，比如第二个问题问“详细一点”，大模型会根据上次的提问生成向量匹配参数，而不会直接将“详细一点”作为向量匹配入参

是不是可以理解为：把上轮问题和答案以及本轮问题先输入给大模型，让模型生成一个本轮问答的详细问法，再把这个生成的提问去做相似性检索

**Comment by wertyac** [comment]
比较难，感觉llm提取上下文上如果没有特别的promot很难主动提取，promot设计师关键？

**Comment by zuoxiang95** [comment]
> 比较难，感觉llm提取上下文上如果没有特别的promot很难主动提取，promot设计师关键？

我自己随便弄了一个，感觉还行

**Comment by 948726484** [comment]
请问楼主现在怎么处理该问题

**Comment by sevenandseven** [comment]
> 在基于知识库的多轮问答中，第一个问题讲述了一个主题，后续的问题描述没有包含这个主题的关键词，但又存在上下文的关联。如果用后续问题去搜索知识库有可能会搜索出无关的信息，从而导致大模型无法正确回答问题。请问这个项目要考虑这种情况吗？ 我目前只想到两种解决办法，一个是将多个问题一起去搜索，但这种效果不一定好。另一个是通过大模型先去判断之前的问题哪些是关联的，然后挑选出来，然后再去搜。不过这样可能很耗时

你好，我碰到和你相同的问题，想请问一下怎么解决？

我有个想法是将原来的信息存放到memory中，但是代码目前没改出来，请问你有什么好办法吗？
