### ISSUE TITLE
[BUG] list_knowledge_bases(), 无法访问

### ISSUE THREAD

**Issue by zifeng-radxa** [chatchat-space/Langchain-Chatchat#4680]
**问题描述 / Problem Description**
list_knowledge_bases(), 无法访问

**复现问题的步骤 / Steps to Reproduce**
```python
from chatchat.webui_pages.utils import api_address, ApiRequest

api = ApiRequest(base_url=api_address())

print(api.base_url)
print(api.list_knowledge_bases())
```

**预期的结果 / Expected Result**
```bash
  "code": 200,
  "msg": "success",
  "data": [
    {
      "id": 1,
      "kb_name": "samples",
      "kb_info": "关于本项目issue的解答",
      "vs_type": "faiss",
      "embed_model": "bge-base-zh",
      "file_count": 12,
      "create_time": "2024-08-05T07:24:07"
    }
  ]
}
```

**实际结果 / Actual Result**
```bash
http://127.0.0.1:7861
2024-08-05 17:00:15.867 | ERROR    | chatchat.webui_pages.utils:get:64 - InvalidURL: error when get /knowledge_base/list_knowledge_bases: Invalid port: ':1'
2024-08-05 17:00:15.899 | ERROR    | chatchat.webui_pages.utils:get:64 - InvalidURL: error when get /knowledge_base/list_knowledge_bases: Invalid port: ':1'
2024-08-05 17:00:15.931 | ERROR    | chatchat.webui_pages.utils:get:64 - InvalidURL: error when get /knowledge_base/list_knowledge_bases: Invalid port: ':1'
2024-08-05 17:00:15.931 | ERROR    | chatchat.webui_pages.utils:to_json:233 - AttributeError: API未能返回正确的JSON。'NoneType' object has no attribute 'json'
None

```

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：
langchain-chatchat 0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：
pypi 安装
- Python 版本 / Python version: 3.10
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU

**Comment by zifeng-radxa** [comment]
i found is the proxy problem in envirnmont, unset all proxy would solve
```bash
unset ftp_proxy
unset http_proxy
unset https_proxy
unset no_proxy
```

**Comment by Mature-B** [comment]
> i found is the proxy problem in envirnmont, unset all proxy would solve
> 
> ```shell
> unset ftp_proxy
> unset http_proxy
> unset https_proxy
> unset no_proxy
> ```

谢谢 今天又出现了这个问题 已解决

**Comment by tonynancy** [comment]
> > i found is the proxy problem in envirnmont, unset all proxy would solve
> > unset ftp_proxy
> > unset http_proxy
> > unset https_proxy
> > unset no_proxy
> 
> 谢谢 今天又出现了这个问题 已解决

请问怎么解决的呢？我也碰到这个问题了，非常感谢

**Comment by tonynancy** [comment]
> > > i found is the proxy problem in envirnmont, unset all proxy would solve
> > > unset ftp_proxy
> > > unset http_proxy
> > > unset https_proxy
> > > unset no_proxy
> > 
> > 
> > 谢谢 今天又出现了这个问题 已解决
> 
> 请问怎么解决的呢？我也碰到这个问题了，非常感谢

找到问题了，httpx版本高了，用0.27.2就可以了，pip install httpx==0.27.2
