### ISSUE TITLE
RAG对话回复：GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG

### ISSUE THREAD

**Issue by RyanOvO** [chatchat-space/Langchain-Chatchat#4683]
![image](https://github.com/user-attachments/assets/fbaf0ef8-8542-4aad-ade6-5c2b75c26f4f)
多功能对话语RAG对话都回复GGG。

模型：GLM4
向量：bge-large-zh-v1.5
推理框架：ollama

**Comment by RyanOvO** [comment]
重启过一次，又好了；但后来又这样了

**Comment by liuchuan01** [comment]
ollama和GLM4的兼容问题，可以去GLM4那边issue看看，都有这个情况，还得等等
