### ISSUE TITLE
多功能对话会调用知识库吗？RAG对话会调用LLM嘛？

### ISSUE THREAD

**Issue by RyanOvO** [chatchat-space/Langchain-Chatchat#4684]
多功能对话会调用知识库吗？RAG对话会调用LLM嘛？

**Comment by Unexpectedlyc** [comment]
同问，多功能对话能不能调用知识库

**Comment by Ederich013** [comment]
rag肯定是调用llm的，多功能的话看你开不开agent吧

**Comment by RyanOvO** [comment]
> rag肯定是调用llm的，多功能的话看你开不开agent吧

如果RAG调用了LLM，那为什么经常会出现 问的问题不在知识库，就会返回
![image](https://github.com/user-attachments/assets/3663d104-3570-4912-ace2-f2f364774be1)

正常来说，如果走LLM，RAG没查到，那就把Input传入LLM，正常走LLM返回响应的流程才对。

**Comment by Ederich013** [comment]
你看看prompt具体咋写的 这种回复应该是prompt里要求了如果没有匹配结果就输出‘根据已知信息无法回答该问题
’

**Comment by Ederich013** [comment]
chatchat现在的逻辑就是拼一个长的prompt出来，你把prompt改改能实现走llm的效果的，只是会比直接用llm差一些因为你的prompt里面会有检索到的内容干扰。大改的话就是看看langchain的原理然后加个链条 不过会比较麻烦

**Comment by RyanOvO** [comment]
> chatchat现在的逻辑就是拼一个长的prompt出来，你把prompt改改能实现走llm的效果的，只是会比直接用llm差一些因为你的prompt里面会有检索到的内容干扰。大改的话就是看看langchain的原理然后加个链条 不过会比较麻烦

好的

**Comment by RyanOvO** [comment]
> chatchat现在的逻辑就是拼一个长的prompt出来，你把prompt改改能实现走llm的效果的，只是会比直接用llm差一些因为你的prompt里面会有检索到的内容干扰。大改的话就是看看langchain的原理然后加个链条 不过会比较麻烦

看官方说明的架构，我理解的话，不管怎么样最终都是组装成Prompt，由LLM响应回复；但现在来看具体的情况，多少和这个逻辑有出入

**Comment by Ederich013** [comment]
这个理解没问题啊 rag就是搜索加组装prompt的过程吧，只是他原来prompt里面在最后强调了不要在知识库没有的情况下回答，可能是做了个相关度的检测，这个改改prompt就可以了

**Comment by RyanOvO** [comment]
好吧。不过这个prompt也是不好改，没有好参考的

**Comment by RyanOvO** [comment]
> 这个理解没问题啊 rag就是搜索加组装prompt的过程吧，只是他原来prompt里面在最后强调了不要在知识库没有的情况下回答，可能是做了个相关度的检测，这个改改prompt就可以了

好吧。不过这个prompt也是不好改，没有好参考的

**Comment by Ederich013** [comment]
可以让gpt来写

**Comment by RyanOvO** [comment]
> 可以让gpt来写

是的

**Comment by moshanghuakai-pang** [comment]
那请问为什么多功能对话中的本地知识库问答 回答不出来问题， rag对话却可以正确回答问题
