### ISSUE TITLE
[BUG] xinference正常启动的，chatchat项目也正常启动，但是对话就会报错 [openai request error: An error occurred during streaming]

### ISSUE THREAD

**Issue by jdx2099** [chatchat-space/Langchain-Chatchat#4686]
xinference正常启动了embedding模型和llm模型，如下图：
<img width="449" alt="xinference截图" src="https://github.com/user-attachments/assets/b442fbbc-4a9e-498c-87e4-facf1e53a8b3">

chatchat项目也正常启动的，
![image](https://github.com/user-attachments/assets/37a0d1f5-2f1e-47ef-9bcf-6db4bd1ae6dd)
![image](https://github.com/user-attachments/assets/41b2cb3d-4d5a-4ebc-83c0-15df866c56e6)

但是在对话框里对话以后，就报错了：
![image](https://github.com/user-attachments/assets/d454672b-8182-4234-93c3-7d96617e5e23)
![image](https://github.com/user-attachments/assets/33e5760f-a7c6-4faa-8821-b085920b7b3b)

**环境信息 / Environment Information**
- commit 号：0212a45b25a545eac1a18fd14c891955b4d334c3（v0.3.1.3)
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：源码部署
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：chatglm3-6b
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-m3
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本: Operating system and version: Linux-5.15.0-117-generic-x86_64-with-glibc2.31.
- Python 版本: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU (4090)
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
我在qwen2-7b、glm-4-9b-chat、glm-4-9b-chat-1m上都试过，都是这个结果，求大佬帮助

**Comment by jdx2099** [comment]
如果直接在xinference上启动的话，用tranformers会报错，用vllm不会报错（但是GPU会不够用）。
报错信息如下：
![image](https://github.com/user-attachments/assets/ee394b51-ea94-4d7b-b6f2-296f54d837fc)

'ChatGLMForConditionalGeneration' object has no attribute 'stream_chat'

**Comment by 171827593** [comment]
也遇到了这个问题，请问你解决了么？

**Comment by 171827593** [comment]
是xinference的问题，经过检查xinference的日志发现它有一个报错：
`024-10-06 20:02:59,027 xinference.model.llm.utils 17810 WARNING  tokenizer.apply_chat_template error. Maybe this is an old model: apply_chat_template requires jinja2>=3.1.0 to be installed. Your version is 3.0.3.
2024-10-06 20:02:59,042 xinference.core.model 17810 ERROR    [request edf71678-83da-11ef-968d-d90d5977f47f] Leave chat, error: No filter named 'items'., elapsed time: 0 s
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/xinference/model/llm/utils.py", line 97, in get_full_context
    full_context = tokenizer.apply_chat_template(
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1783, in apply_chat_template
    compiled_template = self._compile_jinja_template(chat_template)
  File "/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py", line 1909, in _compile_jinja_template
    raise ImportError(
ImportError: apply_chat_template requires jinja2>=3.1.0 to be installed. Your version is 3.0.3.
`
然后重新安装xinference即可 ，我用的python3.9的版本。重新安装后就好了，langchain可以连过来了。

**Comment by billfelix** [comment]
收到，谢谢您的来信。我将及时回复您！ 
祝好！
