### ISSUE TITLE
[BUG] 内存不足的问题

### ISSUE THREAD

**Issue by ccartermices** [chatchat-space/Langchain-Chatchat#470]
我用了本地的chatglm-6b-int4模型，然后显示了内存不足（win10+32G内存+1080ti11G），一般需要多少内存才足够？这个bug应该如何解决？

RuntimeError: [enforce fail at
C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\c10\core\impl\alloc_cpu.cpp:72] data.
DefaultCPUAllocator: not enough memory: you tried to allocate 1069285376 bytes.

**Comment by wipen** [comment]
我遇到了同样的问题。

**Comment by wipen** [comment]
我加载的是chatglm-6b-int4模型，win10+16G+1070ti。一开始和你报错相同，然后关机插上了一块闲置的8G内存，再开机后程序可以正常运行了。
