### ISSUE TITLE
[FEATURE] 请问可以增加第三方集成页面吗

### ISSUE THREAD

**Issue by liuqiang5151** [chatchat-space/Langchain-Chatchat#4709]
**功能描述 / Feature Description**
增加类似maxkb和dify那种通过iframe嵌入第三方系统的页面。

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by liunux4odoo** [comment]
暂无此计划。
