### ISSUE TITLE
请问我该怎么使用本地部署的searx呢，我已经在http://192.168.1.108:8000启用了searx，但是配置文件改了还是报错

### ISSUE THREAD

**Issue by LeeGitHub1** [chatchat-space/Langchain-Chatchat#4712]
<img width="933" alt="截屏2024-08-10 18 29 24" src="https://github.com/user-attachments/assets/89f579ae-09a0-4ef0-a0c8-1c02f46ff952">
![截屏2024-08-10 18 29 36](https://github.com/user-attachments/assets/de6c20dc-644b-4493-9d32-0549861ab450)
<img width="964" alt="截屏2024-08-10 18 29 51" src="https://github.com/user-attachments/assets/873a9bb5-1dce-4166-8d74-e2e0de12a313">

**Comment by LeeGitHub1** [comment]
![截屏2024-08-10 18 30 25](https://github.com/user-attachments/assets/a3300600-4166-416d-8a28-fec5c25a6428)
这个是未上传成功的图片

**Comment by liunux4odoo** [comment]
重复问题。
是glm4的tool输出不对。

**Comment by LeeGitHub1** [comment]
> 重复问题。 是glm4的tool输出不对。

请问该怎么修正呢
