### ISSUE TITLE
[BUG] 我使用源码部署代码，修改/Langchain-Chatchat/libs/chatchat-server/chatchat/下的文件后，如何重新部署启动呢

### ISSUE THREAD

**Issue by aqi123** [chatchat-space/Langchain-Chatchat#4723]
我使用源码部署代码，用了poetry，我现在需要修改/Langchain-Chatchat/libs/chatchat-server/chatchat/下的文件以适应自身需求，修改完后如何重新部署启动呢

**Comment by Ishiki-Iroha** [comment]
不是直接启动就行？不改源码怎么启动，你改了也一样启动啊

**Comment by Ishiki-Iroha** [comment]
```py
python cli.py start -a
```

**Comment by aqi123** [comment]
> 不是直接启动就行？不改源码怎么启动，你改了也一样启动啊

不需要运行poetry install --with lint,test -E xinference和poetry build这两条指令吗，不是很懂这块，希望指点一哈

**Comment by Ishiki-Iroha** [comment]
> > 不是直接启动就行？不改源码怎么启动，你改了也一样启动啊
> 
> 不需要运行poetry install --with lint,test -E xinference和poetry build这两条指令吗，不是很懂这块，希望指点一哈

不需要，那个是安装包依赖用的，装好包之后不用管了；如果你后续更改了依赖包中的代码，再部署到其他环境得同步更改或者自己打包自定义的包去安装；换句话说，你当前的开发环境之后不需要再考虑这个问题

**Comment by aqi123** [comment]
> > > 不是直接启动就行？不改源码怎么启动，你改了也一样启动啊
> > 
> > 
> > 不需要运行poetry install --with lint,test -E xinference和poetry build这两条指令吗，不是很懂这块，希望指点一哈
> 
> 根据我的理解，不需要，那个是安装包依赖用的，装好包之后不用管了；如果你后续更改了依赖包中的代码，再部署到其他环境得同步更改或者自己打包自定义的包去安装；换句话说，你当前的开发环境之后不需要再考虑这个问题

好的，那我修改源码后直接python cli.py start -a就行了，感谢解答！！！

**Comment by Ishiki-Iroha** [comment]
> > > > 不是直接启动就行？不改源码怎么启动，你改了也一样启动啊
> > > 
> > > 
> > > 不需要运行poetry install --with lint,test -E xinference和poetry build这两条指令吗，不是很懂这块，希望指点一哈
> > 
> > 
> > 根据我的理解，不需要，那个是安装包依赖用的，装好包之后不用管了；如果你后续更改了依赖包中的代码，再部署到其他环境得同步更改或者自己打包自定义的包去安装；换句话说，你当前的开发环境之后不需要再考虑这个问题
> 
> 好的，那我修改源码后直接python cli.py start -a就行了，感谢解答！！！

嗯，记得设置好CHATCHAT_ROOT环境变量应该就没问题

**Comment by aqi123** [comment]
> > > > > 不是直接启动就行？不改源码怎么启动，你改了也一样启动啊
> > > > 
> > > > 
> > > > 不需要运行poetry install --with lint,test -E xinference和poetry build这两条指令吗，不是很懂这块，希望指点一哈
> > > 
> > > 
> > > 根据我的理解，不需要，那个是安装包依赖用的，装好包之后不用管了；如果你后续更改了依赖包中的代码，再部署到其他环境得同步更改或者自己打包自定义的包去安装；换句话说，你当前的开发环境之后不需要再考虑这个问题
> > 
> > 
> > 好的，那我修改源码后直接python cli.py start -a就行了，感谢解答！！！
> 
> 嗯，记得设置好CHATCHAT_ROOT环境变量应该就没问题

好的，谢谢你！

**Comment by kid-297** [comment]
请问您的版本是哪个版本啊？我的版本是 0.3.1 ，试了一下不行
