### ISSUE TITLE
知识库构建时对json文件的支持和要求

### ISSUE THREAD

**Issue by AndersWXJY** [chatchat-space/Langchain-Chatchat#4724]
https://github.com/chatchat-space/Langchain-Chatchat/blob/ef46641475750ece6a2df435c6a42ee3f606cbbb/libs/chatchat-server/chatchat/server/knowledge_base/utils.py#L337
在构建知识库时，我用了一个json文件，内容是一个list，list每个元素是一个dict，包含content和meta。经过如上代码部分加载时，发现其解析的结果是将整个list的内容作为了文本，而不是按照list迭代访问各个dict字段。期望是获取每个dict的content字段value作为结果。
请问，对json文件的内容形式有什么要求吗？

**Comment by liunux4odoo** [comment]
没有，都是使用langchain 本身的 UnstructuredJsonLoader，如果需要解析成特定格式，需要自己写 loader
