### ISSUE TITLE
[BUG] webui.py 重新加载模型会导致 KeyError

### ISSUE THREAD

**Issue by aquila-zyy** [chatchat-space/Langchain-Chatchat#473]
**问题描述 / Problem Description**
重新加载模型会导致 KeyError

**复现问题的步骤 / Steps to Reproduce**
1. 执行 `python webui.py`
2. 点击 '模型配置 -> 重新加载本地模型'
3. 问题出现：控制台显示 `ERROR <时间戳>: 'THUDM/chatglm-6b'`

**预期的结果 / Expected Result**
重新加载选择的模型

**实际结果 / Actual Result**
未能加载模型并报错

**环境信息 / Environment Information**
- langchain-ChatGLM 版本号：0.0.174
- 是否使用 Docker 部署：否
- 使用的模型：ChatGLM-6B
- 使用的 Embedding 模型：text2vec-large-chinese
- 操作系统及版本：Ubuntu 22.04.2 LTS
- Python 版本：Python 3.10.6
- 其他相关环境信息 / Other relevant environment information: 

**附加信息 / Additional Information**
似乎是由于 ./models/shared.py 中的[这行代码](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/f0955768f5f9d9fa7e17733495d38c8f0b922b6d/models/shared.py#L22)导致的。[首次加载模型时](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/f0955768f5f9d9fa7e17733495d38c8f0b922b6d/models/shared.py#L35)默认使用本地模型导致模型名称里多了个路径。

**Comment by liunux4odoo** [comment]
在最近的更新后，如果要加载本地模型，需要把config中的no_remote_midel设为true，并且在程序运行期间不能改变，否则就会出现这个错误。

或者你把模型配置中的name和pretrained name应该也能规避这个问题
