### ISSUE TITLE
[BUG] 文本分割模型AliTextSplitter存在bug，会把“.”作为分割符

### ISSUE THREAD

**Issue by Lukangkang123** [chatchat-space/Langchain-Chatchat#476]
阿里达摩院的语义分割模型存在bug，默认会把".”作为分割符进行分割而不管上下文语义。是否还有其他分割符则未知。建议的修改方案：把“.”统一替换为其他字符，分割后再替换回来。或者添加其他分割模型。

以下是我在阿里modelscope官网上测试的结果。
[官方测试链接](https://www.modelscope.cn/models/damo/nlp_bert_document-segmentation_chinese-base/summary)
![bdf3accba7f97f5a4cdc203e1efdb94](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38984189/e118ccc2-fd2d-460e-b582-8a128a05cd34)

**Comment by ATP-BME** [comment]
同样遇到了这一问题

**Comment by ATP-BME** [comment]
请问现在有什么比较好的解决办法吗

**Comment by LMERose** [comment]
hi,do you known how to deal this problems?

**Comment by Lukangkang123** [comment]
> hi,do you known how to deal this problems?

You can replace "." with other characters and then replace them back after the split operation.

**Comment by LMERose** [comment]
> > hi,do you known how to deal this problems?
> 
> You can replace "." with other characters and then replace them back after the split operation.

Will this processing be slow? What is the performance when there are a large number of files? Or have you tried or recommended other segmented models?

**Comment by Super-six-java** [comment]
我在下载模型官网上看见官方的评论
非常抱歉，确实有这个badcase存在。现阶段如果只是中文场景，建议你可以先自行修改本地安装包里这一部分分句函数，modelscope.pipelines.nlp.document_segmentation_pipeline.cut_sentence，你把第一个正则表达式里的小数点去掉即可
![image](https://github.com/chatchat-space/Langchain-Chatchat/assets/55952395/fa2c00c9-052c-4a4d-9ad8-fa5f5f3911dc)
