### ISSUE TITLE
[BUG] Resource punkt_tab not found

### ISSUE THREAD

**Issue by zlpmetyou** [chatchat-space/Langchain-Chatchat#4787]
手动使用Dockerfile打包了镜像，配置使用milvus向量库之后，添加文档到向量库，提示Resource punkt_tab not found

**Comment by lrw-lee** [comment]
<img width="1403" alt="image" src="https://github.com/user-attachments/assets/1665912c-0381-4349-80bc-2862a0ba647d">
pdf和docx文件报错

**Comment by zlpmetyou** [comment]
> <img alt="image" width="1403" src="https://private-user-images.githubusercontent.com/33407226/357333600-1665912c-0381-4349-80bc-2862a0ba647d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1Mzg1ODEsIm5iZiI6MTcyMzUzODI4MSwicGF0aCI6Ii8zMzQwNzIyNi8zNTczMzM2MDAtMTY2NTkxMmMtMDM4MS00MzQ5LTgwYmMtMjg2MmEwYmE2NDdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA4MzgwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZGFjMTE2NGFjYzNjYzk0ZWQxYWVhMjQ0Njg4MmE3MmJkYzNmMDQ1MDM4ZTFkZDA1YjIwMmEwMGJhYmFiNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cRUwS7Lcpvja8DmYr84DdowEioD0vPd4_p56gtP9fX8"> pdf和docx文件报错

我用txt也报错，下载完这个之后，又要求另一个Resource averaged_perceptron_tagger_eng not found.
感觉会没完没了的下载

**Comment by yangwenbing2** [comment]
我也遇到了这个问题，通过手动下载了 punkt_tab 数据包，然后放到其中一个nltk_data文件夹中，还是不行

**Comment by lrw-lee** [comment]
nltk 固定到 3.8.1 解决问题

**Comment by bbgcz** [comment]
今天刚碰到，印象里做了如下操作：
1. 下载nltk_data(https://github.com/nltk/nltk_data)
2. 复制packages里的文件夹到你的nltk_data目录
![image](https://github.com/user-attachments/assets/b4f2b1d0-c28c-4d91-b8b9-9f43cea48c9d)
3. 解压了punkt_tab
![image](https://github.com/user-attachments/assets/989ff821-be67-4d3f-ae96-757e1db8bc1a)
4. 安装了nltk3.8.1而不是3.8.2  (pip install nltk==3.8.1)

刚看评论，或许可能大概第4步就行......

**Comment by zlpmetyou** [comment]
![image](https://github.com/user-attachments/assets/cc593d92-e3b4-4944-81be-fa1bd2bf0379)
@bbgcz 越来越离谱，我按照你这个做了，确实不提示nltk了，但是所有类型的文件都提示这个File is not a zip file
@lrw-lee 只固定3.8.1还是不行

**Comment by yangwenbing2** [comment]
我遇到的问题也成功解决了！解决步骤：

#### 1. 安装了nltk3.8.1而不是3.8.2 (pip install nltk==3.8.1)
报错由 `nltk.download('puntk_tab')` 变为了 `nltk.download('puntk')` 

#### 2. 按照 [ @bbgcz ](https://github.com/chatchat-space/Langchain-Chatchat/issues/4787#issuecomment-2285767635) 这个的前三步骤。但是由于到了新的问题：
![image](https://github.com/user-attachments/assets/fa4a5f9e-05c2-48f3-920d-13c4c0961df4)

#### 3. 解压`nltk_data/taggers/averaged_perceptron_tagger*.zip`的文件。

然后就可以了！

**Comment by zlpmetyou** [comment]
@yangwenbing2 你也是拉取的master最新代码么？

**Comment by yangwenbing2** [comment]
嗯嗯 昨天刚拉的master代码

**Comment by ShirleyJi1998** [comment]
> @yangwenbing2 你也是拉取的master最新代码么？

请问你解决了吗？我按照上面介绍的方法没有效果

**Comment by yangwenbing2** [comment]
> > @yangwenbing2 你也是拉取的master最新代码么？
> 
> 请问你解决了吗？我按照上面介绍的方法没有效果

嗯嗯，解决了。就是按照这个方法：https://github.com/chatchat-space/Langchain-Chatchat/issues/4787#issuecomment-2288113928

你报什么错误呢？

**Comment by ArronAI007** [comment]
我按照[https://github.com/chatchat-space/Langchain-Chatchat/issues/4787#issuecomment-2288113928](url)这个方法还是不行，然后把tokenizers下面的punkt.zip文件解压一下才可以的
