### ISSUE TITLE
[BUG] RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) a 

### ISSUE THREAD

**Issue by jiaohuix** [chatchat-space/Langchain-Chatchat#479]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
在使用webui加载并上传txt后出现了红色的error，在终端报faiss的错误。

**复现问题的步骤 / Steps to Reproduce**
1. python webui.py
2. 打开gradio
3. 上传txt

**预期的结果 / Expected Result**
正确加载知识库

**实际结果 / Actual Result**
红色的ERROR
**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: Ubuntu
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by imClumsyPanda** [comment]
请问知识库名是否不满足英文/数字的字符要求

**Comment by xibeidapiaoke** [comment]
我也遇到了同样的问题，你解决了吗？

**Comment by xibeidapiaoke** [comment]
可能txt中含有特殊字符？？？？

**Comment by zhit-W** [comment]
> 请问知识库名是否不满足英文/数字的字符要求

是这个问题，把知识库名字改成英文就好了
