### ISSUE TITLE
求助，多功能对话的效果怎么通过API调用？

### ISSUE THREAD

**Issue by liutianye** [chatchat-space/Langchain-Chatchat#4812]
**启动服务后混合对话的效果想通过API调用方式实现**
问一个问题想优先查找知识库内数据，如果没有就利用模型自身能力来回答。但是现在调用/chat/kb_chat或/chat/chat/completions后
都只是去找知识库信息，问其他的简单问题也是回答不出来。
![微信截图_20240814191326](https://github.com/user-attachments/assets/a9c75d99-8427-4556-bd1a-1358009a72e1)
但是页面上的“多功能对话”里可以回答出问题。
![微信截图_20240814191748](https://github.com/user-attachments/assets/f9608989-50dc-4046-9af6-c302c5958599)
而且这种问答是不是没有上下文？
求大佬指点一下，万分感谢。

**Comment by liunux4odoo** [comment]
见 api.md

**Comment by liutianye** [comment]
> @liutianye 请问你这个多功能对话问答的上下问解决了吗

没有，放弃掉了，因为看到说就算改了这个，启用了agent能力之后输出也不是流式的，比较麻烦，后续打算更换其他工具了。

**Comment by yuezhupy** [comment]
@liutianye 
好的，谢谢
