### ISSUE TITLE
[BUG] 请问怎么没有requirements.txt文件呢？

### ISSUE THREAD

**Issue by CMaggie-yy** [chatchat-space/Langchain-Chatchat#4830]
**问题描述 / requirements.txt**
请问怎么没有requirements.txt文件呢？

**Comment by imClumsyPanda** [comment]
因为在0.3.x版本中项目改为使用poetry对环境依赖进行管理，请参考https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md
