### ISSUE TITLE
[BUG] master分支中的cli.py文件没有修复nltk_data目录复制失败的问题，但是在master分支的chatchat-server下的readme中却说已经修复了。

### ISSUE THREAD

**Issue by sengineer00** [chatchat-space/Langchain-Chatchat#4831]
感谢各位大佬无私分享！！！

[BUG] master分支中的cli.py文件没有修复nltk_data目录复制失败的问题，但是在master分支的chatchat-server下的readme中却说已经修复了。

**Comment by liunux4odoo** [comment]
兄弟方便测试一下 #4832  吗？

**Comment by sengineer00** [comment]
master分支的cli.py的init函数里面还是没有复制nltk_data的逻辑。我理解的是在执行chatchat init的命令后应该要有复制nltk_data的逻辑。

**Comment by liunux4odoo** [comment]
> master分支的cli.py的init函数里面还是没有复制nltk_data的逻辑。我理解的是在执行chatchat init的命令后应该要有复制nltk_data的逻辑。

现在是没有复制，直接使用chatchat/data/nltk_data。
能测试一下是否正常运行吗？我这边测了没有问题，但不敢确定是否有工作环境影响。

**Comment by sengineer00** [comment]
我这边在添加文件到知识库的时候，会碰到要找不到这两个包，需要下载 nltk.download('punkt_tab'   nltk.download('averaged_perceptron_tagger_eng') 的问题，自己在conda环境下下载就好了，但其实下载的包也没在 chatchat/data/nltk_data的目录下

**Comment by liunux4odoo** [comment]
> 我这边在添加文件到知识库的时候，会碰到要找不到这两个包，需要下载 nltk.download('punkt_tab' nltk.download('averaged_perceptron_tagger_eng') 的问题，自己在conda环境下下载就好了，但其实下载的包也没在 chatchat/data/nltk_data的目录下

是用最新版 master 分支代码试试的吗？

**Comment by sengineer00** [comment]
上周五的master分支

**Comment by liunux4odoo** [comment]
> 上周五的master分


更新后再试一下吧，昨天下午修复了。

**Comment by Sn-HIT** [comment]
我用最新master分支重试了，问题已经修复了

**Comment by sengineer00** [comment]
已测试，问题已修复。

**Comment by liunux4odoo** [comment]
还好还好，没再出问题了。
