### ISSUE TITLE
请问如何在model_settings.yaml中指定本地LLM 模型和Embedding 模型的路径?

### ISSUE THREAD

**Issue by hou-yufeng** [chatchat-space/Langchain-Chatchat#4840]
您好, 应该不是Issue, 仅仅是我自己没有找到配置的地方. 我已经在本地下载好LLM和Embedding模型, 如何在Langchain-Chatchat的配置文件中设置本地模型的路径? Google得到的结果都是在py文件中设置, 但显然那是过期的信息.

**Comment by liunux4odoo** [comment]
不能指定，模型配置见文档。
