### ISSUE TITLE
[BUG] 向量知识库稍微大一些会占用很大的内存。40w条的csv文件需要将近20g的内存。

### ISSUE THREAD

**Issue by mudapakka** [chatchat-space/Langchain-Chatchat#4841]
构建向量知识库时，占用内存过大。100w条。40g的内存进程会自己kill掉。没有任何报错信息。

**Comment by mudapakka** [comment]
感觉可能是把embedding都存到内存里了？

**Comment by mudapakka** [comment]
@dosubot

**Comment by mudapakka** [comment]
@dosu

**Comment by liunux4odoo** [comment]
知识库构建目前是以文件为单位的，所有的 Documents 和 Embeddings 都是在内存里。可以先把 csv 文件拆成多个小文件试试。

**Comment by mudapakka** [comment]
> 知识库构建目前是以文件为单位的，所有的 Documents 和 Embeddings 都是在内存里。可以先把 csv 文件拆成多个小文件试试。

好的，非常感谢。目前现在使用小文件+milvus解决的
