### ISSUE TITLE
[BUG] not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by lhtpluto** [chatchat-space/Langchain-Chatchat#4849]
使用知识库对话时，反馈 not enough values to unpack (expected 2, got 0)

操作系统：Linux-6.8.0-40-generic-x86_64-with-glibc2.35.
python版本：3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
项目版本：0.3.1.3
langchain版本：0.1.17
数据目录：/root

当前使用的分词器：ChineseRecursiveTextSplitter
默认选用的 Embedding 名称： bge-m3

模型是：qwen2-instruct  72B-AWQ
 知识库：   (faiss @ bge-m3)

已经参阅 https://github.com/chatchat-space/Langchain-Chatchat/issues/449

**Comment by trackcan** [comment]
问题有可能是出在bm25检索器内部未做保护，docs进行非空保护下
bm25_retriever = BM25Retriever.from_documents(
            docs,
            preprocess_func=jieba.lcut_for_search,
        )
