### ISSUE TITLE
[小白求助] 通过Anaconda执行webui.py后，无法打开web链接

### ISSUE THREAD

**Issue by NiseAkki** [chatchat-space/Langchain-Chatchat#485]
在执行webui.py命令后，http://0.0.0.0:7860复制到浏览器后无法打开，显示“无法访问此网站”。
各位大佬帮忙看看，谢谢！

**Comment by imClumsyPanda** [comment]
localhost:7860

**Comment by NiseAkki** [comment]
> localhost:7860

感谢大佬回答！

**Comment by LiZhangMing** [comment]
> 

我也使用了这个网址然后还是打不开网址呢。

**Comment by LiZhangMing** [comment]
(demo
 .queue(concurrency_count=3)
 .launch(server_name='0.0.0.0',
         server_port=7860,
         show_api=False,
         share=True,
         inbrowser=False))
我的配置是这个 然后运行后在网页中输入了localhost:7860 还是打不开。能问下怎么回事吗？

**Comment by zealot52099** [comment]
试试 http://127.0.0.1:7860/
