### ISSUE TITLE
0.2.10版本如何使用chatglm4

### ISSUE THREAD

**Issue by tanmw** [chatchat-space/Langchain-Chatchat#4854]
0.3.1版本由于数据库问答效果不好，因此打算继续使用0.2.10版本，但是直接下载glm4并修改path是没办法在chatchat上使用的，请问要修改哪些地方，才可以使用

**Comment by liunux4odoo** [comment]
0.2版本已经停止维护。
你可以尝试以 openai API 的形式接入。
