### ISSUE TITLE
[小白求助]  服务器上执行webui.py后，在本地无法打开web链接

### ISSUE THREAD

**Issue by LiZhangMing** [chatchat-space/Langchain-Chatchat#487]
此项目执行在xxx.xx.xxx.xxx服务器上，我在webui.py上的代码为  (demo
.queue(concurrency_count=3)
.launch(server_name='0.0.0.0',
server_port=7860,
show_api=False,
share=True,
inbrowser=False))
我的配置是这个 然后运行后在本地网页中输入了localhost:7860,打不开，然后尝试使用xxx.xx.xxx.xxx:7860还是打不开。能问下怎么回事吗？

**Comment by nameless0704** [comment]
xxx.xx.xxx.xxx服务器是连接互联网的吗？本地和xxx.xx.xxx.xxx服务器能ping通吗？

**Comment by WQDestiny** [comment]
可能是你的gradio版本太高，建议安装gradio==3.23.0试试

**Comment by LiZhangMing** [comment]
好的

**Comment by liyiyiya** [comment]
> 好的
好兄弟，最后是怎么解决的
