### ISSUE TITLE
[BUG] win10执行chatchat kb -r 报错：由于目标计算机积极拒绝，无法连接。')) 2024-08-28 17:00:31.316 | ERROR    | chatchat.init_database:worker:61 - 向量库 samples 加载失败。

### ISSUE THREAD

**Issue by freezehe** [chatchat-space/Langchain-Chatchat#4878]
**问题描述 / Problem Description**
参考官方操作手册部署，执行到这个命令chatchat kb -r 报错，报错日志截图
![image](https://github.com/user-attachments/assets/f211e656-e227-4af3-9f08-8e36b991546d)

环境：
win10+conda环境下，新建了两个conda虚拟环境，chatchat环境版本
![image](https://github.com/user-attachments/assets/a22bb08d-ef43-4f8f-a7ef-6bfe4d3df05a)
![image](https://github.com/user-attachments/assets/70271d8a-0ac4-4a13-b1e8-9e3965daa302)

xinference环境版本
![image](https://github.com/user-attachments/assets/32ae5c7f-9e37-4631-9d5d-852dd52922dc)
xinference本机启动成功了，
![image](https://github.com/user-attachments/assets/19f967de-3065-4b21-a715-b73135be9a8e)

model_settings.yaml配置文件修改的地方
![image](https://github.com/user-attachments/assets/af924bd2-dab2-432b-ab51-4701c122a5ef)
![image](https://github.com/user-attachments/assets/ab92065a-52e9-4754-8a8a-c8175fd33ee1)

请问如何解决这个bug?

**Comment by imClumsyPanda** [comment]
需要在xinference中启动模型

**Comment by freezehe** [comment]
> 需要在xinference中启动模型

你好，请问怎么启动呢？文档没有写

**Comment by freezehe** [comment]
> 需要在xinference中启动模型

你好，我重新启动了模型，现在又报503的错误，怎么解决？
![image](https://github.com/user-attachments/assets/9e873e89-1a97-4068-a31d-e1768c77a75f)

**Comment by BigKkai** [comment]
你要把模型运行起来 不是只把Xinference运行

**Comment by liunux4odoo** [comment]
duplicate of #4874

**Comment by JayBoy3206** [comment]
> 你要把模型运行起来 不是只把Xinference运行

您好，具体怎么解决呀
