### ISSUE TITLE
[FEATURE] 能不能支持VisualGLM-6B

### ISSUE THREAD

**Issue by haorunze** [chatchat-space/Langchain-Chatchat#488]
**功能描述 / Feature Description**
能不能直接加载这个模型？
https://github.com/THUDM/VisualGLM-6B

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by lliang2003** [comment]
good idea!

**Comment by lzl-hello** [comment]
> **功能描述 / Feature Description** 能不能直接加载这个模型？ https://github.com/THUDM/VisualGLM-6B
> 
> **解决的问题 / Problem Solved** 解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.
> 
> **实现建议 / Implementation Suggestions** 如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.
> 
> **替代方案 / Alternative Solutions** 描述您考虑过的替代方案 / Describe alternative solutions you have considered.
> 
> **其他信息 / Additional Information** 添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

请问这个实现了吗？可以加载吗？
