### ISSUE TITLE
0.3.1.3版本，xinference加载运行qwen1.5-chat模型报错：KeyError: [address=0.0.0.0:33720, pid=21032] 'model.embed_tokens.weight'

### ISSUE THREAD

**Issue by freezehe** [chatchat-space/Langchain-Chatchat#4880]
各位老师好，bug如题，我是在centos7上分别在conda环境创建了两个环境，参考官方手册进行操作的，一个是专门运行框架的xinference，一个是chatchat，在浏览器页面上加载运行qwen1.5-chat模型报错，我贴一下图，我选择的内容：
![image](https://github.com/user-attachments/assets/8192c2f2-8021-4e13-8dbb-7117c8ec2ab2)
然后日志报错如下：
![image](https://github.com/user-attachments/assets/e6395633-a242-4526-8c9c-7037fabc7088)
我也提前在issue上搜索同类问题，没找到，参考官方手册操作还没有运行成功，请各位老师指点一下，谢谢！

centos7
chatchat的环境版本如下：
![image](https://github.com/user-attachments/assets/aaab822e-e5f1-4ec0-b740-64f679f3c019)
![image](https://github.com/user-attachments/assets/958dbbf8-f044-4530-835f-a5a78cae6c1b)
xinference环境版本如下：
![image](https://github.com/user-attachments/assets/f058d914-156a-4fad-a6cd-95dd020c84a3)
我的服务器配置信息如下：
![image](https://github.com/user-attachments/assets/1c1e336e-42f5-4ad0-9c9f-0bb0b22b3081)

**Comment by RengarWang** [comment]
原因是：xinference在使用指定量化时，只能运行bin文件，而qwen1.5或者qwen2的模型是safetensors格式。
