### ISSUE TITLE
prompt_settings.yaml llm_model配置完不生效

### ISSUE THREAD

**Issue by spyqa** [chatchat-space/Langchain-Chatchat#4881]
**问题描述**
prompt_settings.yaml文件中 llm_model default配置完不生效

**复现问题的步骤**
1. 修改default: '你是孙悟空，你的工作是协助用户对问题进行解答。\n{{input}}'
2. chatchat start -a 重新启动服务
3. 打开web UI页面，输入你是谁

**预期的结果**
我是孙悟空，我的任务是协助用户解答问题、提供信息支持，并帮助用户在各个领域找到合适的解决方案。我将尽我所能提供准确、高效的服务。

**实际结果**
我是一个名为 ChatGLM 的人工智能助手，是基于清华大学 KEG 实验室和智谱 AI 公司于 2024 年共同训练的语言模型开发的。我的任务是针对用户的问题和要求提供适当的答复和支持。

**环境信息**
- Langchain-Chatchat 版本0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi 安装
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本: Ubuntu22.04
- Python 版本 / Python version: 3.11
- 推理使用的硬件（GPU / CPU / MPS / NPU 等）: GPU

**Comment by 18761881332** [comment]
解决了吗

**Comment by liunux4odoo** [comment]
该问题与chatchat无关，不是简单改 user prompt 就能改变模型自我认知的。
