### ISSUE TITLE
请问想调用讯飞星火的api怎么配置，如果调用openai形式的url，还用xinference啥的吗，小白刚看不太懂

### ISSUE THREAD

**Issue by annanfree** [chatchat-space/Langchain-Chatchat#4897]

**Comment by jiusi9** [comment]
如果你调用在线模型，就不用xinference了。 

xinference是一个可以把本地模型运行起来的工具，并提供一个openai的api。

**Comment by annanfree** [comment]
> 如果你调用在线模型，就不用xinference了。
> 
> xinference是一个可以把本地模型运行起来的工具，并提供一个openai的api。

如果embedding用本地的，llm掉烽火api呢，也需要xinference吧

**Comment by yangze68** [comment]
然后在model setting的yaml配置页里找到oneapi的配置，填上api key就ok

**Comment by guanxiaoguan** [comment]
> 然后在model setting的yaml配置页里找到oneapi的配置，填上api key就ok

自己搭建的vllm server 没有api key 但是http调用有header验证，配置文件应该怎么写？
