### ISSUE TITLE
请问如何在0.3.1版本中连接上mysql数据库，完成数据库问答，求详细步骤，小白求学

### ISSUE THREAD

**Issue by 2776721779** [chatchat-space/Langchain-Chatchat#4899]

**Comment by wpcwpcwpc** [comment]
在python、mysql环境满足的前提下，将basic_settings.yaml里sqlite的默认配置修改成如下即可（替换user\password）
# 知识库信息数据库连接URI
SQLALCHEMY_DATABASE_URI: mysql+pymysql://<user>:<password>@127.0.0.1:3307/knowledge_base

**Comment by 2776721779** [comment]
文件中的内容填写的没问题，推理时，出现了下面的问题，请问您遇到过这个问题吗？怎么解决的？
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '主机地址' ([Errno 11001] getaddrinfo failed)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by 2776721779** [comment]
> 在python、mysql环境满足的前提下，将basic_settings.yaml里sqlite的默认配置修改成如下即可（替换user\password）
> 
> # 知识库信息数据库连接URI
> SQLALCHEMY_DATABASE_URI: mysql+pymysql://:@127.0.0.1:3307/knowledge_base

请问您遇到过这个问题吗，怎么解决的

**Comment by linssbf** [comment]
数据库跟向量库不同的吧

**Comment by 2776721779** [comment]
数据库和向量库没有什么关系吧

> 数据库跟向量库不同的吧 向量库应该是在kb_settings.yaml这里设置
