### ISSUE TITLE
[BUG] 为什么修改了webui.py中的代码，前端界面没有做更改

### ISSUE THREAD

**Issue by azhe1234** [chatchat-space/Langchain-Chatchat#4903]
为什么修改了webui.py中的代码，前端界面没有做更改
![image](https://github.com/user-attachments/assets/25c5ff63-f0d7-494f-aaa9-1bf9da895ef4)
实际运行结果：
![image](https://github.com/user-attachments/assets/c7541996-14b5-4040-999d-6f9ec44777c1)
依然显示，请问怎么解决谢谢！

**Comment by wangsiyu666** [comment]
清理一下浏览器缓存试试

**Comment by azhe1234** [comment]
> 清理一下浏览器缓存试试

已经解决谢谢！

**Comment by Zasuoq** [comment]
> > 清理一下浏览器缓存试试
> 
> 已经解决谢谢！

您好，方便问一下是怎么解决的吗，我清理了浏览器缓存后，前端依然没有变化
