### ISSUE TITLE
docker环境部署下如何生成和修改配置文件?

### ISSUE THREAD

**Issue by JustTestCode** [chatchat-space/Langchain-Chatchat#4904]
**问题描述 / Problem Description**

docker 部署 后找不到配置文件在哪里. 因为是windows的docker环境,无法修改xinference的地址127.0.0.1为host.docker.internal ,既然是docker-compose模式,为什么不直接用 xinference:9997 进行连接, 反而是127.0.0.1:9997 ?  配置文件进入容器执行了chat chat init, 也没找到生成的配置文件路径在哪.想把配置文件映射出来修改

**复现问题的步骤 / Steps to Reproduce**

**预期的结果 / Expected Result**

**实际结果 / Actual Result**

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1.3-93e2c87-20240829
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：docker

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by linssbf** [comment]
在镜像/root/chatchat_data目录下

**Comment by startLight2019** [comment]
这个可以通过打包进去或者挂载的形式修改配置文件内容吗
