### ISSUE TITLE
请问embedding模型也经过xinference 吗？另外直接调用星火的llm的openai形式的api，请问怎么配置？好像教程写的不是很清楚。

### ISSUE THREAD

**Issue by annanfree** [chatchat-space/Langchain-Chatchat#4906]

**Comment by liunux4odoo** [comment]
参考 xinference 的配置项，只要是openai兼容的接口，api_url/key 配好，模型名称写好就可以了。

**Comment by annanfree** [comment]
> 参考 xinference 的配置项，只要是openai兼容的接口，api_url/key 配好，模型名称写好就可以了。

**Comment by annanfree** [comment]
是把api_url/key配在xinference里，还是在项目配置文件里

**Comment by codewen77** [comment]
> 参考 xinference 的配置项，只要是openai兼容的接口，api_url/key 配好，模型名称写好就可以了。

请问不兼容的呢。。 公司自己部署的模型，api的data自己做了下封装，请问这种如何自定义。

**Comment by liunux4odoo** [comment]
不兼容就没办法了，要么改成兼容的，要么自己做适配。

**Comment by qinhuaian** [comment]
> > 参考 xinference 的配置项，只要是openai兼容的接口，api_url/key 配好，模型名称写好就可以了。
> 
> 请问不兼容的呢。。 公司自己部署的模型，api的data自己做了下封装，请问这种如何自定义。

请问最后怎么用公司自己部署的模型呀？

**Comment by EvanSong77** [comment]
> > > 参考 xinference 的配置项，只要是openai兼容的接口，api_url/key 配好，模型名称写好就可以了。
> > 
> > 
> > 请问不兼容的呢。。 公司自己部署的模型，api的data自己做了下封装，请问这种如何自定义。
> 
> 请问最后怎么用公司自己部署的模型呀？

自己写一个适配的服务接口。

**Comment by EvanSong77** [comment]
> > > 参考 xinference 的配置项，只要是openai兼容的接口，api_url/key 配好，模型名称写好就可以了。
> > 
> > 
> > 请问不兼容的呢。。 公司自己部署的模型，api的data自己做了下封装，请问这种如何自定义。
> 
> 请问最后怎么用公司自己部署的模型呀？

自己写一个适配的服务接口，用服务做转发。
