### ISSUE TITLE
430个文档，解析以后知识库回答特别慢

### ISSUE THREAD

**Issue by public-cdn** [chatchat-space/Langchain-Chatchat#4908]
尝试对接 'faiss', 'milvus' 向量数据库 ，大约反应 3分钟以上
单独多模型对话 尝试 特别快 几乎秒回复 
![image](https://github.com/user-attachments/assets/628567bb-53c1-4432-87ce-d3778fd409d7)

**Comment by liunux4odoo** [comment]
duplicate of #4339
