### ISSUE TITLE
[FEATURE] 文件对话持久化管理优化

### ISSUE THREAD

**Issue by learnmodest** [chatchat-space/Langchain-Chatchat#4910]
**功能描述 / Feature Description**
1.支持通过API调用的方式删除文件对话中上传的文件.
2.支持文件对话对应的临时会话和文件重启不清空

**解决的问题 / Problem Solved**
1.避免上传的文件不支持删除，引发的文件对话时有冗余数据。
2.文件对话对应的临时会话和文件重启清空，导致无法将文件对话持久化，实现类似OpenAI类似的历史会话功能

**实现建议 / Implementation Suggestions**
1.提供支持删除已上传的文件的API接口
2.通过配置项的方式，开启/关闭 清空文件对话数据

**Comment by liunux4odoo** [comment]
需要持久化的文件放入知识库即可。
文件对话的特征就是临时性，向量库都是保存在内存的，重启之后就不存在了。
