### ISSUE TITLE
请问怎么将Langchain-chatchat作为一个服务嵌入到第三方的网页中作为服务？可以提供下思路吗谢谢！

### ISSUE THREAD

**Issue by azhe1234** [chatchat-space/Langchain-Chatchat#4911]
请问怎么将Langchain-chatchat的RAG功能作为一个服务嵌入到第三方的网页中作为服务？可以提供下思路吗谢谢！
![image](https://github.com/user-attachments/assets/4b64fcb8-c88a-487b-aa0c-c7648cd85469)

**Comment by flywhc** [comment]
写个前端调用它的API：

https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/api.md

**Comment by azhe1234** [comment]
> 写个前端调用它的API：
> 
> https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/api.md

好的明白啦，谢谢你！
