### ISSUE TITLE
xinference已经启动本地模型，langchain-chatchat中的config也已经配置了模型名，为什么还是无法使用指定的模型？哪位佬能解答一下？

### ISSUE THREAD

**Issue by Alan-zhong** [chatchat-space/Langchain-Chatchat#4912]
![fdba5cfc666f6180e80114c748c7561](https://github.com/user-attachments/assets/149abdc8-5fea-411d-a8ee-64dbaffc1559)

**Comment by shenlei162** [comment]
xinference要加载qwen-vl模型的，确保模型已经在.xinference缓存里面

**Comment by tf18536** [comment]
一样的问题，同问？
