### ISSUE TITLE
我刚接触项目，看了两遍也没看懂model_setting.yaml，我是embedding模型想用本地的，llm想调用讯飞星火的url（openai格式），请问怎么配置？（我用xinference运行了bge-m3，星火的url配置在哪里）

### ISSUE THREAD

**Issue by annanfree** [chatchat-space/Langchain-Chatchat#4913]
![image](https://github.com/user-attachments/assets/eb5c3e3f-db87-409c-8a11-f3258857d387)
![image](https://github.com/user-attachments/assets/3c02483e-e6fe-4323-8f2e-7171a181a760)
![image](https://github.com/user-attachments/assets/34a6dce3-7633-4379-81c7-04f313cb9b07)
![image](https://github.com/user-attachments/assets/ed8f59b8-106f-48d3-b83a-d39b203764ba)
![Uploading image.png…]()

**Comment by liunux4odoo** [comment]
请勿重复提交 issue
