### ISSUE TITLE
[求助] 如果在公司内部搭建产品知识库，使用INT-4模型，200人规模需要配置多少显存的服务器？

### ISSUE THREAD

**Issue by NiseAkki** [chatchat-space/Langchain-Chatchat#492]
如题，计划给公司搭一个在线知识库。
员工人数约200人次，并发峰值估计100人次，应该选购何种规格的云服务器？

感谢大佬！

**Comment by cristianohello** [comment]
这估计需要4块A100。而且随着轮数的增加，回复速度巨慢。咱俩一样的场景。

**Comment by NiseAkki** [comment]
> 

感谢回答，这个确实没法实现。

**Comment by Lukangkang123** [comment]
200人也不会同时访问吧

**Comment by net592** [comment]
本地知识库，很多标点符号不行，比如网址类，都加了一个空格如何解决的大佬
