### ISSUE TITLE
请问各位如何修改知识库对话的api调用格式，求大佬解惑！！！

### ISSUE THREAD

**Issue by IbuprofenZ** [chatchat-space/Langchain-Chatchat#4920]
**如何将api改为 "http://0.0.0.0:7861/v1"样式的**
如标题，我的网页只能传入标准的openai格式的api，就是/v1/chat/completions的，但现在是chat/chat/completions。
请问各位大佬我如何修改掉他。

在此之前我尝试了一下，ru'guo如果不加tool_input参数，可以返回信息，但是LLM本身的回答，并未结合数据库：
![image](https://github.com/user-attachments/assets/b8570c29-a332-4410-98c9-94aff59b26ee)
![image](https://github.com/user-attachments/assets/30dd4065-0c30-41eb-bd58-8cbb445b7b4f)

加上之后，就会报错：
![b833edb1c866bb62662b1b3681012ba](https://github.com/user-attachments/assets/5108e433-b34c-4b49-b3ec-5967cd3eb37b)
![image](https://github.com/user-attachments/assets/8f95934d-4e57-4548-beed-36b38304dc80)

还有就是openai sdk的方式没办法进行知识库问答，应为无法指定数据库：
![image](https://github.com/user-attachments/assets/014ff84b-0a23-4f22-b253-f0b3a3afbb64)

使用RAG接口（/knowledge_base/chat/compleitons）应该是做检索的。并没有通过LLM进行生成。所以无输出内容。

因为我是pip安装的项目，所以找了很久，未发现修改的方法，求大佬帮助！！！

**Comment by liunux4odoo** [comment]
api base url 改成 `http://0.0.0.0:7861/chat`这种就行了。

**Comment by IbuprofenZ** [comment]
> API base URL 改成 这种就行了。`http://0.0.0.0:7861/chat`

您误会了，我是想将http://127.0.0.1:7861/chat/chat/completions 改为http://127.0.0.1:7861/v1/chat/completions，就像2.0版本中的20000/v1这个一样，因为我有一个前端服务只能传入http://127.0.0.1:7861/v1这样的格式

**Comment by IbuprofenZ** [comment]
> > API base URL 改成 这种就行了。`http://0.0.0.0:7861/chat`
> 
> 您误会了，我是想将 http://127.0.0.1:7861/chat/chat/completions 改为 [http://127.0.0.1:7861/v1/chat/completions，就像2.0版本中的20000/v1这个一样，因为我有一个前端服务只能传入 http://127.0.0.1:7861/v1 这样的格式](http://127.0.0.1:7861/v1/chat/completions%EF%BC%8C%E5%B0%B1%E5%83%8F2.0%E7%89%88%E6%9C%AC%E4%B8%AD%E7%9A%8420000/v1%E8%BF%99%E4%B8%AA%E4%B8%80%E6%A0%B7%EF%BC%8C%E5%9B%A0%E4%B8%BA%E6%88%91%E6%9C%89%E4%B8%80%E4%B8%AA%E5%89%8D%E7%AB%AF%E6%9C%8D%E5%8A%A1%E5%8F%AA%E8%83%BD%E4%BC%A0%E5%85%A5http://127.0.0.1:7861/v1%E8%BF%99%E6%A0%B7%E7%9A%84%E6%A0%BC%E5%BC%8F)

**我做了几个尝试：**
1.在使用知识库对话（LLM 自动解析参数）的方式中，使用base_url = "http://127.0.0.1:7861/v1"。将不会解析参数：
![image](https://github.com/user-attachments/assets/84617adf-87fe-407f-beca-b60fb0423322)
使用base_url = "http://127.0.0.1:7861/chat"时，会自动解析。
![image](https://github.com/user-attachments/assets/2bb1a820-8f19-4eae-b47f-e14652e69bec)
2.在使用知识库对话（手动传入参数）的方式中，使用base_url = "http://127.0.0.1:7861/v1"，会直接报错：
| ERROR    | chatchat.server.api_server.openai_routes:get_model_client:61 - failed when request to ('qwen2:7b', 'ollama')
![image](https://github.com/user-attachments/assets/548cb58c-5726-4f96-86f0-5adfd21f5854)
而使用base_url = "http://127.0.0.1:7861/chat"时，没有任何问题。

3.以都是requests请求，openai sdk方式，问题与上面一样，在使用知识库对话（LLM 自动解析参数）的方式中，使用base_url = "http://127.0.0.1:7861/v1"，也不会解析参数：
![image](https://github.com/user-attachments/assets/65581d72-8945-440e-89a9-d38bf733baa9)
使用base_url = "http://127.0.0.1:7861/chat"时，会自动解析。
![image](https://github.com/user-attachments/assets/f954c828-4dd6-496d-8a8f-3d8e866ee027)
2.在使用知识库对话（手动传入参数）的方式中，openai sdk没办法请求，因为无法传入"tool_input":这个参数。
![image](https://github.com/user-attachments/assets/12f808ad-dde1-47ad-9785-57ea44aeb8ae)

在base_url = "http://127.0.0.1:7861/chat"这个base_url 中，知识库问答可以正常使用。
使用base_url = "http://127.0.0.1:7861/v1，只能用来LLM对话，进行知识库对话（LLM 自动解析参数），不会解析参数，结果与LLM对话一致，知识库对话（手动传入参数）无输出，会报错
![image](https://github.com/user-attachments/assets/1ca0d8e4-0379-4c76-aea2-8e450e45b3ba)

所以是否是因为这个(http://127.0.0.1:7861/v1)端口只能用来进行LLM对话，并没有集成其它的，如知识库问答类的功能

**Comment by IbuprofenZ** [comment]
> /v1 只是对模型平台的转发，跟普通 openai 接口没有太大区别。 /chat 是 chatchat 所有功能的统一入口，在兼容 openai 输入输出的基础上增加了很多功能。

了解了，感谢您的解答。
