### ISSUE TITLE
[BUG] Xinference部署bge-base-zh-v1.5进行pdf文本向量化没有使用gpu而是使用cpu

### ISSUE THREAD

**Issue by JohnnieLZ** [chatchat-space/Langchain-Chatchat#4922]
**问题描述 / Problem Description**
在docker环境下Xinference部署bge-base-zh-v1.5进行pdf文本向量化是没有使用gpu而是使用cpu

**复现问题的步骤 / Steps to Reproduce**
ui->知识库管理->上传pdf->添加文件到知识库

**实际结果 / Actual Result**
系统奔溃重启，使用cpu进行量化,没有使用GPU
<img width="2507" alt="image" src="https://github.com/user-attachments/assets/0939ae15-2eb2-48c9-a828-d96130761dbb">

**环境信息 / Environment Information**
<img width="883" alt="image" src="https://github.com/user-attachments/assets/de888d07-63d0-4f4e-9baa-308066b83f31">
<img width="577" alt="image" src="https://github.com/user-attachments/assets/9a5ce9f6-5e22-4f65-bb23-1325752cf625">
<img width="1592" alt="image" src="https://github.com/user-attachments/assets/4791d7e6-b165-44dc-b100-5414e28b9dde">

**Comment by JohnnieLZ** [comment]
<img width="1156" alt="image" src="https://github.com/user-attachments/assets/fa0bc584-3b27-46ea-96a4-2b36a46f23f7">
使用docker 怎么使用rapidocr_paddle gpu版本

**Comment by liunux4odoo** [comment]
duplicate of #4819
