### ISSUE TITLE
[BUG] 不能用按钮跳转页面 / Can't use buttons to jump to other pages

### ISSUE THREAD

**Issue by naturalRules** [chatchat-space/Langchain-Chatchat#4926]
**问题描述 / Problem Description**
怎么用按钮跳转页面，而不是通过导航栏跳转，我用按钮跳转页面后原页面没有消失。

**复现问题的步骤 / Steps to Reproduce**
![image](https://github.com/user-attachments/assets/9a1bba8f-e519-4f5b-8a60-0db79a0c597e)

**预期的结果 / Expected Result**
在页面里点击按钮跳转页面

**实际结果 / Actual Result**
跳转后原页面没有消失，点一下新页面元素后新页面消失回到原页面。

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：源码部署
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：ONEAPI
- Python 版本 / Python version: 3.11

**Comment by liunux4odoo** [comment]
chatchat 无关问题
