### ISSUE TITLE
[BUG] chroma作为向量库按教程执行chatchat kb -r报错

### ISSUE THREAD

**Issue by arbitraryking** [chatchat-space/Langchain-Chatchat#4930]
**问题描述 / Problem Description**
使用chroma作为向量库按教程执行chatchat kb -r
报错2024-09-09 10:34:03.183 | ERROR    | chatchat.init_database:worker:61 - Collection e55dbf10-399b-4539-853e-1db779402e9f does not exist.

**复现问题的步骤 / Steps to Reproduce**
1. 添加自己的txt测试文档，执行chatchat init
2. 修改kb_settings.yaml设置向量库为chromadb
3. 执行chatchat kb -r
4. 问题出现 
```
正在将 samples/test_files/boss.txt 添加到向量库，共包含45条文档
2024-09-09 10:34:03.183 | ERROR    | chatchat.init_database:worker:61 - Collection e55dbf10-399b-4539-853e-1db779402e9f does not exist.
```

**预期的结果 / Expected Result**
```正在将 samples/test_files/boss.txt 添加到向量库，共包含45条文档

----------------------------------------------------------------------------------------------------
知识库名称      ：samples
知识库类型      ：chromadb
向量模型：      ：bge-large-zh-v1.5
文件总数量      ：1
入库文件数      ：1
知识条目数      ：45
用时            ：0:01:06.517545
----------------------------------------------------------------------------------------------------

总计用时        ：0:01:06.538547
```
**实际结果 / Actual Result**
```
正在将 samples/test_files/boss.txt 添加到向量库，共包含45条文档
2024-09-09 10:34:03.183 | ERROR    | chatchat.init_database:worker:61 - Collection e55dbf10-399b-4539-853e-1db779402e9f does not exist.
```

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi 安装
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）： Oneapi
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-PLUS
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： chroma
- 操作系统及版本 / Operating system and version: Windows10
- Python 版本 / Python version: 3.10.13
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
本地调试定位问题为chatchat\server\knowledge_base\migrate.py中调用子类chatchat\server\knowledge_base\kb_service\chromadb_kb_service.py中删除了原来初始创建的collection
```
#migrate.py
# 清除向量库，从本地文件重建
if mode == "recreate_vs":
    kb.clear_vs()
    kb.create_kb()
    kb_files = file_to_kbfile(kb_name, list_files_from_folder(kb_name))
    result = files2vs(kb_name, kb_files)
    kb.save_vector_store()
```

```
#chromadb_kb_service.py
def do_clear_vs(self):
 # Clearing the vector store might be equivalent to dropping and recreating the collection
    self.do_drop_kb()
```
添加重新创建collection后运行正常
```
#chromadb_kb_service.py
def do_clear_vs(self):
 # Clearing the vector store might be equivalent to dropping and recreating the collection
    self.do_drop_kb()
    collection = self.client.get_or_create_collection(self.kb_name)
    self._load_chroma()
```

**Comment by liunux4odoo** [comment]
感谢反馈，欢迎发个PR。
