### ISSUE TITLE
新增或删除api接口没有作用~~~

### ISSUE THREAD

**Issue by Alan-zhong** [chatchat-space/Langchain-Chatchat#4933]
![image](https://github.com/user-attachments/assets/a06de96e-ea1b-4a4e-a963-95cb86c3cbb7)
![image](https://github.com/user-attachments/assets/30627bcb-4399-4fcf-b112-0a241e17728a)

w为什么我注释掉已有或者新增路由，接口文档没有任何变换啊？？？？

**Comment by yuanhuachao** [comment]
+1

**Comment by liunux4odoo** [comment]
chatchat 无关问题。
