### ISSUE TITLE
[BUG] 无法正常渲染公式

### ISSUE THREAD

**Issue by TongaoY** [chatchat-space/Langchain-Chatchat#4935]
**问题描述 / Problem Description**:无法正常渲染公式
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
使用微调的glm4-9b回答问题时无法正常渲染公式

电解水反应的化学方程式为： [ 2H_2O(l) \rightarrow 2H_2(g) + O_2(g) ] 这表明每电解2摩尔的水，可以生成2摩尔的氢气。

计算电解所需电量： 根据化学方程式，电解1摩尔的水需要转移4个电子（即1个法拉第电荷，96500库仑）。 [ 1 \text{mol} , H_2O \rightarrow 2 \text{mol} , H_2 ] [ 1 \text{mol} , H_2 \text{(需要) \approx 2 \times 96500 \text{库仑} ] 所以，电解1摩尔水所需的电量约为2 × 96500库仑。

转换为千瓦时（kWh）： 1千瓦时（kWh）等于1000瓦时，而1瓦时等于1库仑乘以电荷的元素电荷（1库仑=1伏特×1安培×1秒）。 [ 1 \text{kWh} = 1000 \text{W} \times \frac{1 \text{h}}{3600 \text{s}} ] [ 1 \text{kWh} = \frac{1000 \times 3600 \text{J}}{1 \times 1000 \text{J}} ] [ 1 \text{kWh} = 3.6 \times 10^3 \text{J} ] 所以，电解1摩尔水所需的电能约为： [ 2 \times 96500 \text{库仑} \times \frac{1 \text{J}}{1 \text{库仑}} \times \frac{1 \text{kWh}}{3.6 \times 10^3 \text{J}} ] [ \approx 2.7 \text{kWh} ] 因此，电解1摩尔水所需的电能约为2.7千瓦时。

**环境信息 / Environment Information**
- Langchain-Chatchat 版本：0.3.1 
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi 安装 / Deployment method (pypi installation / dev deployment / docker deployment): pypi installation
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference / Model serve method（Xinference / Ollama / OpenAI API, etc.): Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B 
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss 
- 操作系统及版本 / Operating system and version: Linux
- Python 版本 / Python version: 3.8
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU 
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by liunux4odoo** [comment]
现在没有特别好的办法，官方markdown不支持，有个第三方插件 streamlit-markdown 支持，但一方面效果不稳定，另一方面它不支持新版 streamlit。

**Comment by liunux4odoo** [comment]
dev 版已经通过 streamlit-markdown 实现了公式渲染功能，在 basic_settings 里启用配置即可，欢迎测试。
