### ISSUE TITLE
[FEATURE] 如何实现只匹配下文，而不要上文的结果

### ISSUE THREAD

**Issue by xxcoco763** [chatchat-space/Langchain-Chatchat#494]
在构建自己的知识库时，主要采用问答对的形式，那么也就是我需要的回答是在我的问题下面的内容，但是目前设置了chunk_size的值以后匹配的是上下文的内容，但我实际并不需要上文的。为了实现更完整的展示下面的答案，我只能调大chunk_size的值，但实际上上文的一半内容都是我不需要的。也就是扔了一半没用的东西给prompt，在faiss.py中我也没找到这块的一些描述，请问该如何进行修改呢？

**Comment by xxcoco763** [comment]
求求各位gg，会的人可以帮忙解释一下吗！

**Comment by mottc** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/blob/8d669cdb4c113b865e644a6ad1ea14ad080708f9/chains/local_doc_qa.py#L107
最简单的方法是将这一行改为 `for l in [i + k]: `

**Comment by xxcoco763** [comment]
谢谢gg，解决了，真的很牛！
