### ISSUE TITLE
基于faiss做批量向量化的时候，中间文件处理过程中，数据可以不落盘吗？

### ISSUE THREAD

**Issue by AlexSu1108** [chatchat-space/Langchain-Chatchat#4940]
我使用的数据库是faiss-cpu，embedding model是bge-large，langchain chatchat的版本是0.3.1
我理解faiss数据库每次读取文件向量化的时候，应该每次都要落盘的吧？
这就会导致，如果有一个batch的新数据在content文件夹，每个文件的向量化都要从磁盘上读取一次全量的faiss数据库文件，这会严重影响性能，会使得向量化的速度随着数据库的大小的增加变得越来越慢
所以我想知道，是否可以修改现有的代码，使得我不是每次向量化的都要落盘再读取，而是保存在内存中，直到一个batch向量化完成之后才落盘一次。

感谢您的回复。谢谢！

**Comment by liunux4odoo** [comment]
现在默认以 upload_docs 接口为一个保存周期，如果你要多次调用接口后再统一保存，可以加上 `not_refresh_vs_cache=True` 不保存文件，最后一次设为 False 即可。
