### ISSUE TITLE
知识库回答没有内容，但是有匹配结果

### ISSUE THREAD

**Issue by wzh28x** [chatchat-space/Langchain-Chatchat#4942]
**问题描述 / Problem Description**
知识库回答没有内容，但是有匹配结果
![企业微信截图_17261280818401](https://github.com/user-attachments/assets/21288548-8566-44ba-a94d-254f06f9c5f8)
![企业微信截图_17261281058838](https://github.com/user-attachments/assets/c9c206e9-6022-40ad-85ca-9e0d2e6a152a)

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：(例如：0.3.1 或 commit 123456) / Langchain-Chatchat version / commit number: (e.g., 0.3.1 or commit 123456)
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi 安装 / Deployment method (pypi installation / dev deployment / docker deployment): pypi installation
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference / Model serve method（Xinference / Ollama / OpenAI API, etc.): Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B / LLM used (GLM-4-9B / Qwen2-7B-Instruct, etc.): GLM-4-9B
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 / Embedding model used (bge-large-zh-v1.5 / m3e-base, etc.): bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: MacOS
- Python 版本 / Python version: 3.8
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU 
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by SuperAZHE** [comment]
我也遇到這個問題了，而且發現問問題的方式不同，結果有時候會出來，有時候不會出來，只有引用。蹲一個解決方案。。。

**Comment by guoguo1314** [comment]
怎么样，老哥，解决了吗？

**Comment by wzh28x** [comment]
> 怎么样，老哥，解决了吗？

没有哦

**Comment by wzh28x** [comment]
> 我也遇到這個問題了，而且發現問問題的方式不同，結果有時候會出來，有時候不會出來，只有引用。蹲一個解決方案。。。

我基本就没有结果

**Comment by guoguo1314** [comment]
我使用的qwen2:1.5，embedding是quentinz/bge-large-zh-v1.5:latest，默认知识库，目前是乱回答状态（右上角有个runing，它停了就出来了）。

**Comment by SuperAZHE** [comment]
> 我使用的qwen2:1.5，embedding是quentinz/bge-large-zh-v1.5:latest，默认知识库，目前是乱回答状态（右上角有个runing，它停了就出来了）。

我换成了qwen2:7b，ollama环境的，效果好多了，”无法回答“的概率低了点，但还是有挺多乱回的
