### ISSUE TITLE
运行项目后，想要自己写一个前端调用接口服务，为什么使用vscode调试代码，打印不出变量的值啊，有大佬知道怎么解决吗？谢谢

### ISSUE THREAD

**Issue by azhe1234** [chatchat-space/Langchain-Chatchat#4943]
![image](https://github.com/user-attachments/assets/da83a8ed-be98-47b5-978b-aefd17a05110)
![image](https://github.com/user-attachments/assets/c4ccfb7e-56a8-467f-9ae1-811bbd3d2acb)
控制台没有显示打印的变量值

**Comment by SuperAZHE** [comment]
换成用logger.info()函数来打印一下

**Comment by liunux4odoo** [comment]
chatchat 无关问题。
