### ISSUE TITLE
会话时切换模型

### ISSUE THREAD

**Issue by gzGRQup** [chatchat-space/Langchain-Chatchat#4945]
使用会话功能时切换模型时，需要在本地的Xinference上同时运行这几个所需模型吗？还是Xinference只在同一时刻运行单一一个模型，需要切换时，关掉原先模型，然后启动新的模型呢？
![question](https://github.com/user-attachments/assets/571c668e-2022-417b-9ae8-7002226bd36f)

**Comment by 948024326** [comment]
请问解决了嘛？  我想的是在model_settings.yaml里面的list里面把想注册的模型都写进去， 然后调用会话的时候有一个模型初始化的函数去注册， 应该项目是可以实现这个需求

**Comment by liunux4odoo** [comment]
chatchat 从 0.3 版本开始不再自行加载模型，是以 API 形式接入，你必须确保你配置的模型是可访问的。
