### ISSUE TITLE
今天使用conda安装最新环境后，chatchat init 运行不了。

### ISSUE THREAD

**Issue by jujulike** [chatchat-space/Langchain-Chatchat#4946]
(G:\.conda\langchain) D:\leidian\Langchain-Chatchat>chatchat
usage: chatchat.exe [-h] {config,chat} ...

positional arguments:
  {config,chat}
    config       config platform secret key
    chat         chat in terminal

options:
  -h, --help     show this help message and exit

(G:\.conda\langchain) D:\leidian\Langchain-Chatchat>chatchat -h
usage: chatchat.exe [-h] {config,chat} ...

positional arguments:
  {config,chat}
    config       config platform secret key
    chat         chat in terminal

options:
  -h, --help     show this help message and exit

(G:\.conda\langchain) D:\leidian\Langchain-Chatchat>chatchat init
usage: chatchat.exe [-h] {config,chat} ...
chatchat.exe: error: argument {config,chat}: invalid choice: 'init' (choose from 'config', 'chat')

**Comment by SuperAZHE** [comment]
你安装的是哪一版的软件，release的，还是源码安装的？

**Comment by jujulike** [comment]
直接git clone

**Comment by SuperAZHE** [comment]
我在我的anaconda环境下试了一下,直接gitclone源码，windows环境下没有chatchat这个可执行文件。
然后按照https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md这个步骤
直接`pip install -e .`
然后
```
cd libs/chatchat-server
python chatchat/cli.py init
```
这样子是可以的，
![屏幕截图 2024-09-13 131735](https://github.com/user-attachments/assets/d4a4f1f9-4053-4131-9669-0941a71fec22)

**Comment by jujulike** [comment]
按照如下步骤：

```
git clone https://github.com/chatchat-space/Langchain-Chatchat.git
conda create -n langchain3 python==3.11
conda activate langchain3

pip install langchain-chatchat -U -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install langchain-chatchat[xinference] -U -i https://pypi.tuna.tsinghua.edu.cn/simple

pip install faiss-cpu==1.7.4 -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install xinference_client faiss-gpu “unstructured[pdf]” -i https://pypi.tuna.tsinghua.edu.cn/simple

chatchat --help 命令行帮助
chatchat init
```

执行chatchat --help：
```
(G:\.conda\langchain3) G:\down\Langchain3>chatchat --help
usage: chatchat.exe [-h] {config,chat} ...

positional arguments:
  {config,chat}
    config       config platform secret key
    chat         chat in terminal

options:
  -h, --help     show this help message and exit
```

执行chatchat init：

options:
  -h, --help     show this help message and exit

```
(G:\.conda\langchain3) G:\down\Langchain3>chatchat  init
usage: chatchat.exe [-h] {config,chat} ...
chatchat.exe: error: argument {config,chat}: invalid choice: 'init' (choose from 'config', 'chat')
```

**Comment by jujulike** [comment]
使用源码部署：
[https://github.com/chatchat-space/Langchain-Chatchat/blob/master/README.md](url)
里面的pip安装部署

**Comment by SuperAZHE** [comment]
从你的log上看，好像是你的chatchat命令没有init的选项，只有config和chat的选项。你可以试试`where chatchat`查看一下是不是路径有问题。
另外，我参考你的命令
`conda create -n langchain3 python==3.11
conda activate langchain3

pip install langchain-chatchat -U -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install langchain-chatchat[xinference] -U -i https://pypi.tuna.tsinghua.edu.cn/simple`

这样是可以chatchat init的
![Uploading 屏幕截图 2024-09-13 141730.png…]()

**Comment by jujulike** [comment]
是的，正常应该是可以的，因为我之前是可以的，但是今天突然就不行了

**Comment by jujulike** [comment]
where chatchat 后路劲是不是应该在conda环境中呢？我看我的在c盘，并不在新建的conda环境中

**Comment by jujulike** [comment]
我重新卸载安装python环境后，重新按照我的步骤运行，以可以正常使用。暂时不明确为何出现这种情况，是安装的时候包不全还是如何，也未可知。
