### ISSUE TITLE
请问chatchat可以实现copilot类似的智能副驾模式吗，通过交互式的方式引导用户生成代码

### ISSUE THREAD

**Issue by 1490113799** [chatchat-space/Langchain-Chatchat#4951]
请问chatchat可以实现copilot类似的智能副驾模式吗，通过交互式的方式引导用户生成代码

**Comment by liunux4odoo** [comment]
现在的知识库问答接口是 openai 兼容的，详见 api.md
你可以把相关代码加到知识库，然后任何支持自定义模型的copilot插件指向这个知识库的url即可。

**Comment by imClumsyPanda** [comment]
@1490113799 PyCharm+CodeGPT 或者 VSCode+continue.dev

**Comment by imClumsyPanda** [comment]
@1490113799 这方面还不太了解

**Comment by 1490113799** [comment]
好的谢谢
