### ISSUE TITLE
[BUG] 想问一下8501界面上设置按钮里面的SystemMessage在API请求时，在哪设置

### ISSUE THREAD

**Issue by littleseal** [chatchat-space/Langchain-Chatchat#4954]
![WechatIMG261](https://github.com/user-attachments/assets/41f02f68-088e-49f6-b6af-05f36e830ae1)

在8501访问时，效果很好。

用API访问时，如果拼接在body的messages或者history里面（role：system，content：xxxx），效果并不如8501。

所以想问一下，这个是不是有特别传值的地方

**Comment by liunux4odoo** [comment]
没有，webui 也是拼接到 messages 的。你可以把你 API 请求的参数贴出来看看。
