### ISSUE TITLE
[BUG] 使用xinference框架调用Agent出现问题，使用ollama则不会

### ISSUE THREAD

**Issue by southkorea2013** [chatchat-space/Langchain-Chatchat#4956]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**

**预期的结果 / Expected Result**
正常输出指定城市的天气情况

**实际结果 / Actual Result**
ERROR    | chatchat.server.utils:wrap_done:46 - IndexError: Caught exception: list index out of range

Ollama执行的结果：
<img width="847" alt="image" src="https://github.com/user-attachments/assets/f1a7055b-9742-42a0-ade5-7f123bc821d8">

Xinference执行结果：
<img width="962" alt="image" src="https://github.com/user-attachments/assets/52c74cef-789a-415f-966a-0491e8385e73">

2024-09-18 15:59:10,053 httpx        32993 INFO     HTTP Request: POST http://127.0.0.1:9997/v1/chat/completions "HTTP/1.1 200 OK"

Thought: The user wants to know the current weather in Shenzhen. I will use the `amap_weather` tool to get this information.

Action:
```json
{
  "action": "amap_weather",
  "action_input": {
    "city": "Shenzhen"
  }
}
```2024-09-18 15:59:13.460 | ERROR    | chatchat.server.utils:wrap_done:46 - IndexError: Caught exception: list index out of range




**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：(例如：0.3.1 或 commit 123456) / Langchain-Chatchat version / commit number: (e.g., 0.3.1 or commit 123456)
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi 安装 
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference /
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B / Qwen2-7B-Instruct
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss / Vector library used (faiss, milvus, pg_vector, etc.): faiss
- 操作系统及版本 / Operating system and version: MacOS
- Python 版本 / Python version: 3.11
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU 
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by 948024326** [comment]
像是 提取参数导致不匹配导致的问题   建议debug看下
