### ISSUE TITLE
Agent 框架的tool不支持2个参数以上的输入

### ISSUE THREAD

**Issue by blackwhites** [chatchat-space/Langchain-Chatchat#4960]
用的是v 2.10版本
我定义了个tool
'''
from pydantic import BaseModel, Field

class FlightTimeInput(BaseModel):
    flight_number: str = Field(description="航班号")
    flight_instance: str = Field(description="航班架次")

def search_flighttime(flight_number str,flight_instance: str):
    return "6:00 PM"  # 返回硬编码的时间
    
tools_select.py 也加载这个tool
  Tool.from_function(
        func=search_flighttime,
        name="search_flighttime",
        description="use this tools to search flight time",
        args_schema=FlightTimeInput,
    ),

我的问题是‘航班号是5航班架次是6的时间是啥？后台报错如下
    input_args.validate({key_: tool_input})
  File "pydantic/main.py", line 711, in pydantic.main.BaseModel.validate
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FlightTimeInput
flight_instance
  field required (type=value_error.missing)
2024-09-20 20:40:52,117 - utils.py[line:40] - ERROR: ValidationError: Caught exception: 1 validation error for FlightTimeInput
flight_instance
  field required (type=value_error.missing)
  
  
  如果只支持1个参数是可以工作的，有没有人遇到过怎么支持2个参数？

**Comment by 948024326** [comment]
建议是   用一个参数去放你所有想提取参数的值 例如：    your_args: Any,  
 然后在函数中再去解析你的这两个或多个参数

**Comment by liunux4odoo** [comment]
0.2.x 版本已经停止开发，其 Agent 只是最简单的试验品。
