### ISSUE TITLE
请教知识库怎么实现pg添加自定义字段

### ISSUE THREAD

**Issue by Longleaves** [chatchat-space/Langchain-Chatchat#4964]
想请教：在新建知识库时，怎样在pg中增加自定义字段？
或者在哪里能看到langchain_pg_collection和langchain_pg_embedding这两个表初始化的过程？
希望大佬们慷慨相助，感谢！

**Comment by liunux4odoo** [comment]
langchain的向量库基本都不支持自定义字段，要么自己写，要么放到metadata里做过滤。
