### ISSUE TITLE
[BUG] 知识库构建时批量文件上传错误，显示bad request

### ISSUE THREAD

**Issue by AibibulaAtawula** [chatchat-space/Langchain-Chatchat#4967]
知识库构建时批量文件（大概1200个txt文件）上传时，显示bad request 404错误。

**Comment by azhe1234** [comment]
> 知识库构建时批量文件（大概1200个txt文件）上传时，显示bad request 404错误。

您好，可以和你请教个问题吗？我想要从本地搭建的前端，调用/knowledge_base/update_docs接口，上传文件到服务器上，但是报错显示chatchat.server.knowledge_base.utils:files2docs_in_thread_file2docs:419 - FileNotFoundError: 从文件 samples/2024925.txt 加载文档时出错：[Errno 2] No such file or directory: '/home/lxuekun/Langchain-Chatchat/libs/chatchat-server/chatchat/chatchat_data/data/knowledge_base/samples/content/2024925.txt'
但是接口显示调用成功，INFO: 127.0.0.1:50350 - "POST /knowledge_base/update_docs HTTP/1.1" 200 OK
请问您知道怎么解决吗，谢谢！
