### ISSUE TITLE
你好，问一下，我调用api.py部署，为什么用ip加端口可以使用postman调用，而改为域名使用postman无法调用？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#497]
![5ufBSWxLyF](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109277248/70e2fbac-5699-48d0-b0d1-3dc84fd042c2)
这个可以访问！

下面这个域名无法访问：
![ILSXvKVNm6](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109277248/086f7fc5-ea94-43bc-85f3-5b08312049fa)

**Comment by earthxx** [comment]
你用的这是哪个调试工具？

**Comment by cristianohello** [comment]
@earthxx 
postman

**Comment by a113ert222** [comment]
您好，请问解决了吗
