### ISSUE TITLE
上传文件到知识库失败。

### ISSUE THREAD

**Issue by azhe1234** [chatchat-space/Langchain-Chatchat#4972]
**问题描述 / Problem Description**
我想要从本地搭建的前端，调用/knowledge_base/update_docs接口，上传文件到服务器上，但是报错显示chatchat.server.knowledge_base.utils:files2docs_in_thread_file2docs:419 - FileNotFoundError: 从文件 samples/2024925.txt 加载文档时出错：[Errno 2] No such file or directory: '/home/lxuekun/Langchain-Chatchat/libs/chatchat-server/chatchat/chatchat_data/data/knowledge_base/samples/content/2024925.txt'
但是接口显示调用成功，INFO: 127.0.0.1:50350 - "POST /knowledge_base/update_docs HTTP/1.1" 200 OK
怎么解决？
**复现问题的步骤 / Steps to Reproduce**
1. 调用/knowledge_base/update_docs 接口成功，但是从本地上传文件到服务器失败，显示FileNotFoundError: 从文件 samples/2024925.txt 加载文档时出错：[Errno 2] No such file or directory: '/home/lxuekun/Langchain-Chatchat/libs/chatchat-server/chatchat/chatchat_data/data/knowledge_base/samples/content/2024925.txt'

**预期的结果 / Expected Result**
文件上传成功

**实际结果 / Actual Result**
chatchat.server.knowledge_base.utils:files2docs_in_thread_file2docs:419 - FileNotFoundError: 从文件 samples/2024925.txt 加载文档时出错：[Errno 2] No such file or directory: '/home/lxuekun/Langchain-Chatchat/libs/chatchat-server/chatchat/chatchat_data/data/knowledge_base/samples/content/2024925.txt'

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号： 0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：源码部署
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：Qwen2-7B-Instruct
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: ubuntu
- Python 版本 / Python version: 3.10
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） /  GPU 
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by SuperAZHE** [comment]
看你的报错是没找到对应的文件，可以检查一下文件路径是否正确

**Comment by azhe1234** [comment]
> 看你的报错是没找到对应的文件，可以检查一下文件路径是否正确

解决了，调用api时，请求参数格式有误，谢谢！
