### ISSUE TITLE
[BUG] 简洁阐述问题 / chatchat-config指令无法使用

### ISSUE THREAD

**Issue by 2475754960** [chatchat-space/Langchain-Chatchat#4973]
输入：chatchat-config basic --help
报错：chatchat-config : 无法将“chatchat-config”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ chatchat-config basic --help
+ ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (chatchat-config:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by liunux4odoo** [comment]
请先看下 readme 和部署文档。
