### ISSUE TITLE
[BUG] 接入在线 Embedding 时知识库问答报错

### ISSUE THREAD

**Issue by toulzx** [chatchat-space/Langchain-Chatchat#4979]
#### 问题描述与复现
[源码安装部署 chatchat](https://github.com/chatchat-space/Langchain-Chatchat/blob/master/docs/contributing/README_dev.md)，使用 one-api 接入在线 Embedding （详见 Discussion https://github.com/chatchat-space/Langchain-Chatchat/discussions/4977 中的描述）。
在 model_setting.yaml 设置默认 Embedding 为**在线模型**时，`chatchat start -a` 启动后，知识库问答模式，提问**报错** [chat.completions.create()](https://platform.openai.com/docs/guides/chat-completions) 返回空的 `ChatCompletionChunk`，错误位置为：
https://github.com/chatchat-space/Langchain-Chatchat/blob/fde56046011c9eff4e46baadb9e4513ec273d070/libs/chatchat-server/chatchat/webui_pages/kb_chat.py#L225
打印日志显示，该处变量 `d` 内容为：
```
ChatCompletionChunk(id=None, choices=None, created=None, model=None, object=None, service_tier=None, system_fingerprint=None, usage=None, error='')
````

但当 model_setting.yaml 设置默认 Embedding 为**本地模型**时，`chatchat start -a` 启动后，知识库问答模式，提问可**正常**得到回答，打印日志显示，该处变量 `d` 内容为：
```
ChatCompletionChunk(id='chatxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', choices=[Choice(delta=ChoiceDelta(content='', function_call=None, role=None, tool_calls=[]), finish_reason=None, index=None, logprobs=None, role='assistant')], created=1234567890, model='Doubao-lite-32k', object='chat.completion.chunk', service_tier=None, system_fingerprint=None, usage=None, status=None, message_type=1, message_id=None, is_ref=False, 
docs=[ '出处 [1] [test_files/langchain-ChatGLM_open.csv](http://127.0.0.1:8861/knowledge_base/download_doc?knowledge_base_name=samples&file_name=test_files%2Flangchain-ChatGLM_open.csv) \n\n......\n\n', "出处 [2] ......", '出处 [3] ......' ])
```

Chat Completion 的报错显然与 Embedding 无关，该处并非问题根源，问题根源大概率是 Embedding 没有参与导致的。
PS：chatchat 生成的错误日志见最后一部分。

#### 问题触发条件
知识库问答模式。
`chatchat start -a` 启动后，使用 model_setting.yaml 设置的 Embedding 模型。
- 当首次调用的 Embedding 为“**在线**模型”：
    1. 测试，**报错**。
    2. 修改model_setting.yaml 设置的 Embedding 模型为“本地模型”（**热切换**），测试，依然**报错**。
- 当首次调用的 Embedding 为“本地模型”：
    1. 测试，**正常**。
    2. 修改 model_setting.yaml 设置的 Embedding 模型为“**在线**模型”（**热切换**），测试，**正常**。

#### 排除 chatchat 之外的问题
1. one-api 正确部署并启动。
2. one-api 可以正常访问厂商的 Embedding API。
3. 本地可以正常向 one-api 发出请求，调用  Embedding API，并取得向量化结果。
详见 https://github.com/chatchat-space/Langchain-Chatchat/discussions/4977 中的描述。
5. “model_setting.yaml 中 Embedding 模型由’本地模型‘热切换为’在线模型‘后，正常运行”，这里可以确认热切换是成功的，已通过厂商控制台查到相关 embedding 模型的使用开销。

#### 额外的探索

继续观察日志，可以发现在 server/knowledge_base/kb_doc_api.py/search_docs() 中：
https://github.com/chatchat-space/Langchain-Chatchat/blob/fde56046011c9eff4e46baadb9e4513ec273d070/libs/chatchat-server/chatchat/server/knowledge_base/kb_doc_api.py#L71-L73
由于缺少 Embedding 参与，log 显示，返回的 `docs` 拿不到。它的调用链如下所示。
-> chatchat/server/knowledge_base/kb_service/base.py/[search_docs()](https://github.com/chatchat-space/Langchain-Chatchat/blob/fde56046011c9eff4e46baadb9e4513ec273d070/libs/chatchat-server/chatchat/server/knowledge_base/kb_service/base.py#L210)
-> server/knowledge_base/kb_service/faiss_kb_service.py/[do_search()](https://github.com/chatchat-space/Langchain-Chatchat/blob/fde56046011c9eff4e46baadb9e4513ec273d070/libs/chatchat-server/chatchat/server/knowledge_base/kb_service/faiss_kb_service.py#L72-L79 )
-> server/file_rag/retrievers/[ensemble.py](https://github.com/chatchat-space/Langchain-Chatchat/blob/fde56046011c9eff4e46baadb9e4513ec273d070/libs/chatchat-server/chatchat/server/file_rag/retrievers/ensemble.py#L48)，调用的 `retriever.get_relevant_documents` 是来自 langchain-core 的实现。
仍无法解决问题...

#### 环境信息
- Langchain-Chatchat 版本：0.3.1.3
- 部署方式：源码安装部署/dev deployment
- 使用的模型推理框架：OpenAI API
- 使用的 LLM 模型：Qwen2-Instruct（xinference）、Doubao-lite-4k（one-api）、GLM-4-flash（one-api）
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5（xinference）、Doubao-embedding（one-api）、zhipu-embedding-3（one-api）
- 使用的向量库类型：faiss 
- 操作系统及版本: Ubuntu
- Python 版本 / Python version: 3.9
- 推理使用的硬件： GPU 

#### 报错日志
```
2024-09-27 17:44:54.700 | ERROR    | chatchat.server.chat.kb_chat:knowledge_base_chat_iterator:231 - error in knowledge chat: 
2024-09-27 17:44:54.704 Uncaught app exception
Traceback (most recent call last):
  File "/anaconda3/envs/chatchat/lib/python3.9/site-packages/pydantic/main.py", line 803, in __getattr__
    return pydantic_extra[item]
KeyError: 'docs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Langchain-Chatchat/libs/chatchat-server/chatchat/webui_pages/kb_chat.py", line 233, in kb_chat
    chat_box.update_msg("\n\n".join(d.docs), element_index=0, streaming=False, state="complete")
  File "/anaconda3/envs/chatchat/lib/python3.9/site-packages/pydantic/main.py", line 805, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'ChatCompletionChunk' object has no attribute 'docs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/envs/chatchat/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Langchain-Chatchat/libs/chatchat-server/chatchat/webui.py", line 72, in <module>
    kb_chat(api=api)
  File "/Langchain-Chatchat/libs/chatchat-server/chatchat/webui_pages/kb_chat.py", line 244, in kb_chat
    st.error(e.body)
AttributeError: 'AttributeError' object has no attribute 'body'
```

**Comment by liunux4odoo** [comment]
chatchat 的知识库是和 embedding 模型绑定的，你用哪个模型创建的知识库，那么就得使用哪个模型去检索。知识库创建后就不要手动指定 embedding 模型了，程序会自动识别。如果找不到同样的模型，知识库返回就会报错。

**Comment by ruthy-wei** [comment]
你好，请问你使用one-api接入时，如何修改默认的Embedding模型为本地模型的？由于我在one-api上并没有部署在线模型“bge-large-zh-v1.5”，但是使用one-api接入，好像默认使用就是在线的Embedding 模型，于是报错：
Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised InternalServerError: Error code: 503 - {'error': {'message': '当前分组 default 下对于模型 bge-large-zh-v1.5 无可用渠道 (request id: 2024102411220616042194221974346)', 'type': 'one_api_error'}}.
Retrying chatchat.server.localai_embeddings.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised InternalServerError: Error code: 503 - {'error': {'message': '当前分组 default 下对于模型 bge-large-zh-v1.5 无可用渠道 (request id: 2024102411221374633957723601608)', 'type': 'one_api_error'}}.
2024-10-24 11:22:21.098 | ERROR    | chatchat.server.utils:run_in_thread_pool:733 - error in sub thread: Error code: 503 - {'error': {'message': '当前分组 default 下对于模型 bge-large-zh-v1.5 无可用渠道 (request id: 202410241122215626172017487519)', 'type': 'one_api_error'}}
2024-10-24 11:22:21.183 | ERROR    | chatchat.server.knowledge_base.kb_cache.faiss_cache:load_vector_store:140 - list index out of range
2024-10-24 11:22:21.184 | ERROR    | chatchat.init_database:worker:61 - 向量库 samples 加载失败。
情况：
1.我的本地模型路径在“chatchat-server/chatchat/data/knowledge_base/samples/vector_store/bge-large-zh-v1.5”；
2.在model_settings.yaml 中设置如下：
# 模型配置项


# 默认选用的 LLM 名称
DEFAULT_LLM_MODEL: GLM-4-0520

# 默认选用的 Embedding 名称
DEFAULT_EMBEDDING_MODEL: bge-large-zh-v1.5

# AgentLM模型的名称 (可以不指定，指定之后就锁定进入Agent之后的Chain的模型，不指定就是 DEFAULT_LLM_MODEL)
Agent_MODEL: ''

# 默认历史对话轮数
HISTORY_LEN: 3

# 大模型最长支持的长度，如果不填写，则使用模型默认的最大长度，如果填写，则为用户设定的最大长度
MAX_TOKENS:

# LLM通用对话参数
TEMPERATURE: 0.7

# 支持的Agent模型
SUPPORT_AGENT_MODELS:
  - qwen1.5-chat
  - openai-api
  - Qwen-2
  - qwen2-instruct
  - gpt-3.5-turbo
  - gpt-4o

# LLM模型配置，包括了不同模态初始化参数。
# `model` 如果留空则自动使用 DEFAULT_LLM_MODEL
LLM_MODEL_CONFIG:
  preprocess_model:
    model: ''
    temperature: 0.05
    max_tokens: 4096
    history_len: 10
    prompt_name: default
    callbacks: false
  llm_model:
    model: ''
    temperature: 0.9
    max_tokens: 4096
    history_len: 10
    prompt_name: default
    callbacks: true
  action_model:
    model: ''
    temperature: 0.01
    max_tokens: 4096
    history_len: 10
    prompt_name: ChatGLM3
    callbacks: true
  postprocess_model:
    model: ''
    temperature: 0.01
    max_tokens: 4096
    history_len: 10
    prompt_name: default
    callbacks: true
  image_model:
    model: sd-turbo
    size: 256*256
MODEL_PLATFORMS:
  - platform_name: oneapi
    platform_type: oneapi
    api_base_url: http://101.43.121.117:3000/v1
    api_key: sk-XXXXXXXXXXXXXXXX
    api_proxy: ''
    api_concurrencies: 5
    auto_detect_model: false
    llm_models:
      - GLM-4-0520
      - GLM-4-Plus
      - qwen-turbo
      - qwen-plus
      - qwen-max
      - qwen-max-longcontext
      - ERNIE-4.0-8K
      - ERNIE-3.5-8K
      - SparkDesk
    embed_models:
      - bge-large-zh-v1.5
      - m3e
    text2image_models: []
    image2text_models: []
    rerank_models: []
    speech2text_models: []
    text2speech_models: []

**Comment by toulzx** [comment]
@ruthy-wei :
考虑使用本地模型加载框架（Xinference、Ollama...）单独加载 Embedding 模型？README 提到了“从 0.3.0 版本起，Langchain-Chatchat 不再根据用户输入的本地模型路径直接进行模型加载”。
我之前使用的是 Xinference，One API 好像还支持 Ollama 的接口。

**Comment by ruthy-wei** [comment]
嗯嗯，多谢解惑，我现在在one-api平台调用的百度的向量模型“bge-large-zh”能正常使用了

**Comment by 1122414** [comment]
> > chatchat 的知识库是和 embedding 模型绑定的，你用哪个模型创建的知识库，那么就得使用哪个模型去检索。知识库创建后就不要手动指定 embedding 模型了，程序会自动识别。如果找不到同样的模型，知识库返回就会报错。
> 
> 恍然大悟，感谢解答！我来试试

您好，请问这个是怎么解决的嘞
