### ISSUE TITLE
增加线上模型接口后，前端页面没有显示该接口

### ISSUE THREAD

**Issue by MI-cpu-code** [chatchat-space/Langchain-Chatchat#4983]
LLM_MODELS = ["openai-api","chatglm2-6b", "xinghuo-api"]

# AgentLM模型的名称 (可以不指定，指定之后就锁定进入Agent之后的Chain的模型，不指定就是LLM_MODELS[0])
Agent_MODEL = None

# LLM 运行设备。设为"auto"会自动检测，也可手动设定为"cuda","mps","cpu"其中之一。
LLM_DEVICE = "cpu"

# 历史对话轮数
HISTORY_LEN = 3

# 大模型最长支持的长度，如果不填写，则使用模型默认的最大长度，如果填写，则为用户设定的最大长度
MAX_TOKENS = None

# LLM通用对话参数
TEMPERATURE = 0.2
# TOP_P = 0.95 # ChatOpenAI暂不支持该参数

ONLINE_LLM_MODEL = {
    # 线上模型。请在server_config中为每个在线API设置不同的端口

    "openai-api": {
        "model_name": "gpt-4o-mini",
        "api_base_url": "",
        "api_key": "",
        "openai_proxy": ""
    },

**Comment by SagarChandra07** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by liunux4odoo** [comment]
0.2.x 版本已经停止开发，不再接收相关 issue.
