### ISSUE TITLE
如何实现针对指定网址进行智能问答？

### ISSUE THREAD

**Issue by sunnnyu** [chatchat-space/Langchain-Chatchat#4997]
**功能描述 / Feature Description**
想实现在线知识库功能（不是搜索引擎检索）：比如输入某政府网站链接，能够针对该链接中的内容进行智能问答。

**解决的问题 / Problem Solved**
在线知识库智能问答

应该在哪部分添加代码，通过什么逻辑实现这个功能？请各位大佬指导。

**Comment by sunnnyu** [comment]
已实现

**Comment by a898569012** [comment]
请问可以展示一下实现方法吗
