### ISSUE TITLE
启动复制的项目，调用的代码还是原项目代码

### ISSUE THREAD

**Issue by gotothehill** [chatchat-space/Langchain-Chatchat#5009]
为了方便开发测试，将运行成功的项目，复制了一份。同时复制了conda运行环境。
在新的conda环境下，调整复制的项目的代码，然后运行复制的项目，发现调用的代码还是原来的项目。
该修改的路径都在 basic_setting.yaml 里作了相对应的调整。

还是说还需要再重新安装环境？

**Comment by wzhty86** [comment]
这个问题解决了吗？我也碰到了，想到诡异：对修改后的项目代码，拷贝一份再运行，发现运行结果还是原来的

**Comment by gotothehill** [comment]
> 这个问题解决了吗？我也碰到了，相当诡异：对修改后的项目代码，拷贝一份再运行，发现运行结果还是原来的

好像是不能复制环境，我在环境中的 pip list里看到有 Langchain-Chatchat， 指向的是原来的工程。估计得重新安装环境。

**Comment by wzhty86** [comment]
> 好像是不能复制环境，我在环境中的 pip list里看到有 Langchain-Chatchat， 指向的是原来的工程。估计得重新安装环境。

我是重新打docker镜像来安装依赖包的，只是拷贝了Langchain-Chatchat项目代码，发现新修改的代码没有生效？

**Comment by wzhty86** [comment]
> 
> 那就不清楚了，我都是用的源码安装的。你可以开个issue问问

我也是用源码安装的，吧Langchain-ChatChat代码download下来，然后再安装对应的依赖包的
