### ISSUE TITLE
[BUG] 捉个虫，api.py中的stream_chat解析json问题

### ISSUE THREAD

**Issue by zzxs** [chatchat-space/Langchain-Chatchat#501]
**问题描述 / Problem Description**
部署api后，访问/local_doc_qa/stream-chat/{knowledge_base_id}接口时，message中的question不识别并且报错。

捉个虫，在api.py的311行如下
question, history, knowledge_base_id = input_json[""], input_json["history"], input_json["knowledge_base_id"]

应为：
question, history, knowledge_base_id = input_json["question"], input_json["history"], input_json["knowledge_base_id"]

**Comment by exceedzhang** [comment]
有谁出现过类似错误
KeyError: 'history'
如下图所示
<img width="1184" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/4583537/688fa0d1-433d-4d27-8639-f9fe774b7add">

**Comment by zzxs** [comment]
> 有谁出现过类似错误 KeyError: 'history' 如下图所示 <img alt="image" width="1184" src="https://user-images.githubusercontent.com/4583537/243101388-688fa0d1-433d-4d27-8639-f9fe774b7add.png">

访问接口上传的json格式是不是不对？


这是我的
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/ec1ee493-49cc-4b03-9fe5-f233a34693fe)

**Comment by exceedzhang** [comment]
@zzxs 我调试过了，参数都是对的，相关参数已准确获得，就是服务端报错了！程序BUGS问题

<img width="1183" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/4583537/0aa89752-18cc-4970-bdab-e793fc5a6eb7">

我客户端python代码
import json
import asyncio
import websockets

#定义一个函数处理websocket client api调用

async def stream_chat(question):
    async with websockets.connect('ws://region-3.seetacloud.com:16274/local_doc_qa/stream-chat/95007') as websocket:
        print("connected")
        history = [
    [
      "中国燃气",
      "中国燃气股份有限公司"
    ]]
        # Send a message
        message = json.dumps({'question': question, 'history': history, 'knowledge_base_id': '95007'})
        print("sending:", message)
        await websocket.send(message)

        # Receive the response
        message = await websocket.recv()
        print("got response:", message)

if __name__ == '__main__':
    question = "中国燃气详细介绍"
    asyncio.get_event_loop().run_until_complete(stream_chat(question))

谁帮忙可以看看？或者谁调用成功过？谢谢！

**Comment by exceedzhang** [comment]
问题找到了，客户端请求代码的问题！
def stream_chat(url, question,history):
    with connect(url) as websocket:
        print("connected")
        # Send a message
        message = json.dumps({'question': question, 'history': history, 'knowledge_base_id': '95007'})
        print("sending:", message)
        websocket.send(message)

        # Receive the response
        for message in websocket:
            message = websocket.recv()
            print(message)
            # 判断message是否json格式，如果不是json格式保存到buffer变量中，以便以后再处理
            if message.startswith('{"question":'):
                # json分析message格式，将变量保存到history中
                if json.loads(message).get('flag')=="end":
                    break
        print("connect closed")

上面代码可以准确运行，但是服务器端还是报错！主要由于客户端websockets关闭连接时，不影响使用。
<img width="1181" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/4583537/3bdaed45-da9e-4b7a-9c46-c9fc622e2fb9">

**Comment by exceedzhang** [comment]
问题已解决

**Comment by cristianohello** [comment]
@exceedzhang 
你好，怎么解决的？有详细完整的代码吗？感谢
