### ISSUE TITLE
windows本地部署遇到了omp错误

### ISSUE THREAD

**Issue by crossagent** [chatchat-space/Langchain-Chatchat#502]
**问题描述 / Problem Description**
windows部署的时候，运行python cli_demo.py，提示一下错误

OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

**复现问题的步骤 / Steps to Reproduce**
1. windows下创建干净的conda环境
2. 安装使用python cli_demo.py
3. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
正常启动

**实际结果 / Actual Result**
报错后中断

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:win10，win11
- Python 版本 / Python version:3.9.16
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by crossagent** [comment]
不支持windows部署，可以装linux子系统

**Comment by ywancit** [comment]
> **问题描述 / Problem Description** windows部署的时候，运行python cli_demo.py，提示一下错误
> 
> OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized. OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
> 
> **复现问题的步骤 / Steps to Reproduce**
> 
> 1. windows下创建干净的conda环境
> 2. 安装使用python cli_demo.py
> 3. 问题出现 / Problem occurs
> 
> **预期的结果 / Expected Result** 正常启动
> 
> **实际结果 / Actual Result** 报错后中断
> 
> **环境信息 / Environment Information**
> 
> * langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
> * 是否使用 Docker 部署（是/否）：否
> * 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
> * 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
> * 操作系统及版本 / Operating system and version:win10，win11
> * Python 版本 / Python version:3.9.16
> * 其他相关环境信息 / Other relevant environment information:
> 
> **附加信息 / Additional Information** 添加与问题相关的任何其他信息 / Add any other information related to the issue.

我也遇到了，已经解决：在报错的文件开头加上

import os
 
os.environ['KMP_DUPLICATE_LIB_OK']='True'
