### ISSUE TITLE
混合检索中rank-bm25算法检索影响整体检索效果

### ISSUE THREAD

**Issue by jersonal** [chatchat-space/Langchain-Chatchat#5024]
**问题描述 / Problem Description**
目前使用的基于rank-bm25和faiss向量混合检索算法存在很大的误检索，尤其是rank-bm25，基本检索的内容非常离谱，以下有实例。

**复现问题的步骤 / Steps to Reproduce**
使用langchain_community/retrievers/bm25.py
```
class BM25Retriever(BaseRetriever):
    ....
    def _get_relevant_documents(
        self, query: str, *, run_manager: CallbackManagerForRetrieverRun
    ) -> List[Document]:
        processed_query = self.preprocess_func(query)
        return_docs = self.vectorizer.get_top_n(processed_query, self.docs, n=self.k)
        return return_docs
```
**1.对query预处理得到结果：**
processed_query = ['什么', '时候', '可以', '提取', '住房', '公积', '积金', '公积金']；
**2.获取top_k。**
`self.vectorizer.get_top_n(processed_query, self.docs, n=self.k)`
```
def get_top_n(self, query, documents, n=5):
        assert self.corpus_size == len(documents), "The documents given don't match the index corpus!"
        scores = self.get_scores(query)
        top_n = np.argsort(scores)[::-1][:n]
        return [documents[i] for i in top_n]
```
**3.检索到index如下：**
![image](https://github.com/user-attachments/assets/c42eca47-1e32-4022-a303-c4dfe2683907)
**4.补充我们再看一下score的大小分布：**
发现其array的最大值是2.8+，最小值是0，其中也不乏有0.x和1.x
![image](https://github.com/user-attachments/assets/0fac88db-6c28-4b65-97d8-55b46542a79f)
**5.查看20、19、18的内容发现竟然因为“提取”两个字让其score值为2.8+  ！**
![image](https://github.com/user-attachments/assets/1beafc81-7fa5-4c42-b53d-001a95dc7ce0)
**6.查看faiss向量检索**
发现定义了阈值0.7之后，docs返回为空，合理。
更进一步分析faiss的score分布，其score的值也有出现在-0.x的，不知道是否合理。但是检索结果为空没问题。
注：query为：什么时候可以提取住房公积金
知识库为“一种基于RAG的多轮对话处理方法,装置以及设备.pdf”，其内容与文件名相关。
**7.思考SCORE_THRESHOLD: 0.7参数的合理性**
（1）首先rank-bm25并没有使用该阈值，只使用top-k，所以无论如何都会返回top-k个检索结果，即使无任何相关性
（2）faiss向量检索为什么会出现负数？没有再去看源码的计算方法，但应该合理。
（3）建议将混合检索进行优化，一是rank-bm25算法的升级；二是增加SCORE_THRESHOLD的过滤，防止一种检索算法影响全局结果。

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1 
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：源码部署
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5  bge-large-zh-v1.5
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: Ubuntu20.04
- Python 版本 / Python version: 3.10
- 推理使用的硬件（GPU / CPU / MPS / NPU 等）：GPU 
- 其他相关环境信息 / Other relevant environment information：rank-bm25版本0.2.2

**Comment by Yanhuanjin** [comment]
如果用的默认的similarity_search_with_score方法的话，返回的应该是欧几里得距离的度量吧，3应该是挺大一个值表示不相关。

**Comment by 2069348297** [comment]
佬 混合检索代码是自己写的吗 如果不用源码部署的话 可以改吗

**Comment by azhe1234** [comment]
> **问题描述 / Problem Description** 目前使用的基于rank-bm25和faiss向量混合检索算法存在很大的误检索，尤其是rank-bm25，基本检索的内容非常离谱，以下有实例。
> 
> **复现问题的步骤 / Steps to Reproduce** 使用langchain_community/retrievers/bm25.py
> 
> ```
> class BM25Retriever(BaseRetriever):
>     ....
>     def _get_relevant_documents(
>         self, query: str, *, run_manager: CallbackManagerForRetrieverRun
>     ) -> List[Document]:
>         processed_query = self.preprocess_func(query)
>         return_docs = self.vectorizer.get_top_n(processed_query, self.docs, n=self.k)
>         return return_docs
> ```
> 
> **1.对query预处理得到结果：** processed_query = ['什么', '时候', '可以', '提取', '住房', '公积', '积金', '公积金']； **2.获取top_k。** `self.vectorizer.get_top_n(processed_query, self.docs, n=self.k)`
> 
> ```
> def get_top_n(self, query, documents, n=5):
>         assert self.corpus_size == len(documents), "The documents given don't match the index corpus!"
>         scores = self.get_scores(query)
>         top_n = np.argsort(scores)[::-1][:n]
>         return [documents[i] for i in top_n]
> ```
> 
> **3.检索到index如下：** ![image](https://github.com/user-attachments/assets/c42eca47-1e32-4022-a303-c4dfe2683907) **4.补充我们再看一下score的大小分布：** 发现其array的最大值是2.8+，最小值是0，其中也不乏有0.x和1.x ![image](https://github.com/user-attachments/assets/0fac88db-6c28-4b65-97d8-55b46542a79f) **5.查看20、19、18的内容发现竟然因为“提取”两个字让其score值为2.8+ ！** ![image](https://github.com/user-attachments/assets/1beafc81-7fa5-4c42-b53d-001a95dc7ce0) **6.查看faiss向量检索** 发现定义了阈值0.7之后，docs返回为空，合理。 更进一步分析faiss的score分布，其score的值也有出现在-0.x的，不知道是否合理。但是检索结果为空没问题。 注：query为：什么时候可以提取住房公积金 知识库为“一种基于RAG的多轮对话处理方法,装置以及设备.pdf”，其内容与文件名相关。 **7.思考SCORE_THRESHOLD: 0.7参数的合理性** （1）首先rank-bm25并没有使用该阈值，只使用top-k，所以无论如何都会返回top-k个检索结果，即使无任何相关性 （2）faiss向量检索为什么会出现负数？没有再去看源码的计算方法，但应该合理。 （3）建议将混合检索进行优化，一是rank-bm25算法的升级；二是增加SCORE_THRESHOLD的过滤，防止一种检索算法影响全局结果。
> 
> **环境信息 / Environment Information**
> 
> * Langchain-Chatchat 版本 / commit 号：0.3.1
> * 部署方式（pypi 安装 / 源码部署 / docker 部署）：源码部署
> * 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference
> * 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B
> * 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5  bge-large-zh-v1.5
> * 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
> * 操作系统及版本 / Operating system and version: Ubuntu20.04
> * Python 版本 / Python version: 3.10
> * 推理使用的硬件（GPU / CPU / MPS / NPU 等）：GPU
> * 其他相关环境信息 / Other relevant environment information：rank-bm25版本0.2.2

大佬你好，请问你这边有改进了吗？
