### ISSUE TITLE
[BUG] bug14 ,"POST /local_doc_qa/upload_file HTTP/1.1" 422 Unprocessable Entity

### ISSUE THREAD

**Issue by ucas010** [chatchat-space/Langchain-Chatchat#503]
上传的文件报错，返回错误，api.py

```
{
    "detail": [
        {
            "loc": [
                "body",
                "file"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```

**Comment by ucas010** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/465

**Comment by panjing1111** [comment]
解决了吗，你的调用命令是啥？我启动api.py后，upload接口失败

**Comment by unravel-xu** [comment]
检查下POST携带的数据格式，要求格式如下
`{
  "knowledge_base_id": "string",
  "question": "string",
  "streaming": false,
  "history": []
}`
`response = requests.post(url, headers = headers, json = data)`

**Comment by chenmingwei00** [comment]
有没有解决呢

**Comment by chenmingwei00** [comment]
主要原因是是FASTAPI太坑，为什么不用flask，建议作者更换，报错的原因主要是url接口解析ｊｓｏｎ数据不正确导致的，其实ｊｓｏｎ数据本身没问题，和函数参数一一对应，但是ＦＡＳＴａｐｉ反序列化解析数值性数据有问题，因此更改为
**from pydantic import BaseModel**

class Item(BaseModel):
    query: str = Body(..., description="用户输入", examples=["你好"]),
    knowledge_base_name: str = Body(..., description="知识库名称", examples=["samples"]),
    top_k: int = Body(VECTOR_SEARCH_TOP_K, description="匹配向量数"),
    score_threshold: float = Body(SCORE_THRESHOLD,
                                  description="知识库匹

async def knowledge_base_chat(item: Item):
即可解决问题，最起码ＦＡＳＴａｐｉ解析类对象没问题，强烈建议不要用这么不成熟的框架，用flask  ok??
