### ISSUE TITLE
[BUG] 使用多功能对话时出现：An error occurred during streaming

### ISSUE THREAD

**Issue by suice07** [chatchat-space/Langchain-Chatchat#5039]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 :按照说明逐步部署，其中basic_model_settings.yaml中设置如下
`
MODEL_PLATFORMS:
  - platform_name: xinference
    platform_type: xinference
    api_base_url: http://127.0.0.1:9997/v1
    api_key: EMPTY
    api_proxy: ''
    api_concurrencies: 5
    auto_detect_model: true
    llm_models: 
      - glm4-chat
    embed_models: 
      - quentinz/bge-large-zh-v1.5
    text2image_models: []
    image2text_models: []
    rerank_models: []
    speech2text_models: []
    text2speech_models: []
`

**实际结果 / Actual Result**
描述实际发生的结果：RAG 搜索效果没有问题，多功能对话没办法回答，会出现‘An error occurred during streaming’，同时报错：2024-10-29 16:52:11.012 | ERROR    | chatchat.server.api_server.openai_routes:generator:105 - openai request error: An error occurred during streaming

增加了 log 信息目前报错如下：
RuntimeError: [address=0.0.0.0:34371, pid=1497864] int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
2024-10-31 10:32:45,402 xinference.model.llm.transformers.core 1497864 ERROR    prepare inference error with int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：0.3.1.3
- 部署方式：pypi 安装
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：GLM-4-9B 
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version:Linux ubuntu 20.04
- Python 版本 / Python version: 3.10.12
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU 

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue:
参考了[https://github.com/chatchat-space/Langchain-Chatchat/issues/4579](url)降低了 transformer 版本，还是同样效果，想问下是不是哪里设置错了；

**Comment by Andy1018** [comment]
解决了吗，我也遇到同样的问题

**Comment by suice07** [comment]
> 解决了吗，我也遇到同样的问题

还没有，感觉是 transformer 有问题。但是又不知换哪个版本。

**Comment by MyLifeisGettingBetter** [comment]
请问大佬解决了么？同样遇到，我本地的环境版本配置如下：
# packages in environment at D:\ProgramFiles\anaconda3\envs\chatchat:
#
# Name                    Version                   Build  Channel
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
altair                    4.2.2                    pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     4.6.2.post1              pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
backoff                   2.2.1                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
blinker                   1.8.2                    pypi_0    pypi
brotli                    1.1.0                    pypi_0    pypi
bzip2                     1.0.8                h2466b09_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2024.8.30            h56e8100_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                5.5.0                    pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
chardet                   5.2.0                    pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
contourpy                 1.3.0                    pypi_0    pypi
cryptography              43.0.3                   pypi_0    pypi
cycler                    0.12.1                   pypi_0    pypi
dataclasses-json          0.6.7                    pypi_0    pypi
deepdiff                  8.0.1                    pypi_0    pypi
deprecation               2.1.0                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
elastic-transport         8.15.1                   pypi_0    pypi
elasticsearch             8.15.1                   pypi_0    pypi
emoji                     2.14.0                   pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
et-xmlfile                2.0.0                    pypi_0    pypi
faiss-cpu                 1.7.4                    pypi_0    pypi
faker                     30.8.2                   pypi_0    pypi
fastapi                   0.109.2                  pypi_0    pypi
favicon                   0.7.0                    pypi_0    pypi
filetype                  1.2.0                    pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
fonttools                 4.54.1                   pypi_0    pypi
frozenlist                1.5.0                    pypi_0    pypi
gitdb                     4.0.11                   pypi_0    pypi
gitpython                 3.1.43                   pypi_0    pypi
greenlet                  3.1.1                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
h2                        4.1.0                    pypi_0    pypi
hpack                     4.0.0                    pypi_0    pypi
htbuilder                 0.6.2                    pypi_0    pypi
httpcore                  1.0.6                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hyperframe                6.0.1                    pypi_0    pypi
idna                      3.10                     pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jiter                     0.7.0                    pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonpatch                 1.33                     pypi_0    pypi
jsonpath-python           1.0.6                    pypi_0    pypi
jsonpointer               3.0.0                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
kiwisolver                1.4.7                    pypi_0    pypi
langchain                 0.1.17                   pypi_0    pypi
langchain-chatchat        0.3.1.3                  pypi_0    pypi
langchain-community       0.0.36                   pypi_0    pypi
langchain-core            0.1.52                   pypi_0    pypi
langchain-experimental    0.0.58                   pypi_0    pypi
langchain-openai          0.0.6                    pypi_0    pypi
langchain-text-splitters  0.0.2                    pypi_0    pypi
langchainhub              0.1.14                   pypi_0    pypi
langdetect                1.0.9                    pypi_0    pypi
langsmith                 0.1.138                  pypi_0    pypi
libexpat                  2.6.3                he0c23c2_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libffi                    3.4.2                h8ffe710_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libsqlite                 3.47.0               h2466b09_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
libzlib                   1.3.1                h2466b09_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
loguru                    0.7.2                    pypi_0    pypi
lxml                      5.3.0                    pypi_0    pypi
markdown                  3.7                      pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markdownify               0.13.1                   pypi_0    pypi
markdownlit               0.0.7                    pypi_0    pypi
markupsafe                3.0.2                    pypi_0    pypi
marshmallow               3.23.0                   pypi_0    pypi
matplotlib                3.9.2                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
memoization               0.4.0                    pypi_0    pypi
more-itertools            10.5.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.1                      pypi_0    pypi
nltk                      3.8.1                    pypi_0    pypi
numexpr                   2.10.1                   pypi_0    pypi
numpy                     1.24.4                   pypi_0    pypi
onnxruntime               1.19.2                   pypi_0    pypi
openai                    1.53.0                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
openpyxl                  3.1.4                    pypi_0    pypi
openssl                   3.3.2                h2466b09_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
orderly-set               5.2.2                    pypi_0    pypi
orjson                    3.10.10                  pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
pathlib                   1.0.1                    pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.3.1             pyh8b19718_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prometheus-client         0.21.0                   pypi_0    pypi
propcache                 0.2.0                    pypi_0    pypi
protobuf                  4.25.5                   pypi_0    pypi
pyarrow                   18.0.0                   pypi_0    pypi
pyclipper                 1.3.0.post6              pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pydantic                  2.7.4                    pypi_0    pypi
pydantic-core             2.18.4                   pypi_0    pypi
pydantic-settings         2.3.4                    pypi_0    pypi
pydeck                    0.9.1                    pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
pymdown-extensions        10.12                    pypi_0    pypi
pymupdf                   1.23.26                  pypi_0    pypi
pymupdfb                  1.23.22                  pypi_0    pypi
pymysql                   1.1.0                    pypi_0    pypi
pyparsing                 3.2.0                    pypi_0    pypi
pypdf                     5.1.0                    pypi_0    pypi
pyreadline3               3.5.4                    pypi_0    pypi
python                    3.11.10         hce54a09_3_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.9.0.post0              pypi_0    pypi
python-decouple           3.8                      pypi_0    pypi
python-docx               1.1.2                    pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-iso639             2024.10.22               pypi_0    pypi
python-magic              0.4.27                   pypi_0    pypi
python-magic-bin          0.4.14                   pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
rank-bm25                 0.2.2                    pypi_0    pypi
rapidfuzz                 3.10.1                   pypi_0    pypi
rapidocr-onnxruntime      1.3.25                   pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
regex                     2024.9.11                pypi_0    pypi
requests                  2.31.0                   pypi_0    pypi
requests-toolbelt         1.0.0                    pypi_0    pypi
rich                      13.9.3                   pypi_0    pypi
rpds-py                   0.20.1                   pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.12                   pypi_0    pypi
setuptools                75.3.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
shapely                   2.0.6                    pypi_0    pypi
simplejson                3.19.3                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
smmap                     5.0.1                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
socksio                   1.0.0                    pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
sqlalchemy                2.0.36                   pypi_0    pypi
sse-starlette             1.8.2                    pypi_0    pypi
st-annotated-text         4.0.1                    pypi_0    pypi
starlette                 0.36.3                   pypi_0    pypi
streamlit                 1.34.0                   pypi_0    pypi
streamlit-aggrid          1.0.5                    pypi_0    pypi
streamlit-antd-components 0.3.1                    pypi_0    pypi
streamlit-camera-input-live 0.2.0                    pypi_0    pypi
streamlit-card            1.0.2                    pypi_0    pypi
streamlit-chatbox         1.1.12.post4             pypi_0    pypi
streamlit-embedcode       0.1.2                    pypi_0    pypi
streamlit-extras          0.4.2                    pypi_0    pypi
streamlit-faker           0.0.3                    pypi_0    pypi
streamlit-feedback        0.1.3                    pypi_0    pypi
streamlit-image-coordinates 0.1.9                    pypi_0    pypi
streamlit-keyup           0.2.4                    pypi_0    pypi
streamlit-modal           0.1.0                    pypi_0    pypi
streamlit-option-menu     0.3.12                   pypi_0    pypi
streamlit-paste-button    0.1.2                    pypi_0    pypi
streamlit-toggle-switch   1.0.2                    pypi_0    pypi
streamlit-vertical-slider 2.5.5                    pypi_0    pypi
strsimpy                  0.2.1                    pypi_0    pypi
sympy                     1.13.3                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tenacity                  8.5.0                    pypi_0    pypi
tiktoken                  0.8.0                    pypi_0    pypi
tk                        8.6.13               h5226925_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
toml                      0.10.2                   pypi_0    pypi
toolz                     1.0.0                    pypi_0    pypi
tornado                   6.4.1                    pypi_0    pypi
tqdm                      4.66.6                   pypi_0    pypi
types-requests            2.32.0.20241016          pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2024b                hc8b5060_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ucrt                      10.0.22621.0         h57928b3_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
unstructured              0.11.8                   pypi_0    pypi
unstructured-client       0.25.9                   pypi_0    pypi
urllib3                   2.2.3                    pypi_0    pypi
uvicorn                   0.32.0                   pypi_0    pypi
validators                0.34.0                   pypi_0    pypi
vc                        14.3                h8a93ad2_22    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vc14_runtime              14.40.33810         hcc2c482_22    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vs2015_runtime            14.40.33810         h3bf8584_22    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
watchdog                  5.0.3                    pypi_0    pypi
websockets                13.1                     pypi_0    pypi
wheel                     0.44.0             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
win32-setctime            1.1.0                    pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
xinference-client         0.13.0                   pypi_0    pypi
xz                        5.2.6                h8d14728_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
yarl                      1.17.1                   pypi_0    pypi
zhipuai                   2.1.0                    pypi_0    pypi


xinference服务器上环境配置如下：
# packages in environment at /home/suaike/anaconda3/envs/xinferenceRun:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
accelerate                1.0.1                    pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
aiohappyeyeballs          2.4.3                    pypi_0    pypi
aiohttp                   3.10.10                  pypi_0    pypi
aioprometheus             23.12.0                  pypi_0    pypi
aiosignal                 1.3.1                    pypi_0    pypi
aliyun-python-sdk-core    2.16.0                   pypi_0    pypi
aliyun-python-sdk-kms     2.16.5                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
antlr4-python3-runtime    4.9.3                    pypi_0    pypi
anyio                     4.6.2.post1              pypi_0    pypi
argcomplete               3.5.1                    pypi_0    pypi
async-timeout             4.0.3                    pypi_0    pypi
attrdict                  2.0.1                    pypi_0    pypi
attrs                     24.2.0                   pypi_0    pypi
audioread                 3.0.1                    pypi_0    pypi
auto-gptq                 0.7.1                    pypi_0    pypi
autoawq                   0.2.5                    pypi_0    pypi
autoawq-kernels           0.0.6                    pypi_0    pypi
av                        13.1.0                   pypi_0    pypi
bcrypt                    4.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bitsandbytes              0.44.1                   pypi_0    pypi
black                     24.10.0                  pypi_0    pypi
boto3                     1.28.64                  pypi_0    pypi
botocore                  1.31.85                  pypi_0    pypi
bzip2                     1.0.8                h5eee18b_6  
ca-certificates           2024.9.24            h06a4308_0  
cdifflib                  1.2.6                    pypi_0    pypi
certifi                   2024.8.30                pypi_0    pypi
cffi                      1.17.1                   pypi_0    pypi
charset-normalizer        3.4.0                    pypi_0    pypi
chattts                   0.1.1                    pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
cloudpickle               3.1.0                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
compressed-tensors        0.6.0                    pypi_0    pypi
conformer                 0.3.2                    pypi_0    pypi
controlnet-aux            0.0.7                    pypi_0    pypi
crcmod                    1.7                      pypi_0    pypi
cryptography              43.0.3                   pypi_0    pypi
cython                    3.0.11                   pypi_0    pypi
datamodel-code-generator  0.26.2                   pypi_0    pypi
datasets                  2.14.4                   pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
diffusers                 0.30.3                   pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
diskcache                 5.6.3                    pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
dnspython                 2.7.0                    pypi_0    pypi
ecdsa                     0.19.0                   pypi_0    pypi
editdistance              0.8.1                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
einx                      0.3.0                    pypi_0    pypi
email-validator           2.2.0                    pypi_0    pypi
encodec                   0.1.1                    pypi_0    pypi
eva-decord                0.6.1                    pypi_0    pypi
fastapi                   0.110.3                  pypi_0    pypi
ffmpy                     0.4.0                    pypi_0    pypi
filelock                  3.16.1                   pypi_0    pypi
flagembedding             1.2.11                   pypi_0    pypi
flatbuffers               24.3.25                  pypi_0    pypi
frozendict                2.4.6                    pypi_0    pypi
frozenlist                1.4.1                    pypi_0    pypi
fsspec                    2024.10.0                pypi_0    pypi
funasr                    1.1.12                   pypi_0    pypi
fvcore                    0.1.5.post20221221          pypi_0    pypi
gdown                     5.2.0                    pypi_0    pypi
gekko                     1.2.1                    pypi_0    pypi
genson                    1.3.0                    pypi_0    pypi
gguf                      0.10.0                   pypi_0    pypi
gradio                    5.1.0                    pypi_0    pypi
gradio-client             1.4.0                    pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
hiredis                   3.0.0                    pypi_0    pypi
httpcore                  1.0.6                    pypi_0    pypi
httptools                 0.6.4                    pypi_0    pypi
httpx                     0.27.2                   pypi_0    pypi
huggingface-hub           0.26.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
hydra-core                1.3.2                    pypi_0    pypi
hyperpyyaml               1.2.2                    pypi_0    pypi
idna                      3.10                     pypi_0    pypi
imageio                   2.36.0                   pypi_0    pypi
imageio-ffmpeg            0.5.1                    pypi_0    pypi
importlib-metadata        8.5.0                    pypi_0    pypi
importlib-resources       6.4.5                    pypi_0    pypi
inflect                   5.6.2                    pypi_0    pypi
interegular               0.3.3                    pypi_0    pypi
iopath                    0.1.10                   pypi_0    pypi
isort                     5.13.2                   pypi_0    pypi
jaconv                    0.4.0                    pypi_0    pypi
jamo                      0.4.1                    pypi_0    pypi
jieba                     0.42.1                   pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
jiter                     0.6.1                    pypi_0    pypi
jj-pytorchvideo           0.1.5                    pypi_0    pypi
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.4.2                    pypi_0    pypi
jsonschema                4.23.0                   pypi_0    pypi
jsonschema-specifications 2024.10.1                pypi_0    pypi
kaldiio                   2.18.0                   pypi_0    pypi
lark                      1.2.2                    pypi_0    pypi
lazy-loader               0.4                      pypi_0    pypi
ld_impl_linux-64          2.40                 h12ee557_0  
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libnacl                   2.1.0                    pypi_0    pypi
librosa                   0.10.2.post1             pypi_0    pypi
libstdcxx-ng              11.2.0               h1234567_1  
libuuid                   1.41.5               h5eee18b_0  
lightning                 2.4.0                    pypi_0    pypi
lightning-utilities       0.11.8                   pypi_0    pypi
llama-cpp-python          0.3.1                    pypi_0    pypi
llvmlite                  0.43.0                   pypi_0    pypi
lm-format-enforcer        0.10.6                   pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
loralib                   0.1.2                    pypi_0    pypi
markdown-it-py            3.0.0                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
mdurl                     0.1.2                    pypi_0    pypi
mistral-common            1.4.4                    pypi_0    pypi
modelscope                1.19.0                   pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
msgpack                   1.1.0                    pypi_0    pypi
msgspec                   0.18.6                   pypi_0    pypi
multidict                 6.1.0                    pypi_0    pypi
multiprocess              0.70.15                  pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
natsort                   8.4.0                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
nemo-text-processing      1.0.2                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.4.1                    pypi_0    pypi
numba                     0.60.0                   pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
nvidia-cudnn-cu12         9.1.0.70                 pypi_0    pypi
nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
nvidia-ml-py              12.560.30                pypi_0    pypi
nvidia-nccl-cu12          2.20.5                   pypi_0    pypi
nvidia-nvjitlink-cu12     12.4.127                 pypi_0    pypi
nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
omegaconf                 2.3.0                    pypi_0    pypi
onnxruntime               1.16.0                   pypi_0    pypi
openai                    1.52.0                   pypi_0    pypi
opencv-python             4.10.0.84                pypi_0    pypi
opencv-python-headless    4.10.0.84                pypi_0    pypi
openssl                   3.0.15               h5eee18b_0  
optimum                   1.23.1                   pypi_0    pypi
orjson                    3.10.9                   pypi_0    pypi
ormsgpack                 1.6.0                    pypi_0    pypi
oss2                      2.19.0                   pypi_0    pypi
outlines                  0.0.46                   pypi_0    pypi
packaging                 24.1                     pypi_0    pypi
pandas                    2.2.3                    pypi_0    pypi
parameterized             0.9.0                    pypi_0    pypi
partial-json-parser       0.2.1.1.post4            pypi_0    pypi
passlib                   1.7.4                    pypi_0    pypi
pathspec                  0.12.1                   pypi_0    pypi
peft                      0.13.2                   pypi_0    pypi
pillow                    10.4.0                   pypi_0    pypi
pip                       24.2            py311h06a4308_0  
platformdirs              4.3.6                    pypi_0    pypi
pooch                     1.8.2                    pypi_0    pypi
portalocker               2.10.1                   pypi_0    pypi
prometheus-client         0.21.0                   pypi_0    pypi
prometheus-fastapi-instrumentator 7.0.0                    pypi_0    pypi
propcache                 0.2.0                    pypi_0    pypi
protobuf                  5.28.2                   pypi_0    pypi
psutil                    6.1.0                    pypi_0    pypi
py-cpuinfo                9.0.0                    pypi_0    pypi
pyairports                2.1.1                    pypi_0    pypi
pyarrow                   17.0.0                   pypi_0    pypi
pyasn1                    0.6.1                    pypi_0    pypi
pybase16384               0.3.7                    pypi_0    pypi
pycountry                 24.6.1                   pypi_0    pypi
pycparser                 2.22                     pypi_0    pypi
pycryptodome              3.21.0                   pypi_0    pypi
pydantic                  2.9.2                    pypi_0    pypi
pydantic-core             2.23.4                   pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.18.0                   pypi_0    pypi
pynini                    2.1.5                    pypi_0    pypi
pynndescent               0.5.13                   pypi_0    pypi
pysocks                   1.7.1                    pypi_0    pypi
python                    3.11.10              he870216_0  
python-dateutil           2.9.0.post0              pypi_0    pypi
python-dotenv             1.0.1                    pypi_0    pypi
python-jose               3.3.0                    pypi_0    pypi
python-multipart          0.0.12                   pypi_0    pypi
pytorch-lightning         2.4.0                    pypi_0    pypi
pytorch-wpe               0.0.1                    pypi_0    pypi
pytz                      2024.2                   pypi_0    pypi
pyyaml                    6.0.2                    pypi_0    pypi
pyzmq                     26.2.0                   pypi_0    pypi
quantile-python           1.1                      pypi_0    pypi
qwen-vl-utils             0.0.8                    pypi_0    pypi
ray                       2.37.0                   pypi_0    pypi
readline                  8.2                  h5eee18b_0  
redis                     5.1.1                    pypi_0    pypi
referencing               0.35.1                   pypi_0    pypi
regex                     2024.9.11                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
rich                      13.9.2                   pypi_0    pypi
rouge                     1.0.1                    pypi_0    pypi
rpds-py                   0.20.0                   pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
ruamel-yaml               0.18.6                   pypi_0    pypi
ruamel-yaml-clib          0.2.12                   pypi_0    pypi
ruff                      0.7.0                    pypi_0    pypi
s3transfer                0.7.0                    pypi_0    pypi
sacremoses                0.1.1                    pypi_0    pypi
safetensors               0.4.5                    pypi_0    pypi
scikit-image              0.24.0                   pypi_0    pypi
scikit-learn              1.5.2                    pypi_0    pypi
scipy                     1.14.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
sentence-transformers     3.2.0                    pypi_0    pypi
sentencepiece             0.2.0                    pypi_0    pypi
setuptools                75.1.0          py311h06a4308_0  
sglang                    0.3.4                    pypi_0    pypi
shellingham               1.5.4                    pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
soundfile                 0.12.1                   pypi_0    pypi
soupsieve                 2.6                      pypi_0    pypi
soxr                      0.5.0.post1              pypi_0    pypi
sqlite                    3.45.3               h5eee18b_0  
sse-starlette             2.1.3                    pypi_0    pypi
starlette                 0.37.2                   pypi_0    pypi
sympy                     1.13.1                   pypi_0    pypi
tabulate                  0.9.0                    pypi_0    pypi
tblib                     3.0.0                    pypi_0    pypi
tensorboardx              2.6.2.2                  pypi_0    pypi
tensorizer                2.9.0                    pypi_0    pypi
termcolor                 2.5.0                    pypi_0    pypi
threadpoolctl             3.5.0                    pypi_0    pypi
tifffile                  2024.9.20                pypi_0    pypi
tiktoken                  0.7.0                    pypi_0    pypi
timm                      1.0.11                   pypi_0    pypi
tk                        8.6.14               h39e8969_0  
tokenizers                0.20.1                   pypi_0    pypi
tomlkit                   0.12.0                   pypi_0    pypi
torch                     2.4.0                    pypi_0    pypi
torch-complex             0.4.4                    pypi_0    pypi
torchaudio                2.4.0                    pypi_0    pypi
torchmetrics              1.5.0                    pypi_0    pypi
torchvision               0.19.0                   pypi_0    pypi
tqdm                      4.66.5                   pypi_0    pypi
transformers              4.45.2                   pypi_0    pypi
transformers-stream-generator 0.0.5                    pypi_0    pypi
triton                    3.0.0                    pypi_0    pypi
typer                     0.12.5                   pypi_0    pypi
typing-extensions         4.12.2                   pypi_0    pypi
tzdata                    2024.2                   pypi_0    pypi
umap-learn                0.5.6                    pypi_0    pypi
urllib3                   2.0.7                    pypi_0    pypi
uvicorn                   0.32.0                   pypi_0    pypi
uvloop                    0.21.0                   pypi_0    pypi
vector-quantize-pytorch   1.18.5                   pypi_0    pypi
vllm                      0.6.3.post1              pypi_0    pypi
vocos                     0.1.0                    pypi_0    pypi
watchfiles                0.24.0                   pypi_0    pypi
websockets                12.0                     pypi_0    pypi
wetextprocessing          1.0.3                    pypi_0    pypi
wget                      3.2                      pypi_0    pypi
wheel                     0.44.0          py311h06a4308_0  
wrapt                     1.16.0                   pypi_0    pypi
xformers                  0.0.27.post2             pypi_0    pypi
xinference                0.16.0                   pypi_0    pypi
xoscar                    0.3.3                    pypi_0    pypi
xxhash                    3.5.0                    pypi_0    pypi
xz                        5.4.6                h5eee18b_1  
yacs                      0.1.8                    pypi_0    pypi
yarl                      1.15.5                   pypi_0    pypi
zipp                      3.20.2                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_1  
zstandard                 0.23.0                   pypi_0    pypi

**Comment by beifengche** [comment]
这应该是没有适配号新版本的xinference 导致的bug，可以将xinference 降低到0.15.x的版本尝试一下。希望能尽快适配新版本xinference
