### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue 重排序模型在不同服务器的耗时问题

### ISSUE THREAD

**Issue by TZJ12** [chatchat-space/Langchain-Chatchat#5056]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
在4090服务器上，重排序模型耗时2s以内，但是项目部署到A100上，重排序模型耗时5s多，这是为什么呢

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
重排序模型在两个服务器耗时差不多才对

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
在A100服务器上面比4090服务器上面耗时增大4s

**环境信息 / Environment Information**
- Langchain-Chatchat 版本 / commit 号：
2.10版本

- 部署方式（pypi 安装 / 源码部署 / docker 部署）：
源码部署

- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：OpenAI API

- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：
使用的大模型为基于qwen系列大模型微调的模型

- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）： bge-large-zh-v1.5
- 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 
- 操作系统及版本 / Operating system and version: centOS7
- Python 版本 / Python version: 3.10.12
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU

**Comment by LanYu4qz** [comment]
推荐你用 FlagEmbedding import FlagReranker

**Comment by TZJ12** [comment]
我尝试了FlagEmbedding import FlagReranker，虽然在4090服务器上面表现很好，但是在A100服务器上面响应时长还是需要接近5s
