### ISSUE TITLE
api.py脚本打算增加SSE流式输出吗？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#511]
curl调用的时候可以检测第一个字，从而提升回复的体验

**Comment by cristianohello** [comment]
@ferrymo 
哪个响应时间更快呢？

**Comment by cristianohello** [comment]
@ferrymo 
是下面这样调用的吗？还是其他调用方式。我的向量改成本地加载了，下面这种方式：
![ACfOb1bUHm](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109277248/037b16b7-20b3-4a50-91d9-6df56a6aa5eb)


curl -X 'POST' \
  'http://127.0.0.1:8000/chat-docs/stream-chat/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "knowledge_base_id": "string",
  "question": "你好",
  "history": []
}'

**Comment by cristianohello** [comment]
@ferrymo 
你是怎么调用的？curl吗？
curl -X 'POST' \
  'http://127.0.0.1:8000/chat/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "knowledge_base_id": "string",
  "question": "你好",
  "history": []
}'

这样有问题，该如何修改呢？

**Comment by ferrymo** [comment]
> 面这样调用的吗？还是其他调用方式。我的向量改成本地加载

使用websocket方式调用

**Comment by cristianohello** [comment]
@ferrymo 
websocket怎么调用？有调用的代码吗？感谢感谢

**Comment by cristianohello** [comment]
@ferrymo 
大佬，问一下，能使用curl调用吗？格式是什么？

我下面这样调用会报错：
curl -X 'POST' \
  'http://127.0.0.1:8000/local_doc_qa/stream-chat/baoxian_FAISS_20230602_172352' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "question": "卡塔尔世界杯冠军是谁",
  "history": [],
  "knowledge_base_id": "baoxian_FAISS_20230602_172352",
}'

**Comment by zfanswer** [comment]
需要用websocket的方式调用，不是http的post方式

你用postman的话，有websocket实例
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1787565/60d47e79-45be-4b2a-989e-1aa7d98e39c4)
这样调用
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1787565/e06c16a2-db5c-452c-81fd-7eceb943e23e)

在程序里调用的找下支持ws的sdk
