### ISSUE TITLE
[BUG] 使用tornado实现webSocket，可以多个客户端同时连接，并且实现流式回复，但是多个客户端同时使用，答案就很乱，是模型不支持多线程吗

### ISSUE THREAD

**Issue by forever1dream** [chatchat-space/Langchain-Chatchat#512]
import asyncio
import datetime
import json
import time

import tornado.websocket
import tornado.websocket
from tornado.options import define, parse_command_line
from tornado.platform.asyncio import AnyThreadEventLoopPolicy
from transformers import AutoTokenizer, AutoModel

define("port", default=8888, help="run on given port", type=int)

# 定义一个空的字典
clients = dict()

def build_prompt(history):
    prompt = "欢迎使用 ChatGLM-6B 模型，输入内容即可进行对话，clear 清空对话历史，stop 终止程序"
    q = ""
    r = ""
    for query, response in history:
        prompt += f"\n\nuser-input：{query}"
        prompt += f"\n\nChat-GLM-Answer：{response}"
        q = query
        r = response
    return prompt, q, r

class MyWebSocketHandler(tornado.websocket.WebSocketHandler):

    def initialize(self, my_object, my_tokenizer):
        self.model = my_object
        self.tokenizer = my_tokenizer
        self.executor = tornado.concurrent.futures.ThreadPoolExecutor(4)

    # 有新的连接时open()函数将会被调用,将客户端的连接统一放到clients
    def open(self, *args, **kwargs):
        self.id = self.get_argument("id")
        clients[self.id] = {"id": self.id, "object": self}
        print(clients)
        print("建立连接...")

    # @run_on_executor
    def predict(self, prompt, history):
        count = 0
        for response, history in self.model.stream_chat(self.tokenizer, prompt, history=history):
            count += 1
            print(count)
            if count % 4 == 0:
                p, q, r = build_prompt(history)
                self.write_message(r)
                print(r)

        p, q, r = build_prompt(history)
        self.write_message(r)

    # 客户收到消息将被调用
    # @gen.coroutine
    async def on_message(self, message):
        json_post = json.loads(message)
        prompt = json_post["query"]
        history = json_post['history']
        print(str(prompt))
        print(str(history))
        # yield self.predict(prompt=prompt, history=history)
        new_loop = asyncio.new_event_loop()
        asyncio.set_event_loop(new_loop)
        loop = asyncio.get_event_loop()
        await loop.run_in_executor(self.executor, self.predict, prompt, history)

    # 关闭连接时被调用
    def on_close(self):
        if self.id in clients:
            del clients[self.id]
        print("client %s is closed" % self.id)

    def check_origin(self, origin):
        return True

def send_time():
    while True:
        for key in clients.keys():
            msg = str(datetime.datetime.now())
            clients[key]["object"].write_message(msg)
            print("write to client %s:%s" % (key, msg))
        time.sleep(1)

if __name__ == "__main__":
    asyncio.set_event_loop_policy(AnyThreadEventLoopPolicy())
    # threading.Thread(target=send_time).start()

    tokenizer = AutoTokenizer.from_pretrained(".\\THUDM\\chatglm-6b-int4", trust_remote_code=True)
    model = AutoModel.from_pretrained(".\\THUDM\\chatglm-6b-int4", trust_remote_code=True).float()
    model.eval()
    app = tornado.web.Application([
        (r"/websocket", MyWebSocketHandler, {"my_object": model, "my_tokenizer": tokenizer})])

    parse_command_line()
    app.listen(80)
    tornado.ioloop.IOLoop.instance().start()

**Comment by RudRho** [comment]
请问您解决了吗
