### ISSUE TITLE
[BUG] 知识库和大模型对话都没有返回message_id

### ISSUE THREAD

**Issue by edwardlzh** [chatchat-space/Langchain-Chatchat#5129]
**问题描述 / Problem Description**
知识库和大模型对话都没有返回message_id。

**预期的结果 / Expected Result**
想实现本地知识库对话的评分功能。

**实际结果 / Actual Result**
评分接口需要message_id，看了下好像接口返回的message_id都为空

**环境信息 / Environment Information**
- 0.3.1.3
- 部署方式（pypi 安装 / 源码部署 / docker 部署）：pypi installation
- 使用的模型推理框架（Xinference / Ollama / OpenAI API 等）：Xinference 
- 使用的 LLM 模型（GLM-4-9B / Qwen2-7B-Instruct 等）：qwen1.5-14B
- 使用的 Embedding 模型（bge-large-zh-v1.5 / m3e-base 等）：bge-large-zh-v1.5 
- 使用的向量库类型 (faiss / milvus / pg_vector 等)： faiss
- 操作系统及版本 / Operating system and version: linux
- Python 版本 / Python version: 3.9
- 推理使用的硬件（GPU / CPU / MPS / NPU 等） / Inference hardware (GPU / CPU / MPS / NPU, etc.): GPU 
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by 948024326** [comment]
源码部署改一下

**Comment by edwardlzh** [comment]
@948024326 你好，怎么改呢？有建议吗？

**Comment by edwardlzh** [comment]
已解决

**Comment by yuezhupy** [comment]
> 已解决

请问怎么改的？有什么建议吗

**Comment by yuezhupy** [comment]
> 已解决

@edwardlzh 请问怎么修改的呢？

**Comment by edwardlzh** [comment]
> > 已解决
> 
> @edwardlzh 请问怎么修改的呢？

@yuezhupy 
1. 用/chat/chat/completions接口，自定义传入conversation_id，这样响应可以返回message_id，并且能入库。
```
// libs/chatchat-server/chatchat/server/api_server/chat_routes.py:70
extra = {**body.model_extra} or {}
// libs/chatchat-server/chatchat/server/api_server/chat_routes.py:91
conversation_id = extra.get("conversation_id")
```
2. /kb_chat接口想实现可能需要改代码吧，参考`chatchat.server.db.repository.message_repository.add_message_to_db`

**Comment by yuezhupy** [comment]
> > > 已解决
> > 
> > 
> > @edwardlzh 请问怎么修改的呢？
> 
> @yuezhupy
> 
> 1. 用/chat/chat/completions接口，自定义传入conversation_id，这样响应可以返回message_id，并且能入库。
> 
> ```
> // libs/chatchat-server/chatchat/server/api_server/chat_routes.py:70
> extra = {**body.model_extra} or {}
> // libs/chatchat-server/chatchat/server/api_server/chat_routes.py:91
> conversation_id = extra.get("conversation_id")
> ```
> 
> 2. /kb_chat接口想实现可能需要改代码吧，参考`chatchat.server.db.repository.message_repository.add_message_to_db`
@edwardlzh 
请问在/chat/chat/completions接口自定义的话是在输入的json中extra_body直接添加吗，方便给一个输入的用例吗

**Comment by edwardlzh** [comment]
> > > > 已解决
> > > 
> > > 
> > > @edwardlzh 请问怎么修改的呢？
> > 
> > 
> > @yuezhupy
> > 
> > 1. 用/chat/chat/completions接口，自定义传入conversation_id，这样响应可以返回message_id，并且能入库。
> > 
> > ```
> > // libs/chatchat-server/chatchat/server/api_server/chat_routes.py:70
> > extra = {**body.model_extra} or {}
> > // libs/chatchat-server/chatchat/server/api_server/chat_routes.py:91
> > conversation_id = extra.get("conversation_id")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 2. /kb_chat接口想实现可能需要改代码吧，参考`chatchat.server.db.repository.message_repository.add_message_to_db`
> >    @edwardlzh
> >    请问在/chat/chat/completions接口自定义的话是在输入的json中extra_body直接添加吗，方便给一个输入的用例吗

@yuezhupy 
···
{
	"messages": [{
		"content": "xxxxxxx",
		"role": "user"
	}],
	"model": "qwen1.5-chat",
	"stream": true,
	"tool_choice": "search_local_knowledgebase",
	"tool_input": {
		"database": "",
		"query": "xxxxxxxx"
	},
	"conversation_id": "12345678912345678912345678912345" /* 32位*/
}
···

**Comment by yuezhupy** [comment]
@edwardlzh 
谢谢
