### ISSUE TITLE
支持 chinese_alpaca_plus_lora 吗  基于llama的

### ISSUE THREAD

**Issue by sssdjj** [chatchat-space/Langchain-Chatchat#514]
支持 chinese_alpaca_plus_lora 吗  基于llama的，https://github.com/ymcui/Chinese-LLaMA-Alpaca这个项目的

**Comment by bruceye777** [comment]
同求，测试下来，中文模型中这个效果最佳

**Comment by ChinnYu** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/32726550/e3f26ae9-0fa8-4486-82e6-39d6bda895f8)
按照chinese_alpaca_plus_lora 做出的格式，並再model_config.py 新增一筆進 json選單(選擇 "provides": "LLamaLLMChain")、 LLM_MODEL 填入相同名稱、設置LOAD_IN_8BIT = True，能正常跑起，但回答就有點胡言亂語，不確定是否vector 沒對到嗎?

**Comment by ChinnYu** [comment]
按照chinese_alpaca_plus_lora 做出的格式，並再model_config.py 新增一筆進 json選單(選擇 "provides": "LLamaLLMChain")、 LLM_MODEL 填入相同名稱、設置LOAD_IN_8BIT = True，能正常跑起，但回答就有點胡言亂語，不確定是否vector 沒對到嗎?
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/32726550/640abe9b-2514-47bb-8982-69440f873c53)
