### ISSUE TITLE
[BUG] 现在能读图片的pdf了，但是文字的pdf反而读不了了，什么情况？？？

### ISSUE THREAD

**Issue by haorunze** [chatchat-space/Langchain-Chatchat#515]
**问题描述 / Problem Description**
知识库读取文字pdf失败

**复现问题的步骤 / Steps to Reproduce**
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/33285301/92c983a8-b44f-4a0d-8dad-20a291bc1804)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:3.10.9
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by ucas010** [comment]
大佬试试这个，https://github.com/imClumsyPanda/langchain-ChatGLM/issues/506
