### ISSUE TITLE
curl调用的时候，从第二轮开始，curl如何传参可以实现多轮对话？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#517]
第一轮调用：
curl -X 'POST' \
  'http://126.2.1.3:8000/chat-docs/chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "knowledge_base_id": "string",
  "question": "你好",
  "history":[]
}'

第二轮如何调用呢？
这样吗：
curl -X 'POST' \
  'http://126.2.1.3:8000/chat-docs/chat' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "knowledge_base_id": "string",
  "question": "你是谁",
  "history":[["你好","你也好啊"]]
}'

**Comment by kjcx100** [comment]
同问，有没有大佬解答下呢

**Comment by zRzRzRzRzRzRzR** [comment]
传入History参数，模型会读取History和query实现多轮对话
