### ISSUE TITLE
[BUG] 上传文件到知识库 任何格式与内容都永远失败

### ISSUE THREAD

**Issue by xkkjiayou** [chatchat-space/Langchain-Chatchat#520]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38376865/a19837f2-8f9e-464d-b9a3-27b5def3a338)

上传知识库的时候，传txt无法解析，就算是穿content/sample里的样例txt也无法解析，上传md、pdf等都无法加载，会持续性等待，等到了超过30分钟也不行。

目前只能通过，知识库测试板块中的 单条录入（标题，内容）来解决，传任何文件都不行。

谢谢

**Comment by onetwo12cn** [comment]
同样的问题

> ![image](https://user-images.githubusercontent.com/38376865/242520703-a19837f2-8f9e-464d-b9a3-27b5def3a338.png)
> 
> 上传知识库的时候，传txt无法解析，就算是穿content/sample里的样例txt也无法解析，上传md、pdf等都无法加载，会持续性等待，等到了超过30分钟也不行。
> 
> 目前只能通过，知识库测试板块中的 单条录入（标题，内容）来解决，传任何文件都不行。
> 
> 谢谢

**Comment by xkkjiayou** [comment]
感谢您的来信，此时我不在办公室，稍后会及时阅读。在此期间我不方便接收邮件。如果您想及时获得通讯，请拨打我的手机联系我，谢谢您。

**Comment by ngbruce** [comment]
留意控制台输出的信息，可能是字符编解码组件没有安装

**Comment by xkkjiayou** [comment]
感谢您的来信，此时我不在办公室，稍后会及时阅读。在此期间我不方便接收邮件。如果您想及时获得通讯，请拨打我的手机联系我，谢谢您。
