### ISSUE TITLE
关于prompt_template的问题

### ISSUE THREAD

**Issue by ccartermices** [chatchat-space/Langchain-Chatchat#521]
请问这段prompt_template是什么意思，要怎么使用？可以给一个具体模板参考下吗？
`# 基于上下文的prompt模版，请务必保留"{question}"和"{context}"
PROMPT_TEMPLATE = """已知信息：
{context} 

根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。 问题是：{question}"""`

**Comment by ffy-FFRain** [comment]
程序会将这段话中的context替换为向量匹配到的信息，将question替换为问题，最后将这段话抛给llm让他回答。你可以理解为，prompt是小抄，chatGLM是考生，问题就是一道题。我们要做的就是想办法让chatGLM能看懂小抄。

**Comment by glide-the** [comment]
https://python.langchain.com/en/latest/modules/prompts.html
参考官网对prompts的定义
