### ISSUE TITLE
ImportError: cannot import name 'inference' from 'paddle'

### ISSUE THREAD

**Issue by xiaohengDa** [chatchat-space/Langchain-Chatchat#526]
在网上找了一圈，有说升级paddle的，我做了还是没有用，有说安装paddlepaddle的，我找了豆瓣的镜像源，但安装报错cannot detect archive format

**Comment by lichuan6** [comment]
可以去 [paddle 官网](https://www.paddlepaddle.org.cn/) 安装试试，选择 Package, OS, etc，比如下面是 cuda 11.6 的：

```bash
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
-c conda-forge
```

<img width="1021" alt="Screenshot 2023-06-04 at 23 25 09" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/74223747/b9c71938-ca44-4c34-90be-018fdce476ba">
