### ISSUE TITLE
[BUG]  webscoket 接口串行问题（/local_doc_qa/stream-chat/{knowledge_base_id}）

### ISSUE THREAD

**Issue by ferrymo** [chatchat-space/Langchain-Chatchat#527]
**问题描述 / Problem Description**
调用测试发现是接口是单线程，无法实现多人问答
版本为0.1.12
模型为GLM-6b

测试普通接口把接口的方法前缀去除 async 标识 可以实现多线程并行调用，但模型本身好像是堵塞串行的，GLM-6b是不支持并行推理嘛，还是说需要单独去配置。？
修改 /local_doc_qa/stream-chat/{knowledge_base_id} 接口中 很多处使用 了 await 无法直接去除 async
想着使用多进程部署的方式，但运行起来又报告了以下错误

 修改的语句
`
from path import Path
from path import Path
`
报告的错误
`
ERROR:    Error loading ASGI app. Attribute "app" not found in module "api".
`

期望结果
想实现打字机效果并且支持多人问答。

**Comment by cristianohello** [comment]
+1

**Comment by cristianohello** [comment]
请大家重视这个issue！真正使用肯定是多用户并发问答，希望增加此功能！！！

**Comment by ferrymo** [comment]
> 

查了下，GLM-6b模型本身也存在问答串行推理情况

**Comment by glide-the** [comment]
感谢大家对这个问题的关注，目前社区里对并行调用没有比较完美的解决方案，
在dev的c4ee36b8ac629cf53fa86346b250e626a30e0dc7这次的版本中，我们尝试了使用异步线程队列加上收集器来完成并行调用，主线程用来收集，子线程处理任务，这样就可以保持每个线程的任务，**这个代码不要用在生产哦**，会存在的bug就是子线程会被挂起，直到服务器线程被全部占用，
当然这个问题也可以解决，如果你需要结束子线程，你需要在子线程结束的时候put一个停止标识，里面是有一个ListenerToken的定义的，需要在模型那里定义个listenerToken收集，这样就可以判断每个模型的每次预测停止时间了

大家如果有更好的方案可以提个pr

**Comment by ferrymo** [comment]
> 感谢大家对这个问题的关注，目前社区里对并行调用没有比较完美的解决方案， 在dev的c4ee36b8ac629cf53fa86346b250e626a30e0dc7这次的版本中，我们尝试了使用异步线程队列加上收集器来完成并行调用，主线程用来收集，子线程处理任务，这样就可以保持每个线程的任务，**这个代码不要用在生产哦**，会存在的bug就是子线程会被挂起，直到服务器线程被全部占用， 当然这个问题也可以解决，如果你需要结束子线程，你需要在子线程结束的时候put一个停止标识，里面是有一个ListenerToken的定义的，需要在模型那里定义个listenerToken收集，这样就可以判断每个模型的每次预测停止时间了
> 
> 大家如果有更好的方案可以提个pr

好的，感谢回复

**Comment by exceedzhang** [comment]
看到chatglm-6b项目中关于多线程的问题已经有解决方案了，具体可以参考如下网址：
[https://github.com/THUDM/ChatGLM-6B/issues/1160](https://github.com/THUDM/ChatGLM-6B/issues/1160)
