### ISSUE TITLE
[BUG] 使用ptuning微调模型后，问答效果并不好

### ISSUE THREAD

**Issue by zzxs** [chatchat-space/Langchain-Chatchat#530]
### 未调用ptuning
1、在shared.py中自行添加输出语句，确保未调用ptuning微调模型
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/18f6e3bd-22f7-40dd-ae2b-b4bd596e28c6)
2、控制台输出确认未调用
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/7fde7c48-2556-4a69-97d6-6ae844ffacce)
3、实际问答效果
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/3d6aac30-cb4b-4c4f-a313-0aa92365815b)
————————————————————————————————————————————————————
### 调用ptuning
1、在loader.py中自行添加了输出语句，确保调用了ptuning微调模型
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/7cbf424a-fe5a-4538-aa59-8398952d95fd)
2、控制台输出确认加载完成
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/bf5e9f7b-4b31-4072-92d2-8b520592466b)
3、实际问答效果
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/c9ee9bf9-7677-4337-8791-f78a05ca5429)
4、训练用数据
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/4fa430e7-ceb3-457d-8e2f-c3e383e5a827)
————————————————————————————————————————————————————
### ChatGLM官方web_demo2使用ptuning微调模型使用效果
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27863401/f1c2d1c4-6c09-477e-85de-9eaabda034e9)
————————————————————————————————————————————————————
### 结论
ChatGLM官方使用ptuning微调模型效果较好，在引入langchain之后，微调模型对问答影响明显减弱，并且经常性的胡言乱语。例如询问vue的创始人是谁，会回答创始人是法国科学家某某某，或者是日本人某某某。
————————————————————————————————————————————————————
### 疑问
1、上述操作对于ptuning的微调模型是否真的引用成功了？
2、在未导入知识库的前提下，如何加强ptuning模型对问答的指导性？
3、如果ptuning效果注定不好，有更好的训练方式建议吗？

**Comment by gumanchang** [comment]
想咨询下，你使用了ptuning微调后，知识是否有出现遗忘的现象呢？另外咨询下你的微调数据集有多大呀

**Comment by zzxs** [comment]
> 想咨询下，你使用了ptuning微调后，知识是否有出现遗忘的现象呢？另外咨询下你的微调数据集有多大呀

灾难性的遗忘，对于关键字部分完全胡言乱语。实际上官方ptuning微调的模型文件夹中有很多配置文件，而结合langchain的chatglm对于微调模型的仅仅引用了config和模型文件，可能引用ptuning微调模型的逻辑还得优化。

训练集很小，大概上百条问答而已。

**Comment by dangzheng0430** [comment]
想问下加载微调模型时出现这个错误怎么解决呢？

The device_map provided does not give any device for the following parameters: transformer.prefix_encoder.embedding.weight

**Comment by jby20180901** [comment]
> 上

看了一眼glm官方的源代码，也只用了这俩文件而已

**Comment by zzxs** [comment]
> 看了一眼glm官方的源代码，也只用了这俩文件而已

那是我武断了。两边差别太大，让我怀疑是不是同一个模型。

**Comment by HarveyPhoenix** [comment]
> 上述操作对于ptuning的微调模型是否真的引用成功了？

请问这个现在有方法判断么？我也遇到类似的问题，具体运行信息如下。没有说加载模型报错，直接用训练问题问后效果和不用训练前是一样的

```
Loading chatglm-6b...
Loading checkpoint shards: 100%|██████████████████| 8/8 [01:29<00:00, 11.18s/it]
Some weights of ChatGLMForConditionalGeneration were not initialized from the model checkpoint at /mnt/workspace/ChatGLM-6B-main/ptuning/chatglm-6b and are newly initialized: ['transformer.prefix_encoder.embedding.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Loaded the model in 92.47 seconds.
INFO  2023-06-08 21:31:52,274-1d: Load pretrained SentenceTransformer: GanymedeNil/text2vec-large-chinese
WARNING 2023-06-08 21:31:56,486-1d: No sentence-transformers model found with name /root/.cache/torch/sentence_transformers/GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
INFO  2023-06-08 21:32:01,004-1d: 模型已成功重新加载，可以开始对话，或从右侧选择模式后开始对话
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/utils.py", line 911, in __exit__
    matplotlib.use(self._original_backend)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/__init__.py", line 1233, in use
    plt.switch_backend(name)
  File "/usr/local/lib/python3.8/dist-packages/matplotlib/pyplot.py", line 271, in switch_backend
    backend_mod = importlib.import_module(
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'matplotlib_inline'
INFO  2023-06-08 21:32:34,408-1d: flagging: username=5b8315e4610541be8a94e1313
```

**Comment by FURYFOR** [comment]
能请问下如何使用langchian-ChatGLM加载ptuning-v2微调模型吗？已把微调后的config.json和pytorch_model.bin文件放入ptuning-v2文件夹中，但是好像一直未加载微调模型

**Comment by weizhaokang** [comment]
> 能请问下如何使用langchian-ChatGLM加载ptuning-v2微调模型吗？已把微调后的config.json和pytorch_model.bin文件放入ptuning-v2文件夹中，但是好像一直未加载微调模型

我也有同样的问题，现象上看像是未加载微调

**Comment by danny-zhu** [comment]
> 想问下加载微调模型时出现这个错误怎么解决呢？
> 
> The device_map provided does not give any device for the following parameters: transformer.prefix_encoder.embedding.weight

单机多卡跑会遇到这个情况，可以先临时用单卡跑，loader.py中num_gpus = torch.cuda.device_count()，改成num_gpus = 1

**Comment by danny-zhu** [comment]
> 

model_config.py里面的USE_PTUNING_V2参数系统启动时没有加载，启动后手动勾选”使用p-tuning-v2微调过的模型“选项会导致程序无法正常回答问题。可以修改代码让其启动时从配置文件中加载USE_PTUNING_V2，修改models/loader/args.py增加parser.add_argument('--use-ptuning-v2', action='store_true', default=USE_PTUNING_V2,
                    help='Load the use p-tuning-v2 prefixencoder.')

**Comment by tschen666** [comment]
> > 
> 
> model_config.py里面的USE_PTUNING_V2参数系统启动时没有加载，启动后手动勾选”使用p-tuning-v2微调过的模型“选项会导致程序无法正常回答问题。可以修改代码让其启动时从配置文件中加载USE_PTUNING_V2，修改models/loader/args.py增加parser.add_argument('--use-ptuning-v2', action='store_true', default=USE_PTUNING_V2, help='Load the use p-tuning-v2 prefixencoder.')

请问是加在整个args.py中整段代码之前，还是整段代码之后，还是什么特定位置？
