### ISSUE TITLE
RuntimeError: MPS backend out of memory (MPS allocated: 18.00 GB, other allocations: 4.87 MB, max allowed: 18.13 GB)

### ISSUE THREAD

**Issue by Cacuta** [chatchat-space/Langchain-Chatchat#533]
**问题描述**
模型加载之后报错

1. 执行 webui.py
2. 问题出现 :
        RuntimeError: MPS backend out of memory (MPS allocated: 18.00 GB, other allocations: 4.87 MB, max allowed: 18.13 GB). Tried to allocate 256.00 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).

**环境信息**
- langchain-ChatGLM 版本号：V 0.1.14
- 使用的模型：ChatGLM-6B 
- 操作系统及版本 / Operating system and version: Mac OS 13.2.1｜16G内存｜mps模式
- Python 版本 / Python version: 3.10

这个报错我在chatglm-6b的issue[#311](https://github.com/THUDM/ChatGLM-6B/issues/311)里也看到了，但是没有找到解决方法

**Comment by 1mainxh** [comment]
加显存

**Comment by Cacuta** [comment]
@1mainxh 
Mac拆机加内存有点复杂额，上面提到的那个#311，有人提到可能是系统兼容的问题，硬钢内存烧到70G都无解
