### ISSUE TITLE
   使用流式输出的时候，curl调用的格式是什么？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#536]
app.websocket("/local_doc_qa/stream-chat/{knowledge_base_id}")(stream_chat)中的knowledge_base_id应该填什么？？？

curl -X 'POST' \
  'http://127.0.0.1:8000/local_doc_qa/stream-chat/{knowledge_base_id' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "knowledge_base_id": "aaaaaaaaaaaaaaaaaaa",
  "question": "卡塔尔世界杯冠军是谁",
  "history": []
}'

**Comment by imClumsyPanda** [comment]
填本地知识库名称

cristianohello ***@***.***>于2023年6月2日 周五18:48写道：

**Comment by cristianohello** [comment]
@imClumsyPanda 
这个本地知识库名称指的是txt文件名称吧？还是txt转为faiss向量后的文件名称？

**Comment by imClumsyPanda** [comment]
@cristianohello 向量库名称，目前默认选用faiss所以对应vector_store路径下文件夹

**Comment by cristianohello** [comment]
@imClumsyPanda 

比如我本地vector_store有个baoxian_FAISS_20230602_172352向量文件夹。是这样调用吗？
curl -X 'POST' \
  'http://127.0.0.1:8000/local_doc_qa/stream-chat/baoxian_FAISS_20230602_172352' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "knowledge_base_id": "baoxian_FAISS_20230602_172352",
  "question": "卡塔尔世界杯冠军是谁",
  "history": []
}'

**Comment by cristianohello** [comment]
@imClumsyPanda 
这样调用会报错
