### ISSUE TITLE
使用本地 vicuna-7b模型启动错误

### ISSUE THREAD

**Issue by jiyif11** [chatchat-space/Langchain-Chatchat#538]
环境: ubuntu 22.04 cuda 12.1 没有安装nccl，使用rtx2080与m60显卡并行计算

python webui.py --model-dir /root/GPT/models/ --model vicuna-7b --no-remote-model

`loading model config
llm device: cuda
embedding device: cuda
dir: /root/langchain-ChatGLM
flagging username: 2339e08618d140bd96b30758f7616257

Loading vicuna-7b...
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████| 2/2 [00:05<00:00,  2.68s/it]
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/langchain-ChatGLM/webui.py:279 in <module>                                                 │
│                                                                                                  │
│   276 """                                                                                        │
│   277                                                                                            │
│   278 # 初始化消息                                                                               │
│ ❱ 279 model_status = init_model()                                                                │
│   280                                                                                            │
│   281 default_theme_args = dict(                                                                 │
│   282 │   font=["Source Sans Pro", 'ui-sans-serif', 'system-ui', 'sans-serif'],                  │
│                                                                                                  │
│ /root/langchain-ChatGLM/webui.py:105 in init_model                                               │
│                                                                                                  │
│   102 │                                                                                          │
│   103 │   args_dict = vars(args)                                                                 │
│   104 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                  │
│ ❱ 105 │   llm_model_ins = shared.loaderLLM()                                                     │
│   106 │   llm_model_ins.set_history_len(LLM_HISTORY_LEN)                                         │
│   107 │   try:                                                                                   │
│   108 │   │   local_doc_qa.init_cfg(llm_model=llm_model_ins)                                     │
│                                                                                                  │
│ /root/langchain-ChatGLM/models/shared.py:40 in loaderLLM                                         │
│                                                                                                  │
│   37 │   if 'FastChatOpenAILLM' in llm_model_info["provides"]:                                   │
│   38 │   │   loaderCheckPoint.unload_model()                                                     │
│   39 │   else:                                                                                   │
│ ❱ 40 │   │   loaderCheckPoint.reload_model()                                                     │
│   41 │                                                                                           │
│   42 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])             │
│   43 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                               │
│                                                                                                  │
│ /root/langchain-ChatGLM/models/loader/loader.py:402 in reload_model                              │
│                                                                                                  │
│   399 │   │   │   except Exception as e:                                                         │
│   400 │   │   │   │   print("加载PrefixEncoder config.json失败")                                 │
│   401 │   │                                                                                      │
│ ❱ 402 │   │   self.model, self.tokenizer = self._load_model(self.model_name)                     │
│   403 │   │                                                                                      │
│   404 │   │   if self.lora:                                                                      │
│   405 │   │   │   self._add_lora_to_model([self.lora])                                           │
│                                                                                                  │
│ /root/langchain-ChatGLM/models/loader/loader.py:131 in _load_model                               │
│                                                                                                  │
│   128 │   │   │   │   │   │   else:                                                              │
│   129 │   │   │   │   │   │   │   self.device_map = self.chatglm_auto_configure_device_map(num   │
│   130 │   │   │   │   │                                                                          │
│ ❱ 131 │   │   │   │   │   model = dispatch_model(model, device_map=self.device_map)              │
│   132 │   │   │   else:                                                                          │
│   133 │   │   │   │   model = (                                                                  │
│   134 │   │   │   │   │   LoaderClass.from_pretrained(                                           │
│                                                                                                  │
│ /root/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/big_modeling.py:327 in          │
│ dispatch_model                                                                                   │
│                                                                                                  │
│   324 │   if not is_torch_version(">=", "1.9.0"):                                                │
│   325 │   │   raise NotImplementedError("Model dispatching requires torch >= 1.9.0")             │
│   326 │   # Error early if the device map is incomplete.                                         │
│ ❱ 327 │   check_device_map(model, device_map)                                                    │
│   328 │                                                                                          │
│   329 │   if main_device is None:                                                                │
│   330 │   │   if set(device_map.values()) == {"cpu"} or set(device_map.values()) == {"cpu", "d   │
│                                                                                                  │
│ /root/miniconda3/envs/AI/lib/python3.10/site-packages/accelerate/utils/modeling.py:786 in        │
│ check_device_map                                                                                 │
│                                                                                                  │
│    783 │   │   │   ]                                                                             │
│    784 │   if len(all_model_tensors) > 0:                                                        │
│    785 │   │   non_covered_params = ", ".join(all_model_tensors)                                 │
│ ❱  786 │   │   raise ValueError(                                                                 │
│    787 │   │   │   f"The device_map provided does not give any device for the following paramet  │
│    788 │   │   )                                                                                 │
│    789                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: The device_map provided does not give any device for the following parameters: model.embed_tokens.weight,
`
貌似与accelerate有关系 单显卡却不会错误

**Comment by jiyif11** [comment]
> 兄弟这个问题你解决了吗，我也是，单卡是可以的，双卡就没法加载vicuna

还没24G双卡，过几天换48G看看

**Comment by dongyihua543** [comment]
> 兄弟这个问题你解决了吗，我也是，单卡是可以的，双卡就没法加载vicuna

我在双卡条件下也遇到这个问题了。
你们单卡可以加载成功吗？我4090 24G显存，单卡加载vicuna-7b提示内存溢出。

**Comment by dongyihua543** [comment]
> 兄弟这个问题你解决了吗，我也是，单卡是可以的，双卡就没法加载vicuna

我在双卡条件下也遇到这个问题了。我是4090显卡，24G内存，双卡卡加载vicuna-13提示：ValueError: The device_map provided does not give any device for the following 
parameters

**Comment by ye7love7** [comment]
应该要指定map device吧

**Comment by ye7love7** [comment]
有没有大佬看一下这个问题呀？手动指定mapdevice还是用源码的pytorch_model.bin.index.json
