### ISSUE TITLE
为什么会不调用GPU直接调用CPU呢

### ISSUE THREAD

**Issue by xiaohengDa** [chatchat-space/Langchain-Chatchat#539]
我的阿里云配置是16G显存，用默认代码跑webui.py时提示
![16772879f744b32aa87d3201a34e3e6](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/134503417/dc22d925-6b1e-413d-ac36-632a7b2a4bd6)
想问一下这是为什么，我怎么设置用GPU跑呢？LLM用的是GLM-6B-INT4

**Comment by mlwei1** [comment]
一样的问题，好像是torch默认是cpu版

**Comment by keene06** [comment]
torch版本不对或者cuda未识别，torch.cuda.is_available()测试下
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/28340341/159e2bb1-2aa1-4de0-a26d-7e0f2b389632)

**Comment by xiaohengDa** [comment]
> torch版本不对或者cuda未识别，torch.cuda.is_available()测试下 ![image](https://user-images.githubusercontent.com/28340341/243047775-159e2bb1-2aa1-4de0-a26d-7e0f2b389632.png)

确实结果是false,我的cuda是12.0，torch是2.0.1+cu118，我在torch官网上没找到支持cuda 12.0的torch版本，是不是只能降cuda的版本了？

**Comment by mlwei1** [comment]
pip uninstall torch,然后去torch官网下载，requirements.txt默认的torch是cpu版本的

**Comment by xiaohengDa** [comment]
> pip uninstall torch,然后去torch官网下载，requirements.txt默认的torch是cpu版本的

问一下您通过这种方式解决了吗？我在pytorch的官网上下载的了适配cuda 11.7版本torch之后还是一样的

**Comment by mlwei1** [comment]
> 

我是这么解决的，你是不是cuda本身没装

**Comment by cmdr123** [comment]
去官网下载cuda找到符合你python的版本，记得是cu开头的

**Comment by qq7286590** [comment]
就是torch版本不对，我换了torch,可以调用GPU了

**Comment by yiren97** [comment]
> > torch版本不对或者cuda未识别，torch.cuda.is_available()测试下 ![image](https://user-images.githubusercontent.com/28340341/243047775-159e2bb1-2aa1-4de0-a26d-7e0f2b389632.png)
> 
> 确实结果是false,我的cuda是12.0，torch是2.0.1+cu118，我在torch官网上没找到支持cuda 12.0的torch版本，是不是只能降cuda的版本了？

torch2.0对应 cuda 11.7没问题，我试过这个
