### ISSUE TITLE
上传多个文件时会互相覆盖

### ISSUE THREAD

**Issue by xiaohengDa** [chatchat-space/Langchain-Chatchat#541]
1、在同一个知识库中上传多个文件时会互相覆盖，无法结合多个文档的知识，有大佬知道怎么解决吗？
2、加载本地模型时(LLaMMa-7b-2M)显示加载成功但一对话就显示error,也没有报错。执行时checkpoint也在加载了，这种是显存不够的原因吗？

**Comment by xiaohengDa** [comment]
又测试了一下，似乎txt文件才会互相覆盖，PDF还好。但还有个问题是不同资料库的数据会串，如果建立本地资料库的话会很不方便

**Comment by danny-zhu** [comment]
> 又测试了一下，似乎txt文件才会互相覆盖，PDF还好。但还有个问题是不同资料库的数据会串，如果建立本地资料库的话会很不方便

我也是遇到了大文本上传的难题，内存32G，上传超过50M的文本就会内存溢出，改成多个小文本上传又会覆盖
