### ISSUE TITLE
程序以API模式启动的时候，如何才能让接口以stream模式被调用呢？

### ISSUE THREAD

**Issue by includepanda** [chatchat-space/Langchain-Chatchat#546]
作者您好，我在以API模式进行程序启动后，我发现接口响应时间很长，怎么样才能让接口以stream模式被调用呢？我想实现像webui模式的回答那样

**Comment by ywm12345** [comment]
应该需要将接口写成流式的并前端也需要写适配流的页面

**Comment by cristianohello** [comment]
+1.希望下个版本能出来这种功能。

**Comment by xxentropy** [comment]
+1

**Comment by hzg0601** [comment]
想调用流式问答的接口，需要用支持websocket的api工具，比如postman,insomnia等，建议使用开源的insomnia。
