### ISSUE TITLE
提供system message配置，以便于让回答不要超出知识库范围

### ISSUE THREAD

**Issue by myadsdsss** [chatchat-space/Langchain-Chatchat#549]
**功能描述 / Feature Description**
model_config.py,除了定义PROMPT_TEMPLATE,再增加定义system message

**解决的问题 / Problem Solved**
将system message和PROMPT_TEMPLATE混在一起，会导致LLM回答超出知识库范围的东西，建议将system message和知识库分开。这样就减少了回答知识库以外的内容的概率 。

**实现建议 / Implementation Suggestions**
先将system message送到模型，然后再将搜索到的相关知识和问题送给模型。

**替代方案 / Alternative Solutions**
无

**其他信息 / Additional Information**
在gpt4上测试，system message和PROMPT_TEMPLATE混合也会出现回答知识库以外的内容，分开就不会。

**Comment by sinopec** [comment]
chatglm支不支持systemmessage是个问题。。。
