### ISSUE TITLE
[FEATURE] 我看代码文件中有一个ali_text_splitter.py，为什么不用他这个文本分割器了？

### ISSUE THREAD

**Issue by jby20180901** [chatchat-space/Langchain-Chatchat#554]
我看代码文件中有一个ali_text_splitter.py，为什么不用他这个文本分割器了？

**Comment by imClumsyPanda** [comment]
可以用，但每次使用这个模型需要联网请求数据

**Comment by jby20180901** [comment]
> 

那么我可以下载到本地么？另外它的性能会不会比后来的Chinese_text_splitter.py好呢？

**Comment by imClumsyPanda** [comment]
模型下载到本地也仍然会有联网请求发出，咱也不知道请求的是啥，咱也不敢问
