### ISSUE TITLE
加载文档函数报错

### ISSUE THREAD

**Issue by baolixiong** [chatchat-space/Langchain-Chatchat#557]
def load_file(filepath, sentence_size=SENTENCE_SIZE):
    if filepath.lower().endswith(".md"):
        loader = UnstructuredFileLoader(filepath, mode="elements")
        docs = loader.load()
    elif filepath.lower().endswith(".txt"):
        loader = TextLoader(filepath, autodetect_encoding=True)
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(textsplitter)
    elif filepath.lower().endswith(".pdf"):
        loader = UnstructuredPaddlePDFLoader(filepath)
        textsplitter = ChineseTextSplitter(pdf=True, sentence_size=sentence_size)
        docs = loader.load_and_split(textsplitter)
    elif filepath.lower().endswith(".jpg") or filepath.lower().endswith(".png"):
        loader = UnstructuredPaddleImageLoader(filepath, mode="elements")
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(text_splitter=textsplitter)
    else:
        loader = UnstructuredFileLoader(filepath, mode="elements")
        textsplitter = ChineseTextSplitter(pdf=False, sentence_size=sentence_size)
        docs = loader.load_and_split(text_splitter=textsplitter)
    write_check_file(filepath, docs)
    return docs

使用webui.py运行程序时，加载文档没问题，但是把load_file函数单独拿出来加载文档就会报错， docs = loader.load_and_split(text_splitter=textsplitter) 这段会报：zipfile.BadZipFile: File is not a zip file  。 请问这是什么原因

**Comment by denganhui** [comment]
我碰见了同样的问题，现在解决了没，兄台

**Comment by denganhui** [comment]
我换了一种加载器，这样ok
from langchain.document_loaders import TextLoader
from langchain.text_splitter import CharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import FAISS

filepath = "./1.txt"
sources = []
loader = TextLoader(filepath)
loader.encoding = "utf-8"
sources.extend(loader.load_and_split())


splitter = CharacterTextSplitter(chunk_size=200, chunk_overlap=50)
next_docs = splitter.split_documents(sources)
print(next_docs)
