### ISSUE TITLE
知识库对长文的知识相关度匹配不太理想有何优化方向

### ISSUE THREAD

**Issue by lazecoding** [chatchat-space/Langchain-Chatchat#563]
我们可能录入一个文章有 1W 字，里面涉及这个文章主题的很多角度问题，我们针对他提问，他相关度匹配的内容和实际我们需要的答案相差很大怎么办。

- 比如 【大标题】 的 XXX，正文中往往出现很多和大标题相关的内容，导致 XXX 相关的内容很难匹配到。

**Comment by YidaHu** [comment]
我也遇到类似问题，求解决方案

**Comment by soultrans** [comment]
同问

**Comment by Helenailse1** [comment]
同问 有大佬实现了吗

**Comment by SopmmmodII** [comment]
我也遇到这种问题，现在想法是按照标题级别把文章整理成树形结构后用LLM对每段生成摘要或者关键词，不知道效果如何
