### ISSUE TITLE
使用stream-chat函数进行流式输出的时候，能使用curl调用吗？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#565]
为什么下面这样调用会报错？？？

curl -X 'POST' \
  'http://127.0.0.1:8000/local_doc_qa/stream-chat/baoxian_FAISS_20230602_172352' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "question": "卡塔尔世界杯冠军是谁",
  "history": [],
  "knowledge_base_id": "baoxian_FAISS_20230602_172352",
}'

**Comment by ywm12345** [comment]
自己的写的stream-chat接口吗

**Comment by cristianohello** [comment]
@ywm12345 
不是，api.py自带的函数。你解决了吗？

**Comment by ucas010** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/464#issuecomment-1583922143
