### ISSUE TITLE
现在的添加知识库，文件多了总是报错，也不知道自己加载了哪些文件，报错后也不知道是全部失败还是一部分成功；希望能有个加载指定文件夹作为知识库的功能

### ISSUE THREAD

**Issue by tianheil3** [chatchat-space/Langchain-Chatchat#574]
**功能描述 / Feature Description**
现在的添加知识库，文件多了总是报错，也不知道自己加载了哪些文件，报错后也不知道是全部失败还是一部分成功；希望能有个加载指定文件夹作为知识库的功能；
已经被折磨好几天了，上传总报错，报错后也不知道加载了哪些东西，挂着一晚上然后还在加载，然后还报错的感觉真是。。。。。。

**Comment by tianheil3** [comment]
希望加载知识库这个功能能独立出来，然后报错了也能继续上次未完成的加载

**Comment by Zhaikuku** [comment]
hi, 或许你应该看看这个PR https://github.com/imClumsyPanda/langchain-ChatGLM/pull/471#event-9357405283。

目前功能已经合并至此版本(https://github.com/imClumsyPanda/langchain-ChatGLM/tree/v0.1.14 )。
