### ISSUE TITLE
加载本地moss模型报错Can't instantiate abstract class MOSSLLM with abstract methods _history_len

### ISSUE THREAD

**Issue by zhanaali** [chatchat-space/Langchain-Chatchat#578]
(vicuna) ps@ps[13:56:20]:/data/chat/langchain-ChatGLM2/langchain-ChatGLM-0.1.13$ python webui.py  --model-dir local_models --model moss --no-remote-model
INFO  2023-06-08 13:56:28,038-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /data/chat/langchain-ChatGLM2/langchain-ChatGLM-0.1.13
flagging username: 7ab3fa902a0243dab3564ddb86e42266

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /usr/local/cuda-12.0/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 120
CUDA SETUP: Loading binary /home/ps/anaconda3/envs/vicuna/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda120.so...
Loading moss...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:14<00:00,  3.53s/it]
Loaded the model in 176.98 seconds.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/chat/langchain-ChatGLM2/langchain-ChatGLM-0.1.13/webui.py:253 in <module>                  │
│                                                                                                  │
│   250                                                                                            │
│   251 args_dict = vars(args)                                                                     │
│   252 shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                      │
│ ❱ 253 llm_model_ins = shared.loaderLLM()                                                         │
│   254 llm_model_ins.set_history_len(LLM_HISTORY_LEN)                                             │
│   255                                                                                            │
│   256 model_status = init_model(llm_model=llm_model_ins)                                         │
│                                                                                                  │
│ /data/chat/langchain-ChatGLM2/langchain-ChatGLM-0.1.13/models/shared.py:42 in loaderLLM          │
│                                                                                                  │
│   39 │   loaderCheckPoint.reload_model()                                                         │
│   40 │                                                                                           │
│   41 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])             │
│ ❱ 42 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                               │
│   43 │   return modelInsLLM                                                                      │
│   44                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't instantiate abstract class MOSSLLM with abstract methods _history_len

**Comment by Salierioo** [comment]
我也遇到了这个问题，请问解决了吗

**Comment by andy95201915** [comment]
我也遇到了 参考了#447 问题有解决
