### ISSUE TITLE
无法打开gradio的页面

### ISSUE THREAD

**Issue by forrestneo** [chatchat-space/Langchain-Chatchat#58]
$ python webui.py
/home/zsd/.local/lib/python3.10/site-packages/gradio/components.py:164: UserWarning: Unknown style parameter: height
  warnings.warn(f"Unknown style parameter: {key}")
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by fxths** [comment]
我遇到了相同的问题。在README的常见问题中似乎也没有看到解答。现在这个问题有解决方案了吗？

**Comment by zRzRzRzRzRzRzR** [comment]
新版本都是正常的哦，可以看看最新的版本
