### ISSUE TITLE
启动python cli_demo.py --model chatglm-6b-int4-qe报错

### ISSUE THREAD

**Issue by kuntali** [chatchat-space/Langchain-Chatchat#585]
下载好模型，和相关依赖环境，之间运行`python cli_demo.py --model chatglm-6b-int4-qe`报错了：
INFO  2023-06-09 01:24:49,523-1d: 
loading model config
llm device: cpu
embedding device: cpu
dir: /opt/langchain-ChatGLM
flagging username: cf3312e7301244a79066a90d54b3dae3

INFO  2023-06-09 01:24:50,323-1d: NumExpr defaulting to 8 threads.
/root/anaconda3/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/root/anaconda3/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/root/anaconda3/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/root/anaconda3/envs/langchain/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Loading THUDM/chatglm-6b-int4-qe...
Warning: self.llm_device is False.
This means that no use GPU  bring to be load CPU mode

No compiled kernel found.
Compiling kernels : /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a756e07698483872c5c070eee/quantization_kernels_parallel.c
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a756e07698483872c5c070eee/quantization_kernels_parallel.c -shared -o /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a756e07698483872c5c070eee/quantization_kernels_parallel.so
Kernels compiled : /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a756e07698483872c5c070eee/quantization_kernels_parallel.so
Load kernel : /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a756e07698483872c5c070eee/quantization_kernels_parallel.so
Setting CPU quantization kernel threads to 4
Using quantization cache
Applying quantization to glm layers
------
RuntimeError: Only Tensors of floating point and complex dtype can require gradients
以下是堆栈信息：
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /opt/langchain-ChatGLM/cli_demo.py:56 in <module>                                                │
│                                                                                                  │
│   53                                                                                             │
│   54                                                                                             │
│   55 if __name__ == "__main__":                                                                  │
│ ❱ 56 │   main()                                                                                  │
│   57                                                                                             │
│                                                                                                  │
│ /opt/langchain-ChatGLM/cli_demo.py:19 in main                                                    │
│                                                                                                  │
│   16 │   args = parser.parse_args()                                                              │
│   17 │   args_dict = vars(args)                                                                  │
│   18 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                   │
│ ❱ 19 │   llm_model_ins = shared.loaderLLM()                                                      │
│   20 │   llm_model_ins.history_len = LLM_HISTORY_LEN                                             │
│   21 │                                                                                           │
│   22 │   local_doc_qa = LocalDocQA()                                                             │
│                                                                                                  │
│ /opt/langchain-ChatGLM/models/shared.py:40 in loaderLLM                                          │
│                                                                                                  │
│   37 │   if 'FastChatOpenAILLM' in llm_model_info["provides"]:                                   │
│   38 │   │   loaderCheckPoint.unload_model()                                                     │
│   39 │   else:                                                                                   │
│ ❱ 40 │   │   loaderCheckPoint.reload_model()                                                     │
│   41 │                                                                                           │
│   42 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])             │
│   43 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                               │
│                                                                                                  │
│ /opt/langchain-ChatGLM/models/loader/loader.py:402 in reload_model                               │
│                                                                                                  │
│   399 │   │   │   except Exception as e:                                                         │
│   400 │   │   │   │   print("加载PrefixEncoder config.json失败")                                 │
│   401 │   │                                                                                      │
│ ❱ 402 │   │   self.model, self.tokenizer = self._load_model(self.model_name)                     │
│   403 │   │                                                                                      │
│   404 │   │   if self.lora:                                                                      │
│   405 │   │   │   self._add_lora_to_model([self.lora])                                           │
│                                                                                                  │
│ /opt/langchain-ChatGLM/models/loader/loader.py:206 in _load_model                                │
│                                                                                                  │
│   203 │   │   │   print(                                                                         │
│   204 │   │   │   │   "Warning: self.llm_device is False.\nThis means that no use GPU  bring t   │
│   205 │   │   │   params = {"low_cpu_mem_usage": True, "torch_dtype": torch.float32, "trust_re   │
│ ❱ 206 │   │   │   model = LoaderClass.from_pretrained(checkpoint, **params).to(self.llm_device   │
│   207 │   │                                                                                      │
│   208 │   │   # Loading the tokenizer                                                            │
│   209 │   │   if type(model) is transformers.LlamaForCausalLM:                                   │
│                                                                                                  │
│ /root/anaconda3/envs/langchain/lib/python3.10/site-packages/transformers/models/auto/auto_factor │
│ y.py:462 in from_pretrained                                                                      │
│                                                                                                  │
│   459 │   │   │   model_class = get_class_from_dynamic_module(                                   │
│   460 │   │   │   │   class_ref, pretrained_model_name_or_path, **hub_kwargs, **kwargs           │
│   461 │   │   │   )                                                                              │
│ ❱ 462 │   │   │   return model_class.from_pretrained(                                            │
│   463 │   │   │   │   pretrained_model_name_or_path, *model_args, config=config, **hub_kwargs,   │
│   464 │   │   │   )                                                                              │
│   465 │   │   elif type(config) in cls._model_mapping.keys():                                    │
│                                                                                                  │
│ /root/anaconda3/envs/langchain/lib/python3.10/site-packages/transformers/modeling_utils.py:2611  │
│ in from_pretrained                                                                               │
│                                                                                                  │
│   2608 │   │   │   init_contexts.append(init_empty_weights())                                    │
│   2609 │   │                                                                                     │
│   2610 │   │   with ContextManagers(init_contexts):                                              │
│ ❱ 2611 │   │   │   model = cls(config, *model_args, **model_kwargs)                              │
│   2612 │   │                                                                                     │
│   2613 │   │   # Check first if we are `from_pt`                                                 │
│   2614 │   │   if use_keep_in_fp32_modules:                                                      │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a7 │
│ 56e07698483872c5c070eee/modeling_chatglm.py:1032 in __init__                                     │
│                                                                                                  │
│   1029 │   │   self.quantized = False                                                            │
│   1030 │   │                                                                                     │
│   1031 │   │   if self.config.quantization_bit:                                                  │
│ ❱ 1032 │   │   │   self.quantize(self.config.quantization_bit, self.config.quantization_embeddi  │
│   1033 │                                                                                         │
│   1034 │   def get_output_embeddings(self):                                                      │
│   1035 │   │   return self.lm_head                                                               │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a7 │
│ 56e07698483872c5c070eee/modeling_chatglm.py:1407 in quantize                                     │
│                                                                                                  │
│   1404 │   │   self.config.quantization_bit = bits                                               │
│   1405 │   │   self.config.quantization_embeddings = quantize_embeddings                         │
│   1406 │   │                                                                                     │
│ ❱ 1407 │   │   self.transformer = quantize(self.transformer, bits, use_quantization_cache=use_q  │
│   1408 │   │                                                                                     │
│   1409 │   │   if self.device == torch.device("cpu"):                                            │
│   1410 │   │   │   dtype = torch.float32                                                         │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a7 │
│ 56e07698483872c5c070eee/quantization.py:448 in quantize                                          │
│                                                                                                  │
│   445 │   print("Applying quantization to glm layers")                                           │
│   446 │                                                                                          │
│   447 │   for layer in model.layers:                                                             │
│ ❱ 448 │   │   layer.attention.query_key_value = QuantizedLinearWithPara(                         │
│   449 │   │   │   weight_tensor=layer.attention.query_key_value.weight.to(current_device),       │
│   450 │   │   │   bias_tensor=layer.attention.query_key_value.bias,                              │
│   451 │   │   │   in_features=layer.attention.query_key_value.in_features,                       │
│                                                                                                  │
│ /root/.cache/huggingface/modules/transformers_modules/THUDM/chatglm-6b-int4-qe/977d9df4cfae6b7a7 │
│ 56e07698483872c5c070eee/quantization.py:324 in __init__                                          │
│                                                                                                  │
│   321 │   │   │   │   if weight_bit_width == 4:                                                  │
│   322 │   │   │   │   │   self.weight = compress_int4_weight(self.weight)                        │
│   323 │   │   │                                                                                  │
│ ❱ 324 │   │   │   self.weight = Parameter(self.weight.to(kwargs["device"]), requires_grad=Fals   │
│   325 │   │   │   self.weight_scale = Parameter(self.weight_scale.to(kwargs["device"]), requir   │
│   326 │   │                                                                                      │
│   327 │   │   if bias_tensor is not None:                                                        │
│                                                                                                  │
│ /root/anaconda3/envs/langchain/lib/python3.10/site-packages/torch/nn/modules/module.py:1632 in   │
│ __setattr__                                                                                      │
│                                                                                                  │
│   1629 │   │   │   │   raise AttributeError(                                                     │
│   1630 │   │   │   │   │   "cannot assign parameters before Module.__init__() call")             │
│   1631 │   │   │   remove_from(self.__dict__, self._buffers, self._modules, self._non_persisten  │
│ ❱ 1632 │   │   │   self.register_parameter(name, value)                                          │
│   1633 │   │   elif params is not None and name in params:                                       │
│   1634 │   │   │   if value is not None:                                                         │
│   1635 │   │   │   │   raise TypeError("cannot assign '{}' as parameter '{}' "                   │
│                                                                                                  │
│ /root/anaconda3/envs/langchain/lib/python3.10/site-packages/accelerate/big_modeling.py:108 in    │
│ register_empty_parameter                                                                         │
│                                                                                                  │
│   105 │   │   if param is not None:                                                              │
│   106 │   │   │   param_cls = type(module._parameters[name])                                     │
│   107 │   │   │   kwargs = module._parameters[name].__dict__                                     │
│ ❱ 108 │   │   │   module._parameters[name] = param_cls(module._parameters[name].to(device), **   │
│   109 │                                                                                          │
│   110 │   def register_empty_buffer(module, name, buffer):                                       │
│   111 │   │   old_register_buffer(module, name, buffer)                                          │
│                                                                                                  │
│ /root/anaconda3/envs/langchain/lib/python3.10/site-packages/torch/nn/parameter.py:36 in __new__  │
│                                                                                                  │
│    33 │   │   if type(data) is torch.Tensor or type(data) is Parameter:                          │
│    34 │   │   │   # For ease of BC maintenance, keep this path for standard Tensor.              │
│    35 │   │   │   # Eventually (tm), we should change the behavior for standard Tensor to matc   │
│ ❱  36 │   │   │   return torch.Tensor._make_subclass(cls, data, requires_grad)                   │
│    37 │   │                                                                                      │
│    38 │   │   # Path for custom tensors: set a flag on the instance to indicate parameter-ness   │
│    39 │   │   t = data.detach().requires_grad_(requires_grad)                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by ngbruce** [comment]
这个 qe版本的模型好像很久每更新了，用官方的 int4 模型吧。
