### ISSUE TITLE
[FEATURE] 能否屏蔽paddle，我不需要OCR，效果差依赖环境还很复杂

### ISSUE THREAD

**Issue by liaoweiguo** [chatchat-space/Langchain-Chatchat#587]
希望能不依赖paddle

**Comment by razIove** [comment]
`loader/pdf_loader.py` 中注释掉32-41行即可


`"""Loader that loads image files."""
from typing import List

from langchain.document_loaders.unstructured import UnstructuredFileLoader
from paddleocr import PaddleOCR
import os
import fitz
import nltk
from configs.model_config import NLTK_DATA_PATH

nltk.data.path = [NLTK_DATA_PATH] + nltk.data.path

class UnstructuredPaddlePDFLoader(UnstructuredFileLoader):
    """Loader that uses unstructured to load image files, such as PNGs and JPGs."""

    def _get_elements(self) -> List:
        def pdf_ocr_txt(filepath, dir_path="tmp_files"):
            full_dir_path = os.path.join(os.path.dirname(filepath), dir_path)
            if not os.path.exists(full_dir_path):
                os.makedirs(full_dir_path)
            ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=False, show_log=False)
            doc = fitz.open(filepath)
            txt_file_path = os.path.join(full_dir_path, f"{os.path.split(filepath)[-1]}.txt")
            img_name = os.path.join(full_dir_path, 'tmp.png')
            with open(txt_file_path, 'w', encoding='utf-8') as fout:
                for i in range(doc.page_count):
                    page = doc[i]
                    text = page.get_text("")
                    fout.write(text)
                    fout.write("\n")
                    # no  ocr
                    # img_list = page.get_images()
                    # for img in img_list:
                    #     pix = fitz.Pixmap(doc, img[0])
                    #     if pix.n - pix.alpha >= 4:
                    #         pix = fitz.Pixmap(fitz.csRGB, pix)
                    #     pix.save(img_name)

                    #     result = ocr.ocr(img_name)
                    #     ocr_result = [i[1][0] for line in result for i in line]
                    #     fout.write("\n".join(ocr_result))`

**Comment by liaoweiguo** [comment]
感觉可以做一个配置

**Comment by cristianohello** [comment]
+1，做个配置更好

**Comment by zyhui98** [comment]
对啊

**Comment by zRzRzRzRzRzRzR** [comment]
最新版本将会增加这个配置，感谢issue
