### ISSUE TITLE
我在上传本地知识库时提示KeyError: 'name'错误，本地知识库都是.txt文件，文件数量大约是2000+。

### ISSUE THREAD

**Issue by dongyihua543** [chatchat-space/Langchain-Chatchat#597]
<img width="649" alt="KError" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/59411575/1ecc8182-aeee-4a0a-bbc3-74c2f1373f2d">

**Comment by ucas010** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/589

**Comment by ucas010** [comment]
文档数量太多了？？？

**Comment by dongyihua543** [comment]
不太清楚啊，个人感觉不至于吧？文件太多和报这个错误没有什么必然联系吧？

**Comment by dongyihua543** [comment]
> 这错误看起来更像是gradio本身的问题，检查一下安装的gradio版本根requirements.txt里是不是一致吧

我安装的是gradio==3.28.3，和requirements中的保持一致的。
