### ISSUE TITLE
支持word，那word里面的图片正常显示吗？

### ISSUE THREAD

**Issue by better319** [chatchat-space/Langchain-Chatchat#60]
如题，刚刚从隔壁转过来的，想先了解下

**Comment by imClumsyPanda** [comment]
目前都是加载文本的功能，暂时还没加入读图和ocr

**Comment by imClumsyPanda** [comment]
可以参考 langchain 文档中关于 UnstructuredFileLoader 的介绍，我的理解是只有提取文奔。

better319 ***@***.***>于2023年4月12日 周三16:40写道：

**Comment by geolvr** [comment]
> 不读图和ocr。就是直接把word里面有的部分插图，作为内容的一部分显示出来。 因为我看您的说明里面说是支持word格式的

请问现在知道如何把word文档中的图片显示出来了吗？我的需求和您一样，不要求理解图像内容，只需要知道文档的某某位置有图就行了。比如把图片作为一个特殊的token【PIC】，那文本可能就是 “如下图所示：【PIC】\n从以上图片中能看出...”。

**Comment by chenwenfeng** [comment]
同样需求  链接也会丢失

**Comment by zRzRzRzRzRzRzR** [comment]
目前不支持图片，图片的读取和分析暂时还不会更新，要等之后的版本

**Comment by weiwuxian1998** [comment]
可以将word转换为html格式，图片转成base64在markdown中展示
