### ISSUE TITLE
model_config.py中有vicuna-13b-hf模型的配置信息，但是好像还是不可用？

### ISSUE THREAD

**Issue by dongyihua543** [chatchat-space/Langchain-Chatchat#600]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/59411575/8c0097b6-3b5e-4085-948c-018675003e8e)

**Comment by cristianohello** [comment]
@dongyihua543 
你在哪下载的权重？有地址吗？需要手动下载权重更好

**Comment by Data2Me** [comment]
在哪里下载vicuna-13b的权重？

**Comment by dongyihua543** [comment]
> @dongyihua543 你在哪下载的权重？有地址吗？需要手动下载权重更好

https://huggingface.co/TheBloke/vicuna-13B-1.1-HF/tree/main?doi=true
我在这里下载的，但是用不起来。

**Comment by dongyihua543** [comment]
> 在哪里下载vicuna-13b的权重？

https://huggingface.co/TheBloke/vicuna-13B-1.1-HF/tree/main?doi=true
我在这里下载的，但是用不起来。

**Comment by cristianohello** [comment]
@dongyihua543 @imClumsyPanda 

https://huggingface.co/TheBloke/vicuna-13B-1.1-HF/tree/main?doi=true
这个地址下载的是需要结合llama权重进行转换成vicuna权重吧？

**Comment by Maxliag** [comment]
运行成功了吗

**Comment by bruceye777** [comment]
https://huggingface.co/lmsys/vicuna-13b-v1.3
这个可以直接拿来用，不过回答效果感觉比较差
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/41668200/ac23f8b0-e2bc-4775-a884-d5267ddc4c0a)
