### ISSUE TITLE
ImportError: Using SOCKS proxy, but the 'socksio' package is not installed. Make sure to install httpx using `pip install httpx[socks]`.

### ISSUE THREAD

**Issue by archerdong** [chatchat-space/Langchain-Chatchat#605]
应该代理问题，但是尝试了好多方法都解决不了，
首先排除:
unset http_proxy unset https_proxy

**Comment by Lsnsh** [comment]
And `unset all_proxy`

**Comment by jifeng35** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8026
I think you guys may need this. :)
