### ISSUE TITLE
[FEATURE] API能实现上传文件夹的功能么？

### ISSUE THREAD

**Issue by ucas010** [chatchat-space/Langchain-Chatchat#612]
用户懒得全选所有的文件，就想上传个文件夹，请问下API能实现这个功能么？
web端是支持这个功能的。

**Comment by moolean** [comment]
langchain官方文档有https://python.langchain.com/en/latest/modules/indexes/document_loaders/examples/file_directory.html
直接改loader可能就可以，我没有测试过

**Comment by ucas010** [comment]
@moolean 在哪里修改啊，大佬

**Comment by moolean** [comment]
> @moolean 在哪里修改啊，大佬

chains/local_doc_qa.py 
         def load_file(filepath, sentence_size=SENTENCE_SIZE):
这里面加一个条件判断，loader换成DirectoryLoader()
