### ISSUE TITLE
[BUG] python webui.py提示非法指令

### ISSUE THREAD

**Issue by anotyzwj** [chatchat-space/Langchain-Chatchat#615]
(/data/conda-langchain [root@chatglm langchain-ChatGLM]# python webui.py  
INFO  2023-06-13 17:34:41,686-1d: 
loading model config
llm device: cpu
embedding device: cpu
dir: /data/langchain-ChatGLM
flagging username: 117de30765674f118b2a9539a60817ce

非法指令

--------------
Python版本 3.8.13
尝试过重新clone代码,配置环境,升级更高版本的python等都有此问题,请问该如何排查呢?

**Comment by hzg0601** [comment]
你这个信息也太模糊了，它应该不会给你抛出“非法指令”这样的结果吧

**Comment by Sunjoec** [comment]
我也是这个错误 
系统：centos6.5
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/106213126/bde6194d-dab8-4876-8886-646bd4cfc77b)

**Comment by anotyzwj** [comment]
> 你这个信息也太模糊了，它应该不会给你抛出"非法指令"这样的结果吧

确实是直接提示的"非法指令",没有其他的任何提示
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/56428722/a2e75a5a-dbeb-4d32-b18f-5ab5ffb8eee4)

**Comment by anotyzwj** [comment]
> 我也是这个错误 系统：centos6.5 ![图像](https://user-images.githubusercontent.com/106213126/245662639-bde6194d-dab8-4876-8886-646bd4cfc77b.png)

我的系统是centos 7.6,有什么排查方向吗

**Comment by Sunjoec** [comment]
我以为是系统版本问题，你的是7.6那可能不是了

**Comment by hzg0601** [comment]
flagging username这些信息是model_config.py里打印的，按正常运行，接下来就是打印模型加载信息，但没有。这说明，问题出在webui.py的第7-12行之间，我怀疑是依赖的库版本出了问题，我建议你们在webui.py的第7-12行之间，每个import之下都输出一段打印信息，比如在nltk下增加一行print("加载nltk")，然后就可以定位到对应的文件或者库，看看库的版本是不是正确，比如torch需要安装支持cuda的版本，等等

**Comment by hzg0601** [comment]
最好还是查看一下，你们的安装包里有没有手动安装的，如果有，这些手动安装的包跟python版本、系统平台、芯片类型、cuda版本是不是一致。
以及系统环境变量里，PATH是不是存在冲突的路径

**Comment by anotyzwj** [comment]
> flagging username这些信息是model_config.py里打印的，按正常运行，接下来就是打印模型加载信息，但没有。这说明，问题出在webui.py的第7-12行之间，我怀疑是依赖的库版本出了问题，我建议你们在webui.py的第7-12行之间，每个import之下都输出一段打印信息，比如在nltk下增加一行print("加载nltk")，然后就可以定位到对应的文件或者库，看看库的版本是不是正确，比如torch需要安装支持cuda的版本，等等

按照你的方式我进行了一下排查,发现是  from chains.local_doc_qa import LocalDocQA  这一步出现了问题,进一步发现

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/56428722/7dc9fe05-3c33-4993-b1b4-42b72b19476c)

**Comment by hzg0601** [comment]
我刚刚看了下，master分支似乎更新了MyFAISS,你pull一下，然后运行试试

**Comment by xibok** [comment]
> 我刚刚看了下，master分支似乎更新了MyFAISS,你pull一下，然后运行试试

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/37209971/e46b1d9e-48e9-483c-8a70-8c367e9cb00a)

无论是0.1.15、0.1.16、还是dev版本都遇到了这个问题

**Comment by hzg0601** [comment]
你拉取的代码里有没有vectorstores这个文件夹？

**Comment by hzg0601** [comment]
把文件目录结构截个图发来看看

**Comment by xibok** [comment]
> 你拉取的代码里有没有vectorstores这个文件夹？

有的

**Comment by xibok** [comment]
> 把文件目录结构截个图发来看看

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/37209971/70cc1018-4195-45c3-9ecc-b2bfe8470e6d)

**Comment by xibok** [comment]
> 你拉取的代码里有没有vectorstores这个文件夹？

不是MyFAISS的问题 我再往下print

**Comment by hzg0601** [comment]
> > 你拉取的代码里有没有vectorstores这个文件夹？
> 
> 不是MyFAISS的问题 我再往下print

我刚刚重新读了一下代码逻辑，是我理解错了，sorry。。！问题不一定出在webui.py的第7-12行之间，你能使用vscode的远程开发功能吗?如果可以你可以在vscode里调试，不必一步步打印，

**Comment by hzg0601** [comment]
如果不会的话，这里有教程
https://zhuanlan.zhihu.com/p/143146239

**Comment by hzg0601** [comment]
> > 你拉取的代码里有没有vectorstores这个文件夹？
> 
> 不是MyFAISS的问题 我再往下print

hzg0601@163.com，如果有进一步的信息，可以直接发邮件给我，抱歉浪费了你这么多时间。。。

**Comment by xibok** [comment]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/37209971/4b7a5992-a041-4367-bb1e-b7ab30420701)

是paddleocr的问题
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/37209971/83828801-370a-4e6e-b030-824914dddd95)

**Comment by hzg0601** [comment]
> ![image](https://user-images.githubusercontent.com/37209971/246361669-4b7a5992-a041-4367-bb1e-b7ab30420701.png)
> 
> 是paddleocr的问题 ![image](https://user-images.githubusercontent.com/37209971/246362687-83828801-370a-4e6e-b030-824914dddd95.png)

你最后解决了吗？

**Comment by Sunjoec** [comment]
可以尝试替换下不带avx指令集的paddle  https://www.paddlepaddle.org.cn/whl/linux/openblas/noavx/stable.html

**Comment by Crescentz** [comment]
> 不带avx指令集的paddle
请问这里面的都是不带avx指令集的吗

**Comment by wuyabing** [comment]
最后这个问题解决了，我使用的操作系统centos7.3、python3.10，执行【 python3 loader/image_loader.py】，也是报【非法指令】错误，如果有解决办法，请指导一下 @xibok @hzg0601

**Comment by hzg0601** [comment]
> 

芯片的具体型号和生产时间呢？

**Comment by wuyabing** [comment]
这个不太清楚，我这边没有GPU，用的虚机服务器，搜了一些资料怀疑这个原因：.pdf和图片识别，新增PaddleOCR实现，但需要cpu支持avx指令集，否则会导致项目启动过程中出现 非法指令集的错误

**Comment by hzg0601** [comment]
> 

@wuyabing 非法指令应该就是某个需要编译的包使用了跟你的芯片不兼容的指令集，如果是paddleocr可以参考@Sunjoec的方案。
