### ISSUE TITLE
知识库文件跨行切分问题

### ISSUE THREAD

**Issue by moolean** [chatchat-space/Langchain-Chatchat#616]
我的知识库文件txt文件，是一行一条知识，用\n分行。
但是在实际跑的时候，输出的出处总是跨行输出。

例子：
知识1: XXXXXXXXX，XXXXX 。
知识2: YYYYYYYY，YYYYYY。
知识3:ZZZZ，ZZZZZZZZZZZZ。

输出结果：AAAAAAA 
出处 [1] 知识库.txt:
XXXXX 。YYYYYYYY，YYYYYY。ZZZZ，

我希望他能只输出知识2的当作出处，请问该如何处理呢

**Comment by hzg0601** [comment]
你给出的信息太抽象了，几乎没法回答，但是你这个问题八成应该是由于chinese_text_splitter.py文件里的ChineseTextSplitter类的split_text方法里的33-38行造成的，你可以在debug模式下定位一下，看看text在哪一步'\n'被完全替换了，作相应的修改就可以了

**Comment by bruceye777** [comment]
这个上下文跨行会造成回答错误，比如
问题
 
![1](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/41668200/afe37668-1e43-4b5c-9aa2-704a22307cad)

数据集（一行一个知识点）
 
![2](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/41668200/51743b5c-015f-4df3-b8c0-d2e7be5bb806)

可以看到，因为跨行，把下一行的问题“皮卡堂如何获得红尖椒”放到上下文里面了，导致回答错误。应该在上下文中把换行符或其它约定好的字符之后的文本去除会更好些。

**Comment by net592** [comment]
知识库的格式缺失随意性较大

**Comment by zRzRzRzRzRzRzR** [comment]
最新的代码可以自定义分词器，可以更新后针对自己的内容自定义分词切割

**Comment by youxiaomin** [comment]
我发现是UnstructuredFileLoader读进来的问题，会导致换行符丢失，并不是text_splitter的问题

**Comment by net592** [comment]
:-) 您好，收到了 ，尽快恢复
