### ISSUE TITLE
[BUG] CPU运行cli_demo.py，不回答，hang住

### ISSUE THREAD

**Issue by wupengcheng6819** [chatchat-space/Langchain-Chatchat#622]
没有GPU；32G内存的ubuntu机器。

按照readme，执行
1. conda create -n <环境名> python=3.8
2. conda activate <环境名>
3. 在项目路径下pip install -r requirements.txt
4. 修改model_config.py的默认模型为LLM_MODEL = "chatglm-6b-int4"
5. python cli_demo.py
6. 输入知识库路径，内有一个中文txt文件，而路径和文件名均没有中文。
7. 输入一个问题，随便什么

然后，就hang住了，没有结果返回。

注：模型加载时loader.py中的params参数去掉了`"low_cpu_mem_usage": True`：
`params = {"torch_dtype": torch.float32, "trust_remote_code": True} `
否则会报错：
`RuntimeError: Only Tensors of floating point and complex dtype can require gradients`

**Comment by hzg0601** [comment]
我复现了你的问题，倒不是一直hang，而是在很长一段时间后开始不断输出gugugu。
这个不是项目的问题，只能说int4版本不堪大用吧

**Comment by hzg0601** [comment]
我复现了你的问题，倒不是一直hang，而是在很长一段时间后开始不断输出gugugu。
这个不是项目的问题，只能说int4版本不堪大用吧

**Comment by hzg0601** [comment]
> > 我复现了你的问题，倒不是一直hang，而是在很长一段时间后开始不断输出gugugu。 这个不是项目的问题，只能说int4版本不堪大用吧
> 
> me too ,谁能解释下？

这就是int4版本的问题，这种高度量化的模型有时候就是会因为溢出或精度不足而推理失败

**Comment by RayYe586** [comment]
int4在gpu下运行的很好，应该不是int4模型的问题

**Comment by brizer** [comment]
> int4在gpu下运行的很好，应该不是int4模型的问题

对，现在就是CPU模式下有问题。

**Comment by Crescentz** [comment]
同样的问题

**Comment by melinyang** [comment]
+1，请问解决了么？
