### ISSUE TITLE
关于删除知识库里面的文档后，LLM知识库对话的时候还是会返回该被删除文档的内容

### ISSUE THREAD

**Issue by ywancit** [chatchat-space/Langchain-Chatchat#623]
如题，在vue前端成功执行删除知识库里面文档A.txt后，未能也在faiss索引中也删除该文档，LLM还是会返回这个A.txt的内容，并且以A.txt为出处，未能达到删除的效果

**Comment by welcome2099** [comment]
同上

**Comment by Crazycatlong** [comment]
这个问题我也是

**Comment by Crazycatlong** [comment]
现在有没有什么解决办法

**Comment by ArtPei** [comment]
还是没有解决吗

**Comment by slystrong** [comment]
可以在向量搜索那里加过滤吗？如果搜索结果的文档文件不存在文档目录下，那就跳过。

**Comment by ShinyWey** [comment]
还没解决方法吗, 目前我是前端执行完删除后, 自动多执行一次重建向量库, 文件多了的情况下肯定很久.
