### ISSUE TITLE
[BUG] 调用知识库进行问答,显存会一直叠加

### ISSUE THREAD

**Issue by yuweichen1** [chatchat-space/Langchain-Chatchat#625]
14G的显存,调用的chatglm-6b-int8模型,进行知识库问答时,最多问答四次就会爆显存了,观察了一下显存使用情况,每一次使用就会增加一次显存,请问这样是正常的吗?是否有什么配置需要开启可以解决这个问题?例如进行一次知识库问答清空上次问题的显存?

# 本问题针对知识库问答,llm问答是正常的,显存保持正常,不会持续增加.

**Comment by AllenYang1998** [comment]
我也遇到这个问题

**Comment by AllenYang1998** [comment]
目前想到两个解决方法，不过我还在学习源码
1、滑动窗口（丢弃一部分历史对话）
2、对对话历史进行总结（提炼，精简token）

**Comment by ywm12345** [comment]
我用的是多卡部署，知识库问答，只有一个卡的显存会增加，最后会卡爆，为什么只有一个卡的显存在增加呢，当我调大CHUNK_SIZE时，多卡部署后，进行知识库问答，有时候会直接把其中一个卡的gpu打满，从而卡爆

**Comment by FavoriteStar** [comment]
同问！我也是多卡部署然后问着问着一张卡的显存爆了

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
