### ISSUE TITLE
[BUG] web页面 重新构建数据库 失败，导致 原来的上传的数据库都没了

### ISSUE THREAD

**Issue by Gy1900** [chatchat-space/Langchain-Chatchat#626]
web页面 重新构建数据库 失败，导致 原来的上传的数据库都没了

复现问题的步骤
1. python webui.py
2. 模型配置-修改了llm对话轮数为3
3. 重新加载模型
4. 重新构建知识库

预期的结果
知识库还在，对话轮数变成3

实际结果
构建未成功，原本的知识库没了，vector_store目录也没了

环境信息
- langchain-ChatGLM 版本/commit 号：fef22e3133d8de8f06382149f4303c66afd637cb
- 是否使用 Docker 部署（是/否）：否
- 使用的模型 ：ChatGLM-6
- 使用的 Embedding 模型：本地/text2vec-large-chinese，从 git clone https://huggingface.co/GanymedeNil/text2vec-large-chinese  下载的
- 操作系统及版本:Linux version 4.19.91-012.ali4000.alios7.x86_64 (admin@5ad50c50adde) (gcc version 6.5.1 20181026 (Alibaba 6.5.1-1) (GCC)) #1 SMP Wed Sep 15 17:27:09 CST 2021
- Python 版本 :Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
- 其他相关环境信息：阿里云 CPU-8，内存-30 GiB，GPU-1，型号-NVIDIA A10

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
<img width="873" alt="issue1-重新构建数据库导致vector_store没了" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/27496549/12aaac25-cb35-432d-a2ad-7da6ed98d781">

**Comment by dangzheng0430** [comment]
同问

**Comment by RealDeanZhao** [comment]
同问

**Comment by zicheqingluo** [comment]
同问，vector_store不知道怎么就没了，webui上知识库测试beta中只要输入就报error：AttributeError: 'NoneType' object has no attribute 'embed_query'
'NoneType' object has no attribute 'embed_documents'
知识库无法使用已加载的和新建

**Comment by EvilCalf** [comment]
> 同问，vector_store不知道怎么就没了，webui上知识库测试beta中只要输入就报error：AttributeError: 'NoneType' object has no attribute 'embed_query' 'NoneType' object has no attribute 'embed_documents' 知识库无法使用已加载的和新建

想问解决了么，我没有重新加载知识库也是这个报错，甚至没法加载知识库

**Comment by zicheqingluo** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zicheqingluo** [comment]
同问，加载本地知识库后，重新启动项目，选择已有的知识库就报Error
新建知识库上传文件时报：模型未完成加载，请先在加载模型后再导入文件
     python报错：AttributeError: 'NoneType' object has no attribute 'embed_query

**Comment by Dewey1994** [comment]
同问+1

**Comment by Dewey1994** [comment]
> 同问+1

已解决：下载embedding的model ，在model_config.py下
embedding_model_dict = {
    "ernie-tiny": "nghuyong/ernie-3.0-nano-zh",
    "ernie-base": "nghuyong/ernie-3.0-base-zh",
    "text2vec-base": "your_path\text2vec-base-chinese",
    "text2vec": "GanymedeNil/text2vec-large-chinese",
    "m3e-small": "moka-ai/m3e-small",
    "m3e-base": "moka-ai/m3e-base",
}

# Embedding model name
EMBEDDING_MODEL = "text2vec-base"

下载好对应的模型，然后修改本地路径即可。
