### ISSUE TITLE
OSError: [WinError 1114] 动态链接库(DLL)初始化例程失败。 Error loading "E:\xxx\envs\langchain\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.哪位大佬知道如何解决吗？

### ISSUE THREAD

**Issue by juelinftwd** [chatchat-space/Langchain-Chatchat#629]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
1. 执行 '...' / Run '...'
2. 点击 '...' / Click '...'
3. 滚动到 '...' / Scroll to '...'
4. 问题出现 / Problem occurs

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：是 / Is Docker deployment used (yes/no): yes
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by juelinftwd** [comment]
好的，感谢，我重新安装torch试一下。

**Comment by juelinftwd** [comment]
非常感谢，上一问题重新卸载安装了torch后解决了，但是现在又遇到个新问题，ModuleNotFoundError: No module named 'transformers_modules.models/chatglm-6b'再请教一下是由于下载的pytorch_model-00001-of-00008.bin、pytorch_model-00002-of-00008.bin、pytorch_model-00003-of-00008.bin、pytorch_model-00004-of-00008.bin.....是这个模型文件没放对位置吗？

**Comment by hzg0601** [comment]
你是每个文件都手动下载的吗？如果是纯手动下载的，基本上是没法用的，因为huggingface对每个模型的文件都进行了重新命名，如果使用AutoModel.from_pretrained方法无法下载，可以用huggingface_hub库里的snapshot_download下载，如果还是失败需要用hf_hub_download下载大文件。
如果不是这个原因，你要把完整的打印信息列出来才好判断

**Comment by juelinftwd** [comment]
我是手动下载的，那我再按你说的重新下载试一下。谢谢啦！
