### ISSUE TITLE
detectron2 is not installed. Cannot use the hi_res partitioning strategy. Falling back to partitioning with the fast strategy.

### ISSUE THREAD

**Issue by boxter007** [chatchat-space/Langchain-Chatchat#63]
能够正常的跑起来，在加载content文件夹中的文件时，每加载一个文件都会提示：
detectron2 is not installed. Cannot use the hi_res partitioning strategy. Falling back to partitioning with the fast strategy.

**Comment by imClumsyPanda** [comment]
请参考 https://github.com/imClumsyPanda/langchain-ChatGLM#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by edisonzf2020** [comment]
提示是说：需要按照常见问题 Q2 中描述进行detectron2的安装
但是问题是常见问题没有Q2，Q1后直接跳到Q3
