### ISSUE TITLE
更新后的版本中，删除知识库中的文件，再提问出现error错误

### ISSUE THREAD

**Issue by Missliuff** [chatchat-space/Langchain-Chatchat#634]
针对更新版本，识别到一个问题，过程如下：
1. 把若个文件上传到同一知识库
2. 删除其中一个文件
3. 刷新页面后，问该文件中包含的信息，出现error报错

**Comment by ywancit** [comment]
同问，我也遇到了该bug

**Comment by dangzheng0430** [comment]
使用v0.1.16同样遇到了这个bug，有大佬知道怎么解决吗
