### ISSUE TITLE
[BUG] NPM run dev can not successfully start the VUE frontend

### ISSUE THREAD

**Issue by allenho333** [chatchat-space/Langchain-Chatchat#638]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.
 执行npm run dev  报错

**复现问题的步骤 / Steps to Reproduce**
利用 fastapi 部署 API
$ python api.py

或成功部署 API 后，执行以下脚本体验基于 VUE 的前端页面
$ cd views 

$ pnpm i

$ npm run dev

然后报错

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.
项目成功启动

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
npm run dev

> chatgpt-web@2.11.0 dev
> vite

file:///root/projects/neutrino/langchain-ChatGLM/views/node_modules/vite/dist/node/chunks/dep-24daf00c.js:41545
                    typeof val === 'string' && /^[\p{L}_$]/u.test(val.trim())
                                               ^^^^^^^^^^^^^

SyntaxError: Invalid regular expression: /^[\p{L}_$]/: Invalid property name in character class
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)

Node.js v18.16.0

**Comment by ALLinLLM** [comment]
I have meet the same question. And finally addressed it. Here is what I did:
1. download latest node: https://nodejs.org/en/download
2. for linux, you need unzip the zipped file and add bin dir to PATH

after update PATH, check the version of node and npm:
node: v18.16.1
npm:9.5.1

then, run the cmd in the README.md, and it works now
