### ISSUE TITLE
提一个模型加载的bug，我在截图中修复了，你们有空可以看一下。

### ISSUE THREAD

**Issue by dongyihua543** [chatchat-space/Langchain-Chatchat#642]
![model_load_bug](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/59411575/4432adc4-ccdd-45d9-aafc-5f2d1963403b)

**Comment by zRzRzRzRzRzRzR** [comment]
最新的代码应该已经修复这个问题，感谢您提出的issue
