### ISSUE TITLE
[求助]关于设置embedding model路径的问题

### ISSUE THREAD

**Issue by goldeneave** [chatchat-space/Langchain-Chatchat#643]
如题，我之前成功跑起来过一次，但因环境丢失重新配置 再运行webui就总是报错
```
WARNING 2023-06-16 01:35:31,198-1d: No sentence-transformers model found with name /mnt/workspace/ernie-3.0-base-zh. Creating a new one with MEAN pooling.
Some weights of the model checkpoint at /mnt/workspace/ernie-3.0-base-zh were not used when initializing ErnieModel: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing ErnieModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ErnieModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
WARNING 2023-06-16 01:35:33,136-1d: The dtype of attention mask (torch.int64) is not bool
```
我的embedding model路径配置如下：
```
embedding_model_dict = {
    "ernie-tiny": "nghuyong/ernie-3.0-nano-zh",
    "ernie-base": "/mnt/workspace/ernie-3.0-base-zh",
    "text2vec-base": "shibing624/text2vec-base-chinese",
    "text2vec": "/mnt/workspace/text2vec-large-chinese",
    "m3e-small": "moka-ai/m3e-small",
    "m3e-base": "moka-ai/m3e-base",
}

# Embedding model name
EMBEDDING_MODEL = "ernie-base"
```
想请教大家哪里有错，另外上面报错信息最后一行那个非布尔值提示要紧吗 谢谢了！

**Comment by goldeneave** [comment]
猜想路径问题应该和环境无关，且之前跑起来过 就不放环境了

**Comment by zfanswer** [comment]
这个warning一直有，但是不影响使用吧，实际是load到了embedding model了

**Comment by goldeneave** [comment]
> 

那他创建的这个新的mean pooling没问题的吗 你也是在做embedding时出现了这个warning吗

**Comment by zfanswer** [comment]
嗯，load embedding model的时候出现一次，执行embedding的时候不会出。我用着没问题。

你看下你用的嵌入模型本身要求的是什么吧，
GanymedeNil/text2vec-large-chinese 本身要求就是用mean pooling的
> First, you pass your input through the transformer model, then you have to apply the right pooling-operation on-top of the contextualized word embeddings.
<img width="1065" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1787565/cc523249-14ea-4c6a-bda5-e4e80c48e51f">
所以没问题。

**Comment by goldeneave** [comment]
> 嗯，load embedding model的时候出现一次，执行embedding的时候不会出。我用着没问题。
> 
> 你看下你用的嵌入模型本身要求的是什么吧， GanymedeNil/text2vec-large-chinese 本身要求就是用mean pooling的
> 
> > First, you pass your input through the transformer model, then you have to apply the right pooling-operation on-top of the contextualized word embeddings.
> 
> <img alt="image" width="1065" src="https://user-images.githubusercontent.com/1787565/246340351-cc523249-14ea-4c6a-bda5-e4e80c48e51f.png"> 所以没问题。

好的好的 明白了 感谢大佬

**Comment by Shawnc00** [comment]
请教大佬，我也出现了同样的问题，运行webui.py文件后，弹出了以下信息：
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/93563539/3bfd8092-9243-4b5d-b824-339f1f6a8f67)
运行到这里后，程序没有结束，但也没有出现网页url等信息。

我是在本地加载chatGLM-6b-int4和ernie-base模型的，model_config.py文件内容如下：
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/93563539/d70080a6-3b05-4aaa-9f64-58a5e90a8aa6)
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/93563539/b858a4f8-dcd7-466e-a8f2-d4a07cc2e204)

**Comment by goldeneave** [comment]
我是后来重新配置了一下，你再检查一下两个model里面clone下的文件全不全，huggingface被墙了之后有时候会文件下载不全

Shawnc ***@***.***> 于2023年6月27日周二 15:16写道：

**Comment by Shawnc00** [comment]
仔细检查了一下，chatglm-6b-int4和text2vec-base两个model文件夹中，文件名称、数量、大小都和huggingface里面一致。而且我用chatglm-6b的web_demo是可以正常运行的，也可以打开网页url。
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/93563539/0ef97c6f-435d-4766-9c8f-d7af8b87815b)

但langchain-chatglm中的webui.py和webui_st.py文件运行后都没有显示网页url，程序一直停在下图所示的位置，也没有结束。
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/93563539/662c7755-3384-43b6-89a1-ca48a2d4ded9)

**Comment by goldeneave** [comment]
我也没有用过这个量化版本的模型 我是在这个框架下直接接的glm 或者试试用默认fp16版本的呢

Shawnc ***@***.***> 于2023年6月28日周三 16:26写道：
