### ISSUE TITLE
Lora微调后的模型可以直接使用吗

### ISSUE THREAD

**Issue by Ayachin3ne** [chatchat-space/Langchain-Chatchat#646]
看model_config.py里是有USE_LORA这个参数的，但是在cli_demo.py和webui.py这两个里面都没有用到，实际测试下来模型没有微调的效果，想问问现在这个功能实现了吗

**Comment by glide-the** [comment]
增加--lora-dir 和--lora参数

**Comment by Ayachin3ne** [comment]
@glide-the 在哪个文件里添加呢，/models/loader/args里面是有这两个参数的

**Comment by Ayachin3ne** [comment]
> 这个是启动参数，lora-dir是存放的位置，lora是使用存放位置的哪个
> 
> 例如/lora-dir/adapter-1
> 
> 启动命名参数将为--lora-dir /lora-dir --lora adapter-1

是python webui.py --lora-dir /lora-dir --lora adapter-1这样吗？

**Comment by zealze** [comment]
同问，我训练后chekpoint放ptunring-v2下，配置了config文件`USE_PTUNING_V2 = True`，执行`python api.py`和前端，似乎微调模型没有加载。

**Comment by dangzheng0430** [comment]
> 同问，我训练后chekpoint放ptuning-v2下，配置了config文件`USE_PTUNING_V2 = True`，执行`python api.py`和前端，似乎微调模型没有加载。

我也有这个问题，微调模型似乎不能在运行时直接加载。

**Comment by xiangfeng98** [comment]
请问下怎么加载lora的参数呢？

**Comment by liujun3496** [comment]
请问 您搞定了吗
