### ISSUE TITLE
 [BUG] mac m1 pro  运行提示  zsh: segmentation fault

### ISSUE THREAD

**Issue by snamper** [chatchat-space/Langchain-Chatchat#655]
运行：  python webui.py   
返回                                                                  
INFO  2023-06-17 17:17:23,973-1d: 
loading model config
llm device: mps
embedding device: mps
dir: /Users/xx/PycharmProjects/langchain-ChatGLM/langchain-ChatGLM
flagging username: 17a50bfb4dd940cd98821baade762bb6

zsh: segmentation fault  python webui.py

刚开始以为是paddle问题但换版本也行不行python版本是3.8

**Comment by Neo110** [comment]
你安装成功了吗？

**Comment by Veken** [comment]
我的M1也没安装成功，提示模型未加载成功

**Comment by aliware50** [comment]
解决了吗，这个问题？

**Comment by Veken** [comment]
> 解决了吗，这个问题？

m1要改成cpu进行推理，加载模型生成model的那个地方，可以尝试修改为
model = LoaderClass.from_pretrained(checkpoint,config=self.model_config,torch_dtype=torch.bfloat16 if self.bf16 else torch.float16,trust_remote_code=True).float()

**Comment by aliware50** [comment]
> > 解决了吗，这个问题？
> 
> m1要改成cpu进行推理，加载模型生成model的那个地方，可以尝试修改为 model = LoaderClass.from_pretrained(checkpoint,config=self.model_config,torch_dtype=torch.bfloat16 if self.bf16 else torch.float16,trust_remote_code=True).float()

**Comment by aliware50** [comment]
@Veken 我的是inter

已经是cpu推理了，还是出现

**Comment by aliware50** [comment]
@Veken 我的是inter
运行：
loading model config
llm device: cpu
embedding device: cpu
zsh: segmentation fault  python webui.py

已经是cpu了，为什么还是出现？

**Comment by Veken** [comment]
> 

intel我就不确定了，我的是M1的，估计也得去搜一下

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码尝试
