### ISSUE TITLE
关于本地知识库匹配的问题

### ISSUE THREAD

**Issue by Lukrin-tech** [chatchat-space/Langchain-Chatchat#661]
我发现在匹配知识的时候如果一条知识里存在多个换行符（比如描述一件事情的流程）有时候只会匹配到第一个流程或者前几个流程，无法匹配完全。大伙有没有遇到相似的问题能够很好的解决呢？

**Comment by string-new** [comment]
> 自己修改切分的方式

请问怎么修改切分呢，我现在困惑的是本地知识库应该用什么样的格式才是规范

**Comment by codewen77** [comment]
> 自己修改切分的方式

有没有优雅的切分方式

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码可以自定义切分方式，请更新到最新代码尝试
