### ISSUE TITLE
知识库删除接口405 Method Not Allowed

### ISSUE THREAD

**Issue by syusama** [chatchat-space/Langchain-Chatchat#663]
知识库文件删除接口local_doc_qa/delete_file报405 Method Not Allowed错误
知识库删除接口local_doc_qa/delete_knowledge_base报405 Method Not Allowed错误
导致无法删除文件或知识库

**Comment by bk007lz** [comment]
我也遇到这个问题了，接了吗？

**Comment by tomFoxxxx** [comment]
+1 @imClumsyPanda 求解答 感谢

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
