### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by yuyezhiji** [chatchat-space/Langchain-Chatchat#665]
if "context_expand_method" in doc.metadata and doc.metadata["context_expand_method"] == "forward":
                    expand_range = [i + k]
                elif "context_expand_method" in doc.metadata and doc.metadata["context_expand_method"] == "backward":
                    expand_range = [i - k]
                else:
                    expand_range = [i + k, i - k]
                    
                    其中的context_expand_method 干什么的，给个例子被

**Comment by Halflifefa** [comment]
forward只给出下文,backward只给出上文,如果不设置,默认给出上下文.

**Comment by dangzheng0430** [comment]
这是哪个文件的代码？

**Comment by zfanswer** [comment]
> forward只给出下文,backward只给出上文,如果不设置,默认给出上下文.

我也是看了源码发现有这个判断，请问这个设置在哪儿可以设置，我看这个判断取得内容是从faiss向量数据库的document object里拿的，等于在创建数据库时就要设置了吧？
能说下可以在哪儿设置么？

**Comment by zfanswer** [comment]
> 这是哪个文件的代码？

vectorstores/MyFAISS.py的

**Comment by dangzheng0430** [comment]
> > forward只给出下文,backward只给出上文,如果不设置,默认给出上下文.
> 
> 我也是看了源码发现有这个判断，请问这个设置在哪儿可以设置，我看这个判断取得内容是从faiss向量数据库的document object里拿的，等于在创建数据库时就要设置了吧？ 能说下可以在哪儿设置么？

                    expand_range = [i + k, i - k]
想只显示下文就把" i - k "去掉。

**Comment by zfanswer** [comment]
> > > forward只给出下文,backward只给出上文,如果不设置,默认给出上下文.
> > 
> > 
> > 我也是看了源码发现有这个判断，请问这个设置在哪儿可以设置，我看这个判断取得内容是从faiss向量数据库的document object里拿的，等于在创建数据库时就要设置了吧？ 能说下可以在哪儿设置么？
> 
> ```
>                 expand_range = [i + k, i - k]
> ```
> 
> 想只显示下文就把" i - k "去掉。

嗯，这么改可以，但是功能变了，所有知识库都不能联系上文了。
想实现的是根据context_expand_method对不同文档进行不同的上下文扩展设置，找了目前应该代码里还没做这个实现，只是这里预埋了一个key和判断逻辑，看看接下来更新不，如果不行就自己撸一下试试
