### ISSUE TITLE
关于上传PDF报错

### ISSUE THREAD

**Issue by fghhaha** [chatchat-space/Langchain-Chatchat#670]
上传PDF格式中出现了这个报错有没有大佬知道怎么回事呀。
ERROR 2023-06-19 22:52:12,690-1d: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))

**Comment by hzg0601** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/issues/592#issuecomment-1585471940

**Comment by fghhaha** [comment]
> [#592 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/592#issuecomment-1585471940)

但是我是windows系统

**Comment by fghhaha** [comment]
> [#592 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/592#issuecomment-1585471940)

您好 我已经手动下载了ch_PP-OCRv3_rec_infer.tar文件并放在了C:\Users\29050\.paddleocr\whl\det\ch\ch_PP-OCRv3_det_infer。不过仍然出现报错
Could not create share link. Please check your internet connection or our status page: https://status.gradio.app
download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to C:\Users\29050/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer\ch_PP-OCRv3_det_infer.tar
download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar error,please download it manually:
HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
ERROR 2023-06-20 10:18:50,590-1d: [Errno 2] No such file or directory: 'C:\\Users\\29050/.paddleocr/whl\\det\\ch\\ch_PP-OCRv3_det_infer\\ch_PP-OCRv3_det_infer.tar'

**Comment by hzg0601** [comment]
有三个文件，每运行一次它会提醒你下载的链接和存放的路径，按提示继续下载，把文件放上去，所以要放三次

**Comment by hzhaoy** [comment]
> > [#592 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/592#issuecomment-1585471940)
> 
> 您好 我已经手动下载了ch_PP-OCRv3_rec_infer.tar文件并放在了C:\Users\29050.paddleocr\whl\det\ch\ch_PP-OCRv3_det_infer。不过仍然出现报错 Could not create share link. Please check your internet connection or our status page: https://status.gradio.app download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar to C:\Users\29050/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer\ch_PP-OCRv3_det_infer.tar download https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar error,please download it manually: HTTPSConnectionPool(host='paddleocr.bj.bcebos.com', port=443): Max retries exceeded with url: /PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)'))) ERROR 2023-06-20 10:18:50,590-1d: [Errno 2] No such file or directory: 'C:\Users\29050/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer\ch_PP-OCRv3_det_infer.tar'

你需要将下载的tar文件解压得到三个模型文件，将这三个文件放到对应的目录下。比方你这种情况，就是把ch_PP-OCRv3_rec_infer.tar解压后得到的三个文件放在C:\Users\29050/.paddleocr/whl\det\ch\ch_PP-OCRv3_det_infer下面。

后面还会需要下载识别rec和分类模型cls模型，也遇到同样的问题，一样地处理就行
