### ISSUE TITLE
数据量太大，embedding编码和FAISS存储太慢

### ISSUE THREAD

**Issue by tianyunzqs** [chatchat-space/Langchain-Chatchat#672]
外挂知识库数据量很多，每条内容都很长（上万字符）

考虑到内存原因，因此给长文本进行分句，但是分句后，句子太多，导致建立FAISS向量库的时候，太慢了，1个小时才构建几十条

`FAISS.from_documents(docs, self.embeddings)`好像是并行的，
但是`vector_store.add_documents(docs)`没有并行处理，总是输出Bacthes进度条

请问有啥好办法提速吗？

**Comment by Leawnn** [comment]
+1

**Comment by Dumail** [comment]
+1

**Comment by HS-LaoYao** [comment]
+1

**Comment by Helenailse1** [comment]
+1

**Comment by huarong0906** [comment]
+1

**Comment by huarong0906** [comment]
+1

**Comment by sunlin-xiaonai** [comment]
试试换成数据库呢，pgvector？pinecone

**Comment by JerryYao80** [comment]
同时上传1000个小文件，浏览器就崩溃了

**Comment by danny-zhu** [comment]
> 同时上传1000个小文件，浏览器就崩溃了

可能是内存溢出了，考虑分批处理，参考https://github.com/imClumsyPanda/langchain-ChatGLM/issues/884

**Comment by MC-Zealot** [comment]
+1

**Comment by zRzRzRzRzRzRzR** [comment]
更新最新代码后，换一个数据库试试，因为faiss支持的数据比较小，大文件不太行

**Comment by williamliujl** [comment]
更换为milvus数据库，还是会存在killed情况。请问是什么原因呢？
