### ISSUE TITLE
通过Fastchat API调用模型输出时可以支持流式输出吗?

### ISSUE THREAD

**Issue by Halflifefa** [chatchat-space/Langchain-Chatchat#676]
**功能描述 / Feature Description**
目前通过项目文档中的提示完成了Fastchat API调用一些LLaMa模型来做问答,发现效果不Chat-GLM要好不少,Chat-GLM有两个主要缺点,一是涉及简单逻辑推理的问题完成不了,基本是在说些他自己也不知道是啥的话,二是指令遵循能力不太行,经常输出无关信息. 
而目前的部分基于llama用中文数据训练的模型在这两方面效果要好不少,不过这些模型直接加载或报错,可能的原因是没有设置多卡部署,因为总是加载完参数就跳出了.
因此我最后是通过Fastchat API调用的方式完成的,这样也很方便,唯一的问题就是不支持流式输出了,回答问题要很久,体验不好.

**解决的问题 / Problem Solved**
通过Fastchat API调用模型输出时可以支持流式输出
**实现建议 / Implementation Suggestions**
无
**替代方案 / Alternative Solutions**
直接加载本地llama模型?但我加载总是出错.
**其他信息 / Additional Information**
无

**Comment by staticTao** [comment]
llama是去哪里下载呢？我下载facebook官方的llama，
修改
"vicuna-13b-hf": {
        "name": "vicuna-13b-hf",
        "pretrained_model_name": "vicuna-13b-hf",
        "local_model_path": "这里改成本地的绝对路径",
        "provides": "LLamaLLM"
    },
运行的时候提示错误https://huggingface.co/本地路径，找不到的错误，目前还不知道怎么解决。请帮助一下

**Comment by Halflifefa** [comment]
> llama是去哪里下载呢？我下载facebook官方的llama， 修改 "vicuna-13b-hf": { "name": "vicuna-13b-hf", "pretrained_model_name": "vicuna-13b-hf", "local_model_path": "这里改成本地的绝对路径", "provides": "LLamaLLM" }, 运行的时候提示错误[https://huggingface.co/本地路径，找不到的错误，目前还不知道怎么解决。请帮助一下](https://huggingface.co/%E6%9C%AC%E5%9C%B0%E8%B7%AF%E5%BE%84%EF%BC%8C%E6%89%BE%E4%B8%8D%E5%88%B0%E7%9A%84%E9%94%99%E8%AF%AF%EF%BC%8C%E7%9B%AE%E5%89%8D%E8%BF%98%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%E3%80%82%E8%AF%B7%E5%B8%AE%E5%8A%A9%E4%B8%80%E4%B8%8B)

我下的这个模型:https://huggingface.co/OpenBuddy/openbuddy-openllama-7b-v5-fp16

**Comment by Alex-Zuo-One** [comment]
+1

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.2版本，已支持基于fastchat的流式输出
