### ISSUE TITLE
设置了torch.cuda.set_device(1)，不起作用

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#681]
有两张卡，因为其中一张卡已经使用了挺多了，想用另一张卡跑
在webui.py，local_doc_qa.py和model_config.py中设置了torch.cuda.set_device(1)，但是python webui.py后，程序一部分用到了0号卡，一部分用到了1号卡，0号卡因为之前已经使用了部分，导致加载知识包，推理一会，内存就溢出了。1好卡还有挺多内存没用。

为什么设置的不起作用，是设置的不对吗，有大佬知道什么原因吗

**Comment by hzg0601** [comment]
1. 设置设备的方法不是调用torch.cuda.set_device,而是直接设为类似“cuda:1”的string;
2. 简单这么改是不行的,需要在load.py文件中，修改_load_model函数如下：
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/22924096/a208aa34-2d2d-43a9-ab7a-af35d7f24ade)

修改clear_torch_cache函数如下：
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/22924096/612b34ac-b5b3-40dc-862c-3956ffe7e1c9)

**Comment by ywm12345** [comment]
为什么那个device_id = "0"?呀，我要是多卡部署，这里也是0呀，我在实际使用中，使用多卡部署，当我调大CHUNK_SIZE后，prompt也随之增大，但会把1卡（0）的GPU卡爆，其它卡占用的GPU很少，这是为什么呢

**Comment by hzg0601** [comment]
> 

这段代码的原始设置不是我写的，其中的逻辑我也不清楚，猜测可能是chatglm-6b的多卡部署中，llm_head和embedding层都在0号卡上，所以清除0号卡的显存就够了。如果你觉得有问题，可以把所以的卡都清一清试试

**Comment by ywm12345** [comment]
我测试了的，我将llm_head和embedding层写在其它卡上，当我调大CHUNK_SIZE后，依然把0号卡的GPU卡爆，本地环境是8卡，每张卡24G，我还进行了测试，llm_head和embedding写在0卡上，gpu_target修改为1，从1号卡开始分布神经网络层，这种情况会把1号卡卡爆

**Comment by ywm12345** [comment]
我这个问题不是因为多轮对话把显存吃完，而是加了CHUNK_SIZE，导致上下文的量增多了，第一次知识库问答就会把显存卡爆，但不理解的是，我是多卡部署，按道理是使用多张卡的GPU呀，为什么会把一个卡的显存用完，其它卡的显存还是多卡部署时使用的量。难道不是多卡协作吗

**Comment by ywm12345** [comment]
我这个问题不是因为多轮对话把显存吃完，而是加了CHUNK_SIZE，导致上下文的量增多了，第一次知识库问答就会把显存卡爆，但不理解的是，我是多卡部署，按道理是使用多张卡的GPU呀，为什么会把一个卡的显存用完，其它卡的显存还是多卡部署时使用的量。难道不是多卡协作吗，一个卡的GPU不够，那就使用多个卡的GPU

**Comment by hzg0601** [comment]
> 

显然没有这么智能，它的机制是将模型不同的层分割到不同的GPU上，分配以后每个GPU的负载就是固定的
