### ISSUE TITLE
上传word格式的知识库

### ISSUE THREAD

**Issue by guiniao** [chatchat-space/Langchain-Chatchat#682]
上传word格式的知识库，报错
[Errno 13] Permission denied : 'soffice'

**Comment by hzg0601** [comment]
目前还是不支持word格式

**Comment by VignetteApril** [comment]
扩展名为doc的不行，docx确可以上传。
报错为：
`soffice command was not found. Please install libreoffice`
我后面装好了，在命令行已经有soffice命令了，还是不行。
