### ISSUE TITLE
[BUG] 用产品说明书做测试，出处信息正确，但是回答结果错误

### ISSUE THREAD

**Issue by tddevrtx4090** [chatchat-space/Langchain-Chatchat#685]
我用某产品的使用说明书做测试，出处的信息正确，但回答信息错误，该如何优化，以下是复现内容：

-------------------------------------

Q:海尔冰箱的尺寸是什么

A:根据提供的信息，海尔冰箱的尺寸是700x88x175mm。

出处 [2] BCD-411WLHFD7DC9U1说明书.pdf
让冰箱静置 30 分钟以上， 再接通电源，以确保冰箱正常运转。 撕覆膜 若冰箱外壳带有覆膜，请将覆膜完全撕掉，以免影响冰箱正常散热，造 成耗电量的上升。 使用前请先进行清洁 （清洁方法请参阅“冰箱的清洁”一节） 安装步骤 688 700 1775 冰箱外形尺寸 ： 宽 700x 深 688x 高 1775（mm） BCD-410WLHFD7DSMU1、BCD-411WLHFD7DC9U1、 BCD-412WLHFD7DS9U1 系列

**Comment by glide-the** [comment]
您需要训练lora
https://github.com/hiyouga/ChatGLM-Efficient-Tuning

**Comment by zfanswer** [comment]
@tddevrtx4090 尝试过调整chatglm_llm.py里的 top_p（默认0.95好像）吗？有效果么？
    temperature: float = 0.7
    top_p = 1.0

**Comment by zfanswer** [comment]
> 您需要训练lora https://github.com/hiyouga/ChatGLM-Efficient-Tuning

困惑了，感觉这不是知识库最典型的场景么，如果这样还需要练lora，那知识库查询的使用场景是什么呢？

或者请您解释一下训练lora是为了解决什么问题？是解决回答数字是幻觉的问题吗，还是要加强模型数字数学推理能力？

**Comment by JingyiZhang0225** [comment]
> > 您需要训练lora https://github.com/hiyouga/ChatGLM-Efficient-Tuning
> 
> 困惑了，感觉这不是知识库最典型的场景么，如果这样还需要练lora，那知识库查询的使用场景是什么呢？
> 
> 或者请您解释一下训练lora是为了解决什么问题？是解决回答数字是幻觉的问题吗，还是要加强模型数字数学推理能力？

应该是要增强LLM对出处信息的理解和总结能力，出处信息正确，证明检索方面没问题，有问题的是LLM的基本能力

**Comment by sevenandseven** [comment]
> > > 您需要训练lora https://github.com/hiyouga/ChatGLM-Efficient-Tuning
> > 
> > 
> > 困惑了，感觉这不是知识库最典型的场景么，如果这样还需要练lora，那知识库查询的使用场景是什么呢？
> > 或者请您解释一下训练lora是为了解决什么问题？是解决回答数字是幻觉的问题吗，还是要加强模型数字数学推理能力？
> 
> 应该是要增强LLM对出处信息的理解和总结能力，出处信息正确，证明检索方面没问题，有问题的是LLM的基本能力

请问这种问题怎么处理？
