### ISSUE TITLE
[FEATURE] websocket接口能支持并发请求吗

### ISSUE THREAD

**Issue by swxnh** [chatchat-space/Langchain-Chatchat#688]
**功能描述 / Feature Description**
多个请求同时执行

**解决的问题 / Problem Solved**
多请求时阻塞

**Comment by Gy1900** [comment]
+1,请问大佬做到了吗

**Comment by swxnh** [comment]
> +1,请问大佬做到了吗
没有，应该是模型方面的限制，不知道改动哪里的代码可以

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.2版本，api中流式改为sse方式实现，支持并发，但模型处理过程仍需要排队进行。
