### ISSUE TITLE
加载LLM模型  chatglm chatglm-int8  均可。 但是加载moss报错

### ISSUE THREAD

**Issue by ainndejj11** [chatchat-space/Langchain-Chatchat#689]
使用分支  0.1.16

cli_demo.py
加载LLM模型推理  chatglm chatglm-int8  chatglm-int4 均可。 但是moss报错,加载完模型就报错

错误信息
SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: 
/fnlp/moss-moon-003-sft/resolve/main/modeling_moss.py (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol 
(_ssl.c:1131)')))

请问什么原因

**Comment by hzg0601** [comment]
> 使用分支 0.1.16
> 
> cli_demo.py 加载LLM模型推理 chatglm chatglm-int8 chatglm-int4 均可。 但是moss报错,加载完模型就报错
> 
> 错误信息 SSLError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /fnlp/moss-moon-003-sft/resolve/main/modeling_moss.py (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
> 
> 请问什么原因

这是个网络连接错误，多试几次，或着改用huggingface_hub的snapshot_download先下载好模型。
