### ISSUE TITLE
[BUG]  /  Embedding 模型只能使用webui.py在线下载的，事先下载好的模型不能使用。

### ISSUE THREAD

**Issue by deepblind** [chatchat-space/Langchain-Chatchat#692]
**问题描述 / Problem Description**
事先下载好Embedding 模型（GanymedeNil），然后修改配置文件。启动之后会报错，找不到这个模型。目前只能使用默认的配置，通过webui.py在线下载到cache里。
 

**预期的结果 / Expected Result**
可以事先下载embedding模型，然后修改配置文件来使用。
 

 
描述实际发生的结果 / Describe the actual result.
事先下载的embedding模型失效。只能使用默认的配置并且依赖webui.py在线下载。

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号： 23年6月17下载。可能是1.1
- 是否使用 Docker 部署（是/否）：no
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B  
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese  
- 操作系统及版本 / Operating system and version: windows 10
- Python 版本 / Python version: 3.8
- 其他相关环境信息 / Other relevant environment information:

**Comment by zfanswer** [comment]
v0.1.16没有问题。
用 git-lfs clone huggingface的库，把地址放到config里。
<img width="578" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/1787565/ccce3162-2027-4e1a-8fbc-82050135c88a">

**Comment by deepblind** [comment]
邮件已收到，谢谢。

**Comment by deepblind** [comment]
邮件已收到，谢谢。
