### ISSUE TITLE
请问如何设置用哪一张GPU？

### ISSUE THREAD

**Issue by RickyWang111** [chatchat-space/Langchain-Chatchat#693]
按照说明部署后，运行webui.py 后显存不足，显示使用的是我3060 6G的显卡，但我电脑上是有两张显卡的，另一张是3090 24G，没有被调用。
感谢大佬解惑

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/96077395/38d40049-f468-494d-9124-e5a5b6bdea03)

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/96077395/a4636dc9-90e2-4c14-8e5d-9fd0eb58a19b)

**Comment by RickyWang111** [comment]
附上错误显示：
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 32.00 MiB (GPU 1; 6.00 GiB total capacity; 5.35 GiB already allocated; 0 bytes free; 5.35 GiB reserved in total by PyTorch) If reserved memory is >>    
allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by hzg0601** [comment]
修改load.py中_load_model和clear_torch_cache函数，在model_config.py中设置llm_device的为类似“cuda:1”的形式。具体可以参考PR#664的commit记录，嫌麻烦可以拉取我的llama-cpp分支

**Comment by hzg0601** [comment]
> 按照说明部署后，运行webui.py 后显存不足，显示使用的是我3060 6G的显卡，但我电脑上是有两张显卡的，另一张是3090 24G，没有被调用。 感谢大佬解惑
> 
> ![image](https://user-images.githubusercontent.com/96077395/247901742-38d40049-f468-494d-9124-e5a5b6bdea03.png)
> 
> ![image](https://user-images.githubusercontent.com/96077395/247901673-a4636dc9-90e2-4c14-8e5d-9fd0eb58a19b.png)

默认是两张卡都用的，但是由于你第一张卡显存太小，导致OOM

**Comment by RickyWang111** [comment]
稍等，我通过cmd强制设置临时变量 set CUDA_VISIBLE_DEVICES=2  。可能有戏，正在下载中

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/96077395/603a90af-da67-486b-a8b8-7b970920a37d)
