### ISSUE TITLE
api.py 中建议添加创建知识库的接口

### ISSUE THREAD

**Issue by javabloger** [chatchat-space/Langchain-Chatchat#696]
目前 api.py 中 提供的接口基本上都全了，唯独创建知识库的接口没有，有点可惜啊，建议作者能添加这个接口。

/local_doc_qa/upload_file,上传知识库文件
/local_doc_qa/update_file,更新知识库文件
/local_doc_qa/upload_files,上传知识库多个文件
/local_doc_qa/delete_file，删除知识库文件
/local_doc_qa/list_files，列出知识库下面的文件
/local_doc_qa/local_doc_chat，与知识库下面的聊天机器人对话
/local_doc_qa/list_knowledge_base，列出所有知识库
/local_doc_qa/delete_knowledge_base，删除某个知识库

**Comment by welcome2099** [comment]
在上传文件的时候，需要有两个参数，一个是知识库id,一个是文件名，代码中写到如果不存在知识库会创建一个新的知识库名

**Comment by Vincent-ch99** [comment]
> 在上传文件的时候，需要有两个参数，一个是知识库id,一个是文件名，代码中写到如果不存在知识库会创建一个新的知识库名

你好，请问如何使用这些接口，比如我有很多个不同的查询目标，对应了不同的知识库文件，我希望一个查询目标上传一个知识库文件，应该使用什么格式进行请求？

**Comment by hengwangyue** [comment]
> > 在上传文件的时候，需要有两个参数，一个是知识库id,一个是文件名，代码中写到如果不存在知识库会创建一个新的知识库名
> 
> 你好，请问如何使用这些接口，比如我有很多个不同的查询目标，对应了不同的知识库文件，我希望一个查询目标上传一个知识库文件，应该使用什么格式进行请求？

同问

**Comment by tomFoxxxx** [comment]
> 目前 api.py 中 提供的接口基本上都全了，唯独创建知识库的接口没有，有点可惜啊，建议作者能添加这个接口。
> 
> /local_doc_qa/upload_file,上传知识库文件 /local_doc_qa/update_file,更新知识库文件 /local_doc_qa/upload_files,上传知识库多个文件 /local_doc_qa/delete_file，删除知识库文件 /local_doc_qa/list_files，列出知识库下面的文件 /local_doc_qa/local_doc_chat，与知识库下面的聊天机器人对话 /local_doc_qa/list_knowledge_base，列出所有知识库 /local_doc_qa/delete_knowledge_base，删除某个知识库

您好 请问这些接口的使用样例可以帮忙提供一下吗

我在使用知识库删除功能时遇到了{"detail":"Method Not Allowed"}的问题 感谢

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.2版本，在v0.2.x版本中api进行了重构，已满足新建知识库等接口需求。
