### ISSUE TITLE
[BUG] 服务重启问题回复慢

### ISSUE THREAD

**Issue by taishansky** [chatchat-space/Langchain-Chatchat#698]
**问题描述 / Problem Description**
部署完成后，每次服务重启回复的问题比较慢，过个办小时以上就好了。几乎100%出现。

环境信息 / Environment Information
langchain-ChatGLM 版本/commit 号：langchain-ChatGLM v0.1.16
是否使用 Docker 部署（是/否）：no
使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
操作系统及版本 / Operating system and version: Ubuntu 18.04
Python 版本 / Python version: 3.8.16
其他相关环境信息 / Other relevant environment information:

如下是视频信息
https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38451506/f7505fe7-bedc-415c-9363-b233c039bd38

**Comment by zhubao315** [comment]
问题复现，求解决

**Comment by zhubao315** [comment]
用GLM2或是回退到 0.1.14 就快了
