### ISSUE TITLE
可否在API中新增对文档的摘要功能

### ISSUE THREAD

**Issue by ldxbaby756** [chatchat-space/Langchain-Chatchat#705]
两个疑问
1、目前完成langchain的load_summarize_chain的摘要功能。问题在于：当用户问“请帮我总结这一篇文章”时，其实是被知识库问答的方法get_knowledge_based_answer接收的，此时应该如何组织两者之间的逻辑，是在get_knowledge_based_answer方法里面判断一下用户的意图是否为获取摘要么？
2、求教使用load_summarize_chain时，如何构建流式输出的API？
先感谢大佬回复！

**Comment by zRzRzRzRzRzRzR** [comment]
目前最新代码已经在测试这个功能，请关注我们最新的代码
