### ISSUE TITLE
执行python image_loader.py 出现问题。

### ISSUE THREAD

**Issue by yuyangtian1000** [chatchat-space/Langchain-Chatchat#709]
执行python image_loader.py（在langchain-ChatGLM/loader下）

呈现为：

(langchain-ChatGLM) yu@yu-Standard-PC-i440FX-PIIX-1996:~/langchain-ChatGLM/loader$ python image_loader.py 
非法指令 (核心已转储)
(langchain-ChatGLM) yu@yu-Standard-PC-i440FX-PIIX-1996:~/langchain-ChatGLM/loader$

**Comment by Crescentz** [comment]
请问如何解决的
