### ISSUE TITLE
[BUG] 将model_config.py里面的LLM_MODEL修改为chatglm2-6b启动报错

### ISSUE THREAD

**Issue by string-new** [chatchat-space/Langchain-Chatchat#713]
**问题描述 / Problem Description**

                                                                                                 │
│   698 │   │   start = preferred_clock()                                                          │
│   699 │   │                                                                                      │
│   700 │   │   # Send the request                                                                 │
│ ? 701 │   │   r = adapter.send(request, **kwargs)                                                │
│   702 │   │                                                                                      │
│   703 │   │   # Total elapsed time of the request (approximately)                                │
│   704 │   │   elapsed = preferred_clock() - start                                                │
│                                                                                                  │
│ /root/miniconda3/lib/python3.10/site-packages/requests/adapters.py:547 in send                   │
│                                                                                                  │
│   544 │   │   │   │   │   raise                                                                  │
│   545 │   │                                                                                      │
│   546 │   │   except (ProtocolError, OSError) as err:                                            │
│ ? 547 │   │   │   raise ConnectionError(err, request=request)                                    │
│   548 │   │                                                                                      │
│   549 │   │   except MaxRetryError as e:                                                         │
│   550 │   │   │   if isinstance(e.reason, ConnectTimeoutError):                                  │
?──────────────────────────────────────────────────────────────────────────────────────────────────?
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

很多地方报错，但是都这这个错，请问是因为网络原因造成的吗

**Comment by hzg0601** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/pull/664，参考第6个特性

**Comment by sungh66** [comment]
> #664 参考第6个特性

可以详细一点吗，是因为huggingface连不上吗
