### ISSUE TITLE
[BUG] 简洁阐述问题 / Mac M1 Pro提示模型未加载成功

### ISSUE THREAD

**Issue by Veken** [chatchat-space/Langchain-Chatchat#717]
1、执行webui.py提示了这个错误，web页面提示模型未成功加载
logger.warning("Failed to load cpm_kernels:", exception)
Message: 'Failed to load cpm_kernels:'
Arguments: (RuntimeError('Unknown platform: darwin'),)
2、在进行对话时，提示该错误
AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'
3、在上传文件夹时，一直卡在这，没有上传成功，也没有错误日志，不知是否是因为模型未加载成功导致，还是因为M1的原因
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/12594017/9ba10b2d-1a10-47a3-b79a-606bf7e447d9)

**Comment by Merenguelkl** [comment]
我也报错AttributeError: 'NoneType' object has no attribute 'int4WeightExtractionHalf'
请问解决了吗
