### ISSUE TITLE
上传文件到知识库时出现并行锁死告警，怎么破

### ISSUE THREAD

**Issue by huarong0906** [chatchat-space/Langchain-Chatchat#721]
上传文件到知识库时出现：
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
        - Avoid using `tokenizers` before the fork if possible
        - Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

**Comment by tomFoxxxx** [comment]
在tokenization的时候禁用并行 

- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
-按照这个报错说明添加全局变量试试

**Comment by Edisonwei54** [comment]
> 在tokenization的时候禁用并行
> 
> * Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
>   -按照这个报错说明添加全局变量试试

怎么操作？
