### ISSUE TITLE
[FEATURE] 简洁阐述功能 / Concise description of the feature

### ISSUE THREAD

**Issue by Bruce-XUZILIN** [chatchat-space/Langchain-Chatchat#723]
一个小白，pull了博主的开源项目自己跑了跑，现在有点问题想问各位大佬，问题可能有点白痴。

1. 这个整个模型基于的知识库的代码在哪里。就是我在哪里能找到引用啊之类的代码。

2. 我自己添加了本地的文档进去，发现出来的结果并不满意。我有什么办法看到他每次处理我的问题的时候后台的逻辑么，我想自己调试一下。我现在在一家公司实习，他们想开发给予自己公司文档的知识库问答系统。

希望路过的大佬或者作者给我一些解答和建议。

谢谢

**Comment by tomFoxxxx** [comment]
https://www.bilibili.com/video/BV1iu411x7PP/?spm_id_from=333.788&vd_source=bc9f78296c76ed2e9974df597e29bea5
参考18-20的视频内容 加油

**Comment by imClumsyPanda** [comment]
项目目前已更新至v0.2.2版本，架构与v0.1.x有所调整，基于知识库问答的代码实现位于server/chat/knowledge_base_chat中
