### ISSUE TITLE
[BUG] webui知识库问答报错error

### ISSUE THREAD

**Issue by EvilCalf** [chatchat-space/Langchain-Chatchat#724]
**问题描述 webui知识库问答报错error

**复现问题的步骤 / Steps to Reproduce**
1. 启动webui.py
2. 选择知识库问答
3. 选择samples
4. 问题出现

**预期的结果 / Expected Result**
正常配置知识库

**实际结果 / Actual Result**
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/35754619/5f74abbc-189b-4d46-9b33-8196260d8785)
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/35754619/0e34591c-ba23-48a8-ac09-71a6ae817231)
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/35754619/4227079c-4a13-42d1-8d14-41f17db8eb94)

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：https://github.com/imClumsyPanda/langchain-ChatGLM/commit/d0b746c54ff662b851692cfb6ee8dd96d2927a68
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）text2vec
- 操作系统及版本 / Operating system and version: centos7
- Python 版本 / Python version:3.10
- 其他相关环境信息 / Other relevant environment information:

**Comment by EvilCalf** [comment]
同时如果新增知识库
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/35754619/37b5e4fc-5064-4aa6-9c10-d253551d7300)

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码试试
