### ISSUE TITLE
删除faiss的index

### ISSUE THREAD

**Issue by ZTurboX** [chatchat-space/Langchain-Chatchat#726]
删除doc时要如何同时删除对应faiss的index中向量

**Comment by Wizhiai** [comment]
插眼同问，目前知道有删除file，但如何查询file并删除这些不是很明白

**Comment by ZTurboX** [comment]
找到方法了，用IndexIDMap建立index和index id的映射

**Comment by tomFoxxxx** [comment]
> 找到方法了，用IndexIDMap建立index和index id的映射

您好 请问方便详细介绍下 或者贴一下reference嘛 感谢

**Comment by ZTurboX** [comment]
> > 找到方法了，用IndexIDMap建立index和index id的映射
> 
> 您好 请问方便详细介绍下 或者贴一下reference嘛 感谢

关键的几个步骤：
初始化时：
`
index = faiss.IndexFlatIP(len(embeddings[0]))
index_ids = faiss.IndexIDMap(index)
index_ids.add_with_ids(vector, np.array([id for id in range(0, len(ids))]))
`

删除时：
`
ids = [k for k, v in self.vector_store.docstore._dict.items() if v.metadata["source"] == source]
            index_ids = []
            for id in ids:
                index = list(self.vector_store.index_to_docstore_id.keys())[list(self.vector_store.index_to_docstore_id.values()).index(id)]
                self.vector_store.index_to_docstore_id.pop(index)
                self.vector_store.docstore._dict.pop(id)
                index_ids.append(index)
            self.vector_store.index.remove_ids(np.array(index_ids))
`

**Comment by ZTurboX** [comment]
> > 找到方法了，用IndexIDMap建立index和index id的映射
> 
> 您好 请问方便详细介绍下 或者贴一下reference嘛 感谢

1. 初始化时，建立index和id的映射
 index = faiss.IndexFlatIP(len(embeddings[0]))
 index_ids = faiss.IndexIDMap(index)
用IndexIDMap的add_with_ids添加向量
2. 删除向量用IndexIDMap的remove_ids方法

**Comment by tomFoxxxx** [comment]
> > > 找到方法了，用IndexIDMap建立index和index id的映射
> > 
> > 
> > 您好 请问方便详细介绍下 或者贴一下reference嘛 感谢
> 
> 1. 初始化时，建立index和id的映射
>    index = faiss.IndexFlatIP(len(embeddings[0]))
>    index_ids = faiss.IndexIDMap(index)
>    用IndexIDMap的add_with_ids添加向量
> 2. 删除向量用IndexIDMap的remove_ids方法

感谢！！

**Comment by ucas010** [comment]
直接删除文件和向量文件不行么？

**Comment by ArtPei** [comment]
> 用IndexIDMap建立index和index id的映射

会导致bug

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.2，已支持删除faiss向量库中指定向量。

**Comment by tomFoxxxx** [comment]
> 项目已更新至v0.2.2，已支持删除faiss向量库中指定向量。

借楼问下大佬 0.2.x版本的可扩展性是否变差了 感觉0.1.x更接近原生langchain的架构

**Comment by imClumsyPanda** [comment]
> > 项目已更新至v0.2.2，已支持删除faiss向量库中指定向量。
> 
> 借楼问下大佬 0.2.x版本的可扩展性是否变差了 感觉0.1.x更接近原生langchain的架构

接近原生架构是为了能够有更多精力优化效果，而不是在维护自定义架构本身，包括之前之前不同模型也需要大量精力进行维护。
