### ISSUE TITLE
加载moss模型报错

### ISSUE THREAD

**Issue by ainndejj11** [chatchat-space/Langchain-Chatchat#727]
加载本地moss模型，加载完报错，请问什么原因呢？？  本地加载chatglm6b 就没问题
报错信息如下：

INFO  2023-06-27 05:56:52,308-1d: Note: NumExpr detected 24 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO  2023-06-27 05:56:52,308-1d: NumExpr defaulting to 8 threads.
Loading fnlp/moss-moon-003-sft...
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████| 4/4 [03:54<00:00, 58.57s/it]
Loaded the model in 381.25 seconds.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /alidata/GitHub/langchain-ChatGLM/cli_demo.py:66 in <module>                                     │
│                                                                                                  │
│   63 │   args = parser.parse_args()                                                              │
│   64 │   args_dict = vars(args)                                                                  │
│   65 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                   │
│ ❱ 66 │   main()                                                                                  │
│   67                                                                                             │
│                                                                                                  │
│ /alidata/GitHub/langchain-ChatGLM/cli_demo.py:16 in main                                         │
│                                                                                                  │
│   13                                                                                             │
│   14 def main():                                                                                 │
│   15 │                                                                                           │
│ ❱ 16 │   llm_model_ins = shared.loaderLLM()                                                      │
│   17 │   llm_model_ins.history_len = LLM_HISTORY_LEN                                             │
│   18 │                                                                                           │
│   19 │   local_doc_qa = LocalDocQA()                                                             │
│                                                                                                  │
│ /alidata/GitHub/langchain-ChatGLM/models/shared.py:43 in loaderLLM                               │
│                                                                                                  │
│   40 │   │   loaderCheckPoint.reload_model()                                                     │
│   41 │                                                                                           │
│   42 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])             │
│ ❱ 43 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                               │
│   44 │   if 'FastChatOpenAILLM' in llm_model_info["provides"]:                                   │
│   45 │   │   modelInsLLM.set_api_base_url(llm_model_info['api_base_url'])                        │
│   46 │   │   modelInsLLM.call_model_name(llm_model_info['name'])                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: Can't instantiate abstract class MOSSLLM with abstract methods _history_len

**Comment by hzg0601** [comment]
https://github.com/imClumsyPanda/langchain-ChatGLM/pull/664
参考第二条优化
