### ISSUE TITLE
请问是否兼容新发布的第二代ChatGLM2-6B

### ISSUE THREAD

**Issue by 1586628236** [chatchat-space/Langchain-Chatchat#730]
请问是否兼容新发布的第二代ChatGLM2-6B？

**Comment by tomFoxxxx** [comment]
model_config.py修改了 但是加载模型还是报错

**Comment by 1586628236** [comment]
> model_config.py修改了 但是加载模型还是报错
参考一下Issues #732

**Comment by wayne78ck6** [comment]
不確定是否在ChatGLM2改了一點使用方式，
我之前用ChatGLM的code加載模型出了找不到.half() method的錯誤，
RuntimeError: "arange_cpu" not implemented for 'Half'
比對了一下各自專案的
之後我把model = AutoModel.from_pretrained("chatglm-6b", trust_remote_code=True).half().cuda()
改成ChatGLM2最初版本的web_demo.py裡面寫的：
    model = AutoModel.from_pretrained("chatglm2-6b", trust_remote_code=True, device='cuda')
就意外的通過了。
不過現在改回最新更新的model = AutoModel.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True).cuda()
又噴錯誤了。

爬文發現在ChatGLM那裡有相關討論
https://github.com/THUDM/ChatGLM2-6B/issues/33

查詢git commit以後，推測是當天改成把device='cuda'改成.cuda()後開始有人報錯
https://github.com/THUDM/ChatGLM2-6B/commit/3ee8ff7717f3bd9ac51d5492b16bef34ad20be37

修復方式推測是這個commit提到的transformers==4.30.2，
內文中也有人提到"torch升级到2.0.1.transformers升级到4.30就可以了"
https://github.com/THUDM/ChatGLM2-6B/commit/d3c58147eddd972df2bf393bd19123fe7563e65f

我自己的狀況是因為升級版本怕會弄壞其他程式(後悔沒用conda或contain了)，
所以暫時用model讀取時後面改成 device='cuda'的方式通過
(我是自架ChatGLM API再改code呼叫API，若要改code應該可以修改models/loader/loader.py)

**Comment by tomFoxxxx** [comment]
> 

谢谢！很有帮助！

**Comment by imClumsyPanda** [comment]
目前项目已更新至v0.2.2，支持并默认使用chatglm2-6b作为项目中所选语言模型
