### ISSUE TITLE
[BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters:

### ISSUE THREAD

**Issue by andywwy** [chatchat-space/Langchain-Chatchat#732]
**问题描述 / Problem Description**
采用chatglm2-6b，并且在3张gpu卡的情况下，会报如下错误：
 /home/ezdigit/anaconda3/envs/knowledgeBase/lib/python3.8/site-packages/accelerate/utils/modeling │
│ .py:902 in check_device_map                                                                      │
│                                                                                                  │
│    899 │   │   │   ]                                                                             │
│    900 │   if len(all_model_tensors) > 0:                                                        │
│    901 │   │   non_covered_params = ", ".join(all_model_tensors)                                 │
│ ❱  902 │   │   raise ValueError(                                                                 │
│    903 │   │   │   f"The device_map provided does not give any device for the following paramet  │
│    904 │   │   )                                                                                 │
│    905                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: The device_map provided does not give any device for the following parameters: transformer.embedding.word_embeddings.weight, transformer.rotary_pos_emb.inv_freq,
transformer.encoder.layers.0.input_layernorm.weight, transformer.encoder.layers.0.self_attention.query_key_value.weight,
transformer.encoder.layers.0.self_attention.query_key_value.bias, transformer.encoder.layers.0.self_attention.dense.weight,
.......

**复现问题的步骤 / Steps to Reproduce**
1. 修改配置为chatglm2-6b，并支持python cli_demo.py
2. 系统中存在多张gpu卡，我的环境是 3 张 3090 的卡

经过定位，可能是因为模型不同层分配到不同的gpu上，导致很多参数未分配或分配错误，从而device_map填写错误导致的，临时经过如下修改可以解决该问题：
修改 models/loader/loader.py 下的 LoaderCheckPoint类中的_load_model函数：
将 
if num_gpus < 2 and self.device_map is None :
修改为：
if (num_gpus < 2 and self.device_map is None) or ('chatglm2' in model_name.lower()) :

强制将模型所有层加载到一块gpu上，可以临时解决该问题。

但无法利用多gpu的性能了。

**Comment by xiongziqi** [comment]
same issue

**Comment by xiongziqi** [comment]
另一种解决办法：
在divice_map中对chatglm2-6b作单独配置

        if self.lora:
            layer_prefix = 'base_model.model.transformer'
            device_map = {f'{layer_prefix}.word_embeddings': 0,
                      f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
                      f'base_model.model.lm_head': 0, }
        elif self.model_name.find("chatglm2-6b") != -1:
            layer_prefix = 'transformer.encoder'
            device_map = {f'transformer.embedding.word_embeddings': 0,
                          f'transformer.rotary_pos_emb.inv_freq': 0,
                          f'transformer.output_layer': 0,
                          f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
                          f'base_model.model.lm_head': 0, }
        else:
            layer_prefix = 'transformer'
            device_map = {f'{layer_prefix}.word_embeddings': 0,
                      f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
                      f'base_model.model.lm_head': 0, }

**Comment by ye7love7** [comment]
> 另一种解决办法： 在divice_map中对chatglm2-6b作单独配置
> 
> ```
>     if self.lora:
>         layer_prefix = 'base_model.model.transformer'
>         device_map = {f'{layer_prefix}.word_embeddings': 0,
>                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                   f'base_model.model.lm_head': 0, }
>     elif self.model_name.find("chatglm2-6b") != -1:
>         layer_prefix = 'transformer.encoder'
>         device_map = {f'transformer.embedding.word_embeddings': 0,
>                       f'transformer.rotary_pos_emb.inv_freq': 0,
>                       f'transformer.output_layer': 0,
>                       f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                       f'base_model.model.lm_head': 0, }
>     else:
>         layer_prefix = 'transformer'
>         device_map = {f'{layer_prefix}.word_embeddings': 0,
>                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                   f'base_model.model.lm_head': 0, }
> ```

这个方法似乎并不行，我在loader里修改了这部分，还是同样的报错。

**Comment by xiongziqi** [comment]
> > 另一种解决办法： 在divice_map中对chatglm2-6b作单独配置
> > ```
> >     if self.lora:
> >         layer_prefix = 'base_model.model.transformer'
> >         device_map = {f'{layer_prefix}.word_embeddings': 0,
> >                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
> >                   f'base_model.model.lm_head': 0, }
> >     elif self.model_name.find("chatglm2-6b") != -1:
> >         layer_prefix = 'transformer.encoder'
> >         device_map = {f'transformer.embedding.word_embeddings': 0,
> >                       f'transformer.rotary_pos_emb.inv_freq': 0,
> >                       f'transformer.output_layer': 0,
> >                       f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
> >                       f'base_model.model.lm_head': 0, }
> >     else:
> >         layer_prefix = 'transformer'
> >         device_map = {f'{layer_prefix}.word_embeddings': 0,
> >                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
> >                   f'base_model.model.lm_head': 0, }
> > ```
> 
> 这个方法似乎并不行，我在loader里修改了这部分，还是同样的报错。

是同一个错误吗

**Comment by ye7love7** [comment]
同样的错误，我是按照你的修改的chatglm_auto_configure_device_map下修改的，有没有其他地方需要修改？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




   
另一种解决办法： 在divice_map中对chatglm2-6b作单独配置
     if self.lora:         layer_prefix = 'base_model.model.transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }     elif self.model_name.find("chatglm2-6b") != -1:         layer_prefix = 'transformer.encoder'         device_map = {f'transformer.embedding.word_embeddings': 0,                       f'transformer.rotary_pos_emb.inv_freq': 0,                       f'transformer.output_layer': 0,                       f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                       f'base_model.model.lm_head': 0, }     else:         layer_prefix = 'transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }   
这个方法似乎并不行，我在loader里修改了这部分，还是同样的报错。
  
是同一个错误吗

**Comment by ye7love7** [comment]
兄弟，我看源码用的是rotary.pos.emb，你为何用了inv.freq呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




   
另一种解决办法： 在divice_map中对chatglm2-6b作单独配置
     if self.lora:         layer_prefix = 'base_model.model.transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }     elif self.model_name.find("chatglm2-6b") != -1:         layer_prefix = 'transformer.encoder'         device_map = {f'transformer.embedding.word_embeddings': 0,                       f'transformer.rotary_pos_emb.inv_freq': 0,                       f'transformer.output_layer': 0,                       f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                       f'base_model.model.lm_head': 0, }     else:         layer_prefix = 'transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }   
这个方法似乎并不行，我在loader里修改了这部分，还是同样的报错。
  
是同一个错误吗

**Comment by xiongziqi** [comment]
这是根据代码报错来改的
但是目前没改完好像

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ye7love7 ***@***.***>
发送时间: Wednesday, June 28, 2023 5:49:42 PM
收件人: imClumsyPanda/langchain-ChatGLM ***@***.***>
抄送: xiongziqi ***@***.***>; Comment ***@***.***>
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)


兄弟，我看源码用的是rotary.pos.emb，你为何用了inv.freq呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午5:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)





另一种解决办法： 在divice_map中对chatglm2-6b作单独配置
if self.lora: layer_prefix = 'base_model.model.transformer' device_map = {f'{layer_prefix}.word_embeddings': 0, f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0, f'base_model.model.lm_head': 0, } elif self.model_name.find("chatglm2-6b") != -1: layer_prefix = 'transformer.encoder' device_map = {f'transformer.embedding.word_embeddings': 0, f'transformer.rotary_pos_emb.inv_freq': 0, f'transformer.output_layer': 0, f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0, f'base_model.model.lm_head': 0, } else: layer_prefix = 'transformer' device_map = {f'{layer_prefix}.word_embeddings': 0, f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0, f'base_model.model.lm_head': 0, }
这个方法似乎并不行，我在loader里修改了这部分，还是同样的报错。

是同一个错误吗

―
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

―

**Comment by ye7love7** [comment]
已经解决了，按照官方代码，不要inv.freq



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月28日(周三) 下午5:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




 这是根据代码报错来改的 
 但是目前没改完好像 
 
 获取 Outlook for iOS<https://aka.ms/o0ukef&gt; 
 ________________________________ 
 发件人: ye7love7 ***@***.***&gt; 
 发送时间: Wednesday, June 28, 2023 5:49:42 PM 
 收件人: imClumsyPanda/langchain-ChatGLM ***@***.***&gt; 
 抄送: xiongziqi ***@***.***&gt;; Comment ***@***.***&gt; 
 主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732) 
 
 
 兄弟，我看源码用的是rotary.pos.emb，你为何用了inv.freq呀？ 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年6月28日(周三) 下午5:01 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.******@***.***&amp;gt;; 
 主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732) 
 
 
 
 
 
 另一种解决办法： 在divice_map中对chatglm2-6b作单独配置 
 if self.lora: layer_prefix = 'base_model.model.transformer' device_map = {f'{layer_prefix}.word_embeddings': 0, f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0, f'base_model.model.lm_head': 0, } elif self.model_name.find("chatglm2-6b") != -1: layer_prefix = 'transformer.encoder' device_map = {f'transformer.embedding.word_embeddings': 0, f'transformer.rotary_pos_emb.inv_freq': 0, f'transformer.output_layer': 0, f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0, f'base_model.model.lm_head': 0, } else: layer_prefix = 'transformer' device_map = {f'{layer_prefix}.word_embeddings': 0, f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0, f'base_model.model.lm_head': 0, } 
 这个方法似乎并不行，我在loader里修改了这部分，还是同样的报错。 
 
 是同一个错误吗 
 
 ― 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt; 
 
 ―

**Comment by xiongziqi** [comment]
> 

怎么解决的喃？

**Comment by xiongziqi** [comment]
# bugfix: PEFT加载lora模型出现的层命名不同
        if self.lora:
            layer_prefix = 'base_model.model.transformer'
            device_map = {f'{layer_prefix}.word_embeddings': 0,
                      f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
                      f'base_model.model.lm_head': 0, }
        elif self.model_name.find("chatglm2-6b") != -1:
            layer_prefix = 'transformer.encoder'
            device_map = {'transformer.embedding.word_embeddings': 0,
                          'transformer.output_layer': 0,
                          'transformer.rotary_pos_emb': 0,
                          'transformer.encoder.final_layernorm': 0,
                          'lm_head': 0,
                          'base_model.model.lm_head': 0, }
        else:
            layer_prefix = 'transformer'
            device_map = {f'{layer_prefix}.word_embeddings': 0,
                      f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
                      f'base_model.model.lm_head': 0, }

**Comment by ye7love7** [comment]
是的，这样就可以了，源码有这部分的内容，可能还要优化，吐槽一下，chatglm2的思想钢印很强，怎么提示都还是回答自己是chatglm



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 上午9:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




     # bugfix: PEFT加载lora模型出现的层命名不同     if self.lora:         layer_prefix = 'base_model.model.transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }     elif self.model_name.find("chatglm2-6b") != -1:         layer_prefix = 'transformer.encoder'         device_map = {'transformer.embedding.word_embeddings': 0,                       'transformer.output_layer': 0,                       'transformer.rotary_pos_emb': 0,                       'transformer.encoder.final_layernorm': 0,                       'lm_head': 0,                       'base_model.model.lm_head': 0, }     else:         layer_prefix = 'transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }

**Comment by nilin1998** [comment]
> 请问这段代码加在哪个文件中呀

**Comment by nilin1998** [comment]
> 按照chatglm2-6b的模型配置文件中改的层映射，这个可以用了
> 
> ```
>     # bugfix: PEFT加载lora模型出现的层命名不同
>     if self.lora:
>         layer_prefix = 'base_model.model.transformer'
>         device_map = {f'{layer_prefix}.word_embeddings': 0,
>                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                   f'base_model.model.lm_head': 0, }
>     elif self.model_name.find("chatglm2-6b") != -1:
>         layer_prefix = 'transformer.encoder'
>         device_map = {'transformer.embedding.word_embeddings': 0,
>                       'transformer.output_layer': 0,
>                       'transformer.rotary_pos_emb': 0,
>                       'transformer.encoder.final_layernorm': 0,
>                       'lm_head': 0,
>                       'base_model.model.lm_head': 0, }
>     else:
>         layer_prefix = 'transformer'
>         device_map = {f'{layer_prefix}.word_embeddings': 0,
>                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                   f'base_model.model.lm_head': 0, }
> ```

请问这段代码应该放在哪个文件中呀

**Comment by ye7love7** [comment]
放在loader里面，有一大段注释的上面。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 中午1:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




  
按照chatglm2-6b的模型配置文件中改的层映射，这个可以用了
     # bugfix: PEFT加载lora模型出现的层命名不同     if self.lora:         layer_prefix = 'base_model.model.transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }     elif self.model_name.find("chatglm2-6b") != -1:         layer_prefix = 'transformer.encoder'         device_map = {'transformer.embedding.word_embeddings': 0,                       'transformer.output_layer': 0,                       'transformer.rotary_pos_emb': 0,                       'transformer.encoder.final_layernorm': 0,                       'lm_head': 0,                       'base_model.model.lm_head': 0, }     else:         layer_prefix = 'transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }   
请问这段代码应该放在哪个文件中呀

**Comment by zhipeng9802** [comment]
> 按照chatglm2-6b的模型配置文件中改的层映射，这个可以用了
> 
> ```
>     # bugfix: PEFT加载lora模型出现的层命名不同
>     if self.lora:
>         layer_prefix = 'base_model.model.transformer'
>         device_map = {f'{layer_prefix}.word_embeddings': 0,
>                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                   f'base_model.model.lm_head': 0, }
>     elif self.model_name.find("chatglm2-6b") != -1:
>         layer_prefix = 'transformer.encoder'
>         device_map = {'transformer.embedding.word_embeddings': 0,
>                       'transformer.output_layer': 0,
>                       'transformer.rotary_pos_emb': 0,
>                       'transformer.encoder.final_layernorm': 0,
>                       'lm_head': 0,
>                       'base_model.model.lm_head': 0, }
>     else:
>         layer_prefix = 'transformer'
>         device_map = {f'{layer_prefix}.word_embeddings': 0,
>                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,
>                   f'base_model.model.lm_head': 0, }
> ```

mark：这段代码可以解决chatglm2-6b的多卡部署的问题，除了chatglm2-6b外，vicuna-7b和vicuna-13b也存在类似问题

**Comment by ye7love7** [comment]
本质上按照报错提示，把这些头尾层放到一个卡上就可以了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月29日(周四) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




  
按照chatglm2-6b的模型配置文件中改的层映射，这个可以用了
     # bugfix: PEFT加载lora模型出现的层命名不同     if self.lora:         layer_prefix = 'base_model.model.transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }     elif self.model_name.find("chatglm2-6b") != -1:         layer_prefix = 'transformer.encoder'         device_map = {'transformer.embedding.word_embeddings': 0,                       'transformer.output_layer': 0,                       'transformer.rotary_pos_emb': 0,                       'transformer.encoder.final_layernorm': 0,                       'lm_head': 0,                       'base_model.model.lm_head': 0, }     else:         layer_prefix = 'transformer'         device_map = {f'{layer_prefix}.word_embeddings': 0,                   f'{layer_prefix}.final_layernorm': 0, 'lm_head': 0,                   f'base_model.model.lm_head': 0, }   
mark：这段代码可以解决chatglm2-6b的多卡部署的问题，除了chatglm2-6b外，vicuna-7b和vicuna-13b也存在类似问题

**Comment by ywm12345** [comment]
我是用多卡部署，当我调大CHUNK_SIZE后，prompt也随之增大，但这样会将其中一个的GPU打爆，为什么会是其中一个呢，那个大神解答一下，谢谢

**Comment by ysyx2008** [comment]
调用ChatGLM2-6B，在4块T4的服务器上部署顺利，自动多卡运行，没有报错。

**Comment by ye7love7** [comment]
嗯，作者已经更新了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月6日(周四) 下午5:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [imClumsyPanda/langchain-ChatGLM] [BUG]采用chatglm2-6b，并且在多张gpu卡的情况下，会报错The device_map provided does not give any device for the following parameters: (Issue #732)




 
调用ChatGLM2-6B，在4块T4的服务器上部署顺利，自动多卡运行，没有报错。

**Comment by zRzRzRzRzRzRzR** [comment]
更新最新的代码看看是否解决这个问题
