### ISSUE TITLE
[功能请求] 关于api.py，可以增加一个post请求的流式输出

### ISSUE THREAD

**Issue by devillaws** [chatchat-space/Langchain-Chatchat#733]
**功能描述**
我看到有一个websocket的流式接口，但可否再新增一个http的流式输出，可以使用fastapi的StreamingResponse实现
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/0717d821-c50c-4f26-a791-40deddd145df)

**解决的问题**.
可以解决只能使用http进行流式输出，且不能使用websock的应用场景

**实现建议**
使用fastapi的StreamingResponse实现，类似这样
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/5bbdce7b-4ad0-411d-b1c5-35ef5cd3e3ed)
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/ddae6629-db74-4e92-99c0-6c4cb2fc82b4)

**Comment by hzg0601** [comment]
想要流式就不能用Post,想要用post就不能流式

**Comment by lqhLoveSmy** [comment]
请问stream_chat会经常无限输出重复的结果  是什么原因

**Comment by devillaws** [comment]
> 想要流式就不能用Post,想要用post就不能流式

post当然可以流式啊

**Comment by zdj-1995** [comment]
@devillaws 你实现了流式返回吗？

**Comment by Alex-Zuo-One** [comment]
+1

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.x版本，已经支持了基于fastapi streamingreponse的流式输出，感谢反馈！
