### ISSUE TITLE
[BUG] ChatGLM2-6B loading error 【RuntimeError: "arange_cpu" not implemented for 'Half'】

### ISSUE THREAD

**Issue by tomFoxxxx** [chatchat-space/Langchain-Chatchat#735]
**问题描述 / Problem Description**
加载ChatGLM2-6B时 报错
RuntimeError: "arange_cpu" not implemented for 'Half'

│ /home/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py:69 │
│ 8 in __init__                                                                                    │
│                                                                                                  │
│    695 │   │   │   config.hidden_size // config.num_attention_heads if config.kv_channels is No  │
│    696 │   │   )                                                                                 │
│    697 │   │                                                                                     │
│ ❱  698 │   │   self.rotary_pos_emb = RotaryEmbedding(rotary_dim // 2, original_impl=config.orig  │
│    699 │   │   │   │   │   │   │   │   │   │   │     dtype=config.torch_dtype)                   │
│    700 │   │   self.encoder = init_method(GLMTransformer, config, **init_kwargs)                 │
│    701 │   │   self.output_layer = init_method(nn.Linear, config.hidden_size, config.padded_voc  │
│                                                                                                  │
│ /home/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py:90 │
│ in __init__                                                                                      │
│                                                                                                  │
│     87 class RotaryEmbedding(nn.Module):                                                         │
│     88 │   def __init__(self, dim, original_impl=False, device=None, dtype=None):                │
│     89 │   │   super().__init__()                                                                │
│ ❱   90 │   │   inv_freq = 1.0 / (10000 ** (torch.arange(0, dim, 2, device=device, dtype=dtype)   │
│     91 │   │   self.register_buffer("inv_freq", inv_freq)                                        │
│     92 │   │   self.dim = dim                                                                    │
│     93 │   │   self.original_impl = original_impl                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: "arange_cpu" not implemented for 'Half'

**复现问题的步骤 / Steps to Reproduce**
1. 本地merge最新的代码（基于master分支）
2. 替换model_config.py的文件路径
"chatglm2-6b": {
        "name": "chatglm2-6b",
        "pretrained_model_name": "THUDM/chatglm2-6b",
        "local_model_path": "/home/work/ChatGLM2-6B/model_data/chatglm2-6b",
        "provides": "ChatGLM"
    },
3. terminal执行 python cli_demo.py
4. 出现上述问题

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：d0b746c54ff662b851692cfb6ee8dd96d2927a68 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: Ubuntu 18.04
- Python 版本 / Python version:  3.9.16
- 其他相关环境信息 / Other relevant environment information: null

**附加信息 / Additional Information**
ChatGLM-6B    正常运行
ChatGLM2-6B  正常运行
langchain+ChatGLM-6B  正常运行

**Comment by tomFoxxxx** [comment]
Thanks so much !!!

**Comment by tomFoxxxx** [comment]
求回复 感谢

**Comment by hzg0601** [comment]
把model从半精度转换成全精度，或者加载的时候选择全精度，这可能是chatglm2用了一些cpu下才能执行的函数，导致奇怪的兼容性问题

**Comment by tomFoxxxx** [comment]
> 把model从半精度转换成全精度，或者加载的时候选择全精度，这可能是chatglm2用了一些cpu下才能执行的函数，导致奇怪的兼容性问题

谢谢，我尝试下。
ChatGLM2-6B 的 相关issue 提到是torh版本问题 需要torch2.0 我的是1.12，但是无法更新了，驱动受限。

**Comment by tomFoxxxx** [comment]
已解决：
修改loader.py即可

    from accelerate import dispatch_model
    # default (GLM-6B)
    # model = LoaderClass.from_pretrained(checkpoint,
    #                                     config=self.model_config,
    #                                     torch_dtype=torch.bfloat16 if self.bf16 else torch.float16,
    #                                     trust_remote_code=True).half()
    # modified (GLM2-6B)
    model = LoaderClass.from_pretrained(checkpoint,
                                      config=self.model_config,
                                      torch_dtype=torch.bfloat16 if self.bf16 else torch.float16,
                                      trust_remote_code=True,
                                      device='cuda')

**Comment by xbsdsongnan** [comment]
还有其他方法么

**Comment by tomFoxxxx** [comment]
> 还有其他方法么

更新使用pytorch2.0+版本
