### ISSUE TITLE
[BUG] 教程代码似乎有bug，导致无法加载LLM模型，可能是版本问题？

### ISSUE THREAD

**Issue by Eviannn** [chatchat-space/Langchain-Chatchat#738]
参考教程：https://www.heywhale.com/mw/project/643977aa446c45f4592a1e59

提供的代码中：
LLM_MODEL = "chatglm-6b"     # LLM 模型名，对应 llm_model_dict
LLM_HISTORY_LEN = 3
DEVICE = "cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu"

local_doc_qa = LocalDocQA()

local_doc_qa.init_cfg(llm_model=LLM_MODEL,
                          embedding_model=EMBEDDING_MODEL,
                          llm_history_len=LLM_HISTORY_LEN,
                          top_k=VECTOR_SEARCH_TOP_K)

LLM_MODEL 变量是str类型，但是local_doc_qa中的llm_model需要指定baseanswer类型，导致报错，无法加载LLM模型。

我只能手动添加代码：
shared.loaderCheckPoint = LoaderCheckPoint({"--model-dir":"./chatglm-6b", "model_name":"chatglm-6b"})
llm_model_ins = shared.loaderLLM(llm_model="chatglm-6b",no_remote_model=True)

再修改shared中第31行代码为loaderCheckPoint.model_name = llm_model_dict[pre_model_name]['name']

然后把llm_model_ins赋给llm_model才能解决，此时llm_model_ins类型为models.chatglm_llm.ChatGLM

**Comment by guluo2016** [comment]
遇到了同样的问题
基于langchain-ChatGLM master分支来看，基于你的需要新增一段代码修改，否则会报错：
```
ValueError: 本地模型local_model_path未配置路径
```

修改如下：
1. 修改langchain-ChatGLM/models/shared.py  (30-31行)
```python
if loaderCheckPoint.no_remote_model:
    #loaderCheckPoint.model_name = llm_model_info['name']
    loaderCheckPoint.model_name = llm_model_dict[pre_model_name]['name']
    llm_model_info["local_model_path"] = loaderCheckPoint.model_path
else:
    loaderCheckPoint.model_name = llm_model_info['pretrained_model_name']
```
2. 参考教程：https://www.heywhale.com/mw/project/643977aa446c45f4592a1e59
在调用`local_doc_qa.init_cfg()` 前，新增两行代码：
```python
# model_path 指定glm-6b模型的路径
shared.loaderCheckPoint = LoaderCheckPoint({"model_path":"/home/mw/input/chatglm-6b", "model_name":"chatglm-6b"})
llm_model_ins = shared.loaderLLM(llm_model="chatglm-6b",no_remote_model=True)
```

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
