### ISSUE TITLE
基于知识库中所有文档的某一个文档进行问答，如何实现

### ISSUE THREAD

**Issue by hengwangyue** [chatchat-space/Langchain-Chatchat#745]
**功能描述 / Feature Description**
任务要求：有100篇新闻，包括体育类、娱乐类、时政类、金融类等，每篇新闻是一个TXT文档，当进行问答时，需要基于某一篇具体的新闻进行问答，而不是全部的的新闻进行问答，请问目前如何实现？

**Comment by sunlin-xiaonai** [comment]
我有一个思路就是在存储的时候给文档向量去建立索引，可以去问的时候直接定位到里面去

**Comment by Helenailse1** [comment]
期待实现

**Comment by zfanswer** [comment]
> **功能描述 / Feature Description** 任务要求：有100篇新闻，包括体育类、娱乐类、时政类、金融类等，每篇新闻是一个TXT文档，当进行问答时，需要基于某一篇具体的新闻进行问答，而不是全部的的新闻进行问答，请问目前如何实现？

直接向量数据库命中只取top1，然后上下文chunk_size调非常高，用chatglm2-6b（支持8k长度）做prompt解析，这就相当于把命中的那一个txt文档全部塞到prompt里当作知识去回答你的问题，不知效果如何。
