### ISSUE TITLE
[BUG] 文件未成功加载，Package not found

### ISSUE THREAD

**Issue by sungh66** [chatchat-space/Langchain-Chatchat#748]
**问题描述 / Problem Description**
使用webui.py，新建知识库后无法加载新文件（或者文件夹）

**实际结果 / Actual Result**
文件未成功加载，请重新上传文件
ERROR2023-06-30 Packageat 10:03:54 098-1d: not found /tmp/tmplkgw4ffz/xx.doc

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新git
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B-int8
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
- Python 版本 / Python version:
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后尝试
