### ISSUE TITLE
[BUG] 把代码修改成单显卡运行后，使用本地知识库上传文件时还是用的默认第一张卡

### ISSUE THREAD

**Issue by string-new** [chatchat-space/Langchain-Chatchat#751]
**问题描述 / Problem Description**
有两张卡，其中一台跑的api，准备另一张跑weiui，在启动api后把代码修改成这样，强制使用第二张卡：

# 可传入device_map自定义每张卡的部署情况
                    if self.device_map is None:
                        if 'chatglm1' in model_name.lower():
                            self.device_map = self.chatglm_auto_configure_device_map(num_gpus)
                        elif 'moss' in model_name.lower():
                            self.device_map = self.moss_auto_configure_device_map(num_gpus, model_name)
                        else:
                            self.device_map = infer_auto_device_map(model,
                                                                    dtype=torch.int8,
                                                                    no_split_module_classes=model._no_split_modules,
                                                                    max_memory={0: "0GiB", 1: "20GiB"})
                            #self.device_map = self.chatglm_auto_configure_device_map(num_gpus)
                    model = dispatch_model(model, device_map=self.device_map)

这样再启动webui后确实是在第二张卡上面跑的，但是后面上传本地知识库时发现又是在第一张显卡上处理的，但是内存不够用直接卡死了

.

**Comment by zRzRzRzRzRzRzR** [comment]
更新最新代码后，指定embed和llm不同卡试试
