### ISSUE TITLE
建议对于ChatGLM2 6B做支持，是否现有的流程本身就是支持，只是把模型换成ChatGLM2 6B?

### ISSUE THREAD

**Issue by quitevoid** [chatchat-space/Langchain-Chatchat#762]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by hzg0601** [comment]
已经支持了

**Comment by elven2016** [comment]
> 

你好，多GPU的问题解决了吗？

**Comment by hzg0601** [comment]
> > 
> 
> 你好，多GPU的问题解决了吗？

解决了，但是不在这个仓库了，在这儿https://github.com/hzg0601/langchain-ChatGLM-annotation。你可以参考其中的loader.py的217-226行进行修改

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.x版本，默认使用fastchat提供本地模型接口，支持多gpu加载，具体实现可参考README-开发部署-5.1.2，感谢反馈！
