### ISSUE TITLE
chagglm2-6b知识库不能用

### ISSUE THREAD

**Issue by lnLiChang** [chatchat-space/Langchain-Chatchat#764]
**问题描述 / Problem Description**

chagglm-6b没问题，而chagglm2-6b就不行

对话两轮以上就出现类似下面的返回：

根据已知信息，我无法得到确切的问题，因此无法回答您的问题。
出处 [1] local_knowledge_clothing_describe.txt

启动时有错误：
`
INFO  2023-07-03 11:41:51,206-1d:
loading model config
llm device: cuda
embedding device: cuda
dir: C:\App\langchain-ChatGLM
flagging username: 83bb44d1b005499b889afd5f27854b5e

Loading THUDM/chatglm2-6b-int4...
WARNING 2023-07-03 11:42:03,104-1d: Load parallel cpu kernel failed C:\Users\Admin\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\939776ad4ccb3aaee7d8111af5d607312f1f0719\quantization_kernels_parallel.so: Traceback (most recent call last):
  File "C:\Users\Admin/.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\939776ad4ccb3aaee7d8111af5d607312f1f0719\quantization.py", line 125, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "C:\Sdk\Python\Python310\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Sdk\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\Admin\.cache\huggingface\modules\transformers_modules\THUDM\chatglm2-6b-int4\939776ad4ccb3aaee7d8111af5d607312f1f0719\quantization_kernels_parallel.so' (or one of its dependencies). Try using the full path with constructor syntax.

Loaded the model in 9.93 seconds.
WARNING 2023-07-03 11:42:10,979-1d: No sentence-transformers model found with name C:\Users\Admin/.cache\torch\sentence_transformers\GanymedeNil_text2vec-large-chinese. Creating a new one with MEAN pooling.
{'answer': '你好👋！我是人工智能助手 ChatGLM2-6B，很高兴见到你，欢迎问我任何问题。'}
Running on local URL:  http://0.0.0.0:7861
`

**Comment by bg1avd** [comment]
在配置文件里把缓存知识库数量CHCHED_VS_NUM改成10试试，我改过后好点

**Comment by mougua** [comment]
加载到本地能解决很多奇怪问题

```
    "chatglm2-6b": {
        "name": "chatglm2-6b",
        "pretrained_model_name": "THUDM/chatglm2-6b",
        "local_model_path": "/data/llm/models/chatglm2-6b",
        "provides": "ChatGLM"
    }
```

**Comment by kendou** [comment]
同样， 两三轮后就出现“根据已知信息，我无法得到确切的问题，因此无法回答您的问题。”。 CACHED_VS_NUM改成10也没什么用。

**Comment by mougua** [comment]
我看到上面的报错有个so后缀的文件（Windows的话应该是dll）吧，估计扔到wsl2里跑能解决

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
