### ISSUE TITLE
加载本地知识库后，知识库里没有的问题也会回答，没法限制回答只根据知识库

### ISSUE THREAD

**Issue by 81858** [chatchat-space/Langchain-Chatchat#765]
加载了我的文档后，我发现我问与文档毫不相关的问题，他也会回答，然后我尝试了修改VECTOR_SEARCH_SCORE_THRESHOLD，但是好像没用，PROMPT_TEMPLATE我也修改了下，也没有用，都会回答，请问下怎么限制他只根据我的文档回答我提的问题呢？

**Comment by sunlin-xiaonai** [comment]
是的我也碰到了同样的问题，这个不知道是什么原因导致的

**Comment by sunlin-xiaonai** [comment]
不知道是langchain部分的问题还是说是这个chatglm代码的问题

**Comment by 81858** [comment]
> 不知道是langchain部分的问题还是说是这个chatglm代码的问题

我现在在修改prompt，我让他如果len(related_docs_with_score) > 0就生成模板prompt调用LLM模型，否则prompt=直接回答’我无法回答这个问题‘，但是我测试了下 ，我发现问与文档不相关的问题确实会回答’我无法回答这个问题‘，但是我问文档内的问题也会这么回答。。。

**Comment by hzg0601** [comment]
这个项目的机制是搜索文档里的文本，把相似的文本抽出来跟prompt拼在一起，再调用llm根据新的prompt回答问题，所以不管什么问题，它必然是会回答，因为最终的出口是llm

**Comment by 81858** [comment]
> 这个项目的机制是搜索文档里的文本，把相似的文本抽出来跟prompt拼在一起，再调用llm根据新的prompt回答问题，所以不管什么问题，它必然是会回答，因为最终的出口是llm

嗯嗯  我改了下   如果搜索的内容为空 直接输出无法回答  已经改好啦

**Comment by mougua** [comment]
我换了ChatGLM2有一点改善

**Comment by ywm12345** [comment]
我特地搜索知识库没有的知识，向量搜索还是会找出一堆无关的上下文

**Comment by zfanswer** [comment]
> 我特地搜索知识库没有的知识，向量搜索还是会找出一堆无关的上下文

你需要调整 VECTOR_SEARCH_SCORE_THRESHOLD 

用text2vec我尝试一般600左右
用m3e-base的话设到150左右
效果还可以

**Comment by yamazaki0000007** [comment]
you need to modify the code ,remove history or it gives wrong prompt.

**Comment by 81858** [comment]
> you need to modify the code ,remove history or it gives wrong prompt.

thank you for your reply,I changed the LLM not to be called if the search results are empty

**Comment by wangqiuqiu111** [comment]
> 

怎么改的呀

**Comment by xs1145** [comment]
> > 
> 
> 请问下你是怎么改的呢？我改了prompt还是不行，

prompt修改也是限制不到的，你在local_doc_qa里边的get_knowledge_based_answer修改，让他搜索到的知识库内容为空的话就直接输出我不知道就可以了，这样基本就能限制他的回答

**Comment by Leweibo** [comment]
没有找到相关文档时，如何设置不提交到LLM模型，不做任何答复？

**Comment by Leweibo** [comment]
> > you need to modify the code ,remove history or it gives wrong prompt.
> 
> thank you for your reply,I changed the LLM not to be called if the search results are empty

请问您时如何修改的？
