### ISSUE TITLE
若未找到内容能否不提示出处

### ISSUE THREAD

**Issue by devillaws** [chatchat-space/Langchain-Chatchat#767]
若未找到内容，能否不提示出处
<img width="591" alt="603f651062b5120937b74b00281f316" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/4ec94ead-0888-4a84-ac70-15c4df799df4">

**Comment by hzg0601** [comment]
这需要你根据实际情况设置相似度的阈值
