### ISSUE TITLE
AttributeError: 'str' object has no attribute '_call'

### ISSUE THREAD

**Issue by xiangfeng98** [chatchat-space/Langchain-Chatchat#769]
local_doc_qa.llm._call("chatglm-6b 的局限性具体体现在哪里，如何实现改进")
AttributeError: 'str' object has no attribute '_call'

为什么调用这个 会直接报这个错呢？

**Comment by Allinwang0528** [comment]
你这边解决了吗  我也遇到了同样的问题

**Comment by yuyunfeng666** [comment]
同

**Comment by guluo2016** [comment]
可参考这里： #738
