### ISSUE TITLE
如何改成多卡推理？

### ISSUE THREAD

**Issue by nameless0704** [chatchat-space/Langchain-Chatchat#77]

**Comment by qianchen94** [comment]
+1

**Comment by imClumsyPanda** [comment]
可以考虑参考chatglm-6b项目的issue中关于使用accelerate进行多卡推理的内容

qianchen94 ***@***.***>于2023年4月14日 周五11:30写道：

**Comment by nameless0704** [comment]
感谢 https://github.com/THUDM/ChatGLM-6B/issues/347 和群主
windows系统+cuda的最直接单机多卡解决方法：
1. !pip install bitsandbytes accelerate
2. 在chatglm_llm.py文件里，AutoModel.from_pretrained函数中增加三个参数：
        if torch.cuda.is_available():
            self.model = (
                AutoModel.from_pretrained(
                    model_name_or_path,
                    load_in_8bit=True, #new
                    torch_dtype=torch.float16, #new
                    device_map="auto", #new
                    trust_remote_code=True)
                .half()
                .cuda()
            )

**Comment by nameless0704** [comment]
改成单机多卡推理，AutoModel里加上device_map='auto'之后会报错：tensor不在同一个device上，但是sentencetransformers里读的embeddings和langchain UnstructedFileLoader好像（暂时）都没法multigpu……所以根本不能在一个device？

**Comment by wengieeee** [comment]
> 
你好，你最后有实现多卡推理吗？我是一台机器有4个3080，一个卡有点不ok，想4个卡一起推理。

**Comment by imClumsyPanda** [comment]
项目里面默认检测卡数，所以一个会分配到不同卡上

**Comment by caowenhero** [comment]
webui.py 运行后只有GPU 0占用显存多，其他卡显存不够，应该怎么配置啊

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起

**Comment by xsin333** [comment]
如果支持多卡的话  很多卡可以盘活
