### ISSUE TITLE
想问一下macOS能运行这个项目吗

### ISSUE THREAD

**Issue by Bruce-XUZILIN** [chatchat-space/Langchain-Chatchat#775]
如题，下面是我的电脑配置，能运行这个项目么。
![截屏2023-07-04 15.09.23.png](https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/ec1636a71656495facbfe52e28bc3d4d~tplv-k3u1fbpfcp-watermark.image?)

**Comment by Bruce-XUZILIN** [comment]
内存8GB

**Comment by bosir** [comment]
8G内存，别想了，我的电脑是Macbook Air M1  16G,能跑起来，但是几分钟才能输出1个字，根本没法用的

**Comment by DL909** [comment]
chatGLM对mac系统的支持非常差，最好不要尝试

**Comment by imClumsyPanda** [comment]
目前项目已更新至0.2.2，支持使用openai gpt api和openai embedding api，在本地资源不足时，可尝试使用上述api运行
