### ISSUE TITLE
[FEATURE] 可以支持分布式部署吗？大模型通过配置接口地址形式

### ISSUE THREAD

**Issue by xingyun52** [chatchat-space/Langchain-Chatchat#777]
**功能描述 / Feature Description**
用简洁明了的语言描述所需的功能 / Describe the desired feature in a clear and concise manner.

**解决的问题 / Problem Solved**
解释此功能如何解决现有问题或改进项目 / Explain how this feature solves existing problems or improves the project.

**实现建议 / Implementation Suggestions**
如果可能，请提供关于如何实现此功能的建议 / If possible, provide suggestions on how to implement this feature.

**替代方案 / Alternative Solutions**
描述您考虑过的替代方案 / Describe alternative solutions you have considered.

**其他信息 / Additional Information**
添加与功能请求相关的任何其他信息 / Add any other information related to the feature request.

**Comment by tomFoxxxx** [comment]
+1

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.x版本，默认使用fastchat提供本地模型接口，支持分布式部署，感谢反馈！
