### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by Bruce-XUZILIN** [chatchat-space/Langchain-Chatchat#780]
每次上传文件后都像下面截图一样一直在uploading，然后终端会报如下的错误，求解答：
>   File "/home/user2/anaconda3/envs/bruce233/lib/python3.8/site-packages/gradio/components.py", line 269, in save_uploaded_file
    temp_dir.mkdir(exist_ok=True, parents=True)
  File "/home/user2/anaconda3/envs/bruce233/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/gradio/725318ed313689fc4c27c97aa3902bc3c4a37d3c'

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/64894888/f3138ec5-f05a-499e-a841-311bbca74a5e)

**Comment by danny-zhu** [comment]
看起来是启动应用的用户权限有问题，现在解决了吗

**Comment by Tristar10** [comment]
换一个老一些的transformers版本就好了

**Comment by Droliven** [comment]
请问要降到哪个版本的 transformers ，我现在 4.34.0 还是不行~
