### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by nysaisai** [chatchat-space/Langchain-Chatchat#781]
![311dd528c814154c1af187111425dc8](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/17673699/feb2785c-e6c6-4e5d-8031-c6846ae6113a)

各位，本地电脑：16G+6G显存，langchain-chatglm，模型用的chatglm2-6b-int4，回答速度超慢，一两分钟一两个字，这样的速度正常吗？

**Comment by cherish160** [comment]
我也遇到了同样的问题，int4，一秒两个字，很慢，请问你解决了吗

**Comment by zRzRzRzRzRzRzR** [comment]
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起

**Comment by Mioooooo** [comment]
我也遇到了，你解决了吗？
