### ISSUE TITLE
在加载几个文件后，只能回答一个文件的内容，其它的都是无法回答

### ISSUE THREAD

**Issue by bg1avd** [chatchat-space/Langchain-Chatchat#783]
在加载几个文件后，只能回答一个文件的内容，其它的都是无法回答

**复现问题的步骤 / Steps to Reproduce**
1. 上传文件，多次上传文件，不是上传文件夹，而是单独多次上传文件
2. 对最后一个上传的文件进行提问，可以基于这个文件回答问题
4. 对最先上传的文件进行提问，软件扫描最后上传的文件，回答没有找到答案

**环境信息 / Environment Information**
- langchain-ChatGLM 版本： ChatGLM2-6B
- 是否使用 Docker 部署（是/否）：否
- 使用的模型 :  ChatGLM2-6B 
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: Ubuntu 20.04
- Python 版本 / Python version: python3.10

**Comment by javabloger** [comment]
是的，我们的环境和您遇到的问题是一模一样的。希望能有人解决或解答。

**Comment by finyone** [comment]
> 

你的显存多少？知识库能问几个问题？我这16G显存，只能问一个问题，第二个就崩了

**Comment by bg1avd** [comment]
> 

我用的是2080ti魔改22G的显卡，载入两个文件开始就胡言乱语了

**Comment by bg1avd** [comment]
我仔细研究发现：
1，只能进行一个文件的问答，一个知识库里只能存在一个文件，多了就不行
2，把文本入库的长度改为50更好，也许对于中文可以用100，但是分析英文只能采用更小的步长

**Comment by zfanswer** [comment]
> 1，只能进行一个文件的问答，一个知识库里只能存在一个文件，多了就不行

看下这个 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771

**Comment by zfanswer** [comment]
> > 
> 
> 你的显存多少？知识库能问几个问题？我这16G显存，只能问一个问题，第二个就崩了

看下这个 https://github.com/imClumsyPanda/langchain-ChatGLM/issues/637#issuecomment-1594218771

**Comment by zfanswer** [comment]
> 我仔细研究发现： 1，只能进行一个文件的问答，一个知识库里只能存在一个文件，多了就不行 2，把文本入库的长度改为50更好，也许对于中文可以用100，但是分析英文只能采用更小的步长

1，肯定是不对的，我在v0.1.16下放多个文件也没问题，你用的是哪个分支？

**Comment by bg1avd** [comment]
> > 我仔细研究发现： 1，只能进行一个文件的问答，一个知识库里只能存在一个文件，多了就不行 2，把文本入库的长度改为50更好，也许对于中文可以用100，但是分析英文只能采用更小的步长
> 
> 1，肯定是不对的，我在v0.1.16下放多个文件也没问题，你用的是哪个分支？

我也是这个分支，我可以放几个文件，但是放多了文件也没用，只回答最后一个文件的内容

**Comment by zfanswer** [comment]
我的可以从多个文件分别回答的。

你是每个文件内容都很少么？ 检索上下文chunk_size很大，比一个文件内容多很多？
但是0.1.16确实有个bug，就是文件内容很少的时候，它向量数据库内上下文扩展的时候会把其他文件的内容也合并到一起，在MyFAISS.py里可以看到一个TODO，那里还没做按文件分割引用。
所以可能造成多个文件内容放在一个引用里的bug，然后一并给LLM做最后回答，然后导致LLM找不到答案回答不了的情况。

不知道你的是不是这样，然后你也可以先去chatglml _llm里把temprarutre给改大点，0.1.16里默认给的0.01太小了，知识稍微复杂点都不会好好回答，可以改成0.5之类的试试看。

**Comment by wufxgtihub123** [comment]
> 

@zfanswer 你好，请问你有遇到上传一个100m左右的txt文档，上传很慢的情况吗？我上传了1个小时还没有成功，不知道是什么问题，也没有报错

**Comment by bg1avd** [comment]
> > 
> 
> @zfanswer 你好，请问你有遇到上传一个100m左右的txt文档，上传很慢的情况吗？我上传了1个小时还没有成功，不知道是什么问题，也没有报错

肯定是这样的，因为上传不是简单的上传文件，是需要对文件进行词语分割的

**Comment by GlennCGL** [comment]
> > > 
> > 
> > 
> > @zfanswer 你好，请问你有遇到上传一个100m左右的txt文档，上传很慢的情况吗？我上传了1个小时还没有成功，不知道是什么问题，也没有报错
> 
> 肯定是这样的，因为上传不是简单的上传文件，是需要对文件进行词语分割的

插个题外话请教下您的ubuntu20.04能安装yum吗？看安装里需要yum install libX11来支持paddleocr，这里我卡住了

**Comment by bg1avd** [comment]
apt install libX11-dev
