### ISSUE TITLE
如何修改为个性化的prompt呢？

### ISSUE THREAD

**Issue by SHITIANYU-hue** [chatchat-space/Langchain-Chatchat#796]
**功能描述 / Feature Description**
我希望他不仅仅可以解答问题，同时可以有一定风格的说话能力，比如用可爱的说话风格回复我的问题

请问应该在哪里可以设定prompt进行修改呢？

**Comment by codeAndxv** [comment]
你可以在configs/model_config.py修改 PROMPT_TEMPLATE值

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后再PROMPT_TEMPLATE修改代码即可
