### ISSUE TITLE
[BUG] MyFAISS store_len=1时，similarity_search_with_score_by_vector返回空

### ISSUE THREAD

**Issue by kinghuin** [chatchat-space/Langchain-Chatchat#799]
**问题描述 / Problem Description**

文档如果只有一句话，会直接挑出[上下文拓展逻辑](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/vectorstores/MyFAISS.py#L91)会等于1，此时走到[这个条件](https://github.com/imClumsyPanda/langchain-ChatGLM/blob/master/vectorstores/MyFAISS.py#L98)
会直接返回空列表，不会处理id_set中的唯一元素。 
这个条件判断为什么是用 not rearrange_id_list，而不是使用not id_set呢？设置rearrange_id_list这个变量的目的是？

**预期的结果 / Expected Result**
返回该文档的唯一一句话

**实际结果 / Actual Result**
返回空列表

**Comment by codeAndxv** [comment]
代码是有问题， 可以看看我的改法  https://github.com/codeAndxv/langchain-llm/blob/master/vectorstores/MyFAISS.py#L99
