### ISSUE TITLE
[BUG] 配置知识库文件上传显示ERROR

### ISSUE THREAD

**Issue by spider-warrior** [chatchat-space/Langchain-Chatchat#800]
**问题描述 / Problem Description**
点击配置知识库下的“请选择要加载的知识库”后上传文件页面组件显示“ERROR”

**复现问题的步骤 / Steps to Reproduce**
1. 启动项目
2. 访问页面
3. 点击“请选择要加载的知识库“
4. 上传文件页面组件显示“ERROR”

**预期的结果 / Expected Result**

**实际结果 / Actual Result**
上传文件页面组件显示“ERROR”

**环境信息 / Environment Information**
- 版本: e68bc53cabd1b18d070b84a9e10abb4829b5a2f3
- 是否使用 Docker 部署（是/否）：否
- 使用的模型: ChatGLM-6B
- 使用的 Embedding 模型: text2vec-large-chinese
- 操作系统及版本 / Operating system and version:
  DISTRIB_ID=Ubuntu
  DISTRIB_RELEASE=20.04
  DISTRIB_CODENAME=focal
  DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
- Python 版本 / Python version: 3.10.11
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by galen2027** [comment]
应该还有其它详细的报错信息吧，我记得默认情况下，同级目录下有logs，看看有没有其他日志文件

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后重试
