### ISSUE TITLE
[BUG] 本地知识库，同样的提问回答有时相同，有时不同

### ISSUE THREAD

**Issue by wasphuang** [chatchat-space/Langchain-Chatchat#806]
上传了一个本地知识库，中文。
提了一个本地知识库的问题，不断提交同样问题的情况下，问题的回答会变得相反。
在知识库测试Beta Tab下，提同样的问题，发现库中的结果命中且分值较低。
推测：有时走了LLM，有时走了本地知识库。
不论回答是什么，都会提示出处。

样本问题：
10、公司给客户报销的车票能否计入差旅费？
答复：不可以计入差旅费，应该计入业务招待费。

一种回答是不可以，另一种回答是可以。

---------------------------------------------------------
点击Web页面的 使用模式，切换到LLM对话时，同样的提问，提示了知识库的内容。
回答如下：
根据财税问答710_优化.docx的回答，公司给客户报销的车票不能计入差旅费，应该计入业务招待费。这是因为差旅费是指公司员工因工作原因外出访问、出差等所产生的费用，而报销的车票属于业务招待费。

微信群满了，是否可以再开一个微信群？请拉我入群方便交流。微信号 hornethuang

**Comment by LMC117** [comment]
试试把temperature调低一点呢？我设成0.05，每次回答基本都保持一致。
