### ISSUE TITLE
大规模数据推理（千万条），请问有无打batch，并行推理等推理加速方法。硬件资源充足

### ISSUE THREAD

**Issue by AllenYkl** [chatchat-space/Langchain-Chatchat#807]
**功能描述 / Feature Description**
大规模数据推理（千万条），请问有无打batch，并行推理等推理加速方法。硬件资源充足

**解决的问题 / Problem Solved**
多条同时推理

**Comment by lqhLoveSmy** [comment]
有解决方案了吗？

**Comment by lunalulu** [comment]
请问多batch这方面有进展吗？
