### ISSUE TITLE
[BUG] 下载依赖时 / ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.4.2 (from versions: none) ERROR: No matching distribution found for paddlepaddle==2.4.2

### ISSUE THREAD

**Issue by zhuiyi6** [chatchat-space/Langchain-Chatchat#810]
使用如下命令下载时报错：
pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.4.2 (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.4.2

**Comment by hzg0601** [comment]
直接conda install paddlepaddle，项目用的paddlepaddle的内容比较少，直接安装也能运行成功
