### ISSUE TITLE
[BUG] 问的次数越多，出处的文字越多，这是为啥？

### ISSUE THREAD

**Issue by ucas010** [chatchat-space/Langchain-Chatchat#812]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/b983d03a-a4a0-4a2d-99e9-dea1bcaa01c4)
而且都是重复的，本来很短的文本，最后怎么这么长了，而且再次提问会更多
其他人提问会更多，只要下边的参数不变，
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/50656998/fc5334dc-10ff-4bba-8082-74d5af979999)
返回的“出处”文字会越来越多。我勒个叉。
咋回事？？

**Comment by hzg0601** [comment]
因为项目把前n个历史的问答记录都拼接起来作为prompt

**Comment by ucas010** [comment]
@hzg0601 这个正常吗？“出处”的文字本来是不重复的，上面的完全都是重复的了。要是问100次，这GPU都爆了吧（如果作为prompt）

**Comment by hzg0601** [comment]
> @hzg0601 这个正常吗？“出处”的文字本来是不重复的，上面的完全都是重复的了。要是问100次，这GPU都爆了吧（如果作为prompt）

这个可以通过设置history_len来控制，重复的问题可以通过增加repeat_penalty来减轻
