### ISSUE TITLE
[BUG] views vue 执行起来后，聊天报undefined错

### ISSUE THREAD

**Issue by ablozhou** [chatchat-space/Langchain-Chatchat#817]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

**复现问题的步骤 / Steps to Reproduce**
```
cd veiws
npm run dev
```
在浏览器的界面中输入问题，回答:
问题出现 / Problem occurs:
- Cannot read properties of undefined (reading 'error')

**预期的结果 / Expected Result**
- 连接模型，正确回答问题

**实际结果 / Actual Result**
Cannot read properties of undefined (reading 'error')

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：()
- 是否使用 Docker 部署（是/否）：No
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version: Ubuntu 22.04.2 LTS
- Python 版本 / Python version: Python 3.10.11
- 其他相关环境信息 / Other relevant environment information: node v16.20.0, npm 8.19.4

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.
- 在views目录下执行start.sh 报错，没有service目录。

**Comment by kesshei** [comment]
Has anyone solved it?
