### ISSUE TITLE
如果导入的文件样式是问答式，项目是怎么处理的

### ISSUE THREAD

**Issue by stoneLee81** [chatchat-space/Langchain-Chatchat#818]
如果导入的文件是 提问， 回答 这样的样式文件，项目是怎么样对这类文件进行读取拆分的，也是作为一个文本，对其字符串拆分处理，还是做了一些什么特殊的处理

**Comment by zRzRzRzRzRzRzR** [comment]
取决于文件类型
什么形式都是按照文本来做，就看是什么文本
最新代码可以自定义分词器，你可以根据问答切分
