### ISSUE TITLE
[BUG] 该项目6月版本优化有一些问题，5月份的版本可以正常导入Chatglm2-6b且应对lora只需要修改配置文件

### ISSUE THREAD

**Issue by 976311200** [chatchat-space/Langchain-Chatchat#820]
个人使用问题：不一定是大家的问题
6月版本：
Lora加载方式修改为命令行方式且在web文件中存在修改难度
5月版本：
只需要修改对应的配置文件，即可完成Lora的加载。
并不太清楚6月相较于5月的架构优势是啥，但是从实用感受上而言会更难一些（可能自身代码水平有限）

**Comment by zetaoLian** [comment]
请问具体的哪个版本，以及配置文件如何修改呢
