### ISSUE TITLE
上传文件到知识库的解析过程太慢，CPU占用率不足2%。能否改为多线程并发处理？

### ISSUE THREAD

**Issue by ysyx2008** [chatchat-space/Langchain-Chatchat#821]
**功能描述 / Feature Description**
一个16MB的PDF解析时间超过1400秒，而CPU利用率不足2%。服务器配置不错，但利用率太低，希望改为多线程并发解析文件内容，提高CPU利用率，加快处理速度。

**解决的问题 / Problem Solved**
解决上传文件到知识库速度太慢的问题。

**Comment by Helenailse1** [comment]
+1

**Comment by dzgdp888** [comment]
同，上传个16M的文件，上传了20分钟了还卡着呢，CPU占用才13%

**Comment by aliware50** [comment]
解决了吗？

**Comment by ysyx2008** [comment]
> 解决了吗？

最近没有时间看，没人回复的话应该没解决吧。

**Comment by aliware50** [comment]
看来作者是不打算解决这个问题了

**Comment by hunter2009pf** [comment]
到现在还没解决向量化多线程的问题吗？该我出手了

**Comment by 302658980** [comment]
> 到现在还没解决向量化多线程的问题吗？该我出手了

出手了吗老哥
