### ISSUE TITLE
lora参数加载

### ISSUE THREAD

**Issue by DRZJ1** [chatchat-space/Langchain-Chatchat#824]
l请问ora模型怎么加载啊，一直加载不成功，不知道# 本地lora存放的位置
LORA_DIR = "/home/ubuntu/ChatGLM-6B/nt-_glm2_3.8ut_sft_v2/adapter_model"

# LLM lora path，默认为空，如果有请直接指定文件夹路径
LLM_LORA_PATH = "/home/ubuntu/ChatGLM-6B/nt-_glm2_3.8ut_sft_v2/adapter_model"
# USE_LORA = True if LLM_LORA_PATH else False
USE_LORA = True
# LLM streaming reponse
STREAMING = True
这部分该怎么改动

**Comment by learningguo** [comment]
+1

**Comment by DRZJ1** [comment]
这部分应该是没用，你要在运行cil_demo时，加上去
像这样python3 /home/ubuntu/langchain-ChatGLM/cli_demo.py   --model llama-7b  --no-remote-model  --lora-dir /home/ubuntu/ChatGLM-6B/lora  --lora checkpoint-16200

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.x版本，默认使用fastchat提供本地模型接口，lora加载方式已经与v0.1.x中不同，具体可参考README-开发部署-5.1.3，感谢反馈！
