### ISSUE TITLE
The device_map provided does not give any device for the following parameters: transformer.word_embeddings.weight, transformer.layers.0.input_layernorm.weight,

### ISSUE THREAD

**Issue by 191220042** [chatchat-space/Langchain-Chatchat#827]
**问题描述 / Problem Description**
在启动webui时添加了--lora 的参数，出现如下问题
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/80091648/592d48e5-e008-4379-b9d8-22456cb4357d)
根据报错内容将
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/80091648/458d142c-f8e7-47b1-afa7-128466c88327)
 使用lora部分分支也改为layer_prefix = 'transformer'可以成功运行，请问这里 layer_prefix = 'base_model.model.transformer'为什么会出错

**Comment by sralvins** [comment]
> **问题描述 / Problem Description** 在启动webui时添加了--lora 的参数，出现如下问题 ![image](https://user-images.githubusercontent.com/80091648/252926523-592d48e5-e008-4379-b9d8-22456cb4357d.png) 根据报错内容将 ![image](https://user-images.githubusercontent.com/80091648/252926691-458d142c-f8e7-47b1-afa7-128466c88327.png) 使用lora部分分支也改为layer_prefix = 'transformer'可以成功运行，请问这里 layer_prefix = 'base_model.model.transformer'为什么会出错

这里还没加载lora权重，模型还不是PeftModel，但这块已经按照PeftModel的layer名称来分配设备了，所以后面dispatch_model的时候会报错

**Comment by 191220042** [comment]
> > **问题描述 / Problem Description** 在启动webui时添加了--lora 的参数，出现如下问题 ![image](https://user-images.githubusercontent.com/80091648/252926523-592d48e5-e008-4379-b9d8-22456cb4357d.png) 根据报错内容将 ![image](https://user-images.githubusercontent.com/80091648/252926691-458d142c-f8e7-47b1-afa7-128466c88327.png) 使用lora部分分支也改为layer_prefix = 'transformer'可以成功运行，请问这里 layer_prefix = 'base_model.model.transformer'为什么会出错
> 
> 这里还没加载lora权重，模型还不是PeftModel，但这块已经按照PeftModel的layer名称来分配设备了，所以后面dispatch_model的时候会报错

所以说这里就不应该写base_model.model.transformer对吗？

**Comment by liujun3496** [comment]
您解决了吗
