### ISSUE TITLE
使用chatglm2,lora 运行报错[

### ISSUE THREAD

**Issue by DRZJ1** [chatchat-space/Langchain-Chatchat#830]
ubuntu@ip-172-31-74-124:~/ChatGLM-6B$ python3 /home/ubuntu/langchain-ChatGLM/cli_demo.py   --model chatglm2-6b  --no-remote-model  --lora-dir /home/ubuntu/ChatGLM-6B  --lora nt-_glm2_3.8ut_sft_v2
INFO  2023-07-12 11:44:32,054-1d: 
loading model config
llm device: cuda
embedding device: cuda
dir: /home/ubuntu/langchain-ChatGLM
flagging username: 5dd8bd6e43ab49808df26147ae95265f

INFO  2023-07-12 11:44:32,754-1d: Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO  2023-07-12 11:44:32,754-1d: NumExpr defaulting to 8 threads.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Loading chatglm2-6b...
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|██████████████████████████████| 7/7 [01:37<00:00, 13.93s/it]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
Loaded the model in 103.83 seconds.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Applying the following LoRAs to chatglm2-6b: nt-_glm2_3.8ut_sft_v2
╭─────────────────────────── Traceback (most recent call last) ────────────────────────────╮
│ /home/ubuntu/langchain-ChatGLM/cli_demo.py:66 in <module>                                │
│                                                                                          │
│   63 │   args = parser.parse_args()                                                      │
│   64 │   args_dict = vars(args)                                                          │
│   65 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                           │
│ ❱ 66 │   main()                                                                          │
│   67                                                                                     │
│                                                                                          │
│ /home/ubuntu/langchain-ChatGLM/cli_demo.py:16 in main                                    │
│                                                                                          │
│   13                                                                                     │
│   14 def main():                                                                         │
│   15 │                                                                                   │
│ ❱ 16 │   llm_model_ins = shared.loaderLLM()                                              │
│   17 │   llm_model_ins.history_len = LLM_HISTORY_LEN                                     │
│   18 │                                                                                   │
│   19 │   local_doc_qa = LocalDocQA()                                                     │
│                                                                                          │
│ /home/ubuntu/langchain-ChatGLM/models/shared.py:40 in loaderLLM                          │
│                                                                                          │
│   37 │   if 'FastChatOpenAILLM' in llm_model_info["provides"]:                           │
│   38 │   │   loaderCheckPoint.unload_model()                                             │
│   39 │   else:                                                                           │
│ ❱ 40 │   │   loaderCheckPoint.reload_model()                                             │
│   41 │                                                                                   │
│   42 │   provides_class = getattr(sys.modules['models'], llm_model_info['provides'])     │
│   43 │   modelInsLLM = provides_class(checkPoint=loaderCheckPoint)                       │
│                                                                                          │
│ /home/ubuntu/langchain-ChatGLM/models/loader/loader.py:433 in reload_model               │
│                                                                                          │
│   430 │   │   self.model, self.tokenizer = self._load_model(self.model_name)             │
│   431 │   │                                                                              │
│   432 │   │   if self.lora:                                                              │
│ ❱ 433 │   │   │   self._add_lora_to_model([self.lora])                                   │
│   434 │   │                                                                              │
│   435 │   │   if self.use_ptuning_v2:                                                    │
│   436 │   │   │   try:                                                                   │
│                                                                                          │
│ /home/ubuntu/langchain-ChatGLM/models/loader/loader.py:371 in _add_lora_to_model         │
│                                                                                          │
│   368 │   │   │   │   │   params['device_map'] = {"base_model.model." + k: v for k, v in │
│   369 │   │   │   │   elif self.load_in_8bit:                                            │
│   370 │   │   │   │   │   params['device_map'] = {'': 0}                                 │
│ ❱ 371 │   │   │   self.model.resize_token_embeddings(len(self.tokenizer))                │
│   372 │   │   │                                                                          │
│   373 │   │   │   self.model = PeftModel.from_pretrained(self.model, Path(f"{self.lora_d │
│   374                                                                                    │
│                                                                                          │
│ /home/ubuntu/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:1345 in   │
│ resize_token_embeddings                                                                  │
│                                                                                          │
│   1342 │   │   Return:                                                                   │
│   1343 │   │   │   `torch.nn.Embedding`: Pointer to the input tokens Embeddings Module o │
│   1344 │   │   """                                                                       │
│ ❱ 1345 │   │   model_embeds = self._resize_token_embeddings(new_num_tokens)              │
│   1346 │   │   if new_num_tokens is None:                                                │
│   1347 │   │   │   return model_embeds                                                   │
│   1348                                                                                   │
│                                                                                          │
│ /home/ubuntu/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:1361 in   │
│ _resize_token_embeddings                                                                 │
│                                                                                          │
│   1358 │   def _resize_token_embeddings(self, new_num_tokens):                           │
│   1359 │   │   old_embeddings = self.get_input_embeddings()                              │
│   1360 │   │   new_embeddings = self._get_resized_embeddings(old_embeddings, new_num_tok │
│ ❱ 1361 │   │   self.set_input_embeddings(new_embeddings)                                 │
│   1362 │   │                                                                             │
│   1363 │   │   # if word embeddings are not tied, make sure that lm head is resized as w │
│   1364 │   │   if self.get_output_embeddings() is not None and not self.config.tie_word_ │
│                                                                                          │
│ /home/ubuntu/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:1186 in   │
│ set_input_embeddings                                                                     │
│                                                                                          │
│   1183 │   │   """                                                                       │
│   1184 │   │   base_model = getattr(self, self.base_model_prefix, self)                  │
│   1185 │   │   if base_model is not self:                                                │
│ ❱ 1186 │   │   │   base_model.set_input_embeddings(value)                                │
│   1187 │   │   else:                                                                     │
│   1188 │   │   │   raise NotImplementedError                                             │
│   1189                                                                                   │
│                                                                                          │
│ /home/ubuntu/.local/lib/python3.8/site-packages/transformers/modeling_utils.py:1188 in   │
│ set_input_embeddings                                                                     │
│                                                                                          │
│   1185 │   │   if base_model is not self:                                                │
│   1186 │   │   │   base_model.set_input_embeddings(value)                                │
│   1187 │   │   else:                                                                     │
│ ❱ 1188 │   │   │   raise NotImplementedError                                             │
│   1189 │                                                                                 │
│   1190 │   def get_output_embeddings(self) -> nn.Module:                                 │
│   1191 │   │   """                                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────╯
NotImplementedError issue.

**Comment by sralvins** [comment]
因为chatglm2-6b的`modeling_chatglm.py`里没有`set_input_embedding`方法

**Comment by Littline** [comment]
所以是不支持使用chatGLM2吗

**Comment by Leo4zhou** [comment]
把self.model.resize_token_embeddings(len(self.tokenizer))这一条注释掉之后，可以加载lora。微调chatglm2的代码中默认也没有进行这一步，且尝试执行这一条也会报一样的错误，所以感觉应该不影响？
现在遇到的问题是，使用和chatglm2微调代码中一样的方式成功加载了lora模型，但是实测出来却是未加载lora的原始模型结果。

**Comment by liujun3496** [comment]
请问 您解决了吗

**Comment by zRzRzRzRzRzRzR** [comment]
请使用最新代码并用peft载入微调模型
