### ISSUE TITLE
[BUG] 关闭websocket链接都会报错

### ISSUE THREAD

**Issue by devillaws** [chatchat-space/Langchain-Chatchat#835]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/f55109c2-c9ef-4391-b922-3452ea692cf4)
无论使用postman还是webui还是api，该项目关闭ws链接都会报错

**Comment by hepengyue** [comment]
我也遇到这样的问题

**Comment by hepengyue** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/128773187/8a529503-8b1d-415a-9853-a3e7b9ef8895)
但是我的是这样的
