### ISSUE TITLE
[FEATURE] 希望可以增加自定义模型接入的文档，写明需要实现的方法和类

### ISSUE THREAD

**Issue by Joeking-around** [chatchat-space/Langchain-Chatchat#837]
**功能描述 / Feature Description**
希望可以增加自定义模型接入的文档，写明需要实现的方法和类，并提供示范

**解决的问题 / Problem Solved**
可以让使用者自行接入其他的大语言模型，而不需要等项目组逐个适配

**实现建议 / Implementation Suggestions**
model的loader类以及对对话的功能实现希望能够提供文档，以供二次开发

**替代方案 / Alternative Solutions**

**其他信息 / Additional Information**

**Comment by zhm-super** [comment]
大佬知道自定义接入模型需要如何实现吗

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索

**Comment by cyzLoveDream** [comment]
大佬搞定没，接入自己训练的模型没有文档，太痛苦了

**Comment by Joeking-around** [comment]
就是要重写loader和llm两个类但是没文档我不太想搞

**Comment by Joeking-around** [comment]
你好，我是胡程乔，你的来件已收到，谢谢复制搜索
