### ISSUE TITLE
关于如何提高知识库问答的答复质量和准确度，请各位大神有什么好的经验分享一下吧。

### ISSUE THREAD

**Issue by wuyabing** [chatchat-space/Langchain-Chatchat#844]
各位由如下方面问题的经验，请大神们分享经验，一起进步？
1、知识库问答的训练数据，有没有建议的格式，可以使知识库问答的答复质量和准确度得以提高？
2、关于知识库的训练文档，有没有比较好用的工具用于数据的处理？
3、知识库采用ChatGLM2-6B模型，关于一些参数配置调优，大家有没有什么好的建议，可以提高知识库问答的答复质量和准确度。

**Comment by xhochipe** [comment]
同问，今天自己拆分完模型以后，整体调试流程，发现搜索向量库出来的结果准确性不是很大，这个结果传递给llm下游，直接影响了模型的多轮对话效果

**Comment by HanXM715** [comment]
+1
