### ISSUE TITLE
[BUG] 上传本地数据库文件（450k，word）后会死机重启，显卡4080

### ISSUE THREAD

**Issue by mlwei1** [chatchat-space/Langchain-Chatchat#853]
如题，模型为chatglm-6b-int4，chatglm-6b也试过情况相同。显存16g

**Comment by Gy1900** [comment]
请问现在4080能使用吗？

**Comment by mlwei1** [comment]
> 请问现在4080能使用吗？

你好，电源的问题，现在我换了4090换了电源，可以了

**Comment by mlwei1** [comment]
> 请问现在4080能使用吗？

可以了，电源的问题，满载功耗不够

**Comment by Gy1900** [comment]
嗷嗷，好的，谢谢~

**Comment by mlwei1** [comment]
> 请问下您的cpu配置是什么？

现在我的配置是4090 R5 5600X,1000瓦的电源，运行良好

**Comment by Gy1900** [comment]
好的，感谢~
