### ISSUE TITLE
提示知识库以外的内容不要回答，但是仍然出现

### ISSUE THREAD

**Issue by bleakie** [chatchat-space/Langchain-Chatchat#855]
**例如导入机器学习的内容，PROMPT_TEMPLATE设置如下**
PROMPT_TEMPLATE = """已知信息：
{context} 

根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。 问题是：{question}"""

**当我问马云是谁的时候，他依然会介绍马云，请问该怎样解决呢？**

**Comment by andyzhou1982** [comment]
没法解决，马云是谁这个问题早就训练到大模型里面去了，跟你自己的知识库没关系

**Comment by cristianohello** [comment]
@andyzhou1982 @imClumsyPanda 
不会吧！二次增量训练或者设计prompt

**Comment by zRzRzRzRzRzRzR** [comment]
这个是提示词的问题
