### ISSUE TITLE
上传文件失败

### ISSUE THREAD

**Issue by devillaws** [chatchat-space/Langchain-Chatchat#865]
问题描述 
1.上传各类型文件都会报错
![QQ截图20230717115706](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/1c55ab92-36db-4875-9628-175d4225dda2)
![QQ截图20230717115647](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/8604432/297207cc-1c30-4852-9d66-a17b7aaaa1aa)

复现问题的步骤
1. 创建向量库
2. 选择任意docs文件上传
3. 所有文件上传都会出现error

**Comment by devillaws** [comment]
解决了，这个问题源自faiss库，因此重装了faiss就可以了

**Comment by danny-zhu** [comment]
有没有试过大文件上传，比如单个大小超过50M的文本

**Comment by cristianohello** [comment]
试过，100M的文件会出错，faiss不适合大文件，内存有限制

**Comment by zRzRzRzRzRzRzR** [comment]
faiss适合小文件，请使用其他我们支持的数据库尝试。
由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起
