### ISSUE TITLE
[BUG] 问答结果非正常生成终止

### ISSUE THREAD

**Issue by soultrans** [chatchat-space/Langchain-Chatchat#866]
**问题描述 / Problem Description**
在进行知识库问答中，发现生成的答案显示异常终止的情况。生成模型使用的使用ChatGLM2-6B，未作任何修改，加载的模型以及其他参数配置信息均来自与[THUDM/chatglm2-6b](https://huggingface.co/THUDM/chatglm2-6b/tree/main)。
生成迭代器的最后一个返回结果是 “提出了“《代表宣”，这明显不是正常的生成结果，起码也是”提出了“《代表宣言》。“，确认下整体生成返回的文本长度约为2085，请问这是有在哪里控制生成的最大文本长度吗？如何避免这种情况呢？感谢指点！

**Comment by zRzRzRzRzRzRzR** [comment]
这个应该在fschat源码改限制了，另外，可能是2048token的限制导致了输出中断。该问题在最新代码进行了解决，您可以在最新代码上重新尝试。如果有需求可以重新提起issue。
