### ISSUE TITLE
[BUG] 知识库中资源无法更新

### ISSUE THREAD

**Issue by mario2rio** [chatchat-space/Langchain-Chatchat#874]
**问题描述 / Problem Description**
已上传到知识库中的数据，通过调用fastapi无论是经过先delete后upload，还是直接update，向量数据都无法更新，问答依然以更新前的数据回答

**Comment by mario2rio** [comment]
资源更新和删除之类的操作会导致向量数据有问题，删除所有已有文档，重新上传别的文档，看样子是向量数据都没有生成，问答都是基础模型的回答了 。
具体操作，langchain-ChatGLM WebUI界面->创建知识库->上传文件->问答正常->删除文件->上传别的文件->问答新文件内容->基础模型回答。

**Comment by mario2rio** [comment]
reopem

**Comment by bg1avd** [comment]
我也有这个问题，具体你是怎么解决的？

**Comment by Mingxiangyu** [comment]
同样问题，现在感觉知识库都没有用了，回答都是模型自身的回答

**Comment by jimanji123** [comment]
同样问题，现在感觉知识库都没有用了，回答都是模型自身的回答

老版本正常，现在这个版本全是模型自身答案，没有引用知识库

**Comment by Mingxiangyu** [comment]
> 同样问题，现在感觉知识库都没有用了，回答都是模型自身的回答
> 
> 老版本正常，现在这个版本全是模型自身答案，没有引用知识库

langchain的老版本吗？我就说挺奇怪的，前两天还正常呢

**Comment by cristianohello** [comment]
+1

感觉新版本问题太多了！！！

**Comment by roseChainLisa** [comment]
一大堆问题，最基本的增删改查都做不好

**Comment by SKY-ZW** [comment]
没用的，  只是删除文件而已，并没有删除向量数据库里面的数据
