### ISSUE TITLE
本地lora参数该怎么修改？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#878]
![STXoVICzGv](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109277248/24c5869f-21a6-4e59-b7b2-d063921e1e5c)

下面第一个参数LORA_DIR 该怎么修改？
# 本地lora存放的位置
LORA_DIR = "loras/"

# LLM lora path，默认为空，如果有请直接指定文件夹路径
LLM_LORA_PATH = "/root/autodl-tmp/glm26b/langchain-ChatGLM-master/configs/cognition"

**Comment by cristianohello** [comment]
加载本地lora怎么不成功？

**Comment by andyzhou1982** [comment]
我的做法是在model_config.py中加上LORA常量，然后在args.py中将parser.add_argument('--lora', type=str,help='Name of the LoRA to apply to the model by default.')的default值设置为LORA常量

**Comment by cristianohello** [comment]
@andyzhou1982 
能具体点吗？大佬

**Comment by andyzhou1982** [comment]
model_config.py文件
![1689820598680](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/51428368/2d562e02-4ed0-4fb0-a947-6454577ecb3d)
args.py文件
![1689820667813](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/51428368/11bfe2be-2824-456c-a98d-f0540301d920)

**Comment by cristianohello** [comment]
@andyzhou1982 
大佬。LORA_DIR和LORA区别是什么呢？我是小白一个。

**Comment by cristianohello** [comment]
config.py代码是这样的：

# 本地lora存放的位置
LORA_DIR = "loras/"

# LLM lora path，默认为空，如果有请直接指定文件夹路径
LLM_LORA_PATH = ""
USE_LORA = True if LLM_LORA_PATH else False

**Comment by cristianohello** [comment]
@andyzhou1982 
报错如下大佬：
![1w9QwHUGK9](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109277248/4604b6b6-a0db-46cd-bbe8-3ff7c43f0a49)

**Comment by andyzhou1982** [comment]
看他的代码，是把LORA_DIR跟LORA拼起来作为完整路径

**Comment by cristianohello** [comment]
我用的chatglm2-6B

**Comment by cristianohello** [comment]
@andyzhou1982 
lora权重是合并之后的权重吗？还是lora十几M的权重

**Comment by cristianohello** [comment]
@

![7I1Lmq6mob](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/109277248/a0801c9e-414d-42df-9d12-f6120985f96e)

这LORA_DIR、LORA、LLM_LORA_PATH三个参数分别写什么呢？大佬能详细说一下吗

**Comment by Maxliag** [comment]
请问加载微调之后的lora成功了吗。我给路径之后运行api和webui使用模型回答感觉没有加载上微调的模型

**Comment by andyzhou1982** [comment]
![1689907998335](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/51428368/2fffa32e-a28a-433d-81de-0634f782c877)
这段出来说明加载lora成功了，如果回答没有变化，说明你的lora模型训练得不够
我也只是稍微研究了一下代码而已，LORA_DIR+LORA拼成的是lora的完整路径，LLM_LORA_PATH目前我没发现代码中的实际用处，需要项目开发者来解答了

**Comment by liujun3496** [comment]
> 请问加载微调之后的lora成功了吗。我给路径之后运行api和webui使用模型回答感觉没有加载上微调的模型
您成功了吗

**Comment by liujun3496** [comment]
> ![1689907998335](https://user-images.githubusercontent.com/51428368/255060088-2fffa32e-a28a-433d-81de-0634f782c877.png) 这段出来说明加载lora成功了，如果回答没有变化，说明你的lora模型训练得不够 我也只是稍微研究了一下代码而已，LORA_DIR+LORA拼成的是lora的完整路径，LLM_LORA_PATH目前我没发现代码中的实际用处，需要项目开发者来解答了

我也没有起作用

**Comment by liujun3496** [comment]
您搞定了吗

**Comment by R0nnyz** [comment]
同问，并且想知道可以实现lora多模型融合吗
