### ISSUE TITLE
[BUG] 通过FastChat API方式调用VICUNA13B，在进行知识库问答的时候出现token超限问题

### ISSUE THREAD

**Issue by tanglu86** [chatchat-space/Langchain-Chatchat#882]
目前想做一个企业知识库，测试数据集是一个6W字符的文档
使用langchain-chatglm + chatglm2-6b可以正常进行对话
使用langchain-chatglm + fastchat api + vicuna13b 随便问一个问题（比如请介绍一下xxx的优点）都出现token超限的问题 

openai.error.APIError: Invalid response object from API: '{"object":"error","message":"This model\'s maximum context length is 2048 tokens. However, you requested 2246 tokens (1734 in the messages, 512 in the completion). Please reduce the length of the messages or completion.","code":40303}' (HTTP response code was 400)

![4](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/38269740/66041f30-c859-4773-b86a-b2276d36e86d)

**Comment by twoyang0917** [comment]
+1

**Comment by Alien-smile** [comment]
同样报错
