### ISSUE TITLE
多文件上传速度缓慢，如何提升文件上传的速度

### ISSUE THREAD

**Issue by wgq910668** [chatchat-space/Langchain-Chatchat#883]
经过实际测试：上传5M的PDF文件，时间需要6分钟。
机器环境：
单机 V100 32G  10核 38G内存。普通stat磁盘
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/21257140/acef71f1-29a0-47d9-b8d1-45feee24245a)

**Comment by Vincent-ch99** [comment]
同问

**Comment by qinchaofeng** [comment]
pdf_loader.py里面有个 ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True)
使用gpu这个改成 True试一下

**Comment by thinkinds** [comment]
> pdf_loader.py里面有个 ocr = PaddleOCR(use_angle_cls=True, lang="ch", use_gpu=True) 使用gpu这个改成 True试一下

试过了，没有明显的提速。好像环境里面的paddle那一套都不是gpu的版本？

**Comment by wgq910668** [comment]
经过实际分析和测量。文件上传的瓶颈不在GPU跟内存。而是处理file文件为集合的时候耗费时间很长，而且是单线程处理。因此进行了多线程的并发处理文件。
采用的python 多进程分布式上传。速度提升了3倍。还有优化空间。可以参考看看
def execute_task(file):
    try:
        doc = load_file(file)
        logger.info(f"{file} 已成功加载")
        return doc
    except Exception as e:
        logger.error(e)
        logger.info(f"{file} 未能成功加载")
def multi_run(filepath):
    manager = multiprocessing.Manager()
    task_list = manager.list(filepath)  # 共享的任务列表
    # 创建进程池
    pool = multiprocessing.Pool(5)
    # 使用进程池中的进程来执行共享的任务列表，并获取返回值
    results = pool.map_async(execute_task, task_list)
    # 等待所有任务执行完成
    results.wait()
    # 获取每个任务的返回值
    output = results.get()
    # print(output)  # 打印输出结果
    # 关闭进程池
    pool.close()
    pool.join()
    return output

修改文件保存的地方。
    docss = multi_run(filepath)

**Comment by Vincent-ch99** [comment]
> 经过实际分析和测量。文件上传的瓶颈不在GPU跟内存。而是处理file文件为集合的时候耗费时间很长，而且是单线程处理。因此进行了多线程的并发处理文件。 采用的python 多进程分布式上传。速度提升了3倍。还有优化空间。可以参考看看 def execute_task(file): try: doc = load_file(file) logger.info(f"{file} 已成功加载") return doc except Exception as e: logger.error(e) logger.info(f"{file} 未能成功加载") def multi_run(filepath): manager = multiprocessing.Manager() task_list = manager.list(filepath) # 共享的任务列表 # 创建进程池 pool = multiprocessing.Pool(5) # 使用进程池中的进程来执行共享的任务列表，并获取返回值 results = pool.map_async(execute_task, task_list) # 等待所有任务执行完成 results.wait() # 获取每个任务的返回值 output = results.get() # print(output) # 打印输出结果 # 关闭进程池 pool.close() pool.join() return output
> 
> 修改文件保存的地方。 docss = multi_run(filepath)

建议用代码格式框起来哈，不然可读性不太好：
<img width="435" alt="image" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/34907633/f8b4f350-dee4-4797-a142-358994c0740f">
