### ISSUE TITLE
关于答案胡乱生成的问题

### ISSUE THREAD

**Issue by soultrans** [chatchat-space/Langchain-Chatchat#886]
**问题描述 / Problem Description**
我在进行添加一些知识库语料后，发现对于一些相近的知识或者表述，会存在编造甚至胡乱生成答案的情况。主要存在以下两种问题情况：
1.检索出来的答案来源，不一定都是相关的信息，但是生成的时候会把这些不相关的信息，融合加入到生成的答案结果中。
2.生成的答案中，会存在一些检索来源中都找不到的信息。

我在相关配置文件中，没有找到可以修改控制生成模型参数的配置，但在models文件夹中，找到了具体使用的生成模型代码，一些参数信息（比如：temperature、top_p、top_k）都是写好的固定数值，我想请教下：
1.这些控制模型生成信息的参数（temperature、top_p、top_k），是都已经验证好的最优数据吗？
2.一些控制生成参数信息有可调整的区间范围吗？比如：temperature区间为（0，1]这样
3.我想调整控制生成模型，使尽可能多的根据原文信息回答问题，减少自由发挥编造答案的情况，该如何修改呢？
目前我只尝试修改了chatglm_llm.py中的temperature参数值，但是验证不管是调高或者调低后，都会存在编造答案的情况，请问我还需要做哪些调整，期待大佬的指点，非常感谢！

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：v0.1.16
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B

**Comment by xiaolong888888** [comment]
我今天也是挺关注这个问题的, 我提供知识库后, 聊天模式下, 答案都是多个知识文档间拼凑出来的, 这样子的答案就不严谨了, 没法给人用

**Comment by moonfire95** [comment]
回答准确能下手的地方：1.数据质量：导入的文档已经是清洗过的，信息集中度高，就像FAQ。类似导入制度、手册这种，效果会差。2.文本切割：在load_file函数中，针对不同类型可指定不同分割器，这里可根据自己的文档去定制如何切割更符合实际场景。model_config中有SENTENCE_SIZE是指切割时单句的最大长度，太长或非常短的话向量化后匹配就不精准。还有前面所提的FAQ，可以用txt导入，按固定切割符切割。3.搜索匹配：在get_knowledge_based_answer函数中，chunk_conent控制是否上下文关联（context_expand），chunk_size控制上下文关联时关联的幅度有多大。如果是FAQ，只需context_expand_method向forward扩展一段文本。另外VECTOR_SEARCH_TOP_K控制取匹配的前几个文档，非常明确的话就配为1。VECTOR_SEARCH_SCORE_THRESHOLD是相关度过滤，比如设置300以下，那回答非常准确，不过这和问题的质量也有关系。4.大模型：prompt、temperature、top_p。prompt比较关键，毕竟一个听话的大模型，prompt里可以控制不乱说。可以在prompt模板里加上“不要在答案里添加已知信息不存在的内容”。但更多的是少说了，所以还会加上“请把答案的已有内容全部罗列出来”。temperature设置低点，top_p高点。  
等下找个已经上线的案例聊聊，看他们的效果如何。后面补充

**Comment by soultrans** [comment]
> 回答准确能下手的地方：1.数据质量：导入的文档已经是清洗过的，信息集中度高，就像FAQ。类似导入制度、手册这种，效果会差。2.文本切割：在load_file函数中，针对不同类型可指定不同分割器，这里可根据自己的文档去定制如何切割更符合实际场景。model_config中有SENTENCE_SIZE是指切割时单句的最大长度，太长或非常短的话向量化后匹配就不精准。还有前面所提的FAQ，可以用txt导入，按固定切割符切割。3.搜索匹配：在get_knowledge_based_answer函数中，chunk_conent控制是否上下文关联（context_expand），chunk_size控制上下文关联时关联的幅度有多大。如果是FAQ，只需context_expand_method向forward扩展一段文本。另外VECTOR_SEARCH_TOP_K控制取匹配的前几个文档，非常明确的话就配为1。VECTOR_SEARCH_SCORE_THRESHOLD是相关度过滤，比如设置300以下，那回答非常准确，不过这和问题的质量也有关系。4.大模型：prompt、temperature、top_p。prompt比较关键，毕竟一个听话的大模型，prompt里可以控制不乱说。可以在prompt模板里加上“不要在答案里添加已知信息不存在的内容”。但更多的是少说了，所以还会加上“请把答案的已有内容全部罗列出来”。temperature设置低点，top_p高点。 等下找个已经上线的案例聊聊，看他们的效果如何。后面补充

关于您说的几点我很赞同，目前我这边也做了同样的处理，数据层面进行不同的数据源清洗、不同的切分模式甚至限定固定的文本块、提示生成语的限定等。
我个人认为，究其本身生成模型的生成回答效果，很大程度取决与提示生成的文本信息来源，就是你要告诉模型更加精准或者包含更多相关来源信息，作为文档材料。
现在我这边遇到了这样的问题，随着知识语料库数据的增多、更多样性的数据或者就一个核心点更多角度的数据录入，给文本向量检索就带来了很大的干扰，具体举例比如：录入的主要都是体育新闻，体育新闻又分足球、网球、篮球等不同领域；关于某个体育人物的比赛、转会信息又有多家媒体报道。
我就此进行了以下尝试：1.对切分后的语料信息打标签；2.修改切分逻辑处理，融合标题信息到文本向量中；3.训练短文本对长文本的向量模型训练；

相关文本信息的检索，很大程度上影响到后续生成的答案。除了对模型本身的调参训练意外，检索逻辑的处理也是很重要的，这方面也应该是项目后续优化的重点。

**Comment by soultrans** [comment]
除了对生成模型调参以及现有项目的可配置参数外，有没有一个好的检索方案或者检索模型进行替换呢？

**Comment by moonfire95** [comment]
> 现在我这边遇到了这样的问题，随着知识语料库数据的增多、更多样性的数据或者就一个核心点更多角度的数据录入，给文本向量检索就带来了很大的干扰，具体举例比如：录入的主要都是体育新闻，体育新闻又分足球、网球、篮球等不同领域；关于某个体育人物的比赛、转会信息又有多家媒体报道。

市面上去做，就是知识库要细分，应用要垂直。根据实际场景来优化。例如我们在做客服场景：客服的话其实要求特定的问题回答要准确，而且问题是和公司业务强相关，非常的细分，那最好的就是FAQ库。核心点就是围绕持续沉淀FAQ来做的，大模型是在FAQ和转人工之间加了一层，不管是大模型提炼答案、用户反馈、人工维护都是让FAQ更丰富。

**Comment by moonfire95** [comment]
> 除了对生成模型调参以及现有项目的可配置参数外，有没有一个好的检索方案或者检索模型进行替换呢？

供参考 https://github.com/shibing624/text2vec

**Comment by soultrans** [comment]
> > 除了对生成模型调参以及现有项目的可配置参数外，有没有一个好的检索方案或者检索模型进行替换呢？
> 
> 供参考 https://github.com/shibing624/text2vec

感谢分享，我现在采用的就是类FAQ的形式，“相关核心描述+文本内容”。但是发现现在[text2vec](https://github.com/shibing624/text2vec)，在相同的问句情况下，对于比较贴合的长文本往往会处于相关度较低的短文本后，对比尝m3e也存在同样的问题

**Comment by moonfire95** [comment]
> +文本内容

https://github.com/imClumsyPanda/langchain-ChatGLM/issues/893#issuecomment-1643487476

**Comment by wufxgtihub123** [comment]
> > 除了对生成模型调参以及现有项目的可配置参数外，有没有一个好的检索方案或者检索模型进行替换呢？
> 
> 供参考 https://github.com/shibing624/text2vec

@moonfire95 你好，我想问一下，对于大文本我想提高embedding过程的速度，是不是可以更换词向量模型呀？换句话说，目前的text2vec好像是将文本转为1024维，那我是不是可以降低生成向量的维度，这样对内存的占用也小一些

**Comment by 631068264** [comment]
我目前的情况是文档多起来（20个）后，检索出来的答案来源，相关度分数低 ，但是内容不太相干的。。。

**Comment by tomFoxxxx** [comment]
> 

检索确实是重点，我们产品后期的叠化优化也主要是集中在检索任务。
btw，请教下你说的“训练短文本对长文本的向量匹配模型”，是不是指“问题——出处”这样pair-wise的语料

**Comment by tomFoxxxx** [comment]
> 但是发现现在[text2vec](https://github.com/shibing624/text2vec)，在相同的问句情况下，对于比较贴合的长文本往往会处于相关度较低的短文本后，对比尝m3e也存在同样的问题

这个很正常 长文本无关的东西也多 总体相似度就低了

**Comment by tomFoxxxx** [comment]
> 我目前的情况是文档多起来（20个）后，检索出来的答案来源，相关度分数低 ，但是内容不太相干的。。。

数据质量不好

**Comment by soultrans** [comment]
> > 
> 
> 检索确实是重点，我们产品后期的叠化优化也主要是集中在检索任务。 btw，请教下你说的“训练短文本对长文本的向量匹配模型”，是不是指“问题——出处”这样pair-wise的语料 @soultrans

是的，您说的对，我之前是尝试过这样的模型训练，基于sim-bert、text2vec都做过尝试；
我的实际应用场景大概分为两方面：
1、常规的文档问答，比如一段新闻，问里面具体的发生的时间
2、多个问题形式的问答，比如一篇科研文章中里面，既要问使用的具体方法，又要问采用的具体步骤

对于形式1，正常的来源匹配就能满足；对于形式2，具体步骤可能会被切分成多个，这样来源就变成多个了，考虑到切分过程中存在的信息丢失，有很大的概率向量模型是检索不到的
