### ISSUE TITLE
在加载本地embeddding模型时候报了如下错误

### ISSUE THREAD

**Issue by littlepppig** [chatchat-space/Langchain-Chatchat#891]
Loading /root/miniconda3/project/ChatGLM2-6B/chatglm2-6b...
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.40s/it]
Loaded the model in 13.81 seconds.
INFO  2023-07-20 10:59:03,497-1d: Load pretrained SentenceTransformer: /root/miniconda3/project/langchain-ChatGLM/text2vec-large-chinese
WARNING 2023-07-20 10:59:03,497-1d: No sentence-transformers model found with name /root/miniconda3/project/langchain-ChatGLM/text2vec-large-chinese. Creating a new one with MEAN pooling.
ERROR 2023-07-20 10:59:03,552-1d: Error while deserializing header: HeaderTooLarge
INFO  2023-07-20 10:59:03,552-1d: 模型未成功加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮
Running on local URL:  http://0.0.0.0:6006

**Comment by danny-zhu** [comment]
中文Embedding模型下载了吗？放到model_config指定的目录中
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/12292357/2a30a977-91d4-42a8-bc1a-d8c09962f097)

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/12292357/a9e8fb09-de09-40a4-bd2e-cecad94706c5)

**Comment by Cris-Young** [comment]
一样的问题，text2vec模型以及下载了，并且在配置文件中配置了对应的绝对路径，还是报这个错

**Comment by ilovesouthpark** [comment]
试试这样的格式呢？
    "text2vec": "G:\model\GanymedeNil_text2vec-large-chinese",
    "m3e-small": "moka-ai/m3e-small",
    "m3e-base": "G:\model\m3e-base",

**Comment by Cris-Young** [comment]
> 试试这样的格式呢？ "text2vec": "G:\model\GanymedeNil_text2vec-large-chinese", "m3e-small": "moka-ai/m3e-small", "m3e-base": "G:\model\m3e-base",

我使用的就是这种绝对路径，还是报这个错，我的代码是昨天直接clone的最新版本

**Comment by Cris-Young** [comment]
应该是我的电脑运行内存不够的原因，项目默认的Embedding模型最低显存要求是3G，由于我的LLM使用的不是本地的，所以我以为对笔记本性能要求不大，但现在看来不是这样。不知道如果Embedding用CPU跑的话，需要至少多少空闲的运行内存呢？显存是3G的话，运行内存应该至少剩余8G？

**Comment by danny-zhu** [comment]
看起来是显存不够，模型文件反序列化失败了，显存至少8G才够跑的。用cpu的话，我的配置比较差，16G内存，跑起来很慢，速度只有gpu的几十分之一。

**Comment by XXpE3** [comment]
好像是默认的那个 `text2vec` 的事，我下了好几遍都不行，其他有用到这个的项目也是说找不到模型，我换成 `text2vec-base-chinese-sentence` 就好了。

**Comment by Ikaros-521** [comment]
+1

**Comment by Modas-Li** [comment]
same issue: WARNING: No sentence-transformers model found with name /data/m3e-large. Creating a new one with MEAN pooling.

**Comment by conkeur** [comment]
try
`apt install libgl1-mesa-glx`
