### ISSUE TITLE
如何文本分割的时候，按照每行进行分割？因为我的本地TXT文件知识库是按照Q，A的形式组织的。也就是文本切片的时候按照每行进行切片。

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#893]
如何文本分割的时候，按照每行进行分割？因为我的本地TXT文件知识库是按照Q，A的形式组织的。文本切片的时候按照每行进行切片。

有大佬知道吗？
修改哪里的代码呢？
@imClumsyPanda

**Comment by ilovesouthpark** [comment]
用标点符号吧，行的结尾用一种特别的标点。然后修改chinese_text_splitter.py里面的内容，只留下这个特别的行尾标点。

**Comment by cristianohello** [comment]
@moonfire95 
牛！你的思路可以。请问有没有参考的代码实现

**Comment by moonfire95** [comment]
> 

你先把问题放到txt里导入试试，问下试试能否匹配到问题。
txt切割，可以试下CharacterTextSplitter(chunk_size=1, chunk_overlap=0, separator="\n") 看能否精确匹配到问题

**Comment by cristianohello** [comment]
@moonfire95 

每行是一个QA。
如：
2022年国际足联世界杯在哪举办？在卡塔尔举办。
2022年11月21日，该届世界杯开幕式暨揭幕战在哪举行？在海湾球场举行。
。。。。。。。等等

其实我想的是，如果问题和Q相似度在90%以上，返回QA作为大模型的prompt，让大模型问答Q的问题的答案，这样可以润色一下。

如果用户问题和Q相似度较低，直接走模型回答，不用构建prompt了。
这样可以较大环节幻觉。

**Comment by moonfire95** [comment]
> @moonfire95
> 
> 每行是一个QA。 如： 2022年国际足联世界杯在哪举办？在卡塔尔举办。 2022年11月21日，该届世界杯开幕式暨揭幕战在哪举行？在海湾球场举行。 。。。。。。。等等
> 
> 其实我想的是，如果问题和Q相似度在90%以上，返回QA作为大模型的prompt，让大模型问答Q的问题的答案，这样可以润色一下。
> 
> 如果用户问题和Q相似度较低，直接走模型回答，不用构建prompt了。 这样可以较大环节幻觉。

1.A是确定的，不需要润色；2.Q和A放在一起，会影响向量匹配结果。所以，Q和A分开比较好，把Q导入到向量库。只对Q进行向量匹配，根据相似度及TOP1过滤后，有结果则在关系数据库匹配A。没有结果的话，再把问题抛给大模型回答。

**Comment by cristianohello** [comment]
@moonfire95 
你好，你说的思路很对，问一下你的想法能和这个项目的代码结合起来吗？

**Comment by moonfire95** [comment]
> @moonfire95 你好，你说的思路很对，问一下你的想法能和这个项目的代码结合起来吗？

可以，在做。这种是根据各自业务场景定制，做产品就太合适。

**Comment by cristianohello** [comment]
@moonfire95 
大佬，我本地加载100多M的txt文件，faiss向量化的时候，出现kill错误？好像是内存不足导致的。这样有没有解决办法呢

**Comment by guyuexue** [comment]
> > @moonfire95
> > 每行是一个QA。 如： 2022年国际足联世界杯在哪举办？在卡塔尔举办。 2022年11月21日，该届世界杯开幕式暨揭幕战在哪举行？在海湾球场举行。 。。。。。。。等等
> > 其实我想的是，如果问题和Q相似度在90%以上，返回QA作为大模型的prompt，让大模型问答Q的问题的答案，这样可以润色一下。
> > 如果用户问题和Q相似度较低，直接走模型回答，不用构建prompt了。 这样可以较大环节幻觉。
> 
> 1.A是确定的，不需要润色；2.Q和A放在一起，会影响向量匹配结果。所以，Q和A分开比较好，把Q导入到向量库。只对Q进行向量匹配，根据相似度及TOP1过滤后，有结果则在关系数据库匹配A。没有结果的话，再把问题抛给大模型回答。

问题跟问题的搜索,最好还是取topN,再把这topN用对应的提示交给大模型进行总结回复,因为如果只根据向量相似度作为匹配的唯一标准会以来句向量模型top1准确性,而取topN,答案在这N里面的可能性大大增加,再通过大模型进行判断,最终正确率会大很多.

**Comment by moonfire95** [comment]
> @moonfire95 大佬，我本地加载100多M的txt文件，faiss向量化的时候，出现kill错误？好像是内存不足导致的。这样有没有解决办法呢

把txt文件先自己拆多份。单个文件过大，应该到不了向量化，在读取文件切割时估计就不行了。

**Comment by cristianohello** [comment]
@moonfire95 
就是说，我本地加载多个小的TXT文件吗？之前我是加载一个100M的文件，这次加载10个10M的文件可以吧

**Comment by tomFoxxxx** [comment]
> @moonfire95 就是说，我本地加载多个小的TXT文件吗？之前我是加载一个100M的文件，这次加载10个10M的文件可以吧

可以的，最终还是都在一个知识库里面的，不影响回答的准确率。

**Comment by zRzRzRzRzRzRzR** [comment]
现在已经可以按照自定义的方式进行拆分文件了，可以尝试用最新的代码自己写自定义分词器。由于该issue长期不活跃，开发组将其关闭，可以在最新代码上重新尝试。如果有需求可以重新提起

**Comment by zixiaotan21** [comment]
> > @moonfire95
> > 每行是一个QA。 如： 2022年国际足联世界杯在哪举办？在卡塔尔举办。 2022年11月21日，该届世界杯开幕式暨揭幕战在哪举行？在海湾球场举行。 。。。。。。。等等
> > 其实我想的是，如果问题和Q相似度在90%以上，返回QA作为大模型的prompt，让大模型问答Q的问题的答案，这样可以润色一下。
> > 如果用户问题和Q相似度较低，直接走模型回答，不用构建prompt了。 这样可以较大环节幻觉。
> 
> 1.A是确定的，不需要润色；2.Q和A放在一起，会影响向量匹配结果。所以，Q和A分开比较好，把Q导入到向量库。只对Q进行向量匹配，根据相似度及TOP1过滤后，有结果则在关系数据库匹配A。没有结果的话，再把问题抛给大模型回答。

大佬，我也是在做FAQ+LLM。想请教一下，为什么Q和A放在一起，会影响向量匹配结果呀？

我目前是把Q和A放在一起，如果Q和A分开放的话，后面如何在关系数据库匹配A呢？
