### ISSUE TITLE
[BUG] 关于阈值设定和向量召回逻辑模糊的问题：threshold,socre

### ISSUE THREAD

**Issue by Vincent-ch99** [chatchat-space/Langchain-Chatchat#896]
MyFAISS.py中的关于score筛选代码：
`if i == -1 or 0 < self.score_threshold < scores[0][j]:`

看起来似乎是相关度分数大于阈值则被丢掉？那么相关度分数的具体含义是？欧氏距离？不然如果相关度越高为什么会被丢弃

补充一下：
`scores, indices = self.index.search(vector, k)`
其中socres[0]是每个句子对应的相关度分数，indices[0]是根据socres分数排序的句子索引！
既然是从小到大排序，那么循环句子中：
```
for j, i in enumerate(indices[0]):
    if i == -1 or 0 < self.score_threshold < scores[0][j]:
            # This happens when not enough docs are returned.
            continue
```
如果分数最小的都大于阈值，那么应该是break，而不是continue, 不然代码循环没有意义！
按照这样的写法，代码应该是有逻辑上的问题

**Comment by Zhongyan0721** [comment]
同问

**Comment by cristianohello** [comment]
+1

**Comment by cristianohello** [comment]
# 知识检索内容相关度 Score, 数值范围约为0-1100，如果为0，则不生效，经测试设置为小于500时，匹配结果更精准
#VECTOR_SEARCH_SCORE_THRESHOLD = 10
VECTOR_SEARCH_SCORE_THRESHOLD = 1000

我现在的需要是：只有百分之99相似才召回。我设置了0和1000都不能满足需求。设置0和1000都把有一点相似的召回了，这是怎么回事？

**Comment by Vincent-ch99** [comment]
> MyFAISS.py中的关于score筛选代码： `if i == -1 or 0 < self.score_threshold < scores[0][j]:`
> 
> 看起来似乎是相关度分数大于阈值则被丢掉？那么相关度分数的具体含义是？欧氏距离？不然如果相关度越高为什么会被丢弃
> 
> 补充一下： `scores, indices = self.index.search(vector, k)` 其中socres[0]是每个句子对应的相关度分数，indices[0]是根据socres分数排序的句子索引！ 既然是从小到大排序，那么循环句子中：
> 
> ```
> for j, i in enumerate(indices[0]):
>     if i == -1 or 0 < self.score_threshold < scores[0][j]:
>             # This happens when not enough docs are returned.
>             continue
> ```
> 
> 如果分数最小的都大于阈值，那么应该是break，而不是continue, 不然代码循环没有意义！ 按照这样的写法，代码应该是有逻辑上的问题

经过测试，对top_k进行调整观察，会发现返回的是scores最小的top_k个，因此这里的相关度score更应该解释为distance，这样解释了为什么threshold设置的越低，匹配结果会更精准。设置0的时候，`if i == -1 or 0 < self.score_threshold < scores[0][j]:`肯定不满足，因此一定会把所有的top_k语句都扩充上下文，然后加入prompt。
个人理解！

**Comment by xiaolong888888** [comment]
那这个就不是BUG吧

**Comment by zixiaotan21** [comment]
想问一下，MyFAISS.py文件在哪个文件夹下呀，我使用langchain版本是0.2.10，似乎在vectorstores 下面找不到？
