### ISSUE TITLE
最新版本会输出无关信息，如何去掉？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#898]
我问你好，输出_call等无关信息，在哪去掉这些信息，我只需要：
问题是：你好
你好！有什么我可以帮助你的吗？

Input your question 请输入问题：你好
__call:已知信息：
意大利裁判达尼埃莱·奥萨托当选最佳裁判。 2022年卡塔尔世界杯决赛，于2022年12月18日在卢赛尔体育场举行，以决出2022年卡塔尔世界杯冠军归属，对阵双方为阿根廷与法国。 最终阿根廷队以7:5(点球大战4:2)击败卫冕冠军法国队，时隔36年再次捧起大力神杯。 你好。卡塔尔世界杯冠军是谁？ 阿根廷。 

根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。 问题是：你好
你好！有什么我可以帮助你的吗？

出处 [1] test100.txt：

意大利裁判达尼埃莱·奥萨托当选最佳裁判。 2022年卡塔尔世界杯决赛，于2022年12月18日在卢赛尔体育场举行，以决出2022年卡塔尔世界杯冠军归属，对阵双方为阿根廷与法国。 最终阿根廷队以7:5(点球大战4:2)击败卫冕冠军法国队，时隔36年再次捧起大力神杯。 你好。

**Comment by cristianohello** [comment]
@imClumsyPanda 
你好，这个怎么修改？低版本是没有问题的

**Comment by danny-zhu** [comment]
可以修改源码屏蔽这部分的输出，你用api模式还是webui模式？

**Comment by cristianohello** [comment]
@danny-zhu 
我用的cli_demo.py脚本。具体修改哪个代码呢？新版本会有，老版本没有。我现在正在找。


autodl-tmp/glm26b/langchain-ChatGLM-master/chains/local_doc_qa.py下的脚本。
下面是新版本的：
    def get_knowledge_based_answer(self, query, vs_path, chat_history=[], streaming: bool = STREAMING):
        vector_store = load_vector_store(vs_path, self.embeddings)
        vector_store.chunk_size = self.chunk_size
        vector_store.chunk_conent = self.chunk_conent
        vector_store.score_threshold = self.score_threshold
        related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
        torch_gc()
        '''
        if len(related_docs_with_score) > 0:
            prompt = generate_prompt(related_docs_with_score, query)
        else:
            prompt = query
        
        '''
        if len(related_docs_with_score) > 0:
            prompt = generate_prompt(related_docs_with_score, query)
        else:
            prompt = query

        answer_result_stream_result = self.llm_model_chain(
            {"prompt": prompt, "history": chat_history, "streaming": streaming})

        for answer_result in answer_result_stream_result['answer_result_stream']:
            resp = answer_result.llm_output["answer"]
            history = answer_result.history
            history[-1][0] = query
            response = {"query": query,
                        "result": resp,
                        "source_documents": related_docs_with_score}
            yield response, history


老版本如下：
    def get_knowledge_based_answer(self, query, vs_path, chat_history=[], streaming: bool = STREAMING):
        vector_store = load_vector_store(vs_path, self.embeddings)
        vector_store.chunk_size = self.chunk_size
        vector_store.chunk_conent = self.chunk_conent
        vector_store.score_threshold = self.score_threshold
        related_docs_with_score = vector_store.similarity_search_with_score(query, k=self.top_k)
        torch_gc()
        if len(related_docs_with_score) > 0:
            prompt = generate_prompt(related_docs_with_score, query)
        else:
            prompt = query

        for answer_result in self.llm.generatorAnswer(prompt=prompt, history=chat_history,
                                                      streaming=streaming):
            resp = answer_result.llm_output["answer"]
            history = answer_result.history
            history[-1][0] = query
            response = {"query": query,
                        "result": resp,
                        "source_documents": related_docs_with_score}
            yield response, history

**Comment by cristianohello** [comment]
@danny-zhu 
你好，大佬，我没找到修改的地方，他这个代码很杂

**Comment by cristianohello** [comment]
@danny-zhu 
你好，大佬，看到信息了吗，我还说没找到在哪修改
