### ISSUE TITLE
[BUG] 通过cli_demo.py输入文件夹名加载本地知识文件路径时，始终无法识别到文件名

### ISSUE THREAD

**Issue by we1k** [chatchat-space/Langchain-Chatchat#912]
通过cli_demo.py输入文件夹名加载本地知识文件路径时，始终无法识别到文件名

**复现问题的步骤 / Steps to Reproduce**

1. 执行 `python cli_demo.py`
2. 输入 `path/dir`
3. 问题出现
> load file failed, re-input your local knowledge file path 请重新输入本地知识文件路径
> 注意输入的路径是完整的文件路径，例如knowledge_base/`knowledge_base_id`/content/file.md，多个路径用英文逗号分割

**预期的结果 / Expected Result**
对单一文件夹路径进行初始化`init_knowledge_vector_store`

**实际结果 / Actual Result**
死循环

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：commit 3f76cb5f479566be8cf65e6f0469797e534978ce
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese 
- 操作系统及版本 / Operating system and version: Linux
- Python 版本 / Python version: 3.10

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/43416079/a3900cb4-5906-47db-8e61-fa51d9943aa5)
应该是因为
```python 
while not vs_path:
    filepath = input("Input your local knowledge file path 请输入本地知识文件路径：")

     # 判断 filepath 是否为空，如果为空的话，重新让用户输入,防止用户误触回车
    if not filepath:
        continue

    # 支持加载多个文件
    ##########
    filepath = filepath.split(",") # <- 输出一定是list格式，导致在init_knowledge_vector_store中无法识别dir
    ##########
    
    temp,loaded_files = local_doc_qa.init_knowledge_vector_store(filepath)


---------------------------------------
def init_knowledge_vector_store(self,
                                    filepath: str or List[str],
                                    vs_path: str or os.PathLike = None,
                                    sentence_size=SENTENCE_SIZE):
       
        if isinstance(filepath, str):
            if not os.path.exists(filepath):
                print("路径不存在")
                return None
            elif os.path.isfile(filepath):
               ...
            elif os.path.isdir(filepath):
                ...
        else:
```

**Comment by ScottXiao233** [comment]
借楼，遇到了下面的问题
Input your local knowledge file path 请输入本地知识文件路径：/home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples
加载文件: 0it [00:00, ?it/s]ERROR 2023-07-24 17:47:47,807-1d: Invalid file /home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples/vector_store/index.faiss. The FileType.UNK file type is not supported in partition.
加载文件: 1it [00:02,  2.23s/it]ERROR 2023-07-24 17:47:47,809-1d: Invalid file /home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples/vector_store/index.pkl. The FileType.UNK file type is not supported in partition.
加载文件: 6it [00:05,  1.06it/s]
Input your question 请输入问题：什么是Prompt工程？
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/incar/lx/source/langchain/langchain-ChatGLM/cli_demo.py:66 in <module>                     │
│                                                                                                  │
│   63 │   args = parser.parse_args()                                                              │
│   64 │   args_dict = vars(args)                                                                  │
│   65 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                   │
│ ❱ 66 │   main()                                                                                  │
│   67                                                                                             │
│                                                                                                  │
│ /home/incar/lx/source/langchain/langchain-ChatGLM/cli_demo.py:35 in main                         │
│                                                                                                  │
│   32 │   while True:                                                                             │
│   33 │   │   query = input("Input your question 请输入问题：")                                   │
│   34 │   │   last_print_len = 0                                                                  │
│ ❱ 35 │   │   for resp, history in local_doc_qa.get_knowledge_based_answer(query=query,           │
│   36 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    vs_path=vs_path,       │
│   37 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    chat_history=histor    │
│   38 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    streaming=STREAMING    │
│                                                                                                  │
│ /home/incar/lx/source/langchain/langchain-ChatGLM/chains/local_doc_qa.py:231 in                  │
│ get_knowledge_based_answer                                                                       │
│                                                                                                  │
│   228 │   │   vector_store.chunk_size = self.chunk_size                                          │
│   229 │   │   vector_store.chunk_conent = self.chunk_conent                                      │
│   230 │   │   vector_store.score_threshold = self.score_threshold                                │
│ ❱ 231 │   │   related_docs_with_score = vector_store.similarity_search_with_score(query, k=sel   │
│   232 │   │   torch_gc()                                                                         │
│   233 │   │   if len(related_docs_with_score) > 0:                                               │
│   234 │   │   │   prompt = generate_prompt(related_docs_with_score, query)                       │
│                                                                                                  │
│ /home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/langchain/vectorstores/faiss.py:259  │
│ in similarity_search_with_score                                                                  │
│                                                                                                  │
│   256 │   │   │   L2 distance in float. Lower score represents more similarity.                  │
│   257 │   │   """                                                                                │
│   258 │   │   embedding = self.embedding_function(query)                                         │
│ ❱ 259 │   │   docs = self.similarity_search_with_score_by_vector(                                │
│   260 │   │   │   embedding,                                                                     │
│   261 │   │   │   k,                                                                             │
│   262 │   │   │   filter=filter,                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'
```

**Comment by wmwinner** [comment]
> 借楼，遇到了下面的问题 Input your local knowledge file path 请输入本地知识文件路径：/home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples 加载文件: 0it [00:00, ?it/s]ERROR 2023-07-24 17:47:47,807-1d: Invalid file /home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples/vector_store/index.faiss. The FileType.UNK file type is not supported in partition. 加载文件: 1it [00:02, 2.23s/it]ERROR 2023-07-24 17:47:47,809-1d: Invalid file /home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples/vector_store/index.pkl. The FileType.UNK file type is not supported in partition. 加载文件: 6it [00:05, 1.06it/s] Input your question 请输入问题：什么是Prompt工程？借楼,遇到了下面的问题 Input your local knowledge file path 请输入本地知识文件路径:/home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples 加载文件: 0it [00:00, ? 2019 -07-24 17：47：47，807 -1d：无效文件/home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples/vector_store/index. faiss。分区中不支持FileType.UNK文件类型。 加载文件: 1it [00:02, 2.23s/it]ERROR 2023-07-24 17:47:47,809-1d:无效文件/home/incar/lx/source/langchain/langchain-ChatGLM/knowledge_base/samples/vector_store/index. pkl。分区中不支持FileType.UNK文件类型。 加载文件: 6it [00:05, 1.06it/s] Input your question 请输入问题:什么是Prompt工程?
> 
> ```
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /home/incar/lx/source/langchain/langchain-ChatGLM/cli_demo.py:66 in <module>                     │
> │                                                                                                  │
> │   63 │   args = parser.parse_args()                                                              │
> │   64 │   args_dict = vars(args)                                                                  │
> │   65 │   shared.loaderCheckPoint = LoaderCheckPoint(args_dict)                                   │
> │ ❱ 66 │   main()                                                                                  │
> │   67                                                                                             │
> │                                                                                                  │
> │ /home/incar/lx/source/langchain/langchain-ChatGLM/cli_demo.py:35 in main                         │
> │                                                                                                  │
> │   32 │   while True:                                                                             │
> │   33 │   │   query = input("Input your question 请输入问题：")                                   │
> │   34 │   │   last_print_len = 0                                                                  │
> │ ❱ 35 │   │   for resp, history in local_doc_qa.get_knowledge_based_answer(query=query,           │
> │   36 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    vs_path=vs_path,       │
> │   37 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    chat_history=histor    │
> │   38 │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │   │    streaming=STREAMING    │
> │                                                                                                  │
> │ /home/incar/lx/source/langchain/langchain-ChatGLM/chains/local_doc_qa.py:231 in                  │
> │ get_knowledge_based_answer                                                                       │
> │                                                                                                  │
> │   228 │   │   vector_store.chunk_size = self.chunk_size                                          │
> │   229 │   │   vector_store.chunk_conent = self.chunk_conent                                      │
> │   230 │   │   vector_store.score_threshold = self.score_threshold                                │
> │ ❱ 231 │   │   related_docs_with_score = vector_store.similarity_search_with_score(query, k=sel   │
> │   232 │   │   torch_gc()                                                                         │
> │   233 │   │   if len(related_docs_with_score) > 0:                                               │
> │   234 │   │   │   prompt = generate_prompt(related_docs_with_score, query)                       │
> │                                                                                                  │
> │ /home/incar/miniconda3/envs/llm/lib/python3.9/site-packages/langchain/vectorstores/faiss.py:259  │
> │ in similarity_search_with_score                                                                  │
> │                                                                                                  │
> │   256 │   │   │   L2 distance in float. Lower score represents more similarity.                  │
> │   257 │   │   """                                                                                │
> │   258 │   │   embedding = self.embedding_function(query)                                         │
> │ ❱ 259 │   │   docs = self.similarity_search_with_score_by_vector(                                │
> │   260 │   │   │   embedding,                                                                     │
> │   261 │   │   │   k,                                                                             │
> │   262 │   │   │   filter=filter,                                                                 │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> TypeError: similarity_search_with_score_by_vector() got an unexpected keyword argument 'filter'
> ```
我遇到同样的问题，修改一下版本问题解决了

![图片1](https://github.com/chatchat-space/langchain-ChatGLM/assets/38877864/ab1ac147-855e-43f2-af96-a46800192a4d)

**Comment by shnulailai** [comment]
如果想读取中文命名的文件名应该怎么修改代码呢

**Comment by wmwinner** [comment]
解决方案一：
如果要实现可以简单加载一个文件夹下面的所有文件的话，按照这张图片对cli_demo.py进行修改就可以运行





解决方案二：
这个bug真正出问题的点在load_doc_qa.py文件
要想彻底解决这个bug，那就按照如下情况对load_doc_qa.py进行修改
def init_knowledge_vector_store(self,
                                filepath: str or List[str],
                                vs_path: str or os.PathLike = None,
                                sentence_size=SENTENCE_SIZE):
    loaded_files = []
    failed_files = []
    filepaths = filepath
    docs = []
    for filepath in filepaths:
        if not os.path.exists(filepath):
            print("路径不存在")
            return None
        elif os.path.isfile(filepath):
            file = os.path.split(filepath)[-1]
            try:
                docs += load_file(filepath, sentence_size)
                logger.info(f"{file} 已成功加载")
                loaded_files.append(filepath)
            except Exception as e:
                logger.error(e)
                logger.info(f"{file} 未能成功加载")
                return None
        elif os.path.isdir(filepath):
            for fullfilepath, file in tqdm(zip(*tree(filepath, ignore_dir_names=['tmp_files'])), desc="加载文件"):
                try:
                    docs += load_file(fullfilepath, sentence_size)
                    loaded_files.append(fullfilepath)
                except Exception as e:
                    logger.error(e)
                    failed_files.append(file)

            if len(failed_files) &gt; 0:
                logger.info("以下文件未能成功加载：")
                for file in failed_files:
                    logger.info(f"{file}\n")
    if len(docs) &gt; 0:
        logger.info("文件加载完毕，正在生成向量库")
        if vs_path and os.path.isdir(vs_path) and "index.faiss" in os.listdir(vs_path):
            vector_store = load_vector_store(vs_path, self.embeddings)
            vector_store.add_documents(docs)
            torch_gc()
        else:
            if not vs_path:
                vs_path = os.path.join(KB_ROOT_PATH,
                                       f"""{"".join(lazy_pinyin(os.path.splitext(file)[0]))}_FAISS_{datetime.datetime.now().strftime("%Y%m%d_%H%M%S")}""",
                                       "vector_store")
            vector_store = MyFAISS.from_documents(docs, self.embeddings)  # docs 为Document列表
            torch_gc()

        vector_store.save_local(vs_path)
        return vs_path, loaded_files
    else:
        logger.info("文件均未成功加载，请检查依赖包或替换为其他文件再次上传。")

        return None, loaded_files




方案二是解决该bug的真正方案


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/langchain-ChatGLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月3日(星期四) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/langchain-ChatGLM] [BUG] 通过cli_demo.py输入文件夹名加载本地知识文件路径时，始终无法识别到文件名 (Issue #912)





 
如果想读取中文命名的文件名应该怎么修改代码呢

**Comment by shnulailai** [comment]
您的来信我已经收到了！
