### ISSUE TITLE
[BUG] 先使用text2vec加载本地文件,再使用m3e-base启动项目,页面无法添加新的知识库

### ISSUE THREAD

**Issue by Gierry** [chatchat-space/Langchain-Chatchat#913]
[BUG] 先使用text2vec加载本地文件,再使用m3e-base启动项目,页面无法添加新的知识库, 一直提示: 模型未完成加载，请先在加载模型后再导入文件

![1690117061174](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/59351111/2b33bfb6-0045-426c-8baf-984e8160774b)

**Comment by zRzRzRzRzRzRzR** [comment]
要用同一个embed模型
