### ISSUE TITLE
[BUG] text2vec与text2vec生成的知识库不可以混用,建议做类型隔离

### ISSUE THREAD

**Issue by Gierry** [chatchat-space/Langchain-Chatchat#914]
如下图, aaa时候text2vec新建的知识库,ppppp是m3e-base新建的知识库, 从aaa切换到pppp, 页面报错, 报错能理解, 类型不一致导致, 建议做类型隔离

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/59351111/a3a51bf3-9526-4868-ab1a-46e37d4a6578)

**Comment by zfanswer** [comment]
+1，我现在是在知识库名称上自己区分。。
