### ISSUE TITLE
知识库回答问题不全

### ISSUE THREAD

**Issue by darvsum** [chatchat-space/Langchain-Chatchat#916]
能正常上传docx文件，回答问题也能根据知识库回答，但是回答的问题全部都不完全，只是答案的一部分。如果让它继续时，它就基于前面的答案开始胡说八道了。
请问这是由于文本切分导致的吗？（感觉切分的时候文本信息有丢失） 应该如何处理？

**Comment by 306404391** [comment]
这个也算正常现象吧，很难全部很精准，可以试试整理下上传文件里的内容，改改上下文参数，topk这些，然后试试不同的问法，问题改一下有时候有效
