### ISSUE TITLE
[BUG] 启动webui错误，RuntimeError: CUDA Error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by 452236304** [chatchat-space/Langchain-Chatchat#919]
**问题描述 / Problem Description**
启动webui错误，RuntimeError: CUDA Error: no kernel image is available for execution on the device。能正常访问页面，但是提问也会报这个错误

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：拉取的master最新代码v0.1.16 
- 是否使用 Docker 部署（是/否）：否
- 使用的模型：本地ChatGLM2-6B-int4
- 使用的 Embedding 模型：本地text2vec-large-chinese
- 操作系统及版本 / Operating system and version: Alibaba Cloud Linux release 3/ Linux 5.10.134-14.al8.x86_64
- Python 版本 / Python version: 3.9.17
- 其他相关环境信息 / Other relevant environment information:  
- 显卡：P100
- 显卡驱动：NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0

**Comment by hel404** [comment]
应该是GPU版本问题，我的GTX Titan X也报错
(chatGLM) PS E:\AIs\LLMs\langchain-ChatGLM-0.1.16> python webui.py
INFO  2023-08-07 01:45:40,815-1d:
loading model config
llm device: cuda
embedding device: cuda
dir: E:\AIs\LLMs\langchain-ChatGLM-0.1.16
flagging username: <username>

Loading chatglm-6b-int4...
No compiled kernel found.
Compiling kernels : <path to kernel file>
Compiling gcc -O3 -fPIC -pthread -fopenmp -std=c99 <path to kernel file> -shared -o <path to output file>
Load parallel cpu kernel failed, using default cpu kernel code:
Traceback (most recent call last):
  File "<file path>", line 156, in __init__
    kernels = ctypes.cdll.LoadLibrary(kernel_file)
  File "<ctypes path>", line 452, in LoadLibrary
    return self._dlltype(name)
  File "<ctypes path>", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module '<path to kernel file>' (or one of its dependencies). Try using the full path with constructor syntax.

Compiling gcc -O3 -fPIC -std=c99 <path to kernel file> -shared -o <path to output file>
Load kernel : <path to kernel file>
Using quantization cache
Applying quantization to glm layers
Loaded the model in 12.93 seconds.
WARNING 2023-08-07 01:46:02,266-1d: No sentence-transformers model found with name <model path>. Creating a new one with MEAN pooling.
WARNING 2023-08-07 01:46:09,288-1d: The dtype of attention mask (torch.int64) is not bool
ERROR 2023-08-07 01:46:09,946-1d: CUDA Error: no kernel image is available for execution on the device
Running on local URL:  http://0.0.0.0:7860
