### ISSUE TITLE
创建完本地知识库后，貌似是一个删除本地库的按钮会变成undefined

### ISSUE THREAD

**Issue by bubblebyfly** [chatchat-space/Langchain-Chatchat#920]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/140377071/3b5fa087-8221-4f85-ab74-aed28c43a721)

**Comment by mbw97** [comment]
在webui.py文件中找到这一行file_status = f"已选择知识库{vs_id}，当前知识库中未上传文件，请先上传文件后，再开始提问"，然后将下面return的内容中最后一个value=[]删掉，这样应该可以解决问题哈。
