### ISSUE TITLE
点击 更新已有知识库选项 就报error

### ISSUE THREAD

**Issue by bubblebyfly** [chatchat-space/Langchain-Chatchat#921]
![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/140377071/28c0d4cd-8e09-463b-be4d-37adb2aaa274)
![45b300dc70716e8851bd10ecf67137c](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/140377071/244ce514-bc6b-488c-87fb-77fae4bf2df7)

**Comment by tschen666** [comment]
I met this issue，too

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码应该已经解决问题，请尝试更新到最新代码，如果还有问题，请重新提出issue
