### ISSUE TITLE
VECTOR_SEARCH_SCORE_THRESHOLD 参数设置的越低，检索文本相似度要求越高吗？

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#925]
这个参数我设置数值越低，检索相似度要求越高，为什么呢？

# 知识检索内容相关度 Score, 数值范围约为0-1100，如果为0，则不生效，经测试设置为小于500时，匹配结果更精准
VECTOR_SEARCH_SCORE_THRESHOLD = 800
VECTOR_SEARCH_SCORE_THRESHOLD = 10

**Comment by kendou** [comment]
是的， 文档说得很清楚。 而且在第二个Tab你可以测试不同的Threshold的效果。

**Comment by cristianohello** [comment]
@kendou 

你好，是不是这个VECTOR_SEARCH_SCORE_THRESHOLD 参数的值越小，代表两个文本的相似度约高？？？

**Comment by cristianohello** [comment]
@kendou 
你好，Tab指的是什么

**Comment by kendou** [comment]
> @kendou 你好，Tab指的是什么

你用WebUI模式的话， 在顶端选择“知识库测试Beta”那个页面， 可以测试不同的Threshold检索出来的内容是什么。

**Comment by cristianohello** [comment]
哦，明白了，我是直接命令行执行的，加载本地TXT文件。

**Comment by cristianohello** [comment]
@kendou 
再请教一下你一个关于faiss分片加载的问题，详细见这个issue：https://github.com/imClumsyPanda/langchain-ChatGLM/issues/884#issuecomment-1644946930

现在的问题是我不知道怎么修改local_doc_qa.py文件的init_knowledge_vector_store方法

**Comment by kendou** [comment]
> @kendou 再请教一下你一个关于faiss分片加载的问题，详细见这个issue：[#884 (comment)](https://github.com/imClumsyPanda/langchain-ChatGLM/issues/884#issuecomment-1644946930)
> 
> 现在的问题是我不知道怎么修改local_doc_qa.py文件的init_knowledge_vector_store方法

我加载大文件也会崩溃。 建议你用WebUI模式运行， 在界面上创建KnowledgeBase， 然后把大文件用脚本分割成小文件， 分批加载到创建好的KnowledgeBase中去。

**Comment by cristianohello** [comment]
@kendou 
明白，如果我现在想按照https://github.com/imClumsyPanda/langchain-ChatGLM/issues/925#issuecomment-1648900399这个方式修改local_doc_qa.py文件的init_knowledge_vector_store方法，那么该怎么修改呢？因为我是加载的本地一个TXT文件，本地是这样加载的filepath = "/root/autodl-tmp/glm26b/langchain-ChatGLM-master/datazys2/kataer.txt,/root/autodl-tmp/glm26b/langchain-ChatGLM-master/datazys2/pcauto100000.txt,/root/autodl-tmp/glm26b/langchain-ChatGLM-master/datazys2/zys.txt"

**Comment by danny-zhu** [comment]
> @kendou
> 
> 你好，是不是这个VECTOR_SEARCH_SCORE_THRESHOLD 参数的值越小，代表两个文本的相似度约高？？？

是的，默认使用欧几里得距离计算相似度，值越小表示距离越近，也就是越相似
