### ISSUE TITLE
[BUG]  中文提问 输出中英文混杂

### ISSUE THREAD

**Issue by hepengyue** [chatchat-space/Langchain-Chatchat#926]
**问题描述 / Problem Description**
用简洁明了的语言描述这个问题 / Describe the problem in a clear and concise manner.

![image](https://github.com/imClumsyPanda/langchain-ChatGLM/assets/128773187/5e6033d9-59b2-4c3d-9ac4-1c5983b6b5d5)

**Comment by zRzRzRzRzRzRzR** [comment]
模型的问题，需要设置好提示词和选择更好的模型
