### ISSUE TITLE
调用Embedding模型失败，报错显示找不到模型，

### ISSUE THREAD

**Issue by tschen666** [chatchat-space/Langchain-Chatchat#929]
当我使用text2vec-base作为Embedding时可以正常使用，但使用text2vec（即text2vec-large-chinese）模型失败，报错显示找不到模型。

1.我正确修改了config文件夹的路径参数
2.确认config中Embedding模型是选用的text2vec
3.运行webui.py后在前端也显示使用的为text2vec
4.但运行webui.py后在后端报错找不到模型
详情见图片

**预期的结果 / Expected Result**
描述应该出现的结果 ：应该能正常调用text2vec-large-chinese作为Embedding model才对啊？？

**实际结果 / Actual Result**
描述实际发生的结果 ：调用失败

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：(例如：v1.0.0 或 commit 123456) / langchain-ChatGLM version/commit number: (e.g., v1.0.0 or commit 123456)
- 是否使用 Docker 部署（是/否）：否 
- 使用的模型ChatGLM2-6B 
- 使用的 Embedding 模型text2vec-large-chinese
- 操作系统及版本： 阿里云 linux
- Python 版本 / Python version: Python 3.9.15
- 其他相关环境信息 / Other relevant environment information:

详情见图片
后端终端的报错（最后一行）：
<img width="1041" alt="屏幕截图 2023-07-25 115350" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/137777758/d9bce419-126f-4cc7-b7da-537411e52351">
webui显示的东西：
<img width="1149" alt="屏幕截图 2023-07-25 115425" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/137777758/de192dc8-8256-45af-9319-5d97f5ffef39">
webui前端报错：
<img width="1149" alt="屏幕截图 2023-07-25 115537" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/137777758/5be90d3b-aa41-4ede-a2ad-4948c4d48008">
config参数设置：
<img width="805" alt="屏幕截图 2023-07-25 115900" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/137777758/bc77e6dc-8c7a-46e5-aaa5-6abaeecc7da7">
Embedding路径下的文件
<img width="304" alt="屏幕截图 2023-07-25 120952" src="https://github.com/imClumsyPanda/langchain-ChatGLM/assets/137777758/cde882e0-5035-470f-9ba8-8d9fb345027c">

**Comment by tschen666** [comment]
其实不止有这个问题，还有很多有关于config文件下参数不管用的设置，比如无法正确调用我用p-tuning微调后的模型。比如在webui前端中设置的对话轮数形同虚设。

**Comment by cristianohello** [comment]
+1
他这个项目越来越乱了，不如之前的版本

**Comment by xinzhuang** [comment]
根据描述，”当我使用text2vec-base作为Embedding时可以正常使用，但使用text2vec（即text2vec-large-chinese）模型失败，报错显示找不到模型。“对于截图的理解有误，log中的是Warning不是error,正常加载text2vec-base也会出现这句提示，报错的地方应该是在其他位置，建议补充更多信息。

**Comment by xinzhuang** [comment]
@tschen666 ,两个embedding模型的维度不一样，text2vec是1024，text2vec-base是768，如果基于text2vec-base构建的知识库，切换到text2vec进行问答，会报错，因为维度不一致
