### ISSUE TITLE
以api的形式调用接口，但是接口没有返回

### ISSUE THREAD

**Issue by wangxu011** [chatchat-space/Langchain-Chatchat#934]
**问题描述 / Problem Description**
运行 api.py 文件，以api的形式调用接口，但是接口一直处于hang住的状态，没有返回，问一下是什么问题？

**复现问题的步骤 / Steps to Reproduce**
1. 运行 api.py 文件
2. 使用postman调用知识库对话的接口：http://127.0.0.1:6006/local_doc_qa/local_doc_chat
3. 问题出现：一直没有返回值

**Comment by liunux4odoo** [comment]
请贴上api访问代码，以及访问时的控制台输出。

**Comment by wangxu011** [comment]
你好，截图如下：图1为调用接口时控制台的输出，图2为通过postman调用本地知识库的api接口；

![1](https://github.com/chatchat-space/langchain-ChatGLM/assets/25812979/0d0c6359-6565-4688-8e0a-ff17429a6cd5)
图1
![2](https://github.com/chatchat-space/langchain-ChatGLM/assets/25812979/0bc2bd76-af4a-4e48-aa41-411b4738d247)
图2

**Comment by liunux4odoo** [comment]
我这边试了一下，正常返回：
```
r=requests.post('http://127.0.0.1:7861
/local_doc_qa/local_doc_chat',json={'knowledge_base_id':'kblog','question':'hello'})
r.text
'{"question":"hello","response":"根据已知信息，王治郅是中国篮球界进入NBA的第一人，于1993年入选中国青年男子篮球队，2001-05年效力于NBA独行侠、快船以及热火队，并退役。因此，无法回答用户的问题。","history":[[]],"source_documents":["出处 [1] 王治郅.txt：\\n\\n王治郅，1977年7月8日出生于北京，前中国篮球运动员，司职大前锋/中锋，现已退役。  [1] 1991年12月，王 1993年初入选中国少年特殊身材篮球队，并于同年入选中国青年男子篮球队，后加入八一男子篮球队。 2001-05年曾效力于NBA独行侠、快船以及热火队。  [1] 2015年9月15日新赛季CBA注册截止日，八一队的球员注册名单上并没有出现38岁老将王治郅的名字，王治郅退役已成事实 [2]  。 2016年7月5日，王治郅的退役仪式在北京奥体中心举行，在仪式上，王治郅正式宣布退役。  [3]  2018年7月，王治郅正式成为八一南昌队主教练。  [1]  [4] 王治郅是中国篮球界NBA的第一人，被评选为中国篮坛50大杰出人物和中国申办奥运特使。\\n\\n相关度：162\\n\\n"]}'
---

```
要不你更新一下代码，然后到/docs里面再测试一下？

**Comment by wangxu011** [comment]
你好，你这边是docs有什么新提交的东西吗？关于入参，我仔细对照过了，如截图，应该是没有问题的。
![3](https://github.com/chatchat-space/langchain-ChatGLM/assets/25812979/a0c561e7-cfb3-425f-8aaa-55af169a303e)
可不可以把您的 model_config.py 和 api.py 发给我，然后我对照一下，多谢

**Comment by liunux4odoo** [comment]
这2个参数确实没有问题。
我的代码跟项目是同步的，你可以拉最新的dev分支试一下。或者自己到local_doc_chat里打个断点调试一下。

**Comment by wangxu011** [comment]
你好，我是在云服务器上面运行的这个项目，所以不太好打断点。
我修改的 model_config.py 如图1，图2；
![4](https://github.com/chatchat-space/langchain-ChatGLM/assets/25812979/c1876281-2f65-43a7-baf7-5050c5f1f8a8)
![5](https://github.com/chatchat-space/langchain-ChatGLM/assets/25812979/37ce8a5f-e650-4057-b6f7-1628375af616)
终端执行 api.py 的 命令如图3；
![6](https://github.com/chatchat-space/langchain-ChatGLM/assets/25812979/988092f0-7847-4a78-a94e-966555249acb)
所以我想确认的是，我哪个地方的配置不对，或者还有遗漏的吗？多谢

**Comment by yuanluochenfeng** [comment]
这个问题有解决吗，我使用命令行也出现这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
更新最新代码后，问题还存在吗
