### ISSUE TITLE
[请教]使用gpt-3.5-turbo模型，启动webui.py进行多轮对话，浏览器对话框中只保留最后一轮记录

### ISSUE THREAD

**Issue by mbw97** [chatchat-space/Langchain-Chatchat#935]
**问题描述**
如题所述，使用gpt-3.5-turbo模型，启动webui.py进行多轮对话时，浏览器对话框中只保留（显示）最后一轮记录（一问一答）；然而使用下载到本地的ChatGLM-6B-int4模型时则没有出现这种情况，想请教下这个问题应如何解决？
“LLM对话”模式和“知识库问答”模式下均有上述情况发生。

**Comment by kimyle** [comment]
我也有这问题，另外补充一条，当关闭流式输出，就又可以显示完整的对话历史了。同时，我查看 api 通信日志，发现完整历史是正常发给 llm 的，只是在开启流式输出的情况下，webui 的界面上只显示最后一轮对话。

**Comment by mbw97** [comment]
> 我也有这问题，另外补充一条，当关闭流式输出，就又可以显示完整的对话历史了。同时，我查看 api 通信日志，发现完整历史是正常发给 llm 的，只是在开启流式输出的情况下，webui 的界面上只显示最后一轮对话。

感谢补充！我摸索后有了以下一点思路：因为是在用GPT模型时出现这个情况，所以我找到了models/fastchat_openai_llm.py文件，在241行的下一行增加了print(f"__history:{history}")，想查看一下history的情况，发现每次在浏览器中进行对话，输出的history都只有欢迎语和最后一轮问答，于是考虑是否是第221行history[-1] = [prompt, out_str]只替换了最后一轮对话历史，但并没有增加对话记录的数量。后来尝试在第207行后增加一行history = history + [["", ""]]，再次运行程序，发现对话记录正常。我对程序理解还不到位，不确定这样处理是否合适。

**Comment by kimyle** [comment]
有个想法还没来及试（api 到期了还没充上 😅），第 224 行 answer_result.llm_output = {"answer": out_str}，流式输出跟非流式输出，有个很大的不同就是，流式下 out_str 每次初始化为空，但是非流式下没有初始化这个操作。

**Comment by kimyle** [comment]
试了，可以。真是太棒了 👍🏻👍🏻
