### ISSUE TITLE
[BUG] 模型配置页面从 openai-chatgpt-3.5 切换回  chatglm2-6b ，无法正常切换

### ISSUE THREAD

**Issue by rayoa** [chatchat-space/Langchain-Chatchat#938]
默认启动模型  chatglm2-6b ，在模型配置页面切换至 openai-chatgpt-3.5 后，可正常使用。
但是**从 openai-chatgpt-3.5 切换回  chatglm2-6b ，无法正常切换。**（ chatglm2-6b 和 chatglm-6b之间来回切换无问题）

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码尝试
