### ISSUE TITLE
[BUG] 简洁阐述问题 / history[-1]报空指针错误

### ISSUE THREAD

**Issue by DZRS94** [chatchat-space/Langchain-Chatchat#939]
当用fastchat对接langchain-chatGLM时
访问/chat
{
  "question": "string",
  "history": []
}
history传空会报空指针问题，定位到估计是此处的错误
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/140569218/407d29b8-9463-4ceb-b952-95b5a2f617ce)

**Comment by daxian-lh** [comment]
我也遇到了，请问是怎么解决的嘛

**Comment by JosephLee03** [comment]
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/109290324/7f60251b-8b50-4931-b827-a76a3924168f)
你好，我用的openai接口，发生了index out of range的错误，同样定位到这里。通过图片中加入的一行代码解决了，希望对你有帮助！

**Comment by daxian-lh** [comment]
好的，非常感谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chatchat-space/langchain-ChatGLM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月30日(星期天) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chatchat-space/langchain-ChatGLM] [BUG] 简洁阐述问题 / history[-1]报空指针错误 (Issue #939)





 

 你好，我用的openai接口，发生了index out of range的错误，同样定位到这里。通过图片中加入的一行代码解决了，希望对你有帮助！
