### ISSUE TITLE
这个框架目前能支持最新的Llama-2模型吗？

### ISSUE THREAD

**Issue by baohongmin** [chatchat-space/Langchain-Chatchat#941]
**功能描述 / Feature Description**
能支持最新的Llama-2模型吗？

**解决的问题 / Problem Solved**
GPU和CPU的版本都能运行的Llama-2模型

**Comment by Wizhiai** [comment]
支持，换模型路径就行

**Comment by string-new** [comment]
> 支持，换模型路径就行

请问你是测试了吗，我这边换了模型确实可以启动，但是对话就会报错，应该是需要修改框架底层代码去支持，应该要在这里面封装一个支持的这个模型的类
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/28621576/c3f37edc-b244-4a8e-a0c6-da692b6d2bd2)

**Comment by kztao** [comment]
可以试一下用fastchat的调用方式
[用fastchat跑起llama2模型](https://github.com/chatchat-space/langchain-ChatGLM/blob/master/docs/fastchat.md)

**Comment by baohongmin** [comment]
> > 支持，换模型路径就行
> 
> 请问你是测试了吗，我这边换了模型确实可以启动，但是对话就会报错，应该是需要修改框架底层代码去支持，应该要在这里面封装一个支持的这个模型的类 ![image](https://user-images.githubusercontent.com/28621576/256714112-c3f37edc-b244-4a8e-a0c6-da692b6d2bd2.png)

**Comment by baohongmin** [comment]
> > 支持，换模型路径就行
> 
> 请问你是测试了吗，我这边换了模型确实可以启动，但是对话就会报错，应该是需要修改框架底层代码去支持，应该要在这里面封装一个支持的这个模型的类 ![image](https://user-images.githubusercontent.com/28621576/256714112-c3f37edc-b244-4a8e-a0c6-da692b6d2bd2.png)

我测试的llama2-chinese模型的中文理解能力好像还不如chatGLM，你们测试的llam2效果怎么样？

**Comment by AlterGu** [comment]
> Reference in new is

Hi~
我在model_config.py中添加了以下代码
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/39581263/619535ed-4dd8-461b-ab23-6694c97cc044)
同时激活了配置
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/39581263/5db3dc6f-3cf1-43dc-a0fc-55d99efbcd49)
在运行`python webui.py`后加载很慢，同时资源使用率很底(显卡几乎没有被使用到)
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/39581263/638b7dcd-f61b-4dfc-adf2-29a2a2cae61d)
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/39581263/395530bc-9019-44db-81ed-0556190aa16e)

**Comment by lucheng07082221** [comment]
@baohongmin 你好，请问你langchain-llama2的问题解决了吗？

**Comment by imClumsyPanda** [comment]
项目已更新至v0.2.x版本，默认使用fastchat进行本地模型加载，已支持llama2模型的接入，感谢反馈！
