### ISSUE TITLE
[BUG] 简洁阐述问题 / Concise description of the issue

### ISSUE THREAD

**Issue by zhuozj22** [chatchat-space/Langchain-Chatchat#946]
想问下有无大佬知道langchain chatglm 运行webui.py在网页上点击上传文件按钮后后端代码运行的起点在哪呀
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/126583941/bacb49b6-94ce-4b13-97a9-84b3e875c20e)
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/126583941/1d32522c-d9f7-4f72-a2b1-e1676129adb4)

**Comment by xinzhuang** [comment]
是的，点击按钮后执行的方法是`get_vector_store`,这里文件上传使用的组件是gradio提供的，`gr.File()`[组件](https://www.gradio.app/docs/file)完成了文件的实际上传执行，等点击按钮的时候，点击事件绑定的方法`get_vector_store`通过files参数获取上传的文件，进行后续处理。

代码可见 webui.py
```
with gr.Tab("上传文件"):
        files = gr.File(label="添加文件",
                        file_types=['.txt', '.md', '.docx', '.pdf', '.png', '.jpg', ".csv"],
                        file_count="multiple",
                        show_label=False)
        load_file_button = gr.Button("上传文件并加载知识库")
```
