### ISSUE TITLE
关于知识库对于大文件问答的处理

### ISSUE THREAD

**Issue by wuyabing** [chatchat-space/Langchain-Chatchat#947]
在使用知识库时候，上传了大约4个G的文档，在知识库问答时候回答特别慢，各位谁知道原因可能出在哪里吗？有比较好的建议吗？请各位大神指教 @foxmoon @halfss @imClumsyPanda @thaumstrial

**Comment by xinzhuang** [comment]
基于知识库的问答，分为几个步骤：
1.query embedding
2. 按照相似度查询知识库向量获取相关上下文
3. 组合上下文调用大模型回答
4. 输出结果到显示页面

可根据以上步骤进行排查
1. 可能是向量库太大，相似度查询慢；
2. 可能是相似查询到的上下文太多，提示词toekn多，模型预测慢；
3. 可能使用了13B等大模型，模型本身预测慢
4. 可能以上原因的组合。

可以查看chains\local_doc_qa.py 中 get_knowledge_based_answer，打印每一步骤代码的执行时间来排查。

**Comment by cristianohello** [comment]
@wuyabing 

你好，你上传4G的本地文档不会出现faiss向量加载的时候kill错误吗？我本地100M的TXT文件，加载faiss向量出现kill错误，应该是内存不足，我想问下，你的内存是多少呢？
