### ISSUE TITLE
在requirements.txt中的依赖之间存在模块冲突

### ISSUE THREAD

**Issue by unsatisfying** [chatchat-space/Langchain-Chatchat#952]
## 描述
在requirements.txt中有两个依赖`paddleocr`和`layoutparser`。而`paddleocr`又依赖于`opencv-contrib-python`, `layoutparser`依赖于`opencv-python`。这两个包存在模块冲突(实际上这两个包的区别在于，opencv-python只包含了主模块，而contri包含了所有模块，因此部分模块内容会存在细微的差别)。安装`opencv-python`时在site-packages文件夹中（安装第三方软件包的默认文件夹）会安装cv2模块。随后再安装`opencv-contrib-python`包时（同样存在cv2模块），会将`opencv-python`包的cv2模块覆盖。值得注意的是这两个包中的cv2文件夹内有些模块文件并不相同。

此外再`opencv-python`的[官方文档](https://pypi.org/project/opencv-python/)说，这两个包不能同时安装，必须只安装一个（原话：There are four different packages (see options 1, 2, 3 and 4 below) and you should SELECT ONLY ONE OF THEM. Do not install multiple different packages in the same environment. There is no plugin architecture: all the packages use the same namespace (cv2). If you installed multiple different packages in the same environment, uninstall them all with pip uninstall and reinstall only one package.）。

## 复现
pip install -r requirements.txt
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/19465692/9425a896-2ea9-423f-b9fa-ad52bf89a53f)

## 修改
我不确定这种覆盖问题会对本项目造成什么样的影响，因为它可能会隐藏在深层的调用链中，至少是想要call opencv_python的cv2模块时，实际它已经被覆盖了，于是调用的是opencv_contrib_python的cv2模块。所以覆盖行为肯定会发生。虽然本项目只能处理直接依赖，而间接依赖发生的模块冲突也确实没有什么好的解决办法。并且这样的冲突也可能没有确切的影响。因为不一定调用了cv2模块中相互覆盖的那部分。所以也请确认后麻烦给我回复一个确认该覆盖行为的commits。

**Comment by wuli66ly** [comment]
直接指定一个可以同时满足多个项目的版本号就行，但是如果有点项目不满足就得再单独配个环境

**Comment by unsatisfying** [comment]
> 直接指定一个可以同时满足多个项目的版本号就行，但是如果有点项目不满足就得再单独配个环境

事实上我对本项目并不熟悉，我正在研究模块冲突相关的问题。于是收集了stars数量较高的项目进行case study。但是对于这种同样是间接依赖中包含模块冲突包的情况，我也不确定会发生什么功能上的错误（需要对项目代码和架构很熟悉）。但是我肯定的是覆盖的情况肯定发生，并且别的项目中也有类似的情况并发生了错误。
