### ISSUE TITLE
[BUG] 读取PDF文件时出现libpng warning: iCCP: known incorrect sRGB profile

### ISSUE THREAD

**Issue by wuli66ly** [chatchat-space/Langchain-Chatchat#954]
**问题描述 / Problem Description**
读取PDF文件时候会出现libpng warning: iCCP: known incorrect sRGB profile，这个问题看起来不影响问答，想问下遇见这种怎么办？

个人理解这个问题应该是读取图片方式的原因，读pdf的逻辑是不是读取每个PDF的图片然后OCR识别文字然后当作doc这种类型存vector？

**复现问题的步骤 / Steps to Reproduce**
数据库中加载PDF文件

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/89437715/001ccfbb-df6d-44d3-998a-1ca1c017cafc)

**Comment by zRzRzRzRzRzRzR** [comment]
目前，图片读取功能还没支持，需要在之后的版本中添加支持
