### ISSUE TITLE
[BUG] chatglm2-6b 模型加载失败

### ISSUE THREAD

**Issue by jackluo2012** [chatchat-space/Langchain-Chatchat#955]
**问题描述 / Problem Description**
load_model_config D:\123pan\Downloads\THUDM\chatglm2-6b...
You are using a model of type chatglm to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Loading D:\123pan\Downloads\THUDM\chatglm2-6b...
Warning: self.llm_device is False.
This means that no use GPU  bring to be load CPU mode

You are using a model of type chatglm to instantiate a model of type . This is not supported for all configurations of models and can yield errors.   
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:10<00:00,  1.44s/it]
Loaded the model in 17.67 seconds.
INFO  2023-07-27 16:44:32,137-1d: Load pretrained SentenceTransformer: GanymedeNil/text2vec-large-chinese
ERROR 2023-07-27 16:44:34,465-1d: (ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)), '(Request ID: 274b99e3-c2ab-4c1b-8c16-77a8cda5c5cf)')
INFO  2023-07-27 16:44:34,466-1d: 模型未成功重新加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮
INFO  2023-07-27 16:44:34,469-1d: HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
INFO  2023-07-27 16:44:34,473-1d: HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
Keyboard interruption in main thread... closing server.

**复现问题的步骤 / Steps to Reproduce**
(lcenv) PS D:\works\python\ai\langchain-ChatGLM> python .\webui.py
INFO  2023-07-27 16:43:06,181-1d: 
loading model config
llm device: cpu
embedding device: cpu
dir: D:\works\python\ai\langchain-ChatGLM
flagging username: 0147f430444c450faa37db6512f5ce7d

load_model_config D:\123pan\Downloads\THUDM\chatglm2-6b...
You are using a model of type chatglm to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Loading D:\123pan\Downloads\THUDM\chatglm2-6b...
Warning: self.llm_device is False.
This means that no use GPU  bring to be load CPU mode

You are using a model of type chatglm to instantiate a model of type . This is not supported for all configurations of models and can yield errors.   
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:09<00:00,  1.29s/it]
Loaded the model in 16.63 seconds.
INFO  2023-07-27 16:43:25,296-1d: Load pretrained SentenceTransformer: GanymedeNil/text2vec-large-chinese
ERROR 2023-07-27 16:43:26,647-1d: (ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)), '(Request ID: 9de4d12f-9065-45f0-98a8-a809be8c6c3b)')
INFO  2023-07-27 16:43:26,649-1d: 模型未成功加载，请到页面左上角"模型配置"选项卡中重新选择后点击"加载模型"按钮
D:\works\python\ai\langchain-ChatGLM\webui.py:350: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  chatbot = gr.Chatbot([[None, init_message], [None, model_status.value]],
D:\works\python\ai\langchain-ChatGLM\webui.py:353: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  query = gr.Textbox(show_label=False,
D:\works\python\ai\langchain-ChatGLM\webui.py:432: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  chatbot = gr.Chatbot([[None, knowledge_base_test_mode_info]],
D:\works\python\ai\langchain-ChatGLM\webui.py:435: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  query = gr.Textbox(show_label=False,
Running on local URL:  http://localhost:7860

To create a public link, set `share=True` in `launch()`.
INFO  2023-07-27 16:43:59,027-1d: HTTP Request: POST http://localhost:7860/api/predict "HTTP/1.1 200 OK"
INFO  2023-07-27 16:43:59,030-1d: HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
load_model_config D:\123pan\Downloads\THUDM\chatglm2-6b...
You are using a model of type chatglm to instantiate a model of type . This is not supported for all configurations of models and can yield errors.
Loading D:\123pan\Downloads\THUDM\chatglm2-6b...
Warning: self.llm_device is False.
This means that no use GPU  bring to be load CPU mode

**预期的结果 / Expected Result**
描述应该出现的结果 / Describe the expected result.

**实际结果 / Actual Result**
描述实际发生的结果 / Describe the actual result.

**环境信息 / Environment Information**
- langchain-ChatGLM 版本/commit 号：最新版本
- 是否使用 Docker 部署（是/否）：否
- 使用的模型（ChatGLM-6B / ClueAI/ChatYuan-large-v2 等）：ChatGLM-6B / Model used (ChatGLM-6B / ClueAI/ChatYuan-large-v2, etc.): ChatGLM2-6B
- 使用的 Embedding 模型（GanymedeNil/text2vec-large-chinese 等）：GanymedeNil/text2vec-large-chinese / Embedding model used (GanymedeNil/text2vec-large-chinese, etc.): GanymedeNil/text2vec-large-chinese
- 操作系统及版本 / Operating system and version:windows11
- Python 版本 / Python version:3.10.
- 其他相关环境信息 / Other relevant environment information:

**附加信息 / Additional Information**
添加与问题相关的任何其他信息 / Add any other information related to the issue.

**Comment by xinzhuang** [comment]
- 原因分析：

根据报错内容“ERROR 2023-07-27 16:43:26,647-1d: (ProtocolError('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))“，可能是网络原因，确认下浏览器能否打开[https://huggingface.co/models](https://huggingface.co/models)，如果不能打开，那么应该是网络连接问题。

 - 解决方法：可以在能连接huggingface官网的机器上下载模型，使用离线加载的方式，修改model_config.py文件中模型的local_model_path参数即可。

**Comment by flowbywind** [comment]
我的是向量模型文件没改为本地路径，所以每次执行网络下载因为网络不好报错。需要修改model_config里向量那个文件embedding_model_dict里text2vec值到本地位置 "text2vec": "/opt/*****/text2vec-large-chinese", 同样LLM的文件也要改到本地路径
