### ISSUE TITLE
[BUG] api启动，和webui启动的情况下，直接对话模型，效果不一致

### ISSUE THREAD

**Issue by Solo8World** [chatchat-space/Langchain-Chatchat#956]
**问题描述 / Problem Description**
同样的prompt,在api启动，和webui启动的情况下，直接对话模型，效果不一致，**重复测试了好几次结果都是这样。**

**复现问题的步骤 / Steps to Reproduce**
prompt如下：

```
在2023年05月22日，店铺：必胜客。 销售额为6274.00元，销售笔数为65笔，进店人次为166人次，进店人数为139人，客单价为96.52元，提袋率为0.39，租金坪效为30.02元，与昨日销售额比较的异动量为-25705.00元，租赁面积为209.00平方米，所在楼层为L3。
\n在2023年05月24日，店铺：必胜客。 销售额为7984.00元，销售笔数为110笔，进店人次为261人次，进店人数为222人，客单价为72.58元，提袋率为0.42，租金坪效为38.20元，与昨日销售额比较的异动量为1681.00元，租赁面积为209.00平方米，所在楼层为L3。
\n\n根据上述已知信息，简洁和专业的来回答用户的问题。如果无法从中得到答案，请说 “根据已知信息无法回答该问题” 或 “没有提供足够的相关信息”，不允许在答案中添加编造成分，答案请使用中文。
问题是：2023年5月24日必胜客的销售是多少

```

1.api启动，接口请求模型，prompt如上，回复如下

```
  "response": "根据提供的信息，我们无法计算出2023年5月24日必胜客的销售。因为问题中只提供了2023年5月22日的数据，而且这两天的数据中包含了与问题不相关的信息，如提袋率和租金坪效。此外，我们无法从这两天的数据中计算出2023年5月24日的销售，因为这两天的数据中没有提供足够的相关信息。"
```

2. webui.py启动，默认对话轮数设置：3，直接对话llm，回复如下：

```
根据提供的信息，2023年5月24日必胜客的销售为7984.00元，销售笔数为110笔。
```

3.刷新页面（防止历史对话影响），webui对话轮数设置为1或0,重新加载模型，再次直接对话llm。回复如下：

```
根据提供的信息，我们无法计算出2023年5月24日必胜客的销售。因为问题中没有提供足够的相关信息来计算当天的销售。
```

**预期的结果**
都能很好的回答正确的结果。

**实际结果**
webui启动时，对话轮数的改变，影响了llm的回答。
api启动时，无法回答正确的结果。我重复测试了好几次结果都是这样，然而api启动时对话轮数设置的是10,所以百思不得其解到底什么原因导致的。

**环境信息**
- langchain-ChatGLM /commit 号：cd91290b 
- 是否使用 Docker 部署：否
- 使用的模型：ChatGLM2-6B 非量化部署
- 使用的 Embedding 模型：m3e-base (该问题不涉及向量模型)
- Python 版本 / Python version: 3.8

问题现象补充：刚刚又试了下api启动时，通过webSocket连接并对话llm,发现通过webSocket是能返回正确结果的。更加扑朔迷离了。。。。

**Comment by kg-nlp** [comment]
这个我在使用chatglm2-6b部署时也出现这种问题了,提了个issue,没人解答

**Comment by xuyaokun** [comment]
我现在也是这种情况，大佬解决了没有啊？
