### ISSUE TITLE
faiss向量消耗内存较多，希望支持更多的专业向量数据库。

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#959]
faiss向量加载大文件不合适，希望支持专业的向量数据库

**Comment by danny-zhu** [comment]
langchain已经支持milvs向量库，milvs支持水平扩展

**Comment by xhochipe** [comment]
> langchain已经支持milvs向量库，milvs支持水平扩展

我在代码里面没搜到milvs相关的操作，您在 是那个文件中看到的

**Comment by cristianohello** [comment]
@danny-zhu 
修改哪里代码才能使用milvs提到faiss向量呢？
