### ISSUE TITLE
本地加载 huggingface 上的模型报错

### ISSUE THREAD

**Issue by XIRALIP** [chatchat-space/Langchain-Chatchat#960]
**功能描述 / Feature Description**
本地加载https://huggingface.co/lucio/xls-r-uyghur-cv8 这个模型报错需要怎么解决，是不兼容这个模型么
**解决的问题 / Problem Solved**
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/7464669/21fb8530-5295-436f-b2be-0a75aeda517a)

**Comment by favouriter** [comment]
可能是模型未下载完整，可以删掉重下
https://github.com/favouriter/but4.git
这个项目里写了一个脚本fast_host.py，可以检测优质的IP地址
