### ISSUE TITLE
[BUG] 知识库上传同一个文档，doc格式会出现一个error  javaldx，是什么情况

### ISSUE THREAD

**Issue by wuli66ly** [chatchat-space/Langchain-Chatchat#963]
**问题描述 / Problem Description**
知识库上传同一个文档，doc格式会出现一个error  javaldx: Could not find a Java Runtime Environment!

**复现问题的步骤 / Steps to Reproduce**
上传同一个文档的pdf格式和doc格式

**预期的结果 / Expected Result**
同一个文档的话，pdf格式就没有这个问题

**实际结果 / Actual Result**
doc格式的话会出现这个问题
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/89437715/9c22e61e-1c59-4299-b70e-a4c464cbbf53)

**Comment by GPTlei** [comment]
好像只支持.DOCX？

**Comment by wuli66ly** [comment]
> 好像只支持.DOCX？

pdf是支持的
