### ISSUE TITLE
我在mac M2芯片上安装失败

### ISSUE THREAD

**Issue by ZYQIO** [chatchat-space/Langchain-Chatchat#970]
在mac上执行docker打包命令，
docker build -f Dockerfile-cuda -t chatglm-cuda:latest .

运行就会报错

报错信息：

ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/" did not complete successfully: exit code: 1

执行到这里就执行不下去了，RUN pip3 install -r requirements.txt -i https://pypi.mirrors.ustc.edu.cn/simple/ && rm -rf `pip3 cache dir`

请问这是我还缺少什么环境吗 ？

**Comment by zRzRzRzRzRzRzR** [comment]
在最新代码重新配置，应该可以适配M2
