### ISSUE TITLE
Could not install packages due to an OSError: HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: 

### ISSUE THREAD

**Issue by wsdo** [chatchat-space/Langchain-Chatchat#975]
<img width="1508" alt="CleanShot 2023-07-31 at 15 19 13@2x" src="https://github.com/chatchat-space/langchain-ChatGLM/assets/9738969/aca99c21-0010-4d73-838a-f55cee3af491">

无法继续了

**Comment by ToviHe** [comment]
这不是连接问题吗？
