### ISSUE TITLE
如何区分问题是根据知识库提问还是根据之前回答提问

### ISSUE THREAD

**Issue by coolboyqu** [chatchat-space/Langchain-Chatchat#978]
如图
![@YUJ~{9J(_D_SITTVYIZMED](https://github.com/chatchat-space/langchain-ChatGLM/assets/36916120/d598af79-8f80-458c-a824-e6a3fc94537d)
![T%R7{3%Z(Q5@}SNI _DB $J](https://github.com/chatchat-space/langchain-ChatGLM/assets/36916120/0523e7c5-3e19-4b06-8988-c6491c641123)
针对之前回答的提问与之前的回答没有关系，该怎么解决这个问题呢

**Comment by zRzRzRzRzRzRzR** [comment]
针对之前的的提问是历史记录的功能
针对知识库是嵌入的功能
这两个都会进行参考，但是这就取决于大模型自身的理解能力
如果理解能力强，那么相关回答更强，反之弱
