### ISSUE TITLE
[BUG] 是否属于同一文档的判断bug / seperate_list逻辑bug

### ISSUE THREAD

**Issue by huarong0906** [chatchat-space/Langchain-Chatchat#985]
**问题描述 / Problem Description**
对开启了上下文的开关的情况，现有逻辑对一个query相关的topk个文档段落来自连续的多个文档，则会把多个文档的段落统一归属给其中一个文档，导致来源文档和文档段落不匹配。
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/90168293/451f751a-161f-40a5-82b4-c2d2f45ba8ff)
    def seperate_list(self, ls: List[int]) -> List[List[int]]:
        # TODO: 增加是否属于同一文档的判断
        lists = []
        ls1 = [ls[0]]
        for i in range(1, len(ls)):
            if ls[i - 1] + 1 == ls[i]:
                ls1.append(ls[i])
            else:
                lists.append(ls1)
                ls1 = [ls[i]]
        lists.append(ls1)
        return lists

**Comment by zhipeng9802** [comment]
解决了吗？
