### ISSUE TITLE
文本切分优化思路！

### ISSUE THREAD

**Issue by cristianohello** [chatchat-space/Langchain-Chatchat#992]
我想要按照本地TXT文件的每行进行切分？该怎么修改d代码？

**Comment by danny-zhu** [comment]
中文分词模型本身就是按行进行切分的，切分文本的目的是什么？要解决什么问题？

**Comment by xxcoco763** [comment]
你把后面的那些按照标点符号切分的逻辑去掉就好，然后sentence_size调个特别大的，不要走下面超过sentence_size的逻辑。但是友情提示，本人实践过，按照整行切分后，由于句向量增长，相似度检索起来效果反而一般，切的短一些效果更好一些。

**Comment by zRzRzRzRzRzRzR** [comment]
最新代码已经可以自定义进行切分，可以在最新代码上进行尝试
