### ISSUE TITLE
[BUG] ChatGLM2里用 ptuning做了微调仿到langchain-ChatGLM里没有生效

### ISSUE THREAD

**Issue by MingjunHu** [chatchat-space/Langchain-Chatchat#993]
**问题描述 / Problem Description**
如题：
ChatGLM2里用 ptuning做了微调仿到langchain-ChatGLM里没有生效
怎么解决？

**Comment by zRzRzRzRzRzRzR** [comment]
更新到最新代码后尝试，如果还遇到问题，请重新提交issue并配上你的导入方式和配置
