### ISSUE TITLE
text_split 优化：

### ISSUE THREAD

**Issue by kbwzy** [chatchat-space/Langchain-Chatchat#996]
主要是以下 3 方面可以优化：
1. 优化 text_split 算法，使匹配出的结果作为上下文时能够提供更合理的推理/回答依据；
2. 优化 embedding 模型，提升语义向量化的效果，使得语义匹配过程中能够匹配出最满足要求的文本段落作为上下文；
3. 优化 LLM 模型，使得给定提问相同情况下，得到更理想的推理/回答结果。

_Originally posted by @imClumsyPanda in https://github.com/chatchat-space/langchain-ChatGLM/issues/14#issuecomment-1495338651_

**Comment by kbwzy** [comment]
text_split算法优化：
textsplitter/chinese_text_splitter.py 33行，text = re.sub(r'([;；.!?。！？\?])([^”’])', r"\1\n\2", text)  # 单字符断句符，
英文句号，会对小数点比如1.1吨，网址比如http://www.aaa.bbb.ccc，使用\n切割开来，严重影响文本切割效果。
以下是我的更改：

class ChineseTextSplitter(CharacterTextSplitter):
    def __init__(self, pdf: bool = False, sentence_size: int = SENTENCE_SIZE, **kwargs):
        super().__init__(**kwargs)
        self.pdf = pdf
        self.sentence_size = sentence_size

    def dot_char_split(self, text:str) -> str:
        # text = re.sub(r'([;；.!?。！？\?])([^”’])', r"\1\n\2", text)  # 单字符断句-符拆分为两步骤，解决英文数字小数点会被切分成两句bug。
        # 将句子中的.替换为.\n，但只有在.前后都不是数字，并且.不在URL中时才进行替换。
        url_placeholder = "THIS_IS_A_URL_PLACEHOLDER"
        decimal_placeholder = "THIS_IS_A_DECIMAL_PLACEHOLDER"

        # Step 1: Find all URLs and replace them with placeholder, store URLs in a list
        urls = re.findall(r'((https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|])', text)
        text = re.sub(r'((https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|])', url_placeholder, text)

        # Step 2: Replace decimal points with placeholder
        text = re.sub(r'(\d)\.(\d)', r'\1' + decimal_placeholder + r'\2', text)
        # print("text1:\n",text)
        # Step 3: Replace remaining '.' with '.\n'
        text = re.sub(r'[.]', r".\n", text)

        # Step 4: Replace URL placeholder back to original URLs
        # print("urls:",urls)
        for url in urls:
            text = text.replace(url_placeholder, url[0], 1)

        # Step 5: Replace decimal placeholder back to '.'
        text = text.replace(decimal_placeholder, ".")
        return text
    
    def split_text1(self, text: str) -> List[str]:
        if self.pdf:
            text = re.sub(r"\n{3,}", "\n", text)
            text = re.sub('\s', ' ', text)
            text = text.replace("\n\n", "")
        sent_sep_pattern = re.compile('([﹒﹔﹖﹗．。！？]["’”」』]{0,2}|(?=["‘“「『]{1,2}|$))')  # del ：；
        sent_list = []
        for ele in sent_sep_pattern.split(text):
            if sent_sep_pattern.match(ele) and sent_list:
                sent_list[-1] += ele
            elif ele:
                sent_list.append(ele)
        return sent_list

    def split_text(self, text: str) -> List[str]:   ##此处需要进一步优化逻辑
        if self.pdf:
            text = re.sub(r"\n{3,}", r"\n", text)
            text = re.sub('\s', " ", text)
            text = re.sub("\n\n", "", text)

        text = self.dot_char_split(text)
        text = re.sub(r'([;；!?。！？\?])([^”’])', r"\1\n\2", text)  # 其他单字符断句符

        text = re.sub(r'(\.{6})([^"’”」』])', r"\1\n\2", text)  # 英文省略号
        text = re.sub(r'(\…{2})([^"’”」』])', r"\1\n\2", text)  # 中文省略号
        text = re.sub(r'([;；!?。！？\?]["’”」』]{0,2})([^;；!?，。！？\?])', r'\1\n\2', text)

        # 如果双引号前有终止符，那么双引号才是句子的终点，把分句符\n放到双引号后，注意前面的几句都小心保留了双引号
        text = text.rstrip()  # 段尾如果有多余的\n就去掉它
        # 很多规则中会考虑分号;，但是这里我把它忽略不计，破折号、英文双引号等同样忽略，需要的再做些简单调整即可。
        ls = [i for i in text.split("\n") if i]
        for ele in ls:
            if len(ele) > self.sentence_size:
                ele1 = re.sub(r'([,，.]["’”」』]{0,2})([^,，.])', r'\1\n\2', ele)
                ele1_ls = ele1.split("\n")
                for ele_ele1 in ele1_ls:
                    if len(ele_ele1) > self.sentence_size:
                        ele_ele2 = re.sub(r'([\n]{1,}| {2,}["’”」』]{0,2})([^\s])', r'\1\n\2', ele_ele1)
                        ele2_ls = ele_ele2.split("\n")
                        for ele_ele2 in ele2_ls:
                            if len(ele_ele2) > self.sentence_size:
                                ele_ele3 = re.sub('( ["’”」』]{0,2})([^ ])', r'\1\n\2', ele_ele2)
                                ele2_id = ele2_ls.index(ele_ele2)
                                ele2_ls = ele2_ls[:ele2_id] + [i for i in ele_ele3.split("\n") if i] + ele2_ls[
                                                                                                       ele2_id + 1:]
                        ele_id = ele1_ls.index(ele_ele1)
                        ele1_ls = ele1_ls[:ele_id] + [i for i in ele2_ls if i] + ele1_ls[ele_id + 1:]

                id = ls.index(ele)
                ls = ls[:id] + [i for i in ele1_ls if i] + ls[id + 1:]
        return ls

**Comment by BGMpool2014** [comment]
算法优化后的情况效果还是有问题。
例如输入为：
"""
DarkComet （暗黑彗星）是由 Jean-Pierre Lesueur（称为 DarkCoderSc）开发的远程访问木马（称为 RAT），在 2012 年初开始扩散，它用于许多有针对性的攻击192.168.1.1，能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。别名有：Fynloski、Krademok、DarkKomet 等。
"""

结果为：
['DarkComet ',
 '（暗黑彗星）是由 ',
 'Jean-Pierre ',
 'Lesueur（称为 ',
 'DarkCoderSc）开发的远程访问木马（称为 ',
 'RAT），',
 '在 2012 年初开始扩散，',
 '它用于许多有针对性的攻击192.',
 '168.',
 '1.',
 '1，',
 '能够通过网络摄像头拍照，',
 '通过连接到 PC 的麦克风窃听对话，',
 '并获得对受感染机器的完全控制。',
 '该 RAT 还以其键盘记录和文件传输功能而闻名，',
 '因此，',
 '任何远程攻击者都可以将任何文件加载到受感染的机器上，',
 '甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。',
 '它会禁用任务管理器、注册表编辑器和文件夹选项，',
 '修改注册表项以禁用 Windows 防火墙设置，',
 '此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。',
 '别名有：Fynloski、Krademok、DarkKomet ',
 '等。']

不太好优化，建议还是做问答对吧(费时费api)。文献分段起来太不可控了。

**Comment by kbwzy** [comment]
先用阿里提供的分段模型语义切割，然后再稍微优化下英文符号的情况。
效果如下：
![image](https://github.com/chatchat-space/langchain-ChatGLM/assets/12123683/d113fbc4-824b-44aa-b3c3-9dd93c3d4596)

**Comment by kbwzy** [comment]
> 算法优化后的情况效果还是有问题。 例如输入为： """ DarkComet （暗黑彗星）是由 Jean-Pierre Lesueur（称为 DarkCoderSc）开发的远程访问木马（称为 RAT），在 2012 年初开始扩散，它用于许多有针对性的攻击192.168.1.1，能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。别名有：Fynloski、Krademok、DarkKomet 等。 """
> 
> 结果为： ['DarkComet ', '（暗黑彗星）是由 ', 'Jean-Pierre ', 'Lesueur（称为 ', 'DarkCoderSc）开发的远程访问木马（称为 ', 'RAT），', '在 2012 年初开始扩散，', '它用于许多有针对性的攻击192.', '168.', '1.', '1，', '能够通过网络摄像头拍照，', '通过连接到 PC 的麦克风窃听对话，', '并获得对受感染机器的完全控制。', '该 RAT 还以其键盘记录和文件传输功能而闻名，', '因此，', '任何远程攻击者都可以将任何文件加载到受感染的机器上，', '甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。', '它会禁用任务管理器、注册表编辑器和文件夹选项，', '修改注册表项以禁用 Windows 防火墙设置，', '此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。', '别名有：Fynloski、Krademok、DarkKomet ', '等。']
> 
> 不太好优化，建议还是做问答对吧(费时费api)。文献分段起来太不可控了。

先用阿里提供的分段模型语义切割，然后再稍微优化下英文句号的情况。
————————————————————————————————————————————————
能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。
        DarkComet （暗黑彗星）是由 Jean-Pierre Lesueur（称为 DarkCoderSc）开发的远程访问木马（称为 RAT），在 2012 年初开始扩散，它用于许多有针对性的攻击192.168.1. 109

1，能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。 47
该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。 102
它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。 79
别名有：Fynloski、Krademok、DarkKomet 等。 34

**Comment by Mingxiangyu** [comment]
> > 算法优化后的情况效果还是有问题。 例如输入为： """ DarkComet （暗黑彗星）是由 Jean-Pierre Lesueur（称为 DarkCoderSc）开发的远程访问木马（称为 RAT），在 2012 年初开始扩散，它用于许多有针对性的攻击192.168.1.1，能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。别名有：Fynloski、Krademok、DarkKomet 等。 """
> > 结果为： ['DarkComet ', '（暗黑彗星）是由 ', 'Jean-Pierre ', 'Lesueur（称为 ', 'DarkCoderSc）开发的远程访问木马（称为 ', 'RAT），', '在 2012 年初开始扩散，', '它用于许多有针对性的攻击192.', '168.', '1.', '1，', '能够通过网络摄像头拍照，', '通过连接到 PC 的麦克风窃听对话，', '并获得对受感染机器的完全控制。', '该 RAT 还以其键盘记录和文件传输功能而闻名，', '因此，', '任何远程攻击者都可以将任何文件加载到受感染的机器上，', '甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。', '它会禁用任务管理器、注册表编辑器和文件夹选项，', '修改注册表项以禁用 Windows 防火墙设置，', '此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。', '别名有：Fynloski、Krademok、DarkKomet ', '等。']
> > 不太好优化，建议还是做问答对吧(费时费api)。文献分段起来太不可控了。
> 
> 先用阿里提供的分段模型语义切割，然后再稍微优化下英文句号的情况。 ———————————————————————————————————————————————— 能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。 DarkComet （暗黑彗星）是由 Jean-Pierre Lesueur（称为 DarkCoderSc）开发的远程访问木马（称为 RAT），在 2012 年初开始扩散，它用于许多有针对性的攻击192.168.1. 109
> 
> 1，能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。 47 该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。 102 它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。 79 别名有：Fynloski、Krademok、DarkKomet 等。 34

强的嘞，k老师这个后续准备提pr吗？持续关注。目前也是遇见了文档上传到知识库中，然后提问的问题直接在文档中复制的，最后向量库也没有检索到内容

**Comment by kbwzy** [comment]
> 

你这个也要具体分析是文档切割？还是embedding语义匹配能力不行？还是question跟answer语义相关性不足？

**Comment by Mingxiangyu** [comment]
> > 
> 
> 你这个也要具体分析是文档切割？还是embedding语义匹配能力不行？还是question跟answer语义相关性不足？

应该是文档切割的问题，因为我提的问题直接从上传的文档中摘抄过来的，但是向量检索时候还是没有匹配到任何数据

**Comment by imClumsyPanda** [comment]
测试了一下 llama-index里的sentencesplitter，似乎效果还不错。
```
from llama_index.text_splitter import SentenceSplitter

text_splitter1 = SentenceSplitter(
  separator="[^。(.\b)]+[。(.\b)]{1,}",
  chunk_size=300,
  chunk_overlap=50,
  paragraph_separator="\n\n\n",
  secondary_chunking_regex="[^。，；(.\b)(,\b)(;\b)]+[。，；(.\b)(,\b)(;\b)]{1,}",
)

text_splitter1.split_text(doc)
```
得到的结果是
```
['DarkComet （暗黑彗星）是由 Jean-Pierre Lesueur（称为 DarkCoderSc）开发的远程访问木马（称为 RAT），在 2012 年初开始扩散，它用于许多有针对性的攻击192.168.1.1，能够通过网络摄像头拍照，通过连接到 PC 的麦克风窃听对话，并获得对受感染机器的完全控制。',
 '该 RAT 还以其键盘记录和文件传输功能而闻名，因此，任何远程攻击者都可以将任何文件加载到受感染的机器上，甚至窃取管理员权限、计算机/用户名、语言/国家、操作系统信息、使用的内存、网络摄像头信息、文档等。',
 '它会禁用任务管理器、注册表编辑器和文件夹选项，修改注册表项以禁用 Windows 防火墙设置，此操作允许此恶意进程执行而不会被 Windows 防火墙检测到。别名有：Fynloski、Krademok、DarkKomet 等。']
```

**Comment by zRzRzRzRzRzRzR** [comment]
新版本已经可以自定义分词器了，可以自行尝试，该issue关闭
